### PR TITLE
BUG: Fixed bug that Timedelta raises error when slicing from 0s (issue #10583)

### LINKED ISSUE #10583: TimedeltaIndex raises error when slicing from '0s'
```python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.normal(size=(10,4)))
df.index = pd.timedelta_range(start='0s', periods=10, freq='s')

print(df.loc['0s':,:])
```
raises a `ValueError: invalid resolution`, while `print(df.loc['5s':,:])` works.

Workaround : `print(df.loc[pd.Timedelta('0s'):,:])`
```
INSTALLED VERSIONS
------------------
commit: 6246cc1bb5149863de09b470530b69f7e22cad87
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-57-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8

pandas: 0.16.2-138-g6246cc1
nose: 1.3.1
Cython: 0.20.1post0
numpy: 1.8.2
scipy: 0.13.3
statsmodels: None
IPython: 1.2.1
sphinx: 1.2.2
patsy: None
dateutil: 2.4.1
pytz: 2013b
bottleneck: None
tables: 3.1.1
numexpr: 2.2.2
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: None
```

### PR DESCRIPTION
**Pull request by terrytangyuan**
closes #10583

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. pls add a whatsnew note. ping when green.

**Comment by terrytangyuan** [comment]
I just messed up my last push. It combined some of your previous commits...would this still be ok? I am not sure how to make it back...

**Comment by jreback** [comment]
see how to here: http://pandas.pydata.org/pandas-docs/stable/contributing.html

you need to rebase on master

**Comment by terrytangyuan** [comment]
I've created a new PR [here](https://github.com/pydata/pandas/pull/10960). Sorry for any inconvenience.

**Comment by TomAugspurger** [comment]
FYI you probably would have been able to recover with `git reflog`, which records all the states your branch has been in. You'd use that to find which hash to `git reset` back to.

**Comment by terrytangyuan** [comment]
Got it. Thanks!

**Pull request closed without merging**
