### PR TITLE
TST: Eliminating references to pandas.util.testing.choice

### LINKED ISSUE #12386: CLN: remove pandas.util.testing.choice
xref #12384 

so I think this was for numpy < 1.7 compat.

we should remove ``pandas.util.testing.choice``
https://github.com/pydata/pandas/blob/master/pandas/util/testing.py#L173

there might be some latent doc references

### PR DESCRIPTION
**Pull request by paul-reiners**
- [x] closes #12386
- [x] tests passed
- [x] passes `git diff upstream/master | flake8 --diff`

Want to remove pandas.util.testing.choice.  First eliminating all
references to it.  Doing this in more than one commit as there are a lot
of them.
#12386

### CODE REVIEW

**Comment by jreback** [comment]
gr8!

can you add a whatsnew (even though this is a testing function, technically was in 'public' space, you can put in bug fixes).
squash as well. ping when green.

**Comment by paul-reiners** [comment]
I'm having trouble squashing.  When I do the following:

`git rebase -i HEAD~5`

I see a bunch of other people's commits also, not just mine.  Perhaps this is because I didn't branch off my fork, but worked on it directly?

**Comment by TomAugspurger** [comment]
Yeah, it's typically best to work off feature branches.

What happens if you `git rebase -i upstream/master` and put all your commits at the end by moving those lines down, and the squash? Otherwise we can just make a new pull request from another branch (`git co -b remove-tm-choice`)

**Comment by paul-reiners** [comment]
I'll make a new pull request from another branch tomorrow evening (and close this one afterwards).  Thanks for the suggestion.

**Comment by paul-reiners** [comment]
Or I guess I'll close this one first to eliminate confusion.  Anyway, I'll work on it tomorrow night.

**Comment by jreback** [comment]
you don't need a new PR. just rebase and force push.

**Comment by jreback** [comment]
```
git checkout master
git pull
git checkout <thisbranch>
git pull --rebase master
```
fix anything, then force push (``-f``)

**Pull request closed without merging**
