### PR TITLE
Backport PR #47946: REGR: fix error caused by deprecation warning in pd.merge when joining two Series

### PR DESCRIPTION
**Pull request by phofl**
#47946

### CODE REVIEW

**Comment by phofl** [comment]
cc @simonjayhawkins Added the issue number

**Comment by simonjayhawkins** [comment]
> cc @simonjayhawkins Added the issue number

we need to do the issue number as a sperate PR against main (and either backport or sync directly with 1.4.x) so that the release notes history on the future stable docs are also correct

**Comment by phofl** [comment]
Yep, already prepared the pr

**Review by simonjayhawkins — APPROVED** [review]
Thanks @phofl merge on green(ish)

**Pull request merged**
