### PR TITLE
Add kwargs for kde in scatter_matrix

### PR DESCRIPTION
**Pull request by cottrell**
Minor change to allow customizing the kde through the pandas api.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Have you seen [seaborn](http://stanford.edu/~mwaskom/software/seaborn/tutorial/axis_grids.html#grid-tutorial)? It handles this type of plotting much better than pandas. Specifically, this plot is covered by [`pairgrid` / `pairplot`](http://stanford.edu/~mwaskom/software/seaborn/tutorial/axis_grids.html#plotting-pairwise-relationships-with-pairgrid-and-pairplot)

**Comment by cottrell** [comment]
@TomAugspurger good point. Yes, I use have used it but I often forget to use it.

**Comment by jreback** [comment]
@TomAugspurger status of this?

**Comment by jreback** [comment]
@TomAugspurger close?

**Pull request closed without merging**
