### PR TITLE
CI fix-ci-isocalendar

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Fix failing CI check

https://github.com/pandas-dev/pandas/runs/5874948094?check_suite_focus=true

probably caused by #46674

### CODE REVIEW

**Comment by jreback** [comment]
oh wow i guess that PR really did have an issue

merge when ready

**Comment by MarcoGorelli** [comment]
OK thanks, merging then as this at least fixes the `Code Checks / Docstring and typing validation` job

**Comment by tswast** [comment]
Thanks for the quick fix!

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
