### PR TITLE
BUG / CoW: also return new object in case of null slice for both rows and columsn (.(i)loc[:, :])

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Related to https://github.com/pandas-dev/pandas/pull/49450 (also ensuring we always return new objects from indexing operations, but for a different case). 

Currently, there is the specific corner case of `df.(i)loc[:, :]` that just returns `df` (this doesn't happen for `df.(i)loc[:]` or `df[:]`, where only a single dimension gets indexed)

Given the current inconsistency with `df.loc[:, :]` vs `df.loc[:]`, we could also consider changing this for 2.0 for the default behaviour as well, and not just for when CoW is enabled?

- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

xref https://github.com/pandas-dev/pandas/issues/48998

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
> Given the current inconsistency with df.loc[:, :] vs df.loc[:], we could also consider changing this for 2.0 for the default behaviour as well, and not just for when CoW is enabled?

Yeah it would be nice if there was a consistency in the returned object by whatever method if the entire object is sliced

**Comment by jorisvandenbossche** [comment]
So shall I change this for 2.0 also in the default mode? (so as small breaking change) @jbrockmendel thoughts?

**Comment by jbrockmendel** [comment]
> So shall I change this for 2.0 also in the default mode? (so as small breaking change)

I like this idea.

**Comment by jbrockmendel** [comment]
pandas/tests/indexing/test_loc.py::TestLocBaseIndependent::test_identity_slice_returns_new_object failing

**Comment by jorisvandenbossche** [comment]
Ah, that was the edit I made to the test when assuming this is only changed for CoW, now it is always a new object. Should be fixed now.

**Pull request merged**
