### PR TITLE
CLN: move coverage config to pyproject.toml

### PR DESCRIPTION
**Pull request by fangchenli**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
is all of setup.cfg eventually going to move to pyproject.toml?

**Comment by fangchenli** [comment]
> is all of setup.cfg eventually going to move to pyproject.toml?

Yes.

**Comment by MarcoGorelli** [comment]
> > is all of setup.cfg eventually going to move to pyproject.toml?
> 
> Yes.

flake8 might still be an exception for a while 😄

**Review by MarcoGorelli — APPROVED** [review]
thanks @fangchenli !

**Pull request merged**
