### PR TITLE
BUG: Have object dtype for empty Categorical.categories

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/17248

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. *might* be another issue out there about this.

**Comment by TomAugspurger** [comment]
There's one for `Series()` having float dtype: https://github.com/pandas-dev/pandas/issues/16737 (actually, that's about the index dtype).

Do we want to embrace empty = object dtype everywhere?

**Comment by jreback** [comment]
> Do we want to embrace empty = object dtype everywhere?

yes

**Comment by TomAugspurger** [comment]
FYI CircleCI has finished (https://circleci.com/gh/pandas-dev/pandas/3865?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), but the widget here on Github hasn't updated yet. I'll merge this later today.

Changing `pd.Series([])` will be a big enough change that I've split that into a separate issue: https://github.com/pandas-dev/pandas/issues/17261

**Comment by jreback** [comment]
hmm almost certain there already is an issue about Series.

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request merged**
