### PR TITLE
to_sql: Adding overwrite or ignore behavior for row conflicts

### PR DESCRIPTION
**Pull request by JustinGuese**
- [x] closes https://github.com/pandas-dev/pandas/issues/14553, continuation of https://github.com/pandas-dev/pandas/pull/46232 and https://github.com/pandas-dev/pandas/pull/29636
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).  
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

I do not know how to continue on the PR of LSturtew (https://github.com/pandas-dev/pandas/pull/46232), but I would like to continue on this feature, as only tests or docstrings are missing I guess...
Is there some way to credit LSturtew and cvonsteg for most of the work? It would be unfair if only I get credit for just fixing tests or docstrings

### CODE REVIEW

**Comment by JustinGuese** [comment]
so as I guessed I think the main reason is that `SqlAlchemy` has some problems with arm and mac chips (not available)... Any proposals on how to solve it? Can we make a simple exception, if the chipset is arm or mac, just throw a "Not Implemented" error? Probably not the best solution, right?

Alternatively, we could probably swap out SqlAlchemy with the native libraries (MySQL, Postgresql, ...), but that sounds horrible. What are your thoughts?

```
import sqlalchemy
E   ModuleNotFoundError: No module named 'sqlalchemy'
```

**Review by phofl — COMMENTED** [review]
In general, SQL related tests are skipped when Alchemy is not installed

Alchemy is available for arm and Mac

**Comment by pascaloberle** [comment]
Looking forward to seeing this feature in action! keep up pushing

**Comment by pythonlectures** [comment]
Hi @JustinGuese, any update on this? Thanks for your hard work

**Comment by JustinGuese** [comment]
yeah we need someone who's good with python tests. at least my last status was that it works, but the tests are failing. any volunteers?

**Comment by phofl** [comment]
You are calling functions with invalid keyword arguments. You can step through this locally.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
