### PR TITLE
DEPR: un-deprecate errors kwd reverts #44294

### PR DESCRIPTION
**Pull request by jbrockmendel**
reverts #44294

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@jreback undeprecation for 'where'

**Comment by jreback** [comment]
hmm the CI didn't run on this, can you rebase

**Comment by mroeschke** [comment]
FYI the CI won't run until https://github.com/pandas-dev/pandas/pull/45336 is in.

**Comment by jreback** [comment]
if you can rebase

**Comment by jbrockmendel** [comment]
> if you can rebase

Already up to date.

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
