### PR TITLE
DOC: Validate space before colon docstring parameters #23483

### LINKED ISSUE #23483: DOC: Validate space before colon in the parameters section of the docstrings
In the docstrings, parameters are documented like this:
```
Parameters
----------
name : str
    The name of the person.
```

It is common that the space before the colon is not present, and in that case `validate_docstrings.py` reports:
- `Parameter "name: str" has no type`

Which is confusing, and new contributors may have problems understanding what the problem is. We should validate this specific problem, and report an appropriate error message like `A space is required before the colon separating the parameter name and type`.

This needs to be tested (in `scripts/tests/test_validate_docstrings.py`).

### PR DESCRIPTION
**Pull request by dannyhyunkim**
- [X] closes #23483
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm

@WillAyd can you take a look and merge if you're happy?

**Comment by datapythonista** [comment]
@dannyhyunkim sorry this wasn't merged earlier. Can you please resolve the conflicts?

**Comment by dannyhyunkim** [comment]
@datapythonista I've had a go at resolving conflicts. Could you take a look? Also, how do I rerun the builds/tests?

**Comment by datapythonista** [comment]
@dannyhyunkim, sorry about that, but seems like the CI failed with errors unrelated to your PR. Do you mind merging master into it again, so we trigger a new CI build?

**Comment by dannyhyunkim** [comment]
@datapythonista, done!

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Sorry I missed this before. Great work @dannyhyunkim !

**Pull request merged**
