### PR TITLE
DOC: Added missing links to optional dependencies in getting_started/install.html

### LINKED ISSUE #60364: DOC: Add missing links to optional dependencies in getting_started/install.html
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/getting_started/install.html

### Documentation problem

On the “Installation” page, links are provided to the GitHub pages for the required dependencies and some of the optional dependencies, but the optional dependencies in the tables from “Visualization” onward do not link to the GitHub pages of the projects. Links are provided to the optional HTML-related dependencies are present, but not in the dependency table.

### Suggested fix for documentation

Add links to the library names which link to their respective repositories to make the page more consistent.

### PR DESCRIPTION
**Pull request by Uvi-12**
Closes #60364

### CODE REVIEW

**Comment by Uvi-12** [comment]
pre-commit.ci autofix

**Comment by Uvi-12** [comment]
@rhshadrach I need help with this- the PR is having an issue with ci/circleci: test-linux arm, despite everything is alright. And please check the added link, if it's alright I will proceed on adding the other missing links.
Screenshot 2024-11-29 at 11 16 16 AM

**Comment by rhshadrach** [comment]
> the PR is having an issue with ci/circleci: test-linux arm

You can ignore this build.

**Comment by Uvi-12** [comment]
@rhshadrach It seems it passes the rest of the tests, can you please merge the PR so that the fixed matplotlib link goes live and I will fix the rest of the links.

**Comment by Uvi-12** [comment]
@rhshadrach All the links for the optional dependencies have been added. If everything looks good, please proceed with merging the PR to make the links go live. Let me know if there’s anything else that needs to be addressed.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Uvi-12

**Pull request merged**
