### PR TITLE
Fix num_days in PandasAutoDateLocator

### PR DESCRIPTION
**Pull request by wiktortomczak**
Prior to this commit, one year is worth 12 days, not 12 * 31 days.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Could you add a release note to `whatsnew/v0.19.2.txt`? Tests will be hard I think, but looking at the diff, your logic looks correct.

**Comment by jreback** [comment]
is there an open issue for this?

**Comment by jreback** [comment]
can you add a whatsnew note (0.20.0) and is there a test / example that shows the current behavior (is incorrect)?

**Comment by jreback** [comment]
can you rebase

**Comment by jreback** [comment]
@jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
See discussion in https://github.com/pandas-dev/pandas/issues/15753. Merging this as it was obviously a typo in the code, but one that will not affect any behaviour.

**Pull request merged**
