### PR TITLE
ENH: Allow to skip series type check in assert_frame_equal (#48287)

### LINKED ISSUE #48287: ENH: Allow to skip series type check in assert_frame_equal
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

When using derived Series type in dataframes, it is useful to be able to skip series type check in assert_frame_equal.

```python
import pandas as pd

class Series(pd.Series):
    @property
    def _constructor( self ):
        return Series

    @property
    def _constructor_expanddim( self ):
        return DataFrame

class DataFrame(pd.DataFrame):
    @property
    def _constructor_sliced( self ):
        return Series

s1 = pd.Series( [0] )
s2 = Series( s1 )

pd.testing.assert_series_equal(s1, s2, check_series_type=False)

df1 = s1.to_frame()
df2 = s2.to_frame()

pd.testing.assert_frame_equal(df1, df2, check_frame_type=False)
```

In the code above, the first assert passes, but the second fails with the following message:

```text
DataFrame.iloc[:, 0] (column name="0") classes are different
[left]:  Series
[right]: Series
```

There is currently no easy way to make such dataframes compare equal in testing.

### Feature Description

I suggest the following enhancements:

1. Add a new parameter, `check_series_type` to `assert_frame_equal()` that will pass through to `assert_series_equal()`.
1. Set  the new `check_series_type` to `False` when `check_frame_type` is set to `False`.
1. When type mismatch is detected but type names are the same, include fully qualified names in the assert message. 

### Alternative Solutions

Implement enhancements 1 and 3 without 2.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by abalkin**
Add an option check_series_type that is passed to assert_series_equal
in compare by columns.

- [x] closes #48287
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Please always add tests. In general, it is better to wait for consensus on enhancement requests

**Comment by abalkin** [comment]
> Please always add tests. In general, it is better to wait for consensus on enhancement requests

Thank you for your feedback, @phofl.  I submitted a draft PR to show that the enhancement that I proposed is very easy to implement.  I was planning to add tests, but will need guidance from more experienced contributors to find a place to put the tests.  I was not able to find exiting tests for the `assert_frame_equal()` function.

With respect to reaching the consensus, I am new to the pandas contributors community and will appreciate your advice on the appropriate forum to bring my proposal to.

**Comment by phofl** [comment]
Opening an issue is the correct approach (as you already did). Discussion should happen there.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. Additionally new features usually need buy-in from the core team in the discussion of the issue before moving forward. Closing until there has been sufficient discussion, but can reopen later.

**Pull request closed without merging**
