### PR TITLE
DOC: update `style.ipynb` user guide for recent enhancements

### PR DESCRIPTION
**Pull request by attack68**
I added small changes to the Styler User Guide to exemplify the new builtin highlighting functions.

Also removed some of the longer detail which has been moved to individual documentation pages (for example for `background_gradient`)

### CODE REVIEW

**Comment by dayvheed** [comment]
Hi @attack68. I wish to get started in contributing to open source. Is there any way I can contribute to this issue, please? I see it needs a documentation enhancement but I am not quite sure well. I can always help in writing for a start

**Comment by attack68** [comment]
> Hi @attack68. I wish to get started in contributing to open source. Is there any way I can contribute to this issue, please? I see it needs a documentation enhancement but I am not quite sure well. I can always help in writing for a start

@dayvheed this is not an issue. It is a pull request where I have already made the necessary changes. If you would like to contribute to pandas I would suggest the place to start is reading the documentation on contributing and then tackling real issues (not pull requests) that have the "good first issue" label.

**Comment by dayvheed** [comment]
Thank you@attack68. It was the label that got me confused.

**Comment by jreback** [comment]
sure ping on gree

**Comment by attack68** [comment]
@jreback pinging on green

**Comment by jreback** [comment]
thanks @attack68

**Pull request merged**
