### PR TITLE
CI: unpin IPython

### LINKED ISSUE #30537: Unpin ipython 7.10.1 once ipython 7.11.1 released
xref https://github.com/cython/cython/pull/3291#issuecomment-569403562

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/30537

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

**Comment by WillAyd** [comment]
Does it matter this version was released two days ago? I guess IPython is technically a dev dependency so maybe not, but I would think its common enough outside of just pandas development that requiring such a new release could cause inconsistencies with other packages a user may have

**Comment by TomAugspurger** [comment]
This is only for the doc build / dev environment. We haven't changed the requirement for users.

**Comment by jreback** [comment]
thanks @TomAugspurger 

the less we pin in ci the better generally

**Pull request merged**
