### PR TITLE
Support structural subtyping with ExtensionArray

### LINKED ISSUE #57633: ENH: Make ExtensionArray a Protocol
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

The current pandas ExtensionArray is a standard Python class, and throughout our code base we do things like `isinstance(obj, ExtensionArray)` to determine at runtime if an object is an instance of the ExtensionArray.

While this works for classes implemented purely in Python that may inherit from a Python class, it does not work with extension classes that are implemented in either Cython, pybind11, nanobind, etc... See https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#subclassing for documentation of this limitation in Cython

As such, unless you implement your extension purely in Python it will not work correctly as an ExtensionArray

### Feature Description

PEP 544 describes the [runtime_checkable](https://peps.python.org/pep-0544/#runtime-checkable-decorator-and-narrowing-types-by-isinstance) decorator that in theory can solve this issue without any major changes to our code base (ignoring any performance implications for now)

### Alternative Solutions

Not sure there are any - I am not entirely sure but am fairly certain that extension types in Python may not inherit from Python types

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by WillAyd**
- [X] closes #57633 

This is a very naive implementation. Ideally we would move a lot of the extraneous functions / attributes out of the core `ExtensionArray` class and into a better home

### CODE REVIEW

**Comment by jbrockmendel** [comment]
> move a lot of the extraneous functions / attributes out of the core ExtensionArray class and into a better home

Can you expand on this?  Early on when implementing EAs there was an idea that it could be implemented in terms of a small number of primitives (so the EA namespace could stay small) but that idea didn't pan out.

**Comment by WillAyd** [comment]
Yea I am referring to anything that is a method on the ExtensionArray but that is not documented as part of the interface. `_values_for_json`, `_get_repr_footer`, etc... work when you use nominal typing for for structural typing you'd have to re-implement those (see the test case)

**Comment by jbrockmendel** [comment]
So is the suggestion to move those things out of the EA namespace or just to document them as required?

This Protocol approach seems to make it difficult to implement default-but-overridable implementations for things.

**Comment by WillAyd** [comment]
Yea not sure yet how to best move things. Maybe that would require something like `ExtensionArrayDefaultOpsMixin`?

**Comment by jbrockmendel** [comment]
> Yea not sure yet how to best move things. Maybe that would require something like ExtensionArrayDefaultOpsMixin?

This seems like a lot of effort to reinvent the idea of a subclass.  Is there any evidence that this is a pain point for 3rd parties?

**Comment by WillAyd** [comment]
I am not aware of an existing library asking for this. It would be a new feature for a library that in the future may want to implement a class in an extension without having to interact heavily with the Python runtime

**Comment by WillAyd** [comment]
Closing for now - may revisit later

**Pull request closed without merging**
