### PR TITLE
PERF: sort_values speedup for multiple columns with random numeric values

### PR DESCRIPTION
**Pull request by mficek**
Continue work on #17141.
Speedup achieved for sorting by multiple columns: lexsort over multiple columns
replaced with mergesort of columns in reverse order than specified in "by"
argument of DataFrame.sort_values().
Issues:
- only works for numerical data
- only random enough data achieve sorting speedup (no factorization)
- ASV of one-column sort is worse, why?

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by mficek** [comment]
I'm running tests and found out, that many of them fail simply because expected method for multi column sort is not a mergesort (stable) which I use. Hm... Should I start fixing tests? Doesn't sound right to me, but the approach I use is imho correct.

**Comment by jreback** [comment]
> I'm running tests and found out, that many of them fail simply because expected method for multi column sort is not a mergesort (stable) which I use. Hm... Should I start fixing tests? Doesn't sound right to me, but the approach I use is imho correct.

can you show what you mean here?

prob would just change the default (this is inherited from ndarray which defaults to quicksort :<)

**Comment by desasaliho** [comment]
Hello..i have a problem in my Facebook when I login it say your account has been disabled 
By an administrator I want to know why I am Disabled please and when I can login back I 
Hope that you can help me and it thank you for
Any answer you will give it to me bye

**Comment by jreback** [comment]
can you rebase and fixup

**Comment by mficek** [comment]
Hi Jeff, I'm sorry, but I can not find enough time and motivation to finish this issue. It seems more complex than expected with improvements being too much dependent of the nature of the data.

**Pull request closed without merging**
