### PR TITLE
PKG/DEP: Make importable without pytest

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/16065

Edit: removed the top-level imports of pytest in pandas.util.testing

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Actually, thinking more about this I probably prefer removing the line from panads.__init__ and have people import it separately

```
import pandas.testing as tm
```

**Comment by chris-b1** [comment]
Since `pytest` isn't actually needed for the api functions (`assert_frame_equal`, etc), maybe those could be defined in `pandas.testing`, then imported back into `pandas.util.testing`?

**Comment by chris-b1** [comment]
Looking at [testing.py](https://github.com/pandas-dev/pandas/blob/2f9c854c30385c29a905c0a9bf0b5009e99347e0/pandas/util/testing.py) again - almost every use `pytest` already has function level imports, so may be best to bite the bullet and do it for the few remaining cases?

**Comment by TomAugspurger** [comment]
> so may be best to bite the bullet and do it for the few remaining cases?

OK, let me give this a shot.

**Comment by TomAugspurger** [comment]
Ok, not too bad at all. Hopefully this passes.

And here it is working without pytest, which is nice

```python
In [1]: import pandas as pd

In [2]: pd.testing.assert_series_equal(pd.Series([1]), pd.Series([2]))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-46d7e85da706> in <module>()
----> 1 pd.testing.assert_series_equal(pd.Series([1]), pd.Series([2]))

/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas/pandas/util/testing.py in assert_series_equal(left, right, check_dtype, check_index_type, check_series_type, check_less_precise, check_names, check_exact, check_datetimelike_compat, check_categorical, obj)
   1310                                        check_less_precise=check_less_precise,
   1311                                        check_dtype=check_dtype,
-> 1312                                        obj='{0}'.format(obj))
   1313
   1314     # metadata comparison

as/pandas/util/testing.pyx in pandas.util.libtesting.assert_almost_equal (pandas/util/testing.c:4156)()

as/pandas/util/testing.pyx in pandas.util.libtesting.assert_almost_equal (pandas/util/testing.c:3274)()

/Users/taugspurger/Envs/pandas-dev/lib/python3.6/site-packages/pandas/pandas/util/testing.py in raise_assert_detail(obj, message, left, right, diff)
   1137         msg = msg + "\n[diff]: {diff}".format(diff=diff)
   1138
-> 1139     raise AssertionError(msg)
   1140
   1141

AssertionError: Series are different

Series values are different (100.0 %)
[left]:  [1]
[right]: [2]

```

**Comment by jreback** [comment]
@TomAugspurger btw, make sure you can locally conda build (or pip), install into a fresh env and do a
``python -c "import pandas; pandas.test()"`` works (we tests this on travis, but this is a check).

also *after* you tag, but before pushing, make sure the same works for the ``__version__``

**Comment by jreback** [comment]
thanks @TomAugspurger

**Pull request merged**
