### PR TITLE
CLN: remove deprecated sqlite cursor 

### PR DESCRIPTION
**Pull request by fangchenli**
some cleanup before update the SQL module for sqlalchemy 2.0.

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @fangchenli

**Comment by jreback** [comment]
is this user facing in any way?

**Comment by fangchenli** [comment]
> is this user facing in any way?

No it's not.

**Comment by jreback** [comment]
thanks @fangchenli

**Pull request merged**
