### PR TITLE
WEB: Add Luke to maintainers list

### PR DESCRIPTION
**Pull request by datapythonista**
@lukemanley feel free to merge if it looks fine :)

### CODE REVIEW

**Comment by lukemanley** [comment]
failure seems unrelated? looks like a seg fault.

**Comment by datapythonista** [comment]
> failure seems unrelated? looks like a seg fault.

Yes, the doc build is green, surely unrelated, so safe to merge I think.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Feel free to merge @lukemanley :)

**Comment by lukemanley** [comment]
thanks @datapythonista

**Pull request merged**
