### PR TITLE
Add type annotations to the PR checklist

### PR DESCRIPTION
**Pull request by twoertwein**
It would be great to have an automated check that new arguments/functions/methods have to have type annotations but I'm not sure whether we can enforce that easily. Let's start by encouraging type annotations through the PR template :)

### CODE REVIEW

**Comment by twoertwein** [comment]
@Dr-Irv Should probably also add a comment to nudge people to submit follow-up PRs to [pandas-stubs](https://github.com/pandas-dev/pandas-stubs) to add new/changed arguments/methods/functions.

**Comment by jreback** [comment]
> @Dr-Irv Should probably also add a comment to nudge people to submit follow-up PRs to [pandas-stubs](https://github.com/pandas-dev/pandas-stubs) to add new/changed arguments/methods/functions.

prob need to add to the typing doc-section about this, but +1

**Comment by jreback** [comment]
thanks @twoertwein

**Comment by Dr-Irv** [comment]
> > @Dr-Irv Should probably also add a comment to nudge people to submit follow-up PRs to [pandas-stubs](https://github.com/pandas-dev/pandas-stubs) to add new/changed arguments/methods/functions.
> 
> prob need to add to the typing doc-section about this, but +1

Totally agree.  Still need to write up some docs about how to work with the `pandas-stubs` repo.

**Pull request merged**
