### PR TITLE
Update the common.py file

### LINKED ISSUE #45345: is_numeric_dtype('B') returns True
`is_numeric_dtype` of certain single-capital-letter strings unexpectedly returns `True`

```py
import pandas as pd

pd.api.types.is_numeric_dtype('A')
Out[40]: False
pd.api.types.is_numeric_dtype('B')
Out[41]: True
pd.api.types.is_numeric_dtype('C')
Out[42]: False
pd.api.types.is_numeric_dtype('D')
Out[43]: True
pd.api.types.is_numeric_dtype('E')
Out[44]: False
pd.api.types.is_numeric_dtype('F')
Out[45]: True
pd.api.types.is_numeric_dtype('G')
Out[46]: True
pd.api.types.is_numeric_dtype('H')
Out[47]: True
pd.api.types.is_numeric_dtype('I')
Out[48]: True
pd.api.types.is_numeric_dtype('J')
Out[49]: False
```

That isn't intentional, is it?

### PR DESCRIPTION
**Pull request by yashrajput0508**
Solve the dtype issue in pandas
- [ ] closes #45345
- [ Update the pandas.dtype function at line no. 1779] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
If this is supposed to fix a bug, it needs a test for that bug.  Also looks like it is breaking some existing tests.

**Review by mroeschke — CHANGES_REQUESTED** [review]
The idea is to add an example to the documentation not add code.

https://github.com/pandas-dev/pandas/issues/45345#issuecomment-1012681991

**Review by jreback — CHANGES_REQUESTED** [review]
this is a super hot path i am not sure its worth even doing this

in any event would need tests and benchmark results

**Comment by mroeschke** [comment]
Thanks for the PR @yashrajput0508. But the idea would be to add an example to the docstring that would be run as a doctest. If still interested in working on the docstring, please open a new PR after validating your change by running `ci/code_checks.sh doctests`

**Pull request closed without merging**
