### PR TITLE
WEB: Add Telegram to follow us and footer

### PR DESCRIPTION
**Pull request by datapythonista**
Since we've been posting way more in Telegram than in Twitter, probably worth adding it to the website.

Adding buttons here in the web footer, next to the other icons, and in the home page, in the `Follow us` section (I changed the twitter banner to a button, which I think looks better with more than one item).

This is what's linked for the Telegram icons: https://t.me/s/pandas_dev

### CODE REVIEW

**Comment by mroeschke** [comment]
Related topic, maybe we start posting more on Twitter.

Our reach appears to be greater on Twitter https://twitter.com/pandas_dev (19.4k followers) vs Telegram (81 followers)

**Comment by datapythonista** [comment]
> Related topic, maybe we should start posting more on Twitter?

If someone wants to do that... I personally don't like Twitter. Besides all the censoring and bias, tweets are too short, and it's annoying that they can't be edited. Also, Telegram has a quite nice and open API, so anyone should be able to fetch our updates via JSON very easily, While Twitter requires creating a key, there are quotas, and it's way more work. Also, it's quite easy to automate Telegram posts, for examples for releases. I think a simple CI job and curl should be enough if we wanted to do it. Telegram also supports markdown formatting, including monospace, which is convenient for code.

> Our reach appears to be greater on Twitter https://twitter.com/pandas_dev (19.4k followers) vs Telegram (81 followers)

It's difficult to compare both. Our Twitter account is significantly older, it's been linked from the website for a while, and Twitter is quite used by the PyData community. Our Telegram account is new and hasn't be promoted anywhere (this PR is the first public mention other than a post I did in my personal LinkedIn). Based on what I see, Telegram has more monthly active users (700M vs 300M from Twitter), but most people use it as an IM app, not so much to follow accounts, even if it's growing fast. Not sure if we would get 20k followers, but if our Telegram account was as old as the Twitter one, and was linked from the Website, it'd clearly have few thousands in my opinion.

In any case, I think it's a question of whether anyone is willing to post in them more than anything else. I won't personally post regularly in Twitter since it's technically poor, and completely unethical platform. But if anyone else wants to do it, fine by me.

**Comment by mroeschke** [comment]
Gotcha. I can to mirror our posts and messaging to Twitter then. I think it's worthwhile to ensure the PyData community that's active there also is aware of pandas updates.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @datapythonista

**Comment by MarcoGorelli** [comment]
> But if anyone else wants to do it, fine by me.

I'd be happy to help out with this, though don't currently have access, could either of you please share it with me?

**Comment by datapythonista** [comment]
Sent them to you @MarcoGorelli. I think you already have them @mroeschke, let me know if you don't have access to them anymore.

**Comment by mroeschke** [comment]
I don't have access to the Twitter account, but if @MarcoGorelli would like to ensure we are engaged there I'm fine with not oversharing the credentials.

**Comment by datapythonista** [comment]
I think you were in the sprint when they were shared, that's why I thought you had them. Just ping me if you need them at any point.

**Pull request merged**
