### PR TITLE
DEV: Add static modifier to inline declarations.

### PR DESCRIPTION
**Pull request by jvkersch**
It is currently impossible to build a debug version of Pandas on Mac OS, since some of the C function declarations are declared as `inline`, and compiling in debug mode turns off optimizations and hence inlining. While this could be solved by adding a compile argument to `setup.py` to use the C89 behavior for inline as in #10510, I believe an ultimately cleaner solution may consist of declaring inlined functions as `static`, so that the code is properly C99-compliant.

For the implementation, I added the `static` keyword to the definitions of `PANDAS_INLINE` and `P_INLINE` (and removed duplicate occurrences of `static` from some function declarations), so that future implementations that use those defines are automatically compliant. This is slightly different from e.g. Cython, which defines `CYTHON_INLINE` as `inline` and declares everything as `static CYTHON_INLINE`.

### CODE REVIEW

**Comment by jvkersch** [comment]
I think this provides an alternative solution for #10510, but I haven't tested this yet (currently downloading a FreeBSD vm over crummy internet).

**Comment by wesm** [comment]
Makes sense to me. Reviewed lgtm if the build passes.

**Comment by jvkersch** [comment]
I ended up removing the conditional flag `-fgnu89-inline` on FreeBSD, since the addition of `static` makes it unnecessary. Building succeeds on my copy of FreeBSD 10.2, and the tests more or less run (there are some failures but they don't look related).

**Comment by jreback** [comment]
pls add a whatsnew note
and comment on that other issue for them to try this PR (just to confirm)

**Comment by jvkersch** [comment]
Done. Thanks guys for the quick feedback.

**Comment by jreback** [comment]
@jvkersch thank you sir!

**Pull request closed without merging**
