### PR TITLE
PERF/DOC:  Option to .info() and .memory_usage() to provide for deep introspection of memory consumption #11595

### LINKED ISSUE #11595: Optionally use sys.getsizeof in DataFrame.memory_usage
I would like to know how many bytes my dataframe takes up in memory.  The standard way to do this is the `memory_usage` method

    df.memory_usage(index=True)

For object dtype columns this measures 8 bytes per element, the size of the reference not the size of the full object.  In some cases this significantly underestimates the size of the dataframe.

It might be nice to optionally map `sys.getsizeof` on object dtype columns to get a better estimate of the size.  If this ends up being expensive then it might be good to have this as an optional keyword argument.

    df.memory_usage(index=True, measure_object=True)

### PR DESCRIPTION
**Pull request by jreback**
closes #11595

### CODE REVIEW

**Comment by jreback** [comment]
cc @mrocklin

**Comment by mrocklin** [comment]
Does this descend into categories and the index?

**Comment by jreback** [comment]
wondering if you were going to ask that....it DOES do the index. not the categories, but I can fix this ......

**Comment by jreback** [comment]
Now includes embedded usage for Index & Categorical

```
In [5]:    df = DataFrame({'A' : ['foo']*1000})

In [6]:    df['B'] = df['A'].astype('category')

In [8]:    df.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 2 columns):
A    1000 non-null object
B    1000 non-null category
dtypes: category(1), object(1)
memory usage: 16.6+ KB

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 2 columns):
A    1000 non-null object
B    1000 non-null category
dtypes: category(1), object(1)
memory usage: 55.7 KB

In [11]: df.memory_usage()
Out[11]: 
A    8000
B    1008
dtype: int64

In [12]: df.memory_usage(deep=True)
Out[12]: 
A    48000
B     1048
dtype: int64
```

**Comment by jreback** [comment]
And providing on ``Series`` as well

```
In [6]: df['A'].memory_usage()
Out[6]: 8000

In [7]: df['A'].memory_usage(index=True)
Out[7]: 16000

In [8]: df['A'].memory_usage(index=True,deep=True)
Out[8]: 56000
```

**Comment by mrocklin** [comment]
BTW, I'm glad that `memory_usage_of_objects` is usable on numpy arrays as well.  I may end up using that outside of pandas.

**Comment by jreback** [comment]
right ``dask.array`` could certainly introspect here as well

**Comment by maximilianr** [comment]
I'll wait until this is merged before adding `__getsize__`. 
Is there a reason `index` is `False` by default? I'd have thought that would be 'part of the package'.

**Comment by jreback** [comment]
@maximilianr I don't recall the discussion, but I think we *should* change the default. Note that this is just for a direct call to ``memory_usage`` and not for ``.info`` where it is included.

why don't you post an issue and we'll change in 0.18 (as its a small API change).

**Pull request merged**
