### PR TITLE
CI: Fix jedi upgrades causes deprecation warning

### LINKED ISSUE #31324: CI: seems jedi caused ci to fail in certain versions
```
self = <pandas.tests.indexes.test_base.TestIndex object at 0x7f666b28c990>
ip = <IPython.core.interactiveshell.InteractiveShell object at 0x7f666b28ccd0>

    @async_mark()
    async def test_tab_complete_warning(self, ip):
        # ***/issues/16409
        pytest.importorskip("IPython", minversion="6.0.0")
        from IPython.core.completer import provisionalcompleter
    
        code = "import pandas as pd; idx = pd.Index([1, 2])"
        await ip.run_code(code)
        with tm.assert_produces_warning(None):
            with provisionalcompleter("ignore"):
>               list(ip.Completer.completions("idx.", 4))

pandas/tests/indexes/test_base.py:2418: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <contextlib._GeneratorContextManager object at 0x7f666b2a0a50>
type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               AssertionError: Caused unexpected warning(s): [('DeprecationWarning', DeprecationWarning('Deprecated since version 0.16.0. Use get_signatures()[...].params'), '/home/vsts/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/jedi/cache.py', 111)]
```

### PR DESCRIPTION
**Pull request by charlesdong1991**
- [ ] closes #31324 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by alimcmaster1** [comment]
Assume the warning is raised in the Jedi code? Is there an issue open upstream - so hopefully this gets fixed?

**Comment by charlesdong1991** [comment]
I think `ipython` should have a change to align with the newer version of jedi @alimcmaster1

**Comment by jreback** [comment]
thanks @charlesdong1991 

can you create an issue to see what we should do once a new jedi is released (e.g. revert this patch), but maybe we do nothing.

**Comment by charlesdong1991** [comment]
based on jedi explanation, I think `Ipython` needs to react on the deprecation, and I will create an issue here and also in `ipython` later tonight.

Once ipython changes and no longer raises warning, i think we could revert the change then. @jreback

**Pull request merged**
