### PR TITLE
BUG: pd.concat fails when handling MultiIndex if repeated index exists

### LINKED ISSUE #20565: concat handles MultiIndex differently when row count is the same
#### Code Sample, a copy-pastable example if possible

```python
rows1 = 3
df1 = pd.DataFrame(np.random.randn(rows1, 2), columns=['A', 'B'], index=['Z1']*rows1)

rows2 = 3
df2 = pd.DataFrame(np.random.randn(rows2, 2), columns=['A', 'B'], index=['Z1']*rows2)

df = pd.concat([df1, df2], keys=['Key1', 'Key2'], names=['KEY', 'ID'])
print(df.index)

```
#### Problem description
If rows1 = rows2 as in the example, I get the following multi index from concat where 'Z1' is repeated with separate references in labels. However, if rows1 != rows2 (e.g. change rows1 to 4), I get what seems to be the more reasonable result in the expected output where 'Z1' is listed once with the same reference in labels. 

MultiIndex(levels=[['Key1', 'Key2'], **['Z1', 'Z1', 'Z1']**],
           labels=[[0, 0, 0, 1, 1, 1], **[0, 1, 2, 0, 1, 2]**],
           names=['KEY', 'ID'])

The repeating multi index seemed to cause issues later when using inner merge on left/right index. Is this concat behavior expected?

#### Expected Output
MultiIndex(levels=[['Key1', 'Key2'], **['Z1']**],
           labels=[[0, 0, 0, 1, 1, 1], **[0, 0, 0, 0, 0, 0]**],
           names=['KEY', 'ID'])

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.2.5
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

### LINKED ISSUE #20816: pd.concat fails if given repeated keys
#### Code Sample, a copy-pastable example if possible

```python
series_list = [pd.Series({"a": 1}), pd.Series({"b": 2}), pd.Series({"c": 3})]
print(pd.concat(series_list, verify_integrity=True))  # This works fine

# Raises TypeError 
print(pd.concat(series_list, keys=["red", "red", "red"]))

# Does NOT raise an exception without verify_integirty.
# However, the object `pd.concat` returns is broken (see below for details).
print(pd.concat(series_list, keys=["red", "blue", "red"]))

# Raises ValueError
print(pd.concat(
    series_list, keys=["red", "blue", "red"],
    verify_integrity=True)) 
```

#### Expected Output
Since the indices of the Series don't conflict, it should be fine to use the same key for several rows (after all, it works fine without any keys at all). None of these calls should raise an exception and the objects they return should not be broken (see below for what I mean). Expected output:

```
a    1
b    2
c    3
dtype: int64
red  a    1
red   b    2
red  c    3
dtype: int64
red  a    1
blue   b    2
red  c    3
dtype: int64
```

#### Problem description

This is similar to issue #20565 (but even worse, IMO). I think the problem is that `pd.concat` creates a Series with duplicate entries in its index. This is illustrated by the broken object one of the above calls creates:

```python
> broken = pd.concat(series_list, keys=["red", "blue", "red"])
> broken.index  # Below, `levels[0]` should contain one u'red', not two.
MultiIndex(levels=[[u'red', u'blue', u'red'], [u'a', u'b', u'c']],
           labels=[[1, 0, 1, 1, 1, 0, 1], [0, 1, 2]])
```

Lots of operations fail on this object. For instance,  `broken.sort_index()`   raises "ValueError: operands could not be broadcast together with shapes (7,) (3,) (7,)".

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.3.5-smp-811.22.0.0
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.UTF-8
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: None
setuptools: None
Cython: None
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 2.0.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2018.3
blosc: None
bottleneck: None
tables: 3.1.1
numexpr: 2.5
feather: None
matplotlib: 1.5.2
openpyxl: None
xlrd: 0.9.3
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by charlesdong1991**
xref #20565 

- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by charlesdong1991** [comment]
This PR is basically continuing the work in #25117 with slightly change to make it work, and also add changes based on old reviews.

In the meantime, this also seems to resolve the issue #20816 , therefore, have tests for both.

**Comment by WillAyd** [comment]
Can you check benchmarks for this? I would think that replacing the internal factorize with itertools.chain could drastically slow things down

**Comment by charlesdong1991** [comment]
thanks! @WillAyd changed

btw, just a question, somehow, yesterday when i was trying to check benchmark, it takes ages and I felt my laptop almost burned, is this normal for local benchmark checking?

I will check the benchmark tomorrow

**Comment by WillAyd** [comment]
Running the entire benchmark suite will take a while. You probably want to limit it to what you think is the affected code, so something like `asv continuous upstream/master HEAD -b join_merge.Concat` for this PR

**Comment by WillAyd** [comment]
@charlesdong1991 still active? Can you fix merge conflicts and try to get CI green?

**Comment by charlesdong1991** [comment]
yeah, still active, but i will be off for vacation for several days, will update in a week. @WillAyd 👍

**Comment by simonjayhawkins** [comment]
@charlesdong1991 what's the status here?

**Comment by charlesdong1991** [comment]
emm, let me close for now, haven't past tests locally. will reopen once finding a way.

**Pull request closed without merging**
