### PR TITLE
CI: Fix PyPy CI

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

PyPy was not being pulled correctly. Its fixed now and have confirmed.

### CODE REVIEW

**Comment by lithomas1** [comment]
@github-actions pre-commit.

**Comment by jreback** [comment]
@lithomas1 can you merge master one more time (as i merged the pypy3 affecting PR :-<>)

**Comment by lithomas1** [comment]
@jreback. This is ready now.
There are a couple gotchas, though:
- Cython 0.29.26 doesn't compile correctly for PyPy.
- Coverage is disabled because it slows down everything a lot.
- The CSV reader crashes are gone, but we're crashing a lot elsewhere, and that slows everything down when the crashed workers need to be restarted. So, I set the CI to not restart workers. Some tests may be missed, but otherwise we can't get through the test suite.

I'll open an issue as a follow up.

**Comment by jreback** [comment]
> https://github.com/pandas-dev/pandas/runs/4562612265?check_suite_focus=true

i think this is actually failing (but the check is not)

**Comment by jreback** [comment]
> @jreback. This is ready now. There are a couple gotchas, though:
> 
> * Cython 0.29.26 doesn't compile correctly for PyPy.
> * Coverage is disabled because it slows down everything a lot.
> * The CSV reader crashes are gone, but we're crashing a lot elsewhere, and that slows everything down when the crashed workers need to be restarted. So, I set the CI to not restart workers. Some tests may be missed, but otherwise we can't get through the test suite.
> 
> I'll open an issue as a follow up.

totally cool to disable things, basics are all that is needed here

**Comment by lithomas1** [comment]
Yeah, I set it to always succeed in the testing phase since a lot of tests fail.

**Comment by jreback** [comment]
great as a follow up we should skip / xfail o ln pypy3

**Comment by jreback** [comment]
@lithomas1 hey if you can shoot me an email 'jeffreback@gmail.com' have some info for you

**Pull request merged**
