### PR TITLE
DOC Fix inconsistencies

### PR DESCRIPTION
**Pull request by Scowley4**
Fix a few inconsistencies in the docstrings.

Not sure how pandas community feels about these kinds of fixes (and this is my first PR to pandas). I just notice things that are different from how they occur most of the time and decided to fix them up. 

#### Add 's' to headers
```
Example
```
to
```
Examples
```

#### Correct number of hyphens under headers
```
Yields
-------
```
to
```
Yields
------
```

#### Rewrite testcase in standard format
```
In [1]: c = pd.Categorical(list('aabca'))
```
to
```
>>> c = pd.Categorical(list('aabca'))
```

### CODE REVIEW

**Comment by jreback** [comment]
@WillAyd @datapythonista doesn't the doc-string validator catch the invalid underlines?

**Comment by WillAyd** [comment]
I don't see anything currently for underlines. Worth taking a look at; not sure how numpydoc would even parse that

I am surprised some of these weren't raising GL06 for "unknown section". This is definitely part of the CI and should be raised when the section is called say "Example" instead of "Examples"

**Comment by Scowley4** [comment]
@jreback @WillAyd 

I'm not sure why these weren't caught before but these fixes allowed the Docstring validation test to see that their sections were in the wrong order. It looks like the ones that were out of order _and_ had incorrect number of underlines were not be considered sections before, so they were not considered out of order. I'm not sure where I would look at the Docstring validation to confirm this is what is happening... but should I go ahead and reorder them as part of this pr as well?

**Comment by WillAyd** [comment]
Yea might as well reorder to get rid of any and all failures. FWIW the validator is located in `scripts/validate_docstrings.py` if you wanted to see how it works

**Review by datapythonista — APPROVED** [review]
lgtm, thank for taking care of all those @Scowley4 

Not sure if there is something wrong with the validation of these.  `GL06` is being checked in the CI, and should report unknown headers like `Example`, `Return`.... But I think all the fixed ones are private, and I think we don't run the validation over them.

Having too many hyphens it does happen in public docstrings. In this case I think our validation gets the docstring already parsed from numpydoc, and I'm not sure if numpydoc is happy when there are more or less hyphens.

@Scowley4 do you want to do some research, and open an issue proposing what you think it's best?

**Comment by datapythonista** [comment]
Just saw that the CI is red, the problem is that the fixed sections are now detected, and they are in the wrong position with respect to the other sections. See:
```
pandas/core/indexes/multi.py(122,): error GL07: pandas.MultiIndex: Sections are in the wrong order. Correct order is: Parameters, Attributes, Methods, See Also, Notes, Examples
pandas/core/indexes/multi.py(2347,): error GL07: pandas.MultiIndex.get_loc: Sections are in the wrong order. Correct order is: Parameters, Returns, See Also, Notes, Examples
pandas/core/indexes/multi.py(2447,): error GL07: pandas.MultiIndex.get_loc_level: Sections are in the wrong order. Correct order is: Parameters, Returns, See Also, Examples
pandas/core/indexes/datetimes.py(95,): error GL07: pandas.DatetimeIndex: Sections are in the wrong order. Correct order is: Parameters, Attributes, Methods, See Also, Notes
pandas/core/indexes/period.py(73,): error GL07: pandas.PeriodIndex: Sections are in the wrong order. Correct order is: Parameters, Attributes, Methods, See Also, Notes, Examples
Bash exited with code '5'.
```

So, looks like numpydoc is "ignoring" (not considering header sections) the ones with the wrong hyphens, which I think makes sense. I don't think we can detect wrong section names with wrong hyphens automatically, but we could add a validation that looks for the correct section names in the docstring, and checks if the section exists (if the section has been detected by numpydoc). I think if we check that the name of the section exists in the docstring in a single line, we shouldn't have false positives.

For example, we can have in the notes `Parameters will be added in the future...` and we don't want to fail because we found the word `Parameters` without the section `Parameters`. But if in a line just `Parameters` is found, we probably should fail.

@Scowley4 if you want to work on it, can you open an issue please? Otherwise I'll create it myself so someone else can work on it.

**Comment by Scowley4** [comment]
@WillAyd Thanks for pointing me to the testing code.

@datapythonista Totally agree with the "ignoring section header" thing and have opened an issue about it that I would like to work on. #26307

**Comment by datapythonista** [comment]
Changes look good, but CI is red. Not sure what's the problem, may be you just need to merge master, the error seems unrelated to the docstring changes.

**Comment by Scowley4** [comment]
@datapythonista Was trying to figure out what the error was. Wondering if I accidentally started down a rabbit hole (One fix exposes more problems and more and more...).

Can you be a little more explicit about what you suggest I do? Did you mean for me to merge into my master branch?
(Sorry, still pretty new to working in opensource stuff)

**Comment by datapythonista** [comment]
in you branch just do `git fetch upstream && git merge upstream/master`

this will let in your branch your changes, but applied to the last version of pandas, not the version when you created the branch

**Comment by Scowley4** [comment]
Same error. Maybe now that the sections are actually sections and in the correct order, there is something wrong inside one and that is throwing the error. I haven't found the fix yet, though...

**Comment by Scowley4** [comment]
As far as I can tell, the only place `to_panel` appears is here:

https://github.com/pandas-dev/pandas/blob/2bbc0c2c198374546408cb15fff447c1e306f99f/pandas/core/generic.py#L206-L211

**Comment by Scowley4** [comment]
I guess the above is just in `pandas/pandas`.

In the full repository:

https://github.com/pandas-dev/pandas/blob/2bbc0c2c198374546408cb15fff447c1e306f99f/doc/redirects.csv#L501

https://github.com/pandas-dev/pandas/blob/master/doc/source/reference/frame.rst

And two places in `doc/source/whatsnew` (v0.7.0 and v0.19.0)

----
It looks like this method was removed recently: #25047

**Comment by WillAyd** [comment]
@Scowley4 try merging master issue should have been fixed in #26308

**Review by gfyoung — APPROVED** [review]
@datapythonista @WillAyd : if you'd like to double check before merging

**Comment by WillAyd** [comment]
@Scowley4 just had another PR go in which conflicts here - could you fix that up? Otherwise lgtm

**Review by WillAyd — APPROVED** [review]
ping on green

**Comment by datapythonista** [comment]
thanks @Scowley4, nice clean up

**Pull request merged**
