### PR TITLE
 STYLE: replace unwanted-patterns-strings-to-concatenate with ruff #51406

### PR DESCRIPTION
**Pull request by harsimran44**

### CODE REVIEW

**Comment by harsimran44** [comment]
hey, i need help regarding this please.
git test

**Comment by MarcoGorelli** [comment]
See here https://beta.ruff.rs/docs/rules/explicit-string-concatenation/

**Comment by harsimran44** [comment]
> See here https://beta.ruff.rs/docs/rules/explicit-string-concatenation/

i have done this but there are some other problems came up.
problems

**Comment by MarcoGorelli** [comment]
thanks for your PR

closing in favour of https://github.com/pandas-dev/pandas/pull/51613 (who, in fairness, had already said that they were working on this and to whom the issue had been assigned)

**Comment by harsimran44** [comment]
sir i have mostly fixed the errors. one last can u help me with that. please
issue

**Pull request closed without merging**
