### PR TITLE
TST/STYLE: remove multiprocess nose flags and slight PEP fixes

### PR DESCRIPTION
**Pull request by jreback**
https://github.com/pandas-dev/pandas/pull/13856#issuecomment-278058522

### CODE REVIEW

**Comment by jreback** [comment]
I ended up having to autopep8 things to remove the extra lines when I took out the multiprocessing directive. But seems to pass and all be good.

@jorisvandenbossche @TomAugspurger @bashtage

**Comment by jorisvandenbossche** [comment]
This will not conflict with Tom's pytest PR?

**Comment by TomAugspurger** [comment]
I just did a test rebase on top of this, and didn't have to resolve any conflicts. Haven't looked at the new diff yet though.

**Comment by jorisvandenbossche** [comment]
@jreback The test files are not tested for PEP8 on travis? And would they pass now with those changes?

**Comment by jreback** [comment]
i am not 100% sure we are testing ALL files (that's why some things were changed)

everything passes now but let me see if i can add the other files

**Comment by jreback** [comment]
actually I think the slight peps are to files what we ignore flake on. so pretty innocuous.

**Pull request closed without merging**
