### PR TITLE
DOC: Add datetime.tzinfo to paramater tz in tz_localize and tz_convert

### LINKED ISSUE #50655: DOC: tz_x functions do not include zoneinfo and tzinfo support in their documentation
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

This is present in multiple places such as:

- https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.tz_localize.html
- https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.tz_localize.html
- https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.tz_convert.html

### Documentation problem

The listed types for the parameter `tz` is `str, pytz.timezone, dateutil.tz.tzfile or None`, even though zoneinfo and tzinfo are supported.

### Suggested fix for documentation

I suggest adding updating the docs to include tzinfo.

We could probably skip zoneinfo.ZoneInfo since it is a subclass of tzinfo.

### PR DESCRIPTION
**Pull request by luke396**
- [x] closes #50655 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by aqeelat** [comment]
Don't forget to add it to the functions listed in the issue. There could be more that I forgot to include.

**Comment by luke396** [comment]
> Don't forget to add it to the functions listed in the issue. There could be more that I forgot to include.

All functions about tz_localize or tz_convert seem to share the same doc template, so this will influence all of them (Series.tz_localize, DataFrame.tz_localize, DateIndex.tz_localize... ). I haven't found more functions that need to be added, so if so, feel free to bring them up.

**Comment by aqeelat** [comment]
> All functions about tz_localize or tz_convert seem to share the same doc template, so this will influence all of them (Series.tz_localize, DataFrame.tz_localize, DateIndex.tz_localize... ). I haven't found more functions that need to be added, so if so, feel free to bring them up.

I actually haven't read the code. Sorry for the wrong comment and thank you for solving the issue.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @luke396

**Pull request merged**
