### PR TITLE
ENH: enable server side cursors when chunksize is set

### LINKED ISSUE #35689: ENH: Support PostgreSQL server-side cursors to prevent memory hog on large datasets
#### Is your feature request related to a problem?

`pandas.read_sql_query` supports Python "generator" pattern when providing `chunksize` argument. It's not very helpful when working with large datasets, since the whole data is initially retrieved from DB into client-side memory and later chunked into separate frames based on `chunksize`. Large datasets will easily run into out-of-memory problems with this approach.

#### Describe the solution you'd like

Postgres/psycopg2 are addressing this problem with [server-side cursors](https://www.psycopg.org/docs/usage.html#server-side-cursors). But Pandas does not support it.

#### API breaking implications

`is_cursor` argument of `SQLDatabase` or `SQLiteDatabase` is not exposed in `pandas.read_sql_query` or `pandas.read_sql_table` without any reason. It should be exposed, this way named (server-side) cursor could be provided.

#### Describe alternatives you've considered

Instead of doing:

```
iter = sql.read_sql_query(sql,
      conn,
      index_col='col1',
      chunksize=chunksize)
```

I tried reimplementing it like this:

```
from pandas.io.sql import SQLiteDatabase

curs = conn.cursor(name='cur_name') # server side cursor creation
curs.itersize = chunksize

pandas_sql = SQLiteDatabase(curs, is_cursor=True)
iter = pandas_sql.read_query(
      sql,
      index_col='col1',
      chunksize=chunksize)
```

but it fails because `SQLiteDatabase` tries to access `cursor.description`, which is NULL for some reason with server-side cursors (and idea why?).

### PR DESCRIPTION
**Pull request by skshetry**
Please look at the previous attempts in #40796 and #46166.  A lot of changes have happened since that PR. Since `SQLTable` (or `PandasSQL`) seems polymorphic, I did not want to change the function signature of `execute()` and noticed the use of `self.returns_generator` which can be used to use server-side cursors or not.

- [x] closes #35689
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by WillAyd** [comment]
Does postgres support this? It would be nice if we can add a test that asserts this actually happens.

I suppose it would also be limited to only some of the drivers. I know the ADBC postgres driver does not implement this yet, guessing libpq does?

**Comment by skshetry** [comment]
I have added a simple test to check for `execution_options`.

**Comment by WillAyd** [comment]
> Since this is mostly a memory optimization, I am not sure how to test this. I don't want to mock it as much as possible. If you have any ideas, I'm happy to add a test.

Probably the best way to assert this actually does something is to add a `peakmem` benchmark to `asv_bench/benchmarks/io/sql.py`

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Comment by skshetry** [comment]
I'm so sorry to disappear like this. A lot of things happening both personally and at work that I won't be able to get to it in the short time.

If anyone wants to contribute, the only thing missing from this PR is a _memory_ benchmark (although I don't think it's important).

**Pull request closed without merging**
