### PR TITLE
solve list cannot add to tuple error in make_signature function

### PR DESCRIPTION
**Pull request by caikehe**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
what exactly does this break?

**Comment by caikehe** [comment]
when I run an example like: 

`from pandas.util.decorators import make_signature
def f(a,b,c=2) :
    return a*b*c

print(make_signature(f))`

I will get an error as: 
defaults = ('',) * n_wo_defaults + spec.defaults
TypeError: can only concatenate tuple (not "list") to tuple

**Comment by jreback** [comment]
hmm, that does fail (only in py3). Well must have been a typo in the copy paste a while back. Can you add a test in ``pandas/tests/test_util.py``.  ``make_signature`` is actually used in ``pandas.core.groupby``. Can you repro an error from something?

**Comment by jreback** [comment]
can you rebase / update?

**Pull request closed without merging**
