### PR TITLE
DOC: update the pandas.Series.dt.is_month_end docstring

### PR DESCRIPTION
**Pull request by janelle**
Checklist for the pandas documentation sprint (ignore this if you are doing
an unrelated PR):

- [X] PR title is "DOC: update the <your-function-or-method> docstring"
- [X] The validation script passes: `scripts/validate_docstrings.py <your-function-or-method>`
- [X] The PEP8 style check passes: `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] The html version looks good: `python doc/make.py --single <your-function-or-method>`
- [X] It has been proofread on language by another sprint participant

Please include the output of the validation script below between the "```" ticks:

```
################################################################################
################## Docstring (pandas.Series.dt.is_month_end)  ##################
################################################################################

Return a boolean indicating whether the date is the last day of the month.

Returns
-------
is_month_end : Series of boolean.

See Also
--------
is_month_start : Return a boolean indicating whether the date is
    the first day of the month.

Examples
--------
>>> dates = pd.Series(pd.date_range("2018-02-27", periods=3))
>>> dates
0   2018-02-27
1   2018-02-28
2   2018-03-01
dtype: datetime64[ns]
>>> dates.dt.is_month_end
0    False
1    True
2    False
dtype: bool

################################################################################
################################## Validation ##################################
################################################################################

Errors found:
	No extended summary found

```

If the validation script still gives errors, but you think there is a good reason
to deviate in this case (and there are certainly such cases), please state this
explicitly.

No extended summary required in this case (as confirmed with peers).

### CODE REVIEW

**Comment by janelle** [comment]
please ignore for now, wrong function

**Comment by Cheukting** [comment]
The sentences for See Also section is too long, need to break it into 2 lines.

**Review by jorisvandenbossche — APPROVED** [review]
Looks good!

Added a commit that fixes the PEP8 issues, and added an example with an index (the docstring is shared between Series.dt and DatetimeIndex)

**Comment by jorisvandenbossche** [comment]
Thanks @janelle !

**Pull request merged**
