### PR TITLE
WEB add phofl to maintainers list

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Am I OK to add a checklist (which would probably only have about 3 items: add to pandas-dev team on GitHub, add to mailing group, list on website) to the Wiki for next someone's added?

### CODE REVIEW

**Comment by phofl** [comment]
Thanks @MarcoGorelli

**Comment by jreback** [comment]
thanks @MarcoGorelli and @phofl

**Comment by phofl** [comment]
We should probably add updating the governance people list https://github.com/pandas-dev/pandas-governance/blob/master/people.md every now and then if you add a check list

**Comment by MarcoGorelli** [comment]
Added! https://github.com/pandas-dev/pandas/wiki/Adding-new-maintainers

**Pull request merged**
