### PR TITLE
DOC: df.astype example using dictionary

### LINKED ISSUE #26990: Show astype example with dict in docs
It would be useful to be able to change a column dtype inline.

For example with a DataFrame-level astype() overload:
Assuming `df` has a column called `str_col` that is a string (object),
`df.astype(col='str_col', dtype='int').head()`

The use case that brought me here is to numerically sort a string column without permanently changing it. What I was hoping to do is
`df.astype(col='str_col', dtype='int').sort_values(by='str_col')`

Instead, I had to do this:
`df = df.assign(int_col = lambda x: x['str_col'].astype('int')).sort_values(by='int_col').drop('int_col', axis = 'columns')`

The method would also support dictionaries for multiple column type changes:
`df.astype({'col1':'type1', 'col2':'type2'})`

### PR DESCRIPTION
**Pull request by stevennic**
Closes #26990

### CODE REVIEW

**Comment by WillAyd** [comment]
Thanks! I think this looks good though caused some CI failures if you can take a look.

@datapythonista in case you have any input

**Comment by stevennic** [comment]
Yea the errors don't seem to be related to my changes:
`Worker 'gw0' crashed while running 'pandas/tests/test_sorting.py::TestSafeSort::test_labels_out_of_bound[-1]'`

**Review by WillAyd — APPROVED** [review]
Restarted to be sure but I agree probably unrelated so lgtm. @datapythonista @TomAugspurger if either of you want to take a look feel free to merge

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
