### PR TITLE
DEPR: Index.ravel returning an ndarray

### LINKED ISSUE #19956: PeriodIndex.ravel returns ndarray[int64]
This came up while trying to de-duplicate some DataFrame vs Series arithmetic logic in core.ops.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #19956
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Make Index.ravel() behavior match every other ravel() method in existence.

### CODE REVIEW

**Comment by jreback** [comment]
nice!

**Comment by jorisvandenbossche** [comment]
@jbrockmendel I don't think there was consensus on changing `ravel` to return an Index. See the original discussion at https://github.com/pandas-dev/pandas/issues/19956, and you actually did a similar PR before (https://github.com/pandas-dev/pandas/pull/32641) where I said the same.

- The Index method will now be inconsistent with the Series method
- What's the use case of actually needing an `Index.ravel` method?

**Comment by jbrockmendel** [comment]
> The Index method will now be inconsistent with the Series method

I would be OK changing the deprecation so to say the future behavior is to match self._values.ravel, matching Series behavior.

> What's the use case of actually needing an Index.ravel method?

The same as the use case for Series.ravel: you want to write code that is ndarray/index/series-agnostic

**Comment by jorisvandenbossche** [comment]
> I would be OK changing the deprecation so to say the future behavior is to match self._values.ravel, matching Series behavior.

IMO that sounds as a better option. Having consistency between Series and Index here would be good I think (although Index is more array-like than Series ..)

I am still skeptical about the need for this method at all, though (you can also do a ndim check if you eg want to ensure the array-like is 1D or converted to 1D, see eg Tom's comment at https://github.com/pandas-dev/pandas/issues/19956#issuecomment-433427374)

**Comment by simonjayhawkins** [comment]
> I am still skeptical about the need for this method at all

as there is a top level numpy function for this https://numpy.org/doc/stable/reference/generated/numpy.ravel.html.

In the future, with \_\_array_function__ implemented, could allow much simplification of the pandas API.

so I _think_ OK to deprecate the method, in favour of np.ravel() support.

```
>>> pd.__version__
'1.2.0.dev0+765.g401d7a142c'
>>>
>>> idx = pd.Index([1, 2, 3])
>>>
>>> np.ravel(idx)
array([1, 2, 3], dtype=int64)
>>>
>>> type(_)
<class 'numpy.ndarray'>
>>>
```

so we could use np.ravel to get the current behaviour, of implement \_\_array_function__ if we wanted to return a Index instead.

**Pull request merged**
