### PR TITLE
Create create-issue.yml

### LINKED ISSUE #45409: DOC/CI: Add Github Action cron job to check external links in documentation
1. Modify `doc/make.py` to run `sphinx-build -b linkcheck`. May need to modify `doc/source/conf.py` to ignore some expected link errors.
2. Create a Github Action to run the Sphinx linkcheck monthly
3. If errors are found, have the GIthub Action create a new issue (and delete the old one) reporting all the errors and label and `Docs` and `Good First Issue`

### PR DESCRIPTION
**Pull request by ggold7046**
This is a GIthub Action that creates a new issue (and delete the old one) reporting all the errors and label and Docs and Good First Issue for a broken link.

- [x] closes #45409 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by ggold7046** [comment]
Hi @pmeier, how to proceed with the  [3rd part](https://github.com/pandas-dev/pandas/issues/45409#issue-1105272826) ? The 2nd part is merged.

Almost every time the `linkcheck file` is run there is a new broken link found. Is there a way to automatically append that link into the `ignore list` ?

pmeier Is there any way to Dm you ? I had tried to tag you in the merged PR , but no luck. Do we get notifications in merged or closed PRs ?

**Comment by pmeier** [comment]
> Almost every time the linkcheck file is run there is a new broken link found. Is there a way to automatically append that link into the ignore list ?

No, and that is not the point. When this workflow is running on a schedule and finds broken links, a new issue should be created containing all the broken links so a human can come and fix them. 

Just adding everything to the ignore list is the opposite of what we want. Ideally, we don't want to have an ignore list at all. This is likely not possible, because some links like we have seen for `http://` will never work so they have be ignored. But the ignore list should be as short as possible.

So if you are stuck on this PR, you can also work on reducing the ignore list.

**Comment by datapythonista** [comment]
Thanks for the help with this @ggold7046. The issue you are trying to address is not trivial, and the changes in this PR don't seem to be addressing the issue. I would suggest that you work on an issue that you fully understand. I'll close here, feel free to open a PR once you're sure you understand the problem and you have a reasonable solution. Thank you!

**Comment by ggold7046** [comment]
> So if you are stuck on this PR, you can also work on reducing the ignore list.

I would like to work on the last part of [this](https://github.com/pandas-dev/pandas/issues/45409#issue-1105272826) from where I started. 

> 3. If errors are found, have the GIthub Action create a new issue (and delete the old one) reporting all the errors and label and Docs and Good First Issue

I would like to work on this one.

**Comment by ggold7046** [comment]
> this PR don't seem to be addressing the issue.

Hi @datapythonista , It was a PR work in progress.

**Pull request closed without merging**
