### PR TITLE
CI: Fixed NumPy pinning in conda-build

### LINKED ISSUE #19153: Revert CI: Pin NumPy in 3.6 build
Need a 1.14 build for Numba

xref https://github.com/pandas-dev/pandas/pull/19138
xref #19169

### LINKED ISSUE #19572: CI: conda build test failing
Don't think we have an issue for this yet

```
[building conda recipe]

Leaving build/test directories:
  Work:	 /home/travis/miniconda3/conda-bld/work 
  Test:	 /home/travis/miniconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:	source activate  /home/travis/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:	source activate  /home/travis/miniconda3/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 706, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 441, in decorated
    return f(*args, **kwds)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 540, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 317, in solve_final_state
    conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 697, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 254, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 172, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - numpy[version='>=1.14.0,<1.14']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1032, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 582, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1845, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 670, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 379, in finalize_metadata
    exclude_pattern)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 293, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 281, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 117, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 708, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"numpy[version='>=1.14.0,<1.14']"}

real	0m9.261s
user	0m9.234s
sys	0m1.117s
```

https://api.travis-ci.org/v3/job/338476528/log.txt

Seems like `min_pin='1.14', max_pin='1.14'` is what we would want if want want 1.14.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes #19572 
closes #19153 

(testing locally as well too)

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Built fine locally.

**Comment by jreback** [comment]
local building has always worked fine, its branches that are failing *only* sometimes.

**Comment by TomAugspurger** [comment]
Ah, OK.

Thoughts on failing that worker entirely if the conda-build command fails?

I also see that the command we run is `time conda build ./conda.recipe --numpy 1.13 --python 3.5 -q --no-test`

I suppose that should be bumped?

**Comment by jreback** [comment]
yes should bump that. I *think* there is an issue about 1.14 somewhere as well.

**Comment by TomAugspurger** [comment]
numba packages for numpy 1.14 are out now, so I removed that pin.

Trying without any pins for the conda build recipe. We'll see.

**Comment by jreback** [comment]
so this is still initially installing 1.13 and building, then upgrading to 1.14 after, not sure whey that is. I also *think* we DO need the pinnning on the conda build, it looks like its using a pretty old version (1.11) for building. It still works but is slightly odd.

**Comment by jreback** [comment]
yeah that kind right
we want to build against the oldest version we support for ABI - i guess u can build with 1.9 but maybe we have something in the recipe which doesn’t allow that

**Comment by jreback** [comment]
this still looks odd. we are installing 1.14, then building with 1.11 (i guess min numpy version), but end up with 13.3 (see show_versions() at the end)

```
# Name                    Version                   Build  Channel
pandas                    0.23.0.dev0     np111py35_259_g5d52a3a    local
```

**Comment by TomAugspurger** [comment]
Missed a pin. Hopefully now.

**Comment by TomAugspurger** [comment]
Still ended up with 1.13. One of these packages is forcing a downgrade.

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-dateutil-2.6.1      |           py35_0         237 KB  conda-forge
    parquet-cpp-1.2.0          |                0         1.2 MB  conda-forge
    openssl-1.0.2n             |                0         3.5 MB  conda-forge
    numpy-1.13.3               |py35_nomklhb7e7d7c_0         3.8 MB
    pandas-0.22.0              |           py35_0        25.6 MB  conda-forge
    certifi-2017.11.5          |           py35_0         195 KB  conda-forge
    feather-format-0.4.0       |           py35_2           5 KB  conda-forge
    arrow-cpp-0.5.0            |      np113py35_2         2.0 MB  conda-forge
    pyarrow-0.5.0              |      np113py35_0         600 KB  conda-forge
    jemalloc-4.4.0             |                0         2.3 MB  conda-forge
    ca-certificates-2017.11.5  |                0         145 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        39.6 MB

The following NEW packages will be INSTALLED:

    arrow-cpp:       0.5.0-np113py35_2           conda-forge
    feather-format:  0.4.0-py35_2                conda-forge
    jemalloc:        4.4.0-0                     conda-forge
    pandas:          0.22.0-py35_0               conda-forge
    parquet-cpp:     1.2.0-0                     conda-forge
    pyarrow:         0.5.0-np113py35_0           conda-forge
    python-dateutil: 2.6.1-py35_0                conda-forge

The following packages will be UPDATED:

    ca-certificates: 2017.08.26-h1d4fec5_0                   --> 2017.11.5-0                 conda-forge
    openssl:         1.0.2n-hb7f436b_0                       --> 1.0.2n-0                    conda-forge

The following packages will be DOWNGRADED:

    certifi:         2018.1.18-py35_0                        --> 2017.11.5-py35_0            conda-forge
    numpy:           1.14.0-py35_nomklh7cdd4dd_0             [nomkl] --> 1.13.3-py35_nomklhb7e7d7c_0             [nomkl]

```

pyarrow is pinned to 0.5 for this build. Do you have a preference for

1. pyarrow 0.5 & NumPy 1.13
2. pyarrow / NumPy latest

If 1, this can be merged. Else I'll remove that pyarrow pin.

**Comment by jreback** [comment]
> pyarrow 0.5 & NumPy 1.13
> pyarrow / NumPy latest

hmm would just bump the pyarrow pin to 0.6.0 i think.

**Comment by TomAugspurger** [comment]
0.7.1 was the first one that has a binary that supports numpy 1.14.

**Comment by TomAugspurger** [comment]
OK, https://api.travis-ci.org/v3/job/339442588/log.txt did it correctly. To summarize

1. Build against NumPy 1.11: https://travis-ci.org/pandas-dev/pandas/jobs/339442588#L1131
2. Run in an env with NumPy 1.1.4: https://travis-ci.org/pandas-dev/pandas/jobs/339442588#L947
3. Pyarrow is pinned to 0.7.1: https://travis-ci.org/pandas-dev/pandas/jobs/339442588#L1038

**Pull request merged**
