### PR TITLE
BUG: Fix raw parameter not being respected in groupby.rolling.apply

### LINKED ISSUE #31754: `raw=True` no longer applies to groupby().rolling() in 1.0.0
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'id': [1, 1, 1], 'value': [1, 2, 3]})

def foo(x):
    print(type(x))
    return 0.0
```
When setting `raw=True`
```
>>> df.groupby("id").value.rolling(1).apply(foo, raw=True, engine='numba')
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
id
1   0    0.0
    1    0.0
    2    0.0
Name: value, dtype: float64

>>> df.groupby("id").value.rolling(1).apply(foo, raw=True, engine='cython')
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
id
1   0    0.0
    1    0.0
    2    0.0
Name: value, dtype: float64

>>> df.groupby("id").value.rolling(1).apply(foo, raw=True)
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
id
1   0    0.0
    1    0.0
    2    0.0
Name: value, dtype: float64
```

#### Problem description

This changes the behavior of `raw=True`, it seems it no long allows user to pass numpy array to a rolling udf.

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #31754
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
thanks @mroeschke

**Comment by jreback** [comment]
@mroeschke can you check if this was backported?

**Comment by mroeschke** [comment]
Don't see it in https://github.com/pandas-dev/pandas/commits/1.0.x. I'll backport it when I get a chance

**Comment by jorisvandenbossche** [comment]
@MeeseeksDev backport to 1.0.x

**Comment by jorisvandenbossche** [comment]
@mroeschke I mentioned it on the core list as well now, but know that often commenting with what I did above is enough, which can avoid you need to take the time to manually backport.

**Comment by mroeschke** [comment]
Thanks @jorisvandenbossche. Sorry I forgot to revisit this and backport this PR

**Pull request merged**
