### PR TITLE
CI: Removing Checks job form Azure pipelines

### PR DESCRIPTION
**Pull request by datapythonista**
The `Checks` job was copied to GitHub actions, and looks like it's been working all right. Removing it from pipelines, so it's not diuplicated anymore.

### CODE REVIEW

**Comment by jreback** [comment]
sure

**Comment by jbrockmendel** [comment]
LGTM.  Any reason to wait for the npdev/doc build?

**Comment by gfyoung** [comment]
Given that the failures are most certainly not related to the build.  Merging this.

**Comment by gfyoung** [comment]
Thanks @datapythonista !

**Pull request merged**
