### PR TITLE
DOC: replace deprecated freqs in user_guide Period

### PR DESCRIPTION
**Pull request by natmokval**
xref #54061

replaced deprecated frequencies in user_guide Period with new frequencies.

### CODE REVIEW

**Review by phofl — APPROVED** [review]
Can you grep that they aren't anywhere else?

**Comment by phofl** [comment]
thx @natmokval

**Comment by natmokval** [comment]
> Can you grep that they aren't anywhere else?

yes, I used grep to check if there are anywhere else frequencies which are deprecated.
I found a couple of places where comments contain deprecated frequencies. For example in `pandas/_libs/tslibs/period.pyx` we have deprecated 'T': `# ('T', 5) but may be passed in as a string like '5T'`

I am not sure, should I change 'T' to "min' in the comment?

Also we have in `asv_bench/benchmarks/ `some tests with deprecated frequencies `"S"` and `"H"`. I think it's better to replace them with valid frequencies, are you agree?
Could you please explain why when I run tests with deprecated frequencies they don't fail.

**Comment by natmokval** [comment]
thanks for reviewing this PR @phofl

**Pull request merged**
