### PR TITLE
Update plotting.py

### LINKED ISSUE #10214: hist raises AttributeError: 'AxesSubplot' object has no attribute 'ndim' with a one row DataFrame
Hello,

this code works fine:

    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    bins = np.arange(80, 100 + 2, 1)
    df = pd.DataFrame({"Name": ["AAA", "BBB"], "ByCol": [1, 2], "Mark": [85, 89]})
    df

       ByCol  Mark Name
    0      1    85  AAA
    1      2    89  BBB

    df["Mark"].hist(by=df["ByCol"], bins=bins)
    plt.show()

but same code with a one row DataFrame such as

    df = pd.DataFrame({"Name": ["AAA"], "ByCol": [1], "Mark": [85]})
    df

       ByCol  Mark Name
    0      1    85  AAA

raises:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-35-93bcd47d24f2> in <module>()
    ----> 1 df["Mark"].hist(by=df["Mark"], bins=bins)

    //anaconda/lib/python2.7/site-packages/pandas/tools/plotting.pyc in hist_series(self, by, ax, grid, xlabelsize, xrot, ylabelsize, yrot, figsize, bins, **kwds)
       2847                             **kwds)
       2848
    -> 2849     if axes.ndim == 1 and len(axes) == 1:
       2850         return axes[0]
       2851     return axes

    AttributeError: 'AxesSubplot' object has no attribute 'ndim'

Kind regards

### PR DESCRIPTION
**Pull request by s-celles**
Should fix https://github.com/pydata/pandas/issues/10214#issuecomment-106091734

### CODE REVIEW

**Comment by sinhrks** [comment]
Thanks @scls19fr !

Can you add:

- test cases (pls see ``test_graphics.py``)
- release note for the bug fix (``doc/source/whatsnew``)

**Comment by scls19fr** [comment]
Sorry @sinhrks but I feel:

engrenage

**Comment by TomAugspurger** [comment]
In `pandas/doc/source/whatsnew/v0.17` there's a bunch of one-line notes describing bug fixes. Add one like that.

Tests for this are in `pandas/tests/test_graphics.py` The idea is to make a test that fails without your change, but works with your change. There's a bunch of helpful info here: https://github.com/pydata/pandas/wiki/

Let us know what you're stuck on, and we can walk you through it. Most of us are in the [chat room](https://gitter.im/pydata/pandas) if you want quicker feedback on git stuff.

**Comment by TomAugspurger** [comment]
Superseded by https://github.com/pydata/pandas/pull/10233

**Pull request closed without merging**
