### PR TITLE
Backport PR #34458 on branch 1.0.x (CLN: Clean csv files in test data GH34427)

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref #34458

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@simonjayhawkins do you have time one of those days to do a 1.0.5 release?

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins do you have time one of those days to do a 1.0.5 release?

can do. do we want to include anything else, wait a few weeks before doing the release and see if anything else surfaces or just get a patch release done with the S3 changes?

**Comment by jorisvandenbossche** [comment]
I would personally just do a patch release with the S3 changes, and not wait a few weeks with that. But maybe open a RLS issue for it?

**Comment by jreback** [comment]
agree would just do the revert of the single issue

**Pull request merged**
