### PR TITLE
Removed unnecessary depends arguments in setup.py

### PR DESCRIPTION
**Pull request by WillAyd**
The point of a dependency in build systems is to declare that target X needs to be built before target Y. We use the depends keyword a lot, but list source files as the dependency. This is best case a no-op as we don't build source files, in the worst case these add complexity to the current and future build systems

### CODE REVIEW

**Comment by WillAyd** [comment]
@lithomas1

**Comment by jbrockmendel** [comment]
@WillAyd can you re-push to get circleci to run

**Comment by jbrockmendel** [comment]
@lithomas1 thoughts here?  you've been doing a lot of build-related work lately

**Comment by lithomas1** [comment]
Does modifying a header still trigger a rebuild?

**Comment by WillAyd** [comment]
Ah that's a good point @lithomas1 and something I overlooked. We can just table this for now - hopefully the meson stuff won't be too far off anyway

**Pull request closed without merging**
