### PR TITLE
WEB: add mastodon links

### LINKED ISSUE #52914: WEB: add links to the official mastodon account
It's been a [few months since](https://twitter.com/pandas_dev/status/1592479891496534016) you folks started your [mastodon account](https://fosstodon.org/@pandas_dev). How's that been going? If it's going well, I suggest that it should be bumped up in visibility.

It would be nice to add links to the account on the various pandas web sites. Here are spots I know about:
- Upper right of https://pandas.pydata.org/pandas-docs/stable/
- Bottom right of all pages at https://pandas.pydata.org/
- "Follow us" section on right of the home page at https://pandas.pydata.org/

Additionally, it would be nice to verify that your mastodon account is the official one, by proving that it is blessed by the pandas website (this is the [verification](https://joinmastodon.org/verification) that mastodon offers):
- Add the following to the `<head>` portion of the [home page](https://pandas.pydata.org/): `<link rel="me" href="https://fosstodon.org/@pandas_dev"/>` (and/or add `rel="me"` to the links you add above)
- On your mastodon account, add a profile metadata link back to the home page.

### PR DESCRIPTION
**Pull request by mikix**
- [x] closes #52914
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Sidebar:
Screenshot from 2023-04-26 22-24-40

Footer:
image

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @mikix 

Any reason to have this PR as a draft? Can it be merged already?

**Comment by datapythonista** [comment]
> /preview

There was a problem with the GitHub token and previews of the last couple of days aren't available. It should be fixed now, the preview for this PR should be available when the CI rerun finishes.

**Comment by mikix** [comment]
@datapythonista it _could_ be, but I had some ideas around ordering:

In the api docs, the Twitter & mastodon links are currently in a different order than I put them on the web site. And the Twitter image is a (imo) distractingly bright blue — I was toying with unifying the order and appearance of the links in the api docs.

But it has been fairly difficult to build them!

Anyway, you can merge this if you like - I think it works OK — but I hadn’t just finished all my due diligence.

**Comment by datapythonista** [comment]
Sure, no rush, I was just wondering if there was a reason.

If it makes your life easier, we can also merge this now and you can work on those in a separate PR. But surely fine to continue here if you prefer.

**Comment by mikix** [comment]
Yeah you're right - this can be done incrementally - the current state is fine. I ran into another issue building the api docs, but I was able to confirm at least that the mastodon icon showed up. So this is good from my end. Will mark as ready.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @mikix

**Pull request merged**
