### PR TITLE
DOC: Fix EX02 in pandas.Index.get_loc

### PR DESCRIPTION
**Pull request by farhanreynaldo**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Related to #27977. 

```
################################################################################
################################## Validation ##################################
################################################################################

5 Errors found:
        No extended summary found
        Parameter "key" has no description
        The first line of the Returns section should contain only the type, unless multiple values are being returned
        Return value has no description
        See Also section not found
```

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks @farhanreynaldo 

In the future I think it would help to also post the output of
```
python scripts/validate_docstrings.py pandas.Index.get_loc
```

which here is

```
################################################################################
################################## Validation ##################################
################################################################################

5 Errors found:
        No extended summary found
        Parameter "key" has no description
        The first line of the Returns section should contain only the type, unless multiple values are being returned
        Return value has no description
        See Also section not found
```

to show that the doctests now pass

**Comment by MarcoGorelli** [comment]
Also, adding 
```
xref #27977
```
to the pull request description would be good

**Comment by farhanreynaldo** [comment]
> Thanks @farhanreynaldo
> 
> In the future I think it would help to also post the output of
> 
> ```
> python scripts/validate_docstrings.py pandas.Index.get_loc
> ```
> 
> which here is
> 
> ```
> ################################################################################
> ################################## Validation ##################################
> ################################################################################
> 
> 5 Errors found:
>         No extended summary found
>         Parameter "key" has no description
>         The first line of the Returns section should contain only the type, unless multiple values are being returned
>         Return value has no description
>         See Also section not found
> ```
> 
> to show that the doctests now pass

Thank you for the reminder, @MarcoGorelli, I will add it next time.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Great thanks @farhanreynaldo for PR and @MarcoGorelli for review

**Pull request merged**
