### PR TITLE
CI/TST Removed Timestamp.now() from tests. #44341

### PR DESCRIPTION
**Pull request by Mikhaylov-yv**
Removed Timestamp.now() from tests. #44341

Replaced Timestamp.now () with pd.Timestamp (2021, 1, 1, 12)

### CODE REVIEW

**Comment by jreback** [comment]
@Mikhaylov-yv does this cover *all* the uses in the tests (aside from specifically testing .now()?)

can you merge master.

also wouldn't object to a rule against using Timestamp.now() in testing (exempting the very few cases that we need it); this could be a followup or in this PR

**Comment by jreback** [comment]
cc @mroeschke

**Review by mroeschke — COMMENTED** [review]
LGTM pending green. Looks like there's a few more occurrences that can be addressed in another PR.

**Comment by Mikhaylov-yv** [comment]
Hello @jreback.

In these tests, `Timestamp (2021, 1, 1, 12)` is suitable as a replacement for `Timestamp.now ()`. Did I understand correctly?
In order not to duplicate the code, can I make a `Timestamp (2021, 1, 1, 12)` as a fixture?

Using this example, I wanted to make sure that I was doing it right.

If everything is OK. I will make corrections to all tests where there is a  `Timestamp.now ()`. Of course other than those checking the `Timestamp.now ()`.

**Comment by mroeschke** [comment]
>  In order not to duplicate the code, can I make a Timestamp (2021, 1, 1, 12) as a fixture?

Good idea. A new `fixed_now_ts` fixture would be helpful. Maybe also add minutes, seconds and microseconds to the fixture Timestamp just in case it was significant.

Also not mentioned in the original issue, but this also applies to `utcnow` where the original method isn't being tested.

**Comment by jreback** [comment]
thanks @Mikhaylov-yv happy to have you followup with a fixture for the 'now' tests.

**Comment by Mikhaylov-yv** [comment]
@jreback Thanks for the support.  I keep working on the problem.

**Pull request merged**
