### PR TITLE
BUG: Read CSV on python engine fails when skiprows and chunk size are specified (#55677, #56323) 

### LINKED ISSUE #55677: BUG: TextFileReader from read_csv() fails to iterate when using a callable skiprows and engine='python'
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

# write a csv file to read with read_csv()
dummy_csv = """col_a
10
20
30
40"""

with open("dummy.csv", "w") as file:
    file.write(dummy_csv)

# fetch a TextFileReader to iterate through the file chunk by chunk
text_file_reader = pd.read_csv("dummy.csv",
                               skiprows=lambda row: False,
                               engine='python',
                               chunksize=3)

with text_file_reader as reader:
    iterator = iter(reader)
    next(iterator)  # TypeError: 'function' object is not iterable
```

### Issue Description

A TypeError is raised when iterating through a TextFileReader that was returned by read_csv() using a callable skiprows argument and the python parsing engine.

Making any one of the following changes to the read_csv() arguments causes this code example to successfully complete without raising an error:
- Setting skiprows=None
- Setting skiprows=[]
- Setting skiprows=[1]
- Setting engine='c'

### Expected Behavior

This code example should complete without printing any output or raising any error.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 6.2.0-35-generic
Version             : #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.1
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.3
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : 1.3.5
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : 2.8.7
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
None

</details>

### LINKED ISSUE #56323: BUG: Python Engine does not respect chunksize when skiprows is specified as a nonempty list.
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from io import StringIO

import pandas as pd

import pandas as pd
csv = """col_a
0
1
2
3
4
5
6
7
8
9"""

text_file_reader = pd.read_csv(StringIO(csv),
                               engine='python',
                               skiprows=[1, 2, 3, 7, 10],
                               chunksize=2)
with text_file_reader as reader:
    for chunk in iter(reader):
        print(chunk)
```

### Issue Description

```
   col_a
0      3
1      4
   col_a
2      5
3      7
4      8
```
Pandas returns a chunk of size 3 even though read_csv requests chunks of at most size=2.  

Note: this behavior only occurs when both skiprows and chunksize are specified and skiprows is a non-empty list.

### Expected Behavior

```
   col_a
0      3
1      4
   col_a
2      5
3      7
   col_a
4      8
```
The python engine provides chunks of at most size=2 when the parameter is specified with a nonempty list skiprows (mirroring c engine behavior).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 0e2277b443bad28c798b36e2db2ebcab84ad8811
python              : 3.10.13.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.0.0
Version             : Darwin Kernel Version 23.0.0: Thu Aug 17 21:24:46 PDT 2023; root:xnu-10002.1.11~3/RELEASE_ARM64_T6020
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : None.UTF-8

pandas              : 2.2.0.dev0+536.g0e2277b443
numpy               : 1.24.4
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : 3.0.5
pytest              : 7.4.3
hypothesis          : 6.88.3
sphinx              : 6.2.1
blosc               : None
feather             : None
xlsxwriter          : 3.1.9
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : 1.4.6
psycopg2            : 2.9.7
jinja2              : 3.1.2
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
dataframe-api-compat: None
fastparquet         : 2023.10.1
fsspec              : 2023.10.0
gcsfs               : 2023.10.0
matplotlib          : 3.7.3
numba               : 0.57.1
numexpr             : 2.8.7
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 14.0.0
pyreadstat          : 1.2.4
python-calamine     : None
pyxlsb              : 1.0.10
s3fs                : 2023.10.0
scipy               : 1.11.3
sqlalchemy          : 2.0.23
tables              : 3.9.1
tabulate            : 0.9.0
xarray              : 2023.10.1
xlrd                : 2.0.1
zstandard           : 0.22.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

### PR DESCRIPTION
**Pull request by Flytre**
-Added support for the python parser to handle using skiprows and chunk_size options at the same time to ensure API contract is met.

-Added a regression test to ensure this #55677 can be quickly caught in the future if it reappears.

-Fixed a flawed test case that now screens for #56323 regressions.

- [✅ ] closes #55677 (Replace xxxx with the GitHub issue number)
- [✅ ] closes #56323 (Replace xxxx with the GitHub issue number)
- [✅] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [✅] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [✅] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [✅] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by Flytre** [comment]
pre-commit.ci autofix

**Review by WillAyd — COMMENTED** [review]
minor comments but I think this looks pretty reasonable. thanks!

**Comment by mattharrison** [comment]
Does this support the pyarrow engine as well?

**Comment by Flytre** [comment]
> Does this support the pyarrow engine as well?

pyarrow doesn't support chunksize, so it shouldn't be affected at all. only modifying the python engine, which is the one with incorrect behavior right now.

**Comment by Flytre** [comment]
pre-commit.ci autofix

**Comment by Flytre** [comment]
Passes test, looking for feedback / to merge at this point.

**Review by WillAyd — APPROVED** [review]
lgtm @mroeschke any thoughts?

**Comment by mattharrison** [comment]
Would love to see pyarrow support for this

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Flytre

**Pull request merged**
