### PR TITLE
BUG: consistent datetime display format with < ms #10170

### LINKED ISSUE #10170: Display of a datetime column/index with both second and sub-second resolution
Should a datetime column should use the same precision for all, padding with zeros, just like a float column does?

```
In [121]: df = pd.DataFrame({'datetime': pd.date_range('1/1/2000 09:00:00', freq="5ms",periods=10), 'float': np.arange(0,0.05,0.005)})

In [122]: df
Out[122]:
                    datetime  float
0        2000-01-01 09:00:00  0.000
1 2000-01-01 09:00:00.005000  0.005
2 2000-01-01 09:00:00.010000  0.010
3 2000-01-01 09:00:00.015000  0.015
4 2000-01-01 09:00:00.020000  0.020
5 2000-01-01 09:00:00.025000  0.025
6 2000-01-01 09:00:00.030000  0.030
7 2000-01-01 09:00:00.035000  0.035
8 2000-01-01 09:00:00.040000  0.040
9 2000-01-01 09:00:00.045000  0.045
```

so that the first row would show `2000-01-01 09:00:00.000000`?

### PR DESCRIPTION
**Pull request by jreback**
closes #10170

```
In [3]: Series(date_range('20130101 09:00:00',periods=5,freq='D'))
Out[3]: 
0   2013-01-01 09:00:00
1   2013-01-02 09:00:00
2   2013-01-03 09:00:00
3   2013-01-04 09:00:00
4   2013-01-05 09:00:00
dtype: datetime64[ns]

In [4]: Series(date_range('20130101 09:00:00',periods=5,freq='s'))
Out[4]: 
0   2013-01-01 09:00:00
1   2013-01-01 09:00:01
2   2013-01-01 09:00:02
3   2013-01-01 09:00:03
4   2013-01-01 09:00:04
dtype: datetime64[ns]

In [2]: s = Series(date_range('20130101 09:00:00',periods=5,freq='ms'))

In [3]: s.iloc[1] = np.nan

In [4]: s
Out[4]: 
0   2013-01-01 09:00:00.000
1                       NaT
2   2013-01-01 09:00:00.002
3   2013-01-01 09:00:00.003
4   2013-01-01 09:00:00.004
dtype: datetime64[ns]

In [6]: Series(date_range('20130101 09:00:00',periods=5,freq='us'))
Out[6]: 
0   2013-01-01 09:00:00.000000
1   2013-01-01 09:00:00.000001
2   2013-01-01 09:00:00.000002
3   2013-01-01 09:00:00.000003
4   2013-01-01 09:00:00.000004
dtype: datetime64[ns]

In [7]: Series(date_range('20130101 09:00:00',periods=5,freq='N'))
Out[7]: 
0   2013-01-01 09:00:00.000000000
1   2013-01-01 09:00:00.000000001
2   2013-01-01 09:00:00.000000002
3   2013-01-01 09:00:00.000000003
4   2013-01-01 09:00:00.000000004
dtype: datetime64[ns]
```

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Thanks!

Does it make sense to also have the 'milliseconds' resolution? (the third example above, so up to 3 decimals after the comma) instead of at once microsecond

**Comment by jreback** [comment]
@jorisvandenbossche fixed up for 'ms'. updated the top.

**Comment by jorisvandenbossche** [comment]
Nice!

**Comment by jreback** [comment]
@jorisvandenbossche look ok?

**Comment by jorisvandenbossche** [comment]
yes!

**Pull request merged**
