### PR TITLE
API: Avoid returning same object for various methods

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @jorisvandenbossche

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
We should note this as an API change, I think (which it strictly speaking is), but personally I think that would be a good change for 2.0. It would be nice to have the general rule that a method that _typically_ returns a new series/dataframe never returns `self`, even if no changes were needed.

**Review by jbrockmendel — APPROVED** [review]
needs whatnsew per joris's suggestion, otherwise LGTM

**Comment by phofl** [comment]
Added a note

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
