### PR TITLE
DOC: DataFrame Properties

### PR DESCRIPTION
**Pull request by gambogi**
Added explanations for `axes` and `shape`

### CODE REVIEW

**Comment by jreback** [comment]
could  you reconcile this with the same properties in ``core/series.py``, & ``core/generic.py`` (we would normally use the ``Appender`` decorator, but I don't think it works on properties.

Just want to make sure that these descriptions are all consistent.

**Comment by gambogi** [comment]
Updated with changes.

**Comment by jreback** [comment]
pls squash, otherwise looks good.

**Comment by jreback** [comment]
can you rebase/squash.

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/873bbc2ada4f37a51a397cdb3bf3301e522dd236

**Pull request closed without merging**
