### PR TITLE
Convert badge list into Markdown table in README.md

### PR DESCRIPTION
**Pull request by gliptak**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master | flake8 --diff`
- [ ] whatsnew entry

Also correct some badge links

### CODE REVIEW

**Comment by jreback** [comment]
@gliptak can you past a screen shot of what this looks like.

**Comment by shoyer** [comment]
@jreback  see https://github.com/gliptak/pandas/blob/patch-1/README.md

screenshot from 2016-03-29 13 19 18

There seems to be a visual glitch at the top of the table

**Comment by jreback** [comment]
oh, so this is equiv of the html that we had before (which I ripped off).

what is the glitch?

**Comment by gliptak** [comment]
I corrected several of the links.

**Comment by shoyer** [comment]
If we can't have an empty table header in markdown, I would stick with HTML.

**Comment by gliptak** [comment]
How about a title (Description/Badge)? Or just have them in a row like most projects do:
https://github.com/xmlrunner/unittest-xml-reporting
https://github.com/kennethreitz/requests

**Comment by jreback** [comment]
I think the rows are bad looking
much prefer he table

**Comment by jreback** [comment]
let's leave the existing. of course if a markdown version is better (but preserves the structure), then pls re-open.

**Pull request closed without merging**
