### PR TITLE
Patch for pandas.core.computation.eval with str/byte ndarrays

### PR DESCRIPTION
**Pull request by sjdv1982**
Hello,
I am interested in using Pandas as a numexpr replacement, since its eval/query syntax is much cleaner. However, it doesn't quite work for me, since I rely on byte ndarrays, and I want to avoid DataFrames. Here is an example script that shows the problems I had, and how they are solved in a patched version. I am not very used to open source projects, I hope my patch will be acceptable.

cheers

Sjoerd

### Example script

```python
import numpy as np
import numexpr as ne
from pandas import DataFrame
from pandas.core.computation.eval import eval as pd_eval

# Sample data
s = np.zeros(6, 'S5')
v = np.array([5,8,3,6,7,2])
s[:4] = "Test", "Test2", "Test", "Test"
s_u = np.array([ss.decode() for ss in s])  # s as unicode
dic = {"s": s, "v": v}
dic_u = {"s": s_u, "v": v}


print("Golden standard (numexpr with ugly syntax)\t", ne.evaluate("(s == 'Test') & (v > 3)", dic))

df = DataFrame(dic)
print("df with bytes (wrong)\t\t\t\t", df.eval("s == 'Test' and v > 3").values)
try:  # ugly syntax AND does not work
    print(df.eval("s == b'Test' and v > 3").values)
except AttributeError:
    print("*" * 50)
    import traceback; traceback.print_exc(0)
    print("*" * 50)

df = DataFrame(dic_u)
print("df with unicode (works)\t\t\t\t", df.eval("s == 'Test' and v > 3").values)


from pandas.core.computation.eval import eval as pd_eval
print("pd_eval with bytes (wrong)\t\t\t", pd_eval("s == 'Test' and v > 3", global_dict=dic))
print("pd_eval with unicode (wrong)\t\t\t", pd_eval("s == 'Test' and v > 3", global_dict=dic_u))

print("patched pd_eval with bytes (works)\t\t", pd_eval("s == 'Test' and v > 3", global_dict=dic, align_result=False, str_as_bytes=True))
print("patched pd_eval with unicode (works)\t\t", pd_eval("s == 'Test' and v > 3", global_dict=dic_u, align_result=False, str_as_bytes=True))
```

### Output
```
Golden standard (numexpr with ugly syntax)       [ True False False  True False False]
df with bytes (wrong)                            [False False False False False False]
**************************************************
Traceback (most recent call last):
AttributeError: 'PandasExprVisitor' object has no attribute 'visit_Bytes'
**************************************************
df with unicode (works)                          [ True False False  True False False]
pd_eval with bytes (wrong)                       [False False False False False False]
pd_eval with unicode (wrong)                     [False False False False False False]
patched pd_eval with bytes (works)               [ True False False  True False False]
patched pd_eval with unicode (works)             [ True False False  True False False]
```

### CODE REVIEW

**Review by sjdv1982 — COMMENTED** [review]
Forgot the docstring for "str_as_bytes":
https://github.com/sjdv1982/pandas/commit/051ac83801107f761a92a655f74f8b19756e1df4

**Comment by jreback** [comment]
w/o tests this would not be acceptable. However, we do not deal with raw ndarray's at all as input here to ``.eval()``; so this is creaping out of scope. We have removed similar handling for all top-level pandas routines, so -1 on adding this back.

**Comment by sjdv1982** [comment]
So If I understand correctly: for the Pandas project, ```core.computation.eval``` is meant for only DataFrames and Series in its global/local dict? If I want to use it for something else, I should spin it off?

**Comment by sjdv1982** [comment]
> > So If I understand correctly: for the Pandas project, core.computation.eval is meant for only DataFrames and Series in its global/local dict? If I want to use it for something else, I should spin it off?
> 
> not really sure what you are attempting to do in the first place.

Instead of this (ugly):

```numexpr.evaluate("(s == 'Test') & (v > 3)", dic))```

I want this (clean):

```pd_eval("s == 'Test' and v > 3", dic)```

**Comment by jreback** [comment]
@sjdv1982 again I am not sure what you are actually trying to do. pls show a complete example.

**Comment by sjdv1982** [comment]
> @sjdv1982 again I am not sure what you are actually trying to do. pls show a complete example.

[This](https://github.com/sjdv1982/struclib/blob/master/tests/viewer.ipynb). 

I am building a molecular viewer, and I want users to be able to use [clean selection syntax](https://pymolwiki.org/index.php/Selection_Algebra), no bitmasks.

**Pull request closed without merging**
