### PR TITLE
CI: Moving CI dependencies to "ci/deps"

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] refs #23115
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

@jreback you were +0 on this, do you want to take a look? Also @TomAugspurger and @jbrockmendel

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]
\+1 I think this greatly improves navigating in this directory. 

I wanted to suggest one subdir per CI provider (so eg putting all env yaml files in `/ci/azure`, `/ci/circle/` etc), but I see there are already yaml files for config in `ci/azure`, so that will probably make is more confusing to mix env and config yaml files. And since we use consistent suffix, putting them all in one directory is fine as well (and the positive side is that they are all in one place).

**Comment by jreback** [comment]
looks good. need a clean run though, not sure what is failing.

**Comment by datapythonista** [comment]
I didn't see that one, thanks for pointing out, I couldn't find the error. Changed now.

**Comment by TomAugspurger** [comment]
I think all green @datapythonista are the failures at https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=2559&view=results what we have on master right now?

**Comment by datapythonista** [comment]
I haven't seen those errors before. But I think this is the last build of master, and they are there too: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=2565&view=results

**Comment by TomAugspurger** [comment]
k. feel free to merge this then. I'll open an issue and investigate.

**Comment by TomAugspurger** [comment]
I think that https://github.com/pandas-dev/pandas/pull/23454 is fixing this.

**Comment by alimcmaster1** [comment]
Yes they are on master - this PR here fixes them and also address the issue that build status does not go red when tests fail - #23454

**Pull request merged**
