### PR TITLE
PERF: improves SeriesGroupBy.nunique performance

### LINKED ISSUE #10820: nunique performance for groupby with large number of groups
It looks like `len(set)` beats both `len(np.unique)` and `pd.Series.nunique` if done naively -- here's an example with a large number of groups where we try to compute unique counts of a column when grouping by another column:

```python
>>> df = pd.DataFrame({'a': np.random.randint(10000, size=100000),
                       'b': np.random.randint(10, size=100000)})
>>> g = df.groupby('a')

>>> %timeit g.b.nunique()
1 loops, best of 3: 1 s per loop

>>> %timeit g.b.apply(pd.Series.nunique)
1 loops, best of 3: 992 ms per loop

>>> %timeit g.b.apply(lambda x: np.unique(x.values).size)
1 loops, best of 3: 652 ms per loop

>>> %timeit g.b.apply(lambda x: len(set(x.values)))
1 loops, best of 3: 469 ms per loop
```

The fastest way I know to accomplish the same thing is this:
```python
>>> g = df.groupby(['a', 'b'])

>>> %timeit g.b.first().groupby(level=0).size()
100 loops, best of 3: 6.2 ms per loop
```
... which is a *LOT* faster apparently.

Wonder if something similar could be done in `GroupBy.nunique` since it's quite a common use case?

### PR DESCRIPTION
**Pull request by behzadnouri**
closes https://github.com/pydata/pandas/issues/10820

on master:

``` ipython
In [2]: df = pd.DataFrame({'a': np.random.randint(10000, size=100000),
   ...:                    'b': np.random.randint(10, size=100000)})

In [3]: %timeit df.groupby('a')['b'].nunique()
1 loops, best of 3: 1.66 s per loop

In [4]: %timeit df.groupby(['a', 'b'])['b'].first().groupby(level=0).size()
10 loops, best of 3: 36.3 ms per loop
```

on branch:

``` ipython
In [2]: %timeit df.groupby('a')['b'].nunique()
10 loops, best of 3: 29.2 ms per loop
```

### CODE REVIEW

**Comment by behzadnouri** [comment]
benchmarks:

```
-------------------------------------------------------------------------------
Test name                                    | head[ms] | base[ms] |  ratio   |
-------------------------------------------------------------------------------
groupby_ngroups_10000_nunique                |   6.8550 | 1701.2453 |   0.0040 |
groupby_ngroups_100_nunique                  |   0.5283 |  18.2413 |   0.0290 |
-------------------------------------------------------------------------------
Test name                                    | head[ms] | base[ms] |  ratio   |
-------------------------------------------------------------------------------

Ratio < 1.0 means the target commit is faster then the baseline.
Seed used: 1234

Target [091c73d] : PERF: improves SeriesGroupBy.nunique performance
Base   [54f02df] : COMPAT: value_counts always return int64 dtype, xref #10876
```

**Comment by jreback** [comment]
@behzadnouri looks great. can you add a benchmark as well. ping when green.

**Comment by behzadnouri** [comment]
@jreback there already are 2 benchmarks

**Comment by jreback** [comment]
oh, right, ok then.

**Comment by jreback** [comment]
@behzadnouri thanks!

**Comment by aldanor** [comment]
That's awesome, sort of what I was thinking about but didn't have time to hack together :/ Thanks @behzadnouri!

**Pull request merged**
