### PR TITLE
BUG: tests that can't fail

### PR DESCRIPTION
**Pull request by stephenpascoe**
tm.equalContent does not raise an exception, it returns a Bool.  Therefore these tests need wrapping in self.assertTrue()

### CODE REVIEW

**Comment by jreback** [comment]
maybe better to make this ``assertEqualContents`` (e.g. rename and put the assert in ``utils/testing.py``)

**Comment by jreback** [comment]
does this have a specific issue associated?

**Comment by jorisvandenbossche** [comment]
No, he just discovered it now while looking at the code

**Comment by jreback** [comment]
@stephenpascoe can you update this?

**Comment by jreback** [comment]
closing, but if you would like to continue working on this pls reopen

**Pull request closed without merging**
