### PR TITLE
DEPR: Deprecate try_sort

### PR DESCRIPTION
**Pull request by charlesdong1991**
xref #33336 

While working on another PR, and @WillAyd brought up `try_sort`, and after a quick look, I don't think `try_sort` is needed in that check method in `indexes/api.py`. (I also dont think it is right to have try_sort there), so deprecate it.

### CODE REVIEW

**Comment by jreback** [comment]
yep this is fine, ping on green.

**Comment by charlesdong1991** [comment]
this one needs to wait until #33336 gets merged, since `try_sort` is still being used on master. @jreback 

I will leave it as WIP for now and then rebase once okay.

**Comment by WillAyd** [comment]
Can you merge master on this?

**Comment by charlesdong1991** [comment]
ping @WillAyd @jreback

**Comment by jreback** [comment]
thanks @charlesdong1991

**Pull request merged**
