### PR TITLE
CLN: rename lib.isscalar to lib.is_scalar

### LINKED ISSUE #18987: CLN: rename lib.isscalar to lib.is_scalar
https://github.com/pandas-dev/pandas/pull/18982#issuecomment-354452699

also remove direct calling of ``lib.isscalar`` directly, rather it should be called from ``pandas.core.dtypes.common`` like all other inference functions.

### PR DESCRIPTION
**Pull request by databasedav**
- [x] closes #18987
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

There's also a handful of methods which call `is_scalar` that are named `isscalar`, e.g.:
https://github.com/pandas-dev/pandas/blob/84335621ad0a0d83302a80b6911d3985c00b5cee/pandas/core/computation/ops.py#L101-L103
should these be changed as well?

Also does a CLN require an entry in whatsnew?

### CODE REVIEW

**Comment by jbrockmendel** [comment]
+1. This has bothered me for a while.

**Comment by jreback** [comment]
you can change ``isscalar``  as you pointed above (and other instances as appropriate). making things more clear / consistent is the goal. don't need a whatsnew here as this is an internal change.

**Comment by jreback** [comment]
lgtm. note that windows is currently failing, but ping when travis ci is green.

**Comment by jreback** [comment]
thanks @gitavi

**Pull request merged**
