### PR TITLE
Revert 37 pins

### PR DESCRIPTION
**Pull request by TomAugspurger**
~second commit is temporary.~

Closes #27907 

cc @jjhelmus

### CODE REVIEW

**Comment by jbrockmendel** [comment]
what's the trigger condition for the "temporary" commit?

**Comment by TomAugspurger** [comment]
> what's the trigger condition for the "temporary" commit?

Those packages being uploaded to the defaults channel by Anaconda (tonight if all goes well).

**Comment by TomAugspurger** [comment]
We won't merge this with the second commit. Just testing to ensure there aren't any issues with the packages.

**Comment by TomAugspurger** [comment]
Everything seemed to pass using those packages. Reverting the channel commit, which will cause this to fail again. I'll re-run CI once they've been uploaded to defaults.

**Comment by jjhelmus** [comment]
Corrected Python 3.7.4 package are now in `pkgs/main`, CI should now pass if re-run.

**Pull request merged**
