### PR TITLE
Replaced open with Context Mgrs in Parser Tests

### LINKED ISSUE #21102: CI: Failure on Appveyor Master
https://ci.appveyor.com/project/pandas-dev/pandas/build/job/0y6fvce0al2yax06?fullLog=true#L1989

cc @WillAyd 

Maybe #21066 was related? Not sure how though. Looking now.

### PR DESCRIPTION
**Pull request by WillAyd**
Maybe closes #21102 and #19984, though if not should still work as a general cleanup

### CODE REVIEW

**Comment by alysivji** [comment]
Just did a search and there are a surprising number of non-context manager `open`s in the codebase. Is there a cleanup effort around this? Fix as you see them?

**Comment by WillAyd** [comment]
@alysivji are those using IO buffers or file handles? If the former I don't think it's a necessity. The latter should definitely be cleaned up

**Comment by jreback** [comment]
thanks @WillAyd 

if you can see if #21102 and #19984 are fixed would be great.

**Comment by WillAyd** [comment]
Is that validated by physically restarting the failed jobs associated with those?

**Comment by jreback** [comment]
yep - nothing to do now

**Pull request merged**
