### PR TITLE
DOC: strings longer than min_itemsize are not truncated

### PR DESCRIPTION
**Pull request by toobaz**
Fixed docs on min_itemsize

### CODE REVIEW

**Comment by toobaz** [comment]
Replaced by https://github.com/pydata/pandas/pull/12251 , https://github.com/pydata/pandas/pull/12252 , https://github.com/pydata/pandas/pull/12253

**Comment by toobaz** [comment]
Sorry, closed by mistake

**Comment by jreback** [comment]
this is just a doc change, but you are wanting to change the error, no?

**Comment by toobaz** [comment]
No, my intention (here) was indeed just to update the docs.
(The other open PR related to ``min_itemsize`` has not much to do with this.)

**Comment by toobaz** [comment]
(I think the current behaviour is the sane one, don't you?!)

**Comment by jreback** [comment]
ok why don't u update the doc string of append with an example as well then

**Comment by jreback** [comment]
thanks!

**Pull request closed without merging**
