### PR TITLE
DEPR: DataFrame(floaty, dtype=inty) match Series

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

xref #40110, though we may still deprecate the Series behavior too, in which case we'll need to update the deprecation message here

### CODE REVIEW

**Comment by jreback** [comment]
looks fine. some checks are failing

**Comment by simonjayhawkins** [comment]
release note?

**Comment by jreback** [comment]
hmm ci/checks failing, someting on the asvs?

**Comment by jreback** [comment]
and pls rebase

**Comment by jreback** [comment]
something failing on ci/ checks

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/pull/41770/checks?check_run_id=2732581481 is in the asv benchmarks

**Pull request merged**
