### PR TITLE
DOC: use black to fix code style in doc pandas-dev#36777

### PR DESCRIPTION
**Pull request by PrayagS**
Partially addresses #36777. Ran black on all the files under `doc/source/getting_started/comparison`.

### CODE REVIEW

**Review by dsaxton — APPROVED** [review]
Looks good, thanks @PrayagS

**Comment by dsaxton** [comment]
Actually may have approved too quickly, looks like there are some linting errors @PrayagS

**Comment by PrayagS** [comment]
Seems like the latest commit fixed all the linting errors. Please have a look again.

**Comment by PrayagS** [comment]
Sorry to bother again, but does this PR now count towards Hacktoberfest? It shows that it is under review but we know that it has been already reviewed and accepted. Do you need to add the `hacktoberfest-accepted` label? 

Source:
image

**Comment by dsaxton** [comment]
@PrayagS I'm not too familiar with how Hacktoberfest works, but I think you should be good since the PR was merged. As far as I can tell the Hacktoberfest label is optional (we don't have one).

**Comment by PrayagS** [comment]
So sorry to disturb again but Hacktoberfest has undergone some changes due to the excessive spamming that occurred this year. The rules for a PR to be accepted have been modified. You can read about it here: https://hacktoberfest.digitalocean.com/hacktoberfest-update

Here is the most important part for maintainers:

image

I can completely understand if pandas as an org doesn't do this but just notifying in case.

**Comment by dsaxton** [comment]
@PrayagS Ah, looks like we probably do need to add the hacktoberfest topic. Can you create an issue about that?

**Comment by PrayagS** [comment]
@dsaxton Done. #36837

**Pull request merged**
