### PR TITLE
CLN: D202 No blank lines allowed after function docstring

### PR DESCRIPTION
**Pull request by simonjayhawkins**
This one could conflict which the unchecked rule blank line before comment

### CODE REVIEW

**Comment by jbrockmendel** [comment]
im fine with this either way, seems harmless

**Comment by WillAyd** [comment]
Can you merge master?

**Comment by WillAyd** [comment]
@MomIsBestFriend is there supposed to be a code check for this? Vaguely recall that but may be wrong

**Review by WillAyd — APPROVED** [review]

**Comment by MomIsBestFriend** [comment]
@WillAyd If I recall correctly in ```scripts/validate_doctrings.py``` there's a check for that, but it's not integrated in the CI due to the fact that there's too many occurrences, and they never got fixed (until now)

---

cc @datapythonista

**Comment by WillAyd** [comment]
Sounds like we might not need the custom code check with work that @simonjayhawkins is doing, so great!

Thanks!

**Pull request merged**
