### PR TITLE
DOC: Removing duplicated ecosystem and roadmap in the docs

### PR DESCRIPTION
**Pull request by datapythonista**
The roadmap and ecosystem pages were moved to the website, but left in the docs initially. This removes the duplicated files in the docs.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Did we reach a conclusion on the call yesterday?

IIRC, @jorisvandenbossche preferred keeping the contributing guide in the docs and linking to the dev version from the website. I think that's my preference.

No strong preference on the roadmap.

**Comment by datapythonista** [comment]
My understanding is that it was already decided that ecosystem and roadmap were moved to the web, and it was just pending removing the doc version.

Yesterday's discussion was about the contributing page, if I didn't misuderderstand.

But let's double check that everybody is happy with this before moving forward.

**Comment by datapythonista** [comment]
@jorisvandenbossche is this ok, or is the discussion on where the ecosystem and roadmap go open?

Would be good to get rid of one of the copies before we make changes to them.

**Comment by datapythonista** [comment]
Any further comment here? If there is no agreement on this I'll just close and let someone else take care of this.

**Comment by jorisvandenbossche** [comment]
Sorry for the slow reply here. And yes, the discussion on the call was mainly about the contributor docs, not the roadmap/ecosystem.

I personally have a slight preference for keeping the roadmap together with all other development/contributing related information. But, if that decision was taken and that's the preference of most, I also don't want to reopen this (so in that case, go ahead with this), it's no strong preference (sorry, I honestly don't remember any more what decision we exactly took on this before in the initial web PR). 

The ecosystem seems fine to have on the website. In any case in the current docs it's also a bit "lost" somewhere. I actually removed it from the top navigation bar, because I didn't feel it belonged in the first-level navigation, so it's currently "orphaned".

**Comment by datapythonista** [comment]
No decision was taken, other than the PR that added those pages to the website.

My view was that to avoid linking the dev version of the docs was important. That was the main reason why I didn't use sphinx for the website, but a separate static site generator. My plan was to have everything that we want users to see the version from master in the website.

Since this is finally not happening, I don't have a preference on where to have things.

But I thing we shouldn't keep two versions for long, when there are changes to those pages it'll start to be tricky and time consuming to find differences and keep the updated content in the page that finally stays. 

Closing this for now, but I thing would be good if you can make a decision soon.

**Pull request closed without merging**
