### PR TITLE
BUG: Executing SQL containing non-escaped percent sign fails without parameters

### PR DESCRIPTION
**Pull request by john-bodley**
- [x] closes https://github.com/pandas-dev/pandas/issues/34211
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @john-bodley for the PR. can you add a note to doc\source\whatsnew\v1.1.0.rst. Does this also close #11896?

**Comment by john-bodley** [comment]
@simonjayhawkins I added the node per your request. Also per https://github.com/pandas-dev/pandas/issues/34211#issuecomment-629831983 I'm uncertain whether this closes https://github.com/pandas-dev/pandas/issues/11896.

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by mroeschke** [comment]
> I'm uncertain whether this closes #11896

If you're open to it @john-bodley, maybe you could add a unit test for #11896 to see if it passes out CI. Then we could close that issue

**Comment by john-bodley** [comment]
@mroeschke it seems that this PR doesn't resolve https://github.com/pandas-dev/pandas/issues/11896 for PostgreSQL per the following CI error ([job](https://travis-ci.org/github/pandas-dev/pandas/jobs/688918383)) when I added a unit test:

```
self = <sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x7f7a36467828>
cursor = <cursor object at 0x7f7a375b4e58; closed: -1>
statement = 'INSERT INTO test_frame1 (index, "%%A") VALUES (%(index)s, %(%A)s)'
parameters = {'%A': 1, 'index': 0}
context = <sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2 object at 0x7f7a363fc5c0>
    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       psycopg2.ProgrammingError: incomplete placeholder: '%(' without ')'
```

**Comment by mroeschke** [comment]
Thanks for checking @john-bodley. Your PR looks good otherwise

**Review by mroeschke — APPROVED** [review]

**Comment by WillAyd** [comment]
Looks like some test failures - @john-bodley can you take a look?

**Comment by WillAyd** [comment]
@john-bodley can you fix merge conflict?

**Comment by john-bodley** [comment]
@WillAyd done.

**Comment by WillAyd** [comment]
Awesome - thanks for the great PR @john-bodley

**Pull request merged**
