### PR TITLE
DOC: Fixed all remaining GL02 documentation errors and added appropriate check in CI

### PR DESCRIPTION
**Pull request by fshi01**
- Closes #42809
- Adds check for GL02 in CI

### CODE REVIEW

**Comment by jreback** [comment]
there is a precommit failure

**Comment by fshi01** [comment]
The pre-commit error is now fixed. The remaining errors stem from test_nat_doc_strings, which tests overlapping methods for matching docstrings. 

In order to fix the remaining GL02 docstring errors, I had to overwrite the docstring for two methods from the parent class. In order to fix these two errors, the docstrings will not match. How should I proceed?

**Comment by jreback** [comment]
right you will have to add these same methods to NaT (possibly adjusting the text)

**Review by MarcoGorelli — APPROVED** [review]
As far I can tell, the issue is that the docstring from `datetime` doesn't conform to the requirements? If so, this looks good to me

**Comment by jreback** [comment]
thanks @fshi01 very nice!

**Pull request merged**
