### PR TITLE
DataFrame/Series at set value test GH#30649

### LINKED ISSUE #30649: dtype does not get set to object when adding column with df.at[...] = ['some list']
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame(data={'a':[0,0]})
# df['b'] = None
# df['b'] = df['b'].astype('object')
df.at[0, 'b'] = ['a']
df.at[1, 'b'] = ['a']

>>> df
   a    b
0  0    a
1  0  [a]
```
#### Problem description

df.at[0, 'b'] should be ['a'] instead of 'a'.
I understand that it does not work when while adding the column but it feels inconsistent anyways.
When adding line 2 and 3 it works as expected.

#### Expected Output
```python
>>> df
   a    b
0  0  [a]
1  0  [a]
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.18.0
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.2
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

### PR DESCRIPTION
**Pull request by liang3zy22**
- [ ] closes #30649 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Comment by topper-123** [comment]
Hi @liang3zy22 thanks for the PR!

By running the example code in #30649 in the main branch, It seems we still get the errononous behavior, do you agree, i.e. this PR doesn't close that issue?

**Comment by liang3zy22** [comment]
Oh, so 30649 is not fixed. My codes just tested what it behaves now.

**Comment by topper-123** [comment]
Yes :-). Want to search for how to fix it?

**Comment by liang3zy22** [comment]
Yeah @topper-123 , please give me some info about how to fix this issue. I want to fix it.

**Comment by topper-123** [comment]
This may potentially not be so easy and it can take quite some time to for me also to figure out what need to be fixed here. So you need to either dig into this, or find some other issues you're interested in. Sorry. 

If you're interested in working on some other good starter issue, you can look into some of the issues at https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

If you decide you don't want to keep looking into this issue, can you close this PR.

**Pull request closed without merging**
