### PR TITLE
Deprecate inplace in Categorical.rename_categories

### PR DESCRIPTION
**Pull request by OlehKSS**
- [x] xref #37643
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
need to do `tm.assert_produces_warning` in some of the existing tests i think

**Comment by OlehKSS** [comment]
> need to do `tm.assert_produces_warning` in some of the existing tests i think

As far as I see, the failed CI task treats warnings as errors. I will check which tests should be changed

**Comment by jreback** [comment]
yeah pls assert the warning o nthe failing tests and ping on green

**Comment by OlehKSS** [comment]
@jbrockmendel @jreback 
I fixed the uncaught warning issues, all checks are green.

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jreback** [comment]
thanks @OlehKSS

**Pull request merged**
