### PR TITLE
MAINT: get rid of some compiler warnings

### PR DESCRIPTION
**Pull request by larsmans**
- uninitialized pointer
- unused variables
- unused function
- ISO C prototypes
- `cimport *`
- useless cast before `snprintf`

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks for looking into this.

What compiler are you using? I may have a chance to try it out with clang.

**Comment by larsmans** [comment]
GCC 4.7.

**Comment by jreback** [comment]
can you rebase this?

**Comment by larsmans** [comment]
@jreback done.

**Comment by jreback** [comment]
can you quantify I guess how many warnings this removed? (as obviously still lots)

**Comment by larsmans** [comment]
I don't know, four? The code has moved on since I wrote this patch and I have no idea how many new warnings were introduced.

**Comment by jreback** [comment]
this looks ok, but to be sure, can you rebase and push again?

**Comment by larsmans** [comment]
Green!

**Comment by jreback** [comment]
thanks!

**Pull request merged**
