### PR TITLE
DOC/DEPR: port pandas.rpy to rpy2 guide

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Addresses the doc part of #9602

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks for this. Thoughts on adding a section explaining *why* we're deprecating it? (no real maintainers, `rpy2` is better... I think there were some others).

**Comment by jorisvandenbossche** [comment]
Yes, indeed, good point. I was also thinking that, but in the end just wrote that it is "similar" functionality. 

I think the main reason is to "avoid duplication"? (having the same functionality in both pandas and rpy2 is not needed, and anyhow, those who used `pandas.rpy` were in fact already using ``rp2``) 
Saying that `rpy2` is better is not yet fully correct .. as there are still some things better in the pandas version to be ported (eg NaN handling, see the issue).

**Comment by TomAugspurger** [comment]
Similar is probably good enough. I just didn't read closely enough. :+1:

**Comment by ARF1** [comment]
@jorisvandenbossche I just stumbled across this PR in the CI Travis build queue and was wondering how one would convert a pandas dataframe to a R dataframe with `rpy2`. Any chance the docs could contain a minimal how-to for this very frequent use-case?

**Comment by jorisvandenbossche** [comment]
The `pandas2ri.py2ri` function as mentioned in the new docs in this PR (or even only doing `pandas2ri.activate()` will be enough). But I assumed knowledge of the existing functions, so this is equivalent to the `convert_to_r_dataframe`. 
But it would be nice to also have docs geared towards new users (who didn't know the old way). But let's say that is for another PR.

**Comment by jreback** [comment]
lgtm. merge when ready.

**Pull request merged**
