### PR TITLE
BUG: value_counts not preserving object dtype

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Seems likely to conflict with recent deprecation?

**Comment by phofl** [comment]
Which one?

**Comment by phofl** [comment]
Ah you mean #56161, hm yeah, that behaviour sucks

We can also just xfail those tests till 3.0

**Comment by lithomas1** [comment]
What's the plan here?

Anything we want for 2.1.4?

**Comment by phofl** [comment]
fixing in 3.0

**Pull request closed without merging**
