### PR TITLE
BUG/CLN: use more-correct isinstance check

### PR DESCRIPTION
**Pull request by jbrockmendel**
this is only kind of a bug, since the isinstance check still returns True on the `type(obj)`

### CODE REVIEW

**Comment by WillAyd** [comment]
Makes sense

> this is only kind of a bug, since the isinstance check still returns True on the `type(obj)`

So are there any code paths you could see hitting this?

**Comment by jbrockmendel** [comment]
Int64index.union(UInt64Index) I think goes through here, or the other way
around.

**Comment by jreback** [comment]
does this any tests?

**Comment by jbrockmendel** [comment]
> does this any tests?

no, it doesnt actually change any behavior

**Pull request merged**
