### PR TITLE
Install pyreadstat using conda instead

### PR DESCRIPTION
**Pull request by rs2**
```
> conda search pyreadstat -c conda-forge
Loading channels: done
# Name                       Version           Build  Channel
pyreadstat                     0.2.1  py36h301d43c_0  conda-forge
pyreadstat                     0.2.1  py37h301d43c_0  conda-forge
pyreadstat                     0.2.5  py36h301d43c_0  conda-forge
pyreadstat                     0.2.5  py37h301d43c_0  conda-forge
pyreadstat                     0.2.6  py36h301d43c_0  conda-forge
pyreadstat                     0.2.6  py37h301d43c_0  conda-forge
```

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Can you run `python scripts/generate_pip_deps_from_conda.py  ` too?

**Comment by rs2** [comment]
@TomAugspurger 👍

**Comment by marcelotrevisani** [comment]
related to https://github.com/pandas-dev/pandas/pull/27062

**Comment by TomAugspurger** [comment]
Thanks @rs2

**Comment by datapythonista** [comment]
The rest of the dependencies in that section are sorted alphabetically, if you want to resort in a follow up, that would keep things consistent.

**Pull request merged**
