### PR TITLE
BUG: parsing pyarrow dtypes corner case

### LINKED ISSUE #51225: BUG: dtype="int64[pyarrow]foobar[pyarrow]" fails to raise
```python
pd.Series(range(3), dtype="int64[pyarrow]foobar[pyarrow]")
```

In ArrowDtype.construct_from_string we do 

```
        if not string.endswith("[pyarrow]"):
            raise TypeError(f"'{string}' must end with '[pyarrow]'")
        if string == "string[pyarrow]":
            # Ensure Registry.find skips ArrowDtype to use StringDtype instead
            raise TypeError("string[pyarrow] should be constructed by StringDtype")
        base_type = string.split("[pyarrow]")[0]
```

But that does not rule out the case where there are multiple "[pyarrow]"s in the string.  This should raise.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #51225 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

pretty dumb corner case

### CODE REVIEW

**Review by phofl — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
release note? I think also should now target 2.1 now that rc is cut as this is not a 2.0.x regression or bugfix for a new feature.

**Comment by phofl** [comment]
Arrow support is more or less new, I think we can backport relevant fixes there

**Comment by simonjayhawkins** [comment]
wasn't pd.ArrowDtype was added in 1.5?

**Comment by phofl** [comment]
Yes, but support was very limited for arrow stuff in 1.5

**Comment by simonjayhawkins** [comment]
sure. it is experimental and this is not a big change so no objections to targeting 2.0

**Review by mroeschke — APPROVED** [review]
LGTM. Merged main once more but good for 2.0 IMO

**Comment by phofl** [comment]
thx @jbrockmendel

**Pull request merged**
