### PR TITLE
TST: test custom _formatter for ExtensionArray + revert ExtensionArrayFormatter removal

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/pandas-dev/pandas/pull/26833#issuecomment-502012046

@simonjayhawkins this would be a test for the `_formatter` functionality (it is passing on master before the removal of ExtensionArrayFormatter

Adds an actual test for EA._formatter + reverts https://github.com/pandas-dev/pandas/pull/26833 until we have a more complete solution for simplifying the formatters that take the EA._formatter into account.

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]

**Comment by jreback** [comment]
why revert this? it is just causing churn. it was clear that the change was just a step in fixing this. tests are ok.

**Review by jreback — CHANGES_REQUESTED** [review]
see comments

**Comment by jorisvandenbossche** [comment]
Did you read my comments in the PR? (https://github.com/pandas-dev/pandas/pull/26833#issuecomment-502012046) Then please give reasons why you would rather break the EA interface instead of temporarily reverting. We can fix issues with formatting in a better way in follow-up PRs. 

Without the revert, the test will fail, so I could only add a xfailed test.

**Comment by jreback** [comment]
> Did you read my comments in the PR? ([#26833 (comment)](https://github.com/pandas-dev/pandas/pull/26833#issuecomment-502012046)) Then please give reasons why you would rather break the EA interface instead of temporarily reverting. We can fix issues with formatting in a better way in follow-up PRs.
> 
> Without the revert, the test will fail, so I could only add a xfailed test.

I read your comment. I disagree.

**Comment by TomAugspurger** [comment]
I’d prefer not breaking things.

**Comment by jorisvandenbossche** [comment]
> I read your comment. I disagree.

Can you then please give some reasoning?

**Comment by jreback** [comment]
how is this breaking an existing test? it dud NOT. If you add something, then let's fix it. But reverting is kind of silly here. What to preserve some kind of history? this is just churning for no good reason.

**Comment by jorisvandenbossche** [comment]
Jeff, it only broke no tests because we forgot to properly test it. But what I am adding a test for here, has always been the *intention* of the `_formatter` method of the EA interface. And we for sure broke that.

**Comment by jreback** [comment]
> Jeff, it only broke no tests because we forgot to properly test it. But what I am adding a test for here, has always been the _intention_ of the `_formatter` method of the EA interface. And we for sure broke that.

EA._formatter is completely and utterly broken. Papering this over is not going to help. Let's just move forward. As I said I am happy to merge the test with an xfail.

**Comment by TomAugspurger** [comment]
Lets no break other libraries relying on the documented behavior.

**Comment by jorisvandenbossche** [comment]
> EA._formatter is completely and utterly broken.

This method was purposefully introduced recently as part of the EA interface: https://github.com/pandas-dev/pandas/pull/23601 (a PR that you approved, without calling it "utterly broken")

**Comment by jreback** [comment]
> Lets no break other libraries relying on the documented behavior.

and w/o a test that is useless. If you want to fix it go right ahead. But as I said reverting is just churn. Would rather actually fix this, which has been broken for forever. 

So this will be broken until then

**Comment by jreback** [comment]
> This method was purposefully introduced recently as part of the EA interface: #23601 (a PR that you approved, without calling it "utterly broken")

That's utterly ridiculous, I approve virtually PRs.

**Comment by jreback** [comment]
Actually IIRC I voiced many many arguments on how Index / EA repr's are completely different and you guys pushed it thru.

So if its broken , then please fix it.

merging to avoid this vacuous argument.

**Comment by jorisvandenbossche** [comment]
Thanks for merging. 

> IIRC I voiced many many arguments on how Index / EA repr's are completely different and you guys pushed it thru.

Yes, we had disagreements about that. But as a final thing, I want to note that this discussion is *not* about the difference between Index vs Series vs EA reprs, but about the simple fact that EAs need to control how their scalar values are represented in either of those reprs. That is a basic functionality we had from the beginning of the EA interface (even before we had the discussion about the default repr).

**Pull request merged**
