### PR TITLE
DOC: Fixed to_pickle compression argument list 'gzip' > 'gz'

### LINKED ISSUE #35364: DOC: `to_pickle` arguments for `compression` have a mistake (easy-fix)
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html

#### Documentation problem

`compression{‘infer’, ‘gzip’, ‘bz2’, ‘zip’, ‘xz’, None}, default ‘infer’` notes that `gzip` is a valid extension, this is wrong, the extension checked for is `gz`. The documentation for `to_csv` is correct with `... detect compression mode from the following extensions: ‘.gz’, ‘.bz2’, ‘.zip’ or ‘.xz’` and should act as a guide: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html

#### Suggested fix for documentation

`compression{‘infer’, ‘gz’, ‘bz2’, ‘zip’, ‘xz’, None}, default ‘infer’` to match the code implementation: https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/common.py#L223

There _may_ be an argument to extending the `_compression_to_extension` code to accept both `gzip` and `gz`for gzip compression, whoever reads this might decide this is worth escalating. For me making sure we fix the docs in line with the code is the priority.

### PR DESCRIPTION
**Pull request by ooojpeg**
Removed reference to gzip and replaced with correct extension of gz.

- [x] closes #35364

Screenshot 2020-11-30 at 20 43 59

### CODE REVIEW

**Comment by rhshadrach** [comment]
The compression string here is specifying the compression and is used by the code:

```
# GZ Compression
if compression == "gzip":
```

This is making the docstring incorrect.

**Comment by ooojpeg** [comment]
@rhshadrach Outdated issue?

**Comment by rhshadrach** [comment]
As I commented in the issue, it seems like a good idea to me to have the details that are currently in `DataFrame.to_csv` also in `DataFrame.to_pickle`. These details make clear why the argument is "gzip" and not "gz".

**Comment by ooojpeg** [comment]
Added information as mentioned by @rhshadrach.
Screenshot 2020-11-30 at 23 11 09

**Comment by twoertwein** [comment]
it might be useful to share documentation across all function that support the same compression (csv/pickle/json/...), similar to #37953. I didn't check whether the docstrings match exactly.

**Comment by jreback** [comment]
thanks @ooojpeg 

@twoertwein yeah can you open issue(s) to share these doc-strings as you did before.

**Pull request merged**
