### PR TITLE
PERF: timeseries comparison ops

### LINKED ISSUE #37462: PERF: performance regression in timeseries/timestamp comparison (ASV)
See https://pandas.pydata.org/speed/pandas/#arithmetic.Timeseries.time_series_timestamp_compare?python=3.8&Cython=0.29.21&p-tz=None&commits=ac7ca239-038aab96

This seems to be caused by https://github.com/pandas-dev/pandas/pull/37313 cc @jbrockmendel

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #37462
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Locally this gets me to within 3-4% of 1.1.4 on the asv mentioned in #37462

### CODE REVIEW

**Comment by jreback** [comment]
@jbrockmendel just confirming, but I believe this is for 1.1.5 right?

**Comment by jbrockmendel** [comment]
i think so, best to ask @simonjayhawkins

**Comment by simonjayhawkins** [comment]
> @jbrockmendel just confirming, but I believe this is for 1.1.5 right?

comment from https://github.com/pandas-dev/pandas/issues/37462#issue-731193131

> This seems to be caused by #37313

so IIUC no need to backport.

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
