### PR TITLE
F/rolling size

### LINKED ISSUE #24057: DataFrame.rolling.size not implemented and errors in aggregation
#### Code Sample, a copy-pastable example if possible

```python
>>> idx = pd.date_range('2012-1-1', periods=20)
>>> data = np.random.rand(len(idx))
>>> data[5] = np.nan
>>> s = pd.Series(data, idx)

>>> s.rolling('5D').size()
AttributeError: 'Rolling' object has no attribute 'size'

# no error with `agg`, but yields nonsense result
>>> s.rolling('5D').agg('size')
1

# fails when in a list
>>> s.rolling('5D').agg(['size'])
AttributeError: 'Rolling' object has no attribute 'name
```
#### Problem description

`size` should be implemented and return the size of the window. This is useful when downsampling over a larger frequency than the current. For instance, downsampling with weeks for daily data.

`'size'` yields a nonsense result when used as a string inside of `agg`.  `'count'` works but does not get the desired result as there could be missing values as there is in the above Series.

You can use `np.size` to get the desired result, but for consistency, the string `'size'` should work.

#### Expected Output

```
>>> s.rolling('5D').agg(np.size)
2012-01-01    1.0
2012-01-02    2.0
2012-01-03    3.0
2012-01-04    4.0
2012-01-05    5.0
2012-01-06    4.0
2012-01-07    4.0
2012-01-08    4.0
2012-01-09    4.0
2012-01-10    4.0
2012-01-11    5.0
2012-01-12    5.0
2012-01-13    5.0
2012-01-14    5.0
2012-01-15    5.0
2012-01-16    5.0
2012-01-17    5.0
2012-01-18    5.0
2012-01-19    5.0
2012-01-20    5.0
Freq: D, dtype: float64
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.0.1
pip: 18.1
setuptools: 40.4.3
Cython: 0.29.1
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.14
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0

</details>

### PR DESCRIPTION
**Pull request by bourbaki**
- [x] closes #24057
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by ma3axaka** [comment]
The only question I have is how to properly document an alias like that?

**Review by jreback — CHANGES_REQUESTED** [review]
this is not the right way - this should be setup in base class (where groupby and resample also inherit)

.size is not the same as .count either - it’s the size of the window where
count is the size  - min_count

**Comment by ma3axaka** [comment]
Thanks for the feedback. Maybe this is stupid question but could you give an example where `size` and `count` should give different results?
And what base class do you mean exactly? Looking at the class diagram the most "promising" one is `pandas.core.base.SelectionMixin`

**Comment by ma3axaka** [comment]
@TomAugspurger Do you think I need to implement `roll_size` function? I am looking into `_libs/window.pyx` and there are Cython implementation of basic aggregate functions on windows.

**Comment by TomAugspurger** [comment]
Perhaps... Though I size will be equivalent to the length of each window,
right? I'm familiar with this section of the code base, but you may be able
to find
a way to get that information without having to write any Cython.

**Comment by WillAyd** [comment]
`roll_size` is only used when dealing with frequency windows otherwise there's a `count` method in one of the base classes you could use for reference. Your test case should also take into account various combinations of arguments to the Window

**Comment by jreback** [comment]
so looking at this again, I think that this is almost exactly ``count``, but counts all values rather than ``notna`` ones. So prob easiest to move ``count`` to ``_count.()`` and parameterize this to count na's via a keyword (skipna=True), then both size and count can call this.

**Comment by jorisvandenbossche** [comment]
> Maybe this is stupid question but could you give an example where size and count should give different results?

`size` gives the full size of the group/window (the number of rows), while `count` is a count of the non-missing values. So once you have missing values, there will be different results.

To give a concrete example with groupby, as there both are implemented:

```
In [12]: df = pd.DataFrame({'a': [1, 1, 1, 2, 2, 2], 'b':[1, 2, 3, np.nan, 5, 6]})                                                                                              

In [13]: df.groupby('a')['b'].count()                                                                                                                                           
Out[13]: 
a
1    3
2    2
Name: b, dtype: int64

In [14]: df.groupby('a')['b'].size()                                                                                                                                            
Out[14]: 
a
1    3
2    3
Name: b, dtype: int64
```

**Comment by ma3axaka** [comment]
I have pushed the solution I came up with. Could `roll_size` be redundant?

**Comment by ma3axaka** [comment]
@jreback Is this approach ok?

**Comment by WillAyd** [comment]
Would rather see something that integrates into the existing `count` function as noted above by myself and Jeff. `roll_count` is only used with certain arguments so emulating via `roll_size` isn't the right way to go about this

**Comment by jreback** [comment]
if you want to update according to comment, pls ping.

**Pull request closed without merging**
