### PR TITLE
TST: run setitem tests for IntegerArray

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
`itemsize` isn't part of the interface. I'm not sure it could be added, since we may have variable-width EAs. 

Probably want to add a docstring for your `Int*Dtype.itemsize`, since once won't be inherited.

LGTM otherwise.

**Comment by jreback** [comment]
not sure why azure is not running on the personal builds. but this is ready @TomAugspurger

**Comment by TomAugspurger** [comment]
Agreed. We may want to hold off on merging larger changes, since I believe linting is now on azure, but this LGTM.

**Comment by TomAugspurger** [comment]
But let's see if it runs for the merge build. If so, then we can merge things and followup as needed.

**Pull request merged**
