### PR TITLE
Cython language level 3

### LINKED ISSUE #23927: Cython language_level Warning - switch to Python3?
When compiling with Cython the following warning gets issued:

```bash
Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: clones/pandas/pandas/_libs/groupby.pxd
```

Haven't looked into the implications as of yet but probably worth switching to Python3, especially given the upcoming drop of Python2 support

### PR DESCRIPTION
**Pull request by WillAyd**
- [X] closes #23927

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. ping on green.

**Review by jbrockmendel — COMMENTED** [review]
I think there are places where we do isinstance Unicode checks, may be worth updating

**Comment by WillAyd** [comment]
> I think there are places where we do isinstance Unicode checks, may be worth updating

Yep I do see a few. Going to try and get green as is first then do this on a subsequent pass

**Comment by WillAyd** [comment]
All failures are for the 2.7 builds; are we still worrying about them at this point?

**Comment by jreback** [comment]
only if you want to merge this for 0.24

**Comment by WillAyd** [comment]
I don't think it necessarily adds anything to 0.24 from an end user perspective so fine to wait on my end

**Comment by WillAyd** [comment]
Just rebasing to minimize diff in future; no rush for action here

**Comment by WillAyd** [comment]
@jreback I think timing is finally right for merge here.

To @jbrockmendel point above there are still some isinstance unicode checks that could be cleaned up, but I figure that's better left in follow ups to rip out Py2 compat. This as is is minimum to get language level switched over to 3 syntax

**Comment by jreback** [comment]
thanks @WillAyd

**Pull request merged**
