### PR TITLE
BUG: to_datetime/to_timedelta with memoryview

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
no objections but. an u run the performance on is_list_like

**Comment by jbrockmendel** [comment]
```
In [3]: arr = np.arange(5)
In [4]: %timeit is_list_like(arr)
87.1 ns ± 1.15 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)  # <- PR
84.6 ns ± 0.407 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each))  # <- master
```

**Comment by jreback** [comment]
> pandas/tests/dtypes/test_inference.py:121: error: Argument 1 to "memoryview" has incompatible type "ndarray[Any, Any]"; expected "Union[bytes, bytearray, memoryview, array[Any], mmap]"  [arg-type]
pandas/tests/dtypes/test_inference.py:122: error: Argument 1 to "memoryview" has incompatible type "ndarray[Any, Any]"; expected "Union[bytes, bytearray, memoryview, array[Any], mmap]"  [arg-type]


also prob need a note on this

**Comment by jreback** [comment]
can you merge master, haven't seen the 3.10 failing before

**Pull request closed without merging**
