### PR TITLE
Added orient="ndarray" to DataFrame.to_dict()

### PR DESCRIPTION
**Pull request by LarsKue**
It would be useful to allow Series to be directly converted to numpy arrays instead of having to do this outside.

### CODE REVIEW

**Comment by attack68** [comment]
is this really that useful, its only a one-line transformation?

```
df = pd.DataFrame({'a': [1,2], 'b': [3,4]})
dict_arr = {k: np.array(v) for k, v in df.to_dict(orient='list').items()}
```

**Comment by LarsKue** [comment]
> is this really that useful, its only a one-line transformation?

If you consider this not useful, the entire `to_dict` method should also be considered not useful, since it does exactly this for other types.

**Comment by jnothman** [comment]
`dict(my_dataframe)` does this.

**Comment by LarsKue** [comment]
> `dict(my_dataframe)` does this.

You are right, good to know. I could not find this in the docs. Closing this PR.

**Comment by lfaucheux** [comment]
> `dict(my_dataframe)` does this.

No longer true.

**Pull request closed without merging**
