### PR TITLE
DOC: Fix order section in docstrings (part II)

### LINKED ISSUE #24125: DOC: Fix docstrings error GL07 - Sections are in the wrong order
When checking for errors with ./scripts/validate_docstrings.py, There is an error that comes up:

GL07
'Sections are in the wrong order. Correct order is: ' '{correct_sections}'

I worked on this and will create a pull request for this issue shortly to go into more detail on what I fixed.

@datapythonista

### PR DESCRIPTION
**Pull request by alexander-ponomaroff**
- [X] closes #24125 
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

This is to build on #24126 .

As I commented in the issue, this pull request will fix additional 10 out of 24 errors. 14 errors will remain and are referenced in the issue.

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @alexander-ponomaroff 

can you merge master to rerun the CI please

**Comment by jreback** [comment]
can you rebase

**Comment by alexander-ponomaroff** [comment]
`0cfd1c2f000ad9c4cf8e7a170e85c2971a99cf02` and `f74fc59793ce1f01e1afcdd29bcdf0dceccaf244` commits were added to this pull request by @jreback right? Or did I mess something up?

**Comment by datapythonista** [comment]
When we ask for a rebase, it mainly means to merge master into your branch, so you have your changes on top of the latest version. So, you should have a merge commit, but not commits from master directly or other PRs.

**Comment by alexander-ponomaroff** [comment]
@datapythonista I guess my experimentation went wrong :/. I reverted everything and merged everything properly now right?

**Comment by datapythonista** [comment]
Looks great, but the failures in the CI are because of a test that checks a docstring. Can you take a look and update the test please?

**Comment by datapythonista** [comment]
@jreback I fixed the problems in this PR, and all green now, should be ready to go.

There are still few docstrings with the wrong order, we'll be adding the validation to the CI in the follow up issue to fix them: #24280

**Comment by datapythonista** [comment]
@jreback if you have time to take a quick look at this. Should be ready to be merged, and will block #24288 soon, which will add the linting for this fix. Thanks!

**Review by jreback — APPROVED** [review]
lgtm

**Comment by datapythonista** [comment]
thanks @alexander-ponomaroff for the fixes

and thanks @jreback for the review

**Comment by datapythonista** [comment]
No worries. Are you planning to work on moving the CircleCI build to Travis? I was thinking on taking that myself if you don't.

**Comment by alexander-ponomaroff** [comment]
@datapythonista It would be great if you could take that over. I've been struggling with how to go about moving CicleCI build to Travis and didn't want to be annoying and ask too many questions, so I haven't gotten very far when I was working on it. Then my exams took over all of my time and I had to stop working on it, so if you are ok with taking it over from now, it would be much appreciated. Sorry about this.

**Comment by datapythonista** [comment]
no worries, thanks for giving it a try, and for letting me know

**Pull request merged**
