### PR TITLE
DOC: combine regressions in section in v1.0.1 whatsnew

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Similarly how we did it for 0.24.x, gathering all regressions in the first section of the whatsnew (as those are the most important part of 1.0.1)

cc @TomAugspurger

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Given that there is not much remaining in the "Bug fixes" section, I can probably remove the subtitles there?

**Comment by TomAugspurger** [comment]
> I can probably remove the subtitles there?

Agreed.

**Comment by TomAugspurger** [comment]
This will cause merge conflicts with outstanding PRs. What order do you want to merge these in?

**Comment by jorisvandenbossche** [comment]
I can fixup conflicts later here, or also help fixing conflicts in the other PRs. Doesn't matter really to me

**Comment by TomAugspurger** [comment]
Let's just merge this since it's already passing.

**Pull request merged**
