### PR TITLE
CI: troubleshoot 32bit build

### LINKED ISSUE #32229: 32 bit CI Failures
Haven't had time to debug but seeing this in the logs when setting up the 32 bit linux environment:

```sh
Traceback (most recent call last):
  File "/home/vsts/miniconda3/bin/conda", line 7, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
```

### PR DESCRIPTION
**Pull request by jbrockmendel**
closes #32229

### CODE REVIEW

**Comment by jbrockmendel** [comment]
cc @jreback @WillAyd looks like this fixed azure, travis failure is orthogonal (and i think intermittent)

**Comment by jbrockmendel** [comment]
cc @jreback @WillAyd looks like this fixed azure, travis failure is orthogonal (and i think intermittent)

**Comment by simonjayhawkins** [comment]
@jbrockmendel does this close #32229?

**Comment by jbrockmendel** [comment]
I think so, yes

**Comment by jbrockmendel** [comment]
Merging to get the CI going, can revert later if there are objections.

**Pull request merged**
