### PR TITLE
BLD: Python changes to make meson build work

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by WillAyd** [comment]
FWIW I wouldn't mind if we consolidated some of these PRs into bigger ones. Its a bit difficult to know the context of changes here and the conversation is getting fragmented

**Comment by lithomas1** [comment]
Gotcha, how about if I combine the CI/pyproject.toml changes here too? The diff should be ~200 LOC. We would be good to go after this PR if I combined everything here.

**Comment by WillAyd** [comment]
Cool let's give it a look. I might even prefer if you combined this with the meson files

**Comment by lithomas1** [comment]
Moved to the build files.

**Pull request closed without merging**
