### PR TITLE
CLN: use unicode literals instead of compat.u

### PR DESCRIPTION
**Pull request by jbrockmendel**
This gets _most_ of the non-test usages

### CODE REVIEW

**Review by gfyoung — APPROVED** [review]
Huh...that's a good catch!  Maybe we can rid of it entirely perhaps later?

**Comment by jbrockmendel** [comment]
> Maybe we can rid of it entirely perhaps later?

There's plenty of cases left with `u("foo")` that are easy to modernize.  I didn't look too closely at the handful of `u(bar)` cases.  Presumably it will all become simpler next month after py2 is dropped.

**Comment by jbrockmendel** [comment]
> Is there a reason you want to change this now, rather than just wholesale change after PY2 is dropped?

Not especially.  Just see cleanup opportunities when browsing through modules, figure being aggressive about them is better than the alternative.

> so the reason we have this is to provide a uniform way to do this across py2 and py3. you don't then have to worry about whether you are quoting unicode or not and just use u

I'm guessing this got put in place before unicode literals got added back into py3.  since there is a built-in way of doing this, that should be preferred over a home-built solution.

**Comment by jreback** [comment]
> I'm guessing this got put in place before unicode literals got added back into py3. since there is a built-in way of doing this, that should be preferred over a home-built solution.

was this in 3.4? (e.g. this function was certainly done quite a long time ago).

**Comment by jbrockmendel** [comment]
Rebased.  This is pretty low-priority, should either merge or close.

**Comment by jreback** [comment]
let's close for now.

**Pull request closed without merging**
