### PR TITLE
TST: Different tests were collected between gw0 and gw1

### PR DESCRIPTION
**Pull request by simonjayhawkins**
not sure if anyone else if having issue running tests locally. have created a clean pandas-dev env on a different machine so maybe a transient thing.

https://github.com/pytest-dev/pytest-xdist/issues/432

<details>

```
INSTALLED VERSIONS
------------------
commit           : dce547ea2fe7f8c5c51c04d0a87704a2b4abf476
python           : 3.8.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : English_United Kingdom.1252

pandas           : 1.2.0.dev0+908.gdce547ea2f
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 49.6.0.post20201009
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : 5.37.4
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.4
fastparquet      : 0.4.1
gcsfs            : 0.7.1
matplotlib       : 3.3.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.5.0
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.16.1
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2
```
</details>

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

**Comment by jreback** [comment]
yep lgtm merge when greenish

**Review by simonjayhawkins — COMMENTED** [review]
don't merge yet.

maybe coincidence but the failing test, test_binary_arith_ops (failing elsewhere, see #37328) is parametrerised with test _good_arith_ops which is changed here

**Comment by topper-123** [comment]
I'm on windows and these failures seem to be windows specific. So I've done some bisecting, and the first failing PR for me is #35964 (commit ab5b38d56). Haven't checked what precisely it is there, but could be the parametrization over `transformation_kernels` (a set).

These are also fairly old commits, so I'm wondering why they're failing now. Maybe an incompatable update has been done in `xdist` or `pytest`?

**Comment by topper-123** [comment]
@simonjayhawkins , can we merge this? With these changes everythings runs on my machine and evidently also on the CI.

The changes to `_good_arith_ops ` look reasonable to me, so IMO should be kept.

**Pull request merged**
