### PR TITLE
DOC: Remove deprecated delim_whitespace from user guide

### LINKED ISSUE #58488: DOC: User guide still recommends delim_whitespace
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/user_guide/io.html#basic

### Documentation problem

While the main API reference indicates that the `delim_whitespace` option to `pandas.read_csv` is deprecated, the User Guide still lists it as an option with no caveat. This may lead new users to adopt an option that is already deprecated, and either immediately get warnings, or write code that will break relatively soon.

### Suggested fix for documentation

Either remove the `delim_whitespace` option from the page (probably preferred; new users don't need to be introduced to features about to be deprecated) or add a deprecation notice similar to the one appearing on [the `read_csv` reference](https://pandas.pydata.org/docs/dev/reference/api/pandas.read_csv.html#pandas.read_csv)

### PR DESCRIPTION
**Pull request by Aloqeely**
- [x] closes #58488
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Aloqeely

**Comment by Aloqeely** [comment]
Can this be backported @mroeschke?

**Comment by Aloqeely** [comment]
@meeseeksdev backport 2.2.x

**Comment by mroeschke** [comment]
Hmm I don't think it's super critical that this documentation is backported

**Comment by Aloqeely** [comment]
It isn't critical, but if this isn't going to be backported then users viewing the stable docs won't know this option is deprecated
https://github.com/pandas-dev/pandas/issues/58488#issuecomment-2089150285

**Pull request merged**
