### PR TITLE
upgrade to the latest version of PyData Sphinx Theme

### PR DESCRIPTION
**Pull request by partev**
upgrade PyData Sphinx Theme from 0.14 to the latest 0.16

it is needed to get the latest font-awesome pack to be able to display the new twitter-x icon.

https://github.com/pandas-dev/pandas/pull/60426

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by mroeschke** [comment]
Thanks. Could you run pre-commit over your changes?

**Comment by partev** [comment]
> Thanks. Could you run pre-commit over your changes?

@mroeschke done!

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks let's give this a try

**Comment by partev** [comment]
everything seems to be working now!
image

**Pull request merged**
