### PR TITLE
Refactor CI code

### PR DESCRIPTION
**Pull request by jonashaag**
I know this is a lot of changes. Happy to split into multiple PRs if it is too much to review.

Side effect of the changes is that most jobs are ~ 10 minutes faster.

- Drop Azure (move to GHA).
- Use mamba-org/provision-with-micromamba to set up Conda envs.
- Cache Conda envs.
- Use hendrikmuhs/ccache-action to cache C compiliation.
- Add Windows 32 bit build.
- Drop Ubuntu 32 bit build. (Can also bring back, have code for that.)
- Factor out common GHA code into reusable actions.

### CODE REVIEW

**Comment by jonashaag** [comment]
@mroeschke would love your feedback here.

**Comment by mroeschke** [comment]
+1 to all the changes, but it would be easier to review (and probably safer) if each of these changes could be made in separate PRs

**Comment by jonashaag** [comment]
I can make the following PRs; anything else would require more work but I can do it as well if you want me to.

- PR 1
  - Drop Azure (move to GHA).
  - Drop Ubuntu 32 bit build.
  - Factor out common GHA code into reusable actions.
- PR 2: Add Windows 32 bit build.
- PR 3: Use mamba-org/provision-with-micromamba to set up Conda envs.
- PR 4: Cache Conda envs.
- PR 5: Use hendrikmuhs/ccache-action to cache C compiliation.

**Comment by mroeschke** [comment]
Yup those steps would be more digestible to review.

**Comment by jreback** [comment]
why do we care about windows 32 build?

**Comment by jonashaag** [comment]
Acted on this comment. https://github.com/pandas-dev/pandas/issues/44453#issuecomment-974937782

**Pull request closed without merging**
