### PR TITLE
BUG: avoid segfault in tz_localize with ZoneInfo

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by MarcoGorelli — COMMENTED** [review]
Looks fine to me - does this need a whatsnew note if it fixes a segfault? Also, is there a way to reproduce the segfault locally?

**Comment by jbrockmendel** [comment]
> does this need a whatsnew note if it fixes a segfault?

Nope, only relevant in main, not in any released version.

> Also, is there a way to reproduce the segfault locally?

```
dti = pd.date_range(start="2015-03-29 02:00:00", periods=60, freq="min")
tz =  zoneinfo.ZoneInfo("Europe/Warsaw")
dti.tz_localize(tz, nonexistent="shift_forward)
```

**Comment by MarcoGorelli** [comment]
Ah I was getting `AttributeError`, perhaps because I was using the zoneinfo backport on 3.8
```
In [1]: from backports import zoneinfo

In [2]: dti = pd.date_range(start="2015-03-29 02:00:00", periods=60, freq="min")
   ...: tz =  zoneinfo.ZoneInfo("Europe/Warsaw")
   ...: dti.tz_localize(tz, nonexistent="shift_forward")

AttributeError: 'NoneType' object has no attribute 'total_seconds'
```
I'll try in 3.9

**Review by MarcoGorelli — APPROVED** [review]
Can reproduce in Python 3.9 - looks good to me!

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
