### PR TITLE
BUG: Index.get_loc(np.nan) non-unique non-monotonic

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

The tests file will need to be rebased following #43705.

### CODE REVIEW

**Comment by jreback** [comment]
looks fine, user facing?

**Comment by jbrockmendel** [comment]
> looks fine, user facing?

yah, will add whatsnew

**Comment by jbrockmendel** [comment]
Whatsnew added + green

**Comment by jreback** [comment]
looks good. can you rebase again and ping on green.

**Comment by jbrockmendel** [comment]
ping

**Pull request merged**
