### PR TITLE
BUG: #14095. Amend eval() resolvers kwarg to accept lists

### LINKED ISSUE #14095: BUG: resolvers in pandas.eval should accept list-like
I think the resolvers argument of pandas.eval requires a tuple and not a list
```
resolvers : list of dict-like or None, optional
A list of objects implementing the __getitem__ special method that you can use to inject an additional collection of namespaces to use for variable lookup. For example, this is used in the query() method to inject the index and columns variables that refer to their respective DataFrame instance attributes.
```
as with a list I get a
```
    kwargs['resolvers'] = kwargs.get('resolvers', ()) + resolvers
TypeError: can only concatenate tuple (not "list") to tuple
```

### PR DESCRIPTION
**Pull request by tom-bird**
- [x] closes #14095
- [x] tests added / passed
- [ ] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by chris-b1** [comment]
This should also be tested (and may need a fix) for `pd.eval`

**Comment by theultimatecrouton** [comment]
`pd.eval` seems ok taking a list or tuple

**Comment by jreback** [comment]
@theultimatecrouton can you add a test for ``pd.eval`` as well. otherwise lgtm.

**Comment by theultimatecrouton** [comment]
Added

**Comment by jreback** [comment]
thanks!

**Pull request closed without merging**
