### PR TITLE
Simplify algebra in Week and SemiMonth offsets

### PR DESCRIPTION
**Pull request by jbrockmendel**
This PR is careful to only touch Week-base and SemiMonth-based offsets, i.e. has no overlap with #18263.  It does, however, simplify the algebra such that the end result looks a  lot like 18263.

- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
do we have sufficient tests for all of these cases?

**Comment by jbrockmendel** [comment]
> do we have sufficient tests for all of these cases?

As in #18263, I think so, yes.

**Comment by jbrockmendel** [comment]
> do we have sufficient tests for all of these cases?

Looks like between the three active PRs unifying the `apply` methods, there is one line in `LastWeekOfMonth.apply` that does not currently have coverage.  I'll make sure to hit that in the next follow-up.

Side-note.  I went to check this on codecov by clicking the badge on pandas GH page and the link just goes to the image file for the badge itself.  Looks like all the badges do that.  I doubt that's the intended behavior.

**Comment by jreback** [comment]
> Side-note. I went to check this on codecov by clicking the badge on pandas GH page and the link just goes to the image file for the badge itself. Looks like all the badges do that. I doubt that's the intended behavio

hmm thought that worked.

**Comment by jreback** [comment]
thanks!

**Comment by jreback** [comment]
you can click on the codecov report in the pr to see things FYI

**Pull request merged**
