### PR TITLE
CLN/PERF: remove unnecessary ensure_platform_int

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
This line was added in https://github.com/pandas-dev/pandas/pull/43977, while the docstring and type information (as added in https://github.com/pandas-dev/pandas/pull/43977) indicates this is already the case.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
we have a lot of should-be-unnecessary ensure_platform_int calls.  these should be extremely cheap, so haven't been bothering to remove.

**Comment by jorisvandenbossche** [comment]
> so haven't been bothering to remove.

And in the past I bothered making a fast-path `take_1d` which explicitly removed it. It did show up in reindex benchmarks IIRC (https://github.com/pandas-dev/pandas/pull/40246, https://github.com/pandas-dev/pandas/pull/39692)

**Comment by jorisvandenbossche** [comment]
Digging up the benchmarks. Doing one specific for take_1d:

```python
from pandas.core.array_algos.take import take_1d
arr = np.arange(10000)
idx = np.arange(100, dtype=np.intp)

In [5]: %timeit take_1d(arr, idx, allow_fill=False)
498 ns ± 0.77 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)  # <-- master
465 ns ± 0.962 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)  # <-- PR
```

This is of course about nanoseconds, so in absolute terms only a tiny difference. But because this function is used repeatedly in things like unstack and reindex, it does make a noticeable difference. Eg on the unstack case as used in https://github.com/pandas-dev/pandas/pull/40246, it gives ~ 3-5% difference (which is still small, but IMO worth it since this is actually removing a single line, and the constraint is explicitly documented / in the type information)

**Comment by jbrockmendel** [comment]
sure no objection

**Comment by jreback** [comment]
no objection, can you rebase

**Pull request merged**
