### PR TITLE
GH31581 adding regression test

### LINKED ISSUE #31581: Assigning column with DataFrame(dtype='category') doesn't preserve categorical dtype, but Series does
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame([1,2,3])
df['col1'] = pd.DataFrame([1,2,3], dtype='category')
df['col2'] = pd.Series([1,2,3], dtype='category')
df.dtypes
```
#### Problem description

This returns
```
0          int64
col1       int64
col2    category
dtype: object
```
#### Expected Output
```
0          int64
col1    category
col2    category
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : d9f028dba97e9a3f21077ceeb96ca6552909c3b3
python           : 3.7.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-74-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 0.26.0.dev0+2031.gd9f028dba.dirty
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 45.0.0.post20200113
Cython           : 0.29.14
pytest           : 5.3.3
hypothesis       : 5.1.5
sphinx           : 2.3.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.4.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.11.1
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.2
matplotlib       : 3.1.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.1
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
pytest           : 5.3.3
pyxlsb           : None
s3fs             : 0.4.0
scipy            : 1.4.1
sqlalchemy       : 1.3.12
tables           : 3.6.1
tabulate         : 0.8.6
xarray           : 0.14.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.47.0
</details>

### PR DESCRIPTION
**Pull request by corriebar**
- [x] closes #31581 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Worked on during the PyData workshop with @DrorBendet and @sven-simonsen. Tagging @phofl @noatamir @jorisvandenbossche @MarcoGorelli as reviewers.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
looks good to me, thanks @corriebar

**Comment by mroeschke** [comment]
Could you resolve the merge conflict?

**Comment by corriebar** [comment]
> Could you resolve the merge conflict?

resolved.

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
Thx @corriebar

**Pull request merged**
