### PR TITLE
ENH: scatter_matrix new parameter nondiagonal to allow hexbin plots i…

### LINKED ISSUE #56887: ENH: pandas.plotting.scatter_matrix to support plotting function hexbin in addition to scatter
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could use the [scatter_matrix](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.plotting.scatter_matrix.html) function to make [hexbin](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hexbin.html) plots

### Feature Description

Add a new parameter `nondiagonal` to `scatter_matrix` to support `hexbin` instead of `scatter`

```
def scatter_matrix(...):
    ...
    if nondiagonal=="scatter":
        ax.scatter(...)
    if nondiagonal=="hexbin":
        ax.hexbin(...)
    ...
```

### Alternative Solutions

Seaborn pairplot using `kind = hist`. Link: https://seaborn.pydata.org/generated/seaborn.pairplot.html

### Additional Context

The general consensus on `pandas.plotting.scatter_matrix` is that "seaborn does this better" ([ref 1](https://github.com/pandas-dev/pandas/issues/11978#issuecomment-169533788), [ref 2](https://github.com/pandas-dev/pandas/issues/13400#issuecomment-224766311)). Nevertheless, the functionality was kept, and the changes to support this feature are a few lines of code.

The quality of the plots can improve significantly. Here's an example with scatter:

```
# Copy of example from scatter_matrix docs page, but increase data frame rows from 1k to 10k:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(1_0_000, 4), columns=['A','B','C','D'])
```

image

Same example with hexbin:

image

### PR DESCRIPTION
**Pull request by shadiakiki1986**
…nstead of scatter

- [ ] closes #56887  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
  - running the tests gives an error unrelated to my development: ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'
```
ImportError while loading conftest '/workspaces/pandas/pandas/conftest.py'.
pandas/__init__.py:49: in <module>
    from pandas.core.api import (
pandas/core/api.py:1: in <module>
    from pandas._libs import (
pandas/_libs/__init__.py:16: in <module>
    import pandas._libs.pandas_parser  # isort: skip # type: ignore[reportUnusedImport]
E   ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'
```
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
  - same issue as tests
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
  - didn't add yet

### CODE REVIEW

**Comment by bhattbhuwan13** [comment]
I have the same issue. I can import pandas normally if i switch to the parent directory(the one just outside the root pandas directory) but when I try to import pandas from the directory containing the requirements file, it fails with the same error

**Comment by shadiakiki1986** [comment]
@mroeschke  
Merged. Failed tests were unrelated to the edits in this PR

**Comment by shadiakiki1986** [comment]
I'm not sure how to react to this. We already went through the cycle of
updating the branch. Feels like the start of an infinite loop.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Comment by shadiakiki1986** [comment]
Is this an automated response?

**Pull request closed without merging**
