### PR TITLE
DOC: enable matplotlib plot_directive to include figures in docstrings

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
This adds the matplotlib.sphinxext.plot_directive as extension to conf.py, and added a small example in the `Series.plot.line` docstring

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Documentation on this is here: https://matplotlib.org/devdocs/devel/plot_directive.html

Example how it looks like for the simple things I added:

screenshot from 2018-03-06 16-26-45

**Comment by jorisvandenbossche** [comment]
cc @datapythonista might be useful for the plotting docstrings

**Comment by datapythonista** [comment]
That's really cool, I think it'll make a big difference.

@dukebody, you've been working on the plot docstring, any thought based on what you did?

**Comment by jorisvandenbossche** [comment]
cc @TomAugspurger looking OK?

**Review by TomAugspurger — APPROVED** [review]
Looks great. We may want to add `import matplotlib.pyplot as plt` as the `plot_pre_code` at some point.

**Comment by dukebody** [comment]
@datapythonista We probably want to mention in the documentation for docs that, if I'm not mistaken, one of these blocks is needed everytime we want to output a figure. Hence the `close-fig` context.

Please merge this before the sprint on Saturday if possible, since it can be a real game changer for documenting plot-producing methods, as mentioned by @datapythonista .

**Comment by jreback** [comment]
going to merge shortly. @dukebody can you make an issue for followups to this that are needed (e.g. add how-to in the doc)

**Comment by jreback** [comment]
thanks!

**Pull request merged**
