### PR TITLE
CI try using ubuntu20.04

### LINKED ISSUE #50112: CI warning is causing build to fail
The following shows up in some recent jobs: https://github.com/pandas-dev/pandas/actions/runs/3641110250/jobs/6146658226
```
2022-12-07T17:13:17.4282435Z pandas/_libs/tslibs/parsing.c: In function ‘__pyx_f_6pandas_5_libs_6tslibs_7parsing_dateutil_parse.constprop’:
2022-12-07T17:13:17.4286489Z pandas/_libs/tslibs/parsing.c:10634:22: error: array subscript ‘PyMethodObject[0]’ is partly outside array bounds of ‘PyObject[1]’ {aka ‘struct _object[1]’} [-Werror=array-bounds]
2022-12-07T17:13:17.4287232Z 10634 |           __pyx_t_10 = PyMethod_GET_SELF(__pyx_t_2);
2022-12-07T17:13:17.4288524Z In file included from /home/runner/micromamba/envs/test/include/python3.8/pytime.h:6,
2022-12-07T17:13:17.4289063Z                  from /home/runner/micromamba/envs/test/include/python3.8/Python.h:85,
2022-12-07T17:13:17.4289520Z                  from pandas/_libs/tslibs/parsing.c:46:
2022-12-07T17:13:17.4290230Z /home/runner/micromamba/envs/test/include/python3.8/object.h:560:22: note: while referencing ‘_Py_NoneStruct’
2022-12-07T17:13:17.4290904Z   560 | PyAPI_DATA(PyObject) _Py_NoneStruct; /* Don't use this directly */
2022-12-07T17:13:17.4291327Z       |                      ^~~~~~~~~~~~~~
2022-12-07T17:13:17.4299214Z pandas/_libs/tslibs/parsing.c:10636:23: error: array subscript ‘PyMethodObject[0]’ is partly outside array bounds of ‘PyObject[1]’ {aka ‘struct _object[1]’} [-Werror=array-bounds]
2022-12-07T17:13:17.4299878Z 10636 |             PyObject* function = PyMethod_GET_FUNCTION(__pyx_t_2);
2022-12-07T17:13:17.4300282Z       |                       ^~~~~~~~
2022-12-07T17:13:17.4300776Z In file included from /home/runner/micromamba/envs/test/include/python3.8/pytime.h:6,
2022-12-07T17:13:17.4301291Z                  from /home/runner/micromamba/envs/test/include/python3.8/Python.h:85,
2022-12-07T17:13:17.4301779Z                  from pandas/_libs/tslibs/parsing.c:46:
2022-12-07T17:13:17.4302447Z /home/runner/micromamba/envs/test/include/python3.8/object.h:560:22: note: while referencing ‘_Py_NoneStruct’
2022-12-07T17:13:17.4303287Z   560 | PyAPI_DATA(PyObject) _Py_NoneStruct; /* Don't use this directly */
2022-12-07T17:13:17.4303722Z       |                      ^~~~~~~~~~~~~~
2022-12-07T17:13:18.5474602Z cc1: all warnings being treated as errors
```

Example of green job: https://github.com/pandas-dev/pandas/actions/runs/3633476581/jobs/6130537543
Example of red job: https://github.com/pandas-dev/pandas/actions/runs/3641110250/jobs/6146658226

Can't tell what's caused this

Here's the difference between the environments:
```
                                                  Name Version_x Version_y
0    ──────────────────────────────────────────────...      None      None
59                                           db-dtypes     1.0.4     1.0.5
109                               google-cloud-storage     2.6.0     2.7.0
114                                             grpcio    1.49.1    1.51.1
115                                      grpcio-status    1.49.1    1.51.1
126                                importlib_resources    5.10.0    5.10.1
183                                            libgrpc    1.49.1    1.51.1
284                                     prompt-toolkit    3.0.33    3.0.36
```

### PR DESCRIPTION
**Pull request by MarcoGorelli**
trying to fix broken CI builds

closes https://github.com/pandas-dev/pandas/issues/50112

### CODE REVIEW

**Review by lithomas1 — APPROVED** [review]
Nice catch!

**Comment by lithomas1** [comment]
BTW, I might be considering making a pre-commit hook to ban uses of latest versions of images from being used. 

There's not really much benefit to doing this, and we already do this when building wheels (I've been burned by this in the past, when Visual Studio 2017 was upgraded to Visual Studio 2019).

**Comment by MarcoGorelli** [comment]
Thanks - jobs are passing now, so let's merge to unblock all other PRs

> BTW, I might be considering making a pre-commit hook to ban uses of latest versions of images from being used.

Nice! I'm all for automation

**Comment by phofl** [comment]
Can you open an issue? We should think about upgrading to 22.04.

22.10 is the latest version btw, 22.04 is just the latest version with longer support

**Comment by MarcoGorelli** [comment]
yup, here it is https://github.com/pandas-dev/pandas/issues/50115

**Pull request merged**
