### PR TITLE
CLN: GH29547 replace old string formatting

### PR DESCRIPTION
**Pull request by pcandoalmeida**
Hi there! I've added some missed f-strings to:
* tests/tslibs
* tests/tseries

- [x] tests passed
- [x] passes `black pandas`

Thank you.

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]
Thanks @pcandoalmeida lgtm pending green

**Review by datapythonista — APPROVED** [review]
Looks like the error in the CI is caused by #31156, but can't see why.

@stijnvanhoey any idea what can be wrong?

**Comment by stijnvanhoey** [comment]
```
 Extension error:
Could not import extension contributors (exception: No module named 'gitdb.utils.compat')
##[error]Process completed with exit code 2.
```

We did not encounter this error during the setup, https://github.com/pandas-dev/pandas/pull/31156/checks?check_run_id=411825801. I do not have a specific idea to which this refers. @jorisvandenbossche, do you have an idea?

**Comment by jorisvandenbossche** [comment]
See https://github.com/pandas-dev/pandas/issues/32060

**Comment by TomAugspurger** [comment]
@pcandoalmeida can you merge master and re-push? Then CI should be passing.

**Comment by pcandoalmeida** [comment]
Hi @TomAugspurger I've merged master and pushed now. Thanks!

**Comment by simonjayhawkins** [comment]
Thanks @pcandoalmeida

**Pull request merged**
