### PR TITLE
ENH: storage_options for to_excel

### PR DESCRIPTION
**Pull request by twoertwein**
- [ ] ref #33987 (follow up to #37639)
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry: not added, already implied in whatsnew of #37639?

### CODE REVIEW

**Comment by jreback** [comment]
thanks @twoertwein

**Comment by twoertwein** [comment]
is there a way to re-use documentation? We have blocks about compression storage_options in many places. It would be cool to have them in one place and then import them.

**Comment by jreback** [comment]
> is there a way to re-use documentation? We have blocks about compression storage_options in many places. It would be cool to have them in one place and then import them.

yes for sure, we have the _shared_docs infrastructure, but for excel its prob enough just to use the Appenders

**Comment by alimcmaster1** [comment]
Think this broke CI - https://github.com/pandas-dev/pandas/pull/37818/checks?check_run_id=1399068710 - opening up a fix

**Comment by twoertwein** [comment]
oh yes! I think a pytest.importorskip should fix this. @alimcmaster1  Are you already making a PR?

**Pull request merged**
