### PR TITLE
Improve document for **kwargs argument of pandas.DataFrame.to_markdown

### LINKED ISSUE #34568: DOC: The argument of pandas.DataFrame.to_markdown is unfriendly
#### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_markdown.html

#### Documentation problem

The document of `pandas.DataFrame.to_markdown` is unfriendly because many options are shown as `**kwargs`.
I think these arguments should be documented explicitly like a `to_csv`.

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_csv.html

#### Suggested fix for documentation

All arguments supported by `to_markdown` should be shown at document.
If don't mind, I would like to tackle this improvement.

### PR DESCRIPTION
**Pull request by nuka137**
- [x] closes #34568 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm @TomAugspurger

**Comment by WillAyd** [comment]
Sorry thought Tom implemented the to_markdown but looks like it was @MarcoGorelli - does this look good to you?

**Comment by MarcoGorelli** [comment]
> Sorry thought Tom implemented the to_markdown but looks like it was @MarcoGorelli

Well, it was me but with the core team holding my hand through the process :)

> does this look good to you?

LGTM, tried building it and the link works as expected

**Comment by WillAyd** [comment]
Great thanks @nuka137

**Pull request merged**
