### PR TITLE
Backport PR #35852 on branch 1.1.x (API: replace dropna=False option with na_sentinel=None in factorize)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #35852: API: replace dropna=False option with na_sentinel=None in factorize

### CODE REVIEW

**Comment by jreback** [comment]
@charlesdong1991 and can merge this when green as well

**Comment by simonjayhawkins** [comment]
> @charlesdong1991 and can merge this when green as well

and when merging on the backport branch ensure that Co-authored-by: Kaiqi Dong <kaiqi@kth.se> or whoever the author is is included otherwise they won't appear in the contributors list

**Comment by charlesdong1991** [comment]
may I kindly ask how to check if the author is included in this case? 😅  @simonjayhawkins

**Comment by simonjayhawkins** [comment]
when you click on confirm squash and merge you'll see

image

so the the co-author is included automatically. just need to ensure that if cleaning the description that you don't remove the co-author (i.e. the original author)

**Comment by charlesdong1991** [comment]
yep, get it! thanks very much! @simonjayhawkins

**Pull request merged**
