### PR TITLE
DEPR: dropna multiple axes, fillna int for td64, from_codes with floats, Series.nonzero

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by jreback — APPROVED** [review]
lgtm ping on green.

**Comment by jbrockmendel** [comment]
ping

**Comment by jreback** [comment]
one more rebase and ping on green.

**Comment by jbrockmendel** [comment]
ping

**Comment by jbrockmendel** [comment]
rebased+green

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
