### PR TITLE
setup.py Simplifications

### PR DESCRIPTION
**Pull request by WillAyd**
Just a smattering of things that I doubt anyone is using

### CODE REVIEW

**Comment by jbrockmendel** [comment]
The cython coverage is worthwhile, There’s an issue about running it nightly.

**Comment by jbrockmendel** [comment]
now with an actual keyboard: I periodically do a run with cython coverage enabled to see what parts of the cython code can be trimmed.   Moreover, ours is IMO the clearest example for other projects to use on how to enable cython coverage.

**Comment by WillAyd** [comment]
Sounds good - I’ll scale this back on next iteration

**Comment by WillAyd** [comment]
Closing for now to keep queue down; can reopen later

**Pull request closed without merging**
