### PR TITLE
BUG: Fix #15344 by backporting ujson usage of PEP 393 API

### LINKED ISSUE #15344: Calling DataFrame.to_json() increases data frame memory usage in Python 3.6
#### Code Sample, a copy-pastable example if possible

```python
Python 3.6.0 (default, Dec 29 2016, 21:40:24) 
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> df = pd.DataFrame({'a': [str(i) for i in range(10000)]})
>>> df.memory_usage(index=True, deep=True)
Index        80
a        608890
dtype: int64
>>> j = df.to_json()
>>> df.memory_usage(index=True, deep=True)
Index        80
a        804450
dtype: int64
```

Compared to Python 2.7.12
```python
Python 2.7.12 (default, Jul 18 2016, 15:02:52) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> df = pd.DataFrame({'a': [str(i) for i in range(10000)]})
>>> df.memory_usage(index=True, deep=True)
Index        72
a        488890
dtype: int64
>>> j = df.to_json()
>>> df.memory_usage(index=True, deep=True)
Index        72
a        488890
dtype: int64
```

#### Problem description
Calling `to_json` should not have any impact on the reported memory usage of a DataFrame. Just like in Python 2. The observed increase above is 32% which is really high.

This only seems to happen with dataframes that have strings in them.

I've also tested calling `to_csv`, that does not trigger this behaviour.

Furthermore it seems like the memory usage is quite a lot higher in Python 3 compared to the equivalent data frame in Python 2 (~25% in the example above). I guess this is more related to strings in Python 2 vs Python 3 than Pandas though?

#### Expected Output
No change in reported memory usage after calling `to_json`.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-83-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 34.1.0
Cython: None
numpy: 1.12.0
scipy: None
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.2
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by tobgu**
Make use of the PEP 393 API to avoid expanding single byte ascii characters into four byte unicode characters when encoding objects to json.

 - [ ] closes #15344
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. can you add a whatsnew note? (Bug fix is fine)

**Comment by jreback** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/200143310

we have a c-linter :<

**Comment by tobgu** [comment]
Ouch :-). Hopefully fixed now.

**Comment by jreback** [comment]
thanks @tobgu 

keep em coming!

I am still puzzled why the encoding of a new UTF8 string, that returns a new reference is affecting existing references. Though this maybe some deep things going on that I don't understand. If you have time I would search / post an issue on CPython to understand the semantics here. Its also possible that this is the reason this function is being deprecated (because of these side effects).

```
PyObject* PyUnicode_EncodeUTF8(const Py_UNICODE *s, Py_ssize_t size, const char *errors)
Return value: New reference.
Encode the Py_UNICODE buffer s of the given size using UTF-8 and return a Python bytes object. Return NULL if an exception was raised by the codec.

Part of the old-style Py_UNICODE API; please migrate to using PyUnicode_AsUTF8String() or PyUnicode_AsUTF8AndSize().
Deprecated since version 3.3, will be removed in version 4.0.
```

**Comment by tobgu** [comment]
I think the culprit in this case is the `PyUnicode_AS_UNICODE` macro that's described as inefficient and something you should migrate away from:
https://www.python.org/dev/peps/pep-0393/#porting-guidelines
https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AS_UNICODE

It seems like there's actually an allocation for a full strlen*4 byte unicode string here that would be the root cause of the observed behaviour:
https://github.com/python/cpython-mirror/blob/9aa885c9df5b6895f70272b6abc24ef0b1fb8b46/Objects/unicodeobject.c#L4089

Haven't dug into it further than that...

Thanks @jreback and @chris-b1 for helping out with this! It would have been a show stopper for the application that I'm currently working on. Hope to see it released soon! :-)

**Comment by jreback** [comment]
thanks for looking @tobgu, that is some *nasty* code.

**Pull request closed without merging**
