### PR TITLE
DOC: local py.typed for users

### PR DESCRIPTION
**Pull request by twoertwein**
xref https://github.com/pandas-dev/pandas/pull/44223#issuecomment-954672983

### CODE REVIEW

**Comment by twoertwein** [comment]
Starting with 1.4, it might be useful to slowly start advertising pandas's built-in type annotations (before pandas becomes a py.typed library). Specifically, I can imagine informing the maintainers of https://github.com/microsoft/pylance-release They have often pandas type issues as pylance ships the Microsoft type stubs.

Could maybe even have a note in the whatsnew?

**Comment by jreback** [comment]
happy to have a section in the whats new and the docs as well

**Comment by jreback** [comment]
can you merge master

**Comment by twoertwein** [comment]
@jreback  green'ish, doc seems to fail on master as well

**Comment by twoertwein** [comment]
I don't think it makes sense to advertise experimenting with a local `py.typed` at the moment. People who will test it will be swamped in error messages. I tested it with my own code: many functions return a Union instead of using overloads (`read_csv`, basically all functions taking `inplace`, and indexing with list-like vs. scalars).

I think the earliest it makes sense to advertise experiments with `py.typed` is with 2.0 (when we can make most arguments keyword-only arguments: makes most overloads possible).

**Comment by jreback** [comment]
thanks @twoertwein this is good.

**Pull request merged**
