### PR TITLE
CI: disable numpydev job

### PR DESCRIPTION
**Pull request by TomAugspurger**
xref https://github.com/pandas-dev/pandas/issues/30043.
Will take some time to fix all these cases.

### CODE REVIEW

**Comment by jreback** [comment]
thanks @TomAugspurger

**Comment by jreback** [comment]
merge on green.

**Comment by jreback** [comment]
grr
```
pandas/core/generic.py:9129: error: Item "None" of "Optional[DateOffset]" has no attribute "rule_code"
```
must be something i merged recently

**Comment by TomAugspurger** [comment]
Fixing the mypy issue in https://github.com/pandas-dev/pandas/pull/30049/commits/dd6b8171e549b498cda4c5d532d0e9f30cc2b2a5.

**Comment by jreback** [comment]
thanks @TomAugspurger

**Pull request merged**
