### PR TITLE
Removed is_sparse_array from objToJSON

### PR DESCRIPTION
**Pull request by WillAyd**
@jbrockmendel @jorisvandenbossche

### CODE REVIEW

**Comment by jbrockmendel** [comment]
i couldve sworn i did that in the other PR.  did i screw up?

**Comment by WillAyd** [comment]
Are you thinking #29989 or another PR? If former I don't see this module touched in there; know we discussed it I assumed left to follow up

**Comment by jbrockmendel** [comment]
#29989, yah, i even commented here https://github.com/pandas-dev/pandas/pull/29989#issuecomment-561874530 that i had removed is_sparse_array

**Comment by jbrockmendel** [comment]
mystery notwithstanding, LGTM

**Comment by jreback** [comment]
thanks @WillAyd 
do we actually tests that .to_json() with EAs? is this supported in any way currently?

**Pull request merged**
