### PR TITLE
BUG: boolean/string value in OdsWriter (#54994)

### LINKED ISSUE #54994: BUG: boolean/string in OdsWriter
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.DataFrame([[True, "string", 1, 1.0]]).to_excel("output.ods")
```

### Issue Description

OdsWriter doesn't follow [specification](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#refTable13) when writing boolean/string value (passing those values in `office:value` attribute of `table-cell`). Below screenshot from `content.xml` and LibreOffice, which can't represent bad boolean.

image

### Expected Behavior

Boolean value in `office:value-boolean` and string value in `office:string-value` attributes.

image

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 6980379c251716a14f990c7c1b935822a1a6165b
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 6.2.0-31-generic
Version             : #31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.1+0.g6980379c25.dirty
numpy               : 1.24.4
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 59.6.0
pip                 : 23.2.1
Cython              : 0.29.33
pytest              : 7.4.1
hypothesis          : 6.83.2
sphinx              : 6.2.1
blosc               : 1.11.1
feather             : None
xlsxwriter          : 3.1.2
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : 1.4.6
psycopg2            : 2.9.7
jinja2              : 3.1.2
IPython             : 8.15.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
dataframe-api-compat: None
fastparquet         : 2023.8.0
fsspec              : 2023.9.0
gcsfs               : 2023.9.0
matplotlib          : 3.7.2
numba               : 0.57.1
numexpr             : 2.8.5
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : 1.2.3
pyxlsb              : 1.0.10
s3fs                : 2023.9.0
scipy               : 1.11.2
sqlalchemy          : 2.0.20
tables              : 3.8.0
tabulate            : 0.9.0
xarray              : 2023.8.0
xlrd                : 2.0.1
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

### PR DESCRIPTION
**Pull request by dimastbk**
- [x] closes #54994
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests)
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by WillAyd** [comment]
Can you add a test for this? I don't fully understand the issue from the changelog alone

**Comment by dimastbk** [comment]
I added test. Also bug is described in #54994.

**Review by WillAyd — APPROVED** [review]
looks reasonable. @rhshadrach care to look as well?

**Review by rhshadrach — APPROVED** [review]
lgtm

**Comment by rhshadrach** [comment]
@dimastbk - can you merge main here; I'd like to just make sure the tests pass with #54998 now in main.

**Comment by dimastbk** [comment]
I merged main and removed 3 xfails from tests.

**Pull request merged**
