### PR TITLE
BENCH : Added benchmark for indexing with .loc for sorted/unsorted DatetimeIndex

### LINKED ISSUE #38690: ASV: Add benchmark for indexing with .loc for sorted/unsorted DatetimeIndex
xref #17754, a benchmark should be added for indexing with .loc for sorted/unsorted `DatetimeIndex`. With a constructed `DatetimeIndex`, for example

```python
dates = pd.date_range('2011-1-1', periods=500000, freq='min')
index = np.random.choice(dates, 500000, replace=True)
df = pd.DataFrame(index=index, data={'a': 1})
df_sorted = df.sort_index()
```

the behavior of interest to benchmark is
```python
df.loc['2011-6-11']
```
and 
```python
df_sorted.loc['2011-6-11']
```

### PR DESCRIPTION
**Pull request by sonalprabhu**
- [x] closes #38690

### CODE REVIEW

**Comment by sonalprabhu** [comment]
@github-actions pre-commit

**Review by mzeitlin11 — COMMENTED** [review]
Thanks for the pr @sonalprabhu! Generally looks good, some small comments.

Can you also please post the results of running the benchmark so that we can make sure it's not too long?

**Comment by jreback** [comment]
pls merge master and update to comments

**Comment by sonalprabhu** [comment]
@github-actions pre-commit

**Comment by jreback** [comment]
@sonalprabhu can you merge master again. i think this PR is failing the asv's themselves, so pls test locally.

**Comment by mroeschke** [comment]
Thanks for the PR but it appears to have gone stale. If interested in continuing please merge the main branch and address the failing benchmark  and we can reopen.

**Pull request closed without merging**
