### PR TITLE
CLN: Consistent pandas.util.testing imports in pandas/tests/series

### PR DESCRIPTION
**Pull request by SaturnFromTitan**
Part of #29272

- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jbrockmendel** [comment]
lgtm

**Review by WillAyd — APPROVED** [review]
lgtm as well @jreback

**Comment by jbrockmendel** [comment]
Merge conflicts are going to pile up if we dont merge this promptly, merging.

**Comment by jbrockmendel** [comment]
Thanks @SaturnFromTitan

**Pull request merged**
