### PR TITLE
Raising ValueError when xlim and ylim contain non-int and non-float dtype elements #40889

### LINKED ISSUE #40781: BUG:
- [ * ] I have checked that this issue has not already been reported.

- [ * ] I have confirmed this bug exists on the latest version of pandas.

- [ * ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
df = pd.read_csv(myfile) #contains 2 columns, Time in ms and Voltage in mV
xlabel = "Time in ms"
ylabel = "Volate in mV"
xlim = [0,120]
ylim = [0,8]
df.plot(x = "Time", xlabel= xlabel, ylabel=ylabel, xlim = xlim, ylim = ylim, kind="line")
plt.show()
```

#### Problem description

I am plotting a large dataset using `dataframe.plot()` in pandas. Dataset contains data in csv format. As per documentation, I specify `xlim `and `ylim` as arg in df.plot. Now the axes take the xlim and ylim values accordingly but the figure does not scale to these values and plot shows some part of of graph but not the area defined by 'xlim' and 'ylim'.

without xlim : [image](https://i.stack.imgur.com/9lOzI.png)
with xlim set : [image](https://i.stack.imgur.com/d2dAL.png)
sample files here: [samples](https://github.com/regmibijay/opencarp-analyzer/tree/main/samples)
project: [project](https://github.com/regmibijay/opencarp-analyzer)
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-19041-Microsoft
Version          : #488-Microsoft Mon Sep 01 13:43:00 PST 2020
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.3
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
</details>

### PR DESCRIPTION
**Pull request by regmibijay**
- [x] closes #40781 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]

**Comment by jreback** [comment]
pls merge master and update to comments

**Comment by jreback** [comment]
can you merge master i think there are some comments as well

**Comment by regmibijay** [comment]
> can you merge master i think there are some comments as well

Sorry for not updating this pr for a while, while I have worked on other issues, I have been strugglig with a proper place to move my tests to. I just cant wrap my head around where the perfect spot would be. I would be very thankful for some tips. Other changes will be merged accordingly.

**Comment by jreback** [comment]
needs to be passing and pls merge master

**Comment by jbrockmendel** [comment]
> a proper place to move my tests to

grepping for .plot.line i see several in tests.plotting.frame.test_frame, that would be a good place to start

**Comment by mroeschke** [comment]
Thanks for the PR but appears to have gone stale. If interested in continuing, please merge the main branch and address the review and we can reopen.

**Pull request closed without merging**
