### PR TITLE
Revert "CI: workaround numpydev bug (#29433)"

### LINKED ISSUE #29432: CI: Numpydev failing
I can reproduce with numpy master

```
==================================== ERRORS ====================================
__________ ERROR collecting pandas/tests/arrays/sparse/test_array.py ___________
pandas/tests/arrays/sparse/test_array.py:22: in <module>
    class TestSparseArray:
pandas/tests/arrays/sparse/test_array.py:511: in TestSparseArray
    dtype=SparseDtype("datetime64[ns]", pd.Timestamp("1970")),
pandas/core/arrays/sparse/array.py:364: in __init__
    data, kind=kind, fill_value=fill_value, dtype=dtype
pandas/core/arrays/sparse/array.py:1584: in make_sparse
    sparsified_values = arr[mask]
E   IndexError: arrays used as indices must be of integer (or boolean) type
--------- generated xml file: /home/vsts/work/1/s/test-data-single.xml ---------
========================== slowest 10 test durations ===========================
```

```python
(Pdb) pp arr
array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000001'],
      dtype='datetime64[ns]')
(Pdb) pp fill_value
Timestamp('1970-01-01 00:00:00')
(Pdb) pp arr != fill_value
array([True, True], dtype=object)
```

Previously, that was bool dtype

```python
In [6]: np.array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000001'],
   ...:       dtype='datetime64[ns]') == pd.Timestamp('1970-01-01 00:00:00')
Out[6]: array([False, False])
```

### PR DESCRIPTION
**Pull request by TomAugspurger**
This reverts commit b4adb71aee21fcbda3fed32471c60817a8bd5c9f.

Closes #29432

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Hmm a few warnings snuck in.

@jorisvandenbossche is fixing some in #29549 .

I won't have time today or tomorrow for the rest. Anyone able to push fixes to my branch?

**Comment by jbrockmendel** [comment]
at least some of these look like the result of #29517; ill see what i can do about it

**Comment by jbrockmendel** [comment]
pushed a hopeful-fix, will see how it goes

**Comment by jreback** [comment]
lgtm. any perf implications? (IOW now we have to catch *moar* warnings)?

**Comment by jbrockmendel** [comment]
> any perf implications? (IOW now we have to catch moar warnings)?

It shouldn't be any worse than the previous solution we had in place that did specific dtype checks to prevent the warnings.

**Comment by TomAugspurger** [comment]
I'm not sure we should be filtering the warnings like this. IIUC this may break in the future when NumPy enforces their deprecation.

I don't know enough of the context for https://github.com/pandas-dev/pandas/pull/29517/files, but we don't want the behavior to silently change for the user. If we like the change from NumPy, then we should not filter the warnings. If we don't like it (say because we need more flexible dtype comparison) then I think we need to restore some of the checks in #29517 (again, I haven't read through the changes there in detail).

**Comment by jbrockmendel** [comment]
Tom makes a fair point.  I'd be OK with reverting #29517 since having this build is clearly more important.

**Comment by jreback** [comment]
what if we filter on the specific warning, is that better?

**Comment by jbrockmendel** [comment]
just pushed a commit that restored the checks that were removed by #29517.  I may try to remove them again someday, but getting this build back up is a higher priority

**Comment by jreback** [comment]
do we need this?

**Comment by TomAugspurger** [comment]
"This" being the commit Brock pushed up in https://github.com/pandas-dev/pandas/pull/29553#issuecomment-554589699? I think so... That at least gets us back to where we were, and gets us testing against numpydev again.

**Comment by jreback** [comment]
> "This" being the commit Brock pushed up in [#29553 (comment)](https://github.com/pandas-dev/pandas/pull/29553#issuecomment-554589699)? I think so... That at least gets us back to where we were, and gets us testing against numpydev again.

right. i guess if you can rebase this and see

**Comment by TomAugspurger** [comment]
Merged master.

**Comment by jbrockmendel** [comment]
this should be good to go?

**Comment by jreback** [comment]
thanks @TomAugspurger and @jbrockmendel 

maybe open a followup issue to re-remove this at some point if possible?

**Pull request merged**
