### PR TITLE
CLN: remove split_and_operate in Block.fillna

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
I didn't see any tests failing locally, so checking here with full CI.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jbrockmendel do you have an idea of what case would need the `split_and_operate` for `Block.fillna`? Because if it's needed, it's clearly not covered by the tests.

**Comment by jbrockmendel** [comment]
> do you have an idea of what case would need the split_and_operate for Block.fillna? Because if it's needed, it's clearly not covered by the tests.

None comes to mind.  Best guess is that for object dtype cases a splitting needs to occur at somewhere in the call stack, and in this case it happens later on even if it doesn't happen here.

Happy to see this go away!

**Comment by jreback** [comment]
lgtm. we have *nothing* hit that codepath?

**Comment by jorisvandenbossche** [comment]
Unfortunately, I just thought of a case:

```
df = pd.DataFrame({'a': [0.1, 0.1, np.nan], 'b': [0.1, 0.2, 0.3]})
df.fillna("string")
```

When splitting, this will only convert the column with missing values to object. But with this PR, it will convert the full block to object dtype to then infer and convert back to numeric the columns that didn't have missing values. So the splitting actually does serve some purpose here.

**Comment by jbrockmendel** [comment]
should make a test case out of this?

**Comment by jorisvandenbossche** [comment]
The end result is the same, so I don't think we can test it with a normal test (a benchmark might catch it)

**Comment by jbrockmendel** [comment]
im not sure i understand.  isnt the `df.fillna("string")` case one that works in master and fails under this PR?  (and if not, why would finding it be a reason to close this PR?)

**Comment by jorisvandenbossche** [comment]
No, it doesn't fail here, because we will convert to object dtype but then afterwards infer again to float (for columns that didn't have any NaN). So as mentioned above, the *end result* is the same, but it would be achieved with an additional (unnecessary) conversion float -> object -> infer as float.

**Pull request closed without merging**
