### PR TITLE
CLN: ASV offset

### PR DESCRIPTION
**Pull request by mroeschke**
- Consolidated all the offsets to a list that was reused for all the benchmarks.

- The `ApplyIndex` benchmark seemed to be benchmarking arithmetic, so I changed it to specifically use the `apply_index()` method

```
$ asv dev -b ^offset
· Discovering benchmarks
· Running 10 total benchmarks (1 commits * 1 environments * 10 benchmarks)
[  0.00%] ·· Building for existing-py_home_matt_anaconda_envs_pandas_dev_bin_python
[  0.00%] ·· Benchmarking existing-py_home_matt_anaconda_envs_pandas_dev_bin_python
[ 10.00%] ··· Running offset.ApplyIndex.time_apply_index                              ok
[ 10.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                            <YearEnd: month=12>               173ms  
                            <YearBegin: month=1>              6.94ms 
                       <QuarterEnd: startingMonth=3>          194ms  
                      <QuarterBegin: startingMonth=3>         7.15ms 
                                 <MonthEnd>                   1.28ms 
                                <MonthBegin>                  1.19ms 
                <DateOffset: kwds={'months': 2, 'days': 2}>   2.45ms 
                               <BusinessDay>                  136ms  
                      <SemiMonthEnd: day_of_month=15>         138ms  
                     <SemiMonthBegin: day_of_month=15>        140ms  
               ============================================= ========

[ 20.00%] ··· Running offset.OffestDatetimeArithmetic.time_add                        ok
[ 20.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      106μs  
                        <BusinessYearEnd: month=12>           202μs  
                        <BusinessYearBegin: month=1>          123μs  
                   <BusinessQuarterEnd: startingMonth=3>      105μs  
                  <BusinessQuarterBegin: startingMonth=3>     124μs  
                             <BusinessMonthEnd>               121μs  
                            <BusinessMonthBegin>              138μs  
                            <CustomBusinessDay>               89.2μs 
                            <CustomBusinessDay>               89.6μs 
                         <CustomBusinessMonthBegin>           415μs  
                          <CustomBusinessMonthEnd>            442μs  
                          <CustomBusinessMonthEnd>            422μs  
                            <YearEnd: month=12>               63.0μs 
                            <YearBegin: month=1>              61.7μs 
                       <QuarterEnd: startingMonth=3>          105μs  
                      <QuarterBegin: startingMonth=3>         150μs  
                                 <MonthEnd>                   176μs  
                                <MonthBegin>                  121μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   69.2μs 
                               <BusinessDay>                  84.9μs 
                      <SemiMonthEnd: day_of_month=15>         179μs  
                     <SemiMonthBegin: day_of_month=15>        177μs  
               ============================================= ========

[ 30.00%] ··· Running offset.OffestDatetimeArithmetic.time_add_10                     ok
[ 30.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      121μs  
                        <BusinessYearEnd: month=12>           161μs  
                        <BusinessYearBegin: month=1>          162μs  
                   <BusinessQuarterEnd: startingMonth=3>      207μs  
                  <BusinessQuarterBegin: startingMonth=3>     137μs  
                             <BusinessMonthEnd>               141μs  
                            <BusinessMonthBegin>              156μs  
                            <CustomBusinessDay>               111μs  
                            <CustomBusinessDay>               121μs  
                         <CustomBusinessMonthBegin>           458μs  
                          <CustomBusinessMonthEnd>            464μs  
                          <CustomBusinessMonthEnd>            461μs  
                            <YearEnd: month=12>               129μs  
                            <YearBegin: month=1>              99.1μs 
                       <QuarterEnd: startingMonth=3>          115μs  
                      <QuarterBegin: startingMonth=3>         219μs  
                                 <MonthEnd>                   192μs  
                                <MonthBegin>                  148μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   280μs  
                               <BusinessDay>                  101μs  
                      <SemiMonthEnd: day_of_month=15>         187μs  
                     <SemiMonthBegin: day_of_month=15>        185μs  
               ============================================= ========

[ 40.00%] ··· Running offset.OffestDatetimeArithmetic.time_apply                      ok
[ 40.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      98.1μs 
                        <BusinessYearEnd: month=12>           192μs  
                        <BusinessYearBegin: month=1>          116μs  
                   <BusinessQuarterEnd: startingMonth=3>      96.5μs 
                  <BusinessQuarterBegin: startingMonth=3>     116μs  
                             <BusinessMonthEnd>               118μs  
                            <BusinessMonthBegin>              129μs  
                            <CustomBusinessDay>               79.8μs 
                            <CustomBusinessDay>               81.3μs 
                         <CustomBusinessMonthBegin>           526μs  
                          <CustomBusinessMonthEnd>            416μs  
                          <CustomBusinessMonthEnd>            414μs  
                            <YearEnd: month=12>               53.1μs 
                            <YearBegin: month=1>              51.8μs 
                       <QuarterEnd: startingMonth=3>          95.0μs 
                      <QuarterBegin: startingMonth=3>         137μs  
                                 <MonthEnd>                   165μs  
                                <MonthBegin>                  113μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   61.1μs 
                               <BusinessDay>                  76.8μs 
                      <SemiMonthEnd: day_of_month=15>         170μs  
                     <SemiMonthBegin: day_of_month=15>        168μs  
               ============================================= ========

[ 50.00%] ··· Running offset.OffestDatetimeArithmetic.time_apply_np_dt64              ok
[ 50.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      104μs  
                        <BusinessYearEnd: month=12>           199μs  
                        <BusinessYearBegin: month=1>          121μs  
                   <BusinessQuarterEnd: startingMonth=3>      105μs  
                  <BusinessQuarterBegin: startingMonth=3>     123μs  
                             <BusinessMonthEnd>               121μs  
                            <BusinessMonthBegin>              137μs  
                            <CustomBusinessDay>               86.2μs 
                            <CustomBusinessDay>               88.0μs 
                         <CustomBusinessMonthBegin>           411μs  
                          <CustomBusinessMonthEnd>            420μs  
                          <CustomBusinessMonthEnd>            421μs  
                            <YearEnd: month=12>               60.4μs 
                            <YearBegin: month=1>              58.5μs 
                       <QuarterEnd: startingMonth=3>          103μs  
                      <QuarterBegin: startingMonth=3>         119μs  
                                 <MonthEnd>                   174μs  
                                <MonthBegin>                  118μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   69.0μs 
                               <BusinessDay>                  82.6μs 
                      <SemiMonthEnd: day_of_month=15>         178μs  
                     <SemiMonthBegin: day_of_month=15>        173μs  
               ============================================= ========

[ 60.00%] ··· Running offset.OffestDatetimeArithmetic.time_subtract                   ok
[ 60.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      125μs  
                        <BusinessYearEnd: month=12>           165μs  
                        <BusinessYearBegin: month=1>          165μs  
                   <BusinessQuarterEnd: startingMonth=3>      117μs  
                  <BusinessQuarterBegin: startingMonth=3>     136μs  
                             <BusinessMonthEnd>               145μs  
                            <BusinessMonthBegin>              144μs  
                            <CustomBusinessDay>               114μs  
                            <CustomBusinessDay>               105μs  
                         <CustomBusinessMonthBegin>           380μs  
                          <CustomBusinessMonthEnd>            564μs  
                          <CustomBusinessMonthEnd>            569μs  
                            <YearEnd: month=12>               104μs  
                            <YearBegin: month=1>              104μs  
                       <QuarterEnd: startingMonth=3>          114μs  
                      <QuarterBegin: startingMonth=3>         130μs  
                                 <MonthEnd>                   209μs  
                                <MonthBegin>                  140μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   129μs  
                               <BusinessDay>                  85.2μs 
                      <SemiMonthEnd: day_of_month=15>         191μs  
                     <SemiMonthBegin: day_of_month=15>        188μs  
               ============================================= ========

[ 70.00%] ··· Running offset.OffestDatetimeArithmetic.time_subtract_10                ok
[ 70.00%] ···· 
               ============================================= =======
                                   offset                           
               --------------------------------------------- -------
                                   <Day>                      139μs 
                        <BusinessYearEnd: month=12>           198μs 
                        <BusinessYearBegin: month=1>          196μs 
                   <BusinessQuarterEnd: startingMonth=3>      126μs 
                  <BusinessQuarterBegin: startingMonth=3>     146μs 
                             <BusinessMonthEnd>               157μs 
                            <BusinessMonthBegin>              158μs 
                            <CustomBusinessDay>               144μs 
                            <CustomBusinessDay>               114μs 
                         <CustomBusinessMonthBegin>           386μs 
                          <CustomBusinessMonthEnd>            482μs 
                          <CustomBusinessMonthEnd>            478μs 
                            <YearEnd: month=12>               156μs 
                            <YearBegin: month=1>              136μs 
                       <QuarterEnd: startingMonth=3>          123μs 
                      <QuarterBegin: startingMonth=3>         140μs 
                                 <MonthEnd>                   210μs 
                                <MonthBegin>                  154μs 
                <DateOffset: kwds={'months': 2, 'days': 2}>   516μs 
                               <BusinessDay>                  115μs 
                      <SemiMonthEnd: day_of_month=15>         197μs 
                     <SemiMonthBegin: day_of_month=15>        195μs 
               ============================================= =======

[ 80.00%] ··· Running offset.OffsetDatetimeIndexArithmetic.time_add_offset            ok
[ 80.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      1.14ms 
                        <BusinessYearEnd: month=12>           1.97s  
                        <BusinessYearBegin: month=1>          1.08s  
                   <BusinessQuarterEnd: startingMonth=3>      920ms  
                  <BusinessQuarterBegin: startingMonth=3>     1.10s  
                             <BusinessMonthEnd>               1.07s  
                            <BusinessMonthBegin>              1.14s  
                            <CustomBusinessDay>               752ms  
                            <CustomBusinessDay>               754ms  
                         <CustomBusinessMonthBegin>           4.56s  
                          <CustomBusinessMonthEnd>            4.04s  
                          <CustomBusinessMonthEnd>            4.02s  
                            <YearEnd: month=12>               172ms  
                            <YearBegin: month=1>              7.10ms 
                       <QuarterEnd: startingMonth=3>          191ms  
                      <QuarterBegin: startingMonth=3>         7.13ms 
                                 <MonthEnd>                   1.48ms 
                                <MonthBegin>                  1.40ms 
                <DateOffset: kwds={'months': 2, 'days': 2}>   3.09ms 
                               <BusinessDay>                  137ms  
                      <SemiMonthEnd: day_of_month=15>         141ms  
                     <SemiMonthBegin: day_of_month=15>        136ms  
               ============================================= ========

[ 90.00%] ··· Running offset.OffsetSeriesArithmetic.time_add_offset                   ok
[ 90.00%] ···· 
               ============================================= =======
                                   offset                           
               --------------------------------------------- -------
                                   <Day>                      416ms 
                        <BusinessYearEnd: month=12>           2.39s 
                        <BusinessYearBegin: month=1>          1.50s 
                   <BusinessQuarterEnd: startingMonth=3>      1.34s 
                  <BusinessQuarterBegin: startingMonth=3>     1.51s 
                             <BusinessMonthEnd>               1.49s 
                            <BusinessMonthBegin>              1.56s 
                            <CustomBusinessDay>               1.17s 
                            <CustomBusinessDay>               1.18s 
                         <CustomBusinessMonthBegin>           5.02s 
                          <CustomBusinessMonthEnd>            4.49s 
                          <CustomBusinessMonthEnd>            4.46s 
                            <YearEnd: month=12>               588ms 
                            <YearBegin: month=1>              426ms 
                       <QuarterEnd: startingMonth=3>          611ms 
                      <QuarterBegin: startingMonth=3>         425ms 
                                 <MonthEnd>                   422ms 
                                <MonthBegin>                  420ms 
                <DateOffset: kwds={'months': 2, 'days': 2}>   422ms 
                               <BusinessDay>                  549ms 
                      <SemiMonthEnd: day_of_month=15>         559ms 
                     <SemiMonthBegin: day_of_month=15>        561ms 
               ============================================= =======

[100.00%] ··· Running offset.OnOffset.time_on_offset                                  ok
[100.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      28.1μs 
                        <BusinessYearEnd: month=12>           6.93ms 
                        <BusinessYearBegin: month=1>          5.21ms 
                   <BusinessQuarterEnd: startingMonth=3>      5.61ms 
                  <BusinessQuarterBegin: startingMonth=3>     4.61ms 
                             <BusinessMonthEnd>               5.33ms 
                            <BusinessMonthBegin>              34.6μs 
                            <CustomBusinessDay>               409μs  
                            <CustomBusinessDay>               408μs  
                         <CustomBusinessMonthBegin>           16.1ms 
                          <CustomBusinessMonthEnd>            16.3ms 
                          <CustomBusinessMonthEnd>            16.3ms 
                            <YearEnd: month=12>               34.7μs 
                            <YearBegin: month=1>              21.3μs 
                       <QuarterEnd: startingMonth=3>          252μs  
                      <QuarterBegin: startingMonth=3>         4.48ms 
                                 <MonthEnd>                   34.5μs 
                                <MonthBegin>                  18.8μs 
                <DateOffset: kwds={'months': 2, 'days': 2}>   21.4μs 
                               <BusinessDay>                  21.0μs 
                      <SemiMonthEnd: day_of_month=15>         38.6μs 
                     <SemiMonthBegin: day_of_month=15>        22.6μs 
               ============================================= ========
```

### CODE REVIEW

**Comment by jreback** [comment]
can you reduce the add_offset size a bit, so these are in-line to the others?

**Comment by jreback** [comment]
cc @jbrockmendel as you would expect on these?

**Comment by jbrockmendel** [comment]
I don't see anything obviously problematic, but hard to say much without something to compare against.  And even with, you know my thoughts on asv reliability...

**Comment by jreback** [comment]
@mroeschke did you push the smaller n? can you show an update?

**Comment by mroeschke** [comment]
Currently on vacation, but I will be back on the weekend to update the PR

**Comment by mroeschke** [comment]
Reduced the samples for the addition benchmarks by a factor of 10. Additionally changed the current lint rule for asv to capture the files I already cleaned up. 

```
$ asv dev -b ^offset
· Discovering benchmarks
· Running 10 total benchmarks (1 commits * 1 environments * 10 benchmarks)
[  0.00%] ·· Building for existing-py_home_matt_anaconda_envs_pandas_dev_bin_python
[  0.00%] ·· Benchmarking existing-py_home_matt_anaconda_envs_pandas_dev_bin_python
[ 10.00%] ··· Running offset.ApplyIndex.time_apply_index                     ok
[ 10.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                            <YearEnd: month=12>               190ms  
                            <YearBegin: month=1>              9.00ms 
                       <QuarterEnd: startingMonth=3>          209ms  
                      <QuarterBegin: startingMonth=3>         7.55ms 
                                 <MonthEnd>                   1.43ms 
                                <MonthBegin>                  1.22ms 
                <DateOffset: kwds={'months': 2, 'days': 2}>   2.75ms 
                               <BusinessDay>                  138ms  
                      <SemiMonthEnd: day_of_month=15>         145ms  
                     <SemiMonthBegin: day_of_month=15>        148ms  
               ============================================= ========

[ 20.00%] ··· Running offset.OffestDatetimeArithmetic.time_add               ok
[ 20.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      111μs  
                        <BusinessYearEnd: month=12>           211μs  
                        <BusinessYearBegin: month=1>          145μs  
                   <BusinessQuarterEnd: startingMonth=3>      142μs  
                  <BusinessQuarterBegin: startingMonth=3>     151μs  
                             <BusinessMonthEnd>               135μs  
                            <BusinessMonthBegin>              137μs  
                            <CustomBusinessDay>               108μs  
                            <CustomBusinessDay>               90.1μs 
                         <CustomBusinessMonthBegin>           417μs  
                          <CustomBusinessMonthEnd>            489μs  
                          <CustomBusinessMonthEnd>            486μs  
                            <YearEnd: month=12>               125μs  
                            <YearBegin: month=1>              61.1μs 
                       <QuarterEnd: startingMonth=3>          107μs  
                      <QuarterBegin: startingMonth=3>         128μs  
                                 <MonthEnd>                   177μs  
                                <MonthBegin>                  144μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   70.8μs 
                               <BusinessDay>                  96.0μs 
                      <SemiMonthEnd: day_of_month=15>         218μs  
                     <SemiMonthBegin: day_of_month=15>        210μs  
               ============================================= ========

[ 30.00%] ··· Running offset.OffestDatetimeArithmetic.time_add_10            ok
[ 30.00%] ···· 
               ============================================= =======
                                   offset                           
               --------------------------------------------- -------
                                   <Day>                      122μs 
                        <BusinessYearEnd: month=12>           199μs 
                        <BusinessYearBegin: month=1>          162μs 
                   <BusinessQuarterEnd: startingMonth=3>      218μs 
                  <BusinessQuarterBegin: startingMonth=3>     137μs 
                             <BusinessMonthEnd>               146μs 
                            <BusinessMonthBegin>              180μs 
                            <CustomBusinessDay>               135μs 
                            <CustomBusinessDay>               106μs 
                         <CustomBusinessMonthBegin>           462μs 
                          <CustomBusinessMonthEnd>            462μs 
                          <CustomBusinessMonthEnd>            498μs 
                            <YearEnd: month=12>               147μs 
                            <YearBegin: month=1>              116μs 
                       <QuarterEnd: startingMonth=3>          130μs 
                      <QuarterBegin: startingMonth=3>         136μs 
                                 <MonthEnd>                   218μs 
                                <MonthBegin>                  150μs 
                <DateOffset: kwds={'months': 2, 'days': 2}>   346μs 
                               <BusinessDay>                  110μs 
                      <SemiMonthEnd: day_of_month=15>         211μs 
                     <SemiMonthBegin: day_of_month=15>        247μs 
               ============================================= =======

[ 40.00%] ··· Running offset.OffestDatetimeArithmetic.time_apply             ok
[ 40.00%] ···· 
               ============================================= =========
                                   offset                             
               --------------------------------------------- ---------
                                   <Day>                       99.3μs 
                        <BusinessYearEnd: month=12>            193μs  
                        <BusinessYearBegin: month=1>           114μs  
                   <BusinessQuarterEnd: startingMonth=3>      100.0μs 
                  <BusinessQuarterBegin: startingMonth=3>      132μs  
                             <BusinessMonthEnd>                120μs  
                            <BusinessMonthBegin>               130μs  
                            <CustomBusinessDay>                92.6μs 
                            <CustomBusinessDay>                91.8μs 
                         <CustomBusinessMonthBegin>            541μs  
                          <CustomBusinessMonthEnd>             442μs  
                          <CustomBusinessMonthEnd>             415μs  
                            <YearEnd: month=12>                54.1μs 
                            <YearBegin: month=1>               111μs  
                       <QuarterEnd: startingMonth=3>           107μs  
                      <QuarterBegin: startingMonth=3>          124μs  
                                 <MonthEnd>                    201μs  
                                <MonthBegin>                   138μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>    64.9μs 
                               <BusinessDay>                   89.9μs 
                      <SemiMonthEnd: day_of_month=15>          170μs  
                     <SemiMonthBegin: day_of_month=15>         231μs  
               ============================================= =========

[ 50.00%] ··· Running ...OffestDatetimeArithmetic.time_apply_np_dt64         ok
[ 50.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      107μs  
                        <BusinessYearEnd: month=12>           200μs  
                        <BusinessYearBegin: month=1>          131μs  
                   <BusinessQuarterEnd: startingMonth=3>      104μs  
                  <BusinessQuarterBegin: startingMonth=3>     132μs  
                             <BusinessMonthEnd>               144μs  
                            <BusinessMonthBegin>              136μs  
                            <CustomBusinessDay>               98.2μs 
                            <CustomBusinessDay>               101μs  
                         <CustomBusinessMonthBegin>           590μs  
                          <CustomBusinessMonthEnd>            416μs  
                          <CustomBusinessMonthEnd>            418μs  
                            <YearEnd: month=12>               61.0μs 
                            <YearBegin: month=1>              59.6μs 
                       <QuarterEnd: startingMonth=3>          103μs  
                      <QuarterBegin: startingMonth=3>         135μs  
                                 <MonthEnd>                   201μs  
                                <MonthBegin>                  123μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   70.1μs 
                               <BusinessDay>                  92.8μs 
                      <SemiMonthEnd: day_of_month=15>         188μs  
                     <SemiMonthBegin: day_of_month=15>        173μs  
               ============================================= ========

[ 60.00%] ··· Running offset.OffestDatetimeArithmetic.time_subtract          ok
[ 60.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      125μs  
                        <BusinessYearEnd: month=12>           164μs  
                        <BusinessYearBegin: month=1>          162μs  
                   <BusinessQuarterEnd: startingMonth=3>      116μs  
                  <BusinessQuarterBegin: startingMonth=3>     137μs  
                             <BusinessMonthEnd>               146μs  
                            <BusinessMonthBegin>              146μs  
                            <CustomBusinessDay>               143μs  
                            <CustomBusinessDay>               113μs  
                         <CustomBusinessMonthBegin>           454μs  
                          <CustomBusinessMonthEnd>            723μs  
                          <CustomBusinessMonthEnd>            571μs  
                            <YearEnd: month=12>               104μs  
                            <YearBegin: month=1>              103μs  
                       <QuarterEnd: startingMonth=3>          137μs  
                      <QuarterBegin: startingMonth=3>         151μs  
                                 <MonthEnd>                   232μs  
                                <MonthBegin>                  140μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   133μs  
                               <BusinessDay>                  86.1μs 
                      <SemiMonthEnd: day_of_month=15>         192μs  
                     <SemiMonthBegin: day_of_month=15>        188μs  
               ============================================= ========

[ 70.00%] ··· Running ...t.OffestDatetimeArithmetic.time_subtract_10         ok
[ 70.00%] ···· 
               ============================================= =======
                                   offset                           
               --------------------------------------------- -------
                                   <Day>                      159μs 
                        <BusinessYearEnd: month=12>           220μs 
                        <BusinessYearBegin: month=1>          211μs 
                   <BusinessQuarterEnd: startingMonth=3>      187μs 
                  <BusinessQuarterBegin: startingMonth=3>     145μs 
                             <BusinessMonthEnd>               175μs 
                            <BusinessMonthBegin>              160μs 
                            <CustomBusinessDay>               159μs 
                            <CustomBusinessDay>               136μs 
                         <CustomBusinessMonthBegin>           396μs 
                          <CustomBusinessMonthEnd>            583μs 
                          <CustomBusinessMonthEnd>            688μs 
                            <YearEnd: month=12>               176μs 
                            <YearBegin: month=1>              157μs 
                       <QuarterEnd: startingMonth=3>          156μs 
                      <QuarterBegin: startingMonth=3>         144μs 
                                 <MonthEnd>                   211μs 
                                <MonthBegin>                  155μs 
                <DateOffset: kwds={'months': 2, 'days': 2}>   535μs 
                               <BusinessDay>                  115μs 
                      <SemiMonthEnd: day_of_month=15>         198μs 
                     <SemiMonthBegin: day_of_month=15>        244μs 
               ============================================= =======

[ 80.00%] ··· Running ...fsetDatetimeIndexArithmetic.time_add_offset         ok
[ 80.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      908μs  
                        <BusinessYearEnd: month=12>           205ms  
                        <BusinessYearBegin: month=1>          114ms  
                   <BusinessQuarterEnd: startingMonth=3>      95.5ms 
                  <BusinessQuarterBegin: startingMonth=3>     123ms  
                             <BusinessMonthEnd>               113ms  
                            <BusinessMonthBegin>              128ms  
                            <CustomBusinessDay>               79.9ms 
                            <CustomBusinessDay>               80.6ms 
                         <CustomBusinessMonthBegin>           433ms  
                          <CustomBusinessMonthEnd>            435ms  
                          <CustomBusinessMonthEnd>            466ms  
                            <YearEnd: month=12>               21.9ms 
                            <YearBegin: month=1>              4.46ms 
                       <QuarterEnd: startingMonth=3>          24.1ms 
                      <QuarterBegin: startingMonth=3>         4.44ms 
                                 <MonthEnd>                   666μs  
                                <MonthBegin>                  869μs  
                <DateOffset: kwds={'months': 2, 'days': 2}>   1.38ms 
                               <BusinessDay>                  17.5ms 
                      <SemiMonthEnd: day_of_month=15>         19.0ms 
                     <SemiMonthBegin: day_of_month=15>        18.6ms 
               ============================================= ========

[ 90.00%] ··· Running offset.OffsetSeriesArithmetic.time_add_offset          ok
[ 90.00%] ···· 
               ============================================= =======
                                   offset                           
               --------------------------------------------- -------
                                   <Day>                      442ms 
                        <BusinessYearEnd: month=12>           654ms 
                        <BusinessYearBegin: month=1>          560ms 
                   <BusinessQuarterEnd: startingMonth=3>      536ms 
                  <BusinessQuarterBegin: startingMonth=3>     557ms 
                             <BusinessMonthEnd>               596ms 
                            <BusinessMonthBegin>              611ms 
                            <CustomBusinessDay>               532ms 
                            <CustomBusinessDay>               523ms 
                         <CustomBusinessMonthBegin>           868ms 
                          <CustomBusinessMonthEnd>            876ms 
                          <CustomBusinessMonthEnd>            874ms 
                            <YearEnd: month=12>               460ms 
                            <YearBegin: month=1>              443ms 
                       <QuarterEnd: startingMonth=3>          466ms 
                      <QuarterBegin: startingMonth=3>         443ms 
                                 <MonthEnd>                   440ms 
                                <MonthBegin>                  444ms 
                <DateOffset: kwds={'months': 2, 'days': 2}>   446ms 
                               <BusinessDay>                  461ms 
                      <SemiMonthEnd: day_of_month=15>         472ms 
                     <SemiMonthBegin: day_of_month=15>        491ms 
               ============================================= =======

[100.00%] ··· Running offset.OnOffset.time_on_offset                         ok
[100.00%] ···· 
               ============================================= ========
                                   offset                            
               --------------------------------------------- --------
                                   <Day>                      29.8μs 
                        <BusinessYearEnd: month=12>           7.47ms 
                        <BusinessYearBegin: month=1>          6.11ms 
                   <BusinessQuarterEnd: startingMonth=3>      6.04ms 
                  <BusinessQuarterBegin: startingMonth=3>     4.62ms 
                             <BusinessMonthEnd>               5.59ms 
                            <BusinessMonthBegin>              36.3μs 
                            <CustomBusinessDay>               407μs  
                            <CustomBusinessDay>               417μs  
                         <CustomBusinessMonthBegin>           18.4ms 
                          <CustomBusinessMonthEnd>            17.8ms 
                          <CustomBusinessMonthEnd>            18.6ms 
                            <YearEnd: month=12>               36.3μs 
                            <YearBegin: month=1>              21.7μs 
                       <QuarterEnd: startingMonth=3>          252μs  
                      <QuarterBegin: startingMonth=3>         4.80ms 
                                 <MonthEnd>                   37.7μs 
                                <MonthBegin>                  19.5μs 
                <DateOffset: kwds={'months': 2, 'days': 2}>   22.1μs 
                               <BusinessDay>                  21.0μs 
                      <SemiMonthEnd: day_of_month=15>         38.1μs 
                     <SemiMonthBegin: day_of_month=15>        25.1μs 
               ============================================= ========
```

**Comment by jreback** [comment]
thanks!

**Pull request merged**
