### PR TITLE
TST: remove non-strict xfails

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

If/when this gets to green, I'll want to re-run it a few times to make sure it stays that way.

### CODE REVIEW

**Comment by mroeschke** [comment]
FWIW these tests shouldn't be running in the CI currently since we switched to a moto service. This might be only applicable for local runs?

**Review by mroeschke — APPROVED** [review]

**Comment by jbrockmendel** [comment]
if they're not being run on the CI then aren't they kind of pointless?

**Comment by mroeschke** [comment]
These tests should be useful for those who run the test suite locally in which case these tests are still useful.

In theory, if/once CI platforms allows moto service images for non-Linux OSs these tests should be run-able.

**Comment by jbrockmendel** [comment]
Makes sense, thanks.

**Pull request merged**
