### PR TITLE
REF: smarter NaN handling in remove_unused_levels()

### PR DESCRIPTION
**Pull request by toobaz**
- [x] tests passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Sorry for the bad timing @jreback , only after you merged #18426 this simpler way to proceed came to my mind.

### CODE REVIEW

**Comment by jreback** [comment]
thanks! @toobaz 

separately, it might be nice to see (on a bigger MI), how much time this actually takes, if its small then it might be theoretically feasible to actually do this (or at least check whether we need to do this).

**Comment by toobaz** [comment]
> might be theoretically feasible to actually do this

Do you mean to implicitly do this (e.g. when slicing)?

**Comment by jreback** [comment]
yep - seeing if this is feasible

**Comment by toobaz** [comment]
But do we actually want this? E.g. a categorical does not loose categories when it is sliced.

**Comment by jreback** [comment]
it’s actuaiky confusing to users
if it were cheap i think we would (but i don’t think it’s cheap)

**Pull request merged**
