### PR TITLE
CI / BLD: Various CI Backports

### PR DESCRIPTION
**Pull request by gfyoung**
* Pin `blosc` to `1.14.3` (#22429)
* Migrate to CircleCI 2.0 (#21814)
* Pin `openpyxl` to `2.5.5` (#22601)
* Bump `numpy` to `1.9.3` (#22499)
* Fix locale handling (#21739, #22213)
* Upgrade `Cython` to `>=0.28.2` (#21688)

### CODE REVIEW

**Comment by gfyoung** [comment]
@jreback @TomAugspurger : Looks like we need to backport a couple of other things:

* `numpy` version updates (for the `lib.gfortran` errors)
* locale fixes!? (for some reason, `py35_ascii` is picking up way more locales than it does on `master`, causing all of the failures on that build - there are some slight differences in the implementation of `tm.get_locales`, so that might be the cause)

**Comment by gfyoung** [comment]
@jreback @TomAugspurger :

* https://travis-ci.org/pandas-dev/pandas/jobs/426221423

Build keeps timing out.

* https://circleci.com/gh/pandas-dev/pandas/19464 and https://circleci.com/gh/pandas-dev/pandas/19465

Really weird locale failures.

Any thoughts?

**Comment by gfyoung** [comment]
@jreback @TomAugspurger : Tried doing some more investigation, but still not sure where the locale failures are coming from.  I would like to potentially merge everything up to 2b28893 first, which would address the failures I was seeing in #22634.

**Comment by TomAugspurger** [comment]
What's our plan for release? I don't really have a strong desire to do a
0.23.5, especially if it's a pain to backport things.

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/pull/22213 may be the one to fix locales.

**Comment by jreback** [comment]
could pass on 23.5 and just do 24 maybe by end of sept

**Comment by gfyoung** [comment]
> What's our plan for release? I don't really have a strong desire to do a
0.23.5, especially if it's a pain to backport things.

@TomAugspurger : The "pain" of backporting has been due to CI changes that in hindsight should have been backported earlier than later.  I think in the future, we should probably backport changes that either:

* Modify existing CI configurations / scripts
* Modify existing tests / testing utilities

**Comment by gfyoung** [comment]
> #22213 may be the one to fix locales.

@TomAugspurger : Ah, thanks for pointing that out.  Let me see if that solves anything...

**Comment by gfyoung** [comment]
@jreback @TomAugspurger : Well would you look at that?  That seemed to have done the trick!  PTAL.

**Comment by TomAugspurger** [comment]
LGTM at a glance, thanks. Feel free to merge when you're ready (probably rebase & merge since it's a backport branch).

**Comment by gfyoung** [comment]
@TomAugspurger : This is against the `0.23.x` branch, so I think we're good here.

**Pull request merged**
