### PR TITLE
Chooses eval engine automatically depending on whether numexpr is installed

### LINKED ISSUE #12008: Clarify documentation on numexpr in eval / query
So the `query` function calls `eval` under the hood, which ends up meaning that the function call ends failing with the following when numexpr is not present.  This means that the default engine (numexpr) will lead to error on systems without having extra dependencies present.

```
ImportError: 'numexpr' not found. Cannot use engine='numexpr' 
```

I see four solutions, which I list in increasing order of difficulty:

1.  Make the `numexpr` dependency much clearer in the docstrings.  Explicitly say that an ImportError will occur if you use the default arguments without having numexpr installed.
2.  Make the python engine default
3.  Let the numexpr engine fallback on the python engine in the case of import error
4.  Make numexpr a required dependency

*edit* It appears that option (3) is preferred here.

### PR DESCRIPTION
**Pull request by robintw**
Fixes #12008

### CODE REVIEW

**Comment by jreback** [comment]
can you add some tests for this (e.g. the example from the issue). 
The 2.7_LOCALE build (the 2nd one down on the travis builds), does NOT have numexpr installed (its the only one). So if you mark this tests as slow it will get run there (and should pass with the python parser) and on the other builds (don't mark as slow) with the numexpr engine.

So the tests should assert the state of ``_NUMEXPR_INSTALLED`` (IOW whichever you are actually testsing), then run the query. I don't think there is an easy way to figure out which engine is actually used (we may have to do some gymnastics here to assert that)

**Comment by jreback** [comment]
this needs a whatsnew note, put in API changes (even though it is more of a bug-fix)

**Comment by robintw** [comment]
Which whatsnew file should it be put in? 0.18.1?

Also, I'm a little confused about the tests: surely the test is either marked as slow or not marked as slow? I assume the tests should go in `test_query_eval.py`, but having looked at the tests in there I would have thought they would have caught this bug previously...

I'm happy to have a go at writing a test, with a bit of help, but I may not be the best person to do this - and someone else may be able to do it in a tiny fraction of the time.

**Comment by jreback** [comment]
0.18.1

you need 2 tests the same 1 slow and 1 not-slow (don't mark it)
they will be run in separate builds

**Comment by jreback** [comment]
replaced by https://github.com/pydata/pandas/commit/504ad4641e5b3a87b655da5dd31840de12495e97

but #12867 is still relevant (e.g. we may want to show a ``PerformanceWarning`` when ``numexpr`` is not installed

**Pull request closed without merging**
