### PR TITLE
REF: IntervalIndex.intersection match pattern in other intersection methods

### PR DESCRIPTION
**Pull request by jbrockmendel**
Looking to share the boilerplate and have subclasses just implement _intersection.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@jreback between @phofl and me there's a handful of FooIndex.intersection PRs that are becoming blockers: #38190, #38111, #38197, #38154, #38196 (and #38105 will allow for more de-duplication and fastpaths)

**Comment by jreback** [comment]
kk will look soon
 
can i indicate which are orthogonal? or any ordering here?

**Comment by jbrockmendel** [comment]
> or any ordering here?

Current plan in #38197 is to share the whatsnew note with #38111, but otherwise these should be all independent.

These should be all logically orthogonal, but the ones least likely to involve merge conflicts are #38105 and #38154.

**Comment by jreback** [comment]
I think all are merged (except one needs a rebase),

**Pull request merged**
