### PR TITLE
ERR: Raise on duplicates names in read_csv

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] xref #6581
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
Nice job @mroeschke

**Comment by jreback** [comment]
thanks @mroeschke

**Comment by jbrockmendel** [comment]
@mroeschke should the entry for this in #6581 be moved to #13777?  (also the docstring for `_validate_names` is now inaccurate)

**Comment by mroeschke** [comment]
@jbrockmendel Good catch. Looks like I forgot to move it to #13777 after this PR was merged.

**Comment by jbrockmendel** [comment]
which version did this make it into?

**Comment by jbrockmendel** [comment]
Looks like 0.25.0

**Pull request merged**
