### PR TITLE
ENH: Corrects to_html print spacing GH4987

### LINKED ISSUE #4987: ENH: to_html improvement
I know that the whitespace doesn't meter in HTML but this is really a strange behaviour:

```python
>>> df = pd.read_html(
             'http://en.wikipedia.org/wiki/Vancouver',
             match='Municipality', header=0
         )[0]
>>> df
0         Country         Municipality   NaN
1         Ukraine               Odessa  1944
2           Japan             Yokohama  1965
3  United Kingdom  Edinburgh[198][199]  1978
4           China       Guangzhou[200]  1985
5   United States          Los Angeles  1986
6     South Korea                Seoul  2007
>>> df.iat[3, 0]
'China'
>>> df.iat[4, 0]
'United States'
>>> df.iat[5, 1]
'Seoul'
```
Which is all fine, but if i try to convert it to HTML I get a really funky looking data :)

```python
>>> print(df.to_html(index=False))
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Country</th>
      <th>Municipality</th>
      <th>nan</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>        Ukraine</td>
      <td>              Odessa</td>
      <td> 1944</td>
    </tr>
    <tr>
      <td>          Japan</td>
      <td>            Yokohama</td>
      <td> 1965</td>
    </tr>
    <tr>
      <td> United Kingdom</td>
      <td> Edinburgh[198][199]</td>
      <td> 1978</td>
    </tr>
    <tr>
      <td>          China</td>
      <td>      Guangzhou[200]</td>
      <td> 1985</td>
    </tr>
    <tr>
      <td>  United States</td>
      <td>         Los Angeles</td>
      <td> 1986</td>
    </tr>
    <tr>
      <td>    South Korea</td>
      <td>               Seoul</td>
      <td> 2007</td>
    </tr>
  </tbody>
</table>
```
And also, if I specify explicitly the `classes` why does it always adds the `dataframe` class? Shouldn't the `classes` override the default `dataframe` class?

### PR DESCRIPTION
**Pull request by clham**
Closes #4987 

This is my first non-doc PR, so please bare with me.  Is it worth my while to go through the tests and standarize all of the test HTML to all block-strings, or is the mix of individual lines/blocks ok?

### CODE REVIEW

**Comment by jreback** [comment]
does this actually change the way the output looks?

**Comment by clham** [comment]
As far as I know it only strips off the leading/trailing spaces in the HTML data rows. Those spaces shouldn't be rendered by a browser?

**Comment by jreback** [comment]
@jorisvandenbossche @cpcloud @TomAugspurger look ok?

**Comment by jreback** [comment]
@clham can you add a release note? (put it under API changes section in whatsnew, just a single line and reference the underlying issue)

**Comment by clham** [comment]
Should be good to go. I added a plain api section. Current version only
lists breakages.

**Comment by jreback** [comment]
@TomAugspurger @jorisvandenbossche any problem with this?

**Comment by jorisvandenbossche** [comment]
Seems OK to me

**Comment by jorisvandenbossche** [comment]
But I think this should not be listed in API changes, but can be considered as a bug fix. 
And it needs a rebase.

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/ed45e6eeab43c1abf7b541fd659dada12172b52c

thanks!

**Comment by JanSchulz** [comment]
Thanks a lot for this, I had some problems letting pandoc convert such html and was doing a `re.sub(' +',' ', html)`but after this it isn't nessesary anymore :-)

**Pull request closed without merging**
