### PR TITLE
BUG fixes for date_range boundaries

### LINKED ISSUE #56134: BUG: date_range(freq='Y') is missing a date
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.date_range(start=pd.to_datetime('2021-12-31 00:00:01'), end=pd.to_datetime('2023-11-01 00:00:00'), freq='Y')
```
`DatetimeIndex(['2021-12-31 00:00:01'], dtype='datetime64[ns]', freq='A-DEC')`
```


### Issue Description

Looks like the following Year End freq should returns 2 datetimes not 1:

### Expected Behavior

`DatetimeIndex(['2021-12-31 00:00:01', '2022-12-31 00:00:01'], dtype='datetime64[ns]', freq='A-DEC')`

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 106 Stepping 6, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.5.3
numpy            : 1.26.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 67.3.1
pip              : 23.3
Cython           : 0.29.30
pytest           : 7.2.1
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.1
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.58.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 13.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.3
snappy           : None
sqlalchemy       : 1.4.41
tables           : None
tabulate         : 0.8.9
xarray           : 2022.3.0
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None
</details>

### LINKED ISSUE #56147: BUG: Negative freq in date_range produces values out of start and endpoints
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

start = pd.to_datetime('2023-10-31 00:00:00')
end = pd.to_datetime('2021-11-01 00:00:00')

rng = pd.date_range(start=start,end=end,freq='-1Y')
print(rng)
>>> DatetimeIndex(['2023-12-31', '2022-12-31', '2021-12-31'], dtype='datetime64[ns]', freq='-1Y-DEC')
```

### Issue Description

When using negative `freq` value for the year, the date range produces a value outside the range of start and end points.

### Expected Behavior

Expected the resulting dates to fall between start and end
`>>> DatetimeIndex(['2022-12-31', '2021-12-31'], dtype='datetime64[ns]', freq='-1Y-DEC')`

### Installed Versions

<details>
INSTALLED VERSIONS
------------------

commit              : 984d75543fce5c68f0dcc4f0b3500256e4a9c0c9
python              : 3.10.4.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64
processor           : Intel64 Family 6 Model 140 Stepping 2, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : English_Australia.1252

pandas              : 2.2.0.dev0+471.g984d75543f
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 58.1.0
pip                 : 23.3.1
Cython              : 0.29.33
pytest              : 7.4.3
hypothesis          : 6.88.1
sphinx              : 6.2.1
blosc               : 1.11.1
feather             : None
xlsxwriter          : 3.1.9
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : 1.4.6
psycopg2            : 2.9.9
jinja2              : 3.1.2
IPython             : 8.16.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
dataframe-api-compat: None
fastparquet         : 2023.10.1
fsspec              : 2023.10.0
gcsfs               : 2023.10.0
matplotlib          : 3.7.3
numba               : 0.58.1
numexpr             : 2.8.7
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : 1.2.4
python-calamine     : None
pyxlsb              : 1.0.10
s3fs                : 2023.10.0
scipy               : 1.11.3
sqlalchemy          : 2.0.22
tables              : 3.9.1
tabulate            : 0.9.0
xarray              : 2023.10.1
xlrd                : 2.0.1
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

### PR DESCRIPTION
**Pull request by jrmylow**
- [X] closes #56134
- [X] closes #56147 
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Fix for two issues with date_range where:
* A valid timestamp in range would be accidentally dropped when using year end and the starting timestamp was not midnight (56134)
* A negative year end offset and start increment at a date earlier than year end would include the year end of the starting date (despite being out of bounds of start and end)

### CODE REVIEW

**Comment by jrmylow** [comment]
pre-commit.ci autofix

**Comment by jrmylow** [comment]
> This pull request is stale because it has been open for thirty days with no activity. Please [update](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#updating-your-pull-request) and respond to this comment if you're still interested in working on this.

updated and still pending review

**Comment by MarcoGorelli** [comment]
sorry for the delay, will try to get to it this week or next

**Review by MarcoGorelli — COMMENTED** [review]
Nice work! Sorry this has taken me a while

First, can we move this to the 2.3.0 whatsnew note please?

Second, is it possible to fix the two bugs independently?
As in, I think you can just remove the
```
    elif end and not offset.is_on_offset(end):
        # Incompatible types in assignment (expression has type "datetime",
        # variable has type "Optional[Timestamp]")
        end = offset.rollback(end)  # type: ignore[assignment]
```
completely, and all existing tests will pass, as well the snippet from `56134`?

If so, I'd suggest splitting this - first, remove the unnecessary `elif end` block, and then we fix the `if start and not ...` one separately

**Comment by jrmylow** [comment]
ok then I'll close this, this has been picked up separately in:
* https://github.com/pandas-dev/pandas/pull/56831 for #56134
* https://github.com/pandas-dev/pandas/pull/56832 for #56147

Thanks

**Pull request closed without merging**
