### PR TITLE
flake8 cleanup

### PR DESCRIPTION
**Pull request by jbrockmendel**
Entirely aesthetic.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by gfyoung** [comment]
Quick question(s): are we not style-checking this file in the first place?  If not, why haven't we added it to the list of checked files?

**Comment by jbrockmendel** [comment]
IIUC its only the diffs that get checked in the CI, so existing flake8 errors pass through.

**Comment by gfyoung** [comment]
That's not the case, we *should be* linting the entire repository.  However, I think it's because we only lint the `pandas/pandas` directory, and `setup.py` is not in that directory.  Have a look at `lint.sh` and see if you can just add a line for that.

**Comment by jreback** [comment]
@gfyoung is right
this is fine if u also update lint.sh

all flake updates should update the checking code (eg for cython flaking)

**Comment by jbrockmendel** [comment]
OK, just added a clause in ci/lint.sh.  I fully expect it to fail for the time being -- is there a mechanism to `xfail`?

**Comment by gfyoung** [comment]
@jbrockmendel : Not as far as I know.  If you don't mind, why don't you try making a push to patch the remainding issues.  If you have problems, remove the lint command from `lint.sh`, and we can pick it up from where you left off.

**Comment by jreback** [comment]
> OK, just added a clause in ci/lint.sh. I fully expect it to fail for the time being -- is there a mechanism to xfail?

why would you expect a lint on this to fail? isn't that the point here, to make it work?

**Comment by jbrockmendel** [comment]
> why would you expect a lint on this to fail? isn't that the point here, to make it work?

The original PR fixed some but not all of the issues.  Following gfyoung's suggestion, I cleaned up the rest of it.  So it should now pass.

**Comment by jreback** [comment]
@jbrockmendel yep looks good now.

**Review by gfyoung — APPROVED** [review]
@jreback : if this looks good to you, we can just merge this.

**Comment by jreback** [comment]
no merging until after the release (except specifically tagged pr)

**Comment by jreback** [comment]
even though this looks fine, can you rebase (as just added another cython module, indexing.pyx), maybe fine, but just want this to run and go green again.

**Comment by jreback** [comment]
thanks!

**Pull request merged**
