### PR TITLE
ENH: Do unique check before computing indexer in reindex

### LINKED ISSUE #51287: BUG: pandas halted in a busy loop when assigning new column with non-unique index
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

indices = (
    ["label 1" for _ in range(10000)]
    + ["label 2" for _ in range(10000)]
    + ["label 3" for _ in range(10000)]
)
data = {"values": np.random.randn(30000)}

print("create dataframe")
df = pd.DataFrame(data, index=indices)

"""""
The original DataFrame looks like this

	     values
label 1	 0.808733
label 1	 1.112494
label 1  0.995864
label 1	 0.884037
label 1	 0.260556
        	...
label 3	 -0.411496
label 3	 -1.603830
label 3	 0.058993
label 3	 1.374946
label 3	 0.172165
"""

print("create `new_value` of disordered index (which have duplicate) ...")
new_value = df["values"].sort_values()

"""""
The index of the Series `new_value` are disordered and look like this

label 1   -4.210096
label 2   -4.154975
label 2   -3.996140
label 3   -3.767073
label 1   -3.754259
             ...   
label 3    3.533630
label 1    3.593864
label 2    3.614379
label 2    3.728890
label 3    3.768827
Name: values, Length: 30000, dtype: float64
"""

# The program is halted in a busy loop while executing the following statement
print("assign `new_value` as column...")
df["new"] = new_value
```

### Issue Description

 The program is halted in a busy loop when assigning new column

### Expected Behavior

I figured out the correct way to achieve my goal is to `df.reset_index()` to use the default ordinal index first then `df.set_index('label')` after the adding of new column.
I suspect that this usage (with duplcate values in index) may not be a well-defined use case.
But I could not found any documentation regarding this and pandas did not report error on the index being invald.

### Installed Versions

<details>
<code>
INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.1.6-arch1-1
Version          : #1 SMP PREEMPT_DYNAMIC Sat, 14 Jan 2023 13:09:35 +0000
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 63.2.0
pip              : 22.2
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
</code>
</details>

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #51287 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by phofl** [comment]
I'd feel a bit weird advertising that we are raising the error faster now :) But ok to add, if you feel strongly about it

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Guess that's fair. Thanks @phofl

**Comment by Alexia-I** [comment]
Hello, @phofl @mroeschke  I was wondering if this pull request has been backported? According to the [backporting guidelines](https://pandas.pydata.org/docs/development/maintaining.html#backporting), it seems that PRs with a milestone should be backported. However, I couldn't find a corresponding backport PR linked to this one. Can you please clarify if a backport has been created or if there's a different situation here?

**Comment by phofl** [comment]
This pr was released in 2.0, which is what the milestone tells you. 

You’ll have to clarify your question. To which branch should we have backported this pr?

**Comment by Alexia-I** [comment]
Thank you for your response! 

Sorry for any confusion earlier, I'm not familiar with the open-source management mechanisms on GitHub. I took another look at the documentation and realized indeed when a milestone corresponds to the master version, a backport isn't necessary. 

My question is actually about the process of fixing bugs: when you address a bug, do you first fix it in the master version and then backport that fix to the milestone, which is the target version? Does this mean that other versions won't receive the fix? For example, if the master is at 2.0 and the milestone is set for 1.3.x, does that mean only these two versions will be corrected on GitHub, and other minor versions, such as 1.4.x, 1.5.x, won't be fixed? Additionally, regarding PyPI releases, if a version on GitHub is backported, will the content in the PyPI package be updated with the fix?

**Comment by mroeschke** [comment]
pandas only maintains 2 branches during active development: The main branch which reflects the next upcoming minor/major release, e.g. 3.0, and the latest minor release branch, e.g. 2.2.x. A backported PR will apply to main and the latest minor release branch. The latest minor release branch usually only gets 3 or 4 packages on PyPI and conda e.g. 2.2.1, 2.2.2,  2.2.3.

**Comment by Alexia-I** [comment]
Thank you for your response! Now I get it.

**Pull request merged**
