### PR TITLE
REF: support object dtype in libgroupby.group_add

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
does this change any tests?

**Comment by jbrockmendel** [comment]
> does this change any tests?

no, just avoids going through fallback paths

**Comment by jreback** [comment]
> > does this change any tests?
> 
> no, just avoids going through fallback paths

kk so in theory more performant? (merging regardless as this is a good idea)

**Comment by jbrockmendel** [comment]
BTW the biggest blocker among the groupby stuff that your attention could help unblock is #41291

**Pull request merged**
