### PR TITLE
DOC: Remove travis doc build

### PR DESCRIPTION
**Pull request by datapythonista**
In #26648 we started building the documentation in azure pipelines. Seems to work fine, removing the travis build here.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
did you fix the doc links in contributing guide to show the new site?

**Comment by datapythonista** [comment]
Just opened #26857 for that.

**Comment by topper-123** [comment]
I got an https security warning on https://dev.pandas.io/. Anyone can confirm?

**Comment by datapythonista** [comment]
We've got #26841 for the TLS warning, didn't take a look yet.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
did this need a rebase? the reason i ask is IIRC the travis file was updated, but not sure this matters here.

**Comment by datapythonista** [comment]
I rebased it today, this is up to date with master, except for any commit in the last couple of hours.

**Comment by jreback** [comment]
thanks @datapythonista

**Pull request merged**
