### PR TITLE
Use https for links where available

### PR DESCRIPTION
**Pull request by rebecca-palmer**
As some of our links are suggestions to install add-on software, insecure links potentially allow an attacker to replace this with their malware.

During the process of writing this, I also found and fixed some broken or semi-broken (e.g. redirected to the top level instead of the page we want) links.

The following (already) broken links remain:
http://nipunbatra.github.io/2015/06/timeseries/ + others from this site
http://collaboration.cmc.ec.gc.ca/science/rpn/biblio/ddj/Website/articles/CUJ/1992/9210/ross/ross.htm
http://mysite.verizon.net/aesir_research/date/jdalg2.htm

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase on master. 

also if you can add a code_checks for this as well (can be a followup too)

**Comment by rebecca-palmer** [comment]
ci/code_checks.sh looks like it checks everything (not just new changes), so while it would be easy to add "http://" to its banned patterns list, that would fail as long as we have _any_ http links.  As some of our existing links (the ones I didn't convert) don't work over https, this is probably not a good idea.

The PEP8 issue isn't new, and involves a link that is >80char by itself.

**Comment by MomIsBestFriend** [comment]
> ci/code_checks.sh looks like it checks everything (not just new changes), so while it would be easy to add "http://" to its banned patterns list, that would fail as long as we have _any_ http links. As some of our existing links (the ones I didn't convert) don't work over https, this is probably not a good idea.
> 
> The PEP8 issue isn't new, and involves a link that is >80char by itself.

@rebecca-palmer I *think* that appending ```# noqa``` should do the trick despite the fact that it's inside a comment, so it will look kida like this:

```python
# <comments> <comments>
# <VERY_LARGE_URL> # noqa
# <more comments> <more comments>
```

**Review by WillAyd — APPROVED** [review]
lgtm @jreback

**Comment by jreback** [comment]
thanks !

**Pull request merged**
