### PR TITLE
REF: RelativeDeltaOffset.apply_index operate on ndarray

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
is this exercised in any tests?

**Comment by jbrockmendel** [comment]
> is this exercised in any tests?

Based on a quick check, looks like we have coverage for everything besides L1067

**Comment by jreback** [comment]
> > is this exercised in any tests?
> 
> Based on a quick check, looks like we have coverage for everything besides L1067

kk if you want to add here or followon ok

**Comment by jbrockmendel** [comment]
> kk if you want to add here or followon ok

lets do for follow-on.  there are a few more of these coming up

**Review by jreback — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
This is an API change?

**Comment by jbrockmendel** [comment]
> This is an API change?

No, apply_index_wraps already made it return an ndarray

**Pull request merged**
