### PR TITLE
BUG: DatetimeIndex.get_loc/get_value raise InvalidIndexError

### PR DESCRIPTION
**Pull request by jbrockmendel**
almost done with the get_value/get_loc methods

### CODE REVIEW

**Comment by jreback** [comment]
needs a rebase. not user facing right?

**Comment by jbrockmendel** [comment]
> not user facing right?

technically get_loc is part of the Index api

**Comment by jreback** [comment]
ok, though I feel this needs more tests, but maybe just being paranoid

**Comment by jbrockmendel** [comment]
> ok, though I feel this needs more tests

yah, i spent most of yesterday trying to organize/flesh-out the index/indexing tests and it turned in to a yak-shaving kind of day.  this is gonna be a marathon.  xref #31241 #31193.

**Pull request merged**
