### PR TITLE
Re-land PyCapsule

### PR DESCRIPTION
**Pull request by mroeschke**
Looks like this was accidentally reverted https://github.com/pandas-dev/pandas/pull/51952#issuecomment-1469076603 https://github.com/pandas-dev/pandas/pull/51951#issuecomment-1470386562

### CODE REVIEW

**Comment by phofl** [comment]
Are we sure that this isn't breaking anything?

**Review by WillAyd — APPROVED** [review]
lgtm - thanks!

**Comment by WillAyd** [comment]
> Are we sure that this isn't breaking anything?

This is the documented way to share C functions across extension modules. See https://docs.python.org/3/extending/extending.html#using-capsules

**Comment by phofl** [comment]
That's not what I meant. This is a pretty big pr where it's easy to miss something

**Comment by WillAyd** [comment]
The diff is a bit deceiving. The only real large addition to the code base is the 2 new include files. Everything else is just moving things to a better home (ex: function definitions of out parse_helper.h into pd_parser.c).

This actually improves type safety; the parsers.pyx changes before were happy redeclaring functions that are really implemented as returning a double * to functions returning a float64_t *. Guessing Cython relied on letting the linker resolve symbols before, but that returns a compilation warning/error in the current design.

**Review by lithomas1 — CHANGES_REQUESTED** [review]
Blocking until we figure out whether this lands in 2.0 or 2.1.

If going in 2.1, it has to go in late (after no more 2.0.x). PRs in C/Cython land will be very hard to backport, since the headers and stuff are all different.

**Comment by WillAyd** [comment]
Hmm why would this make backporting Cython changes any different?

**Comment by WillAyd** [comment]
The only file git doesn't correctly recognize as being moved is parse_helper.h which was last changed in 2020

**Comment by lithomas1** [comment]
Actually, looking at this again, I guess the only case backports would be affected are if a function was added/changed.

IIUC, the new process with the PyCapsule, is to modify the function in the original file, change the declarations in ``pd_parser``/``pd_datetime``, and then modify pyx imports. Is that right?

I guess leaving it in only 2.1 could be fine, but wasn't sure if you were planning on refactoring more (in which case I'd expect this backported).

In general, I like to keep CI/build stuff as close as possible between the main/release branch.

**Comment by WillAyd** [comment]
> IIUC, the new process with the PyCapsule, is to modify the function in the original file, change the declarations in `pd_parser`/`pd_datetime`, and then modify pyx imports. Is that right?

Generally, if we:

  1. Update a function within a module (ex: np_datetime.c) then that's it; the capsule changes nothing
  2. New/changed function declaration; would need to be reflected in the capsule as well (think of the capsule as the internal API)
  3. Decide we want to use the capsule functions in a Cython module that hasn't previously used the capsule; we need to cimport the `import_pandas_X` function and invoke it; this is the same functionality we already have with `cnp.import_array()` and `PyDateTime_IMPORT`

**Review by lithomas1 — APPROVED** [review]
Makes sense. Thanks for clarifying.

**Comment by mroeschke** [comment]
Since it appears this is a reorganization, I suppose this could go in 2.0, but no strong preference on my end. Would you still prefer this go into 2.1 @lithomas1?

**Comment by lithomas1** [comment]
No strong preference anymore, let's just put in in main for now, and see if it sticks this time.

**Pull request merged**
