### PR TITLE
Remove Unused Functions from ujson

### PR DESCRIPTION
**Pull request by WillAyd**
dump and load don't appear anywhere in the code base except for UltraJSON tests. Since they are part of the exposed API I figure makes just as much sense to remove

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Nice.  Those C files are hard to work in; I’m glad to see them getting trimmed down.

**Comment by jreback** [comment]
fine with this, can you add a whatsnew note just to document; also a lint error.

**Comment by jreback** [comment]
can you rebase

**Comment by jreback** [comment]
thanks @WillAyd

**Pull request merged**
