### PR TITLE
DEPR: DFGB.dtypes, rolling axis, Categorical.to_list

### LINKED ISSUE #51045: DEPR: GroupBy.dtypes
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = pd.DataFrame(
        {
            "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
            "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
            "C": np.random.randn(8),
            "D": np.random.randn(8),
        }
    )

rng = pd.date_range("2014", periods=len(df))
df.columns.name = "foo"
df.index = rng

g = df.groupby(["A"])[["C"]]
g_exp = df[["C"]].groupby(df["A"])

tm.assert_frame_equal(g.dtypes, g_exp.dtypes)

>>> print(g.dtypes)
foo        C
A           
bar  float64
foo  float64
```

### Issue Description

Not clear to me what this is supposed to mean.  The example above is from the one test we have (test_groupby_selection_other_methods) that gets here.  Shouldn't a user just check `df["C"].dtype` in this case?

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] <s>closes #51254</s>Reverted that part
- [x] closes #51045
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by mroeschke** [comment]
`Categorical.to_list` is the only one that we may want to deprecate the other way instead? xref https://github.com/pandas-dev/pandas/issues/14278 https://github.com/pandas-dev/pandas/issues/8826

**Comment by jbrockmendel** [comment]
w/r/t to_list/tolist i dont have an opinion, just dont want an outlier.  (also i dont expect people to use Categorical directly that much)

**Comment by mroeschke** [comment]
Yeah likewise. I would just recommend tabling `Categorical.to_list` until there's some more steam around which to list variant we want everywhere.

**Comment by jbrockmendel** [comment]
updated + green, will handle Categorical.to_list in an upcoming DEPR PR

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
