### PR TITLE
CLN: factorize returns ndarray[intp], not int64

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jreback** [comment]
any perf changes? are the XML changes orthogonal? (not objecting)

**Comment by jbrockmendel** [comment]
>any perf changes?

same as the other PRs: should be neglible on 64bit, mixed on 32bit until we are internally consistent

> are the XML changes orthogonal? (not objecting)

i didnt do those, no idea how they got into the diff

**Comment by jbrockmendel** [comment]
looks like the XML edits are already present in master, but just rebased, so hopefully they'll dissappear from the diff

**Comment by jreback** [comment]
i guess general question then

i agree aligning in intp is good mainly because we need to convert when we do a take
but shouldn't we see perf gains (from not constantly converting)?

**Comment by jbrockmendel** [comment]
> but shouldn't we see perf gains (from not constantly converting)?

on 64bit systems intp and int64 are the same and ensure_platform_int doesnt make a copy if it doesnt have to (and is in cython, so is cheap).  on 32bit yes, we are going back-and-forth in some places but ATM it is too scattered to really track down (even if i had the hardware on hand)

**Pull request merged**
