### PR TITLE
REF: use base class for BooleanArray any/all

### PR DESCRIPTION
**Pull request by mzeitlin11**
#41970 moved this to the base class, so not needed here anymore

### CODE REVIEW

**Comment by jbrockmendel** [comment]
nice!

**Review by jreback — CHANGES_REQUESTED** [review]
docs strings the same?

**Comment by mzeitlin11** [comment]
> docs strings the same?

Yep, just a bit more generic in the base class (also has a few more examples)

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @mzeitlin11

**Pull request merged**
