### PR TITLE
Revert "Re-enable parallel builds in CI"

### PR DESCRIPTION
**Pull request by jbrockmendel**
Reverts pandas-dev/pandas#51902

Depends on #51525 which is reverted by #51951

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@phofl ping on merging this and #51951

**Comment by phofl** [comment]
Didn't follow this last week. This breaks other stuff that you want to fix, that's why we are reverting?

**Comment by jbrockmendel** [comment]
Yes

**Comment by jbrockmendel** [comment]
ATM I can't maintain the C parts of the datetime code, which is unacceptable.

**Comment by phofl** [comment]
Sorry that it took me so long, I was going through the initial PR. If I understand it correctly it did not fix anything user visible and might get simpler if we can upstream stuff to NumPy? So should be good to revert, hopefully will get simpler in the future.

**Comment by WillAyd** [comment]
This shouldn't be reverted. The whole point of this and the capsule PR is to clean up our internal symbols and make an internal API for our extensions. Reverting this puts us back into a place of hacks and guesses until things work. Can we revert this revert?

**Comment by jbrockmendel** [comment]
Fine

**Pull request merged**
