### PR TITLE
WIP: All the CI in GitHub actions (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by datapythonista**
Many things are incomplete or broken here, but opening this so people can see the progress.

This needs to be discussed, and if we move forward splitted in many PRs, before it can be merged.

This adds all our current builds to GitHub actions, with two new features:
- Creating an artifact for the built web and docs
- A `Finalize` job is triggered when all the others are finished, that should summarize the errors in a GitHub comment (WIP)

Some things that are broken:
- The builds with locale different than English
- The grep that checks if there are ipython errors in the sphinx logs
- The builds other than Linux (because the matrix tries to create the containers for MySQL and PostgreSQL for all builds now)
- The `Finalize` job is WIP, and not sure if even triggered

I'll probably work on #29685 before adding any test build to actions. I think we can do much better in terms of simplicity and coverage with the creation of the matrix (which builds we run, and what's tested in each).

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@datapythonista anything i/others can do to help with this?

**Comment by datapythonista** [comment]
> @datapythonista anything i/others can do to help with this?

So far I'm mainly experimenting, to see challenges and what can be done. There are several builds that are working now, but I'd probably wait for now, before moving anything. I'd probably start by the web+docs build, and the ones in travis, and those are the ones that are failing (besides the windows ones).

What's your idea? If you'd like to see things in GitHub actions soon, we can discuss and see how can split this already. Is there anything that you think we should prioritize?

**Comment by jbrockmendel** [comment]
I don't have any ideas, no, just was going through PRs and seeing where I might be useful

**Comment by datapythonista** [comment]
Closing this, was just for testing. Will propose new builds to GitHub actions incrementally.

**Pull request closed without merging**
