### PR TITLE
ENH: read_excel: try converting numeric to int

### PR DESCRIPTION
**Pull request by jtratner**
Adds a convert_float=True kwarg to read_excel and parse.

All Excel numeric data is stored as floats, so have to convert it specifically.
Changing default because it's suprising to save something with what looks like
a row/column of integers and get a column of floats instead. (especially
because it can lead to annoying Float64Indexes)

Resolves recent ML issue too...

### CODE REVIEW

**Comment by denis-bz** [comment]
@rhshadrach, just a comment: this might be the same as your updated `_openpyxl.py _convert_cell`,
seems to me consistent with the 1.2.4 doc

> convert_float bool, default True
    Convert integral floats to int (i.e., 1.0 –> 1).
    If False, all numeric data will be read in as floats

```
    def _convert_cell(self, cell, convert_float: bool) -> Scalar:
        ...
        elif cell.data_type == TYPE_NUMERIC:  # -> float or int
            f = float(cell.value)
            if convert_float and f == int(f):
                return int(f)
            else:
                return f

        return cell.value
```

**Comment by rhshadrach** [comment]
@denis-bz - sorry, I don't understand. What is the significance if it is the same or not? Not sure if this is helpful, but openpyxl is already doing conversions to int, so pandas does not need to handle it.

**Comment by denis-bz** [comment]
@rhshadrach, my mistake, sorry, delete it.
(By "same" I meant "is code == doc" -- wan't clear to me.) Thanks

**Comment by rhshadrach** [comment]
Thanks, I think I understand now. I believe that is the code behavior matches the documentation. If you find or think that might not be the case, please do open an issue

**Pull request merged**
