### PR TITLE
BUG: closes bug in stack when index is not unique

### LINKED ISSUE #10417: BUG: groupby with levels on duplicated multi-index
```
x = pd.DataFrame({'x':[1,1,3,3],'y':[3,3,5,5]},index=[11,11,12,12])
y = x.stack()
print(y)
print(y.groupby(level=[0,1]).sum())
```
Ouput
```
11  x    1
    y    3
    x    1
    y    3
12  x    3
    y    5
    x    3
    y    5
dtype: int64
11  x    1
    y    3
    x    1
    y    3
12  x    3
    y    5
    x    3
    y    5
dtype: int64
```
The stack and group by sum are just the same.

Expected output:

```
11  x    2
11  y    6
12  x    6
12  y    10
```

### PR DESCRIPTION
**Pull request by behzadnouri**
closes https://github.com/pydata/pandas/issues/10417

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase

**Comment by behzadnouri** [comment]
@jreback rebased

**Comment by jreback** [comment]
thanks!

**Comment by behzadnouri** [comment]
@jreback *my* version of travis build of pandas fails (https://travis-ci.org/behzadnouri/pandas/builds), do u know why is that and how to fix it? 

it seems that pandas have recently made some changes to travis setup, and for whatever reason those changes are not picked up on my side. is there anything that i have to do manually?

**Comment by jreback** [comment]
hmm, odd, we did remove ``pandas/version.py``, but that's should cause an issue on travis. you sure you are based on remote master?

**Comment by jreback** [comment]
merged version passed ok: https://travis-ci.org/pydata/pandas/builds/74690863

**Comment by behzadnouri** [comment]
**my** hook of travis fails, not pydata;
i.e. this one: https://travis-ci.org/behzadnouri/pandas/builds
not this: https://travis-ci.org/pydata/pandas/builds

i have rebased couple of times, and `origin/master` is identical to `upstream/master` but still it fails.

**Comment by jreback** [comment]
no I know. that's a bit odd. I wonder if travis is doing something like migrating infrastructure (and yours is migrating).

**Comment by seth-p** [comment]
@behzadnouri, would the ``factorize()`` in ``pandas.core.algorithms`` not work here?

I'm trying to rebase #9023 (which I think addressed the issue of this PR, among other things), and am wondering what was the reason for defining a local ``factorize()``.

**Comment by jreback** [comment]
a categorical is created with factorize
this just takes advantage of a unique index

**Comment by seth-p** [comment]
So it's purely a speed optimization? If so, can it be incorporated in to ``pandas.core.algorithms.factorize()``? It seems rather confusing to define a new function of the same name and similar behavior (at least I was confused).

**Comment by jreback** [comment]
no this is a special case

you normally DO want to factorize even unique indices except in some certain cases

**Comment by seth-p** [comment]
FWIW, I deleted the specialized local ``factorize()`` as part of rebasing #9023 (for no particular reason other than that I didn't understand why it was necessary), and all tests pass: https://travis-ci.org/pydata/pandas/builds/77865221.

**Pull request merged**
