### PR TITLE
DOC: update examples in MonthBegin/MonthEnd to use rollbackward/rollforward

### LINKED ISSUE #52106: DOC: MonthBegin suggestion to get start of current month not quite right?
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.tseries.offsets.MonthBegin.html?highlight=monthbegin#pandas.tseries.offsets.MonthBegin

### Documentation problem

The docs for [MonthEnd](https://pandas.pydata.org/docs/dev/reference/api/pandas.tseries.offsets.MonthEnd.html?highlight=monthend#pandas.tseries.offsets.MonthEnd) say

> To get the end of the current month pass the parameter n equals 0.

This is correct:
```python
In [51]: pd.Timestamp('2023-03-21') + pd.offsets.MonthEnd(n=0)
Out[51]: Timestamp('2023-03-31 00:00:00')
```

But for `[MonthBegin](https://pandas.pydata.org/docs/dev/reference/api/pandas.tseries.offsets.MonthBegin.html?highlight=monthbegin#pandas.tseries.offsets.MonthBegin), it says

> To get the start of the current month pass the parameter n equals 0.

I think this is not quite right:
```python
In [58]: pd.Timestamp('2023-03-21') + pd.offsets.MonthBegin(n=0)
Out[58]: Timestamp('2023-04-01 00:00:00')
```

### Suggested fix for documentation

I would have expected `- pd.offsets.MonthBegin(n=0)` to go to the beginning of the current month, but it doesn't:
```python
In [64]: pd.Timestamp('2023-03-21') - pd.offsets.MonthBegin(n=0)
Out[64]: Timestamp('2023-04-01 00:00:00')
```

I'm not sure if this is a bug, I've not looked closely enough.

I think I'd suggest:
- removing the "To get the start of the current month pass the parameter n equals 0." suggestion
- adding an example of using `+ pd.offsets.MonthBegin() - pd.offsets.MonthBegin()` to get the start of the current month

cc @natmokval in case you wanted to make a PR (no blame of course! I should have noticed this when reviewing)

### PR DESCRIPTION
**Pull request by pranav-ravuri**
- [ ] closes #52106
updated docstring of pandas.offsets.MonthBegin, pandas.offsets.MonthEnd, pandas.offsets.BMonthBegin, pandas.offsets.BMonthEnd
the output of the `validate_docsctrings.py`  is similar to the below output as follows
```
################################################################################
#################### Docstring (pandas.offsets.MonthBegin)  ####################
################################################################################

DateOffset of one month at beginning.

Examples
--------
>>> ts = pd.Timestamp(2022, 1, 1)
>>> ts + pd.offsets.MonthBegin()
Timestamp('2022-02-01 00:00:00')

################################################################################
################################## Validation ##################################
################################################################################

2 Errors found:
        No extended summary found
        See Also section not found
```

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
This is a great first contribution, thanks @pranav-ravuri ! Looks good to me pending green

**Comment by MarcoGorelli** [comment]
@pranav-ravuri there's one more related one, in case you wanted to take this one on https://github.com/pandas-dev/pandas/issues/52169

**Comment by pranav-ravuri** [comment]
Hi @MarcoGorelli there seems to be conflict, but I did not understand what it is? And how could I have avoided it?

**Comment by MarcoGorelli** [comment]
the conflict is only when backporting to version 2.0 (from which the next stable docs will be built) - you did everything right, it's just that not everything gets backported, so conflicts creep in sometimes

**Pull request merged**
