### PR TITLE
TST: broken off from #32187

### PR DESCRIPTION
**Pull request by jbrockmendel**
troubleshooting an apparently-unrelated Travis failure there

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@simonjayhawkins if you're interested in a change of pace from test organization, the Travis failure here is a mystery ive had no luck resolving.  any ideas?

**Comment by jbrockmendel** [comment]
hey neat!  any guesses why using the fixture instead of the generator worked?

**Comment by simonjayhawkins** [comment]
I guess just changed the order/randomness of the tests. I couldn't reproduce the failure locally, but we had a similar issue once before.

**Comment by jreback** [comment]
thanks

**Pull request merged**
