### PR TITLE
BUG: Series.view from int64 to datetimelike

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Broken off of a branch fixing #41927

### CODE REVIEW

**Comment by jreback** [comment]
this or #44582 first?

**Comment by jbrockmendel** [comment]
this

**Comment by jreback** [comment]
ok then same comment on using super

**Comment by jbrockmendel** [comment]
> ok then same comment on using super

added + greenish

**Review by jreback — APPROVED** [review]

**Pull request merged**
