### PR TITLE
Update 10min.rst

### PR DESCRIPTION
**Pull request by aflah02**
Added Links for Matplotlib Close along with a line explaining what it does.
I had faced difficulty when I read it for the first time and had to google search what close does

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by aflahkhan** [comment]
Hey Can someone explain what went wrong. This is the first time I used Sphinx directly but it seems to fail and I can't understand why

**Comment by aflahkhan** [comment]
@jbrockmendel 
Hey
I saw your contributions and commits on the top page 
I want some help here can you tell me what's going wrong and causing all this fail?

**Comment by jbrockmendel** [comment]
Near the bottom of the page there is a red x for the "pre-commit" CI check.  click on the "details" link to see the logs for the failed check.  There is a line that the code-check wants to see changed, I think it just wants some whitespace removed.

**Comment by aflahkhan** [comment]
Thank You @jbrockmendel 
So now when I rework on the branch do I need to pull it again and delete this pull request?

**Comment by aflahkhan** [comment]
@jbrockmendel 
I've made the whitespace changes yet it fails any ideas why would it happen now?

**Comment by aflahkhan** [comment]
@jbrockmendel 
Hey I'd like to apologize in case my message was aggressive to say the least. Someone pointed it out to me and I am just starting but that is no excuse so I will try my best to keep this in mind in the future.
Thank You for all the help though

**Comment by jbrockmendel** [comment]
Looks like the code check passed this time around.  Good job.  Someone more familiar with the docs will come along to review this before too long.

**Comment by jreback** [comment]
thanks @aflah02

**Comment by aflah02** [comment]
@jreback You're Welcome

**Pull request merged**
