### PR TITLE
PERF: extract_array -> _values

### PR DESCRIPTION
**Pull request by jbrockmendel**
Found that grepping for uses of pd.array is a PITA, so went through and changed them all (inside core) to pd_array.  @MarcoGorelli would it be feasible to make a code check for this?

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Should we then also use consistently `pd_array` in tests and remove the line

https://github.com/pandas-dev/pandas/blob/95a86a9884e6e0a32aeffff345e39434bbb722e5/scripts/check_for_inconsistent_pandas_namespace.py#L32

?  cc @jorisvandenbossche as you're commented on `pd_array` previously

**Comment by jbrockmendel** [comment]
> Should we then also use consistently pd_array in tests and remove the line

another option would be to define it pd_array in core.construction and import it into the pd namespace as `array`

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by MarcoGorelli** [comment]
understood - thanks for explaining!

**Comment by jreback** [comment]
any non-trivial perf impact?

and should we have a rule for internal tests? (to use `pd_array`)?

**Comment by jbrockmendel** [comment]
>> another option would be to define it pd_array in core.construction and import it into the pd namespace as array

> That doesn't solve the issue that I want it as pd.array in the tests, though ;)

Maybe I communicated poorly. The ideas was that `pd.__init__` could have `from pandas.core.construction import pd_array as array`, so tests could still use `pd.array` or `from pandas import array`

**Comment by jorisvandenbossche** [comment]
@jbrockmendel I understood that correctly ;) (but so then it doesn't matter for tests, and since you were replying to Marco's comment about tests, I thought it was related to that)

**Pull request merged**
