### PR TITLE
DOC: Updates to documentation for Series functions

### LINKED ISSUE #15580: DOC: overall improvement of docstrings
This is a general issue, to have as a starting point for (new) contributors to improve the docstrings (many docstrings have missing parts, and improvements on this front are always welcome).

In general, some attention points for docstrings in pandas. Each docstring should have:

- Clear explanation of the function/method/attribute's purpose and what it does
- Clear explanation of all parameter values
- State the return value and type (xref #17114)
- Some examples
  - Note: examples should be runnable (thus include creation of the example DataFrame/Series, `import pandas as pd` not needed to include) (xref #3439)
- follow more the numpydoc docstring standard (stylistic, see also, all arguments)

There are quite some docstrings that are still lacking on some of these points (in particular examples), and PRs to improve this are always welcome.

**Approach**: pick a function, check the docstring, and if needed make a PR with updates!

### PR DESCRIPTION
**Pull request by chikausa**
- [ ] closes #15580
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

I wanted to update some functions that are missing documentation in Series, and ended up updating `Series.shape`, `Series.size`, `Series.dtype`, `Series.dtypes`, and `Series.hasnans`.

I might have done too much in one PR, so I hope this is okay!

### CODE REVIEW

**Comment by chikausa** [comment]
Admittedly, I forgot to run pre-commit, so I ran it after. However, since I use conda, it now returns a strange issue when I try to commit. Here's the log from the pre-commit.
image

I downgraded `virtualenv` in conda, but it still doesn't seem to work...

**Comment by mroeschke** [comment]
Were you able to create you contribution environment according to: https://pandas.pydata.org/pandas-docs/stable/development/contributing.html and then run `pre-commit install`?

**Comment by chikausa** [comment]
> Were you able to create you contribution environment according to: https://pandas.pydata.org/pandas-docs/stable/development/contributing.html and then run `pre-commit install`?

Aah, so I was missing that. My apologies! Let me try making my contribution environment and then I'll try running pre-commit install again.

**Comment by chikausa** [comment]
My pre-commit turned out fine, but I'm not sure about these other checks...

**Comment by mroeschke** [comment]
Looks like another docstring needs to be aligned with the changes you made

```
     def test_hasnans_uncached_for_series():
        # GH#19700
        idx = Index([0, 1])
        assert idx.hasnans is False
        assert "hasnans" in idx._cache
        ser = idx.to_series()
        assert ser.hasnans is False
        assert not hasattr(ser, "_cache")
        ser.iloc[-1] = np.nan
        assert ser.hasnans is True
>       assert Series.hasnans.__doc__ == Index.hasnans.__doc__
E       AssertionError: assert '\n        Re...rue\n        ' == '\n        Re...ps.\n        '
E         Skipping 81 identical leading characters in diff, use -v to show
E           speedups.
E         + 
E         +         Returns
E         +         --------
E         +         bool
E         +             Whether the Series contains a NaN....
E         
E         ...Full output truncated (8 lines hidden), use '-vv' to show
```

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
