### PR TITLE
skip 32 bit linux

### PR DESCRIPTION
**Pull request by WillAyd**
follow up to #32706

### CODE REVIEW

**Comment by jreback** [comment]
can you also create an issue investigate this.

**Comment by jreback** [comment]
@TomAugspurger marking this for 1.0.3 if needed with the manual backport tag

**Comment by WillAyd** [comment]
Sure opened #32709 to come back to a long term solution

**Comment by jreback** [comment]
thanks

**Comment by jorisvandenbossche** [comment]
@MeeseeksDev backport to 1.0.x

**Pull request merged**
