### PR TITLE
CLN,TYP Remove string return annotations

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

this was just done with
```python
    parser = argparse.ArgumentParser()
    parser.add_argument('paths', nargs='*', type=Path)
    args = parser.parse_args()
    for path in args.paths:
        text = path.read_text()
        text = re.sub(r'-> "(\w+)"', '-> \\1', text)
        path.write_text(text)
```

There's other to do (which I'll get to in other PRs), but this already gets rid of a big load of them

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]
nice. merge on green.

**Comment by jbrockmendel** [comment]
Not a huge deal, but I like the string versions since they make the dependency structure clearer, i.e. I’m not going to incorrectly infer that Series is in the namespace.

**Comment by simonjayhawkins** [comment]
> Sure, but you can't click and go to a definition if it's a string version (this is my main reason for wanting to make this kind of change)

some discussion in https://github.com/pandas-dev/pandas/pull/36034#issuecomment-684972993


> I think it only makes the dependency structure clearer if string ones are used consistently (currently there's a mix)

agreed. You can (and people have) quote types even if the type is imported at runtine, or quote the whole type expression such as `"List[grouper.Grouping]"` which the PR resolves.

"we" agreed (https://github.com/pandas-dev/pandas/pull/36034#issuecomment-685186742) on going this route. Do we want another discussion?

**Comment by jbrockmendel** [comment]
> Do we want another discussion?

Nope, I'm pretty happy with my "defer to Simon when it comes to annotations" policy.

**Comment by MarcoGorelli** [comment]
OK, merging following https://github.com/pandas-dev/pandas/pull/39174#pullrequestreview-568442160 and https://github.com/pandas-dev/pandas/pull/39174#issuecomment-760992916

**Comment by simonjayhawkins** [comment]
Thanks @MarcoGorelli

**Pull request merged**
