### PR TITLE
DOC: sub-section on boolean Index array changes

### LINKED ISSUE #17740: DOC: note for changes in #17738, .loc with a boolean Index
https://github.com/pandas-dev/pandas/pull/17738#issuecomment-333522998

### PR DESCRIPTION
**Pull request by jreback**
closes #17740

### CODE REVIEW

**Comment by jreback** [comment]
cc @jorisvandenbossche

**Review by jorisvandenbossche — COMMENTED** [review]
Thanks! 

I would also add that previously for non-boolean and non-numeric indices, it would raise a KeyError (since the True / False were regarded as labels), and not will do boolean selection.

**Comment by jreback** [comment]
> Iwould also add that previously for non-boolean and non-numeric indices, it would raise a KeyError (since the True / False were regarded as labels), and not will do boolean selection.

not following, what is the example?

**Comment by jorisvandenbossche** [comment]
So previously Index with True / False values were always regarded as *labels*, not as a boolean mask. Which resulted in a KeyError for non-numeric indices or actual label-based indexing for numeric/boolean index (the fact that it interpreted True/False as 1/0 is the bug that was been fixed in an earlier PR regarding drop, but the general thing (your recent PR) that boolean index is not seen as labels is the API change you describe in the PR here).

So previous:

```
In [38]: s = pd.Series([1,2,3], index=['a', 'b', 'c'])

In [39]: s.loc[pd.Index([True, False, True])]
...
KeyError: "None of [Index([True, False, True], dtype='object')] are in the [index]"

In [42]: s = pd.Series([1,2,3])

In [43]: s.loc[pd.Index([True, False, True])]
Out[43]: 
1    2
0    1
1    2
dtype: int64
```

Now:

```
In [4]: s = pd.Series([1,2,3], index=['a', 'b', 'c'])

In [5]: s.loc[pd.Index([True, False, True])]
Out[5]: 
a    1
c    3
dtype: int64

In [6]: s = pd.Series([1,2,3])

In [7]: s.loc[pd.Index([True, False, True])]
Out[7]: 
0    1
2    3
dtype: int64
```

**Comment by jorisvandenbossche** [comment]
(but it is not perse necessary to add all those example, for me just adding it in the text is fine as well. I suspect that not many people deliberately will have used a boolean index to index a non-numeric index and explicitly catched the KeyError ... The main change is when you actually had a boolean index in the object you are indexing (i.e. the case for which you already have an example))

**Comment by jreback** [comment]
ic, ok will add that as well.

**Pull request merged**
