### PR TITLE
BUG: read_excel with openpyxl and missing dimension

### LINKED ISSUE #38956: BUG: read_excel() using openpyxl engine header argument not working as expected
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example
I am happy to provide the file I am using privately, offline if necessary. This would be necessary to directly reproduce this error. 
```
import pandas as pd
df = pd.read_excel(myfile.xlsx, engine='openpyxl', header=2)
```
Throws error:
```...ValueError: Passed header=2 but only 2 lines in file```

#### Problem description
I changed my `read_excel()` code to be now using `engine='openpyxl` with the 1.2 `read_excel()` changes, but the `header` argument is no longer working as it was before. I am trying to read in a .xlsx file that has 2 initial rows that should be skipped, and the 3rd row contains the headers. Thus, I am passing `header=2`, which should automatically skip the first two rows and use the 3rd (0-indexed) row as the headers.  However, I am getting the following error: `ValueError: Passed header=2 but only 2 lines in file`. I have confirmed multiple times that this file contains more than 2 lines - it contains thousands (happy to provide this file offline if necessary). I was able to previously run this code with the same file (before the `xlrd` deprecation, using the same header specification. With the openpyxl changes in 1.2, should we be using the `header` argument any differently? Thank you.

This is related to changes in https://github.com/pandas-dev/pandas/pull/35029.

#### Expected Output
Intended behavior would be that the .xlsx file is successfully read in as a dataframe using headers in row 3 and does not throw the above error.

#### Output of ``pd.show_versions()``
<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.19.4
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 50.3.2
Cython           : None
pytest           : 4.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 4.3.1
pyxlsb           : None
s3fs             : 0.4.2
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
xlsxwriter       : None
numba            : None
```
</details>

### LINKED ISSUE #39001: BUG: read_excel with openpyxl results in empty data frame
- [ X ] I have checked that this issue has not already been reported.

- [ X ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

-----

#### Old behavior with xlrd 1.2.0 (last version with XLSX support)

```
>>> import pandas as pd
>>> df=pd.read_excel('infile.xlsx', engine='xlrd')
<stdin>:1: FutureWarning: Your version of xlrd is 1.2.0. In xlrd >= 2.0, only the xls format is supported. As a result, the openpyxl engine will be used if it is installed and the engine argument is not specified. Install openpyxl instead.
>>> df.shape
(843, 11)
```

File is read perfectly and dataframe is ok, with all 11 columns.

#### Problem description

When using openpyxl as engine for read_excel:

```
>>> import pandas as pd
>>> df=pd.read_excel('infile.xlsx', engine='openpyxl')
>>> print(df)
Empty DataFrame
Columns: [Column1, Column2, Column3]
Index: []
>>> df.shape
(0, 3)
```

Only the 3 first headers are read, and it stops.

However, if the file is opened directly with openpyxl, it works fine, I'm using it to open and save the file with a temporary name to make openpyxl work as engine on Pandas:
```
>>> wb = load_workbook('infile.xlsx')
>>> wb.save(filename = 'temp.xlsx')
>>> pd.read_excel('temp.xlsx', engine='openpyxl')
>>> df.shape
(843, 11)
```

<details>

INSTALLED VERSIONS
------------------
commit           : 3e89b4c4b1580aa890023fc550774e63d499da25
python           : 3.8.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.128-microsoft-standard
Version          : #1 SMP Tue Jun 23 12:58:10 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.0
numpy            : 1.19.5
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.3.1
Cython           : 0.29.21
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.5
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : 0.8.7
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : None

</details>

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] closes #38956
- [x] closes #39001
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Targeted for 1.2.2 because this resolves an issue that occurs from the change of default engine from xlrd to openpyxl in 1.2.

### CODE REVIEW

**Comment by rhshadrach** [comment]
Didn't read the discussion from #39001; I'm thinking now this is probably the wrong thing to do.

**Comment by asishm** [comment]
This can probably be a follow up issue, but running this patch on the `sample.xlsx` file of #38956 results in different shapes of dataframes with engine=xlrd vs engine=openpyxl.

openpyxl generates 39 rows vs 9 rows for xlrd. The first 9 rows seem equivalent for both. The latter rows with openpyxl are all NaNs

**Comment by rhshadrach** [comment]
Agreed @asishm - I think that is the cause for #39181 as well, and my guess is that adding a call to ``reset_dimension`` will fix as well. However, will tests - I think it makes sense to add them all here as they are all the same core issue (openpyxl being given no/incorrect dimension information).

**Comment by rhshadrach** [comment]
My previous comment was not correct - if there are empty cells then we still get null values coming through and need to trim, e.g. the following would result in a DataFrame with rows 7 through 17 np.nan

```
<row r="6" customFormat="false" ht="13.8" hidden="false" customHeight="false" outlineLevel="0" collapsed="false">
  <c r="A6" s="3" t="n">
    <v>3</v>
  </c>
  <c r="B6" s="4" t="n">
    <v>6</v>
  </c>
  <c r="C6" s="4" t="n">
    <v>9</v>
  </c>
</row>
<row r="16">
  <c r="B16" s="7"/>
  <c r="C16" s="7"/>
</row>
<row r="17">
  <c r="B17" s="7"/>
  <c r="C17" s="7"/>
</row>
```

**Comment by rhshadrach** [comment]
I've reverted the fixes for #39181 as they are of a different nature than just dimension information and opened #39547

**Comment by rhshadrach** [comment]
Current minimum version for openpyxl is 2.6.0, this patch would need 2.6.1 (reset_dimensions doesn't exist before this). Is increasing the minimum version here okay to do for 1.2.2? cc @jreback @simonjayhawkins

**Comment by jreback** [comment]
> Current minimum version for openpyxl is 2.6.0, this patch would need 2.6.1 (reset_dimensions doesn't exist before this, accesses protected members). Is increasing the minimum version here okay to do for 1.2.2? cc @jreback @simonjayhawkins

yep that's fine (just update all the locations, install, show_versions, and put it in the whatsnew note)

**Comment by jreback** [comment]
can you rebase

**Comment by rhshadrach** [comment]
@jreback I've merged master and included increased the minimum version for openpyxl.

**Comment by jreback** [comment]
> pandas/io/excel/_openpyxl.py:543: error: Unsupported operand types for + ("List[Union[Union[str, int, float, bool], Union[Any, Any, Any, Any]]]" and "List[str]")  [operator]

:-<

**Comment by rhshadrach** [comment]
Thanks @jreback, turns out that this needs openpyxl 3.0.0. Prior versions still suffer from not reading the full excel file even after calling `reset_dimension`.

**Comment by jreback** [comment]
can we *easily* fallback to behavior if older version of openpyxl is installed? (just because this is a minor release)

**Comment by rhshadrach** [comment]
Yes - good idea and I think it should be easy enough. Because I don't understand what happened between openpyxl 2.6.4 and 3.0.0 (there are no release notes for the 3.0.0 that I can find), my thought is to not modify behavior if openpyxl < 3.0.0. If that is the case, then what should be done with the minimum version here? Keep at 2.6.0 until pandas 1.3 (or 2.0)?

**Comment by jreback** [comment]
> Yes - good idea and I think it should be easy enough. Because I don't understand what happened between openpyxl 2.6.4 and 3.0.0 (there are no release notes for the 3.0.0 that I can find), my thought is to not modify behavior if openpyxl < 3.0.0. If that is the case, then what should be done with the minimum version here? Keep at 2.6.0 until pandas 1.3 (or 2.0)?

yes exactly so we don't actually bump the min in 1.2.2 (or just bump to 2.6.1) and just fallback (even if slow / whatever), and make the bump for 1.3

**Comment by rhshadrach** [comment]
@jreback - changes made. One thing I noticed is that the minimum version in `_optional.py` was incorrect - I've updated it to 2.6.0 - uncertain if this needs a line in the whatsnew.

**Comment by jreback** [comment]
thanks @rhshadrach 

happy to have the min version bump for 1.3

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
