### PR TITLE
get_dummies to select string dtype in addition to object and categorical

### LINKED ISSUE #44965: BUG: Apply pd.get_dummies() on string type columns of pandas dataframe do nothing?
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

I have the following dataframe:

```
df = pd.DataFrame({'a': [6.6, -5.2, 2.1, 3.3, 1.1],
              'b': ['a', 'a', 'c', 'b', 'a'],
              'c': ['kfr', 'kfr', 'lu', 'ku', 'lu'],
              'd': ['t', 's', 's', 't', 'a']})
```
All the dtypes (columns b, c, d) are of type string.

If I call `df = df.convert_dtypes()`, and then call `pd.get_dummies()`, nothing happens:

```
df = pd.DataFrame({'a': [6.6, -5.2, 2.1, 3.3, 1.1],
              'b': ['a', 'a', 'c', 'b', 'a'],
              'c': ['kfr', 'kfr', 'lu', 'ku', 'lu'],
              'd': ['t', 's', 's', 't', 'a']})
df = df.convert_dtypes()
pd.get_dummies(df)
```

But if I will change the `df.convert_dtypes()` to `df.convert_dtypes(convert_string=False) ` it will work as expected.
Why is this happening? Is it a bug?

### Expected Behavior

pandas `pd.get_dummies()` should work on strings columns dtype also.

### Installed Versions

<details>
1.3.5
</details>

### PR DESCRIPTION
**Pull request by lukemanley**
- [x] closes #44965
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Could you add a whatsnew?

**Comment by lukemanley** [comment]
Sure - would this go under `Bug Fixes > Strings` or `Other enhancements`?

**Comment by phofl** [comment]
Would put it under bug fixes

**Comment by NumberPiOso** [comment]
Should a test that uses `df = df.convert_dtypes() ` be added? #44965

**Comment by jreback** [comment]
thanks @lukemanley

**Pull request merged**
