### PR TITLE
DOC: Fix EX01 issues in docstrings

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Towards https://github.com/pandas-dev/pandas/issues/37875

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Nice as always @DeaMariaLeon

**Comment by DeaMariaLeon** [comment]
Thanks @mroeschke for reviewing and merging. I have some questions:

1. Do you prefer that I include more examples per PR or is "little by little" OK?
2. Should I avoid many commits and send just one? I think I should use `git rebase`..

**Comment by mroeschke** [comment]
> Do you prefer that I include more examples per PR or is "little by little" OK?

I am okay with more examples per PR. Personally, I would say no more than addressing 10 functions per PR

> Should I avoid many commits and send just one? I think I should use git rebase..

No need to worry about this. When your PRs are merged, the commits are squashed all together.

**Comment by DeaMariaLeon** [comment]
OK, good to know both points. 
Thanks.

**Pull request merged**
