### PR TITLE
[BUG]Fix read_html error when URL include Unicode

### LINKED ISSUE #47899: BUG: read_html produce UnicodeEncodeError for multibyte URL
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
url = "https://en.wikipedia.org/wiki/2013–14_Premier_League"
url_escaped = urllib.parse.quote_plus(url, "/:?=&") # need this line
print(f"url:{url}")
print(f"escaped:{url_escaped}")
tables = pd.read_html(url_escaped, encoding="UTF-8") # non-error
tables = pd.read_html(url, encoding="UTF-8") # error

# url:https://en.wikipedia.org/wiki/2013–14_Premier_League
# escaped:https://en.wikipedia.org/wiki/2013%E2%80%9314_Premier_League
```

### Issue Description

Some people faced UnicodeEncodeError when using read_html.
Internally, Pandas use urllib which can't support multibyte URLs. so, we need to escape the URL before passing the URL.

so, I think we can fix it by passing the escaped URL instead of a multibyte URL.

### Expected Behavior

It should be returned expected tables even if we passed the multibyte URL.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 3e89b4c4b1580aa890023fc550774e63d499da25
python           : 3.9.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.2.0
numpy            : 1.23.1
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 22.0.3
setuptools       : 51.1.1
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.37
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
In [4]: pd.show_versions()
In [4]: pd.show_versions()
In [4]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 3e89b4c4b1580aa890023fc550774e63d499da25
python           : 3.9.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.2.0
numpy            : 1.23.1
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 22.0.3
setuptools       : 51.1.1
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.37
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by kouml**
- [x] closes #47899 and #21499 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Let's tackle the last one after getting the approval for this PR.
I fixed the unicode URL issue for `read_html` function by converting the unicode-style URL.

```
# url:https://en.wikipedia.org/wiki/2013–14_Premier_League
# escaped:https://en.wikipedia.org/wiki/2013%E2%80%9314_Premier_League
```

### CODE REVIEW

**Comment by kouml** [comment]
Sorry, I'll fix some tests first.

**Comment by kouml** [comment]
CI failure is just rate limit exceeded issue. I'll rerun later.

```
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/users/wesm
```

**Comment by kouml** [comment]
Now, 32 Bit Linux test is canceled due to a timeout issue, and it is debugging in this PR.
https://github.com/pandas-dev/pandas/pull/50376

however, failed and canceled tests are irrelevant issues for this PR, so after fixing the above test, I think this PR is fine. 
so, Please review the PR when you have time. Thanks in advance.

**Comment by kouml** [comment]
All tests are done now. Could someone help me to review it?@phofl, @mroeschke

**Comment by WillAyd** [comment]
I'm not sure this is something we should be special-casing. Looks like there has been some upstream conversation on this already in Python

https://bugs.python.org/issue3991

Not an expert on the RFCs but I think we would just want to defer to the language

FYI since the characters included are non-printable the test case is a bit deceiving. If you remove the non-printable characters everything works fine

**Comment by kouml** [comment]
@WillAyd Sorry for the late reply due to my new year holidays.
Thanks for the RFC confirmation, I didn't notice that. however, That makes sense to me.
I agreed with your suggestion, so It's better to defer to the Python language.

Let's close the related issues or pull requests, and Let's clearly state this is the spec and not the bug.

**Pull request closed without merging**
