### PR TITLE
Filter warning in sparse repr

### PR DESCRIPTION
**Pull request by TomAugspurger**
xref https://github.com/pandas-dev/pandas/issues/26555

### CODE REVIEW

**Comment by jreback** [comment]
lgtm.

**Comment by jreback** [comment]
this should close #26555 yes? (or is there more to do?)

**Comment by TomAugspurger** [comment]
Still more to do in theory. Things like SparseDataFrame + SparseDataFrame
will still emit warnings since we create intermediate SparseSeries.

I probably won't put more time into sparse though.

**Comment by jreback** [comment]
ok thanks, good for now then

**Pull request merged**
