### PR TITLE
BUG: set_levels set wrong order levels for MutiIndex

### LINKED ISSUE #33420: BUG: set_levels set wrong order levels for MutiIndex
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'one', 'one', 'one', 'one', 'one', 'one', 'one'],
          ['three', 'four', 'three', 'four', 'three', 'four', 'three', 'four'],
          ]

df = pd.DataFrame(np.random.randn(8, 4), index=arrays)
df.index.set_levels([3, 4], level=2, inplace=True)
```

#### Problem description

The changed MutiIndex isn't the same order of assigned list.
```
                  0         1         2         3
bar one 4 -0.606998 -1.225794  0.284541 -0.395946
        3  2.693403  0.803962  0.421412 -0.369766
baz one 4  0.182893  0.364850  0.499927  0.271245
        3 -0.783458 -0.072504 -1.081301 -0.091093
foo one 4  2.630340 -0.442308  0.519715 -0.412296
        3 -0.813574  0.323040 -0.356866  1.877196
qux one 4 -0.578158  0.511383  0.613484 -0.483777
        3 -0.161618 -0.481930  0.012694 -1.001978
```

#### Expected Output
```
                  0         1         2         3
bar one 3 -0.606998 -1.225794  0.284541 -0.395946
        4  2.693403  0.803962  0.421412 -0.369766
baz one 3  0.182893  0.364850  0.499927  0.271245
        4 -0.783458 -0.072504 -1.081301 -0.091093
foo one 3  2.630340 -0.442308  0.519715 -0.412296
        4 -0.813574  0.323040 -0.356866  1.877196
qux one 3 -0.578158  0.511383  0.613484 -0.483777
        4 -0.161618 -0.481930  0.012694 -1.001978
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200325
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by yixinxiao7**
- [ ] closes #33420
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Added parameter that allows user to reset codes

### CODE REVIEW

**Comment by yixinxiao7** [comment]
If there's a better way to update the codes, please let me know!

**Review by mroeschke — CHANGES_REQUESTED** [review]
We would want to fix this behavior without adding a new keyword argument to `set_levels`

**Review by jreback — CHANGES_REQUESTED** [review]
can you explain the purpose of this PR. If you reassign the index this works, so why would you need a parameter to do anything? what is exactly the problem?

**Comment by yixinxiao7** [comment]
> can you explain the purpose of this PR. If you reassign the index this works, so why would you need a parameter to do anything? what is exactly the problem?

**Comment by yixinxiao7** [comment]
@jreback Thanks for getting back to me! Sorry if I misunderstood the issue, but I originally believed that set_levels should effectively reassign the index automatically. I do realize now that adding a parameter to the method isn't necessary since the user can reassign the index themselves. Please let me know what your thoughts are on my original understanding!

**Comment by jreback** [comment]
closing as this is an internal implementation detail.

**Pull request closed without merging**
