### PR TITLE
CI: add empty line in `no-bool-in-generic` to avoid `black` complaining

### PR DESCRIPTION
**Pull request by Charlie-XIAO**
*No reference issues (I ran into this during another contribution).*

### CODE REVIEW

**Comment by mroeschke** [comment]
Why is this needed?

**Comment by Charlie-XIAO** [comment]
Originally the last empty line will be deleted, but then if you run pre-commit again `black` will complain about it.

**Comment by mroeschke** [comment]
Can you show a commit where this happened?

**Comment by Charlie-XIAO** [comment]
Does this suffice?

https://github.com/pandas-dev/pandas/assets/108576690/858ec0dc-b550-4e65-93fe-55d2ec53bd53

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
