### PR TITLE
CI: activate github actions on 1.1.x (PR only)

### PR DESCRIPTION
**Pull request by simonjayhawkins**
same as #35459 against master. so should be OK when backported.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
some failures not seen in other PRs. will re-run and see if they repeat.
```
=========================== short test summary info ============================
FAILED pandas/tests/io/formats/test_format.py::TestDataFrameFormatting::test_repr_deprecation_negative_int
FAILED pandas/tests/io/formats/test_format.py::TestDataFrameFormatting::test_repr_min_rows
FAILED pandas/tests/io/formats/test_format.py::TestDataFrameFormatting::test_str_max_colwidth
FAILED pandas/tests/io/formats/test_format.py::TestDataFrameFormatting::test_east_asian_unicode_false
FAILED pandas/tests/io/formats/test_format.py::TestDataFrameFormatting::test_east_asian_unicode_true
FAILED pandas/tests/io/formats/test_format.py::TestDataFrameFormatting::test_datetimelike_frame
= 6 failed, 73402 passed, 1017 skipped, 1051 xfailed, 240 warnings in 1450.34s (0:24:10) =
```

**Comment by simonjayhawkins** [comment]
The option to re-run has disappeared from Travis again.

**Comment by simonjayhawkins** [comment]
test failures unrelated

**Comment by WillAyd** [comment]
Do we even need the branches option or can we just remove and have it run against any target?

**Comment by simonjayhawkins** [comment]
github actions updates the dev docs on the website. so only want that on master.

**Comment by jreback** [comment]
@simonjayhawkins feel free to merge things like this when you need.

**Comment by simonjayhawkins** [comment]
@MeeseeksDev backport to 1.1.x

**Pull request merged**
