### PR TITLE
API: Change str for CategoricalDtype to category

### LINKED ISSUE #17782: API: CategoricalDtype str, repr
I think that `str(cat.dtype)` should be changed back to always being 'category'. I've seen several places where people use `str(thing.dtype) == 'category'` as a way to check for Categoricals. Even subtle things like [this arrow PR](https://github.com/apache/arrow/pull/1161/files#diff-4b312e1fbf7b4c070f9788be9db33b20R198) would break.

So instead of

```
In [6]: str(pd.Categorical([1, 2, 3]).dtype)
Out[6]: 'CategoricalDtype(categories=[1, 2, 3], ordered=False)'
```

it would be

```
Out[6]: 'category'
```

We can leave `__repr__` to be unambiguous.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Better compatibility with older versions

Closes #17782

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jreback** [comment]
I am not sure this is a great idea, what is the purpose here?

**Comment by TomAugspurger** [comment]
There's, lot's of code out there that expects `str(dtype)` to be `'category '`, and an established tradition in Python of `str(obj)` being simple, while `repr(obj)` is more complicated.

Why are you against it?

**Comment by jreback** [comment]
this loses informtion, no reason why for that. where does code == 'str(dtype)` live? IOW can you show me an example from a project?

**Comment by TomAugspurger** [comment]
The information is still there... It's only when you call str(dtype). I
linked to an example in the issue

- https://github.com/dask/fastparquet/pull/200/files
-
https://github.com/dask/dask/pull/2737/commits/f8e382cc3bcf07acfaa03386d6c550d0a2d8507f
-
https://github.com/apache/arrow/pull/1161/files#diff-4b312e1fbf7b4c070f9788be9db33b20R198

**Comment by jreback** [comment]
the ``if str(dtype) == 'category'`` was never a way to do this. to be honest I am in favor of breaking this.

**Comment by TomAugspurger** [comment]
Ok, I'm +1 for this change, and so is Joris.

**Comment by jorisvandenbossche** [comment]
It maybe never really was meant to do that, but before is_categorical was consistently publicly exposed, I think it was a sensible thing to do. 
Personally I don't find undoing the loss of information when converting dtype to string worth it to potentially break people's code.

**Comment by jreback** [comment]
ok then, merge away.

**Comment by jorisvandenbossche** [comment]
Another reason that I think this was a good change, is because it is used in the 'dtypes' overview. Before this PR you got:

```
In [19]: df.dtypes
Out[19]:
cats    CategoricalDtype(categories=['a', 'b', 'c'], o...
vals                                                int64
dtype: object
```

which I think is not ideal (although that might have been solved in another way as well). 

But that did me think, we could think of some kind of 'shorter but still informative' repr like datetimetz has (although once you have more categories, it will always be truncated, which is not that nice in a default repr I think).

**Pull request merged**
