### PR TITLE
CI: Pin setuptools for sdist too

### PR DESCRIPTION
**Pull request by phofl**
Don't understand why this was green before

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]

**Comment by jreback** [comment]
hmm i am not sure that worked

**Comment by phofl** [comment]
Nope, this got reinstalled by the setup-miniconda step

**Comment by phofl** [comment]
This works now

**Comment by jreback** [comment]
excellent! merge on green

**Comment by jreback** [comment]
thanks @phofl

**Pull request merged**
