### PR TITLE
WIP: TST: split up tests/plotting/test_frame.py into subdir & modules #34769

### LINKED ISSUE #34769: TST: split up tests/plotting/test_frame.py into subdir & modules
we should split up this test file into a separate subdir and multiple test modules for better groking. first PR should be a straight move, then can split (or all in one is ok)

### PR DESCRIPTION
**Pull request by iahsanujunda**
Moved `tests/plotting/test_frame.py` to `tests/plotting/frame/test_frame.py`.

Worked towards #34769 but not closing it as this has not split the test suite.

- [ ] xref #34769
- [x] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you merge master and ping on green.

**Comment by iahsanujunda** [comment]
hi @jreback I have merged master and all checks are green now

**Comment by jreback** [comment]
sorry can u merge master again and ping on green 

also remove WIP from title

**Comment by WillAyd** [comment]
@iahsanujunda can you fix the merge conflict?

**Comment by jbrockmendel** [comment]
GH is showing me an empty diff.  is this active?

**Comment by Mikhaylov-yv** [comment]
Can I continue working on this branch?

**Comment by jreback** [comment]
@Mikhaylov-yv pls create a new PR

**Pull request closed without merging**
