### PR TITLE
An optional parameter called check_series_type was created

### LINKED ISSUE #48287: ENH: Allow to skip series type check in assert_frame_equal
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

When using derived Series type in dataframes, it is useful to be able to skip series type check in assert_frame_equal.

```python
import pandas as pd

class Series(pd.Series):
    @property
    def _constructor( self ):
        return Series

    @property
    def _constructor_expanddim( self ):
        return DataFrame

class DataFrame(pd.DataFrame):
    @property
    def _constructor_sliced( self ):
        return Series

s1 = pd.Series( [0] )
s2 = Series( s1 )

pd.testing.assert_series_equal(s1, s2, check_series_type=False)

df1 = s1.to_frame()
df2 = s2.to_frame()

pd.testing.assert_frame_equal(df1, df2, check_frame_type=False)
```

In the code above, the first assert passes, but the second fails with the following message:

```text
DataFrame.iloc[:, 0] (column name="0") classes are different
[left]:  Series
[right]: Series
```

There is currently no easy way to make such dataframes compare equal in testing.

### Feature Description

I suggest the following enhancements:

1. Add a new parameter, `check_series_type` to `assert_frame_equal()` that will pass through to `assert_series_equal()`.
1. Set  the new `check_series_type` to `False` when `check_frame_type` is set to `False`.
1. When type mismatch is detected but type names are the same, include fully qualified names in the assert message. 

### Alternative Solutions

Implement enhancements 1 and 3 without 2.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lucaslarios**
- [x ] closes #48287
- [x ] [Tests added and passed]
- [ x] All [code checks passed]

An optional parameter called check_series_type was created in the assert_frame_equal function which solves the problem passed by issue #48287.

By default the parameter is set to True, however it is now  its possible to set it to False and skip series_type_check.

Example:

import pandas as pd

class Series(pd.Series):
    @property
    def _constructor( self ):
        return Series

    @property
    def _constructor_expanddim( self ):
        return DataFrame

class DataFrame(pd.DataFrame):
    @property
    def _constructor_sliced( self ):
        return Series

s1 = pd.Series( [0] )
s2 = Series( s1 )

pd.testing.assert_series_equal(s1, s2, check_series_type=False)

df1 = s1.to_frame()
df2 = s2.to_frame()

pd.testing.assert_frame_equal(df1, df2, check_frame_type=False,check_series_type=False)

### CODE REVIEW

**Review by phofl — CHANGES_REQUESTED** [review]
Hey, please always add tests

**Comment by lucaslarios** [comment]
> Hey, please always add tests

is there any documentation explaining the requested test patterns?

**Comment by phofl** [comment]
You can check the contributor guide, testing is explained there as well

https://pandas.pydata.org/docs/dev/development/contributing.html

**Comment by lucaslarios** [comment]
Tests have been added

**Comment by lucaslarios** [comment]
Still relevant?

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
