### PR TITLE
ENH: Add 'truncate' option for if_exists arg for DataFrame.to_sql method

### LINKED ISSUE #37210: ENH: DataFrame.to_sql with if_exists='replace' should do truncate table instead of drop table
#### Is your feature request related to a problem?
Dropping table when if_exists=‘replace’ will fail if the table has any objects, like a view, depending on it. Also, some databases like Oracle will end a transaction implicitly when a DLL statement like 'drop table' is issued. 

#### Describe the solution you'd like
Better alternative would be to issue 'truncate table' command instead.

#### API breaking implications

Should not have any changes on API

#### Describe alternatives you've considered

As above or a new flag if_exists=‘truncate’

### PR DESCRIPTION
**Pull request by lzieglerpenn**
This is my first ever PR on an open source project. This one seemed pretty small & straight forward so I gave it go.  Just merged main into the branch so it is conflict free. Please let me know if there's anything else I can do to help get this merged!

See issue #37210 for more context but this essentially gives a user the option to truncate an existing table before inserting new rows into it via the `DataFrame.to_sql` method.

- [X] closes #37210
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [X] Added an entry in the latest `doc/source/whatsnew/v2.1.0.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by iBoxerman** [comment]
Amazing!
I was wondering why truncate isn’t supported.

**Review by mroeschke — CHANGES_REQUESTED** [review]
Thanks for the PR, but it's preferred to use a sqlalchemy function to truncate instead of running raw SQL since it's not guaranteed for the SQL to be database dialect agnostic

**Comment by lzieglerpenn** [comment]
> Thanks for the PR, but it's preferred to use a sqlalchemy function to truncate instead of running raw SQL since it's not guaranteed for the SQL to be database dialect agnostic

Thanks @mroeschke ! I couldn't find anything in the SQLalchemy docs for truncate specifically but [they do have](https://docs.sqlalchemy.org/en/20/core/dml.html#sqlalchemy.sql.expression.delete) `.delete()` which would have the same end result of keeping the table but removing all the existing rows. Would that be acceptable function to use for the `truncate` option?

**Comment by mroeschke** [comment]
I suppose `delete` would work, but possible renaming the option to `delete_rows` would be more appropriate

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
