### PR TITLE
COMPAT: add back dummy CategoricalBlock class

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/pandas-dev/pandas/issues/40226#issuecomment-804903010

@jbrockmendel this is unfortunate, but short term I think we need to keep the CategoricalBlock class. I am not directly sure what would be the best way to actually deprecate this.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
>  I am not directly sure what would be the best way to actually deprecate this.

Could keep the deprecation in `internals.__init__.__getattr__`

**Comment by jorisvandenbossche** [comment]
Ah, yes, that's a good idea. Since we don't use that import path ourselves, we can still deprecate accessing the class that way.

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jreback** [comment]
what is the user of this actual class? pyarrow?

**Comment by jorisvandenbossche** [comment]
yes, pyarrow uses `isinstance(block, CategoricalBlock)` right now

**Comment by jreback** [comment]
why didn't this break the CI? (the original change)

**Comment by jorisvandenbossche** [comment]
Because we don't have full coverage of pyarrow functionality in our tests (and we don't run the full pyarrow test suite), there were only a few failures in the pyarrow CI.

**Comment by jreback** [comment]
> Because we don't have full coverage of pyarrow functionality in our tests (and we don't run the full pyarrow test suite), there were only a few failures in the pyarrow CI.

ahh ok. is it possible to add something that exercises internals? (not blocking here)

**Pull request merged**
