### PR TITLE
BUG&TST: HTML formatting error in Styler.render() in rowspan attribute

### PR DESCRIPTION
**Pull request by JoseNavy**
- [x] closes [#38234](https://github.com/pandas-dev/pandas/issues/38234)
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
can you add a whatsnew note, bug fixes for 1.2 (add a Styler sub-section after Plotting). merge master and ping on green-ish.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
lgtm ping on greenish

**Comment by JoseNavy** [comment]
The Travis check didn't pass and after checking why, I don't see a clear error on what went wrong. All the other checks did pass, can you help me with this? @jreback

**Comment by jreback** [comment]
thanks @JoseNavy the travis CI is acting up, unrelated

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
