### PR TITLE
DOC: Add example to pandas.DataFrame.applymap

### PR DESCRIPTION
**Pull request by proinsias**

### CODE REVIEW

**Comment by MaximilianR** [comment]
Examples are great - how would you feel about having one that distinguishes `applymap`? `df.apply(abs)` gives the same result there

**Comment by jorisvandenbossche** [comment]
Further, `abs` is actually not a really good example as a functions for which you need `applymap`, as `abs(df)` will also work due to delegation to `__abs__`

**Comment by proinsias** [comment]
I've updated this to use a function that operates element-wise.

**Comment by MaximilianR** [comment]
:+1:

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
