### PR TITLE
CLN: suppress distutils warnings, assorted 

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@mroeschke do you have a gameplan for fixing the py38 GHA or should i spend some time troubleshooting it?

**Comment by mroeschke** [comment]
I'm looking into it, not lead yet, but some help would be appreciated.

IIRC I saw this yesterday too but the logs are not that helpful

```
2022-01-27T19:21:29.7660840Z Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-latest'
2022-01-27T19:21:29.8118611Z Waiting for a Hosted runner in the 'organization' to pick this job...
2022-01-27T19:21:30.1206185Z Job is waiting for a hosted runner to come online.
2022-01-27T19:21:34.4331926Z Job is about to start running on the hosted runner: GitHub Actions 31 (hosted)
```

**Comment by mroeschke** [comment]
On other builds, it appears like another test is hanging since builds are exiting with 143 sigterms

**Comment by jbrockmendel** [comment]
@mroeschke thoughts here?  id like to get the warning suppression in

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
