### PR TITLE
Use correct random choice function in code snippet

### PR DESCRIPTION
**Pull request by carroux**
A hidden code snippet uses `tm.choice()` when it should use `np.random.choice()`

### CODE REVIEW

**Comment by carroux** [comment]
cc @ellisonbg

**Comment by TomAugspurger** [comment]
@carroux thanks!

**Comment by jreback** [comment]
so I think this was for numpy < 1.7 compat.

pls remove this: https://github.com/pydata/pandas/blob/master/pandas/util/testing.py#L173

as well (its possible there are some other references as well), pls search the docs; in the code I think something will fail.

thanks!

**Comment by jreback** [comment]
oh, saw @TomAugspurger merged this, ok. then.

**Comment by TomAugspurger** [comment]
Ha, sorry bout that. FYI

```bash
pandas/tests/frame/test_query_eval.py
99:        a = tm.choice(['red', 'green'], size=10)
100:        b = tm.choice(['eggs', 'ham'], size=10)
152:        a = tm.choice(['red', 'green'], size=10)
153:        b = tm.choice(['eggs', 'ham'], size=10)
246:        a = tm.choice(['red', 'green'], size=10)
978:        a = Series(tm.choice(list('abcde'), 20))

pandas/tests/test_graphics_others.py
638:            gender = tm.choice(['male', 'female'], size=n)
712:            gender_int = tm.choice([0, 1], size=n)

pandas/tests/test_graphics.py
63:            gender = tm.choice(['Male', 'Female'], size=n)
64:            classroom = tm.choice(['A', 'B', 'C'], size=n)
3864:            gender = tm.choice(['male', 'female'], size=n)

pandas/tools/tests/test_merge.py
239:            df = DataFrame({'a': tm.choice(['m', 'f'], size=3),
241:            df2 = DataFrame({'a': tm.choice(['m', 'f'], size=10),
248:            df = DataFrame({'a': tm.choice(['m', 'f'], size=3),
251:            df2 = DataFrame({'a': tm.choice(['m', 'f'], size=10),
257:            df = DataFrame({'a': tm.choice(['m', 'f'], size=3),
259:            df2 = DataFrame({'a': tm.choice(['m', 'f'], size=10),
```

are the other occurrences.

**Pull request closed without merging**
