### PR TITLE
CI: py38 builds

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
greenish

**Comment by jreback** [comment]
hmm does this fix?

**Comment by jbrockmendel** [comment]
> hmm does this fix?

fixes the py38 issue yah

**Comment by jbrockmendel** [comment]
btw who is the go-to person for merge_asof?

**Comment by jreback** [comment]
you, me or @mroeschke

**Comment by jbrockmendel** [comment]
hah if its me then we're in trouble

**Pull request merged**
