### PR TITLE
Replaced value assignment by location accessor.

### PR DESCRIPTION
**Pull request by kosmitive**
Changed self.obj[key] = value to self.obj.loc[:, key] = value to disable warning.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by mzeitlin11** [comment]
Thanks for the pr @kosmitive.  Is there an issue associated with this? What is the behavior change here (and if there is, it should be tested). Also seems like a change that might be performance sensitive

**Review by jreback — CHANGES_REQUESTED** [review]
pls explain rationale

**Comment by kosmitive** [comment]
I get a warning otherwise that the old command operates on a copy, so I thought changing it to in-place assignment would make sense and be a really quick fix. But I didn't do further investigation on that line of code.

**Comment by kosmitive** [comment]
@mzeitlin11 @jreback  Here is the warning I get with python 3.9

.../.venv/lib/python3.9/site-packages/pandas/core/indexing.py:1597: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

**Comment by jreback** [comment]
@kosmitive pls file an issue with a reproducible test. The code you are touching is not trivially changed and has quite some implications.

**Comment by mroeschke** [comment]
Thanks for the PR, but agreed it would be better if an issue could be raised first so the entirety of the issue could be understood before diving into a fix. Closing.

**Pull request closed without merging**
