### PR TITLE
ARM64 parallel builds

### LINKED ISSUE #36719: CI: arm Travis build timing out
I'm seeing this in most but not all builds ATM.

Even if we moved it to allowed-failures, it would still be slowing the Travis turnaround time down a lot.

### PR DESCRIPTION
**Pull request by lithomas1**
- [x] closes #36719 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Seems to have gotten build from > 1 hr to ~ 38 min.

### CODE REVIEW

**Comment by jreback** [comment]
thanks @lithomas1 yes this looks great!

**Comment by martin-g** [comment]
Hi!
Actually this PR changed from ARM64 to AMD64. See https://travis-ci.com/github/pandas-dev/pandas and expand `Build system information` . There you will see `OS/Arch:           linux/amd64`. The label "arm64-graviton2" is a known bug but Travis people don't want to fix it.

https://blog.travis-ci.com/2020-09-11-arm-on-aws, section "Quick tips" says: `You have to explicitly set virt: and group: keys to invoke the AWS Graviton2 CPU. Otherwise, your builds will be routed to the Travis CI default amd64 environment.`

**Comment by jreback** [comment]
wow that's a crazy bug

cc @lithomas1

**Comment by martin-g** [comment]
A fix is proposed with https://github.com/pandas-dev/pandas/pull/40959

**Pull request merged**
