### PR TITLE
MAINT: Remove assertRaises from testing

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.  Pretty hefty PR this one.

Partially addresses #15990.

### CODE REVIEW

**Comment by jreback** [comment]
thanks!

awesome job!

**Comment by gfyoung** [comment]
FYI (for future PR's), `tm.assertRegexp` should not be used.  Rather, we should use this paradigm:
~~~python
with pytest.raises(cls) as exc_info:
   ...
exc_info.matches(regexp)
~~~
I stumbled upon this while doing this massive PR.

**Comment by jreback** [comment]
hmm, that's going to be a change, though ok with it if its documented :>

can you create a context manager which emulated ``assertRaisesRegexp`` (or gives a better name)?

**Comment by gfyoung** [comment]
> hmm, that's going to be a change, though ok with it if its documented :>

Yes, I added that in this PR.

> can you create a context manager which emulated assertRaisesRegexp (or gives a better name)?

I think the name is alright, and we do have a context manager for this (it's a port of Python 2.7's implementation).

**Comment by jorisvandenbossche** [comment]
@gfyoung what is wrong with `tm.assertRaisesRegexp` ? (why should it not be used)

**Comment by gfyoung** [comment]
It isn't idiomatic under the pytest framework.  Also, it is a port of Python's unittest `tm.assertRaisesRegexp` (extra bloat to test framework).

**Comment by jorisvandenbossche** [comment]
Why isn't it idiomatic? I think it is *very* similar to `pytest.raises` in usage, but with a more specific functionality (just a different style in the naming)

And it is not because it is a port of a unittest function, that is is bad?

**Comment by jreback** [comment]
i agree with joris
let's just rename to non camel

**Comment by gfyoung** [comment]
The <a href="https://docs.pytest.org/en/latest/assert.html">docs</a> explicitly address `regex` matching in the form that I described <a href="https://github.com/pandas-dev/pandas/pull/16089#issuecomment-296316048">above</a>.  Does that change anything?

Also, I don't know what you think about this, but what about `pytest.warns` instead of `tm.assert_produces_warning` (see <a href="https://docs.pytest.org/en/latest/recwarn.html#warns">here</a>)?

I'm not pushing these very hard (I ask because they are the `pytest` conventions instead of `unittest` for example).  However, even if we don't make these changes, we could at least document in #15990 why they were not made.

**Comment by jorisvandenbossche** [comment]
I still think a helper function is more easy to use than what the pytest docs propose to do (but nice docs actually!), but based on what they do, we can probably simplify the current implementation of `assertRaisesRegex` a lot?

**Comment by gfyoung** [comment]
The current implementation of `assertRaisesRegexp` is relatively stripped down I thought.  Most of the heavy lifting is done by the context manager.  What did you think we could simplify?

**Comment by jorisvandenbossche** [comment]
What I meant was that wrapping the code snippet you gave above in a new contextmanager, may be less code than the current implementation. 
But I didn't look in detail whether this would be worth it (actually improve code simplicity), and it may also not cover directly all cases that the current code can handle.

**Comment by gfyoung** [comment]
Hmmm...I'm not sure how worthwhile that may be since you have to consider both cases when it is used as a context manager (`with`) statement or a pure function call (context manager used internally).  And I don't think wrapping the `pytest` snippet is flexible enough to avoid duplicating logic.

**Pull request merged**
