### PR TITLE
TST: skip -> xfail

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@mroeschke ive started getting local test failures at collect-time with "ERROR: Unknown config option: asyncio_mode".  commenting out the 'asyncio_mode = "strict"' line in pyproject.toml seems to fix it.  Could this be related to any of the recent CI stuff you've been doing?

**Comment by mroeschke** [comment]
> @mroeschke ive started getting local test failures at collect-time with "ERROR: Unknown config option: asyncio_mode". commenting out the 'asyncio_mode = "strict"' line in pyproject.toml seems to fix it. Could this be related to any of the recent CI stuff you've been doing?

Hmm do you have `pytest-asyncio` in your virtual environment?

**Comment by jbrockmendel** [comment]
> Hmm do you have pytest-asyncio in your virtual environment?

Yes.  should i get rid of it?

**Comment by mroeschke** [comment]
Hmm odd I've seen the CI complain if it wasn't installed. What are your pytest & plugin versions? Or maybe it's a pytest cache issue?

```
(pandas-dev) ...  % pytest pandas --collect-only
========================================================= test session starts ==========================================================
platform darwin -- Python 3.8.12, pytest-7.0.0, pluggy-1.0.0
rootdir: /Users/... , configfile: pyproject.toml, testpaths: pandas
plugins: xdist-2.5.0, forked-1.4.0, cython-0.1.1.post0, hypothesis-6.36.1, instafail-0.4.1, asyncio-0.18.0, cov-3.0.0
asyncio: mode=strict

...
========================================== 166393 tests collected in 49.85s ===========================================
```

**Comment by jbrockmendel** [comment]
looks like upgrading from 0.14..0 to 0.18.0 fixed it, thanks.  sorry for derailing.

**Pull request merged**
