### PR TITLE
have _NaT subclass datetime directly

### LINKED ISSUE #17435: NaT inheritance
`pd.NaT` is an instance of `NaTType`.  `NaTType` inherits from `_NaT`, which inherits from `_Timestamp`, which inherits from `datetime`.

How would people feel about taking `_Timestamp` out of that chain?  Note that `_Timestamp` is not exported, so no users should be checking e.g. `isinstance(x, _Timestamp)`.

The motivation: if we can take `_Timestamp` out of the inheritance chain, then the entire `NaT` hierarchy along with the instance itself can be defined in its own dedicated module, with no intra-pandas dependencies other than `util`.  This comes out to a little over 500 lines.

This opens up opportunities for simplification elsewhere, since there are a _bunch_ of modules that import `NaT` but don't care about most of the rest of `tslib` (the same applies to the timezones functions in #17274).  Of particular interest are `_libs.lib`, `_libs.period`, `tseries.frequencies`, and `tseries.offsets`.

The other upside is that with few dependencies, the module becomes much easier to test/benchmark/maintain.

Without `_NaT` inheriting from `_Timestamp`, a methods in `_Timestamp` become eligible for the `@cython.final` decorator.  My (limited) understanding is that this provides a small performance improvement.

The main downside I see is that the docstring pinning done by `_make_error_func`, `_make_nat_func`, and `_make_nan_func` is a bit of a hassle.

### PR DESCRIPTION
**Pull request by jbrockmendel**
The main change made by this PR is to have `_NaT` subclass `datetime` directly instead of subclassing `_Timestamp`.  Everything else is just to preserve the current behavior.

Why you ask?  Because once this is OKed, the entire `NaT` machinery can be cut/paste into a stand-alone module whose only intra-pandas dependency is `util`.

The only non-trivial behavior is in `__add__` and `__sub__`, where currently `_NaT` dispatches to `_Timestamp` for a few cases.  This PR re-implements those cases directly in `_NaT`.  While that does mean a small amount of repetition, it opens up the possibility of using `@cython.final` for potential optimization in `_Timestamp.__add__/__sub__`.

`NaTType.to_datetime` could use `_make_nat_func` if we were OK with it not producing the same warning as `Timestamp.to_datetime`.

- [ ] closes #17435
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
going to wait on this till after we release 0.21.0

**Comment by jreback** [comment]
note that we might as well NOT subclass datetime at all! its a bit tricky though you would have to implement a metaclass so isinstance check would work (IOW you still want this to be a datetime). but that makes this simpler.

**Comment by jbrockmendel** [comment]
> its a bit tricky though you would have to implement a metaclass so isinstance check would work 

My impression is that metaclasses in cython are finicky.  That might be out of date.

> going to wait on this till after we release 0.21.0

Sounds good.  In the interim I'll try to finish off the `offsets` and go down the TODO list.

**Comment by jreback** [comment]
i would like to see this not subclass datetime
then this becomes really simple; would still have to be able to masquerade as a datetime/timedelta
for isintsance checks

you can dig into the CPython source to see how this is done

**Comment by jbrockmendel** [comment]
> i would like to see this not subclass datetime

I'll put looking into this on the tslibs todo list.

> then this becomes really simple; would still have to be able to masquerade as a datetime/timedelta for isintsance checks

At the moment `isinstance(NaT, Timedelta)` returns False.  Is it supposed to be True?

**Comment by jreback** [comment]
> At the moment isinstance(NaT, Timedelta) returns False. Is it supposed to be True?

hmm maybe we don’t event need to make isinstance be true; so try not subclassing datetime and see what breaks;

**Comment by jbrockmendel** [comment]
> hmm maybe we don’t event need to make isinstance be true; so try not subclassing datetime and see what breaks;

Do you mind saving that for a follow-up?  This has been added to #17652.

**Comment by jreback** [comment]
ok this lgtm.

**Comment by jreback** [comment]
@jbrockmendel if you want to merge in different order that my arbitrary one :> lmk. just ping which one should go first.

**Comment by jbrockmendel** [comment]
I'll be happy with any order; go nuts. Way to be a closer today!

**Comment by jreback** [comment]
thanks!

**Pull request merged**
