### PR TITLE
REGR: Better warning in pivot_table when dropping nuisance columns

### LINKED ISSUE #49247: BUG: Getting FutureWarning for Groupby.mean when using .pivot_table
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({"C1": ["a", "b", "c"],
                   "C2": [1, 2, 3]})
table = pd.pivot_table(df, columns=['C2'])
```

### Issue Description

Getting FutureWarning:

"<stdin>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function."

### Expected Behavior

pivot_table is internally using DataFrameGroupBy.mean, but does not allow a user to pass a numeric_only argument as suggested in the FutureWarning

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.9.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.4.0-19041-Microsoft
Version          : #1237-Microsoft Sat Sep 11 14:32:00 PST 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.5
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.3
Cython           : None
pytest           : 7.1.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           :
fastparquet      : None
fsspec           : 2022.10.0
gcsfs            : None
matplotlib       : 3.6.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.2
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] closes #49247 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
Looks good. Does this warrant a whatsnew?

**Review by phofl — APPROVED** [review]
thx, this looks great.

I don't think we need a whatsnew here

**Comment by rhshadrach** [comment]
Agreed @phofl - users are currently getting FutureWarnings, so really no behavior change. The change in message is just a bit easier to understand.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @rhshadrach

**Comment by rhshadrach** [comment]
@mroeschke - I can take care of the backport, but meeseeks usually has very explicit output for doing so - did this get moved to somewhere else?

**Comment by phofl** [comment]
its also not adding the manual backport label, something is off

**Comment by mroeschke** [comment]
Don't think this should have changed. I'll try retriggering the backport

**Comment by mroeschke** [comment]
@meeseeksdev backport 1.5.x

**Comment by rhshadrach** [comment]
@meeseeksdev say hi

**Comment by Sierra-MC** [comment]
Thank you!

**Comment by rhshadrach** [comment]
@meeseeksdev backport 1.5.x

**Comment by MarcoGorelli** [comment]
@meeseeksdev backport 1.5.x

**Comment by MarcoGorelli** [comment]
looks like this was already backported manually in #49653

removing the 'still needs manual backport' then

**Comment by rhshadrach** [comment]
Ack - sorry for my bad bookkeeping @MarcoGorelli!

**Pull request merged**
