### PR TITLE
WEB: Update versions json to fix version switcher in the docs

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] xref https://github.com/pandas-dev/pandas/pull/48600#issuecomment-1252065060

CC: @phofl

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
So we don't need the full path?

**Comment by datapythonista** [comment]
> So we don't need the full path?

The url is only used in the new version of the theme, and for what I saw the value is used directly in the href, so probably better without then I think.

**Comment by phofl** [comment]
I am asking because initially we had the full path:

```
    "switcher": {
         "json_url": "https://pandas.pydata.org/versions.json",
         "url_template": "https://pandas.pydata.org/{version}/",
         "json_url": "/versions.json",
         "version_match": switcher_version,
     },
```

but this is part of the conf.py, so the old versions of the docs can still access this, correct?

**Comment by datapythonista** [comment]
Yes, everything in conf.py stays in the already rendered version of the docs, so it's not affecting the released versions, and we can't update it for them either.

Both will work, with and without the domain. But without will allow for example to test it in the new server without unintentionally going to the old one.

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @datapythonista

**Pull request merged**
