### PR TITLE
CLN: Clean some formatting

### PR DESCRIPTION
**Pull request by dsaxton**
ref https://github.com/pandas-dev/pandas/issues/36450

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Some of this seems to overlap with #36453, e.g. pandas/core/generic.py

**Comment by dsaxton** [comment]
> Some of this seems to overlap with #36453, e.g. pandas/core/generic.py

Ah you're right (maybe we're using the same tool 😄). This may find some different things so could always merge that one in and look at the (hopefully non-zero) diff between master and this branch afterwards. Or if we're doing literally the exact same thing I could just close this.

**Comment by MarcoGorelli** [comment]
:rofl: looks like we had the same idea, sorry!

Looks like the rest of the files are covered by #36457

**Comment by dsaxton** [comment]
NP, I can just close this

**Pull request closed without merging**
