### PR TITLE
ENH: Adding implementation for issue #51748

### LINKED ISSUE #51748: ENH: Allow dictionaries to be passed to pandas.Series.str.replace
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I often want to replace various strings in a Series with an empty string and it would be nice to be able to do so in one call passing  dictionary rather than chaining multiple `.str.replace` calls.

Alternatively I *can* use the regex flag and use some OR logic there but I think it would be much cleaner and more consistent with other functions to be able to pass a dictionary in my opinion.

### How it currently works
```python
messy_series = pd.Series(
    data=['A', 'B_junk', 'C_gunk'],
    name='my_messy_col',
)

clean_series = messy_series.str.replace('_junk', '').str.replace('_gunk', '')
clean_series = messy_series.str.replace('_junk|_gunk', '', regex=True)
```
### How I'd like for it work

```python
messy_series = pd.Series(
    data=['A', 'B_junk', 'C_gunk'],
    name='my_messy_col',
)

clean_series = messy_series.str.replace({'_gunk':'', '_junk':''})
```

Curious folks' thoughts, thanks y'all!!

### Feature Description

A simple way to solve the problem would be inspect if a dictionary is passed to `str.replace`, and if so iterate over the items of the dictionary and simply call replace on each key/value pair.

If this is an acceptable way to do it from the maintainers' perspectives then I'd happily submit such a PR. 

### Alternative Solutions

As mentioned above, both the following indeed currently work:
```python
messy_series = pd.Series(
    data=['A', 'B_junk', 'C_gunk'],
    name='my_messy_col',
)

clean_series = messy_series.str.replace('_junk', '').str.replace('_gunk', '')
clean_series = messy_series.str.replace('_junk|_gunk', '', regex=True)
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rmhowe425**
- [X] closes #51748 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [X] Added an entry in the latest doc/source/whatsnew/vX.X.X.rst file if fixing a bug or adding a new feature.

* Adding implementation for issue #51748 51748

### CODE REVIEW

**Comment by rmhowe425** [comment]
Second commit should fix the 2 failing code check tests. Needed to add an extra line at the end of `accessor.py`

**Comment by rmhowe425** [comment]
@rhshadrach Do you see any issues with this PR?

**Comment by rmhowe425** [comment]
Hi  @MarcoGorelli, this PR should be good to go now since I have taken care of all 5 tasks. I'm not sure if I should reach out to someone to inspect this PR.

**Comment by rhshadrach** [comment]
I'm not sure we should be expanding the API here; I've put some comments in the linked issue.

**Comment by rmhowe425** [comment]
@rhshadrach I saw the comments. Should I cancel the PR?

**Comment by rhshadrach** [comment]
In this instance, I would recommend closing to take it off the queue until there is some consensus for this feature. We can reopen if we decide to go forward with it. In the meantime, any feedback on why this is worth supporting would help in pushing the discussion forward.

**Comment by rmhowe425** [comment]
@rhshadrach In the future, should I avoid tackling enhancement requests with the `Needs Triage` tag? It seems like I jumped the gun on this one

**Comment by rhshadrach** [comment]
Yes - that would be my recommendation. And I would also extend that to enhancements that do not have a consensus among core developers as to whether they should be added. The pandas API is very large, and we are cautious about making potentially unnecessary additions.

**Pull request closed without merging**
