### PR TITLE
CLN: Break up aggregate.transform

### PR DESCRIPTION
**Pull request by rhshadrach**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Precursor to #36478. Just breaks up transform without any code changes.

### CODE REVIEW

**Review by arw2019 — COMMENTED** [review]
Just an idea but it looks like we have a bunch of functions with the same signature which differ by the type of `func` arg. Would it make sense to use `single dispatch`?

**Comment by rhshadrach** [comment]
Thanks for the suggestion @arw2019. In this particular case, I think not. In #36478, we'll change e.g. `isinstance(func, dict)` to using `is_dict_like`. I believe that makes singledispatch not viable.

**Comment by arw2019** [comment]
> Thanks for the suggestion @arw2019. In this particular case, I think not. In #36478, we'll change e.g. `isinstance(func, dict)` to using `is_dict_like`. I believe that makes singledispatch not viable.

Right, that makes sense.

Another question, should `transform_dict_like` and `transform_str_or_callable` be underscored? Since AFAICT they're private methods

**Comment by jreback** [comment]
> > Thanks for the suggestion @arw2019. In this particular case, I think not. In #36478, we'll change e.g. `isinstance(func, dict)` to using `is_dict_like`. I believe that makes singledispatch not viable.
> 
> Right, that makes sense.
> 
> Another question, should `transform_dict_like` and `transform_str_or_callable` be underscored? Since AFAICT they're private methods

this entire hierarchy is private pandas/core/* (yes it doesn't actually look like it, but its been document this way for a long time)

**Comment by jreback** [comment]
thanks @rhshadrach 

happy to have typing passes as well

**Pull request merged**
