### PR TITLE
PERF: avoid printing object in Dtype.construct_from_string message

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/pandas-dev/pandas/pull/26562#issuecomment-500120556

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Can you post the ASV for one of the affected benchmarks?

**Comment by jorisvandenbossche** [comment]
Master:

```
In [1]: import scipy.sparse

In [2]: N = 1000 
   ...: sparse = scipy.sparse.rand(N, N, 0.005)

In [3]: import warnings

In [4]: warnings.simplefilter('ignore', FutureWarning)

In [5]: %timeit pd.SparseDataFrame(sparse)
2.7 s ± 512 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

This PR:

**Comment by jreback** [comment]
well that's a difference!

though, why is the construction of the SDF so much? (even now)

**Comment by jorisvandenbossche** [comment]
> though, why is the construction of the SDF so much? (even now)

It's quite a big matrix / DataFrame (1000 columns), and we need to create a SparseArray for each column of the sparse matrix. So there is some conversion needed. It might be possible to optimize, although the `DataFrame.sparse.from_spmatrix`, which uses a totally different implementation, also takes around 400 ms, so quite similar.

**Comment by jreback** [comment]
thanks @jorisvandenbossche

**Pull request merged**
