### PR TITLE
Use set literal syntax for set prettyprinting

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by jreback** [comment]
pls add a test in ``tests/test_format.py`` in ``test_pprint``

**Comment by jreback** [comment]
pls add a whatsnew note in 0.17.1 as well

**Comment by jreback** [comment]
can you add a whatsnew note (api changes section)

**Comment by flying-sheep** [comment]
done

**Comment by jreback** [comment]
can you add a test as well

``tests/test_format.py`` in ``test_pprint``

**Comment by flying-sheep** [comment]
done

**Comment by jreback** [comment]
awesome. ping when green.

**Comment by flying-sheep** [comment]
ping!

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/76d4c49a10b2606458d2622a05bb14aea578e9a5

thanks!

**Pull request closed without merging**
