### PR TITLE
CI: Don't split slow vs non slow jobs for GHA posix

### PR DESCRIPTION
**Pull request by mroeschke**
Since GHA has a 6 hour job limit, and it appears that slow jobs take ~25 mins and non-slow jobs take ~35 minutes, it shouldn't be necessary to split these anymore.

Helps reduce the number of builds so more can run concurrently.

### CODE REVIEW

**Comment by jreback** [comment]
this needed?

**Comment by mroeschke** [comment]
Yup this is an orthogonal cleanup.

**Comment by mroeschke** [comment]
All good here. Failure unrelated.

**Comment by jreback** [comment]
@mroeschke needs a rebase

**Comment by jreback** [comment]
@mroeschke one more rebase if you can and https://github.com/pandas-dev/pandas/runs/4932326914?check_suite_focus=true failed (but looks suprios)

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
