### PR TITLE
WEB: Update feed to Tom's posts

### PR DESCRIPTION
**Pull request by datapythonista**
The link to Tom's blog is broken, and it used to fetch everything (not only pandas related things).

Updated the link to the rss new location for the pandas tag.

CC: @TomAugspurger

### CODE REVIEW

**Comment by datapythonista** [comment]
@TomAugspurger looks like your blog has invalid dates for some posts. Can you have a look at your side please? I don't think we want to add any hack for this in the pandas codebase.

**Comment by TomAugspurger** [comment]
Maybe fixed on my side.

**Comment by datapythonista** [comment]
Cool, rerunning the CI, let's see if it works now.

**Comment by datapythonista** [comment]
Seems like at least one of the posts still have a published date with year set to zero: https://github.com/pandas-dev/pandas/actions/runs/4248115161/jobs/7386912564#step:5:21

**Comment by TomAugspurger** [comment]
I think I have this fixed locally. https://github.com/pandas-dev/pandas/actions/runs/4248115161 is the re-triggered job.

**Comment by datapythonista** [comment]
Excellent. Seems like the web could be generated without problems this time. :) I just merged master, so we can easily preview the blog and see if your posts are there (this PR was opened before the previewing system, and the preview wasn't triggered at the end of the docs build).

**Comment by datapythonista** [comment]
Oh, nice, you've got a recent article, it was easy to check if this was working: https://pandas.pydata.org/preview/51438/community/blog/

Feel free to merge this when you want. I'm going to read it. ;)

**Comment by datapythonista** [comment]
Ups, seems like it's an article from 2014 that appears in the rss as being from this week. Not sure if it's still relevant the article, but I guess better to fix the date so it doesn't appear as recent in the pandas blog.

**Comment by datapythonista** [comment]
@TomAugspurger could you have a look at the problem above? If it's not easy to fix, I may remove the feed to your blog for now, so it's not broken (I'd like to fail the CI is a blog feed is broken in a separate PR, so we realize of problems earlier). Then you can add it back whenever the dates in your blog are fixed.

Happy to wait few more days, but if it's going to take much longer, maybe let's do this?

**Comment by datapythonista** [comment]
Closing. Feel free to reopen or open a new PR once the blog is fixed.

**Pull request closed without merging**
