### PR TITLE
MAINT: asv with py3 on windows

### PR DESCRIPTION
**Pull request by chris-b1**
Since benchmarking on python 3, no longer want to install `libpython`

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Can you keep those entries but specify it is only for python 3? 
Then for people benchmarking on python 2, it keeps working

**Comment by chris-b1** [comment]
@jorisvandenbossche - asv actually still works on python 2 with this change, as long as the right version of MSVC is installed (https://www.microsoft.com/en-us/download/details.aspx?id=44266).

This would be the same compiler our release binaries / tests are built with, and easy enough to install now (wasn't always), so I think we should prefer it over the `mingw` toolchain.

**Comment by jorisvandenbossche** [comment]
OK, I currently don't use python 2 on windows anymore, so won't push too hard. I just know that being able to just conda install the correct compilers was very handy at that time :-) But if that has improved, then certainly OK!

Our contributing docs still mention `libpython`: http://pandas-docs.github.io/pandas-docs-travis/contributing.html#creating-a-windows-development-environment

**Comment by chris-b1** [comment]
Yeah, that's fair, I think MSVC would be the 'recommended' way now, but `libpython` is still valid for 2.x.  I added a comment that hopefully is a decent middle ground?

**Comment by jorisvandenbossche** [comment]
thanks!

**Pull request merged**
