### PR TITLE
WIP BUG: Inconsistent date parsing of to_datetime

### LINKED ISSUE #12585: Inconsistent date parsing of to_datetime
As this comes up regularly:
- [x] https://github.com/pydata/pandas/issues/12583
- [x] https://github.com/pydata/pandas/issues/12501
- [x] https://github.com/pydata/pandas/issues/7348
- [x] https://github.com/pandas-dev/pandas/issues/15075
- [x] #12611 deal with `yearfirst/datefirst` in `read_csv`
- [x] #12730, compat with dateutil 2.5.2 `dayfirst=True, yearfirst=True` fixes
- [x] https://github.com/pydata/pandas/issues/14301 raise if inconsistency in `read_csv` with `dayfirst/yearfirst`
- [x] performance https://github.com/pandas-dev/pandas/issues/25848
**The problem**

Depending on the string formats, you can get inconsistent parsing (meaning: different interpretation of parts of the strings as days vs months between different values in the passed list/array of strings). 
For example:

```
In [22]: pd.to_datetime(["31/12/2014", "10/03/2011"])
Out[22]: DatetimeIndex(['2014-12-31', '2011-10-03'])
```

where the first is parsed as 'dayfirst' and the second not. Above particular case can be solved by passing `dayfirst=True`, but in any case, the default behaviour of `to_datetime` results in inconsistent parsing here. 
Another typical case if where you do provide `dayfirst=True` but have a malformed date, then it will fall back to 'not dayfirst' (https://github.com/pydata/pandas/issues/3341).

**The reason**

The reason is the flexibility of `dateutil.parser.parse`. This is in the first place also a feature, as it lets you parse messy datetime colums. But when it comes to flexibility regarding `dayfirst`/`yearfirst`, this gives unexpected results. 
So dateutil will 'try' to use `dayfirst=True`, but when this does not give a valid date, it will ignore `dayfirst=True` and parse the string anyway:

```
In [3]: dateutil.parser.parse('1/12/2012', dayfirst=True)
Out[3]: datetime.datetime(2012, 12, 1, 0, 0)

In [4]: dateutil.parser.parse('1/13/2012', dayfirst=True)
Out[4]: datetime.datetime(2012, 1, 13, 0, 0)
```

The same is true for `dayfirst=False` (the default) as this will also try with 'day first' if the other way around failed. 
The issue for the lack of strictness of dayfirst is actually https://github.com/pydata/pandas/issues/3341.

**Possible solutions**
- In some cases passing `dayfirst=True` is sufficient (if you don't have messy or malformed dates).
- The typical answer is saying: "if you want to be sure to have strict and consistent parsing, provide a `format` argument. 
  We should probably stress this more in the docstring of `to_datetime` 

But, regardless of the two points above, fact is that the _default_ behaviour of `to_datetime` (without passing any arguments) can do inconsistent parsing and so give unexpected results. 
Possible ways to have better default behaviour:
- Have the possibility to specify that `dateutil` should be strict about `dayfirst`. I raised an issue for that here: https://github.com/dateutil/dateutil/issues/214
- Changing the default of `infer_datetime_format` to `True` would solve it in some cases (where the first datetime has the correct format you want), but certainly not all.
- The idea of raising a warning when inconsistent parsing happened, is AFAIK not possible as pandas does not know how dateutil parsed the dates. And always warning when no format is passed or could be inferred (so in practice, when dateutil is used), is maybe to drastically, as the flexible parsing is also a feature.

### PR DESCRIPTION
**Pull request by arw2019**
- [x] closes #12585
- [x] tests added / passed
- [ ] documentation updated 
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry (pending 1.2)

This PR is an attempt to address concerns about datetime parsing. I'll update the docs if people approve this change.

#### Original problem
From #12585:
``` python
In [3]: pd.to_datetime(["31/12/2014", "10/03/2011"]) 
   ...:                                                                                                               
Out[3]: DatetimeIndex(['2014-12-31', '2011-03-10'], dtype='datetime64[ns]', freq=None)
```
The issue is that the first item is parsed as `DD\MM\YYYY` whereas for the second the format is `MM\DD\YYYY`, and there is no message to alert the user of inconsistency in the output.

The problem lies with the `dayfirst` argument that selects between `DD\MM\YYYY` and `MM\DD\YYYY`. In the parser:
https://github.com/pandas-dev/pandas/blob/04e9e0afd476b1b8bed930e47bf60ee20fa78f38/pandas/_libs/tslibs/parsing.pyx#L94-L163
we try  `DD\MM\YYYY` or `MM\DD\YYYY` first depending on `dayfirst` but if the result is invalid we try the other. 

#### Proposed change
I'd like to raise warnings whenever we parse in contradiction to the directive of `dayfirst`. The OP, where `dayfirst` defaults to `False`, now raises a Warning:
``` python
In [4]: pd.to_datetime(["31/12/2014", "10/03/2011"], dayfirst=False) 
   ...:                                                                                                               
/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 31/12/2014 DD/MM format.
  result, tz_parsed = tslib.array_to_datetime(
Out[4]: DatetimeIndex(['2014-12-31', '2011-10-03'], dtype='datetime64[ns]', freq=None)
```
A downside of this change is that sometimes a consistent output produces unnecessary warnings (due to mismatch with the default value of `dayfirst`):
``` python
In [11]: pd.to_datetime(["31/12/2014", "30/04/2011", "31/05/2016"] )                                                 
/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 31/12/2014 DD/MM format.
  result, tz_parsed = tslib.array_to_datetime(
/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 30/04/2011 DD/MM format.
  result, tz_parsed = tslib.array_to_datetime(
/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 31/05/2016 DD/MM format.
  result, tz_parsed = tslib.array_to_datetime(
Out[11]: DatetimeIndex(['2014-12-31', '2011-04-30', '2016-05-31'], dtype='datetime64[ns]', freq=None)
```
but these can be silenced with `infer_datetime_format`:
``` python
In [12]: pd.to_datetime(["31/12/2014", "30/04/2011", "31/05/2016"], infer_datetime_format=True )                      
Out[12]: DatetimeIndex(['2014-12-31', '2011-04-30', '2016-05-31'], dtype='datetime64[ns]', freq=None)
```
For invalid input (if it cannot be parsed according to a single format) we will *always* raise a warning, even with `infer_datetime_format=True`:
``` python
In [13]: pd.to_datetime(["31/12/2014", "03/31/2011"], infer_datetime_format=True)                                     
/workspaces/pandas-arw2019/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing 31/12/2014 DD/MM format.
  result, tz_parsed = tslib.array_to_datetime(
Out[13]: DatetimeIndex(['2014-12-31', '2011-03-31'], dtype='datetime64[ns]', freq=None)
```

#### Remaining issues
Personally I can see a case for raising an error with 
``` python
In [13]: pd.to_datetime(["31/12/2014", "03/31/2011"], infer_datetime_format=True)                                     
```
since there's no valid way to process that. I also think that 
``` python
In [11]: pd.to_datetime(["31/12/2014", "30/04/2011", "31/05/2016"])                                                 
```
shouldn't be raising warnings, but I feel much less strongly about that. That said, changing this behaviour will require more heavy-handed alterations to the codebase (and maybe performance implications - not sure).

I think that the warnings I added here will allow users to figure out the origin of these problems when they turn up and that should do away with most of the headaches.

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
Thanks, I think the warning approach is reasonable.

Might be preferable to the user if they just get 1 warning along the lines of "Parsed {date} as DD/MM/YYY and {other date} as MM/DD/YYY. Provide `format` or specify infer_datetime_format=True for consistent parsing"

**Comment by arw2019** [comment]
> Might be preferable to the user if they just get 1 warning along the lines of "Parsed as DD/MM/YYY and as MM/DD/YYY. Provide `format` or specify infer_datetime_format=True for consistent parsing"

Sounds good. I'll keep working on this

**Comment by simonjayhawkins** [comment]
@arw2019 doc build failing

```
>>>-------------------------------------------------------------------------
Warning in /home/runner/work/pandas/pandas/doc/source/user_guide/timeseries.rst at block ending on line 222
Specify :okwarning: as an option in the ipython:: block to suppress this message
----------------------------------------------------------------------------
/home/runner/work/pandas/pandas/pandas/core/arrays/datetimes.py:2044: UserWarning: Parsing '01-14-2012' in MM/DD/YYYY format.
  result, tz_parsed = tslib.array_to_datetime(
<<<-------------------------------------------------------------------------
```

**Comment by simonjayhawkins** [comment]
@arw2019 are you still working on this?

**Comment by arw2019** [comment]
@simonjayhawkins yes, will push what I have shortly. Sorry about keeping this idle

**Comment by arw2019** [comment]
Closing this for now. I'll circle back when I'm ready for review.

**Pull request closed without merging**
