### PR TITLE
DEPR: enforce deprecation of old set_axis signature

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jreback** [comment]
lgtm ping on green.

**Comment by jbrockmendel** [comment]
We're running out of things to remove in #6581!  One thing there that could use a look from someone more experienced than me is the how/fill_method/resample one (now top of this list).  My last attempt to enforce it didn't go well.

**Comment by jreback** [comment]
> We're running out of things to remove in #6581! One thing there that could use a look from someone more experienced than me is the how/fill_method/resample one (now top of this list). My last attempt to enforce it didn't go well.

lol, yeah I added that too.

did you have a branch for this?

**Comment by jbrockmendel** [comment]
> did you have a branch for this?

not one that i pushed, will have to see if i still have it locally

**Comment by jbrockmendel** [comment]
de facto green.  im going to try to see if the same codecs.open thing can fix the CI failure were seeing here

**Comment by jbrockmendel** [comment]
booyah! tentatively figured out why we're leaking files that is failing the py36 build occasionally

**Comment by jreback** [comment]
thanks

**Pull request merged**
