### PR TITLE
BUG: categorical unpickle to use _coerce_indexer_dtype

### PR DESCRIPTION
**Pull request by sinhrks**
- [x] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry

follow up for #13080 to use `_coerce_indexer_dtype`.

### CODE REVIEW

**Comment by jreback** [comment]
this *should* show up in tests I think for an older pickle (I don't recall when we started coercing the codes), but not really a big deal.

**Comment by jreback** [comment]
can you add a test, or do we have coverage?

**Comment by sinhrks** [comment]
No, added some pickles to test it.

**Comment by jreback** [comment]
thanks!

**Pull request closed without merging**
