### PR TITLE
future annotations

### LINKED ISSUE #40533: Use from __future__ import annotations (almost?) everywhere?
This means we can address

> type hints are executed at module import time, which is not computationally free.

(from https://www.python.org/dev/peps/pep-0563/), as well as use the more modern syntax of Python

----

This is easy to automate, just checking there's no downsides to putting this everywhere. Should any files (probably `__init__.py`, any others?) be excluded? cc @simonjayhawkins

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [x] closes #40533 
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

### CODE REVIEW

**Comment by jreback** [comment]
sure, can you merge master once more and ping on green (of course in draft status)

**Comment by jreback** [comment]
thanks @MarcoGorelli

**Comment by rs2** [comment]
@jreback @MarcoGorelli `from __future__ import annotations` is a Python 3.7+ feature*. Can I please check whether `pandas` no longer supports Python 3.6 and earlier versions of Python?

<sup>* See here: https://docs.python.org/3/whatsnew/3.7.html#pep-563-postponed-evaluation-of-annotations</sup>

**Comment by MarcoGorelli** [comment]
@rs2 that's right, Python3.6 is no longer supported

**Pull request merged**
