### PR TITLE
Create ABCDateOffset

### PR DESCRIPTION
**Pull request by jbrockmendel**
`DateOffset` is one of a small number of commonly-used classes for which no `ABCFoo` class exists.  Putting this in place is cheap and gives us an option to use it down the road.

Replaced `isinstance(x, DateOffset)` with `isinstance(x, ABCDateOffset)` in a few places where doing so lets us avoid run-time imports.  Other than that this holds off on actually _using_ `ABCDateOffset`, as the `ABCFoo` isinstance checks do appear to be appreciably slower than the non-ABC versions.

 - [ ] closes #xxxx
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

### CODE REVIEW

**Comment by gfyoung** [comment]
@jbrockmendel : Good start here.  Needs a `whatsnew` + some testing (we have tests for checking the `ABC*`)

**Comment by jreback** [comment]
> Good start here. Needs a whatsnew + some testing (we have tests for checking the ABC*)

only the tests for the ABC are necessary. this is purely internal and doesn't require a whatsnew.

there *might* be a couple of places that you can use this in cython as well (in the .pyx).

**Review by jreback — CHANGES_REQUESTED** [review]
needs tests as indicated

**Comment by jbrockmendel** [comment]
Just pushed a commit with added tests.

> there might be a couple of places that you can use this in cython as well (in the .pyx).

Looks like it gets checked in period.pyx.  `_libs.period` already imports `tseries.frequencies` (which imports `tseries.offsets`), so replacing `DateOffset` with `ABCDateOffset` there wouldn't simplify the import structure.  That said, the downside is minimal if someone has a strong preference.

Related: for kicks I tried implementing `ABCDateOffset` in cython and found it made a non-trivial (relative) difference.  Instead of `isinstance(item, ABCDateOffset)` taking 2x as long as `isinstance(item, DateOffset)`, its closer to 1.1x.

**Comment by jreback** [comment]
this looks fine. needs a rebase.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks!

**Pull request merged**
