### PR TITLE
REF: share .astype code for astype_nansafe + TDA.astype

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This changes TDI.astype and TDA.astype in the cast with no-NAs to return float64 instead of int64, matching Series behavior.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Is this "pandas convention" documented anywhere?

**Comment by jbrockmendel** [comment]
> Is this "pandas convention" documented anywhere?

Not that I'm aware of.  I'm not a fan of this behavior, looking forward to making it unnecessary when we support non-nano td64

**Comment by jreback** [comment]
thanks @jbrockmendel yep nice refactor here.

**Comment by jorisvandenbossche** [comment]
>  I'm not a fan of this behavior, looking forward to making it unnecessary when we support non-nano td64

We already might want to start deprecating this in advance.

**Pull request merged**
