### PR TITLE
API: Allow groupby's by to take column and index names [WIP]

### LINKED ISSUE #5677: ENH/API: clarify groupby by to handle columns/index names
Referenced briefly in the OP at #3275

``` python
In [11]: idx = pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('a', 3), ('b', 1), ('b', 2), ('b', 3)])

In [12]: idx.names = ['outer', 'inner']

In [13]: df = pd.DataFrame({"A": np.arange(6), 'B': ['one', 'one', 'two', 'two', 'one', 'one']}, index=idx)
```

So the idea is to be able to call

``` python
df.groupby('B', level='inner')
```

instead of

``` python
In [15]: df.reset_index().groupby(['B', 'inner']).mean()
Out[15]: 
             A
B   inner     
one 1      0.0
    2      2.5
    3      5.0
two 1      3.0
    3      2.0

[5 rows x 1 columns]
```

Currently this raises `TypeError: 'numpy.ndarray' object is not callable`.  Mostly just syntactic sugar, but I've been having to do a lot of this lately and all the `reset_index`es are getting annoying. Thoughts?

### PR DESCRIPTION
**Pull request by TomAugspurger**
closes https://github.com/pydata/pandas/issues/5677

As a reminder, with a  data frame like:

``` python
from itertools import cycle, islice 

np.random.seed(0)
df = pd.DataFrame(np.random.randn(20, 2))
df.columns = ["foo","bar"]
df['g0'] = list(islice(cycle('ab'), 20))
df['g1'] = ['a'] * 10 + ['b'] * 10
df['g2'] = ['c'] * 5 + ['d'] * 5 + ['c'] * 5 + ['d'] * 5

df = df.set_index(['g1', 'g2'])
```

Before if you wanted to groupby a a column and index level, you'd have to

``` python
g = df.reset_index().groupby(['g0', 'g1'])
```

Now you can just do `df.groupby(['g0', 'g1'])`. In ambiguous cases where a there's a key in `by` that's in both the index names and columns we warn and proceed with grouping by the columns (I haven't tested this part yet).

### CODE REVIEW

**Comment by jreback** [comment]
@TomAugspurger what's the status of this?

**Comment by jreback** [comment]
@TomAugspurger what's the status of this?

**Comment by jreback** [comment]
closing pls reopen if/when updated

**Comment by jmmease** [comment]
@TomAugspurger I'm interesting in working on #5677 and will likely use this PR as a starting point.  Tom, if you have time could you elaborate on your comment from May 5, 2014 where you mention that this current implementation violates a property of `.transform`?

**Comment by TomAugspurger** [comment]
@jmmease not 100% sure what I meant by that last comment. If I had to guess, it's that something like


```python
df = DataFrame([[1, 2, 'x', 'a', 'a'],
                [2, 3, 'x', 'a', 'b'],
                [3, 4, 'x', 'b', 'a'],
                [4, 5, 'y', 'b', 'b']],
               columns=['c1', 'c2', 'g1', 'i1', 'i2'])
df = df.set_index(['i1', 'i2'])
```

I don't know what the expected index of this operation would be


```python
df.groupby(['i1', 'g1']).transform('max')
```

Typically the output of `transform` retains the index, so it should have the same index has the input `df`. But in my implementation I was calling `.reset_index()`, so the output had a `range(n)` index.

**Pull request closed without merging**
