### PR TITLE
(WIP) TYP: add some obvious -> None to pandas/core

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

via https://github.com/MarcoGorelli/add-obvious-return-none - adding `-> None` where possible so at least those functions will be type-checked

there's gonna be a tonne of CI failures so opening as draft for now

### CODE REVIEW

**Comment by twoertwein** [comment]
> via https://github.com/MarcoGorelli/add-obvious-return-none - adding `-> None` where possible so at least those functions will be type-checked

Does this also add `None` to `__init__`? Just surprised that no `__init__` had missing return annotations :)

Not sure whether it is worth the effort: you could extend your hook to also check pyi files: they have obviously no implementation but at least `__init__`'s that have no return annotation should probably return `None`.

If you want to cover non-obvious `None`s, you could use pyright: it infers missing return types.

**Comment by MarcoGorelli** [comment]
Closing for now, this'd need some other adjustments first

**Comment by twoertwein** [comment]
> Closing for now, this'd need some other adjustments first

Would be great to have it to close #46337

**Comment by MarcoGorelli** [comment]
Thanks - I hope to be able to address it soonish

**Comment by twoertwein** [comment]
Might be great to set up https://github.com/JelleZijlstra/autotyping (I failed to get it running locally)

**Pull request closed without merging**
