### PR TITLE
DOC: Add .map to ExtensionArray reference

### PR DESCRIPTION
**Pull request by topper-123**

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @topper-123

**Comment by rhshadrach** [comment]
On the docs build here, I'm seeing 

> /home/runner/work/pandas/pandas/doc/source/reference/api/pandas.api.extensions.ExtensionArray.map.rst: WARNING: document isn't included in any toctree

I _think_ this might be causing the docs build to "fail".

**Comment by mroeschke** [comment]
Oops yeah jumped the gun on the merge. Will revert for now.

**Comment by rhshadrach** [comment]
@datapythonista - in this case the docs are still built successfully but I _think_ we can't use `/preview` because the step is skipped. Is that right? I wonder if there is an easy way still be able to view the docs if something is built (but not a big issue either way).

**Comment by datapythonista** [comment]
> @datapythonista - in this case the docs are still built successfully but I _think_ we can't use `/preview` because the step is skipped. Is that right? I wonder if there is an easy way still be able to view the docs if something is built (but not a big issue either way).

@rhshadrach we consider warnings as errors in the docs, for me the current behavior seems fine, even if I agree that the docs exist and we could preview them. The main problem I see is that it probably makes the CI quite complex to move forward with the publishing when the docs step is red. But I'm open to the change if things don't become too complicated.

**Pull request merged**
