### PR TITLE
Remove pd_array from tests

### PR DESCRIPTION
**Pull request by olgarithms**
- [x] closes https://github.com/MarcoGorelli/pyladies-sprint-March-2021/issues/7
- [x] tests passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Thanks @olgarithms looks good

I forgot to mention this when I wrote the issue, but now we can make the relevant CI check stricter. Could you please also:
- in `pandas/tests/frame/test_constructors.py`, change `test_constructor_stdlib_array` test so it has `from array import stdlib_array` instead of `import array` (and then use `stdlib_array` instead of `array.array` in that little test)
- in `scripts/check_for_inconsistent_pandas_namespace.py`, line 32, remove `array`
- run `pre-commit run inconsistent-namespace-usage --all-files` and check it passes

Then this should be good to go :+1:

cc @jorisvandenbossche @jbrockmendel as you'd both commented on `pd_array` usage (in #40150 it seemed there was agreement on using `pd_array` internally in `core`, and the public API `pd.array` in tests)

**Comment by olgarithms** [comment]
Thanks for looking @MarcoGorelli !

As for the changes, I understand the one for the pre-commit, but can you explain what `stdlib_array` is and where it is supposed to live? I do not see where it is defined.

When I do the change as you mention, I get this error:
`ImportError: cannot import name 'stdlib_array' from 'array'`

**Comment by MarcoGorelli** [comment]
Hey @olgarithms - sorry, I mistyped, I mean to write `from array import array as stdlib_array` (`array` is a standard library module)

**Comment by MarcoGorelli** [comment]
Thanks @olgarithms

**Pull request merged**
