### PR TITLE
Replace _has_complex_internals #29227

### LINKED ISSUE #29227: Replace _has_complex_internals with isinstance(..., ABCMultiIndex)
I've stumbled across this code a few times in groupby and it took me a while to grasp. I'm pretty sure this always evaluates to False, unless we are dealing with a MultiIndex.

For code clarity, I think it would be better if we just did an isinstance check as I don't think the intent of `_has_complex_internals` is very clear

### PR DESCRIPTION
**Pull request by Aivengoe**
closes #29227

Hi, it my first issues within hacktoberfest. 
I replaced _has_complex_internals with isinstance/
Is it possible to import ABCMultiIndex?

### CODE REVIEW

**Comment by jbrockmendel** [comment]
You're going to need to run `isort -rc pandas` to fix the linting errors.  In the reduction.pyx we don't allow imports from `core`, so the check will need to be something like `index.nlevels > 1`

**Comment by jreback** [comment]
also pls merge master, we just update the codebase with another small usage of  this (which needs to be changed)

**Comment by jbrockmendel** [comment]
pushed rebased and isort fixup

**Comment by jreback** [comment]
@jbrockmendel this needed or did you already remove?

**Comment by jbrockmendel** [comment]
still needed

**Comment by jreback** [comment]
ok @Aivengoe can you merge master. 

@jbrockmendel feel free to push here if its faster

**Comment by jreback** [comment]
thanks @Aivengoe and @jbrockmendel

**Pull request merged**
