### PR TITLE
Backport PR #55619 on branch 2.1.x (BUG: Groupby not keeping string dtype for empty objects)

### PR DESCRIPTION
**Pull request by lithomas1**
* BUG: Groupby not keeping string dtype for empty objects

* Fix

Backports PR #55619

### CODE REVIEW

**Comment by lithomas1** [comment]
Ack, looks like there's a segmentation fault here.

see https://github.com/pandas-dev/pandas/actions/runs/6654698565/job/18083267496?pr=55705#step:9:467.

@phofl I'm gonna bump this off the milestone then.

**Comment by phofl** [comment]
Yeah no worries

**Comment by lithomas1** [comment]
Nevermind about the segfault, it seems to be unrelated to this PR (I saw it happen on the 2.1.x branch too, and I made a comment about it on the release issue).
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=812339&view=logs&j=385a3385-ae8b-54d1-9abe-3c614f74cb73&t=d0913101-e169-5874-b37d-533167693e73&l=1989.

I'll send a PR to move the release note.

**Comment by lithomas1** [comment]
Oops, looks like I accidentally hit close on this for some reason.

(I think I meant to hit merge).

**Comment by lithomas1** [comment]
Merging, 

I need to move the release note now.

**Pull request merged**
