### PR TITLE
REF: remove group_selection_context

### PR DESCRIPTION
**Pull request by jbrockmendel**
cc @rhshadrach

### CODE REVIEW

**Review by rhshadrach — COMMENTED** [review]
Wow - I didn't think this would be possible without some refactoring. This is approaching bikeshedding, but with `obj = self._obj_with_exclusions` it's tempting to see `obj` and think this would be `self.obj`. Any opposition to doing `obj_with_exclusions = self._obj_with_exclusions`?

**Comment by jbrockmendel** [comment]
We already have `obj = self._obj_with_exclusions` in a few places.  Can we do a one-and-for-all bikeshed on this topic separately?

**Review by rhshadrach — APPROVED** [review]
lgtm

**Comment by rhshadrach** [comment]
Thanks @jbrockmendel

**Pull request merged**
