### PR TITLE
Backport PR #44315 on branch 1.3.x (Pin aiobotocore to lower than 2.0 )

### PR DESCRIPTION
**Pull request by phofl**
(cherry picked from commit 28c7f7628dd6b862e1eed29ff71e2e8363ca1eee)

- [x] xref #44315

### CODE REVIEW

**Comment by phofl** [comment]
@simonjayhawkins Failing pipelines are related. Looks like our env files changed on master. Should we adress this here?

**Comment by simonjayhawkins** [comment]
The failing envs are picking up aiobotocore-2.0.0, so we can just pin those envs too?

**Comment by simonjayhawkins** [comment]
> Looks like our env files changed on master

python 3.7 is dropped on master so there has been many changes on master compared to 1.3.x

**Comment by phofl** [comment]
Pinned the other two envs

**Review by lithomas1 — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
Thanks @phofl

**Pull request merged**
