### PR TITLE
BUG: Period.now not taking kwargs

### LINKED ISSUE #53369: BUG: Period.now() does not accept kwarg "freq" but doc and typing say otherwise
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
p = pd.Period.now(freq='D')

# Gives: "TypeError: Period.now() takes no keyword arguments"

p = pd.Period.now('D')  
# Gives: Period('2023-05-24', 'D')
# BTW, here the type checker complains about wrong type, expects 'BaseOffset' not 'str'
```

### Issue Description

The method call `Period.now(freq="D")` raises a "TypeError: Period.now() takes no keyword arguments" but this behavior deviates from Pandas 1.5.X and is in contradiction to type annotations and not documented.

### Expected Behavior

The kwarg "freq" should work or it should be documented accordingly in type annotations and as breaking change.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.11.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.14393
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 0, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.8.0
pip              : 23.1.2
Cython           : None
pytest           : 7.3.1
hypothesis       : 6.75.3
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.6
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #53369  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Confirmed working with both setuptools/meson.

### CODE REVIEW

**Comment by mroeschke** [comment]
Not sure if this build related error is due to this PR

```
   /home/runner/micromamba/envs/test/lib/python3.10/site-packages/Cython/Compiler/Main.py:370: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/runner/work/pandas/pandas/pandas/_libs/tslibs/offsets.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)

  Error compiling Cython file:
  ------------------------------------------------------------
  ...

      def get_rule_code_suffix(self) -> str:
          prefix = self._get_suffix_prefix()
          month = MONTH_ALIASES[self.startingMonth]
          weekday = int_to_weekday[self.weekday]
          return f"{prefix}-{month}-{weekday}"
                 ^
  ------------------------------------------------------------

  /home/runner/work/pandas/pandas/pandas/_libs/tslibs/offsets.pyx:3324:15: Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.
  [35/164] Compiling C object pandas/_libs/tslibs/offsets.cpython-310-x86_64-linux-gnu.so.p/src_datetime_np_datetime.c.o
  [36/164] Compiling C object pandas/_libs/tslibs/np_datetime.cpython-310-x86_64-linux-gnu.so.p/meson-generated_pandas__libs_tslibs_np_datetime.pyx.c.o
```

**Comment by lithomas1** [comment]
Marking as draft pending resolution of a Cython bug I think.
https://github.com/cython/cython/issues/5484

**Comment by WillAyd** [comment]
Does this change impact all of the Cython functions? From the docs makes it seems like it could be a performance hit for cdef functions we call in tight loops

**Comment by lithomas1** [comment]
Only affects single-arg functions.
(see https://github.com/cython/cython/issues/3090).

The affected functions are ``def`` functions I think as well. I don't think we really do any loops in Python so perf impact shouldn't be too horrible (the Cython functions should use the cdef variants).

**Comment by lithomas1** [comment]
Cython cut 3.0rc1 a little while ago, so this should be ready in a couple of days once the Github cache catches up.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @lithomas1

**Pull request merged**
