### PR TITLE
DOC/BUG: Enforce that freq is required in Period.now

### PR DESCRIPTION
**Pull request by bashtage**
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.

### CODE REVIEW

**Comment by bashtage** [comment]
xref pandas-dev/pandas-stubs#383

**Review by phofl — COMMENTED** [review]
This changes the API?

**Comment by bashtage** [comment]
No. It looks optional but if not provided it raises.  This just makes it crystal clear that it is required.

**Comment by bashtage** [comment]
@phofl Code check is fixed.

**Comment by phofl** [comment]
thx @bashtage

**Pull request merged**
