### PR TITLE
DOC: pin gitdb2

### PR DESCRIPTION
**Pull request by TomAugspurger**
ref #32060

### CODE REVIEW

**Comment by jbrockmendel** [comment]
looks like 3.0.1 and 3.0.2 are on pip, are they not yet on conda?

**Comment by simonjayhawkins** [comment]
won't this fail without running scripts\generate_pip_deps_from_conda.py?

**Comment by jreback** [comment]
needs backport?

**Comment by jorisvandenbossche** [comment]
> needs backport?

Yes

**Pull request merged**
