### PR TITLE
STYLE: fix PDF026 issues

### LINKED ISSUE #42359: STYLE disallow Series | AnyArrayLike
PR should be made to https://github.com/pandas-dev/pandas-dev-flaker

idea is to disallow `foo: Series | AnyArrayLike`, as `Series` is array-like already

This came out of this review: https://github.com/pandas-dev/pandas/pull/41955#discussion_r663390463

### LINKED ISSUE #46528: STYLE fix PDF026 issues from pandas-dev-flaker
task is:

1. bump version of pandas-dev-flaker in https://github.com/pandas-dev/pandas/blob/c3ab0c99264be1c7907525ea4846f3f024057a28/.pre-commit-config.yaml#L53 to 0.5.0
2. update `pandas-dev-flaker`: `pip install -U pandas-dev-flaker`
3. run `flake8 pandas --select PDF026`
4. fix any issues that are highlighted by `flake8`
5. run `flake8 pandas` and add any new codes to https://github.com/pandas-dev/pandas/blob/c3ab0c99264be1c7907525ea4846f3f024057a28/setup.cfg#L76

### PR DESCRIPTION
**Pull request by Moisan**
- [x] closes #46528
- [x] closes #42359
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
A few checks a failing, you probably need to add the other new error codes to setup.cfg, and they can gradually be removed

**Review by MarcoGorelli — APPROVED** [review]
Nice, well done - the CI failures look unrelated

**Comment by jreback** [comment]
> /home/runner/work/pandas/pandas/doc/source/whatsnew/v0.13.1.rst:33: WARNING: undefined label: tutorials

**Comment by MarcoGorelli** [comment]
> > /home/runner/work/pandas/pandas/doc/source/whatsnew/v0.13.1.rst:33: WARNING: undefined label: tutorials

looks like this was unrelated - merging then, thanks @Moisan

**Pull request merged**
