### PR TITLE
REF: remove JoinUnit.shape

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Can you please wait with further PRs to JoinUnit until the discussion in https://github.com/pandas-dev/pandas/pull/43507 is resolved? (since those might make it harder to revert the change)

**Comment by jreback** [comment]
> Can you please wait with further PRs to JoinUnit until the discussion in #43507 is resolved? (since those might make it harder to revert the change)

@jorisvandenbossche if you don't like the new behavior then pls open an issue

**Comment by simonjayhawkins** [comment]
moving off 1.5

**Comment by jreback** [comment]
@jbrockmendel pls rebase, let's just do this

**Pull request merged**
