### PR TITLE
DOC: Clean up redirects & dead links

### PR DESCRIPTION
**Pull request by mroeschke**
Ran `sphinx-build -b linkcheck` and fixed some redirects and dead links

### CODE REVIEW

**Comment by jreback** [comment]
> 

we could add a check for this (after everything is fixed)

**Comment by mroeschke** [comment]
> > 
> 
> we could add a check for this (after everything is fixed)

Yup xref https://github.com/pandas-dev/pandas/issues/45409

**Comment by jreback** [comment]
oh sure any of the doc ones are fine

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.4.x

**Comment by simonjayhawkins** [comment]
conflict was with #45456 which was already backported.

**Pull request merged**
