### PR TITLE
BLD: remove MSVC workaround

### LINKED ISSUE #23209: PERF: replace use of `isnan` once MSVC bug is fixed
ref #23182, #21813

MSVC bug tracker  - https://developercommunity.visualstudio.com/content/problem/294290/incorrect-codegen-for-double-equality.html

Once that bug is fixed in a widely available MSVC for python 3 builds we should redefine `isnan` / `notnan` to be based on an equality check here.
https://github.com/pandas-dev/pandas/pull/23182/files#diff-467e9a847ab859a085518bc17711fe57R20

Current code works around that MSVC bug by using the libc, `isnan`, which works, but can't be inlined, so likely has a little perf cost
https://godbolt.org/z/y550lB

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #23209
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Shot in the dark to see if the upstream problem behind #23209 is resolved.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
does this bump up min versions of any windows things?

**Comment by jbrockmendel** [comment]
> does this bump up min versions of any windows things?

im not aware of anywhere that we specify those

**Comment by lithomas1** [comment]
We're still on VS 2017 on the wheel repo. This needs to wait for MacPython/pandas-wheels#160.

**Comment by jbrockmendel** [comment]
Thanks @lithomas1.  Is there an ETA on that?  i.e. should this be closed or just given the "Blocked" label?

**Comment by lithomas1** [comment]
That patch is scheduled to land for the 1.4rc, but this'll probably have to land in 2.0 because we'll have to wait until after 1.4.0 is released to make sure that no issues are reported that will cause it to be rolled back(last time we upgraded to Visual Studio 2019, we had missing DLL issues).

**Comment by simonjayhawkins** [comment]
> That patch is scheduled to land for the 1.4rc, but this'll probably have to land in 2.0 because we'll have to wait until after 1.4.0 is released to make sure that no issues are reported that will cause it to be rolled back(last time we upgraded to Visual Studio 2019, we had missing DLL issues).

changing milestone to 1.5

**Comment by jbrockmendel** [comment]
@lithomas1 looks like MacPython/pandas-wheels#160 has been merged, does that mean we're good to go here?

**Comment by lithomas1** [comment]
I think so.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
ok let's give this a go, thanks @lithomas1 

might be worth updating install.rst with the min required MSVC version?

**Pull request merged**
