### PR TITLE
lint import order

### PR DESCRIPTION
**Pull request by jbrockmendel**
Expecting lots and lots of flake8 complaints...

### CODE REVIEW

**Comment by TomAugspurger** [comment]
FYI: http://isort.readthedocs.io/en/latest/ will rewrite the imports automatically.

**Comment by jbrockmendel** [comment]
flake8+multiprocessing is throwing an error here.  Unfortunately it gives a line number but not a filename.

```
Linting  *.py
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/pandas/bin/flake8", line 11, in <module>
    load_entry_point('flake8==3.4.1', 'console_scripts', 'flake8')()
  File "/home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages/flake8/main/application.py", line 348, in run
    self._run(argv)
  File "/home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages/flake8/main/application.py", line 336, in _run
    self.run_checks()
  File "/home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages/flake8/main/application.py", line 266, in run_checks
    self.file_checker_manager.run()
  File "/home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages/flake8/checker.py", line 317, in run
    self.run_parallel()
  File "/home/travis/miniconda3/envs/pandas/lib/python2.7/site-packages/flake8/checker.py", line 286, in run_parallel
    for ret in pool_map:
  File "/home/travis/miniconda3/envs/pandas/lib/python2.7/multiprocessing/pool.py", line 289, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/travis/miniconda3/envs/pandas/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
ValueError: Expected token OP:'[', got OP:'(' on line 477 col 33
```

**Comment by jbrockmendel** [comment]
@TomAugspurger +1.  Doing this manually would be a PITA.

**Comment by jreback** [comment]
don’t use multiprocessing

**Comment by jbrockmendel** [comment]
> don’t use multiprocessing

Well, yah.  It's apparently being called under the hood by flake8.  I'll get around to looking at it eventually, someone else is welcome to beat me to it.

**Pull request closed without merging**
