### PR TITLE
Updated PeriodIndex docstrings #10094

### LINKED ISSUE #10094: DOC: update docstrings with new Index repr
After #9901 has been merged, we should go through the docstrings and update where there are examples with Index reprs.

The ones that changed the most are the datetime-like. A search for `<class 'pandas.tseries.period.PeriodIndex'>` and alike can help there.

### PR DESCRIPTION
**Pull request by ExSidius**
- [x] closes #10094
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by ExSidius** [comment]
I wasn't sure what to add in the whatsnew entry. Some guidance would be appreciated.

**Comment by ExSidius** [comment]
Also unsure as to why code coverage issues are so significant.

**Comment by WillAyd** [comment]
These updates look good. No whatsnew is required for docstring updates.

Does this fully close the issue referenced? @jorisvandenbossche

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @ExSidius

**Comment by ExSidius** [comment]
No problem.

**Comment by jorisvandenbossche** [comment]
> Does this fully close the issue referenced? @jorisvandenbossche

From a quick search it seems it does. Thanks @ExSidius

**Comment by ExSidius** [comment]
Cheers. Happy to help.

**Pull request merged**
