### PR TITLE
Surface NumPy FutureWarning about comparisons

### LINKED ISSUE #22698: Handle FutureWarning from NumPy in Series Construction
This is with NumPy dev.

```python
In [2]: pd.Series(['0', '1'], dtype=float)
/Users/taugspurger/sandbox/numpy/numpy/core/numeric.py:2468: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return bool(asarray(a1 == a2).all())
Out[2]:
0    0.0
1    1.0
dtype: float64

```

https://travis-ci.org/pandas-dev/pandas/jobs/427640030#L5344

this goes from `core.series._sanitize_array` -> `_try_cast` -> `maybe_cast_to_integer_array`.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/22698

Specifically, see
https://github.com/pandas-dev/pandas/issues/22698#issuecomment-458968300.

I don't think we need to worry about the others in https://github.com/pandas-dev/pandas/issues/22698#issuecomment-422446071 datetimearray and integer array. I couldn't reproduce the returning a scalar behavior with those.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Oh, I was a bit confused... This happens with IntegerArray

```python
In [7]: a = pd.array([1, None], dtype='Int64')

In [8]: a == 'a'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-3812dba97b6d> in <module>
----> 1 a == 'a'

~/sandbox/pandas/pandas/core/arrays/integer.py in cmp_method(self, other)
    561                 mask = self._mask | mask
    562
--> 563             result[mask] = op_name == 'ne'
    564             return result
    565

TypeError: 'bool' object does not support item assignment
```

So right now `IntegerArray.__eq__(other)` is broken when the op is using the deprecated behavior.

I don't think showing a warning here is useful. We could work around it I suppose?

**Comment by jreback** [comment]
looks fine. do we need to catch / suppress this in *any* of our tests?

**Comment by TomAugspurger** [comment]
I don’t think we hit this anywhere else. If we did the NumPy dev build would be failing.

**Comment by jreback** [comment]
k thanks @TomAugspurger

**Pull request merged**
