### PR TITLE
Pin aiobotocore to lower than 2.0

### PR DESCRIPTION
**Pull request by phofl**
- [x] xref #44311

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM pending green

do we need a comment about conditions under which the pin can be reverted?

**Comment by phofl** [comment]
Would have tracked this through the issue, but could add a comment to

**Comment by jreback** [comment]
nice merge on green

**Comment by lithomas1** [comment]
thanks @phofl

**Comment by lithomas1** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
