### PR TITLE
tostring->tobytes

### LINKED ISSUE #33238: CI/COMPAT: Linux py37_np_dev pipeline timeouts
#### Problem description

Linux py37_np_dev pipeline appears to timeout for everyone after 60 minutes.
There are a couple hundred thousand errors like this:
```
Exception ignored in: 'pandas.io.sas._sas.Parser.process_byte_array_with_data'
DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
```
Here is a [link](https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=32212&view=logs&j=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&t=4d05ed0e-1ed3-5bff-dd63-1e957f2766a9&l=792078) to it failing for me.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #33238
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks, maybe a few others

```
pandas/core/computation/pytables.py
176:        val = v.tostring(self.encoding)
606:    def tostring(self, encoding) -> str:

pandas/io/sas/sas.pyx
434:                    start + lngt)]).tostring().rstrip(b"\x00 ")

pandas/_libs/writers.pyx
115:    return narr.tostring().decode('utf-8')
```

**Comment by jbrockmendel** [comment]
updated+green

**Comment by TomAugspurger** [comment]
Thanks!

**Comment by simonjayhawkins** [comment]
@Meeseeksdev backport to 1.0.x

**Pull request merged**
