### PR TITLE
Doc: Example of merging Dataframe and Series

### LINKED ISSUE #12550: Equivalent of Series.map for DataFrame
I think there should be a way to take a DataFrame and use the values in its columns as indices into a MultiIndexed Series.  Here is an example:

```
>>> d = pandas.DataFrame({"Let": ["A", "B", "C"], "Num": [1, 2, 3]})
>>> d
  Let  Num
0   A    1
1   B    2
2   C    3
>>> ser = pandas.Series(
...     ['a', 'b', 'c', 'd', 'e', 'f'],
...     index=pandas.MultiIndex.from_arrays([["A", "B", "C"]*2, [1, 2, 3, 4, 5, 6]])
... )
>>> ser
A  1    a
B  2    b
C  3    c
A  4    d
B  5    e
C  6    f
dtype: object
```

With this data, you should be able to do `d.map(ser)` (or whatever method name instead of `map`) and get the same result as this:

```
>>> ser.ix[d.apply(tuple, axis=1)]
A  1    a
B  2    b
C  3    c
dtype: object
```

You currently cannot do this without converting the rows to tuples (`ser[d]` gives `ValueError: Cannot index with multidimensional key`).  Converting to tuple is an awkward way to do a very natural task, which is using a tabular array of data to look up values in a tabular index (i.e., a MultiIndex).

I'm creating an issue to resurrect this request from much earlier discussion [here](https://groups.google.com/forum/#!searchin/pydata/dataframe$20map/pydata/sibkQ5Ea-Hc/RKMwiNsH7TMJ) and [here](http://stackoverflow.com/questions/22293683/equivalent-of-series-map-for-dataframe).

### PR DESCRIPTION
**Pull request by pdpark**
- [ ] closes #12550

### CODE REVIEW

**Comment by jreback** [comment]
@pdpark you seem to picking up *other* PR's commits. start with a fresh master and checkout a branch from that with your changes.

**Comment by pdpark** [comment]
@jreback, sorry, still learning the process. So I make a branch for a change, commit my changes on my fork and submit a PR. How do I get a fresh master on my fork at that point? Thanks.

**Comment by pdpark** [comment]
Looking at the How to Contribute document, it looks like I need to execute these git commands:

git remote add upstream <link to parent repo>
git fetch upstream
git rebase upstream/master

**Comment by pdpark** [comment]
Submitted a new pull request. Let me know if it looks okay this time.

**Comment by pdpark** [comment]
This PR can be closed. I am resubmitting these changes as separate PRs.

**Pull request closed without merging**
