### PR TITLE
CI: latest ipython version for doc build

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/pydata/pandas/pull/12002#issuecomment-174550631

Doc builds are failing, testing if using the latest `ipython` version solves it.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. The build *looked* like it succeded.

**Comment by jreback** [comment]
@jorisvandenbossche shall we merge this?

**Comment by jorisvandenbossche** [comment]
yes!

**Comment by jorisvandenbossche** [comment]
yes!

**Comment by jreback** [comment]
ok, merging now

**Comment by jreback** [comment]
dev docs built! looks good.

lots of warnings in the build of course....

and did API reference! awesome!

**Comment by jorisvandenbossche** [comment]
> lots of warnings in the build of course....

Yes, there is an issue with our custom accessor documenters that are not working anymore with the latest sphinx (that I needed for getting this run on travis). So need to investigate that ..

Apart from that, we normally don't have that many warnings! :-)

**Pull request closed without merging**
