### PR TITLE
REF: put DatetimeBlock adjacent to DatetimeLikeBlockMixin

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
just a straight move?

**Comment by jbrockmendel** [comment]
yep

**Comment by jreback** [comment]
k ping on green

**Comment by jbrockmendel** [comment]
ping

**Pull request merged**
