### PR TITLE
CI: xfail on numpy 1.18

### PR DESCRIPTION
**Pull request by jbrockmendel**
xref #29053 

i think this addresses the failing azure builds, not sure about Travis.

Will open an issue for a longer-term fix.

### CODE REVIEW

**Review by TomAugspurger — APPROVED** [review]

**Comment by jreback** [comment]
cool, merge on green.

do you need to port this to 0.25.2 as well?

**Comment by TomAugspurger** [comment]
Probably need to backport.

**Comment by TomAugspurger** [comment]
Restarted the stalled 3.8 build.

**Comment by jbrockmendel** [comment]
updated the 3.8 build to use the numpy wheel

**Pull request merged**
