### PR TITLE
DEPR: Series.ravel

### LINKED ISSUE #52511: DEPR: Deprecate Series.ravel
The methods looks quite unnecessary, the EAs are a no-op and for NumPy users can simply call ravel on the NumPy array.

### PR DESCRIPTION
**Pull request by marechaux**
- [ ] closes #52511 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by phofl** [comment]
I'll have to take a closer look here, looks like we are using this internally. Will get to this over the weekend. pr itself is good!

**Comment by marechaux** [comment]
Thanks, Should I replace the internal usage of this function ?

**Comment by phofl** [comment]
I'll have to check what we are doing before I can give you a definitiv answer here

**Comment by jorisvandenbossche** [comment]
One place where we use `ravel()` internally that seems to cause many of the failures is in `maybe_downcast_numeric`:

https://github.com/pandas-dev/pandas/blob/961f9c4d7899121669c4832512c5903db573bb47/pandas/core/dtypes/cast.py#L348-L355

Changing `r = result.ravel()` to `r = np.ravel(result)` might be sufficient (assuming this won't dispatch to the method), or otherwise `r = np.asarray(result).ravel()` (we know at this point we have a numpy dtyped Series, so `np.asarray(..)` is cheap)

In theory we should not call this method with a Series though, but with an array (or, the type annotation is wrong)

**Comment by jbrockmendel** [comment]
> Thanks for your answer, Should I replace the internal usage of this function ?

Yes.

> In theory we should not call this method with a Series though, but with an array (or, the type annotation is wrong)

Agreed.

**Review by phofl — COMMENTED** [review]
Two quick changes to get ci green (hopefully):

- in assert_is_valid_plot_return_object there is still a ravel on a Series object. I'd recommend calling np.asarray(obj) and call ravel on the array
- FAILED pandas/tests/copy_view/test_array.py::test_ravel_read_only[F] You have to use tm.assert_produces_warning here

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
