### PR TITLE
Bug pyarrow implementation of str.fullmatch matches partial string. issue #56652

### LINKED ISSUE #56652: BUG: Pyarrow implementation of str.fullmatc matches partial string
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pyarrow as pa
import pandas as pd
print("pd Version: ", pd.__version__, "pa Version: ",  pa.__version__)
print(
    "Pyarrow Implementation:", pd.Series(["test$test"], dtype=pd.ArrowDtype(pa.string())).str.fullmatch("test\\$").values[0],
    "\nNative Implementation:", pd.Series(["test$test"]).str.fullmatch("test\\$").values[0]
)
# pd Version:  2.1.2 pa Version:  14.0.2
# Pyarrow Implementation: True 
# Native Implementation: False
```

### Issue Description

Fullmatch with pattern ending in "$" on pyarrow implementation can match a partial string. Expected the pyarrow and the native implementation to match. It appears that the "//$" in the following line should be a "\\$"
https://github.com/pandas-dev/pandas/blob/62dbbe6713b6467ff10673eb10adaf4342e67780/pandas/core/arrays/arrow/array.py#L2274

### Expected Behavior

A fullmatch on a pattern ending with "$" should not allow a partial match

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.11.4.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.0.0
Version             : Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : None.UTF-8

pandas              : 2.1.2
numpy               : 1.26.1
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 65.5.0
pip                 : 23.1.2
Cython              : None
pytest              : 7.4.3
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.17.2
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.12.1
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 14.0.2
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.3
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

### PR DESCRIPTION
**Pull request by JackCollins91**
- [x] closes #56652
- [x] Tests updated and passed
- [x] All code checks passed

Changed array.py: Makes Series(["abc$abc]).str.fullmatch("abc\\$") give the same result as when dtype = pyarrow.string as opposed to dtype = str.

Issue reporter (Issue-[#56652](https://github.com/pandas-dev/pandas/issues/56652)) requested change "//$" to "\\$", but this resulted in DepreciationWarnng in pytest, so used "\\\\$" instead.

Change test_arrow.py: updated test_str_fullmatch to account for edge cases where string starts with and ends with literal $ as well as ends with the string.

### CODE REVIEW

**Review by asishm — COMMENTED** [review]
thanks for the PR!

Grepping the codebase for `'//\$'` gives 

> ./pandas/core/arrays/arrow/array.py
> ./pandas/core/arrays/string_arrow.py

Testing further - it looks like the first affects `dtype=pd.ArrowDtype(pa.string())` while the second one affects `dtype="string[pyarrow]"`. The fix should be applied to both of the above files.

Also while the test method states `test_str_fullmatch` it seems to be testing `ser.str.match` instead. The fullmatch tests are present in `./pandas/tests/strings/test_find_replace.py`

**Comment by JackCollins91** [comment]
Thanks @asishm , I can make a commit which makes the changes in `./pandas/core/arrays/string_arrow.py`
and also updates the fullmatch test in `./pandas/tests/strings/test_find_replace.py`

To clarify, from testing, the changes to  ./pandas/core/arrays/arrow/array.py also affect `test_str_fullmatch` even though it does so via `str.fullmatch()`.

**Comment by JackCollins91** [comment]
Updated PR. 
Question: For consistency, I formatted test_fullmatch_dollar_literal() to match other unit tests in .py - Should I instead aim to implement @pytest.mark.parametrize, which is inconsistent with its neighbour tests, but more in-line with developer guidelines?

**Review by mroeschke — COMMENTED** [review]
Thanks could you add a whatsnew note in `v2.2.0.rst` under the `Strings` section?

**Comment by JackCollins91** [comment]
Thanks @mroeschke that update to `v2.2.0.rst` is added now.

**Comment by JackCollins91** [comment]
Resolved merge conflict by rebasing off upstream main.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @JackCollins91

**Pull request merged**
