### PR TITLE
replace Appender decorator with doc

### PR DESCRIPTION
**Pull request by smartvinnetou**
- [x] ref #31942
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] replaces Appender with doc for NDFrame.compare()

### CODE REVIEW

**Review by arw2019 — APPROVED** [review]
LGTM

**Comment by jbrockmendel** [comment]
Don't you need to Series.compare and DataFrame.compare too?

**Comment by smartvinnetou** [comment]
> Don't you need to Series.compare and DataFrame.compare too?

Yes. Done.

I kept the use to of `_shared_docs["compare"]` to keep the PR small but I'd find it more intuitive to define the doc string on `NDFrame.compare()` and then refer to it in the calls to the doc decorator on `Series.compare()` and `DataFrame.compare()`.

**Comment by jbrockmendel** [comment]
> Yes. Done.

Have you checked locally that you get the correctly-rendered docstrings?  When I try it with this PR, pandas cant even be imported.

**Comment by smartvinnetou** [comment]
> > Yes. Done.
> 
> Have you checked locally that you get the correctly-rendered docstrings? When I try it with this PR, pandas cant even be imported.

You were right. The CI is passing now.

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jbrockmendel** [comment]
thanks @smartvinnetou

**Pull request merged**
