### PR TITLE
CLN remove unnecessary trailing commas in pandas/io

### PR DESCRIPTION
**Pull request by sarthakvk**
@MarcoGorelli can you review this PR this is related to issue #35925, if this looks good to you I can open another PR
- [x] pandas/io/sas/sas_xport.py
- [x] pandas/io/stata.py
  
- [x] passes `black pandas`

### CODE REVIEW

**Review by dsaxton — COMMENTED** [review]
Thanks @sarthakchaudhary13, can you run black on /pandas/io to get linting green?

**Comment by sarthakchaudhary13** [comment]
Thanks for reviewing this PR @dsaxton, this is the output after re-running black on pandas/io.
```
$ black pandas/io
All done! ✨ 🍰 ✨ 
47 files left unchanged. 
```

**Comment by MarcoGorelli** [comment]
> Thanks for reviewing this PR @dsaxton, this is the output after re-running black on pandas/io.
> 
> ```
> $ black pandas/io
> All done! ✨ 🍰 ✨ 
> 47 files left unchanged. 
> ```

Can you check this with `black` version 19.10b0 as well, as that's the version that's run during CI? Ideally, you would:

- upgrade `black`
- run `black` on some files
- check what's changed, and try removing the trailing commas
- run `black` again
- downgrade `black` to version 19.10b0 and check everything is still fine

**Comment by sarthakchaudhary13** [comment]
> Can you check this with `black` version 19.10b0 as well, as that's the version that's run during CI? Ideally, you would:
> 
>     * upgrade `black`
> 
>     * run `black` on some files
> 
>     * check what's changed, and try removing the trailing commas
> 
>     * run `black` again
> 
>     * downgrade `black` to version 19.10b0 and check everything is still fine

@MarcoGorelli Thanks for the tip, both black versions checks are passing
I did a git revert for my previous commit but somehow other files also got changed, can you help me to fix this 😞

**Comment by MarcoGorelli** [comment]
@sarthakchaudhary13 I think I would do something like
```
git fetch upstream master
git rebase -i upstream/master  # choose which commits you want to keep
git push origin <your branch name> -f
```

**Comment by sarthakchaudhary13** [comment]
> @sarthakchaudhary13 I think I would do something like
> 
> ```
> git fetch upstream master
> git rebase -i upstream/master  # choose which commits you want to keep
> git push origin <your branch name> -f
> ```

@MarcoGorelli Thanks, if this looks good to you I can open another PR with fixing more files 😄

**Review by MarcoGorelli — APPROVED** [review]
Nice one @sarthakchaudhary13 ! And sure, any help here would be appreciated

**Comment by MarcoGorelli** [comment]
@sarthakchaudhary13 looks like there's a merge conflict, could you fetch and merge upstream/master and then push again please?

**Comment by sarthakchaudhary13** [comment]
> @sarthakchaudhary13 looks like there's a merge conflict, could you fetch and merge upstream/master and then push again please?

Yeah sure.

**Comment by WillAyd** [comment]
Thanks @sarthakchaudhary13

**Pull request merged**
