### PR TITLE
Pr09 batch 3

### PR DESCRIPTION
**Pull request by HughKelley**
part of #28602

### CODE REVIEW

**Comment by HughKelley** [comment]
@jbrockmendel is there a guide somewhere that specifies what each label is used for? Thanks!

**Comment by jbrockmendel** [comment]
i dont understand the question.  what labels?

**Comment by jreback** [comment]
can you merge master & ping on green.

**Comment by jreback** [comment]
> @jbrockmendel is there a guide somewhere that specifies what each label is used for? Thanks!

no guide on the labels, they are *hopefully* self-explanatory :-> they are just to organize the issues & PRs

**Comment by HughKelley** [comment]
like the Docs label is self explanatory but I'm not sure what Clean is for. 

Is the failing test (probably) due to a missing commit from master?

**Comment by HughKelley** [comment]
@jreback  all set.

**Comment by jreback** [comment]
thanks @HughKelley 

master was failing because of a numpy change; we disabled that build for now.

clean is just a generic label for internal cleaning.

**Pull request merged**
