### PR TITLE
CLN: remove core/matrix.py, not imported into the pandas namespace

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
+1

**Comment by jreback** [comment]
I don't think this needs to be deprecated in any way.

anyone disagree?

@wesm @jorisvandenbossche

**Comment by wesm** [comment]
I'm +1 on removal. Deprecation warning ought to have been there in 2011 but at this point minimal users will be affected.

**Comment by wesm** [comment]
you pushed the button!! =)

**Comment by jreback** [comment]
oh right
hmm

is there a way to disable it in GitHub?

**Comment by wesm** [comment]
No; it's been requested many times by users, though, since in a lot of OSS projects with tighter merge protocol they've had mishaps with merges happening by accident

**Pull request merged**
