### PR TITLE
WIP: REF: `DataFrame.to_html` directs to `Styler.to_html`

### PR DESCRIPTION
**Pull request by attack68**
This is being worked towards in #41693. Please look at that issue and comment if there are specific features we need to keep/discuss. This is a medium term project I've been working on but would be great if someone else in team can be sounding board.

### CODE REVIEW

**Comment by alimcmaster1** [comment]
Seems like some great work is being done here. I'm likely missing something but has anyone else in @pandas-dev/pandas-core approved/+1 this? 

As I suspect this might receive some complaints from users for 1.4 since this is such a commonly used method.

**Comment by bashtage** [comment]
> > What goal does it serve to have users reach deeper to access a method that has been around for ages?
> 
> * maintaining only one set of rendering methods and tests to produce HTML output.
> * removing some of the deprecated features of `DataFrame.to_html` that haven't been followed up over the years.
> * better performance and more features in `Styler.to_html`.

I wan't suggesting keeping 2 implementation.  I was just quibbling moving `to_html` to a different location. I think what @jreback  said is the best way forward.

**Comment by attack68** [comment]
> 
> I wan't suggesting keeping 2 implementation. I was just quibbling moving `to_html` to a different location. I think what @jreback said is the best way forward.

will work towards that, seems sensible and has good support.

**Comment by attack68** [comment]
Personally, I expected that jinja2 would be added as a hard requirement.

Having said that using pandas in a Notebook is commonly used with charting, where matplotlib is an optional dependency, so forcing another optional dependency might not be too restrictive, especially if well documented.

A fallback for a non-jinja2 notebook could be to use the string representation of a DataFrame with/without a warning?

**Comment by jreback** [comment]
so adding jinja2 as a hard requirement for styler is fine i think

**Comment by jreback** [comment]
ahh just read @jorisvandenbossche comment again

i think we should just add it as a hard requirement

**Comment by lithomas1** [comment]
Quick question: Would this be targeted for 1.4 or 2.0? I feel like we would need a deprecation cycle before switching the implementations around.

**Comment by attack68** [comment]
closing this temporarily in favour of #44451

**Pull request closed without merging**
