### PR TITLE
DOC: Replace .values with .to_numpy() in enhancingperf

### PR DESCRIPTION
**Pull request by huizew**
As suggested in https://github.com/pandas-dev/pandas/issues/24807#issuecomment-454905470

Replace `.values` with `.to_numpy()` in the benchmark demonstration code.

### CODE REVIEW

**Comment by WillAyd** [comment]
Thanks for the PR! How much effort do you think it would it be to swap out all of these instances across the documentation?

**Comment by huizew** [comment]
@WillAyd All the `.values` in this file have been replaced. 

Took a look at the other files under `pandas/doc/source`. Apart from `whatsnew` folder, no other file uses `.values` for pandas objects. And I suppose `whatsnew` files shouldn't be changed, right?

**Review by WillAyd — APPROVED** [review]
Great thanks for checking. I think this looks good - @gfyoung any thoughts?

**Comment by gfyoung** [comment]
For our own edification, can those benchmark numbers be double-checked (i.e. the ones that follow the `timeit` commands)?  Are those still approximately correct if we swap in `to_numpy`?  And how much is it vs. `.values` ?

**Comment by huizew** [comment]
Thanks for the review.

I just checked that changing to ‘.to_numpy()’ doesn’t change the benchmark time very much (less than 1%), and all the points that this guide tries to demonstrate still hold.

The performance comparison between ‘.to_numpy()’ and ‘.values’ is not discussed in this guide page. The difference seems negligible when compared to other things discussed in this guide page, such as Cython and Jit compiling. Personally I think the main reason behind this PR is to follow the documentation/community’s encouragement to use ‘.to_numpy()’ rather than ‘.values’.

**Comment by gfyoung** [comment]
> Personally I think the main reason behind this PR is to follow the documentation/community’s encouragement to use .to_numpy() rather than .values

True, but always good to double check to make sure we aren't actually proposing a performance regression in our docs.

**Comment by gfyoung** [comment]
Thanks @huizew !

**Pull request merged**
