### PR TITLE
CI/TST: add is_ci_environment to test_close_file_handle_on_invalid_usecols skip

### PR DESCRIPTION
**Pull request by simonjayhawkins**
follow-up to #45507 and #45771, xref https://github.com/pandas-dev/pandas/pull/45786#discussion_r798163348

### CODE REVIEW

**Comment by mroeschke** [comment]
Thanks @simonjayhawkins for catching this.

**Comment by mroeschke** [comment]
@meeseeksdev backport 1.4.x

**Comment by simonjayhawkins** [comment]
> Thanks @simonjayhawkins for catching this.

should maybe do this for `check_for_file_leaks` and `file_leak_context` in #45702?

**Comment by mroeschke** [comment]
> > Thanks @simonjayhawkins for catching this.
> 
> should maybe do this for `check_for_file_leaks` and `file_leak_context` in #45702?

Good point. Yeah those changes should be CI specific too.

**Pull request merged**
