### PR TITLE
DOC: whatsnew note for groupby.apply bugfix

### PR DESCRIPTION
**Pull request by rhshadrach**
ref https://github.com/pandas-dev/pandas/issues/45315#issuecomment-1013655106
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
thanks @rhshadrach

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by rhshadrach** [comment]
I forgot to cc @jbrockmendel - wanted to make sure you're good with the description here. Can do a follow up.

**Comment by jbrockmendel** [comment]
this is a great idea

**Pull request merged**
