### PR TITLE
CI: wrap ExcelFile.__del__ in try/except

### LINKED ISSUE #30217: CI Error AttributeError: 'ExcelFile' object has no attribute 'engine'
Showing up in 

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=22986&view=logs

```python
Traceback (most recent call last):
  File "D:\a\1\s\pandas\io\excel\_base.py", line 907, in __del__
    self.close()
  File "D:\a\1\s\pandas\io\excel\_base.py", line 890, in close
    if self.engine == "openpyxl":
AttributeError: 'ExcelFile' object has no attribute 'engine'
```

Looks to be caused by changes in #30096 - I think need to make it `self.reader.engine`. But definitely shows this code getting hit

@jbrockmendel

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes https://github.com/pandas-dev/pandas/issues/30217

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
cc @jbrockmendel @WillAyd

**Review by WillAyd — APPROVED** [review]
lgtm. I suppose if this hits an AttributeError things are just leaked right?

**Comment by jbrockmendel** [comment]
Worth a shot

**Comment by WillAyd** [comment]
Thanks @jorisvandenbossche

**Pull request merged**
