### PR TITLE
PERF: use _get_axis_number instead of if axis in [...]: #43048

### PR DESCRIPTION
**Pull request by KiranHipparagi**
Added _get_axis_number in test_at_time.py as per the standards

``` 
 if axis in ["index", 0]:              #<- master
      expected = ts.loc[indices, :]
 elif axis in ["columns", 1]:
      expected = ts.loc[:, indices]

 axis = self.data._get_axis_number(axis)   #<- PR
 expected = ts.loc[indices, :] if axis == 0 else ts.loc[:, indices]
```

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @KiranHipparagi for the PR. from #43048

> ...non-test codebase (i.e. don't find code examples in pandas/tests)

so closing this one.

**Comment by KiranHipparagi** [comment]
@simonjayhawkins can you please tell me why this PR closed. i'm new to open source contribution.This is my first PR on git.

**Comment by simonjayhawkins** [comment]
see https://github.com/pandas-dev/pandas/issues/43048#issuecomment-907582458

> Don't try and fix test files in pandas/tests.

**Comment by KiranHipparagi** [comment]
@simonjayhawkins Thank you for the clarification.

**Pull request closed without merging**
