### PR TITLE
fixed pathlib tests on windows

### PR DESCRIPTION
**Pull request by flying-sheep**
as requested here: https://github.com/pydata/pandas/issues/11033#issuecomment-148924778

i can’t test on windows unfortunately.

### CODE REVIEW

**Comment by jreback** [comment]
use this

```
In [6]: os.path.join('',*['foo','bar'])
Out[6]: 'foo/bar'
```

**Comment by flying-sheep** [comment]
much easier: `os.path.join('foo', 'bar')`

**Comment by jreback** [comment]
@flying-sheep right!

ok ping on green.

**Comment by jreback** [comment]
passes on windows

**Comment by flying-sheep** [comment]
ping!

**Comment by jreback** [comment]
thanks!

**Pull request merged**
