### PR TITLE
Replace old string formatting syntax with f-strings #29547

### PR DESCRIPTION
**Pull request by ynorouzz**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
there are some linting issues

**Comment by jreback** [comment]
see https://github.com/pandas-dev/pandas/pull/34903/checks?check_run_id=790893140

**Comment by WillAyd** [comment]
@ynorouzz is this still active? Can you address the comments / failures?

**Comment by simonjayhawkins** [comment]
closing since these were changed to f-strings in #34502 which has been merged, hence the conflict.

**Pull request closed without merging**
