### PR TITLE
CI: troubleshoot s3fs failures

### PR DESCRIPTION
**Pull request by jbrockmendel**
xref #28612.  Recent failures used 0.3.4, the last passing build I see used 0.2.0

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
I think this works for now @TomAugspurger

**Comment by TomAugspurger** [comment]
Won't be able to take a look today. Feel free to merge whenever.

cc @martindurant.

**Comment by WillAyd** [comment]
Thanks @jbrockmendel

**Comment by martindurant** [comment]
Locally, with pandas 0.25.0, s3fs master and fsspec master, a dataframe round-trips to S3 just fine.

**Pull request merged**
