### PR TITLE
REF: avoid getattr pattern for unstack, assorted cleanups

### PR DESCRIPTION
**Pull request by jbrockmendel**
Remove the only "FIXME" left in the cython code

### CODE REVIEW

**Comment by WillAyd** [comment]
Looks good - so these are replaced by a fused type right?

**Comment by jbrockmendel** [comment]
> so these are replaced by a fused type right?

In the unstack case we switched to fused types a while ago and this is finally doing the cleanup that made possible

**Review by WillAyd — APPROVED** [review]
lgtm @jreback

**Comment by jreback** [comment]
thanks

**Pull request merged**
