### PR TITLE
Added suggested new line to fix doc code example

### LINKED ISSUE #53770: DOC: to_orc example doesn't render
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.to_orc.html

### Documentation problem

The example doesn't render, see the example of the page

### Suggested fix for documentation

just need to add an empty line (with no whitespace!)

```diff
diff --git a/pandas/core/frame.py b/pandas/core/frame.py
index b411cfc4a4..352d353ef4 100644
--- a/pandas/core/frame.py
+++ b/pandas/core/frame.py
@@ -2981,6 +2981,7 @@ class DataFrame(NDFrame, OpsMixin):
         1     2     3
 
         If you want to get a buffer to the orc content you can write it to io.BytesIO
+
         >>> import io
         >>> b = io.BytesIO(df.to_orc())  # doctest: +SKIP
         >>> b.seek(0)  # doctest: +SKIP
```

### PR DESCRIPTION
**Pull request by rahulsiloniya**
- [x] closes #53770
- [x] Modified as suggested in the issue

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
can you remove the whitespace pls?

**Comment by rahulsiloniya** [comment]
Sure thing but, then what is supposed to be changed in the docstring?

**Comment by MarcoGorelli** [comment]
you need a blank line with no whitespace

**Comment by rahulsiloniya** [comment]
Oh, okay

**Review by MarcoGorelli — APPROVED** [review]
thanks @rahulsiloniya

**Comment by rahulsiloniya** [comment]
Yay!! Looking forward to contribute some code to this repo.

**Pull request merged**
