### PR TITLE
BUG: Index[offset_objects] + Period

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
Related to https://github.com/pandas-dev/pandas/issues/50162 in which case this is only an issue on main?

**Comment by jbrockmendel** [comment]
> this is only an issue on main?

No, the incorrect raising also occurs on 1.5.0

**Review by mroeschke — APPROVED** [review]

**Comment by jbrockmendel** [comment]
> So does the not necessarily close https://github.com/pandas-dev/pandas/issues/50162?

No

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
