### PR TITLE
ENH: Add dict support for read_csv date_format

### LINKED ISSUE #51240: ENH: let date_format take a mapping of columns to formats
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

follow-up to https://github.com/pandas-dev/pandas/pull/51019

### Feature Description

`date_format` should accept either a single format, or a mapping from column names to formats

### Alternative Solutions

Just keep as-is. But this has been requested by a few people in https://github.com/pandas-dev/pandas/pull/51019, and would be consistent with some other IO arguments

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #51240 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @phofl

**Comment by phofl** [comment]
thx @MarcoGorelli for helping out

**Comment by mroeschke** [comment]
So it appears the tests added here can raise a UserWarning 

```
============================================================================= warnings summary =============================================================================
pandas/tests/io/parser/test_parse_dates.py::test_parse_dates_dict_format_two_columns[c_high-foo-parse_dates1]
pandas/tests/io/parser/test_parse_dates.py::test_parse_dates_dict_format_two_columns[c_low-foo-parse_dates1]
pandas/tests/io/parser/test_parse_dates.py::test_parse_dates_dict_format_two_columns[python-foo-parse_dates1]
  /.../opt/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: 'pandas._libs.tslibs.parsing._maybe_warn_about_dayfirst'

  Traceback (most recent call last):
    File ".../pandas/core/tools/datetimes.py", line 137, in _guess_datetime_format_for_array
      guessed_format = guess_datetime_format(
  UserWarning: Parsing dates in %d- %m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

I would expect no warning since an explicit format is passed?

**Comment by MarcoGorelli** [comment]
That's a good question - so, `parse_dates` is `{'foo': [0, 1]}`, and `date_format` specifies column `'foo'`, but in 

https://github.com/pandas-dev/pandas/blob/7598f71993f442c6420456e1e2c3c8d3bc65c80b/pandas/io/parsers/base_parser.py#L1118-L1120

, `col` is `'a_b'`, and so it doesn't find the date format in the dict and so `date_fmt` is `None`, so the format has to be guessed. It's reassuring that the correct format was guessed 😄 

Thanks for spotting this

@phofl should the user have passed `date_format={'a_b': '%d- %m-%Y'}`, or does this need fixing in the code?

**Comment by phofl** [comment]
code I'd say, good catch btw.

**Comment by phofl** [comment]
#51479

**Pull request merged**
