### PR TITLE
DOC: updated plotting/_misc.py for PR08 errors

### PR DESCRIPTION
**Pull request by willpeppo**

### CODE REVIEW

**Review by alimcmaster1 — APPROVED** [review]

**Comment by alimcmaster1** [comment]
Thanks for the PR - mind referring the issue on this?

**Comment by willpeppo** [comment]
yes no problem at a all... what's the best way to do that?   Just put the issue number in the comments ?   Thanks in advance for the guidance.

**Comment by alimcmaster1** [comment]
Exactly - the template should help. https://github.com/pandas-dev/pandas/issues/25232

**Review by WillAyd — CHANGES_REQUESTED** [review]
So this conflicts a bit with PRs like #32439 that try to make the word pandas always lowercase. With that in mind I would say just remove the word pandas here, as it doesn't add any value

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Great thanks @willpeppo

**Pull request merged**
