### PR TITLE
CLN: clean the conda-to-pip script

### PR DESCRIPTION
**Pull request by fangchenli**
precursor of #42304

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
No objections here, good to remove the now-unnecessary `azure` flag

**Comment by jreback** [comment]
thanks @fangchenli

**Comment by simonjayhawkins** [comment]
this is a precursor to #42304, see https://github.com/pandas-dev/pandas/pull/42720#issue-696688995

needs backport for #42901

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
