### PR TITLE
DEP: Remove xlrd as being the default reader for xlsx

### LINKED ISSUE #38884: DEPR: Remove xlrd as being the default reader for xlsx
Currently the default reader for xlsx is openpyxl if installed, otherwise it is xlrd. While xlrd == 1.2.0 will work with xlsx files, xlrd >= 2.0 will not. In pandas 1.2, a FutureWarning is raised if xlrd is used on non-xls files. We should remove xlrd as being the default for xlsx files in pandas 2.0, but perhaps even 1.3 (if 1.3 != 2.0).

cc @jorisvandenbossche

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] closes #38884
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

One thing I noticed while working on this is that xlrd is in requirements-dev but not environment.yml; not sure if it should be removed from requirements-dev.

cc @jreback @jorisvandenbossche

### CODE REVIEW

**Comment by jreback** [comment]
dont' we have *any* tests that needed to be changed? (also pls merge master)

**Comment by jreback** [comment]
> One thing I noticed while working on this is that xlrd is in requirements-dev but not environment.yml; not sure if it should be removed from requirements-dev.

requirements-dev is autogenerated from environment.yml so this would be strange (but it appears to be in both).

**Comment by WillAyd** [comment]
Can we add a test that openpyxl is actually being dispatched to as the default?

**Comment by rhshadrach** [comment]
@jreback

> requirements-dev is autogenerated from environment.yml so this would be strange (but it appears to be in both)

Whoops - not sure what I was looking at then :)

@jreback, @WillAyd - tests added. For ExcelFile we can get the engine directly, for pd.read_excel I monkey patched ExcelFile.parser.

**Comment by jreback** [comment]
very nice @rhshadrach

**Pull request merged**
