### PR TITLE
fix #28926 mypy error in pandas\tests\arrays\test_array.py 

### PR DESCRIPTION
**Pull request by yogendrasoni**
- [ ] xref #28926
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
lgtm @simonjayhawkins

**Comment by jjlkant** [comment]
Was (accidentally) also looking into this fix. However, I believe this is also the fix for:
* _pandas\tests\arrays\test_period.py_
```bash
pandas\tests\arrays\test_period.py:245: error: Argument "freq" to "period_array" has incompatible type "str"; expected "Optional[Tick]"
```
* _pandas\tests\arrays\test_base.py_
```bash
pandas\tests\test_base.py:1312: error: Argument "freq" to "period_array" has incompatible type "str"; expected "Optional[Tick]"
pandas\tests\test_base.py:1354: error: Argument "freq" to "period_array" has incompatible type "str"; expected "Optional[Tick]"
```

This implies the entries for both of these files should also be removed from setup.cfg

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
@yogendrasoni lgtm. can you also remove the sections in setup.cfg for pandas\tests\arrays\test_period.py and pandas\tests\test_base.py see https://github.com/pandas-dev/pandas/pull/28970#issuecomment-541964482

**Review by simonjayhawkins — COMMENTED** [review]
@yogendrasoni Thanks for making those changes. ci failures are unrelated. see #29008

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
@yogendrasoni can you merge master

**Comment by simonjayhawkins** [comment]
@yogendrasoni in merging master the section in setup.cfg for pandas\tests\arrays\test_period.py was reinstated. can you remove.

**Review by simonjayhawkins — APPROVED** [review]
@yogendrasoni lgtm ping on green.

**Comment by simonjayhawkins** [comment]
Thanks @yogendrasoni

**Pull request merged**
