### PR TITLE
DOC: Add missing single quote to `Timestamp.tz_localize`

### PR DESCRIPTION
**Pull request by rob-sil**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks @rob-sil

**Comment by MarcoGorelli** [comment]
merging as ci failure is unrelated

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
sorry, i was sure the ci failure wouldn't been unrelated, but it appears not to be so:

```
=================================== FAILURES ===================================
_________________ test_nat_doc_strings[Timestamp.tz_localize] __________________
[gw3] linux -- Python 3.11.9 /home/runner/micromamba/envs/test/bin/python3.11

compare = (<class 'pandas._libs.tslibs.timestamps.Timestamp'>, 'tz_localize')

    @pytest.mark.parametrize(
        "compare",
        (
            _get_overlap_public_nat_methods(Timestamp, True)
            + _get_overlap_public_nat_methods(Timedelta, True)
        ),
        ids=lambda x: f"{x[0].__name__}.{x[1]}",
    )
    def test_nat_doc_strings(compare):
        # see gh-17327
        #
        # The docstrings for overlapping methods should match.
        klass, method = compare
        klass_doc = getattr(klass, method).__doc__
    
        if klass == Timestamp and method == "isoformat":
            pytest.skip(
                "Ignore differences with Timestamp.isoformat() as they're intentional"
            )
    
        if method == "to_numpy":
            # GH#44460 can return either dt64 or td64 depending on dtype,
            #  different docstring is intentional
            pytest.skip(f"different docstring for {method} is intentional")
    
        nat_doc = getattr(NaT, method).__doc__
>       assert klass_doc == nat_doc
E       AssertionError

pandas/tests/scalar/test_nat.py:335: AssertionError
```
could you fix it up please

**Comment by rob-sil** [comment]
@MarcoGorelli good catch! Sorry about that. Found a couple more cases of that same line.

**Review by MarcoGorelli — APPROVED** [review]
thanks @rob-sil

**Pull request merged**
