### PR TITLE
PERF: Series.to_numpy with float dtype and na_value=np.nan

### PR DESCRIPTION
**Pull request by lukemanley**
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/v2.1.0.rst` file if fixing a bug or adding a new feature.

Avoids filling na values with `np.nan` if the array is already a numpy float dtype. (`DataFrame` has a similar optimization in `BlockManager.as_array`)

```
import pandas as pd
import numpy as np

ser = pd.Series(np.random.randn(10_000_000))

%timeit ser.to_numpy(dtype="float64", na_value=np.nan, copy=False)

# 22.5 ms ± 2.56 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)          -> main
# 1.97 µs ± 24.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)   -> PR
```

ASV added:
```
       before           after         ratio
     [3ce07cb4]       [020fb14a]
     <main>           <series-to-numpy-float-nan>
-     1.02±0.02ms      2.12±0.03μs     0.00  series_methods.ToNumpy.time_to_numpy_float_with_nan

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```

### CODE REVIEW

**Review by topper-123 — APPROVED** [review]
LGTM

**Comment by topper-123** [comment]
Actually, what about `FloatDtype(64|32)`?

**Comment by lukemanley** [comment]
> Actually, what about `FloatDtype(64|32)`?

EA dtypes dispatch to their own implementation of `to_numpy`. In the case of `FloatDtype(64|32)`, I'm not sure there is anything to be done. `BaseMaskedArray.to_numpy` needs to combine the data array and the mask array when NAs exist.

**Review by topper-123 — APPROVED** [review]
LGTM.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @lukemanley

**Pull request merged**
