### PR TITLE
Remove alias in pandas docs for numpy.random.randn

### PR DESCRIPTION
**Pull request by WuraolaOyewusi**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WuraolaOyewusi** [comment]
@datapythonista , Hi Marc

**Review by datapythonista — COMMENTED** [review]
Thanks for the change . Can you replace the `randn` in the release notes of 0.10.0 by `np.random.randn` too please?

**Comment by WuraolaOyewusi** [comment]
Ok Marc

**Comment by datapythonista** [comment]
Superseded by #28082

**Pull request closed without merging**
