### PR TITLE
STYLE: Sort tests/groupby imports GH23334

### PR DESCRIPTION
**Pull request by samcan**
Sort imports in `tests/groupby`.

- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by alimcmaster1 — CHANGES_REQUESTED** [review]
Please fix the lint errors in CI

Linting .py code
./pandas/tests/groupby/test_grouping.py:24:1: E302 expected 2 blank lines, found 1

**Comment by jreback** [comment]
can you merge master, we just updated the isort cfg

**Comment by samcan** [comment]
I'm going to take a look at this tomorrow afternoon (about 4pm -800)

**Comment by jreback** [comment]
can you rebase and fixup

**Comment by samcan** [comment]
I've remerged the master from https://pandas.pydata.org/pandas-docs/stable/contributing.html#updating-your-pull-request but when I try to rebase my commits into one, I can't find my original commit. If I try to push my new commit to the branch tests-groupby-sorted it says the update was rejected because the tip of the current branch is behind the remote counterpart. I'm not sure where to go from here.

**Comment by samcan** [comment]
And to clarify, (from Note about Fast-forwards at the git-push documentation) it appears that the issue is that development has proceeded on a different commit, so my commit needs to integrate data from that commit before my commit can be merged back into master. But I don't know then why fetching the upstream master wouldn't have done that.

**Comment by jreback** [comment]
you can just merge master and push
you don’t need to squash

**Comment by samcan** [comment]
But without trying to squash, it's still saying my current branch is behind. Again, this is from https://pandas.pydata.org/pandas-docs/stable/contributing.html#updating-your-pull-request

```
> git fetch upstream

> git merge upstream/master
Already up to date.

> git push origin tests-groupby-sorted
To https://github.com/samcan/pandas
 ! [rejected]            tests-groupby-sorted -> tests-groupby-sorted (non-fast-forward)
error: failed to push some refs to 'https://github.com/samcan/pandas'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I added `--force` to get it to run:
```

>git push --force origin tests-groupby-sorted
Enumerating objects: 1344, done.
Counting objects: 100% (1344/1344), done.
Delta compression using up to 4 threads
Compressing objects: 100% (386/386), done.
Writing objects: 100% (995/995), 334.78 KiB | 6.83 MiB/s, done.
Total 995 (delta 825), reused 716 (delta 609)
remote: Resolving deltas: 100% (825/825), completed with 324 local objects.
To https://github.com/samcan/pandas
 + 254af7073...4870a412f tests-groupby-sorted -> tests-groupby-sorted (forced update)
```

But I'm nervous about doing so because the docs say it can lose commit history. Would that only be in my branch?

Thank you,

**Comment by jreback** [comment]
if you rebase then you need to force push; the point is to overwrite history
you can alternately simply merge master and push (this is the official workflow in the docs)
it doesn’t matter at the end of the day as when merged your PR will be squashed anyhow

**Comment by jreback** [comment]
closing as stale. would take PR's that fix style though.

**Pull request closed without merging**
