### PR TITLE
DEPR: int slicing always positional

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

We've gone back and forth on this a couple times (#45324, #49869 would have done this as a breaking change in 2.0).

### CODE REVIEW

**Comment by mroeschke** [comment]
Do you remember why this was reverted before?

**Comment by jbrockmendel** [comment]
> Do you remember why this was reverted before?

There was a deprecation #45324 that was basically the opposite of this (make slice-with-integer-index label-based) but i messed up the deprecation and didn't warn in enough cases (discussed #49612), so actually enforcing it would have broken a bunch more stuff.

Also you pointed out (https://github.com/pandas-dev/pandas/issues/49612#issuecomment-1322569915) a different inconsistency, and I guess in the Dec dev call we decided to punt on this.

**Comment by mroeschke** [comment]
+1 for still moving forward with this deprecation

**Comment by jbrockmendel** [comment]
@phofl @marcogorelli OK here?

**Review by MarcoGorelli — APPROVED** [review]
yeah no objections

wouldn't be opposed to completely deprecating slicing rows, and only supporting `.iloc` / `loc`

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
