### PR TITLE
STYLE: Inconsistent namespace - apply (pandas-dev#39992)

### LINKED ISSUE #39992: STYLE Increase coverage of inconsistent-namespace-usage
If you already have experience contributing, then please leave this issue to newcomers - thanks :+1: 

---

In `.pre-commit-config.yaml`, the check `inconsistent-namespace-usage` is limited to `pandas/tests/frame/`. Let's expand it to the rest of `pandas/tests/`.

The task here is:

0. make sure you're familiar with the [contributing guide](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html)
1. choose a folder from the list below (e.g. `series`) and add it to the check in `.pre-commit-config.yaml`. E.g., if you chose `series`, that would be:

  ```yaml
      -   id: inconsistent-namespace-usage
          name: 'Check for inconsistent use of pandas namespace in tests'
          entry: python scripts/check_for_inconsistent_pandas_namespace.py
          language: python
          types: [python]
          files: ^pandas/tests/(frame|series)/
  ```

2. temporarily add `tokenize-rt` as an additional dependency and `--replace` as an arg (these will be removed later):

  ```yaml
      -   id: inconsistent-namespace-usage
          name: 'Check for inconsistent use of pandas namespace in tests'
          entry: python scripts/check_for_inconsistent_pandas_namespace.py
          language: python
          types: [python]
          files: ^pandas/tests/(frame|series)/
          additional_dependencies: [tokenize-rt]
          args: [--replace]
  ```

3. run this check on all files with pre-commit, i.e.:

```console
  $ pre-commit run inconsistent-namespace-usage --all-files
  [INFO] Initializing environment for local:tokenize-rt.
  [INFO] Installing environment for local.
  [INFO] Once installed this environment will be reused.
  [INFO] This may take a few minutes...
  Check for inconsistent use of pandas namespace in tests.......................Failed
  - hook id: inconsistent-namespace-usage
  - files were modified by this hook
  ```

4. run it again - this time, it should pass

  ```console
  $ pre-commit run inconsistent-namespace-usage --all-files
  Check for inconsistent use of pandas namespace in tests.......................Passed
  ```
  
  Check that the other hooks still pass - if you enable pre-commit (`pre-commit install`), then this will happen automatically when you try to commit your changes (see step 6)

5. revert the changes to `.pre-commit-config.yaml` (we'll update it once these changes are all so as to avoid a barrage of merge conflicts)
6. commit your changes, and open a pull request. Check over your changes, make sure they look sensible, let me know if not

---

Here are the folders in `pandas/tests` which this check needs expanding to:

- [x] series
- [x] scalar
- [x] resample
- [x] util
- [x] tseries
- [x] dtypes
- [x] arrays
- [x] plotting
- [x] tools
- [x] indexing
- [x] strings
- [x] reductions
- [x] frame
- [x] arithmetic
- [x] config
- [x] api
- [x] generic
- [x] io
- [x] base
- [x] window
- [x] internals
- [x] reshape
- [x] computation
- [x] apply
- [x] groupby
- [x] tslibs
- [x] libs
- [x] indexes
- [x] extension

No need to ask for permission to work on this, just leave a comment letting people know which folder(s) from the list above you're working on

### PR DESCRIPTION
**Pull request by punitvara**
Fix inconsistent namespace in apply directory.

- [x] xref #39992
- [ ] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks @punitvara , pending green this looks good to me

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
No need for a whatsnew note, can you revert it please?

It looks like you've done this correctly, but now some of the other hooks are failing (e.g. `black`, can you fix them up please?

**Comment by punitvara** [comment]
@MarcoGorelli  Sure. I have reverted it back. Thanks for guiding me.

**Comment by MarcoGorelli** [comment]
> Hope this looks fine now.

You still need to fixup the error from the `black` formatter

```
pre-commit run --files pandas/tests/apply/test_frame_apply.py pandas/tests/apply/test_series_apply.py
```

**Comment by punitvara** [comment]
Done.

**Review by MarcoGorelli — APPROVED** [review]
Now it's correct, thanks!

**Comment by jreback** [comment]
@MarcoGorelli go ahead and merge PRs like this that are all green-ish

**Comment by MarcoGorelli** [comment]
sure, thanks - flake8 and the rest pass, so this should be good to go

**Pull request merged**
