### PR TITLE
Fix groupby-resample KeyError when resampling on Index and giving explicit list of columns. (1.5.x)

### LINKED ISSUE #50840: BUG: df.groupby().resample()[[cols]] raise KeyError when resampling on index
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from pandas import (
    DataFrame,
    Index,
    Series,
    Timestamp,
)
from pandas.core.indexes.datetimes import date_range

df = DataFrame(
    data={
        "group": [0, 0, 0, 0, 1, 1, 1, 1],
        "val": [3, 1, 4, 1, 5, 9, 2, 6],
    },
    index=Series(
        date_range(start="2016-01-01", periods=8),
        name="date",
    ),
)
result = df.groupby("group").resample("2D")[["val"]].mean()
```

### Issue Description

If I try and do a `GroupBy` and `Resample` on a DataFrame, asking for only a subset of the columns before the aggregate, I get a KeyError.

### Expected Behavior

I expect to see that the following DataFrame where the aggregate has been performed on the requested column(s)
```
expected = DataFrame(
    data={
        "val": [2.0, 2.5, 7.0, 4.0],
    },
    index=Index(
        data=[
            (0, Timestamp("2016-01-01")),
            (0, Timestamp("2016-01-03")),
            (1, Timestamp("2016-01-05")),
            (1, Timestamp("2016-01-07")),
        ],
        name=("group", "date"),
    ),
)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.9.15.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-66-generic
Version          : #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.2
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 66.0.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

### PR DESCRIPTION
**Pull request by czroth**
- [x] closes #50840
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by czroth** [comment]
Pandas Devs:
I updated the 1.5.x branch with the fix. Please reply with instructions on if I should add the fix and test code to the main branch as well, or if you would like to do that. This is my first contribution to Pandas, so I'm unfamiliar with the workflow at this point.

**Comment by mroeschke** [comment]
PRs should generally always target the main branch. This bug fix should also target 2.0 and not 1.5.x as this doesn't appear like a regression per se

**Comment by czroth** [comment]
@mroeschke, I'll leave this PR open in case you also want to have the changes made to the 1.5.x branch. I'll also open a new PR (linked with this one) where I've applied the fix to the main branch and added to the whatsnew for v2.0

**Comment by mroeschke** [comment]
We have a backporting bot that would take care of this (and this fix doesn't appear eligible for it) so will close this one

**Pull request closed without merging**
