### PR TITLE
BUG: Fix crash using to_csv with QUOTE_NONE

### PR DESCRIPTION
**Pull request by jtratner**
Fixes #4328.

Now passes `quotechar` to csv's writer. Default is same as csv (`'"'`), but sets to `None` with `quoting=csv.QUOTE_NONE`.

### CODE REVIEW

**Comment by pronojitsaha** [comment]
Hi, 
I am having this issue still now. My data frame contains unicode strings. Now when I use 'to_csv' without any quoting parameter, I get a csv file where certain fields (2 out of 11 to be exact) are in double quotes. For example:
```28,"May 8, 2013 10:22 AM","76th St, Yates Blvd",41.75717,-87.56633,3,-,1,4,-```
 Now when I use csv.QUOTE_NONE i get the following error:
```Error: need to escape, but no escapechar set```
So i do the following (quoting=csv.QUOTE_NONE, escapechar='"'), and I get this:
```28,May 8", 2013 10:22 AM,76th St", Yates Blvd,41.75717,-87.56633,3,-,1,4,-```
So I get a new quote (") in  those 2 fields. How to get around this problem? Thanks.

**Comment by jreback** [comment]
you need to provide a copy-pastable example which reproduces

**Comment by pronojitsaha** [comment]
Please find below:
```
html = urlopen('http://www.city-data.com/accidents/acc-Chicago-Illinois.html#googleStreetView2013').read()
soup = BeautifulSoup(html)
tables = soup('table', {'class': 'table tblsort tblsticky tabBlue'})

id = []
date = []
location = []
vehicles = []
drunken_persons = []
fatalities = []
persons = []
pedestrians = []


for table in tables:
    for row in table.tbody('tr'):
        tds = row('td')
        id.append(tds[0].text)
        date.append(tds[1].text) # .encode('UTF8')
        location.append(tds[2].text)
        vehicles.append(tds[3].text)
        drunken_persons.append(tds[4].text)
        fatalities.append(tds[5].text)
        persons.append(tds[6].text)
        pedestrians.append(tds[7].text)

data = pd.DataFrame({'#':id, 'Date':date, 'Vehicles':vehicles, 'Drunken Persons':drunken_persons, 'Fatalities':fatalities, 'Persons':persons,  'Pedestrians':pedestrians, 'Location':location})

data[['#','Date','Location','Vehicles','Drunken Persons','Fatalities','Persons', 'Pedestrians']].astype(str).to_csv('Chicago.csv',  sep=',', index = False, quoting=csv.QUOTE_NONE, escapechar='"')
```

**Comment by jreback** [comment]
pls only an example that is not subject to these types of external dependencies.

**Comment by pronojitsaha** [comment]
OK. I have updated the original post.

**Comment by jreback** [comment]
and this is a merged issues, so pls open a new one

**Comment by pronojitsaha** [comment]
Ok, done. Here - https://github.com/pydata/pandas/issues/10783

**Pull request merged**
