### PR TITLE
Update PSF_LICENSE

### PR DESCRIPTION
**Pull request by saintgabriel0**
Corrections on some misspelled words on the PSF_LICENSE.

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by chineduG** [comment]
Spellings are updated on the PSF_LICENSE.

**Review by jreback — CHANGES_REQUESTED** [review]
there seems to be quite a lot of whitespace here, is this on purpose? can you link to the source where you are getting the license itself

**Comment by datapythonista** [comment]
@chineduG do you have time to address the comments? If you check the diff, you will quickly see that the format of your changes is not correct. It's fine to update the text, but the format should be the same, not all these blank lines that make really hard to read the document.

**Comment by datapythonista** [comment]
Closing as stale. @chineduG if you still want to address the comments and continue working on this please let us know to reopen.

**Pull request closed without merging**
