### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mayank1897**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
If you think it's important that this change be made, use semi-colons, not full stops

> For a list of longer items or sentences, which follow on from an introductory sentence, each item should end with a semi colon and the final item should end with a full stop.

https://www.imperial.ac.uk/brand-style-guide/writing/grammar/punctuation/bullet-points/

**Comment by MarcoGorelli** [comment]
thanks

**Comment by mayank1897** [comment]
you're welcome.

**Pull request merged**
