### PR TITLE
Fix import format tests/indexes/ "Part One"

### PR DESCRIPTION
**Pull request by thoo**
- [x] xref #23334
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
Run `isort -rc pandas/tests/indexes/`

PR is capped at 20 files. So this is not all the files modified from `pandas/tests/indexes/`. So this is Part One of this directory `pandas/tests/indexes/`.

### CODE REVIEW

**Comment by jreback** [comment]
@thoo pls remove the fixed files from the setup.cfg as then the flaker will check.

**Comment by thoo** [comment]
Sorry. I missed that part.

**Review by jreback — CHANGES_REQUESTED** [review]
ping on green.

**Comment by jreback** [comment]
btw, since lots of these PR's, any time you push merge in master as well.

**Comment by thoo** [comment]
@jreback  Pass all checks.

**Review by jreback — APPROVED** [review]

**Pull request closed without merging**
