### PR TITLE
CI: Revert 31323 for deprecation warning from Jedi

### LINKED ISSUE #31407: CI: revert the warning change once IPython updates
A couple days ago, there was a CI broken caused by the latest jedi release, and back then, made a patch to catch the warning. Ideally, after ipython updates and fixes the deprecated code, then the warning should be removed, and we should be able to revert the change in #31323

FYI, I created an issue on IPython: https://github.com/ipython/ipython/issues/12102

### PR DESCRIPTION
**Pull request by charlesdong1991**
- [x] closes #31407

ipython/ipython#12102 has been solved, and the new release came out a couple weeks ago, so revert should be fine according to https://github.com/ipython/ipython/issues/12102#issuecomment-670987484

### CODE REVIEW

**Comment by WillAyd** [comment]
Is this still active?

**Comment by charlesdong1991** [comment]
emm, it is blocked by an ipython issue. my previous issue was closed ipython/ipython#12102 however, it wasn't being solved in the later version of ipython

there is a new issue  https://github.com/ipython/ipython/issues/12597 now tracking this warning issue, not sure if the fix will be included a newer version.

**Comment by jreback** [comment]
what is the status here?

**Comment by jreback** [comment]
we have a *new* jedi issue, but this one is moot.

**Pull request closed without merging**
