### PR TITLE
TST: add tests for DatetimeIndex.is_year_start/is_quarter_start on "BMS" frequency

### LINKED ISSUE #58729: BUG: DatetimeIndex.is_year_start breaks on BusinessMonthBegin frequency
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

dr1 = date_range("2020-01-01", periods=1, freq="CBMS")
print(dr1.is_year_start)
dr2 = date_range("2020-01-01", periods=1, freq="BMS")
print(dr2.is_year_start)
```

### Issue Description

This outputs:
```
[ True]
[False]
```

### Expected Behavior

it should return [ True] in both cases, as 1st of January 2020 was a Wednesday

### Installed Versions

<details>
commit                : ae1928b0aac0ebcefe2158891c8a837bab242b9b
python                : 3.10.13.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 4.19.0-22-amd64
Version               : #1 SMP Debian 4.19.260-1 (2022-09-29)
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_GB.UTF-8
LOCALE                : en_GB.UTF-8

pandas                : 3.0.0.dev0+478.gae1928b0aa.dirty
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0
setuptools            : 69.1.1
pip                   : 24.0
Cython                : 3.0.8
pytest                : 8.0.2
hypothesis            : 6.98.17
sphinx                : 7.2.6
blosc                 : None
feather               : None
xlsxwriter            : 3.1.9
lxml.etree            : 5.1.0
html5lib              : 1.1
pymysql               : 1.4.6
psycopg2              : 2.9.9
jinja2                : 3.1.3
IPython               : 8.22.2
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : 1.3.8
fastparquet           : 2024.2.0
fsspec                : 2024.2.0
gcsfs                 : 2024.2.0
matplotlib            : 3.8.3
numba                 : 0.59.0
numexpr               : 2.9.0
odfpy                 : None
openpyxl              : 3.1.2
pyarrow               : 15.0.0
pyreadstat            : 1.2.6
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 2024.2.0
scipy                 : 1.12.0
sqlalchemy            : 2.0.27
tables                : 3.9.2
tabulate              : 0.9.0
xarray                : 2024.2.0
xlrd                  : 2.0.1
zstandard             : 0.22.0
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
</details>

### PR DESCRIPTION
**Pull request by natmokval**
- [x] closes #58729
- [x] Tests added and passed
- [x] Added an entry in the latest `doc/source/whatsnew/v3.0.0.rst

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @natmokval for the PR.

Should the OP be an issue instead.? or is there already an open issue for this?

**Comment by natmokval** [comment]
> Thanks @natmokval for the PR.
> 
> Should the OP be an issue instead.? or is there already an open issue for this?


thanks @simonjayhawkins for the comment. No, there is no open issue for this.
It's my mistake; I should have opened an issue first. Now I've opened the issue for this PR.

**Comment by natmokval** [comment]
Fixed bug in `DatetimeIndex.is_year_start` and `DatetimeIndex.is_quarter_start` returning `False` instead of `True` when using BusinessMonthBegin frequency. @MarcoGorelli, could you please take a look at this PR?

**Comment by MarcoGorelli** [comment]
thanks for looking into this

not sure this fixes the issue to be honest:
```python
In [2]: pd.DatetimeIndex(['1976-11-01', '1976-12-01', '1977-01-03'], freq='BMS')
Out[2]: DatetimeIndex(['1976-11-01', '1976-12-01', '1977-01-03'], dtype='datetime64[s]', freq='BMS')

In [3]: arr = pd.DatetimeIndex(['1976-11-01', '1976-12-01', '1977-01-03'], freq='BMS')

In [4]: arr.is_year_start
Out[4]: array([False, False,  True])

In [5]: [x.is_year_start for x in arr]
Out[5]: [False, False, False]
```
We'd expect `Out[4]` and `Out[5]` to be the same, right?

Here's a little hypothesis test I put together:
```python
import pytest
import hypothesis.strategies as st
from hypothesis import given
import pandas as pd
from datetime import datetime


@pytest.mark.parametrize('freq', [
    'MS',
    'BMS',
])
@given(dt = st.datetimes(min_value=datetime(1960, 1, 1), max_value=datetime(1980, 1, 1)))
def test_me(freq, dt):
    d = pd.date_range(dt, periods=3, freq=freq)
    result = [x for x in d.is_year_start]
    expected = [x.is_year_start for x in d]
    assert result == expected
```

Granted, it looks like this is already super-broken on `main` anyway, but I think this requires a more general and a very careful and focused fix

**Comment by MarcoGorelli** [comment]
Sorry, as an addendum to my previous comment: `Timestamp` doesn't have `freq`, so the two results can't be expected to be the same

If I amend the hypothesis test to be:
```python
@given(
    dt = st.datetimes(min_value=datetime(1960, 1, 1), max_value=datetime(1980, 1, 1)),
    n = st.integers(min_value=1, max_value=10),
    freq = st.sampled_from(['BMS'])
)
def test_me(freq, dt, n):
    freq = f'{n}{freq}'
    d = pd.date_range(dt, periods=3, freq=freq)
    result = [x for x in d.is_year_start]
    expected = []
    for x in d:
        if x.is_year_start:
            expected.append(True)
        else:
            if x.day_of_week == 0 and (x - pd.Timedelta(days=1)).is_year_start:
                expected.append(True)
            elif x.day_of_week == 0 and (x - pd.Timedelta(days=2)).is_year_start:
                expected.append(True)
            else:
                expected.append(False)
    assert result == expected
```
then it does indeed pass

I think we should get https://github.com/pandas-dev/pandas/pull/57494 in first though, as I think that that also fixes the issues "for free" (but then we keep the test from this one)

**Comment by natmokval** [comment]
> I think we should get #57494 in first though, as I think that that also fixes the issues "for free" (but then we keep the test from this one)
>
thanks, I will update this PR after we get the #57494 in.

**Comment by natmokval** [comment]
@MarcoGorelli, I updated this PR, could you please take a look at my changes?

**Review by MarcoGorelli — APPROVED** [review]
thanks @natmokval !

**Pull request merged**
