### PR TITLE
BUG: Replace on Series/DataFrame stops replacing after first NA

### LINKED ISSUE #56599: BUG: DataFrame.replace with regex on `StringDtype` column with NA values stops replacing after first NA
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'old': ['my', 'test', pd.NA, 'word', 'to', 'replace']}, dtype="string")
# In [3]: df
# Out[3]:
#        old
# 0       my
# 1     test
# 2     <NA>
# 3     word
# 4       to     
# 5  replace

 df['old'].replace(regex={r't.*': 'replaced'})
# Out[4]:
# 0          my
# 1    replaced
# 2        <NA>
# 3        word
# 4          to    <---- *** should have replaced this one ***
# 5     replace
# Name: old, dtype: string

df['old'].astype('object').replace(regex={r't.*': 'replaced'})
# Out[5]:
# 0          my
# 1    replaced
# 2        <NA>
# 3        word
# 4    replaced  <---- *** properly replaced***
# 5     replace
# Name: old, dtype: object
```

### Issue Description

Hi, thank you for pandas ❤🙏

When using regex, [`pandas.DataFrame.replace`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html) on a [StringDtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.StringDtype.html#pandas.StringDtype) column containing `pd.NA` values, the replacement stops after the first `pd.NA` value is met.

The problem doesn't occur when using the `object` dtype.

### Expected Behavior

I would expect the replacement to ignore NA values and still replace all matching values for both the `object` and the `StringDtype` dtypes.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.133.1-microsoft-standard-WSL2
Version             : #1 SMP Thu Oct 5 21:02:42 UTC 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : C.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.2
pip                 : 23.3.1
Cython              : None
pytest              : 7.4.3
hypothesis          : None
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.18.1
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.12.2
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 10.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : 2023.12.2
scipy               : 1.11.4
sqlalchemy          : 2.0.23
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

### PR DESCRIPTION
**Pull request by asishm**
- [x] closes #56599
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

The issue was the line `a = a[mask]` was triggered only for `ndarray` and doesn't hit when `dtype='string'`, but the `np.place` logic applied as long as the result was an `ndarray`.

The old behavior had things like (depending on the number and location of NAs)

```py
In [2]: s = pd.Series(['m', 'm', pd.NA, 'm', 'm', 'm'], dtype='string')

In [3]: s.replace({'m': 't'}, regex=True)
Out[3]:
0       t
1       t
2    <NA>
3       m
4       t
5       t
dtype: string

In [4]: s = pd.Series(['m', 'm', pd.NA, pd.NA, 'm', 'm', 'm'], dtype='string')

In [5]: s.replace({'m': 't'}, regex=True)
Out[5]:
0       t
1       t
2    <NA>
3    <NA>
4       m
5       m
6       t
dtype: string

In [6]: s = pd.Series(['m', 'm', pd.NA, 'm', 'm', pd.NA, 'm', 'm'], dtype='string')

In [7]: s.replace({'m': 't'}, regex=True)
Out[7]:
0       t
1       t
2    <NA>
3       m
4       t
5    <NA>
6       t
7       m
dtype: string
```

### CODE REVIEW

**Comment by asishm** [comment]
pre-commit.ci autofix

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @asishm

**Comment by rhshadrach** [comment]
Along with other string type fixes, I think it'd be good to backport this to 2.3.x. Any objection @mroeschke @jorisvandenbossche?

**Comment by mroeschke** [comment]
No objection from me

**Comment by rhshadrach** [comment]
@MeeseeksDev backport to 2.3.x

**Comment by jorisvandenbossche** [comment]
@rhshadrach I see there is commit linking to this PR, but not an actual open PR. Did you start backporting but didn't finish? (I was just planning to backport this one, but want to avoid double work)

**Comment by jorisvandenbossche** [comment]
Ah, I see this is already applied to the 2.3.x branch in https://github.com/pandas-dev/pandas/commit/8d1cc9088d358a4fb364a0a75fa4fed834211e21 (just not through a PR, and now I remember you mentioning you did an accidental push to 2.3.x). 
So no need to backport anymore. Reminder to try to think about removing the label (and ideally referencing the backport PR/commit, so things can be tracked later if needed)

**Pull request merged**
