### PR TITLE
Add odo to ecosystem docs

### LINKED ISSUE #244: DOC: add issues & pandas links
- see questions like this from [SO](http://stackoverflow.com/questions/30372960/how-to-store-pandas-dataframe-to-mongodb). Ideally should put a link for sure [here](http://pandas.pydata.org/pandas-docs/stable/ecosystem.html) and maybe in [here](http://pandas.pydata.org/pandas-docs/stable/io.html)

- I couldn't find an issues link on [odo docs](http://odo.readthedocs.org/en/latest/) e.g. pointing to [issues]( https://github.com/ContinuumIO/odo/issues)

### PR DESCRIPTION
**Pull request by cpcloud**
closes ContinuumIO/odo#244

### CODE REVIEW

**Comment by cpcloud** [comment]
@jreback ok with this?

**Comment by jreback** [comment]
lgtm

**Comment by shoyer** [comment]
looks good to me, too

**Comment by cpcloud** [comment]
thanks guys, merging

**Pull request merged**
