### PR TITLE
STY: proposed isort settings [ci skip] [skip ci] [ciskip] [skipci]

### PR DESCRIPTION
**Pull request by jbrockmendel**
(not sure which tag(s) skip the CI)

I propose we change the isort settings to arrange within-pandas imports by dependency structure.  i.e. 

- `pandas._libs`, `pandas.compat`, `pandas.util._*`, `pandas.errors` are for the most part not dependent on pandas.core, so get their own section(s)
- `pandas.core.dtypes` for the most part does not depend on the rest of `pandas.core`, so it goes next
- then the rest of `pandas.core`
- then pandas non-core: `pandas.io`, `pandas.plotting`, `pandas.tseries`

Within blocks I propose we stick to alphabetical ordering.  e.g. right now in `core.series` we have import `pandas.core.indexes.base as ibase` 35 lines away from all the other `pandas.core.indexes` imports.  These should be adjacent.

The main thing I'd still like to fix/improve is that in this PR isort is failing to put `from pandas import compat` with the other `pandas.compat` imports.

Putting the trailing parentheses on the same line as the imports instead of a separate line is less important, but I prefer it because it makes it cleaner when I wrap lines in sublimetext.  Happy to revert that if it is a sticking point.

### CODE REVIEW

**Comment by jreback** [comment]
this is going to massively change the in-progress isort cleanups no?

**Comment by jreback** [comment]
ok does this break anything i the current build?

**Comment by jbrockmendel** [comment]
>ok does this break anything i the current build?

Yes, a bunch of files.  If this format is agreed upon, I can either add those back to the ignore list in setup.cfg or go through and fix them all in one swoop now.

**Comment by jreback** [comment]
either ok

**Comment by jbrockmendel** [comment]
updated, now passes `isort -rc pandas`

**Comment by jreback** [comment]
thanks @jbrockmendel let's hope this works :>

**Comment by alimcmaster1** [comment]
I like this alot - thanks @jbrockmendel ! I did actually try this myself since you requested it back in #23048 . But isort seemed to produce non-deterministic sort for me. But I think i wasn't sorting within sections like you added `force_sort_within_sections=True`

**Comment by jorisvandenbossche** [comment]
One disadvantage is that it will be harder to know how to correctly do the imports manually, so I think we need to explain the logic in the guidelines (@alimcmaster1 if you can do that in https://github.com/pandas-dev/pandas/pull/23364, that would be great)

**Comment by alimcmaster1** [comment]
Sure happy to @jorisvandenbossche , but I hope most people  will use isort to sort imports opposed to doing so manually

**Comment by jorisvandenbossche** [comment]
Yes, but still, if I just need to add an import to an already correctly sorted file, I think it is nice to know how to do this correctly instead of each time to have to run isort after making a small change (although you could maybe configure your editor to do so, or with a git commit hook)

**Pull request merged**
