### PR TITLE
DEPR: df.iloc[:, foo] = bar attempt to set inplace

### LINKED ISSUE #44353: BUG/API: DataFrame.iloc[:, foo] = bar inplaceness?
In 1.3.0 we made it so that `df["A"] = foo` *never* operates in-place (xref [whatsnew](https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v1.3.0.rst#never-operate-inplace-when-setting-framekeys--values),  #33457) and *mostly* made it so that `df.loc[foo, bar] = baz` tries to operate in-place before falling back to casting (xref [whatsnew](https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v1.3.0.rst#try-operating-inplace-when-setting-values-with-loc-and-iloc), https://github.com/pandas-dev/pandas/issues/33457#issuecomment-660126628)

There are some remaining cases where .iloc and .loc do not try to set inplace.  This issue is to make sure we have consensus about changing/deprecating that behavior.  Most of the impacted test cases involve doing an astype, e.g.

```
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(4).reshape(2, 2), dtype=object)
df.iloc[:, 0] = df.iloc[:, 0].astype(np.float64)
```

ATM this changes df[0] to float64, i.e. is not inplace.

In this case, the user could/should do `df[0] = df[0].astype(np.float64)`.  But that approach runs into problems with either non-unique columns or setting a slice of columns `df.iloc[:, :2] = foo`

My thoughts are that 1) we should be consistent about inplace-ness, not special-case the API and 2) the use case here _is_ convenient.

Thoughts?

<b>update</b> Cataloguing issues/PRs where this behavior we implemented apparently-intentionally
#29393 (#25495)
#6149
#6159  BUG/API: df['col'] = value and df.loc[:,'col'] = value are now completely equivalent

<b>update 2</b> Cataloguing issues that appear to be caused by/related to this inconsistency
#20635 BUG: indexing with loc and iloc with list-likes and new dtypes do not change from object dtype
#24269 DataFrame.loc/iloc fails to update object with new dtype

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #44353
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase

**Comment by jbrockmendel** [comment]
Made a couple of efforts recently to simplify the `iloc.__setitem__` and they all crash on the rocks of this inconsistency.

**Comment by jbrockmendel** [comment]
There's a problem here in that the `use .iloc(axis=1)[foo]=bar` won't actually work, so still need a better alternative.

But getting this done should be a very high priority for 1.5 as its a blocker for all kinds of inconsistency-fixing.

**Comment by jbrockmendel** [comment]
@jreback in the Feb call i think we agreed to move forward with this but there was some bikeshedding over the name of the replacement method.  Do you remember what we landed on?

**Comment by jreback** [comment]
> @jreback in the Feb call i think we agreed to move forward with this but there was some bikeshedding over the name of the replacement method. Do you remember what we landed on?

`isetitem` I *think*

**Comment by jbrockmendel** [comment]
> `isetitem` I think

cool, since thats what the PR implements ATM

**Comment by jbrockmendel** [comment]
@jreback gentle ping, finally green

**Comment by jreback** [comment]
thanks @jbrockmendel yeah has been out here for a while :->

followup, i think we need `.isetitem` in the api docs (and maybe a mention in the indexing.rst as well)

**Pull request merged**
