### PR TITLE
DOC: Modify validate_rst_title_capitalization.py script

### PR DESCRIPTION
**Pull request by cleconte987**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks for this @cleconte987 

Can you please explain what you are proposing here, and why? It's difficult to review without referencing an issue, or providing a description.

My understanding from your other PR is that we wanted to add a lot of keywords to the list of accepted keywords. I guess this is related, but not sure why you think this is a better approach.

**Comment by cleconte987** [comment]
Sorry I didn't put any information, I didn't opened or referenced an issue.

Yes it is related to the other PR. What I wanted to do was to not remove uppercases from words which are proper nouns. From what I understand, all words with two or potentially more uppercase letters are proper nouns and should be kept as is. So the snippet's aim is to separate words which have 2 or more uppercase letters from others, and to only lower the second ones.

**Comment by datapythonista** [comment]
So, if I understand correctly, with this change, if I write `PANDAS`, `FooBar` or whatever with more than two upper cases, it will be considered valid, right?

I'm personally -1 on this, I would prefer to be explicit on what we accept and we don't. I think the list of exceptions is big, but still ok.

**Comment by cleconte987** [comment]
> So, if I understand correctly, with this change, if I write `PANDAS`, `FooBar` or whatever with more than two upper cases, it will be considered valid, right?
> 
> I'm personally -1 on this, I would prefer to be explicit on what we accept and we don't. I think the list of exceptions is big, but still ok.

Yes exactly, words like `PANDAS` and `FooBar` will be considered valid. But they still be changed in the end by the correct spelling from CAP_EXCEPTIONS_DICT if they belong to it.

Ok I will add elements to CAPITALIZATION_EXCEPTIONS then

**Comment by datapythonista** [comment]
Can you add them in the other PR for now, and leave this open?

@WillAyd what do you think about this? Feels like making things too complicated, but may be it's a good idea.

**Comment by cleconte987** [comment]
Ok sure.

I will add them meanwhile right

**Comment by cleconte987** [comment]
Wouah I accidentally deleted my remote branch on GitHub and closed the PR :/
Sorry for that

**Comment by cleconte987** [comment]
I will reopen one

**Pull request closed without merging**
