### PR TITLE
BUG: issubclass check with dtype instead of type, closes GH#24883

### LINKED ISSUE #24883: Pandas dataframe eval
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
Scenario 1:

df2=pd.DataFrame({'a1':[10,20]})

df2.eval("c=((a1>10) & True )")
Out[8]: 
   a1      c
0  10  False
1  20   True
Scenario 2:
df2=pd.DataFrame({'a1':['Y','N']})
df2.eval("c=((a1 == 'Y') & True )")
Traceback (most recent call last):

TypeError: issubclass() arg 1 must be a class






```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]
By changing datatype of a column from int to str, pd.eval throws "TypeError: issubclass() arg 1 must be a class" 

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
In Scenario 2

 a1      c
  10  True
 20   False

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.21.1
pytest: 3.0.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.14.2
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.9
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #24883
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
lgtm, can you add a whatsnew note.

**Comment by jbrockmendel** [comment]
updated+green

**Comment by simonjayhawkins** [comment]
milestone 1.2 whatsnew 1.1.2 do you want this backported?

**Comment by jbrockmendel** [comment]
i think so yes

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.1.x

**Pull request merged**
