### PR TITLE
HTML Parsing Cleanup

### PR DESCRIPTION
**Pull request by cancan101**
- Can pass `Flavor` to HTML parse (closes #4594 and #5130). Instead of #5131
- Cleanup API for HTML parsers

I added new (public class) `Flavor` which users can subclass. Currently the expectation is to pass in the class (not an instance of the class)

CC @cpcloud @jtratner @jreback

### CODE REVIEW

**Comment by gliptak** [comment]
Some folks brave decided to carve it out. https://github.com/pydata/pandas-datareader/issues/148

**Comment by cancan101** [comment]
@gliptak I looked over the project that you referenced, but it doesn't seem to have the HTML parsing factored out.

**Comment by gliptak** [comment]
@cancan101 In https://github.com/pydata/pandas/issues/5404 I proposed to replace bs4/lxml/html5lib with http://phantomjs.org/ (I completed a limited local refactoring, no patch was uploaded). In https://github.com/pydata/pandas/issues/5404 it was stated that HTML scraping is not a goal for https://github.com/pydata/pandas With the separation of https://github.com/pydata/pandas-datareader maybe DataReader could have its HTML scraping strengthened.

As per https://github.com/pydata/pandas-datareader/issues/148 http://phantomjs.org/ discontinued Python support so now http://jeanphix.me/Ghost.py/ would be a better choice.

There are several other issues opened around this like https://github.com/pydata/pandas-datareader/issues/171

**Comment by jreback** [comment]
@gliptak the way to go about this is to create a package where you expose an interface. once stable, pandas could offload this type of parsing to your package (which would then become an optional dep), your package could have whatever deps you want. of course cross-platform is best! good luck.

**Comment by gliptak** [comment]
These files reference ```lxml|html5lib|bs4```:

    ./pandas/io/tests/test_data.py
    ./pandas/io/tests/test_excel.py
    ./pandas/io/tests/test_html.py
    ./pandas/io/data.py
    ./pandas/io/html.py

```data.py``` is deprecated to ```pandas-datareader```. Is ```html.py``` also planned to be moved?

Thanks

**Comment by jreback** [comment]
no, unless/until it is spun off to
pandas-htmlreader (or could be another name)
where we could deprecate and just use the new library

**Comment by gliptak** [comment]
@jreback I separated pandas-htmlreader as

https://github.com/gliptak/pandas-htmlreader

The build works for ``` PYTHON=3.5 PANDAS=0.17.1```:

https://travis-ci.org/gliptak/pandas-htmlreader/jobs/115686777

Please review and let me know if there is an interest to move forward with this. Thanks

**Comment by jreback** [comment]
@gliptak looks interesting. So the key would be a version that is a complete drop-in replacement for pandas (IOW doesn't require ANYTHING beyond what the current version does). You can't depend on ``requests`` for example.

That's the initial version (say 1.0), but then you can feel free to branch off in (1.1) or whatever and do whatever you'd like, keeping in mind that a compat API is good.

**Comment by gliptak** [comment]
I removed the ```requests`` dependencies (they came over from ```pandas-datareader```):

https://github.com/gliptak/pandas-htmlreader
https://travis-ci.org/gliptak/pandas-htmlreader

```lxml|html5lib|bs4``` dependencies are not indicated ...

(PS Instead of starting from an initial commit, I could overlay this on ```pandas``` source tree to keep additional history)

**Comment by jreback** [comment]
no that's fine the key is to have the same exact API as current

**Comment by gliptak** [comment]
@jreback Any directions on how to move forward with this? Should I open a new issue? Thanks

**Comment by jreback** [comment]
yes, you can open a new issue. To be clear this will have to be a drop-in replacement.

**Comment by jreback** [comment]
best if you can make your replacement completely work (in your namespace), then we can migrate the namespace to ``pydata/pandas-htmlreader``. you then publish a 1.0. which can then be incorporated in pandas at some point.

**Pull request closed without merging**
