### PR TITLE
Debug 38 build

### PR DESCRIPTION
**Pull request by WillAyd**
Seeing if this helps with 38 build hanging until something more permanent comes along

@TomAugspurger @jorisvandenbossche

### CODE REVIEW

**Comment by WillAyd** [comment]
Adding a verbose flag seemed to work here. I *think* the issue is just that there is no output coming from setup.py during install and it takes over 10 minutes. We could roll with this and see how it goes (knowing this is a temporary build solution anyway) or look into global settings, though I doubt we care to increase timeouts for other builds:

https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

**Comment by jbrockmendel** [comment]
makes sense, lgtm

**Comment by jbrockmendel** [comment]
@TomAugspurger thoughts?  might fix the travis 38 builds

**Review by TomAugspurger — APPROVED** [review]

**Comment by TomAugspurger** [comment]
Thanks @WillAyd!

**Pull request merged**
