### PR TITLE
BUG: DataFrame.floordiv(ser, axis=0) not matching column-wise bheavior

### PR DESCRIPTION
**Pull request by jbrockmendel**
We're pretty close to being able to combine _combine_frame and _combine_match_index (and hopefully get rid of them both before long)

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by WillAyd** [comment]
Is this an outstanding bug or just a test coverage gap? If former probably worth a whatsnew

**Comment by jbrockmendel** [comment]
> Is this an outstanding bug or just a test coverage gap? If former probably worth a whatsnew

Bug, will add whatsnew

**Comment by jreback** [comment]
great thanks

**Pull request merged**
