### PR TITLE
CLN: Remove python2-style longs in regexes

### PR DESCRIPTION
**Pull request by topper-123**
- [x] xref #25725

Minor cleanup: Cleanup some regexes that guard against python2 style longs in their error messages.

### CODE REVIEW

**Comment by topper-123** [comment]
The failures are unrelated: 

```
Exception: Cython-generated file 'pandas\_libs/algos.c' not found.
                    Cython is required to compile pandas from a development branch.
                    Please install Cython or download a release package of pandas
```

**Comment by gfyoung** [comment]
@topper-123 : The issue actually traces to `conda` being unable to create the `pandas-dev` environment that we use for testing:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=11274

Not sure why Windows is not liking the YAML.  It hasn't been touched since end of March.

**Comment by topper-123** [comment]
Ok, I'll push again, maybe it was something intermittent on the servers.

**Comment by topper-123** [comment]
No, already failed. Strange...

**Comment by jreback** [comment]
looks ok; waiting on resolution of CI issues.

**Comment by topper-123** [comment]
This passes now.

**Comment by jreback** [comment]
thanks @topper-123

**Pull request merged**
