### PR TITLE
API: value_counts consistently return int64 dtype

### LINKED ISSUE #44679: API: value_counts with nullable dtype should return np.int64 like everything else
ATM these are special-cased to return Int64 (i.e. nullable) instead of np.int64.  But the result of value_counts will never have any NAs, so there is no benefit.  It complicates the code, complicates the API, and prevents us from sharing tests.

These should return np.int64 dtype like everything else.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #44679
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
Let's first discuss this further at https://github.com/pandas-dev/pandas/issues/44679

**Comment by jreback** [comment]
when was the change added to make these EA types in the first place, was it for 1.4?

**Comment by jorisvandenbossche** [comment]
This is already the behaviour since at least 1.0

**Comment by jreback** [comment]
> This is already the behaviour since at least 1.0 (checked it for Int64 for that version)

ahh then this would be hard to change actually (as its the return type)

**Comment by jbrockmendel** [comment]
> ahh then this would be hard to change actually (as its the return type)

its all still marked as experimental

**Comment by jbrockmendel** [comment]
no apparent interest here, closing.

**Pull request closed without merging**
