### PR TITLE
travis deduping on prs

### LINKED ISSUE #12438: BLD: Travis dedup via webhooks
Came across this just now https://github.com/grosser/travis_dedup
It sounds like it cancels old builds on a PR.  It works via github webhooks.

### PR DESCRIPTION
**Pull request by jreback**
closes #12438

### CODE REVIEW

**Comment by jreback** [comment]
ok, in theory this should work :>

I have a test commit up and the original PR. when the original runs it should cancel almost immediately (not 100% sure the osx build will work as this relies on the system python, but will see)

**Comment by jreback** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/213816512

success!

**Comment by jorisvandenbossche** [comment]
Cool!

**Comment by jreback** [comment]
you also may notice that builds now take about 2hrs when in full-caching. so if extensions are rebuilt then this goes up to about 3. and when I touch ci/* it deletes the cache for 2 builds :< (and thus takes about 3 as well )

**Pull request closed without merging**
