### PR TITLE
DOC: fix Series.reset_index example

### PR DESCRIPTION
**Pull request by philngo**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Show correct values in idx column.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks! Do you have any interest in updating the example right below that in the docstring so that the doctest passes? `pytest --doctest-modules pandas/core/series.py  -k reset_index` currently fails since we use random numbers for the next one. I think if you did `s2 = pd.Series(range(8),  index=...)` and updated the example, things should pass.

**Comment by philngo** [comment]
Sure, I'll make the change.

**Comment by philngo** [comment]
Not sure if I'm missing a doctest gotcha here, but I still get the following output. Probably a simple fix but I don't see it.

`$ pytest --doctest-modules pandas/core/series.py -k reset_index`

```
============================================== FAILURES ===============================================
___________________________ [doctest] pandas.core.series.Series.reset_index ___________________________
1029
1030         >>> arrays = [np.array(['bar', 'bar', 'baz', 'baz', 'foo',
1031         ...                     'foo', 'qux', 'qux']),
1032         ...           np.array(['one', 'two', 'one', 'two', 'one', 'two',
1033         ...                     'one', 'two'])]
1034         >>> s2 = pd.Series(
1035         ...     range(8),
1036         ...     index=pd.MultiIndex.from_arrays(arrays,
1037         ...                                     names=['a', 'b']))
1038         >>> s2.reset_index(level='a')
Differences (unified diff with -expected +actual):
    @@ -1,4 +1,4 @@
            a  0
    -b
    +b
     one  bar  0
     two  bar  1
```

**Comment by TomAugspurger** [comment]
That is indeed a doctest gotcha. I think it's wanting some whitespace after the `b` and below the column names. Added https://github.com/pandas-dev/pandas/issues/19934 to talk about how to handle that.

This looks good to me. Will merge once appveyor is finished (let us know if you see that it's done).

**Comment by philngo** [comment]
Great, thanks! @TomAugspurger Looks like appveyor finished.

**Comment by jorisvandenbossche** [comment]
@philngo Thanks a lot!

**Pull request merged**
