### PR TITLE
CLN: period boundscheck warnings

### PR DESCRIPTION
**Pull request by chris-b1**
follow up to fix warnings in https://github.com/pydata/pandas/pull/11263#issuecomment-149641296

### CODE REVIEW

**Comment by jreback** [comment]
gr8. ping on green.

**Comment by jreback** [comment]
repush as conda had some issues

**Comment by chris-b1** [comment]
@jreback - this is passing now

**Comment by jreback** [comment]
thanks!

**Comment by jreback** [comment]
@chris-b1 if you'd do one more ....thanks!

```
cythoning pandas/tslib.pyx to pandas/tslib.c
warning: pandas/tslib.pyx:4257:25: Use boundscheck(False) for faster access
warning: pandas/tslib.pyx:4258:26: Use boundscheck(False) for faster access
warning: pandas/tslib.pyx:4260:56: Use boundscheck(False) for faster access
warning: pandas/tslib.pyx:4261:22: Use boundscheck(False) for faster access
warning: pandas/tslib.pyx:4275:25: Use boundscheck(False) for faster access
warning: pandas/tslib.pyx:4276:26: Use boundscheck(False) for faster access
warning: pandas/tslib.pyx:4278:56: Use boundscheck(False) for faster access
warning: pandas/tslib.pyx:4279:22: Use boundscheck(False) for faster access
```

**Pull request merged**
