### PR TITLE
Revert "REF: use astype_nansafe in Index.astype"

### LINKED ISSUE #38607: REGR: astype(str) of object array with byte objects
On released version, we see this behaviour:

```
In [1]: idx = pd.Index(['あ', b'a'], dtype='object')

In [2]: idx
Out[2]: Index(['あ', b'a'], dtype='object')

In [4]: idx.astype(str)
Out[4]: Index(['あ', 'a'], dtype='object')
```

So where the `bytes` object `b"a"` gets converted to the string `"a"`.

On master (since a few days), however, we now get:

```
In [7]: idx.astype(str)
Out[7]: Index(['あ', 'b'a''], dtype='object')
```

so where the `bytes` object gets converted to the string `"b'a'"`

Possibly due to https://github.com/pandas-dev/pandas/pull/38518 cc @jbrockmendel

### PR DESCRIPTION
**Pull request by simonjayhawkins**
Reverts pandas-dev/pandas#38518

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
may also close #38592, see https://github.com/pandas-dev/pandas/issues/38592#issuecomment-748691750

**Comment by jreback** [comment]
this is for 1.3?

**Comment by jreback** [comment]
@jbrockmendel ok here ?

**Comment by jbrockmendel** [comment]
Yep

**Comment by simonjayhawkins** [comment]
> may also close #38592, see [#38592 (comment)](https://github.com/pandas-dev/pandas/issues/38592#issuecomment-748691750)

hmm, maybe not.

```
       before           after         ratio
     [d3c52e4a]       [15daa4c5]
     <master>         <revert-38518-ref-astype-index>
-        9.82±1ms       7.09±0.1ms     0.72  stat_ops.FrameOps.time_op('sem', 'Int64', 0)

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```

**Comment by jreback** [comment]
thanks @simonjayhawkins 

@jbrockmendel might want to rebase any PRs which touch this

**Pull request merged**
