### PR TITLE
BLD: Fix regex in arm64 wheel builders

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by phofl** [comment]
They are still building here, probably still buggy?

**Comment by lithomas1** [comment]
> They are still building here, probably still buggy?

They still go, but exit early. There's no way to skip them conditionally once the job has started.

**Comment by phofl** [comment]
Ah so there is no way to skip them completely like gha?

**Comment by lithomas1** [comment]
> Ah so there is no way to skip them completely like gha?

Unfortunately not. The only thing that I can skip on (before the job starts) is branches.

**Comment by lithomas1** [comment]
Looks like this works so I'm just going to put it in.

**Comment by phofl** [comment]
Thx

**Pull request merged**
