### PR TITLE
TST: xfail gbq & feather tests for now as version incompat

### PR DESCRIPTION
**Pull request by jreback**
need to revert these when fixed
https://travis-ci.org/pandas-dev/pandas/builds/444265455

### CODE REVIEW

**Comment by jreback** [comment]
cc @tswast is this a newer pandas-gbq?

**Review by tswast — APPROVED** [review]
Sorry about that. I removed these methods in https://github.com/pydata/pandas-gbq/pull/216 (I thought they were unused.) Since listing datasets while you are deleting them is flakey, I updated the pandas-gbq tests in that PR to use a fixture to create a random dataset and delete it when the test finishes.

**Comment by jreback** [comment]
ok that's fine. can you PR to pandas to fix this up?

**Comment by tswast** [comment]
PR for gbq tests: https://github.com/pandas-dev/pandas/pull/23303

**Pull request merged**
