### PR TITLE
WEB: Update sponsors in website

### PR DESCRIPTION
**Pull request by datapythonista**
Still waiting for the logos of the new sponsors, and final confirmation that we want to replace Ursa Labs by Voltron, but opening early in case there is feedback.

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
Can probably add Nvidia, will confirm and find what image to use

```
  - name: "Nvidia"
    url: https://www.nvidia.com
    logo:  # TODO pending
    kind: partner
    description: "Matthew Roeschke"
```

**Comment by datapythonista** [comment]
> Can probably add Nvidia, will confirm and find what image to use

I forgot about Nvidia, sorry. Thanks for the heads up, added it now.

**Comment by datapythonista** [comment]
This should be ready now. This is how the home page look with the new sponsors:

Screenshot at 2022-07-22 12-08-47

@mroeschke I found the nvidia logo online, I think it should be fine.

I watched @jreback recent talk, and I'm wondering whether we should also add USC (who sponsored @jbrockmendel to work on the non-nanosecond stuff via Quansight), and NASA (I don't know much about that grant). No strong opinion, but if we add them let's do it in a follow up PR, since getting the logos takes a while and this is ready now.

**Comment by mroeschke** [comment]
> @mroeschke I found the nvidia logo online, I think it should be fine.
 
Thanks. I am still inquiring within my company to get approval, but if you'd like to merge this and add Nvidia's logo (and the others) in a followup I would be fine with that

**Comment by datapythonista** [comment]
I'll split this in two and have nvidia in a separate PR, so we can get the rest merged, and nvidia is ready for whenever the decision is made. Thanks for letting me know.

**Comment by mroeschke** [comment]
@datapythonista I just got approval now that the Nvidia logo usage is good!

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
