### PR TITLE
REGR: sample modifying `weights` inplace

### PR DESCRIPTION
**Pull request by mzeitlin11**
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Targeting 1.4 and no whatsnew since only a regression on master.

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Review by KrishnaSai2020 — APPROVED** [review]
Appears to be fine.

**Comment by jreback** [comment]
looks fine can you add a whatsnew note (1.4) reshaping is fine & ping on green.

**Comment by mzeitlin11** [comment]
> looks fine can you add a whatsnew note (1.4) reshaping is fine & ping on green.

Didn't include a whatsnew because it is only a regression on master caused by #42233

**Comment by jreback** [comment]
> > looks fine can you add a whatsnew note (1.4) reshaping is fine & ping on green.
> 
> Didn't include a whatsnew because it is only a regression on master caused by #42233

kk cool

**Comment by jreback** [comment]
thanks @mzeitlin11

**Pull request merged**
