### PR TITLE
Remove isort dep

### LINKED ISSUE #26661: CI: Remove isort from CI dependencies
In #25455 we added `isort` as a dependency to all our builds. Looks like the CI was failing, and adding `isort` fixed the problem. Not sure what the problem is, but `isort` is something we should only have in `environment.yml`, as it's only used in `ci/code_checks.sh` and locally.

We should remove `isort` from all files in `ci/deps/` and if the CI complains, find out what's the problem, and fix it.

### PR DESCRIPTION
**Pull request by alimcmaster1**
#LondonPythonSprints

  - [x] closes #26661
  - [x] tests added / passed
 - [x] passes git diff upstream/master -u -- "*.py" | flake8 --diff

cc @datapythonista

### CODE REVIEW

**Comment by alimcmaster1** [comment]
closed and re-opened the PR since Travis doesn't seem to run on draft PRs

**Comment by jreback** [comment]
so we don't actually need isort in *any* of the ci/* .yml files, only in environment.yml, can you remove to all.

**Comment by alimcmaster1** [comment]
yep sorry added the ones I missed thanks @jreback

**Comment by jreback** [comment]
thanks !

**Comment by jreback** [comment]
hmm one more:
```ci/deps/travis-36-doc.yaml:  - isort```

**Comment by alimcmaster1** [comment]
aah! https://github.com/pandas-dev/pandas/pull/26741

**Pull request merged**
