### PR TITLE
adding convert_cell to read_excel

### LINKED ISSUE #49872: ENH: read_excel: Add a callable to access the Cell before getting the value
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

In pandas.read_excel it's not possible to access information about the cell object before converting to dataframe. In some cases as in [#47269](https://github.com/pandas-dev/pandas/issues/47269),[#46895](https://github.com/pandas-dev/pandas/issues/46895), and #49770 it's necessary to acces the cell, especially number_format to change the values

### Feature Description

Add a new parameter to read_excel, something like value_of_cell, that receive a cell and return a value. In my case i change _convert_cell in _openpyxl to:
```
def _convert_cell(self, cell, convert_float: bool, value_of_cell:Union[None, Callable]) -> Scalar:
        from openpyxl.cell.cell import (
            TYPE_ERROR,
            TYPE_NUMERIC,
        )
        if cell.value is None:
            return ""  # compat with xlrd
        elif cell.data_type == TYPE_ERROR:
            return np.nan
        elif value_of_cell is not None: # this is new
            return value_of_cell(cell) # this is new
        elif cell.data_type == TYPE_NUMERIC:
            # GH5394, GH46988
            if convert_float:
                val = int(cell.value)
                if val == cell.value:
                    return val
            else:
                return float(cell.value)
        return cell.value
```

so in my code i call
```
def conv(cell):
            if cell.number_format.startswith("0"):
                return "0" * (len(cell.number_format) - len(str(cell.value))) + str(cell.value)
            else:
                return cell.value
 df = pd.read_excel(file, header=None, na_filter=False, dtype=str, value_of_cell:=conv)
```

 
 
 of course is neccesary to edit all the calls from read_excel to _convert_cell ( i think is something like 10 functions), but i will create a pull request if can pass the test. I hope this is useful for the community

### Alternative Solutions

Another option is to use openpyxl directly as, but loss the extra functions of read_excel and more code is needed:
```
        document = load_workbook(file)
        sheet = document.active
        for row in sheet:
            for cell in row:
              cell.value = value_of_cell(cell)
        df = pd.DataFrame(sheet.values)
        df = df.fillna('')
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Polandia94**
- [x ] closes #49872
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
there is already a converters arg

how is this different?

**Comment by Polandia94** [comment]
The converters do the convertion after the reading (i'm not sure of that) and doesn't have access to the cell format. 
In my case i have a  convert a cell with the number 2345, with numeric_format 00000 to the string '02345'. In Excel you see this as a number with leading zeros, wich isn't valid python. If a use a converter i will convert the number 2345 to the string '2345'.
I'm working normalizing financial documents, and in a lot of cases they use format as a data, for example another color for negative numbers(not as condicional, as simple formatted), and things like that.

**Comment by Polandia94** [comment]
I don't know if this is useful for a lot of people. Another option, less agressive is just add in the read_excel documentation an explanation that, in the case you want to access cell format you have to override _convert_cell(cell). I'm new in the community, is better have the discussion of the pertinence of the request in the pull request, the issue or the slack?

**Comment by phofl** [comment]
Discussion should be on the issue. Please wait with an implementation until there is agreement

**Comment by mroeschke** [comment]
Thanks for the pull request, but agreed before moving forward with a PR discussion is needed in the original issue first, so closing until a decision has been made there

**Pull request closed without merging**
