### PR TITLE
CLN: Remove unused code

### PR DESCRIPTION
**Pull request by tqa236**

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @tqa236 

I guess the CI failure is unrelated, but if you can have a look...

**Comment by tqa236** [comment]
Hi Marc, I think it's indeed unrelated and it's also beyond my understanding to debug it as well.

Just FYO, Matthew is debugging it here: https://github.com/pandas-dev/pandas/pull/57845

**Comment by datapythonista** [comment]
Thanks. Yes, I meant to have a look to make sure it's unrelated.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @tqa236

**Pull request merged**
