### PR TITLE
[TST] Fix test_quantile_interpolation_int

### PR DESCRIPTION
**Pull request by makbigc**
Follow up https://github.com/pandas-dev/pandas/pull/26556#discussion_r289056741

### CODE REVIEW

**Comment by WillAyd** [comment]
Based off test name it looks like the TODO comment here is to add `interpolation='linear'` to q1 - any reason not to do that instead of removing?

@simonjayhawkins

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
@WillAyd That's correct, the bad test needs fixing, not the code removing.

**Review by gfyoung — APPROVED** [review]
@simonjayhawkins if you can have a look

**Review by WillAyd — APPROVED** [review]
lgtm as well merge when satisfied @simonjayhawkins

**Review by simonjayhawkins — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
Thanks @makbigc

**Pull request merged**
