### PR TITLE
DOC: Splitting api.rst in several files

### LINKED ISSUE #24451: DOC: Split api.rst in sections
The pandas API reference page is huge. Which makes it difficult for users to find information, and for us to edit.

Given the size of the page, I think it'd make more sense to split the current page `api.rst` into different pages, one per section:
- `api/series.rst`
- `api/functions.rst`
- ...

The document is already divided into sections, I think the current division would make sense with few changes:
- Input/Output
- General functions
- Series
- DataFrame
- Panel
- Index (will include all the Index classes/section in the top level of `api.rst`)
- Scalars
- Date Offsets and Frequencies
- Window
- GroupBy
- Resampling
- Style
- Plotting
- General utility functions
- Extensions

Does anybody think a single page is better? Any other division you think of?

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #24451
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

@TomAugspurger do you know why moving the api `autosummary` to a directory, make the build not find the generated files? For what I understand, the `:toctree: generated/` is used for both, to know where to generate the API files, and later on to link them. But it looks like they are generated in `generated/`, but then I get warnings because sphinx is looking for them in `api/generated/`.

There was something a bit tricky in the `autosummary_generate` option that I removed in #24428 (it's not yet merged), but I don't see anything in the configuration that can be causing this behavior (and I've seen other projects using autosummaries in directories without problems, like https://github.com/bradgwest/esof523a3/tree/master/doc/reference).

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I'm not sure what would be wrong with the autosummary. Your description sounds correct.

**Comment by datapythonista** [comment]
This is looking good now, I think it can be merged. In this PR I just did the splitting without making any other change (more than standardizing blank lines, and the currentmodule directive).

A small change to the validation script was needed to keep it working, which is implemented here (at the very end of the changes).

In a follow up I'll propose changes to the titles of some pages, but I don't want to implement them here, as this is difficult to review, and I think it's better to not change any content here. 

There are some warnings, but none is introduced here, I'll keep taking care of them in separate PRs.

This is how the new API main page looks like:

api_home

And this is a sample of one of the individual pages:

api_io

CC: @TomAugspurger @jreback

**Comment by TomAugspurger** [comment]
LGTM. Maybe wait till later today to merge in case other's have comments.

We might want to rethink some of the organization / section headings (e.g. "general functions" isn't especially informative) but those can be done as followups.

**Comment by jreback** [comment]
yeah this is ok. sure we need some work on the names / maybe some org of this, but a great first step.

**Pull request merged**
