### PR TITLE
DOC: Fix PEP-8 issues in timedeltas.rst

### PR DESCRIPTION
**Pull request by FHaase**
- Replace `from pandas.tseries.offsets import *` with `pd.offsets.<ClassName>` for better readability.

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @FHaase 

@jbrockmendel if you want to take a look here too

**Comment by jbrockmendel** [comment]
This looks fine to me.  Only question is if the importing of Second/Minute etc is intentional.

**Comment by datapythonista** [comment]
Not sure what you mean. Replacing the `from pandas.tseries.offsets import *` and using the full path version of `Second`... is intentional, as importing `*` is discouraged in Python, and having the full path makes things clearer IMO, as the user know where `Second` and the rest are coming from. Is this what you mean?

**Comment by jreback** [comment]
thanks @FHaase 

yeah more explicit the better.

**Pull request merged**
