### PR TITLE
TYP: privatize type alias in pandas/util/_decorators.py

### PR DESCRIPTION
**Pull request by simonjayhawkins**
broken off #28339

### CODE REVIEW

**Comment by jreback** [comment]
why do you think privatizing this is warranted? (other parts are ok)

**Comment by simonjayhawkins** [comment]
It was a mistake when first added. Type aliases added directly in modules are added or the purpose of type checking only and shouldn't be public.

They should be considered an implementation detail and subject to change without notice.

All aliases in typeshed are prefixed with an underscore.

**Comment by jreback** [comment]
> It was a mistake when first added. Type aliases added directly in modules are added or the purpose of type checking only and shouldn't be public.
> 
> They should be considered an implementation detail and subject to change without notice.
> 
> All aliases in typeshed are prefixed with an underscore.

this entire module is private and this is inconsistent with the rest of the codebase where a type annotation is just a name; private just makes this harder to read.

**Comment by simonjayhawkins** [comment]
so should I close this then?

**Comment by jreback** [comment]
> so should I close this then?

i don't see any other changes? if so, yes

do we have this pattern elsewhere? we should be consistent about it (I think we *mostly* are already)

**Comment by simonjayhawkins** [comment]
> i don't see any other changes? if so, yes

one other minor change, i'll include in future PR instead.

> do we have this pattern elsewhere?

just https://github.com/pandas-dev/pandas/pull/29755#discussion_r349210957, could be reverted.

used heavily in #28339, but will change as break bits off


> we should be consistent about it

agreed. so this module being private is probably not relevant. We should not privatize aliases in any modules

> (I think we _mostly_ are already)

not really used many aliases outside of pd._typing yet

**Pull request closed without merging**
