### PR TITLE
DOC: Add whatsnew

### LINKED ISSUE #38878: BUG: Unexpected typecast on datetime.date in groupby.key()
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import datetime as dt
>>> import pandas as pd
>>> df = pd.DataFrame([[dt.date(2021,1,1), 1, 'a'], [dt.date(2021,1,2),  2, 'b']])
>>> g = df.groupby([0, 1])
>>> g.groups.key()
... dict_keys([(Timestamp('2021-01-01 00:00:00'), 1), (Timestamp('2021-01-02 00:00:00'), 2)])
```

#### Problem description
When multiple columns pass to groupby, the `datetime.date` type columns cast o the `Timestamp` type.

Due to the unexpected type casting, following code raises a `KeyError`.

```python
>>> list(g.get_group(key) for key in g.groups.keys())
... KeyError: (Timestamp('2021-01-01 00:00:00'), 1)
```
[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

This typecast will only be performed if multiple indexes are specified.

```python
>>> g = df.groupby([0])
>>> g.groups.key()
... dict_keys([datetime.date(2021, 1, 1), datetime.date(2021, 1, 2)])
```

#### Expected Output
```python
>>> g.groups.key()
... dict_keys([(datetime.date(2021, 1, 1), 1), (datetime.date(2021, 1, 2), 2)])
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 3e89b4c4b1580aa890023fc550774e63d499da25
python           : 3.8.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.2.0
Version          : Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : ja_JP.UTF-8
pandas           : 1.2.0
numpy            : 1.19.4
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.1.1
Cython           : 0.29.21
pytest           : 6.2.1
hypothesis       : None
sphinx           : 3.4.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : 2.7.2
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.52.0

</details>

### PR DESCRIPTION
**Pull request by vangorade**
- [x] closes #38878
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks @vangorade - can you rebase so as to drop the unrelated commits please?

**Comment by vangorade** [comment]
did i just messed up something @MarcoGorelli?

**Comment by MarcoGorelli** [comment]
possibly :) no worries though - at this point I think the easiest thing might be to just do
```
git fetch upstream --prune
git reset --hard upstream/master
<make the same changes you'd made previously>
git add -u
git commit -m <commit message>
git push origin HEAD -f
```

**Comment by vangorade** [comment]
> possibly :) no worries though - at this point I think the easiest thing might be to just do
> 
> ```
> git fetch upstream --prune
> git reset --hard upstream/master
> <make the same changes you'd made previously>
> git add -u
> git commit -m <commit message>
> git push origin HEAD -f
> ```

Thanks. I thought i broke something, after some google search i learned about this issue and how to time travel in git and thanks to your reply i finally resolve this issue!

**Comment by jreback** [comment]
thanks @vangorade

**Pull request merged**
