### PR TITLE
CI: troubleshoot windows builds

### PR DESCRIPTION
**Pull request by jbrockmendel**
Windows builds are still hitting what look like OOM errors.  Trying splitting these into smaller pieces; its fragile.

### CODE REVIEW

**Comment by WillAyd** [comment]
Any idea which set of tests are likely to cause memory issues? Maybe matplotlib tests?

**Comment by jbrockmendel** [comment]
> Any idea which set of tests are likely to cause memory issues? Maybe matplotlib tests?

hard to tell; in most cases there isnt a traceback pointing to a test

**Comment by jbrockmendel** [comment]
new idea: lets just drop windows altogether

**Comment by jbrockmendel** [comment]
@datapythonista help?  ive been banging my head against this windows build and am getting nowhere, somehow managed to break a linux build for a little while there.

Could we disable xdist and see if we can get more meaningful exception messages?

Could we split this into multiple builds to avoid the time limit?

**Comment by jreback** [comment]
@jbrockmendel how about one more rebase here and then let's merge and call it a day.

**Comment by jbrockmendel** [comment]
> how about one more rebase here and then let's merge and call it a day.

just rebased, but i got a _lot_ of failing builds before getting one to pass.  lets try to get at least a few in a row before merging (and make sure we are OK with dropping all these optional dependencies)

**Comment by jbrockmendel** [comment]
HOW DID THIS BREAK THE LINUX BUILDS

**Comment by jreback** [comment]
> HOW DID THIS BREAK THE LINUX BUILDS

broken elsewhere, pending patch for that.

**Comment by jbrockmendel** [comment]
> broken elsewhere, pending patch for that.

is that related to the something.xls and something.xlsx files that im seeing left behind after running the tests for the last day or two?

**Comment by twoertwein** [comment]
> is that related to the something.xls and something.xlsx files that im seeing left behind after running the tests for the last day or

damn, I was wondering where those came from. `ExcelWriter` now opens the files which changed the behavior of this test `pandas/tests/io/excel/test_writers.py:test_register_writer`. This test wasn't expecting that an empty file will be created so it also didn't clean them up.

I will make a PR.

**Comment by jbrockmendel** [comment]
Is `xvfb-run: error: Xvfb failed to start` showing in the linux builds for any other PR?  bc if not, then this is somehow breaking those builds.

**Comment by datapythonista** [comment]
Sorry for the delay @jbrockmendel. I've been having a look, but I'm missing some context.

The current failure seems to be a timeout. There is something I don't quite understand on it, seems like after finishing the tests, which take around 30 minutes, another call to pytest starts, and it doesn't finish on time. But this seems unrelated to the out of memory problems you mention.

Does this make sense? Is the problem I'm seeing the one you're having trying to address?

**Comment by jreback** [comment]
trying nth time, if green let's just merge

**Comment by jreback** [comment]
wow 2 in a row, merging.

**Comment by jreback** [comment]
@jbrockmendel i thought we had an issue about troubleshooting these builds, can you update it to say now windows/plotting excluded.

**Pull request merged**
