### PR TITLE
Fix test for boto3

### LINKED ISSUE #17135: still doesn't work with boto3 StreamingBody
ref: https://github.com/pandas-dev/pandas/issues/16135 https://github.com/pandas-dev/pandas/pull/16150

#### Example
```py
s3_object = client.get_object(Bucket=bucket, Key=key)
result = read_csv(s3_object["Body"])
# ValueError: Invalid file path or buffer object type: <class 'botocore.response.StreamingBody'>
```

#### Problem description
issue: is_file_like requirements are too strict for boto3 S3 objects https://github.com/pandas-dev/pandas/issues/16135
pull request: https://github.com/pandas-dev/pandas/pull/16150

This issue was closed but it's not working. I've found that the test is skipped and has a bug.
I'll send a pull request to reproduce the behavior.

I think it's because `botocore.response.StreamingBody` doesn't have `__iter__` so `is_file_like` returns `False`.

<details>

INSTALLED VERSIONS
------------------------
commit: c8dcf194c7a5264ed6d9161d5807e9da972cab4c
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL:
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.21.0.dev+317.gc8dcf19
pytest: 3.1.3
pip: 7.1.2
setuptools: 36.2.6
Cython: 0.26
numpy: 1.13.1
scipy: None
pyarrow: None
xarray: None
IPython: 5.0.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: 0.1.2
pandas_gbq: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by uiur**
- [ ] closes #17135
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

This is a failing test for #17135 to reproduce the behavior.

### CODE REVIEW

**Comment by gfyoung** [comment]
@uiureo : For us to accept this patch, we would need you to patch existing behavior, not just fix the test to reproduce a failure.

**Comment by jreback** [comment]
@uiureo can you make this into an xfailing test.

note that ``moto`` is now used to mock these types of things, so it should be against that as well.

**Comment by jreback** [comment]
can you rebase and update according to comments.

**Comment by jreback** [comment]
closing as stale

**Pull request closed without merging**
