### PR TITLE
don't repeat yourself in pyproject.toml

### PR DESCRIPTION
**Pull request by stonebig**
- [x] simplifies pyproject.toml writing, and so maintenance. zero change

### CODE REVIEW

**Comment by stonebig** [comment]
this method is applied in dask project since two months, so I presume not bad.

**Comment by stonebig** [comment]
hummm, maybe thre was a reason ? https://github.com/pandas-dev/pandas/blob/main/scripts/generate_pip_deps_from_conda.py

**Comment by MarcoGorelli** [comment]
> hummm, maybe there was a reason ? https://github.com/pandas-dev/pandas/blob/main/scripts/generate_pip_deps_from_conda.py

thanks for your PR - you could update that script too if you wanted to do this

**Comment by stonebig** [comment]
> > hummm, maybe there was a reason ? https://github.com/pandas-dev/pandas/blob/main/scripts/generate_pip_deps_from_conda.py
> 
> thanks for your PR - you could update that script too if you wanted to do this

Well, I thought it was a low hanging fruit, now I see it's a bit too complex for me

**Comment by mroeschke** [comment]
Could you reference where dask does this?

**Comment by stonebig** [comment]
> Could you reference where dask does this?

https://github.com/dask/dask/blob/main/pyproject.toml#L66-L70

**Comment by mroeschke** [comment]
Thanks but since we have a script enforcing these are consistent in the file (as opposed to the pip extras being consistent), I think keeping the verboseness is fine so closing.

**Pull request closed without merging**
