### PR TITLE
Added Hypothesis property-based test for timedelta addition

### PR DESCRIPTION
**Pull request by c74p**
- [ ] closes #xxxx
- [1 ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

- This is the first pull request I've done on any project in any language.  Any feedback, pointing to docs, requests to work on other issues instead, etc. happily accepted. Thanks for your work on Pandas!

### CODE REVIEW

**Review by WillAyd — CHANGES_REQUESTED** [review]
Thanks for the PR. Can you speak to the utility of this though? Is it closing an issue or increasing coverage that doesn't exist?

**Comment by c74p** [comment]
> Thanks for the PR. Can you speak to the utility of this though? Is it closing an issue or increasing coverage that doesn't exist?

It's not increasing coverage per se, it's an attempt to improve the quality of the test where it exists:
- The current test says 'with some particular Timestamp and some particular Timedelta, check that adding them produces the expected result.'
- This test says 'give me 100 random examples of Timestamps and Timedeltas, and check that adding them produces the expected result.'

Note that the coverage report says that this change REDUCES the code coverage by 0.1%, even though I didn't remove any tests. I'm not sure what the next step is on that, nor the other failing test.

I'd like to add more of these tests and eventually also improve code coverage, but this first one was a trial balloon.

**Comment by mroeschke** [comment]
If you'd like to help increase test coverage (not necessarily code path test coverage), we have quite a number of issues that would need regression tests.

https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+Tests%22

**Comment by WillAyd** [comment]
Closing as not sure we want / need this, though @c74p we certainly appreciate any contributions you'd like to make. What @mroeschke linked to above would be a good reference if you are looking to help out

**Pull request closed without merging**
