### PR TITLE
TST: Making explicit when we run the db tests

### LINKED ISSUE #23928: TST: Run tests using a database explicitly
At the moment, our tests accessing a database (in `pandas/tests/io/test_sql.py`) are being skipped if the module to connect to the database are not installed (e.g. `pymysql` or `psycopg2`), or if the connection to the database doesn't succeed.

This has two implications:
- It's not easy in the CI to know which builds are running the db tests (we need to check for the dependencies, and also check if a db server is set up in the host)
- If there is an issue with the db, the tests will be skipped silently (we'll log that they are skipped, but I guess nobody will notice)

I think a better approach would be:
- Mark those tests in the cateogry `db` (i.e. `@pytest.mark.db`)
- Remove the skips for when the the connection fails (and possibly the one for when the db modules are not installed)
- In the CI add `-m "not db"` or `-m "db"` depending on whether we want to run the tests or not (this will be done with the env `PATTERNS` when #23924 is merged)

@jreback is this ok?

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #23928
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
you need to leave the skips if not installed

**Comment by datapythonista** [comment]
I was checking that no errors happened when tests were not skipped unless explicitly. All was green, added the skips now.

**Comment by jreback** [comment]
lgtm. can you just do a ``import pandas; pandas.test()`` to make sure properly skipping when libraries are not installed. I believe we test this in the CI as well.

**Comment by datapythonista** [comment]
`pandas.test()` is also skipping the tests
```
pandas/tests/io/test_sql.py ....................................................................................................s....sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 66%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss...ssssssssssssssssssssssssssssssssssss.................s.............ssssssssss                                                        [ 66%]
```

**Comment by jreback** [comment]
thanks!

**Pull request merged**
