### PR TITLE
Removed scikit-timeseries migration docs from FAQ

### PR DESCRIPTION
**Pull request by ihoegen**
Issue #10281

### CODE REVIEW

**Comment by shoyer** [comment]
LGTM, thanks!

**Comment by jorisvandenbossche** [comment]
Indeed, looks good!  
Only, I think, when we merge this, the scikit-timeseries website should ideally also be updated: http://pytseries.sourceforge.net/ (it still mentions it is the 'plan' to port it to pandas)

Because it is still downloaded quite a lot: only looking at the last of year and from sourceforge, it has 2000 downloads (or is it downloaded from travis ci or the like?)

**Comment by ihoegen** [comment]
I agree

**Comment by jreback** [comment]
If people really are interested in migration they will hit the pandas page, and eventually ask on the tracker so I don't think that link is ok

**Comment by jorisvandenbossche** [comment]
Anyway, we ourselves can't change that website. So merging this. Thanks @ihoegen !

**Comment by jorisvandenbossche** [comment]
@pierregm I don't know if we can contact you this way, but: the warning notice on the http://pytseries.sourceforge.net/ website is a little out of date. Would it be possible to update this?

**Pull request merged**
