### PR TITLE
DOC: Update README to link to install instructions.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Want any updates to the actual install instructions? Should we remove the section on wakari? Do we have a preference for conda-forge over the default channel?

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I would maybe leave in the "pip install pandas" and "conda install pandas" (but removal of easy install and addition of link to full docs is certainly good!)

I would keep the default channel for now

**Comment by jorisvandenbossche** [comment]
I would actually remove the detailed list of dependencies (not needed in the readme I think, and duplicated content with install.rst which both have to be kept up to date). But I can also do in another PR.

**Comment by TomAugspurger** [comment]
Sounds good, I'll update tonight.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger Thanks, I will do a follow-up with some clean-up of the install.rst page.

**Pull request merged**
