### PR TITLE
TYP: Expanding.__init__

### PR DESCRIPTION
**Pull request by twoertwein**

### CODE REVIEW

**Comment by mroeschke** [comment]
LGTM. Could you rebase? The code checks were not working when you originally opened this PR.

**Comment by twoertwein** [comment]
> LGTM. Could you rebase? The code checks were not working when you originally opened this PR.

This time it ran :) Might be worth skipping the typing tests only if building pandas fails.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @twoertwein 

> Might be worth skipping the typing tests only if building pandas fails.

I think this should be the case since we have `if: ${{ steps.build.outcome == 'success' }}` in the GHA job.

**Comment by twoertwein** [comment]
I think the typing tests are also skipped when the doc-build/tests fail?

**Comment by mroeschke** [comment]
Hmm that shouldn't be the case.

The docbuild is in a separate workflow, `docbuild-and-upload.yml`, from the typing checks, `code-checks.yml` which each build a separate version of pandas. So if the docbuild fails the typing checks in code-checks still run.

**Comment by twoertwein** [comment]
Sorry, I meant the `Docstring and typing validation` workflow:

image

**Comment by mroeschke** [comment]
Ah gotcha, yes correct. If any of the prior checks fail, then the whole workflow will stop. Feel free to add a `continue-on-error: true` in a subsequent PR for all the actual code checking steps

**Pull request merged**
