### PR TITLE
Bug: merge_asof() cannot use datetime.timedelta as tolerance kwarg 

### PR DESCRIPTION
**Pull request by ianzur**
- [x] Fixes issue #28098
- [x] tests added / passed [1/0]
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by ianzur** [comment]
datetime.timedelta objects do not have nanoseconds like pd.Timedelta

Another check and conversion is necessary to convert datetime.timedelta correctly to nanoseconds similarly to pd.Timedelta.value
@TomAugspurger

**Comment by ianzur** [comment]
The offending test

https://github.com/pandas-dev/pandas/blob/def01cf7bbb5ef8c9bf2e19737ea918e6a76a143/pandas/tests/reshape/merge/test_merge_asof.py#L593-L611

**Comment by WillAyd** [comment]
I only see a whatsnew - did you have an actual fix and tests for this?

**Comment by ianzur** [comment]
Thank you, I'm new at this. I'll reopen when a fix is in place.

Ian

**Pull request closed without merging**
