### PR TITLE
CI: continue-on-error: true for scorecard action

### PR DESCRIPTION
**Pull request by mroeschke**
This job on main is currently failing with a 500 error 

```
 2022/12/14 18:00:45 error processing signature: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it."}
```

I am doubtful this is entirely actionable on our side (or if it ever will be), and it masks if there are actual failures on main so just letting this job "pass" even if there are these issues

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
thanks @mroeschke 

this doesn't run on the PR, so might as well merge

**Comment by mroeschke** [comment]
Darn that didn't work, maybe I have to manually skip the failing step

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error led me to believe you could do this for a entire job-id but I guess only if a strategy is used?

**Comment by lithomas1** [comment]
We can just delete the job, honestly. I find it kind of annoying, to be honest, and I don't think it really is catching actual security issues.

If we already have CodeQL, I think we should be fine.

**Comment by MarcoGorelli** [comment]
agreed

**Pull request merged**
