### PR TITLE
CLN: Remove unused script find_commits_touching_func.py

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] xref #31039

I've been trying the script `find_commits_touching_func.py` and doesn't seem to be working. Tried for many existing functions, and never get any result. I guess it doesn't work with newer git versions, or with the latest dependencies. And if nobody realized of this before, I assume nobody is using this script (and in any case, a separate project would be more appropriate for it, since I don't think it's pandas specific).

The script was being refactored in #32044, that's why I was having a look.

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]

**Comment by jbrockmendel** [comment]
LGTM

**Comment by WillAyd** [comment]
I vaguely recall some contributor using this recently (@3vts or @MomIsBestFriend - either of you?)

No objections to getting rid of it, though cc'ing them in case they have a counter point

**Comment by 3vts** [comment]
I did not work on this file. Just tested and seems it does not work as stated earlier

**Comment by MomIsBestFriend** [comment]
@WillAyd I cannot recall when I used this script.

I think I was the one who were one on this as part of the ```f-strings``` formatting change.

I have no objections in removing this script as I never used it, and for the fact that I haven't seen anyone else use it.

**Comment by WillAyd** [comment]
OK thanks all for comments and @datapythonista for PR

**Pull request merged**
