### PR TITLE
TYP: clean for PY3.8 (Literal)

### PR DESCRIPTION
**Pull request by simonjayhawkins**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
39 failure looks unrelated; ive seen it on at least one other PR today

**Comment by simonjayhawkins** [comment]
#42381

**Comment by Dr-Irv** [comment]
@simonjayhawkins I don't think this will work with python 3.7.  Does that mean we are dropping support for 3.7 in the near future?

**Comment by simonjayhawkins** [comment]
already dropped. #41678

**Comment by jreback** [comment]
thanks @simonjayhawkins

**Pull request merged**
