### PR TITLE
TST: Skip leaky test on Python 3.10

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] xref #41935 (we should close after updating MacPython)
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

This test seems to be leaking on Python 3.10, causing subsequent tests to fail with a cryptic and flaky error. Let's skip it.
This unblocks official Python 3.10 support.
I am not fixing the test since my first attempt at fixing the leakiness failed and I don't understand and don't have time to fix the problem.

If this works, we can revert #41990.

### CODE REVIEW

**Comment by lithomas1** [comment]
@github-actions pre-commit

**Comment by lithomas1** [comment]
We need to target 1.3.4 since we've already released Python 3.10 wheels, which means we've committed to Python 3.10 support in 1.3.x. We cannot commit to Python 3.10 support if we allow failure on the CI build. This PR takes the CI build out of allow failure by resolving the leaky test causing flaky, cryptic errors.

**Comment by jreback** [comment]
sounds good

**Review by mzeitlin11 — APPROVED** [review]
LGTM

**Comment by jbrockmendel** [comment]
LGTM

**Comment by jreback** [comment]
thanks @lithomas1 very nice

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
