### PR TITLE
DEPR: deprecate units 'w', 'd', 'MS', 'US', 'NS' for Timedelta in favor of  'W', 'D', 'ms', 'us', 'ns'

### PR DESCRIPTION
**Pull request by natmokval**
xref #58998

### CODE REVIEW

**Review by MarcoGorelli — COMMENTED** [review]
Nice one, thanks @natmokval!

Just one question - do we still need `c_DEPR_ABBREVS`, or can `c_DEPR_UNITS` be used in its place?

**Comment by natmokval** [comment]
> Nice one, thanks @natmokval!
> 
> Just one question - do we still need `c_DEPR_ABBREVS`, or can `c_DEPR_UNITS` be used in its place?

Thanks @MarcoGorelli for reviewing this PR. I think we need `c_DEPR_ABBREVS`, because so far it's allowed to use lowercase strings `w`, `d`, `b` and `c` for offsets/period. 

After deprecation lowercase strings w, d, b and c denoting frequencies in Week, Day, BusinessDay and CustomBusinessDay classes (PR #58998 is ready for review) we can use `c_DEPR_UNITS` instead `c_DEPR_ABBREVS`.

**Review by MarcoGorelli — APPROVED** [review]
Thanks for explaining! Cool, I think this is ready then

Approving, leaving open a little in case anyone has objections

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @natmokval

**Pull request merged**
