### PR TITLE
Revert "CI: Pin blosc to fix pytables"

### PR DESCRIPTION
**Pull request by lithomas1**
Reverts pandas-dev/pandas#58209

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @lithomas1

**Comment by simonjayhawkins** [comment]
@lithomas1 was https://github.com/pandas-dev/pandas/pull/58209 ever backported? We can remove the needs backport label here?

**Comment by lithomas1** [comment]
This wasn't needed for 2.2.3. 

Thanks for checking.

**Comment by lithomas1** [comment]
I think this is causing problems for 2.2.x now, backporting.

**Pull request merged**
