### PR TITLE
ENH: Adds errors parameter to array strftime to enhance exception handling. 

### LINKED ISSUE #58178: ENH: Better error handling in `strftime`
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

`ValueError` due to `Timestamp.strftime` are currently silently caught by DatetimeLike array strftime and replaced with `str(t)`. This leads to unexpected behaviour:

```python
> dta = pd.DatetimeIndex(np.array(['1820-01-01', '2020-01-02'], 'datetime64[s]'))

> dta[0].strftime("%y")  # Instance operation raises ValueError
Traceback (most recent call last):
  (...)
  File "timestamps.pyx", line 1518, in pandas._libs.tslibs.timestamps.Timestamp.strftime
ValueError: format %y requires year >= 1900 on Windows

> dta.strftime("%y")  # Array operation catches error and turns into str representation (with default datetime format)
Index(['1820-01-01 00:00:00', '20'], dtype='object')
```

This very surprising behaviour on the array strftime is due to the try-except at https://github.com/pandas-dev/pandas/blob/b8a4691647a8850d681409c5dd35a12726cd94a1/pandas/_libs/tslib.pyx#L219-L224

Note that this try-except is around since 0.16.1 (introduced by commit https://github.com/pandas-dev/pandas/commit/3d54482bbd8086c27a01d489a0ae751e0b9c3731)

This "questionable behaviour" was also reported in https://github.com/pandas-dev/pandas/issues/48588

Note that this does not happen with dates that cannot be converted to `datetime` at all, because this particular `ValueError` is currently caught and turned into a `NotImplementedError`:

```python
> dta = pd.DatetimeIndex(np.array(['-0020-01-01', '2020-01-02'], 'datetime64[s]'))

> dta.strftime("%Y_%m_%d")  # Custom so falls back on Timestamp.strftime
NotImplementedError: strftime not yet supported on Timestamps which are outside the range of Python's standard library. For now, please call the components you need (such as `.year` and `.month`) and construct your string from there.

> dta[0].strftime("%Y_%m_%d")
NotImplementedError: strftime not yet supported on Timestamps which are outside the range of Python's standard library. For now, please call the components you need (such as `.year` and `.month`) and construct your string from there.
```

### Feature Description

I propose to add an `errors` parameter to array `strftime` with the following values

 - ‘raise’ (default) would not catch any underlying error and raise them as is
 - ‘ignore’ would catch all errors and silently replace the output with None instead of a string
 - 'warn' would have the same behaviour as 'ignore' and would additionally issue a `StrftimeErrorWarning` warning message `"The following timestamps could be converted to string: [...]. Set errors=‘raise’ to see the details"`

```python
> dta = pd.DatetimeIndex(np.array(['1820-01-01', '2020-01-02'], **'datetime64[s]'))**
> dta[0].strftime("%y")
ValueError: format %y requires year >= 1900 on Windows
> dta.strftime("%y")
ValueError: format %y requires year >= 1900 on Windows
> dta.strftime("%y", errors='raise')
ValueError: format %y requires year >= 1900 on Windows
> dta.strftime("%y", errors='ignore')
Index([None, '20'], dtype='object')
> dta.strftime("%y", errors='warn')
StrftimeErrorWarning : Not all timestamps could be converted to string: ['1820-01-01']. Set errors=‘raise’ to see the details
Index([None, '20'], dtype='object')
```

The specific `NotImplementedError` described previously can either disappear or stay, but in any case it should be handled the same way than ValueErrors above (meaning that if user selects 'ignore', the error must be silently caught)

### Alternative Solutions

An alternative solution could be to always raise errors

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by stanleyo03**
- [x] closes #58178 
- [x] Tests added and passes in pandas\tests\arrays\test_datetimelike.py
- [x] Pre-commit passes
- [x] Added type annotations for new 'errors' parameter in changed strftime functions. 
- [x] Added an entry in the latest `doc/source/whatsnew/v3.0.0.rst` file in the enhancement section.

### CODE REVIEW

**Comment by mroeschke** [comment]
Thanks for the PR, but the original enhancement request hasn't gotten enough feedback from the core team to move forward yet so closing this PR for now. If the original issue gains more support we can reopen this PR

**Comment by StanO1225** [comment]
Hi, thank you for looking at the PR. Are there any specific concerns with the way we are handling this issue or does the team just need more time to discuss if it is necessary? Thank you for the update.

**Comment by mroeschke** [comment]
The team just needs more time to discuss the original enhancement request. i.e. if an enhancement issue has `Needs Triage` or `Needs Discussion` labels, it is not suitable to open a PR yet

**Comment by StanO1225** [comment]
I see. Thanks for the clarification!

**Pull request closed without merging**
