### PR TITLE
Removed duplicated _constructor_sliced definition in sparse.frame

### PR DESCRIPTION
**Pull request by avmarchenko**
Removal of duplicated code in core.sparse.frame

### CODE REVIEW

**Comment by avmarchenko** [comment]
The one failed travis-ci build seems due to "CondaHTTPError"

**Comment by TomAugspurger** [comment]
Restarted those workers.

**Review by gfyoung — APPROVED** [review]
Nice catch!

**Comment by gfyoung** [comment]
Thanks @avmarchenko !

**Pull request merged**
