### PR TITLE
BUG: read_csv with engine pyarrow doesn't handle missing values

### LINKED ISSUE #47950: BUG: read_csv with engine pyarrow doesn't handle missing values
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import io

data = """idx,date
2,2000-01-01
,
"""

print('pyarrow engine', pd.read_csv(io.StringIO(data), parse_dates=['date'], engine='pyarrow'))
print('default engine', pd.read_csv(io.StringIO(data), parse_dates=['date']))
```

### Issue Description

Like this, we get:

```
pyarrow engine    idx        date
0  2.0  2000-01-01
1  NaN        None
default engine    idx       date
0  2.0 2000-01-01
1  NaN        NaT
```

### Expected Behavior

I'd expect:
```
pyarrow engine    idx        date
0  2.0  2000-01-01
1  NaN        NaT
default engine    idx       date
0  2.0 2000-01-01
1  NaN        NaT
```

### Installed Versions

<details>

/home/megorelli/pandas-dev/.venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 61464f8cad07271114af7668bbae158ba963126c
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.114-16025-ge75506b9d98e
Version          : #1 SMP PREEMPT Sat Jul 16 18:52:19 PDT 2022
machine          : aarch64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+1230.g61464f8cad.dirty
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.1.0
pip              : 22.0.4
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.47.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.4.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [x] closes #47950 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
@mroeschke I'm not really familiar with pyarrow, any thoughts on this solution? Tagging you as I've seen you in lot's of arrow-related PRs

---


PS. I'm aware I still need a whatsnew note, will add that later

**Comment by WillAyd** [comment]
Is pyarrow reading this as a date or something else?

**Comment by MarcoGorelli** [comment]
Currently on main, `None` gets read as `'None'`, and the whole column gets parsed as `object`. By keeping it as `None`, it gets parsed as `NaT`

**Comment by WillAyd** [comment]
Not super familiar with our implementation, but I wonder if we should be passing along the `parse_dates` fields to the underlying pyarrow implementation. Something like this

```python
>>> import pyarrow as pa
>>> import io
>>> data = """idx,date
... 2,2000-01-01
... ,
... """
>>> pa.csv.read_csv(io.BytesIO(data.encode()), convert_options=csv.ConvertOptions(column_types={"date": pa.timestamp(unit="ns")}))
pyarrow.Table
idx: int64
date: timestamp[ns]
----
idx: [[2,null]]
date: [[2000-01-01 00:00:00.000000000,null]]
```

Might simplify code paths compared to reading in as an object and converting on our end

**Comment by MarcoGorelli** [comment]
Here's what currently happens:

in 

https://github.com/pandas-dev/pandas/blob/7214f857e45965fe7a0cfbba1d2dc35abb0fd7f4/pandas/io/parsers/base_parser.py#L1061

, `date_cols` is `(array([datetime.date(2000, 1, 1), None], dtype=object),)`.

This gets converted to `array(['2000-01-01', 'None'], dtype=object)`, which can't be converted to a date.

In this branch, on the other hand, it gets converted to ``. So then, when we get to

https://github.com/pandas-dev/pandas/blob/7214f857e45965fe7a0cfbba1d2dc35abb0fd7f4/pandas/core/tools/datetimes.py#L434-L442

which goes to

https://github.com/pandas-dev/pandas/blob/7214f857e45965fe7a0cfbba1d2dc35abb0fd7f4/pandas/core/arrays/datetimes.py#L2159-L2167

which converts `array(['2000-01-01', None], dtype=object)` to `(array(['2000-01-01T00:00:00.000000000',                           'NaT'], dtype='datetime64[ns]'), None)`

**Comment by WillAyd** [comment]
I was thinking more that we would pass the `parse_dates` options to `convert_options` here:

https://github.com/pandas-dev/pandas/blob/7214f857e45965fe7a0cfbba1d2dc35abb0fd7f4/pandas/io/parsers/arrow_parser_wrapper.py#L147

Which might have that off to arrow and reduce the layers / complexity we have in the wrapper?

**Comment by MarcoGorelli** [comment]
Thanks @WillAyd for weighing in - indeed, with that option, then `table.to_pandas()` would have `NaT` rather than `None`.

However, we run into another issue: when we get to

https://github.com/pandas-dev/pandas/blob/85738b3106fe06fcca0cb5f56f9a689f1f3cd1b7/pandas/_libs/tslibs/parsing.pyx#L1155-L1160

then `array` is `array ['2000-01-01T00:00:00.000000000'                           'NaT']`, and the first `item` is `946684800000000000`.

But then, we get to

https://github.com/pandas-dev/pandas/blob/85738b3106fe06fcca0cb5f56f9a689f1f3cd1b7/pandas/_libs/tslibs/parsing.pyx#L1096

which throws

```
OverflowError: value too large to convert to int
```

So like this, it's the first element (`2000-01-01T00:00:00.000000000`) that ends up throwing an error, rather than the second (missing) one

**Comment by WillAyd** [comment]
Do you get that while also commenting out line 111 in that module?

**Comment by MarcoGorelli** [comment]
> Do you get that while also commenting out line 111 in that module?

Ah gotcha, thanks!

Yes, that works, but then
```
data = """idx,date
2,19990127 19:00:00
"""

df = pd.read_csv(io.StringIO(data), parse_dates=['date'], engine='pyarrow')
```
fails:
```
  File "/home/megorelli/pandas-dev/pandas/io/parsers/arrow_parser_wrapper.py", line 148, in read
    table = pyarrow_csv.read_csv(
  File "pyarrow/_csv.pyx", line 1217, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 1226, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: In CSV column #1: CSV conversion error to timestamp[ns]: invalid value '19990127 19:00:00'
```

, whereas on this branch it would output:
```
   idx                date
0    2 1999-01-27 19:00:00
```

**Comment by mroeschke** [comment]
Agreed with @WillAyd general suggestion to dispatch this to Arrow's read_csv as much as possible.

With the above error, might be worth reporting to the Arrow Jira board, but I can see how this is one of those tricky parsing situations that Arrow does not (may not) support.

**Comment by WillAyd** [comment]
Agreed with @mroeschke   I think Arrow should handle the date conversions if the arrow engine is chosen. If that doesn’t work for users they can use another engine, but picking and choosing read_csv arguments to dispatch across engines is pretty confusing

**Comment by MarcoGorelli** [comment]
Thanks for your comments

I may have misunderstood, but are you suggesting to accept this error? Wouldn't that introduce a regression? Because currently, with the latest pandas release,
```
import pandas as pd
import io

data = """idx,date
2,19990127 19:00:00
"""

df = pd.read_csv(io.StringIO(data), parse_dates=['date'], engine='pyarrow')

print(pd.read_csv(io.StringIO(data), parse_dates=['date'], engine='pyarrow'))
```
works fine, it outputs
```
idx                date
0    2 1999-01-27 19:00:00
```

**Comment by WillAyd** [comment]
Yea I think that behavior should be deprecated if it’s not the arrow engine doing the date parsing

**Comment by MarcoGorelli** [comment]
sounds good to me - I've opened https://github.com/pandas-dev/pandas/issues/48017 - closing this PR then

**Pull request closed without merging**
