### PR TITLE
(WIP) CI: Check private function not used across modules

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [x] xref https://github.com/pandas-dev/pandas/pull/32942#issuecomment-609893282
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

---

cc @jbrockmendel

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Nice.  I'm not aware of any alternative to sys._getframe, but the others we should be able to either track down alternatives or de-privatize

**Comment by MomIsBestFriend** [comment]
> Nice. I'm not aware of any alternative to sys._getframe, but the others we should be able to either track down alternatives or de-privatize

It will be very easy to white-list ```sys._getframe``` or for that matter, any other class/module/function...

**Comment by jbrockmendel** [comment]
just pushed with rebase

**Comment by jbrockmendel** [comment]
@MomIsBestFriend can we exclude the tests directory here

**Comment by jbrockmendel** [comment]
@MomIsBestFriend you ok?  havent heard from you in a while

**Comment by MomIsBestFriend** [comment]
> @MomIsBestFriend you ok? havent heard from you in a while

Yes I am perfectly fine, due to COVID-19 I have much more work IRL, and I am not able to contribute to pandas ATM :disappointed: 

When I have the time I'll be back to contribute once again.

Thank you for thinking about me @jbrockmendel <3

**Comment by jreback** [comment]
nice idea, please comment if you can come back to this / open a new PR

**Pull request closed without merging**
