### PR TITLE
CLN: refactor roll_generic to call roll_generic_with_indexer

### PR DESCRIPTION
**Pull request by ghost**
Make it possible for users to directly supply their own indexer when pandas doesn't provide what they want out of the box. This is useful for quickly doing something like "groupby" with overlapping groups (xref #26959) and/or strided rolling.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
> Make it possible for users to directly supply their own indexer when pandas doesn't provide what they want out of the box.

does this need some documentation?

**Comment by pilkibun** [comment]
This is the low-level to make this possible. I think there's another piece needed which wraps it for users. It's a valid refactor regardless.

**Review by jreback — CHANGES_REQUESTED** [review]
this is too specific, meaning would take a change like this but it should be generic to all aggregation functions. This maybe a large effort.

**Comment by pilkibun** [comment]
That's fair.  

Lifting the indexer out of  the remaining kernels (which have better performance then `rolling_generic`) wouldn't be that difficult. However, some kernels, like the new rolling_min_max from #19549, allow for variable window *size* but still assume a fixed stride of 1 (`start[i+1]=start[i]+1`). That's always true currently, but relaxing that is actually the goal here. 

I have some ideas for a larger refactor but building up gradually to large PRs is more prudent.
So closing now and I hope to revisit more thoroughly in the future.

**Pull request closed without merging**
