### PR TITLE
DEPR: Positional arguments in Series.to_string

### LINKED ISSUE #57280: DEPR: Positional arguments in Series.to_markdown/string
While most method were captured in https://github.com/pandas-dev/pandas/issues/54229, `Series.to_string` and `Series.to_markdown` were missed

### PR DESCRIPTION
**Pull request by rmhowe425**
- [X] closes #57280
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by rmhowe425** [comment]
@mroeschke Pinging on green

**Comment by twoertwein** [comment]
Looking good! You can already make the two overloads keyword-only, if you want to:

```py
    @overload
    def to_string(
        self,
        buf: None = ...,
        *,
        na_rep: str = ...,
```

**Comment by rmhowe425** [comment]
@twoertwein It looks like the two overloaded methods are already keyword only. Is there something specific I need to do?

**Comment by twoertwein** [comment]
> Is there something specific I need to do?

Just need to add two `*,`

```py
    @overload
    def to_string(
        self,
        buf: None = ...,
       *,  # add this
        na_rep: str = ...,

    @overload
    def to_string(
        self,
        buf: FilePath | WriteBuffer[str],
       *, # add this
        na_rep: str = ...,

    @deprecate_nonkeyword_arguments(
    def to_string(
```

**Comment by rmhowe425** [comment]
@twoertwein Pinging on green. 

BTW I didn't know that you can use `*` to mandate the use of keyword args after the `*`. I learned something new today!

**Review by twoertwein — APPROVED** [review]

**Comment by twoertwein** [comment]
Thank you @rmhowe425 !

**Pull request merged**
