### PR TITLE
CI: Fixing benchmark log

### LINKED ISSUE #24061: CI: Log of the benchmarks doesn't keep the line breaks
The log displayed in azure-pipelines for the benchmarks, doesn't keep the line breaks, making it very difficult to read. See: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=4580

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #24061
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by datapythonista** [comment]
@gfyoung, can you take a look at the benchmark log. Will fix the error when you confirm, so we can merge.

**Review by gfyoung — APPROVED** [review]
This is much better.  Thanks!

**Comment by jreback** [comment]
can you point to the errored one?

**Comment by jreback** [comment]
thanks @datapythonista

**Pull request merged**
