### PR TITLE
Fix module name for _LoadSparseFrame

### PR DESCRIPTION
**Pull request by eltoder**

### CODE REVIEW

**Comment by jreback** [comment]
what exactly reproduces this

**Comment by eltoder** [comment]
@jreback that's just not where _LoadSparseFrame is defined. Check the other entry below. pandas.core.sparse.frame does not exist.

**Comment by jreback** [comment]
> @jreback that's just not where _LoadSparseFrame is defined. Check the other entry below. pandas.core.sparse.frame does not exist anymore.

sure i get that. but what broke, we need a test that exercises this. we have older pickles which are deserialized just fine.

**Comment by eltoder** [comment]
You can construct a case by pickling SparseDataFrame with an old version and trying to unpickle it. I couldn't find any unit tests for pickle_compat though.

**Comment by jreback** [comment]
> You can construct a case by pickling SparseDataFrame with an old version and trying to unpickle it. I couldn't find any unit tests for pickle_compat though.

we would for sure need a test case. we *already* have old pickled files that have sparse in them. So my question is how did you get this to fail?

**Comment by eltoder** [comment]
> we would for sure need a test case. we _already_ have old pickled files that have sparse in them.

Mind pointing me to these?

> So my question is how did you get this to fail?

I didn't. I just read the code and it's obviously wrong.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/generate_legacy_storage_files.py and https://github.com/pandas-dev/pandas/tree/master/pandas/tests/io/data/pickle

we are prob not properly testing these legacy things. if you can generate an old pickle then the tests should fail w/o the patch and work with.

**Comment by jbrockmendel** [comment]
@eltoder i know writing tests for old pickles is a PITA, but the process is to use pandas/tests/io/generate_legacy_storage_files.py to write a pickle file containing objects created using old versions.  looks like we don't have any SparseDataFrame objects in there, so you may need to modify the script

**Comment by mroeschke** [comment]
Thanks for the PR, but it appears to have gone stale and just needs some tests to exercise this case. If you're interested in continuing we would be happy to reopen this PR, but closing in the meantime.

**Pull request closed without merging**
