### PR TITLE
TYP: use from __future__ import annotations more - batch 1

### PR DESCRIPTION
**Pull request by simonjayhawkins**
I'm fairly sure that we agreed we would do this but leave it to just before the 1.3 release to reduce the chance of auto backports failing

### CODE REVIEW

**Comment by jreback** [comment]
after you have changed everything should create a rule to avoid Optional if this is possible.

**Comment by simonjayhawkins** [comment]
> after you have changed everything should create a rule to avoid Optional if this is possible.

it is still needed when creating aliases although I could move all aliases definitions into if TYPE_CHECKING blocks or into pandas._typing where that makes sense.

A couple of other points that have arisen from this exercise..
we are using Optional/Union alot in docstrings
some imports from pandas._typing instead of typing... could maybe limit what's reexported from pandas._typing.

**Comment by simonjayhawkins** [comment]
I think is we have a rule that if we import from typing we also use `from __future__ import annotations` and pyupgrade and flake8 should make sure that the typing imports of Union, Optional etc are only used in casts and aliases.

**Comment by MarcoGorelli** [comment]
> I think is we have a rule that if we import from typing we also use `from __future__ import annotations` and pyupgrade and flake8 should make sure that the typing imports of Union, Optional etc are only used in casts and aliases.

Might be easier to require that every file (except for __init__.py , api.py, tests, setup.py, and probably just a handful of others) contains this import. This could be done with `pygrep` and `--negate`, I'll open an issue for this

**Comment by simonjayhawkins** [comment]
sounds good

**Comment by jreback** [comment]
can you rebase thisone

**Comment by mwaskom** [comment]
> after you have changed everything should create a rule to avoid Optional if this is possible.

Sorry for barging in but can someone link me to context for this? My understanding was that the recommendation is to prefer `Optional` over a union with `None`  (but maybe that changed with support for the `|` operator in type hints?)

**Comment by MarcoGorelli** [comment]
@mwaskom yeah it's just to use the latest `| None` syntax, rather than anything against `Optional` specifically

**Comment by ForestMars** [comment]
Since this is needed for 1.3 release: 

https://github.com/pandas-dev/pandas/pull/41939

**Pull request merged**
