### PR TITLE
COMPAT: ensure no warnings on tab completion with Jedi 0.15

### LINKED ISSUE #27900: Tab completion triggers deprecation warnings with latest Jedi (0.15.1)
I reported it at Jedi: https://github.com/davidhalter/jedi/issues/1383 
But opening an issue here as well in case there are workarounds we need to do in pandas itself (last time we did do something: https://github.com/pandas-dev/pandas/pull/16414)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes https://github.com/pandas-dev/pandas/issues/27900

I didn't yet add any tests, because I am not fully sure how to write them (the IPython tests we already have clearly don't work, I suppose the programmatic `ip.Completer.completions(..)` doesn't go through jedi)

### CODE REVIEW

**Review by TomAugspurger — APPROVED** [review]
Tested it out locally. Still a bit slow the first time, but no warnings.

Agreed with backporting.

**Comment by WillAyd** [comment]
What do we need to back port this for? Thought we were only back porting `0.25.X` regressions but this has been around since `0.20.X`?

**Comment by jorisvandenbossche** [comment]
https://github.com/pandas-dev/pandas/issues/27900 is a new issue (due to a recent release of Jedi). The issue that I reference there is several releases old, but that was actually also fixed back then.

**Comment by WillAyd** [comment]
Yea I guess I just fail to see the point of back porting. I thought we wanted to be conservative and only do regressions. 

Is it just a warning or is it actually going to break soon, hence the request for back port?

**Comment by jorisvandenbossche** [comment]
I don't know if you are using tab completion in an ipython console with latest versions of IPython and Jedi, but IMO this is *usability* regression. Getting a flood of warnings each time you press TAB is quite annoying.

**Comment by jorisvandenbossche** [comment]
To be clear, you are certainly right that this is not a regression in the sense that something actually broke. And it depends a bit on your habits if you do tab completion without already starting to type (it only happens if you do `s.<TAB>`, not `s.me<TAB>`). But if you do this regularly to show all possible attributes and methods, the flood of warnings is annoying. And given that is a fairly small / innocent change otherwise, I have a preference to backport this.

**Comment by WillAyd** [comment]
I tried on IPython 7.8.0 with jedi 0.15.1 on macOS with Python 3.7 and didn't get any warnings. Mistake on my end?

image

**Comment by WillAyd** [comment]
Hmm also no issue doing `pd.DataFrame().` + TAB which might be more applicable

**Comment by WillAyd** [comment]
Nevermind looks like I can reproduce with the code you have in #1383

In any case I'd still rather not back port as I don't think it's that critical but will leave to majority

**Comment by TomAugspurger** [comment]
I think this is important enough to backport.

**Comment by jreback** [comment]
thanks @jorisvandenbossche 

I suppose we should have a test that we don't show any Deprecationwarnings (on tests) though thought we did

**Comment by TomAugspurger** [comment]
@jorisvandenbossche can you do the manual backport?

**Comment by jorisvandenbossche** [comment]
Yep will do

> I suppose we should have a test that we don't show any Deprecationwarnings (on tests) though thought we did

Yes, we do have a test for that using IPython. But the programmatic way to do that does not match exactly the interactive console behaviour (it does not use Jedi), so we would need to write a specific test using Jedi.

**Pull request merged**
