### PR TITLE
CI: Unpin Cython

### LINKED ISSUE #54756: Cython 3.0.1 seems to break our compile process
https://app.circleci.com/pipelines/github/pandas-dev/pandas/35409/workflows/a4c9fd69-5f8b-462d-a3ef-af13db8ead32/jobs/103623

cc @lithomas1 maybe

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #54756 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by lithomas1** [comment]
Something is going wrong on the Cython end I think ...

Pushing this to 2.1.1.

**Comment by lithomas1** [comment]
I'm gonna merge to get Cython unpinned for now. Happy to address followups in another PR.

**Comment by rhshadrach** [comment]
@lithomas1 - We've been pinning Cython in the ASVs; should this be unpinned too?

https://github.com/pandas-dev/pandas/blob/753d0ed38adae2acbd928c06cce9a320253fff2e/asv_bench/asv.conf.json#L45

**Comment by rhshadrach** [comment]
Ah - maybe I'm confused. Looks like we're only unpinning Cython in the CI?

**Comment by lithomas1** [comment]
Yeah, ASVs have to stay pinned since there was a perf regression with Cython 3 (so we'd have spurious regressions if we unpinned).

**Pull request merged**
