### PR TITLE
TST/CLN: Remove makeDataFrame

### PR DESCRIPTION
**Pull request by mroeschke**

### CODE REVIEW

**Comment by mroeschke** [comment]
Looks like tests are passing here so merging. Happy to follow up if needed

**Comment by janosh** [comment]
I quite liked `makeDataFrame` (except it being camel-cased). What was the reason for removal? Seems to have caused ~400 lines of boilerplate.

**Comment by mroeschke** [comment]
This was technically a private API in the pandas namespace. Within pandas, this was a legacy API before pytest was adopted and no longer has new usages.

**Comment by janosh** [comment]
True. Maybe it could have been converted into a pytest fixture? it's easy to replace with a fixture in my own code, but I think it's useful for every package author relying on pandas to have such a utility so why not make it a public API?

**Comment by mroeschke** [comment]
pandas API for testing involve assertions rather than data generation which can be very arbitrary. I would recommend using hypothesis' pandas DataFrame generation: https://hypothesis.readthedocs.io/en/latest/numpy.html#pandas

**Pull request merged**
