### PR TITLE
BUG: CSS strings truncated at ":"

### PR DESCRIPTION
**Pull request by invalidarg**
Fixes issue #59623 

Changes `maybe_convert_css_to_tuples` called by `style.map()` so that it no longer truncates the CSS-value at the ":". 

e.g. `background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" id="flag-icons-dk" viewBox="0 0 640 480"><path fill="%23c8102e" d="M0 0h640.1v480H0z"/><path fill="%23fff" d="M205.7 0h68.6v480h-68.6z"/><path fill="%23fff" d="M0 205.7h640.1v68.6H0z"/></svg>');` will no longer be truncated to the tuple `("background-image" ,  "url('data:")`

### CODE REVIEW

**Comment by attack68** [comment]
needs a unit test to demonstrate it solves the test

**Comment by invalidarg** [comment]
@attack68 the failing test seems unralated to my change? I'm not sure how to proceed.


The pre-commit.ci is failing but I'm not sure how to fix. I think it fails due to this string.

```python
msg = (
	"Styles supplied as string must follow CSS rule formats, "
	"for example 'attr: val;'. 'err' was given."
)
```

**Comment by attack68** [comment]
`ruff format` failed. This means you need to install ruff and run `ruff format` in terminal **on your file**. It will edit it according to specifications, i.e. it might remove some whitespace or dangling commas etc.

**Comment by invalidarg** [comment]
> `ruff format` failed. This means you need to install ruff and run `ruff format` in terminal **on your file**. It will edit it according to specifications, i.e. it might remove some whitespace or dangling commas etc.

Thanks. It looks good now I think :)

**Comment by attack68** [comment]
Thanks. LGTM.
This is a nice fix for the issue, although we acknowledge we can't go further without a proper CSS parser.

**Review by attack68 — APPROVED** [review]

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @invalidarg

**Pull request merged**
