### PR TITLE
Single quotes

### PR DESCRIPTION
**Pull request by skorani**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
can you merge master

**Comment by dsaxton** [comment]
Is this identical to https://github.com/pandas-dev/pandas/pull/36878?

**Comment by MarcoGorelli** [comment]
Thanks @skorani - the task here is to apply `blacken-docs`, not to find and replace single quotes with double quotes, let us know if you need help

**Comment by alimcmaster1** [comment]
@skorani - are you still interested in working on this? Otherwise we can close. Thanks

**Comment by dsaxton** [comment]
> @skorani - are you still interested in working on this? Otherwise we can close. Thanks

The relevant issue here has been closed, so I think safe to close this as well. Thanks anyways @skorani for the PR, there are other good first issues if you wanted to take a look at those.

**Pull request closed without merging**
