### PR TITLE
Closes #13688: added scroll to top button to div.footer via doc/_temp…

### LINKED ISSUE #13688: DOCS/ENHANCEMENT: Scroll to top button in documentation
I've been using pandas for a while and am just now starting to contribute. One of the things that has bugged me for a while is that in the docs there is no scroll to top button. Some of the pages get pretty long, and I'm usually without a Home button on my laptop, so I end up *stuck* (exaggeration) deep in the docs. 

I looked into templating with Sphinx and discovered that it's pretty easy to add this feature to all pages. Under pandas/doc/_templates, I created a file layout.html (see code below) that adds a small bit of HTML, CSS, and JS which create a scroll to top button. I kept it to a basic implementation, but feel free if anyone has any suggestions about style or the breakpoint for viewing the button. 

**pandas/doc/_templates/layout.html**
```
{% extends "!layout.html" %} {%- block footer %}
<style type="text/css">
	.scrollToTop {
	    text-align: center;
	    font-weight: bold;
	    position: fixed;
	    bottom: 60px;
	    right: 40px;
	    display: none;
	}
</style>
<a href="#" class="scrollToTop">Scroll To Top</a>
<script type="text/javascript">
$(document).ready(function() {
    //Check to see if the window is top if not then display button
    $(window).scroll(function() {
        if ($(this).scrollTop() > 200) {
            $('.scrollToTop').fadeIn();
        } else {
            $('.scrollToTop').fadeOut();
        }
    });

    //Click event to scroll to top
    $('.scrollToTop').click(function() {
        $('html, body').animate({
            scrollTop: 0
        }, 500);
        return false;
    });
});
</script>
{% endblock %}
```

### PR DESCRIPTION
**Pull request by shawnheide**
- [x] closes #13688
- [ ] tests added / passed
- [ ] passes `git diff upstream/master | flake8 --diff`
- [ ] whatsnew entry

Added scroll to top feature to documentation div.footer using Sphinx template

### CODE REVIEW

**Comment by jreback** [comment]
I don't think this is the right template

**Comment by jreback** [comment]
well did the docs build?

**Comment by shawnheide** [comment]
Yes, they build just fine as far as I can tell and the code is inserted just above the </body>. 

Here's the bottom of my build for **index.html**
```
    <style type="text/css">
    .scrollToTop {
        text-align: center;
        font-weight: bold;
        position: fixed;
        bottom: 60px;
        right: 40px;
        display: none;
    }
    </style>
    <a href="#" class="scrollToTop">Scroll To Top</a>
    <script type="text/javascript">
    $(document).ready(function() {
        //Check to see if the window is top if not then display button
        $(window).scroll(function() {
            if ($(this).scrollTop() > 200) {
                $('.scrollToTop').fadeIn();
            } else {
                $('.scrollToTop').fadeOut();
            }
        });

        //Click event to scroll to top
        $('.scrollToTop').click(function() {
            $('html, body').animate({
                scrollTop: 0
            }, 500);
            return false;
        });
    });
    </script>
</body>
```
screen shot 2016-07-17 at 12 36 40 pm

**Comment by shawnheide** [comment]
@jreback, just curious if you had any other feedback on this

**Comment by jorisvandenbossche** [comment]
@shawnheide Can you explain again why this cannot be added to the doc/source/themes/nature_with_gtoc/static/layout.html ? Can't you add the footer there as well?

**Comment by jorisvandenbossche** [comment]
But to be clear, the enhancement itself is really nice!

**Comment by shawnheide** [comment]
@jorisvandenbossche No reason it couldn't be added. In all honesty I just got a little burnt out on Sphinx and didn't look into last week. I moved it to the theme as you and Jeff requested and changed the commit. Thanks for following up on this.

**Comment by jorisvandenbossche** [comment]
@shawnheide Thanks!

**Pull request merged**
