### PR TITLE
DOC: Edited/proofread the website's getting started page for readability

### PR DESCRIPTION
**Pull request by shindelr**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

I noticed that the Getting Started page had some typos and issues with sentence structure. I went through and modified index.rst to reflect what I hope are some quality changes in readability. 

Also, I'm pretty new to GitHub and I had some trouble with the commit process. Somehow I included 12 images in my commit without modifying them, so I apologize in advance for the clutter. 

Thanks for checking out my ideas!

### CODE REVIEW

**Review by chaityacshah — COMMENTED** [review]
What are all these new images for?

**Comment by shindelr** [comment]
I don't believe they're new, I think they're already part of the project. I had accidentally staged them and was unable to remove them from my commit. I didn't make any modifications to any images, or add/remove any images. The only thing I meant to be in this pr were my proposed changes to `index.rst`.  Sorry about that!

**Comment by chaityacshah** [comment]
All good. You can git rebase to keep the commit history clean.

**Comment by shindelr** [comment]
Great, should I go ahead an close this pr? Then re-commit rebased with a clean commit history?

**Comment by chaityacshah** [comment]
Yes, please!

**Comment by mroeschke** [comment]
> Great, should I go ahead an close this pr? Then re-commit rebased with a clean commit history, then open a new pr?

You can just run 

```bash
git checkout upstream/main doc/
git commit -m"Undo doc changes"
git push origin HEAD
```

And update this PR

**Comment by shindelr** [comment]
Alright, thank you! I followed those steps and pushed the changes. Just to be clear, when I update the branch, should I select the rebase option? 
Screenshot 2024-06-01 at 2 00 06 PM

**Comment by shindelr** [comment]
Okay, I followed the steps from @mroeschke and updated the PR with a rebase, so the second commit has the changes to index.rst but does not have the random images. Is this correct?

**Review by chaityacshah — APPROVED** [review]

**Comment by mroeschke** [comment]
It looks like your latest push still shows a diff for the images. I guess I would recommend creating a new pull request with just the changes to `doc/source/getting_started/index.rst`.

(Also as a best practice, I would recommend creating a branch from your `main` branch and create a pull request from that branch)

**Pull request closed without merging**
