### PR TITLE
BUG: Fix small memory access errors in ujson objToJSON.c

### PR DESCRIPTION
**Pull request by seberg**
These were found (and validated fixed) using valgrind. It is likely
that none of these changes should create any issues (except maybe
on a debug build of python?). But silencing valgrind warnings is
good on its own, to ease possible future debugging using valgrind.

----

NOTE: I removed skipping of `test_astype_generic_timestamp_no_frequency`, this is just out of curiosity, I would be very surprised if it made a difference. So this should probably be only merged after undoing the test change.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
JSON changes look good

Out of curiosity is there a guide you can share for running this with valgrind? I’ve tried unsuccessfully in the past but would be interested in knowing how

**Comment by seberg** [comment]
There is no secret, in this case I did not even to bother debug builds. The only thing to remember nowadays is to use `PYTHONMALLOC=malloc` as an environment variable, otherwise you will get thousands of false positives (and generally less useful output).

**Comment by seberg** [comment]
OK, this (unsurprisingly) did not change anything with the test, so removed it from the PR, I guess it should be all set, considering that it is a tiny bug fix really?

**Comment by jbrockmendel** [comment]
Travis fail is unrelated, has been affecting a bunch of tests for the last few days

**Review by WillAyd — APPROVED** [review]
Lgtm

**Comment by jreback** [comment]
thanks @seberg

**Pull request merged**
