### PR TITLE
Follow-up: XLSB Support

### LINKED ISSUE #8540: Enhancement: XLSB support in read_excel()
openpyxl and xlrd do not support XLSB. I'm curious if anyone has taken a look at integrating (more like creating) the functionality into Pandas. Looks like it could be a Python package in it self. 

Spec from Microsoft:
http://msdn.microsoft.com/en-us/library/cc313133(v=office.12).aspx

### PR DESCRIPTION
**Pull request by Rik-de-Kort**
Updated min version for `pyxlsb` to 1.0.6 and removed the now unnecessary xfail for read from url. Turns out the other xfail is actually unnecessary so I've removed it.

Question: is my name supposed to show up in the contributors list?

- [X] closes #8540
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
@Rik-de-Kort yea your name should auto-generate as a contributor when we release

Thanks!

**Comment by Rik-de-Kort** [comment]
> @Rik-de-Kort yea your name should auto-generate as a contributor when we release
> 
> Thanks!

Excellent, and you're welcome. Maybe next patch we go a bit quicker, eh? :P

**Comment by Rik-de-Kort** [comment]
> @Rik-de-Kort yea your name should auto-generate as a contributor when we release
> 
> Thanks!

@WillAyd Happy to see the release is out, with my code :D However, my name does not appear to have been auto-generated in the contributors list. I do have the tag here though. Any ideas?

**Comment by WillAyd** [comment]
Hmm @TomAugspurger any ideas on the contributor piece? Original PR of #29836 was part of 1.0

**Pull request merged**
