### PR TITLE
Remove pyx dependencies from setup

### PR DESCRIPTION
**Pull request by jbrockmendel**
See discussion in #17419

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by gfyoung** [comment]
@jbrockmendel : The builds are passing, so can't complain, but just curious : is there anything further that can be done now that you've dropped these dependencies?

**Comment by jreback** [comment]
@jbrockmendel 
does ``scripts/build_release_for_dist.sh`` work locally?

**Comment by jbrockmendel** [comment]
> does `scripts/build_release_for_dist.sh` work locally?

Just tried it and it went through OK.

> but just curious : is there anything further that can be done now that you've dropped these dependencies?

Not sure what you have in mind.  This doesn't affect the _actual_ dependencies, is just about the rules for declaring cython deps.

**Comment by jbrockmendel** [comment]
There _are_ some pretty significant simplifications that can be made once timezone functions get moved out of `tslib`, and another big batch if/when `NaT` becomes standalone.  Is that what you're referring to?

**Comment by jreback** [comment]
ok this looks fine. ping on green.

**Comment by jreback** [comment]
ok going to merge. I hope this doesn't bite us from something we are not testing, possibly on the development side.

**Comment by jbrockmendel** [comment]
Poking at this further has me confused.  It is not clear to me what is the distinction is between the `'include'` vs `'depends'` vs `'pxdfiles'`.

I saw that the `ext_data` entries that don't include a `'include'` key get the default include of `['pandas/_libs/src/klib', 'pandas/_libs/src']`.  Many of the `_libs` extensions only need one or two of the files in `_libs/src`, so I tried specifying those explicitly and pinning `include` entries to `[]` in the hopes of trimming the build time.  For the most part this led to compile-time errors complaining that there is no "datetime/np_datetime.h" file.  Lots of reasonable explanations for that, no big deal.

More noteworthy is that removing "compat_helper.h" from `lib_depends` doesn't seem to matter.  The only explanation I've come up with is that the `ext_data['_libs.lib']['include']` gets set to the default value of `common_include` which is `['pandas/_libs/src/klib', 'pandas/_libs/src']` and since "compat_helper.h" is in the "pandas/_libs/src" directory, that is sufficient.  But then why are there separate `'include'` and `'depends'` keys?

**Comment by jreback** [comment]
you should dig into the cython docs to see

**Comment by jbrockmendel** [comment]
I have.  I've also used Google.

These args are getting passed to `distutils.extension.Extension`, so I don't think it is cython-specific.  (Yes, I've looked through the distutils docs).

**Pull request merged**
