### PR TITLE
consistent imports in text.rst

### PR DESCRIPTION
**Pull request by SebastianRubbert**

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. can you squash. ping when pushed / green.

**Comment by jreback** [comment]
@SebastianRubbert docs still build fully? (note that we don't actually test this on travis, except after it is merged).

**Comment by SebastianRubbert** [comment]
I rebuilt the doc and I did not have errors in the files I edited.

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/5803e4c7417130536e4c12412c03c5bbaac60219

thanks!

**Pull request closed without merging**
