### PR TITLE
CI: transition powershell-> bash

### PR DESCRIPTION
**Pull request by jbrockmendel**
xref #26344

If this works, i think the remaining places to bashify are
- identical powerhsell commands in windows.yml and posix.yml to check for test failures
- conda.recipe/bld.bat (do we need this directory at all?)
- test.bat, test_fast.bat (do we need the bash versions of these?)

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @jbrockmendel

**Comment by jbrockmendel** [comment]
@jreback any idea if we need conda.recipe or test/test_fast files mentioned in the OP?  (or binstar.yml, that looks you-specific)

**Comment by jreback** [comment]
binstar is really old can remove

the test_fast are local scripts
need a canonical way to run all tests
how do u usually do it?

**Comment by jbrockmendel** [comment]
how do u usually do it?

In my .bash_aliases file i have

```
gitd () {
	BRANCH=$1
	rm -rf ../$BRANCH
	git worktree prune
	git branch -D $BRANCH
}

pbranch () {
	BRANCH=$1
	git branch $BRANCH
	git worktree add ../$BRANCH $BRANCH
	cd ..
	cd $BRANCH
	python3 setup.py build_ext --inplace
}

alias ptest="python3 -m pytest pandas/tests --skip-slow --skip-db"
alias pflake="git diff --name-only | grep '\.py$' | xargs flake8"
alias psort="git diff --name-only | grep '\.py$' | xargs isort"
alias pblack="git diff --name-only | grep '\.py$' | xargs black"
alias pbuild="python3 setup.py build_ext --inplace"
alias ppull="git pull upstream master"

```

**Comment by jbrockmendel** [comment]
>  need a canonical way to run all tests

if we want to support this robustly, we might want to consider going back to `tox`

**Comment by WillAyd** [comment]
@jbrockmendel the one disadvantage to your commands versus pytest would be the lack of parallel execution (i.e. `-n 8` flag). Indifferent on getting rid of the file but if we do probably worth specifying the parallel execution ability as it can save significant time when running tests

**Comment by jreback** [comment]
so would be nice to push some of these commands to the makefile:)

also not averse to having. single canonical test_fast.sh (which we basically have now)

**Pull request merged**
