### PR TITLE
style: fix import format at pandas/core/computation

### PR DESCRIPTION
**Pull request by streeck**
- [ ] xref #23334 
- [x] passes `git diff master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by alimcmaster1 — CHANGES_REQUESTED** [review]
Thanks for the PR!

pandas/core/computation/scope.py:50: in <module>
    'Timestamp': pandas._libs.tslib.Timestamp,
E   NameError: name 'pandas' is not defined

We seem to have removed some required imports here. Please can you run code_checks locally and see if you can fix

**Comment by jreback** [comment]
can you merge master, we just updated the isort cfg

**Comment by jreback** [comment]
can you merge master and update

**Comment by streeck** [comment]
Will do later today +  the fix

**Comment by jreback** [comment]
thanks !

**Pull request merged**
