### PR TITLE
DEPR: Remove weekday_name

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] xref #18164
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

**Comment by jbrockmendel** [comment]
@mroeschke CI should pass if you rebase

**Comment by mroeschke** [comment]
All green.

**Comment by jbrockmendel** [comment]
Thanks @mroeschke

**Pull request merged**
