### PR TITLE
Using Literal["a"] instead of str in generic.py

### PR DESCRIPTION
**Pull request by kevx82**
Specifies limit_area in interpolate and how in asfreq more precisely.

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by twoertwein — APPROVED** [review]
Looks good to me! Can you please resolve the conflict?

**Review by phofl — APPROVED** [review]
Yep good to merge after conflicts are resolved.

**Comment by kevx82** [comment]
conflict resolved.

**Comment by twoertwein** [comment]
Thanks @kevx82 !

**Pull request merged**
