### PR TITLE
DEPR: deprecate Index.is_interval

### PR DESCRIPTION
**Pull request by ShisuiUzumaki**
- [ ] progress towards https://github.com/pandas-dev/pandas/issues/50042
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/v2.0.0.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by ShisuiUzumaki** [comment]
@topper-123 could you review

**Comment by topper-123** [comment]
Looks good. The failure looks unrelated, but the ARM tests should be run again just in case.

Like @phofl said in #50178, it may be a while before we merge. I can keep an eye on this getting in in due time, if you want to focus on other things.

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @ShisuiUzumaki 

@phofl I see there are just few deprecations in #30228 pending enforcement. Are we still waiting for them to merge PRs with new deprecations?

@ShisuiUzumaki You'll have to merge main and fix the conflicts in what's new before we can merge.

**Comment by jbrockmendel** [comment]
Ideally I'd like to get #49560 and #49715 in before adding new deprecations, but not a huge deal.  Other than that I'm fine with it as long as @mroeschke is.

**Comment by mroeschke** [comment]
Yeah ideally I would like to get all the old 1.x deprecations out before adding new ones, but that might not be realistic to block given wanting to release 2.0 next month or so.

I would be fine with merging new ones soon as long as we start a new deprecation tracker for 3.0 issue documenting these new ones

**Comment by ShisuiUzumaki** [comment]
> lgtm, thanks @ShisuiUzumaki
> 
> @phofl I see there are just few deprecations in #30228 pending enforcement. Are we still waiting for them to merge PRs with new deprecations?
> 
> @ShisuiUzumaki You'll have to merge main and fix the conflicts in what's new before we can merge.

Which branch do I have to merge `main` into? Are you referring to `ShisuiUzumaki:index_dtype_api_deprecation`

**Comment by datapythonista** [comment]
> I would be fine with merging new ones soon as long as we start a new deprecation tracker for 3.0 issue documenting these new ones

I created #50578 to track new deprecations. I also created #50579 to keep track of deprecations pending enforcement. What it makes sense to me is to have a detailed look at the code base, see what else is pending enforcement, update #50579, and when we're confident we've got everything pending enforcement under control, then we can start merging PRs with new deprecations. @mroeschke @phofl @jbrockmendel is this more or less what you have in mind to hold merging new deprecations before the rest are enforced? To make it easier to verify we don't forget any?

**Comment by phofl** [comment]
Needs a rebase, good to merge afterwards

**Comment by topper-123** [comment]
Ping. Can you rebase.

**Comment by ShisuiUzumaki** [comment]
> Ping. Can you rebase.

On it!

**Comment by ShisuiUzumaki** [comment]
> Ping. Can you rebase.

Have a look!

**Comment by topper-123** [comment]
YEah, you need to fix the ‘. pre-commit-config.yaml ‘, else looks good and ready to merge.

**Comment by ShisuiUzumaki** [comment]
> YEah, you need to fix the ‘. pre-commit-config.yaml ‘, else looks good and ready to merge.

I think it is done

**Comment by topper-123** [comment]
There is still a change in '.pre-commit-config.yaml' in this PR?

**Comment by ShisuiUzumaki** [comment]
> There is still a change in '.pre-commit-config.yaml' in this PR?

You mean from the main branch?

**Comment by topper-123** [comment]
If you go to https://github.com/pandas-dev/pandas/pull/50196/files, you can see there's still a change in the file `.pre-commit-config.yaml`. Can you remove that change.

**Comment by ShisuiUzumaki** [comment]
> If you go to https://github.com/pandas-dev/pandas/pull/50196/files, you can see there's still a change in the file `.pre-commit-config.yaml`. Can you remove that change.

Sure!

**Comment by ShisuiUzumaki** [comment]
> If you go to https://github.com/pandas-dev/pandas/pull/50196/files, you can see there's still a change in the file `.pre-commit-config.yaml`. Can you remove that change.

Is it good to go now?

**Review by topper-123 — APPROVED** [review]

**Comment by topper-123** [comment]
Yeah, it's good, Thanks @ShisuiUzumaki.

**Pull request merged**
