### PR TITLE
TYP: internals.pyi

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase

**Comment by jbrockmendel** [comment]
rebased + greenish

**Comment by jreback** [comment]
cool. any ideas about the failures on master?

**Comment by jreback** [comment]
e.g. https://github.com/pandas-dev/pandas/runs/2220118625

**Comment by jbrockmendel** [comment]
> cool. any ideas about the failures on master?

looking into it now

BTW the other open TYP PRs all play together nicely

**Pull request merged**
