### PR TITLE
CI: Move MacOS build from Azure to GHA

### PR DESCRIPTION
**Pull request by mroeschke**
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Similar to https://github.com/pandas-dev/pandas/pull/46960

### CODE REVIEW

**Review by lithomas1 — COMMENTED** [review]
Thanks for doing this. Should we add slow builds too? (I know we don't run any currently, but would be nice to have that coverage on Windows and MacOS too)

**Comment by jreback** [comment]
> Thanks for doing this. Should we add slow builds too? (I know we don't run any currently, but would be nice to have that coverage on Windows and MacOS too)

no objections, though not sure this adds a whole lot (but let's do in another PR).

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by mroeschke** [comment]
> Thanks for doing this. Should we add slow builds too? (I know we don't run any currently, but would be nice to have that coverage on Windows and MacOS too)

I can try removing the `not slow` mark from the current Windows/MacOS builds (I'm not fond of create whole separate build for those test)

**Pull request merged**
