### PR TITLE
ERR: raise on python in object hashing, only supporting strings, nulls

### PR DESCRIPTION
**Pull request by jreback**
xref #14729

### CODE REVIEW

**Comment by jreback** [comment]
cc @mikegraham 
cc @mrocklin

**Comment by mikegraham** [comment]
Awesome, I think this is a really worth while restriction. Thanks!

**Comment by mikegraham** [comment]
Initially you were worried about things like tuples for multiindices -- did you decide that wasn't really a concern?

**Comment by jreback** [comment]
problem with tuples is that they can contain arbitrary things - so punting for now

**Pull request closed without merging**
