### PR TITLE
DEPR: Index.get_loc with method

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

We only use it one place internally; this will allow us to simplify get_loc, which will marginally improve perf.

### CODE REVIEW

**Comment by shoyer** [comment]
We can probably work around it, but just as a heads up, this is also used externally in Xarray in a pretty extensively used code path (#5721).

**Comment by lukemanley** [comment]
Is it correct that the `tolerance` argument will also need to be removed as part of this? I think the `tolerence` is only relevant to inexact methods. The `tolerance` argument is not currently marked as deprecated, but maybe its implicit given the relationship?

**Comment by jbrockmendel** [comment]
> Is it correct that the tolerance argument will also need to be removed as part of this? I

yes.

**Comment by jbrockmendel** [comment]
trying to enforce this I found that for DatetimeIndex cases the alternative `get_indexer([key], ...)` doesn't work because get_loc does string parsing that get_indexer doesn't.

I'd be OK with either a) requiring users to do the parsing themselves before calling get_indexer or b) reverting this deprecation.

**Pull request merged**
