### PR TITLE
PERF: fix regression in reductions for boolean/integer data (assume no missing values)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Address performance regression in https://github.com/pandas-dev/pandas/pull/41711/files#r647515492 (https://pandas.pydata.org/speed/pandas/#series_methods.All.time_all?python=3.8&Cython=0.29.21&p-N=1000000&p-case='fast'&p-dtype='bool'&commits=9231b495-44237a58)

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]
Thanks @jorisvandenbossche I perhaps should have done this originally for the regression fix in 1.2.4 https://github.com/pandas-dev/pandas/pull/40143#issuecomment-787945291, but was hesitant to change lower level code.

**Comment by jorisvandenbossche** [comment]
Yeah, I think this is not lower level than the later PR #41711 (which was also backported), and IMO this should be safe for a backport.

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche I didn't notice #41911 (was on the wrong milestone) with a different fix.

**Comment by jreback** [comment]
merged #41911

**Pull request closed without merging**
