### PR TITLE
REF: make pd._testing directory, split out asserters

### PR DESCRIPTION
**Pull request by jbrockmendel**
Scattered throughout the tests we have other helpers like assert_block_equal that probably belong in `tm`.  Before trying to collect all of these, it makes sense to split this already-cumbersome module.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Good idea on splitting it. But while doing it, can you split a bit further? For example all `make...` functions can go in one file (eg "generators" or something). 

I personally prefer to split this in one go now (if we plan to further split it). Moving things around is annoying for git blame, so prefer to have it done in one step. And it also doesn't seem hard to further split it here

**Comment by jbrockmendel** [comment]
> I personally prefer to split this in one go now

sounds good

**Comment by jbrockmendel** [comment]
@jorisvandenbossche this isn't viable exactly as-is because of mypy complaints, but id like to get your thoughts on the general layout

**Comment by jbrockmendel** [comment]
Closing to clear the queue, will revisit

**Comment by jorisvandenbossche** [comment]
>  this isn't viable exactly as-is because of mypy complaints,

Can't you just silence mypy then for now on this directory? (as it is doing for `_testing.py` now)

Layout looks good to me! Seems logical groups

**Comment by jbrockmendel** [comment]
> Layout looks good to me! Seems logical groups

Great, any other groupings to get more stuff out of `__init__`?

Once the PR queue quiets down ill try to sort out the mypy issues.

**Pull request closed without merging**
