### PR TITLE
CI: remove no-longer-available conda versions

### LINKED ISSUE #15214: DEPS: drop bottleneck < 1.0
should prob address #9422 simultaneously.

### PR DESCRIPTION
**Pull request by jreback**
closes #15214, remove bottleneck < 1.0.0
changes CI min of xlsxwriter to 0.5.2

removing our ``pandas`` channel as well (which held some really old versions of things).

### CODE REVIEW

**Comment by jreback** [comment]
seems conda simply 'removed' old versions of packages (xlsxwriter 0.4.6 and bottleneck 0.8.0). They are pretty old so adjusting the CI.

**Comment by jorisvandenbossche** [comment]
> seems conda simply 'removed' old versions of packages (xlsxwriter 0.4.6 and bottleneck 0.8.0). They are pretty old so adjusting the CI.

there are some problems with conda-forge at the moment, so it might also be you are running in similar things (https://github.com/Anaconda-Platform/support/issues/126-

**Comment by jorisvandenbossche** [comment]
Ah, you already opened an issue :-)

**Comment by jreback** [comment]
yeah I think I fixed some of the older packages issues, but this is an odd one.

**Pull request merged**
