### PR TITLE
CI: isort ci

### PR DESCRIPTION
**Pull request by alimcmaster1**
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

asv_bench and doc dir where [added](https://github.com/pandas-dev/pandas/pull/24092/files) to the isort skip section. We should actually check this directory in CI.

Checking doc dir is more effort that its worth ( barely any .py files ) so let's just leave this.

### CODE REVIEW

**Review by gfyoung — APPROVED** [review]
cc @datapythonista

**Comment by datapythonista** [comment]
I understand the point of the PR, and this makes things more consistent, but I'm not a big fan of what we did with isort. So making the list of excludes even longer, seems the opposite direction we should take.

Not a problem with getting this merged, but would be nice to see a solution of a very strict and complex and not-human friendly validation of half of the code base, and no validation in the rest.

**Comment by datapythonista** [comment]
Sorry, just saw that almost all the code has been isorted, didn't see that before. I guess this makes more sense then.

**Comment by alimcmaster1** [comment]
hey thanks for the comments @datapythonista , how come you are not a fan of isort out of interest? - In my mind we previously had an undocumented set of rules for what import order should look like ( my dependency structure ) - so now we don't need to battle on PRs about what that order should be, I just run one command and don't have to worry/often IDE's like to change the import order too ( "optimize imports" in pycharm for example ).
 
I will follow up after this PR to isort the asv_bench directory.

**Comment by datapythonista** [comment]
afaik none of the pandas devs is able to sort the imports properly unless using isort. I'm happy we respect pep8 and we have the imports sorted by stdlib, third-party and pandas. But the rest doesn't add any value, but extra steps and CI problems even for files with few imports.

**Comment by jreback** [comment]
using isort is much better than the alternative - random changes due to import ordering and re-ordering

**Comment by jreback** [comment]
can you merge master

**Comment by jreback** [comment]
thanks @alimcmaster1

**Pull request merged**
