### PR TITLE
Index union sort hack

### LINKED ISSUE #17376: Union of indexes of tuples is not sorted
#### Code Sample, a copy-pastable example if possible

```python
aidx1 = np.array([(1, 'A'), (2, 'A'), (1, 'B'), (2, 'B')],
                 dtype=[('num', int), ('let', 'a1')])
aidx2 = np.array([(1, 'A'), (2, 'A'), (1, 'B'),
                  (2, 'B'), (1, 'C'), (2, 'C')],
                 dtype=[('num', int), ('let', 'a1')])

idx1 = pd.Index(aidx1)
idx2 = pd.Index(aidx2)

idx1.union(idx2)
```

Result: ``Index([(1, b'A'), (2, b'A'), (1, b'B'), (2, b'B'), (1, b'C'), (2, b'C')], dtype='object')``

This was already known (the example above is copied from [the tests](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexes/test_base.py#L1332)), but I don't see it reported anywhere.

#### Problem description

The ``Index.union`` docs states the result is sorted if possible - and it is possible with the above.

#### Expected Output

``` python
In [4]: idx1.union(idx2).sort_values()
Out[4]: Index([(1, b'A'), (1, b'B'), (1, b'C'), (2, b'A'), (2, b'B'), (2, b'C')], dtype='object')
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 0d676a3ccf1d7aa986416a7488b941496f936d98
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.21.0.dev+405.g0d676a3cc
pytest: 3.0.6
pip: 9.0.1
setuptools: None
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 5.1.0.dev
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

### PR DESCRIPTION
**Pull request by toobaz**
- [x] closes #17376
- [x] tests added / passed
- [x] passes `git diff master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

This is an attempt to adapt #17378 according to @gfyoung 's suggestions.

(I do plan to investigate more in depth the problem in Windows, I just won't be able to do it soon)

### CODE REVIEW

**Comment by gfyoung** [comment]
@toobaz : Quick question.  Does this supersede #17378 (i.e. should we close that?)

**Comment by toobaz** [comment]
> @toobaz : Quick question: does this supersede #17378 (i.e. should we close that?)

... if this passes tests, I guess we will.

**Comment by gfyoung** [comment]
> if this passes tests, I guess we will.

**Comment by jreback** [comment]
closing as stale, if you want to continue working, pls ping and we can re-open. you will need to merge master.

**Pull request closed without merging**
