### PR TITLE
PEP: pandas/core round 3 (generic, groupby, index)

### PR DESCRIPTION
**Pull request by rockg**
yapf with manual modifications for error strings and bad yapf formatting.

### CODE REVIEW

**Comment by rockg** [comment]
No github diffs again!  

There are some pieces of code that I think can be removed but want to confirm:
[index.py](https://github.com/pydata/pandas/blob/master/pandas/core/index.py#L1029) i/j are not used anywhere.
[groupby.py](https://github.com/pydata/pandas/blob/master/pandas/core/groupby.py#L1717) how can this work?  `agg_func` is not defined.

**Comment by jreback** [comment]
``index`` i/j ok to remove

**Comment by jreback** [comment]
yeh that looks not tested, it for a transform on a Panel or greater. I think just raise ``NotImplemented`` (if the ndim >= 3) & remove the 2nd clause (where you noted). If nothing breaks in the test suite then ok!

**Comment by rockg** [comment]
I assume it should be ```transform_func(result[:, :, i], chunk, comp_ids, accum)```

**Comment by rockg** [comment]
k, I can do that.

**Comment by jorisvandenbossche** [comment]
@rockg I would keep style changes and code clean-up (as in removal of unused code) strictly separated (at least in a separate commit). Just to be sure, in case we overlooked something, then it is not burried in a gigantic commit for which you can't see the diff.

**Comment by rockg** [comment]
The main goal of this exercise is to make flake8 passing and cleanup some style were necessary.  What I cleaned out were unused variables reported by flake8 and, as a result, I don't see a problem including that here.

**Comment by wesm** [comment]
@rockg I've been putting `# noqa` on these lines and adding a `TODO` comment to come back and investigate

**Comment by wesm** [comment]
This is especially important in unit tests where I suspect that there are some test cases that may have skipped some intended checks

**Comment by rockg** [comment]
Okay, that seems reasonable.

**Comment by jreback** [comment]
ok, rebasing ``core/groupby.py`` is going to be painful for #11841 but go ahead (my touches are mostly reorg anyhow)

**Comment by wesm** [comment]
Is this good to merge?

**Comment by wesm** [comment]
I'll leave this to @jreback with the pending rebase

**Comment by jreback** [comment]
if u want to remove groupby.py from this would be great (I'll catch that in resample fixes)

otherwise lgtm

**Comment by wesm** [comment]
thanks! we're almost there =)

**Pull request closed without merging**
