### PR TITLE
  Edit DOC: consistent imports (GH9886) part V

### PR DESCRIPTION
**Pull request by springcoil**
Updated - but no idea why this is such a messed up branch.

### CODE REVIEW

**Comment by jreback** [comment]
needs a rebase

**Comment by jorisvandenbossche** [comment]
@springcoil I don't really understand how you manage to such a mess of your commits :-) (we had better looked at it together yesterday)

Some things:
- if you start to work on something new (eg updating the imports in merging.rst), no rebase or something is needed. Just be sure to start your branch from the latest upstream master. Rebasing is only needed once there are conflicts because other people have changed the same file. Which is not the case here at all.

- To start a new branch from upstream master, just do:

```
git checkout master
git fetch upstream
git merge --ff-only upstream/master
git checkout -b new_branch
```

- When you need to rebase (which will probably not be the case here if you did like above), simply do the following:
  ```
git fetch upstream
git checkout new_branch
git rebase upstream/master
  ```

  and this should almost always work.

Don't close this PR, just try to clean up this branch and force push. To clean this up, do exactly the following:

```
git fetch upstream
git checkout merging
git rebase -i upstream/master
# then in overview of commits, remove all commits apart from the last one 'updating the docs' (the only commit with the actual changes I think), and leave that one as 'pick'
git push -f origin merging
```

If you do exactly as above, this should be fine

**Comment by springcoil** [comment]
Ok will do that thanks.
ᐧ

On Mon, Aug 31, 2015 at 12:45 PM, Joris Van den Bossche <
notifications@github.com> wrote:

> @springcoil <https://github.com/springcoil> I don't really understand how
> you manage to such a mess of your commits :-) (we had better looked at it
> together yesterday)
>
> Some things:
>
>    -
>
>    if you start to work on something new (eg updating the imports in
>    merging.rst), no rebase or something is needed. Just be sure to start your
>    branch from the latest upstream master. Rebasing is only needed once there
>    are conflicts because other people have changed the same file. Which is not
>    the case here at all.
>    -
>
>    To start a new branch from upstream master, just do:
>
> git checkout master
> git fetch upstream
> git merge --ff-only upstream/master
> git checkout -b new_branch
>
>
>    -
>
>    When you need to rebase (which will probably not be the case here if
>    you did like above), simply do the following:
>
>    git fetch upstream
>    git checkout new_branch
>    git rebase upstream/master
>
>    and this should almost always work.
>
> Don't close this PR, just try to clean up this branch and force push. To
> clean this up, do exactly the following:
>
> git fetch upstream
> git checkout merging
> git rebase -i upstream/master
> # then in overview of commits, remove all commits apart from the last one 'updating the docs' (the only commit with the actual changes I think), and leave that one as 'pick'
> git push -f origin merging
>
> If you do exactly as above, this should be fine
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/pandas/pull/10941#issuecomment-136330541>.
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by springcoil** [comment]
Thanks for the help - @jreback and @jorisvandenbossche Ok @jorisvandenbossche all the checks passed. Is this ready to be merged?

**Comment by jorisvandenbossche** [comment]
Yep, thanks!

**Pull request merged**
