### PR TITLE
DEPR: Deprecate NDFrame.filter

### PR DESCRIPTION
**Pull request by topper-123**
- [ ] xref #26642
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

I propose to deprecate (DataFrame|Series).filter. The method's functionality is already in the ``.loc``method, except the regex functionality, for which I've made a proposal adding regex functionality  to ``.loc`` in #27363.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
ok,  we need to decide on #27363 first

**Comment by jreback** [comment]
can you rebase again.

**Comment by topper-123** [comment]
I've rebased. As you noted, this depends on #27363.

**Comment by jbrockmendel** [comment]
@topper-123 im trying to clear the PR backlog; can this be closed pending #27363?

**Comment by WillAyd** [comment]
Knowing the outstanding issue is around regex capability, maybe we should just deprecate all keywords from filter for now that aren't regex?

**Comment by topper-123** [comment]
That sounds like a stepping stone to deprecating. Wouldn't it make more sense then to just deprecate this method before 1.0 is released?

**Comment by WillAyd** [comment]
I don't *think* we'd want to outright deprecate without a replacement for the regex unless we instruct users to do `df[(re.search(x) for x in df.columns)]`

**Comment by topper-123** [comment]
Oh yes, I meant choose another way to select by regex at the same time, sorry.

**Comment by jreback** [comment]
can you merge master and will look again

**Comment by topper-123** [comment]
I've rebased.

I do think an alternative should be settled on for the regex use case and I've had two proposals that were not accepted. So I'm not sure where this is floating currently?

**Comment by WillAyd** [comment]
Thanks for the PR! But I think agreement on approach here is still outstanding. If something you want to drive forward can revisit discussion in issue first

**Pull request closed without merging**
