### PR TITLE
fixed docstring error with pandas.Series.plot.area:Unknown parameter: {'stacked'}

### PR DESCRIPTION
**Pull request by joshuabello2550**
When you run python `./scripts/validate_docstrings.py --errors=PR02`, one of the errors is `/home/pandas/pandas/plotting/_core.py:1470:PR02:pandas.Series.plot.area:Unknown parameters {'stacked'}`

The error I believe is because "stacked" is declared in the docstring, but is not a parameter within the function. Even though stacked is only passed in when setting stacked to False, it should still be defined in the function parameter.

- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Comment by joshuabello2550** [comment]
Hi, I don't believe the changes I have made, contributed to the errors in the checks. Could you please clarify?

**Comment by mroeschke** [comment]
> Hi, I don't believe the changes I have made, contributed to the errors in the checks. Could you please clarify?

There are some related test failures: https://github.com/pandas-dev/pandas/runs/7811767621?check_suite_focus=true

**Comment by joshuabello2550** [comment]
Hi, I have tried to reproduce the test cases that are failing locally but could not. How can I go about debugging these errors?

**Comment by mroeschke** [comment]
The issues look unrelated to this PR. Could you merge in main once more?

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @joshuabello2550

**Pull request merged**
