### PR TITLE
REF: collect arithmetic benchmarks

### PR DESCRIPTION
**Pull request by jbrockmendel**
ATM these are scattered, making it tough to a) run just arithmetic-relevant benchmarks and b) determine what we have good benchmark coverage for.

This collects the scattered benchmarks in one place, cleaning up and fleshing these out is for a separate pass.

I also intend to do something analogous for indexing benchmarks.

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
sure I'd be OK with this

**Comment by jorisvandenbossche** [comment]
Note that renaming benchmarks like this defeats somewhat the function of the tracking of benchmarks over time (not when comparing manually two commits, as the old commit is run with the new benchmarks, but for the benchmark machine)

**Comment by jbrockmendel** [comment]
> as the old commit is run with the new benchmarks, but for the benchmark machine

That's an unfortunate side effect, but in the class of problems where "throw hardware at it" is a viable solution.

**Comment by jreback** [comment]
@WillAyd for the grant you are looking at, e.g. should take a current benchmark file and run for all released versions as far back as you can (and if anything breaks fix in current benchmarks). we should do this periodically to get good baselines.

**Pull request merged**
