### PR TITLE
Fixed docstrings as referenced in issue no: #24071

### LINKED ISSUE #24071: DOC: Fix quotes position in pandas.core
To keep out docstrings consistent, and make them easier to read, we try to keep always the same exact format. In the case of the opening and closing quotes, the right format is:
```
def foo():
    """
    Summary of the docstring.

    Returns
    -------
    str
        Explaining what is being returned.
    """
```

But for historical reasons, we have many docstrings with different format, for example:
```
def foo():
    """Summary of the docstring.

    Returns
    -------
    str
        Explaining what is being returned."""
```

Besides being inconsistent, having docstrings with the wrong format doesn't let us start validating and enforcing automatically the wanted format. So, we need to change all the wrong cases.

For this issue, all the wrong cases of methods of `pandas.core` should be fixed. The list can be obtained with the next command (the command should not report any error when this is fixed):
```
$ ./scripts/validate_docstrings.py --prefix=pandas.core --errors=GL01,GL02
pandas.core.window.Rolling.skew: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.window.Expanding.skew: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.aggregate: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.aggregate: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.GroupBy.transform: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.transform: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.GroupBy.pipe: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.first: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.last: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.max: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.min: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.prod: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.GroupBy.sum: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.corr: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.corr: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.count: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.count: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.cov: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.cov: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.diff: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.diff: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.fillna: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.fillna: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.hist: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.hist: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.idxmax: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.idxmax: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.idxmin: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.idxmin: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.mad: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.mad: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.quantile: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.quantile: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.skew: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.skew: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.take: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.take: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.tshift: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.tshift: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.SeriesGroupBy.nlargest: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.SeriesGroupBy.nlargest: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.SeriesGroupBy.nsmallest: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.SeriesGroupBy.nsmallest: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.SeriesGroupBy.nunique: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.SeriesGroupBy.nunique: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.SeriesGroupBy.unique: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.SeriesGroupBy.unique: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.SeriesGroupBy.value_counts: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.SeriesGroupBy.value_counts: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.SeriesGroupBy.is_monotonic_increasing: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.SeriesGroupBy.is_monotonic_increasing: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.SeriesGroupBy.is_monotonic_decreasing: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.SeriesGroupBy.is_monotonic_decreasing: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.groupby.DataFrameGroupBy.corrwith: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.groupby.DataFrameGroupBy.corrwith: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.resample.Resampler.pipe: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.resample.Resampler.nunique: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.resample.Resampler.nunique: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
pandas.core.resample.Resampler.first: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.resample.Resampler.last: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.resample.Resampler.max: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.resample.Resampler.min: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.resample.Resampler.prod: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
pandas.core.resample.Resampler.sum: Docstring text (summary) should start in the line immediately after the opening quotes (not in the same line, or leaving a blank line in between)
```

### PR DESCRIPTION
**Pull request by killerontherun1**
- [1] closes #24071 
- [1] tests added / passed
- [0] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [0] whatsnew entry

tests : `./scripts/validate_docstrings.py --prefix=pandas.core --errors=GL01,GL02`

### CODE REVIEW

**Comment by WillAyd** [comment]
Does this fully close the issue? There was a previous PR for this (#26037) which contained a few more changes so think some of that might need to be included here as well

**Comment by datapythonista** [comment]
This lgtm, but won't be that useful if we don't continue  fixing the rest of `GL01` and `GL02` errors. The problem is that if we just fix this, we can't add the validation of the errors to the CI (in `ci/code_checks.sh`, in the docstrings part). And if we don't do it, then we'll eventually have couple more docstrings wrong in `pandas.core`, and we'll have to keep opening these small PRs.

@killerontherun1 if you can work on this, what would be very useful would be to address all the errors in `/scripts/validate_docstrings.py --errors=GL01,GL02`. They seem a lot, but most of them are from the same docstrings (or very similar ones next to each other). And then add `GL01` and `GL02` to `ci/code_checks.sh`, so in every PR we make sure that no docstrings with wrong opening/closing quotes can be added in the future.

Do you have time to work on those and add the fixes to this PR?

**Comment by killerontherun1** [comment]
@datapythonista : Yes please! I'd love to take this up. I ran `/scripts/validate_docstrings.py --errors=GL01,GL02` on my local environment post merging and rebasing and it doesn't give me any errors. Am I doing something wrong to be missing these in my env? Or is there another script/parameter combination I need to run to produce more errors? Also, I was checking out other error codes. I would be happy to address those too. 

I do have the time. Please let me know how I should move forward.

**Comment by WillAyd** [comment]
@killerontherun1 not sure what happened here but this looks to have brought in a lot of other changes. Are you merging the upstream master?

**Comment by datapythonista** [comment]
@killerontherun1 you may be able to restore your branch with the instructions of the first section in https://datapythonista.github.io/blog/useful-git-commands.html

Not sure what caused the problem, but when merging master, you should be using `git fetch upstream` and `git merge upstream/master`, and this state where you have unrelated commits shouldn't happen.

And what you did initially was correct, the issue you were addressing was to fix the docstrings in `pandas.core`, and in general we discourage adding unrelated changed. But in this case that ticket was almost addressed by another PR, and what it's more useful now is to fix all `GL01` and `GL02` errors, so they are not introduced again. Thanks for helping with that.

**Comment by killerontherun1** [comment]
Got it. So there are other changes in the last three commits that are not part of the docstring_fix branch from earlier? 

I think I merged master with this branch by mistake. 

So sorry, but I'm new to this. What exactly should I do? Should I create patches for each of the commits and apply them after I revert the current head to the state before the merge? My git log looks like this:
```
commit 0341bf48c08ea2e893494957816b9e2cc1fa85ac (HEAD -> docstring_fix, origin/docstring_fix)
Author: 
Date:   Sun May 26 11:21:12 2019 +0530

    solved GL01 GL02 for pandas.Index.T

commit c9d2fb51b65b33d359790b3f41d6bcd96e457df4
Author: 
Date:   Sun May 26 11:15:07 2019 +0530

    solved GL01 GL02 for pandas.HDFStore

commit 3b572139874d0fb6b578f5e89e905d93747d966f
Author: 
Date:   Sun May 26 11:11:55 2019 +0530

    GL01 and GL02 solved for pandas.eval

commit 67ebeb9e585d670b76365a0b8aef62fa2a88593d
Author: 
Date:   Sun May 26 10:49:23 2019 +0530

    Fixed GL01 and GL02 in pandas.api

commit 3e32dcdfe4aacccc89b799846d95d13262488363
Merge: 62deebc27 b72832d68
Author: 
Date:   Sat May 25 20:21:10 2019 +0530

    Merge branch 'master' into docstring_fix


```

**Comment by datapythonista** [comment]
If you check the "Files changed" tab of this PR you'll see that there is plenty of unrelated stuff. With some luck, you can fix this with the link I provided.

**Comment by killerontherun1** [comment]
Yep. Lot of file changes. Thanks so much for the link. I went through the options, but none of them seem to be helping me sort out my branch. It is be because I merged the master with this branch. Man, my branch is a real mess now. 

Any idea how I can rebase this branch to my first commit so that I can remove the other unrelated commits from here?

**Comment by datapythonista** [comment]
if the instructions in the link I sent don't work, you'll probably want to start a new branch from an updated master, and manually apply the relevant commits from this branch there.

**Comment by killerontherun1** [comment]
Yep. Just doing that. Sorry, but major noob question again. Is it possible
for me to update this same PR with a new branch with just the related
changes? Or would I have to raise a new PR with the changes and we could
close this one?



Warm Regards,

Mathew George
Mob: +91-9820502747

**Comment by datapythonista** [comment]
You surely can, but if you're unsure of those things, better do the simplest thing. pandas is not the best project for experimenting, this is creating noise for too many people.

**Comment by killerontherun1** [comment]
Closing this PR. I'm terribly sorry about the noise. Did not mean to waste anybody's time. Thank you so much for your patience with me.

**Comment by datapythonista** [comment]
No worries, this problem with the branch happens very often (that's why I wrote the post on how to fix it).

My point is only to better not try fancy things pushing here, as this notifies many people. Feel free to open a new PR with the changes, and let's continue there. Thanks!

**Pull request closed without merging**
