### PR TITLE
BUG: Fix bug in putmask for CoW

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @jorisvandenbossche this did not work an 1.5.2

### CODE REVIEW

**Comment by phofl** [comment]
cc @jorisvandenbossche Could you have a quick look? Ideally this would go into 1.5.3

**Review by mroeschke — APPROVED** [review]
LGTM

**Comment by jorisvandenbossche** [comment]
Should we backport https://github.com/pandas-dev/pandas/pull/50675 as well?

**Comment by jorisvandenbossche** [comment]
Ah, forget what I said, the usage of `using_copy_on_write` is in the internals itself, so there it is fine as is.

**Comment by phofl** [comment]
Puuuuh, is there anything else that is scheduled for 1.5.3 regarding CoW? If not, I wouldn't backport I think

**Comment by phofl** [comment]
Good :)

**Pull request merged**
