### PR TITLE
Respect byteorder in StataReader

### LINKED ISSUE #11282: few fresh failed tests on big-endian platforms (0.17.0+git8-gcac4ad2)
for details see https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=powerpc&ver=0.17.0%2Bgit8-gcac4ad2-1&stamp=1444485115  but here is the excerpt of few failed tests:

```
======================================================================
FAIL: pandas.io.tests.test_packers.TestMsgpack.test_msgpack('0.16.2',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/test_packers.py", line 623, in read_msgpacks
    self.compare(vf, version)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/test_packers.py", line 595, in compare
    check_arbitrary(result, expected)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/test_packers.py", line 42, in check_arbitrary
    assert_series_equal(a, b)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 903, in assert_series_equal
    obj='{0}.index'.format(obj))
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 669, in assert_index_equal
    obj=obj, lobj=left, robj=right)
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 798, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series.index are different

Series.index values are different (80.0 %)
[left]:  Int64Index([                 0,  72057594037927936, 144115188075855872,
            216172782113783808, 288230376151711744],
           dtype='int64')
[right]: Int64Index([0, 1, 2, 3, 4], dtype='int64')

======================================================================
FAIL: pandas.io.tests.test_packers.TestMsgpack.test_msgpack('0.16.0',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/test_packers.py", line 623, in read_msgpacks
    self.compare(vf, version)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/test_packers.py", line 595, in compare
    check_arbitrary(result, expected)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/io/tests/test_packers.py", line 44, in check_arbitrary
    assert_index_equal(a, b)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 665, in assert_index_equal
    raise_assert_detail(obj, msg, left, right)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 798, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Index are different

Index values are different (100.0 %)
[left]:  DatetimeIndex(['1970-01-03 12:45:03.392593170',
               '1970-01-01 06:33:35.598089490',
               '1970-01-02 06:33:18.485329170',
               '1970-01-03 06:51:25.162321170',
               '1970-01-01 00:39:57.351040530',
               '1970-01-02 00:58:04.028032530',
               '1970-01-03 00:57:46.915272210',
               '1970-01-04 01:15:53.575487250',
               '1970-01-01 19:04:25.780983570',
               '1970-01-02 19:04:08.668223250'],
              dtype='datetime64[ns]', freq='D')
[right]: DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10'],
              dtype='datetime64[ns]', freq='D')

======================================================================
FAIL: test_NaT_cast (pandas.tseries.tests.test_timeseries.TestSeriesDatetime64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/tseries/tests/test_timeseries.py", line 3498, in test_NaT_cast
    assert_series_equal(result, expected)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 925, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 798, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (100.0 %)
[left]:  [2262-04-10T00:12:45.292707840+0000]
[right]: [NaT]

======================================================================
FAIL: test_where_datetime (pandas.tests.test_series.TestSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/tests/test_series.py", line 2156, in test_where_datetime
    assert_series_equal(rs, expected)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 925, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3809)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2685)
  File "/«BUILDDIR»/pandas-0.17.0+git8-gcac4ad2/debian/tmp/usr/lib/python2.7/dist-packages/pandas/util/testing.py", line 798, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (50.0 %)
[left]:  [1970-01-01T00:00:00.000000010+0000, 2262-04-10T00:12:45.292707840+0000]
[right]: [1970-01-01T00:00:00.000000010+0000, NaT]

----------------------------------------------------------------------
Ran 8936 tests in 754.808s

FAILED (SKIP=248, failures=4)
```

### PR DESCRIPTION
**Pull request by aplanas**
Partially fix #11282 for s390x

### CODE REVIEW

**Comment by jreback** [comment]
would love to include, but can you include a test. ideally write a test frame in (both little/big) endian then read back.

**Comment by aplanas** [comment]
Actually I detected that because of this test:

nosetests -s pandas/io/tests/test_stata.py:TestStata.test_read_dta18

This test was OK in x86_64 and wrong on ARM and S390X machines, now is green in both.

**Comment by jreback** [comment]
don't delete tests
better to skip that on platforms where it is inappropriate (and use a different one where it is)

so ideally have a file in a different byte order then test it can be read in the correct platform (and errors on incorrect platforms)

**Comment by kshedden** [comment]
Does anyone have access to Stata on a BE machine?  If so we should just convert a few of the test files to BE and then test that we can read them back in on a LE machine.

I don't have access to a BE machine with Stata, but I can provide Stata code to load/save the files.  If run on a BE machine that should convert the file byteorder to BE.  I don't think Stata will save files in non-native byte order, so I can't do this on any of my machines.

**Comment by jreback** [comment]
closing, but pls reopen if you can add tests

**Pull request closed without merging**
