### PR TITLE
CLN: Split test_window.py further

### LINKED ISSUE #19228: TST: split tests for windows to sub-modules
after #18723 

can split test_window.py to a sub-dir ``pandas/tests/window/`` and have
``test_rolling, expanding, emwa`` and prob ``test_window`` (for other)

### PR DESCRIPTION
**Pull request by ihsansecer**
closes #19228
xref #26807
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] passes `black pandas`

Just splitted code into files by classes. No changes made to code

cc @jreback

### CODE REVIEW

**Comment by WillAyd** [comment]
Not sure we need this (probably should have closed first issue after last PR). Any interest in parametrizing instead?

**Comment by ihsansecer** [comment]
Opened as per @jreback's [comment](https://github.com/pandas-dev/pandas/pull/27275#issuecomment-510564495).

**Comment by WillAyd** [comment]
My mistake! Though would still take parametrization (separate PR is fine) if you are up for it

**Comment by ihsansecer** [comment]
@WillAyd thanks for suggestion noted that

**Comment by gfyoung** [comment]
If this is a pure split, then I would be in favor of merging this.

**Comment by jreback** [comment]
thanks @ihsansecer

**Pull request merged**
