### PR TITLE
CI: troubleshoot travis-36-cov on 1.1.x

### LINKED ISSUE #37309: CI: travis-36-cov builds regularly fails to build with The build has been terminated on 1.1.x
The last good build can be seen at https://travis-ci.org/github/pandas-dev/pandas/builds/736681105

There are some failures that have started to appear since this started timing out that also need to be resolved.

```
=========================== short test summary info ============================
FAILED pandas/tests/test_downstream.py::test_pandas_gbq - AttributeError: mod...
FAILED pandas/tests/io/test_sql.py::TestMySQLAlchemy::test_to_sql_with_negative_npinf[load_iris_data0-input0]
FAILED pandas/tests/io/test_sql.py::TestMySQLAlchemy::test_to_sql_with_negative_npinf[load_iris_data0-input1]
FAILED pandas/tests/io/test_sql.py::TestMySQLAlchemy::test_to_sql_with_negative_npinf[load_iris_data0-input2]
FAILED pandas/tests/io/test_sql.py::TestMySQLAlchemyConn::test_to_sql_with_negative_npinf[load_iris_data0-input0]
FAILED pandas/tests/io/test_sql.py::TestMySQLAlchemyConn::test_to_sql_with_negative_npinf[load_iris_data0-input1]
FAILED pandas/tests/io/test_sql.py::TestMySQLAlchemyConn::test_to_sql_with_negative_npinf[load_iris_data0-input2]
FAILED pandas/tests/util/test_show_versions.py::test_show_versions - Attribut...
ERROR pandas/tests/io/test_gbq.py - AttributeError: module 'google.protobuf.d...
= 8 failed, 73783 passed, 1033 skipped, 1053 xfailed, 6 xpassed, 77 warnings, 1 error in 1533.46s (0:25:33) =
```

xref #36779, https://github.com/pandas-dev/pandas/pull/37303#issuecomment-713513751, https://github.com/pandas-dev/pandas/pull/37304#issuecomment-713515608

### PR DESCRIPTION
**Pull request by simonjayhawkins**
closes #37309

### CODE REVIEW

**Comment by jbrockmendel** [comment]
it looks like this build is gone; is this PR still actionable?

**Comment by simonjayhawkins** [comment]
> it looks like this build is gone; is this PR still actionable?

I thought I had got somewhere after trying to debug locally #36779. Was taking a stab in the dark on most of these commits. Not found any authoritative resources on how to debug conda solve issues.

The issue could be closed if 1.1.4 is the last in the 1.1.x series.

I'll close this PR for now to clear the queue since I doubt I'll waste any more time on this before the 1.1.4.

Can reopen if planning a 1.1.5 or maybe move the coverage build to 3.7 (same as master)

**Comment by simonjayhawkins** [comment]
it appears that the xfail condition on test_apply may be suspect, see discussion in https://github.com/MacPython/pandas-wheels/pull/64

**Comment by simonjayhawkins** [comment]
all green here. will merge shortly if no objections. this is against 1.1.x directly. @jreback

**Comment by jreback** [comment]
sure

we still have other 3.6 testing on 1.1.x right?

**Comment by simonjayhawkins** [comment]
> we still have other 3.6 testing on 1.1.x right?

plenty. 6 envs in azure and 1 in travis

**Comment by jreback** [comment]
great merge away

**Pull request merged**
