### PR TITLE
BUG, COMPAT: Fix multi-char sep + non-utf8 in read_csv for Python 2

### LINKED ISSUE #3404: Multicharacter delimiters + non-UTF8 encoding doesn't work correctly in parsers
The new C parser handles user-specified encoding properly. The Python parser not so much (I think it may only be an issue when regular-expression parsing is used).

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.  Closes #3404.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Not sure if so many different ones to test is not overkill, but looks good, thanks

**Comment by gfyoung** [comment]
@jorisvandenbossche : it was a good thing you asked about a specific test.  You caught a Python 2 bug.  Turns out when we have a `StringIO` (the Python 2 `BytesIO`) of encoded data, we can't wrap it with a `TextIOWrapper` and pass in the `encoding` parameter like we do in Python 3 so that we can decode it.

Normally, this would in fact be taken care by `CsvReader`, BUT that's only for standard delimiters.  When we have a multi-char separator, we have to resort to an ad-hoc method of creating a generator, which does zero decoding.

**Comment by gfyoung** [comment]
@jorisvandenbossche : Squashed the bug, and Travis is passing <a href="https://travis-ci.org/pydata/pandas/builds/147951933">here</a> (had to make a doc change after, hence the `[ci skip]`).  Ready to merge if there are no concerns.

**Comment by jreback** [comment]
thanks @gfyoung

**Pull request merged**
