### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by felixdivo**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
thanks @felixdivo

**Comment by TomAugspurger** [comment]
@felixdivo this was applied to the 0.25.x branch. If you want it to be fixed for all versions going forward you'll need to make a PR against master.

**Comment by jreback** [comment]
grr didn't notice this was not master :-<

**Comment by TomAugspurger** [comment]
The GitHub UI doesn't make it obvious :/ Only saw it in my email.

**Comment by felixdivo** [comment]
Okay sure, I didn't get your branching model. I'll apply it to master as well, that's the more important one. :smile:

**Pull request merged**
