### PR TITLE
Merge pull request #1 from pandas-dev/master -  #34498 improve the .equals() docstring

### PR DESCRIPTION
**Pull request by data-RanDan**
#34498 improve the .equals() docstring

### CODE REVIEW

**Comment by WillAyd** [comment]
@jorisvandenbossche

**Comment by data-RanDan** [comment]
Hi
I'm not sure what causes these failures, i only changed the comments..

**Comment by jorisvandenbossche** [comment]
We actually already have an open PR that is trying to address the same issue: https://github.com/pandas-dev/pandas/pull/34508

**Comment by data-RanDan** [comment]
well' he seems to be at it for a while..
and i just solved it for you

**Review by WillAyd — APPROVED** [review]
lgtm - I think OK to merge

**Comment by jorisvandenbossche** [comment]
It's only two weeks, and just a trailing whitespace failure that was remaining in the older PR. So I updated that one.

**Comment by jorisvandenbossche** [comment]
@data-RanDan I merged the other PR, so going to close this one. But know that your contribution is very much valued nonetheless! On a big project like pandas it is easy to overlook other issues/PRs. It's always a bit annoying if such duplicate work happens, but given that the other PR was older and further in the review process, decided to merge that one.

**Pull request closed without merging**
