### PR TITLE
BUG: SparseSeries.to_frame results in dense

### LINKED ISSUE #9850: API: SparseSeries.to_frame and SparseDataFrame.to_panel result in dense structures
Related to #9802. I think these should return sparse.

```
import pandas as pd

ss = pd.SparseSeries([1, 0, 1])
type(ss.to_frame())
# <class 'pandas.core.frame.DataFrame'>

index = pd.MultiIndex.from_tuples([(0, 0), (0, 1), (1, 1)])
sdf = pd.SparseDataFrame([[1, 0, 1], [0, 0, 0], [1, 0, 0]], index=index)
type(sdf.to_panel())
# <class 'pandas.core.panel.Panel'>
```

### PR DESCRIPTION
**Pull request by sinhrks**
- [x] closes #9850
- [x] tests added / passed
- [x] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry

This should be after #12831.

### CODE REVIEW

**Comment by jreback** [comment]
thanks!

**Comment by jreback** [comment]
so this can be rebased

**Comment by sinhrks** [comment]
Rebased. Also, forgot to note that I don't fix ``to_panel`` which is being deprecated.

**Comment by jreback** [comment]
@sinhrks thanks! you are really closing these sparse issues!

yeah ``SparseDataFrame.to_panel()`` is no problem

**Pull request closed without merging**
