### PR TITLE
CLN: deprivatize factorize_from_iterable

### PR DESCRIPTION
**Pull request by topper-123**
Deprivatize ``_factorize_from_iterable`` and ``_factorize_from_iterables``

### CODE REVIEW

**Comment by jbrockmendel** [comment]
pending green, lgtm

**Comment by WillAyd** [comment]
What is the goal of this?

**Comment by jbrockmendel** [comment]
> What is the goal of this?

rule of thumb: respect private naming conventions

**Comment by topper-123** [comment]
> What is the goal of this?

This isn't private any more than any other function in ``pd.core``.

**Comment by jreback** [comment]
lgtm. merge master and merge on green.

**Pull request merged**
