### PR TITLE
DOC: Change document code prun in a row

### LINKED ISSUE #28026: DOC: Fix python code error in enhancingperf
#### Problem description
image

This screenshot is in  `pandas 0.25.0 documentation`, https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html#using-ndarray

Current code is
```python3
.. ipython:: python

   %prun -l 4 apply_integrate_f(df['a'].to_numpy(),
                                df['b'].to_numpy(),
                                df['N'].to_numpy())
```
`%prun` takes only single line, so it can be 
```python3
.. ipython:: python
   %prun -l 4 apply_integrate_f(df['a'].to_numpy(), df['b'].to_numpy(), df['N'].to_numpy())
```
or use `%%prun`
```python3
.. ipython:: python
   %%prun -l 4 apply_integrate_f(df['a'].to_numpy(),
                                df['b'].to_numpy(),
                                df['N'].to_numpy())
```

#### Expected Output
image

#### Output of ``pd.show_versions()``
In [1]: import pandas as pd;pd.show_versions()                                                            

INSTALLED VERSIONS
------------------
commit           : 5b0a2a6e361f75c8cbb715cd33ff55dd61c631c9
python           : 3.6.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-54-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.0+191.g5b0a2a6e3.dirty
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.1.0
Cython           : 0.29.13
pytest           : 5.1.0
hypothesis       : 4.32.3
sphinx           : 1.8.5
blosc            : 1.8.1
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : 0.14.1
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : 3.5.2
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

### PR DESCRIPTION
**Pull request by EunSeop**
- [x] closes #28026 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @EunSeop, can you fix the CI please, seems like your change is making something fail.

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @EunSeop 

did you build the documentation to see if this is rendering as expected?

`./doc/make.py html` does it. Thanks!

**Comment by EunSeop** [comment]
image
Seems working correctly

**Review by jorisvandenbossche — APPROVED** [review]
Thanks for the catch and the fix!

**Comment by jorisvandenbossche** [comment]
@datapythonista strange thing is that this error was not visible (and thus catched) on Azure ..

**Pull request merged**
