### PR TITLE
ENH: add peek function

### LINKED ISSUE #18691: Add an ends function that shows both head and tail of the df
#### Add the following function to pd. dataFrame and pd.Series

```python
def ends(df, x=5):
    """Returns both head and tail of the dataframe or series.
    
    Args:
        x (int): Optional number of rows to return for each head and tail
    """
    print('{} rows x {} columns'.format(np.shape(df)[0],np.shape(df)[1]))
    return df.head(x).append(df.tail(x))

```
#### Problem description
Often both the beginning and end of a df are of interest, fore example in a time series. 

This leads to calling df.head() df.tail()  in two seperate notebook cells. This is not only tedious, but also leads to a cluttered notebook. A function that returns both of these + a print on the number of rows and columns, thus allowing a check if the index matches the number of rows.

#### Example
```python

import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(1500,6))
print(ends(df,2))
```
1500 rows x 6 columns

|      | 0        | 1        | 2        | 3        | 4        | 5        |
|------|----------|----------|----------|----------|----------|----------|
| 0    | 0.949695 | 0.160928 | 0.434134 | 0.943103 | 0.477830 | 0.903479 |
| 1    | 0.736711 | 0.103746 | 0.028694 | 0.205910 | 0.226061 | 0.458452 |
| 1498 | 0.362950 | 0.586887 | 0.399681 | 0.115366 | 0.239049 | 0.386281 |
| 1499 | 0.018102 | 0.852198 | 0.880993 | 0.671604 | 0.705586 | 0.802237 |

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.3.1
pip: 9.0.1
setuptools: 38.2.4
Cython: 0.26.1
numpy: 1.12.1
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by Quetzalcohuatl**
- [x]  closes #18691
- [x] tests added / passed
- [ ] passes black pandas
- [ ] passes git diff upstream/master -u -- "*.py" | flake8 --diff
- [x] whatsnew entry

added peek, which is essentially a concatenation of head and tail functions. The reason I add, is because often for sorted data, you are interested in looking at both the head and tail simultaneously to see the min/max range.

### CODE REVIEW

**Comment by WillAyd** [comment]
This has been discussed previously in #18691 - not sure we want to add this to the API

**Comment by jreback** [comment]
yeah -1 on adding this. We *already* already pretty much show this when doing a repr.

**Comment by jreback** [comment]
thanks @Quetzalcohuatl plently of formatting issues if you would like to tackle.

**Comment by Quetzalcohuatl** [comment]
@jreback We have `head` and `tail` even though you can _already_ already show that by doing `.iloc[n:]`. I think this would be a very useful option to add instead of having to type the very long `with pd.option_context('display.max_rows'=50)`... I can never remember the phrase to use, and this would be a quick and easy way to do it. Even in the linked issue someone made a function `def show` that they use in every notebook. Nobody wants to be copy pasting the repr every time they want to show different amounts of rows. Sometimes you only want head(1) and tail(1), sometimes you want head(25) tail(25) which will fit within the default 50 rows displayed in Jupyter Notebook. Please reconsider.

**Comment by jreback** [comment]
@Quetzalcohuatl see the linked issue - happy to take an example function (see @TomAugspurger example) / doc string update 

this is useful but we cannot have everything

**Pull request closed without merging**
