### PR TITLE
DOC: Start 1.1.2

### PR DESCRIPTION
**Pull request by simonjayhawkins**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
```
/home/runner/work/pandas/pandas/doc/source/whatsnew/v1.1.1.rst:70: WARNING: Cannot find contributors for range 'v1.1.0..v1.1.1': Cmd('git') failed due to: exit code(128)
  cmdline: git log --grep=Co-authored --pretty=%b v1.1.0..v1.1.1
  stderr: 'fatal: ambiguous argument 'v1.1.0..v1.1.1': unknown revision or path not in the working tree.
```

**Comment by simonjayhawkins** [comment]
> ```
> /home/runner/work/pandas/pandas/doc/source/whatsnew/v1.1.1.rst:70: WARNING: Cannot find contributors for range 'v1.1.0..v1.1.1': Cmd('git') failed due to: exit code(128)
>   cmdline: git log --grep=Co-authored --pretty=%b v1.1.0..v1.1.1
>   stderr: 'fatal: ambiguous argument 'v1.1.0..v1.1.1': unknown revision or path not in the working tree.
> ```

only just pushed the tag. will restart github actions and should be OK

**Comment by simonjayhawkins** [comment]
known test failures on travis-37-locale

**Comment by simonjayhawkins** [comment]
hmm, marking as ready for review has re-triggered azure build.

**Comment by simonjayhawkins** [comment]
@jbrockmendel I think now OK to merge if holding up other PR changes.

**Comment by jreback** [comment]
thanks @simonjayhawkins

**Pull request merged**
