### PR TITLE
DOC: automatic 'end' year of copyright

### PR DESCRIPTION
**Pull request by ShaharNaveh**
#31022 Updated it after nearly 6 years, I think this will update with each new merge, so that should not be a problem from now on, (I think)
cc (@datapythonista)

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Makes sense, looks good to me.

In general I think it's better to `import datetime`, since when reading code `datetime` is ambiguous, but `datetime.datetime` is not. But not a big deal, we have imports like this everywhere in the code, just saying.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @MomIsBestFriend

**Comment by MomIsBestFriend** [comment]
> Makes sense, looks good to me.
> 
> In general I think it's better to `import datetime`, since when reading code `datetime` is ambiguous, but `datetime.datetime` is not. But not a big deal, we have imports like this everywhere in the code, just saying.

Do you mind if I open a pull request addressing these?

**Comment by datapythonista** [comment]
Better open an issue first, so there is some discussion and you see if there is agreement in it.

**Pull request merged**
