### PR TITLE
Backport PR #43608: REGR: spearman corr raising on 32-bit

### PR DESCRIPTION
**Pull request by mzeitlin11**
Backport PR #43608

### CODE REVIEW

**Comment by mzeitlin11** [comment]
cc @lithomas1 does the circleci pr need to be backported?

**Comment by lithomas1** [comment]
On it, thanks for the reminder. This was not backported initially because we wanted to see if it worked first. This might still fail if 1.3.x doesn't work well with ARM64 but we'll see.

**Comment by jreback** [comment]
@mzeitlin11 if you'd merge 1.3.x master and push again (to pick up the circle config)

**Comment by jreback** [comment]
thanks @mzeitlin11

**Comment by simonjayhawkins** [comment]
@mzeitlin11 when doing the manual backport , we need to make sure that the merge conflicts in the release notes are resolved in the same order as master otherwise future autobackports could fail.

I'll do a PR syncing the notes on 1.3.x with master shortly.

---

There is also a missing double quote in the release note. if this is fixed on master, the autobackport will fail until the notes are synced. I'll do that after since there is also an error in the release note for #43132 which can be done at the same time.

**Comment by simonjayhawkins** [comment]
> I'll do a PR syncing the notes on 1.3.x with master shortly.

will merge #43630 first, but restated ci on that one to get to green.

**Comment by mzeitlin11** [comment]
> @mzeitlin11 when doing the manual backport , we need to make sure that the merge conflicts in the release notes are resolved in the same order as master otherwise future autobackports could fail.
> 
Sorry about messing that up, will keep in mind going forward.  Please let me know if there's anything I can do to help

**Comment by simonjayhawkins** [comment]
> Sorry about messing that up

no problem. easy to do and easy to fix #43636

**Pull request merged**
