### PR TITLE
Tests added for dtype comparison with fixture

### PR DESCRIPTION
**Pull request by ataturhan21**
- #43038 closes #xxxx
- 3 tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- Dtype comparsisons added for regression test

Firstly, this is my first contribution to a huge code base therefore I am learning everything the first time, sorry for this inconvenience, again. Secondly, I have another pr for this commit but it involved a lot of other changes (315 file change) by other people and I dont know what to do with those changes. So I made this pr to make my one file change merge to master branch. If you can merge it to master before Sunday, I will be very happy because I need it for my class project. Thank you and kind regards.

My another pull who had 315 file change by other people: https://github.com/pandas-dev/pandas/pull/44618

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
can we stick to the original PR please? rebasing is a fundamental part of the git workflow, it's worth learning

**Comment by fotino21** [comment]
@MarcoGorelli My latest commit passed all the tests except one because of this code:

FAILED pandas/tests/io/parser/test_c_parser_only.py::test_buffer_rd_bytes[c_low]
= 1 failed, 141673 passed, 2728 skipped, 1264 xfailed, 2 xpassed, 136 warnings in 1894.99s (0:31:34) =

This is not a test I wrote, so what can i do about it? Thank you.

**Comment by MarcoGorelli** [comment]
it's unrelated, don't worry about it

**Comment by fotino21** [comment]
> it's unrelated, don't worry about it

@MarcoGorelli Do i need to do anything else before merge?

**Comment by jreback** [comment]
thanks @fotino21

**Comment by fotino21** [comment]
Thanks for all of you. I am grateful for this experience ;] @jreback @MarcoGorelli

**Pull request merged**
