### PR TITLE
STYLE: Flake8 "Do not assign a lambda expression, use a def. "

### PR DESCRIPTION
**Pull request by radojicic23**
*  Do not assign a lambda expression,  consider using def().
*  Imports at the top

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
This fails the CI checks

If you want to solve all E731 checks and remove this line

https://github.com/pandas-dev/pandas/blob/57d8d3a7cc2c4afc8746bf774b5062fa70c0f5fd/setup.cfg#L192-L193

then OK, would take that

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
you haven't addressed

https://github.com/pandas-dev/pandas/pull/49522#pullrequestreview-1168521338

, feel free to re-request a review after you've done that

**Comment by MarcoGorelli** [comment]
sorry, this is too far off - I'd suggest you start by reading through the contributing guide, and looking at some good first issues

closing for now then

**Comment by radojicic23** [comment]
Is it okay now?

**Pull request closed without merging**
