### PR TITLE
CLN: Clean NDFrame.__finalize__ signature

### PR DESCRIPTION
**Pull request by dsaxton**
`NDFrame.__finalize__` doesn't do anything with `method` or `kwargs` so removing them from the signature and all calls. Had to change a few tests which overrode this method with another that also included those arguments.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
I think @TomAugspurger had some plans for this?

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
This is used by subclasses (see eg https://github.com/geopandas/geopandas/blob/5d1181af6bcca88351d84bb63fc0fbe0e32ce055/geopandas/geodataframe.py#L643), so can't be simply removed

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/pull/28394 is still a WIP, though I split out the finalize bits.

But we'll want `method` for us, and subclasses may be using the other arguments.

**Comment by dsaxton** [comment]
Sounds like this may not make sense so I'll go ahead and close

**Pull request closed without merging**
