### PR TITLE
CLN: F-string formatting in pandas/tests/indexes/*.py (#29547)

### PR DESCRIPTION
**Pull request by yashukla**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by yashukla** [comment]
I'm a little unsure how to interpret the results of the checks - since code_checks.sh exits with an error at a line where isort is called, it seems like it would point to an issue with importing. However, I haven't changed any import statements, and I checked that all the pytests were consistent with before I changed anything, so I'm not sure what the issue is.

**Comment by alimcmaster1** [comment]
Hi @yashukla the issue is related to black opposed to isort see:

```
black, version 19.3b0
Checking black formatting
would reformat /home/vsts/work/1/s/pandas/tests/indexes/test_common.py
```
can you run `black pandas` on the changes?

**Comment by alimcmaster1** [comment]
Also please could you reference the issue:

https://github.com/pandas-dev/pandas/issues/29547

**Comment by yashukla** [comment]
@alimcmaster1 Oh, I wasn't using black correctly. Thanks so much! Correct issue referenced, formatting fixed, and code now passes `black pandas` and `git diff upstream/master -u -- "*.py" | flake8 --diff`, along with checks; anything else that needs to be done?

**Comment by jreback** [comment]
thanks @yashukla

**Pull request merged**
