### PR TITLE
CI: fix wrong syntax in CI env yml files (mamba 2.0 compat)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
All CI is failing with the new mamba 2.0 release. But it seems this is because we had invalid syntax (pip extras syntax) in our environment files, where mamba now fails on (previously used conda for parsing the yml files).

### CODE REVIEW

**Comment by mroeschke** [comment]
It seems like there a few issues with mamba 2.0 with windows (https://github.com/mamba-org/setup-micromamba/issues/227) and the `list` command (https://github.com/mamba-org/setup-micromamba/issues/225) that we're also seeing here.

We may just need to pin the mamba version

**Comment by rhshadrach** [comment]
I opened #59912 - planning to merge as soon as that's green. We can then use this to unpin once upstream is fixed.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
Manual backport -> https://github.com/pandas-dev/pandas/pull/60175

**Pull request merged**
