### PR TITLE
PKG: Added pyproject.toml for PEP 518

### PR DESCRIPTION
**Pull request by TomAugspurger**
Declaring build-time requirements: https://www.python.org/dev/peps/pep-0518/

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I tested this by

1. creating a clean virtualenv
2. installing pip master (10.0 dev)
3. removing the `setup_requires` lines from `setup.py`
4. running `pip wheel .` from the top-level directory.

And the wheel successfully built, and afterwards my `pip list` was just

```
Package    Version
---------- -----------
pip        10.0.0.dev0
setuptools 36.0.1
wheel      0.29.0
```

which I think means it worked correctly.

**Comment by TomAugspurger** [comment]
Oh, and I don't really think this needs a release note, but I added one just to encourage other projects to adopt pep 518.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by TomAugspurger** [comment]
From https://github.com/pandas-dev/pandas/issues/16715#issuecomment-310227035

> I am not sure PEP518 is going to change anything about this, because the problem still remains that at the moment you build the pandas wheel (with specification of numpy>0.17 from the pyproject.toml, which will download the latest 1.13) it does not seem to know about the exact numpy version that is installed at the same time (and can thus be older than the one used in the wheel building step)
>
> Should we actually pin the numpy version to the oldest supported one in the build-system requires? (what we in practice do when building wheels to distribute?) Since this is done in an isolated environment, it shouldn't influence your actual environment

I think you're right. I need to do some research on which versions of numpy actually work together. Let's wait before merging this.

**Comment by jreback** [comment]
lgtm. I theory you could have the 2.7_BUILD_TEST try to 'build' using this?

**Comment by gfyoung** [comment]
@TomAugspurger : merge conflict for this PR.  Otherwise, it should be good to merge.

**Comment by TomAugspurger** [comment]
Gonna wait till I can talk to some other projects about how they're using it to make sure things are correct.

**Comment by TomAugspurger** [comment]
Here's SciPy's https://github.com/scipy/scipy/pull/7309, https://github.com/scipy/scipy/blob/master/pyproject.toml

**Comment by jreback** [comment]
lgtm.

**Pull request merged**
