### PR TITLE
DEPR: deprecate the data reader package, #10861

### LINKED ISSUE #10861: DEPR: deprecate datareader in 0.17.0
xref https://github.com/pydata/pandas/pull/10061
closes #8961 

point to [pandas-datareader package](https://github.com/pydata/pandas-datareader)

### PR DESCRIPTION
**Pull request by jreback**
closed #10861

### CODE REVIEW

**Comment by jreback** [comment]
@jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
Yep! Merged with https://github.com/pydata/pandas/commit/dacae1039485634d77f0cc5422330268f467653d (I slightly changed the wording and added the imports changes)

**Comment by jorisvandenbossche** [comment]
And did the same for wb.py: https://github.com/pydata/pandas/commit/a44e4b376f2a882763230fd264193c1d75b063dc

**Comment by jreback** [comment]
awesome thxs!

**Comment by hayd** [comment]
The original idea was to just replace pandas data/web with an import statement, that way no code actually needs to be updated... tests could remain etc.

If there's a warning (not sure there has to be if we change the import) it should include, "install pandas-datareader and replace `pandas.io.data` with `pandas_datareader.data`".

Thoughts?

**Comment by jreback** [comment]
that's how it is; see joris commit above

**Comment by hayd** [comment]
Great, sorry didn't see that!

But why warn here... if we're later to just replace this in pandas as the import statement, I thought the idea was that users don't need to change any code; they just need to install pandas-datareader.

**Comment by jorisvandenbossche** [comment]
@hayd You are correct that that was one of the ideas in the discussion, but in my impression we didn't really converged to a final decision there yet (but maybe that is because I am not fully convinced of that position .. :-))

So this can certainly still be discussed/adapted (but indeed, I changed the wording a bit in the commit, so the import change is noted).

**Comment by jorisvandenbossche** [comment]
See my comment here with my reasons: https://github.com/pydata/pandas/issues/8961#issuecomment-70367939 + my last comment.

But if we discuss it further, maybe lets do it in the original issue over there: #8961

**Comment by jreback** [comment]
I have to agree with joris
this should be very explicit that you are now importing a new package (though it's highly related)

people will see the deprecation if they use the data package - they can then choose to update or not

**Pull request closed without merging**
