### PR TITLE
CLN remove dataframe api consortium entrypoint

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Discussed privately

In short:
- I'm no longer involved in the project
- nobody in pandas has much interest in leading the effort
- pandas devs are already carrying out enough (mostly unpaid) maintenance, let's not add to it

The Consortium is more than welcome to work on this, but outside of pandas

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by anmyachev** [comment]
Just curious why you didn't update the `What's New` section to match the way it was done when adding the entrypoint: https://github.com/pandas-dev/pandas/commit/809f3710807efedc684c8f0ed4adef8d01af3171#diff-cc8593fd6d3036f46dbd73bcd245aef9a5e737cd22ca67e9567e686872bf093e. It took me a while to figure out where it was deleted.

@rgommers are you aware of this change?

**Comment by MarcoGorelli** [comment]
Hey Anatoly,

I can't remember exactly, I probably just forgot

**Comment by rgommers** [comment]
> @rgommers are you aware of this change?

I don't think I was, thanks for pointing it out. 

This change was breaking it looks like (or you wouldn't have noticed in Modin I think), and the maintenance burden was minimal (xref gh-54383 comments), so I wouldn't have done it this way. But ultimately decisions like this are up to the maintainers alone, so it is what it is.

**Pull request merged**
