### PR TITLE
BUG: Fix na_rep when using pd.NA in _format_strings (#33950)

### LINKED ISSUE #33950: BUG: pd.NA ignored in DataFrame.to_html(na_rep)
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

A short example adjusted from the one in issue #29975 (which appeared to be the closest bug to this one, unless I missed something)

```python
>>> df = pd.DataFrame({'a': [1, pd.NA, 2]})
>>> df
>>> 'zzzz' in df.to_csv(na_rep='zzzz')
True
>>> 'zzzz' in df.to_html(na_rep='zzzz')
False
```

#### Problem description

pd.NA seems to be ignored by the `na_rep` in `to_html()`. In the HTML, pd.NA shows up as `<NA>`.

The `na_rep` works fine for pd.NA in `to_csv()` and works fine for NaNs in `to_html()`:

```python
>>> df = pd.DataFrame({'a': [1, float('nan'), 2]})
>>> 'zzzz' in df.to_csv(na_rep='zzzz')
True
>>> 'zzzz' in df.to_html(na_rep='zzzz')
True
```

#### Expected Output

I'd expect pd.NA to be represented by the `na_rep` in the output of `to_html()`.

#### Output of ``pd.show_versions()``

<details>

commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-7642-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : 0.29.15
pytest           : 5.4.1
hypothesis       : 5.8.3
sphinx           : 2.4.4
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.15
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.8
numba            : 0.48.0

</details>

### PR DESCRIPTION
**Pull request by k-fillmore**
- [x] closes #33950
- [x] tests added / passed
- [x] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@k-fillmore thanks for the contribution!

Does this keep the correct "<NA>" representation by default? (when not using `na_rep` keyword)

**Comment by k-fillmore** [comment]
Hi, @jorisvandenbossche  Doesn't appear to retain the "" representation.  I've added an additional expression to address this. Working on tests.

**Comment by k-fillmore** [comment]
@jorisvandenbossche added tests. Don't really like the leading whitespace that I had to add. But that's how they're being passed back from GenericArrayFormatter. I tried to track down where they're coming from but didnt have much luck. Any ideas?

**Comment by k-fillmore** [comment]
Just want to follow up on this. Do I need to add anything else?

**Comment by TomAugspurger** [comment]
https://github.com/pandas-dev/pandas/issues/33950#issuecomment-680406172 noted that this affects NaT too. Can you fix that here or open a second issue?

**Comment by TomAugspurger** [comment]
Can you also merge master and re-push. I don't know why CI failed last time. We also need a release note in whatsnew/1.2.0.rst.

**Comment by k-fillmore** [comment]
Noted, working on NaT here. Will do a merge master and add change logs as requested.

**Review by arw2019 — COMMENTED** [review]
@k-fillmore are you interested in continuing? If yes merge master (looks like you have merge issues atm) and we'll take another look

**Comment by arw2019** [comment]
Closing for now. @k-fillmore let us know whenever you'd like to continue and we'll reopen!

**Pull request closed without merging**
