### PR TITLE
DOC: Add pyjanitor to ecosystem.rst

### PR DESCRIPTION
**Pull request by topper-123**
[pyjanitor](https://github.com/ericmjl/pyjanitor) is a quite nice pandas data cleaning library and gives its users some useful method on data frames. It's pipe oriented, so it can be helpful in data cleaning/transformation work.

Adding pyjanitor to the ecosystem page gives it visibility to our users and makes it easier for the users to discover if there is functionailty in pyjanitor, that will help their use cases.

### CODE REVIEW

**Comment by WillAyd** [comment]
Not super familiar with this package but does it just rename parts of the API? If so I'm not sure about putting it there as I feel like the API can just confuse with pandas' own

**Comment by gfyoung** [comment]
There does seem to be a lot of renaming, which IMO I'm not super-adverse to, as it could make a transition from R to `pandas` a little smoother.

**Comment by TomAugspurger** [comment]
It does more than that. Happy to add it to the ecosystem page.

**Review by WillAyd — APPROVED** [review]
Sounds good and lgtm

**Comment by topper-123** [comment]
Yeah, it does a lot of things and I particularly like to use it when I'm working interactively in ipython/Jupyter and in data cleaning scripts. It's a bit of a heavy dependency, so I don't include it in programs (because I want to minimize dependencies and make the programs leaner).

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
