### PR TITLE
ENH: Informative dtype message for for assert_series_equal

### LINKED ISSUE #28991: assert_frame_equal: "AssertionError: Attributes are different" is un-informative for DataFrames
#### Example from the docstring of `assert_frame_equal`

```
>>> from pandas.util.testing import assert_frame_equal
>>> df1 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
>>> df2 = pd.DataFrame({'a': [1, 2], 'b': [3.0, 4.0]})
>>> assert_frame_equal(df1, df2)
Traceback (most recent call last):
AssertionError: Attributes are different
...
Attribute "dtype" are different
[left]:  int64
[right]: float64
```
#### Problem description

The `AssertionError` is un-informative in that it does not state the column for which the error happens.

#### Expected Output
Something like:
```
AssertionError: Attributes of "DataFrame.iloc[:, 1]" are different
...
Attribute "dtype" are different.
```

#### Output of ``pd.show_versions()``

<details>                                                                                                                                                           

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-31-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : de_DE.UTF-8

pandas           : 0.25.0
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : 5.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.7.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.6
tables           : 3.5.2
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

#### Remedy
- `assert_frame_equal` passes `obj="{obj}.iloc[:, {idx}]".format(obj=obj, idx=i)` to `assert_series_equal`
- `assert_series_equal` should pass `obj=Attributes of "{obj}".format(obj=obj)` to `assert_attr_equal`

### PR DESCRIPTION
**Pull request by moi90**
Pass obj to assert_attr_equal in assert_series_equal.

- [ ] closes #28991
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry
- [x] Fix example in `assert_frame_equal` docstring

### CODE REVIEW

**Comment by moi90** [comment]
Which whatsnew do I have to change?

**Comment by jbrockmendel** [comment]
If there's nothing user-facing, you dont need a whatsnew entry

**Comment by moi90** [comment]
OK thanks! Then this pull request should be ready to merge.

**Comment by jreback** [comment]
can you merge master. ping when all green.

**Comment by jbrockmendel** [comment]
@moi90 can you rebase?  the CI failures should be fixed now

**Comment by jreback** [comment]
thanks @moi90

**Comment by moi90** [comment]
You're welcome!

**Pull request merged**
