### PR TITLE
DEPR: removing to_long and toLong, deprecated in 0.7.0

### LINKED ISSUE #19077: Remove to_long and toLong, deprecated in 0.7.0
Those `Panel` methods were deprecated in December 2011, before Pandas 0.7.0 was released [1]. Probably because they used the `deprecate`decorator, they weren't spotted before, and they weren't added to #6581. So, they are still available, even if they had to be removed in Pandas 0.10.0.

1. https://github.com/pandas-dev/pandas/commit/fae6272607d4e0787a2e5476b5401144473dfced

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #19077 
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you add a note to the Deprecations section. Also can you see if you can see when this was deprecated originally? its not in our master list.

**Comment by datapythonista** [comment]
@jreback I created an issue, with the information on when it was deprecated (in 2011), and added the note in whatsnew doc. Thanks a lot for the reviews, they're really helpful. Please let me know if this requires something else.

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by jreback** [comment]
thanks!

**Pull request merged**
