### PR TITLE
DOC: added more and updated links in cheat sheet

### PR DESCRIPTION
**Pull request by OliEfr**
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you say what you changed here.

cc @Dr-Irv

**Comment by OliEfr** [comment]
I created this PR #39707 (which was essentially the same) and it was merged yesterday with master. However, I checked in [pandas-dev:master](https://github.com/pandas-dev/pandas/tree/master/doc/cheatsheet) and my changes don't appear there.

That is why I created another this PR which is essentially the same.

(I used to use a [pullBot](https://wei.github.io/pull/) to stay up to date with master. I figured, that my changes might have been reversed by the pullbot?! Now I am not using a pullbot anymore.)

This is my first contribution to a larger OSS-Project and I am kind of confused by the automated tests. I am not sure how to fix the failing tests. Merging with master didn't help.

Sorry for confusion.

**Comment by Dr-Irv** [comment]
@jreback He added hyperlinks to the documentation from the cheat sheet.  I compared the current and his changes, and it looks fine to me.

**Comment by OliEfr** [comment]
Oh, thanks very much :) Happy to contribute!

**Pull request merged**
