### PR TITLE
xref #26189, xfail scipy interpolate test for pchip with timedelta

### PR DESCRIPTION
**Pull request by jreback**
xref #26189

### CODE REVIEW

**Comment by jreback** [comment]
cc @WillAyd this should over the failing numpy-dev build issue

**Comment by WillAyd** [comment]
Makes sense. lgtm if green

**Comment by jreback** [comment]
this will still fail on the doc-string validation issue (your PR is fixing)

**Comment by WillAyd** [comment]
Yea meant excluding that. Looks like there's something else I need to fix in that PR so feel free to merge this in advance

**Pull request merged**
