### PR TITLE
Removed indentation in documentation

### PR DESCRIPTION
**Pull request by thvranken**
Removed indentation in documentation
https://github.com/noatamir/scipy-2023-sprint/issues/8

@phofl, @noatamir

### CODE REVIEW

**Comment by rhshadrach** [comment]
By indenting the last bullet, sphinx is treating it as a separate block from the first line whereas I think we just want a natural continuation. Also, the first line of the last bullet is getting bolded.

image

[This SO answer](https://stackoverflow.com/a/54677891) seems to indicate your first commit here had the correct level of indentation; I'm wondering if the newline you've added at the top (before the list) was sufficient (I'm not sure).

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @thvranken

**Pull request merged**
