### PR TITLE
GH41457 Upgrade Bootstrap to v5.0

### LINKED ISSUE #41457: WEB: Upgrade Bootstrap from v4.0 to v5.0
Bootstrap has a [new stable version v5.0](https://blog.getbootstrap.com/2021/05/05/bootstrap-5/). I think it is a good idea to upgrade the website to use this new version. It no longer uses jQuery (one less dependency) and new features can be utilized by developers to further improve the website.

Please share your thoughts.

related to issue #41438 and pull request #41447

### PR DESCRIPTION
**Pull request by calvh**
Whats new:

Update BS script tags in template

Replace jumbotron with utilities

Replace font-weight-bold with fw-bold

Replace ml-auto with ms-auto

Replace float-right with float-end

Replace data-target with data-bs-target

Replace data-toggle with data-bs-toggle

Add CSS rules for <a>

- [x] closes #41457 
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by calvh** [comment]
Live preview [here](https://adoring-swanson-8508a0.netlify.app/)
I have the build folder too in case anyone wants to double check locally without pulling the branch.

**Review by datapythonista — APPROVED** [review]
Thanks @calvh, really nice. Lgtm, sorry for the delay.

Do you mind merging master? I think the CI should be green now.

**Comment by calvh** [comment]
Thank you @datapythonista! I am sorry this may be a dumb question, but do you mean I should merge with the latest master so that the CI will pass? If so, should I be doing merge (fast-forward) or rebase?

**Comment by datapythonista** [comment]
Your branch was created two weeks ago, so your changes (the diff in this PR) are proposed on that old `master`. That master was broken for some problems with the development branch of numpy, that's why the CI is red.

So, the idea is that you updated your branch, so it contains all the changes in master for the last two weeks. The CI should be then green, and also, if anything changed in master that affects this PR, we should have it in the diff and in the CI.

In practice, that's simply `git fetch upstream`, and then `git merge upstream/master` being in your branch. And then you `git push` to update this PR.

Does it make sense?

**Comment by calvh** [comment]
@datapythonista I need some help, I merged master but some CI checks are still failing. Should I merge again with the latest master and try again? Thank you in advance.

**Comment by datapythonista** [comment]
I can't check in detail now, but seems like all last PRs are red, so I guess something is broken in master. You'll have to wait until it's fixed, and thrn merge master again.

**Comment by calvh** [comment]
@datapythonista thought I'd try again after merging with the latest master, but still no luck :(

The error from one of the failing check occurs when running the bash script to create the conda environment

`("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`

I wonder what I can do to fix this problem?

**Comment by datapythonista** [comment]
Let's rerun and see, seems like conda servers are having problems recently.

**Comment by calvh** [comment]
Thank you!

All the tests passed except one. Looks like an issue with one of the `scalar/timedelta` tests. There is currently a PR to fix it (#42413). Once that is merged to master I will merge and push again.

**Comment by calvh** [comment]
@datapythonista all the tests passed. Thank you for your guidance and assistance!

**Comment by jreback** [comment]
thanks @calvh

**Pull request merged**
