### PR TITLE
CI: add conda-forge as lowest priority channel

### PR DESCRIPTION
**Pull request by jreback**
xref #14495

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback The failing test for the python 3.4 build is due to a very old version of sqlalchemy that is installed (0.7.1). Not sure where this is coming from, as the requirements file do not specify a version.

**Comment by jorisvandenbossche** [comment]
Ah, it's coming from the `pandas` conda channel. I suppose the conda-forge channel had priority over that before. 
Is there a reason you want conda-forge as the lowest priority?

**Comment by jreback** [comment]
@jorisvandenbossche yeah maybe I should just take this out of the pandas channel. The idea with conda-forge is that we can pick up things that are *not* in the default channel (quicker), but if they are already there, use them. The reasoning is that most people are using *defaults*, so we want to be exposed to that pipeline first.

The case here is ``bottleneck==1.2.0`` which is only on conda-forge (ATM).

**Comment by jorisvandenbossche** [comment]
That sounds good as a reasoning. 
Are there actually still packages in the pandas channel we need? I suppose eg `psycopg2` is in the meantime also available in either defaults or conda-forge

Is specifying a version in a requirements file enough to trigger it to get it from conda-forge?

https://github.com/conda-forge/bottleneck-feedstock/pull/7 is merged in the meantime, so you can specify 1.2.0 for one of the builds?

**Comment by jreback** [comment]
yeah I need to add the new version on a build (unfort have to manually specify it).

yes, can prob remove the need for the pandas channel entirely (if we have conda-forge), or maybe will add that one *after*. will try later

**Comment by jreback** [comment]
closing for now. have better ways to do this esp when you need to specify more things than a channel, e.g. 34_SLOW build. / 3.6 build

**Pull request closed without merging**
