### PR TITLE
ENH: GH10485 'Frequency' label for Series.plot

### PR DESCRIPTION
**Pull request by clarkfitzg**
More informative label for histogram.

Conversation in #10485

### CODE REVIEW

**Comment by sinhrks** [comment]
Thanks! Please do:

- Fix the test cases under ``pandas/tests/test_graphics.py``
- Add release note to ``doc/source/whatsnew/v0.17.0.txt``

**Comment by clarkfitzg** [comment]
@sinhrks Tests pass locally now. Is there a way to trigger another build on Travis?

**Comment by sinhrks** [comment]
If you've updated this branch, please once rebase then push with force flag (``-f``). Travis test runs automatically.

https://github.com/pydata/pandas/wiki/Git-Workflows

**Comment by clarkfitzg** [comment]
Ok, rebased. Build log shows this failure, which I believe is unrelated:

```
FAIL: test_metadata_immutable (pandas.tests.test_index.TestMultiIndex)
```

**Comment by shoyer** [comment]
Indeed, build failure was unrelated -- I just retriggered your tests

**Comment by clarkfitzg** [comment]
@sinhrks build looks good now.

**Pull request merged**
