### PR TITLE
DOC: update usage of randn in io.rst

### LINKED ISSUE #24148: DOC: update usage of randn in io.rst
In the IO page of the docs (https://github.com/pandas-dev/pandas/blob/master/doc/source/io.rst), there are some occurrences of direct calls to `randn` instead of using the properly imported `np.random.randn` in full, which makes the examples not reproducible if you only imported `import numpy as np`.

A PR that replaces `randn` with `np.random.randn` would thus be very welcome.

### PR DESCRIPTION
**Pull request by charlesdong1991**
- [x] closes #24148
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @charlesdong1991

**Comment by datapythonista** [comment]
@charlesdong1991 the azure CI is red, can you fix the error please

`doc/source/io.rst(4153,83): error E501: line too long (87 > 79 characters)`

**Comment by datapythonista** [comment]
@charlesdong1991 not sure why you undid the commit that fixed the PEP8 error, but we need it to merge this. CI is failing because of it.

**Comment by charlesdong1991** [comment]
ahh, @datapythonista , sorry, since in the last submit, the error was caused by `metadata` in developer.rst, and i didn't know why it was related to my change here, so i undid the commit to verify it... looks like it's unrelated, and i saw other PRs, and some of them have the same problem, probably something was wrong in master ( and seems master is healthy now)... so this time i added the change back to fix linting error, should pass the all tests now...

**Comment by datapythonista** [comment]
master was broken, and in those cases you can just wait until we fix it  then merge master and push again

You may have to merge the latest master to make the CI pass here, not sure.

**Comment by charlesdong1991** [comment]
thanks, @datapythonista , i get it! If the tests fail again, I will merge the latest master and push again.

**Pull request merged**
