### PR TITLE
BUG: disallow scalar in Categorical constructor

### LINKED ISSUE #38433: BUG/API: allowing scalars in Categorical constructor
I expected this to raise

```
>> pd.Categorical("A")
['A']
Categories (1, object): ['A']
```

This gets listified inside the call to `maybe_infer_to_datetimelike` in `Categorical.__init__`

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #38433
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
We could also easily deprecate this first. I don't know if others would rely on it, but at least we did ourselves (the behaviour was explicitly tested)

**Comment by jreback** [comment]
indifferent here. am ok pushing this thru or deprecating.

**Comment by jreback** [comment]
doesn't this duplicate #38614 (or vice versa)

**Comment by jbrockmendel** [comment]
> doesn't this duplicate #38614 (or vice versa)

no.  one is for Categorical, the other for CategoricalIndex

**Comment by jreback** [comment]
> > doesn't this duplicate #38614 (or vice versa)
> 
> no. one is for Categorical, the other for CategoricalIndex

ok.

should we deprecate this? i agree its very weird, but i suppose it might happen in the real world.

**Comment by jorisvandenbossche** [comment]
Given that we had tests for it, and that it is actually also allowed for Series, I would go for deprecation first (it shouldn't be hard I think?)

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request merged**
