### PR TITLE
CI: Auto-cancel redundant builds

### PR DESCRIPTION
**Pull request by TomAugspurger**
This removes the `workflows` section from the `cirleci` config, which broke auto-cancellation.

Also testing whether azure auto-cancels builds.

cc @gfyoung

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I've had 3 commits

1. the initial commit when opening the PR
2. a second commit `cancel?` after the CIs received their web hook notification
3. a third commit `cancel 2?` after the Cis received their second web hook notification

**Comment by TomAugspurger** [comment]
In theory, https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=2495&view=logs should not be built, since there are later commits on the same branch.

**Comment by TomAugspurger** [comment]
Heh, this was testing azure, but I notice circleci isn't cancelling either.

https://discuss.circleci.com/t/auto-cancel-redundant-builds-not-working-for-workflow/13852/33 says that workflows don't support it yet, but we don't need workflows. Will make this into a real PR now :)

**Comment by TomAugspurger** [comment]
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=2495&view=logs ran, even though we'd like it to have been auto-canceled (I manually canceled the last two).

@chrispatterson do you know if azure pipelines supports auto-cancelling builds when a branch has new commits? Something similar to what's described in https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation. If not, is there a place I should go to voice support for that feature?

**Comment by TomAugspurger** [comment]
@vtbassmatt do you know if there's a way to auto-cancel queued (or maybe running) builds when new commits are pushed to a PR branch?

**Comment by vtbassmatt** [comment]
That should be the current behavior. (In fact, we've been asked for an explicit flag to override that behavior, which we're in the process of building.) @DavidStaheli any thoughts on why Pandas PR pipelines aren't auto-canceling?

**Comment by DavidStaheli** [comment]
@TomAugspurger, this is a bug specific to using the Azure Pipelines GitHub App.  I'm so sorry for the time it cost you!  We should have a fix deployed to production tomorrow (Thursday) or Friday.

**Comment by jreback** [comment]
@TomAugspurger lgtm. Pls merge if this will fix the issue.

**Comment by TomAugspurger** [comment]
This will hopefully fix circle. Azure should be fixed with no config changeable.

**Comment by datapythonista** [comment]
@DavidStaheli just in case you're not aware, auto-cancel is still not working

**Comment by DavidStaheli** [comment]
Thanks @datapythonista.  It looks like deployment was delayed at the end of last week and is proceeding again.  Fingers crossed, the fix will be in production by Tuesday afternoon (eastern time) at the latest.

**Comment by datapythonista** [comment]
I guessed it was just delayed, but wanted to let you know just in case you thought it was fix. Thanks for the update @DavidStaheli

**Comment by datapythonista** [comment]
@DavidStaheli I'd say that auto-cancel is still not working, is that expected?

**Pull request merged**
