### PR TITLE
CI/TST: fix failing tests in py37_np_dev

### PR DESCRIPTION
**Pull request by ShaharNaveh**

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm if green

**Comment by WillAyd** [comment]
Looks like need to manually backport @Momisbestfriend mind doing that?

**Comment by MomIsBestFriend** [comment]
> Looks like need to manually backport @MomIsBestFriend mind doing that?

sure!

**Comment by MomIsBestFriend** [comment]
@WillAyd I just checked it again, and this is not an external error message.

https://github.com/pandas-dev/pandas/blob/a72eef5a86979232337149961d2122f0b555c876/pandas/core/indexes/range.py#L698

And it's located in:

```python
# class RangeIndex(Int64Index):

def __getitem__(self, key):
        """
        Conserve RangeIndex type for scalar and slice keys.
        """
        if isinstance(key, slice):
            new_range = self._range[key]
            return self._simple_new(new_range, name=self.name)
        elif is_integer(key):
            new_key = int(key)
            try:
                return self._range[new_key]
            except IndexError:
                raise IndexError(
                    f"index {key} is out of bounds for axis 0 with size {len(self)}"
                )
        elif is_scalar(key):
            raise IndexError(
                "only integers, slices (`:`), "
                "ellipsis (`...`), numpy.newaxis (`None`) "
                "and integer or boolean "
                "arrays are valid indices"
            )
        # fall back to Int64Index
        return super().__getitem__(key)
```

I think that a future version of numpy will break ```pd.RangeIndex```.

**Comment by jorisvandenbossche** [comment]
> this is not an external error message.

That's only for RangeIndex (where we mimic numpy's behaviour and error messages), for all other cases it comes from numpy I think?

> I think that a future version of numpy will break pd.RangeIndex.

How do you mean?

**Comment by MomIsBestFriend** [comment]
> How do you mean?

@jorisvandenbossche  Now that you explained that

> That's only for RangeIndex (where we mimic numpy's behaviour and error messages), for all other cases it comes from numpy I think?

I don't think that a future version of numpy will break ```RangeIndex```, I didn't understand what was going on before, but now I do.

Thank you for your explanation :)

**Pull request merged**
