### PR TITLE
PERF: reductions

### PR DESCRIPTION
**Pull request by jbrockmendel**
Discussed on today's call

### CODE REVIEW

**Comment by jreback** [comment]
forgot the ref issue, but this improves the relevant asvs's?

**Comment by jbrockmendel** [comment]
> forgot the ref issue, but this improves the relevant asvs's?

Based on the most-affected asv discussed on the call:

```
In [2]: ser = pd.Series([True] * 10**6)

In [3]: %timeit ser.all()
53.3 µs ± 1.85 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)  # <-- PR
431 µs ± 7.61 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)  # <-- master

```

**Comment by jorisvandenbossche** [comment]
Sorry, I didn't see you opened a PR already (it could help to reference the original PR), and I also made one this morning: https://github.com/pandas-dev/pandas/pull/41920 

I think my fix might be a bit simpler, but didn't check in detail.

**Comment by jreback** [comment]
they are pretty similar. going to merge this one as its slightly more explict.

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Comment by jorisvandenbossche** [comment]
Sorry Jeff, I don't really appreciate that (yes it was duplicate work, but I also did put time in this, then at least give some time to discuss what's the best approach), so I reverted this

**Comment by jorisvandenbossche** [comment]
And sorry for my over-reaction, I shouldn't have directly reverted the merge. I was just annoyed by the lack of time to respond, but I didn't need to revert it for that.

**Comment by jorisvandenbossche** [comment]
I opened a new PR with Brock's change -> https://github.com/pandas-dev/pandas/pull/41924

**Comment by jreback** [comment]
@jorisvandenbossche this is a way over reaction 

brock's pr was first and is better

but you can handle now

**Pull request merged**
