### PR TITLE
CI: enable arm64 build on drone.io #39730

### LINKED ISSUE #39730: CI: enable drone.io
I have enabled https://cloud.drone.io/ to connect to pandas. We need to configure it, ideally for arm64 builds (only).

cc @xhochy

### PR DESCRIPTION
**Pull request by fangchenli**
- [x] closes #39730
xref #36719

### CODE REVIEW

**Comment by jreback** [comment]
a couple of thoughts here.

- can you make multiple sections on drone, e.g. setup / build / test (mainly to separate out the building from the testing).
- you can just start with very minimal deps, e.g. numpy & dateutil  to make this faster.

**Comment by jreback** [comment]
great this looks like its running now; i would xfail the tests that are failing and open an issue for them.

**Comment by fangchenli** [comment]
xref #38921 #38923

xpass #38798

**Review by jreback — CHANGES_REQUESTED** [review]

**Comment by jreback** [comment]
hmm looks like it is timing out, for sure skip the slow tests. maybe have to see what is slow on arm and re-add back the arm_slow (or similar) to skip more.

**Comment by fangchenli** [comment]
The building phase took either 4 min or 14 min. Not sure why.

**Comment by fangchenli** [comment]
drone_build_23
drone_build_24

**Comment by fangchenli** [comment]
drone_build_23
drone_build_24

**Comment by fangchenli** [comment]
@jreback I asked Drone about the performance issue https://discourse.drone.io/t/unstable-performance-on-arm64/8833. This is the response: 

> Drone Cloud (cloud.drone.io) is our personal Drone instance that we make available to the public for testing and evaluation purposes; it has limited capacity. Once you evaluate the product, you should decide whether or not you want to install Drone on your own infrastructure (the same way you would install Jenkins). Drone is meant to be a Jenkins alternative (self-hosted) as opposed to a Travis alternative (saas).

**Comment by jreback** [comment]
so basically this is unusable :(

iirc numpy does build arm for CI but i don't recall exactly where

cc @seberg

**Comment by seberg** [comment]
We did not move away from TravisCI, instead apparently the right tree got shaken and (apparently enough) credits fell out: https://github.com/numpy/numpy/issues/17824#issuecomment-733878761

Is that is what you were asking?  I suppose that should also work for pandas, but I am not sure about the correct "process" for it. Maybe pinging those involved directly, although it would be nice if there was a better solution after the initial quick policy-change...

**Comment by fangchenli** [comment]
Let's find the right tree :)

**Comment by jreback** [comment]
i am going to hook us up with circleci which i think supports arm (or does so via a docker image)

**Pull request closed without merging**
