### PR TITLE
BUG: Timedelta.total_seconds() precision issue

### LINKED ISSUE #19458: Precision error when using Timedelta.total_seconds method
#### Code Sample
```python
>>> import pandas as pd
>>> block = pd.Timedelta('30S')
>>> block.total_seconds()
30.000000000000004
>>> 

```
#### Problem description
When using `Timedelta.total_seconds` I sometime encounter a small precision error (1e-15), which can be significant in some scenarios (for instance when later dividing the results and expecting an integer). The workaround is to always use a rounding method, which makes the code cumbersome.

#### Expected Output
A float or integer representing the seconds precisely.

#### Output of ``pd.show_versions()``

<details>

>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-5-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.utf8
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 38.4.0
Cython: None
numpy: 1.14.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by CruiseDevice**
- [x] closes #19458
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks! Could you add a test for this, maybe in `pandas/tests/scalar/test_timedelta.py` and a release note?

**Comment by CruiseDevice** [comment]
@TomAugspurger okay. I will try to work on tests. What does a release note mean?

**Comment by TomAugspurger** [comment]
A line in `doc/source/whatsnew/v0.23.0.txt`: http://pandas.pydata.org/pandas-docs/stable/contributing.html#documenting-your-code

**Comment by CruiseDevice** [comment]
```
rng = Timedelta('30S')
expt = 30.0
tm.assert_almost_equal(rng.total_seconds(), expt)

```
I wrote something like this. Is this correct?

**Comment by jreback** [comment]
you could do
``assert expected - result < 1e-20`

**Comment by jreback** [comment]
can you add a test & a whatsnew note

**Comment by jreback** [comment]
nvm. this was closed via https://github.com/pandas-dev/pandas/pull/19783/files

**Pull request closed without merging**
