### PR TITLE
DOC: Fix language style

### PR DESCRIPTION
**Pull request by alimcmaster1**
- Ref: https://9to5google.com/2020/06/12/google-android-chrome-blacklist-blocklist-more-inclusive/
- Ref: https://android-review.googlesource.com/c/platform/frameworks/ml/+/970739

cc @pandas-dev/pandas-core

### CODE REVIEW

**Comment by wesm** [comment]
Thanks for doing this

**Comment by WillAyd** [comment]
Lgtm

**Review by datapythonista — APPROVED** [review]
Thanks @alimcmaster1, lgtm. Is this ready to be merged? I see the `WIP` in the title.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by TomAugspurger** [comment]
LGTM. These are all internal, so no need for a deprecation correct?

Thoughts on adding a linting rule to catch these in the future?

**Comment by alimcmaster1** [comment]
> LGTM. These are all internal, so no need for a deprecation correct?
> 
> Thoughts on adding a linting rule to catch these in the future?

Yep all internals. Good shout if ppl think a lint check is helpful here i'm happy to add.

P.S Any further thoughts/further ideas in the space welcomed.

**Comment by WillAyd** [comment]
Thanks @alimcmaster1

**Comment by alimcmaster1** [comment]
> Thanks @alimcmaster1

Thanks @WillAyd

**Pull request merged**
