### PR TITLE
Fix docstring error

### PR DESCRIPTION
**Pull request by WuraolaOyewusi**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WuraolaOyewusi** [comment]
Hello Marc @datapythonista .
Kindly confirm if this is as discussed.
Thank you

**Comment by jorisvandenbossche** [comment]
Do we rather want to update the validation script to allow this? (because now we are duplicating an explanation that almost nobody needs)

**Comment by WuraolaOyewusi** [comment]
@jorisvandenbossche . That will be faster especially for the *args and **kwargs. Some of the functions with PR02 errors have totally different parameters from their docstrings. 
I don't know how to go about updating the validation script. If you have the time, you can put me through.

**Comment by datapythonista** [comment]
Agree with Joris. Any other of the errors in the parameters can be fixed in
the docstrings, but having args and kwargs together is a false positive of
the validation, we should update the script.

I think I opened an issue for this, and not sure if someone was already
working on it. Can you have a look and see if you can find that issue, not
sure if in the mentoring repo or in pandas itself. I'm in my phone with
poor internet connection right now, but will help you later if you can't
find it.

**Comment by WuraolaOyewusi** [comment]
Ok marc. I will check

**Comment by WillAyd** [comment]
#28811 was just merged and should allow for this, so I don't think this PR is applicable any more.

Thanks of course for the submission @WuraolaOyewusi - there are plenty more out there would welcome contributions on

**Pull request closed without merging**
