### PR TITLE
BUG: median() not correctly handling non-float null values (fixes #10…

### LINKED ISSUE #10040: Median returns odd value when applied to timedeltas
```python
from pandas import DataFrame
from numpy import datetime64
data = ['2015-02-03', '2015-02-07']
data = DataFrame(data, dtype=datetime64)
data.diff().median()
```

This code returns 
```python
0   -53374 days +00:06:21.572612
dtype: timedelta64[ns]
```
while I would expect it to return the same as data.diff().mean()
```python
0   4 days
dtype: timedelta64[ns]
```

Here is my setup

```python
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Darwin
OS-release: 14.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.16.0
nose: 1.3.4
Cython: None
numpy: 1.9.2
scipy: 0.14.0
statsmodels: None
IPython: 2.3.1
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.2
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.2
openpyxl: 2.1.3
xlrd: 0.9.3
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.5.4 (dt dec pq3 ext)
```

### PR DESCRIPTION
**Pull request by mortada**
closes #10040

### CODE REVIEW

**Comment by mortada** [comment]
Note that the existing unit test is actually wrong

```
In [1]: from pandas import Series, Timestamp

In [2]: from datetime import timedelta

In [3]: s = Series([Timestamp('20130101') + timedelta(seconds=i*i) for i in range(10)])

In [4]: td = s.diff()

In [5]: td
Out[5]:
0        NaT
1   00:00:01
2   00:00:03
3   00:00:05
4   00:00:07
5   00:00:09
6   00:00:11
7   00:00:13
8   00:00:15
9   00:00:17
dtype: timedelta64[ns]
```

`td.median()` should really be `00:00:09` instead of `00:00:08` as it is currently asserting.

**Comment by jreback** [comment]
pls add a release note for 0.16.1

**Comment by mortada** [comment]
@jreback it's updated

**Comment by jreback** [comment]
ty!

side issue. I briefly looked it and it appears to work, but are there cases where precision drops are an issue? e.g. we have int64 converted to float64 which drops precision, but it DOES seem to work. if you can experiment and see (I don't have a good) example. If you find somethign pls file an issue.

**Comment by mortada** [comment]
sure I'll play with this and see if I can find examples where precisions become an issue. It does seem like it could be a problem.

**Pull request merged**
