### PR TITLE
REF: raise scalar_data_error to make mypy happy

### PR DESCRIPTION
**Pull request by jbrockmendel**
@simonjayhawkins do I need to update a config file or enable something?

### CODE REVIEW

**Comment by WillAyd** [comment]
Have you tried using `NoReturn` for the return value of `_scalar_data_error`? It wasn't added until Python 3.5.4 so will fail the CI pinned to 3.5.3, but could be reasonable to use going into 1.0.0

**Comment by jbrockmendel** [comment]
I haven't tried that, will look into it for future reference.  In this particular case I agree with mypy that this is clearer than the status quo

**Comment by simonjayhawkins** [comment]
> In this particular case I agree with mypy that this is clearer than the status quo

tend to agree, although the `NoReturn` is intended for patterns like this.

**Review by simonjayhawkins — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
lgtm. @WillAyd

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks!

**Pull request merged**
