### PR TITLE
ENH: return RangeIndex from difference, symmetric_difference

### LINKED ISSUE #12034: ENH: Return RangeIndex for .difference and .symmetric_difference
xref https://github.com/pydata/pandas/pull/11892

possible to return `RangeIndex` more often for:
- [x] `union` #12109 
- [ ] `difference` & `sym_diff`
- [x] revisit `__floordiv__` #12070

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #12034
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@iamlemec can you take a look and tell me what needs to be done here to be consistent with what you're doing in #36413?

**Comment by iamlemec** [comment]
> @iamlemec can you take a look and tell me what needs to be done here to be consistent with what you're doing in #36413?

I think the most consistent way here would be to use `_wrap_setop_result` on the final return statement and `_get_reconciled_name_object` on the quick return statements up top. I actually didn't really touch `difference` and `symmetric_difference` in #36413, but it would make sense that they get a similar treatment.

My only concern regarding `difference` is that maybe since it's not a symmetric operation, it's naming rule should be left-biased. Like, if you're just dropping a few nameless elements, should that clobber the original name?

**Comment by jbrockmendel** [comment]
added name checks to tests

**Comment by jreback** [comment]
i guess this is technically a change, can you add a note; ping on green.

**Comment by jbrockmendel** [comment]
ping

**Pull request merged**
