### PR TITLE
TST: Fixturize series/test_arithmetic.py

### PR DESCRIPTION
**Pull request by Anjali2019**
This is in reference to issue #22550

### CODE REVIEW

**Comment by h-vetinari** [comment]
Your test won't be able to pass as is because `test_api.py` has a class `SharedWithSparse`, where some tests for `SparseSeries` inherit the same tests, but then don't have the required fixtures available. I ran into exactly the same problem on the DataFrame-side, see #22738 how I solved it.

Probably best to revert the commit for `test_api.py` here and open a separate PR for that.

**Comment by h-vetinari** [comment]
Also (now that I'm trying to update the references in #22550), it seems you've already got a PR for `test_analytics.py` and `test_validate.py`. Probably best to revert those here too.

**Comment by h-vetinari** [comment]
OK, I now see that you *have* separate PRs for those other files as well. But make sure each PR only changes one module. You can `git revert <hash-of-commit>` the others.

Furthermore, I'd recommend to wait until 2-3 of your 6 open PRs manage to go through review, before you open more of them. Chances are you'll get feedback that will be relevant to the future PRs and will save you time-intensive reverting/rebasing/restarting.

**Comment by Anjali2019** [comment]
Corrected all PRs

**Pull request closed without merging**
