### PR TITLE
Use _values_for_factorize by default for hashing ExtensionArrays

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
PR https://github.com/pandas-dev/pandas/pull/51319 added the `EA._hash_pandas_object` method to let ExtensionArrays override how they are hashed. But it also changed to no longer use the values returned by `EA._values_for_factorize()` by default for hashing, but change this to `EA.to_numpy()`.  The previous behaviour was documented, and changing this can cause regressions / changes in behaviour or performance (depending on the return values of those two methods). 

See https://github.com/pandas-dev/pandas/pull/51319/files#r1212106303 for some more details.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jbrockmendel are you OK with this?

**Comment by jorisvandenbossche** [comment]
Sorry for the backport noise, the original PR was only for 2.1, so of course this fixup only needs to target 2.1 as well

**Comment by lithomas1** [comment]
Does this need a whatsnew?

This looks like only a regression on main.
(If so, the whatsnew can be deleted)

**Comment by jorisvandenbossche** [comment]
Good catch, sorry! I only realized after merging it was only a change on main and thus didn't need to be backported, but forgot that I actually added a whatsnew ...

**Pull request merged**
