### PR TITLE
TST: clean deprecation warnings for xref #19980

### PR DESCRIPTION
**Pull request by jreback**
xfail some mpl > 2.1.2 tests

### CODE REVIEW

**Comment by jreback** [comment]
@jorisvandenbossche
cc @GGordonGordon  

would have rather actually changed the usage of ``tsplot`` to the non-deprecated form in all places (except the actual deprecation test), followup PR would be great.

**Comment by jorisvandenbossche** [comment]
@jreback sorry, somehow I had in my mind that we didn't use this `tsplot` method at all, which is also the case in the code, but apparently not in the tests ... and didn't check that when merging. 

I personally wouldn't bother with changing the tests to non-deprecated version (it seems the tests already test both), but rather just remove them.

**Comment by jorisvandenbossche** [comment]
@jreback did you open an issue for matplotlib 2.2? As this is unrelated I think to the tsplot deprecation?

**Comment by jreback** [comment]
@jorisvandenbossche no I didn't open an issue for mpl 2.2.2. the package is *only* on conda-forge and I don't think works on mac. just trying to fix the build. not even sure what's wrong.

**Comment by jorisvandenbossche** [comment]
@jreback it are issues with the new matplotlib release, not specifically related to mac. Opened an issue for this: https://github.com/pandas-dev/pandas/issues/20031

**Comment by jreback** [comment]
the mac issue were existing for those tests

**Comment by jorisvandenbossche** [comment]
yes, i know, I justed wanted to say that the *new* failure is only related to the new mpl release and not specifically to mac. But that's how you skipped it now, so perfect. We should only actually solve it, therefore opened the issue.

**Pull request merged**
