### PR TITLE
BUG: Convert <br> to space in `pd.read_html`

### LINKED ISSUE #29528: pd.read_html() convert <br> to space
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
pd.read_html('http://vybary2019.by/regions/49.html',header=0)[0]
```
#### Problem description
In original web page the first cell of table contains three separate words.

image

In `pandas` table the first cell contains only two words, with first word being the join of the former two first.

image

[**why** the current behaviour is a problem]
Because during pandas parsing there is a data loss that is non-trivial to fix.

The reason for this behaviour is the presence of `<br>` tag between first two words in original content. 

image

`<br>` should be converted to space or at least to a new line when converting to text representation.

I found the similar reference in https://github.com/pandas-dev/pandas/issues/14608#issuecomment-274268024 but no separate GitHub issue.

#### Expected Output

image

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.14.137+
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.3
pytz             : 2018.9
dateutil         : 2.6.1
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : 3.6.4
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : 0.4.0
xlsxwriter       : None
lxml.etree       : 4.2.6
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 5.5.0
pandas_datareader: 0.7.4
bs4              : 4.6.3
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.6
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.5.9
pandas_gbq       : 0.11.0
pyarrow          : 0.14.1
pytables         : None
s3fs             : 0.3.5
scipy            : 1.3.1
sqlalchemy       : 1.3.10
tables           : 3.4.4
xarray           : 0.11.3
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : None
</details>

### PR DESCRIPTION
**Pull request by abmyii**
- [x] closes #29528
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by attack68** [comment]
since <br> is a line break is it better to convert it to `\n`?

**Comment by abmyii** [comment]
> since `<br>` is a line break is it better to convert it to `\n`?

I do convert it to `\n` in the code - however pandas either replaces it or renders it as a space. I'm not sure if it is worth forcing the matter, but I'd be interested to see what the maintainers opinions are.

**Comment by abmyii** [comment]
> This pull request is stale because it has been open for thirty days with no activity. Please [update](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#updating-your-pull-request) and respond to this comment if you're still interested in working on this.

Ping @attack68

**Comment by attack68** [comment]
Can you merge master.

This looks good to me, the solution opens the door to a list of general replacements if we also want to go that way in the future.

**Review by attack68 — CHANGES_REQUESTED** [review]
needs merge

**Comment by abmyii** [comment]
> needs merge

OK now?

**Comment by jreback** [comment]
@attack68 ok here?

**Review by attack68 — APPROVED** [review]
lgtm

**Comment by jreback** [comment]
thanks @abmyii

**Comment by HymanHuang** [comment]
> > since `<br>` is a line break is it better to convert it to `\n`?
> 
> I do convert it to `\n` in the code - however pandas either replaces it or renders it as a space. I'm not sure if it is worth forcing the matter. Thoughts?

function `_remove_whitespace` caused it

image

@attack68 @abmyii

**Pull request merged**
