### PR TITLE
DEPR: lowercase strings `w`, `d`, `b` and ``c`` denoting frequencies in `Week`, `Day`, `BusinessDay` and `CustomBusinessDay` classes

### PR DESCRIPTION
**Pull request by natmokval**
xref #57986

- deprecated lowercase strings `d`, `b` and `c` denoting frequencies in `Day`, `BusinessDay` and `CustomBusinessDay` in favour of `D`, `B` and `C`
- deprecated lowercase strings `w`, `w-mon`, `w-tue`, etc. denoting frequencies in `Week` in favour of `W`, `W-MON`, `W-TUE`, etc. 

we can  deprecated lowercase strings `w`, `d`, `b` and `c` for `Timedelta` in a separate PR

### CODE REVIEW

**Comment by natmokval** [comment]
I deprecated lowercase strings `w`,  `d`, `b` and `c` denoting frequencies in favour of `W`, `D`, `B` and `C`. @MarcoGorelli, could you please take a look at this PR? I think CI failures are unrelated to my changes.

**Review by MarcoGorelli — COMMENTED** [review]
Looks good to me

Given that 2.3 isn't out yet, I wonder if it makes sense to get this in for 2.3, and then in 3.0 we make all these changes in one go and be done with it?

**Comment by MarcoGorelli** [comment]
@mroeschke thoughts on 2.3 vs 3.0?

**Review by MarcoGorelli — APPROVED** [review]
If in doubt, let's just follow the usual process - deprecate in 3.0, remove thereafter - will merge then if there's no further objections

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @natmokval and @MarcoGorelli

**Pull request merged**
