### PR TITLE
DOC: Fix read_hdf docstring

### PR DESCRIPTION
**Pull request by bashtage**
Read HDF docstring was not in NumPy format.  Corrects the formatting

[skip ci]

- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bashtage** [comment]
The rendered docstring

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_hdf.html

does not have the correct appearance.

**Comment by jreback** [comment]
can you run the validation script on this?

**Comment by bashtage** [comment]
Seems inevitable since signature uses **kwargs to capture most inputs.

```
Errors found:
        Errors in parameters section
                Unknown parameters {'iterator', 'start', 'chunksize', 'where', 'columns', 'stop '}
```

**Comment by TomAugspurger** [comment]
CI wasn't running, pushed a commit w/ a few small changes (mentioning `__fspath__`) to re-trigger it.

**Review by TomAugspurger — APPROVED** [review]

**Comment by TomAugspurger** [comment]
Merging since the doc build passed cleanly.

**Pull request merged**
