### PR TITLE
[DOC] Transferring data from the 6th column to the first.  #44379

### PR DESCRIPTION
**Pull request by Mikhaylov-yv**
Transferring data from the 6th column to the first.
This should resolve issue #44379

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks @Mikhaylov-yv - could you post a screenshot of the docs please?

**Comment by Mikhaylov-yv** [comment]
@MarcoGorelli

Oh sure. I just don't understand why the links in the first column do not work for me:

-- :ref:`categorical`

skrin

**Comment by MarcoGorelli** [comment]
Thanks - it may be that you need to build the whole documentation, rather than just the page, in order for the link to work?

**Comment by Mikhaylov-yv** [comment]
Yes, you are right.

Снимок экрана от 2021-11-14 01-07-40

**Comment by MarcoGorelli** [comment]
Thanks @Mikhaylov-yv - is it possible to have it such that the text redirects to the link? E.g. clicking on "Intervals" redirects to "IntervalIndex".

If not, an alternative would be to write it as "Intervals - see IntervalIndex", it just looks a bit funny like this

**Comment by Mikhaylov-yv** [comment]
Thanks @MarcoGorelli
Now I figured out how to do it. It turned out grea
Снимок экрана от 2021-11-14 23-03-25
t.

**Review by MarcoGorelli — APPROVED** [review]
Looks good to me!

Leaving open for a bit in case others have comments

**Comment by Mikhaylov-yv** [comment]
@MarcoGorelli  Yes fine. No problem.

I am just checking for other updates.

**Comment by jreback** [comment]
thanks @Mikhaylov-yv 

let's check the built docs to make sure this looks good

**Pull request merged**
