### PR TITLE
STYLE: fix pylint no-method-argument warning

### PR DESCRIPTION
**Pull request by gulyapulya**
- [ ] Refers to one of the issues in #48855
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

I have removed "no-method-argument" from pyproject.toml and addressed all the lines that create a warning.  I followed this [documentation](https://docs.quantifiedcode.com/python-anti-patterns/correctness/method_has_no_argument.html) on anti-patterns and corresponding best practices. 

This is my first Hacktoberfest and I was wondering if you could add "hacktoberfest-accepted" label to this PR to count. 

Thanks, and please let me know if any changes are required. 😊

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
looks good to me, thanks

CI failure looks unrelated, will re-trigger this once it's sorted out

**Comment by gulyapulya** [comment]
@MarcoGorelli, alright, thanks, I will wait then. Let me know if I should adjust anything. :)

**Comment by MarcoGorelli** [comment]
thanks @gulyapulya !

**Comment by gulyapulya** [comment]
Welcome! @MarcoGorelli, would it be possible to add "hacktoberfest-accepted" label to this PR? This will be much appreciated and help me in my first Hacktoberfest!

**Pull request merged**
