### PR TITLE
Replace custom macro with stdlib 

### PR DESCRIPTION
**Pull request by WillAyd**
This is part of the C99 standard so I think better to leverage builtin functionality rather than redefine

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM pending green

**Comment by jbrockmendel** [comment]
test failure looks similar to #29976.

**Comment by jbrockmendel** [comment]
possibly related to #30065

**Comment by jorisvandenbossche** [comment]
You can ignore that error, did a quick "fix" to get CI green again for now: https://github.com/pandas-dev/pandas/pull/30069

**Review by alimcmaster1 — APPROVED** [review]
Lgtm

**Comment by WillAyd** [comment]
Thanks @alimcmaster1 and @jbrockmendel for review

**Pull request merged**
