### PR TITLE
BUG: #10565 Series.name lost in rolling_* funcions

### PR DESCRIPTION
**Pull request by chris-b1**
Addresses #10565

### CODE REVIEW

**Comment by shoyer** [comment]
Looks good to me... anyone else?

**Comment by TomAugspurger** [comment]
Sure. I think @sinhrks has been closing a bunch of these losing names issues. Is there a master list somewhere?

**Comment by jreback** [comment]
@chris-b1 thanks!

**Comment by sinhrks** [comment]
@TomAugspurger There is no master tracker for ``Series.name``, but only for ``Index.name`` (#9862). I'll change this to list both ``Series.name`` and ``Index.name``.

**Pull request merged**
