### PR TITLE
Copy on write using weakrefs (part 2)

### PR DESCRIPTION
**Pull request by nickeubank**
Continuation of #11500

### CODE REVIEW

**Comment by nickeubank** [comment]
@shoyer @jreback Ballpark timeline on refactor? Like, >1.5 years? 

If so, I think I'll set this aside.Trying to modify the DataFrame constructor just opened a huge can of worms I think it'd take a long time to work through. 

Till the refactor, any interest in making `SettingWithCopyWarning` into an exception?

**Comment by wesm** [comment]
I'd like to get it done in under a year; in combing through the codebase I've been making lists of things to do. It's a large effort but luckily we have a huge test suite to protect us and help keep the train on the rails. Will keep you posted

**Comment by nickeubank** [comment]
@wesm Great. Then will def set aside. :)

**Comment by jreback** [comment]
@nickeubank thanks for all the effort / commentary tests. I think these will be useful in the refactor.

**Comment by nickeubank** [comment]
@jreback thanks for the guidance! If nothing else, I now know a lot more about how references work in Python! :)

**Comment by TomAugspurger** [comment]
@nickeubank If you want to apply that knowledge for some internet karma, [this](http://stackoverflow.com/questions/34884536/what-is-the-point-of-views-in-pandas-if-it-is-undefined-whether-an-indexing-oper) came up yesterday ;)

**Comment by nickeubank** [comment]
@TomAugspurger on it, thanks Tom.

**Comment by pkch** [comment]
Is there an open issue for this? All issues that refer to this discussion are closed.

**Comment by jreback** [comment]
there are refeneced issues

**Comment by shoyer** [comment]
See https://github.com/pydata/pandas-design/issues/10

**Pull request closed without merging**
