### PR TITLE
DOC: Adds the PDEP vote issue template

### PR DESCRIPTION
**Pull request by noatamir**
This template will facilitate changes currently proposed in #53576. 

Recommend merging it after #53576 is approved. Opened now to facilitate ongoing PDEP voting work.

Also adding PDEP to rst capitalization exception list.

### CODE REVIEW

**Review by Dr-Irv — COMMENTED** [review]
I'm fine with the proposed template, but shouldn't we just do this by creating an issue template at https://github.com/pandas-dev/pandas/tree/main/.github/ISSUE_TEMPLATE rather than documenting the template contents here?

**Comment by noatamir** [comment]
Do we mind that it means anyone could use it, even though they needn't?! 
I thought it might just be cleaner to have issues templates on gh which are user/contributor friendly/relevant. 
But I'm not averse to it.

**Comment by mroeschke** [comment]
I would be in favor of making it an issue template for future convenience. I think you can specify the purpose of each issue template too so that it won't be likely for others to select it.

**Comment by noatamir** [comment]
Awesome - thanks for the input. I'll adjust it then.

**Comment by noatamir** [comment]
First stab at an issue template. Anyone knows a way to preview them?

**Review by Dr-Irv — COMMENTED** [review]
Is there a way to validate that this template is set up correctly?

**Comment by mroeschke** [comment]
The only way I've found to preview is to push the change to your fork an inspect from your repo.

**Comment by Dr-Irv** [comment]
> The only way I've found to preview is to push the change to your fork an inspect from your repo.

Is there a way that we as reviewers can see how the template would be rendered?

@noatamir  Separately, if I go to https://github.com/noatamir/pandas/blob/vote_issue_template/.github/ISSUE_TEMPLATE/pdep_vote.yaml there is a message at the top that says "body[6]: validations is not a permitted attribute."

**Comment by Dr-Irv** [comment]
> > Is there a way that we as reviewers can see how the template would be rendered?
> 
> I don't think there is besides copying the changes to your own fork :/

So if I do that, how can I then see the rendered issue template?  When I go to my forks, I don't have any issue tab (and maybe I have to do something to create it??)

**Comment by Dr-Irv** [comment]
> > > Is there a way that we as reviewers can see how the template would be rendered?
> > 
> > 
> > I don't think there is besides copying the changes to your own fork :/
> 
> So if I do that, how can I then see the rendered issue template? When I go to my forks, I don't have any issue tab (and maybe I have to do something to create it??)

@noatamir  in your fork of the repo, if you turn on "issues" in "Settings", then the new template should show up if we try to create an issue in your repo, which would allow us to preview the template

**Comment by Aloqeely** [comment]
#53576 has been merged, should I attempt to continue the work on this?

**Comment by Dr-Irv** [comment]
> #53576 has been merged, may I attempt to continue the work on this?

Yes, you can take it over.  See comments above (https://github.com/pandas-dev/pandas/pull/54469#issuecomment-1673627307) about how we can look at how the template is rendered.

**Comment by mroeschke** [comment]
Closed by https://github.com/pandas-dev/pandas/pull/58204

**Pull request closed without merging**
