### PR TITLE
fixes qcut failing for labels = True

### LINKED ISSUE #26963: qcut fails with labels=True
The docs say that `qcut()` takes either a list or a boolean as its `labels` argument. The argument is `None` by default. This, which I would have expected to give me the standard set of labels -- like None -- errors:

```python
pd.qcut(range(5), 4, labels=True)

```

This may well be expected behavior, but it does strike me as semantically weird.

### PR DESCRIPTION
**Pull request by Dharni0607**
-  closes #26963

### CODE REVIEW

**Comment by Dharni0607** [comment]
@WillAyd, This is my first pull request, please review and let me know if anything needs to be changed. Thanks :-)

**Comment by WillAyd** [comment]
Hi @Dharni0607 - thanks for the PR. The most critical part of any PR is a test case which ensures that the change is working as intended which we don't have here, so would be a good idea to start with that.

You would want to give the contributing guide a read as it will give you good instructions on how to go about the process

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#contributing-to-pandas

**Comment by Dharni0607** [comment]
Thanks @WillAyd, I will refer it and add required tests.

**Comment by Dharni0607** [comment]
I am not able to figure out why exactly the codecov has decreased. Can someone help, so that I can work on it.

**Comment by jreback** [comment]
the coverage is not relevant it gives weird results.

but more importantly, I think this needs discusion as this gives really weird semantics.

**Review by jreback — CHANGES_REQUESTED** [review]
needs discussion

**Comment by WillAyd** [comment]
Thanks for the PR @Dharni0607 . I think for now though this has gone stale and needs discussion anyway, so going to close to keep our PR queue clean. If interested in going further let's move discussion back to associated issue

Thanks again!

**Pull request closed without merging**
