### PR TITLE
CLN: address FIXME comments

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jreback** [comment]
sure merge on green.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Failure seems unrelated, it's also failing on other PRs

**Comment by jorisvandenbossche** [comment]
Thanks Brock!

**Comment by jorisvandenbossche** [comment]
CI failure -> https://github.com/pandas-dev/pandas/issues/33890

**Pull request merged**
