### PR TITLE
Disable M8 in nanops

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/24752

xref https://github.com/pandas-dev/pandas/commit/fe696e453b9236b226a0656028be43b4706ce1a1#diff-12444145caa7d0c14da51377a05e46d6

### CODE REVIEW

**Comment by TomAugspurger** [comment]
cc @jbrockmendel, this probably breaks your other PR badly. But I'm not sure what's best to do here...

**Comment by TomAugspurger** [comment]
The whole `DataFrame._reduce` implementation seems ripe for a refactor. In principal, we should know *ahead* of time if the op in question is valid for the dtype, no need for all the try / excepts.

And we really shouldn't be applying the op it to `df.values`. It should be done block or column-wise.

**Comment by jorisvandenbossche** [comment]
For historical note: this reverts partly https://github.com/pandas-dev/pandas/pull/24293 (the part of allowing nanmean on M8 data)

**Comment by jorisvandenbossche** [comment]
@TomAugspurger there is some datetime64 check inside `nanmean` that was added in that PR, which could now in principle be removed (but minor detail, shouldn't matter)

**Comment by TomAugspurger** [comment]
Yes, I've left it for now, to make the re-revert easier when we do decide to implement this. But I can do either way.

**Comment by TomAugspurger** [comment]
Oh fun... gotta rework disallow for extension dtypes.

**Comment by jbrockmendel** [comment]
If this helps get 0.24.0 out the door, I say go for it.

**Comment by jbrockmendel** [comment]
> The whole DataFrame._reduce implementation seems ripe for a refactor [...] this should be done block of column-wise

+1

**Comment by jbrockmendel** [comment]
>  this probably breaks your other PR badly

I'll double-check, probably.  Regardless, that PR is stalled until someone (hint: Tom or Joris?) helps resolve a communication problem.

**Pull request merged**
