### PR TITLE
DOC: Fixes LaTeX build error

### PR DESCRIPTION
**Pull request by TomAugspurger**
The PDF doc build was chocking on the `Parameters` section being the first item.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I might be pushing a few more stylistic changes here, so maybe hold on merging. e.g. 

screen shot 2016-03-10 at 7 39 51 am

**Comment by jreback** [comment]
@TomAugspurger at your leisure

**Comment by TomAugspurger** [comment]
One API question, do we want to expose `Resampler` at the top level, similar to `Grouper`? The methods like `Resampler.fillna` weren't being linked to correctly in `api.rst`. Rebuilding now, but it may have been because `panads.Resampler.fillna` isn't a thing. Would need `pandas.tseries.resample.Resampler.fililna`.

**Comment by TomAugspurger** [comment]
Actually, that seems to be an issue just with my build, as the traivs docs have it linked correctly: http://pandas-docs.github.io/pandas-docs-travis/api.html#resampling

**Comment by jreback** [comment]
hmm, btw make sure that in your doc-build env you actually have an *installed* pandas of master/latest (you can simply install from conda), as it doesn't use the current one (as you are in ``pandas/doc``)

**Comment by jreback** [comment]
side note, this is master: https://travis-ci.org/pydata/pandas/jobs/115054959

there is a seg fault right at the end of building the docs (before all of the ``create *`` stuff). Any idea what that is from?

I don't get this locally.

**Comment by jreback** [comment]
@TomAugspurger ok I am pretty much done with doc changes. So pls build at your leisure (or you can wait for the final tag prob sunday eve)

**Comment by TomAugspurger** [comment]
Ok, I'll merge this, and then build later tonight probably. You're last suggestion about having a real install fixed the link issues.

Not sure about the segfault in travis. The error this is fixing does occur towards the end of the build, but is probably unrelated. I'll look into it tonight.

**Comment by jreback** [comment]
gr8

yeah I noticed the segfault as was looking thru logs

i bet it's for the latex building on Travis

**Comment by jreback** [comment]
actually. let's let everything turn green. I'll push the 0.18.0 tag later today. You can build (and if anything else you need to fix, just include it and do a PR later). Then can release on sunday.

**Comment by TomAugspurger** [comment]
just did a quick build. Seems like the API reference is having trouble with the accessors (.str, .dt, .plot). It's also not linking /building those properly in the dev build. http://pandas-docs.github.io/pandas-docs-travis/api.html#string-handling Other than that, things seem ok at a glance.

Gotta run for now, but I'll investigate later.

**Comment by jreback** [comment]
thanks @TomAugspurger lmk.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger about the API docs, yes, that is a known issue: https://github.com/pydata/pandas/issues/12161. I inteded to look at it, but won't be able to do this for 0.18.0. I can do it later in April, but if you can have a look now, great! (but if you cannot directly fix it, it shouldn't hold up the release. Another possibility is building with 1.1.3, which I thought still worked but I am not sure).

**Comment by TomAugspurger** [comment]
Oh, I assumed that section in the wiki with sphinx==1.1.3 was just out of date :)

I’ll try both 1.1.3 and seeing what’s wrong.

**Comment by jorisvandenbossche** [comment]
Well, it should be :-) 
It's possible that it works with 1.2 as well, but I switched to 1.3 for speed (otherwise it wouldn't finish in time on travis). The reason we were still using 1.1.3 is that the API docs were broken on 1.3 for the first minor releases, and only recently was fixed.

We should maybe actually also test sphinx 1.4, which is in beta.

**Comment by jorisvandenbossche** [comment]
The instructions in the docs also need an update: http://pandas-docs.github.io/pandas-docs-travis/contributing.html#requirements (> 1.3.2 also works now: https://github.com/pydata/pandas/issues/10316)

**Pull request closed without merging**
