### PR TITLE
CLN: Remove leftover partial-result code from apply

### PR DESCRIPTION
**Pull request by alonme**
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jreback** [comment]
hmm yeah i don't really recall while this was needed

any perf differences?

**Comment by alonme** [comment]
@jreback I added the partial results in order to solve https://github.com/pandas-dev/pandas/issues/33879 ( PR https://github.com/pandas-dev/pandas/pull/34183)
But it seems that the whole use of `libreduction` was removed, and there is no need.

All the code i removed isn't actually used, so there shouldn't be any perf difference

Do you happen to know why `libreduction` isn't used anymore? is there a slowdown after its removal?

**Comment by jreback** [comment]
libreduction just added complexity

**Comment by alonme** [comment]
ok.
Anything left for this to be merged?

**Comment by jreback** [comment]
yeah this is nice @alonme thanks

**Pull request merged**
