### PR TITLE
DOC: Fixing even more warnings (not many left)

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] xref #24173
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Let's wait for the logs, tested locally only part of them, but this should fix most of the remaining warnings.

CC: @jorisvandenbossche

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Almost! ;)

There are two left (from the ones we could solve):

/home/travis/build/pandas-dev/pandas/doc/source/reference/api/pandas.Index.asi8.rst: WARNING: document isn't included in any toctree
/home/travis/build/pandas-dev/pandas/doc/source/reference/api/pandas.api.extensions.ExtensionDtype.na_value.rst: WARNING: document isn't included in any toctree

About the ExtensionDtype.na_value: It doesn't seem generated in the actual class docstring page (http://dev.pandas.io/reference/api/pandas.api.extensions.ExtensionDtype.html#pandas.api.extensions.ExtensionDtype), so I think we can remove the comment at the bottom of https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/source/reference/index.rst to avoid the warning

**Comment by datapythonista** [comment]
Didn't see where `Index.asi8` is implemented, just saw the methods for subclasses of it. Let the trickier ones for the end, I'm having a look at the contributor errors, I'll open a PR to add the error returned by git to the warning.

Feel free to look at those if you want, and also:
```
/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/IPython/core/interactiveshell.py:925: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
```

I think we should be able to start failing on warnings today, before more are introduced. :)

**Comment by jorisvandenbossche** [comment]
I made the change locally, will push here

**Comment by datapythonista** [comment]
I just saw that the virtualenv error doesn't happen in azure, there are just 3 warnings left there according to sphinx. Better don't bother then, it's in azure where we need to add the validation.

**Comment by jorisvandenbossche** [comment]
Do you already know how you would do the validation? Can we capture and parse the log build in azure?

**Comment by datapythonista** [comment]
sphinx has parameters for that:
```
  -W                turn warnings into errors
  --keep-going      With -W, Keep going when getting warnings
```

**Comment by jorisvandenbossche** [comment]
I think we had some discussion about that before, but some problems with that: a) it doesn't handle the ipython directive errors (I think?) and b) it doesn't allow us to have some exceptions (eg to ignore our contributor directive that needs the full git history)

**Comment by jorisvandenbossche** [comment]
Refeshing my memory: we had a discussion about this in https://github.com/pandas-dev/pandas/pull/22743. You added a `--warnings-are-errors` to our doc build script to basically have this `-W --keep-going` (https://github.com/pandas-dev/pandas/pull/24523). 
Ah, and https://github.com/pandas-dev/pandas/issues/24661 is the proper issue to further discuss this.

**Comment by jorisvandenbossche** [comment]
Hmm, my commit didn't work, reverting.
I actually read the warning wrong: it says those two attributes are not included in any toctree, while they actually are (that's what I first tried to remove). Not sure then ..

**Comment by jorisvandenbossche** [comment]
Let's already merge those.

**Pull request merged**
