### PR TITLE
travis: enable bionic & multi-cpu testing

### PR DESCRIPTION
**Pull request by xnox**
- [x] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
what does this actually do? (the arch directive)

**Comment by xnox** [comment]
> what does this actually do? (the arch directive)

spins up Ubuntu LXD containers on arm64, s390x (big endian, 64bit mainframe), ppc64el (POWER8 6bit little endian), amd64 metal and lets one build & run code on those architectures, thanks to hardware that Travis got from partners.

**Comment by xnox** [comment]
@jreback  you can see from https://travis-ci.org/pandas-dev/pandas/builds/654862395?utm_source=github_status&utm_medium=notification that all tests on non-x86 are currently failing.

Similarly this is the reason we can't update pandas in Ubuntu 20.04 LTS for the release in april at the moment - https://launchpad.net/ubuntu/+source/pandas/0.25.3+dfsg-5

**Review by jreback — CHANGES_REQUESTED** [review]
sympathetic with the request. however we have 0 support for non-standard arches. that said, if it can be made to work great.

I would start really small though, enable 1 thing (on an failing ok build), then would take patches to fix.

Almost everything would need to be build from source if conda is not available (IIRC this is somewhat supported for the arm arches but nothing else)

**Comment by jreback** [comment]
@xnox we also don't have the capacity to actually have multi arch on *every* build.

**Comment by WillAyd** [comment]
@xnox is there also infrastructure for building wheels on these platforms?

**Comment by MomIsBestFriend** [comment]
@WillAyd I had a very good experience with https://github.com/joerick/cibuildwheel

**Comment by jreback** [comment]
we would *only* need a single build on each arch, need a PR more like: https://github.com/pandas-dev/pandas/pull/30641

**Pull request closed without merging**
