### PR TITLE
STY: avoid backslash

### PR DESCRIPTION
**Pull request by jbrockmendel**
Related: #11954.

This gets most of the non-`textwrap.dedent` cases.

### CODE REVIEW

**Comment by datapythonista** [comment]
Nice change, but I think we expect `and`, `or`... after the line break, as we ignore `W503` in the linting, and not `W504`. I don't have a preference, but I guess that's how it's in the rest of the code based on the linting setup.

**Comment by jbrockmendel** [comment]
> as we ignore W503 in the linting, and not W504

OK, I was wondering why pep8speaks was complaining about those.  I'm used to seeing the warnings in the other direction.  Will update.

**Comment by datapythonista** [comment]
Just check the linting settings, you may want to look in more detail before changing.

**Comment by jreback** [comment]
this looks fine. Do we have a lint rule to flag the line-continuation? alt do it in lint.sh (this can be a followup).

@datapythonista you ok here? merge away.

**Comment by datapythonista** [comment]
I was checking again, and looks like indded our standard is to have the operator after the line break and not before. For example: https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L243

So, I think it makes sense to make the changes to this PR, unless we want to change the convention at this point, and change the others. I personally don't have a preference, and I don't know what's supposed to be the way to avoid both `W503` and `W504`. But I think it makes sense to ignore just one of them, and be consistent in what we do.

Those are the cases where we're ignoring `W503` right now:
```
./doc/make.py:103:30: W503 line break before binary operator
./doc/make.py:104:30: W503 line break before binary operator
./pandas/core/series.py:243:19: W503 line break before binary operator
./pandas/core/frame.py:420:15: W503 line break before binary operator
./pandas/core/generic.py:1257:17: W503 line break before binary operator
./pandas/core/generic.py:1269:17: W503 line break before binary operator
./pandas/core/strings.py:2115:32: W503 line break before binary operator
./pandas/core/strings.py:2119:33: W503 line break before binary operator
./pandas/core/arrays/integer.py:243:17: W503 line break before binary operator
./pandas/core/indexes/multi.py:837:21: W503 line break before binary operator
./pandas/core/indexes/base.py:3128:25: W503 line break before binary operator
./pandas/core/reshape/merge.py:972:21: W503 line break before binary operator
./pandas/core/reshape/merge.py:975:21: W503 line break before binary operator
./pandas/core/groupby/grouper.py:502:17: W503 line break before binary operator
./pandas/core/internals/blocks.py:2112:13: W503 line break before binary operator
./pandas/core/internals/blocks.py:2164:13: W503 line break before binary operator
./pandas/tests/indexes/datetimes/test_date_range.py:784:39: W503 line break before binary operator
./pandas/tests/extension/test_integer.py:31:13: W503 line break before binary operator
./pandas/tests/extension/test_integer.py:102:21: W503 line break before binary operator
./pandas/tests/extension/test_integer.py:103:21: W503 line break before binary operator
./pandas/tests/tseries/offsets/conftest.py:15:25: W503 line break before binary operator
./pandas/io/parsers.py:1717:12: W503 line break before binary operator
./pandas/io/sas/sas7bdat.py:307:17: W503 line break before binary operator
./pandas/io/formats/csvs.py:146:13: W503 line break before binary operator
./scripts/validate_docstrings.py:114:17: W503 line break before binary operator
./scripts/validate_docstrings.py:225:17: W503 line break before binary operator
./scripts/download_wheels.py:28:14: W503 line break before binary operator
```

**Comment by jreback** [comment]
@datapythonista hmm, that is not convention. though its possible we have both flavors of this as not checking before.

**Comment by WillAyd** [comment]
I didn't think this was our convention as much as what's suggested (though not enforced) by PEP8

https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

**Comment by datapythonista** [comment]
Sorry, I just saw that `flake8` does not validate `W504` (the operator before the line break). I was assuming it didn't happen anywhere in the code before this PR, that's why I suggested to change it here.

I think it would be a good practice to follow the PEP8 recommendation (@WillAyd link) at some point, but that's surely for a different PR (and we'll have to wait for a newer version of `flake8` that validates it, or use something else).

Happy to merge this, but I think it makes sense to wait for #23101, or `pep8speaks` may report invalid errors in new PRs .

**Comment by datapythonista** [comment]
Thanks @jbrockmendel, #23101 is merged, so the linting should complain about the binary operations now.

**Pull request merged**
