### PR TITLE
ENH: str extract with default value

### LINKED ISSUE #38001: ENH: add default value to str.extract
#### Is your feature request related to a problem?

In some cases we can set a default value for non matches of `str.extract` with `Series/Frame.fillna`.

But there are cases when the data prior to applying `str.extract` already has NaN values. So running fillna on the results would fill both, and there we cannot distinguish between what the actual NaN values were and what the NaN values are as a result of str.extract. 

#### Describe the solution you'd like

Set a default value which has to be a string, to indicate the non matches of the regex pattern.

#### API breaking implications

None I think

```python
from pandas import DataFrame
import numpy as np

df = DataFrame({'A': ['a84', 'abcd', '99string', np.nan]})
result = df['A'].str.extract(r'(\d+)', expand=False, default='missing')
print(result)

0         84
1    missing
2         99
3        NaN    <-- the NaN which was already present is not filled.
Name: A, dtype: object
```

### PR DESCRIPTION
**Pull request by erfannariman**
- [x] closes #38001 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by erfannariman** [comment]
@jreback any chance we can decide what we want to do with this PR? If you think this change is not needed, It's fine for me to close it.

**Comment by jreback** [comment]
i'd really like a real-world usecase of this. The work-aroudn is actually very simpler (even simpler that what you posted), so not convinced this all that useful. that said prob doesnt' hurt.

@erfannariman yeah i guess this is ok, can't hurt. rename default -> fill_value (as that is the term we use else where) and move the note to 1.3.

**Comment by datapythonista** [comment]
@erfannariman closing this, if you think of a real case for this, happy to reopen. But agree with Jeff that even if this makes sense, adding more complexity to pandas for a reasonable use case that no user may ever face, it's not worth

**Comment by simonjayhawkins** [comment]
I'll reopen this, but I think this enhancement should wait until after str.extract is dispatched to array and the _wrap_result and str_map methods are re-used. #41372

**Comment by simonjayhawkins** [comment]
@erfannariman can you resolve conflicts and can take another look

**Comment by simonjayhawkins** [comment]
@erfannariman closing as stale. ping if you want to pick this up again.

**Pull request closed without merging**
