### PR TITLE
Dispatch IntervalIndex.argsort to IntervalArray

### PR DESCRIPTION
**Pull request by jbrockmendel**
cc @jschendel thoughts on if we can do better in the non-ascending/"quicksort" case?

### CODE REVIEW

**Comment by jreback** [comment]
any timings on the various cases?

**Comment by jreback** [comment]
lgtm. perf timings?

**Comment by jbrockmendel** [comment]
havent done any timings, am hoping to get guidance from @jschendel on the remaining cases

**Comment by jbrockmendel** [comment]
Closing to clear the queue, will revisit, still hoping @jschendel can weigh in on how best to handle the remaining cases.

**Pull request closed without merging**
