### PR TITLE
Convert Sparse ASVs

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by gfyoung** [comment]
For my personal edification, why are we filtering these?

**Comment by TomAugspurger** [comment]
Keeps them from polluting the output of ASV runs.

Alternatively, we just remove all the SparseDataFrame / SparseSeries asvs,
or convert them to using DataFrame[sparse] / Series[Sparse]?

**Comment by jreback** [comment]
> Alternatively, we just remove all the SparseDataFrame / SparseSeries asvs,
or convert them to using DataFrame[sparse] / Series[Sparse]?

should do this, can open an issue?

is this mergable (or failing for some other reason)?

**Comment by TomAugspurger** [comment]
Updated to remove the filter and change the SparseSeries / SparseFrame tests to use regular dataframe / series.

**Comment by TomAugspurger** [comment]
FYI, all green if anyone has a chance to take a quick look.

**Comment by jreback** [comment]
+1 on this, though means we lose asv's on previous versions for sparse (which I think is ok). 

cc @topper-123 @qwhelan

**Review by topper-123 — APPROVED** [review]

**Comment by topper-123** [comment]
+1 for me. Logical step, now that sparse(DataFrame|Series) is deprecated.

**Review by qwhelan — APPROVED** [review]

**Comment by qwhelan** [comment]
+1, if loss of old benchmark comparisons is a concern it would probably make sense to set up a regular backfill job on the speed site. `asv` could make this quite a bit easier, but just covering every major point release would go pretty far. Happy to work on this starting in about a week if there's interest.

**Comment by jreback** [comment]
thanks @TomAugspurger

**Pull request merged**
