### PR TITLE
CI: Upgrade "actions/(checkout|cache)" to version 2

### PR DESCRIPTION
**Pull request by ShaharNaveh**
According to the change log of both "checkout" and "cache" this should increase performance.

---

Fell free to close this PR if this was already discussed, I haven't saw any discussion about this topic.

### CODE REVIEW

**Review by fangchenli — CHANGES_REQUESTED** [review]
To get all the tags, you need
```yml
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
```

**Comment by datapythonista** [comment]
@ShaharNaveh do you have time to have a look at the comment and leave the CI green?

**Comment by ShaharNaveh** [comment]
> @ShaharNaveh do you have time to have a look at the comment and leave the CI green?

OFC:)

**Review by fangchenli — APPROVED** [review]

**Comment by datapythonista** [comment]
Checked quickly, and this does seem to speed up the checkout a bit, from around 28 second to around 22 (not sure if very significant, but nice to use the latest version of the action regardless).

What I see is that if we don't fetch all tags and branches the checkout is almost immediate (like 2 seconds). I think we need them for the release notes, but I'm not aware of anything else that should require them. @ShaharNaveh would you mind having a look and see if the `fetch-depth` is required for all builds. I don't think anything other than the docs build should need them.

Also, if you want to have a better look at timings, including the ones of the cache action (I didn't check those), that would be great.

**Comment by ShaharNaveh** [comment]
> Checked quickly, and this does seem to speed up the checkout a bit, from around 28 second to around 22 (not sure if very significant, but nice to use the latest version of the action regardless).
> 
> What I see is that if we don't fetch all tags and branches the checkout is almost immediate (like 2 seconds). I think we need them for the release notes, but I'm not aware of anything else that should require them. @ShaharNaveh would you mind having a look and see if the `fetch-depth` is required for all builds. I don't think anything other than the docs build should need them.

@datapythonista The way I decided where each `fetch-depth: 0` will be, was to look at the failed tests in https://github.com/pandas-dev/pandas/pull/41336/commits/e35cc1be12814e59b5ce67e2764ce7e1bddb0923 and I added the `fetch-depth: 0` wherever there was a failing test.

> Also, if you want to have a better look at timings, including the ones of the cache action (I didn't check those), that would be great.

I did see an improvement with the cache, but the difference is `1s`.

**Review by datapythonista — APPROVED** [review]
Thanks for the info @ShaharNaveh. Sounds good. I'd like to understand why we need tags or branches for so many builds, but that's unrelated to this PR.

Thanks for working on this!

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @ShaharNaveh

**Comment by simonjayhawkins** [comment]
We've had several failures in the last couple of days, could there be a compatibility issue with conda-incubator/setup-miniconda@v2 or maybe this was failing before and I didn't notice.

**Comment by datapythonista** [comment]
> We've had several failures in the last couple of days, could there be a compatibility issue with conda-incubator/setup-miniconda@v2 or maybe this was failing before and I didn't notice.

I saw a connection error on conda, are those the failures you are referring to? We can revert, but probably better to try to understand the problem better first.

**Pull request merged**
