### PR TITLE
54628 fix find stack level memory leak

### LINKED ISSUE #54628: BUG: memory leak in `find_stack_level`
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
from pandas.util._exceptions import find_stack_level
find_stack_level()
```

### Issue Description

The source for `find_stack_level` does not delete the frame reference

https://github.com/pandas-dev/pandas/blob/e92ea577ccce3ae8cc7da2baba44d72854f4947f/pandas/util/_exceptions.py#L33-L54

From the `inspect` docs:

> Note
> 
> Keeping references to frame objects, as found in the first element of the frame records these functions return, can cause your program to create reference cycles. Once a reference cycle has been created, the lifespan of all objects which can be accessed from the objects which form the cycle can become much longer even if Python’s optional cycle detector is enabled. If such cycles must be created, it is important to ensure they are explicitly broken to avoid the delayed destruction of objects and increased memory consumption which occurs.
> 
> Though the cycle detector will catch these, destruction of the frames (and local variables) can be made deterministic by removing the cycle in a finally clause. This is also important if the cycle detector was disabled when Python was compiled or using gc.disable(). For example:
> 
> ```py
> def handle_stackframe_without_leak():
>     frame = inspect.currentframe()
>     try:
>         # do something with the frame
>     finally:
>         del frame
> ```
> 
> If you want to keep the frame around (for example to print a traceback later), you can also break reference cycles by using the frame.clear() method.

### Expected Behavior

```py
def find_stack_level() -> int:
    """
    Find the first place in the stack that is not inside pandas
    (tests notwithstanding).
    """

    import pandas as pd

    pkg_dir = os.path.dirname(pd.__file__)
    test_dir = os.path.join(pkg_dir, "tests")
    # https://stackoverflow.com/questions/17407119/python-inspect-stack-is-slow
    frame = inspect.currentframe()
    try:
        n = 0
        while frame:
            fname = inspect.getfile(frame)
            if fname.startswith(pkg_dir) and not fname.startswith(test_dir):
                frame = frame.f_back
                n += 1
            else:
                break
    finally:
        del frame
    return n
```

- I would also replace the `while` loop with `for frame in iter(lambda: frame.f_back, None)`
  - [example](https://gist.github.com/lmmx/b9d3b4881f9b7fcc8498efe72883c0b8)

### Installed Versions

N/A

### PR DESCRIPTION
**Pull request by mroeschke**
- [ ] closes #54628 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @lmmx for the initial find

**Comment by jorisvandenbossche** [comment]
Should we backport this for 2.2.x? (it's a memory leak, although presumably only a small one)

**Comment by mroeschke** [comment]
Sure no harm in doing so

**Comment by mroeschke** [comment]
@meeseeksdev backport 2.2.x

**Comment by mroeschke** [comment]
@meeseeksmachine backport 2.2.x

**Pull request merged**
