### PR TITLE
BUG: avoid unnecessary casting in CategoricalIndex.reindex

### PR DESCRIPTION
**Pull request by jbrockmendel**
Doesn't appear to be anything user-facing.  The only unequivocally wrong bit is on L420 where the current condition is always truthy.

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase. what's the bug?

**Comment by jbrockmendel** [comment]
> what's the bug?

It's not user-facing, just clearly-unintended code.  On L420 `if not isinstance(cats, CategoricalIndex) or (cats == -1).any():` always holds bc `cats` is an ndarray.

**Comment by jbrockmendel** [comment]
rebased + greenish

**Comment by jreback** [comment]
looks fine can you rebase

**Comment by jbrockmendel** [comment]
rebased + green

**Comment by jbrockmendel** [comment]
booyah.  bunch of MultiIndex PRs that are blockers for... more MultiIndex PRs.  Nothing urgent.

**Pull request merged**
