### PR TITLE
DOC: update tutorial docs

### PR DESCRIPTION
**Pull request by fabiangabel**
**N**itrogen Di-**O**xide

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Do you have any others? If you, you can put them all in the same pr , no need to open multiple

**Comment by eltenedor** [comment]
> Do you have any others? If you, you can put them all in the same pr , no need to open multiple

@MarcoGorelli Thanks for the info. For the moment that's all the typos I discovered so far. But I'm planning to work through the tutorial the next days. I'll  just kep pushing my suggestions to this PR.

**Comment by jreback** [comment]
@eltenedor pls merge master and make a non-draft and can merge

**Comment by eltenedor** [comment]
> @eltenedor pls merge master and make a non-draft and can merge

of course.

**Comment by jreback** [comment]
thanks @eltenedor

**Pull request merged**
