### PR TITLE
[WIP] Debug R doc build failure

### PR DESCRIPTION
**Pull request by TomAugspurger**
#20648

### CODE REVIEW

**Comment by TomAugspurger** [comment]
The packages built by anaconda include a compiler flag (`-fPIC`) that should make this error impossible. Seeing if (temporarily) excluding conda-forge packages fixes things.

**Comment by TomAugspurger** [comment]
Hmm, still trying to get  a local reproducer, but https://travis-ci.org/pandas-dev/pandas/jobs/371582150#L2705 managed to import rpy2, I guess since it was imported early enough :/

https://stackoverflow.com/questions/19268293/matlab-error-cannot-open-with-static-tls/19468365#19468365

It sounds like either Travis' glibc is the bottleneck here. We won't be able to do much to work around it unfortunately.

**Comment by jorisvandenbossche** [comment]
Thanks for looking into this. 
Temporary / definite workaround would be just remove that doc section, or to convert it to static code-blocks.

**Comment by TomAugspurger** [comment]
Yeah. I'm able to build things locally, so I'm not too worried about it delaying the relase.

**Comment by jreback** [comment]
closing as stale. if you'd like to continue pls ping.

**Pull request closed without merging**
