### PR TITLE
Backport PR #24916 on branch 0.24.x (BUG-24212 fix regression in #24897)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #24916: BUG-24212 fix regression in #24897

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback I reverted this *on the 0.24.x branch*, see my comments there (https://github.com/pandas-dev/pandas/pull/24916#pullrequestreview-196792659), I feel this has a bit a too big possibility on side effects to include it in a bug fix release (it's also not a critical bug fix anyway).

**Comment by jreback** [comment]
please speak up much sooner then

i would rather not have this kind of back and forth

**Comment by jorisvandenbossche** [comment]
@jreback I *did* speak up before you merged this: https://github.com/pandas-dev/pandas/pull/24916#issuecomment-457837974 and https://github.com/pandas-dev/pandas/pull/24916#pullrequestreview-196792659

**Comment by jreback** [comment]
no you didn’t

**Comment by jreback** [comment]
@jorisvandenbossche I am not sure why you didn't change the what's new in 0.25.0 as well here. This is likely to cause merging issues to 0.24.x. can you update that.

**Comment by TomAugspurger** [comment]
What looks wrong about the 0.25.0.rst on the 0.24.x branch? I don't see any issues. As long as it has the orphan directive and isn't in the whatsnew/index.rst toctree, thing should be fine.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v0.24.1.rst

has the change, but should be in 0.25.0

**Comment by TomAugspurger** [comment]
👍 https://github.com/pandas-dev/pandas/pull/24998

**Pull request merged**
