### PR TITLE
CLN use default_index more

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
why?  no strong opinion, just curious

**Comment by mroeschke** [comment]
Would `default_index` help prime optional Index work as well?

The only one here where it changes the type is in merge not on index. Currently, pandas returns an Int64Index - would it be better to return RangeIndex?

+1 to generally return RangeIndex when possible

**Comment by MarcoGorelli** [comment]
> Would default_index help prime optional Index work as well?

yup (that's how I came across this)

**Comment by mroeschke** [comment]
Could use a whatsnew (perf maybe) regarding the merge `Int64Index` -> `RangeIndex` change otherwise LGTM

**Review by mroeschke — COMMENTED** [review]
Looks okay to me. Could you merge in main once more?

**Review by mroeschke — APPROVED** [review]
LGTM cc @jbrockmendel still no strong objection?

**Comment by jbrockmendel** [comment]
A-OK

**Comment by mroeschke** [comment]
Thanks @MarcoGorelli

**Pull request merged**
