### PR TITLE
STYLE: inconsistent namespace (io, reshape)

### PR DESCRIPTION
**Pull request by AA-Turner**
- [x] xref #39992
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

### CODE REVIEW

**Comment by AA-Turner** [comment]
@MarcoGorelli this is `io` and `reshape`. First time contributing to pandas so let me know if there are any style things I should change - I read over the dev docs and think I've got everything.

Thanks!

**Comment by jreback** [comment]
can you merge master

**Comment by AA-Turner** [comment]
Rebased & pushed

**Comment by MarcoGorelli** [comment]
Hi @AA-Turner - `reshape` is already covered by #40058, could you revert those changes and just keep this to `io` please?

**Comment by AA-Turner** [comment]
Thanks Marco, mutst've missed that when I was looking for what had been done already. Will do as you ask

**Comment by AA-Turner** [comment]
Done

**Comment by MarcoGorelli** [comment]
Thanks @AA-Turner !

**Comment by rhshadrach** [comment]
Looks like this PR had some failure - seeing them on master as well now. Are these related?

**Comment by AA-Turner** [comment]
Hi Richard - will look into this. Given this just changes namespace usage, may be that pandas/__init__.py exposes names or something that aren't in submodules. 

Given a lot of tests/CI checks failed - is there a known subset that are ingored? I'll look for `io` related tests in the logs first, though.

**Comment by AA-Turner** [comment]
Found three failures I think are related - all in `test_stata.py`. The changes moved to using `io.stata.blah` (stripping the leading `pd.`), which shadows the io builtin, and I didn't catch when looking over.

PR to fix is at #40094

Adam

**Pull request merged**
