### PR TITLE
CI: Sync web and dev docs automatically with prod server

### LINKED ISSUE #28528: WEB: Deployment of the new website in production
Until now, we've been deploying the website manually afaik, from the separate repo.

What I would do with the new website is next (open to discussion):
- Have a job running to automatically deploy the website from master, possible frequencies:
  - Every commit
  - Daily
  - Weekly
- Build the website normally, as we do in https://github.com/pandas-dev/pandas/blob/master/azure-pipelines.yml#L122
- Deploy it to the server with rsync, something like: `rsync avz --delete  --exclude="docs" ~/web/build pandas_ci@pandas.io:/var/www/pandas`

For the docs, I see two main options:
- Inside `docs/` have a directory per language (currently English), and inside them one per version (with a symlink `stable/ -> 0.25.1`), so the urls would be something like pandas.io/docs/en/stable or pandas.io/docs/en/0.24.0 (and redirect pandas.io/docs/ to pandas.io/docs/en/stable)
- Copy the docs directly in pandas.io/docs/ and keep the old version in directories there pandas.io/docs/0.24.0/

In both cases, we can deploy the master docs into a `dev/` directory together with the versions.

I think the first option is a bit simpler to maintain, and the second makes the url a bit simpler. I don't have a strong preference.

I think this is very simple, but **requires that all pages that we don't want to version are in the web, and not in the docs**. So, if the roadmap is in the docs, the version we will have will be the stable version (0.25.1) and not master.

@jorisvandenbossche you proposed to have the next pages in the docs:
- Roadmap
- Ecosystem
- Contributing to pandas

Do you have a proposal for how to serve or deploy these? Or are you ok having the stable version of those? I thought about it, and I couldn't find any option I liked to keep those in the docs, that's why I'm proposing to move them to the website.

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #28528

This forgets about the OVH server, and after every merge to master will synchronize the repo web and docs in the production server.

**Note** that this will delete any file in the server that is not known, except the cheat sheets, and all the docs versions in `pandas-doc`. I don't think anything else should be kept, but if there is anything else that we upload manually, please let me know. I made a backup in the server, so if we delete anything by accident with this, it can be easily restored.

CC: @TomAugspurger @jorisvandenbossche

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Looks good to me. 

But not very familiar with the server, to know whether we uploaded things manually in the past.

**Comment by TomAugspurger** [comment]
> delete any file in the server that is not known

Starting in what directory? `/usr/share/nginx/` or `/usr/share/nginx/pandas`?

**Comment by TomAugspurger** [comment]
I suppose the diff answers my question: `nginx/pandas`. So this looks good.

Merge when you're ready.

**Comment by datapythonista** [comment]
Yes, `nginx/pandas`. Thanks for the reviews.

**Pull request merged**
