### PR TITLE
CLN: Enforce deprecation of pinning name in SeriesGroupBy.agg

### PR DESCRIPTION
**Pull request by rhshadrach**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Ref: #51703

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Looks great, thanks @rhshadrach

**Comment by rhshadrach** [comment]
@datapythonista - if you tag enforcements of deprecations as deprecations, our CI will add it to the list of deprecations to enforce in pandas 4.0. I think most are sticking to "Clean" for the enforcement.

**Comment by datapythonista** [comment]
Ah, thanks for the heads up, I forgot the bot.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @rhshadrach

**Pull request merged**
