### PR TITLE
DOC: Add explanation how to convert arrow table to pandas df

### LINKED ISSUE #51760: Provide a way to convert Arrow tables to Arrow-backed dataframes
As far as I could see, there is no easy way given a PyArrow table, to get a DataFrame with pyarrow types.

I'd expect that those idioms work:

```python
import numpy
import pyarrow
import pandas

arrow_u8 = pyarrow.array([1, 2, 3], type=pyarrow.uint8())
arrow_f64 = pyarrow.array([1., 2., 3.], type=pyarrow.float64())
table = pyarrow.table([arrow_u8, arrow_f64], names=['u8', 'f64'])

# Using the PyArrow `to_pandas` method will use NumPy backed data
df = table.to_pandas()

# Using the constructor with a PyArrow table raises: ValueError: DataFrame constructor not properly called!
df = pandas.DataFrame(table)

# This is not implemented (the method doesn't exist)
df = pandas.DataFrame.from_arrow(table)

# Creating a dataframe column by column naively from the arrow array will use NumPy dtypes
df = pandas.DataFrame({'u8': arrow_u8,
                       'f64': arrow_f64})
```

I think the easier way to make the transition is with something like this:

```python
df =  pandas.DataFrame({name: pandas.Series(array,
                                            dtype=pandas.ArrowDtype(array.type))
                        for array, name
                        in zip(table.columns, table.column_names)})
```

@pandas-dev/pandas-core Given that Arrow dtypes is one of the highlights of pandas 2.0, shouldn't we provide at least one easy way to convert before the release?

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #51760 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
Looks good, but as discussed in #51769, we can implement `DataFrame.from_arrow`, which is probably easier to expect and remember by users. Maybe let's leave this open for now, in case there is an issue with that, but I guess we can  implement this paragraph and example with the `from_arrow` idiom in that other PR.

**Comment by phofl** [comment]
Not totally sure, maybe it's better for now to expected users to be explicit when converting? I think we can expected users that have arrow tables to be aware of the to_pandas method?

**Review by mroeschke — APPROVED** [review]
Since #51769 seems to have mixed feelings currently I'd be okay with adding this note in the meantime

**Comment by datapythonista** [comment]
Thanks @phofl, this is useful

**Pull request merged**
