### PR TITLE
TST: coverage for skipped tests in io/formats/test_to_html.py

### PR DESCRIPTION
**Pull request by simonjayhawkins**
- [ N/A] precursor to #22786
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ N/A] whatsnew entry

There are currently 3 skipped tests in `io/formats/test_to_html.py`; `test_to_html_truncate`, `test_to_html_truncate_multi_index` and `test_to_html_truncate_multi_index_sparse_off`

Only `test_to_html_truncate` is required to provide regression coverage for #22786

However, it is probably appropriate for any changes to `test_to_html_truncate` to also be applied to the other two skipped tests within the scope of this PR.

cc @jreback

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
`test_to_html_truncate_multi_index_sparse_off` should fail! see #22887

**Comment by simonjayhawkins** [comment]
changing:

https://github.com/pandas-dev/pandas/blob/e45a6c14fc969c31c46ae890e72883ffe6658b4e/pandas/io/formats/html.py#L235

to:

```python
sentinel = False
```
would pass all tests.

**Comment by jreback** [comment]
can you rebase / tests are failng

**Comment by jreback** [comment]
thanks!

**Comment by simonjayhawkins** [comment]
xref #11060

**Pull request merged**
