### PR TITLE
Backport PR: BUG: Array.__setitem__ failing with nullable boolean mask (#31484)

### PR DESCRIPTION
**Pull request by charlesdong1991**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
looks good

**Comment by charlesdong1991** [comment]
thanks for the tip! appreciate a lot! @WillAyd

**Comment by charlesdong1991** [comment]
emm, error does not seem to be related to this pr, #30588

**Comment by jreback** [comment]
thanks @charlesdong1991

**Pull request merged**
