### PR TITLE
TST: re-enable gbq tests

### PR DESCRIPTION
**Pull request by tswast**
Fix clean-up steps to use the google.cloud.bigquery client
library directly, since some of the _Dataset and _Table
logic was removed from pandas-gbq.

Follow-up to #23281

- [x] tests added / passed

```
$ pytest pandas/tests/io/test_gbq.py
====== test session starts ======
platform darwin -- Python 3.6.4, pytest-3.6.2, py-1.5.3, pluggy-0.6.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/swast/src/pandas/pandas/.hypothesis/examples')
rootdir: /Users/swast/src/pandas/pandas, inifile: setup.cfg
plugins: xdist-1.22.2, forked-0.2, cov-2.5.1, hypothesis-3.70.3
collected 2 items

pandas/tests/io/test_gbq.py ..           [100%]

====== slowest 10 test durations ======
12.55s call     pandas/tests/io/test_gbq.py::TestToGBQIntegrationWithServiceAccountKeyPath::test_roundtrip
1.30s setup    pandas/tests/io/test_gbq.py::TestToGBQIntegrationWithServiceAccountKeyPath::test_roundtrip
0.66s teardown pandas/tests/io/test_gbq.py::TestToGBQIntegrationWithServiceAccountKeyPath::test_roundtrip
0.18s call     pandas/tests/io/test_gbq.py::test_read_gbq_without_dialect_warns_future_change
0.00s setup    pandas/tests/io/test_gbq.py::test_read_gbq_without_dialect_warns_future_change
0.00s teardown pandas/tests/io/test_gbq.py::test_read_gbq_without_dialect_warns_future_change
====== 2 passed in 15.00 seconds ======
```

- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jreback** [comment]
is the min version for pandas-gbq good in the install?

**Comment by tswast** [comment]
I think the min version should be 0.6.0. Should I set that in the impororskip? I don't see versions for pandas-gbq anywhere when I search for it.

The last time we changed the arguments to read_gbq was https://github.com/pydata/pandas-gbq/pull/196, which shipped in 0.6.0 / 2018-08-15 and I updated pandas in https://github.com/pandas-dev/pandas/pull/22557 for that change.

**Comment by jreback** [comment]
this is fine, we are only testing on a single build I think. We should move this to the 3.6 build. If you want to update the min version its ok by me (or not is fine too), I think mostly people just install the latest.

**Comment by jreback** [comment]
thanks @tswast

**Pull request merged**
