### PR TITLE
[WIP] Add a test using intNA

### PR DESCRIPTION
**Pull request by rotuna**
Added an extra  test in algorithms.py in asv_benchmarks.

This test does same benchmark but uses intNA instead of np.nan

Based on #24351

### CODE REVIEW

**Comment by jreback** [comment]
there are some linting errors in the asvs

**Comment by WillAyd** [comment]
@rotuna can you merge master here?

**Comment by WillAyd** [comment]
Can you merge master?

**Comment by jreback** [comment]
closing as stale

**Pull request closed without merging**
