### PR TITLE
TST: insert 'match' to bare pytest raises in pandas/tests/tools/test_…

### PR DESCRIPTION
**Pull request by krajatcl**
- [ ] ref https://github.com/pandas-dev/pandas/issues/30999
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by krajatcl** [comment]
Hi,
can anyone add this label hacktoberfest-accepted

**Comment by jreback** [comment]
thanks @krajatcl

**Comment by hongshaoyang** [comment]
this PR is causing datetime tests to fail

https://dev.azure.com/pandas-dev/pandas/_build?definitionId=1&_a=summary

**Comment by jreback** [comment]
ok can u revert the commit in a new PR?

**Comment by hongshaoyang** [comment]
Done: #37048

**Pull request merged**
