### PR TITLE
Make subdirs in tests/io/data

### PR DESCRIPTION
**Pull request by alimcmaster1**
- [x] closes https://github.com/pandas-dev/pandas/issues/29439
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

A few of the "network" tests are failing locally as they require the data on master:
e.g
```
  @tm.network
    def test_spam_url(self):
        url = (
            "https://raw.githubusercontent.com/pandas-dev/pandas/master/"
            "pandas/tests/io/data/html/spam.html"
        )
        df1 = self.read_html(url, ".*Water.*")
        df2 = self.read_html(url, "Unit")

        assert_framelist_equal(df1, df2)
```

^ Will change to this branch to get the test passing on this PR. Then in a follow up PR will revert to master unless any core devs have a different idea

### CODE REVIEW

**Comment by WillAyd** [comment]
Yea the network stuff is a little wonky to manage when doing this, but note there is also non-network stuff mixed in. Out of the azure stuff I think only `py36_locale_slow_old_np` actually runs the network tests, so rest should be green

**Comment by alimcmaster1** [comment]
Test failures now just 1 test related to - https://github.com/pandas-dev/pandas/issues/29514

**Comment by jreback** [comment]
i think if you merge master this will be green.

**Comment by jreback** [comment]
thanks !

**Comment by alimcmaster1** [comment]
No worries - I’ll attempt to fix that flakey test mentioned above

**Pull request merged**
