### PR TITLE
TYP: Upgrade mypy to 0.960

### PR DESCRIPTION
**Pull request by phofl**
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Looks like this passed out of the box

### CODE REVIEW

**Review by twoertwein — APPROVED** [review]
Can you also update the mypy version in https://github.com/pandas-dev/pandas/blob/main/doc/source/whatsnew/v1.5.0.rst

**Comment by jreback** [comment]
how old is 0.96?

**Comment by twoertwein** [comment]
> how old is 0.96?

mypy aims to have a monthly release cycle

**Comment by phofl** [comment]
> Can you also update the mypy version in https://github.com/pandas-dev/pandas/blob/main/doc/source/whatsnew/v1.5.0.rst

done

**Comment by twoertwein** [comment]
Thank you @phofl

**Pull request merged**
