### PR TITLE
DOC: update link to user guide

### LINKED ISSUE #39863: DOC: fixup link for lookup example
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.lookup.html?highlight=lookup#pandas.DataFrame.lookup

#### Documentation problem

It says

> For an example see lookup() in the user guide.

but the hyperlink doesn't send to the user guide

#### Suggested fix for documentation

link to https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#looking-up-values-by-index-column-labels instead

### PR DESCRIPTION
**Pull request by morrme**
- [x] closes #39863

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Built this locally and the link now works fine - thanks @morrme !

**Comment by MarcoGorelli** [comment]
@jorisvandenbossche I put the 1.3 milestone, but now I'm seeing other doc changes (e.g. #39858) being backported - should I change to 1.2.3 and backport?

**Comment by MarcoGorelli** [comment]
This fixes a doc change concerning a 1.2 deprecation, so am pretty convinced it needs backporting

@MeeseeksDev backport to 1.2.x

**Comment by jreback** [comment]
normally we don't backport too much except for CI issues that are likely to affect 1.2.x 
ok here if fixing something broken

**Pull request merged**
