### PR TITLE
TST: remove test_error

### PR DESCRIPTION
**Pull request by jbrockmendel**
It makes no sense to me that we'd test unwanted behavior by default and then override it for working arrays.

### CODE REVIEW

**Comment by jreback** [comment]
the default behavior *is* to error, how else would you test this? an EA that does not inherit the arithmetic mixins *should* error on these

**Comment by jbrockmendel** [comment]
> the default behavior is to error, how else would you test this? an EA that does not inherit the arithmetic mixins should error on these

It is the default behavior, but it isnt the _desired_ behavior.  e.g. if im a downstream author and i inherit the test class and see that `test_errors` is failing, what does that indicate that I need to fix?  nothing, the test itself is the problem.

if you want to test that this raises on the base class then OK i guess, but it doesnt make sense to have a test that exists only to be overridden to as a no-op (no-test?)

**Comment by jreback** [comment]
> > the default behavior is to error, how else would you test this? an EA that does not inherit the arithmetic mixins should error on these
> 
> It is the default behavior, but it isnt the _desired_ behavior. e.g. if im a downstream author and i inherit the test class and see that `test_errors` is failing, what does that indicate that I need to fix? nothing, the test itself is the problem.

ok fair

> 
> if you want to test that this raises on the base class then OK i guess, but it doesnt make sense to have a test that exists only to be overridden to as a no-op (no-test?)

yes pls. the issue is that someone expecting that the artithmetic ops should work *just* by inheriting the base class. We also would want a test to break if support for arithmetic ops was pushed to the base class itself.

**Comment by jbrockmendel** [comment]
updated + green

**Comment by jreback** [comment]
thanks

**Pull request merged**
