### PR TITLE
Remove Scatter and Hexbin from Series plot documentation

### LINKED ISSUE #38976: DOC: Scatter and Hexbin from Series plot documentation
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.html

#### Documentation problem

As the scatter and hexbin kinds are not supported for Series, it shouldn't appear in the docs for Series, just for DataFrames.

#### Suggested fix for documentation

Simply removing them.

### PR DESCRIPTION
**Pull request by 1nF0rmed**
- [x] closes #38976
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] Remove scatter and hexbin entry from https://github.com/pandas-dev/pandas/blob/v1.2.0/pandas/plotting/_core.py#L603-L1708

### CODE REVIEW

**Comment by jreback** [comment]
this is fine. there *is* a more comprehensive soln to this but it is more involed in not showing the access for those plot types for the underlying object (and then dynamically generating the doc-string), but out of scope.

**Comment by 1nF0rmed** [comment]
> this is fine. there _is_ a more comprehensive soln to this but it is more involed in not showing the access for those plot types for the underlying object (and then dynamically generating the doc-string), but out of scope.

Can you provide a reference for this?

**Comment by jreback** [comment]
> > this is fine. there _is_ a more comprehensive soln to this but it is more involed in not showing the access for those plot types for the underlying object (and then dynamically generating the doc-string), but out of scope.
> 
> Can you provide a reference for this?

you would to look in pandas/plotting/_core and see how the accessor is registered, basically trace it.

**Comment by jreback** [comment]
thanks @1nF0rmed

**Pull request merged**
