### PR TITLE
DOC: Update escapechar param description for read_csv

### PR DESCRIPTION
**Pull request by mhlevgen**
- [X] closes #23717
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
what issue is this closing?

**Comment by datapythonista** [comment]
@mhlevgen thanks for the contribution. Besides the incorrection regarding the quoting, I don't think the description of the `escapechar` parameter is very clear. Do you think you can improve it in this same PR?

**Comment by datapythonista** [comment]
@mhlevgen do you have time to fix the conflicts?

**Comment by datapythonista** [comment]
Closing as stale

**Pull request closed without merging**
