### PR TITLE
REF: change TDI.delete behavior to match DTI.delete

### PR DESCRIPTION
**Pull request by jbrockmendel**
With this change, the two methods behave the same and can be shared.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Whats the behavior change between "infer" and None?

**Comment by jbrockmendel** [comment]
> Whats the behavior change between "infer" and None?

```
tdi = pd.TimedeltaIndex(["1 Day", "2 Days", None, "3 Days", "4 Days"])

>>> tdi.delete(2).freq
None   <-- PR
<Day>  <-- master
```

**Review by jreback — CHANGES_REQUESTED** [review]
can you add a test that hits this

**Review by jreback — APPROVED** [review]

**Review by jreback — APPROVED** [review]
lgtm. ping on green.

**Comment by jbrockmendel** [comment]
ping

**Pull request merged**
