### PR TITLE
TST: Remove unused fixtures

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Looks like recent commits are trial/error for [something].  If thats sorted out ill take a look, tentatively looks good.

**Comment by mroeschke** [comment]
> Looks like recent commits are trial/error for [something]. If thats sorted out ill take a look, tentatively looks good.

This was an attempt at fixing https://github.com/pandas-dev/pandas/runs/4992372435?check_suite_focus=true but I cant reproduce locally

**Comment by mroeschke** [comment]
Ready for another look

**Comment by jbrockmendel** [comment]
thanks @mroeschke

**Pull request merged**
