### PR TITLE
Add --quiet option to isort command

### LINKED ISSUE #30974: DOC: Fix isort output in CI
In the CI, we're using `isort` to check whether the imports in Python files are sorted in an standard way. See https://github.com/pandas-dev/pandas/blob/master/ci/code_checks.sh#L114

The way it is implemented, we expect isort to not print anything in the terminal if everything is ok, and to show errors for the errors encountered. This is mostly true, except that `isort` is also reporting when there are files being skipped.

The result of this, is that we highlight in the CI as an error when there are files being skipped. See https://github.com/pandas-dev/pandas/pull/30946/checks?check_run_id=385833706#step:6:36

This can be misleading, and we should try to avoid it. Without adding much complexity to the already complex CI. Not sure if there is an `isort` parameter to simply not report the skipped files. Or if there is an easy way to not highlight the skipped files as an error.

### PR DESCRIPTION
**Pull request by d1618033**
- [x] closes #30974
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by alimcmaster1** [comment]
What does the output look like whenever an import is incorrectly sorted? Let’s push a commit here (you can mess up import ordering in any file) so we can double check all looks as expected on github actions

**Comment by d1618033** [comment]
@alimcmaster1 done. the output looks like this in case of an error:

```
Check import format using isort
##[error]ERROR: /home/runner/work/pandas/pandas/pandas/_config/config.py Imports are incorrectly sorted.
Check import format using isort DONE
```

**Comment by alimcmaster1** [comment]
LGTM - thanks. cc @datapythonista

**Review by alimcmaster1 — APPROVED** [review]

**Review by datapythonista — APPROVED** [review]
Did you check if errors are still displayed? If that's the case, this lgtm.

Thanks!

**Comment by d1618033** [comment]
@datapythonista The errors are still displayed. 
[This](https://github.com/pandas-dev/pandas/pull/31733#issuecomment-582933506) is a snippet from the output of [this](https://github.com/pandas-dev/pandas/pull/31733/checks?sha=4e72237f340eb63968f4bb099fec272eb6ab5769) commit where I changed the order of the imports to verify that errors are still being displayed (the CI logs seem to have been deleted, unfortunately)

**Comment by datapythonista** [comment]
Thanks for researching and fixing this!

**Pull request merged**
