### PR TITLE
Initialize row data frame with list

### LINKED ISSUE #48479: ENH: initialize row DataFrame with list
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

The following code does not work:
```
pd.DataFrame(data=[1,2,3], columns=["a", "b", "c"], index=[0])
```
but it should be quite easy to infer that the list must be intended as a row since both `columns` and `index` arguments are set.

### Feature Description

Provide the possibility to initialize a DataFrame with a plain list (or in general 1-D structures) when both `columns` and `index` arguments are specified. Optionally, provide an additional argument (eg: `direction` with possible values `index` and `columns`) that specifies if the 1-D structure must fill the DataFrame by row or by column.

### Alternative Solutions

A working solution is:
```
pd.DataFrame.from_records([[1,2,3]], columns=["a", "b", "c"])
```

But is sounds weird to me that the code in the Problem Description section does not work.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lucaslarios**
[X ] closes #48479(Replace xxxx with the GitHub issue number)
[ X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
[ X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
 Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
New Feature
It is now possible to initialize a dataframe with a list.

A parameter was also created that allows choosing the direction in which the list will be inserted in the dataframe when initializing it. By column or row.

Here are some examples:

EX1: direction parameter was not set and index parameter was
list_data = [1,2,3,4]
list_columns = ["a","b","c","d"]
result = pd.DataFrame(data=list_data,columns=list_columns,index=[5])

Result:
a b c d
5 1 2 3 4

EX2: direction parameter set as column

list_data = ["x","y","z","k"]
list_columns = ["a","b","c","d"]
pd.DataFrame(data=list_data,columns=list_columns,direction=["columns","b"])

Result:
a b c d
0 NaN NaN x NaN
1 NaN NaN y NaN
2 NaN NaN z NaN
3 NaN NaN k NaN

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
Thanks for the PR. Is there an existing issue discussing this feature?

As is, I would be -1 for this feature. The `DataFrame` constructor is essentially feature complete at this point

**Comment by lucaslarios** [comment]
https://github.com/pandas-dev/pandas/issues/48479

**Comment by attack68** [comment]
The underlying issue was never picked up by core devs. Im also -1 for this I'm afraid.

**Comment by mroeschke** [comment]
Thanks for the pull request, but unfortunately, the feature hasn't gotten enough support from the core devs. If you are interested in contributing, I would recommend searching for issues labeled `good first issue`. Closing

**Pull request closed without merging**
