### PR TITLE
STYLE: Inconsistent namespace - Indexes (#39992)

### PR DESCRIPTION
**Pull request by alexprincel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [X] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [X] whatsnew entry

Don't think tests apply here. By itself, does not close 39992.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Hi @alexprincel - no need for a whatsnewnote - other than that and the merge conflicts, this looks good, thanks

**Comment by MarcoGorelli** [comment]
Thanks @alexprincel for updating - there's still a conflict, could you resolve it please?

**Comment by alexprincel** [comment]
> Thanks @alexprincel for updating - there's still a conflict, could you resolve it please?

Hello, yes will do. Could not finish yesterday but it's fixed on my local environment now. Still learning how to use git properly :)

**Comment by MarcoGorelli** [comment]
No worries, I'd recommend the first 3 chapters of the [Pro Git](https://git-scm.com/book/en/v2) book to learn the common commands

**Pull request merged**
