### PR TITLE
DEPR: Series/Index .values special cases

### LINKED ISSUE #36957: API: series.values EA or ndarray[object]?
ATM `Series[categorical].values` gives a Categorical and `Series[sparse].values` gives a SparseArray.  Interval, Period, and DatetimeTZ get cast to ndarray[object].  3rd party EAs return the EA.

We should choose one or the other.  I have no real preference which.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #36957
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Is this motivated by code-sharing or trying to reduce special casing of our extension blocks?

IMO, if there's code in pandas that relies on `.values` returning an ndarray or not then that's a sign that we shouldn't be using `.values`. We should be using `.array` or `.to_numpy()` instead.

**Comment by jbrockmendel** [comment]
> Is this motivated by code-sharing or trying to reduce special casing of our extension blocks?

That, plus the general "this is a code smell" thing

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
Let's discuss further on the issue first?

**Comment by jbrockmendel** [comment]
> Let's discuss further on the issue first?

Sounds good.  I'll keep this open to debug the npdev build.

**Comment by jbrockmendel** [comment]
Not worth the effort to get the npdev build passing.  Closing.

**Pull request closed without merging**
