### PR TITLE
CLN: remove SingleBlockManager._values

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by topper-123 — APPROVED** [review]
LGTM

**Review by jreback — CHANGES_REQUESTED** [review]
hmm, i actually think this is worse as we are now peering into internal state. We should use the internals api in any callers, esp groupby.

**Comment by jbrockmendel** [comment]
> hmm, i actually think this is worse as we are now peering into internal state. We should use the internals api in any callers, esp groupby.

Just implemented with much better alternative: use obj._values like we do everywhere else

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
lgtm. merge on green.

**Pull request merged**
