### PR TITLE
CLN: inconsistent namespace usage in tests.indexes

### PR DESCRIPTION
**Pull request by jbrockmendel**
Finding these annoying while doing other work in this directory.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
can u update the precommit rule

**Comment by jbrockmendel** [comment]
> can u update the precommit rule

short answer: not really.  this only gets a handful of things in a handful of files.

i pinged @MarcoGorelli on the script; there are things I think it should catch that it isn't.  i dont want to tinker with the script until im confident it is working correctly.

**Comment by MarcoGorelli** [comment]
The original script only looks for class names - for methods, I think we could change `[A-Z]` to `\w` - I can test it out later

> i pinged @MarcoGorelli on the script

Where did you ping me? If it was in another issue then I may have missed it, sorry

**Comment by jbrockmendel** [comment]
> Where did you ping me? If it was in another issue then I may have missed it, sorry

Huh I'm not finding it, my bad.  I was asking why CLASS_NAMES had been removed, since ive noticed that both MultiIndex and pd.MultiIndex are present in some of the indexes test files.

**Comment by MarcoGorelli** [comment]
It might be that they appear if they're present with starting brackets, currently we just check for cases of e.g. `MultiIndex(` and `pd.MultiIndex(` being in the same file. pandas/tests/indexes/test_common.py contains `pd.MultiIndex` and `MultiIndex`, but neither are called, they're just used to check `isinstance`.

Maybe it's OK to remove the paren and extend the check beyond classes now

**Comment by jbrockmendel** [comment]
Makes sense.  For now I'll be happy with just fixing the handful in this PR so I don't keep stumbling over them in other branches.

**Comment by MarcoGorelli** [comment]
sure - I've opened #38093 as a placeholder

**Comment by jreback** [comment]
> sure - I've opened #38093 as a placeholder

great yeah we ought to become strict on these

**Review by jreback — APPROVED** [review]

**Pull request merged**
