### PR TITLE
Created icons for dark theme

### LINKED ISSUE #48762: DOC: Update color of icons for dark theme
The color of our icons in the docs don't look good with the dark theme:

dark_theme_icons

It'd be good to edit the svg files and make the color the same as the titles for example, rgb(69, 157, 185).

In the [Getting started](https://pandas.pydata.org/docs/getting_started/index.html) there are couple of icons that don't look good either. For the sql, we could pick a gray that looks good with both the bright and dark themes. For the SAS we may need two images, one with black letters and one with white (the pydata sphinx theme supports having different images for each theme).

Not sure if there is any other part of the docs where images need to be updated, but would be good that docs look good with dark theme everywhere.

### PR DESCRIPTION
**Pull request by lorenzovngl**
- [x] closes #48762

For the `svg` images mentioned in the referred issue, I created a version for the dark theme as suggested by @datapythonista.
The images are retrieved by the pydata sphinx theme as explained in [PyData Theme documentation](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/light-dark.html#use-theme-dependent-content).

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @lorenzovngl, looks good. I think we can probably keep just the new version of the icons, I think the new blue looks good for both themes, what do you think?  And the SQL one, if instead of white you make it gray, we can probably do the same. For SAS makes sense how it is now. What do you think? I think having just one version when possible will make things easier to maintain. And I think the new blue icons may look even better in the bright theme.

**Comment by lorenzovngl** [comment]
Hi! I absolutely agree with you. In my opinion, the new light blue looks better than the older one even for the light theme.
For the SQL logo, I chose the gray `#888888` because it seems to look good in both themes.
Since these latest changes are a kind of rollback, I created a new branch [lorenzovngl:dark-theme-icons-2](https://github.com/lorenzovngl/pandas/tree/dark-theme-icons-2). If everything is ok I can make a new pull request from that branch.

**Comment by datapythonista** [comment]
I think it'd be ok to also commit the changes here even if it's a rollback. Since the changes would vome in a separate commit, we could see differences, restore the old version... Even if it's in the same branch. But also fine to open a new PR and close this one if you think it's better.

**Review by datapythonista — APPROVED** [review]
Thanks @lorenzovngl, looks great!

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Awesome, thanks @lorenzovngl!

**Comment by datapythonista** [comment]
@lorenzovngl looks like the code for the SAS icon didn't work as expected. The sphinx code is leaked into the website.

Can you have a look please? https://pandas.pydata.org/docs/dev/getting_started/index.html#coming-from

**Comment by lorenzovngl** [comment]
I noticed there is a wrong syntax and it caused the code leak, but I can't figured out how to solve it...

**Comment by datapythonista** [comment]
> I noticed there is a wrong syntax and it caused the code leak, but I can't figured out how to solve it...

Do you mind reverting the changes in the rst file for now if you can't find the fix please? You can leave the two images and all the other changes, but at least it'll work well with the light theme while we find the fix. Also, if you can create an issue to use both images once it's reverted, that would be great. Thanks!

**Comment by lorenzovngl** [comment]
I opened #48935

**Pull request merged**
