### PR TITLE
DOC: Fix docstrings errors SEM and GET_GROUP

### PR DESCRIPTION
**Pull request by Axeldnahcram**
- [ ] part of https://github.com/pandas-dev/pandas/issues/60365

### CODE REVIEW

**Review by rhshadrach — APPROVED** [review]
lgtm

**Comment by rhshadrach** [comment]
@Axeldnahcram - can you merge main and resolve the conflicts.

**Comment by Axeldnahcram** [comment]
@rhshadrach done. I also have a small question. I have had some issues running the formatting/cleaning steps of precommit/linting and I was wondering if we should not include it in the Making a [pull request contribution guideline ](https://pandas.pydata.org/docs/development/contributing.html#id10)
Maybe it is intended ? Or maybe I simply missed a readme/documentation somewhere. Let me know what you think

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Axeldnahcram

**Pull request merged**
