### PR TITLE
Upload nightlies to new location

### PR DESCRIPTION
**Pull request by jarrodmillman**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by martinfleis** [comment]
A bit of context - the [Scientific Python Developer Summit](https://scientific-python.org/summits/developer/2023/) is happening this week. A part of the effort is to ensure that Scientific Python core packages follow the upcoming SPEC documents and support their implementation across the ecosystem. One of the specific changes is a move of the nightly wheels from `pypi.anaconda.org/scipy-wheels-nightly` which is planned to be closed to `pypi.anaconda.org/scientific-python-nightly-wheels`. That is what this PR does.

Once all of the packages that currently use `scipy-wheels-nightly` switch to `scientific-python-nightly-wheels`, we will use a bot to open PRs in downstream repositories to automatically change the index for nightlies across the ecosystem to minimise breakage.

One more step will need to happen here though. The upload requires an upload token stored as a repository secret (as you have right now). However, you will need to generate a new token for the new anaconda organisation. @jarrodmillman already added some people to the org but I don't think anyone from the pandas team is there right now. So let us know who is managing this at the moment so we can give you a proper access to the new repo so you can generate a new token.

The same change is happening in the other packages as well (e.g. https://github.com/numpy/numpy/pull/23792).

**Comment by mroeschke** [comment]
Thanks for opening. It sounds like the numpy, scipy and scikit-learn are moving in this direction so +1 to this change. Would be great to coordinate the change around the same time the other libraries are moving

**Comment by ksunden** [comment]
Numpy has moved already, scipy is likely to move today, I think pandas is the next domino after scipy, then matplotlib can follow shortly thereafter (we are basically ready, but the PR includes our nightly tests, and we install pandas for that workflow)

xref numpy/numpy#23792 scipy/scipy#18504 matplotlib/matplotlib#25950

**Comment by mroeschke** [comment]
Thanks for the update. Are most projects doing a hard cutoff from uploading from the old to new index?

**Comment by martinfleis** [comment]
@mroeschke that is what scipy and numpy have done and it seems that matplotlib will do the same.

**Comment by tupui** [comment]
Hi folks,

So here are the latest information about the migration. NumPy and SciPy have now migrated (still some small things to adjust, but some wheels are there.)

To add a new package this needs to be done (instructions have been updated on the SPEC4):

1. Tell us who needs to be responsible for nighlies for your package. And give us the anaconda handles.
2. We download from PyPi a wheel and upload it using an admin token. This will create the package.
3. We link the package to your group.
4. You can now create a personal token and upload your package.

Let me know if you need any assistance, I am happy to make calls to speed up things or we can chat on Slack/Discord.

**Comment by ksunden** [comment]
@pllim I uploaded a set of mpl wheels yesterday, so if that was what was holding you up, you should be good to go, we do want this PR merged so we can merge matplotlib/matplotlib#25950 to keep our nightly installs working/start automatically uploading to the new location, but there is a recent nightly of mpl on the new location now.

**Comment by pllim** [comment]
@ksunden , yes, I saw, thank you very much! This is not a blocker, though I also do not want to rely on a one-off that could go stale, in case this drags on for months. I just want a feel of the timing. No worries here (for now).

**Comment by mroeschke** [comment]
@pandas-dev/pandas-core does anyone have a anaconda handle that would like to be associated with the new nightly wheels location?

**Comment by lithomas1** [comment]
aarch64 wheels are currently uploaded with a token from my personal account(lithomas1).

I believe @TomAugspurger has access to the ``scipy-wheels-nightly`` account that uploads the rest of the wheels.

I'm fine with continuing with the current setup, but its probably better if an admin of the pandas-dev org does the uploads.
(I can't add secrets to the Github Actions workflows, only an admin can do that I think)

**Comment by mroeschke** [comment]
I can work on creating an anaconda account early next week and migrate our wheel uploads to `scientific-python-nightly-wheels`

**Comment by mroeschke** [comment]
Sorry for the delay @tupui, I just created an anaconda account with username `mroeschke`. I can be responsible for the nightly package.

Let me know what the best next steps would be. Side note: I could also work with @betatim on the transition since we work together

**Comment by tupui** [comment]
@mroeschke all done 😃 Thanks!

https://anaconda.org/scientific-python-nightly-wheels/pandas

I uploaded the latest wheel for linux to create the package. You should now be able to administrate the package itself. I did not add for now Tim as he is already on another project. But up to you in the end.


Let me know if you have any questions, issues. Note that the policy is still in the making, so please allow us some time to adjust 😅 Moving forward, for transparency, please open an issue on the SPEC repo if you need anything.

**Review by rhshadrach — COMMENTED** [review]
What about actions-310-numpydev.yaml which has the line

    "--extra-index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple"

**Comment by jarrodmillman** [comment]
> What about actions-310-numpydev.yaml which has the line
> 
> ```
> "--extra-index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple"
> ```

It looks like that was fixed in #53508.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Great thanks all! Let's see if the nightly wheels get uploaded to the new index later today

**Comment by mattip** [comment]
Hi all. I see 80GB of files at https://anaconda.org/scipy-wheels-nightly/pandas. May I delete them? The last upload to there was June 6, 2023.

**Comment by mattip** [comment]
Also, it seems the location https://anaconda.org/multibuild-wheels-staging/pandas is in active use. There are many old files there, but also some new ones. How should that space be managed?

**Comment by mroeschke** [comment]
> Hi all. I see 80GB of files at https://anaconda.org/scipy-wheels-nightly/pandas. May I delete them? The last upload to there was June 6, 2023.

Yes, I think it OK to remove all those wheels now that we're using the `scientific-python-nightly-wheels` index for nightlies

> Also, it seems the location https://anaconda.org/multibuild-wheels-staging/pandas is in active use. There are many old files there, but also some new ones. How should that space be managed?

I don't recall anymore the purpose for the `multibuild-wheels-staging` index. I see numpy is the only other project actively uploading there too. Is the ecosystem still using `multibuild-wheels-staging`?

**Comment by mattip** [comment]
NumPy stopped uploading there when it moved to using trusted publishing a few months ago. It was previously used as a staging area for convenient downloading of wheels to then upload to PyPI.

**Comment by mattip** [comment]
> Yes, I think it OK to remove all those wheels now that we're using the scientific-python-nightly-wheels

Done.

**Comment by jorisvandenbossche** [comment]
With https://github.com/pandas-dev/pandas/pull/63265, we should also stop uploading to multibuild-wheels-staging now

**Comment by mroeschke** [comment]
@mattip pandas should be OK now to purge its wheels from `multibuild-wheels-staging`

**Comment by mattip** [comment]
> purge its wheels from `multibuild-wheels-staging`

Thanks, done.

**Pull request merged**
