### PR TITLE
TYP: use TYPE_CHECKING for import_optional_dependency("numba")

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref https://github.com/pandas-dev/pandas/pull/44233#issuecomment-955594933 or could go with https://github.com/pandas-dev/pandas/pull/44254#issuecomment-956450632 instead.

cc @twoertwein

### CODE REVIEW

**Comment by twoertwein** [comment]
There is one more: pandas/core/window/numba_.py:261 After that one you can also remove the pyright comment from the file.

If `numba.generated_jit` can be typed in `typings.numba`, we can also remove the pyright comment in pandas/core/util/numba_.py.

**Review by twoertwein — APPROVED** [review]

**Comment by twoertwein** [comment]
@simonjayhawkins I'd be happy to merge this PR (after rebasing), but I'm not sure whether I (as the only reviewer so far) am allowed/supposed to also merge it?

**Comment by jreback** [comment]
@twoertwein can you merge master and @mroeschke if you can have a look

**Review by mroeschke — APPROVED** [review]

**Comment by jreback** [comment]
thanks @simonjayhawkins

**Pull request merged**
