### PR TITLE
Fixing documentation lists indentation (#21518)

### LINKED ISSUE #21518: DOC: Fix indentation of lists in rst files
The indentation for lists in the restructuredText standard is next:
- No indentation for top level lists
- 4 space indentation for sublists

When a top list is indented (with for example one space), the list is included in a `blockquote` element when rendered as html. In the current sphinx template, this does not seem to have any visual impact, but with other templates (e.g. the `sphinx-responsive-theme`) it does. See this screenshot for an example:

https://user-images.githubusercontent.com/10058240/41320132-6d1b1078-6e96-11e8-9b7b-a6617bdcdd16.png

Regarding sublists, sphinx is flexible when applying the standard, and sublists indented with for example 3 spaces, are rendered correctly as sublists. But other software like `pandoc` (not currently used to render `rst` files), does not consider the indented lists as sublists unless they are indented with the right number of spaces (four).

Ideally we want to have all the top level lists without indentation, and the sublists with 4 space indentation, so we can replace the current sphinx template, and we can render the `rst` files with software that is strict with the standard.

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #21518
- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
- does this change the rendering anywhere?
- do you have a script to check this? (e.g. we can add to lint.sh)

**Comment by datapythonista** [comment]
There is a subtle change in the margins with the current template. The change is mainly to have a correct rendering with other markdowns that change the font of blockquotes.

With the current theme, it will make lists like the one in:
- https://pandas.pydata.org/pandas-docs/stable/overview.html#package-overview

Render with the margins of lists like:
- https://pandas.pydata.org/pandas-docs/stable/visualization.html#plotting-with-error-bars

The lists that currently have spaces before the `*` like the one in the overview page have a greater left indentation, that with this change will be removed. The resulting indentation will be the one in the visualization page.

I don't have any script that checks the rendering. Are you thinking on something for visual regression testing, or something simpler?

**Comment by jreback** [comment]
@datapythonista I meant a script to check the indentation of the lists. (checking rendering is extremely hard and out of scope)

**Comment by datapythonista** [comment]
Oh, I understand now, I mixed the two questions; Monday morning... :)

I did the changes looking for the indentation manually. I think a script is a good idea, not sure if it's trivial. I'll create a separate ticket for implementing the script if that's all right.

**Comment by datapythonista** [comment]
Created #21520

**Comment by datapythonista** [comment]
Ups, forgot to mention about using stars... In the first files I reviewed, all lists were using stars, so when I found the first hyphens I changed them for consistency, expecting to be very few cases. At the end there were many, so I think the change wasn't that much of a good idea, and just adds noise to the PR. But as I already changed them I didn't want to revert.

**Comment by jreback** [comment]
@jorisvandenbossche I put this on 0.23.2 as it other changes touch the docs might be a slight diff, but no big deal.

**Comment by jreback** [comment]
thanks @datapythonista

**Comment by jorisvandenbossche** [comment]
> @jorisvandenbossche I put this on 0.23.2 as it other changes touch the docs might be a slight diff, but no big deal.

Yep, will decide on it when backporting

**Pull request merged**
