### PR TITLE
CI: Mark network test as xfail

### PR DESCRIPTION
**Pull request by phofl**
- [x] xref #39155
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

https://github.com/pandas-dev/pandas/issues/39155#issuecomment-759783358

### CODE REVIEW

**Comment by jreback** [comment]
great ping on green

**Comment by phofl** [comment]
@jreback green

**Comment by jreback** [comment]
thanks @phofl

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
