### PR TITLE
CI: Limit pip extras check to Build tag

### PR DESCRIPTION
**Pull request by mroeschke**
xref https://github.com/pandas-dev/pandas/pull/49241#issuecomment-1320485994

cc @lithomas1

### CODE REVIEW

**Comment by lithomas1** [comment]
This doesn't seem to be triggering, but the logic looks correct to me(pretty sure its identical to the working sdist trigger).

I'll try again later, we might be hitting some sort of concurrency limit.

**Comment by lithomas1** [comment]
Oh, I figured it out. You need to add "labeled" to the "on" tag like https://github.com/pandas-dev/pandas/blob/main/.github/workflows/sdist.yml#L12, for the labelling to trigger the runs.

**Comment by mroeschke** [comment]
> Oh, I figured it out. You need to add "labeled" to the "on" tag like https://github.com/pandas-dev/pandas/blob/main/.github/workflows/sdist.yml#L12, for the labelling to trigger the runs.

Ah cool thanks. Added the on tags to the workflow

**Review by lithomas1 — APPROVED** [review]

**Comment by lithomas1** [comment]
Thanks @mroeschke.

**Pull request merged**
