### PR TITLE
Fix typo in docstring of DataFrame.memory_usage

### PR DESCRIPTION
**Pull request by pjleimbigler**

### CODE REVIEW

**Comment by WillAyd** [comment]
Can you address the PEP8 violation?

**Review by WillAyd — CHANGES_REQUESTED** [review]
comment above

**Comment by pjleimbigler** [comment]
Apologies; rewrapped the offending line in a new commit (c4e48f0).

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks!

**Pull request merged**
