### PR TITLE
CI/TST: Check that unittest.mock is not being used in testing

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref https://github.com/pandas-dev/pandas/pull/24624#issuecomment-451658866

### CODE REVIEW

**Comment by jreback** [comment]
ping on green.

**Comment by jreback** [comment]
thanks!

**Comment by plammens** [comment]
What was the rationale behind this? `unittest.mock.Mock` and `unittest.mock.MagicMock` are really useful (see [this](https://github.com/pandas-dev/pandas/commit/ced8628a71063cf4b080ef335cd7c005d7b4f8b7#diff-86951d150476847d783821ee0f0842d7) for example), and there's no equivalent with the `monkeypatch` fixture (which really only substitutes `unittest.mock.patch`, not the whole `unittest.mock` module). 

If this was to avoid the import under Python 2, it's no longer relevant since Python 2 is no longer supported, and it should be reverted.

CC @simonjayhawkins, @jreback, @WillAyd

**Comment by jreback** [comment]
i think the description says it all

there is really no reason to use mock as monkey patch will do the limited things that we need

generally we prefer to not mock at all - when apis change often time mocks will work but the code is broken

**Pull request merged**
