### PR TITLE
CI: Remove docs build from pipelines

### LINKED ISSUE #29472: CI: Move documentation build to GitHub actions
GitHub actions is out of beta, and should have much better integration with GitHub than pipelines.

I'm thinking on giving it a try for the documentation build, and see if we can get an improvement on current CI problems:
- Too many steps from the PR page to the logs (#26895)
- Notify with a comment on the PR when there are problems (#26930)
- Publish the documentation for a PR so it can be seen

Any objection? Depending on how things go with the doc build, I think it may make sense to give other builds a try to.

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #29472

At the moment we're building the web and the docs from both Actions and Pipelines. While is still under discussion where things should be hosted, it's probably worth to just build on Actions for now, and publish from there to both the OVH cloud, and to GitHub pages.

**This needs the GitHub pages ssh key to be added to the secrets of this repo with name "github_pages_ssh_key".*** Can someone with permissions please add it? Or if we already got it with a different name, please let me know the name.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
> Can someone with permissions please add it?

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
I'm not sure what the value of the key is. Perhaps @jorisvandenbossche has it?

**Comment by datapythonista** [comment]
Sent them via email.

**Comment by TomAugspurger** [comment]
Thanks @datapythonista. Added to the pandas-dev/pandas github repo's secrets with the name `github_pages_ssh_key`.

**Comment by datapythonista** [comment]
Cool, this should be ready then. As a follow up, I'll synchronize the website and the dev docs in the rackspace server in the GitHub Actions build.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
I just noticed https://github.com/ammaraskar/sphinx-action (a github action to build sphinx docs and puts errors inline), might be interesting (but didn't really look at it)

**Review by WillAyd — APPROVED** [review]
lgtm - can you merge master one more time to be sure?

**Comment by datapythonista** [comment]
All green after rebasing, merging.

**Pull request merged**
