### PR TITLE
BUG: Fix typo in parsers.py

### LINKED ISSUE #9266: uin8 should be uint8 in io/parsers.py
while using read_fwf I had a bug that had this line from parsers.py

https://github.com/pydata/pandas/blob/072e40b0b5beab36c2adda9e0bcbb26755e1928f/pandas/io/parsers.py#L989

in which there is a np.uin8 which I'm pretty sure should be a np.uint8

apologise if this has already been submitted - I did a search on uin8 and only got the offending line in the code.

I just fixed on my arch source code to keep working on my problem (I'm an engineer not a software guy!). I will try and find time for a patch and test (I failed on my last one)

CHeers

Rick

### PR DESCRIPTION
**Pull request by twu**
closes #9266 

np.uin8 should be np.uint8

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Looks like this code path was never tested then :laughing: @twu interested in writing a test that *does* cause cause a `ValueError` here?

**Comment by twu** [comment]
Sure, will do as soon as I'm home from work :)

**Comment by jreback** [comment]
this is already partially done in #9350 

just need a complete test

**Comment by jreback** [comment]
closing in favor of #9350

**Pull request closed without merging**
