### PR TITLE
BLD: Clean up dependencies for Cython files

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
an does this solve the problem?
this is including way too many things; all of the pyx are not needed just the pxd

**Comment by jbrockmendel** [comment]
FFS I asked exactly that pyx vs pxd question over in #18089 and you guys ignored it.  Fix this yourselves.

As far as I'm concerned this makes things distinctly worse.

**Comment by gfyoung** [comment]
IMO, let's focus on getting a working build first.  We can "clean up" later.  Mixing the two together is making it hard for us to make progress here.

**Comment by gfyoung** [comment]
Actually, due to merge conflicts, it looks like this will be annoying to merge in as written.  Let's start from scratch.

**Pull request closed without merging**
