### PR TITLE
Bug: Don't intercept TypeError in DataFrame.agg

### LINKED ISSUE #49399: Bug: Don't intercept TypeError in DataFrame.agg
https://github.com/pandas-dev/pandas/blob/3370c8179de16b3f0556891a1ff06131e186dfd1/pandas/core/apply.py#L735-L745

We intercept any TypeError and reword the message to be about the DataFrame constructor. This likely made sense before, but with the code being refactored and #43741, TypeErrors can occur for many different reasons. We should just remove the `except` block above.

### PR DESCRIPTION
**Pull request by sarvaSanjay**
- [ ] closes #49399  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by rhshadrach** [comment]
Thanks for the PR! Could you update the title by clicking the edit button here:

image

to be a bit more descriptive? It can even just be the title from the corresponding issue.

I also suspect there will be a number of test failures; we check the error message and that message will now need to be updated.

**Comment by sarvaSanjay** [comment]
@rhshadrach,
Thanks for your msg. Sorry about the title. I believe it's better now. Also regarding the test failures, I believe they will have to be fixed at your end? Or would I have to change something in the test folder?

**Comment by rhshadrach** [comment]
Title looks great - thanks!

> Or would I have to change something in the test folder?

You're changing tested behavior of pandas, and that is going to cause the tests to "fail". The tests that have failed need to be updated with the correct error types and messages.

**Comment by rhshadrach** [comment]
Closing as stale. @sarvaSanjay - if you'd like to continue comment here and we can reopen.

**Pull request closed without merging**
