### PR TITLE
CI Ipython ci fixup again

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Looks like with ipython 8.8.0, it's necessary to `# type: ignore` this line, as opposed to 8.7.0 (that's the difference in the environments between today and yesterday):
```
                                                  Name Version_x Version_y
0    ──────────────────────────────────────────────...      None      None
61                                            cfn-lint    0.72.5    0.72.6
68                                            coverage     7.0.2     7.0.3
144                                           identify    2.5.11    2.5.12
151                                            ipython     8.7.0     8.8.0
169                                       jupyter_core     5.1.1     5.1.2
377                                              scipy     1.9.3    1.10.0
399                                         sqlalchemy    1.4.45    1.4.46
```

**Review by mroeschke — APPROVED** [review]
LGTM pending green

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @MarcoGorelli

**Comment by rhshadrach** [comment]
Probably due to https://github.com/ipython/ipython/pull/13858/

**Pull request merged**
