### PR TITLE
DOC: Fixes additional flake8 issues in whatsnew v0.14.0 #24240

### PR DESCRIPTION
**Pull request by Seuss27**
Related to #24240 

Fixed an indentation error that revealed more flake8 issues.

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
@Seuss27 the template we provide in the description of the pull request, helps us know which issue are you addressing, and it closes it automatically when we merge the PR. Instead of deleting it, the idea is that you replace the `#xxxxx` by the issue number, and tick all the checkboxes that apply.

For this PR, we need the changes in `setup.cfg` that remove the file from the exclusion list, so it's validated.

**Comment by Seuss27** [comment]
@datapythonista This file was already processed and removed from setup.cfg, I noticed the compilation errors when I was debugging another rst file.  Understood regarding the template and the usage.

**Review by datapythonista — APPROVED** [review]
ok, I see, thanks for clarifying @Seuss27 

Next time it makes it easier if you say that in the PR description, and you add the PR number this is a follow up of.

**Comment by jreback** [comment]
are we not checking? since 0.14. is removed?

**Comment by datapythonista** [comment]
For what I understand, `flake8-rst` wasn't detecting the issue, but it was generating warnings in the sphinx build. We will start taking care of the warnings when we fix the `flake8-rst` issues, so eventually we'll check them.

**Comment by jreback** [comment]
thanks @Seuss27

**Pull request merged**
