### PR TITLE
Use date32 for pyarrow date

### PR DESCRIPTION
**Pull request by alippai**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
I don't think this necessarily should unequivocally be date32. There may be a use case for storing with increased precision.

**Comment by alippai** [comment]
@mroeschke the precision is always the same, it's unexpected to store non-fullday value in pa.date64: https://lists.apache.org/thread/q036r1q3cw5ysn3zkpvljx3s9ho18419

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks for the explanation @alippai

**Comment by alippai** [comment]
Thanks for the swift merge and backport @mroeschke

**Pull request merged**
