### PR TITLE
BUG GH#43414 Infer and coerce datetimes am pm

### LINKED ISSUE #43414: BUG: pd.to_datetime cannot infer and coerce dates with AM/PM and infer_datetime_format=True and errors="coerce".
#### Checklist
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas.
- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

```python
series = pd.Series(data=['1/1/2021 11:00:00 AM', '1/1/2021 12:00:00 PM', '1/1/2021 1:00:00 PM'])
result = pd.to_datetime(series, errors='coerce', infer_datetime_format=True)
```

#### Problem description
The function should be able to infer datetime strings with AM/PM correctly.  This can be seen when using errors='raise' which will correctly return the expected values.  Looks like this is a result of an existing issue - https://github.com/pandas-dev/pandas/issues/25143.

#### Expected Output
expected = pd.Series(data=[Timestamp('2021-01-01 11:00:00'), Timestamp('2021-01-01 12:00:00'), Timestamp('2021-01-01 13:00:00')])

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 6a683a2911bd82ea40c7e11b8135a0e952f55f2c
python           : 3.8.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 1.4.0.dev0+597.g6a683a2911
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.1.3
setuptools       : 52.0.0.post20210125
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : 6.14.4
sphinx           : 4.1.2
blosc            : 1.10.4
feather          : None
xlsxwriter       : 1.4.4
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.25.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 2021.05.0
fastparquet      : 0.6.3
gcsfs            : 2021.05.0
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : 2021.05.0
scipy            : 1.7.0
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1

</details>

### PR DESCRIPTION
**Pull request by ghost**
- [ ] closes #43414 
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by mikephung122** [comment]
Something interesting is that when we infer_datetime_format we actually only use the first record.  This is important because in some of the tests we generate data with pd.date_range where by default the first record will start at midnight.  This can lead to different behavior than if the data did not start with a record at midnight, which is probably more common in practice.

**Comment by simonjayhawkins** [comment]
Thanks @mikephung122 for the PR.

tests are failing https://github.com/pandas-dev/pandas/pull/43416/checks?check_run_id=3517046932

> Something interesting I found is that when we infer_datetime_format we actually only use the first record.

This is clearly stated in the docs. 

```
infer_datetime_format : bool, default False
        If True and no `format` is given, attempt to infer the format of the
        datetime strings based on the first non-NaN element,
        and if it can be inferred, switch to a faster method of parsing them.
        In some cases this can increase the parsing speed by ~5-10x.
```

There is an underlying issue with `infer_datetime_format=True` and `errors='coerce'` specified together, #25143

The fact that specifying `errors='raise'` or not specifying `infer_datetime_format=True` gives the correct result with the code sample in the issue OP #43414, would fixing the underlying issue not fix this issue without the code added here?

**Comment by mikephung122** [comment]
When I found this problem I also thought it was related to #25143.  However, the more I looked into it the more unclear and now I believe fixing this as a separate issue might make more sense.

I think this fix is straight-forward.  Ideally, the guess_datetime_format function can and should be able to guess date and time formats with AM/PM.  However, right now it will return something like this '%m/%d/%Y %H:%M:%S AM'.  
Screen Shot 2021-09-04 at 10 08 45 PM

So when we try to use that to parse, if we're trusting the guessed format, I actually think it's correct behavior that those errors return a NaT.  I would expect that errors="raise" does not properly raise when unable to parse with the guessed format.  However, this does not occur because the "coerce" vs. "raise" errors argument changes how the datetime is parsed, not just how errors are handled.  You can see this affecting many more examples than just the AM / PM.  

I checked the test, it looks like its the new unit tests that are failing for that one environment.  However, they don't fail locally or on the other CI/CD environments.  I'm wondering if this is related to how the "pytest (actions-38-locale.yaml, not slow and not network, language-pack-zh-hans xsel, zh_CN.utf8,..." is built and ran?

**Comment by mikephung122** [comment]
I checked the test, it looks like its the new unit tests that are failing for one posix environment.  However, they don't fail locally or on the other environments.  I'm wondering if this is related to how "pytest (actions-38-locale.yaml, not slow and not network, language-pack-zh-hans xsel, zh_CN.utf8,..." is built and ran?  This is actually my first time touching any of the cython, are there any additional steps that need to be done outside of changing the .pyx file?

**Pull request closed without merging**
