### PR TITLE
CI: Pin pyarrow to < 11.0

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @MarcoGorelli

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
I think you'll need to fix the sed too, like was done in https://github.com/pandas-dev/pandas/pull/50055/files

**Comment by phofl** [comment]
thx, adjusted

**Review by MarcoGorelli — APPROVED** [review]
thanks @phofl

**Comment by phofl** [comment]
no need to backport, it's pinned to <10 on 1.5.x

**Pull request merged**
