### PR TITLE
BLD: support 3.8 pre

### LINKED ISSUE #26626: Setup python 3.8 builds
As the python 3.8 release date draws closer ( currently [scheduled](https://www.python.org/dev/peps/pep-0569/#release-schedule) for October this year ).

I was wondering if we want to set up python3.8 builds?

Given the 3.8 dev branch is available on [travis](https://docs.travis-ci.com/user/languages/python/) and shortly [azure](https://github.com/Microsoft/azure-pipelines-image-generation/issues/905).

Might be abit early for this - but it will mean we can catch any potential issues early + support python 3.8 upon release date.

Related issues: https://github.com/pandas-dev/pandas/issues/22714

I am happy to work on this - but would be good to get people's thoughts first.

Thanks!

### PR DESCRIPTION
**Pull request by jreback**
closes #26626

### CODE REVIEW

**Comment by jreback** [comment]
this is not working yet :-<

https://travis-ci.org/jreback/pandas/jobs/555079593

```
    error: Command "ccache gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibuild/src.linux-x86_64-3.8/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/travis/miniconda3/envs/pandas-dev/include/python3.8m -Ibuild/src.linux-x86_64-3.8/numpy/core/src/common -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/common -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -c build/src.linux-x86_64-3.8/numpy/core/src/npysort/radixsort.c -o build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/numpy/core/src/npysort/radixsort.o -MMD -MF build/temp.linux-x86_64-3.8/build/src.linux-x86_64-3.8/numpy/core/src/npysort/radixsort.o.d" failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/travis/miniconda3/envs/pandas-dev/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-midvhiik/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-89u54j1w/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-midvhiik/
```

any ideas here @mattip

**Comment by mattip** [comment]
I think you need to add `-std=c99` to the CFLAGS

**Comment by mattip** [comment]
You are building NumPy since NumPy does not yet provide a wheel for python3.8, and somehow the build script is not adding that flag. NumPy seems to be adding it into the CI configurations. This might be a bug in the way `pip install git+https://github.com/numpy/numpy` is invoking the compiler.

**Comment by jreback** [comment]
> You are building NumPy since NumPy does not yet provide a wheel for python3.8, and somehow the build script is not adding that flag. NumPy seems to be adding it into the CI configurations. This might be a bug in the way `pip install git+https://github.com/numpy/numpy` is invoking the compiler.

interesting, is there any way to force this on pip?

**Comment by mattip** [comment]
Can you try this in a clean python 3.8 virtualenv?
```
pip install cython pytz
pip install git+https://github.com/numpy/numpy
```

**Comment by jreback** [comment]
> Can you try this in a clean python 3.8 virtualenv?
> 
> ```
> pip install cython pytz
> pip install git+https://github.com/numpy/numpy
> ```

I tried this exactly on macosx and it fails as well (was using the conda install via the pre channel for python & pip; cython from source)

e.g. I was always doing
```pip install cython pytz --no-binary :all: --pre```

**Comment by mattip** [comment]
Maybe we only set the flag automatically for gcc (I assume you are using clang)? What happens if you
```
CFLAGS='-std=c99' pip install git+https://github.com/numpy/numpy
```
You should see the flag appear in the compile flags

**Comment by jbrockmendel** [comment]
Anything left to do here?

**Comment by jreback** [comment]
numpy is not installing correctly yet.

**Comment by mattip** [comment]
Steps I took to reproduce, these succeeded for me on x86-64 Ubuntu 18.04

```
conda init -n python3.8
conda activate python3.8
conda config --env --add channels conda-forge/label/pre-3.8
conda install python=="3.8.*"
python3.8 -mpip install --pre --no-binary :all: cython
python3.8 -mpip install --pre --no-binary :all: git+https://github.com/numpy/numpy
```

**Comment by TomAugspurger** [comment]
That was only tested against 3.8 locally. We would ideally have a 3.8 build
on CI before release 0.25.2.

I think we'll need to wait for 3.8b4, otherwise we'll have segfaults from
https://bugs.python.org/issue37915.

**Comment by jbrockmendel** [comment]
> I think we'll need to wait for 3.8b4

`pyenv install 3.8-dev` now installs 3.8b4.  Does that un-block this?

**Comment by TomAugspurger** [comment]
Not really. We use conda on CI.

Travis already provided a python-dev base environment. If anyone wants to,
we'd probably be OK with a PR that added
a new entry on travis using 3.8 from travis and compiling NumPy from source
as a stopgap until conda packages are
ready for 3.8.

**Comment by jreback** [comment]
looks like @jbrockmendel is working on this now.

**Pull request closed without merging**
