### PR TITLE
CI: unary operator expected error in log files

### PR DESCRIPTION
**Pull request by simonjayhawkins**
fix error in azure log

```
ci/setup_env.sh: line 121: [: ==: unary operator expected
```

### CODE REVIEW

**Comment by WillAyd** [comment]
Was this causing any other issues or was our CI just not running DB tests on travis?

**Comment by simonjayhawkins** [comment]
causing a spurious message in the azure logs. it's probably no big deal. Travis didn't run, so will need to re-run to check this didn't break anything on the Travis front.

**Comment by simonjayhawkins** [comment]
so it appears Travis is not run for draft PRs. marking this as ready for review, but's it not ready! need to check the Travis logs.

**Comment by simonjayhawkins** [comment]
> or was our CI just not running DB tests on travis?

it's the other way round. db tests running on Travis only.

**Comment by jreback** [comment]
lgtm. pls verify that the message is coming on the right builds; merge when ready.

**Comment by simonjayhawkins** [comment]
> pls verify that the message is coming on the right builds

checked.

**Pull request merged**
