### PR TITLE
Backport PR #41730: CI: suppress npdev warnings

### PR DESCRIPTION
**Pull request by simonjayhawkins**
Backport PR #41730

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
It would be nice to get ci green on 1.2.x but not needed for release. Could merge this as is to reduce the number of errors on npdev env considerably and maybe look at the other errors separately.

The 2 test fails are just error messages so could be easily changed (here or followup).

The setup errors that do not fail on master are due to some recent changes on master for maybe_infer_to_datetimelike, so we won't be backporting those. I think we could maybe filter the warnings differently and that may work in the setup phase too. will look soon.

**Comment by jreback** [comment]
sure merge as needed (or ping me if u want review)

**Comment by simonjayhawkins** [comment]
@jreback green (except circle CI, would either need to backport configuration file or change config on master to not run on branches)

**Comment by jreback** [comment]
ignore circle

**Pull request merged**
