### PR TITLE
scatterplot issue

### PR DESCRIPTION
**Pull request by raunakchhabra**
added basic idea to add labels to scatter plot

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Hi @raunakchhabra - why is this in .github/ISSUE_TEMPLATE/plotscatter.py, and what does it do? What 'scatterplot issue' are you referencing?

**Comment by raunakchhabra** [comment]
> Hi @raunakchhabra - why is this in .github/ISSUE_TEMPLATE/plotscatter.py, and what does it do? What 'scatterplot issue' are you referencing?
scatterplot issue #36774

**Comment by MarcoGorelli** [comment]
> > Hi @raunakchhabra - why is this in .github/ISSUE_TEMPLATE/plotscatter.py, and what does it do? What 'scatterplot issue' are you referencing?
> > scatterplot issue #36774

That's the pull request number - what issue are you trying to solve?

**Comment by raunakchhabra** [comment]
> > > Hi @raunakchhabra - why is this in .github/ISSUE_TEMPLATE/plotscatter.py, and what does it do? What 'scatterplot issue' are you referencing?
> > > scatterplot issue #36774
> 
> That's the pull request number - what issue are you trying to solve?

Adding labels to scatter plots

**Comment by MarcoGorelli** [comment]
OK, please see here https://pandas.pydata.org/pandas-docs/stable/development/contributing.html for how to contribute to pandas

Closing as this is too far off, sorry, but thanks for your interest

**Pull request closed without merging**
