### PR TITLE
CI: Debug segfaults on npdev

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by lithomas1** [comment]
Got the backtrace, going to post on #51589.

**Comment by jbrockmendel** [comment]
Have we tried asking @seberg for help?

**Comment by lithomas1** [comment]
Didn't ask yet, was going to try to get this down to a MRE, but got sidetracked.

**Comment by seberg** [comment]
Hmmmmpf, some other PRs still seem to fail in much the same way?  Seems my fix may have not been complete.

**Comment by lithomas1** [comment]
> Hmmmmpf, some other PRs still seem to fail in much the same way? Seems my fix may have not been complete.

We cache our dependencies, I'll just cleared the cache, and now we're hitting problems because of the latest Cython 3 beta.

**Comment by lithomas1** [comment]
@seberg Looks like the segfaults have disappeared. We do have some other failures, but those seem Cython related.

Thanks for the quick fix.

**Pull request closed without merging**
