### PR TITLE
Update multi.py

### PR DESCRIPTION
**Pull request by zky001**
fix bugs be metioned on issue #35301

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by arw2019 — CHANGES_REQUESTED** [review]
We need a test for this 

Also - are you sure this is enough to fix the original problem? I tried this quickly and it seems like the error persists

**Review by arw2019 — COMMENTED** [review]
Cool, I think that does fix the original issue!

Unfortunately as is it seems to break some of the other tests so that's something to look into (in particular a few go wrong in `pandas/tests/multi/test_indexing.py`)

**Comment by zky001** [comment]
> We need a test for this
> 
> Also - are you sure this is enough to fix the original problem? I tried this quickly and it seems like the error persists



> Cool, I think that does fix the original issue!
> 
> Unfortunately as is it seems to break some of the other tests so that's something to look into (in particular a few go wrong in `pandas/tests/multi/test_indexing.py`)

thanks , I will fix that

**Comment by zky001** [comment]
shall I close this pr? xs is intended for scalar lookups

**Comment by jreback** [comment]
as indicted in the issue would take a better error message
add a test from the OP

**Pull request closed without merging**
