### PR TITLE
fixed capitalization on ecosystem.rst

### PR DESCRIPTION
**Pull request by data-RanDan**
Fixed capitalization on doc/source/ecosystem.rst

### CODE REVIEW

**Comment by mroeschke** [comment]
Thanks but `pandas` is intentionally lowercase and was recently changed in https://github.com/pandas-dev/pandas/pull/36845

If further interested in contributing, please check out issues labeled with `good first issue`

**Comment by data-RanDan** [comment]
Where do you think i got it from?
 #32550
./scripts/validate_rst_title_capitalization.py

doc/source/ecosystem.rst:83:Heading capitalization formatted incorrectly.

**Comment by mroeschke** [comment]
Looks like the `./scripts/validate_rst_title_capitalization.py` has not been modified to ignore capitalization of `pandas`. Would you like to submit a PR to modify that script?

**Comment by data-RanDan** [comment]
Just to make sure,
both Pandas and pandas is fine?

**Comment by mroeschke** [comment]
It should always be referenced as lowercase `pandas`

**Pull request closed without merging**
