### PR TITLE
CLN : Removed unnecessary numba-compat code

### PR DESCRIPTION
**Pull request by PrathumP**
- [x] closes ##50392 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
can you run the code checks please?

**Comment by PrathumP** [comment]
Yes, sure

**Comment by PrathumP** [comment]
I ran tests fro this individual file and everything seems fine.

Screenshot_2023-05-28_17-10-26

Then, I ran code checks for all files and it also seems to be working fine.

Screenshot_2023-06-30_20-46-37

**Comment by MarcoGorelli** [comment]
it fails in CI, so I guess you didn't commit?

**Comment by PrathumP** [comment]
It was a insignificant change, it should pass CI now ig.

**Review by MarcoGorelli — APPROVED** [review]
thanks @PrathumP

**Pull request merged**
