### PR TITLE
MAINT: Make pandasSQL_builder private

### PR DESCRIPTION
**Pull request by gfyoung**
Per discussion with @jorisvandenbossche <a href="https://github.com/pydata/pandas/pull/13611#discussion_r71048508">here</a>.

### CODE REVIEW

**Comment by gfyoung** [comment]
@sinhrks , @jorisvandenbossche : any updates on this?

**Comment by gfyoung** [comment]
@sinhrks , @jorisvandenbossche : any updates on this?

**Comment by gfyoung** [comment]
@sinhrks , @jorisvandenbossche : any updates on this?  This seems relatively trivial to merge.

**Comment by gfyoung** [comment]
@sinhrks , @jorisvandenbossche , @jreback : any updates on this?  Seems relatively trivial to merge.

**Comment by jreback** [comment]
lgtm. @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
Sorry for the delay. 
I did a quick search on github, and few people did actually use this in their code (and that were not copies of pandas), so not sure this is worth to change. 
I meant we should have made it internal when it was added in 0.14, but not sure if it is worth to change.

**Comment by gfyoung** [comment]
Ah, that's a good point.  If the intention was internal, but people are actually using this function for their own `pandas` engines, I wonder if we should even make internal at all.

**Comment by jorisvandenbossche** [comment]
Yep, then we just let it be :-)

**Comment by jorisvandenbossche** [comment]
Sorry for my inclarity triggering you to action

**Comment by gfyoung** [comment]
No worries.  Good that we at least investigated.

**Pull request closed without merging**
