### PR TITLE
REF: Categorical.fillna match patterns in other methods

### PR DESCRIPTION
**Pull request by jbrockmendel**
Also:

- always return a copy even if there is nothing to fill
- validate the fill_value even if there is nothing to fill

### CODE REVIEW

**Review by WillAyd — COMMENTED** [review]
I am OK with this in the name of consistency. Can you add a whatsnew?

**Comment by jreback** [comment]
what is the visible user change here?

**Comment by jbrockmendel** [comment]
> what is the visible user change here?

A couple of exception messages changed (see changed tests), always returning a copy even if a no-op, always validate fill value even if no-op (see OP, xref #36466)

**Comment by jbrockmendel** [comment]
Possibly closes #19705 cc @TomAugspurger

**Comment by jbrockmendel** [comment]
whatsnew added + green

**Review by TomAugspurger — APPROVED** [review]

**Comment by jreback** [comment]
nice code deletion!

**Pull request merged**
