### PR TITLE
CLN: replaced Appender with doc

### PR DESCRIPTION
**Pull request by smartvinnetou**
- [x] ref #31942
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] replaced the Appender/Substitute decorators with doc

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Can you fix merge conflicts?

**Comment by WillAyd** [comment]
Can you fix up merge conflict again? If so can merge

**Comment by WillAyd** [comment]
@smartvinnetou can you fix conflicts?

**Comment by smartvinnetou** [comment]
Will do.

**Comment by jbrockmendel** [comment]
one more rebase pls

**Comment by smartvinnetou** [comment]
Rebase done. Still some glitches in the doctests. Will keep fixing.

**Comment by jreback** [comment]
thanks @smartvinnetou  keep em coming

**Pull request merged**
