### PR TITLE
CI: Remove redundant sdist workflow

### PR DESCRIPTION
**Pull request by mroeschke**
AFAICT: The sdist workflow was essentially similar as the `build_sdist` job in the wheels workflow except it didn't test the sdist cc @lithomas1

### CODE REVIEW

**Comment by lithomas1** [comment]
I think the reason that I didn't remove this yet was because we don't have a way of testing that the oldest supported numpy works (on all Python versions).

Not sure if this testing is too relevant now though.

**Comment by mroeschke** [comment]
It seems the workflow never really _tested_ pandas with the lowest oldest supported, just that `pd.show_versions` worked. It doesn't look like we have any runtime checks for this either.

But as long as we have `oldest-supported-numpy` shouldn't we be okay?

**Review by datapythonista — APPROVED** [review]
This seems reasonable.

Not sure the context when the job was created, but testing that pandas can be imported when installed with an sdist with an old numpy installed seems redundant and somehow cumbersome, given that we run all the test suite with the old numpy and we test the sdist.

Somehow unrelated. Would it make sense to run the tests on the same jobs we build the wheels? From the release point of view, feels like it'd make sense to test on the CI what's really being released.

Also, how do you feel about copying the recipe from feedstock to this repo, and having a CI job to build the conda package? That would be nice to avoid having to update the recipe during the release process.

**Comment by mroeschke** [comment]
> Somehow unrelated. Would it make sense to run the tests on the same jobs we build the wheels? From the release point of view, feels like it'd make sense to test on the CI what's really being released.

I would be +1 to this. It would be great to the have the CI more representative of testing pandas from what users install. We should probably still have a job that tests that pandas can be installed from source and pass the test suite.

> Also, how do you feel about copying the recipe from feedstock to this repo, and having a CI job to build the conda package? That would be nice to avoid having to update the recipe during the release process.

I guess I wouldn't be opposed to this, but IIRC the conda forge build is still triggered from the Github release being created?

**Pull request merged**
