### PR TITLE
DOC: Fixing EX01 - Added more examples

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Towards https://github.com/pandas-dev/pandas/issues/37875

### CODE REVIEW

**Review by rhshadrach — APPROVED** [review]
lgtm

**Review by rhshadrach — CHANGES_REQUESTED** [review]
Just some docstring validation issues: https://github.com/pandas-dev/pandas/actions/runs/5191391678/jobs/9359155808?pr=53540#step:9:36

**Comment by DeaMariaLeon** [comment]
I think that the new failing test is not related to this.

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
