### PR TITLE
BUG: item_cache not cleared on DataFrame.values

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
any perf impact? (i would actually expect some small regressions)

**Comment by jbrockmendel** [comment]
```
In [1]: import pandas as pd                                                                                                                                                                                        


In [2]:                                                                                                                                                                                                            

In [2]: df = pd.DataFrame([1, 2])                                                                                                                                                                                  

In [3]: %timeit df.values
2.25 µs ± 42.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)  # <-- master
3.82 µs ± 106 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)  # <-- PR
```

**Comment by jreback** [comment]
hmm, do we have any to_numpy() benchmarks? just to see not blocking this PR

**Comment by jbrockmendel** [comment]
> do we have any to_numpy() benchmarks

Looks like we do not

**Comment by jreback** [comment]
> > do we have any to_numpy() benchmarks
> 
> Looks like we do not

kk happy to merge and can create issue for benchmarks (as a good first - people like to do those)

**Comment by jbrockmendel** [comment]
issue opened

**Comment by jreback** [comment]
thanks

**Comment by TomAugspurger** [comment]
@jbrockmendel caused a 100x slowdown in replace.Convert.time_replace (https://pandas.pydata.org/speed/pandas/index.html#replace.Convert.time_replace?p-constructor=%27Series%27&p-replace_data=%27Timestamp%27&commits=dbfbef7eaea7f23a42d9a65344b5745fc055f5b4). Is that expected?

**Comment by jbrockmendel** [comment]
>  caused a 100x slowdown in replace.Convert.time_replace  [...] Is that expected?

I'd expect something closer to the 70% slowdown we see in `df.values`.  100x is surprising.

**Comment by TomAugspurger** [comment]
Opened https://github.com/pandas-dev/pandas/issues/35053 to track this.

**Comment by B417037** [comment]
Hey I am new to open source. Can I take up this issue?

**Comment by jorisvandenbossche** [comment]
@B417037 this is a merged PR, not an issue to take up. Have a look at https://github.com/pandas-dev/pandas/labels/good%20first%20issue

**Pull request merged**
