### PR TITLE
On traces of #33982

### PR DESCRIPTION
**Pull request by kuraga**
To pay attention on https://github.com/pandas-dev/pandas/pull/33982#issuecomment-643246205. Sorry, I don't know another way now.

/cc @mproszewska , @jreback

Thanks.

### CODE REVIEW

**Comment by WillAyd** [comment]
Can you clarify what this is for? I didn't understand from the comment linked

**Comment by kuraga** [comment]
@WillAyd , #33982 introduces `index_col` argument in `_is_potential_multi_index`:
```diff
- def _is_potential_multi_index(columns):
+ def _is_potential_multi_index(
+     columns, index_col: Optional[Union[bool, Sequence[int]]] = None
+ ):
```

There are two usage of this function:
1. https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/parsers.py#L1526
2. https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/parsers.py#L1547

#33982 modifies first call only. In that comment I ask if it is correct.

**Comment by alimcmaster1** [comment]
@kuraga - might be worth adding a test to highlight what functionality this changes?

**Comment by WillAyd** [comment]
Closing as its not clear what this is or solves; if you can clarify further and add a test case can certainly reopen

**Comment by kuraga** [comment]
@WillAyd , it solves nothing. It demonstrates https://github.com/pandas-dev/pandas/pull/33982

**Comment by jreback** [comment]
@kuraga ia this actually a bug?

iow can u hit the line of code u added?

**Comment by kuraga** [comment]
> #33982 introduces `index_col` argument in `_is_potential_multi_index`:
> 
> ```diff
> - def _is_potential_multi_index(columns):
> + def _is_potential_multi_index(
> +     columns, index_col: Optional[Union[bool, Sequence[int]]] = None
> + ):
> ```
> 
> There are two usages of this function in Pandas:
> 
> 1. https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/parsers.py#L1526
> 2. https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/parsers.py#L1547
> 
> #33982 modifies first call only. In that comment I ask if it is correct.

It's correct: we're constructing (multi-)index ourselves there, so we don't have the index column(s)).

**Pull request closed without merging**
