### PR TITLE
DOC: regenerate CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by shoyer**
This is an alternative to #9796.

I simply did a couple of changes to the restructuredtext source so it generates cleaner markdown. The main thing was making the categories not quite so nested. (Was that [heavy nesting](http://pandas-docs.github.io/pandas-docs-travis/contributing.html#committing-your-code) intentional?) I think pandoc was running out of header styles or something like that.

cc @rockg @jreback @jorisvandenbossche

### CODE REVIEW

**Comment by jreback** [comment]
lgtm

**Comment by rockg** [comment]
What I had in mind for this actually just having a link to the pandas documentation in contributing.md.  The whole point of this was to have all the documentation in one place so they are never disconnected.

**Comment by jreback** [comment]
GitHub seems to want to have a CONTRUBUTING.md file to show to the user.
but I think we all agree it's better in the docs
not sure how we can have only a link (well we could but it's not as nice as a rendered markdown) in the CONTRIBUTING.md file

**Comment by rockg** [comment]
I was thinking something like the below on the page:

Thank you for contributing to pandas.  Please see our guidelines [here](http://pandas-docs.github.io/pandas-docs-travis/contributing.html#contributing-to-the-code-base)

**Comment by jorisvandenbossche** [comment]
I also think having things not duplicated would be better. But I think it should be possible to 'include' the version in the docs into the CONTRIBUTING one with `..inlcude::`. Or does the CONTRIBUTING has to be markdown?

Otherwise I would also go for a link to the developers docs, but maybe with a kind of shorter 'summary'

**Comment by shoyer** [comment]
Unfortunately a CONTRIBUTING.rst files doesn't work.

I'm not opposed to making this file just a link, but it also seems safe enough to just generate it automatically with pandoc.... that seems like it will be straightforward enough to keep up to date.

**Comment by jreback** [comment]
I agree

let's just out the pandoc command in the wiki somewhere

**Comment by jorisvandenbossche** [comment]
ok!

**Comment by shoyer** [comment]
Just put the instructions in the wiki, see the bottom here: https://github.com/pydata/pandas/wiki

**Comment by rockg** [comment]
To answer your question, the heavy nesting was intentional (and I still think we should find a way to do it in CONTRIBUTING).  Everything was setup to be sequential so after you checkout, then you either work on the docs or the code and then you commit.  So I think both the contributing to docs/code should be on same level as those two other things (and the rest of the workflow).

Maybe what we should be doing here is to pull out the `Contributing to the Code Base` into a separate .rst file and then only convert that subfile into contributing.md.  I think that is really the relevant section for ensuring a pull request is following the project's guidelines.  I can play around with that.

**Comment by shoyer** [comment]
Oh, OK :). In that case, my mistake -- please feel free to revert. I'm guessing you might have mixed up subsection styles (e.g., `~~~~~~~` vs `""""""""""`) -- it looked like almost everything converted properly except for one section title.

**Pull request merged**
