### PR TITLE
Style source

### PR DESCRIPTION
**Pull request by joekane3**
I am attempting to style a column based on another column's data, for example:

``` python
import pandas as pd

now = pd.datetime.now()
rng = now + pd.timedelta_range("1D","10D",freq='D')

df = pd.DataFrame(rng,columns=["ExactDate"])

df['Display Date'] = df['ExactDate'].dt.strftime("%m-%Y")

style = df.style.bar(subset='Display Date', source = rng)

html = style.render()

print html
```

Gives: 
image

### CODE REVIEW

**Comment by joekane3** [comment]
Thread about this: #11610

**Comment by TomAugspurger** [comment]
I'd rather not complicate the signature of `.bar` (and presumably every style function, why limit this to just bar?) with a `source` argument.

I'm strapped for time right now so I can't write up an example, but what you want can be accomplished through `Styler.apply`. I'll check back in in a couple weeks.

**Comment by joekane3** [comment]
@TomAugspurger , sorry I should have answered before, I took your advice and wrote a custom function to perform this, and used the apply method. it works great, I just needed a push in the right direction, thanks. The feature itself is very useful, kudos.

I agree that my suggested change would convolute the code and would indeed need to be applied to all styling functions. One day I'll make a useful and worthy PR!

**Comment by joekane3** [comment]
for other that may want the  example:


```python
def _table_bar(s, color, vmin = 0 , vmax = 100, c_source = None):
        if c_source is not None:
            s = c_source

        normed = vmin +((vmax-vmin) * (s - s.min()) / (s.max() - s.min()))
        attrs = 'width: 10em; height: 80%;'\
            'background: linear-gradient(90deg,'\
            '{c} {w}%, transparent 0%)'
        return [attrs.format(c=color, w=x) for x in normed]
```

is as ```Styler.bar``` but with a c_source argument, called by:

```python
df.style.apply(_table_bar, color="#D55E00", subset='Display Date',  c_source = df['ExactDate'].values)
```

achieving the above desired:

image

**Comment by TomAugspurger** [comment]
Glad to hear you worked it out!

We might be able to refactor the color handling code and include that as part of the public API.

-Tom

**Pull request closed without merging**
