### PR TITLE
CLN: plotting cleanups for groupby plotting

### PR DESCRIPTION
**Pull request by sinhrks**
Related to #8018. Because it touches lots of codes, I've split some cleanups required for #8018 which does NOT changes current functionality.

### CODE REVIEW

**Comment by jreback** [comment]
@sinhrks status?

**Comment by sinhrks** [comment]
@TomAugspurger Can you take a look? It's nice if #8018 can be included in v0.17.

**Comment by jreback** [comment]
this lgtm. so when you guys are ok, pls merge.

**Comment by sinhrks** [comment]
Let me merge this if there is no objections in this weekend.

**Pull request merged**
