### PR TITLE
PERF: column_arrays

### PR DESCRIPTION
**Pull request by jbrockmendel**
Shaves a couple percent off of time_to_json_wide asv

Reprises #42824.

### CODE REVIEW

**Comment by jreback** [comment]
hmm just a couple of percent?

**Comment by jbrockmendel** [comment]
> hmm just a couple of percent?

I'm seeing 13.5% locally

```
from asv_bench.benchmarks.io.json import *

self = ToJSONWide()
self.setup("columns", "df_td_int_ts")

%timeit self.time_to_json_wide("columns", "df_td_int_ts")
82.4 ms ± 1.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)  # <- master
71.3 ms ± 1.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)  # <- PR
```

**Comment by jreback** [comment]
just converned this is too specialy casey for json. but not a big deal.

**Comment by jbrockmendel** [comment]
Column_arrays is already only for json

**Comment by jbrockmendel** [comment]
gentle ping; this is the last of the asv-identified perf PRs

**Review by jreback — APPROVED** [review]

**Pull request merged**
