### PR TITLE
CI: Fix error when creating postgresql db

### LINKED ISSUE #29643: CI: postgresql job failing
e.g. https://travis-ci.org/pandas-dev/pandas/jobs/612501204

```
installing dbs

psql: could not connect to server: No such file or directory

	Is the server running locally and accepting

	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

The command "ci/setup_env.sh" failed and exited with 2 during .

Your build has been stopped.
```

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #29643

Not sure if this makes sense, but let's try if this is the problem.

### CODE REVIEW

**Comment by datapythonista** [comment]
Looks like this change adds this at the beginning of the log:
```
$ travis_setup_postgresql
Starting PostgreSQL v9.2
sudo service postgresql start 9.2
$ sudo service mysql start
start: Job is already running: mysql
```
But still the same error. I guess we'll have to add traces during the build to see if the postgres service is running, and what are the server, port...

**Comment by jbrockmendel** [comment]
maybe if we used 9.5 instead of 9.2?  the log has a bit about shutting down 9.5, then starting 9.4 then stopping 9.4, then starting 9.3...

**Comment by datapythonista** [comment]
Didn't see that, let's see if this works. I'm going to sleep now, feel free to push here if you want to try more things.

**Comment by alimcmaster1** [comment]
Maybe someone from @travis-ci can help us here?

**Comment by datapythonista** [comment]
I'm going to move the failing build to GitHub actions. That was more or less planned (#28545), and looks like shouldn't be difficult.

**Comment by jreback** [comment]
let’s just disable the server for now
until it can be diagnosed

**Comment by datapythonista** [comment]
> let’s just disable the server for now

Not sure what do you mean. Disable the failing build?

**Comment by datapythonista** [comment]
I think the problem is that something in https://github.com/pandas-dev/pandas/blob/master/ci/deps/travis-36-cov.yaml is making conda install postgres, see:
```
postgresql                11.2                 h20c2e04_0
```
I didn't see that there are two travis builds where the db is correctly created, and I think this is the main difference. In the working builds postgres is not installed.

Let's see if uninstalling coda fixes the error.

**Comment by datapythonista** [comment]
@pandas-dev/pandas-core this fixes the problem with the CI (the postgresql error)

**Comment by jreback** [comment]
great merge one green

**Pull request merged**
