### PR TITLE
Revert "Deprecated casting an object-dtype index of datetime objects to DatetimeIndex in the Series constructor (23598)"

### LINKED ISSUE #38182: BUG/DEPR: Fix unwanted warnings from the Series(Index[datetime objects]) deprecation
See https://github.com/pandas-dev/pandas/pull/36697#discussion_r497786546 and https://github.com/pandas-dev/pandas/pull/37193#issuecomment-715228272

Due to the `Index.is_all_dates` + `Series(Index[datetime object])` deprecation warnings, there are several code examples that are not using this attribute or constructor method directly, that still cause this warning (from internal pandas code, without direct control over this by the user). 

Users should not see unrelated deprecation warnings from the internals of pandas that they can't do anything about themselves, so IMO we should either fix those for 1.2, or delay the deprecationg for 1.3

### PR DESCRIPTION
**Pull request by simonjayhawkins**
This **partially** reverts commit 90a61350b1be7a200238212bd8d118a25a4d3d95.

- [ ] closes #38182
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
fine by me. cc @jbrockmendel

**Comment by jbrockmendel** [comment]
If the idea is to un-revert following 1.2, sure.

**Comment by simonjayhawkins** [comment]
> If the idea is to un-revert following 1.2, sure.

from https://github.com/pandas-dev/pandas/issues/38182#issue-753330794

> Users should not see unrelated deprecation warnings from the internals of pandas that they can't do anything about themselves, so IMO we should either fix those for 1.2, or delay the deprecationg for 1.3

not fixed, so delaying to 1.3

**Comment by jreback** [comment]
ok great, thanks @simonjayhawkins 

yeah we can unrevert this for 1.3, but i think ok to release once this hits.

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
