### PR TITLE
BUG: Ensure consistent kwarg only restriction on df.any and df.all

### LINKED ISSUE #57087: BUG:  `DataFrame.any()` inconsistent with other methods
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'x':[1,2,3],'y':[1,2,3]})

df.all(0) # Positioned arg for axis is allowed.
df.any(0) # Positioned arg for axis not allowed.
```

### Issue Description

The `any` method has a keyword only restriction for its arguments.  The `all` method doesn't.

### Expected Behavior

`any` and `all` should be consistent. To my POV `any` seems to be doing the right thing, while `all` (and other similar methods without a restriction and default arguments only, `min`, `max` etc) seems to be going against what Pandas has been moving toward where all arguments with defaults tend to fall on the keyword only side of the argument list.

Which is correct? 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : b5a963c872748801faa7ff67b8d766f7043bb1c1
python                : 3.11.7.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.5.13-1rodete1-amd64
Version               : #1 SMP PREEMPT_DYNAMIC Debian 6.5.13-1rodete1 (2023-12-06)
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 3.0.0.dev0+172.gb5a963c872
numpy                 : 1.26.3
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 65.5.0
pip                   : 23.3.2
Cython                : 3.0.5
pytest                : 7.4.4
hypothesis            : 6.97.0
sphinx                : 7.2.6
blosc                 : None
feather               : None
xlsxwriter            : 3.1.9
lxml.etree            : 5.1.0
html5lib              : 1.1
pymysql               : 1.4.6
psycopg2              : 2.9.9
jinja2                : 3.1.3
IPython               : 8.20.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : 2023.10.1
fsspec                : 2023.12.2
gcsfs                 : 2023.12.2post1
matplotlib            : 3.8.2
numba                 : 0.58.1
numexpr               : 2.9.0
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 15.0.0
pyreadstat            : 1.2.6
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 2023.12.2
scipy                 : 1.12.0
sqlalchemy            : 2.0.25
tables                : 3.9.2
tabulate              : 0.9.0
xarray                : 2024.1.1
xlrd                  : 2.0.1
zstandard             : 0.22.0
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

### PR DESCRIPTION
**Pull request by aidoskanapyanov**
- [x] closes #57087 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
These would need deprecating first cc @twoertwein

**Comment by aidoskanapyanov** [comment]
Oh, my bad, okay 👌
Gotta learn about depreciating

**Comment by twoertwein** [comment]
> Gotta learn about deprecating

Luckily, it is quite simple:

1) you decorate the method with this:
`@deprecate_nonkeyword_arguments(version="3.0", allowed_args=["self"], name="all")`
where `name` is the name of the method.

2) Add a whatsnew entry

3) Ideally, have a test (not sure whether that is needed)

These deprecations apply to both DataFrame and Series for at least the following methods: any, all, min, max, mean, median, sum, prod, std, var, sem, skew, kurt.


I had [similar changes in this PR](https://github.com/pandas-dev/pandas/pull/56739/commits/9de4f705f4ea170ae5aca64fddc704ef51db4905#diff-421998af5fe0fbc54b35773ce9b6289cae3e8ae607f81783af04ebf1fbcaf077) but removed them from the PR to keep it easier to merge. Feel free to have a look at that PR to see how to adjust some of the tests (some of them will fail when you deprecate positional arguments).

**Comment by aidoskanapyanov** [comment]
> Luckily, it is quite simple:

Thank you for explaining, this is super helpful! 👍

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
