### PR TITLE
TST: improve readability using dedent in test_to_string.py

### PR DESCRIPTION
**Pull request by ivanovmg**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Improve readability of expected outputs using dedent in ``pandas/tests/io/formats/test_to_string.py``

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]
Thanks @ivanovmg lgtm pending green

**Comment by ivanovmg** [comment]
One travis job failed because of its internal error. Can you re-start?
Windows py38_np18 error seems irrelevant.

**Review by dsaxton — APPROVED** [review]
:+1:

**Comment by jreback** [comment]
thanks @ivanovmg keep em coming

**Pull request merged**
