### PR TITLE
BUG: read_excel not forward filling index columns when no names are given

### LINKED ISSUE #47487: BUG: read_excel() doesn't handle Multiindex correctly
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# Could not provide a copy-pastable Reproducible Example because of empty line bug in ".to_excel" https://github.com/pandas-dev/pandas/issues/27772
# Please use either Screenshot or attached Excel-File.

import pandas as pd

df = pd.read_excel('sample.xlsx', index_col=[0, 1, 2], header=[0, 1, 2])

print(df.index)

MultiIndex([('A', 'AA', 'AAA'),
            (nan, 'BB', 'BBB'),
            (nan, 'CC', 'CCC'),
            (nan, 'DD', 'DDD'),
            (nan, 'EE', 'EEE')],
           )
```

### Issue Description

When importing a Excel-XSLX File ([sample.xlsx](https://github.com/pandas-dev/pandas/files/8968355/sample.xlsx)) into pandas with .read_excel() the Multiindex is not handled properly.

Instead of copying the value of the first Index-Column-Cell into the Cells beneath it, it is pasting "NAN"s there. 
This also doesn't change when merging the area to a merged cell.

Example Data in Excel/Calc:
pandas_bug

### Expected Behavior

It should copy the first Value in the Index-Column into the cells beneath them:

```python
    print(df.index)

    MultiIndex([('A', 'AA', 'AAA'),
                ('A', 'BB', 'BBB'),
                ('A', 'CC', 'CCC'),
                ('A', 'DD', 'DDD'),
                ('A', 'EE', 'EEE')],
               )
```

When commenting out the changes made with [Issue:34673](https://github.com/pandas-dev/pandas/issues/34673) it is working correctly:
https://github.com/pandas-dev/pandas/blob/b022a3bea7227709052b2e3c2176833735112b2e/pandas/io/excel/_base.py#L804-L808

### Installed Versions

<details>
'1.4.2'
</details>

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #47487 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

The prevoious has_index_name routine was too simple. This version is aligned with the TextReader version that is used a few lines below

### CODE REVIEW

**Comment by mroeschke** [comment]
```
pandas/io/excel/_base.py:793: error: List item 0 has incompatible type "Union[int, Sequence[int]]"; expected "int"  [list-item]
pandas/io/excel/_base.py:797: error: Argument 1 to "len" has incompatible type "Union[int, Sequence[int], None]"; expected "Sized"  [arg-type]
pandas/io/excel/_base.py:798: error: Argument 1 to "len" has incompatible type "Union[int, Sequence[int], None]"; expected "Sized"  [arg-type]
Found 3 errors in 1 file (checked 1391 source files)
```

**Comment by phofl** [comment]
Thx, fixed

**Comment by jreback** [comment]
thanks @phofl

**Comment by kuraga** [comment]
@phofl, @jreback,
should we document such behavior (taking #38517 into account, too) in `read_excel`?

And, more: do `read_csv`/etc. do the same?

**Pull request merged**
