### PR TITLE
Explicitly define cmp_pandas_datetimestruct

### PR DESCRIPTION
**Pull request by jbrockmendel**
Fixes build warning
```
pandas/_libs/tslib.c:78967:17: warning: implicit declaration of function 'cmp_pandas_datetimestruct' is invalid in C99 [-Wimplicit-function-declaration]
```

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by jreback** [comment]
this is causing some more warnings have a look at the travis logs

**Comment by jbrockmendel** [comment]
Are you referring to 

```
In file included from pandas/_libs/period.c:250:0:
pandas/_libs/src/datetime/np_datetime.h:106:5: note: expected ‘struct pandas_datetimestruct *’ but argument is of type ‘const struct pandas_datetimestruct *’
 int cmp_pandas_datetimestruct(pandas_datetimestruct *a,
     ^
pandas/_libs/period.c:20547:3: warning: passing argument 2 of ‘cmp_pandas_datetimestruct’ discards ‘const’ qualifier from pointer target type [enabled by default]
```

?  AFAICT there's not much to be done about that unless we want to un-declare the `const` in np_datetime.c.

**Comment by jreback** [comment]
so how does this PR help then?

**Comment by jreback** [comment]
```
the warning currently s

pandas/_libs/tslib.c:81135:3: warning: implicit declaration of function ‘cmp_pandas_datetimestruct’ [-Wimplicit-function-declaration]
   __pyx_t_2 = ((cmp_pandas_datetimestruct(__pyx_v_dts, (&_NS_MIN_DTS)) == -1L) != 0);
   ^
pandas/_libs/tslib.c: In function ‘__pyx_pymod_exec_tslib’:
```

**Comment by jreback** [comment]
you need to declar ``const *`` the structures in .h and change in .c

**Comment by jreback** [comment]
thanks!

**Pull request merged**
