### PR TITLE
TST: Make assert_extension_array_equal behavior consistent

### LINKED ISSUE #23709: TST: assert_extension_array_equal is inconsistent in how precision is handled
#### Code Sample, a copy-pastable example if possible

Setup:
```python
In [2]: values1 = np.array([-0.17387645482451206, 0.3414148016424936])
   ...: values2 = np.array([-0.17387645482451206, 0.3414148016424937])

In [3]: df1 = pd.DataFrame({'a': values1, 'b': ['foo', 'bar']})
   ...: df2 = pd.DataFrame({'a': values2, 'b': ['foo', 'bar']})
```

By default, `assert_frame_equal` will not fail on a difference in precision that's as slight as what's above, and will only detect the difference if `check_exact=True` is passed:
```python
In [4]: tm.assert_frame_equal(df1, df2)

In [5]: tm.assert_frame_equal(df1, df2, check_exact=True)
---------------------------------------------------------------------------
AssertionError: DataFrame.iloc[:, 0] are different

DataFrame.iloc[:, 0] values are different (50.0 %)
[left]:  [-0.173876454825, 0.341414801642]
[right]: [-0.173876454825, 0.341414801642]
```

However, when extension arrays are introduced, which causes `assert_frame_equal` to dispatch to `assert_extension_array_equal`, this difference in precision is detected by default:

```python
In [6]: tm.assert_frame_equal(df1.to_sparse(), df2.to_sparse())
---------------------------------------------------------------------------
AssertionError: numpy array are different

numpy array values are different (50.0 %)
[left]:  [-0.17387645482451206, 0.3414148016424936]
[right]: [-0.17387645482451206, 0.3414148016424937]
```
#### Proposed Solution
Looking at the source code for `assert_extension_array_equal`, it does not accept any of the keyword arguments that the `assert_*_equal` functions take in regards to precision:

https://github.com/pandas-dev/pandas/blob/e413c491e090274aad78489cc17a2e29cbd8e269/pandas/util/testing.py#L1192-L1198

I'd like to add `check_exact`, `check_less_precise`, and `check_dtype` parameters to `assert_extension_array_equal` with the same defaults as the other `assert_*_equal` functions.

Note that this would resolve #23605, which is the source of my example.

cc @TomAugspurger : Thoughts on this? Is there a reason we'd want `check_exact` style checking by default?

### PR DESCRIPTION
**Pull request by jschendel**
- [X] closes #23709
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Doesn't seem like a whatsnew entry is needed for this, but can add one if need be.

This should also address #23605; I don't want to autoclose it, as I'd rather wait to confirm that the nightly build passes after this is merged.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Seems like a precision issue on the py2 test: https://travis-ci.org/pandas-dev/pandas/jobs/457327081#L2551

**Review by TomAugspurger — APPROVED** [review]
Merging later today.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
@jschendel thanks!

**Comment by jorisvandenbossche** [comment]
Should #23605 also be closed?

**Comment by jschendel** [comment]
> Should #23605 also be closed?

Yes, will close that issue manually.  The latest pandas-wheels build was successful, which looks to include this PR based on the time at which it was started: https://travis-ci.org/MacPython/pandas-wheels/builds/457775113

**Comment by jreback** [comment]
yep looks like the 32 bit are finally fixed thanks!

**Pull request merged**
