### PR TITLE
Backport PR #40768 on branch 1.2.x (DOC/CI: temp pin of decorator (IPython dependency))

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #40768: DOC/CI: temp pin of decorator (IPython dependency)

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
this doesn't need to be backported, as it's already reverted on master

**Comment by simonjayhawkins** [comment]
see https://github.com/pandas-dev/pandas/pull/40801#issuecomment-814224625 although not sure if this will fix. currently recreating this env locally

**Comment by jorisvandenbossche** [comment]
That are different warnings than addressed in this PR. Comparing the two envs, another difference is the docutils version. They had a new release a few days ago, and since that broke a bunch of stuff in sphinx, I pinned the docutils version in the pydata-sphinx-theme. But the 1.2.x branch is still using an older version of the theme (not having this pin), so it might be https://github.com/pandas-dev/pandas/pull/40407 we need to backport.

**Comment by simonjayhawkins** [comment]
Thanks @jorisvandenbossche . yes this doesn't fix. will try  #40407 instead.

**Pull request closed without merging**
