### PR TITLE
DEP: Bump min version of dateutil to 2.7.3

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [x] xref https://github.com/pandas-dev/pandas/pull/32465#discussion_r404449469
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

---

Not sure where to put the note in the "whatsnew"

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @MomIsBestFriend 

Can you have a look at the CI and see what's wrong please?

**Comment by TomAugspurger** [comment]
In 1.0, we had dependency bumps under the "Backwards incompatible" section. https://pandas.pydata.org/docs/whatsnew/v1.0.0.html#increased-minimum-versions-for-dependencies. We can do that again, or make a new top-level section.

**Comment by simonjayhawkins** [comment]
> In 1.0, we had dependency bumps under the "Backwards incompatible" section.

so, by definition, this is an breaking change? is this necessary or can it keep till 2.0?

**Comment by MomIsBestFriend** [comment]
> > In 1.0, we had dependency bumps under the "Backwards incompatible" section.
> 
> so, by definition, this is an breaking change? is this necessary or can it keep till 2.0?

Haven't thought of that.

---

I'll push more commits when someone from the pandas-core team will tell me if this PR is relevant :)

**Comment by TomAugspurger** [comment]
I wouldn't consider this an API breaking change. That's just the header it went under in older versions.

**Comment by MomIsBestFriend** [comment]
> Can you have a look at the CI and see what's wrong please?

@datapythonista I have found out that there is a bug in 2.7.0 that was fixed in 2.7.3 when parsing a ```NaN``` (ref https://github.com/dateutil/dateutil/issues/662)

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by jreback** [comment]
thanks @MomIsBestFriend 

as a followon can you see if we can change code for anything that needed < 2.7.3 (i don't know if there is anything, but its possible).

**Pull request merged**
