### PR TITLE
DOC fix the incorrect doc style in 1.2.1

### LINKED ISSUE #39290: DOC: fix the incorrect doc style in 1.2.1
@jorisvandenbossche pls following up and fix the docs

it's not a style issue rather this is completely inconsistent with the current docs 

we NEVER use the style - always ipython docs style

__Originally posted by @jreback in https://github.com/pandas-dev/pandas/pull/39239#issuecomment-763475054__

### PR DESCRIPTION
**Pull request by debnathshoham**
- [x] closes #39290
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
hmm, this looks fine, IIRC did we somehow change the whatsnew way back when?

cc @simonjayhawkins @datapythonista

**Review by datapythonista — APPROVED** [review]
I think we used to use the ipython directive (the one automatically running the code, not the ipython format) in the whatsnew. But code was failing often as pandas evolves, since it is run with the latest pandas, and not the pandas version of the whatsnew. So, it was changed to not runnable examples. Based on the issue description, looks like we had to change them to the non-runnable ipython format, and we changed it to the standard python format.

This seems fine. Not sure I understand the resetting of the numbering (the `1` in `In [1]`...), I think it used to just increment for a whole file. But this seems fine to me, and more maintainable. Thanks for the work on this @debnathshoham

**Comment by jreback** [comment]
thanks @debnathshoham

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
