### PR TITLE
DOC: also redirect old whatsnew url

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
The whatsnew was already splitted longer time ago, but I think we can also add a redirect for the main release page.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
cc @TomAugspurger @datapythonista

**Comment by datapythonista** [comment]
That makes sense. We just need to add `release,whatsnew/index` to a new section in `doc/redirects.csv`.

**Comment by jorisvandenbossche** [comment]
Ah, yes, that one as well. Will add.

**Comment by datapythonista** [comment]
leave it for a beginner, surely someone if happy to take care of this :)

**Review by TomAugspurger — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Too late, and I am doing this because we want to release.

**Comment by datapythonista** [comment]
oh, I thought this was a ticket, not a PR, was commenting from the phone :)

**Comment by datapythonista** [comment]
When are you planning to release? Will try to work on the redirects for the API today.

Are we finally happy with `api/generated/`, or should I move them somewhere else?

Also, I think it'd be great to have #24890 in 0.24, do you mind taking a look?

**Pull request merged**
