### PR TITLE
WEB: Update to `jupyterlite==0.1.0b12`

### PR DESCRIPTION
**Pull request by jtpio**
Update to the latest `jupyterlite` release to bring some more bug fixes and improvements.

This should help fix an issue with the current repl failing to load

- [x] ~closes #xxxx (Replace xxxx with the Github issue number)~
- [x] ~[Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature~
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] ~Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.~
- [x] ~Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.~

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @jorisvandenbossche for reporting the issue today.

I tried the built archive locally downloaded from https://github.com/pandas-dev/pandas/actions/runs/2964426541, and it seems to be working well with the update:

image

**Review by datapythonista — APPROVED** [review]
Thanks @jtpio, lgtm.

Btw, would it be easy to show a spinner or even the word `Loading...` while the webassembly binary is being downloaded and loaded? I think it'd make the user experience much nicer, since this can take several seconds to be available.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jtpio. Agreed, a loading indicator would be a nicer user experience (to set expectation of the activity in the background)

**Comment by jtpio** [comment]
Thanks all.

> a loading indicator

Yes that's a good point and it is currently tracked this in https://github.com/jupyterlite/jupyterlite/issues/619, which could be applied to all applications (lab, notebook, repl).

**Pull request merged**
