### PR TITLE
Fixed rendering of ticks in error bars

### LINKED ISSUE #17467: Error bars not rendered correctly
#### Code Sample, a copy-pastable example if possible

From the `/doc/source/visualization.rst`:

```python
import pandas as pd
import matplotlib.pyplot as plt

# Generate the data
ix3 = pd.MultiIndex.from_arrays([['a', 'a', 'a', 'a', 'b', 'b', 'b', 'b'], ['foo', 'foo', 'bar', 'bar', 'foo', 'foo', 'bar', 'bar']], names=['letter', 'word'])
df3 = pd.DataFrame({'data1': [3, 2, 4, 3, 2, 4, 3, 2], 'data2': [6, 5, 7, 5, 4, 5, 6, 5]}, index=ix3)

# Group by index labels and take the means and standard deviations for each group
gp3 = df3.groupby(level=('letter', 'word'))
means = gp3.mean()
errors = gp3.std()
means
errors

# Plot
fig, ax = plt.subplots()
means.plot.bar(yerr=errors, ax=ax)
```
#### Problem description

The resulting image doesn't contain the horizontal ticks of the error bars.

figure_1

#### Expected Output

figure_1

To achieve this the last line should be replaced with

```
means.plot.bar(yerr=errors, ax=ax, capsize=4)
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.3
pytest: 3.2.1
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.26
numpy: 1.13.1
scipy: 0.19.1
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by drorata**
- [x] closes #17467
- [x] tests passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by drorata** [comment]
How did this change changed the coverage?

**Comment by drorata** [comment]
Any feedback on this PR would be appreciated...

**Comment by TomAugspurger** [comment]
In https://github.com/pandas-dev/pandas/pull/17462 we're discussing changing the style to seaborn or matplotlib 2.0's new defaults. I think both of those suppress the caps for error bars (by default).

Any reason you want to explicitly add them? Just a style thing?

**Comment by drorata** [comment]
Well, as is, the code in the example doesn't yield the rendered result. I had (using matplotlib 2.0 and ggplot/default style) to add the `cap` related option. So this PR is mostly for the sake of correctness of the documentation.

**Comment by TomAugspurger** [comment]
I think if you were to set `matplotlib.style.use('seaborn')` before making
the plot, you'll see the caps. But since we're changing the style used in
the docs, I don't think we need the changes here, unless I'm
misunderstanding something.

**Comment by drorata** [comment]
If the change you plan will fix the rendered plot, then you're right. In any case, the current status where the rendered image is *not* yielded by the sample code is confusing.

**Comment by TomAugspurger** [comment]
> In any case, the current status where the rendered image is not yielded by the sample code is confusing

Yeah it's strange since those aren't static images, they're generated as the code runs. Maybe a version mismatch between your environment and the docs?

Either way I think aesthetically the version without caps looks better. What do you think?

**Comment by drorata** [comment]
Regarding the environment: could be... I failed to installed the environment as described [here](https://pandas.pydata.org/pandas-docs/stable/contributing.html#creating-a-development-environment) but this is a different story I guess.

As for the aesthetic aspect --- I think the caps are crucial for faster and better perception of the error bars.

**Comment by jorisvandenbossche** [comment]
@drorata It seems something went wrong with the latest update, as there is now some unrelated code in the diff.

**Comment by drorata** [comment]
As per @TomAugspurger [comment](https://github.com/pandas-dev/pandas/pull/17468#issuecomment-328628462) I guess this PR should be closed and not merged.

**Pull request closed without merging**
