### PR TITLE
TST: GH#23922 Add missing match params to pytest.raises

### PR DESCRIPTION
**Pull request by mike-cramblett**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by mike-cramblett** [comment]
xref  #23922

**Review by gfyoung — APPROVED** [review]
Nice!

cc @jreback

**Comment by jreback** [comment]
thanks @mike-cramblett

**Comment by mike-cramblett** [comment]
No prob!

**Pull request merged**
