### PR TITLE
CLN: test code no longer shared with sparse

### PR DESCRIPTION
**Pull request by jbrockmendel**
broken off from #29985.

### CODE REVIEW

**Review by gfyoung — APPROVED** [review]

**Comment by jreback** [comment]
great!

**Comment by jbrockmendel** [comment]
this PR is showing up as merged but still open, huh?

**Comment by jreback** [comment]
oh that's weird

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/commit/c5f2084160f765f6b7495b987a198f9db5e972cd definitly merged

**Comment by jreback** [comment]
lol i clicked the button :->

**Pull request merged**
