### PR TITLE
CI: use pyarrow 0.17.1 instead of 0.17.0 for py37_macos build

### LINKED ISSUE #41937: CI: intermittent segfaults on `macOS py37_macos` run
See https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=61339&view=logs&j=b516280a-8c75-541b-8ba0-ae13561718a7&t=a9217cb1-24f6-5625-717d-72085a70e1d3

and https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=61324&view=logs&j=b516280a-8c75-541b-8ba0-ae13561718a7&t=a9217cb1-24f6-5625-717d-72085a70e1d3

for some examples on 2 different runs. I've only noticed it on this run, will look to try to see when it started (unless anyone knows :)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes #41937

### CODE REVIEW

**Comment by jreback** [comment]
thanks merge when green (note we may need for 1.2.5 as well?)

**Comment by simonjayhawkins** [comment]
> note we may need for 1.2.5 as well?

will know for sure when I do the manual backport of #41924

or could backport anyway?

**Review by lithomas1 — CHANGES_REQUESTED** [review]
@jorisvandenbossche Do we want to bump min version to 0.17.1 in general for MacOS, not just in the CI? 
~~@simonjayhawkins I think 1.2.5 is still on pyarrow 0.15 so shouldn't backport?~~
EDIT: See below comment for clarification.

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins I think 1.2.5 is still on pyarrow 0.15 so shouldn't backport?

we don't really want ci constantly failing. if we need a patch for pandas 1.2.x to work with pyarrow 0.15 that's a different issue.

**Comment by lithomas1** [comment]
Sorry, should've been more clear.
The MacOS Python 3.7 job on Azure is on pyarrow 0.15.1 on 1.2.x.
https://github.com/pandas-dev/pandas/blob/322d54a9257e0d57a13dae6a443855df39e18ba3/ci/deps/azure-macos-37.yaml#L24
According to the JIRA issue, it seems this would only affect 0.17.0. I guess we should just first not backport, and then backport if CI is red on the MacOS job then.

**Comment by simonjayhawkins** [comment]
> According to the JIRA issue, it seems this would only affect 0.17.0. I guess we should just first not backport, and then backport if CI is red on the MacOS job then.

sgtm

**Comment by jreback** [comment]
thanks @jorisvandenbossche

**Pull request merged**
