### PR TITLE
ENH: Provide the error message from the HTTP server when return the HTTPError, #47242

### LINKED ISSUE #47242: ENH: Provide the error message from the HTTP server when return the HTTPError
#### Is your feature request related to a problem?

When we use pandas to read data from a HTTP server and encounter an error, the error traceback of pandas only shows the HTTP response status code and the description of the status code, e.g.: `HTTPError: HTTP Error 400: Bad Request`. If the HTTP server returns the detailed error message in the response body, the pandas error traceback won't show it.

#### Describe the solution you'd like

I would like to add a try-except when calling the `urllib.request.urlopen`(https://github.com/pandas-dev/pandas/blob/main/pandas/io/common.py#L232-L239). If encounter an error while read data from the server, it adds the detailed error message to the traceback before raising it.

#### API breaking implications

None. This feature shouldn't affect any API.

#### Describe alternatives you've considered

The other approach is to change the API of `urllib.request.urlopen` but it's more complicated.

#### Additional context

A simple HTTP server that return 400 with detailed message.
```python
from fastapi import FastAPI, HTTPException


app = FastAPI()


@app.get("/")
async def main():
    raise HTTPException(
        status_code=400,
        detail="The format of the parameter is wrong!",
    )
    return None
```

When using `curl` to get data from the HTTP server, it shows the status code with the detailed error message.
```sh
curl http://127.0.0.1:8000

>>> {"detail":"The format of the parameter is wrong!"}
```

When using pandas to get data, it only shows the status code.

```python
import pandas as pd

df = pd.read_csv("http://127.0.0.1:8000")
```
The traceback would miss the detailed error message part.
```sh
Traceback (most recent call last):
  File "andrew-test.py", line 3, in <module>
    df = pd.read_csv("http://127.0.0.1:8000")
  File "/Users/andrew/github/orcahmlee/pandas/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "/Users/andrew/github/orcahmlee/pandas/pandas/io/parsers/readers.py", line 927, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/andrew/github/orcahmlee/pandas/pandas/io/parsers/readers.py", line 582, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/andrew/github/orcahmlee/pandas/pandas/io/parsers/readers.py", line 1421, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/andrew/github/orcahmlee/pandas/pandas/io/parsers/readers.py", line 1707, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/Users/andrew/github/orcahmlee/pandas/pandas/io/common.py", line 672, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/Users/andrew/github/orcahmlee/pandas/pandas/io/common.py", line 336, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/Users/andrew/github/orcahmlee/pandas/pandas/io/common.py", line 239, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/Users/andrew/miniconda3/envs/pandas-dev/lib/python3.8/urllib/request.py", line 274, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/andrew/miniconda3/envs/pandas-dev/lib/python3.8/urllib/request.py", line 598, in open
    response = meth(req, response)
  File "/Users/andrew/miniconda3/envs/pandas-dev/lib/python3.8/urllib/request.py", line 715, in http_response
    response = self.parent.error("http", request, response, code, msg, hdrs)
  File "/Users/andrew/miniconda3/envs/pandas-dev/lib/python3.8/urllib/request.py", line 633, in error
    return self._call_chain(*args)
  File "/Users/andrew/miniconda3/envs/pandas-dev/lib/python3.8/urllib/request.py", line 567, in _call_chain
    result = func(*args)
  File "/Users/andrew/miniconda3/envs/pandas-dev/lib/python3.8/urllib/request.py", line 724, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

I think the traceback shown as follows would be very useful for the end-users.
```sh
urllib.error.HTTPError: HTTP Error 400: Bad Request, {"detail":"The format of param is wrong!"}
```

If this feature requests meaningful, I would like to open a PR for this.

### PR DESCRIPTION
**Pull request by orcahmlee**
ENH: Provide the error message from the HTTP server when return the HTTPError, #47242

Signed-off-by: Andrew Li <orcahmlee@gmail.com>

- [x] closes #47242 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
I would be -1 on this change. For `urllib.error.HTTPError`, the exception object contains more attributes than just the reason (code, reason, headers). So I think it's more sensible for the user to catch and log/handle as appropriate.

**Comment by orcahmlee** [comment]
> I would be -1 on this change. For `urllib.error.HTTPError`, the exception object contains more attributes than just the reason (code, reason, headers). So I think it's more sensible for the user to catch and log/handle as appropriate.

Hi @mroeschke , thanks for your advice.

I did some changes. I only appended the error message from the server and re-raise the `urllib.error.HTTPError`.

The user would see
```sh
urllib.error.HTTPError: HTTP Error 400: Bad Request, message from server: <MORE DETAILED MESSAGES> 
```
instead of 
```sh
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

Also, the users are still able to catch the `urllib.error.HTTPError` if they want to access the attributes of the `HTTPError`.

Please give me some advice on this approach.

**Comment by mroeschke** [comment]
> > I would be -1 on this change. For `urllib.error.HTTPError`, the exception object contains more attributes than just the reason (code, reason, headers). So I think it's more sensible for the user to catch and log/handle as appropriate.
> 
> Hi @mroeschke , thanks for your advice.
> 
> I did some changes. I only appended the error message from the server and re-raise the `urllib.error.HTTPError`.
> 
> The user would see
> 
> ```shell
> urllib.error.HTTPError: HTTP Error 400: Bad Request, message from server: <MORE DETAILED MESSAGES> 
> ```
> 
> instead of
> 
> ```shell
> urllib.error.HTTPError: HTTP Error 400: Bad Request
> ```
> 
> Also, the users are still able to catch the `urllib.error.HTTPError` if they want to access the attributes of the `HTTPError`.
> 
> Please give me some advice on this approach.

I still believe that this change is not significant enough to warrant a change in pandas. This exception is wholly provided by the Python stdlib and not necessarily pandas; therefore, HTTPError messaging should be improved in the stdlib.

**Comment by orcahmlee** [comment]
> I still believe that this change is not significant enough to warrant a change in pandas. This exception is wholly provided by the Python stdlib and not necessarily pandas; therefore, HTTPError messaging should be improved in the stdlib.

OK, I see. Thanks again for your review.

**Pull request closed without merging**
