### PR TITLE
API: Rename BaseGrouper.recons_codes to BaseGrouper.reconstructed_codes

### PR DESCRIPTION
**Pull request by topper-123**
Rename ``BaseGrouper.recons_codes`` to ``BaseGrouper.reconstructed_codes``. This is an internal attribute, so ok to rename. 

Also adds some typing.

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
Nice updates; I think this definitely helps readability

**Comment by jreback** [comment]
this needs to coordinate with #28634 (so may need to rebase here once that is merged)

**Comment by WillAyd** [comment]
The other PR is from a first time contributor that's been at it for a month and a half, so I think let's merge that first and rebase here to keep things moving

**Comment by jreback** [comment]
@topper-123 if you can rebase; might need to type the added method

**Pull request merged**
