### PR TITLE
ENH: Totality validation for merge operation

### LINKED ISSUE #58547: ENH: Add totality validation to merge method
### Feature Type

- Adding new functionality to pandas

### Problem Description

The available validation methods lack checks for (left-/right-)totality. I am frequently encountering cases where I need to manually check that eg. a one-to-one merge also finds a match match in the right DF for every row in the left DF or vice versa.

### Feature Description

Add the following to `one_to_one`, `one_to_many` and `many_to_one` merge validations:

- `left_total` ... Each row in the left DataFrame is matched to (at least) one row in the right DataFrame
- `right_total` ... Each row in the right DataFrame is matched to (at least) one row in the left DataFrame
- `total` ... Both `left_total` and `right_total` must hold

A combination of join relation and totality constraint should be possible by combining with a `+`: `one_to_one+left_total`

### Alternative Solutions

Currently, doing an outer join and checking for `NaN` values in the "foreign" columns works to find unmerged rows. However, this will fail if there are already `NaN` values in the initial DataFrames.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by z3rone**
- [x] closes #58547
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/v3.0.0.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by WillAyd** [comment]
Hmm I'm not too sure about adding this - the validation keyword strictly deals with cardinality today. This seems to blur that scope a little.

Does a library like great expectations not already have something to solve your need?

**Comment by z3rone** [comment]
@WillAyd I would argue that adding totality has a special significance. It would enable the validation of all the cardinalities defined by the [entity relationship model](https://datacadamia.com/data/type/relation/modeling/cardinality#cardinality_symbol).

This defines a clear scope for what the `validate` option's itention is and also adds compatability with the most common modeling language for merges.

**Comment by z3rone** [comment]
Also the existing validations are useful to avoid unwanted data duplication. My validations would help avoiding unwanted data loss during merge. I think the new validations are just the complementary extension of the existing ones.

**Comment by mroeschke** [comment]
Thanks for the PR, but I am also skeptical of adding this into pandas as well. In addition, it appears the original issue has not been triaged yet so a PR is a bit early for this stage - discussion on the issue is still need regarding acceptance and implementation, so closing

**Pull request closed without merging**
