### PR TITLE
DEPR: Remove how, fill_method, and limit from resample

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Deprecated since 0.18

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
lgtm. looks like some linting checks are failing and some warnings need to removed somewhere

**Comment by jbrockmendel** [comment]
py36 build is the old ResourceWarning, ill look into that this week.

Nice to see this ripped out!

**Comment by jreback** [comment]
> py36 build is the old ResourceWarning, ill look into that this week.
> 
> Nice to see this ripped out!

cool, can we suppress in the interim?

**Comment by mroeschke** [comment]
Hmm the linting error looks like flake8 raising a ValueError. Wasn't able to reproduce this locally with the same venisons on mac.

```
2019-12-08T19:32:40.7248259Z flake8 --version
2019-12-08T19:32:40.9269883Z 3.7.9 (flake8-comprehensions: 3.1.4, mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.7.3 on Linux
2019-12-08T19:32:40.9426782Z Linting .py code
2019-12-08T19:33:56.3771046Z Traceback (most recent call last):
2019-12-08T19:33:56.3772178Z   File "/home/runner/miniconda3/envs/pandas-dev/bin/flake8", line 11, in <module>
2019-12-08T19:33:56.3772525Z     sys.exit(main())
2019-12-08T19:33:56.3773059Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
2019-12-08T19:33:56.3773175Z     app.run(argv)
2019-12-08T19:33:56.3773513Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/main/application.py", line 393, in run
2019-12-08T19:33:56.3773630Z     self._run(argv)
2019-12-08T19:33:56.3773941Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/main/application.py", line 382, in _run
2019-12-08T19:33:56.3774050Z     self.report()
2019-12-08T19:33:56.3774384Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/main/application.py", line 373, in report
2019-12-08T19:33:56.3774786Z     self.report_errors()
2019-12-08T19:33:56.3775155Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/main/application.py", line 334, in report_errors
2019-12-08T19:33:56.3775273Z     results = self.file_checker_manager.report()
2019-12-08T19:33:56.3775604Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/checker.py", line 265, in report
2019-12-08T19:33:56.3775715Z     results_reported += self._handle_results(filename, results)
2019-12-08T19:33:56.3776055Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/checker.py", line 167, in _handle_results
2019-12-08T19:33:56.3776152Z     physical_line=physical_line,
2019-12-08T19:33:56.3776487Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/style_guide.py", line 418, in handle_error
2019-12-08T19:33:56.3776601Z     code, filename, line_number, column_number, text, physical_line
2019-12-08T19:33:56.3776951Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/style_guide.py", line 565, in handle_error
2019-12-08T19:33:56.3777048Z     self.formatter.handle(error)
2019-12-08T19:33:56.3777382Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/formatting/base.py", line 91, in handle
2019-12-08T19:33:56.3777491Z     line = self.format(error)
2019-12-08T19:33:56.3777824Z   File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.7/site-packages/flake8/formatting/default.py", line 39, in format
2019-12-08T19:33:56.3777916Z     "col": error.column_number,
2019-12-08T19:33:56.3778195Z ValueError: unsupported format character ':' (0x3a) at index 41
```

**Comment by jbrockmendel** [comment]
could add `-v` to the flake8 call?

**Comment by mroeschke** [comment]
Got the lint error. All green.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks a lot!

**Comment by jbrockmendel** [comment]
nice.  out of curiosity, what did the lint issue turn out to be?

**Comment by mroeschke** [comment]
@jbrockmendel it was an unused import. Odd that it would crated that `ValueError` in flake8

**Pull request merged**
