### PR TITLE
BLD: add locale to 34_nslow build

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by bashtage** [comment]
You might need

```
      addons:
        apt:
          packages:
          - language-pack-zh-hans
```

**Comment by bashtage** [comment]
I don't know how job name and cache name work, but there are 2 with the name `34_nslow` and the same cache.

**Comment by jreback** [comment]
@bashtage there are always 2 when you have an allowed failure.

**Comment by bashtage** [comment]
Python 2/3 Unicode challenges.

**Comment by jreback** [comment]
yep I just put it upagain using ZH on 2.7, so will see.

**Comment by bashtage** [comment]
Just did a quick local check and it looks like my patch for the date problem fixes Python 3 issues in `stata`.

**Comment by jreback** [comment]
@bashtage do we have a test for this? (IOW, the above shows no issues in master on py3).

**Comment by bashtage** [comment]
All of these failures

https://travis-ci.org/jreback/pandas/jobs/194872508

are the same bug with locale being used for `strftime`.  There didn't seem to be a specific test needed since it was already being hit in lots of existing tests.

**Comment by jreback** [comment]
hmm, I must have cancelled it too soon (or was looking at the wrong build). ok so this fails on py3. great, going to merge the original change then (running ZH on 3.4).

**Comment by jreback** [comment]
this surfaced an addition (non-stata error)

```
======================================================================
ERROR: test_to_datetime_format_microsecond (pandas.tseries.tests.test_timeseries.TimeConversionFormats)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jreback/pandas/pandas/tseries/tools.py", line 407, in _convert_listlike
    values, tz = tslib.datetime_to_datetime64(arg)
  File "pandas/tslib.pyx", line 1756, in pandas.tslib.datetime_to_datetime64 (pandas/tslib.c:30671)
    raise TypeError('Unrecognized value type: %s' % type(val))
TypeError: Unrecognized value type: <class 'str'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/jreback/pandas/pandas/tseries/tests/test_timeseries.py", line 5374, in test_to_datetime_format_microsecond
    result = to_datetime(val, format=format)
  File "/home/travis/build/jreback/pandas/pandas/tseries/tools.py", line 427, in to_datetime
    return _convert_listlike(np.array([arg]), box, format)[0]
  File "/home/travis/build/jreback/pandas/pandas/tseries/tools.py", line 410, in _convert_listlike
    raise e
  File "/home/travis/build/jreback/pandas/pandas/tseries/tools.py", line 377, in _convert_listlike
    errors=errors)
  File "pandas/tslib.pyx", line 3600, in pandas.tslib.array_strptime (pandas/tslib.c:58664)
    raise ValueError("time data %r does not match "
ValueError: time data '01-Apr-2011 00:00:01.978' does not match format '%d-%b-%Y %H:%M:%S.%f' (match)
```

**Comment by jreback** [comment]
@bashtage going to merge this one: https://travis-ci.org/jreback/pandas/jobs/194920988

which your PR should fix all but 1 of these I think (the one above needs more looking), so i'll create an issue.

**Pull request closed without merging**
