### PR TITLE
REF: move bits of offsets to liboffsets, de-privatize

### PR DESCRIPTION
**Pull request by jbrockmendel**
xref #32942, #33394

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Is there a performance benefit of moving those things to cython?

**Review by jreback — APPROVED** [review]
seems fine to me.

**Comment by jbrockmendel** [comment]
> Is there a performance benefit of moving those things to cython?

Not until we get all of tseries.offsets into liboffsets

**Comment by jorisvandenbossche** [comment]
OK!

**Pull request merged**
