### PR TITLE
Doc: add ExtensionArray.map to reference/extensions.rst

### PR DESCRIPTION
**Pull request by topper-123**
xref #52247 & #52263.

### CODE REVIEW

**Comment by mroeschke** [comment]
This is the error that also failed last time

```
2023-03-29T20:13:24.9068667Z /home/runner/work/pandas/pandas/doc/source/reference/api/pandas.api.extensions.ExtensionArray.map.rst: WARNING: document isn't included in any toctree
```

**Comment by topper-123** [comment]
Still as a loss why this fails. Error message still the same (`pandas/doc/source/reference/api/pandas.api.extensions.ExtensionArray.map.rst: WARNING: document isn't included in any toctree`).

Any suggestion welcome :-)

**Comment by mroeschke** [comment]
Looks like this PR is stale and the check is still failing so closing for now. Feel free to reopen when you want to get back to this PR

**Pull request closed without merging**
