### PR TITLE
DOC: Move whatsnew for indexing regression

### PR DESCRIPTION
**Pull request by phofl**
xref #47921, https://github.com/pandas-dev/pandas/issues/47867#issuecomment-1198412271

Moves the whatsnew

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
milestone 1.4.4 but does not need to be backported (@phofl note that sometimes that the release notes go out of sync and need to be corrected)

Do you think we should also add the code sample from #47867 to close that issue? (the test would also be backported so could be a separate PR)

**Comment by phofl** [comment]
Yes. would do this as a follow up

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
Thanks @phofl ok to merge this once #47921 is merged. see https://github.com/pandas-dev/pandas/pull/47921#pullrequestreview-1060443573

**Comment by simonjayhawkins** [comment]
@phofl i'm not sure about #47925 so have resolved the conflict, but if that gets merged we would probably have conflicts here again.

**Comment by simonjayhawkins** [comment]
urgh I should have left it in otherwise we will get more conflicts if we have to move the release note for that one.

don't merge this yet. although i'm doing something else at the moment (fixing the typing on 1.4.x) so probably won't fix this till tomorrow.

**Comment by phofl** [comment]
No worries, added it back in

**Comment by simonjayhawkins** [comment]
Thanks. sorry for interfering. I thought it'd be quicker to just resolve the conflicts on the web interface than ping you.

**Review by simonjayhawkins — APPROVED** [review]
Thanks @phofl merge when ready

**Comment by phofl** [comment]
No worries. I am doing this in Pycharm anyway, so did not create additional work for me. Thanks for helping

**Comment by phofl** [comment]
Don't need to backport this

**Pull request merged**
