### PR TITLE
REF: de-duplicate symmetric_difference, _union

### PR DESCRIPTION
**Pull request by jbrockmendel**
Also fixes buglet in CategoricalIndex.equals(MultiIndex)

### CODE REVIEW

**Comment by jreback** [comment]
yeah seeing failures on master

**Comment by jbrockmendel** [comment]
rebased + green

**Comment by jreback** [comment]
wow nice

**Comment by jorisvandenbossche** [comment]
This seems to have caused several regressions, see https://pandas.pydata.org/speed/pandas/#regressions?sort=1&dir=desc (the ones for commit "bf72b70b")

**Comment by jorisvandenbossche** [comment]
Opened https://github.com/pandas-dev/pandas/issues/42239 to track this regression

**Pull request merged**
