### PR TITLE
DOC: 1.0.4 whatsnew

### PR DESCRIPTION
**Pull request by TomAugspurger**
Brings 1.0.4.rst to master & sets the release date (for tomorrow)

cc @simonjayhawkins.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
just updated 1.0.4 release notes on 1.0.4. was planning this next.

**Comment by simonjayhawkins** [comment]
I've set the release date to today. was planning to tag (locally) now and hopefully if conda and pip tests pass (they did on a practice run) tag today. The pdf docs seem problematic though but don't want to hold things up.

**Comment by TomAugspurger** [comment]
Ah great. I've restored from 1.0.x, so things should match.

**Comment by simonjayhawkins** [comment]
Was also planning to remove the notes from 1.1 whatsnew for things backported. will open pr shortly.

**Comment by simonjayhawkins** [comment]
I think will also need to update 1.0.3 contributors on master. #33970

**Comment by TomAugspurger** [comment]
Thanks. Feel free to push those changes to this branch, or as a followup. Whatever is easiest for you.

**Comment by simonjayhawkins** [comment]
> Thanks. Feel free to push those changes to this branch, or as a followup. Whatever is easiest for you.

#34430 for the removals.

**Pull request merged**
