### PR TITLE
Doc contribution pr06

### PR DESCRIPTION
**Pull request by tolaa001**
Documentation update fixing some of the methods with a PR06 error code which involved updating  

- string to str

- integer to int

- boolean to bool

No tests required

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @tolaa001

**Comment by WillAyd** [comment]
These aren't all of the methods yet right? Do you know how many more still outstanding?

**Comment by tolaa001** [comment]
@WillAyd no these are not all the methods. There are a few left and will continue to work through it in another PR :)

**Comment by WillAyd** [comment]
Great thanks!

**Pull request merged**
