### PR TITLE
Backports round 2

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Hmm, not sure why those linting errors are coming up here, but not in https://github.com/pandas-dev/pandas/pull/18385.

**Comment by jorisvandenbossche** [comment]
Because W503 was added to setup.cfg as ignored error code on master

**Comment by jorisvandenbossche** [comment]
See https://github.com/pandas-dev/pandas/pull/18046#discussion_r147925011. Maybe add a commit that adds it here as well

**Comment by jorisvandenbossche** [comment]
and I merged https://github.com/pandas-dev/pandas/pull/18730

**Comment by TomAugspurger** [comment]
Ah thanks. Yes, I'll just make a new commit then I think.

**Comment by jreback** [comment]
lgtm.

**Pull request merged**
