### PR TITLE
CI: Switch to large for circleci

### PR DESCRIPTION
**Pull request by phofl**
- [ ] ref #48179 (Replace xxxx with the Github issue number)
Just checking what this would change

### CODE REVIEW

**Comment by mroeschke** [comment]
Looks like some of the CircleCI builds are completing okay now. Do you think this is still needed?

**Comment by phofl** [comment]
Some of them is the important part :)

Not all of them were failing before either, but we are right at the 60 minute limit (57, 58, ...). It would definitely improve stability.

**Comment by mroeschke** [comment]
Okay maybe good to rebase a few time to confirm this helps the consistency of the CircleCI build

**Comment by phofl** [comment]
Makes sense, will do that

**Review by lithomas1 — APPROVED** [review]
lgtm. I dunno how our plan works, though. (cc @datapythonista @jreback )

**Review by mroeschke — APPROVED** [review]
LGTM. Seems like it makes the CircleCI job more stable. Think this is okay to backport to 1.5

**Review by datapythonista — APPROVED** [review]
lgtm

My understanding is that we're in the free plan: https://circleci.com/pricing/

I'm not sure the implications of a larger image. I assume we'll use less minutes, but minutes will cost more credits (even if the quote is defined in minutes). So, the only problem can be that we run out of credits with this. But let's give it a try, and if we run out of credits we check whether we can use cirun and OVH resources, or if we want to pay for a premium CircleCI plan...

**Comment by phofl** [comment]
Large costs 20 credits per minute while medium costs 10, ci minutes are 35 to close to 60, so it is not much more in total, thanks merging for now. Can revert if we run out

**Pull request merged**
