### PR TITLE
CLN: Clean csv files in test data GH34427

### LINKED ISSUE #34427: CLN: is pandas/tests/data used?
In `pandas/tests/data` there are two files:
```
iris.csv
tips.csv
```
Both of these files are also in `pandas/tests/io/data/csv`.

Do they need to be in both places? If not, can they be removed from one of them?

### PR DESCRIPTION
**Pull request by najann**
- [x] closes #34427
- [x] tests passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I deleted the `iris.csv` and `tips.csv` files which are unused duplicates (i.e. those in `pandas/tests/io/data/csv`).

### CODE REVIEW

**Comment by WillAyd** [comment]
Thanks for the PR. Is it possible to do this the other way around? i.e. delete what's in tests/data and update the tests to make sure they point to tests/io/data/csv ?

**Comment by jreback** [comment]
yeah agree here, let's remove the test/data ones

**Comment by jreback** [comment]
@najann yes we'd like to fix this in tests / docs.

**Comment by najann** [comment]
@jreback there is also a `tips.csv` and `iris.data` file in doc/data... Should I clean that up & update any references (which exist only for `iris.data`), too?

**Comment by WillAyd** [comment]
I think OK to leave the doc ones alone for now

**Comment by WillAyd** [comment]
Actually made the above comment without realizing you already have to change some of the rst files; didn't realize they peered into the test folders like that

So I'm indifferent on that for now. I think this is good as is but can either fix all of the docs here or as a follow up.

I think test failure is unrelated; over to @jreback

**Review by jreback — APPROVED** [review]
lgtm merge on green

**Comment by alimcmaster1** [comment]
Re-running the failing travis job: https://travis-ci.org/github/pandas-dev/pandas/builds/692962783

**Comment by WillAyd** [comment]
Travis looks ok just hasn't updated status here

**Comment by WillAyd** [comment]
Thanks @najann very nice clean up and first PR

**Comment by jorisvandenbossche** [comment]
@MeeseeksDev backport to 1.0.x

**Pull request merged**
