### PR TITLE
REF: simplify reindexing in _align_series()

### PR DESCRIPTION
**Pull request by johannes-mueller**
Follow-up to #46058

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Could you adress https://github.com/pandas-dev/pandas/pull/46058#discussion_r821210037 too?

**Comment by johannes-mueller** [comment]
> Could you adress [#46058 (comment)](https://github.com/pandas-dev/pandas/pull/46058#discussion_r821210037) too?

That's what I intended to address, actually. No more `self.values` in the new version.

**Comment by phofl** [comment]
Sorry, should have looked closer. Forget what I‘ve said

**Review by mroeschke — APPROVED** [review]

**Comment by jreback** [comment]
thanks @johannes-mueller

**Pull request merged**
