### PR TITLE
add a new feature sample() into groupby

### PR DESCRIPTION
**Pull request by echozzy629**
- [ ] closes #33175
- [ ] 0 tests added / 0 passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by alimcmaster1** [comment]
@echozzy629 

Thanks for the PR please can you fix up the following

- Test failures there seems to be alot (merging master will help for np dev build)
- run flake8 and black 
- Can you please ref the correct issue - currently doesn't look correct.

Our contributing guide might help:
https://pandas.pydata.org/docs/development/contributing.html

**Review by alimcmaster1 — CHANGES_REQUESTED** [review]
See comments

**Comment by MarcoGorelli** [comment]
Thanks @echozzy629 

Is this still active? If so, can you please address @alimcmaster1 's review?

Also, this would close #31775, not #33175

**Comment by MarcoGorelli** [comment]
Closing due to lack of response, feel free to reopen if you address @alimcmaster1 's feedback

**Pull request closed without merging**
