### PR TITLE
Diff low precision ints

### LINKED ISSUE #45562: BUG: inconsistent upcasting dtypes between diff and shift for int8/int16
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

pd.Series([1, 2, 3], dtype="int8").agg(["diff", "shift"]).dtypes
```

### Issue Description

It appears diff and shift have inconsistent upcasting of types when the input is either int8 or int16:

```
diff     float32
shift    float64
dtype: object
```

Its possible there is good reason for this, but I couldn't find it documented or explained anywhere. 

### Expected Behavior

More consistency in upcasting between diff and shift.

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : a221491f999cca5ac45a6616a4a928977f2d9855
python           : 3.8.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17134
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.5.0.dev0+133.ga221491f99.dirty
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.5.0
Cython           : 0.29.26
pytest           : 6.2.5
hypothesis       : 6.35.0
sphinx           : 4.3.2
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fastparquet      : 0.7.2
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.1
numba            : 0.55.0
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : 1.1.4
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.7.3
sqlalchemy       : 1.4.29
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

### PR DESCRIPTION
**Pull request by lukemanley**
- [x] closes #45562
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

Submitting this PR as a potential option. This changes the diff method to upcast int8/int16 to float64 similar to shift and other methods. It avoids the int8/int16 > float64 cython issue referenced in the code by doing an initial cast from int8/int16 > int32. Note the tests were updated to now expect float64 in a few cases. 

If the existing behavior is preferred, I'm happy to close this. I thought the consistency and fewer special cases elsewhere might be worth the change here.

### CODE REVIEW

**Comment by jreback** [comment]
@lukemanley can you add a whatsnew note in 1.5

cc @jbrockmendel @rhshadrach any objections?

**Comment by jbrockmendel** [comment]
im ambivalent.  being consistent with shift would be nice, but a) i dont like the extra copy this makes and b) users using small-itemsize dtypes probably want small-itemsize results

**Comment by rhshadrach** [comment]
Everything being equal, I'd rather see shift support lower precision dtypes, but perhaps that isn't currently feasible? I haven't looked.

**Comment by lukemanley** [comment]
> im ambivalent. being consistent with shift would be nice, but a) i dont like the extra copy this makes and b) users using small-itemsize dtypes probably want small-itemsize results

Agreed, the extra copy is unfortunate. 


> Everything being equal, I'd rather see shift support lower precision dtypes, but perhaps that isn't currently feasible? I haven't looked.

I think there are a number of examples beyond `shift`. When upcasting, most methods seem to upcast low precision ints to float64 even if a lower precision like float32 could suffice. It seems `diff` stands alone in this aspect. Here are two other examples where low precision ints are upcast to float64:

```
>>> pd.Series([1, 2, 3], dtype='int8').reindex(range(4))
0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

>>> pd.Series([1, 2, 3], dtype='int8').rolling(1).max()
0    1.0
1    2.0
2    3.0
dtype: float64
```

**Comment by jreback** [comment]
can you merge master here

**Comment by lukemanley** [comment]
Merged main, errors look unrelated

**Comment by rhshadrach** [comment]
> I think there are a number of examples beyond shift. When upcasting, most methods seem to upcast low precision ints to float64 even if a lower precision like float32 could suffice. It seems diff stands alone in this aspect.

I think the consensus is that we'd like to see better support for lower precision ops. We aren't going to get there all at once, so there will be inconsistencies in support for quite some time. And we certainly aren't going to get there by taking ops that do support lower precision and removing that support for the purpose of consistency. For that reason, I'm -1 here.

**Comment by jreback** [comment]
> > I think there are a number of examples beyond shift. When upcasting, most methods seem to upcast low precision ints to float64 even if a lower precision like float32 could suffice. It seems diff stands alone in this aspect.
> 
> I think the consensus is that we'd like to see better support for lower precision ops. We aren't going to get there all at once, so there will be inconsistencies in support for quite some time. And we certainly aren't going to get there by taking ops that do support lower precision and removing that support for the purpose of consistency. For that reason, I'm -1 here.

so generally I agree with you. but this little inconsistency is troubling. wouldn't it be better to make a systematic change to support this rather than doing it piecemeal?

**Comment by rhshadrach** [comment]
> wouldn't it be better to make a systematic change to support this rather than doing it piecemeal?

If this were possible to do all in one go, I'm all for it. But I don't think that is likely - there are a ton of ops, including indexing, that need changed.

**Comment by lukemanley** [comment]
I'm happy to close this one if the preference is to keep the current behavior. 

If the current behavior is preferred, `diff` could treat uint8 and uint16 similarly and upcast to float32 rather than float64:

```
import numpy as np
import pandas as pd

df = pd.DataFrame({
    t: np.arange(3, dtype=t) 
    for t in ['int8', 'int16', 'uint8', 'uint16']
})

df.diff(1).dtypes
```

```
int8      float32
int16     float32
uint8     float64
uint16    float64
dtype: object
```

**Pull request closed without merging**
