### PR TITLE
DEPR: is_extension_type

### PR DESCRIPTION
**Pull request by jbrockmendel**
It is mostly redundant with `is_extension_array_dtype`, and having both is confusing.

xref #23179.

### CODE REVIEW

**Comment by WillAyd** [comment]
Can this not be removed outright? It's non-public and sits behind an experimental interface, so I think not worth the effort of a deprecation cycle

**Comment by jbrockmendel** [comment]
i wouldnt shed any tears if we removed it altogether

**Comment by WillAyd** [comment]
I'm +1 to outright remove but let's see what @TomAugspurger and @jreback think

**Comment by jreback** [comment]
is this in pd.api.types?

if not ok to remove

**Comment by TomAugspurger** [comment]
It’s not public right? So fine to just remove.

This predated the EA interface.

**Comment by jbrockmendel** [comment]
> is this in pd.api.types?

Yes, this is in pd.api.types.  (via a `*` import)

**Comment by jreback** [comment]
> > is this in pd.api.types?
> 
> Yes, this is in pd.api.types. (via a `*` import)

really? it has a test that catches the earning?

**Comment by jbrockmendel** [comment]
We have tests (updated appropriately in this PR) for deprecated functions
in this module.

**Comment by jreback** [comment]
ok i see the change now, yeah have to deprecate

can u add to the master depreciation issue (or create say a 1.2 removals issue)

**Comment by jbrockmendel** [comment]
> can u add to the master depreciation issue (or create say a 1.2 removals issue)

will do

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
