### PR TITLE
CI/TST: update exception message, xfail

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jreback** [comment]
hmm this is failing the 32-bit build  (though likley to pass all others)

**Comment by jbrockmendel** [comment]
ive got some troubleshooting to do here.  if you're starved for things to review, #39454 #39453 #39446 are collectively blockers for reshape bugs/refactor, #39508 #39502 #39495 are test improvements, and #38992 is a blocker for fleshing out tests.  #39163 is not at all trivial, but i think will lead to appreciably simpler code once it goes in.

**Comment by jreback** [comment]
> ive got some troubleshooting to do here. if you're starved for things to review, #39454 #39453 #39446 are collectively blockers for reshape bugs/refactor, #39508 #39502 #39495 are test improvements, and #38992 is a blocker for fleshing out tests. #39163 is not at all trivial, but i think will lead to appreciably simpler code once it goes in.

heheh, will look. more trying to have a green CI  :->

**Comment by jbrockmendel** [comment]
green, booyah

**Comment by jreback** [comment]
nice!

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
