### PR TITLE
backport 43638: BUG: styler to_latex doesnt respect hide_index

### PR DESCRIPTION
**Pull request by attack68**

### CODE REVIEW

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
the backport (alternative fix) of #43638 should be done only after #43638 is merged to master?

**Comment by attack68** [comment]
> the backport (alternative fix) of #43638 should be done only after #43638 is merged to master?

yes, should really have done this as wip, just did both prs now to save time later/

**Comment by jreback** [comment]
closed by #43649 ?

**Comment by attack68** [comment]
indeed.

**Pull request closed without merging**
