### PR TITLE
Fix broken np_dev CI

### LINKED ISSUE #26725: CI 3.7 NumPy Dev Failures
Quite a few CI failures lately so apologies if this was missed but I don't think we have an issue for this one. It looks like we are getting some failures with error message checking on NumPy dev. I think this is a result of this change upstream:

https://github.com/numpy/numpy/pull/13721/files

Here's a sample build failure:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=12453&view=logs&jobId=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&taskId=264dbb61-dd41-5ada-cfaa-25751f4c2dca&lineStart=70&lineEnd=71&colStart=1&colEnd=1

Need to update and maybe simplify the error message checking on our end.

cc @simonjayhawkins if you have thoughts

### PR DESCRIPTION
**Pull request by WillAyd**
- [X] closes #26725
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]
lgtm. (failed workers on Travis are a separate issue)

**Comment by jreback** [comment]
are the doc / slow failures covered by this?

**Comment by WillAyd** [comment]
No those are separate

**Comment by simonjayhawkins** [comment]
> are the doc / slow failures covered by this?

no. docs #26723, slow #26714, and timeouts #26716

**Comment by jreback** [comment]
k merge away

**Comment by simonjayhawkins** [comment]
thanks @WillAyd

**Pull request merged**
