### PR TITLE
WEB: Adding Effective pandas 2 book to home page

### PR DESCRIPTION
**Pull request by datapythonista**
@mattharrison I think you discussed this with @phofl, I need the affiliated link before it's published.

Also, I changed the color palette of the book cover to reduce the size of the file. I don't think it's easy to notice, but if you want to have a look, to make sure you're happy with it. Thanks!

### CODE REVIEW

**Comment by mattharrison** [comment]
Hi @datapythonista . Can I get an email address to attribute referrals from the website?

**Comment by mattharrison** [comment]
Here's the link https://store.metasnake.com/effective-pandas-book/lhte7

**Comment by datapythonista** [comment]
Thanks @mattharrison, this should be ready now

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
Thx @datapythonista

**Pull request merged**
