### PR TITLE
Ci #34131 rm slow fixtures

### PR DESCRIPTION
**Pull request by OlivierLuG**
- [ x ] Part of #34131 
- [ x ] passes `black pandas`
- [ x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ FAIL ] tests passed for 11 of 12 files changed. 6 tests fail inside the file `pandas/core/arrays/datetimes.py` , but there are not concerned by this PR. So I decide to push anyway.

I went through tests tagged with `@pytest.mark.slow` and take a look at the duration. The test is unmarked if the test duration is below 1 second.
note: I considered the total time for each combination in case of parameters

A total of 76 flags `slow` were unmark, so we can focus on "real" slow tests.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
for future reference, lets refer to these as `pytest.mark.slow`, since they're not technically fixtures

**Comment by jbrockmendel** [comment]
looks like some of the failing tests need a td.skip_if_no_scipy decorator

**Comment by jreback** [comment]
@OlivierLuG aplaud the effort here. this is a bit tricky because IIRC we only run the slow on a single job (on travis); the issue is that *some* of these tests are marked slow not to indicate they are slow but rather that we want to run them there, e.g. plotting tests and such. 

we have a pretty tricky setup with this, so you will have to play with the ci to get this to pass.

you might want to start with a smaller scope (e.g. start with x tests), then get it passing, then keep adding.

**Comment by OlivierLuG** [comment]
Thanks for the explaination. If I do understand correctly, the objective of this issue is either to unmark the slow tests, and still passing the CI tests or to optimise the speed of the tests itself ?

**Comment by jreback** [comment]
i think a good start here would be to fix some of the really slow tests themselves 

also the original issue was about some fast tests that are actually slow on ARM

**Pull request closed without merging**
