### PR TITLE
BUG: incorrectly accepting datetime64(nat) for dt64tz

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
is this user facing at all?

**Comment by jbrockmendel** [comment]
> is this user facing at all?

yes.  `DatetimeIndex[tz].insert(np.datetime64("NaT"))` now casts to object, and a bunch of the TestSetitemNADatetime64Dtype tests fail in master

**Comment by jreback** [comment]
> > is this user facing at all?
> 
> yes. `DatetimeIndex[tz].insert(np.datetime64("NaT"))` now casts to object, and a bunch of the TestSetitemNADatetime64Dtype tests fail in master

kk can you add a whatsnew :->

**Comment by jbrockmendel** [comment]
whatsnew added + green

looking forward to the follow-up that de-duplicates a bunch of tests

**Pull request merged**
