### PR TITLE
CLN: Exception in io, plotting

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@datapythonista the two failures in the slow build are showing up for me locally (OSX, py37, up-to-date numpy).  I'm having a hard time troubleshooting them.  Any idea who to talk to?

**Comment by datapythonista** [comment]
Not sure if I understand. Do you mean you can't reproduce them locally?

My view is that we shouldn't be using `pyplot`. `pyplot` is a convenient API for users in a notebook. But for production code using an API that changes an internal state of a module like `pyplot` does makes things very tricky. Mainly for the tests, since tests running in parallel keep changing the internal state of `pyplot` affecting each other. Matplotlib offers more Pythonic APIs.

Of course there is a huge amount of work in the Matplotlib backend, and implementing one based on the object based Matplotlib API is not an immediate fix, but  a wish for the long term. But I guess it's useful to keep that in mind.

In #27009 I had all sort of weird errors related to this. One of them was that some tests broke just by adding a `from pandas import Series` somewhere. I didn't find a proper fix, but just kept reverting things and looking for alternative ways until errors disappeared.

May be things will be better after we merge #28531. Not sure if in the case of Matplolib it'll make a difference, since there are several files of tests. But not parallelizing tests in the same file can help, since I guess tests in the same file are likely to affect the same parts of `pyplot`.

Hope it helps. If I misunderstood and you think talking to someone from Matplotlib or Azure may help, let me know.

**Comment by jbrockmendel** [comment]
> Not sure if I understand. Do you mean you can't reproduce them locally?

I can reproduce it locally, I just can't figure out how to fix it.

**Comment by datapythonista** [comment]
> I can reproduce it locally, I just can't figure out how to fix it.

I see. Had a look, but can't really tell. Not sure if you can open a separate PR for each change, and at least we'll know which one if causing the error.

**Comment by jbrockmendel** [comment]
Separate PRs it is.

**Comment by jbrockmendel** [comment]
Closing while I troubleshoot this locally.

**Pull request closed without merging**
