### PR TITLE
CI: Fix Assign CI not working with quotes

### LINKED ISSUE #29768: CI: Action to assign issues fails when quotes are present
So, this is a little weird. Apparently I left such a bad comment on an issue, it failed CI 😄. 

I'm not sure how it got triggered, but looks like it's from a recently added workflow. The CI error has the contents of my comment, and I got an email that looks like this:

<details>
<summary> Notification email </summary>

------------

Run failed for master (6d11aa8)

Repository: pandas-dev/pandas
Workflow: Assign
Duration: 16.0 seconds
Finished: 2019-11-21 05:41:26 UTC

[View results](https://github.com/pandas-dev/pandas/commit/6d11aa89fc06ebc55519507f6652dcfcba35a302/checks)

Jobs:
[cb4db6dd-e658-55b7-b337-8761517bc1a3](https://github.com/pandas-dev/pandas/runs/313172123) failed (1 annotation)
—
You are receiving this because this workflow ran on your branch.
Manage your GitHub Actions notifications here.

-------------------

</details>

* [CI failure](https://github.com/pandas-dev/pandas/runs/313172123) - [Raw log](https://pipelines.actions.githubusercontent.com/xZyE9jtmkxWlfCAbyu1SHPJOlsa2huNFYcxohSTomy6EbdNZT9/_apis/pipelines/1/runs/857/signedlogcontent/3?urlExpires=2019-11-21T06%3A00%3A03.3232502Z&urlSigningMethod=HMACV1&urlSignature=vlq2JBJLcoJ3pFQnugH8M9AcGnopXrvuooUOaeU2eAA%3D)
* [The comment](https://github.com/pandas-dev/pandas/issues/14177)

Looks like this might be related to #29648, @datapythonista?

### PR DESCRIPTION
**Pull request by lithomas1**
- [x] closes #29768 
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Examples(all three passed)
image

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks for working on this. Do you know why this works? I'm wondering if it's because the content of the variable is assigned and taking a substring is having no effect.

**Review by datapythonista — COMMENTED** [review]
I think this is much better. But it just came to my mind, that we should be able to do the comparison before fetching the content of the variable. I think the next or something similar should work:
```python
if [[ "${{ github.event.comment.body == "take" }}" == "true" ]]; then
```

Github actions supports expressions with operators, and even some functions, you can find more info at:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#operators

Thanks!

**Comment by lithomas1** [comment]
@datapythonista I think I got it now. 
Can you take another look? Thanks.

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by datapythonista** [comment]
Thanks @lithomas1, I think this fix is better than what I proposed.

For the next time, I recommend you use a hit branch, and not work directly in master.

(Just trying " this, to see if it works as expected).

**Pull request merged**
