### PR TITLE
Fix float formatting edge case

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by jreback** [comment]
I guess I changed this on purpose !
```
*** Processing results...
*** 
Invoked with :
--ncalls: 3
--repeats: 3


-------------------------------------------------------------------------------
Test name                                    | head[ms] | base[ms] |  ratio   |
-------------------------------------------------------------------------------
read_csv_infer_datetime_format_ymd           |   1.9714 |   2.0163 |   0.9777 |
read_csv_comment2                            |  25.3403 |  25.4656 |   0.9951 |
read_csv_precise_converter                   |   1.5370 |   1.5430 |   0.9961 |
read_csv_roundtrip_converter                 |   2.3714 |   2.3573 |   1.0060 |
frame_to_csv2                                | 117.3016 | 115.5004 |   1.0156 |
read_csv_thou_vb                             |  19.5527 |  19.1456 |   1.0213 |
read_csv_default_converter                   |   1.6466 |   1.5797 |   1.0424 |
read_csv_infer_datetime_format_iso8601       |   1.9317 |   1.8443 |   1.0474 |
read_csv_infer_datetime_format_custom        |  10.3533 |   9.6080 |   1.0776 |
read_csv_standard                            |  11.9016 |  10.5267 |   1.1306 |
read_csv_vb                                  |  22.6383 |  18.4843 |   1.2247 |
packers_read_csv                             | 193.1477 | 156.2746 |   1.2360 |
frame_to_csv_date_formatting                 |  12.8030 |  10.2570 |   1.2482 |
frame_to_csv_mixed                           | 175.5013 | 138.3707 |   1.2683 |
read_csv_skiprows                            |  16.4720 |  12.2391 |   1.3459 |
packers_write_csv                            | 1086.9323 | 621.1909 |   1.7498 |
write_csv_standard                           |  45.0310 |  24.5957 |   1.8309 |
frame_to_csv                                 | 126.7430 |  54.7020 |   2.3170 |
-------------------------------------------------------------------------------
Test name                                    | head[ms] | base[ms] |  ratio   |
-------------------------------------------------------------------------------

Ratio < 1.0 means the target commit is faster then the baseline.
Seed used: 1234

Target [4c4497c] : Fix float formatting precision
Base   [1d87174] : BUG: plot doesnt default to matplotlib axes.grid setting (#9792)
```

**Comment by cpcloud** [comment]
Alright, I'll take a look and see if I can get the perf up to snuff with master

**Comment by jreback** [comment]
@cpcloud any luck with the perf fix on this?

**Comment by jreback** [comment]
@cpcloud status?

**Comment by jreback** [comment]
@cpcloud closing, but reopen if still interested

**Pull request closed without merging**
