### PR TITLE
Backport PR #28614 on branch 0.25.x (CI: troubleshoot s3fs failures)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #28614: CI: troubleshoot s3fs failures

### CODE REVIEW

**Comment by WillAyd** [comment]
Not sure what is up with py36 failure. If someone has time to debug would certainly be welcome

**Comment by jbrockmendel** [comment]
Failure is in read_parquet, traceback goes to a .pxi file in pyarrow and ends with "???" which usually means its in C.  cc @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
That's a know problem for certain versions of fastparquet, we skip those tests on master, but should probably backport that skip: https://github.com/pandas-dev/pandas/pull/28357

**Comment by jorisvandenbossche** [comment]
Triggered backport: https://github.com/pandas-dev/pandas/pull/28627

**Comment by jorisvandenbossche** [comment]
I restarted the failed builds, and now all green, so merging

**Pull request merged**
