### PR TITLE
DOC: complement the documentation for pandas.DataFrame.agg #35912

### LINKED ISSUE #35912: DOC: Aggregate and rename is undocumented
The function `DataFrame.agg` allows for kwargs to aggregate and rename the results.

    df = pd.DataFrame({'a': [1, 2, 3]})
    print(df.agg(a_new=('a', 'sum')))

results in

           a
    a_new  6

Perhaps I'm missing it, but I can't find it in both the API reference and the User Guide.

### PR DESCRIPTION
**Pull request by onshek**
- [x] closes #35912
- [x] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry
Screenshot 2020-08-28 at 11 59 23

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Nice, thanks @onshek !

**Comment by onshek** [comment]
Sorry for closing it by mistake :)

**Comment by onshek** [comment]
Can anyone help me to figure why two new checks failed here? Thanks! @MarcoGorelli @charlesdong1991 @rhshadrach

**Comment by MarcoGorelli** [comment]
> Can anyone help me to figure out why two new checks failed here (This PR passed all 15/15 checks two days ago and I didn't make new changes)? Thanks! @MarcoGorelli @charlesdong1991 @rhshadrach

Failures are unrelated, if you merge master and push again I'd expect them to be fixed

**Comment by onshek** [comment]
> > Can anyone help me to figure out why two new checks failed here (This PR passed all 15/15 checks two days ago and I didn't make new changes)? Thanks! @MarcoGorelli @charlesdong1991 @rhshadrach
> 
> Failures are unrelated, if you merge master and push again I'd expect them to be fixed

Got it, thanks!

**Comment by mroeschke** [comment]
Thanks @onshek. The CI failure is unrelated
```

============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/vsts/work/1/s, configfile: setup.cfg, testpaths: pandas
plugins: hypothesis-5.28.0, forked-1.2.0, asyncio-0.12.0, xdist-2.1.0, azurepipelines-0.8.0
gw0 I / gw1 I
gw0 [76009] / gw1 [76009]

##[error]1 test(s) failed, 76009 test(s) collected.
Skipping uploading of coverage data.

=================================== FAILURES ===================================
_____________________ TestIndex.test_tab_complete_warning ______________________

```

**Pull request merged**
