### PR TITLE
CLN: Move code outside of try/except blocks

### PR DESCRIPTION
**Pull request by jbrockmendel**
Trying to make it clearer exactly what the failure modes being caught are.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Travis fail unrelated

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by jbrockmendel** [comment]
ping

**Comment by jreback** [comment]
thanks

**Comment by jorisvandenbossche** [comment]
Didn't yet look in detail, but it seems this broke geopandas: https://travis-ci.org/jorisvandenbossche/geopandas/jobs/554786189 (at least it started failing the last two hours, and is related to a get_value)

**Comment by jorisvandenbossche** [comment]
Opened an issue: https://github.com/pandas-dev/pandas/issues/27258

**Pull request merged**
