### PR TITLE
DOC: fixing GL08 errors for pandas.IntervalIndex.right and pandas.Series.dt

### PR DESCRIPTION
**Pull request by s1099**
Resolved GL08 errors for the following:
1. `scripts/validate_docstrings.py --format=actions --errors=GL08 pandas.IntervalIndex.right`
2. `scripts/validate_docstrings.py --format=actions --errors=GL08 pandas.Series.dt`

xref: #57443 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by s1099** [comment]
pre-commit.ci autofix

**Review by datapythonista — COMMENTED** [review]
Do you mind splitting the two docstrings in separate pull requests please? I have some comments, but reviewing them together is not very efficient. Surely feel free to work in the same PR for the `right` and `left` methods, since they'll be pretty much the same, but for unrelated docstrings it will force us to review the two of them at each iteration, even when one of them is already finished.

**Comment by datapythonista** [comment]
Also, since you worked on the `main` branch, you may want to clone pandas again and start the work in different branches. If you work in `main`, then any new branch you create to work in different things in parallel will contain the changes you made in `main`, and you will have unrelated things in the branches. In general you want to make sure you never commit to `main` and it's synced with the latest `main` in pandas, so when you create branches you start from the right state of pandas.

I'll close this PR, since you'll have to open new ones from the new branches, but surely happy to review your changes in those.

**Comment by s1099** [comment]
moved to #57751

**Pull request closed without merging**
