### PR TITLE
Very useful toolkit for pythonUpdate 

### PR DESCRIPTION
**Pull request by rajarajput2**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by rajarajput2** [comment]
Very useful toolkit for python

**Comment by rajarajput2** [comment]
Very useful toolkit fot python

**Comment by rajarajput2** [comment]
Very useful toolkit for python

**Comment by TomAugspurger** [comment]
No thanks.

**Pull request closed without merging**
