### PR TITLE
BLD: Update MANIFEST.in

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref https://github.com/pandas-dev/pandas/pull/41977#issuecomment-860171367

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
The pip-test and conda-test steps of the release process pass with this patch.

**Comment by simonjayhawkins** [comment]
> The pip-test and conda-test steps of the release process pass with this patch.

I should have said locally.

I think the reason that the ci action https://github.com/simonjayhawkins/pandas-release/actions/runs/932775977 is failing for the conda-test maybe due to the conda recipe being removed from the pandas repo in 1.3. This is a separate issue and maybe an error in the "unofficial" ci scripts there. Will investigate further.

**Comment by simonjayhawkins** [comment]
> I think the reason that the ci action https://github.com/simonjayhawkins/pandas-release/actions/runs/932775977 is failing for the conda-test maybe due to the conda recipe being removed from the pandas repo in 1.3. This is a separate issue and maybe an error in the "unofficial" ci scripts there. Will investigate further.

the scripts are failing for 1.2.5 now too. so something else has changed in the last few days. not relevant for this PR.

**Comment by jreback** [comment]
yeah we removed the conda recioe

i think we can remove this action as well as the conda recioe is maintained externally

**Comment by simonjayhawkins** [comment]
> i think we can remove this action as well as the conda recioe is maintained externally

the action is maintained by me on my personal branch to avoid surprises when doing the release and as a basis for the release automation #21050 and #36704

but that's not relevant to this PR. OK to merge?

**Comment by jreback** [comment]
sure

**Pull request merged**
