### PR TITLE
MAINT: Use __module__ in _DeprecatedModule.

### PR DESCRIPTION
**Pull request by gfyoung**
Follow-up to #14105. Uses the `__module__` method to correctly determine the location of the alternative
module to use.

### CODE REVIEW

**Comment by jreback** [comment]
somethings wrong. so now ``dir(pandas.datetools)`` works, but

``from pandas.core.datetools import yearEnd`` does not show a warning

nor does tab completion on the module
```
In [1]: from pandas.core.datetools import /Users/jreback/miniconda/lib/python2.7/site-packages/IPython/core/completerlib.py:158: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future ver.
  m = __import__(mod)               
                                    
                         ABCDataFrame             BDay                     BMonthEnd                businessDay              cache_readonly           CDay                     CustomBusinessHour       DateParseError            
                         ABCIndexClass            bday                     BQuarterBegin            BusinessHour             CBMonthBegin             cday                     customBusinessMonthBegin datetime                  
                         ABCSeries                bmonthBegin              BQuarterEnd              BYearBegin               cbmonthBegin             compat                   customBusinessMonthEnd   Day                      >
                         algos                    BMonthBegin              bquarterEnd              BYearEnd                 CBMonthEnd               customBusinessDay        D_RESO                   day                       
```

can you add some tests for this

**Comment by gfyoung** [comment]
@jreback : Did tab completion work before?

**Comment by jreback** [comment]
yes

**Comment by gfyoung** [comment]
@jreback : I couldn't get tab completion to issue a warning like that on `master`.  Still not sure why the `pandas.core.datetools` import stopped issuing warnings.  I think it is because I imported the module once during `__init__` with a filter.

**Comment by jreback** [comment]
wel it needs to be the same as master and have the warning and have the same behavior as 0.18.1 for function

**Comment by gfyoung** [comment]
@jreback : Fair enough.  I made some modifications.  Can you take a look?

**Comment by jreback** [comment]
tab complete / warnings loooking good
```
In [1]: import pandas

In [2]: from pandas.core.datetools import C:\Anaconda\envs\pandas3.5\lib\site-packages\IPython\core\completerlib.py:158: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  m = __import__(mod)

In [3]: from pandas.core.datetools import yearEnd
```

```
In [1]: pd.datetools.yearEnd
C:\Anaconda\envs\pandas3.5\Scripts\ipython-script.py:1: FutureWarning: pandas.core.datetools.yearEnd is deprecated and will be removed in a future version.
  if __name__ == '__main__':
Out[1]: <YearEnd: month=12>
```

**Comment by jreback** [comment]
lgtm. @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
@gfyoung Thanks a lot!

**Pull request merged**
