### PR TITLE
BUG: read_csv skips lines with initial whitespace + one non-space character

### PR DESCRIPTION
**Pull request by evanpw**
Fixes GH #9710

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase (prob just a whatsnew conflict)

**Comment by jreback** [comment]
@evanpw can you rebase; we just merged another csv fix and need this retested. thxs.

**Comment by evanpw** [comment]
Rebased, and tests are still green

**Comment by jreback** [comment]
merged via  https://github.com/pydata/pandas/commit/2997e70202bac0ca6ecba0d87f936e208af5ac3b

thanks!

**Pull request closed without merging**
