### PR TITLE
BUG: columns name retention in groupby methods

### LINKED ISSUE #41564: BUG: groupby().ffill() strips level names from MultiIndex on columns
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd

df = pd.DataFrame(
    [[1,2,3,4],[5,6,7,8]],
    columns=pd.MultiIndex.from_product(
        [[0,1], ['foo','bar']], 
        names=['x', 'y']
    )
)

after_groupby = df.groupby(df.index).ffill()

print(f"original dataframe:\n{df}\n")
print(f"result of groupby().ffill():\n{after_groupby}\n")
print(f"original dataframe columns.names:\n{df.columns.names}\n")
print(f"columns.names after groupby().ffill():\n{after_groupby.columns.names}\n")

```

#### Actual output

```
original dataframe:
x   0       1
y foo bar foo bar
0   1   2   3   4
1   5   6   7   8

result of groupby().ffill():
    0       1
  foo bar foo bar
0   1   2   3   4
1   5   6   7   8

original dataframe columns.names:
['x', 'y']

columns.names after groupby().ffill():
[None, None]
```

#### Expected output

```
original dataframe:
x   0       1
y foo bar foo bar
0   1   2   3   4
1   5   6   7   8

result of groupby().ffill():
x   0       1
y foo bar foo bar
0   1   2   3   4
1   5   6   7   8

original dataframe columns.names:
['x', 'y']

columns.names after groupby().ffill():
['x', 'y']
```

#### Problem description

Calling `groupby().ffill()` on a DataFrame with a `MultiIndex` column index strips the `names` attribute of the column index. The above shows the trivial case of `groupby(df.index)`, but I have also found it to occur with nontrivial `by` arguments (e.g. grouping a `DatetimeIndex` by dates).

This is obviously unexpected and undesirable.

#### Output of ``pd.show_versions()``

I have observed this bug on WSL with Python 3.6 and pandas 1.1.5, as well as an M1 MacBook Air with the latest available M1-native pandas version from `conda`. The details of the latter are below.

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.9.2.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 49.6.0.post20210108
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.0
IPython          : 7.23.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #41564
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
is there an issue for this?

**Comment by jbrockmendel** [comment]
> is there an issue for this?

No, though I _think_ it fixes #41564

**Comment by jbrockmendel** [comment]
checked and this does close #41564, will update above

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
