### PR TITLE
_get_new_index always returns index in PeriodIndexResampler

### PR DESCRIPTION
**Pull request by max-sixty**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master | flake8 --diff`
- [ ] whatsnew entry

Cleans up a method that returned different types depending on the length of the index

### CODE REVIEW

**Comment by jreback** [comment]
was this meant to be a PR?

**Comment by MaximilianR** [comment]
Yes! Split this out of the other given it wasn't directly impacting the issue. 
Does the point make sense?

**Comment by jreback** [comment]
can you add some tests for validation, or you can just roll this into the other issue

**Comment by MaximilianR** [comment]
OK I will roll in. Sometimes I know you prefer things split out where it doesn't directly impact; am v happy to roll it in though

**Comment by MaximilianR** [comment]
Rolling into #12874

**Pull request closed without merging**
