### PR TITLE
BUG: Fixed bug in groupby.std changing target column when as_index=False

### LINKED ISSUE #10355: BUG: STD modifies groupby target column when as_index=False
xref #14547 for other tests

In pandas 0.16.2 (and already in 0.16.0), using std() for aggregation after a groupby( 'my_column', as_index=False) modifies 'my_column' by taking its sqrt(). Example:

``` python
df = pandas.DataFrame({
               'a' : [1,1,1,2,2,2,3,3,3],
               'b' : [1,2,3,4,5,6,7,8,9],
})
df.groupby('a',as_index=False).std()
Out[5]: 
          a  b
0  1.000000  1
1  1.414214  1
2  1.732051  1
```

The square root values of 'a' are returned instead of 1, 2, 3.
## INSTALLED VERSIONS

commit: None
python: 2.7.9.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: fr_CH

pandas: 0.16.2
nose: 1.3.4
Cython: 0.22
numpy: 1.9.2
scipy: 0.15.1
statsmodels: None
IPython: 3.0.0
sphinx: 1.3.1
patsy: 0.3.0
dateutil: 2.4.0
pytz: 2015.2
bottleneck: None
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.4.3
openpyxl: None
xlrd: 0.9.3
xlwt: None
xlsxwriter: 0.7.1
lxml: None
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 0.9.9
pymysql: None
psycopg2: None

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixed #10355

### CODE REVIEW

**Comment by jreback** [comment]
this is not going to be oerformant

is there a reason you didn't follow the soln from the issue?

**Comment by terrytangyuan** [comment]
I think the code structure changed somewhat. I couldn't figure out how to
use it.

**Comment by terrytangyuan** [comment]
They are refactored to `_cython_functions` I guess. I tried to do similar thing using `cython` but failed. Maybe this is good for now and I'll figure out how to do it in a separate PERF PR?

**Comment by jreback** [comment]
no that will just change it again

**Comment by terrytangyuan** [comment]
@jreback any updated soln for the soln mentioned in issue? I tried similar way and failed, maybe I missed something.

**Comment by jreback** [comment]
you can just do the ``.var``, then the ``np.sqrt`` only applies to the action columns.

**Comment by terrytangyuan** [comment]
@jreback  Could you take a look at the new push? Did I get what you meant?

**Comment by jreback** [comment]
no u can't use the lamba
that goes to a python path

compute var then apply the sqrt

**Comment by terrytangyuan** [comment]
How do I apply it only to action columns without lambda?

**Comment by terrytangyuan** [comment]
Since the result of applying `.var` would be a `DataFrame` and it lost its original groups, which is why the original implementation causes this bug.

**Comment by jreback** [comment]
this needs a similar approach to what I suggest (and like what ``.first`` does)

**Comment by terrytangyuan** [comment]
So I removed the original definition of `std()` and the diff is as follows:
```
@@ -828,6 +828,8 @@ class GroupBy(PandasObject):
                               numeric_only=False, _convert=True)
     last = _groupby_function('last', 'last', _last_compat, numeric_only=False,
                              _convert=True)
+    def std(self):
+        return self._cython_agg_general('std')

     def ohlc(self):
         """
@@ -1485,6 +1487,8 @@ class BaseGrouper(object):
             'f': lambda func, a, b, c, d: func(a, b, c, d, 1)
         },
         'last': 'group_last',
+        'std': {'name' : 'group_var',
+                'f' : lambda func, a: np.sqrt(func(a))}
     }
```

Still couldn't get it working. (tried other similar things too) The code structure of groupby.py must have changed a lot since the issue has been posted. I think this PR at least fixed the bug. I won't be the best person to fix the perf issues.

**Comment by jreback** [comment]
then let's close this for now. this is non performant.

**Comment by xieyuheng** [comment]
https://github.com/pandas-dev/pandas/pull/25315

**Pull request closed without merging**
