### PR TITLE
DOC: Add missing attributes and methods to MultiIndex API documentation

### PR DESCRIPTION
**Pull request by Elvislim1991**
- [x] xref #50496  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by Elvislim1991** [comment]
PR referenced to open issues [here](https://github.com/pandas-dev/pandas/issues/50496)

**Review by datapythonista — APPROVED** [review]
Looks good, not sure if there was a reason for not being there, I guess they were just forgotten.

CI failures are unrelated.

**Comment by Elvislim1991** [comment]
Okay, I will just touch the IndexSlice for this PR.

**Review by datapythonista — APPROVED** [review]
lgtm, thanks for the work on this @Elvislim1991

**Review by datapythonista — CHANGES_REQUESTED** [review]
Sorry, I realize now that `IndexSlice` is under the `MultiIndex` category, not with its own. Moving it to its own is what makes the CI fail.

It makes sense that it's under `MultiIndex`, but at the same time it makes the navigation confusing, since it splits the `MultiIndex` methods and attributes, which is not great. I'm not sure what's the best here. Maybe I'd revert this for now, and see in a separate PR if something can be done unifying `MultiIndex` objects. And we see after that what makes sense to do with `IndexSlice`.

**Comment by Elvislim1991** [comment]
Ok, I will move back IndexSlice under MultiIndex.

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @Elvislim1991

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Elvislim1991

**Pull request merged**
