### PR TITLE
DOC: Added section on git bisect to pandas maintenance

### LINKED ISSUE #35685: DOC/DEV: document approach to bisect regressions
@simonjayhawkins you have been doing great work on finding the causes of bugs/regressions! 
To make it easier for other contributors to also do this, I think it would be nice to document this is the contributing docs (even though it is relying on git, using it with pandas (which needs to be rebuilt for each commit) requires a bit of custom setup I think?)

### PR DESCRIPTION
**Pull request by seljaks**
- [ ] closes #35685
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/v1.6.0.rst` file if fixing a bug or adding a new feature.

Added section on regressions to development guide under pandas maintenance. Wasn't sure if this needs a whatsnew entry, added it anyway.

@MarcoGorelli Please let me know what you think.

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Nice, very well-written! We don't need the whatsnew note though as it's not a user-facing change, could you remove that please?

**Comment by seljaks** [comment]
@MarcoGorelli Thank you for the speedy feedback! The whatsnew entries are removed.

**Review by MarcoGorelli — APPROVED** [review]
Looks good to me, thanks

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @seljaks

**Pull request merged**
