### PR TITLE
[BUG]: Fix regression when adding timeldeta_range to timestamp

### LINKED ISSUE #35897: Regression in pandas 1.1.0: no longer allows adding a timestamp to timedelta range to create a datetime range.
Under pandas 1.0.5:

```python
>>> import pandas as pd
>>> pd.Timestamp.now() + pd.timedelta_range('0s','1s', periods=31)
DatetimeIndex([   '2020-08-25 12:27:57.690332',
               '2020-08-25 12:27:57.723665333',
               '2020-08-25 12:27:57.756998666',
                  '2020-08-25 12:27:57.790332',
               '2020-08-25 12:27:57.823665333',
               '2020-08-25 12:27:57.856998666',
                  '2020-08-25 12:27:57.890332',
               '2020-08-25 12:27:57.923665333',
               '2020-08-25 12:27:57.956998666',
                  '2020-08-25 12:27:57.990332',
               '2020-08-25 12:27:58.023665333',
               '2020-08-25 12:27:58.056998666',
                  '2020-08-25 12:27:58.090332',
               '2020-08-25 12:27:58.123665333',
               '2020-08-25 12:27:58.156998666',
                  '2020-08-25 12:27:58.190332',
               '2020-08-25 12:27:58.223665333',
               '2020-08-25 12:27:58.256998666',
                  '2020-08-25 12:27:58.290332',
               '2020-08-25 12:27:58.323665333',
               '2020-08-25 12:27:58.356998666',
                  '2020-08-25 12:27:58.390332',
               '2020-08-25 12:27:58.423665333',
               '2020-08-25 12:27:58.456998666',
                  '2020-08-25 12:27:58.490332',
               '2020-08-25 12:27:58.523665333',
               '2020-08-25 12:27:58.556998666',
                  '2020-08-25 12:27:58.590332',
               '2020-08-25 12:27:58.623665333',
               '2020-08-25 12:27:58.656998666',
                  '2020-08-25 12:27:58.690332'],
              dtype='datetime64[ns]', freq=None)
```

Under pandas 1.1.0:

```python
>>> import pandas as pd
>>> pd.Timestamp.now() + pd.timedelta_range('0s','1s', periods=31)
Traceback (most recent call last):
  File "/Users/cbarber/miniconda3/envs/episodic-dev3/lib/python3.6/site-packages/pandas/core/arrays/datetimelike.py", line 1157, in _validate_frequency
    raise ValueError
ValueError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/cbarber/miniconda3/envs/episodic-dev3/lib/python3.6/site-packages/pandas/core/indexes/extension.py", line 147, in method
    result = meth(_maybe_unwrap_index(other))
  File "/Users/cbarber/miniconda3/envs/episodic-dev3/lib/python3.6/site-packages/pandas/core/arrays/datetimelike.py", line 1446, in __radd__
    return self.__add__(other)
  File "/Users/cbarber/miniconda3/envs/episodic-dev3/lib/python3.6/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/Users/cbarber/miniconda3/envs/episodic-dev3/lib/python3.6/site-packages/pandas/core/arrays/datetimelike.py", line 1406, in __add__
    result = self._add_datetimelike_scalar(other)
  File "/Users/cbarber/miniconda3/envs/episodic-dev3/lib/python3.6/site-packages/pandas/core/arrays/timedeltas.py", line 441, in _add_datetimelike_scalar
    return DatetimeArray(result, dtype=dtype, freq=self.freq)
  File "/Users/cbarber/miniconda3/envs/episodic-dev3/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py", line 284, in __init__
    type(self)._validate_frequency(self, freq)
  File "/Users/cbarber/miniconda3/envs/episodic-dev3/lib/python3.6/site-packages/pandas/core/arrays/datetimelike.py", line 1171, in _validate_frequency
    ) from e
ValueError: Inferred frequency None from passed values does not conform to passed frequency 33333333N
```

This error really makes no sense given the above code.

Obviously an unintended side-effect of some other fix.

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #35897
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
This is half of the fix i suggested in #35897, but we need both halves.

**Comment by phofl** [comment]
@jbrockmendel Why is the freq incorrect? We get ``0.033333333``, what would you expect here?

**Comment by jbrockmendel** [comment]
Because of rounding error

```
tdi = pd.timedelta_range('0s','1s', periods=31)

>>> tdi - tdi.shift(1)
TimedeltaIndex(['-1 days +23:59:59.966666667', '-1 days +23:59:59.966666667',
                '-1 days +23:59:59.966666667', '-1 days +23:59:59.966666668',
                '-1 days +23:59:59.966666668', '-1 days +23:59:59.966666668',
                '-1 days +23:59:59.966666669', '-1 days +23:59:59.966666669',
                '-1 days +23:59:59.966666669', '-1 days +23:59:59.966666670',
                '-1 days +23:59:59.966666670', '-1 days +23:59:59.966666670',
                '-1 days +23:59:59.966666671', '-1 days +23:59:59.966666671',
                '-1 days +23:59:59.966666671', '-1 days +23:59:59.966666672',
                '-1 days +23:59:59.966666672', '-1 days +23:59:59.966666672',
                '-1 days +23:59:59.966666673', '-1 days +23:59:59.966666673',
                '-1 days +23:59:59.966666673', '-1 days +23:59:59.966666674',
                '-1 days +23:59:59.966666674', '-1 days +23:59:59.966666674',
                '-1 days +23:59:59.966666675', '-1 days +23:59:59.966666675',
                '-1 days +23:59:59.966666675', '-1 days +23:59:59.966666676',
                '-1 days +23:59:59.966666676', '-1 days +23:59:59.966666676',
                '-1 days +23:59:59.966666677'],
               dtype='timedelta64[ns]', freq=None)
```

If `tdi.freq` is non-None, then we would expect to see `tdi - tdi.shift(1)` to be constant

**Comment by simonjayhawkins** [comment]
> If `tdi.freq` is non-None, then we would expect to see `tdi - tdi.shift(1)` to be constant

so are there cases where a frequency should not be inferred by `timedelta_range`?

if so, maybe revert #32377 and open a issue for discussion on how inference should work?

The docs begin 'Return a fixed frequency TimedeltaIndex...'

so having None as in 1.0.5 maybe not desirable, but can perhaps also discuss the api breaking implications.

for instance should pd.timedelta_range('0s','1s', periods=31) perhaps raise with a message along the lines 'ValueError: cannot infer a fixed frequency from start, end and periods due to rounding errors` or is a fractional freq a feasible option? 

did #32377 actually fix/address any reported bugs/enhancement requests? It appears it was a pre-cursor to a PR that was closed without merging #31195.

> This is half of the fix i suggested in #35897, but we need both halves.

is it worth splitting #35897

or is the inferred freq for `pd.timedelta_range('0s','1s', periods=31)` really the only issue here?

**Comment by phofl** [comment]
We create the index values via numpy
``index = np.linspace(start.value, end.value, periods).astype("i8")``
We would have to change this, if we would like to avoid the rounding errors.

**Comment by phofl** [comment]
Failure seems unrelated?

**Comment by simonjayhawkins** [comment]
is the solution to only infer freq if

```
> c:\users\simon\pandas\pandas\core\arrays\timedeltas.py(271)_generate_range()
-> freq = to_offset(td)
(Pdb) td
Timedelta('0 days 00:00:00.033333333')
(Pdb) td.value
33333333
(Pdb) start.value
0
(Pdb) end.value
1000000000
(Pdb) periods
31
(Pdb) assert start.value + td.value * periods == end.value
*** AssertionError
(Pdb) start.value + td.value * periods
1033333323
```

**Comment by jreback** [comment]
thanks @phofl good patch.

@simonjayhawkins can certainly discuss on the issue but agree inferring None here is right.

**Comment by jbrockmendel** [comment]
@jreback pls revert, this is 100% wrong, #36595 is the correct solution.

**Comment by jreback** [comment]
ok sure (pls push it if you can).

**Pull request merged**
