### PR TITLE
CI: rerun flaky test in html #36467

### PR DESCRIPTION
**Pull request by fangchenli**
Part of #36467

### CODE REVIEW

**Comment by WillAyd** [comment]
Hmm so is this test failing or just sometimes leaking a resource? If the latter it seems like there is an issue elsewhere we need to find

**Comment by fangchenli** [comment]
> Hmm so is this test failing or just sometimes leaking a resource? If the latter it seems like there is an issue elsewhere we need to find

The coverage build generates many many ResourceWarnings (I wonder if it has something to do with the coverage plugin). This test just happens to have an assert_produces_warning in it. Therefore it's the only one that failed.

**Comment by WillAyd** [comment]
> This test just happens to have an assert_produces_warning in it.

We have quite a few tests that would do this though, no?

**Comment by jreback** [comment]
> > Hmm so is this test failing or just sometimes leaking a resource? If the latter it seems like there is an issue elsewhere we need to find
> 
> The coverage build generates many many ResourceWarnings (I wonder if it has something to do with the coverage plugin). This test just happens to have an assert_produces_warning in it. Therefore it's the only one that failed.

happy to try to fix that, but is this really the fix?

**Comment by fangchenli** [comment]
I'll take a deeper look at this. Close for now.

**Pull request closed without merging**
