### PR TITLE
CLN: use self.dtype internally in Categorical

### PR DESCRIPTION
**Pull request by topper-123**
Some clean-up that makes the code a bit easier to read IMO.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
looks fine, can u do a perf check

**Comment by topper-123** [comment]
Ran ASV on benchmarks/categoricals.py. Result are varying a bit, which I attribute to randomness. For example:

```
      before           after         ratio
     [fa47b8d9]       [70ddcef7]
+          5.65μs           13.7μs     2.42  categoricals.CategoricalSlicing.time_getitem_list_like('monotonic_incr')
+          5.76ms           6.70ms     1.16  categoricals.CategoricalSlicing.time_getitem_bool_array('monotonic_incr')
+          3.42μs           3.91μs     1.14  categoricals.CategoricalSlicing.time_getitem_scalar('monotonic_decr')
+           610μs            689μs     1.13  categoricals.CategoricalSlicing.time_getitem_list('monotonic_decr')
-          6.12μs           5.55μs     0.91  categoricals.CategoricalSlicing.time_getitem_list_like('monotonic_decr')
-          6.46μs           5.65μs     0.88  categoricals.CategoricalSlicing.time_getitem_list_like('non_monotonic')
-          3.66μs           3.20μs     0.88  categoricals.CategoricalSlicing.time_getitem_scalar('monotonic_incr')
-          6.08ms           5.21ms     0.86  categoricals.CategoricalSlicing.time_getitem_bool_array('monotonic_decr')
-          4.66μs           4.00μs     0.86  categoricals.CategoricalSlicing.time_getitem_slice('non_monotonic')
-           729μs            567μs     0.78  categoricals.CategoricalSlicing.time_getitem_list('monotonic_incr')

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
```

and

```
      before           after         ratio
     [fa47b8d9]       [70ddcef7]
+          15.6ms           26.0ms     1.67  categoricals.CategoricalSlicing.time_getitem_bool_array('non_monotonic')
+           648μs            933μs     1.44  categoricals.CategoricalSlicing.time_getitem_list('monotonic_decr')
+           613μs            854μs     1.39  categoricals.CategoricalSlicing.time_getitem_list('monotonic_incr')
+          4.88μs           6.10μs     1.25  categoricals.CategoricalSlicing.time_getitem_list_like('monotonic_incr')
-          3.66μs           3.20μs     0.88  categoricals.CategoricalSlicing.time_getitem_scalar('monotonic_incr')
-          4.39μs           3.50μs     0.80  categoricals.CategoricalSlicing.time_getitem_scalar('non_monotonic')
-           729μs            539μs     0.74  categoricals.CategoricalSlicing.time_getitem_list('non_monotonic')
-          6.70ms           4.69ms     0.70  categoricals.CategoricalSlicing.time_getitem_bool_array('monotonic_incr')

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
```

Notice how ``categoricals.CategoricalSlicing.time_getitem_bool_array('monotonic_incr'`` in one run is slow (1.16) and th other fast (0.70).

Overall, I'd say this has is no significant effect on speed.

**Review by gfyoung — APPROVED** [review]
The benchmarks look alright to me.

cc @jreback

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
@TomAugspurger a look pls. lgtm to me.

**Pull request merged**
