### PR TITLE
BUG: scatter_matrix draws incorrect axis

### LINKED ISSUE #5662: unexpected axis ticks in tools.plotting.scatter_matrix
The upper left y axis tick marks in a scatter_matrix appear to have units/values pulled from the (0, 0) histogram counts, instead of the data values that are used for all other axis tick values.

Example:

```
In [1]: import numpy as np

In [2]: import pandas as pd

In [3]: pd.__version__
Out[3]: '0.12.0'

In [4]: df = pd.DataFrame(np.random.randn(100,3), columns=['a', 'b', 'c'])

In [5]: pd.tools.plotting.scatter_matrix(df)
Out[5]: 
array([[<matplotlib.axes.AxesSubplot object at 0x1071d5d90>,
        <matplotlib.axes.AxesSubplot object at 0x1089aa0d0>,
        <matplotlib.axes.AxesSubplot object at 0x1071e36d0>],
       [<matplotlib.axes.AxesSubplot object at 0x10a7d4f90>,
        <matplotlib.axes.AxesSubplot object at 0x10a7fd450>,
        <matplotlib.axes.AxesSubplot object at 0x10a8197d0>],
       [<matplotlib.axes.AxesSubplot object at 0x10a83bf90>,
        <matplotlib.axes.AxesSubplot object at 0x10a84fe50>,
        <matplotlib.axes.AxesSubplot object at 0x10a886310>]], dtype=object)
```

figure_1

### PR DESCRIPTION
**Pull request by sinhrks**
Closes #5662. Refactored a little.

Made examples to confirm 1st and 2nd row's yaxis are identical.

```
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(100, 3))
df[0] = df[1]
pd.tools.plotting.scatter_matrix(df)
```

figure_1

```
df[1] = df[1] / 3 - 2
df[0] = df[1]
pd.tools.plotting.scatter_matrix(df)
```

figure_2

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@sinhrks is there actually anything that prevents this from being merged?
cc @TomAugspurger

**Comment by sinhrks** [comment]
No, I think this is ready for review. Because it is categorized as a bug fix, is it possible to include it in 0.16.1 (not next major release)?

I'll rebase to in this later to fix the release note.

**Comment by TomAugspurger** [comment]
Thanks. Ping me when the rebase is done and I'll get it merged.

**Comment by sinhrks** [comment]
@TomAugspurger Rebased, and now green.

**Comment by TomAugspurger** [comment]
OK, thanks!

**Pull request merged**
