### PR TITLE
DOC: update styler user guide for ref to hiding cols and index and link to to_LaTeX

### PR DESCRIPTION
**Pull request by attack68**
should be backported to 1.3.0 as it references the features add there.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @attack68 web and docs is failing on rate limit exceeded. As this PR changes docs will need to re-run later to make sure this is green.

**Comment by attack68** [comment]
@simonjayhawkins this is green now

**Comment by jreback** [comment]
thanks @attack68

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
