### PR TITLE
DOC: Remove deprecated use of level for agg functions

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

ref #40869, cc @phofl

### CODE REVIEW

**Review by phofl — APPROVED** [review]
lgtm, should we remove the examples from the userguide too?

**Comment by rhshadrach** [comment]
I assumed these would give warnings when building the docs. Just took a look through and didn't find any. However, there are documented cases of `Series.sub` and `Series.div` using level. I think these are not deprecated (but maybe should be as well?)

**Comment by phofl** [comment]
Sorry I forgot this. I changed them to using groupby when deprecating the keyword

**Comment by jreback** [comment]
> I assumed these would give warnings when building the docs, and there weren't any. Just did some searching through the userguide and didn't find any. However, there are documented cases of `Series.sub` and `Series.div` using level. I think these are not deprecated (but maybe should be as well?)

`.sub` and so on are not deprecated; I think we need the level keyword (as it provides broadcasting behavior)

**Comment by jreback** [comment]
thanks @rhshadrach

**Pull request merged**
