### PR TITLE
CLN: always rebox_native in DatetimeLikeArray

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
The ASV suite marked this as a regression, opened #37462

**Comment by jbrockmendel** [comment]
ill take a look, thanks

**Comment by simonjayhawkins** [comment]
> ill take a look, thanks

@jbrockmendel will you get a chance to look into this before the 1.2.0 release?

**Comment by jbrockmendel** [comment]
that's sometime today?  ill start right now

**Comment by simonjayhawkins** [comment]
no. the actual 1.2.0 release. we will be backporting any regression fixes between 1.2.0rc0 and 1.2.0

**Comment by jbrockmendel** [comment]
Oh then for sure.

**Pull request merged**
