### PR TITLE
REF: helpers to de-duplicate datetimelike arithmetic

### PR DESCRIPTION
**Pull request by jbrockmendel**
1-2 more PRs after this using these helpers

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Review by mroeschke — CHANGES_REQUESTED** [review]
Typing failures: https://github.com/pandas-dev/pandas/actions/runs/3148299272/jobs/5131019981

**Comment by jbrockmendel** [comment]
> Typing failures: https://github.com/pandas-dev/pandas/actions/runs/3148299272/jobs/5131019981

merged master.  hopefully that'll do it since the other one is OK

**Comment by jbrockmendel** [comment]
green

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
