### PR TITLE
Pinned pycodestyle

### PR DESCRIPTION
**Pull request by WillAyd**
Fixes issues with the LINT failures as of recent. Quick fix with more permanent solutions split between #25697 and #25622

@TomAugspurger

### CODE REVIEW

**Comment by TomAugspurger** [comment]
With the latest flake8 (3.7.7) and pycodestyle=2.4.0, I get an exception

```
module 'pycodestyle' has no attribute 'maximum_doc_length
```

I'm having trouble finding which versions of flake8 are compatible with which versions of pycodestyle.

**Comment by TomAugspurger** [comment]
Ok, for reference here's what conda found

```
flake8                    3.6.0                    py37_0
pycodestyle               2.4.0                    py37_0
pyflakes                  2.0.0                    py37_0
```

and that works well.

**Review by TomAugspurger — APPROVED** [review]

**Comment by WillAyd** [comment]
@TomAugspurger all green here. Would we need to back port this as well?

**Comment by jreback** [comment]
thanks @WillAyd 

yeah this needs a backport too

**Comment by jreback** [comment]
we *may* need to patch https://github.com/macpython/pandas-wheels as well

**Pull request merged**
