### PR TITLE
Use the Agg backend for docs builds

### LINKED ISSUE #21913: Default docs builds to a non-interactive matplotlib backend
`python make.py html` fails on Mac OS in a virtualenv, using a Python interpreter installed with pyenv, because the interpreter isn't a framework build, and matplotlib defaults to using the macosx interactive backend, which requires a framework build of the interpreter.

I think the docs build doesn't require an interactive backend and it should be safe to use Agg, which is available on all platforms.

The failure looks like:
```
(pandas-dev) tsmith-0yhv2t:tsmith doc (master *)$ python make.py html
Running Sphinx v1.7.5

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/Users/tsmith/.pyenv/versions/3.6.4/envs/pandas-dev/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/Users/tsmith/.pyenv/versions/3.6.4/envs/pandas-dev/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 285, in <module>
    klass = getattr(importlib.import_module(mod), classname)
  File "/Users/tsmith/.pyenv/versions/3.6.4/envs/pandas-dev/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tsmith/upstream/pandas/pandas/io/formats/style.py", line 34, in <module>
    import matplotlib.pyplot as plt
  File "/Users/tsmith/.pyenv/versions/3.6.4/envs/pandas-dev/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/tsmith/.pyenv/versions/3.6.4/envs/pandas-dev/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/Users/tsmith/.pyenv/versions/3.6.4/envs/pandas-dev/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

### PR DESCRIPTION
**Pull request by tdsmith**
This uses a non-interactive Agg matplotlib backend to build docs, which avoids trying to use the default MacOS backend, which can fail in some environments.

Closes #21913.

### CODE REVIEW

**Comment by jreback** [comment]
@jorisvandenbossche @TomAugspurger @datapythonista

**Review by TomAugspurger — APPROVED** [review]

**Comment by datapythonista** [comment]
Looks good, tested on Linux.

I was just guessing whether it'd be possible to set an environment variable in `conf.py` instead of creating a new file. Not a big deal, but there are already many files in `doc/source` and if it's the same, I'd prefer changing `conf.py` than adding a new file.

I'd say this link is about the same problem: https://stackoverflow.com/questions/25124977/cant-use-sphinxs-matplotlib-extension-with-qt-on-os-x#25164523

What do you think @tdsmith ?

**Comment by jorisvandenbossche** [comment]
Just to check, this has no influence on how the figures look in the docs? (the quality)

**Comment by datapythonista** [comment]
No quality difference that I can spot:

screenshot at 2018-07-16 14-53-38

**Comment by jorisvandenbossche** [comment]
I would also assume this can be set in `conf.py`

**Review by datapythonista — APPROVED** [review]
Thanks @tdsmith, lgtm.

**Comment by tdsmith** [comment]
Thanks for the review, all! I just realized you asked for conf.py and not make.py -- it works for me in either place; AFAICT tweaking the environment is still the right thing to do in either place.

**Comment by jreback** [comment]
thanks @tdsmith

**Pull request merged**
