### PR TITLE
TST: Un-xfail tests on numpy-dev

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Makes 3.8 npdev green.

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jbrockmendel** [comment]
@simonjayhawkins @jreback are we still in a merge moratorium?  i think this fixes one of our broken builds

**Comment by jreback** [comment]
no this is fine (just needing to backport any 1.3 things)

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
