### PR TITLE
Replace str::replace hack for getting module name from ImportError in __init__.py

### PR DESCRIPTION
**Pull request by a2435191**

### CODE REVIEW

**Comment by jreback** [comment]
this looks fine, i doubt we actually test this line, can you confirm that this prints a nice message

**Comment by 2435191** [comment]
Like this?
```
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> try:
...     import mymoduleisntloaded
... except ImportError as e:
...     module = e.name
...     raise ImportError(
...             f"C extension: {module} not built. If you want to import "
...             "pandas from the source directory, you may need to run "
...             "'python setup.py build_ext --force' to build the C extensions first."
...     ) from e
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'mymoduleisntloaded'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
ImportError: C extension: mymoduleisntloaded not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --force' to build the C extensions first.
```

**Comment by jreback** [comment]
can you merge master just to make this this didn't affect anything.

**Comment by jreback** [comment]
thanks @2435191

**Pull request merged**
