### PR TITLE
Bug: DataFrame.clip fixed for lower > upper

### LINKED ISSUE #52147: BUG: df.clip does not handle inverted lower/upper bounds consistently
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
data = {'A': [-2, -1, 0, 1, 2], 'B': [-2, 1, 0, 1, 2]}
df = pd.DataFrame(data)
df
	A	B
0	-2	-2
1	-1	1
2	0	0
3	1	1
4	2	2
df.clip(lower=10, upper=[1,1])
A	B
0	10	10
1	10	10
2	10	10
3	10	10
4	1	1
```

### Issue Description

This is undocumented behavior; but when upper is < lower, and upper is not a scalar the resulting data frame is not consistently producing the same results. If lower is an array, and upper is a scalar the values are fixed at whatever the scalar upper is.

I'm not sure if pandas should simply throw an error when the bounds are inverted, or what - but some consistency would be helpful.

### Expected Behavior

Either throw an error when upper < lower or have a consistent way to handle the result between scalar and list-like things.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.4.0
Version          : Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.6.0
pip              : 23.0
Cython           : None
pytest           : 7.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.10.0
pandas_datareader: None
bs4              : 4.11.2
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 2.0.4
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : 0.19.0
tzdata           : None
</details>

### PR DESCRIPTION
**Pull request by m-ganko**
Fixed behavior of DataFrame.clip for `lower` > `upper` arguments. Changed to be consistent with numpy - all equal to `upper`. Main reason of bug was undocumented swap of arguments for scalars and for list-like arguments comparison with initial DataFrame for both bounds.

- [x] closes #52147 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by m-ganko** [comment]
Looks like some tests are failing after merging in main branch. I will look at this.

**Comment by m-ganko** [comment]
It is worth mentioning that `Series.clip` also works in the same way as `numpy.clip`. I think it is rather logical result, in first step we are clipping lower numbers, in second step upper numbers. We end up with all numbers equal to `upper`.

Another similar example from pandas api, `pandas.date_range` - when we pass `start` > `end` there is no exception, but empty `DatetimeIndex`.

**Comment by mroeschke** [comment]
> Another similar example from pandas api, pandas.date_range - when we pass start > end there is no exception, but empty DatetimeIndex.

`pd.date_range` makes sense to be more flexible in this sense because the `freq` can be negative allowing start > end to make sense

**Comment by m-ganko** [comment]
I have started implementation and I think there is too much to make validation for scalars, lists and DataFrame arguments. 

So if you insist on doing this, I can close this PR and unassign from issue.

**Comment by mroeschke** [comment]
I would suggest closing this PR now until there is some consensus on the main issue on how to handle this scenario

**Pull request closed without merging**
