### PR TITLE
Fix issue with Tempita recompilation

### PR DESCRIPTION
**Pull request by WillAyd**
xref https://github.com/mesonbuild/meson-python/issues/589#issuecomment-1987206217 @rhshadrach I think you mentioned this originally on Slack

### CODE REVIEW

**Review by rhshadrach — APPROVED** [review]
Nice - lgtm. I've confirmed that when compiling twice with this branch nothing is compiled the 2nd time.

**Comment by rhshadrach** [comment]
@lithomas1 - thought you might want to review.

**Comment by lithomas1** [comment]
No objections here - I think adding the files as sources was originally a hack to workaround a bug in meson.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @WillAyd

**Comment by WillAyd** [comment]
The more I have used this the less I am sure that it actually fixed the issue. Whenever I edit a tempita file now it does _not_ trigger a recompilation as it should

**Pull request merged**
