### PR TITLE
troubleshoot CI failing Linux py36_32bit

### LINKED ISSUE #28829: CI failing Linux py36_32bit
https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=18548

attrs 19.1 -> 19.2

https://github.com/pytest-dev/pytest/issues/5903

### PR DESCRIPTION
**Pull request by simonjayhawkins**
closes #28829

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@TomAugspurger there's probably a reason pytest was pinned. if not successful we should add attrs to dependencies and pin attrs?

**Comment by simonjayhawkins** [comment]
ok so the pytest pin makes no difference. pytest 4.0.2 installed.

**Comment by simonjayhawkins** [comment]
so pytest is now running. merge on green? @pandas-dev/pandas-core

**Comment by jreback** [comment]
this is ok

**Comment by TomAugspurger** [comment]
FYI, these CI fixups should typically be backported. Doing so in https://github.com/pandas-dev/pandas/pull/28999.

**Pull request merged**
