### PR TITLE
CI: Test clipboard on Linux via pyqt

### LINKED ISSUE #52129: DEPR: to_clipboard
Discussed briefly in #52020.  At least some of the relevant tests are xfailed (though they are xpassing locally for me on mac).  Might just be "wide unicode"?

`pandas.io.clipboard.__init__` looks like it is adapted from "pyperclip".  Is there a real need for this to live in pandas?

xref #45433 similar suggestion for s3 support

### PR DESCRIPTION
**Pull request by mroeschke**
closes https://github.com/pandas-dev/pandas/issues/52129

### CODE REVIEW

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @mroeschke

**Comment by jbrockmendel** [comment]
I just got a segfault locally (mac) in the clipboard tests.  will keep track of it here if it recurs

**Comment by jbrockmendel** [comment]
Again 2023-12-14 17:48

**Comment by mroeschke** [comment]
Is there a particular test where is always fails at? Does this occur when you just run the tests over all of `pandas/tests`?

**Comment by jbrockmendel** [comment]
I don't know, current hypothesis is it involves running the tests in more than one branch at a time

**Comment by jbrockmendel** [comment]
Just got it again. Was running tests in a bunch of windows at the time.

**Pull request merged**
