### PR TITLE
BUG: fix json_normalize with meta far different from record_path

### PR DESCRIPTION
**Pull request by Opostol**
- fix of json_normalize when record_path long and meta path far different from record_path
- 1 test added and passed

### CODE REVIEW

**Comment by mroeschke** [comment]
Is there an associate GIthub issue for this PR?

**Comment by Opostol** [comment]
> Is there an associate GIthub issue for this PR?

no. Should i create one with minimal reproducible example?

**Comment by Opostol** [comment]
`result = pd.json_normalize(data={'meta1':{'meta2':'meta_val'}, 'record1':{'record2':[{'rec1':'rec_val1'},{'rec1':'rec_val2'}]}}, meta=[['meta1','meta2']], record_path=['record1','record2'])` falls into exception `KeyError: "Key 'meta2' not found.`

**Comment by mroeschke** [comment]
> no. Should i create one with minimal reproducible example?

Yes, it would give more context why this fix is needed

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
