### PR TITLE
INT: Implement _set_freq for TDI/DTI

### LINKED ISSUE #29843: REF: internal method to set DatetimeIndex freq
xref #29801 we currently have a number of places where we do something like `dti._data._freq = new_freq` (where we have already validated `new_freq`), we should have some private method to do this.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #29843
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by topper-123** [comment]
In #29604 I had to do the same methods twice for ``DateTimeIndex.difference`` and ``TimeDeltaIndex.difference``, because ``PeriodIndex.difference`` worked differently.

Could you see if it works to add a difference method here and remove the other two?

**Review by jreback — APPROVED** [review]
lgtm.

**Comment by jbrockmendel** [comment]
> Could you see if it works to add a difference method to this MixIn and remove the other two?

Yes, in a follow-up I plan to see what else can be de-duplicated

**Review by topper-123 — APPROVED** [review]

**Comment by topper-123** [comment]
Thanks, @jbrockmendel .

**Pull request merged**
