### PR TITLE
DOC: fix quotes for index and column

### PR DESCRIPTION
**Pull request by DJCordhose**

### CODE REVIEW

**Comment by gfyoung** [comment]
We only use the doubleticks if we are referring to an actual variable or function.  In this case, we are accepting the string "index" and "column"

**Comment by gfyoung** [comment]
@DJCordhose : Unless you have any objections, I will close this PR because the change isn't actually what we are looking.  Sorry about that! 😢

**Comment by DJCordhose** [comment]
@gfyoung how would you make the change? I am happy to change my PR.

**Comment by gfyoung** [comment]
@DJCordhose : This is no change.  The documentation is good as is.

**Comment by gfyoung** [comment]
I don't want to discourage you from finding ways to contribute, so keep prying through the documentation!  I'm pretty sure you'll find other ways to improve it!

**Comment by DJCordhose** [comment]
Oh, maybe I did not make my point clear, the generated documentation has broken quotes. 

Looking at 

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html

the quotes look like

‘index’

but should be

'index'

**Comment by gfyoung** [comment]
I'm not sure I follow you here: the quotation marks look okay to me.

**Comment by DJCordhose** [comment]
Try and copy past them from the web site into your code. I am not sure if they are properly displayed on this PR.

**Comment by gfyoung** [comment]
I see the following:

<left-quotation-mark>index<right-quotation-mark>

The same for `column` for all cases.

**Comment by DJCordhose** [comment]
This is what you find on the website

<li>0 or ‘index’: apply function to each column</li>
<li>1 or ‘columns’: apply function to each row</li>

Please note the broken quotes. Those are not python quotes. This is the generation result after the change. Please note the quotes that are not proper Python quotes. 

<li>0 or <code class="docutils literal"><span class="pre">'index'</span></code>: apply function to each column</li>
<li>1 or <code class="docutils literal"><span class="pre">'columns'</span></code>: apply function to each row</li>

**Comment by DJCordhose** [comment]
broken
fixed

**Comment by gfyoung** [comment]
Those quotation marks are perfectly fine, as we were not aiming for Python quotes necessarily.  We don't double-tick allowed string-inputs, and that's the standard for us.

**Comment by DJCordhose** [comment]
I thought I directly copied this from other places within pandas, like e.g.

https://github.com/pandas-dev/pandas/blob/master/pandas/io/json/json.py#L194

I am happy to be corrected here

**Comment by gfyoung** [comment]
That's a fair point.  We do have exceptions!  In that case, because we have a bullet-point list, we would like to indicate what part comes before the colon for readability.

**Comment by TomAugspurger** [comment]
It'd be good to quote them so it's easier to copy-paste into the interpreter.

**Comment by gfyoung** [comment]
> It'd be good to quote them so it's easier to copy-paste into the interpreter.

@TomAugspurger : Okay, but how much of a use-case is there for this?  Mind you, a doc-change like this should be applied to every function not only in this file but any function that involves string inputs.

**Comment by DJCordhose** [comment]
@gfyoung 
I thought it is inconsistent anyway. There are many examples where string constants are escaped the way I propose all over the code base. Changing all the spots in one go might be a bad idea, but would you not agree that having them quoted properly is a better idea than not having them quoted properly in general?

**Comment by gfyoung** [comment]
> I thought it is inconsistent anyway. There are many examples where string constants are escaped the way I propose all over the code base.

It would be helpful if you could point to several locations that you found inconsistent, as I can only think of ones where we use non-Python quotation marks, such as `read_csv` and `DataFrame.merge`.

> Changing all the spots in one go might be a bad idea, but would you not agree that having them quoted properly is a better idea than not having them quoted properly in general?

Actually, given that it should not impact the code that much, trying to tackle as many as possible on PR (especially just these in this file) would be reasonable.

I see where you're trying to go with that question, but as I said before, I don't find those quotes to be quoted "badly" (AFAIK, we've never said anything about non-Python quotes being "bad" quotes in the documentation).  That's why I pushed back against this change.

**Comment by gfyoung** [comment]
Test failure on Appveyor unrelated to PR.

**Comment by gfyoung** [comment]
@TomAugspurger : your thoughts?

**Comment by DJCordhose** [comment]
I would also say that either do it everywhere or nowhere. Closing the PR.

**Pull request closed without merging**
