### PR TITLE
DOC: include Offset.__call__ to autosummary to fix sphinx warning

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@datapythonista is this the right way to fix the doc build?

**Comment by datapythonista** [comment]
I'm not sure, sphinx still confuses me with those. @jorisvandenbossche knows better.

**Comment by jorisvandenbossche** [comment]
It clearly fixes it, because CI is green ;)

Now, the actual answer: it depends. Are we fine with including the `__call__` docstring? Is this considered public / documented in the user guide?

**Comment by jreback** [comment]
> It clearly fixes it, because CI is green ;)
> 
> Now, the actual answer: it depends. Are we fine with including the `__call__` docstring? Is this considered public / documented in the user guide?

these *are* public methods.

**Comment by jorisvandenbossche** [comment]
Then the fix is fine

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks @jbrockmendel !

**Comment by simonjayhawkins** [comment]
@Meeseeksdev backport to 1.0.x

**Pull request merged**
