### PR TITLE
DEPR: passing timedelta-like to DatetimeIndex constructor, xref #23675

### PR DESCRIPTION
**Pull request by jbrockmendel**
Implements the agreed-upon portions of #23675 so we can keep moving the ball down the field.

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. add to #6581 ping on green.

**Comment by jbrockmendel** [comment]
azure failure is Hypothesis.  de-facto green ping

**Comment by jreback** [comment]
thanks. do we need to simply raise the timeout on hypthossis?

**Comment by jbrockmendel** [comment]
> do we need to simply raise the timeout on hypthossis?

I think I saw a PR for that recently.  Didn't look at it too closely.  If I'm going to spend time on one minor annoyance today, it'll be the dateutil DeprecationWarning.

**Pull request merged**
