### PR TITLE
ADMIN: Auto-label PRs for review

### PR DESCRIPTION
**Pull request by dsaxton**
Not certain this will work, but nonetheless I think something like this would be helpful (analogous to "Needs Triage" for issues)

### CODE REVIEW

**Comment by rhshadrach** [comment]
At what point does the "Needs Review" tag get removed?

**Comment by dsaxton** [comment]
> At what point does the "Needs Review" tag get removed?

I think it'd be the judgement of whoever is doing the reviewing, but initial thought is to take it down as soon as initial feedback is given (so the label means something like "not yet looked at"; so you could untag this one 😄). I'm imagining a way of making it easier to do "visual triage" when looking at the PR list (and also to have meaningful exemptions if the linked stale PR action gets merged).

**Comment by rhshadrach** [comment]
That makes sense. I might even think of going further, to untag if the PR "has legs". That is, if it appears to be going in the right direction, even if more refinement is needed.

**Comment by simonjayhawkins** [comment]
I'm happy with this in principal since sometimes I look at the PR list for PRs without comments but that misses PRs where the author has added additional comments outside the OP.

**Review by WillAyd — APPROVED** [review]
Sure I see no harm in trying this out

**Comment by jreback** [comment]
sure

**Pull request merged**
