### PR TITLE
Wrote test for Issue#29576 with resampling in non-unitary quarters

### LINKED ISSUE #29576: startingMonth ignored on non-unitary Quarter periods
#### Code Sample

```python
import pandas as pd
import numpy as np

d = pd.Series(data=np.zeros(365), 
                       index=pd.date_range('1950-01-01', '1950-12-31', freq='D'))
d.resample('2QS-MAR').mean()
```
returns:
```
1949-12-01    0.0
1950-06-01    0.0
1950-12-01    0.0
Freq: 2QS-MAR, dtype: float64
```
But as I explicitly asked for 2 Quarters starting in March, I expected:
```
1949-09-01    0.0
1950-03-01    0.0
1950-09-01    0.0
Freq: 2QS-MAR, dtype: float64
 ```

So, when specifying a multiple, the first time still goes to the closest single quarter before.

Not really a duplicate, but closely related to #22362.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-66-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : fr_CA.UTF-8
LOCALE           : fr_CA.UTF-8

pandas           : 0.25.3
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 39.0.1
Cython           : None
pytest           : 5.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : 0.13.0
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

### PR DESCRIPTION
**Pull request by joshdelg**
- [ ] closes #29576
- [ ] Added test to `tests/resample/test_datetime_index.py` following expected and actual output of original commenter
- [ ] All [code checks passed] (https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
Looks like the tests are failing, and `Mambaforge-Darwin-x86_64.sh` was accidentally committed

**Comment by joshdelg** [comment]
Noticed the tests failed, I don't think the issue was fixed. Is the the expected output given in the issue description what the test should anticipate?

**Comment by mroeschke** [comment]
I don't think `expected` is correctly constructed to match https://github.com/pandas-dev/pandas/issues/29576#issue-521751237

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
