### PR TITLE
CLN: Remove u and u_safe from pandas.compat

### PR DESCRIPTION
**Pull request by jschendel**
- [X] xref #25725
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Another incremental step in removing Python 2.  Only non-standard changes were to `pandas/tests/test_strings.py` where I deleted a bunch of code, as removing `u` resulted in duplicate test scenarios.

### CODE REVIEW

**Comment by jreback** [comment]
can we remove unicode strings themselves if they e.g. u'....'?

**Comment by jschendel** [comment]
> can we remove unicode strings themselves if they e.g. u'....'?

Yeah, I was thinking that seemed better suited for a separate PR since, after a quick check, there looks to be 1000+ instances of it, and I didn't want to jam too much into a single PR.  Can do it here if you'd prefer.

**Comment by jreback** [comment]
separate is good!

**Review by WillAyd — APPROVED** [review]
lgtm - thanks @jschendel that was a lot!

**Comment by jreback** [comment]
thanks @jschendel  keep em coming!

**Pull request merged**
