### PR TITLE
CLN: remove arrmap, closes #27251

### LINKED ISSUE #27251: CLN: Can we remove libalgos.arrmap_*?
Discussed in #27236, after that there will be only one non-test usage of libalgos.arrmap_* and it looks like it may be feasible to just use np.vectorize.  Check if this is correct and if there is a perf impact.

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
This removes the dependency of this module on non-cython parts of the code (and the circular dependency with _libs.lib)

**Comment by simonjayhawkins** [comment]
https://github.com/pandas-dev/pandas/issues/27251#issue-464667280 was it not feasible to just use np.vectorize? is there is a perf impact?

**Comment by jbrockmendel** [comment]
> feasible to just use np.vectorize?

Probably.  My understanding was that is just a fancy for-loop.  Am I missing something?

> is there is a perf impact?

Haven't measured.  On the one hand we get rid of a call to lib.maybe_convert_objects (and a semi-expensive runtime import), and on the other we do a python-space list comprehension.  My assumption is that this isn't called with particularly large arrays for the quantile arg.

One alternative would be to keep arrmap_float64 and specialize it given that we know the output will be float64.  We'd still get to remove the maybe_convert_objects call, which is what I'm most excited about.

**Comment by simonjayhawkins** [comment]
> > feasible to just use np.vectorize?
> 
> Probably. My understanding was that is just a fancy for-loop. Am I missing something?

so according the numpy docs, The vectorize function is provided primarily for convenience, not for performance. so I guess that using a list comprehension is a sensible approach. 

> Haven't measured. On the one hand we get rid of a call to lib.maybe_convert_objects (and a semi-expensive runtime import), and on the other we do a python-space list comprehension. My assumption is that this isn't called with particularly large arrays for the quantile arg.
> 
> One alternative would be to keep arrmap_float64 and specialize it given that we know the output will be float64. We'd still get to remove the maybe_convert_objects call, which is what I'm most excited about.

i'll leave that to you to decide if its worth further investigation.

**Comment by jreback** [comment]
@simonjayhawkins yeah we talked about this in a previous issue. *even* if this was a measureable slowdown, would still take it in reducing complexity.

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
