### PR TITLE
set eval(engine="python") for python2

### PR DESCRIPTION
**Pull request by shouldsee**
see issue https://github.com/pandas-dev/pandas/issues/26549

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
this would require a release of the 24.x series. This is not contemplated at the current time. Further I am not even sure this is a good change, what is the reason?

**Comment by shouldsee** [comment]
> this would require a release of the 24.x series. This is not contemplated at the current time. Further I am not even sure this is a good change, what is the reason?

Bascially `eval(engine="numexpr")` is broken on python2-pandas

To reproduce with Python 2.7.12

```python
## !pip2 install numexpr==2.6.9 --user
import pandas as pd
dfc = pd.DataFrame(map(str,range(10)),columns=['colA'])
dfc.query('colA.str.contains("0")',engine="numexpr")
```

**Comment by jreback** [comment]
> Bascially eval(engine="numexpr") is broken on python2-pandas

and python 2 is not longer supported. So I am not completely objecting to merging this (though it would require some tests / note and such). But pointing out that a release may not be happening for far in the future.

**Comment by shouldsee** [comment]
> > Bascially eval(engine="numexpr") is broken on python2-pandas
> 
> and python 2 is not longer supported. So I am not completely objecting to merging this (though it would require some tests / note and such). But pointing out that a release may not be happening for far in the future.

Thanks for explaining this to me. I don't care too much about the release, just wanting to make people aware that this bug exists and there are ways to circumventing it so that they don't have to repeat my frustrating debugging practice :smiley: .

**Comment by jreback** [comment]
ok as we have no plans for further PY2 support, closing.

**Pull request closed without merging**
