### PR TITLE
DEPR: tz kwarg in Period.to_timestamp

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

inconsistent with PeriodArray/PeriodIndex methods

### CODE REVIEW

**Comment by jreback** [comment]
pls add this to the deprecation removal issue

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
Is there a motivation?

**Comment by jbrockmendel** [comment]
> Is there a motivation?

As mentioned in the OP, its inconsistent with the PeriodArray/PeriodIndex methods.

**Comment by jorisvandenbossche** [comment]
Whoops, sorry, missed that sentence.

Now, this keyword doesn't seem really a burden to me, so I still don't find that a fully convincing reason (could it be added to the array method?)

Also, it seems we are using this feature internally in pandas, according to the test failure.

**Comment by jorisvandenbossche** [comment]
> Also, it seems we are using this feature internally in pandas, according to the test failure.

It's in `timeseries.py`. It can of course easily be fixed there to use `tz_localize`

**Comment by jbrockmendel** [comment]
> Now, this keyword doesn't seem really a burden to me, so I still don't find that a fully convincing reason (could it be added to the array method?)

Either way works.  My default is to prefer a smaller API surface, but not a strong preferenc.

Note also that Period.to_timestamp incorrectly ignores the tz arg in the how == 'end' case, so i see it as deprecating a broken feature.

**Comment by jreback** [comment]
agree with @jbrockmendel here; simpler is better, we *always* convert to naive, which is inline the model of Periods which are naive by definition.

**Comment by jorisvandenbossche** [comment]
OK, if it's only partly implemented, that's certainly another reason to deprecate it

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request merged**
