### PR TITLE
WIP: add pd.read_ipc and DataFrame.to_ipc to provide efficient serialization to/from memory

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by jreback** [comment]
cc @mrocklin
@wesm @cpcloud

**Comment by chris-b1** [comment]
Given that this is a pretty 'advanced' feature (and presumably an unstable format?), maybe would make sense to expose these functions somewhere like `pandas.api.lib` rather than in the main namespace?

**Comment by jreback** [comment]
@chris-b1 yeah probably. This is just trying to get working (today) locally. :>

**Comment by wesm** [comment]
I agree putting such things into an experimental namespace would be a good idea

**Comment by jorisvandenbossche** [comment]
Genuine question: since we are typically trying to limit pandas' scope, why should we include this in the core package? Instead of having this live in the package implementing this / a separate package ('pandas-ipc') providing this API?

**Comment by jreback** [comment]
> Genuine question: since we are typically trying to limit pandas' scope, why should we include this in the core package? Instead of having this live in the package implementing this / a separate package ('pandas-ipc') providing this API?

True, we are trying to limit scope. This is essentialy an ipc version of ``arrow`` (which also back ``feather``). So this ATM expands scope, though eventually would limit it somewhat (as the back-end would have less tooling).

Could consider this as ``pandas-ipc`` though this is pretty 'simple' and not meant as a full-fledged package, mostly a passthru / convenient interface for others (e.g. dask).

**Comment by wesm** [comment]
I think it would be useful for pandas to have more robust support for various transient serialization formats, with a choice between pickle (most compatible) vs msgpack vs arrow vs other things. Whether the implementation of this goes into core pandas, or into a "leaf" library that gets imported, I don't have a strong opinion

**Comment by jreback** [comment]
closing for now. This will be pretty transparent with ``pyarrow``, so this interface would just be a simple wrapper. let's see if its even needed.

**Comment by jreback** [comment]
so this is now available in a released version in arrow: https://arrow.apache.org/docs/python/ipc.html (IIRC 0.5.0 has full support). appetite for this in main pandas as ``read_ipc/to_ipc`` ?

@wesm @cpcloud @jorisvandenbossche

**Comment by wesm** [comment]
Depending on what memory format these functions create it may affect the name. If it's vanilla arrow stream (schema + sequence of record batches), then it might be better to call it `read_arrow_stream` / `to_arrow_stream` (in the latter case, you could select a batch size to use for chunking the DataFrame once someone implements this)

**Pull request closed without merging**
