### PR TITLE
Add gitpython to requirements

### LINKED ISSUE #26142: dev-requirements missing 'gitpython'
`python make html` fails without gitpython, which currently doesn't install from dev-requirements.

### PR DESCRIPTION
**Pull request by ExSidius**
- [X] closes #26142
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
why are you adding this?

**Comment by ExSidius** [comment]
@jreback the command `python make.py html` was failing because gitpython wasn't installed in requirements.

**Comment by jreback** [comment]
you must have an old version: https://github.com/pandas-dev/pandas/blob/master/requirements-dev.txt

**Comment by ExSidius** [comment]
@jreback You're right. Sorry about that.

**Pull request closed without merging**
