### PR TITLE
WEB: Fix extension of about/index

### LINKED ISSUE #29325: WEB: about/index has the extension wrong
xref: https://github.com/pandas-dev/pandas/issues/28580#issuecomment-548876428

Looks like the file `web/pandas/about/index.html` has the wrong extension `.html`, since it's a markdown file and should be `.md`. This is causing that the file is not rendered as html but left untouched in the website: https://dev.pandas.io/about/index.html

### PR DESCRIPTION
**Pull request by est271**
- [✓] closes #29325
- [✓] whatsnew: the about/index.html file is now about/index.md

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm

@est271 did you generate the website locally to see if this page is looking all right?

You can do it by running `python pandas_web.py pandas` in the web directory, and starting a server with `python -m http.server` from the `web/build` directory.

If you want to upload a screenshot of the page, I'll be able to help check whether everything looks ok.

Thanks for the help on this.

**Comment by est271** [comment]
@datapythonista 
Here is a screenshot of the page that was generated locally. I just noticed that the URL shows the .html extension at the end. Should it be .md or is it ok as shown?

Screenshot_index_html

**Comment by datapythonista** [comment]
Thanks, looks perfect now. The extension in the web needs to be html, we convert markdowns to html if they have the right extension.

This is ready, will let someone else from the team review and merged.

Thanks for the fix!

**Comment by jreback** [comment]
lgtm. merge when ready.

**Comment by datapythonista** [comment]
Sorry for the delay @est271 and thanks a lot for your contribution. Hope to see more coming!

**Comment by est271** [comment]
@datapythonista No worries. Glad to help.

**Pull request merged**
