### PR TITLE
DEPS: Bump Cython

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] xref #41935 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Remember to also merge MacPython/pandas-wheels#181 too (I would recommend against merging this if you don't have write perms there as well, as we merge these too at the same time ideally).

### CODE REVIEW

**Comment by jreback** [comment]
thanks @lithomas1

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by simonjayhawkins** [comment]
> Remember to also merge [MacPython/pandas-wheels#181](https://github.com/MacPython/pandas-wheels/pull/181) too (I would recommend against merging this if you don't have write perms there as well, as we merge these too at the same time ideally).

do we need to update the pandas-feedstock for the conda packages? https://github.com/conda-forge/pandas-feedstock/pull/134 recently updated `cython >=0.29.16` to `cython >=0.29.24,<3`

**Comment by simonjayhawkins** [comment]
> Remember to also merge [MacPython/pandas-wheels#181](https://github.com/MacPython/pandas-wheels/pull/181) too

that PR closed #41935

test_read_csv_and_table_sys_setprofile is still skipped?

**Comment by lithomas1** [comment]
> do we need to update the pandas-feedstock for the conda packages? [conda-forge/pandas-feedstock#134](https://github.com/conda-forge/pandas-feedstock/pull/134) recently updated `cython >=0.29.16` to `cython >=0.29.24,<3`

This should be done whenever 1.4.3 comes out.

> > Remember to also merge [MacPython/pandas-wheels#181](https://github.com/MacPython/pandas-wheels/pull/181) too
> 
> that PR closed #41935
> 
> test_read_csv_and_table_sys_setprofile is still skipped?

Thanks for the reminder, will update.

**Pull request merged**
