### PR TITLE
DOC: further clean-up null/na changes

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Old whatsnew example was failing -> converted to static code-block

(+ some additional minor fixes)

### CODE REVIEW

**Comment by gfyoung** [comment]
> Old whatsnew example was failing -> converted to static code-block

Just curious, do you know why it was failing?

**Review by gfyoung — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
> Just curious, do you know why it was failing?

Ah, good question. As it should be supposed to raise a warning instead of raise I think? (that's at least what it says in the whatsnew notice)

**Comment by jorisvandenbossche** [comment]
@jreback 

```
In [24]: pd.set_option('use_inf_as_null', True)
...
OptionError: "No such keys(s): 'use_inf_as_null'"

In [25]: pd.options.mode.use_inf_as_null
...
KeyError: 'use_inf_as_null'
```

those should issue a warning instead?

**Comment by jorisvandenbossche** [comment]
Opened In [24]: pd.set_option('use_inf_as_null', True)
...
OptionError: "No such keys(s): 'use_inf_as_null'"

In [25]: pd.options.mode.use_inf_as_null
...
KeyError: 'use_inf_as_null' to keep track of this

**Comment by jorisvandenbossche** [comment]
Opened https://github.com/pandas-dev/pandas/issues/17115 to keep track of this

**Pull request merged**
