### PR TITLE
DEPR: special-casing PeriodDtype in Series.where/Series/mask fallback

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
doesn't this overlap with #45193 ?

**Comment by jbrockmendel** [comment]
> doesn't this overlap with #45193 ? IOW we should either merge both or neither for 1.4

It does overlap, yes.  My expectation is that #45193 wont make it in time for 1.4.

**Comment by jreback** [comment]
> > doesn't this overlap with #45193 ? IOW we should either merge both or neither for 1.4
> 
> It does overlap, yes. My expectation is that #45193 wont make it in time for 1.4.
> 
> > IOW we should either merge both or neither for 1.4
> 
> No. This should be done especially if we dont do 45193.

got it

**Comment by jbrockmendel** [comment]
we could plausibly call this a bugfix on the grounds that `Series.mask(..., inplace=True)` coerces while `Series.mask(..., inplace=False)` raises is inconsistent

**Comment by jbrockmendel** [comment]
closing in favor of #45546

**Pull request closed without merging**
