### PR TITLE
CLN: Clean frame/test_constructors.py

### PR DESCRIPTION
**Pull request by dsaxton**
I think these classes are all imported directly so don't need to reference the pandas namespace

### CODE REVIEW

**Comment by WillAyd** [comment]
OK as a one off, though @jorisvandenbossche I think and I generally prefer the way things are here. 

I know @jreback disagrees and prefers what you've done, but we don't have a consensus to do things like this generally

**Comment by dsaxton** [comment]
> OK as a one off, though @jorisvandenbossche I think and I generally prefer the way things are here.
> 
> I know @jreback disagrees and prefers what you've done, but we don't have a consensus to do things like this generally

I was thinking the tests might run ever so slightly faster if we refer to (for example) `Series` instead of `pd.Series` when it's already imported

**Comment by jreback** [comment]
what I don't want are *mixed* uses in a single file, IOW ``pd.Series`` and ``Series`` are not good. slight preference to using ``Series``,  but wouldn't wholesale change things.

**Comment by jreback** [comment]
> I was thinking the tests might run ever so slightly faster if we refer to (for example) `Series` instead of `pd.Series` when it's already imported

this is not a consideration at all. In testing its all about coverage and clarity, while being as concise as possible.

**Comment by jorisvandenbossche** [comment]
> OK as a one off, though @jorisvandenbossche I think and I generally prefer the way things are here.

That's correct 
(in general we should for sure try to use the public namespeace where possible in tests. Of course, `from pandas import Series` and `import pandas as pd` are both perfectly fine public ways to access Series in this case (on constract to eg `from pandas.core.series import Series`). But using `pd` for top-level objects is closer to how I (and I think most contributors) typically code, and avoids long imports)

Also agreed with @jreback that consistency within a file is more important.

**Review by WillAyd — APPROVED** [review]
having stated above this lgtm

**Comment by jreback** [comment]
thanks @dsaxton

**Pull request merged**
