### PR TITLE
Fix type annotation for pandas.core.indexes.base

### LINKED ISSUE #26363: Fix type annotations for pandas.core.indexes.base
Part of #25882 

Current errors are:

    pandas\core\indexes\base.py:9: error: Module 'pandas._libs' has no attribute 'join'

### PR DESCRIPTION
**Pull request by vaibhavhrt**
- [x] closes #26363 
- [x] tests passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
Looks like an isort error - can you fix up and merge master?

**Comment by vaibhavhrt** [comment]
There is an isort error in a file that I haven't even touched. Merging upstream/master should fix it.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Nice work @vaibhavhrt

**Comment by vaibhavhrt** [comment]
@WillAyd thanks.

**Pull request merged**
