### PR TITLE
DOC: fix URLs, formatting and typos

### PR DESCRIPTION
**Pull request by partev**
"## Development tools" is not formatted correctly here: https://pandas.pydata.org/community/ecosystem.html
Screenshot 2022-02-10 10 22 42

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks @partev - btw, if you have many more changes like these, it's OK to group them together into the same PR

**Comment by attack68** [comment]
> Thanks @partev - btw, if you have many more changes like these, it's OK to group them together into the same PR
> 
> 

yes, please don't fill up the PRs with a number of one line typos fixes. 

It is probably better to close the other PRs and include them all here. Thx

**Comment by jreback** [comment]
thanks @partev

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
