### PR TITLE
REF: Period check compatabile with

### PR DESCRIPTION
**Pull request by TomAugspurger**
Split from #24024 

cc @jbrockmendel 

There are a couple cases in `PeriodArray.__setitem__` that I didn't update, because `PeriodArray.__setitem__` is being remove entirely in #24024.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. merge on green.

**Comment by jbrockmendel** [comment]
Travis fail is hypothesis

**Comment by TomAugspurger** [comment]
Yep, ignoring it though I'll keep my eye on the merge build.

**Comment by jbrockmendel** [comment]
There are 5 places in indexes.period where DIFFERENT_FREQ/IncompatibleFrequency are used. Should these dispatch to self._data._check_compatible_with?

**Comment by TomAugspurger** [comment]
Seems reasonable to me.

**Pull request merged**
