### PR TITLE
DOC: "Next" link from user_guide/io.rst goes to read_sql_table API pa…

### PR DESCRIPTION
**Pull request by souvik3333**
…ge (#30332)

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Can you post a screenshot of what the "Next" text looks like when you build it locally?

**Comment by souvik3333** [comment]
Screenshot from 2019-12-19 22-07-11
Here is the screenshot.

**Review by TomAugspurger — APPROVED** [review]
Thanks! Looks great.

**Comment by WillAyd** [comment]
Thanks @souvik3333

**Pull request merged**
