### PR TITLE
DEPR `fill_method` and `limit` keywords in `pct_change`

### LINKED ISSUE #53491: DEPR: pct_change method/limit keyword
We should deprecate these and have users do obj.fillna(...).pct_change() instead.

### PR DESCRIPTION
**Pull request by Charlie-XIAO**
- [ ] Closes #53491
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests)
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit)
- [x] Added an entry in the latest `doc/source/whatsnew/v2.1.0.rst` file

### CODE REVIEW

**Review by rhshadrach — CHANGES_REQUESTED** [review]
This would be good if the default for `fill_method` was `None`. However, it is currently "pad". When the deprecation is enforced, I _think_ we'll want the behavior to be `None` instead. This means we first need to deprecate/change the result, and then once that's done we can deprecate the argument.

**Comment by Charlie-XIAO** [comment]
Can these be done in a single PR or in separate PRs?

**Comment by rhshadrach** [comment]
I don't think these can be done in a single major version. In 2.x we deprecate the default; in 3.x we can then change the default to None. Finally in 3.x we can also deprecate the arguments and in 4.x we can remove them.

**Comment by Charlie-XIAO** [comment]
@rhshadrach I have updated the PR to deprecate only the default value of `fill_method`. Not sure if I'm doing correctly, so please let me know if I should make changes.

**Comment by jbrockmendel** [comment]
I disagree with @rhshadrach that this needs to be a two-major-version process.  This is just not that big of a deal.

**Comment by rhshadrach** [comment]
@jbrockmendel - what's your recommended way forward here?

**Comment by jbrockmendel** [comment]
1) warn if method is explicitly passed
2) otherwise warn if there are NAs present

**Comment by Charlie-XIAO** [comment]
Okay, so in other words, revert to my original version, and in addition warn when has NA but method is not explicit passed.

I will make the changes soon. Thanks for your discussion.

**Review by rhshadrach — APPROVED** [review]
lgtm

**Comment by mroeschke** [comment]
Could you merge main once more?

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Charlie-XIAO

**Comment by holymonson** [comment]
@rhshadrach @jbrockmendel Hi, we need `fill_method='None'` to force `pct_change` not to handle NAs, but this PR cause a lot of deprecated warning and we can't fix it. Before you provide an alternative to do that, deprecating`fill_method` is unwise.

**Comment by Charlie-XIAO** [comment]
Does obj.fillna(...).pct_change not work, as is also mentioned in the deprecation message? @holymonson

**Comment by holymonson** [comment]
> Does obj.fillna(...).pct_change not work, as is also mentioned in the deprecation message? @holymonson

We don't want `fillna()` at all, on the contrary we want keeping NAs, while your deprecation message doesn't tell howto **NOT** fillna.

**Comment by rhshadrach** [comment]
@holymonson - I've responded in #53491

**Pull request merged**
