### PR TITLE
DOC: Fix F821 error in docstring

### PR DESCRIPTION
**Pull request by tqa236**
- [ ] xref #22900 (I think this PR can also close the linked issue as now `pandas` and `numpy` are considered defaults import before linting docstring)

The command below returns no error now.

```
flake8 --doctest --ignore="" --select=F821 pandas/ | grep -v "F821 undefined name 'pd'" | grep -v "F821 undefined name 'np'"
```

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Thanks @tqa236, looks great

**Comment by datapythonista** [comment]
@tqa236 should we add a check in the CI for this?

**Comment by datapythonista** [comment]
Sounds good, up to you, I was just wondering if you considered it. Thanks for all the details and for the continued work on this.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @tqa236

**Pull request merged**
