### PR TITLE
CI: Split CI workflow into code checks, docbuild & web, and arraymanager

### LINKED ISSUE #37242: CI: Split .github\workflows\ci.yml into separate workflows
CI / Checks (push) — Checks and CI / Web and docs (push) — Web and docs are part of the same workflow.

If we want to restart one of the jobs (quiet infrequent - a few instances of connection issues on web and docs IIRC), both are re-run.

It may make sense to split these.

An alternative could be to combine with pre-commit into a single workflow and only run 'Checks' and 'Web and docs' on success.

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #37242
- [x] tests added / passed

`ci.yml` split into:

* `arraymanager.yml`
* `code-checks.yml` (includes `pre-commit.yml` now)
* `docbuild-and-upload.yml`

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Does this mean that if one fails we can re-run just that one?

**Comment by mroeschke** [comment]
> Does this mean that if one fails we can re-run just that one?

Yes where "one" is the entire workflow. 

e.g. If the arraymanager tests fail, the docbuld or code checks won't be re-run
e.g. If one code check fails, all the code checks still need to be rereun https://github.com/actions/runner/issues/432

**Comment by lithomas1** [comment]
I think it might be worth waiting for github/roadmap#271. Of course we could also merge this now and revert when that is implemented.

**Comment by mroeschke** [comment]
> I think it might be worth waiting for [github/roadmap#271](https://github.com/github/roadmap/issues/271). Of course we could also merge this now and revert when that is implemented.

github/roadmap#271 would make this a lot nicer (as well as our other workflows). 

I have slight preference just splitting now to make re-running things more focused in the short term.

**Comment by jreback** [comment]
thanks @mroeschke seems ok to do now

**Pull request merged**
