### PR TITLE
DEPR: Index.insert dtype-inference

### LINKED ISSUE #51363: API: Index.insert too much dtype inference
```python
idx = pd.Index([1], dtype=object)

idx.insert(0, 1).dtype
```

ATM Index.insert uses `Index._with_infer` to construct a result, which will cast the case here to int64 instead of retaining object.  I think in this case it would be more reasonable to keep object dtype, which we'd get by just calling `Index.__new__` instead of _with_infer.

We have no tests that depend on this ATM.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #51363 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Doesn't have a "do X to avoid this warning, not sure if this merits future option or temporary keyword.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Its kind of annoying that this warning gets issued (the PR currently suppress it) in `frame_or_series[new_key] = val`.  any preferences on whether to warn there?

**Comment by jbrockmendel** [comment]
@phofl thoughts on doing this?  i think there was some vague similarity to some of what you were working on.  main open question here is whether to continue suppressing warnings on setitem-with-expansion

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @jbrockmendel

**Comment by jbrockmendel** [comment]
Glad to get movement here, but i was hoping for some discussion of whether suppressing the warning in setitem-with-expansion was the way to go

**Comment by phofl** [comment]
I wouldn’t want to warn there, I don’t think that anyone cares about inference there and getting rid of it is a pain

**Pull request merged**
