### PR TITLE
TST: mark all plotting tests as slow

### PR DESCRIPTION
**Pull request by ivanovmg**
- [ ] xref https://github.com/pandas-dev/pandas/pull/37735#issuecomment-732530791
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Marked all plotting tests as slow globally at the top of each module.

### CODE REVIEW

**Comment by ivanovmg** [comment]
One test fails in travis.

```
    def test_area_lim(self):
        df = DataFrame(np.random.rand(6, 4), columns=["x", "y", "z", "four"])

        neg_df = -df

        for stacked in [True, False]:
            ax = _check_plot_works(df.plot.area, stacked=stacked)
            xmin, xmax = ax.get_xlim()
            ymin, ymax = ax.get_ylim()
            lines = ax.get_lines()
            assert xmin <= lines[0].get_data()[0][0]
            assert xmax >= lines[0].get_data()[0][-1]
>           assert ymin == 0
E           assert -0.11510497676407896 == 0
```

My changes presumably did not affect it.

**Comment by ivanovmg** [comment]
Locally this test passes, the same matplotlib version as in travis build, 3.3.2.

**Comment by jreback** [comment]
I am not sure this had an effect, i think these are actually already skipped, maybe with some exceptions). However the builds are still extremely slow (30+min for tests). let me make an issue about this.

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/issues/38091

**Comment by jreback** [comment]
can you merge master and let's see this run again.

**Comment by jreback** [comment]
thanks @ivanovmg 

can you update pandas/tests/plotting/common.py with some comments to indicate all test files are running as slow.

**Pull request merged**
