### PR TITLE
BUG: .groupby on Series' values without reindexing

### LINKED ISSUE #15338: .groupby by should indicate it aligns the passed in Series
#### Code Sample, a copy-pastable example if possible

```python
>>> series = pd.Series([1, 2, 3], index=range(3))

>>> key = pd.Series([0, 0, 1], index=range(3, 6))  # Note: disjunct index

>>> series.groupby(key).sum()
Series([], dtype: int64)

>>> series.groupby(key.values).sum()
0    3
1    3
dtype: int64
```
#### Problem description

The current behavior is a bug because the [.groupby() documentation](https://github.com/pandas-dev/pandas/blob/v0.19.2/pandas/core/generic.py#L3948-L3949) says about `by` parameter:
> If a dict or Series is passed, the Series or dict **VALUES** will be used to determine the groups

Above example shows this not being the case.

#### Expected Output

With above setup:
```py
>>> series.groupby(key).sum()
0    3
1    3
dtype: int64
```

#### Output of ``pd.show_versions()``

<details>
pandas: 0.19.0+416.ge1390cd
</details>

### PR DESCRIPTION
**Pull request by kernc**
- [X] closes #15338
 - [X] tests added / passed
 - [X] passes ``git diff upstream/master | flake8 --diff``
 - [X] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
see my comments on the issue.

**Comment by jreback** [comment]
so this changes the actual behavior. why is this warranted?

**Comment by kernc** [comment]
I don't know if it is. The docs say in case of series, the values will be used as grouping keys. I guess in this instance I don't see series as much different from any other series of values, like lists or numpy arrays. I don't know why aligning is necessary, particularly if the series of keys comes from another source (if not, why would it be passed as a series explicitly instead of by a column reference), in which case the index can be arbitrary and the result of alignment just as so.

In other words, if the grouping series is from the same source (i.e. the same frame) as the grouped object, then it already shares the same index, hence aligning is not necessary.
If the series is from a different source, then automatically aligning might be dangerous. I highly appreciate the fact that an indexed series makes a great random-access key-value store, but I assume most users don't treat it as such in preference to somewhat simpler _ordered array of values which happens to have an additional index_.

Ideally, I'd have `.groupby()` fail if the passed grouping is a Sequence and its length doesn't match. Otherwise, it should behave as it does when passed a list.

Of course, Series is not a Sequence?? :flushed:

**Comment by kernc** [comment]
> so this changes the actual behavior. why is this warranted?

It's wholly compatible with the docs, and it doesn't break any previous tests. :laughing:

**Comment by jreback** [comment]
@kernc this certainly changes behavior. The entire point is to align. This is actually very confusing what you changed. Virtually every operation in pandas aligns. Why would this not?

**Comment by kernc** [comment]
Thanks for treating me like a pandas expert I'm not. :heart: 

In that case, I agree a remark in the docs (docstring) would be welcome.

**Comment by jreback** [comment]
@kernc hahh, np.

if you'd like to do a PR for the doc-string would be great.

**Pull request closed without merging**
