### PR TITLE
REF: do all convert_tolerance casting inside Index.get_loc

### PR DESCRIPTION
**Pull request by jbrockmendel**
As a bonus we get better exception messages in the affected tests.

### CODE REVIEW

**Comment by jreback** [comment]
is this actually a bug fix? e.g.the error message before was ints and not its (correctly) timestamps.?

**Comment by jbrockmendel** [comment]
> e.g.the error message before was ints and not its (correctly) timestamps.?

I guess so, sure

**Comment by WillAyd** [comment]
lgtm ex merge conflict

**Comment by jbrockmendel** [comment]
rebased+green

**Comment by jbrockmendel** [comment]
added whatsnew for improved exception messages, rebased+green

**Comment by jreback** [comment]
ok!

**Pull request merged**
