### PR TITLE
DOC: add anonymizeIp for Google analytics in docs

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Using a more recent snippet (following their current docs), and adding anonymization of the IP (according to their docs, this should only "slightly reduce the accuracy of geolocation"). 

If we do this, should do the same for main website as well.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. if anyone @pandas-dev/pandas-core can give this a look see.

**Review by datapythonista — APPROVED** [review]
Looks good. No preference on anonymizing ips. I don't know much of the topic, and doesn't seem so very relevant for us, but happy to do it if you think it's good.

**Review by gfyoung — APPROVED** [review]
LGTM

**Comment by jreback** [comment]
thanks @jorisvandenbossche

**Pull request merged**
