### PR TITLE
CI: Use regular solver for docker build

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by phofl** [comment]
Newest numpy and numba are incompatible, so the docker build fails without taking dependencies into account

**Review by MarcoGorelli — APPROVED** [review]
thanks @phofl

**Comment by MarcoGorelli** [comment]
the dockerfile in 1.5.x is very different, does this need backporting?

**Comment by phofl** [comment]
Wasn't aware of that, are we using mamba there? If yes, then we don't have to backport

**Comment by MarcoGorelli** [comment]
yup

**Comment by MarcoGorelli** [comment]
we've backported the docker changes, so let's backport this too

@meeseeksdev please backport to 1.5.x

**Pull request merged**
