### PR TITLE
TYPING: add stubs for _packer and _unpacker

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref #28133

```
pandas\io\packers.py:800: error: Base type _Packer becomes "Any" due to an unfollowed import
pandas\io\packers.py:820: error: Base type _Unpacker becomes "Any" due to an unfollowed import
```

### CODE REVIEW

**Comment by WillAyd** [comment]
Are there packaging considerations to be made here? Given these modules are deprecated I think we should just ignore them if causing problems

**Comment by simonjayhawkins** [comment]
`pd.to_msgpack` and `pd.read_msgpack` will not be deprecated until pandas 1.2. #27103

we will still be accepting bugfixes? if so, type hints should be a benefit. no reason to ignore?

**Comment by jreback** [comment]
we haven’t really quite decided on the length of this deprecation
but adding types would be fine

**Comment by WillAyd** [comment]
Sounds good. Would we need to do anything with setup.py to get these distributed?

**Comment by simonjayhawkins** [comment]
atm we're primarily concerned with code quality? (and reducing the pull request review overhead if mypy can find problems)

making pandas PEP 561 compatible is outside the scope of the PR. https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages

**Comment by WillAyd** [comment]
Cool that's what I was asking about. Yea doesn't need to be solved here but seems like already some people have started using types hints with IDEs, so would be good to ship stubs alongside releases. If you want to open an issue for that discussion would be helpful

**Review by WillAyd — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
personally, my time spent in an IDE is with pandas itself and use notebook for using pandas. so i'll raise the issue but add contributions welcome so that someone using pandas as a library in an IDE can perhaps take it on.

**Pull request merged**
