### PR TITLE
ENH: add interval kwarg to get_data_yahoo issue #9071

### PR DESCRIPTION
**Pull request by alexamici**
PR for the issue #9071

### CODE REVIEW

**Comment by jreback** [comment]
@alexamici well it appears to be failing on the routine you changed.

**Comment by alexamici** [comment]
@jreback short story: this is quite embarrassing, but the test function I wrote was total crap and I didn't notice as it was being skipped in my local testing. Now all should be well.

Long story: to my partial excuse I usually use py.test assert or doctests so I had no prior experience with assertEqual and friends, and I made a mess of the test function. Furthermore when running locally my tests were skipped due to lxml missing and I didn't figure it out until today. Last but not least, I was using the 'GOOG' symbol that has been redefined recently and queries for 2013 results in a Yahoo! API failure.

**Comment by jorisvandenbossche** [comment]
Tests are passing now!

**Comment by jreback** [comment]
thanks @alexamici !

**Comment by jreback** [comment]
btw, if you would like to review the docs in remote.rst for any updates
(looking for a general review, not necessarily tied to this change).

**Pull request merged**
