### PR TITLE
IntervalArray equality follow-ups 

### PR DESCRIPTION
**Pull request by jschendel**
Follow-ups to #30640 based on @jbrockmendel's comments.

Haven't addressed all the comments yet but pushing this up now so there's a record of it.

Changes thus far:
- Created `tests/arithmetic/test_interval.py ` and moved the tests there
- Used `make_wrapped_comparison_op` to add `__eq__` and `__ne__` to `IntervalArray`.

### CODE REVIEW

**Review by jreback — APPROVED** [review]
lgtm @jbrockmendel

**Comment by jbrockmendel** [comment]
LGTM

**Comment by WillAyd** [comment]
Thanks @jschendel

**Comment by jbrockmendel** [comment]
@jschendel could IntervalIndex also pass through inequalities to IntervalArray?  if so then thats some more code we can share

**Comment by jschendel** [comment]
Yes, although inequalities haven't been implemented yet, even at the scalar `Interval` level.  Still would be good to get the code to share in place though, as the error messages are inconsistent.

**Pull request merged**
