### PR TITLE
CLN: Added annotations.

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by alimcmaster1 — APPROVED** [review]

**Comment by MomIsBestFriend** [comment]
I'm really confused about, how it failed.

**Comment by alimcmaster1** [comment]
Don't think the test failures are related to this change - I see the same on the latest PR that was merged -
https://github.com/pandas-dev/pandas/runs/295247988

**Comment by MomIsBestFriend** [comment]
I'm now even more confused, about the fact that it passed.

**Comment by alimcmaster1** [comment]
> I'm now even more confused, about the fact that it passed.

The test is unreliable ive raised an issue here: https://github.com/pandas-dev/pandas/issues/29514

**Comment by jbrockmendel** [comment]
Thanks @MomIsBestFriend

**Pull request merged**
