### PR TITLE
ENH add warning to Series.drop column noting that it does nothing

### PR DESCRIPTION
**Pull request by Fealthas**
Partial solution to #39509

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
-1 on a warning. would be ok with raising though.

**Review by jreback — CHANGES_REQUESTED** [review]
actually let's just deprecate `columns` its useless here.

**Comment by Fealthas** [comment]
Hello,
I don't really know how to fix this to the point the maintainers want(haven't contributed before).

If you still feel this is worth fixing(I do), someone else should take over. It seems like a pretty simple change - adding a warning or a raise.

Thx,
Fealth

**Comment by mroeschke** [comment]
Thanks for taking a stab at this @Fealthas. Agreed this behavior needs improving, but appears this PR has gotten stale, so closing due to that.

**Pull request closed without merging**
