### PR TITLE
CI: update to isort 5 (#35134)

### LINKED ISSUE #35134: CI: Update to isort 5
`isort` 5.x is out with some changes to how it sorts. We'll need to update the code and unpin in our environment file.

### PR DESCRIPTION
**Pull request by fangchenli**
- [x] closes #35134
- [x] 0 tests added / 0 passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
can you rebase

**Comment by simonjayhawkins** [comment]
IIUC isort 5 is sorting imports that we not sorted before (in .pyx and imports not at the top)

maybe possible to break some changes here off into smaller PRs before updating isort?

**Comment by VirosaLi** [comment]
> IIUC isort 5 is sorting imports that we not sorted before (in .pyx and imports not at the top)
> 
> maybe possible to break some changes here off into smaller PRs before updating isort?

I posted a tracking list on the original issue. And I'll break this PR into samller PRs.

**Comment by simonjayhawkins** [comment]
> I posted a tracking list on the original issue. And I'll break this PR into samller PRs.

Thanks. I think this makes sense. when we introduced isort, we did it on small batches of files. These can be quickly reviewed and merged.

**Pull request closed without merging**
