### PR TITLE
BLD: make bottleneck required

### LINKED ISSUE #12149: BLD: make bottleneck a required dependency
xref #12141 

currently we have backup routines for everywhere we use bottleneck.

If we made it a requirement (rather than a highly recommended dep) we could forgo this.

its easily installable via `conda` and `pip` (wheels); this used to be an issue.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #12149
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
even though i created the original issue

-1 on adding this dependency. rather would drop it and add numba instead to do the computation.

bottleneck doesn’t really add much performance except in a very limited way

**Comment by jbrockmendel** [comment]
> rather would drop it and add numba instead to do the computation.

I'm happy to put this PR off if this topic needs discussion.  My impression is that numba is less of a bottleneck-substitute than it is a cython-substitute.  Could be way off in that, since I don't use numba myself.

**Comment by shoyer** [comment]
I have an experimental project reimplementing bottleneck functions in Numba, which might be a helpful reference: github.com/shoyer/numbagg

**Comment by TomAugspurger** [comment]
I'd also prefer not to do this.

I think once we're ready to take on proper string support (next year some time?) there's a chance we'll add numba as a required dependency anyway (though that shouldn't be taken as a given at this point).

**Comment by jreback** [comment]
maybe what’s useful here is to decouple the bottleneck code from nanops - iow make it like a plug-in that we then swap out (to another engine) might require some refactoring

**Comment by shoyer** [comment]
Numbagg works with modern numba, which has been remarkably stable over the
past few years. I'm still not sure I would recommend that pandas use it --
bottleneck (written in C) is definitely easier to install than Numba. If we
vendored bottleneck in pandas (not that I recommend it) our users would
hardly notice the difference from what we do currently. That's probably not
as true for Numba.

**Comment by jreback** [comment]
I am making a more general point - I think we should use numba as a hard dependency - allows lots of flexibility and quite good performance with an easier maintenance burden

and installation is well supported across the eco system

**Pull request closed without merging**
