### PR TITLE
DEPR: Enforce melt(value_name) behavior

### PR DESCRIPTION
**Pull request by mroeschke**
Introduced in https://github.com/pandas-dev/pandas/pull/35003

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM pending green

**Comment by samukweku** [comment]
@mroeschke an observation here - I believe the error message should be that `value_name` should not exist in the `id_vars` or `var_name`. An example from the melt docs: 

```py
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})

df
   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6
```

This should not raise, since there is no name conflict with `id_vars` or `var_name`: 

```py
df.melt(id_vars='A', value_vars='B', value_name='C')
<ipython-input-5-6a973a750e09>:1: FutureWarning: This dataframe has a column name that matches the 'value_name' column name of the resulting Dataframe. In the future this will raise an error, please set the 'value_name' parameter of DataFrame.melt to a unique name.
  df.melt(id_vars='A', value_vars='B', value_name='C')
Out[5]: 
   A variable  C
0  a        B  1
1  b        B  3
2  c        B  5
```

This however should raise : 

```py
df.melt(id_vars='A', value_vars='B', value_name='variable')
Out[8]: 
   A variable variable
0  a        B        B
1  b        B        B
2  c        B        B
```

**Comment by mroeschke** [comment]
Thanks for the response @samukweku 

> I believe the error message should be that value_name should not exist in the id_vars or var_name

I think this is an _additional_ check that would be useful (from https://github.com/pandas-dev/pandas/issues/34731#issuecomment-643490012 generally we should be checking for conflicts with all combinations of `vars`/`values`  names & compared to existing column names). But this PR looks to be enforcing https://github.com/pandas-dev/pandas/pull/35003 which disallows `value_name` in the `df.columns`

**Comment by samukweku** [comment]
@mroeschke my point is that in the first example there is no conflict with the column names, so why raise. `C` does not exist in the new columns, and as such should be fine. The premise of #35003 is incorrect IMHO

**Pull request merged**
