### PR TITLE
DOC: do not include type hints in signature in html docs

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See https://github.com/pandas-dev/pandas/issues/33025. Removing the type hints in the online docs until we have a better solution to improve readability.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Can you post a screenshot of the output?

**Comment by jorisvandenbossche** [comment]
It simply removed type hints from the signature, so you get

image

instead of

image

using the example from https://github.com/pandas-dev/pandas/issues/33025 (but there are other pages that have much more elaborate type hints, where the improvement in readability is bigger)

**Comment by simonjayhawkins** [comment]
lgtm

**Review by TomAugspurger — APPROVED** [review]

**Review by datapythonista — APPROVED** [review]
lgtm. Can you merge master? CI should be fix I think

**Comment by TomAugspurger** [comment]
Thanks for confirming.

**Pull request merged**
