### PR TITLE
CI: parametrize and xfail

### PR DESCRIPTION
**Pull request by jbrockmendel**
cc @mroeschke

### CODE REVIEW

**Review by lithomas1 — APPROVED** [review]

**Comment by lithomas1** [comment]
Do we need this for 2.1.x?

**Review by mroeschke — APPROVED** [review]
I don't think this needs a backport to 2.1.x since the potential failure might be due to upcoming 2.2 changes, but we can backport this later if needed

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Comment by jbrockmendel** [comment]
i think the relevant test was added recently so wont be in 2.1.x

**Pull request merged**
