### PR TITLE
DEPR: deprecate Series/DataFrame.compound

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/pandas-dev/pandas/issues/18262

Not sure if we need to point to an alternative in the deprecation warning. I can put the exact "formula" for what we are currently calculating, but I don't know enough from finance to know if that is actually good to point to (eg I don't directly see that formula on the first google hit https://en.wikipedia.org/wiki/Compound_interest)

### CODE REVIEW

**Comment by topper-123** [comment]
I'm +1 on deprecating this, as a scalar verion of compount is not particularly useful (I'm an economist).

But also, compound interests arrays can be a bit tricky to calulate in some cases. Would there be acceptance for adding e.g. ``cumpct_change`` to mirror ``cumsum`` etc.?

**Comment by jorisvandenbossche** [comment]
Thanks, good to have feedback of somebody who knows something about it! :)

> Would there be acceptance for adding e.g. cumpct_change to mirror cumsum etc.?

Personally, I would say, that looks a a bit too specific (but yeah, I would never use it myself). Maybe we should think about making it easier to do generic cumulative operations.

**Comment by jorisvandenbossche** [comment]
> Maybe we should think about making it easier to do generic cumulative operations.

Actually, that's `expanding` no?

**Review by jreback — CHANGES_REQUESTED** [review]
lgtm. can you add a whats new note & add to the deprecated issue tracker

**Comment by jorisvandenbossche** [comment]
Added whatsnew

**Comment by Davdav05** [comment]
Hey guys, as you mentioned there is no alternative suggested. I've been using this method for a while, what would be the shortest/cleanest way to replace this method?

Thanks!

**Comment by jreback** [comment]
it’s just

(1 + s).prod() - 1

**Pull request merged**
