### PR TITLE
CLN: replace %s syntax with .format in io/formats/format.py

### PR DESCRIPTION
**Pull request by cbertinato**
Progress toward issue #16130. Converted old string formatting to new string formatting in io/formats/format.py.

- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by gfyoung** [comment]
> I believe this failing test is addressed in this PR:

@cbertinato : Yes, you are correct.  Please ignore this failure for your PR.

**Comment by gfyoung** [comment]
@cbertinato : This PR looks good to go, but I think we'll hold on merging until we fix the test failure.

**Comment by cbertinato** [comment]
Sounds good.

**Comment by gfyoung** [comment]
Awesome.  Thanks for understanding.  We'll ping when it's merged so you can rebase and get all tests to pass.

**Comment by jreback** [comment]
if you can rebase and push again

**Comment by jreback** [comment]
thanks!

**Pull request merged**
