### PR TITLE
DOC: fix options table

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@jorisvandenbossche can you fix the groupby tuple issue in `groupby.rst` here? I have https://github.com/pandas-dev/pandas/pull/18731 for the warning, but that'll get squashed down to a commit, and the warning doesn't need to be backported.

**Comment by jorisvandenbossche** [comment]
But a revert to interpret tuple should go in 0.21.1 no? 
Otherwise what is the point of warning for it in 0.22

**Comment by TomAugspurger** [comment]
Oh sorry I was being silly. That example builds correctly on the 0.21.x branch, yes?

**Comment by jorisvandenbossche** [comment]
> That example builds correctly on the 0.21.x branch, yes?

Ah, no that is a good question! Have to check

**Comment by jorisvandenbossche** [comment]
Yeah, sorry, I was looking at a travis build of master, not 0.21.x, so this change was only introduced in 0.22.dev. So nothing urgent for today. Sorry! 

But the patch itself is looking good to me though.

**Pull request merged**
