### PR TITLE
DOC: Add See Also section on series.py

### PR DESCRIPTION
**Pull request by za**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by datapythonista** [comment]
This fixed the error, but I don't think we want to add a WIP note into the official documentation of pandas. We can discuss what to add in the see also if you want.

**Comment by za** [comment]
@datapythonista Yes please. Let's get this PR done. What relevant function that we can add at `See Also` section? Any hint? `s.to_markdown()`?

**Comment by za** [comment]
After had a discussion with @datapythonista should add `See Also` section in the parent file somewhere in `pandas/core/generic.py`.

**Comment by datapythonista** [comment]
Closing this, as this needs to be started from the beginning. Better open a new PR with the correct changes. Thanks!

**Pull request closed without merging**
