### PR TITLE
Remove offset/DTI caching (disabled since 0.14

### LINKED ISSUE #23080: DatetimeIndex._use_cached_range, _cached_range not reachable
Because `freq._should_cache()` is always False.

My inclination would be to get rid of use_cached_range and cached_range (as opposed to enabling it)

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #23080
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
> also add a whatsnew note (put in api breaking changes, even though it has long been disabled)

OK.  What do I say has changed?

**Comment by jreback** [comment]
just say that the attribute has been removed; it’s just a notice that a change was made (though is not actually public folks sometimes rely on this)

**Comment by jbrockmendel** [comment]
> just say that the attribute has been removed

Done.  asvs showed no change.

**Comment by jreback** [comment]
lgtm merge on green

**Pull request merged**
