### PR TITLE
BLD: address build warnings

### PR DESCRIPTION
**Pull request by jbrockmendel**
xref #30609

### CODE REVIEW

**Comment by WillAyd** [comment]
Nice! Does this address all of them?

**Comment by datapythonista** [comment]
Not sure if you've seen it, but besides the failure in the docs, this error is happening lots of times in the tests:
```
Exception ignored in: 'pandas._libs.window.aggregations.is_monotonic_start_end_bounds'

TypeError: Argument 'arr' has incorrect type (expected numpy.ndarray, got pandas._libs.window.aggregations._memoryviewslice)
```

**Comment by jbrockmendel** [comment]
> Does this address all of them?

No.  Locally (only checked OSX) it addresses the buffer unpacking in aggregations.pyx and the assignment warnings for algos.c.  The __pyx_memview_get_object ones I think are coming from an unused import; they dont correspond directly to any of the .pyx code

**Comment by alimcmaster1** [comment]
> > Does this address all of them?
> 
> No. Locally (only checked OSX) it addresses the buffer unpacking in aggregations.pyx and the assignment warnings for algos.c. The __pyx_memview_get_object ones I think are coming from an unused import; they dont correspond directly to any of the .pyx code

Nice! What's the best way of figuring out what unused import is causing? - For my own knowledge!
`pandas/_libs/hashing.c:25344:20: warning: ‘__pyx_memview_get_object’`

Also I randomly get this warning: (which doesn't seem to be as expected)
```
pandas/_libs/src/ujson/python/objToJSON.c: In function ‘NpyArr_encodeLabels’:
pandas/_libs/src/ujson/python/objToJSON.c:1616:18: warning: ‘len’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```

**Comment by jbrockmendel** [comment]
> What's the best way of figuring out what unused import is causing? - For my own knowledge!

No idea

**Comment by WillAyd** [comment]
The one is caused by Cython so can't speak to that but for the JSON one if you look at the line:

https://github.com/pandas-dev/pandas/blob/4206fd42cc5cd20204c0c5f192f7e59f204ad48d/pandas/_libs/src/ujson/python/objToJSON.c#L1616

The warning is saying that there are some code paths where `len` is declared but never assigned, which would give it an undefined value and either give weird results or segfault if that line gets hit.

Not clear what path that is though - you are only getting the error intermittently?

**Comment by WillAyd** [comment]
Thanks @jbrockmendel

**Pull request merged**
