### PR TITLE
ENH: Adding table name parameter to pandas.read_excel

### LINKED ISSUE #38937: ENH: pd.read_excel with table parameter
#### Is your feature request related to a problem?
Excel has [tables ](https://support.microsoft.com/en-us/office/overview-of-excel-tables-7ab0bb7d-3a9e-4b56-a3c9-6c94334e492c#:~:text=To%20quickly%20create%20a%20table,row%2C%20and%20then%20click%20OK.), that makes data managing within Excel easier and offers some other features. 

At the moment, pandas cannot access those tables, it simply reads in all the data. I think it would be helpful if a `table` parameter was added to `pd.read_excel` to capture table(s) defined in a sheet.

#### Sample Data:
Attached is a sample excel file: [016-MSPTDA-Excel.xlsx](https://github.com/pandas-dev/pandas/files/5768126/016-MSPTDA-Excel.xlsx)

With the current implementation of `read_excel`, we cannot select specific tables (dSalesReps, dProduct, dCategory, or dSupplier). Even if we read the `Tables` sheet, it becomes quite hard to separate the data into individual tables.

#### Describe the solution you'd like

```pd.read_excel(io=filename, sheet=sheetname, table=tablename, ...)```

The table parameter can have a default of `None`, in which case the entire sheet is read in; if however table is not `None`, then the table or lists of tables only are read in. The `openpyxl` library would be used to implement this.

#### API breaking implications

I am not aware of any API breaking implications

#### Describe alternatives you've considered
It could be done outside Pandas, where you read in the data first through `openpyxl`, before passing it to Pandas. I wrote a [blog post](https://samukweku.github.io/data-wrangling-blog/spreadsheet/python/pandas/openpyxl/2020/05/19/Access-Tables-In-Excel.html) about it; I feel, however, that it may be more convenient to provide that same functionality within Pandas and let the user worry less about the abstractions.

#### Additional context

I did check to see if this has been raised before, but did not find any. If it already has, kindly point me to that issue, and I will gladly close this.

Thanks.

### PR DESCRIPTION
**Pull request by iangainey**
- [x] closes #38937  (Replace xxxx with the GitHub issue number)

- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by iangainey** [comment]
As far as I can tell this should be passing all of the tests. Some pre-commit hooks seem to not be passing in this PR but some make no sense, saying there is no attribute, yet there is. Tons of "not indexable errors", that are indexable, and were existing functionality prior to opening this so I'm not certain how it's failing.
Any guidance on getting these to pass would be great.

**Review by rhshadrach — CHANGES_REQUESTED** [review]
Thanks for the PR. This issue is tagged as `Needs Discussion`, and I am hesitant to add this functionality to pandas' already complicated Excel reading code. This is especially true because, as the implementation currently stands, it's only supported by openpyxl.

That said, it seems to me the move of code in `parse` to it's own method (currently - your `parse_mutliindex`) is a good cleanup anyways (without the reading tables feature), and it would simplify the diff here. Would you consider doing that refactor as a pre-cursor?

I'm also curious as to why `parse_multiindex` since (I think) there isn't necessarily a MultiIndex. I would suggest `parse_sheet` instead.

**Comment by mroeschke** [comment]
Agreed with the hesitancy to implement this feature as of now. Going to close since I think more buy-in needs to happen in the issue first, but happy to have a separate PR with the cleanups

**Comment by iangainey** [comment]
I guess I'm a bit confused, as I had tried to get more of a discussion on the issue but could not get any response from you (the development team), only from other contributors. The functionality only adds complexity when the user wants to read in tables, and there are plenty of other functionality in the excel io area of pandas that only works with one of the engines.

**Comment by rhshadrach** [comment]
> The functionality only adds complexity when the user wants to read in tables

Each feature adds a certain amount of technical debt - it increases the surface area of pandas requiring tests, documentation, dealing with new bug reports.

> there are plenty of other functionality in the excel io area of pandas that only works with one of the engines.

This is something we would like to reduce.

That said - I would take a look at the diff here after #58497 is merged.

**Comment by rhshadrach** [comment]
For the future - we can reopen the PR. But let's continue this in #58500.

**Pull request closed without merging**
