### PR TITLE
CLN: Index._values docstring + Block.internal/external_values

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
@jbrockmendel this is the "clean" part of https://github.com/pandas-dev/pandas/pull/31037, so if you merge this, I will update the other PR so that only the required changes are in the PR for 1.0.0.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by WillAyd** [comment]
Is this all internal or would anything leak into `.values`?

**Comment by jorisvandenbossche** [comment]
This is mainly doc updates + removal of an unused internal keyword + duplicated definition. Should be no public consequence.

**Comment by WillAyd** [comment]
Great thanks @jorisvandenbossche

**Pull request merged**
