### PR TITLE
Prefixed batch script commands with call

### LINKED ISSUE #26345: Windows 3.7 CI Failures
Lots of failures recently with CI build. I do see this in the logs:

```sh
CondaValueError: Malformed version string '~': invalid character(s).
```

Which I assume is the root cause, though the dependency file hasn't been updated in some time.

@TomAugspurger if you have any thoughts; maybe a conda-forge issue?

### PR DESCRIPTION
**Pull request by WillAyd**
maybe fixes #26345

### CODE REVIEW

**Comment by gfyoung** [comment]
@WillAyd : Can you try updating `conda` itself before doing the environment creation?

**Comment by WillAyd** [comment]
Good idea just pushed that through

**Comment by WillAyd** [comment]
Manually stopped the build but looks like that did get us past the issue

**Comment by WillAyd** [comment]
I'm not overly familiar with the CI here but perhaps related is also the fact that we have a deprecated task in our build that prevents Conda from being updated:

https://github.com/pandas-dev/pandas/blob/304d8d4bc3b3cde7e2b463426bf484701df142cd/ci/azure/windows.yml#L20

I'm going to push a separate PR for that; if it fixes this just by doing that great but may be worth removing given the deprecation in the logs regardless:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=11409&view=logs&jobId=76104ccd-8dcc-5006-a17c-28bcdd709542&taskId=54201e92-6f3a-5f33-d5a0-ee2a32fc9e73&lineStart=4&lineEnd=5&colStart=1&colEnd=1

**Comment by WillAyd** [comment]
Closing as I don't think this is the right solution. Per comment by @datapythonista after refactoring Azure CI a Conda update is actually suggested:

https://github.com/pandas-dev/pandas/pull/26384#pullrequestreview-237714053

So I'll push a separate PR which does that later and adds gcsfs back in

**Pull request closed without merging**
