### PR TITLE
TST/CLN: Avoid subprocess shell=True

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
nice, that's a good one to avoid

**Comment by jbrockmendel** [comment]
LGTM pending green

**Review by phofl — COMMENTED** [review]
the failures look legit, restarted the jobs yesterday after they failed initially too

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @mroeschke

**Pull request merged**
