### PR TITLE
updated CODEOWNERS file

### PR DESCRIPTION
**Pull request by anirudh-hegde**
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
what are you trying to do?

**Comment by MarcoGorelli** [comment]
closing as this file is fine as-is

**Comment by Anianonymous** [comment]
> what are you trying to do?
I saw that  CODEOWNERS file contains errors.
I was trying to solve errors.

**Comment by Anianonymous** [comment]
> closing as this file is fine as-is

ya fine

**Comment by MarcoGorelli** [comment]
> I saw that CODEOWNERS file contains errors.

which errors?

**Pull request closed without merging**
