### PR TITLE
DOC: Fix flake8 issues in doc/source/reshaping.rst

### LINKED ISSUE #24180: DOC: Fix flake8 issues in doc/source/reshaping.rst
We didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.

The first step of this issue would be edit `setup.cfg` in the pandas home, and in the `flake8-rst` section, remove from the `exclude` list the file `doc/source/reshaping.rst`

After that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version `0.7.0` or higher):

```
$ flake8-rst doc/source/reshaping.rst 
doc/source/reshaping.rst:21:7: E111 indentation is not a multiple of four
doc/source/reshaping.rst:22:7: E111 indentation is not a multiple of four
doc/source/reshaping.rst:25:7: E111 indentation is not a multiple of four
doc/source/reshaping.rst:26:7: E111 indentation is not a multiple of four
doc/source/reshaping.rst:374:28: W504 line break after binary operator
doc/source/reshaping.rst:375:83: E501 line too long (80 > 79 characters)
doc/source/reshaping.rst:400:83: E501 line too long (80 > 79 characters)
doc/source/reshaping.rst:724:83: E501 line too long (89 > 79 characters)
doc/source/reshaping.rst:739:13: E999 SyntaxError: invalid syntax
```

Once all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from `setup.cfg`. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.

### PR DESCRIPTION
**Pull request by charlesdong1991**
- [x] closes #24180
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm

you'll have to merge the conflict in `setup.cfg`, we just merged a PR removing some other files from the exclude list

**Comment by charlesdong1991** [comment]
@datapythonista thanks, just rebased...

**Comment by datapythonista** [comment]
@charlesdong1991 can you delete the `comparison_with_*` from the exclude list? when fixing the conflict they were incorrectly added back

**Comment by charlesdong1991** [comment]
oh, @datapythonista sorry, i didn't check very carefully... just recalled that they were in between `HEAD`, should be removed indeed.... sorry, next time will check the conflicts more carefully

**Comment by datapythonista** [comment]
No worries, usually conflicts are about code added or modified, but when the code is deleted, the fix is usually removing the code block. It usually helps to do a `git diff` after fixing the conflict, so you know what your branch is actually changing with respect to master.

**Comment by jreback** [comment]
can you merge master here

**Comment by jreback** [comment]
thanks!

**Comment by charlesdong1991** [comment]
@datapythonista sorry, i was working and didn't notice the email... and many thanks for solving the merge conflict for me...

**Comment by datapythonista** [comment]
no worries, these trivial conflicts can be easily fixed in the github UI

**Pull request merged**
