### PR TITLE
PERF: RangeIndex.insert maintains RangeIndex when empty

### PR DESCRIPTION
**Pull request by mroeschke**
Discovered in https://github.com/pandas-dev/pandas/pull/57441

### CODE REVIEW

**Comment by mroeschke** [comment]
cc @WillAyd if you have time could you help look at the ASAN / UBSAN builds? It looks like recently they have been failing with `AddressSanitizer: DEADLY SIGNAL`?

**Comment by WillAyd** [comment]
That is definitely strange. Do you know when that first started? My guess is the error is coming from something in our conftest or a third party dependency, since it looks like it happens before the test suite even begins

**Comment by mroeschke** [comment]
This commit looks like it was the first one to exhibit the failure (but doesn't look like these changes should have caused it?) https://github.com/pandas-dev/pandas/commit/10f31f6a242fb01fdf37f5db2e8c6f4f82f5af16

**Comment by WillAyd** [comment]
Yea that looks unrelated. Guessing it's a dependency version issue

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @mroeschke

**Pull request merged**
