### PR TITLE
CLN: intp_t instead of int64_t for indexers in libs funcs

### PR DESCRIPTION
**Pull request by jbrockmendel**
The places where this will need updating proliferate, so right now im just looking to see how the 32bit builds handle this.

### CODE REVIEW

**Comment by jreback** [comment]
any perf diffs?

**Comment by jbrockmendel** [comment]
> any perf diffs?

very little.  except for a possibly-avoided copy in Categorical, it should only show up on 32bit

**Comment by jreback** [comment]
can you rebase

**Comment by jbrockmendel** [comment]
rebased + green

**Pull request merged**
