### PR TITLE
fix BUG #58524

### LINKED ISSUE #58524: BUG: DatetimeIndex.is_year_start breaks for business-day frequency where `n` is greater than 1
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [68]: dr = pd.date_range("2017-01-01", periods=2, freq="B")

In [69]: dr
Out[69]: DatetimeIndex(['2017-01-02', '2017-01-03'], dtype='datetime64[ns]', freq='B')

In [70]: dr.is_year_start
Out[70]: array([ True, False])

In [71]: dr = pd.date_range("2017-01-01", periods=2, freq="2B")

In [72]: dr
Out[72]: DatetimeIndex(['2017-01-02', '2017-01-04'], dtype='datetime64[ns]', freq='2B')

In [73]: dr.is_year_start
Out[73]: array([False, False])
```

### Issue Description

`'2017-01-02'` is recognised as year-start in one case, but not in the other

This hacky line is probably to blame

https://github.com/pandas-dev/pandas/blob/f2c8715245f3b1a5b55f144116f24221535414c6/pandas/_libs/tslibs/fields.pyx#L249

If anyone submits a fix, you probably want to parse the `n` and `freq` components of the offset, rather than messing around with `freqstr`

### Expected Behavior

both return the same result

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.9.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.146.1-microsoft-standard-WSL2
Version               : #1 SMP Thu Jan 11 04:09:03 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 65.5.0
pip                   : 24.0
Cython                : None
pytest                : 8.1.1
hypothesis            : 6.100.1
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.23.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.3.1
gcsfs                 : None
matplotlib            : 3.8.4
numba                 : 0.59.1
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 15.0.2
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.0
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>

### PR DESCRIPTION
**Pull request by Nrezhang**
- [ ] closes #58524
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Changed it to check the last character of the string so it handles if numbers in front. Works with the example, but not sure about if there are other cases that would break this. The fix seems almost too simple. Let me know :)

### CODE REVIEW

**Comment by Nrezhang** [comment]
Modified my PR to parse the characters in freqstr and check that for more flexibility

**Comment by Nrezhang** [comment]
Hi, when I run the pre-commit hooks pre-commit run --hook-stage manual --all-files, all the lines pass, but it seems like I have many failing checks. Could I have some guidance with how to understand which tests are failing and if there are issues with how I write my code? Thanks

**Comment by Aloqeely** [comment]
Hey, the pre-commit code checks are actually passing, the problem here is that some of the unit tests are failing

See this guide for running the unit tests locally: https://pandas.pydata.org/docs/dev/development/contributing_codebase.html#running-the-test-suite

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
