### PR TITLE
REF: change parameter name fname -> path

### LINKED ISSUE #23574: Change Name of `fname` Parameter to `path` in Parquet IO Methods
_Originally posted by @jreback in https://github.com/pandas-dev/pandas/pull/23321_

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #23574
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@datapythonista i think we discussed this recently: is there a way to make the docbuild output easier to identify the part that went wrong?  Also would be nice to have a way to test locally instead of having to flood the CI

**Comment by datapythonista** [comment]
I think for the docs is not trivial to generate the output in a GutHub Actions friendly way. I guess we can do the `sed` hack in the bash script, if the sphinx output has a consistent format.

But a better fix would be to implement a Sphinx extension, less hacky, and it could be reused by other projects. 

Not sure what do you mean by testing locally. What can't we test locally?

**Comment by jbrockmendel** [comment]
> Not sure what do you mean by testing locally. What can't we test locally?

I mean doing the docbuild locally so i can troubleshoot it without clogging the CI.

You've already gone above-and-beyond in making the CI easier to use, don't worry about this nitpicking.

**Comment by datapythonista** [comment]
if you installed the dependencies in the root `environment.yml` file, building the docs locally should be as easy as running `. /doc/make.py html`. I don't think anything else is missing, not sure if I'm missing something.

I'll have a look at making the errors in the output of the docs easier to find. I think those things are worth, since they save all us a significant amount of time. But I'll check for GitHub actions, since we're moving the docs build there. So it'll have to wait until #29874 is merged.

**Pull request merged**
