### PR TITLE
Backport PR #36927: BUG: Fix duplicates in intersection of multiindexes

### PR DESCRIPTION
**Pull request by simonjayhawkins**
Backport PR #36927

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@phofl can you give this a quick once over before I merge since there were several merge conflicts to resolve.

**Comment by simonjayhawkins** [comment]
> @phofl can you give this a quick once over before I merge since there were several merge conflicts to resolve, where I could have gone wrong.

**Comment by phofl** [comment]
Looks good. Should cover everything.

**Review by phofl — APPROVED** [review]
LGTM

**Comment by simonjayhawkins** [comment]
Thanks @phofl

**Pull request merged**
