### PR TITLE
DOC: Fixing flake8 error in basics.rst

### LINKED ISSUE #24173: DOC: Fix all flake8 issues and warning in the documentation pages
This issue is to track the pending work in making the `.rst` documentation pages be free of PEP-8 and other flake8 issues, and to not generate warnings.

| Page                         | flake8 | warnings |
|------------------------------|--------|----------|
| `10min.rst`                  | FAIL: #24174 | FAIL |
| `advanced.rst`               | OK: #24182 | FAIL |
| `api.rst`                    | OK | FAIL |
| `basics.rst`                 | FAIL | FAIL |
| `categorical.rst`            | OK: #24182 | FAIL |
| `comparison_with_r.rst`      |  OK    | FAIL |
| `comparison_with_sas.rst`    | OK: #24182 | FAIL |
| `comparison_with_sql.rst`    | OK: #24182 | FAIL |
| `comparison_with_stata.rst`  | OK: #24182 | FAIL |
| `computation.rst`            | OK     | FAIL |
| `contributing.rst`           | OK: #24182 | FAIL |
| `contributing_docstring.rst` | FAIL | FAIL |
| `cookbook.rst`               | OK: #23794 | FAIL |
| `developer.rst`              | OK     | FAIL |
| `dsintro.rst`                | FAIL: #24175 | FAIL |
| `ecosystem.rst`              | OK     | FAIL |
| `enhancingperf.rst`          | FAIL: #24176 | FAIL |
| `extending.rst`              | OK: #24182 | FAIL |
| `gotchas.rst`                | OK     | FAIL |
| `groupby.rst`                | FAIL: #24178 | FAIL |
| `index.rst`                  | OK     | FAIL |
| `indexing.rst`               | PR: #24089 | FAIL |
| `install.rst`                | OK     | FAIL |
| `internals.rst`              | OK     | FAIL |
| `io.rst`                     | OK: #23791 | FAIL |
| `merging.rst`                | FAIL: #24179 | FAIL |
| `missing_data.rst`           | PR: #24089 | FAIL |
| `options.rst`                | PR: #24089 | FAIL |
| `overview.rst`               | OK     | FAIL |
| `r_interface.rst`            | OK     | FAIL |
| `release.rst`                | PR: #24089 | FAIL |
| `releases.rst`               | OK     | FAIL |
| `reshaping.rst`              | FAIL: #24180 | FAIL |
| `sparse.rst`                 | OK     | FAIL |
| `text.rst`                   | OK     | FAIL |
| `timedeltas.rst`             | OK     | FAIL |
| `timeseries.rst`             | OK     | FAIL |
| `tutorials.rst`              | OK     | FAIL |
| `visualization.rst`          | FAIL: #24181 | FAIL |

After this issue is closed, we shouldn't have any file (other than the whatsnew pages) in the `exclude` section of `flake8-rst` in `setup.cfg`, and we should be able to enable the `-W` flag for `sphinx-build` in `doc/make.py`.

CC: @FHaase

### PR DESCRIPTION
**Pull request by iamshreeram**
- [x] closes #24173 and follow up on it
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by iamshreeram** [comment]
Not sure why `https://codecov.io/gh/pandas-dev/pandas/compare/9f93d57025d7b906de6956f287b71cd18c17b13d...80a2027ce6d762c24ae62853fb77c6aed113e073` failed. There were no changes other than adding example for pipe() in `basics.rst`

**Review by datapythonista — CHANGES_REQUESTED** [review]
Thanks for working on this @iamshreeram.

My preference would be to find something that looks like a real example, not those `h`, `g`,... abstract functions. I think to most people (at least surely myself), understanding the point of that example is not that easy, and it's not obvious to imagine a case where you'd want to use that. I think with something that looks like real data, and real transformations will be much easier.

It's not easy (that's why this hasn't been fixed yet), but surely doable.

Thanks!

**Comment by WillAyd** [comment]
Hi @iamshreeram - can you merge master and address comment?

**Comment by iamshreeram** [comment]
Sure @WillAyd . I will work on it.

**Comment by jreback** [comment]
can you merge master

**Comment by datapythonista** [comment]
Closing as stale

**Pull request closed without merging**
