### PR TITLE
ENH: Add query functionality to skiprows param in read_csv

### LINKED ISSUE #32072: Feature Request: "Skiprows" by a condition or set of conditions
#### Code Sample, a copy-pastable example if possible

```python
# data file path: foo/bar/data.csv
  col_1 col_2  ...  col_n
0   940    45  ...  0.023
1  1040    52  ...  0.430
2  1530    45  ...  0.302
3   753    43  ...  0.450
4   890    32  ...  0.023

schema={
    "col_1": int,
    ...,
    "col_n": float
}
mask = (col_1 >= 1000)
df = pd.read_csv('foo/bar/data.csv', skiprows=mask, dtype=schema)

```

#### Problem description

Pandas read methods currently support skipping rows by index with the parameter `skiprows`. It'd be a good feature if usage of `skiprows` is extended in way that it can take conditional statements just like many pandas objects. I anticipate that this feature may not be useful to all, it is certain that it will ease the people's pain who are dealing with many (large) files. Memory usage would drastically be downed in some situations I think. 

I am opening this issue with hoping a welcome on dev side, not opening this because it first glanced as a fancy request, but because I think it may affect many people's work in a good way. It may be later used as a schema reference as well. Similar to schema validation of a data set.

**NOTE:** I am uncertain how can this be achieved or even if it can be done at all. It may not apply to pandas module. Consider this also as a brain storming.

#### Expected Output

This requires passing column names & dtype (schema) before reading the file, but I am not sure how to convey the mask for skiprows it should be similar to `pandas.DataFrame` condition & masks, but we may only pass column names since there is no `pandas.DataFrame` object.

```
  col_1 col_2  ...  col_n
0  1040    52  ...  0.430
1  1530    45  ...  0.302

```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.18.0
pytz             : 2019.2
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0
Cython           : 0.29.12
pytest           : 5.3.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.2.0
lxml.etree       : 4.3.4
html5lib         : None
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : 0.4.0
scipy            : 1.3.1
sqlalchemy       : None
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : 1.2.0

</details>

### PR DESCRIPTION
**Pull request by slimnsour**
This allows users to pass in strings to query through the ``skiprows`` parameter in ``pandas.read_csv``. This is done through querying the Dataframe as soon as it is created, and returning a Dataframe with the desired columns to the user. 

Included in this PR are the relevant whatsnew entry, documentation changes, and new tests.

- [X] closes #32072
- [x] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
this completely changes the semantics of skiprows. its a nice idea, and *maybe* as a callable we might accept this, but am -1 on using query.

**Comment by TomAugspurger** [comment]
Agreed that we shouldn't proceed in the current form. Passing a string expression implies (at least to me) that the filtering happens before the data is loaded into a DataFrame.

**Review by mroeschke — CHANGES_REQUESTED** [review]
It looks like the conclusion of the original issue was to add a documentation example of using `query` instead of adding this directly in `read_csv`. Are you interested in documenting this example?

https://github.com/pandas-dev/pandas/issues/32072#issuecomment-588544984

**Comment by slimnsour** [comment]
Skiprows being separate makes sense to me. In the latest change I added a new parameter ``conditionalrows`` that performs the query functionality instead. I feel this is a nice thing for users to have when reading in data, so hopefully this is a better integration of the idea.

If it's still a better idea to separate query from read_csv entirely, I can take a look at improving the documentation instead.

**Comment by TomAugspurger** [comment]
I don't think we should add any kind of "query" functionality to `read_csv` unless it's reducing the peak memory usage. For anything that's equivalent to `read_csv(...).query(...)` (i.e. read all the data, construct the DataFrame, then query) the user should just write that.

**Comment by jreback** [comment]
I think an example in the docs or cookbook along the lines of 

```result = pd.concat([df.query(...) for df in pd.read_csv(...., chunksize=...)], ignore_index=True)```

is ok

**Comment by devrimcavusoglu** [comment]
> Skiprows being separate makes sense to me. In the latest change I added a new parameter `conditionalrows` that performs the query functionality instead. I feel this is a nice thing for users to have when reading in data, so hopefully this is a better integration of the idea.
> 
> If it's still a better idea to separate query from read_csv entirely, I can take a look at improving the documentation instead.

I totally agree on this. Remaining `skiprows` separate and adding a new query param is a lot nicer and reasonable. I think it'd be great to support query-like param while reading the data. I know pretty much `df.read_csv(..., chunksize=...).query(...)` does the trick, but this query-like feature would be nice for users.

**Comment by jreback** [comment]
closing this as wont fix
but would take a doc example if you want

**Pull request closed without merging**
