### PR TITLE
Remove ix, part 1

### PR DESCRIPTION
**Pull request by topper-123**
- [ ] xref #15113 and #26438 

First part of removal od ``NDFrame.ix``.  There's still alot of tests for this, so I'll do this removal in 2-3 steps. This PR removes pandas/tests/indexing/test_ix.py and tests for ix in a few more places.

### CODE REVIEW

**Comment by topper-123** [comment]
Just seen #6581, where it says ix is to be removed in 1.2. So this is perhaps too early?

**Comment by WillAyd** [comment]
Anything deprecated prior to 0.25 is good to remove for 1.0, so no issue there.

There is however #27620 out there as well

**Comment by jreback** [comment]
ix is good to remove now

**Comment by topper-123** [comment]
I’ll just close this down, given that #27620 is already on this...

**Pull request closed without merging**
