### PR TITLE
Use Sphinx RTD Theme

### LINKED ISSUE #15556: DOC: more modern sphinx theme
We currently use a slightly adapted version of the 'nature' theme (you can also see it in this list of built-in themes: http://www.sphinx-doc.org/en/stable/theming.html#builtin-themes).

I think this can use an update, for some reasons:

- a mobile friendly theme (more and more useful, and currently this completely fails on mobile)
- more powerful theme (allowing eg better nested structure of the docs, which could enable a reorganisation of the docs. Now we have a single flat table of contents on the left)
- refreshed look (but this is subjective of course :-))

(could go together with a refresh of the main website as well, but not necessarily I think)

http://www.writethedocs.org/guide/tools/sphinx-themes/

### PR DESCRIPTION
**Pull request by WillAyd**
- [X] closes #15556 

TOC on the left hand side is pinned during navigation and also expandable/collapsible

image

image

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Should we be re-styling the website at the same time as the docs? Or would people be OK with changing those at different times?

@WillAyd have you looked at the http://pandas-docs.github.io/pandas-docs-travis/user_guide/style.html page with this theme?

**Comment by WillAyd** [comment]
@TomAugspurger sorry just seeing this now. That theme looks OK to me!

I'm not terribly tied to the this PR but opened because:

  1. I think it's regardless an improvement over the nature theme
  2. Would be entirely external to pandas (no theme vendoring or changes required)
  3. Has a better dropdown on the left (i.e. doesn't require navigating to page to expand options)
  4. It's easy

If there's not an appetite for it though certainly can close

**Comment by WillAyd** [comment]
> Should we be re-styling the website at the same time as the docs? Or would people be OK with changing those at different times?

To answer this explicitly I think different times is fine. I don't see a super tight harmony between existing site and docs (though more than RTD) and wouldn't want to try a super big change at once.

**Comment by TomAugspurger** [comment]
That's fair.

Thoughts on holding off on this till we hear if we line up someone to work on our docs as part of that NUMFocus grant?

**Comment by WillAyd** [comment]
Yep works for me - no real urgency here.

**Pull request closed without merging**
