### PR TITLE
PERF: avoid is_dtype_equal

### PR DESCRIPTION
**Pull request by jbrockmendel**
This gets rid of all our non-test usages.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Will need to wait until we bump our minimum numpy version, not sure when exactly numpy fixed `np.dtype.__eq__` to not raise

**Comment by jbrockmendel** [comment]
mothballing to clear the queue

**Comment by jbrockmendel** [comment]
Looks like this is now viable since we've bumped our min numpy version

**Review by mroeschke — COMMENTED** [review]
Looks okay. Just a merge conflict

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
