### PR TITLE
CI: Pin matplotlib to < 3.7.0

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
whats the condition under which we can revert the pin?

**Comment by phofl** [comment]
#51394 links a failing build.

Not really familiar with how matplotlib works, but couldn't find a whatsnew that references this

**Comment by MarcoGorelli** [comment]
> whats the condition under which we can revert the pin?

[taking plotting out of pandas](https://github.com/pandas-dev/pandas/issues/50059) 😄

**Review by MarcoGorelli — APPROVED** [review]
There's failures because of both MPL and openpyxl, and here you're only pinning MPL (hence some CI failures)?

Looks good to me

**Comment by phofl** [comment]
Yep, merging both should get ci green.

**Comment by phofl** [comment]
Makes reverting easier when doing it separately

**Pull request merged**
