### PR TITLE
Misc. Typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**
Both user and non-user facing. Found via `codespell -q 3  -I ../pandas-whitelist.txt` whereby the whitelist consisted of: 
```
behaviour
indicies
initialise
initialised
initialising
resetted
thru
writeable
```

### CODE REVIEW

**Comment by jreback** [comment]
thanks @luzpaz 

have a look at https://travis-ci.org/pandas-dev/pandas/jobs/322503804

couple of linting issues (now lines too long) as well as a failing test that checks the error message (you can adjust the test / message).

**Comment by luzpaz** [comment]
@jreback apologies, i'm having trouble understanding the errors of the tests on TravisCI. Are all of those issues related to this PR ? Can you give me an example of lines that are too long? I'll be happy to fix, I'm not yet down with the lingo. Thank you.

**Comment by jreback** [comment]
``git diff master --name-only -- "*.py" | grep "pandas" | xargs flake8``

will show the linting issues

**Comment by jreback** [comment]
also you need to merge master. and there is 1 test failure as indicated.

**Comment by luzpaz** [comment]
@jreback After I rebase, should I force push or just create another commit ?

**Comment by jreback** [comment]
you can force push if you rebase, or simply ``git merge master`` and just keep pushing commits.

**Comment by jreback** [comment]
2nd is prob easier

**Comment by jreback** [comment]
thanks @luzpaz nice patch!

**Pull request merged**
