### PR TITLE
REGR: MultiIndex Indexing

### LINKED ISSUE #35351: BUG: multiindex slice 1.1.0rc0
mulitindex slicing returns different (from pandas<=1.0.x) results in pandas 1.1.0rc0

```
df = pd.DataFrame( data=[[0,1,'a',1],[1,0,'a',0],[1,1,'b',1],[1,1,'c',2]], columns=['index','date','author','price'] )

# to keep the most recent date for every index (could happen in practice)
idx = df.drop_duplicates('index',keep='last').set_index(['index','date']).index 

df.set_index(['index','date']).loc[idx,:].reset_index()
```

df

 index | date  | author | price
-- | -- | -- | --
0|1|a | 1
1|0|a | 0
1|1|b | 1
1|1|c | 2

Result

  | | author | price
 -- | -- | --
(0, 1) | a | 1
(1, 1) | b | 1
(1, 1) | c | 2

### PR DESCRIPTION
**Pull request by simonjayhawkins**
- [ ] closes #35351
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
I'll add tests if nothing breaks. I'm not keen on special casing the base Index method, but overriding _reindex_non_unique maybe overkill. maybe better to revert part of #33691

**Comment by simonjayhawkins** [comment]
test failures unrelated, see #35350 so marking as ready for review. whatsnew needed for regression in rc?

**Comment by TomAugspurger** [comment]
Thanks, LGTM.

> whatsnew needed for regression in rc?

I don't think so.

**Comment by jreback** [comment]
mpl issue breaking the docs?

**Review by jreback — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
rebased and green. since this is for 1.1, I suppose this could be merged even without a firm decision on the branch strategy.

**Comment by TomAugspurger** [comment]
Yep, thanks.

**Pull request merged**
