### PR TITLE
fix broken Docker image build

### LINKED ISSUE #45807: BUG: ERROR building development env using Docker
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
docker build --tag pandas-numberpioso-env .

ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pandas/setup.py'"'"'; __file__='"'"'/home/pandas/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.


<details>
  Running setup.py develop for pandas
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pandas/setup.py'"'"'; __file__='"'"'/home/pandas/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/pandas/
    Complete output (25 lines):
    running develop
    running egg_info
    writing pandas.egg-info/PKG-INFO
    writing dependency_links to pandas.egg-info/dependency_links.txt
    writing entry points to pandas.egg-info/entry_points.txt
    writing requirements to pandas.egg-info/requires.txt
    writing top-level names to pandas.egg-info/top_level.txt
    reading manifest file 'pandas.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /tmp/pip-build-env-lkhctcw3/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:157: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /tmp/pip-build-env-lkhctcw3/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    no previously-included directories found matching 'doc/build'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '#*' found anywhere in distribution
    warning: no previously-included files matching '*.py[ocd]' found anywhere in distribution
    adding license file 'LICENSE'
    running build_ext
    building 'pandas._libs.algos' extension
    /opt/conda/compiler_compat/ld: cannot find /lib64/libpthread.so.0
    /opt/conda/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a
    collect2: error: ld returned 1 exit status
    error: command '/opt/conda/bin/gcc' failed with exit code 1
    ----------------------------------------
</details>
```

### Issue Description

Last command  `python -m pip install -e . ` at the Dockerfile fails:

https://github.com/pandas-dev/pandas/blob/5c757e9c4cf6a74fabfa1983dcd72b4759a88e5f/Dockerfile#L42-L48

Running manually those lines at docker image is successful until we arrive at this one
 `python -m pip install -e . `

### Expected Behavior

I would expect that the image should be successfully built

```bash
> docker build --tag pandas-numberpioso-env
Successfully built a3c5533304a3
Successfully tagged pandas-numberpioso-env:latest
```

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 5c757e9c4cf6a74fabfa1983dcd72b4759a88e5f
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-28-generic
Version          : #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+277.g5c757e9c4c.dirty
numpy            : 1.19.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 59.8.0
Cython           : 0.29.26
pytest           : 6.2.5
hypothesis       : 6.36.0
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fastparquet      : 0.7.2
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
matplotlib       : 3.5.1
numba            : 0.55.0
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : 1.1.4
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.7.3
sqlalchemy       : 1.4.30
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

### PR DESCRIPTION
**Pull request by rendner**
- [X] closes #45807

This PR adds a missing flag to successfully build the pandas Docker image.

### CODE REVIEW

**Comment by NumberPiOso** [comment]
I have not tested the environment itself, but I could build the docker image properly.
```bash
docker build --tag pandas-pr45807-env .
Successfully built ba38c2d0969f
Successfully tagged pandas-pr45807-env:latest
```

I think a test to test the build of this image could avoid the same mistake.

**Comment by jreback** [comment]
sure would welcome a test of this.

**Comment by mroeschke** [comment]
> Can you give me a pointer where I should create such a test?

Maybe the easiest thing is to create a "no-op" Github action (in `code-checks.yml`) that builds the Dockerfile: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

**Comment by rendner** [comment]
I created a new job in the mentioned `code-checks.yml`. 

I have run the new build job twice and both failed. There were different `CondaHTTPError: HTTP 404 NOT FOUND` errors:

- [first](https://github.com/pandas-dev/pandas/runs/5169893922?check_suite_focus=true#step:3:1051)
- [second](https://github.com/pandas-dev/pandas/runs/5170008127?check_suite_focus=true#step:3:1050)

Another problem which I currently see is that in the Dockerfile the [main branch](https://github.com/pandas-dev/pandas/blob/main/Dockerfile#L27-L31) is used to build the Docker image. Therefore, changes in a PR outside of the Dockerfile are only taken into account after they are merged into the main branch. This means that even if the job runs successfully for the PR, it can fail after the merge into the main branch.

**Comment by mroeschke** [comment]
For the 404, maybe make sure `-c conda-forge` is passed when installing the deps from `environment.yml`.

I'm guessing this Dockerfile shouldn't change much ideally so I think it's a good first pass test for this PR

**Comment by rendner** [comment]
@mroeschke 
For me it looks like that the `conda-forge` channel is used (as configured). The problem seems to be that it tries to download non-existing `conda` files instead of the existing `tar.bz2` files.

What I tried in the meantime:

- I added `conda config --set use_only_tar_bz2 true`
	-> flag was added to `/root/.condarc`: https://github.com/pandas-dev/pandas/runs/5183038474?check_suite_focus=true#step:4:569
	-> results into the same problem: 11 non-downloadable conda files (it seems the flag isn't taken into account)
	
- I updated conda before installing mamba: `conda update -n base conda`
	-> results into the same problem: but 10 non-downloadable conda files instead of 11
	
Since I am not familiar with conda and mamba, I would need help at this point. I have enabled additional debug output:

- [conda info + conda config](https://github.com/pandas-dev/pandas/runs/5184695517?check_suite_focus=true#step:4:546)
- [mamba env update with debug output](https://github.com/pandas-dev/pandas/runs/5184695517?check_suite_focus=true#step:4:670)

Maybe you can find something.
I also recognized that the `Dockerfile` and the `ci/setup_env.sh` use different steps to configure the setup.

**Comment by mroeschke** [comment]
For now, I think it's best to just make the Dockerfile changes here and open a new issue about testing the Dockerfile in the CI (i.e. revert the Github Action job changes).

I don't use the Dockerfile for local development so I am not sure where the issue might be

**Comment by rendner** [comment]
I digged a lilte bit deeper, to identify why the problem didn't happen locally. 

Starting with `quay.io/condaforge/miniforge3:4.11.0-2` (released 2022-02-11) I see the strange `download non-existant .conda URLs` behavior.
The previous versions seem to work.

Here is a reduced Dockerfile to demo the problem:
```
# first non working base image
FROM quay.io/condaforge/miniforge3:4.11.0-2

# last working base image
# FROM quay.io/condaforge/miniforge3:4.11.0-0

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Configure apt and install packages
RUN apt-get update \
    && apt-get -y install --no-install-recommends apt-utils dialog 2>&1 \
    #
    # Verify git, process tools, lsb-release (common in install instructions for CLIs) installed
    && apt-get -y install git iproute2 procps iproute2 lsb-release \
    #
    # cleanup
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

COPY environment.yml environment.yml

RUN conda install -y mamba
RUN mamba env update -n base -f environment.yml
```

I will pin the base image and see if the CI can run the test.

**Comment by rendner** [comment]
@mroeschke The PR is ready for review from my side.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Excellent! Thanks @rendner

**Comment by NickCrews** [comment]
Thank you @rendner! I was having trouble getting docker to build, but I assumed it was on my end, so just gave up because I didn't want to dig into the weeds. Thank you for doing this, it works now for me!

**Comment by rendner** [comment]
The latest version `quay.io/condaforge/miniforge3:4.11.0-4` (released Feb 26, 2022) works again. 

This seems to be the commit which temporary solves the problem: https://github.com/conda-forge/miniforge/commit/5429a0fe6e37cc996327be9e5496df2d1f011cba

@mroeschke 
We could unpin the version of the base image or wait until it is fully resolved. What do you think?

*Note:*
After unpinning the base image, users who have the broken image `quay.io/condaforge/miniforge3:4.11.0-2` as the latest version locally must delete the image or use build option [--pull](https://docs.docker.com/engine/reference/commandline/build/#options) to be able to build successfully.

**Comment by mroeschke** [comment]
Sure. As long as our CI check can replicate a Docker build with an image that works correctly, updating the version should be fine

**Pull request merged**
