### PR TITLE
DOC: fix EX02 errors in docstrings

### PR DESCRIPTION
**Pull request by lia2710**
Some work towards issue https://github.com/pandas-dev/pandas/issues/51236

Makes docstrings pass EX02 error for:
```
pandas.plotting.radviz
pandas.tseries.frequencies.to_offset
```

### CODE REVIEW

**Comment by lia2710** [comment]
doctests and doctrings had a conflict on `pandas.plotting.radviz` example return.
doctests got `<AxesSubplot: xlabel='y(t)', ylabel='y(t + 1)'>`
doctrings got `<AxesSubplot: >`

**Comment by MarcoGorelli** [comment]
you're right - I'll take a look at why that might be

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
for the plot one, I think we should just remove the output and skip them, like is done here

https://github.com/pandas-dev/pandas/blob/3f2b18aed1468d3643bf638f7859cacf3141c8f4/pandas/plotting/_core.py#L333-L339

It's not really a meaningful doctest anyway, `<AxesSubplot: >` could include anything 😄

**Comment by lia2710** [comment]
> for the plot one, I think we should just remove the output and skip them, like is done here
> 
> https://github.com/pandas-dev/pandas/blob/3f2b18aed1468d3643bf638f7859cacf3141c8f4/pandas/plotting/_core.py#L333-L339
> 
> It's not really a meaningful doctest anyway, `<AxesSubplot: >` could include anything 😄

Thank you. Will do.

Just out of curiosity, do you happen to know that why doctests got <AxesSubplot: xlabel='y(t)', ylabel='y(t + 1)'>? I ran the plot on python console and got <AxesSubplot: > too.

**Comment by MarcoGorelli** [comment]
I think it's because one of the doctests (hist_plot if I remember right) from _core.py doesn't have the doctest+skip, and so was setting some option

**Review by MarcoGorelli — APPROVED** [review]
thanks @lia2710 !

**Pull request merged**
