### PR TITLE
CI: added unwanted pattern test case for "foo.__class__" instead of type(foo)

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

ref #29816 (splitted to #29889, #29893, #29894, #29902, #29904, #29905)

### CODE REVIEW

**Comment by WillAyd** [comment]
Looks good. To be sure can you intentionally change the code somewhere to make this fail so we can see how it looks in CI?

**Comment by MomIsBestFriend** [comment]
ping @WillAyd

**Comment by alimcmaster1** [comment]
image

This is how it looks in CI. Might be worth adding something that explains one should use type()?

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Great thanks @MomIsBestFriend

**Pull request merged**
