### PR TITLE
DEPR: Remove SparseDataFrame/Series pickle compat

### PR DESCRIPTION
**Pull request by mroeschke**
Follow up to https://github.com/pandas-dev/pandas/pull/49218

Also some pickles generated with 0.20.3 contained these objects, so thought to remove since the pandas version is very old

### CODE REVIEW

**Review by phofl — APPROVED** [review]
no whatsnew needed?

**Comment by mroeschke** [comment]
> no whatsnew needed?

Thanks. Noted in the whatsnew removal of SparseFrame/Series that pickle support was also removed.

**Comment by aterrel** [comment]
@mroeschke this cause a regression, was there a decision to stop support 0.20? If so I can update the documentation, which says we do support 0.20 pickle files.

**Comment by cliffckerr** [comment]
I think it would be great if backwards compatibility could be maintained. I don't think it's sufficient to just update the documentation now, because promises of backwards compatibility (as `pd.read_pickle()` has) can't be un-promised in the same way that other aspects of the API can be updated, especially without a deprecation warning first. If this were a major version change (e.g. `pandas 2.x → 3.x`) it would be more understandable, but as it is, this seems like a major inconvenience to some users (disclosure: including me 🙂).

**Pull request merged**
