### PR TITLE
COMPAT: Ensure rolling indexers return intp

### LINKED ISSUE #35148: CI: MacPython failing test_consistency_with_window
https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=38672&view=logs&j=c0130b29-789d-5a3c-6978-10796a508a7f&t=e120bc6c-1f5e-5a41-8f0a-1d992cd2fbfb&l=1286

```python
    def test_consistency_with_window():
    
        # consistent return values with window
        df = test_frame
                index_array = self.index_array
            indexer = self.rolling_indexer(
                index_array=index_array, window_size=self.window_size,
            )
            start, end = indexer.get_window_bounds(
                len(indicies), min_periods, center, closed
            )
            start = start.astype(np.int64)
            end = end.astype(np.int64)
            # Cannot use groupby_indicies as they might not be monotonic with the object
            # we're rolling over
            window_indicies = np.arange(
                window_indicies_start, window_indicies_start + len(indicies),
            )
            window_indicies_start += len(indicies)
            # Extend as we'll be slicing window like [start, end)
            window_indicies = np.append(
                window_indicies, [window_indicies[-1] + 1]
            ).astype(np.int64)
>           start_arrays.append(window_indicies.take(start))
E           TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

test_venv\lib\site-packages\pandas\core\window\indexers.py:318: TypeError
```

cc @mroeschke if you know where to look / who to ping. I haven't looked yet.

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #35148
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Unable to test this locally for the MacPython build, but I am pretty sure this is the main culprit of that failing job.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
you can leave entirely in int64 as we do now for all rolling ops

except when you are going to .take() something u have to wrap ensure_intp_dtype around the array

windows should be affected but pass by this change

**Comment by mroeschke** [comment]
Wouldn't it be better if all the indexers were just platform int to begin with so we don't have to worry about casting?

**Comment by jreback** [comment]
no int64 are fine

**Review by jreback — CHANGES_REQUESTED** [review]
@mroeschke none of this is needed or a good idea. you *only* need to ensure_platform_int when indexing via .take

**Comment by mroeschke** [comment]
Going to start over in a new branch

**Comment by TomAugspurger** [comment]
> @mroeschke none of this is needed or a good idea. you only need to ensure_platform_int when indexing via .take

How do we know that it's safe to cast at take time? Ensuring that indicies are the platform int seems like the way to go.

**Comment by TomAugspurger** [comment]
@mroeschke in case it helps, here's the dockerfile I'm using locally

```
FROM quay.io/pypa/manylinux1_i686

RUN /opt/python/cp38-cp38/bin/python -m pip install \
  cython \
  numpy \
  python-dateutil \
  pytz \
  pytest \
  hypothesis
COPY pandas /pandas
RUN cd /pandas && /opt/python/cp38-cp38/bin/python setup.py build_ext -i -j 4
```

Then run it and mount the `pandas/` directory to `/pandas` so you can easily test things.

**Pull request closed without merging**
