### PR TITLE
BUG: Series/Index contains NaT with object dtype comparison incorrect

### LINKED ISSUE #9005: BUG: comparing 'NaT' in series with series returns True
xref #12877 (test on Series & DataFrame)

When having a 'NaT' in a datetime series and comparing this to a datetime series, the comparison with NaT returns True (and shouldn't comparisons with NA not always return False?) Comparing it with a scalar does return False:

```
In [54]: s = pd.Series([pd.Timestamp('2012-01-01'), pd.Timestamp('NaT')])
In [55]: s2 = pd.Series([pd.Timestamp('2013-01-01'), pd.Timestamp('2014-01-01')])

In [57]: s
Out[57]:
0   2012-01-01
1          NaT
dtype: datetime64[ns]

In [58]: s2
Out[58]:
0   2013-01-01
1   2014-01-01
dtype: datetime64[ns]

In [59]: s < s2
Out[59]:
0    True
1    True
dtype: bool

In [60]: s < pd.Timestamp('2013-01-01')
Out[60]:
0     True
1    False
dtype: bool
```

Original from http://stackoverflow.com/questions/27305324/pandas-comparison-with-variable-number-of-columns/27305661#27305661

### PR DESCRIPTION
**Pull request by sinhrks**
- [x] closes #9005 
- [x] tests added / passed
- [x] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry

`Series` and `Index` compares `NaT == NaT` as `True` if it has `object` dtype. 

```
pd.Series([pd.NaT])
#0   NaT
# dtype: datetime64[ns]

# OK
pd.Series([pd.NaT]) == pd.NaT
#0    False
# dtype: bool

# NG in object dtype
pd.Series([pd.NaT], dtype=object) == pd.NaT
#0    True
# dtype: bool

# OK
pd.Index([pd.NaT]) == pd.NaT
array([False], dtype=bool)

# NG in object dtype
pd.Index([pd.NaT], dtype=object) == pd.NaT
# array([ True], dtype=bool)
```

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. Do we have an associated issue? I do recall this somewhere.

**Comment by sinhrks** [comment]
Maybe #9005, though it looks to be fixed on current master (but added tests for native/object dtypes).

**Comment by sinhrks** [comment]
Ah, found #9005 is not fixed if ``NaT`` is on rhs. On current master:

```
pd.Series([pd.Timestamp('2011-01-01')]) > pd.Series([pd.NaT])
# 0    True
# dtype: bool
```

Already included the fix to this PR.

**Comment by jreback** [comment]
thanks!

**Pull request merged**
