### PR TITLE
CI: pin fsspec

### PR DESCRIPTION
**Pull request by mzeitlin11**
Hopefully fixes new Windows py37_np17 failures

### CODE REVIEW

**Comment by jreback** [comment]
ok exciting, ping on green.

**Comment by jreback** [comment]
@simonjayhawkins we *may* want to do this for 1.2.5

**Comment by simonjayhawkins** [comment]
sure. maybe best to just backport ci changes to 1.3 for now, and i'll go through the backports and backport any needed to 1.2.5

**Comment by mzeitlin11** [comment]
The azure failure timed out on this latest run, but succeeded on previous commit, so greenish

**Comment by jreback** [comment]
thanks @mzeitlin11

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
