### PR TITLE
DOC: reduce API docs for offset aliases

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Test to see if this works with sphinx

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Nice, there are some other aliases we could do the same for if this works.

Also some methods/properties that dont need to be advertised, e.g. `__call__`

**Comment by jorisvandenbossche** [comment]
Yeah, first need to see if it works ;) 
(locally it did, but I would actually expect to need to edit the BDay docstring to ensure it lists no methods/attributes, similar as eg the docstring of DatetimeArray)

**Comment by jorisvandenbossche** [comment]
It seems to work.

Can you say which are the aliases? Just the ones here?

https://github.com/pandas-dev/pandas/blob/5239cfa612b1798b8da46c7380c321c7e598214c/pandas/_libs/tslibs/offsets.pyx#L3487-L3494

**Comment by jbrockmendel** [comment]
I think thats all of them, yes.

**Pull request merged**
