### PR TITLE
Add Python 3 support and optional parameter "silent" for read_gbq

### PR DESCRIPTION
**Pull request by ghost**
Google's libraries support Python 3 since version 1.4.0, so we could add support for Python 3 in read_gbq method.
Also it is not always useful to see "Job not yet complete" printings, so I've added optional parameter that allows disable it.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Ca you:

* also update the tests?
* add a release note in whatsnew/v0.17.0.txt ?

**Comment by jreback** [comment]
these tests are all skipped on py3 (as I don't think the libraries are event installed), e.g. ``ci/requirements-3.4.txt`` (as compared to 2.7)

**Comment by jreback** [comment]
I don't believe ANY of the tests are actually run on travis; they are all skipped because of some import issues.

**Comment by a-rodin** [comment]
Than would it be merged?

**Comment by jreback** [comment]
if we have sufficient test coverage and validation

**Comment by jreback** [comment]
cc @parthea

**Comment by jreback** [comment]
issue is now #11094 

pls reopen if you wish to update this issue

**Comment by parthea** [comment]
@a-rodin From version `0.17.0` onwards, you can use the `verbose` flag to disable printing. 

eg.
`pd.read_gbq('SELECT * FROM test_dataset.test_table', projectid, verbose=True)`

See the documentation here :
http://pandas-docs.github.io/pandas-docs-travis/io.html#io-bigquery

**Pull request closed without merging**
