### PR TITLE
CI: add validate_unwanted_patterns to known_third_parties

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

By using `seed-isort-config`, the `known_third_party` setting is automatically populated and alphabetically sorted. This is a cleaner solution which doesn't require manually adding third parties to `setup.cfg`.

Furthermore, it catches an existing inconsistency: currently, `validate_docstrings` is set as a known third party, while `validate_unwanted_patterns` isn't. Neither should be, IMO.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
We had this and removed it in https://github.com/pandas-dev/pandas/pull/28272 (see some discussions there). I think I struggled the most with it, dunno if it hit other contributors.

**Comment by MarcoGorelli** [comment]
@TomAugspurger thanks for pointing me towards that - OK, am happy to not add `seed-isort-config` if it causes issues.

Should `validate_docstrings` be removed from the list of known_third_parties though?

**Comment by TomAugspurger** [comment]
Don't know. It's not in the pandas namespace, so probably not? Don't have a strong preference though.

**Comment by MarcoGorelli** [comment]
Sure - have removed that and added `validate_unwanted_patterns` to the list of known 3rd parties (I presume they should either both be there, or neither?)

**Comment by WillAyd** [comment]
I think this is fine

**Review by jreback — APPROVED** [review]
lgtm

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
