### PR TITLE
TST: to_json keeps column info with empty dataframe (#7445)

### LINKED ISSUE #7445: Column information lost in to_json() if data frame is empty
Create empty dataframe with a column and write it out with to_json(), then read it back in:

```
In [55]: s = pandas.DataFrame({'test': [] }, index=[] ).to_json(orient='columns')
In [56]: s
Out[56]: '{}'
In [57]: str( pandas.read_json(s, orient='columns') )
Out[57]: 'Empty DataFrame\nColumns: []\nIndex: []'
```

I think the expected string is '{"test":{}}'

This situation arises when code filters data frames and writes them out, while not being very careful to make sure the filtered frames contain at least one row.

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #7445
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master | flake8 --diff``

Closed by #9805

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]
Perfect!

**Comment by jreback** [comment]
the original issue has sufficient tests AFICT. what does this add?

**Comment by jorisvandenbossche** [comment]
Ah, yes, that is maybe true. The original PR has roundtrip tests for empty frames, while this one adds an explicit test of the output format in such a case. So that's maybe slightly useful to add, but in any case, if we keep it, would be good to have them at the same place

**Comment by mroeschke** [comment]
Agreed, makes sense to move it to `test_frame_empty`. Doesn't look like this specific case is tested there. I'll make the change later tonight.

**Comment by jreback** [comment]
thanks!

**Pull request closed without merging**
