### PR TITLE
BUG: Handle Datetimelike data in DataFrame.combine

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/23079

### CODE REVIEW

**Comment by TomAugspurger** [comment]
After this, we'll need an additional change on the PeriodArray PR:

```diff
commit f73f83e2878e04d266d8f86c2675d6c1fae6d90e
Author: Tom Augspurger <tom.w.augspurger@gmail.com>
Date:   Wed Oct 24 11:28:59 2018 -0500

    TST: Unxfail combine

diff --git a/pandas/core/dtypes/cast.py b/pandas/core/dtypes/cast.py
index 56bf39472..46c8126f6 100644
--- a/pandas/core/dtypes/cast.py
+++ b/pandas/core/dtypes/cast.py
@@ -6,7 +6,7 @@ import numpy as np
 import warnings
 
 from pandas._libs import tslib, lib, tslibs
-from pandas._libs.tslibs import iNaT, OutOfBoundsDatetime
+from pandas._libs.tslibs import iNaT, OutOfBoundsDatetime, Period
 from pandas.compat import string_types, text_type, PY3
 from .common import (ensure_object, is_bool, is_integer, is_float,
                      is_complex, is_datetimetz, is_categorical_dtype,
@@ -164,6 +164,12 @@ def maybe_downcast_to_dtype(result, dtype):
                     result = to_datetime(result).tz_localize('utc')
                     result = result.tz_convert(dtype.tz)
 
+        elif dtype.type == Period:
+            # TODO(DatetimeArray): merge with previous elif
+            from pandas.core.arrays import PeriodArray
+
+            return PeriodArray(result, freq=dtype.freq)
+
     except Exception:
         pass
 
diff --git a/pandas/tests/frame/test_combine_concat.py b/pandas/tests/frame/test_combine_concat.py
index 2803db4f4..3b8d6e6c5 100644
--- a/pandas/tests/frame/test_combine_concat.py
+++ b/pandas/tests/frame/test_combine_concat.py
@@ -759,7 +759,6 @@ class TestDataFrameCombineFirst(TestData):
         tm.assert_frame_equal(res, exp)
         assert res['TD'].dtype == 'timedelta64[ns]'
 
-    @pytest.mark.xfail(reason="GH-23079", strict=True)
     def test_combine_first_period(self):
         data1 = pd.PeriodIndex(['2011-01', 'NaT', '2011-03',
                                 '2011-04'], freq='M')
```

**Comment by TomAugspurger** [comment]
@jreback do you have a chance to look at this? It's one of the blockers for PeriodArray.

Originally, this was done as part of 
https://github.com/pandas-dev/pandas/pull/3595. I think the conversion of i8 needs to happen inside the `combiner` function, not outside of it.

**Comment by TomAugspurger** [comment]
Actually... one sec, this may not be a blocker.

**Comment by TomAugspurger** [comment]
Oh, yes, it is kinda a blocker, but I mis-diagnosed the real issue. The real thing we need on the PeriodArray PR is the change in `maybe_downcast_to_dtype` turning the i8 array back into a PeriodArray. But we'll still need this so that we handle the unpacking from series correctly.

So, I think this is still a valuable change on its own.

**Comment by jreback** [comment]
might be some more issues about this (which this may fix)

**Pull request merged**
