### PR TITLE
TST: add test cases for reset_index method

### LINKED ISSUE #17067: reset_index can reset index name
```python
import pandas as pd
assert (pd.DataFrame(index=pd.Index([], name='x'))
        .reset_index(level=[]).index.name) is None
```

The root of the problem is in `pandas.core.common._default_index`:
```python
def _default_index(n):
    from pandas.core.index import RangeIndex
    return RangeIndex(0, n, name=None)
```

Probably, a new optional argument `name` can be introduced to `_default_index` and used in `reset_index`.

### PR DESCRIPTION
**Pull request by minggli**
- [x] closes #17067
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

the fix appears to work but it breaks previous assert_frame_equal that assumes index.name == None after reset_index() call. 

The question remains that is the issue #17067 actually a bug and does it require a fix at all? user can pretty much do `series.index.name = 'new name'` to handle this problem.

### CODE REVIEW

**Comment by jreback** [comment]
there are 2 issues pointed out in the OP

the first should already be fixed (and was a bug)

to answer your question, yes we want to be consistent in this

**Comment by minggli** [comment]
@jreback thanks for commenting! it seems it has indeed been fixed already. closing this PR.

**Comment by minggli** [comment]
strangely, it appears that below would fail:

```python3
s = pd.Series([1, 2, 3], index=pd.Index(range(3), name='x'))
assert s.reset_index().index.name == 'x'
assert s.reset_index(drop=True).index.name == 'x'
```

**Comment by jreback** [comment]
```
In [11]: s.reset_index(drop=True).index.name == 'x'
Out[11]: False

In [12]: s.reset_index().index.name == 'x'
Out[12]: False
```
these both look correct to me, the index name *should* not be carried over.

**Comment by minggli** [comment]
@jreback reflected your comment in added tests.

**Comment by minggli** [comment]
welcome! @jreback @gfyoung 😃

**Pull request merged**
