### PR TITLE
CI: Add back CircleCI for ARM64

### LINKED ISSUE #41829: CI: Re-enable Circle CI
I contacted CircleCI to check if they could be interested in sponsoring our ARM builds. Will update if I hear from them. For now looks like we're getting the 2,500 credits that @lithomas1 mentioned (not the 400,000 for open source projects for Linux builds). So, not much we can do with those.

I updated this PR so we don't add the CircleCI build, but still, it has everything else so the build passes when it can be added wherever. Only thing is that we now need to disable Circle CI, so the build doesn't fail after we remove the configuration. But only an admin of the pandas-dev organization can do it. @jreback do you mind going to https://app.circleci.com/settings/project/github/pandas-dev/pandas?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fpandas-dev%2Fpandas%2F30%2Fworkflows%2Ff9a6db17-510a-4eaf-a10c-b3a800e0a6c4%2Fjobs%2F30872 and clickig on "Stop builds" please?

_Originally posted by @datapythonista in https://github.com/pandas-dev/pandas/issues/41739#issuecomment-852446796_

We should re-enable Circle CI if we receive the Circle CI credits. 
cc @datapythonista for updates on this

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #41829
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Successful run https://app.circleci.com/pipelines/github/lithomas1/pandas/3/workflows/ebe9e4aa-f86b-4bb2-9324-2b7a5eb9c243/jobs/3 (my fork)

I think someone with admin permissions in the github organization needs to turn on CircleCi on the pandas repo again. It probably would be better if this were merged first.

I also figured out how the credits work. Basically there's a setting for it in project settings. I think it should already be on.
image
(my fork settings)

### CODE REVIEW

**Comment by jreback** [comment]
wow @lithomas1 do I need to enable anything on the pandas repo for this to work?

**Comment by lithomas1** [comment]
Yeah. I think you need to go here https://app.circleci.com/projects/project-dashboard/github/pandas-dev/ and click the setup button for the pandas repo. It'll probably better if this is merged first so that CircleCI can detect the config file. 

Then, I think in Project Settings > Advanced we should probably Build Forked Pull Requests, and Auto Cancel Redundant Builds, but the only thing that really needs to be on is Free and Open Source(it should be on by default, but can't hurt to double-check).

**Comment by jreback** [comment]
ok done. Build Forked PRs was already checked as was auto cancel.

**Comment by jreback** [comment]
ok let's see how this goes

**Comment by lithomas1** [comment]
Nice. Just a heads up that a lot of PRs will be red unless they merge master, since Circle needs the config to run.

**Comment by jreback** [comment]
that's fine

**Comment by lithomas1** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
