### PR TITLE
TST: Test cow for set_flags

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

No changes needed here, just adding a test to ensure behavior does not change

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]
Looks good to me (just needs a merge of main)

Side note: (not this PR, but generally enabling CoW) in case of `set_flags`, this is actually a change in behaviour, since its behaviour was copy=False by default (while almost all other methods have a copy=True default)

**Comment by phofl** [comment]
Merged

> Side note: (not this PR, but generally enabling CoW) in case of set_flags, this is actually a change in behaviour, since its behaviour was copy=False by default (while almost all other methods have a copy=True default)

This is something I wanted to discuss tomorrow as well

**Comment by jorisvandenbossche** [comment]
There is a linting failure

**Comment by phofl** [comment]
Thx, shouldn't edit files through the browser

**Pull request merged**
