### PR TITLE
BUG: Fix validation script not printing docstring is correct (#34228)

### LINKED ISSUE #34228: DOC: Validation script doesn't report that the docstring is correct
When executing for example:
```
./scripts/validate_docstrings.py pandas.DataFrame.head
```
The script, after the docstring, should report:
```
################################################################################
################################## Validation ##################################
################################################################################
Docstring for DataFrame.head correct. :)
```
But for some reason, the sentence `Docstring for DataFrame.head correct. :)` is not being printed.

This is the line that is not being executed: https://github.com/pandas-dev/pandas/blob/master/scripts/validate_docstrings.py#L364

### PR DESCRIPTION
**Pull request by rtm010**
- [x] closes #34228 
- [ ] tests added / passed
- [x] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
Looks reasonable - @datapythonista

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @rtm010 

Just to make sure, did you run the script with both, a correct docstring, and one with errors, to see if this is working as expected now?

**Comment by rtm010** [comment]
Good call @datapythonista 

I only tested with a correct docstring when I made the change. I've now tested one with errors as well and it seems to work as expected

**Comment by datapythonista** [comment]
Thanks for the fix @rtm010

**Pull request merged**
