### PR TITLE
DOC: Add pint pandas ecosystem docs

### PR DESCRIPTION
**Pull request by znicholls**
- [ ] closes #xxxx (N/A)
- [ ] tests added / passed (N/A)
- [ ] passes `black pandas` (N/A)
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff` (N/A)
- [ ] whatsnew entry

### CODE REVIEW

**Comment by znicholls** [comment]
@datapythonista thanks for your help with this (and #22582). What did you mean when you said the docs had moved?

**Comment by datapythonista** [comment]
Didn't realize we still have the ecosystem page in the docs. We moved it to the [web](https://github.com/pandas-dev/pandas/blob/master/web/pandas/community/ecosystem.md), but I think we finally didn't have an agreement on which version to keep. Do you mind duplicating the changes in the web file here, so they keep synchronized.

**Comment by znicholls** [comment]
Ok done (also added pandas path into the list of accessors for completeness)

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @znicholls

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Great thanks @znicholls

**Pull request merged**
