### PR TITLE
CLN: changed .format to f string in pandas/core/arrays/base.py

### PR DESCRIPTION
**Pull request by Jcole429**
- [ ] ref #29547
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Sounds good thanks @Jcole429 !

**Comment by Jcole429** [comment]
@WillAyd , What is the best practice for maintaining my fork? Should I delete and make a new fork next time I want to contribute?

> This action cannot be undone. This will permanently delete the Jcole429/pandas repository, wiki, issues, and comments, and **remove all collaborator associations**.

If I delete my fork, will I lose any evidence of collaboration from my profile?

Thank you

**Comment by WillAyd** [comment]
Set pandas as your upstream if you haven't already (noted in contributor guide) then just always pull updates from `upstream/master` to your local master. Then just fork locally off master to the branch you want and push that to your fork before making a PR

I wouldn't worry about keeping master on your fork in sync with pandas unless you have another reason to

**Comment by Jcole429** [comment]
Okay, I do have it set as my upstream. I'll do that, thank you!

Just for clarification, if I were to delete my fork, all evidence would be removed from my profile?

**Comment by WillAyd** [comment]
You can delete the branch on github after merge but keep your fork. You will push future branches to your fork

**Pull request merged**
