### PR TITLE
Added extra info section to EA repr

### LINKED ISSUE #24278: Add an "extra info" section to the base ExtensionArray repr
This would be useful for DTA / TDA, to include the optional `freq`.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/24278

### CODE REVIEW

**Comment by jreback** [comment]
can you do the same for Index

**Comment by TomAugspurger** [comment]
The same what? This is just changing the base ExtensionArray repr.

**Comment by jreback** [comment]
> The same what? This is just changing the base ExtensionArray repr.

yes, the same, to avoid departing from what we do in Index, which is pretty similar.

**Comment by TomAugspurger** [comment]
Sorry, I'm still not following what you're suggesting.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/master/pandas/core/indexes/base.py#L929

this is called _format_attrs in Index, so change one or the other

**Comment by TomAugspurger** [comment]
IIUC, `Index._format_attrs` returns a `List[Tuple[str, str]]`. So things like `[('name', self.name), ('dtype', self.dtype)]`

`ExtensionArray._repr_extra` doesn't require key-value pairs. Rather, we just expect a bit of text to include. I don't think it would be appropriate to require key-value pairs here.

**Comment by jreback** [comment]
> IIUC, Index._format_attrs returns a List[Tuple[str, str]]. So things like [('name', self.name), ('dtype', self.dtype)]

> ExtensionArray._repr_extra doesn't require key-value pairs. Rather, we just expect a bit of text to include. I don't think it would be appropriate to require key-value pairs here

This is just yet another difference with index. I would rather not have these differences.

**Review by jreback — CHANGES_REQUESTED** [review]
@TomAugspurger and that's fine, so change Index. this duplicated code between EA and Index is driving me bananas. The entire point is to share code. So it needs to be changed in one or the other.

**Comment by TomAugspurger** [comment]
This isn't a priority for me right now. I'd say merge if we think it's an improvement, or close and do it later. Either works for me.

**Comment by jreback** [comment]
I guess this is fine. ideally just have some integration with Index here (basically use the ``_repr_extra_`` there as well for consistency.

**Review by jorisvandenbossche — COMMENTED** [review]
Personally, I would prefer adding the extra section between length and dtype (so dtype is always the last element), but that's minor.

Is it needed to add an extra method for it? Won't we be able to reuse some existing thing like `_attributes`, and then automatically fill in the value for that?

Should we use this new ability to add `freq` for DatetimeArray?

**Comment by TomAugspurger** [comment]
Yes, DatetimeArray should use freq for it.

I don't know which `_attributes` attribute you're referring to. I don't think there's anything like that on ExtensionArray. DatetimeArray defines `_attributes = ['freq', 'tz']`, but the `tz` is already encoded in the dtype.

**Comment by jorisvandenbossche** [comment]
> I don't know which _attributes attribute you're referring to. I don't think there's anything like that on ExtensionArray. DatetimeArray defines _attributes = ['freq', 'tz'], but the tz is already encoded in the dtype.

Ah, yes, I meant that `_attributes`, but assumed it only had `freq` in it (exactly because `tz` is already in the dtype), but didn't actually check ..

**Comment by jreback** [comment]
looking again. this is reasonable. can you merge master. are there other places that you see this being used in the current EA's? (other than Decimal).

**Comment by jreback** [comment]
closing this; I think we need more consolidation on repr to avoid code duplication.

**Pull request closed without merging**
