### PR TITLE
Changing logo in README and removing old logo

### PR DESCRIPTION
**Pull request by datapythonista**
Not sure if anyone prefers to publish the new logo when we release pandas 1.0 and the new website is life. I don't have a strong preference, but I'd say let's change the logo now if nobody cares, so one thing less to think about. I'll change the twitter logo and tweet about it once this is merged.

### CODE REVIEW

**Comment by WillAyd** [comment]
I'd slightly prefer to wait until the new site goes up as it would be cooler to release at once, but not blocking if others want to move forward with this

**Comment by datapythonista** [comment]
As said, no strong preference, and also thought it'd be cool to change everything together. But I see advantages on moving forward:
- NumFOCUS has the stickers, the shop...
- This announcement separately will allow a bit more visibility to Indeed for sponsoring the logo (and besides the deserved credit, I think it may be good that other companies see that open source projects are happy to see help from them)
- Releasing is enough work, having to synchronize these with the release is adding some more things to keep in mind

Nothing is that important, but that's why I thought of opening this now.

CC: @TomAugspurger

**Comment by jreback** [comment]
+1 in this

doing anythig non completely standardized at release time is a no no

**Comment by TomAugspurger** [comment]
Either works for me. Will's points are good, but I may lean slightly towards just updating this now. 1.0 will still be a large enough celebration I think :)

The CI failure can likely be ignored.

**Comment by datapythonista** [comment]
@WillAyd happy to get this merged, based on previous comments?

**Comment by WillAyd** [comment]
Yea totally - merge away if ready

**Pull request merged**
