### PR TITLE
TST: move melt tests to separate file

### LINKED ISSUE #18367: TST: split out melt-tests in pandas/tests/reshape/test_reshape.py
since ``melt`` and friends were moved to ``pandas/core/reshape/melt.py`` want to follow suit with the tests.

if you want to go once further and split out the ``melt``, ``wide_to_long`` and ``lreshape`` tests to a new sub-module, e.g. ``pandas.tests.reshape.melt.test_melt, test_lreshape, test_wide_to_long`` would not object.

### PR DESCRIPTION
**Pull request by tdpetrou**
- [x] closes #18367

This breaks out melt, lreshape, and wide_to_long tests into their own module.

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase this. ping as soon as green to avoid future conflict.

**Comment by tdpetrou** [comment]
@jreback when you say 'ping on green' do you mean wait for the three continuous integration services to finish or that big green circle with a checkmark that says 'this branch has no conflicts with the bae branch'?

**Comment by jreback** [comment]
the ci to be all green (may take a while)

**Comment by tdpetrou** [comment]
@jreback its green now (that took 4 hours?). Looks like there has been another commit to master. Should i rebase again?

**Comment by jreback** [comment]
yeah that’s fine- the commit to master fixes the ci issue
no need to rebase 

ci runs for every commit for all prs so quite a queue

**Comment by jreback** [comment]
thanks

**Pull request merged**
