### PR TITLE
REF: simplify groupby.ops

### PR DESCRIPTION
**Pull request by jbrockmendel**
Inching towards refactoring out special-cased EA methods into EA/EADtype methods.

I expect this to need some troubleshooting on the 32bit linux build.

### CODE REVIEW

**Comment by jreback** [comment]
hmm lots of checks were skipped

**Comment by jbrockmendel** [comment]
hmmph 32bit build is still a PITA.  will troubleshoot a bit more and scale back the offending part of necessary.  related #46197 should be OK in the interim

**Comment by jbrockmendel** [comment]
looks like the 32bit is segfaulting and that is somehow screwing up the other builds?

**Comment by jbrockmendel** [comment]
punted on the 32bit thing; greenish

**Pull request merged**
