### PR TITLE
CLN: replace %s syntax with .format in tslibs/timedeltas

### PR DESCRIPTION
**Pull request by WillAyd**
- [X] Progress towards #16130
- [X] tests passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by WillAyd** [comment]
FWIW I didn't see what the point of the 'even_day' argument was to _repr_base in timedeltas.pyx. From both the test cases provided and the control flow, unless I'm missing something that argument is no different from passing nothing or None explicitly. 

Left alone for now but if you want me to remove it won't be a problem

**Comment by WillAyd** [comment]
I’ll go ahead and update the docstring to remove. Did you want to keep the test cases for backwards compatibility or would you rather I delete and just stick with the cases for None?

**Comment by jreback** [comment]
> I’ll go ahead and update the docstring to remove. Did you want to keep the test cases for backwards compatibility or would you rather I delete and just stick with the cases for None?

ok to delete; these are only tests, yes?

**Comment by WillAyd** [comment]
It looks like the tests and one piece of code in pandas/io/formats/format.py at line 2277 to change 

    format = ‘even_day’

To

    format = None

It looks like there’s already a test case called test_timedelta in the tests/io/formats/test_format.py module to regression test that. 

Sorry for any formatting issues - sent from my phone.

**Comment by jreback** [comment]
thanks!

**Pull request merged**
