### PR TITLE
TST: remove never-used singleton fixtures

### PR DESCRIPTION
**Pull request by jbrockmendel**
The fact that these are never used would be obvious if these were in a file not ignored by coverage, i.e. not relying on pytest magic.

broken off of #24873.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
nope how about we use them

**Comment by jbrockmendel** [comment]
> nope how about we use them

Where?  Buddy, you're usually the president of the "remove unused/duplicate code" club.

Wait, shoot.  Did you and josef-pkt have a Freaky-Friday body-swap?

**Comment by jreback** [comment]
my point is i would rather add fixture use in tests/frame and then see what falls out

i am of course amenable to removing things but one offs are not great for this

**Comment by jbrockmendel** [comment]
You want to add tests specifically to get fixture coverage?  I mean, I could implement a "test":

```
def test_cargo_cult(otherwise_unused_fixture):
    pass
```

and you would prefer that over removing unused code?

I guess it might not be a Freaky Friday, situation, it could also be one of [these](https://www.youtube.com/watch?v=GEStsLJZhzo)

**Comment by jreback** [comment]
btw you know you can simply import fixtures and call them as functions?

I am not sure of your debugging pattern, but I never need to actually call functions in a terminal
I exclusively use tests; just out a breakpoint in the test (or use —orb) and it works very nicely

**Comment by jreback** [comment]
the reason these fixtures were pulled out is to start a pattern; let’s continue rather than reverse

**Comment by h-vetinari** [comment]
> btw you know you can simply import fixtures and call them as functions?

That had been deprecated and has been removed in pytest 4.0: https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly

**Comment by jreback** [comment]
@h-vetinari that's not right. calling then *inside* of a test function is deprecated. calling them directory is certainly possible, after all they are just a function.

> Calling a fixture function directly, as opposed to request them in a test function, is deprecated.

**Comment by h-vetinari** [comment]
@jreback 

I had read over the debugging part, but I just tried it in a REPL, and it doesn't work:
```
(pandas-dev) C:\Users\[...]\pddev>python
Python 3.7.2 (default, Jan  2 2019, 17:07:39) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from pandas.conftest import *
C:\ProgramData\Miniconda3\envs\pandas-dev\lib\site-packages\hypothesis\_settings.py:193: HypothesisDeprecationWarning: The timeout setting can safely be removed with no effect.
  verbosity=self.verbosity,
>>>
>>> any_numpy_dtype()
Traceback (most recent call last):
[...]
Failed: Fixture "any_numpy_dtype" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
```

**Comment by WillAyd** [comment]
> we have at least one case where the fixture is behaving differently from the non-fixture implementation.

@jbrockmendel admittedly haven't kept up on the entire thread but you aren't referring to #24826 here are you? That wasn't an issue with the fixture as much as the test definition itself which should now be corrected

**Comment by jbrockmendel** [comment]
> That wasn't an issue with the fixture as much as the test definition itself which should now be corrected

That was one guess about what was going on.  I'm pretty sure I've rebased+pushed more recently than that, but will do so again to double-check.

**Comment by jbrockmendel** [comment]
@h-vetinari thank you for clarifying.  Apologies if I came off as snapping at you.  This has been frustrating.

**Comment by jbrockmendel** [comment]
@WillAyd nope, after rebasing #24769 still has failing builds.  Fixture versions are definitely behaving differently from non-fixture versions.

I'm stepping away from this for a while.  Maybe jreback will care about this after his Freaky Friday body swap gets un-done.

**Comment by jbrockmendel** [comment]
Just rebased.  Assuming the CI shows these haven't been put into use since the PR was opened, keeping unused code around remains a Bad Idea.  @jreback most of the other fixture-related PRs have been closed, but this one should be easy.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
ok @jbrockmendel but ideally would like to convert things that use setup functions and the older class testing structure in pandas/tests/frame before changing more fixtures.

**Pull request merged**
