### PR TITLE
STYLE enable ruff TCH on pandas/core/arrays

### PR DESCRIPTION
**Pull request by t0uch9r455**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by clarkwiththew** [comment]
I finished the task STYLE enable ruff TCH #51740

**Comment by MarcoGorelli** [comment]
thanks @clarkwiththew - can you remove the folder for which you've enabled this from `pyproject.toml` please?

**Comment by clarkwiththew** [comment]
I removed the folder from pyproject.toml

**Comment by MarcoGorelli** [comment]
thanks - can you also run `pre-commit run --all-files` please?

**Comment by MarcoGorelli** [comment]
something went wrong when merging, there's lots of unrelated changes

**Comment by clarkwiththew** [comment]
I'm fixing it right now

**Comment by clarkwiththew** [comment]
I've made some changes, hopefully the issues should be removed

**Comment by MarcoGorelli** [comment]
not quite, sorry

**Comment by clarkwiththew** [comment]
I think the pre-commit changed a lot of other files, I'm going to try just try it on a new branch

**Comment by clarkwiththew** [comment]
I ran the pre-commit and only the edited files should be changed now. I made a new PR here:

https://github.com/pandas-dev/pandas/pull/51786

**Pull request closed without merging**
