### PR TITLE
CI: Bump numpydev URL

### PR DESCRIPTION
**Pull request by TomAugspurger**
NumPy and scipy are uploading their wheels to a new URL.

### CODE REVIEW

**Comment by jreback** [comment]
great this is the same URL that we recommended in #33505  

cc @alimcmaster1

**Comment by jreback** [comment]
merge on green.

**Comment by TomAugspurger** [comment]
We got

```
numpy                     1.19.0.dev0+8dfaa4a          pypi_0    pypi
```

That's from 12 days ago, but there are newer wheels available (one from yesterday). Is pip just grabbing the "highest" version number, which happens to be `...8dfaa4a`?

**Comment by TomAugspurger** [comment]
@mattip has NumPy's development builds always used `.dev0+<git hash>` instead of something like `.dev0+<increasing-count>.<git hash>`? Perhaps I'm just noticing that now.

**Comment by jreback** [comment]
> @mattip has NumPy's development builds always used `.dev0+<git hash>` instead of something like `.dev0+<increasing-count>.<git hash>`? Perhaps I'm just noticing that now.

hmm, that is problematic.

**Comment by mattip** [comment]
Looking at the [old location](http://66ce22ef0bf26a5e2cca-4ffdece11fd3f72855e4665bc61c7445.r49.cf2.rackcdn.com/) I see it used the dates as well, for instance numpy-1.19.0.dev0+20200504031348_58dbafa-cp37-cp37m-linux_x86_64.whl. I must have missed that in the move to azure scripts

**Comment by TomAugspurger** [comment]
@mattip I didn't immediately see where version was set with the old MacPython/numpy-wheels setup. Do you want me to open an issue somewhere as a reminder?

**Comment by mattip** [comment]
ping me here again if it is not fixed soonish.

**Comment by mattip** [comment]
It is [something the uploader did](https://github.com/matthew-brett/wheelhouse-uploader/blob/master/wheelhouse_uploader/upload.py#L180) to rename dev wheels.

**Comment by jbrockmendel** [comment]
Is this related to the issue breaking the npdev builds?

**Comment by mattip** [comment]
@TomAugspurger newer wheels are available. Is there a reason not to delete the old ones?

**Comment by TomAugspurger** [comment]
Thanks! No reason to keep the old ones around I think.

@jbrockmendel are you referring to the

```
Cython.Compiler.Errors.CompileError: pandas/_libs/reduction.pyx
```

in https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=34915&view=logs&j=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&t=fe74a338-551b-5fbb-553d-25f48b1836e8&l=443? That looks unrelated from the changes here.

**Comment by jreback** [comment]
triggering to see if this is picked up

**Comment by jreback** [comment]
hmm not sure this is picking up the right version.

**Comment by jbrockmendel** [comment]
#34050 should fix the non-npdev CI failure

**Comment by jreback** [comment]
I think we are still getting the older versions.

**Comment by TomAugspurger** [comment]
Actually I think we're OK. https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=35269&view=logs&j=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&t=fe74a338-551b-5fbb-553d-25f48b1836e8&l=664 has

```
numpy                     1.19.0.dev0+e664535
```

Looking at https://anaconda.org/scipy-wheels-nightly/numpy/files, that's from yesterday.

On anaconda.org, it included the full tag `numpy-1.19.0.dev0+20200510035734_e664535-cp37-cp37m-manylinux1_i686.whl`. Hopefully it's not just by accident that we got the latest wheel :)

**Comment by jreback** [comment]
ok great, thanks @TomAugspurger 

I guess just let's monitor to make sure we keep getting updates.

**Comment by simonjayhawkins** [comment]
@Meeseeksdev backport to 1.0.x

**Pull request merged**
