### PR TITLE
BUG: groupby's first/last functions maintain Series rather than convert to numpy array (#15884)

### LINKED ISSUE #15884: BUG: first() loses the timezone in groupby
need a systematic test of all groupby methods here.

This works as expected:

```
pd.DataFrame({'time': [pd.Timestamp('2012-01-01 13:00:00+00:00')],
              'A': [3]}).groupby('A', as_index=False).head(1)
```

However, this loses the timezone:

```
pd.DataFrame({'time': [pd.Timestamp('2012-01-01 13:00:00+00:00')],
              'A': [3]}).groupby('A', as_index=False).first()
```

### PR DESCRIPTION
**Pull request by chrisaycock**
- [x] closes #15884 
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
@chrisaycock not what I was looking for. The only reason that compat routine is called is because the block aggregator raises. So this will not be performant. I don't think these compat routines are actually called at all (or should be). All of the handling is now done via the cython routines (I *think).

**Comment by jreback** [comment]
So these compat routines are *only* called if ``numeric_only=False`` is passed. It tries the cython path first. So for datetimes it *should* be working (but is raising because its being called incorrectly).

**Comment by chrisaycock** [comment]
@jreback Those compat functions were definitely being called for the test case, which is how I found them. If they aren't supposed to be called, then I'll have to take another crack at that issue.

**Comment by jreback** [comment]
@chrisaycock not what I mean.

put a breakpoint in ``_cython_agg_blocks``. It is hit *first* (pun intended). This raises (incorrectly), then the compat routines are called.

**Comment by chrisaycock** [comment]
@jreback Ok, I see what you mean. The `.values` is definitely a `DatetimeIndex` instead of a multi-dimensional array.

**Pull request closed without merging**
