### PR TITLE
DEPR: deprecate pandas.rpy (GH9602)

### LINKED ISSUE #9602: DEPR/DOC: rpy deprecation
so we should put up a deprecation notice on `rpy`imports that in the future the user should use  `rpy2` directly rather than the less-supported  `pandas.rpy` converters that we can take action say in 0.17.0

discussed extensivley in #7385 

xref #7385, #9187 #7309, #8255 
- [x] Update the docs with some example of how to port your pandas examples to the `rpy2` API -> done with #10075
- [ ] Go over the functionality in pandas and check if some things should be ported to `rpy2` (what still works better in pandas?)
  - [ ] Handling of NaN values (comment below: https://github.com/pydata/pandas/issues/9602#issuecomment-94716332)
  - [ ] index is not preserved in `ri2py` -> this should be handled in https://bitbucket.org/rpy2/rpy2/issues/285
- [ ] The closed PRs -> push them to `rpy2`?

### PR DESCRIPTION
**Pull request by jreback**
closes #9602

### CODE REVIEW

**Comment by jreback** [comment]
@jorisvandenbossche pls have a look (failures are the Mysql issue #9608)

**Comment by jorisvandenbossche** [comment]
For me it is OK to already deprecate it, but I think we still should make sure that all existing functionality in pandas is ported to rpy2 (if any, but is should be checked)

**Comment by jorisvandenbossche** [comment]
And, also provide in the docs some explanation about how to move from the pandas api to rpy2

**Comment by jreback** [comment]
@jorisvandenbossche agreed. Nothing has really changed. But I think for example having ``rpy2`` add Categorical is a good idea.

**Comment by jorisvandenbossche** [comment]
ok that we keep the #9602 issue open for this

**Pull request merged**
