### PR TITLE
DOC: removed wrong value of `pd.NA ** 0`

### LINKED ISSUE #31003: incorrect docs: pd.NA ** 0 should return 1
`pd.NA ** 0` returns 1. which is correct, as far as I understand <sup>1</sup>
However, the [documents, line 832](https://dev.pandas.io/docs/user_guide/missing_data.html) incorrectly claims that `pd.NA ** 0` returns 0.

----
<sup>1</sup> although one can ask if `NULL**0` should behave like `NAN**0`

### PR DESCRIPTION
**Pull request by tsvikas**
- [x] closes #31003
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Nice! Seems like a good decision to put this inside an `ipython` block to avoid similar mistakes

**Review by MarcoGorelli — APPROVED** [review]

**Comment by TomAugspurger** [comment]
I think I prefer this as a table so that it is formatted nicely in the docs. Curious to hear what others think.

**Review by datapythonista — APPROVED** [review]
Happy either way. If I had to choose, I'd probably go for the ipython block, but I don't have much of a preference.

**Comment by TomAugspurger** [comment]
Let's go with that then.

**Comment by simonjayhawkins** [comment]
@TomAugspurger should the auto-backport kick-in moreless straight-away

**Comment by TomAugspurger** [comment]
Oh, whoops, this was merged to the wrong branch. PRs should go to master.

**Comment by TomAugspurger** [comment]
So, I think I will revert this, make a new PR to master, and then use the bot to backport it... Probably not necessary, but let's do it to not mess up history / branching.

**Comment by TomAugspurger** [comment]
OK, reverted on 1.0.x, and made https://github.com/pandas-dev/pandas/issues/31003 to master (which will be backported).

**Comment by tsvikas** [comment]
I thought we need to work on the development branch, and bit on master. Hmmm. How axtually do you manage your Branch's in pandas?

**Comment by jorisvandenbossche** [comment]
> I thought we need to work on the development branch, and bit on master. Hmmm. How axtually do you manage your Branch's in pandas?

Everything is merged in master, and the appropriate commits for 1.0.0 are backported into the 1.0.x branch. So in practice, almost all PRs should target the master branch.

**Pull request merged**
