### PR TITLE
MAINT: Rename assertRaisesRegexp to assert_raises_regex

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.

xref <a href="https://github.com/pandas-dev/pandas/pull/16089#issuecomment-296327919">#16089 (comment)</a>

### CODE REVIEW

**Comment by jreback** [comment]
``assert_raises_regex`` is a bit shorter

**Comment by gfyoung** [comment]
I was thinking that the "with" makes the name a little clearer (from a grammatical perspective especially).  Thoughts?

**Comment by gfyoung** [comment]
I was thinking the "with" makes the name a little clearer (from a grammatical perspective especially).  What do you think?

**Comment by jreback** [comment]
```
with tm.assert_raises_with_regex(
                 ValueError, "\"mysin\" is not a supported function"):
```

This is much more clear (and not redundant).
```
with tm.assert_raises_regex(
                 ValueError, "\"mysin\" is not a supported function"):
```

**Comment by gfyoung** [comment]
Fair enough.  Done.

**Comment by gfyoung** [comment]
@jreback : Renaming done, and all is green.

**Comment by gfyoung** [comment]
@jreback : Renaming done, and all is green.

**Comment by gfyoung** [comment]
@jreback : It would be great to get this merged in ASAP, since every time `master` gets updated, I have to rebase to ensure that there are no merge conflicts + no new `assertRaisesRegexp` have been used.

**Comment by jreback** [comment]
yes, sorry, busy with some other things.

thanks @gfyoung

**Comment by gfyoung** [comment]
@jreback : FYI, `master` is going to break because I was just going to remove the remain `assertRaisesRegexp` from the latest commits before you merged.

**Comment by gfyoung** [comment]
@jreback : Putting up PR right now to patch this immediately.

**Comment by jreback** [comment]
yep

**Pull request merged**
