### PR TITLE
STY: remove --keep-runtime-typing from pyupgrade Final_Part-5

### LINKED ISSUE #40759: STYLE remove --keep-runtime-typing from pyupgrade
xref @simonjayhawkins 's comment: https://github.com/pandas-dev/pandas/pull/40545#discussion_r606360410

Task is:
- remove `keep-runtime-typing` from:

https://github.com/pandas-dev/pandas/blob/cc84a2383c641998d4817cfaeb33c64f017b7454/.pre-commit-config.yaml#L57

- run `pre-commit run pyupgrade --all-files`
- run `pre-commit run flake8 --all-files`, fixup any errors (probably some about extra imports)

Finally, run `pre-commit run --all-files` (this may take a few minutes), fixup any hooks which don't pass, and when everything passes, open a pull request :rocket:

### PR DESCRIPTION
**Pull request by fathomer**
To fix issue #40759 :
Changes here are from PEP585 (e.g. List[str] -> list[str]) and from PEP604 (Optional[str] -> str | None), both of which are only applied in the presence of from future import annotations. Some imports became unused after this so those have been removed.
As there were changes in many files (97) this has been split up into 5 smaller PRs.
This is the final PR 5 of 5.
Checks in this one will pass only when other parts are merged as --keep-runtime-typing is removed the pyupgrade precommit hook.

Refer the discussion here : #40773

- [x] closes #40759 
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
@github-actions pre-commit

**Review by MarcoGorelli — APPROVED** [review]
Looks good to me pending green

**Comment by MarcoGorelli** [comment]
Thanks @fathomer !

**Comment by fathomer** [comment]
> Thanks @fathomer !

Thanks @MarcoGorelli for all the help and clear details of the task.
Glad to make my first ever open source contribution here! :)

**Pull request merged**
