### PR TITLE
BUG: get_indexer_non_unique with np.nan

### LINKED ISSUE #35392: BUG: Index.get_indexer_non_unique misbehaves when index contains multiple nan
#### Code Sample, a copy-pastable example

```python
axis = pd.Index([np.nan, 'var1', np.nan])
axis.get_indexer_for([np.nan])
```

#### Current Output

`array([-1], dtype=int64)`
Meaning that `np.nan` is not in axis which is incorrect and makes `df.drop(columns=[np.nan])` to fail when columns contains multiple `nan`.

#### Expected Output

`array([0, 2], dtype=int64)`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : None.None

pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : 0.29.21
pytest           : 5.4.3
hypothesis       : 5.20.3
sphinx           : 3.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.2
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.9
numba            : 0.50.1

</details>

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #35392
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

One of the tests is copied from #35498

### CODE REVIEW

**Comment by realead** [comment]
I think in order to be consistent, one could use `_lib.hashtable.PyObjectHashTable` - it has the "expected" behavior when it comes to nan-floats and can also handle more complex cases (like `(float("nan),)` or `complex(0, float("nan"))`) out-of-the-box.

The downside is, that one has to misuse a table for a set (#39799 would fix that).

**Comment by jbrockmendel** [comment]
@realead IIUC what you're suggesting is viable medium-term but likely not short-term?  i.e. is it worth doing a temporary fix like this PR without what you're describing?

**Comment by realead** [comment]
I must confess, I assumed the solution would be within reach. 

But there are some stumbling blocks:

Panda's `PyObjectHashTable` doesn't perform reference counting

https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/hashtable_class_helper.pxi.in#L1126-L1138

 so using it as set/dict with temporary objects is problematic. 

Also `PyObjectHashTable` maps objects to int64 and not `pyobject`, which is at least a problem for performance. Maybe it is worth to introduce `PandasSet` and `PandasDict` which would have the same handling of nans as pandas algorithm. But until then a fix like that is probably best we can do.

**Comment by jbrockmendel** [comment]
> But until then a fix like that is probably best we can do.

Makes sense, thanks for taking a look.

> Maybe it is worth to introduce PandasSet and PandasDict which would have the same handling of nans as pandas algorithm

I'll defer to you on this, as you've mentioned using other khash functionality before.  I'm a bit wary about the increasing build size.

**Comment by jbrockmendel** [comment]
closing in favor of #35498

**Pull request closed without merging**
