### PR TITLE
Fix: Use only one blank line to separate sections or paragraphs

### LINKED ISSUE #23870: DOC: Use only one blank line to separate sections or paragraphs
When checking for errors with  `./scripts/validate_docstrings.py`, There is an error that comes up:

**GL03**
**Use only one blank line to separate sections or paragraphs**

I started working on this and will create a pull request for this issue shortly to go into more detail on what I fixed.

@datapythonista

### PR DESCRIPTION
**Pull request by alexander-ponomaroff**
By running `./scripts/validate_docstrings.py --errors=GL03 --format=azure`, I was able to get the list of GL03 errors with files and line numbers where these errors occurred.

I fixed a big portion of these issues so far.

@datapythonista 

- [ ] closes #23870 
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by alexander-ponomaroff** [comment]
### Original List of Errors - 127 errors

pandas.read_table
pandas.read_csv
pandas.read_fwf
pandas.read_msgpack
pandas.io.json.json_normalize
pandas.HDFStore.select
pandas.HDFStore.walk
pandas.read_feather
pandas.read_parquet
pandas.read_sql_table
pandas.read_sql_query
pandas.read_sql
pandas.melt
pandas.crosstab
pandas.merge_ordered
pandas.merge_asof
pandas.unique
pandas.util.hash_array
pandas.util.hash_pandas_object
pandas.Series.argmin
pandas.Series.argmax
pandas.DataFrame.iterrows
pandas.DataFrame.lookup
pandas.DataFrame.add
pandas.DataFrame.sub
pandas.DataFrame.mod
pandas.DataFrame.radd
pandas.DataFrame.rsub
pandas.DataFrame.rmod
pandas.DataFrame.count
pandas.DataFrame.swaplevel
pandas.DataFrame.melt
pandas.DataFrame.plot.pie
pandas.DataFrame.from_csv
pandas.DataFrame.to_feather
pandas.Panel.xs
pandas.Panel.major_xs
pandas.Panel.minor_xs
pandas.Panel.swaplevel
pandas.Index.reindex
pandas.Index.astype
pandas.Index.intersection
pandas.Index.union
pandas.Index.difference
pandas.Index.asof_locs
pandas.Index.get_indexer
pandas.Index.get_slice_bound
pandas.CategoricalIndex
pandas.IntervalIndex.from_arrays
pandas.IntervalIndex.from_tuples
pandas.IntervalIndex.get_indexer
pandas.MultiIndex.set_levels
pandas.MultiIndex.sortlevel
pandas.MultiIndex.remove_unused_levels
pandas.MultiIndex.get_indexer
pandas.DatetimeIndex
pandas.DatetimeIndex.snap
pandas.Timedelta
pandas.Timedelta.max
pandas.Timedelta.min
pandas.tseries.offsets.BusinessHour
pandas.tseries.offsets.CustomBusinessHour
pandas.tseries.offsets.LastWeekOfMonth
pandas.core.window.Rolling.max
pandas.core.window.Rolling.aggregate
pandas.core.window.Expanding.max
pandas.core.window.Expanding.aggregate
pandas.core.window.EWM.std
pandas.core.window.EWM.var
pandas.core.window.EWM.corr
pandas.core.window.EWM.cov
pandas.core.groupby.GroupBy.apply
pandas.core.groupby.GroupBy.all
pandas.core.groupby.GroupBy.any
pandas.core.groupby.GroupBy.head
pandas.core.groupby.GroupBy.mean
pandas.core.groupby.GroupBy.median
pandas.core.groupby.GroupBy.nth
pandas.core.groupby.GroupBy.ohlc
pandas.core.groupby.GroupBy.rank
pandas.core.groupby.GroupBy.sem
pandas.core.groupby.GroupBy.std
pandas.core.groupby.GroupBy.var
pandas.core.groupby.GroupBy.tail
pandas.core.groupby.DataFrameGroupBy.agg
pandas.core.groupby.DataFrameGroupBy.all
pandas.core.groupby.DataFrameGroupBy.any
pandas.core.groupby.DataFrameGroupBy.corr
pandas.core.groupby.DataFrameGroupBy.cov
pandas.core.groupby.DataFrameGroupBy.diff
pandas.core.groupby.DataFrameGroupBy.fillna
pandas.core.groupby.DataFrameGroupBy.hist
pandas.core.groupby.DataFrameGroupBy.idxmax
pandas.core.groupby.DataFrameGroupBy.idxmin
pandas.core.groupby.DataFrameGroupBy.mad
pandas.core.groupby.DataFrameGroupBy.quantile
pandas.core.groupby.DataFrameGroupBy.rank
pandas.core.groupby.DataFrameGroupBy.shift
pandas.core.groupby.DataFrameGroupBy.skew
pandas.core.groupby.DataFrameGroupBy.take
pandas.core.groupby.DataFrameGroupBy.tshift
pandas.core.groupby.SeriesGroupBy.nlargest
pandas.core.groupby.SeriesGroupBy.nsmallest
pandas.core.groupby.SeriesGroupBy.unique
pandas.core.groupby.SeriesGroupBy.is_monotonic_increasing
pandas.core.groupby.SeriesGroupBy.is_monotonic_decreasing
pandas.core.groupby.DataFrameGroupBy.corrwith
pandas.core.resample.Resampler.__iter__
pandas.core.resample.Resampler.apply
pandas.core.resample.Resampler.aggregate
pandas.core.resample.Resampler.mean
pandas.core.resample.Resampler.median
pandas.core.resample.Resampler.ohlc
pandas.core.resample.Resampler.sem
pandas.io.formats.style.Styler.applymap
pandas.io.formats.style.Styler.where
pandas.io.formats.style.Styler.bar
pandas.plotting.andrews_curves
pandas.describe_option
pandas.reset_option
pandas.get_option
pandas.set_option
pandas.option_context
pandas.errors.UnsortedIndexError
pandas.api.types.pandas_dtype
pandas.api.types.is_scalar
pandas.DataFrame.subtract

### Current List of Errors - 58 errors

pandas.read_table
pandas.read_csv
pandas.read_fwf
pandas.read_feather
pandas.melt
pandas.Series.argmin
pandas.Series.argmax
pandas.DataFrame.add
pandas.DataFrame.sub
pandas.DataFrame.mod
pandas.DataFrame.radd
pandas.DataFrame.rsub
pandas.DataFrame.rmod
pandas.DataFrame.melt
pandas.Panel.swaplevel
pandas.Index.reindex
pandas.IntervalIndex.from_arrays
pandas.IntervalIndex.from_tuples
pandas.Timedelta
pandas.Timedelta.max
pandas.Timedelta.min
pandas.core.window.Rolling.max
pandas.core.window.Rolling.aggregate
pandas.core.window.Expanding.max
pandas.core.window.Expanding.aggregate
pandas.core.window.EWM.std
pandas.core.window.EWM.var
pandas.core.window.EWM.corr
pandas.core.window.EWM.cov
pandas.core.groupby.GroupBy.apply
pandas.core.groupby.DataFrameGroupBy.agg
pandas.core.groupby.DataFrameGroupBy.corr
pandas.core.groupby.DataFrameGroupBy.cov
pandas.core.groupby.DataFrameGroupBy.diff
pandas.core.groupby.DataFrameGroupBy.fillna
pandas.core.groupby.DataFrameGroupBy.hist
pandas.core.groupby.DataFrameGroupBy.idxmax
pandas.core.groupby.DataFrameGroupBy.idxmin
pandas.core.groupby.DataFrameGroupBy.mad
pandas.core.groupby.DataFrameGroupBy.quantile
pandas.core.groupby.DataFrameGroupBy.skew
pandas.core.groupby.DataFrameGroupBy.take
pandas.core.groupby.DataFrameGroupBy.tshift
pandas.core.groupby.SeriesGroupBy.nlargest
pandas.core.groupby.SeriesGroupBy.nsmallest
pandas.core.groupby.SeriesGroupBy.unique
pandas.core.groupby.SeriesGroupBy.is_monotonic_increasing
pandas.core.groupby.SeriesGroupBy.is_monotonic_decreasing
pandas.core.groupby.DataFrameGroupBy.corrwith
pandas.core.resample.Resampler.apply
pandas.core.resample.Resampler.aggregate
pandas.plotting.andrews_curves
pandas.describe_option
pandas.reset_option
pandas.get_option
pandas.set_option
pandas.api.types.is_scalar
pandas.DataFrame.subtract

**Review by WillAyd — APPROVED** [review]
lgtm - @datapythonista

**Comment by datapythonista** [comment]
Thanks for taking care of those @alexander-ponomaroff 

I kept the issue open, as you mention that there are still 58 errors to fix. Was there any impediment to fix those, or there were just too many for a single PR?

**Comment by datapythonista** [comment]
Yes, unfortunately the introspection to detect where a function is defined doesn't work well if the function is created in a tricky way (and we do that somehow often for better code organization and not repeating code in pandas).

One option (tricky but effective) is check the docstring with for example `scripts/validate_docstrings.py pandas.Series.head` and then grep for the shot summary of any part that looks like it should be unique.

The good news is that I think many of the pending one in your list reuse docstring, so there are probably one third of the number in the list that need to fixed.

**Pull request merged**
