### PR TITLE
DOC: Use container directives instead of raw html for the doc "cards"

### PR DESCRIPTION
**Pull request by stijnvanhoey**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

The PR is a follow up of #31156 and #31148 translating the raw html to docutils/sphinx directives, making it more _readable_. 

Furthermore, it fixes the redundant css in `pandas.css` versus `getting_started.css` by removing the `install-card` class and merging it with the existing `intro-card` class. 

__Note:__ The setup required an [adjustment to the theme](https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/pull/92) to overcome the usage of the `container` class by both docutils and bootstrap.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@stijnvanhoey can you merge master to get the ci green.

**Comment by WillAyd** [comment]
I think looks good but @jorisvandenbossche 

Is this directive provided by sphinx or someone else?

**Comment by jorisvandenbossche** [comment]
Yes, it's even from base `docutils` / restructuredtext. 

But, this still depends on a change in the sphinx theme to support the way it is styled (a conflict in a css class needs to be solved); so this needs to wait on that (https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/pull/92)

**Comment by datapythonista** [comment]
Looks like both this PR and the one is depending on have conflicts. Are we still moving forward with this?

**Comment by jorisvandenbossche** [comment]
Yes, I think we still want to forward with this. The linked PR mainly conflicts due to the rename, will try to move forward that PR.

**Comment by chrisjsewell** [comment]
Hey guys, just an FYI, that I took your good idea here and turned it into an extension: https://github.com/executablebooks/sphinx-panels

**Comment by jorisvandenbossche** [comment]
First try to convert some of the cards to use sphinx-panels -> https://github.com/pandas-dev/pandas/pull/34065 (still needs to be further updated, though). So let's close this PR in favor of that one.

**Pull request closed without merging**
