### PR TITLE
COMPAT: Pyarrow supports div with duration

### LINKED ISSUE #54315: TST: div/truediv with PyArrow duration types
Looks like they implemented ``__truediv__`` for more types.

https://github.com/pandas-dev/pandas/actions/runs/5707046701/job/15463354529

### PR DESCRIPTION
**Pull request by mroeschke**
- [ ] closes #54315 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM pending greenish

**Review by phofl — COMMENTED** [review]
I think we should try to test those properly. The type error is raised while constructing expected, not in the actual operation

**Comment by mroeschke** [comment]
Yeah agreed. I'll reopen the issue and relabel it a testing issue

**Comment by phofl** [comment]
Thx

**Pull request merged**
