### PR TITLE
Tst interval index NaN uniqueness

### PR DESCRIPTION
**Pull request by r-toroxel**
add test cases for interval-indexer with unique NaN value and non-unique NaN values.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @r-toroxel is this not currently tested or is it one of the open issues that are fixed on master

is this related to #41831 and the associated open PR #41863

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by r-toroxel** [comment]
@simonjayhawkins yes, these were not tested before and seems to be related to #41831.

**Comment by jreback** [comment]
thanks @r-toroxel

**Comment by jreback** [comment]
@jbrockmendel does this close #41831 ?

**Comment by r-toroxel** [comment]
@jreback I'm afraid it does not fix the bug and hence close the issue. just a test added.

**Pull request merged**
