### PR TITLE
DOC iris.csv file has moved

### PR DESCRIPTION
**Pull request by benabel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Nice catch @benabel, thanks for the PR and the fix!

**Comment by WillAyd** [comment]
Thanks @benabel

**Comment by konstell** [comment]
Resolves https://github.com/pandas-dev/pandas/issues/33428

**Pull request merged**
