### PR TITLE
BUG: Fixed bug that Timedelta raises error when slicing from 0s (issue #10583)

### LINKED ISSUE #10583: TimedeltaIndex raises error when slicing from '0s'
```python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.normal(size=(10,4)))
df.index = pd.timedelta_range(start='0s', periods=10, freq='s')

print(df.loc['0s':,:])
```
raises a `ValueError: invalid resolution`, while `print(df.loc['5s':,:])` works.

Workaround : `print(df.loc[pd.Timedelta('0s'):,:])`
```
INSTALLED VERSIONS
------------------
commit: 6246cc1bb5149863de09b470530b69f7e22cad87
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-57-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8

pandas: 0.16.2-138-g6246cc1
nose: 1.3.1
Cython: 0.20.1post0
numpy: 1.8.2
scipy: 0.13.3
statsmodels: None
IPython: 1.2.1
sphinx: 1.2.2
patsy: None
dateutil: 2.4.1
pytz: 2013b
bottleneck: None
tables: 3.1.1
numexpr: 2.2.2
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: None
```

### PR DESCRIPTION
**Pull request by terrytangyuan**
closes #10583

### CODE REVIEW

**Comment by jreback** [comment]
ping on green

**Comment by terrytangyuan** [comment]
@jreback looks like all the PRs on Travis are pending (none of them is running now)? BTW, how can I cancel/drop one of the tasks that I created? (In case in the future when I need to fix my commits)

**Comment by jreback** [comment]
things can take a while on travis. pandas only has a limited amount of capacity (across pandas master and other accounts), so could be a while as I pushed a bunch of things recently.

you can go to travis and cancel things manually if you want. but the green button is run by a different process.

**Comment by terrytangyuan** [comment]
I see. On green now!

**Comment by jreback** [comment]
thank you sir!

**Pull request merged**
