### PR TITLE
STY: standardize spacing for casting, with linting

### PR DESCRIPTION
**Pull request by jbrockmendel**
Casting in cython is done with the syntax `<type>obj` or `<type> obj`.  ATM the code uses both of these.  This PR standardizes on the first usage, with a lint check.

@datapythonista I'm not sure whether the grep check here belongs in the patterns section or in the non-python section.  LMK if you have a preference.

### CODE REVIEW

**Review by jreback — APPROVED** [review]
nice

prob should put all of these rules into a flake-cython package :)

**Comment by jbrockmendel** [comment]
> prob should put all of these rules into a flake-cython package :)

If we can find someone else to maintain it, that'd be fantastic.

**Comment by jbrockmendel** [comment]
Not for this PR, but a couple of other patterns that would be relatively easy to lint for:

`cimport numpy as np` --> should be `cnp` (not a widely-used convention, but it should be)
`*` imports
number of lines after function/class

For these purposes (and for this PR) we just assume away comments and docstrings.

**Comment by datapythonista** [comment]
Thanks @jbrockmendel, nice addition.

There are reasons for having it with both the linting and the patters, happy with any.

**Pull request merged**
