### PR TITLE
BUG: Fix DataFrame logical ops Series inconsistency

### LINKED ISSUE #5035: BUG: bool methods are wrong with DataFrame and Series (or at least wrong error)
```
from pandas import Series, DataFrame
s = Series([2, 3, 4, 5, 6, 7, 8, 9, 10])
d = DataFrame({'a': s})
s + d
d + s
print(d & s)
```

produces Traceback:

```
raceback (most recent call last):
  File "testcase2.py", line 6, in <module>
    print(d & s)
  File "../pandas/core/frame.py", line 217, in f
    return self._combine_series(other, na_op, fill_value, axis, level)
  File "../pandas/core/frame.py", line 3040, in _combine_series
    return self._combine_match_columns(other, func, fill_value)
  File "../pandas/core/frame.py", line 3079, in _combine_match_columns
    func, right, axes=[left.columns, self.index])
  File "../pandas/core/internals.py", line 2048, in eval
    return self.apply('eval', *args, **kwargs)
  File "../pandas/core/internals.py", line 2033, in apply
    applied = getattr(blk, f)(*args, **kwargs)
  File "../pandas/core/internals.py", line 850, in eval
    result = get_result(other)
  File "../pandas/core/internals.py", line 834, in get_result
    return self._try_coerce_result(func(values, other))
  File "../pandas/core/frame.py", line 201, in na_op
    mask = notnull(xrav) & notnull(yrav)
ValueError: operands could not be broadcast together with shapes (81) (9)
```

`s & d` currently raises `NotImplemented` instead. (because there's no `__rand__`)

### LINKED ISSUE #5284: Binary operators between DataFrame and Series object doesn't seem to work
related similar operation

http://stackoverflow.com/questions/19484344/how-do-i-use-a-specific-columns-value-in-a-pandas-dataframe-where-clause/19494873#19494873

http://stackoverflow.com/questions/19507088/filtering-a-pandas-dataframe-without-removing-rows/19516869#19516869

http://stackoverflow.com/q/21627926/190597

This should be a bit more intuitive

```
In [59]: data = """      A    B    C    D
1/1   0    1    0    1
1/2   2    1    1    1
1/3   3    0    1    0 
1/4   1    0    1    2
1/5   1    0    1    1
1/6   2    0    2    1
1/7   3    5    2    3"""

In [60]: df = read_csv(StringIO(data),sep='\s+')

In [61]: df
Out[61]: 
     A  B  C  D
1/1  0  1  0  1
1/2  2  1  1  1
1/3  3  0  1  0
1/4  1  0  1  2
1/5  1  0  1  1
1/6  2  0  2  1
1/7  3  5  2  3

In [62]: df.where((df>df.shift(1)).values & DataFrame(df.D==1).values)
Out[62]: 
      A   B   C   D
1/1 NaN NaN NaN NaN
1/2   2 NaN   1 NaN
1/3 NaN NaN NaN NaN
1/4 NaN NaN NaN NaN
1/5 NaN NaN NaN NaN
1/6   2 NaN   2 NaN
1/7 NaN NaN NaN NaN
```

Given that normal binary operators like addition or logical `and` work well between a pair of Series objects, or between a pair of DataFrame objects (returning a element-wise addition/conjuction), I found it surprising that I cannot do the same between a Series object and a DataFrame object.

Here's a demonstration of what doesn't work now and what would be the expected result: http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/52886258/000-qdoqud/Untitled0.ipynb

### PR DESCRIPTION
**Pull request by jbrockmendel**
closes #5284 
closes #5035
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Will need to look and see if this closes anything else.

This will have a merge conflict with #28638, that is a slightly higher priority.

Not sure if this constitutes an API change as the behavior for these ops is all over the place.

### CODE REVIEW

**Comment by jreback** [comment]
pls rebase

**Comment by jbrockmendel** [comment]
rebased+green

**Comment by jreback** [comment]
lgtm. I think we need a small section in whatsnew to show what has changed? (could defer if you want to do a larger section on ops changes, though maybe easier to grok in pieces).

**Comment by jbrockmendel** [comment]
Added line in whatsnew, not a whole section.  Prefer to hold off on more pending nailing down remaining inconsistencies

**Comment by jreback** [comment]
thanks. I would add the original issues to the whatsnew that you have here (and maybe in the comments you added in ops.py)

**Pull request merged**
