### PR TITLE
Fix string format in test runner

### PR DESCRIPTION
**Pull request by rhysparry**
`.format()` was expecting keyword arguments. Updated to match other skips nearby.

### CODE REVIEW

**Review by alimcmaster1 — COMMENTED** [review]
LGTM, mind updating the PR title to something like "Fix string format in test runner" the current one is a bit misleading

**Comment by TomAugspurger** [comment]
If you fetch and merge master the CI failures should be fixed.

**Review by gfyoung — APPROVED** [review]
Good catch!

**Comment by gfyoung** [comment]
@rhysparry : Thanks!

**Pull request merged**
