### PR TITLE
BLD: recursive inclusion of DLLs in package data

### PR DESCRIPTION
**Pull request by chris-b1**
- [x] step 1 towards #32857

Will also make a PR in https://github.com/MacPython/pandas-wheels to add the DLLs to the wheel packaging script

### CODE REVIEW

**Comment by chris-b1** [comment]
Fair question - whole thing is a bit clunky - we will still specify the specific files in wheel building script, so no risk for now.
https://github.com/MacPython/pandas-wheels/pull/82/files#diff-c57957756c5cc094d7bb705d01a62868R74

**Comment by jreback** [comment]
> * [x]  step 1 towards #32857
> 
> Will also make a PR in https://github.com/MacPython/pandas-wheels to add the DLLs to the wheel packaging script

I believe we are using azure to build and NOT the original MacPython repo.

**Comment by jreback** [comment]
> Should we explicitly include the files we want? Just wondering if there's any licensing risk to recursively bundling dlls

NO, this is much easier.

**Comment by jreback** [comment]
@chris-b1 can you add a bug fix note in Other section (for 1.1). whether we backport is a different issue (we might not be doing a 1.0.4)

**Comment by jreback** [comment]
> > I believe we are using azure to build and NOT the original MacPython repo.
> 
> The azure stuff is running in the same MacPython repo.

oh my mistake, I thought we were now generating wheels on the pandas runs? guess not

**Comment by TomAugspurger** [comment]
CI is passing here. Is this good to go?

**Comment by chris-b1** [comment]
Should be - still some path stuff to figure out on the wheel building PR
that I haven't had a chance to look at, but in setup.py this is all that's
needed

**Comment by jreback** [comment]
we might need a what's new (esp if we backport to 1.0.4), can you do a followon (stick in 1.1 for now).

**Comment by simonjayhawkins** [comment]
@Meeseeksdev backport to 1.0.x

**Pull request merged**
