### PR TITLE
Faster method of normalising dictionary, allows user to select columns to ignore

### PR DESCRIPTION
**Pull request by PriestlyAdejo**
- [ ] Adds new feature and functionality to _normalize() function; ignores user specifed columns and returns the ignored columns in multiple forms (dictionary, tuple, list)
- [ ] closes https://github.com/pandas-dev/pandas/issues/47852
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
- [ ] CODE:

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
is this in reference to. specific issue?

**Review by PriestlyAdejo — COMMENTED** [review]
Was all I needed to do indent a few lines? I had some problems when copying the main nested_to_record() code to my own editor, all the indentation levels were completely off, so I changed them in my new function (nested_ignore_cols_to_record()). This PEP checker thing just brought up a lot of errors regarding line indentations.

**Review by PriestlyAdejo — COMMENTED** [review]
I don't know how to approve the request sorry lol

**Review by PriestlyAdejo — COMMENTED** [review]
I've fixed all the errors as noted by the automatic error checker. The errors all seemed to be with the indentation and some silly mistakes I made wit conditions and line continuations in my code.

**Comment by PriestlyAdejo** [comment]
Why does pre-commit keep on failing? I made sure to revise all the errors I made before...

**Review by mroeschke — CHANGES_REQUESTED** [review]
Thanks for the pull request. Of note, this is unlikely to be accepted in it's current state due to 

1. There appears to be no prior issue discussion supporting adding this new method.
2. Generally, the project has been weary of adding new methods since the API surface area is large already.

If you are aiming to improve the performance of `json_normalize`, it would be better to first open a Github issue describing the performance before/after of a modification made to `json_normalize`

**Comment by PriestlyAdejo** [comment]
> 

No not really... I made it as an addition to pandas_normalize as I was having major problems with the original function when I had json files with uneven columns (due to creating extra data while scraping).

**Comment by PriestlyAdejo** [comment]
I've added an issue in issues. This was an ENH:. Sorry for the errors, it's my first time making a contribution to a community package! 

Issue: #47843

**Comment by mroeschke** [comment]
Thanks for creating the issue (https://github.com/pandas-dev/pandas/issues/47852).

I see that this function has differences than `json_normalize`, but given that the new function is similar to `json_normalize` I would be -1 on including an entirely separate method.

**Comment by PriestlyAdejo** [comment]
> Thanks for creating the issue (#47852).
> 
> I see that this function has differences than `json_normalize`, but given that the new function is similar to `json_normalize` I would be -1 on including an entirely separate method.

I agree with you on that I don't think this should replace json_normalize, but I added it as an extra function WITHIN json normalize. This function could be used for whenever a user wants to ignore columns, although they can still choose to use the original json_normalize if they want to.

**Comment by PriestlyAdejo** [comment]
Hello?

**Comment by mroeschke** [comment]
Thanks for the effort here so far, but I think it's best if discussion occur on the issue you made first to gauge interest before moving with a pull request, so closing.

**Pull request closed without merging**
