### PR TITLE
issue-11833

### PR DESCRIPTION
**Pull request by Vutsuak16**
Updated the format.py  file in pandas core directory

Function updated : to_string()

Class : DataFrameFormatter

.travis.yml also changed to for fewer builds

### CODE REVIEW

**Comment by Vutsuak16** [comment]
@jreback  @jorisvandenbossche  I again created pandas development environment from scratch, to send pull requests. Now i am able to do it comfortably, no longers mutiple PRs to be created
I am closing the previous PR , would work on this
Thanks for bearing with me, I am new to pandas code base

**Comment by jreback** [comment]
@Vutsuak16 don't remove the travis file, that defeats the purpose of the testing

instead you need to run the tests locally, and see what fails, and change that test (as that is what this PR is about)

**Comment by Vutsuak16** [comment]
@jreback I  did run the tests, locally , hence have modified the travis file,based on the test failures.

**Comment by jreback** [comment]
you need to fix test failures not remove tests

pls reopen when u have updated

**Pull request closed without merging**
