### PR TITLE
TYP: __array__

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by WillAyd — CHANGES_REQUESTED** [review]
Can you add Dtype from pandas._typing to these? I think should be pretty trivial to add while touching

**Comment by jbrockmendel** [comment]
> Can you add Dtype from pandas._typing to these? I think should be pretty trivial to add while touching

I think we would need something more restricted to rule out ExtensionDtype

**Review by WillAyd — APPROVED** [review]
lgtm @simonjayhawkins

**Review by simonjayhawkins — APPROVED** [review]

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
