### PR TITLE
API: Disallow dict as agg parameter during groupby

### PR DESCRIPTION
**Pull request by gfyoung**
Grouped, rolled, and resample `Series` / `DataFrames` will now disallow dicts / nested dicts respectively
as parameters to aggregation (was deprecated before).

xref #15931.

### CODE REVIEW

**Comment by gfyoung** [comment]
@jreback : Rebased and green. PTAL.

**Comment by jreback** [comment]
@jorisvandenbossche @TomAugspurger any objections. even though there is not a great soln to replace this, it is time.

**Comment by TomAugspurger** [comment]
I think this shouldn’t be enforced until we have a replacement in place. Rather we should update the warning to show the new style once that’s implemented, and give people a release to update.

**Comment by jorisvandenbossche** [comment]
Yes, we should first work on the ideas discussed in https://github.com/pandas-dev/pandas/issues/18366. 

I am going to try to find some time for that the coming month, but other people looking at it is certainly welcome.

**Comment by gfyoung** [comment]
Ah, thanks for reminding me about #18366, in which case, I do agree that this error should wait...

Where does `0.25` fit into deprecation removals though? (I see only targets for `1.0`)

**Comment by TomAugspurger** [comment]
AFAIK, the current plan is to deprecate everything in 0.24, not remove
anything in 0.25, and have 1.0 be backwards-compat with 0.25 aside from the
removals of deprecated features.

The idea is for people to upgrade 0.25, fix warnings, and then get on 1.0
relatively easily.

**Comment by gfyoung** [comment]
Gotcha.  In that case, I'll move this deprecation removal to `1.0`.

**Pull request closed without merging**
