### PR TITLE
WIP/API: Make Day not a Tick

### LINKED ISSUE #41943: API: Make 'D' & offsets.Day always operate as calendar day instead of 24 Hour
From 2021-06-09 dev call, new discussion of https://github.com/pandas-dev/pandas/issues/22864

**Problem**:  Frequency string `'D'` and `pd.offsets.Day` can mean 24 hours or calendar day (23/24/25H) depending on the operation

**Original Settled Solution**: Deprecate all behavior where Frequency string `'D'` and `pd.offsets.Day` is a fixed 24 hours in favor of `"24H"`. A private `_Day` offset would be used where appropriate internally and swapped out once the deprecation is enforced.

(Note: I lost steam last time catching all the warnings issued in the testing suite given the above solution touches datetimes, timedeltas, offsets, methods, etc)

**Other Solutions**

1. Implement a new offset, e.g. `"'DayDST'"/pd.offsets.CalendarDay"`, that users can migrate to.
2. Deprecate `Tick`s (`Day` is a subclass) all together since they are redundant with `Timedelta`s

cc @pandas-dev/pandas-core

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #41943 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Still have a handful of failing tests and a bunch of ugly kludges.

With a second rc next week, we potentially have a second chance to get this in for 2.0.  Largely posting this to get @mroeschke's thoughts on if it is worth trying to get this in.

### CODE REVIEW

**Comment by mroeschke** [comment]
On first glance, I am a little surprised how much `isinstance(offset, Day)` special casing we still need, unless those are kludges (I would have hoped making it a calendar day would have provided some simplifications).

I am on the fence for rushing to get this into the second 2.0rc; personally I haven't fully comprehended all the implication of telling users to migrate from n * Days -> 24 * n Hours which seems like may touch a lot of areas I'm not aware of.

**Comment by jbrockmendel** [comment]
More cleanup to do, but I'm more optimistic about this than I was a day or two ago.

Some of the diff will be reduced by separately addressing a pre-existing bug in resample incorrectly allowing non-Tick offsets in TimedeltaIndex.

**Comment by jbrockmendel** [comment]
We could probably restore+deprecate Day multiplication and division, maybe also Timedelta(Day) and Day.nanos

**Comment by jbrockmendel** [comment]
Some of this will be unnecessary with #51896

**Comment by MarcoGorelli** [comment]
+1 on the idea, but isn't it a bit big to get into the RC at this point?

**Comment by jbrockmendel** [comment]
> but isn't it a bit big to get into the RC at this point?

Yes, that's why I want buy-in!

This is a bug that @mroeschke and I have been trying to fix on and off since 2018.  I only finally got a branch working a few days ago.

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
> This is a bug that @mroeschke and I have been trying to fix on and off since 2018. I only finally got a branch working a few days ago.

OK this makes me feel even more uneasy about rushing it in for 2.0

**Comment by mroeschke** [comment]
Yeah while I want to see this fixed too, I also think this is a lot for the RC2 in a few days.

Additionally, maybe we can think of a more holistic change for 3.0 that may simplify this more; deprecating Ticks all together and introducing a CalendayDay frequency.

**Comment by jbrockmendel** [comment]
Fair enough.  I'll try to keep this green until the 3.0 merge window opens, maybe we can chip away at it with deprecations in the interim.

**Comment by MarcoGorelli** [comment]
> rule_code

nope, it's from `scripts/validate_docstrings.py`

**Comment by MarcoGorelli** [comment]
is this ready for review? just asking because of the 'wip' in the title

**Comment by jbrockmendel** [comment]
> is this ready for review? just asking because of the 'wip' in the title

Ambiguous.  It is a breaking change to be merged for 3.0. I made a PR on the theory that keeping it green for a year would be easier than rebasing it _in_ a year.  Ideally we can find some bits to break off as deprecations in the interim.

So reviews are welcome, but definitely not a priority.

**Comment by jbrockmendel** [comment]
Closing in favor of #55502

**Pull request closed without merging**
