### PR TITLE
Disallow lossy SparseArray conversion

### PR DESCRIPTION
**Pull request by jbrockmendel**
cc @TomAugspurger

### CODE REVIEW

**Review by TomAugspurger — COMMENTED** [review]
The behavior on master is to silently convert to UTC? We should likely detect that, warn, and ask users to convert before passing to SparseArray.

**Comment by jbrockmendel** [comment]
> We should likely detect that, warn, and ask users to convert before passing to SparseArray.

This gets hairy in a way that im not sure is worth it.  In particular for tzaware, if instead of raising we fall through to `data = np.array(data)`, we get object-dtype, and fill_value of np.nan instead of NaT.

**Comment by jbrockmendel** [comment]
Updated to warn and maintain current behavior.

**Comment by jreback** [comment]
thanks, pls add a whatsnew as a followon

**Pull request merged**
