### PR TITLE
ENH:  add new feature of yyyyww for .isocalendar()  to resolve issue #49353

### PR DESCRIPTION
**Pull request by u5927645**
- [x] closes #49353   (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
Is there an open Github issue associated with this?

I would be -1 for this change. `isocalendar` should align with `datetime.datetime` which doesn't return `yearandweek`

**Comment by u5927645** [comment]
> 



> Is there an open Github issue associated with this?
> 
> I would be -1 for this change. `isocalendar` should align with `datetime.datetime` which doesn't return `yearandweek`

Yeah, this is an issue associated with this. Please see the link here: https://github.com/pandas-dev/pandas/issues/48947

Thanks for the suggestion about datetime.datetime.

**Comment by jreback** [comment]
-1 as well this is easily computable and doesn't warrant a method

**Comment by mroeschke** [comment]
Thanks for the PR, but closing as it appears this approach is undesirable.

**Pull request closed without merging**
