### PR TITLE
REF: implement tests/indexes/objects/

### PR DESCRIPTION
**Pull request by jbrockmendel**
Many of the tests in test_base are about `Index.__new__` cases that return a subclass.  This is intended specifically for Index-only tests.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Does the "objects" mean "object dtype" or Index "objects" ?

**Comment by jbrockmendel** [comment]
> Does the "objects" mean "object dtype" or Index "objects" ?

Good question, im open to a better name.  The idea here is for tests specific to the base Index class

**Comment by jorisvandenbossche** [comment]
Maybe something like `base_index` ?

**Comment by jreback** [comment]
great; test_base is huge!

**Pull request merged**
