### PR TITLE
BUG: frame.any/all with bool_only=True and Categorical[bool]

### PR DESCRIPTION
**Pull request by jbrockmendel**
Started with sharing some code, unearthed a bug along the way.

Nothing user-facing since it is only in ArrayManager.

### CODE REVIEW

**Comment by jreback** [comment]
is this user facing at all?

**Comment by jbrockmendel** [comment]
> is this user facing at all? if so, pls add a whatnew

nothing changing for users.  only change is in ArrayManager, where the current behavior doesnt match BlockManager

**Comment by jreback** [comment]
looks fine, pls rebase and ping on green.

**Comment by jbrockmendel** [comment]
ping

**Pull request merged**
