### PR TITLE
CI/DOC: fix clipboard on travis

### LINKED ISSUE #26075: DOC: clipboard library missing in doc env on travis
The doc builds sees the following failure: 

```
PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.org 
```

which is happening since the refactor of the CI envs in https://github.com/pandas-dev/pandas/pull/24632. In unifying things we might have by accident removed some clipboard related things for the doc build.

cc @saurav2608 if you want to take a look at this, always welcome

### PR DESCRIPTION
**Pull request by saurav2608**
- [ ] closes #26075

### CODE REVIEW

**Comment by saurav2608** [comment]
this is more complex than what I thought. I will relook tomorrow.

**Comment by saurav2608** [comment]
I am unable to replicate this in any of my environments. Thus I am create PRs to investigate.

**Comment by jreback** [comment]
@saurav2608 meaning the doc-build does not show any pyperclip error?

**Comment by jreback** [comment]
closing as stale

**Comment by jorisvandenbossche** [comment]
(reopened to try something out, based on the diff I noticed the use of `export DISPLAY`, and that it was in a different place before. Who knows that makes a difference ..)

**Comment by jorisvandenbossche** [comment]
@jreback OK?

(if this passes, will add a comment explaining why / referencing this PR)

**Comment by jreback** [comment]
so these are actually run? can u show that somewhere
maybe should make these tests highly visible somehow

**Comment by jorisvandenbossche** [comment]
What do you mean with "so these are actually run?" ? 
Or is it a comment meant for a different PR? (there are no tests involved here, only for doc building)

**Comment by jreback** [comment]
@jorisvandenbossche we didn't notice that we should be running these (and weren't); I dont' think this has changed. We need a highly visible test that we can simply look in the logs and inspect (maybe just add a print statement to it).

https://travis-ci.org/pandas-dev/pandas/jobs/532738283

```
-----------------------------------------------------------------------------------------------------------------------------
#5 pandas.tests.test_algos.TestRank.test_pct_max_many_rows[1d]: skipping high memory test since --run-high-memory was not set
#6 pandas.tests.test_algos.TestRank.test_pct_max_many_rows[2d]: skipping high memory test since --run-high-memory was not set
------------------------------------------------------------------------------------------------------------------------------
#7 pandas.tests.frame.test_rank.TestRank.test_pct_max_many_rows: skipping high memory test since --run-high-memory was not set
-----------------------------------------------------------------------------------------------------------------
#8 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[delims]: clipboard primitives not installed
#9 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[utf8]: clipboard primitives not installed
#10 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[utf16]: clipboard primitives not installed
#11 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[string]: clipboard primitives not installed
#12 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[long]: clipboard primitives not installed
#13 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[nonascii]: clipboard primitives not installed
#14 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[colwidth]: clipboard primitives not installed
#15 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[mixed]: clipboard primitives not installed
#16 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[float]: clipboard primitives not installed
#17 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame[int]: clipboard primitives not installed
#18 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[delims-\t]: clipboard primitives not installed
#19 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[delims-,]: clipboard primitives not installed
#20 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[delims-|]: clipboard primitives not installed
#21 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[utf8-\t]: clipboard primitives not installed
#22 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[utf8-,]: clipboard primitives not installed
#23 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[utf8-|]: clipboard primitives not installed
#24 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[utf16-\t]: clipboard primitives not installed
#25 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[utf16-,]: clipboard primitives not installed
#26 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[utf16-|]: clipboard primitives not installed
#27 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[string-\t]: clipboard primitives not installed
#28 pandas.tests.io.test_clipboard.TestClipboard.test_round_trip_frame_sep[string-,]: clipboard primitives not installed
```

**Comment by jorisvandenbossche** [comment]
Ah, so those tests have not been running on master for a while? (since the CI env refactor PR https://github.com/pandas-dev/pandas/pull/24632), ok, I see now.

But it seems that this PR actually solves that. They are running again (just not on the first travis build, but if you look eg at the second travis build: https://travis-ci.org/pandas-dev/pandas/jobs/532738284: no message about skipped tests anymore. On the first travis build, they have been skipped even before the CI env refactor). 

But not sure I understand why the first travis build (in the build matrix) would skip those and the second not. I don't see anything in their definition that can explain that (the clipboard tests are marked as 'single').

**Comment by jorisvandenbossche** [comment]
> But not sure I understand why the first travis build (in the build matrix) would skip those and the second not.

Ah, maybe because the first build has no qt installed and the second does (through matplotlib), travis-37.yml vs travis-36-locale.yaml.

**Comment by jreback** [comment]
right I don't care that they run on *all* builds, but at least one. I think just add a print statement in the basic clip test might be enough here to provide us an easy visual reference.

**Comment by jorisvandenbossche** [comment]
@jreback I added some print statements, but they don't show up in the travis logs (although we have `-s` in the pytest command)

**Comment by jreback** [comment]
@jorisvandenbossche then how can we be sure these are actually run? This is the entire problem.

**Comment by jorisvandenbossche** [comment]
Well, you can say that for all other tests as well... 
Unless we do `-v` to show each test that has been run.

**Comment by jreback** [comment]
> Well, you can say that for all other tests as well...
Unless we do -v to show each test that has been run.

maybe, but this is a continual issue, and we need a foolproof way to say these tests are actually run

**Comment by jorisvandenbossche** [comment]
Will open an issue about that, but merging this since it is actually solving a problem

**Comment by jorisvandenbossche** [comment]
@saurav2608 thanks for putting me on the right track with the DISPLAY change !

**Comment by saurav2608** [comment]
> @saurav2608 thanks for putting me on the right track with the DISPLAY change !

@jorisvandenbossche  Absolutely. I wish I could have contributed more.  I am totally swamped at work.

**Pull request merged**
