### PR TITLE
Implement Delegate parts of #24024

### PR DESCRIPTION
**Pull request by jbrockmendel**
This one got a little bit messy because until we move all the way away from inheritance there are some methods that need to be overwritten, so the `@delegate_names` calls are a bit more verbose than in #24024.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
The delegation changes seem relatively straightforward. @jorisvandenbossche @jreback do you have any problems with doing them in #24024?

**Comment by jreback** [comment]
I think this uses ``_eadata`` changes. ok here or in main PR.

**Comment by TomAugspurger** [comment]
My point was that if people have had a chance to review the dispatching in #24024, and are happy with it, then it needn't be split off here (especially when the changes here aren't what will end up being in master when eadata is removed).

**Comment by jreback** [comment]
> My point was that if people have had a chance to review the dispatching in #24024, and are happy with it, then it needn't be split off here (especially when the changes here aren't what will end up being in master when eadata is removed).

well that's the problem. that PR is so big that its not easy to review it at all.

**Comment by TomAugspurger** [comment]
I was under the impression that people had already looked at the dispatching parts. Was that wrong?

cc @jorisvandenbossche.

**Comment by jreback** [comment]
@TomAugspurger there is so much going on there it will take enormous effort and time to do it this way. splitting is much better.

**Comment by TomAugspurger** [comment]
I don't follow your logic. I'm trying to reduce wasted effort, by not
splitting things that have already been reviewed (though maybe they haven't
been reviewed) and by not having the intermediate _eadata in too many
places.

**Comment by jreback** [comment]
> I don't follow your logic. I'm trying to reduce wasted effort, by not
splitting things that have already been reviewed (though maybe they haven't
been reviewed) and by not having the intermediate _eadata in too many
places.

The problem is if its in the original, *who* and *how* was it reviewed? its not clear at all. sure maybe it was looked at briefly, but leaving it there is the worst scenario. you have to constantly scan for changes. I haven't even looked at your PR fully once. Its simply too many changes.

**Comment by TomAugspurger** [comment]
I guess I was wrong then. Feel free to proceed how you see best.

**Comment by jreback** [comment]
thanks @jbrockmendel and @TomAugspurger

**Pull request merged**
