### PR TITLE
REF: de-duplicate IntervalIndex._intersection

### PR DESCRIPTION
**Pull request by jbrockmendel**
made possible by #41863

### CODE REVIEW

**Review by jreback — APPROVED** [review]
wow luv it!

**Comment by jreback** [comment]
failures looks spurious

**Comment by jorisvandenbossche** [comment]
This _might_ have caused a big slowdown, see https://pandas.pydata.org/speed/pandas/#index_object.IntervalIndexMethod.time_intersection_both_duplicate?python=3.8&Cython=0.29.21&p-param1=100000&commits=17391997-969688a9

(the [range of commits](https://github.com/pandas-dev/pandas/compare/17391997...969688a9) also includes some other commits)

**Comment by jbrockmendel** [comment]
> This might have caused a big slowdown [...] (the range of commits also includes some other commits)

The indexing bugfix _might_ play a part, but it does seem likely that this is the culprit.  Profiling it looks like drop_duplicates is the big time sink.

**Comment by jbrockmendel** [comment]
ive got a IntervalArray.unique branch in the works that cuts this this from 4x down to 2x, still a ways to go.

**Pull request merged**
