### PR TITLE
BLD: drop `options.package_data` from setup.cfg

### LINKED ISSUE #46270: BLD: Remove `options.package_data` from setup.cfg
Hello! Not sure if this is actually what we want, but I think this can simplify things.

Currently, we include data files in builds in 3 ways:
1. Listing them in MANIFEST.in
2. Listing them under `options.package_data` in setup.cfg
3. Setting `include_package_data = True` in setup.cfg

I believe that it is possible (and therefore desirable, as it is more DRY and less spread out) to migrate everything in number 2 to number 1, and still have the same behavior.

This is per both https://setuptools.pypa.io/en/latest/userguide/datafiles.html and from experiments in https://github.com/abravalheri/experiment-setuptools-package-data, where it is shown that if you have `include_package_data = True`, then MANIFEST.in is sufficient, you don't need `options.package_data`, both for sdists and wheels.

It looks like `include_package_data = True` quietly snuck during https://github.com/pandas-dev/pandas/pull/38852. Before this, I think the package_data was needed, but now it is not.

A small local test I think showed this to be true, but I might have messed it up so not sure. Probably artifacts from CI would tell the story.

@fangchenli I think you might be the one to look at this? Thank you! See the attached PR

### PR DESCRIPTION
**Pull request by NickCrews**
- [x] closes #46270
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] N/A Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

@fangchenli it looks like you have a lot of history here

### CODE REVIEW

**Comment by fangchenli** [comment]
I think you need to trigger the sdist build. 

@lithomas1

**Comment by NickCrews** [comment]
> I think you need to trigger the sdist build.
It looks like the sdist build ran? https://github.com/pandas-dev/pandas/runs/5470020092?check_suite_focus=true#step:5:856. There you can see that the `pandas/io/formats/templates/*.tpl` files are all included. Not sure about the `.dll` files, maybe that's what you mean, the windows sdist build needs to get run?

The test failures look totally unrelated, but I'm not sure why they aren't failing on `main`...?

**Comment by NickCrews** [comment]
OK, so I downloaded the python 3.9 `sdist` artifacts from the last successful run before this PR (https://github.com/pandas-dev/pandas/actions/runs/2118052199) and from this PR (https://github.com/pandas-dev/pandas/actions/runs/2138906174)

and ran `diff -rq pandas-1.5.0.dev0+660.gb3b5e2a46a pandas-1.5.0.dev0+663.g468ff52b7b` and got:
```
Files pandas-1.5.0.dev0+660.gb3b5e2a46a/MANIFEST.in and pandas-1.5.0.dev0+663.g468ff52b7b/MANIFEST.in differ
Files pandas-1.5.0.dev0+660.gb3b5e2a46a/PKG-INFO and pandas-1.5.0.dev0+663.g468ff52b7b/PKG-INFO differ
Files pandas-1.5.0.dev0+660.gb3b5e2a46a/pandas/_version.py and pandas-1.5.0.dev0+663.g468ff52b7b/pandas/_version.py differ
Files pandas-1.5.0.dev0+660.gb3b5e2a46a/pandas.egg-info/PKG-INFO and pandas-1.5.0.dev0+663.g468ff52b7b/pandas.egg-info/PKG-INFO differ
Files pandas-1.5.0.dev0+660.gb3b5e2a46a/setup.cfg and pandas-1.5.0.dev0+663.g468ff52b7b/setup.cfg differ
```
I checked each of these and they look as expected.

So I think that this doesn't introduce any other changes? @fangchenli any other things to check, or is this good to merge? Thanks!

**Review by fangchenli — APPROVED** [review]

**Comment by jreback** [comment]
thanks @NickCrews

**Pull request merged**
