### PR TITLE
DOC: Clarify column type for 'on' parameter of rolling

### LINKED ISSUE #21687: "on" argument of DataFrame.rolling only works for datetime columns
the `on=` argument of `DataFrame.rolling` only works for datetime columns.

```
df = pd.DataFrame([
    [18, 0],
    [2, 0],
    [1, 0],
    [9, 1],
    [8, 1],
], columns=['value', 'roll'])
```

```
df.roll = pd.to_datetime(df.roll, unit='s')
df.rolling('1s', on='roll').value.max()
```

returns:

```
0    18.0
1    18.0
2    18.0
3     9.0
4     9.0
Name: value, dtype: float64
```
as expected.

But 

```df.rolling(1, on='roll').value.max()```

returns:

```
0    18.0
1     2.0
2     1.0
3     9.0
4     8.0
Name: value, dtype: float64
```

If this is intentional behavior, I'd be happy to change the docs to note this (the docs currently imply that `on=` can be used for any column).

### PR DESCRIPTION
**Pull request by ihsansecer**
- [x] closes #21687

### CODE REVIEW

**Comment by WillAyd** [comment]
Might be reading it wrong but not sure about the referenced issue. Commented there

**Review by jreback — CHANGES_REQUESTED** [review]
I would rather say that the 'on' argument is ignore for for an integer window argument.

**Comment by ihsansecer** [comment]
@WillAyd I believe he is confused if an integer column is used while calculating rolling window

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @ihsansecer

**Pull request merged**
