### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by pombredanne**
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by WillAyd** [comment]
Failures appear to be a result of an isort change so unrelated, but might see if we can fix that first and ask you to rebase thereafter just to be safe

**Comment by WillAyd** [comment]
PR for issue above is #25455

**Comment by WillAyd** [comment]
Can you merge master? Just had a PR go in that should resolve build failures

**Review by datapythonista — APPROVED** [review]

**Comment by jreback** [comment]
thanks @pombredanne

**Pull request merged**
