### PR TITLE
DOC: remove older whatsnew

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by jreback** [comment]
@jorisvandenbossche what do you think? should remove 0.17 as well? 0.18? (e.g. keep last 2 major releases).

Idea is that this will make docs a bit shorter / build faster (slightly). not sure if its is worth though.

**Comment by jorisvandenbossche** [comment]
I personally would not remove them. I am more in favor of https://github.com/pandas-dev/pandas/issues/6856 -> converting examples to static code-blocks (keeping behaviour as when released, instead of updating examples), which also makes it a lot faster to build.

Although I am maybe a bit too 'attached' to the older whatsnew docs (I regularly search through them, but maybe this is rather uncommon behaviour as I am a dev).

**Comment by jreback** [comment]
@jorisvandenbossche ahh I c, didn't even know that issue existed! ok that actually makes sense. I tagged that a bit. closing then.

**Comment by jorisvandenbossche** [comment]
Something else we should do, is starting a separate page at a certain point, instead of one huge (or moving the older to a separate page, but problem with that is that it breaks links)

**Comment by jreback** [comment]
@jorisvandenbossche yep, though I think we have a reorg on the whole doc structure somewhere....

**Pull request closed without merging**
