### PR TITLE
TST: only catch deprecation warnings for top-level module imports

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback What is the rationale here? Whas there a certain problem? The fact that those raise a warning is useful to test, no?

**Comment by jreback** [comment]
well the problem is we have ``pandas.json``, which if you are *in* ``pandas`` and do an ``import json`` it imports the local module (and not from the std library). So eventually when I get rid of ``pandas.json`` this will go away.

I put this in here, because you see the warning when the ``_version`` is imported.

**Comment by jorisvandenbossche** [comment]
Sorry, I don't understand the connection between the import problem of json, and the fact that `pd.json.dumps` raises a FutureWarning ?

> I put this in here, because you see the warning when the _version is imported.

Do you mean

```
In [1]: from pandas import _version
```

I don't see a warning there.

**Comment by jreback** [comment]
try creating a sdist, then untarring it. you will see a file ``pandas/_version.py``, versioneer creates this. 

IN this file it does a ``import json``. BUT this is IN the ``pandas/`` directory. guess what it picks up ``pandas.json``. (it has always been this ways, and it just happens to work, because ``json.loads`` is works like the library one).

It actually loading the WRONG library. The deprecation warning is because we are deprecating ``pandas.json``.

Its an unfortunate consequence of having a stdlib module name that is pretty common.

**Comment by jreback** [comment]
this ONLY happens on a package version FYI! It *does* NOT happen with a dev version. I noticed this when on the new build-test job, which actually does a full install then ``import pandas; pandas.test()``, just like an end-user would do.

It shows a deprecation warning immediately.

**Pull request merged**
