### PR TITLE
ENH: Added support for the pd.read_sql to return a dictionary of all tables

### LINKED ISSUE #45979: IF the read_sql function can read multi datatable results in one time like the read_excel behaves
#### Is your feature request related to a problem?

IF the read_sql function can read multi datatable results in one time like the read_excel behaves. 
For sometimes, I have to read data from database with read_sql for several times.

#### Describe the solution you'd like
Like the function read_excel, setting the param sheet_name=None will get all the worksheets, add a similar param like that for read_sql funtion,try to make it convenient to read  multi datatable results in one time.
The read_sql returns the first datatable result only now, like that shown in the following picture
image

Is it possible to return multi datatable results in one time? Thanks!

### PR DESCRIPTION
**Pull request by Pydare**
- [x] closes #45979 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by mroeschke** [comment]
Thanks for the pull request, but we require discussion for enhancement requests before moving forward with pull requests The referenced issue has not been triaged by the core team yet. (As a reference I would be -1 on this enhancement as our other `read_*` methods are not "multi-file/table" aware and trivial to perform in a loop).

Closing for now, but if you'd like to stimulate the discussion in the original issue or work on an enhancement that has been triaged and supported by the core team that would be much appreciated

**Comment by Pydare** [comment]
Thanks for the update, I would look at other issues that have been triaged. 

How do I know when an issue has been triaged? Is there a specific label?

Lastly, what does -1 mean on enhancements? I noticed some other figures like -0.5 in some PRs too

**Comment by jreback** [comment]
-1 means almost no chance of the PR being accepted

**Comment by mroeschke** [comment]
> How do I know when an issue has been triaged? Is there a specific label?

Any issue with `Needs ...` generally means it has not been fully vetted yet.

**Pull request closed without merging**
