### PR TITLE
DOC: updating the Series.str.cat docstring

### PR DESCRIPTION
**Pull request by ym-pett**
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by amblina** [comment]
We have run ``validate_docstrings.py`` and gotten the following error:

```
Errors found:
  Errors in parameters section
       Parameter "join" description should finish with "."
```
This is nothing to do with our PR.  We're great.

**Comment by Cheukting** [comment]
I think the error is because the "." is followed by "`other`" @datapythonista may be you can varify

**Comment by TomAugspurger** [comment]
Pretty sure that error is from the `.. versionadded:: `. We need to update the script to not complain when there isn't an ending period for those.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
