### PR TITLE
CLN: Remove tseries v0.19.0 deprecations

### PR DESCRIPTION
**Pull request by gfyoung**
* Remove frequencies.get_standard_freq
* Drop the "freqstr" keyword from frequencies.to_offset

Deprecated in v0.19.0

xref #13874

### CODE REVIEW

**Comment by jreback** [comment]
rebase and push again, fixed some hanging by Travis CI

**Comment by gfyoung** [comment]
@jreback : Surprised `master` is doing okay.  A lot of PR builds on Travis are getting hit with this "disk quota exceeded" error.  Seems to be affecting a lot of other repositories though.

**Comment by jreback** [comment]
@gfyoung that was this morning. I think travis ci is having issues since then.

**Comment by gfyoung** [comment]
It's still happening though AFAICT.  The PR build before mine has already failed on two builds with that exact same error.

https://travis-ci.org/pandas-dev/pandas/builds/323891129

**Comment by jreback** [comment]
see the Travis Status: https://twitter.com/traviscistatus?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

still happening. FYI this is the Red icon on the travis page

**Comment by gfyoung** [comment]
@jreback : Looks like Travis is up and running again.  All is green now.  PTAL.

**Comment by jreback** [comment]
thanks!

**Pull request merged**
