### PR TITLE
CI: Removed pattern check for specific modules

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Looks good. Do you have a larger plan with doctest or just this?

**Comment by MomIsBestFriend** [comment]
@WillAyd The end goal is to have the line
```
pytest -q --doctest-module pandas/
```

But ATM it's not possible.

---

I am just making sure that we keep some modules with correct examples.
My next PR will cover ```pd.Series```

**Comment by simonjayhawkins** [comment]
Thanks @MomIsBestFriend

**Comment by WillAyd** [comment]
Could be convinced otherwise but I think worth backporting to keep CI consistent - @MomIsBestFriend can you do manually?

**Comment by MomIsBestFriend** [comment]
@WillAyd Sure! I have opened a PR here #31993

**Pull request merged**
