### PR TITLE
Bumping up min version for pyarrow

### LINKED ISSUE #18742: COMPAT: drop pyarrow < 0.7 and fastparquet < 0.1 for Parquet IO
What @dhirschfeld originally did in https://github.com/pandas-dev/pandas/pull/18629, but what was removed to merge it for 0.21.1. I think we can do this for 0.22

For pyarrow < 0.7 we can remove some extra complexity, for fastparquet I am actually not sure if it is needed.

### LINKED ISSUE #23409: we should bump our min of pyarrow to 0.7.0
_Originally posted by @jreback in https://github.com/pandas-dev/pandas/pull/23321_

### PR DESCRIPTION
**Pull request by anjsudh**
closes #18742
closes #23409 
- [x] tests passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
linting issues run: ``LINT=1 ci/code_checks.sh`` locally to see.

also can you put a check on fastparquet < 0.1 (or could do 0.1.2) i think is ok too

**Comment by jreback** [comment]
@martindurant what is the oldest fastparquet that we should target here?

**Comment by datapythonista** [comment]
Can you run `scripts/convert_deps.py`, so `ci/requirements-optional-pip.txt` is updated.

**Comment by martindurant** [comment]
Since this is for newer pandas, and fastparquet is pretty light on specific versions of its dependencies, I would keep with the most recent, 0.1.6, which is now 2.5 months old. I ought to put out a new version but wouldn't ask you to depend on it.

**Comment by jreback** [comment]
@martindurant well, this version of pandas could easily be installed on an existing setup, so easier to allow an older version unless we really need to upgrade it. ok let's go with 0.1.2 then.

**Comment by martindurant** [comment]
0.1.2 is over a year old. OK, if the tests still pass...

My point was, if someone was wanting to upgrade their pandas, it should be reasonable for them to upgrade fastparquet too.

**Comment by jreback** [comment]
there is no easy way to force an upgrade as fp is just one of many optional dependencies 

so much easier to have backward compatibility rather than annoy users

**Comment by anjsudh** [comment]
so shall i go ahead with fastparquet 0.1.2 as minimum version?

**Comment by anjsudh** [comment]
have set min version for fastparquet as 0.1.2.

**Comment by jreback** [comment]
you have a lint error

```
inting .py code
./pandas/io/parquet.py:8:1: F401 'pandas.Int64Index' imported but unused
./pandas/io/parquet.py:8:1: F401 'pandas.RangeIndex' imported but unused
```

ping on green.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
