### PR TITLE
Fixes non-existent doc/source/api.rst issue 

### PR DESCRIPTION
**Pull request by ArunimSamudra**
Modified the path doc/source/api.rst

### CODE REVIEW

**Comment by WillAyd** [comment]
@datapythonista

**Review by datapythonista — APPROVED** [review]
Thanks for fixing those!

**Comment by WillAyd** [comment]
Thanks @ArunimSamudra

**Comment by ArunimSamudra** [comment]
You're welcome @WillAyd. Happy to get my first PR merged.

**Pull request merged**
