### PR TITLE
Changed pct_change parameters to calculate pct_change right-to-left f…

### LINKED ISSUE #39672: Pandas dataframe pct_change function arguments
Typically financial data is ordered by columns in reverse chronology ie columns '2020', '2019', '2018', '2017'.. But we need the pct_change function in reverse order. Looking at the Pandas reference (last example): https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pct_change.html?highlight=pct_change#pandas.DataFrame.pct_change

df.pct_change(axis='columns')

           2016    2015         2014

GOOG NaN -0.151997 -0.086016

APPL NaN 0.337604 0.012002

Such a calculation makes no sense or at least is not useful. We need to look at change from today over past period, not past period over future period. Other than iterating in reverse order or transposing, can the pct_change function be augmented with a new argument to reverse the calculation to the form: (A0-A1)/A1 instead of (A1-A0)/A0 ??

### PR DESCRIPTION
**Pull request by andrei-assa**
…or axis=1.

- [ ] closes #39672
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- For axis = 1, periods = -periods.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
tests pls

**Comment by MarcoGorelli** [comment]
> closes #39672

The issue just involves slightly changing the example in the docs, the source code shouldn't need changing

**Comment by bashtage** [comment]
> The issue just involves slightly changing the example in the docs, the source code shouldn't need changing

Fully agree.  It is not reasonable to change the behavior of `pct_change` when applied across columns. It should be the case that `pct_change(periods=n)` should be the change from `df.iloc[:-n]` to `df.iloc[n:]` for positive `n` and `df.iloc[n:]` to `df.iloc[:-n]` for negative `n`. Adding an axis shouldn't change this behavior, and when computed across columns `pct_change(periods=n)` should be the change from `df.iloc[:,:-n]` to `df.iloc[:,n:]` for positive `n` and `df.iloc[:,n:]` to `df.iloc[:,:-n]` for negative `n`

**Comment by MarcoGorelli** [comment]
closed in #40266 , thanks anyway @andrei-assa for your PR

**Pull request closed without merging**
