### PR TITLE
CLN/DEPR: remove setter for MultiIndex levels/labels properties

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Noticed this in another PR, this doesn't seem to be listed in our deprecations master issue https://github.com/pandas-dev/pandas/issues/6581. But it is already deprecated since 0.13 (https://github.com/pandas-dev/pandas/pull/4039)

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Failure only seems to be the clipboard one (which is known), and the BUILD_TEST. 
Not sure why that last one is failing already tried to restart it some times)

**Comment by jreback** [comment]
> Failure only seems to be the clipboard one (which is known), and the BUILD_TEST.
Not sure why that last one is failing already tried to restart it some times)

assume you have rebased on master. These failures are not longer.

**Comment by jreback** [comment]
your build looks old (e.g. not rebased)

**Comment by jreback** [comment]
lgtm otherwise (but push again anyhow)

**Comment by jorisvandenbossche** [comment]
This *was* from a clean master, at the moment the PR was opened :-)

**Pull request merged**
