### PR TITLE
Move tests that dont belong in test_offsets

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
needs a rebase, ping on green.

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by jbrockmendel** [comment]
Ping

**Comment by jreback** [comment]
thanks!

**Pull request merged**
