### PR TITLE
WIP Add ccache to Azure builds 

### PR DESCRIPTION
**Pull request by jonashaag**
New try of #46307

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jonashaag** [comment]
@phofl do you know why #46308 runs on Azure but not this one?

**Comment by phofl** [comment]
Not sure, but it might be related to draft status? Also have not looked at your diff

**Comment by jonashaag** [comment]
I tried w/o draft, no change. Do you know where on Azure I can go looking for any errors with the pipeline file?

**Comment by phofl** [comment]
Not really no, https://dev.azure.com/pandas-dev/pandas/_build?view=runs lists all builds, but yours is not there

**Comment by jonashaag** [comment]
@phofl seems like at least one GitHub Action must run otherwise Azure won't run. WTF

**Comment by phofl** [comment]
Ok this is good to know

**Comment by himanshubathamx2** [comment]
nicee

**Pull request closed without merging**
