### PR TITLE
BUG: adds validation for boolean keywords in DataFrame.set_index

### LINKED ISSUE #16714: inplace kwarg must be of bool type, but other boolean kwargs don't have this restriction
#### Code Sample, a copy-pastable example if possible

Using `DataFrame.set_index` as an example, but this applies to other methods that take an inplace kwarg:

```python
# The following work
df.set_index('foo', drop=0)
df.set_index('foo', append='yes please')
df.set_index('foo', verify_integrity=22.7)
# This doesn't
df.set_index('foo', inplace=1)
```
The last line raises `ValueError: For argument "inplace" expected type bool, received type int.1`

#### Problem description

This behaviour seems inconsistent.

#### Expected Output

The last line should proceed successfully with inplace treated as `True`.

Or every boolean kwarg should be type-checked, though I like this option much less. I think using 0/1 as shorthand for True/False is a pretty common idiom.

It looks like this is the result of a somewhat recent 'bug fix': #14189. To me, it feels like a regression.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-78-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8

pandas: 0.20.1
pytest: None
pip: 9.0.1
setuptools: 36.0.1
Cython: None
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.4.1
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.3.0
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.1
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by richardjgowers**
ENH: Adds util._validators.validate_keywords_as_bool decorator

- [x] closes #16714
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

I've used a decorator so that we can check all the boolean kwargs at once rather than have a lot of lines of `validate_bool_kwarg` at the top of every method.

### CODE REVIEW

**Comment by richardjgowers** [comment]
Oh, and if people are happy with this decorator approach, I can go through and give all methods the same treatment/tests

**Comment by gfyoung** [comment]
> Oh, and if people are happy with this decorator approach

Just for reference, can you list 1 - 2 places where this also could be applied?  Seems reasonable otherwise, though I would check performance just in the case the decorator imposes too much overhead.

**Comment by richardjgowers** [comment]
@gfyoung this could/(should according to @jreback https://github.com/pandas-dev/pandas/issues/16714#issuecomment-309593201) be applied to all boolean keyword arguments.  So I could go through all of DataFrame, Series etc and decorate all methods with boolean kwargs

**Comment by gfyoung** [comment]
@richardjgowers : Sure, though if you could specify a couple just for reference which take multiple boolean arguments, that would be great.

**Comment by richardjgowers** [comment]
@gfyoung just scanning through frame.py I found:

https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L1528
https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L1653
https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L1681
https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L3161
https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L3638

**Comment by jreback** [comment]
can you rebase; move note to 0.22.0

**Comment by jreback** [comment]
closing as stale, if you want to work on this, pls ping.

**Pull request closed without merging**
