### PR TITLE
TST: Add Series.update ExtensionArray tests

### PR DESCRIPTION
**Pull request by dsaxton**
cc @simonjayhawkins 

xref https://github.com/pandas-dev/pandas/issues/25744 https://github.com/pandas-dev/pandas/issues/34020

I think the dtype issue for DataFrame.update with categorical columns mentioned in the first issue is still unaddressed, so likely don't want to only close and lose that (perhaps break into its own issue)?

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
> I think the dtype issue for DataFrame.update with categorical columns mentioned in the first issue is still unaddressed, so likely don't want to only close and lose that (perhaps break into its own issue)?

sgtm.

although this PR _could_ close the 2 issues (with the caveat of opening a new issue for the DataFrame case), my preference would be to replace test_update_extension_array_series with a test in tests/extension instead.

**Comment by dsaxton** [comment]
> my preference would be to replace test_update_extension_array_series with a test in tests/extension instead.

I think this is okay since it's the Series update method that we're testing? TBH the extension-specific tests are a bit confusing to me because of the class hierarchies and heavy use of fixtures (IMHO it's easier if we can reason about tests locally)

**Review by jreback — APPROVED** [review]
lgtm. ping on green.

**Comment by dsaxton** [comment]
> lgtm. ping on green.

@jreback ping

**Comment by jreback** [comment]
thanks

**Pull request merged**
