### PR TITLE
[BUG] change types to Py_ssize_t to fix #21905

### LINKED ISSUE #21905: Are tests failing on Windows?
Running the tests on windows fail:

```
>>> pytest pandas\tests\tseries\offsets\test_offsets.py -x
――――――――――――――――――――― TestCommon.test_apply[BusinessDay0] ―――――――――――――――――――――

self = <pandas.tests.tseries.offsets.test_offsets.TestCommon object at 0x066D4530>
offset_types = <class 'pandas.tseries.offsets.BusinessDay'>

    def test_apply(self, offset_types):
        sdt = datetime(2011, 1, 1, 9, 0)
        ndt = np_datetime64_compat('2011-01-01 09:00Z')

        for dt in [sdt, ndt]:
            expected = self.expecteds[offset_types.__name__]
            self._check_offsetfunc_works(offset_types, 'apply', dt, expected)

            expected = Timestamp(expected.date())
            self._check_offsetfunc_works(offset_types, 'apply', dt, expected,
>                                        normalize=True)

pandas\tests\tseries\offsets\test_offsets.py:357:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas\tests\tseries\offsets\test_offsets.py:320: in _check_offsetfunc_works
    result = func(dt_tz)
pandas\tseries\offsets.py:85: in wrapper
    result = result.normalize()
pandas\_libs\tslibs\timestamps.pyx:1086: in pandas._libs.tslibs.timestamps.Timestamp.normalize
    normalized_value = normalize_i8_timestamps(
pandas\_libs\tslibs\conversion.pyx:1095: in pandas._libs.tslibs.conversion.normalize_i8_timestamps
    result = _normalize_local(stamps, tz)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   pos = trans.searchsorted(stamps, side='right') - 1
E   ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'int'

pandas\_libs\tslibs\conversion.pyx:1151: ValueError
```

Several tests fail. 

By going back in commit history until the tests pass, it looks like this is caused by #21826.

### PR DESCRIPTION
**Pull request by jbrockmendel**
May close #21905, will need to check with OP.

### CODE REVIEW

**Comment by topper-123** [comment]
I've run the complete test suite on this. Everything passes beutifully.

**Comment by gfyoung** [comment]
@jbrockmendel : Can we add a `whatsnew` entry for this?

**Comment by jbrockmendel** [comment]
> Can we add a `whatsnew` entry for this?

I don't think so, the relevant bug was only introduced a few days ago.

**Comment by topper-123** [comment]
Is it possible to add 32-bit tests to the testing systems, to guard against similar bugs in the future?

**Comment by gfyoung** [comment]
@topper-123 : I don't see why not.  Feel free to propose some if you have ideas.

**Comment by jbrockmendel** [comment]
@topper-123 might want to discuss in #13715.

@jreback this should be good to go.

**Comment by topper-123** [comment]
uh, I 've never set such things up before, so it will proabbly take more time than I'd like. 

It's very seldom that things like this happen, so maybe it's so rare, that building it into the testing systems will be overkill?

**Comment by gfyoung** [comment]
> uh, I 've never set such things up before, so it will proabbly take more time than I'd like.

It's very seldom that things like this happen, so maybe it's so rare, that building it into the testing systems will be overkill?

@topper-123 : Not overkill but not straightforward to do.  I tried once emulating what `numpy` did (the start of the fun can be found [here](https://github.com/numpy/numpy/blob/master/.travis.yml#L42)), but even that was surprisingly error-prone.

**Comment by jreback** [comment]
32 bit testing happens on another CI on a daily basis

it’s a PITA because it’s not easily testable (eg you can run your PR against it) - this is a limited of travis currently

but haven’t put much effort because we should just drop 32 bit anyways

OTOH datetime changes often force these 32 bugs to the surface

**Comment by jbrockmendel** [comment]
Unless there’s an objection, let’s move the CI discussion to #13715 and push this bug fix through.

**Comment by jreback** [comment]
ok let's see.

**Comment by topper-123** [comment]
I just built the newest master release with this PR and tested it.

Everything built correctly and all tests passed.

**Pull request merged**
