### PR TITLE
Manual Backport PR #47287 on branch 1.4.x (DEPS: Sync environment.yml with CI dep files)"

### PR DESCRIPTION
**Pull request by mroeschke**
PR #47287

### CODE REVIEW

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
will look soon. nbd if backport misses 1.4.3

(not changed mypy version on backport branch for previous releases).

**Comment by simonjayhawkins** [comment]
moving to 1.4.4 as the typing issues on main need sorting too.

**Comment by simonjayhawkins** [comment]
@mroeschke the typing failures on 1.4.x I'm also seeing locally with numpy 1.23.1 on main. downgrading to 1.22.4 and mypy checks pass. (So I'm assuming the mypy errors reported on 1.4.x are correct)

With the xarray failure here, I'm not sure what the status of mypy is here. (IIRC you did a PR that run checks even if previous checks failed, we could maybe backport that one)

I'm assuming the environment for the mypy checks on main is incorrect?

I need to understand the issues here and purpose of this more before merging. (As mentioned above, we have tended not to update mypy on the backport branches before and although only a dev dependency, we do list the change in the 1.5 release notes, so updating on 1.4.x could lead to confusion?)

**Comment by mroeschke** [comment]
This PR just aimed to align the CI changes between main and 1.4.x, namely ensuring all the jobs that utilize `environment.yml` (all non-testing related checks) include all the dependencies. Looks like in turn this changed typing validations due to bumped versions.

IMO maybe it's not worth back-porting this as it might risk change in behavior in 1.4.x, so closing

**Pull request closed without merging**
