### PR TITLE
REGR: Fix fastparquet 0.7.0 not being able to read a parquet file

### LINKED ISSUE #43075: BUG: pandas 1.3.2 incompatible with fastparquet 0.7.0
- [x] I have checked that this issue has not already been reported.
I've searched listing of open issues for "parquet" and found no matching entry describing this problem

- [x] I have confirmed this bug exists on the latest version of pandas.
Exists in 1.3.2

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.
Exists also in the master branch.
---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

df = pd.read_parquet("df.parquet")

```
This fails with the following stack trace:
```
In [8]: df = pd.read_parquet("df.parquet")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-3c208bf199a1> in <module>
----> 1 df = pd.read_parquet("df.parquet")

~/.virtual_envs/kapi2/lib/python3.9/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, storage_options, use_nullable_dtypes, **kwargs)
    493     impl = get_engine(engine)
    494
--> 495     return impl.read(
    496         path,
    497         columns=columns,

~/.virtual_envs/kapi2/lib/python3.9/site-packages/pandas/io/parquet.py in read(self, path, columns, storage_options, **kwargs)
    342             path = handles.handle
    343
--> 344         parquet_file = self.api.ParquetFile(path, **parquet_kwargs)
    345
    346         result = parquet_file.to_pandas(columns=columns, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'pandas_nulls'
```

#### Problem description

AFAICT, the root cause of the problem is the "api" version test in [io/parquet.py](https://github.com/pandas-dev/pandas/blob/master/pandas/io/parquet.py#L314) It needs to test `self.api.__version__ > Version("0.7.0")`. `ParquetFile` constructor in `fastparquet` 0.7.0 does not support  `pandas_nulls` argument. This argument is supported from version 0.7.1.

`fastparquet` 0.7.1 unfortunately does not build/install on darwin/arm64 (well, at least for me) :-/.

#### Expected Output
Obviously, the expected behavior is that the `DataFrame` is read from the file. 

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.9.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.5.0
Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.26.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.07.0
fastparquet      : 0.7.0
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by lithomas1**
- [x] closes #43075 
- [ ] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

My bad on this one, pinning one of the CI to ensure that this works.

### CODE REVIEW

**Comment by lithomas1** [comment]
Well this does work as expected, but I can't pin CI to fastparquet 0.7.0(I forgot that it breaks tests). I'll figure something out tomorrow(probably xfailing the tests).

**Comment by alimcmaster1** [comment]
> Well this does work as expected, but I can't pin CI to fastparquet 0.7.0(I forgot that it breaks tests). I'll figure something out tomorrow(probably xfailing the tests).

Do you want to merge master? Which tests need xfailing - not sure I understand why? thanks!

**Comment by lithomas1** [comment]
Just rebased. (Sorry for letting this one stale out. I completely forgot about it).



> > Well this does work as expected, but I can't pin CI to fastparquet 0.7.0(I forgot that it breaks tests). I'll figure something out tomorrow(probably xfailing the tests).
> 
> Do you want to merge master? Which tests need xfailing - not sure I understand why? thanks!

Sorry for being vague here. If we want to pin one of the CI's to make sure that this patch works, we'll have to xfail some tests. We need to do this, because fastparquet 0.7.0 broke some tests, and we didn't xfail them yet(Currently, CI is on 0.7.1 which fixed those tests and is green, so no-one bothered to xfail them for 0.7.0).

The other option is accepting this patch untested and I've verified it manually.

Thanks for the review, and sorry about causing the regression.

**Comment by alimcmaster1** [comment]
Looks like the code checks are failing please can you update the whatsnew

```
/home/runner/work/pandas/pandas/doc/source/whatsnew/v1.3.3.rst:36: WARNING: Bullet list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
```

**Comment by alimcmaster1** [comment]
> Just rebased. (Sorry for letting this one stale out. I completely forgot about it).
> 
> > > Well this does work as expected, but I can't pin CI to fastparquet 0.7.0(I forgot that it breaks tests). I'll figure something out tomorrow(probably xfailing the tests).
> > 
> > 
> > Do you want to merge master? Which tests need xfailing - not sure I understand why? thanks!
> 
> Sorry for being vague here. If we want to pin one of the CI's to make sure that this patch works, we'll have to xfail some tests. We need to do this, because fastparquet 0.7.0 broke some tests, and we didn't xfail them yet(Currently, CI is on 0.7.1 which fixed those tests and is green, so no-one bothered to xfail them for 0.7.0).
> 
> The other option is accepting this patch untested and I've verified it manually.
> 
> Thanks for the review, and sorry about causing the regression.

Understood thank you. Yes agree think we are unlikely to ever run CI against fastparquet 0.7.0 now that 0.7.1 is out and fixes the regressions. The usually pattern when making a change like this would be to pin a build temporarily, like you did, post a link on the PR of the desired tests passing in the pipeline then undo the pin.

Happy with the current solution - ping on green.

**Comment by jreback** [comment]
thanks @lithomas1

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
