### PR TITLE
DOC: removed versionadded <0.17 in doc strings

### PR DESCRIPTION
**Pull request by topper-123**
Cleaned up old references to when functionality was added.

See also #17442, #17442, #17404.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. ping  on green.

**Comment by topper-123** [comment]
It's green, I think? The failure doesn't seem to have anything to do with my pull request, right?

**Comment by gfyoung** [comment]
@topper-123 : Just ping us regarding unrelated failures, and we'll take care of it for you.

**Review by gfyoung — APPROVED** [review]

**Comment by gfyoung** [comment]
@topper-123 @jreback : Everything is green and good to go now.

**Comment by jreback** [comment]
thanks!

**Pull request merged**
