### PR TITLE
BUG: Changed function signature to replace args and kwargs

### LINKED ISSUE #53071: BUG: Add ``numeric_only`` to function signature of ``DataFrameGroupBy.cumprod`` and ``DataFrameGroupBy.cumsum`
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

Both methods support numeric only but it goes through args or kwargs, which is annoying signature wise.

### Issue Description

Add the keyword with the appropriate default

### Expected Behavior

See above

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

### PR DESCRIPTION
**Pull request by rsm-23**
- [ ] closes #53071
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests)
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by rhshadrach** [comment]
Changes look good, but are causing some uncaught warnings in the tests.

**Comment by rsm-23** [comment]
Getting this error: Is it safe to change the superclass definition? @rhshadrach 
`pandas/core/frame.py:11132: error: Signature of "cumsum" incompatible with supertype "NDFrame"  [override]
pandas/core/frame.py:11132: note:      Superclass:
pandas/core/frame.py:11132: note:          def cumsum(self, axis: Optional[Union[int, Literal['index', 'columns', 'rows']]] = ..., skipna: bool = ..., *args: Any, **kwargs: Any) -> Any
pandas/core/frame.py:11132: note:      Subclass:
pandas/core/frame.py:11132: note:          def cumsum(self, axis: Optional[Union[int, Literal['index', 'columns', 'rows']]] = ..., numeric_only: bool = ..., skipna: bool = ..., *args: Any, **kwargs: Any) -> Any`

**Comment by rhshadrach** [comment]
Yes - you'll also need to change the signature in NDFrame as well.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
