### PR TITLE
BLD: Refactor Dockerfile to not install dev enviornment on base

### LINKED ISSUE #48382: CI: Mambaforge upgrade base image to 3.10 in docker build
Mambaforge upgraded the python version to 3.10 in their image causing our builds to fail. The first affected version is 4.14.0-0

Failing build:
https://github.com/pandas-dev/pandas/runs/8171619523?check_suite_focus=true

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #48382 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

* Ensure packages are installed with `--no-install-recommends` and remove some unnecessary packages (saves ~0.7GB)
* Add smoke test to show `pandas-dev` environment is installed.

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]

**Comment by jbrockmendel** [comment]
docbuild fail looks like its happening on all PRs

```
Exception in /home/runner/work/pandas/pandas/doc/source/user_guide/timeseries.rst at block ending on line 2001
Specify :okexcept: as an option in the ipython:: block to suppress this message
  Cell In [360], line 2
    p == pd.Period("2012-01", freq="3M")
    ^
SyntaxError: invalid syntax

```

The preceeding line is `@okexcept`, which maybe should be `:okexcept:`? but the `@` isn't a recent change, so no idea why it just started complaining

**Comment by mroeschke** [comment]
Merging as the Docker build check passed: https://github.com/pandas-dev/pandas/runs/8232582540?check_suite_focus=true

**Comment by mroeschke** [comment]
@phofl do you think we should backport as you backported your pinning of this Docker image to 1.5?

This PR does a little more than just revert the pin.

**Comment by phofl** [comment]
+1 on backport in general

Different question: We have 2 environments inside the Dockerfile now, correct?
Are we ok with the increased size?

**Comment by mroeschke** [comment]
> We have 2 environments inside the Dockerfile now, correct?

Yes. Technically there is a workflow change for users that develop using the container (need to activate pandas-dev now). But IMO probably more sane for users to still have access to the `base` environment

> Are we ok with the increased size?

I personally don't use the container for development so I don't have a strong opinion. Since this isn't a production image per se, I think any size changes should be okay?

**Comment by phofl** [comment]
I am not using it either, shouldn't be an issue in general I think. It's not deployed on machines with limited disk space (probably :))

Can we promote this a bit more offensive? Whatsnew is the wrong place probably?

**Comment by mroeschke** [comment]
I can add a small whatsnew note. If we backport to 1.5, the additional instructions I added will be available by default once 1.5 is release as opposed to users needing to navigate to the `dev` tab.

**Review by phofl — APPROVED** [review]
Thx, can merge on greenish and backport to 1.5

**Comment by mroeschke** [comment]
Greenish, merging.

**Pull request merged**
