### PR TITLE
DEPR: Series/DataFrame/HDFStore.iteritems()

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
What's the reasoning to deprecate `iteritems()`? 

I suppose it is the duplication with `items()`? On the other hand, `iteritems()` also gives some consistency with `iterrows` and `itertuples`, which could be a reason in favor to rather keep `iteritems()`?

**Comment by mroeschke** [comment]
The duplication with `items()` was the motivation.

I think `iteritems()` was designed to mirror Python's dict API in 2.7, and since that was removed in PY3 I chose to remove `iteritems()`. (I encountered evidence of this when I tried deprecating `Series/DataFrame.keys`, and an internal path was flexibly accepting a dict-like API)

**Comment by jorisvandenbossche** [comment]
> when I tried deprecating `Series/DataFrame.keys`

Do you still have plans to propose that? Or the problems you encountered were sufficient to drop the idea? 
(if we would like to deprecate `.keys()` (I personally never use it), that would be another reason to keep `iteritems()`, I would say)

**Comment by mroeschke** [comment]
Yeah it was tricky to deprecate `keys()` since:

```
In [3]: pd.core.dtypes.inference.is_dict_like(Series([1]))
Out[3]: True

In [4]: pd.core.dtypes.inference.is_dict_like(DataFrame([1]))
Out[4]: True
```

in which `keys` is an attribute `is_dict_like` checks. So it may be API breaking / a lot of effort if keys were deprecated.

**Comment by jreback** [comment]
-1 on interitems this deprecated in python itself

**Pull request merged**
