### PR TITLE
BUG: GH14882 Incorrect index label displayed on MultiIndex DataFrame

### LINKED ISSUE #14882: Incorrect index label displayed on MultiIndex DataFrame
I have a DataFrame with a hierarchical index as follows:

```python
MultiIndex(levels=[[30, 40, 50], [6, 12, 24], ['MRIgFUS', 'ablation', 'hysterectomy', 'iud', 'myomectomy', 'none', 'uae']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2], [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]],
           names=['age', 'followup', 'next intervention'])
```

Notice in particular the values of the first two levels, and that they are balanced in the labels. However, the display of the table is incorrect. Here is what it looks like:

Notice the second label of the first two levels of the hierarchical index are repeated (40 and 40 instead of 40 and 50, and 12 and 12 instead of 12 and 24).

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 16.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.1
nose: None
pip: 9.0.1
setuptools: 31.0.1
Cython: 0.25.2
numpy: 1.11.2
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by Dr-Irv**
- [x] closes #14882 
 - [x] tests added / passed
   Add `tests/formats/test_format.py:TestDataFrameFormatting.test_to_html_multiindex_odd_even_truncate`
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
hmm, this seems to duplicate lots of code. I think a better soln is to borrow what @TomAugspurger 
did in pandas.formats.style where this all works as expected (maybe need to move some code from there to a more common location, e.g. ``_get_level_lengths`` though)

**Comment by jreback** [comment]
@Dr-Irv that's the point, you may need to adjust ``.style`` and/or to_html to fix this. otherwise just creating even more code.

**Comment by Dr-Irv** [comment]
@jreback The current PR fixes the truncation issue for `to_html`. Shouldn't the lack of support for `display.max_rows` in `.style` be a separate issue?  Then there is how to have code that is not duplicated between how `to_html` does things and how `.style` does things (and I'm guessing you've discussed having the `.style` implementation replace the current `to_html` implementation in the future??).

**Comment by jreback** [comment]
@Dr-Irv yes, my point is that rather than fixing 'to_html', I would rather try to write new code in .style and just fix the issue that way. otherwise this will just go on, creating more and more code. 

IIRC @TomAugspurger didn't think this was very difficult

**Comment by Dr-Irv** [comment]
@jreback I guess we should hear what @TomAugspurger has to say? You're suggesting that the implementation in `.style` will eventually replace the current `to_html` implementation, if I understand you correctly. IMHO, that's fine for the future, but at least for now, this PR can fix the bug, and then getting `max_rows` support in `.style`, as well as removing the current `to_html` implementation to use `.style` instead (which reduces the size of the code) should be handled as a separate issue.

How about this idea. You merge in this PR, and I'll create a new issue for `max_rows` and `max_columns` support in `.style`, and I can separately work on figuring that out. And maybe there should be another issue to reduce code size by removing the current `to_html` code and using `.style` instead??

**Comment by jorisvandenbossche** [comment]
Didn't look at the code, but regarding the "implement in `style` or not" issue: IMO as long as `.style` has not replaced our default html formatter, separate fixes to the html formatter should be OK. As fixing it in `.style` will not yet fix our notebook repr.

I don't know if we are ready for such a switch (@TomAugspurger ? do you have an idea on what would be the hurdles? missing features?), but I would see this as a separate issue.

**Comment by TomAugspurger** [comment]
Yes, separate issues.

I don't think there are any blockers for rewriting to_html with the style stuff, other than formally adding jinja2 as a dependency.

**Comment by jreback** [comment]
The issue I have with this is we are adding lots of code (with if-thens), which is simply going to be ripped out when this is converted to ``.style``.

So, is it easier to convert to ``.style``, then fix this?

**Comment by jorisvandenbossche** [comment]
> The issue I have with this is we are adding lots of code (with if-thens), which is simply going to be ripped out when this is converted to .style.

Not only those added lines, but the full html formatting code will be ripped out, which is a lot longer as the added lines.

> So, is it easier to convert to .style, then fix this?

The thing is, converting the repr to be based on `.style` is a larger PR I think. And indeed this would make this fix not needed. But the work still has to be done. And do we have the guarantee that someone will do it before 0.20? 
Until then, this PR fixes a very obvious bug (totally wrong displayed index)

> I don't think there are any blockers for rewriting to_html with the style stuff, other than formally adding jinja2 as a dependency.

@TomAugspurger Does `style` already support truncated output? (I don't see a way to get this)

Is `jinja2` in a possibly problematic dependency?

**Comment by TomAugspurger** [comment]
> The thing is, converting the repr to be based on .style is a larger PR I think

Agreed, which means I'm +1 for merging this PR, even if it's obsolete in the near future. In any event, the tests from this PR would be great to have.

> And do we have the guarantee that someone will do it before 0.20?

I'm not going to have time to work on it before 0.20.

> @TomAugspurger Does style already support truncated output?

No, not yet. It wouldn't be terribly difficult code-wise. I just don't know if it's appropriate for `.style` (what if you highlihgt the max, and the max is in the truncated section? But that's a separate issue).

> Is jinja2 in a possibly problematic dependency?

I'm OK with it (and its dependency on MarkupSafe), but willing to be convinced otherwise.

**Comment by jreback** [comment]
ok then. @jorisvandenbossche or @TomAugspurger pls merge when satisfied

though I would add a big TODO in general on the HTMLFormatter class (about this being converted eventually).

**Comment by jorisvandenbossche** [comment]
Seems we have already an issue for this: https://github.com/pandas-dev/pandas/issues/11700. Will move some of the discussion from here over there

**Comment by jreback** [comment]
thanks @Dr-Irv !

thought we had merged this a while back........

**Pull request closed without merging**
