### PR TITLE
Remove SKIP summary from CI logs

### PR DESCRIPTION
**Pull request by WillAyd**
I think this was @rhshadrach idea originally. This currently generates about 3k lines of SKIPs in the CI output, which can be mildly annoying to have to scroll through every log

### CODE REVIEW

**Review by rhshadrach — COMMENTED** [review]
@lithomas1 pointed out you can just search for "failure" in the log and it jumps to the line I want. This works well and I've been doing it ever since. Still, if we think no one finds this generally useful (and I imagine that's the case), definitely very positive here.

**Comment by lithomas1** [comment]
+1 on this - sometimes the large amount of output does make my logs lag.

**Comment by lukemanley** [comment]
+1 as well

**Review by mroeschke — APPROVED** [review]
It was useful for me on occasion when investigating fixable skips, but I can do that manually once in a while

**Comment by mroeschke** [comment]
Thanks @WillAyd

**Pull request merged**
