### PR TITLE
BUG: Should allow numeric mysql table/column names

### LINKED ISSUE #10255: to_sql : MySQL identifier cannot be entirely numeric
Reported at StackOverflow: http://stackoverflow.com/questions/30586292/valueerror-mysql-identifier-cannot-be-entirely-numeric-with-pandas-to-sql

MySQL supports numeric identifiers (if quoted) (http://dev.mysql.com/doc/refman/5.0/en/identifiers.html) 
@artemyk Was there a reason we explicitely disallowed this? (https://github.com/pydata/pandas/blob/v0.16.1/pandas/io/sql.py#L1287)

### PR DESCRIPTION
**Pull request by artemyk**
Closes #10255 , alternative to #10262 .

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Looks good! 
Only, seems it cannot be merged, can you rebase on the latest master? 
Will then merge when travis is green.

**Comment by artemyk** [comment]
@jorisvandenbossche conflict in whatsnew doc... should be fixed now.

**Comment by jreback** [comment]
pls rebase on master and repush had an issue with some builds

**Comment by jorisvandenbossche** [comment]
@artemyk Thanks!

**Pull request merged**
