### PR TITLE
REF: make maybe_cast_result_dtype a WrappedCythonOp method

### PR DESCRIPTION
**Pull request by jbrockmendel**
Abstraction-wise, this is a much better place for it.

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase

**Comment by jbrockmendel** [comment]
rebased + greenish

**Comment by jreback** [comment]
can you merge master (just because merge lots of groupby things)

**Comment by jbrockmendel** [comment]
hah i was just about to comment "no merge conflict".  will do.

**Comment by jbrockmendel** [comment]
rebase + greenish (just the ResourceWarning that apparently we _still_ arent suppressing and the pyarrow stuff thats failing everywhere)

**Pull request merged**
