### PR TITLE
Backport PR #48398 on branch 1.5.x (WARN: Avoid FutureWarnings in tests)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #48398: WARN: Avoid FutureWarnings in tests

### CODE REVIEW

**Comment by datapythonista** [comment]
I can't reproduce this locally, and the error in the CI doesn't seem to make a lot of sense. @phofl any idea what can be wrong? Doesn't seem related to your changes, but just in case.

**Comment by phofl** [comment]
This was caused by the ipython upgrade and fixed yesterday (already on 1.5.x)

**Comment by datapythonista** [comment]
Great, thanks for the info. I updated this with the latest 1.5.x changes, let's see if this passes the CI now.

**Review by datapythonista — APPROVED** [review]
Yep, the docs build is working as expected.

**Comment by phofl** [comment]
Please don't merge yet

**Comment by phofl** [comment]
We probably don't want to merge the update change, but another change went missing here that we should back in. Will push this after #48468 is merged

**Comment by phofl** [comment]
cc @mroeschke I'd like to merge this part of the initial pr into 1.5.x, already remove the other part

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
