### PR TITLE
BUG: Series[object].unstack preserve object dtype

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

Sits on top of #44593

### CODE REVIEW

**Comment by jreback** [comment]
looks good if u can add a whatsnew

**Comment by TomAugspurger** [comment]
@jbrockmendel can you confirm whether the slowdown in https://pandas.pydata.org/speed/pandas/#reshape.ReshapeExtensionDtype.time_transpose?python=3.8&Cython=0.29.24&p-dtype='datetime64%5Bns%2C%20US%2FPacific%5D'&commits=8374c656 pointing to this is expected? I think it is, but wanted to confirm.

**Comment by jbrockmendel** [comment]
OK I think #44593 caused us to split a 2D DatetimeArray into column arrays, which would account for the slowdown, but is not intended.  Will look into a fix.

**Comment by jbrockmendel** [comment]
Perf regression fixed in #44724

**Pull request merged**
