### PR TITLE
DOC: collapse subpages in sidebar for API reference docs

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
The latest version of the theme added the capability to collapse/expand subsections in the sidebar (without directly navigating to the page), see eg the new dropdown arrows on https://pandas.pydata.org/docs/dev/getting_started/index.html

But, an unintended consequence is that the build takes*much* longer (this the reason that the Web / Doc CI build is now always slow on the current open PRs), and this is especially due to our API reference page, which has more than 1000 subpages, and all those pages now have the full navigation structure to all other 1000 pages. 

In this PR I am trying to override the base theme template for the sidebar navigation, to not do this for the reference section of our docs.

xref https://github.com/pydata/pydata-sphinx-theme/issues/364

### CODE REVIEW

**Comment by jbrockmendel** [comment]
cc @datapythonista

**Comment by datapythonista** [comment]
Looks like this speeds up to build from 75m to 35m. Having the dropdowns is nice, but I think this makes sense.

**Comment by jreback** [comment]
thanks @jorisvandenbossche

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
