### PR TITLE
DOC: add plt.show so that the plot will show, along with note about p…

### LINKED ISSUE #43560: DOC: plot doesn't show in some environments
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/user_guide/10min.html#plotting

### Documentation problem

When following the tutorial, plot may not appear, depending on the environment.  Some environments require `plot.show`, some will require `plot.savefig`.
PR #43544 adds a very brief explanation.

### Suggested fix for documentation

If running under Jupyter Notebook, the plot will appear on `~ts.plot`.  Otherwise use [`matplotlib.pyplot.show`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.show.html) to show it or [`matplotlib.pyplot.savefig`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.savefig.html) to write it to a file.

   plt.show();

### PR DESCRIPTION
**Pull request by woodvi**
…lt.show, plt.savefig and Jupyter Notebook.

- [x] closes #43560
- [ ] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by mzeitlin11 — COMMENTED** [review]
Thanks for the pr @woodvi! Is there an issue associated with this? Can you also please post a screenshot of the rendered docs after this change?

**Comment by woodvi** [comment]
image
have added issue #43560 for this, and referenced this PR

**Comment by jreback** [comment]
@mzeitlin11 over to you

**Review by mzeitlin11 — APPROVED** [review]
Thanks @woodvi!

**Pull request merged**
