### PR TITLE
replace NotImplementedError with AttributeError

### LINKED ISSUE #31474: Not supported for DataFrames Exception triggered by a simple inspect.getmembers() call on a DataFrame
#### Code Sample, a copy-pastable example if possible

```python
import inspect
import pandas as pd
df = pd.DataFrame()
try:
   members = inspect.getmembers(df)
except Exception as e:
   print(e)

```
#### Problem description

A "**Not supported for DataFrames Exception**" is triggered by a simple inspect.getmembers() call on a DataFrame instance.  There are some useful libraries like the Python 'fire' library which are disabled by this bug, which was not present in Pandas Release 0.24.2 but emerged in 0.25.0

#### Expected Output

A list of DataFrame members (without crashing)

#### Output of ``pd.show_versions()``

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-26-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

### PR DESCRIPTION
**Pull request by RichardBruskiewich**
Fixes Python inspection of members - bug reported in https://github.com/pandas-dev/pandas/issues/31474

- [ ] closes #31474
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
i think TypeError would be more appropriate

regardless, needs tests

**Comment by WillAyd** [comment]
Given the purpose of this method I don’t think it makes sense to change this. What issue is this fixing exactly?

**Comment by WillAyd** [comment]
I am -1 on changing anything here. This looks to just be a bug with Python:

https://bugs.python.org/issue35108

So should be fixed upstream if needed

**Comment by RichardBruskiewich** [comment]
The missing function needs to throw an AttributeError to avoid breaking the Python built-in "inspect" self reflection on the class which fails obscurely since the given method is a member of the DataFrame class but previously simply throws an NotImplementedException exception rather than indicating that it is a missing member (function attribute) of the class.

I attempted to cover the missing method with a multi-inheritance "DataFrame" Exception to deal with the polymorphism of failure modes here (also inherited from the TypeError in case it is deemed valid in this context).

Regarding tests, @jbrockmendel , I leave it to the Pandas gurus here. The proposed change is a small one which fixes the above unfriendly interaction of DataFrames with inspect.getmembers(). If you need a test to code that, there is a snippet of code at the top of https://github.com/pandas-dev/pandas/issues/31474

**Comment by RichardBruskiewich** [comment]
I have trouble considering this a Python bug. The previous Pandas 0.24.3 worked fine. 0.25.1 doesn't.

If you single step down inside the Python `inspect` module, you'll find it expects to trap `AttributeError`, not `NotImplementedError` exceptions for any symbol defined in the module dictionary as a member. The Python inspect module has been around since release 2.1 of Python...

**Comment by MarcoGorelli** [comment]
> Regarding tests, @jbrockmendel , I leave it to the Pandas gurus here.

Thanks for the info you provided, but in general pull requests aren't accepted without tests (unless they're just fixing docstrings / typos), see the [contributing guide](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#writing-tests)

> 
> pandas is serious about testing and strongly encourages contributors to embrace test-driven development (TDD). This development process “relies on the repetition of a very short development cycle: first the developer writes an (initially failing) automated test case that defines a desired improvement or new function, then produces the minimum amount of code to pass that test.” So, before actually writing any code, you should write your tests. Often the test can be taken from the original GitHub issue. However, it is always worth considering additional use cases and writing corresponding tests.
> 
> Adding tests is one of the most common requests after code is pushed to pandas. Therefore, it is worth getting in the habit of writing tests ahead of time so this is never an issue.

**Comment by jorisvandenbossche** [comment]
@RichardBruskiewich would it also fix your usecase if we simply raise a TypeError? (the custom error subclassing from both NotImplementedError, TypeError and AttributeError seems a bit strange)

**Comment by TomAugspurger** [comment]
I'd also like to see this solved upstream. I'll try to take a bit of time today. Doesn't seem too bad.

**Comment by TomAugspurger** [comment]
https://github.com/python/cpython/pull/18330 for reference.

**Comment by RichardBruskiewich** [comment]
> 
> 
> @RichardBruskiewich would it also fix your usecase if we simply raise a TypeError? (the custom error subclassing from both NotImplementedError, TypeError and AttributeError seems a bit strange)

Alas, not it would not suffice to use 'TypeError' since the core behaviour of inspect.getmembers() is to trap AttributeError exceptions while it iterates through attributes. See the code snippet in between 345 and 362 in https://github.com/python/cpython/blob/master/Lib/inspect.py.

 If Pandas would simply raise the AttributeError either in lieu of the NotImplementedError or alongside (see my attempt to create a polymorphic Exception class by parental inheritance), then inspect would work as expected.

My problem is that at least one other significant third party library - the Python (Google-hosted) Fire CLI library - applies inspect.getmembers to interrogate the data types flowing through its CLI processing mechanism.  See line 635 inhttps://github.com/google/python-fire/blob/master/fire/core.py.

It's an "all or none" process which currently propagates the NotImplementedError exception which means the code fails completely with Pandas 0.25.1 version DataFrames (but not with the earlier 0.24.2 release) because of this flaw in the code, wherever we collectively decide to place the blame.

I know that this feels like a hack and a bandaid solution, but when I came across the idea of a polymorphic Exception definition, it seemed acceptable to "solve" the issue this way. i.e.

class DataFrameError(NotImplementedError, AttributeError, TypeError):
    pass
...
def theNaughtyMethod:
    raise DataFrameError("I'm being cantankerous!")

Methods throwing more than one class of exception are not unheard of in the world of computing, although of course, each exception is generally considered to convey a unique failure condition; however, in this case, it is simply a matter of getting the code to be a good citizen in the wild west of computing, especially when the sheriff in town happens to be called Python and different Deputy libraries really want to use Python methods to interrogate Pandas.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger Contribution to CPython, cool! :)

Now, personally, I wouldn't mind changing the error in pandas, if that solves some downstream annoyances now (the python fix will only be available in a further future). 

In the end, do we really care which exception is being raised? In principle, this should never be called, or the user should never see this error, IIUC?

**Comment by TomAugspurger** [comment]
Right, `DataFrame._constructor_expanddim` should never be called in principle. So if we're going for 100% correctness, an `AssertionError` might be more appropriate.

That said, since this is never called (in theory) I don't think we care whats returned. I'd be fine with just returning `None`, or perhaps something like

```python
@property
def _constructor_expanddim(self):
    def constructor(*args, **kwargs):
        raise AssertionError("Not supported for DataFrames!")
    return constructor
```

to please mypy.

**Comment by TomAugspurger** [comment]
@RichardBruskiewich for a test, I think something simple like 

```python
def test_get_members():
    inspect.getmembers(pd.DataFrame())
```

will suffice. That can go somewhere like `pandas/tests/frame/test_subclass.py`. We may need a similar fix for Series and constructor_sliced.

**Comment by jorisvandenbossche** [comment]
I think your code example with returning a function that raises an error is actually a good idea, that also maps with the expected return value.

**Comment by TomAugspurger** [comment]
@RichardBruskiewich do you have time to update this PR with something like https://github.com/pandas-dev/pandas/pull/31549#issuecomment-581579126?

**Comment by jbrockmendel** [comment]
> medicine for the US National Institutes of Health

While I agree with others that this should be fixed upstream, I find myself motivated to help out with this short-term.

@RichardBruskiewich Is Series._constructor_sliced also an issue, or just DataFrame._constructor_expanddim?

**Comment by RichardBruskiewich** [comment]
Hello everyone,
Going back to the original bug report:

**Problem description**
A "Not supported for DataFrames Exception" is triggered by a simple inspect.getmembers() call on a DataFrame instance. There are some useful libraries like the Python 'fire' library which are disabled by this bug, which was not present in Pandas Release 0.24.2 but emerged in 0.25.0

Whatever solves this problem is fine by me. I need to mention now that the code I wrote that depended on Python Fire ( a Google hosted project?) simply wouldn't work unless I pinned it to 0.24.2.

That same project didn't get funded for further development this spring, so the code base is frozen for posterity, and I've moved onto other funded projects. Thus, my own personal motivation to get the bug fixed has faded a bit.  However, it does seem to me that such a major impedance mismatch between Pandas and such a useful Google-hosted CLI library should somehow be mitigated. 

Somebody with more intimate knowledge about these code bases: please simply do the needful!

**Comment by RichardBruskiewich** [comment]
> ```python
> def test_get_members():
>     inspect.getmembers(pd.DataFrame())
> ```

Added this one test to the patch-1 pull request submitted

**Comment by jreback** [comment]
closing in favor of #33628

**Comment by TomAugspurger** [comment]
@RichardBruskiewich I think that https://github.com/pandas-dev/pandas/pull/33628 has the preferred approach.

That was just merged to master, if you want to try it out. I don't think the changes here should be needed any more.

**Comment by RichardBruskiewich** [comment]
> @RichardBruskiewich I think that #33628 has the preferred approach.
> 
> That was just merged to master, if you want to try it out. I don't think the changes here should be needed any more.

Thank you Tom, for the update. Sorry that I lacked the experience with the code base and time to clean up my own recommended patches. I'll see if the latest master works in my Fire infested project. Sincere regards, R

**Pull request closed without merging**
