### PR TITLE
CLN: missing f for f-string

### PR DESCRIPTION
**Pull request by twoertwein**

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jreback** [comment]
wonder if there is a way to actually check for this (out of scope here).

cc @MarcoGorelli would be a nice plugin for style checking.

**Comment by MarcoGorelli** [comment]
I think pylint detects this... might be worth bringing some of its (less pedantic) rules

**Comment by twoertwein** [comment]
https://github.com/MichaelKim0407/flake8-use-fstring That's how I found it but we have many false positives because of the shared documentation using "{}"

**Pull request merged**
