### PR TITLE
DEPR: tz-aware Series/DatetimIndex.__array__ returns an object array of Timestamps

### LINKED ISSUE #24716: DataFrame.to_xarray produces FutureWarning for DatetimeTZ data
```python
In [16]: df = pd.DataFrame({"A": pd.date_range('2000', periods=12, tz='US/Central')})

In [17]: df.to_xarray()
/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/xarray/core/dataset.py:3111: FutureWarning: Converting timezone-aware DatetimeArray to timezone-naive ndarray with 'datetime64[ns]' dtype. In the future, this will return an ndarray with 'object' dtype where each element is a 'pandas.Timestamp' with the correct 'tz'.
        To accept the future behavior, pass 'dtype=object'.
        To keep the old behavior, pass 'dtype="datetime64[ns]"'.
  data = np.asarray(series).reshape(shape)
Out[17]:
<xarray.Dataset>
Dimensions:  (index: 12)
Coordinates:
  * index    (index) int64 0 1 2 3 4 5 6 7 8 9 10 11
Data variables:
    A        (index) datetime64[ns] 2000-01-01T06:00:00 ... 2000-01-12T06:00:00
```

@shoyer thoughts on how to resolve this? We can continue dropping the timezone and passing datetime64[ns], break API and return an object-dtype array of timestamps, or add a parameter so that the user can control this.

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #24716
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Review by jreback — APPROVED** [review]
lgtm. merge on green.

**Comment by jbrockmendel** [comment]
IIRC the places where i see this warning are in xarray and matplotlib tests.  should we check with them to make sure they're ready for this?  cc @shoyer, not sure who for matplotlib

**Comment by jbrockmendel** [comment]
closes #24716?

**Comment by mroeschke** [comment]
Yup, looks like it.

**Comment by jreback** [comment]
I guess waiting on xarray / mpl, can you open an issue on each of those trackers.

**Comment by jbrockmendel** [comment]
Does/should this affect `np.array(datetimeindex)`?

**Comment by TomAugspurger** [comment]
Yeah, https://github.com/pandas-dev/pandas/pull/30516/files#diff-b8a7b94d7e2ed5f7f109922e7bd3480cL313.

FWIW, I don't think we need to wait on xarray or matplotlib. These are warnings that should be seen by the user, and they have actions they can take already to avoid them.

**Review by TomAugspurger — APPROVED** [review]

**Comment by shoyer** [comment]
+1 for xarray -- this is something that users can already deal with as
needed

**Comment by jreback** [comment]
thanks @mroeschke

**Pull request merged**
