### PR TITLE
CI/TST: update pyarrow pin in windows-3.8 env / fix failing parquet test on windows

### LINKED ISSUE #45344: TST: error in parquet tests on windows with new pyarrow exception
see https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=72195&view=logs&j=9dd5e044-6afa-5be6-cb56-860f1ee82b31&t=d3ae057b-d0af-59ce-6e4c-b69ef3739701

```
================================== FAILURES ===================================
__________________________ test_arrowparquet_options __________________________
[gw1] win32 -- Python 3.8.12 C:\Miniconda\envs\pandas-dev\python.exe

fsspectest = <pandas.conftest.fsspectest.<locals>.TestMemoryFS object at 0x00000236F72FED90>

    @td.skip_if_no("pyarrow")
    def test_arrowparquet_options(fsspectest):
        """Regression test for writing to a not-yet-existent GCS Parquet file."""
        df = DataFrame({"a": [0]})
>       df.to_parquet(
            "testmem://test/test.csv",
            engine="pyarrow",
            compression=None,
            storage_options={"test": "parquet_write"},
        )

pandas\tests\io\test_fsspec.py:167: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas\util\_decorators.py:207: in wrapper
    return func(*args, **kwargs)
pandas\core\frame.py:2842: in to_parquet
    return to_parquet(
pandas\io\parquet.py:420: in to_parquet
    impl.write(
pandas\io\parquet.py:195: in write
    self.api.parquet.write_table(
C:\Miniconda\envs\pandas-dev\lib\site-packages\pyarrow\parquet.py:1673: in write_table
    with ParquetWriter(
C:\Miniconda\envs\pandas-dev\lib\site-packages\pyarrow\parquet.py:544: in __init__
    filesystem, path = resolve_filesystem_and_path(where, filesystem)
C:\Miniconda\envs\pandas-dev\lib\site-packages\pyarrow\filesystem.py:455: in resolve_filesystem_and_path
    return _ensure_filesystem(filesystem), path
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fs = <pandas.conftest.fsspectest.<locals>.TestMemoryFS object at 0x00000236F72CAE80>

```

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes #45344

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
So updating pyarrow from 1.0 to 2.0 seems to highlight some other bugs ..

**Comment by jbrockmendel** [comment]
> So updating pyarrow from 1.0 to 2.0 seems to highlight some other bugs ..

Something like this seems to happen frequently.  I've got an under-utilized ubuntu machine that i could set up with 'tox' to run the tests daily(ish) with a thorough(ish) matrix of pyarrow versions. Would that be useful?  If this is windows-specific then never mind.

**Comment by jreback** [comment]
closing in favor of #45354 which is already merged & backported

**Comment by jorisvandenbossche** [comment]
> closing in favor of #45354 which is already merged & backported

#45354 is only xfailing the test, while this PR is an initial attempt to actually fix #45344 (which is still open)

> Something like this seems to happen frequently. I've got an under-utilized ubuntu machine that i could set up with 'tox' to run the tests daily(ish) with a thorough(ish) matrix of pyarrow versions. Would that be useful? If this is windows-specific then never mind.

I don't think it is windows-specific. But I also don't think it's necessarily needed for you to set up separate testing against more versions of pyarrow (or at least it _should_ not be needed, we should "simply" do this better on our CI). I would first try to diversify the version in our own CI matrix (eg we can already reduce the number of builds that pins against pyarrow=1.0.1).

**Comment by jreback** [comment]
this looks good thanks @jorisvandenbossche

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by jreback** [comment]
@jorisvandenbossche if you wouldn't mind pushing the manual backport here

**Comment by jorisvandenbossche** [comment]
-> https://github.com/pandas-dev/pandas/pull/45450

**Pull request merged**
