### PR TITLE
BUG: Switch more size_t references to int64_t

### LINKED ISSUE #20785: heap corruption in read_csv on 32-bit big-endian architectures
While building pandas 0.22.0 for 32-bit big-endian architectures, the test suite crashes in **TestMultiLevel::test_unstack_odd_failure** with various errors:
```
realloc(): invalid next size
malloc(): smallbin double linked list corrupted
Segmentation fault
corrupted double-linked list
```
This happened to be the first test that calls **read_csv**, and I could reproduce this in the REPL by simply doing:
```
import pandas as pd
df = pd.read_csv('data.csv')
```
I narrowed it down to https://github.com/pandas-dev/pandas/commit/8d7d3fb545b4273cf9d1a61bf7ea3bfdde8a1199 and found https://github.com/pandas-dev/pandas/issues/17063 describing a similar problem introduced by the same commit affecting other 32-bit architectures.

### PR DESCRIPTION
**Pull request by ginggs**
closes #20785

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
this looks fine. can u add a whatsnew note (u can put in bug fix io section)

**Comment by ginggs** [comment]
All tests OK on this side, and I added a whatsnew note.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
look good. ping on green.

**Comment by ginggs** [comment]
ping

**Comment by jreback** [comment]
thanks @ginggs

**Pull request merged**
