### PR TITLE
Bug in to_json causing segfault with a CategoricalIndex (GH #10317)

### PR DESCRIPTION
**Pull request by evanpw**
Fixed GH #10317
Stole tests from #10321

### CODE REVIEW

**Comment by jreback** [comment]
oh, see you did already!

**Comment by jreback** [comment]
creating the tests was the hardest part actually :)

**Comment by evanpw** [comment]
I agree! Glad I didn't have to.

**Comment by jreback** [comment]
thanks @evanpw !

**Comment by jreback** [comment]
FYI, https://github.com/pydata/pandas/commit/da3e0d1c9778ac39d1daec779d6defa322ed37b4

windows didn't like the redeclaration; gcc was ok with it...weird

**Pull request merged**
