### PR TITLE
BUG 1.4: do not suppress errors when closing file handles

### LINKED ISSUE #47136: BUG: Pandas should not swallow exceptions when close()ing a write handle
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
pd.to_pickle(large_python_object, '/mnt/some_nfs_mount')
```

### Issue Description

`IOHandles.close` (https://github.com/pandas-dev/pandas/blob/v1.4.2/pandas/io/common.py#L119) throws away any exceptions raised by calling close() on the handle it is managing. When writing to certain file systems (in particular NFS mounts), write errors caused by e.g. runnning out of disk space may not be raised at the point you actually do a `write()` but rather get deferred to the `close()`. Therefore, by ignoring exceptions raised by `close()` it's possible for a Pandas IO utility function to silently write a truncated file.

### Expected Behavior

Exceptions raised by `close()` should be propagated to the user for appropriate handling. You may optionally want to continue to ignore exceptions raised by handles open in read mode.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.18.0-305.19.1.el8_4.x86_64
Version          : #1 SMP Wed Sep 15 15:39:39 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.3.5
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : 7.31.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2022.01.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.0
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 4.0.1
pyxlsb           : None
s3fs             : 2022.01.0
scipy            : 1.7.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.20.1
xlrd             : 2.0.1
xlwt             : None
numba            : 0.54.1
</details>

### PR DESCRIPTION
**Pull request by twoertwein**
xref https://github.com/pandas-dev/pandas/pull/47153#discussion_r884156873, closes https://github.com/pandas-dev/pandas/issues/47136

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
@twoertwein can you open against main instead and we will merge this first, then merge main on the other PR

**Comment by twoertwein** [comment]
> @twoertwein can you open against main instead and we will merge this first, then merge main on the other PR

These changes will fail on main because `_BytesTarFile` was causing errors. I'm not entirely sure why, maybe `super().close()` will call close on both superclasses which then caused a ValueError.

**Comment by simonjayhawkins** [comment]
right. so this PR is effectively a manual partial backport of https://github.com/pandas-dev/pandas/pull/47153 (opened prematurely) and not broken off from #47153

I suppose that's OK (although not how we normally do things) if there are other issues on main.

the other PR should be merged first then?

**Comment by twoertwein** [comment]
> right. so this PR is effectively a manual partial backport of #47153 (opened prematurely) and not broken off from #47153

#47153 also de-duplicates the write buffer across `_BytesTarFile` and `_BytesZipFile` which is technically not needed for this bug.

> the other PR should be merged first then?

When seeing it as a backport, it would make sense to merge the other one first.

**Comment by twoertwein** [comment]
maybe a cleaner option: I do not remove the try-catch in #47153 (just fix the underlying bug+cleanup), open this PR against main after #47153 is merged

**Comment by twoertwein** [comment]
> maybe a cleaner option: I do not remove the try-catch in #47153 (just fix the underlying bug+cleanup), open this PR against main after #47153 is merged

I removed the bug fix in #47153

**Comment by simonjayhawkins** [comment]
> maybe a cleaner option: I do not remove the try-catch in #47153 (just fix the underlying bug+cleanup), open this PR against main after #47153 is merged

sgtm

**Comment by twoertwein** [comment]
Closing this one as I don't know how to change the target branch. Opened #47165.

**Pull request closed without merging**
