### PR TITLE
CLN: MultiIndex._union

### PR DESCRIPTION
**Pull request by lukemanley**
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.

No need to special-case missing/NA following the fix in #49442

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
We have tests covering this?

Looks good otherwise

**Comment by lukemanley** [comment]
> We have tests covering this?

yes, a handful in pandas/tests/indexes/multi/test_setops.py:
test_union_with_missing_values_on_both_sides
test_union_nan_got_duplicated
test_union_keep_ea_dtype_with_na
test_union_with_na_when_constructing_dataframe

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
cc @lukemanley The Minimum versions failure could be legit, could you have a look? Might be possible that the PerformanceWarning is avoided now

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @lukemanley

**Pull request merged**
