### PR TITLE
Add pandas blog to feed

### PR DESCRIPTION
**Pull request by TomAugspurger**
I don't think this needs to be backported.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
FYI @datapythonista

**Comment by jbrockmendel** [comment]
i get a 404 when i visit the new URL.  is that what this PR fixes?

**Comment by datapythonista** [comment]
Looks good, I guess you're setting up blog.pandas.io as the domain for the blog? I think the web build will fail if we merge this before the new domain is working. 

There was some discussion where some people wanted to keep using the old domain and discard pandas.io,not sure if a final decision was made.

**Comment by TomAugspurger** [comment]
Oh, that's the URL from the footer on http://dev.pandas.io/pandas-blog/.

So the right one at the current URL would be http://dev.pandas.io/pandas-blog/feeds/all.atom.xml.

**Review by datapythonista — APPROVED** [review]
Not sure if dev.pandas.io should be the final domain for the blog, but let's get this merged, and we'll see later how to best organize everything.

**Comment by TomAugspurger** [comment]
The npdev failure is fixed on master / 1.0.x.

**Pull request merged**
