### PR TITLE
Fix numpydev CI failure

### PR DESCRIPTION
**Pull request by WillAyd**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM pending green

**Comment by WillAyd** [comment]
Adding to 1.1.1 as I think should backport - @TomAugspurger or @simonjayhawkins good to merge?

**Comment by TomAugspurger** [comment]
Yep to backport, whenever you're ready.

**Comment by simonjayhawkins** [comment]
> Adding to 1.1.1 as I think should backport - @TomAugspurger or @simonjayhawkins good to merge?

aren't the same tests failing or am I missing something.

we only have Travis running on backport so could wait to backport till after the 2 PRs activating azure and github actions are merged.

**Comment by WillAyd** [comment]
@simonjayhawkins whoops good point. Using the github app misread the checks. Will take a look in a bit

**Pull request closed without merging**
