### PR TITLE
COMPAT: avoid invalid buffer comparisions

### LINKED ISSUE #18064: ERR: lib.is_xyz_array errors, some ignored
See #18054 

```
In [1]: import pandas as pd
In [2]: import numpy as np
In [3]: from pandas._libs import lib
In [4]: values = np.array([2, 1, 1, 2], dtype=np.int64)    # The relevant arg in TestMergeCategorical.test_other_columns
In [5]: lib.is_bool_array(values)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
Exception ValueError: "Buffer dtype mismatch, expected 'Python object' but got 'long'" in 'pandas._libs.lib.is_bool_array' ignored
Out[5]: False

In [7]: lib.is_bool_array(values.astype(bool))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Does not understand character buffer dtype format string ('?')
Exception ValueError: "Does not understand character buffer dtype format string ('?')" in 'pandas._libs.lib.is_bool_array' ignored
Out[7]: False

In [8]: lib.is_datetime_array(values)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-a5b7fc4b6701> in <module>()
----> 1 lib.is_datetime_array(values)

pandas/_libs/src/inference.pyx in pandas._libs.lib.is_datetime_array()

ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'

In [9]: lib.is_datetime_array(values.astype('datetime64[ns]'))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-0c109014e134> in <module>()
----> 1 lib.is_datetime_array(values.astype('datetime64[ns]'))

pandas/_libs/src/inference.pyx in pandas._libs.lib.is_datetime_array()

ValueError: cannot include dtype 'M' in a buffer

In [11]: lib.is_integer_array(values)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
Exception ValueError: "Buffer dtype mismatch, expected 'Python object' but got 'long'" in 'pandas._libs.lib.is_integer_array' ignored
Out[11]: False

In [14]: lib.is_bytes_array(values)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
Exception ValueError: "Buffer dtype mismatch, expected 'Python object' but got 'long'" in 'pandas._libs.lib.is_bytes_array' ignored
Out[14]: False

In [15]: lib.is_bytes_array(values.astype(bytes))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: Buffer dtype mismatch, expected 'Python object' but got a string
Exception ValueError: "Buffer dtype mismatch, expected 'Python object' but got a string" in 'pandas._libs.lib.is_bytes_array' ignored
Out[15]: False
```

The closest thing to good news is that most of these functions are not used very much (at least not outside of inference.pyx, where maybe they behave better because of [mumble]). Four of them are explicitly tested in tests.dtypes.test_inference (is_datetime_array, is_datetime64_array, is_timdelta_array, is_timedelta64_array). Other than that, its just two uses of is_bool_array (core.common, core.internals) and one of is_datetime_array (in core.indexes.base)

### PR DESCRIPTION
**Pull request by jreback**
closes #18064

### CODE REVIEW

**Comment by martinholmer** [comment]
I don't see merged pull request #18252 in the 0.22.0 milestone even though @jreback said he added it to that milestone.  Did I miss this pull request in the 0.22.0 milestone?  The [Tax-Calculator project](https://github.com/open-source-economics/Tax-Calculator) is having difficulties with this and is looking forward to a fix in the 0.22.0 release of Pandas.

@hdoupe

**Comment by jorisvandenbossche** [comment]
If you scroll up you will see that this PR is tagged with the 0.22 milestone. Or do you mean something else? 
But, as far as I know this is a rather internal fix-up PR, without reported user facing problems. If that is the case, can you specify the issues you have with this? (because if that is the case, we could consider tagging this for 0.21.1)

**Comment by martinholmer** [comment]
@jorisvandenbossche,  Thanks for you quick response in which you said:
> If you scroll up you will see that this PR is tagged with the 0.22 milestone. Or do you mean something else?

Yes, I see the mention of 0.22  in the pull request, but I didn't see it listed in the 0.22 milestone list [here](https://github.com/pandas-dev/pandas/milestone/53).
Maybe I missed it or I'm confused.

**Comment by martinholmer** [comment]
@jorisvandenbossche, Sorry for my confusion, but I now see #18252 on the fifth page of the merged pull requests in the 0.22 milestone.  Guess 0.22 is scheduled for early January 2018 distribution.

@hdoupe

**Comment by jorisvandenbossche** [comment]
But still, how is this affecting your code? 
That would be interesting to know, so we can actually test for that

**Comment by martinholmer** [comment]
@jorisvandenbossche asked:
> But still, how is this affecting your code? 
> That would be interesting to know, so we can actually test for that.

We are having what I hope are just cosmetic problems: we are getting the following kind of **ignored** error message:
```
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
Exception ValueError: "Buffer dtype mismatch, expected 'Python object' but got 'long'" in 'pandas._libs.lib.is_bool_array' ignored
```

**Comment by jorisvandenbossche** [comment]
OK, then it is the same issue, but there is no problem in the actual behaviour.

**Comment by martinholmer** [comment]
@jorisvandenbossche said:
> OK, then it is the same issue, **but there is no problem in the actual behaviour**.

Yes, that's what we hope.  We'll see if the Pandas change in #18252 makes the ignored error messages go away when we move to Pandas 0.22.  If they don't, then we'll have to look at our code more carefully.

Thanks for your quick and thorough responses to my questions.

cc @hdoupe

**Comment by bplant17** [comment]
I'm still getting the error.  :(

**Comment by jorisvandenbossche** [comment]
@bplant17 if you still have a problem, please open an new issue with more information

**Pull request merged**
