### PR TITLE
Standard error of the mean

### PR DESCRIPTION
**Pull request by DmitriyLanchakov**
- [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

### CODE REVIEW

**Comment by shoyer** [comment]
Please explain this change and why it's a good idea.

**Comment by DmitriyLanchakov** [comment]
It gives more informative output:
count  33.00
mean    3.09
sd      2.89 
min     0.00
2.5%    0.00
25%     1.00 
50%     2.00 
75%     5.00
97.5%  10.20 
max    11.00 
se      0.50

**Comment by shoyer** [comment]
My personal opinion is that it isn't worth adding standard error to `.describe()`. It's something that I have never had the need for when first getting familiar with a dataset (which is what `.describe()` is for).

**Comment by jorisvandenbossche** [comment]
It is my feeling as well that the standard error is not essential enough to add it (the standard deviation is already included). See also https://github.com/pandas-dev/pandas/issues/14483 for a similar request to add 'sum', which was also declined.

**Comment by jreback** [comment]
agreed, closing.

**Pull request closed without merging**
