### PR TITLE
BUG: unstack with nulls & Timedelta/DateTime index

### PR DESCRIPTION
**Pull request by behzadnouri**
xref https://github.com/pydata/pandas/pull/9292#discussion_r24620887

on branch:

```
>>> df
           a       b    c
0 2014-02-01 -1 days  100
1        NaT     NaT  101
2 2014-02-03  1 days  102
3        NaT  2 days  103
4 2014-02-05     NaT  104
5 2014-02-06  4 days  105

>>> df.pivot('a', 'b', 'c').fillna('-')
b           NaT -1 days 1 days 2 days 4 days
a
NaT         101       -      -    103      -
2014-02-01    -     100      -      -      -
2014-02-03    -       -    102      -      -
2014-02-05  104       -      -      -      -
2014-02-06    -       -      -      -    105

>>> df.pivot('b', 'a', 'c').fillna('-')
a        NaT 2014-02-01 2014-02-03 2014-02-05 2014-02-06
b
NaT      101          -          -        104          -
-1 days    -        100          -          -          -
1 days     -          -        102          -          -
2 days   103          -          -          -          -
4 days     -          -          -          -        105
```

### CODE REVIEW

**Comment by jreback** [comment]
- can you add a release note
- pls make the test on a mixed frame e.g. with ints/datetimes/timedeltas in it (with datetimes/timedeltas) have NaT's. for a full test

**Comment by behzadnouri** [comment]
what do u mean? the added test is already a mixed frame with ints, datetimes & timedelta

**Comment by jreback** [comment]
sorry, was looking at some things else....ok just the release note and good to go (and put a comment on the test that refers to issue as well)

**Comment by behzadnouri** [comment]
added the release note

**Comment by jreback** [comment]
@behzadnouri thanks as always!

**Pull request merged**
