### PR TITLE
CLN: Split pandas/tests/base/test_ops.py

### PR DESCRIPTION
**Pull request by SaturnFromTitan**
As suggested by @jreback in [this PR comment](https://github.com/pandas-dev/pandas/pull/32725#issuecomment-599299873)

- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jreback** [comment]
great, i think we merged something, can you rebase.

cc @jbrockmendel who has an outstanding PR that overlaps a bit here (well inserting some new things)

**Comment by jbrockmendel** [comment]
I dont think any of my PRs have a conflict here; if they do I'll rebase when the time comes

**Comment by SaturnFromTitan** [comment]
@jreback @jbrockmendel Conflicts resolved and CI green

**Comment by jreback** [comment]
thanks @SaturnFromTitan

**Pull request merged**
