### PR TITLE
DOC: Replace pandas on Ray in ecosystem.rst with Modin

### LINKED ISSUE #37247: DOC: Replace pandas on Ray in ecosystem.rst with Modin
#### Location of the documentation

https://pandas.pydata.org/docs/ecosystem.html#ray

#### Documentation problem

Pandas on Ray does not exist anymore.

#### Suggested fix for documentation

Update references to Modin. 

I will do this.

### PR DESCRIPTION
**Pull request by devin-petersohn**
* Resolves #37247

Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>

- [x] closes #37247
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@datapythonista have you seen this GitHub API rate limit issue before?

```
  File "/home/runner/work/pandas/pandas/web/pandas_web.py", line 154, in maintainers_add_info
    resp.raise_for_status()
  File "/home/runner/miniconda3/envs/pandas-dev/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/users/gfyoung
Error: Process completed with exit code 1.
```

**Comment by datapythonista** [comment]
> @datapythonista have you seen this GitHub API rate limit issue before?

Yes, I was having it all the time when doing tests with the website locally. To render the `Team` page, we call the GitHub API for the photos and names of the active maintainers. There is an hourly quote, so if `number of doc builds in one hour * number of maintainers > GitHub quota`, then this will happen.

I guess the quota is per ip, so not sure how different builds impact the quota.

For this PR, just retrying a bit later will fix the issue. For the future, I see two options:
- Trivial: Move active maintainers to emeritus maintainers for who it makes sense, and that will make it more unlikely to happen
- Find a way to avoid calling the GitHub API on PRs, since only the website rendered in master builds is published

**Comment by devin-petersohn** [comment]
Has it been long enough to retry? @datapythonista @TomAugspurger

**Comment by datapythonista** [comment]
I think so, reruning the CI...

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @devin-petersohn

**Comment by jreback** [comment]
thanks @devin-petersohn

**Comment by devin-petersohn** [comment]
@datapythonista @TomAugspurger I have not seen the changes propagate to the documentation, is there a problem with the changes?

https://pandas.pydata.org/docs/ecosystem.html

**Comment by TomAugspurger** [comment]
The version at /docs are updated with releases (this was in 1.2 I think).

https://pandas.pydata.org/pandas-docs/dev/ecosystem.html <https://pandas.pydata.org/pandas-docs/dev/ecosystem.html> should have the changes.

**Comment by datapythonista** [comment]
We have some duplicated pages, the ecosystem is one of them. You changed it in the docs, and I'm not sure where that is being rendered (@jorisvandenbossche should know), and the one you're linking is to the web.

This was discussed some time ago in #29586, but there was no consensus to delete the copy in the docs, so the two copies were left. You can open another PR for the doc in the website, sorry for the extra work.

**Comment by datapythonista** [comment]
Ups, sorry, Tom is right, I got confused. The web version is at https://pandas.pydata.org/community/ecosystem.html and updates as soon as the PR is merged, but for the docs one, you'll have to wait until the next release.

**Comment by devin-petersohn** [comment]
Makes sense, thank you @TomAugspurger and @datapythonista!

**Pull request merged**
