### PR TITLE
MAINT: Ignore .pxi files

### PR DESCRIPTION
**Pull request by gfyoung**
All `.pxi` files have the warning to not edit directly, so why not have Git ignore any changes made there?

In addition, this PR deletes all of the `.pxi` files from the codebase because they are automatically generated by the `.pxi.in` files

### CODE REVIEW

**Comment by jreback** [comment]
if you did this and don't check them in.

the a new clone & build will generate them, so that's ok.

when you change a ``.in`` they will get regenerated, so that seems ok.

when you switch branches what happens? (e.g. modify something in a .in in one branch), switch to another
make should just regen the files you need. does that work?

**Comment by gfyoung** [comment]
@jreback : Yes, it does.

**Comment by jreback** [comment]
ok so in this PR, remove all of the .pxi as well.

**Comment by gfyoung** [comment]
Travis OSX keeps breaking because it cannot seem to hit the `github.com` endpoint when cloning the repository, which is unrelated to this PR.  Silencing testing for now until that resolves itself.

**Comment by jorisvandenbossche** [comment]
cc @sinhrks @chris-b1

**Comment by gfyoung** [comment]
@jreback , @jorisvandenbossche : Travis is behaving again, so this should be ready to merge.

**Comment by jreback** [comment]
can  do firm that that travis caching still works?

**Comment by sinhrks** [comment]
I've added these files only for travis caching, so it's good to remove if caching can still work.

**Comment by gfyoung** [comment]
@sinhrks , @jreback : I don't see any issues with caching on Travis, so I think this should be good to go.

**Comment by jreback** [comment]
thanks!

**Comment by jreback** [comment]
let's keep an eye on the caching though

**Pull request closed without merging**
