### PR TITLE
CLN: Fix typos (mainly in docs and comments)

### PR DESCRIPTION
**Pull request by minho42**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by topper-123** [comment]
Very nice patch! It needs a rebase, so ping when green.

**Review by topper-123 — APPROVED** [review]

**Comment by TomAugspurger** [comment]
FYI, it may be easier to split this into smaller pieces, to avoid merge conflicts like the one that came up.

**Review by datapythonista — APPROVED** [review]
Great job @minho42, nice clean up.

Let us know if you need help resolving the conflicts.

**Comment by minho42** [comment]
I tried to rebase, but not sure if it's okay.
Please change/amend further if necessary.

**Comment by datapythonista** [comment]
Looks ok, let's wait until the CI finishes, but this should be ready to be merged. Thanks @minho42

**Comment by datapythonista** [comment]
Thanks @minho42

**Pull request merged**
