### PR TITLE
CLN: .values -> ._values

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
Similar general question as in https://github.com/pandas-dev/pandas/pull/32781: what logic do we we use to decide when to use which property?  
Just always `_values` when possible (to ensure we always are using the correct representation, ndarray or EA)? Or do we still prefer to use the public attribute where it's not different from `_values`?

Also, in the latter case, that's typically because we are either sure the result is always numpy array (in which case `np.asarray()` or `to_numpy` might be more explicit) or always an ExtensionArray (in which case `.array` might be more idiomatic).

**Comment by jbrockmendel** [comment]
> what logic do we we use to decide when to use which property?

The default should be ._values, as .values may be either lossy (dt64tz), involve an object-dtype cast (period, interval), or be surprising (until recently I forgot that Series[Sparse].values gives a SparseArray, not ndarray).

Both this and #32781 are aimed at usages where the two are equivalent.  This should make it easier to focus attention on usages where they are not equivalent, and double-check whether those are intentional or improveable.

**Comment by jreback** [comment]
comments here: https://github.com/pandas-dev/pandas/pull/32781#issuecomment-600927742

**Comment by mroeschke** [comment]
@jbrockmendel if you'd like to tackle the `.values` calls in this PR or a followup in `pandas/core/indexes/base.py` that'd fix https://github.com/pandas-dev/pandas/issues/32740

**Comment by jbrockmendel** [comment]
Travis yellow is wrong; travis is green

**Comment by jreback** [comment]
kk, no test covers this?

**Comment by jbrockmendel** [comment]
> no test covers this?

not sure what you're referring to

**Pull request merged**
