### PR TITLE
Add On being part of the pandas Benchmarks Grant blog

### PR DESCRIPTION
**Pull request by dorothykiz1**
The pandas Benchmarks Grant blog

### CODE REVIEW

**Comment by dorothykiz1** [comment]
@datapythonista this PR is ready for your review

**Comment by datapythonista** [comment]
CI is red. Also, my understanding that you were going to write this post together with @LucyJimenez, that would still be my preference. IMHO it'd also be nice to provide more context at the beginning on what this post is about 

Also, would be helpful if you could limit the line lengths as you do with code, makes it easier to review and edit the file if ever needed.

Finally, did you build the website as we discussed to see if the blog home and the html of your post is rendered as expected?

**Comment by LucyJimenez** [comment]
Hi @datapythonista. I thought each one was going to write a blog. I'm preparing mine, that's why I asked you if it was okay to hand it over the next weekend, @dorothykiz1 says that she can finished in Wednesday.

**Comment by dorothykiz1** [comment]
Yes ,thats what I had thought so too.Everyone writing their experience.But you can advise otherwise

**Comment by dorothykiz1** [comment]
closed to be modified

**Pull request closed without merging**
