### PR TITLE
Update outdated instructions in scripts/generate_pip_deps_from_conda.py #36494

### LINKED ISSUE #36494: Update outdated instructions in scripts/generate_pip_deps_from_conda.py
It says
```
Usage:

    Generate `requirements-dev.txt`
    $ ./conda_to_pip

    Compare and fail (exit status != 0) if `requirements-dev.txt` has not been
    generated with this script:
    $ ./conda_to_pip --compare
```
but it should be
```
Usage:

    Generate `requirements-dev.txt`
    $ python scripts/generate_pip_deps_from_conda.py

    Compare and fail (exit status != 0) if `requirements-dev.txt` has not been
    generated with this script:
    $ python scripts/generate_pip_deps_from_conda.py --compare
```

No need to ask if you can work on this, feel free to just submit a PR

### PR DESCRIPTION
**Pull request by sharonwoo**
- [x] closes #36494 
- [x] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by sharonwoo** [comment]
PR in response to https://github.com/pandas-dev/pandas/issues/36494

**Review by MarcoGorelli — APPROVED** [review]
Thanks @sharonwoo ! CI failures are unrelated, might be necessary to merge upstream/master later to get this green

**Review by dsaxton — APPROVED** [review]
Thanks @sharonwoo

**Comment by jreback** [comment]
thanks @sharonwoo

**Pull request merged**
