### PR TITLE
BUG: overflow in astype(td64ns)

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
seem to remember a bug report about this, but could be imagintion

**Comment by simonjayhawkins** [comment]
This results in a 5.22x slowdown in one of our benchmarks

https://simonjayhawkins.github.io/fantastic-dollop/#inference.ToTimedelta.time_convert_int?branch=1.2.x&branch=1.3.x&commits=b7618487

**Comment by jbrockmendel** [comment]
> This results in a 5.22x slowdown in one of our benchmarks

Yah AFAICT this is unavoidable if we want to fix the bug.  https://github.com/numpy/numpy/issues/16352 is about fixing the astype upstream.

**Comment by jbrockmendel** [comment]
BTW looking at the regressions listed, I think we can hit "ignore" for the TimestampProperties.time_freqstr ones, since those are driven by a deprecation of freqstr (and are still measured in ns)

**Comment by simonjayhawkins** [comment]
> > lts in a 5.22x slowdown in one of our benchmarks
> 
> Yah AFAICT this is unavoidable if we want to fix the bug. [numpy/numpy#16352](https://github.com/numpy/numpy/issues/16352) is about fixing the astype upstream.

ok. have ignored https://simonjayhawkins.github.io/fantastic-dollop/#regressions?sort=3&dir=desc&branch=1.3.x

**Pull request merged**
