### PR TITLE
Added Datetime & Timedelta inference to array

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/24568

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. let's waiting on things though till we have fixed windows CI.

**Comment by TomAugspurger** [comment]
Replacing that turned up an issue with non-ns datetime64 / timedelta64
values. Pushing a fix for that in a bit.

**Comment by TomAugspurger** [comment]
3d9cebe8b17d66a9425bb68431139be03188f5b3 fixes the datetime / timedelta
issue.

pd.array isn't a drop-in replacement for tm.to_array, since to_array
returns an ndarray for non-special cased dtypes.

**Comment by jreback** [comment]
@jbrockmendel but maybe should use its as much as possible (e.g. hit the special cases, else hit pd.array)

**Comment by TomAugspurger** [comment]
Agreed. I tried that briefly, and things failed (haven't looked deeply yet). Not sure if it's a bug in pd.array or different semantics for tm.to_array.

**Comment by jreback** [comment]
thanks @TomAugspurger

**Pull request merged**
