### PR TITLE
TYP:  changed variable cat_array to cat_array_list in dtypes.py

### PR DESCRIPTION
**Pull request by nickleus27**
xref #37715

### CODE REVIEW

**Comment by nickleus27** [comment]
@jbrockmendel any idea why I am failing these tests?  Thanks for your time.

**Comment by jbrockmendel** [comment]
Best guess is the CI started using a newer version of pyarrow and ran into #44231, so its unrelated to this PR and you can ignore those particular failures for now

**Comment by jreback** [comment]
can you merge master

**Comment by nickleus27** [comment]
@jreback Sorry I pulled from master then pushed. I guess that was the wrong thing to do to git merge.  Not sure how to undo this.

**Pull request closed without merging**
