### PR TITLE
DOC: make deprecation warning more visible with red box

### LINKED ISSUE #20349: Add CSS formating for deprecated parameters / methods
These aren't especially noticeable in the HTML docs.

screen shot 2018-03-14 at 1 13 58 pm

Adding this to our CSS should fix that

```
div.deprecated {
    background-color: #ffe4e4;
    border: 1px solid #f66;
}
```

cc @datapythonista @shoyer

### PR DESCRIPTION
**Pull request by Imanflow**
- [x ] closes #20349
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
How it currently looks:

screenshot-2018-3-15 pandas dataframe from_csv pandas 0 23 0 dev0 604 g8ca08d1 documentation

So I think we need to add some more css to have it look better (border spacing). As comparison, the see also box:

screenshot-2018-3-15 pandas dataframe from_csv pandas 0 23 0 dev0 604 g8ca08d1 documentation 1

**Comment by jorisvandenbossche** [comment]
Apparently I did something very similar for sklearn a while ago, so you can see there how I did it then: https://github.com/scikit-learn/scikit-learn/pull/8914

**Comment by jreback** [comment]
lgtm. @jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
Don't merge yet. We should fix the styling.

@Imanflow you can take a look at the PR in sklearn I mentioned above how it was done there.

**Comment by Imanflow** [comment]
For a reason I can't undersand, further changes in `https://github.com/pandas-dev/pandas/blob/master/doc/source/themes/nature_with_gtoc/static/nature.css_t`doesn't get reflected when i do 

`# in pandas/doc `
`python make.py --single=pandas.DataFrame.from_csv`


any clue?

**Comment by arminv** [comment]
I'm not sure why you can't see your changes, but based on how @jorisvandenbossche [fixed](https://github.com/scikit-learn/scikit-learn/pull/8914/files) this issue before and #20349, you need:

```
div.admonition p.admonition-title + p, div.deprecated p {
    display: inline;
}
```
`, div.deprecated p` is missing in your code.

You also need:
```
div.deprecated {
    background-color: #ffe4e4;
    border: 1px solid #f66;
    margin-bottom: 10px;
    margin-top: 10px;
    padding: 7px;
    border-radius: 4px;
    -moz-border-radius: 4px;
}
```
I think the last two properties here (`border-radius: 4px;` and `-moz-border-radius: 4px;`) are not necessary as we want the box to have sharp edges and be consistent with 'See also' box etc,.

So you are missing these: 
```
    margin-bottom: 10px;
    margin-top: 10px;
    padding: 7px;
```

**Comment by Imanflow** [comment]
Done, thanks for your patience. 

PD: The problem with not seeing the changes was that on terminal I was in a different branch than in Pycharm.

**Review by jorisvandenbossche — APPROVED** [review]
Looks good!

**Comment by jorisvandenbossche** [comment]
@Imanflow @arminv Thanks!

**Pull request merged**
