### PR TITLE
BUG: Series.__setitem__[listlike_of_integers] with IntervalIndex

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by gfyoung** [comment]
Changes make sense.  Just needs a `whatsnew` I think.

**Comment by jreback** [comment]
yep if you can add a whatsnew

**Comment by jbrockmendel** [comment]
updated with whatsnew

**Comment by jbrockmendel** [comment]
updated + green (finally)

**Review by TomAugspurger — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
