### PR TITLE
ENH: Index[complex]

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
looks ok for 1.4? can you rebase

**Comment by jbrockmendel** [comment]
> looks ok for 1.4?

id rather not rush this.

**Comment by jbrockmendel** [comment]
uh probably premature.  among other things needs whatsnew

**Comment by jreback** [comment]
ok sure

**Pull request merged**
