### PR TITLE
REGR: show_versions

### PR DESCRIPTION
**Pull request by simonjayhawkins**
regression in #31660 (no need to backport)

master
```
INSTALLED VERSIONS
------------------
{k:<17}: {stat}
{k:<17}: {stat}
{k:<17}: {stat}
...
```

this PR
```
INSTALLED VERSIONS
------------------
commit           : b11e0647d42a27c279f3c46d5ce26d79bb5f5dec
python           : 3.7.4.final.0
python-bits      : 64
...
```

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by jbrockmendel** [comment]
merits test?

**Comment by simonjayhawkins** [comment]
@jbrockmendel looks like the fakemodule tests don't clean-up. will look tomorrow if can't get to machine later this evening. could maybe use monkeypatch VERSIONS or just delete fakemodule from VERSIONS after test

**Comment by jbrockmendel** [comment]
ok, test here isnt important enough to be a blocker

**Review by datapythonista — APPROVED** [review]
lgtm,

Just an idea, we could rename `show_versions` to `_get_versions` and make it a generator yielding the version information. Then implement a small `show_versions` function that prints the results of `_get_versions`.

This way your tests would be much simpler and clearer, and I guess it can be useful in some cases to access the versions from Python, not just getting them printed.

Happy to get this merged as is.

**Comment by simonjayhawkins** [comment]
> Just an idea, we could rename `show_versions` to `_get_versions` and make it a generator yielding the version information. Then implement a small `show_versions` function that prints the results of `_get_versions`.

have started #32042 to clean-up since `get_sys_info` was stringifying the `None`s which then appears in the json output. so could incorporate this suggestion there.

**Comment by WillAyd** [comment]
Thanks @simonjayhawkins

**Pull request merged**
