### PR TITLE
wip: BUG: styler hide index fails for latex translate

### LINKED ISSUE #43637: BUG: `styler.to_latex` does hide rows after `hide_index([subset])`
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
>>> df = DataFrame([[1], [2]])
>>> print(df.style.hide_index([0]).to_latex())
\begin{tabular}{lr}
 & 0 \\
 \\
1 & 2 \\
\end{tabular}
```

### Issue Description

its the header cells that render as empty spaces creating an unwanted line. 

### Expected Behavior

no unwanted line.

### Installed Versions

master

### PR DESCRIPTION
**Pull request by attack68**
- [x] closes #43637
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Is this a regression or bug fix? we are quite late in the release cycle of 1.3.x now. Probably only one release after the next one. so opportunities to resolve any issues are limited.

**Comment by attack68** [comment]
this is a bug fix. pretty simple one so I bothered to backport it. if too late, no worries, close the backport and i put it in 1.4.0

**Comment by simonjayhawkins** [comment]
we don't have any hard and fast rules. see what others think.

**Comment by attack68** [comment]
just converted this to wip as #43644 was detected whilst solving this and a fix for that might be a universal fix

**Comment by jreback** [comment]
@attack68 replaced by #43649 ?

**Comment by attack68** [comment]
> @attack68 replaced by #43649 ?

yes that one has become more developed and is better than this.

**Pull request closed without merging**
