### PR TITLE
BUG: Fix error in printing timezone series

### LINKED ISSUE #54623: BUG: Printing a timezone-aware datetime series raises
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> import numpy as np
>>> ser1 = pd.Series(np.array(["2999-01-01"], dtype="datetime64[us]"))
>>> print(ser1) # This is fine
0   2999-01-01
dtype: datetime64[us]
>>> ser2 = pd.Series(np.array(["2999-01-01"], dtype="datetime64[us]")).dt.tz_localize("US/Pacific")
>>> print(ser2) # This breaks
[...]
pandas._libs.tslibs.conversion.convert_datetime_to_tsobject
  File "np_datetime.pyx", line 231, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 2999-01-01 00:00:00, at position 0
```

### Issue Description

Printing a timezone aware datetime Series for non-ns resolution raises OutOfBoundsDatetime error

### Expected Behavior

We should be able to print the Series

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : 77bc67a3a794cc4d7cf3c318e70292fceb65eab7
python              : 3.11.1.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 22.6.0
Version             : Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_GB.UTF-8
LOCALE              : en_GB.UTF-8

pandas              : 0+untagged.33100.g77bc67a.dirty
numpy               : 1.24.4
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 65.5.0
pip                 : 22.3.1
Cython              : 0.29.33
pytest              : 7.4.0
hypothesis          : 6.82.5
sphinx              : 6.2.1
blosc               : 1.11.1
feather             : None
xlsxwriter          : 3.1.2
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : 1.4.6
psycopg2            : 2.9.7
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
brotli              : 
dataframe-api-compat: None
fastparquet         : 2023.7.0
fsspec              : 2023.6.0
gcsfs               : 2023.6.0
matplotlib          : 3.7.2
numba               : 0.57.1
numexpr             : 2.8.5
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 12.0.1
pyreadstat          : 1.2.2
pyxlsb              : 1.0.10
s3fs                : 2023.6.0
scipy               : 1.11.2
snappy              : None
sqlalchemy          : 2.0.20
tables              : None
tabulate            : 0.9.0
xarray              : 2023.7.0
xlrd                : 2.0.1
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
</details>

### PR DESCRIPTION
**Pull request by AdrianDAlessandro**
- [x] closes #54623
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by AdrianDAlessandro** [comment]
@jorisvandenbossche

**Review by jorisvandenbossche — APPROVED** [review]
Change itself looks good to me, thanks!

Could you add a short note to our changelog? I think we should backport this for 2.1 (failure in the repr is _really_ annoying), so could you add a line to the `doc/source/whatsnew/v2.1.0.rst` file? (section "Bug Fixes" -> "Datetimelike"))

**Comment by AdrianDAlessandro** [comment]
Done

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @AdrianDAlessandro

**Pull request merged**
