### PR TITLE
TST: pandas/test/window/ changes for #30999

### PR DESCRIPTION
**Pull request by boweyism**
- [ ] xref  #30999 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I've made changes for:
- tests/window/moments/test_moments_rolling.py
- tests/window/test_dtypes.py
- tests/window/test_ewm.py
- tests/window/test_expanding.py
- tests/window/test_timeseries_windows.py

In a couple of places there were comments stating the raised error's output. The `msg` variable contains the same information. Should I remove these coments?

Belongs to issue: https://github.com/pandas-dev/pandas/issues/30999

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by jreback** [comment]
looks like a code check failed if u can address
pls ping on green

**Comment by boweyism** [comment]
@jreback the checks came back green :)

**Comment by simonjayhawkins** [comment]
Thanks @boweyism

**Pull request merged**
