### PR TITLE
CLN: Remove pd.parser, lib, and tslib

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.

xref #15537.

### CODE REVIEW

**Comment by gfyoung** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/447030560

`xarray=0.8.0` depends on `pandas.tslib` existing, hence the downstream failure.

@TomAugspurger : Do you remember why it was pinned in #20767?

Alternatively, because it's a Python 2.x failure, skip and ignore it?

**Comment by jreback** [comment]
u can bump the xarray test

**Comment by gfyoung** [comment]
> u can bump the xarray test

@jreback : To clarify, you mean bump the version number for the `xarray` dependency?

**Comment by jreback** [comment]
it’s just the test version
we don’t depend on xarray

**Comment by gfyoung** [comment]
@jreback : Sorry, poor choice of words.  I meant to say:

Should we bump the `xarray` version for that Travis build?

**Comment by jreback** [comment]
nice, thanks!

**Pull request merged**
