### PR TITLE
Revert #12260 "BUG: Make Styler ignore None index names to match to_html..."

### PR DESCRIPTION
**Pull request by TomAugspurger**
Master started failing on https://github.com/pydata/pandas/pull/12260 [travis](https://travis-ci.org/pydata/pandas/builds/113480877). Not entirely sure why yet, but was able to reproduce one of the failures locally, and fix it with the revert.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I'll followup later with the actual changes made in #12260 later.

**Comment by jorisvandenbossche** [comment]
The TestYahooOptions is in any case not related, as I get the same error when using pandas 0.16.2. So probably something changed on the Yahoo side.

**Comment by TomAugspurger** [comment]
And I just got a success and then a failure on master for the Yahoo tests, seems to be intermittent.

**Comment by jreback** [comment]
yeh we should just disable some more of these yahoo tests

**Comment by TomAugspurger** [comment]
Going to close this one then.

**Pull request closed without merging**
