### PR TITLE
Fix exception causes in 14 modules

### PR DESCRIPTION
**Pull request by cool-RR**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by cool-RR** [comment]
This covers around half of the project. We could do the rest later.

**Comment by cool-RR** [comment]
Any idea why some checks are failing? I'm seeing "ImportError: No module named conda.cli" but I don't see how that's related to my PR.

**Comment by simonjayhawkins** [comment]
> Any idea why some checks are failing? I'm seeing "ImportError: No module named conda.cli" but I don't see how that's related to my PR.

failing CI should be fixed now. can you merge master.

**Review by WillAyd — APPROVED** [review]
Lgtm if green

**Comment by jreback** [comment]
thanks @cool-RR 

in theory we could have a code_checks rule that fails if we *don't* have ```from err```, but might be non-trivial to do via bash, maybe a linter could do this? (flake plugin)

**Pull request merged**
