### PR TITLE
COMPAT: Drop reference to deprecated dateutil.zoneinfo.gettz

### LINKED ISSUE #19004: COMPAT: python-dateutil deprecation warnings
not trivial to actually trigger these, but showing up on some of our appeveyor builds.

```
pandas\tests\indexes\datetimes\test_arithmetic.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas\core\indexes\datetimes.py:2138: in date_range
    closed=closed, **kwargs)
pandas\util\_decorators.py:123: in wrapper
    return func(*args, **kwargs)
pandas\core\indexes\datetimes.py:374: in __new__
    ambiguous=ambiguous)
pandas\core\indexes\datetimes.py:509: in _generate
    tz = timezones.maybe_get_tz(tz)
pandas\_libs\tslibs\timezones.pyx:93: in pandas._libs.tslibs.timezones.maybe_get_tz
    cpdef inline object maybe_get_tz(object tz):
pandas\_libs\tslibs\timezones.pyx:103: in pandas._libs.tslibs.timezones.maybe_get_tz
    tz = dateutil_gettz(zone)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
name = 'Asia/Singapore'
    def gettz(name):
        """
        This retrieves a time zone from the local zoneinfo tarball that is packaged
        with dateutil.
    
        :param name:
            An IANA-style time zone name, as found in the zoneinfo file.
    
        :return:
            Returns a :class:`dateutil.tz.tzfile` time zone object.
    
        .. warning::
            It is generally inadvisable to use this function, and it is only
            provided for API compatibility with earlier versions. This is *not*
            equivalent to ``dateutil.tz.gettz()``, which selects an appropriate
            time zone based on the inputs, favoring system zoneinfo. This is ONLY
            for accessing the dateutil-specific zoneinfo (which may be out of
            date compared to the system zoneinfo).
    
        .. deprecated:: 2.6
            If you need to use a specific zoneinfofile over the system zoneinfo,
            instantiate a :class:`dateutil.zoneinfo.ZoneInfoFile` object and call
            :func:`dateutil.zoneinfo.ZoneInfoFile.get(name)` instead.
    
            Use :func:`get_zonefile_instance` to retrieve an instance of the
            dateutil-provided zoneinfo.
        """
        warnings.warn("zoneinfo.gettz() will be removed in future versions, "
                      "to use the dateutil-provided zoneinfo files, instantiate a "
                      "ZoneInfoFile object and use ZoneInfoFile.zones.get() "
                      "instead. See the documentation for details.",
>                     DeprecationWarning)
E       DeprecationWarning: zoneinfo.gettz() will be removed in future versions, to use the dateutil-provided zoneinfo files, instantiate a ZoneInfoFile object and use ZoneInfoFile.zones.get() instead. See the documentation for details.
C:\Miniconda3_64\envs\pandas\lib\site-packages\dateutil\zoneinfo\__init__.py:156: DeprecationWarning
_____ TestDatetimeIndexArithmetic.test_dti_isub_int[dateutil/US/Pacific] ______
```

### PR DESCRIPTION
**Pull request by pganssle**
- [X] closes #19004

I'm assuming these will be handled by CI:
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Not sure this is necessary, it's a very "behind the scenes" fix, replacing `zoneinfo.gettz` with the superior `tz.gettz()`:

- [ ] whatsnew entry

### CODE REVIEW

**Comment by pganssle** [comment]
Original PR adding this was #9123, I believe it was just a bit conservative in switching over to the preferred API.

**Comment by jreback** [comment]
thanks @pganssle yeah I think this will fix. not really sure why we had this older code.

**Comment by pganssle** [comment]
I could see someone writing code like this because they figured that `tz.gettz()` will prefer system time zones on Mac and *nix, but on Windows there *are* no system time zones, so you should use the `zoneinfo.gettz` version. That logic is already built into `tz.gettz()` though, so it's preferable to just always use `tz.gettz` (there's another way to get the equivalent of what `zoneinfo.gettz()` does if you actually care that it's dateutil's `zoneinfo` files, not the system ones).

**Comment by jreback** [comment]
@pganssle thanks. might as well just change it, prefer the logic to exist in dateutil anyhow.

well that was the deprecation warning, so this patch should fix us.

**Comment by jreback** [comment]
thanks @pganssle

**Pull request merged**
