### PR TITLE
Remove redundant lists in array.py

### PR DESCRIPTION
**Pull request by cool-RR**
As far as I know these lists do nothing but taking up memory.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Note that this is a dummy implementation only for tests, so there is not much need in making an effort  to optimize this

**Comment by WillAyd** [comment]
looks good to me - can you merge master and re-push to fix CI?

**Comment by cool-RR** [comment]
Looks like the CI failure is unrelated to my changes.

**Comment by jreback** [comment]
thanks @cool-RR

**Pull request merged**
