### PR TITLE
Add column index to be removed in get_dummies

### PR DESCRIPTION
**Pull request by jmehault**
While create dummies with get_dummies, we sometime want to remove an other column than the first one.
Add this possibility by :
- changing drop_first to drop_idx,
- drop_idx accept both bool (as drop_first) and int

 - [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
this seems overly complicated. you can simply select what you need (or don't after).

**Comment by TomAugspurger** [comment]
We also can't remove the `drop_first` keyword, since that isn't backwards compatible.

My preferred solution for this is to re-order the categories with `.set_categories` before calling get_dummies, so that the one you want dropped is first.

**Comment by phypho** [comment]
Indeed you are right both of you. I hope to do some thing simple but it's not. Especially when we apply get_dummies to a data frame with more than one categorical columns.

Thanks for your comments

**Comment by TomAugspurger** [comment]
If you're interested, you could submit a PR with some documentation on how to achieve this. I'm sure you're not the only one who's wanted to drop a column other than the first.

**Pull request closed without merging**
