### PR TITLE
Update broken-linkcheck.yml

### LINKED ISSUE #45409: DOC/CI: Add Github Action cron job to check external links in documentation
1. Modify `doc/make.py` to run `sphinx-build -b linkcheck`. May need to modify `doc/source/conf.py` to ignore some expected link errors.
2. Create a Github Action to run the Sphinx linkcheck monthly
3. If errors are found, have the GIthub Action create a new issue (and delete the old one) reporting all the errors and label and `Docs` and `Good First Issue`

### PR DESCRIPTION
**Pull request by ggold7046**
A Github Action to run the Sphinx linkcheck monthly to check link errors. If errors are found, the GIthub Action creates a new issue, (and delete the old one) reporting all the errors, and label as Docs and Good First Issue

- [X] closes #45409 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by ggold7046** [comment]
@datapythonista

**Comment by mroeschke** [comment]
Can you test this on your own fork to see an example of an issue being created?

**Comment by ggold7046** [comment]
@mroeschke,  the `create or update Linkcheck` issue step is showing these errors in my repo:
```
Error: HttpError: Resource not accessible by integration
Error: Request to create new issue failed
```
Is this related to any permission related problem ?

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
