### PR TITLE
DOC: fixes pipe example in basics.rst due to statsmodel changes

### LINKED ISSUE #19713: pipe example in basics.rst broken due to SciPy / statsmodels changes
```python
AttributeErrorTraceback (most recent call last)
<ipython-input-140-7e4e9a85c845> in <module>()
      1 (bb.query('h > 0')
      2    .assign(ln_h = lambda df: np.log(df.h))
----> 3    .pipe((sm.poisson, 'data'), 'hr ~ ln_h + year + g + C(lg)')
      4    .fit()
      5    .summary()
~/miniconda3/envs/pandas/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py in summary(self, yname, xname, title, alpha, yname_list)
   2548                      ('Log-Likelihood:', None),
   2549                      ('LL-Null:', ["%#8.5g" % self.llnull]),
-> 2550                      ('LLR p-value:', ["%#6.4g" % self.llr_pvalue])
   2551                      ]
   2552 
~/miniconda3/envs/pandas/lib/python3.6/site-packages/statsmodels/tools/decorators.py in __get__(self, obj, type)
     95         if _cachedval is None:
     96             # Call the "fget" function
---> 97             _cachedval = self.fget(obj)
     98             # Set the attribute in obj
     99             # print("Setting %s in cache to %s" % (name, _cachedval))
~/miniconda3/envs/pandas/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py in llr_pvalue(self)
   2403     @cache_readonly
   2404     def llr_pvalue(self):
-> 2405         return stats.chisqprob(self.llr, self.df_model)
   2406 
   2407     @cache_readonly
AttributeError: module 'scipy.stats' has no attribute 'chisqprob'
<<<-------------------------------------------------------------------------
```

Just do something other than poisson. Or remove statsmodels entirely, that's not the crucial point of the example.

### PR DESCRIPTION
**Pull request by ccatalfo**
To work around changes in statsmodel api.

- [ ] closes #19713
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you also do the same change in ``whatsnew/v0.16.2`` and change the test

```
pandas) bash-3.2$ grep -r sm.poisson doc/
doc//source/whatsnew/v0.16.2.txt:   # sm.poisson takes (formula, data)
doc//source/whatsnew/v0.16.2.txt:      .pipe((sm.poisson, 'data'), 'hr ~ ln_h + year + g + C(lg)')
doc//source/basics.rst:For example, we can fit a regression using statsmodels. Their API expects a formula first and a ``DataFrame`` as the second argument, ``data``. We pass in the function, keyword pair ``(sm.poisson, 'data')`` to ``pipe``:
doc//source/basics.rst:      .pipe((sm.poisson, 'data'), 'hr ~ ln_h + year + g + C(lg)')
```

**Review by jreback — CHANGES_REQUESTED** [review]
comments

**Comment by ccatalfo** [comment]
Thanks @jreback I've made the requested changes to whatsnew/v0.16.2.

**Comment by jorisvandenbossche** [comment]
@ccatalfo Thanks a lot!

**Pull request merged**
