### PR TITLE
REF/TYP: arrays.datetimelike

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

@simonjayhawkins this is still giving me two mypy complaints locally:

```
pandas/core/arrays/datetimelike.py:549: error: Too many arguments for "object"  [call-arg]
pandas/core/arrays/datetimelike.py:556: error: Too many arguments for "object"  [call-arg]
```

These lines are both calls to `self._scalar_type(foo)`

_scalar_type is annotated as `Type[DatetimeLikeScalar]`, which is a TypeVar for Period/Timestamp/Timedelta.  Is there a non-ignoring solution here?

### CODE REVIEW

**Comment by jbrockmendel** [comment]
updated to revert the setup.cfg edit for now to get CI passing

**Comment by jreback** [comment]
one more rebase to make sure didn't break anything from a recent merge (as I saw some PRs using DatetimeArraylikeMixin) but could be mistaken.

**Comment by jbrockmendel** [comment]
are both travis and azure down?

**Comment by jreback** [comment]
thanks. ideally if we can see what has changed about the failing builds. maybe a package was released which bumped things?

**Pull request merged**
