### PR TITLE
CI: 32 bit maybe_indices_to_slice

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
hmm you are backing this to fix the 32-bit tests? does this have a perf hit?

**Comment by jbrockmendel** [comment]
Not sure yet, still trying to get this passing

**Comment by jbrockmendel** [comment]
got some more troubleshooting to do, but in the interim, some greenish: #37365, #37402, #37449, #37451, #37456, #37470, #37472, #37475
and green but less trivial #37425, #37436, #37423, #37425, #37179, #37164, #34683 

The deluge is going to slow to a crawl since the next task on my list is a doozy: figuring out why the categorical validators all behave slightly differently.

**Comment by jbrockmendel** [comment]
alright, got the 32bit working

**Review by jreback — COMMENTED** [review]
can u run asvs

**Comment by jbrockmendel** [comment]
> can u run asvs

i can start them running overnight.  this should be totally neutral on 64bit since np.intp is an alias for np.int64

**Comment by jbrockmendel** [comment]
forgot to run asvs overnight, just started them now.

**Comment by jbrockmendel** [comment]
ran with `-b index`

```
BENCHMARKS NOT SIGNIFICANTLY CHANGED.
```

**Comment by simonjayhawkins** [comment]
@jreback if this is ready to merge will backport, otherwise can just skip failing 32 bit test on MacPython.

**Comment by jreback** [comment]
thanks @jbrockmendel

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.1.x

**Pull request merged**
