### PR TITLE
TST/CI: speed up chunksize test

### PR DESCRIPTION
**Pull request by mzeitlin11**
Seeing lots of CI timeouts - this test sometimes takes > 5 min for the python parser, guessing dependent on memory availability. 

AFAICT the data size is only so large to test the warning given by the c parser and low memory case, so shrank size for other cases.

### CODE REVIEW

**Comment by mzeitlin11** [comment]
Also tentatively removed resource warning handling as hoping that was only needed because of memory issues.

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jreback** [comment]
thanks @mzeitlin11

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
