### PR TITLE
STYLE Remove flake8-rst

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

flake8-rst is unmantained. It causes errors on Python3.10 - (Explanation by @MarcoGorelli)

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
thanks @DeaMariaLeon !

there's an issue about replacing flake8-rst with something maintained, if we find it we can use that. for now, if this one keeps causing issues (I've run into issues with it on newer Python versions), it's probably best to just get rid of it

**Comment by DeaMariaLeon** [comment]
Thanks @MarcoGorelli 
Linking to the issue you mention: #46865

**Review by MarcoGorelli — APPROVED** [review]
cool, let's merge, and if/when we find an alternative we can put it back

thanks @DeaMariaLeon !

**Comment by mroeschke** [comment]
So confirming we won't have flake8 checking on our rst files in the meantime?

**Comment by DeaMariaLeon** [comment]
That's what I understand @mroeschke.

**Comment by MarcoGorelli** [comment]
that's right unfortunately...I'll see if I can fork it, should be too big of a deal to make it compatible with latest versions of things

**Pull request merged**
