### PR TITLE
DOC: Additional Items for the Cheat Sheet

### PR DESCRIPTION
**Pull request by rishitbhojak**
- https://github.com/pandas-dev/pandas/issues/40680

- Added Plotting Functions 
- Added a 3rd page consisting of various plots
- Adjusted the 2nd page and added a snippet to 'Drop a Column'

### CODE REVIEW

**Comment by Dr-Irv** [comment]
Will be reviewing soon.  Sorry for the delay

**Comment by jreback** [comment]
@rishitbhojak can you merge master

**Comment by rishitbhojak** [comment]
> @rishitbhojak can you merge master

Can you please elaborate @jreback  sir?

**Comment by datapythonista** [comment]
There is some nice stuff in the proposed changes, but in general I'm -1 on this. At least in its current version. I add the proposed changes here, to give context to my comments:

Screenshot at 2022-04-05 00-16-28

The dropping a column part seems quite unreadable. Not sure if `pop` is the method we want to show in the cheatsheet for dropping a column, but regardless, we don't build the dataframe in any other function, I wouldn't do it here.

For the plots, more than a cheatsheet it looks like a gallery. Which is nice, but not sure if the cheatsheet is the right place for this. For a cheatsheet, it could be convenient to list the kind of plots, and the briefly explain what they do. More similar to the two plotting examples were there. Not just showing plot calls with the results, some times showing the data, some times without it.

Unless this can be improved significantly, present the information in a more consistent way, and showing the most relevant data (kde is probably among the least used functions, and there are lots of examples with it)., I'd rather stay with the current version.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale and doesn't look likely to move forward in it's current state. If interested in continuing, please merge in main and address the review, and this can be reopened

**Pull request closed without merging**
