### PR TITLE
Backport PR #37198 on branch 1.1.x (BUG: Regression in Resample.apply raised error when apply affected only a Series)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #37198: BUG: Regression in Resample.apply raised error when apply affected only a Series

### CODE REVIEW

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
DO NOT MERGE - failures are not false positives

**Comment by phofl** [comment]
Was this introduced through my fix or did I use something, which is only working on master and not 1.1.4?

**Comment by simonjayhawkins** [comment]
> Was this introduced through my fix or did I use something, which is only working on master and not 1.1.4?

not got to the bottom of it yet. see https://github.com/pandas-dev/pandas/issues/36951#issuecomment-713623620

**Comment by jbrockmendel** [comment]
> any ideas where changes in master could have corrected this

Not off the top of my head, no.

**Comment by simonjayhawkins** [comment]
> > any ideas where changes in master could have corrected this
> 
> Not off the top of my head, no.

appears to be #35792

https://github.com/simonjayhawkins/pandas/runs/1305349161?check_suite_focus=true

**Comment by simonjayhawkins** [comment]
looks like #35792 can be backported without any conflicts. added here for ci checking. would backport independently if moving forward with this. (whatsnew would need to be changed on master)

depending on tests passing, 3 options.

1. don't backport #37198 (see https://github.com/pandas-dev/pandas/issues/36951#issuecomment-713623620 this regression is from 0.25.3 to 1.0.0, we could decide not to backport.)

2. backport #37198 and change tests to not check frequency of index on backport only.

3. backport #37198 and #35792 (which fixes bug for Categoricalndex and preserves freq in DatetimeIndex following DataFrameGroupby)

**Comment by simonjayhawkins** [comment]
@jreback OK with option 3 https://github.com/pandas-dev/pandas/pull/37305#issuecomment-716486341

will start on a separate backport PR #35792 and PR to move the whatsnew

**Pull request merged**
