### PR TITLE
CLN: Remove unicode u string prefix

### PR DESCRIPTION
**Pull request by jschendel**
- [X] xref #25725
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

More Python 2 removal.  Could use a second pair of eyes to make sure the regex I used to make these fixes wasn't overzealous anywhere.

### CODE REVIEW

**Comment by jschendel** [comment]
I think as-is this will fail CI only because the following xfailed test is now passing, and we're being strict with XPASS here:

https://github.com/pandas-dev/pandas/blob/dca809b0151adb744940a727f5d82ca43f4c3ea4/pandas/tests/io/formats/test_to_csv.py#L355-L368

The only change I made a was removing the `u` prefix on lines 362-3, so it looks like this was only failing on Python 3 due to the expected string containing the prefixes?  I was able to manually confirm that this appears to be working on Python 3 and failing on Python 2 in the 0.24.2 release, meaning the issue was Python 2 specific and we can remove the `xfail`?

cc @jreback : Does the above make sense to you, or am I misinterpreting the issue?  If so, does it make sense to also close the associated issue?

**Comment by jreback** [comment]
that issue looks pretty confusing so not sure
you can make strict=False to get this PR passing

**Comment by jschendel** [comment]
okay, marked it as `@pytest.mark.xfail(strict=False)`

**Comment by jreback** [comment]
thanks @jschendel

**Pull request merged**
