### PR TITLE
DEPR: enforce nested-renaming deprecation

### PR DESCRIPTION
**Pull request by jbrockmendel**
Looks like this deprecation was introduced in #14668 (April 2017), so should be OK to remove by now.

Suggestions for better error messages welcome.

Not passing `_level` around is pretty nice

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@jorisvandenbossche i could use some help figuring out what the intended post-deprecation-enforcement behavior is.  From the test failures, I'm guessing some of these cases should not raise?

**Comment by jorisvandenbossche** [comment]
@jbrockmendel can you give an example of a case you are unsure about?

**Review by jreback — CHANGES_REQUESTED** [review]
can you add the whatsnew for this in removals & update the deprecation removal issue.

**Comment by jbrockmendel** [comment]
> can you give an example of a case you are unsure about?

Since the test failures have been fixed, the remaining question is if there are better error messages we should give

**Comment by jbrockmendel** [comment]
> can you add the whatsnew for this in removals & update the deprecation removal issue.

added (but not checked off) to #13777

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks!

**Pull request merged**
