### PR TITLE
Backport PR #49053 on branch 1.5.x (REVERT caching in find_stack_level)

### PR DESCRIPTION
**Pull request by MarcoGorelli**
#49053

Revert "PERF cache find_stack_level (#48023)"

This reverts commit 2f8d0a36703e81e4dca52ca9fe4f58c910c1b304.

Co-authored-by: MarcoGorelli <>
(cherry picked from commit 0106c26529900bad0561efb9c9180f7f016365b0)

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by phofl** [comment]
Sorry should have asked first, so this is not really a backport?

**Comment by MarcoGorelli** [comment]
sorry not sure what you mean, isn't it a backport?

**Comment by phofl** [comment]
I got a bit confused, sorry for that. Did you revert this strictly on the 1.5.x branch or did you cherry pick #49053 onto the 1.5.x branch?

**Comment by phofl** [comment]
Ok got you, thx for clearing this up for me :)

**Comment by MarcoGorelli** [comment]
no worries, thanks for checking

actually, looks like I got a different commit message than usual as, after fixing the conflicts, I did
```
git cherry-pick --continue
```
rather than
```
git commit -am 'Backport PR #49053: REVERT caching in find_stack_level'
```

**Comment by MarcoGorelli** [comment]
@phofl good to merge? I've been through the diff and it looks fine to me, doesn't look like anything unexpected has crept in when resolving conflicts

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @MarcoGorelli

**Pull request merged**
