### PR TITLE
CI: replace flake8-pyi with ruff

### PR DESCRIPTION
**Pull request by twoertwein**
Not all rules are covered by ruff but, from my point of view, the important ones are covered.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks @twoertwein !

**Comment by twoertwein** [comment]
Slightly (un)-related: Ruff started to cover some of the autotyping parts. I would be fine replacing autotyping with ruff when ruff adds type annotations to int/float/str/... default parameters. I consider this rule "important" as it "gently encourages" people who add new arguments to also add type annotations.

**Comment by MarcoGorelli** [comment]
sounds good

did you try upgrading to the latest autotyping? I tried, but got lots of error I couldn't resolve (though admittedly I didn't spend that long on it)

**Comment by twoertwein** [comment]
> did you try upgrading to the latest autotyping? I tried, but got lots of error I couldn't resolve (though admittedly I didn't spend that long on it)

I think these are triggered by the new `--guess-common-names`. I will go through them and see which ones are correct. But I think we probably have to exclude that option (or postpone until all incorrect guesses have correct annotations) .

**Pull request merged**
