### PR TITLE
Update doc URL in `setup.cfg` (for `1.5.x`)

### PR DESCRIPTION
**Pull request by jakirkham**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jakirkham** [comment]
This came out of recent discussion with @jorisvandenbossche ( https://github.com/conda-forge/pandas-feedstock/pull/147#discussion_r1048944958 )

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @jakirkham 

You can combine prs like you did in the future

**Comment by jakirkham** [comment]
Thanks @phofl! 🙏

So this one was making the change to 1.5.x. In 2, this has moved to a different file, which the other PR updated

**Comment by phofl** [comment]
Ah thx, missed that.

**Comment by jakirkham** [comment]
No worries. Also thanks for the reviews 🙏

**Pull request merged**
