### PR TITLE
PERF: Define Block.__init__ in cython

### PR DESCRIPTION
**Pull request by jbrockmendel**
Shaves about 10% off the benchmark discussed in https://github.com/pandas-dev/pandas/pull/40171#issuecomment-790219422

### CODE REVIEW

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
lgtm. maybe some of these checks are stuck.

**Comment by jbrockmendel** [comment]
green

**Comment by jreback** [comment]
can u rebase

**Comment by jbrockmendel** [comment]
rebased + green

**Pull request merged**
