### PR TITLE
CI: use dateutil-master in testing

### LINKED ISSUE #18332: CI: use dateutil master
revert this https://github.com/pandas-dev/pandas/pull/18325

when #18141 is a bit more stable

### PR DESCRIPTION
**Pull request by jreback**
closes #18332

### CODE REVIEW

**Comment by jreback** [comment]
cc @pganssle 

```
(pandas) bash-3.2$ pytest pandas/tests/tslibs/test_parsing.py --tb=short
=============================================================================================================================== test session starts ===============================================================================================================================
platform darwin -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /Users/jreback/pandas, inifile: setup.cfg
plugins: xdist-1.20.1, forked-0.2, cov-2.5.1, hypothesis-3.38.5
collected 42 items                                                                                                                                                                                                                                                                

pandas/tests/tslibs/test_parsing.py ......ssssssssssssssFFsssFFF.ssssssFFFFFF.                                                                                                                                                                                              [100%]

==================================================================================================================================== FAILURES =====================================================================================================================================
__________________________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_with_dayfirst_gt_261[True] __________________________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:146: in test_guess_datetime_format_with_dayfirst_gt_261
    assert result is None
E   AssertionError: assert '%d/%m/%Y' is None
_________________________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_with_dayfirst_gt_261[False] __________________________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:146: in test_guess_datetime_format_with_dayfirst_gt_261
    assert result is None
E   AssertionError: assert '%m/%d/%Y' is None
_______________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_with_locale_specific_formats_gt_261[30/Dec/2011] _______________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:172: in test_guess_datetime_format_with_locale_specific_formats_gt_261
    assert result is None
E   AssertionError: assert '%d/%b/%Y' is None
____________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_with_locale_specific_formats_gt_261[30/December/2011] _____________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:172: in test_guess_datetime_format_with_locale_specific_formats_gt_261
    assert result is None
E   AssertionError: assert '%d/%B/%Y' is None
__________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_with_locale_specific_formats_gt_261[30/Dec/2011 00:00:00] ___________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:172: in test_guess_datetime_format_with_locale_specific_formats_gt_261
    assert result is None
E   AssertionError: assert '%d/%b/%Y %H:%M:%S' is None
__________________________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_nopadding_gt_261[2011-1-1] __________________________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:220: in test_guess_datetime_format_nopadding_gt_261
    assert result is None
E   AssertionError: assert '%Y-%m-%d' is None
_________________________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_nopadding_gt_261[30-1-2011] __________________________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:220: in test_guess_datetime_format_nopadding_gt_261
    assert result is None
E   AssertionError: assert '%d-%m-%Y' is None
__________________________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_nopadding_gt_261[1/1/2011] __________________________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:220: in test_guess_datetime_format_nopadding_gt_261
    assert result is None
E   AssertionError: assert '%m/%d/%Y' is None
_____________________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_nopadding_gt_261[2011-1-1 00:00:00] ______________________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:220: in test_guess_datetime_format_nopadding_gt_261
    assert result is None
E   AssertionError: assert '%Y-%m-%d %H:%M:%S' is None
_______________________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_nopadding_gt_261[2011-1-1 0:0:0] _______________________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:220: in test_guess_datetime_format_nopadding_gt_261
    assert result is None
E   AssertionError: assert '%Y-%m-%d %H:%M:%S' is None
______________________________________________________________________________________________ TestGuessDatetimeFormat.test_guess_datetime_format_nopadding_gt_261[2011-1-3T00:00:0] ______________________________________________________________________________________________
pandas/tests/tslibs/test_parsing.py:220: in test_guess_datetime_format_nopadding_gt_261
    assert result is None
E   AssertionError: assert '%Y-%m-%dT%H:%M:%S' is None
================================================================================================================= 11 failed, 8 passed, 23 skipped in 0.36 seconds =================================================================================================================
```

**Comment by pganssle** [comment]
@jreback A lot of these seem to be "breaking" in that you expect to be unable to infer the format, but now you are able to. Am I understanding this correctly?

**Comment by pganssle** [comment]
CC @jbrockmendel

**Comment by jreback** [comment]
yeah we prob just need to adjust the tests.

**Pull request merged**
