### PR TITLE
MAINT: Remove self.assertTrue from testing

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.

Partially addresses #15990.

### CODE REVIEW

**Comment by gfyoung** [comment]
Appveyor failing due to network issues.  Travis and Circle seem okay.

@jreback : Could you restart the Appveyor build?

**Comment by jreback** [comment]
yeah those are 'network' tests that don't have the decorator! (as I think there is some interaction with parametrize).

**Comment by jreback** [comment]
thanks!

**Comment by gfyoung** [comment]
> yeah those are 'network' tests that don't have the decorator!

Is there a reason the `tm.network` decorator is not applied?

**Comment by jreback** [comment]
> Is there a reason the tm.network decorator is not applied?

I think I briefly tried it and couldn't get it to work when the parameterize one was as well.
give it a shot!

**Comment by gfyoung** [comment]
The test is actually decorated because the function called has the `tm.network`.  I suspect it's because network failures are supposed to trigger test failures per the documentation of `tm.network`.

**Pull request merged**
