### PR TITLE
DOC: Fix indendation in docstring sort_values  'by' parameter 

### PR DESCRIPTION
**Pull request by stijnvanhoey**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Current version looks like:
```
Parameters
----------
        by : str or list of str
            Name or list of names to sort by.

            - if `axis` is 0 or `'index'` then `by` may contain index
              levels and/or column labels.
            - if `axis` is 1 or `'columns'` then `by` may contain column
              levels and/or index labels.
axis : {0 or 'index', 1 or 'columns'}, default 0
     Axis to be sorted.
```

### CODE REVIEW

**Comment by mroeschke** [comment]
How does this render in the docs?

IMO it looks fine currently? https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

**Comment by stijnvanhoey** [comment]
> How does this render in the docs?

Indeed, this look good in the sphinx rendered version. But when I checked the text-version (inside notebook or ipython), it looks like:

image

**Comment by mroeschke** [comment]
> this PR fixes the latter.

Ah okay. Could you double check the sphinx rendered version looks okay too (screenshot of a local rendered doc is fine)?

**Comment by stijnvanhoey** [comment]
Good point, I checked and seems ok
image

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @stijnvanhoey

**Pull request merged**
