### PR TITLE
CLN: remove compat.iterkeys

### PR DESCRIPTION
**Pull request by topper-123**
- [x] xref #25725

Removes ``compat.iterkeys``.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]
Failure related to https://github.com/pandas-dev/pandas/issues/26069

**Comment by topper-123** [comment]
Thanks @mroeschke , I was not certain if the error was something I wasnt catching locally.

**Comment by gfyoung** [comment]
@topper-123 : If you can address the merge conflicts from merging your other PR, this should be good to go.

**Comment by topper-123** [comment]
Rebased.

**Comment by jreback** [comment]
thanks @pep8speaks

**Pull request merged**
