### PR TITLE
DOC: Clarify behaviour of pd.merge

### LINKED ISSUE #34412: DOC:/USAGE: Resulting Index when merging over indices
#### Location of the documentation

https://dev.pandas.io/docs/reference/api/pandas.DataFrame.merge.html

#### Documentation problem

There is no documentation on this case

#### Suggested fix for documentation

I'm a bit confused about the behavior here, because I don't know what to expect. When I perform the merge as shown below, I would expect that both operations return the same output.

```
left = pd.DataFrame({'a': [1, 2], 'b': [1, 1], "l": [22, 23]}).set_index(['a', 'b'])
right = pd.DataFrame({'b': [1], "r": [12]}).set_index(['b'])
print(pd.merge(left, right, left_on=['b'], right_index=True, how="left"))
print(pd.merge(left, right, left_on=['b'], right_on=["b"], how="left"))
```

But the Index of both results differs. The first merge has the same index as the left `DataFrame` while the second merge has only `b` as index. As a result, the index from the second merge is no longer unique.

**First Merge:**
```
      l   r
a b        
1 1  22  12
2 1  23  12
```

**Second Merge:**

```
    l   r
b        
1  22  12
1  23  12
```

**If** this is the desired behavior, we should adjust the documentation to show this. If it is not, I would file an BUG issue. We should adjust the documentation nevertheless. I would add an example with an index join to show the right behavior.

### PR DESCRIPTION
**Pull request by bharatr21**
- [x] Closes #34412 (also attempts to clarify #34273)
- [x] tests added / passed (passes `scripts/validate_docstrings.py`)
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry (Not needed)

### CODE REVIEW

**Comment by phofl** [comment]
We should discuss first if this is the expected behavior. Imo that is pretty weird. The join is exactly the same for both cases, but the result is different. Does not seem consistent.

**Review by jreback — CHANGES_REQUESTED** [review]
yeah this actually looks like a bug

**Comment by Bharat123rox** [comment]
@jreback what should the expected behaviour be? Also, some guidance through this part of the code would help (I believe this is responsible for the behaviour):
https://github.com/pandas-dev/pandas/blob/433c9007781080658553fbef1a4d0c2813b404c0/pandas/core/reshape/merge.py#L876-L884

**Comment by WillAyd** [comment]
I think the index from left should be preserved in both cases no? So the second example is incorrect IMO

**Comment by WillAyd** [comment]
@Bharat123rox can you try to identify the code paths that cause this inconsistency?

**Comment by WillAyd** [comment]
Closing for now as I don't think this is something that we should document; probably needs some more discussion on the original issue and a fix to the code instead

**Pull request closed without merging**
