### PR TITLE
PERF: Use list comprehension to join strings (#41753)

### PR DESCRIPTION
**Pull request by ghost**
PERF: Use list comprehension to join strings (#41753)

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks @vrserpa - if you fetch and merge upstream/master that should fix the pre-commit failure

Are you interested in writing a linting check for this in [pandas-dev-flaker](https://github.com/pandas-dev/pandas-dev-flaker)?

**Comment by vrserpa** [comment]
Hi @MarcoGorelli, I will write a linting check for [pandas-dev-flaker](https://github.com/pandas-dev/pandas-dev-flaker).

**Comment by MarcoGorelli** [comment]
awesome, thanks, let me know if you want/need any help with that - I expect you'd be able to model it off of https://github.com/asottile/pyupgrade/blob/5fb168667ae73f157dd579344708e1cdfb0c0341/pyupgrade/_plugins/generator_expressions_pep289.py

**Comment by vrserpa** [comment]
Thanks @MarcoGorelli! I'm going to have a look at this.

**Comment by MarcoGorelli** [comment]
Hi @vrserpa - can you fetch and merge upstream/master?

**Comment by vrserpa** [comment]
Ok!

**Comment by MarcoGorelli** [comment]
can you fixup the pre-commit failures please? https://pandas.pydata.org/docs/development/contributing_codebase.html#pre-commit

**Comment by vrserpa** [comment]
Sorry, @MarcoGorelli. I did the check with pre-commit now.

**Review by MarcoGorelli — APPROVED** [review]
looks good to me pending green

**Comment by mroeschke** [comment]
@MarcoGorelli will this be automatically checked in the CI/precommit?

**Comment by MarcoGorelli** [comment]
once https://github.com/pandas-dev/pandas-dev-flaker/pull/26 is in, yup!

**Pull request merged**
