### PR TITLE
CLN: resolve DeprecationWarning in `pandas/_testing.py` #35942

### LINKED ISSUE #35942: CLN: DeprecationWarning in `_testing`
```
pandas/tests/indexes/test_index_new.py::TestIndexConstructorInference::test_constructor_infer_nat_dt_like[<NA>-DatetimeIndex-datetime64[ns]-ctor0-0]
pandas/tests/indexes/test_index_new.py::TestIndexConstructorInference::test_constructor_infer_nat_dt_like[<NA>-DatetimeIndex-datetime64[ns]-ctor0-0]
pandas/tests/indexes/test_index_new.py::TestIndexConstructorInference::test_constructor_infer_nat_dt_like[<NA>-DatetimeIndex-datetime64[ns]-ctor0-1]
pandas/tests/indexes/test_index_new.py::TestIndexConstructorInference::test_constructor_infer_nat_dt_like[<NA>-DatetimeIndex-datetime64[ns]-ctor0-1]
pandas/tests/indexes/test_index_new.py::TestIndexConstructorInference::test_constructor_infer_nat_dt_like[<NA>-TimedeltaIndex-timedelta64[ns]-ctor1-0]
pandas/tests/indexes/test_index_new.py::TestIndexConstructorInference::test_constructor_infer_nat_dt_like[<NA>-TimedeltaIndex-timedelta64[ns]-ctor1-0]
pandas/tests/indexes/test_index_new.py::TestIndexConstructorInference::test_constructor_infer_nat_dt_like[<NA>-TimedeltaIndex-timedelta64[ns]-ctor1-1]
pandas/tests/indexes/test_index_new.py::TestIndexConstructorInference::test_constructor_infer_nat_dt_like[<NA>-TimedeltaIndex-timedelta64[ns]-ctor1-1]
  /home/fangchenli/Workspace/pandas-VirosaLi/pandas/_testing.py:790: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
    diff = np.sum((left.values != right.values).astype(int)) * 100.0 / len(left)

```

### PR DESCRIPTION
**Pull request by fangchenli**
- [x] closes #35942
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks for the PR. Can you confirm that this is the correct fix? On master I see this

```
> /Users/taugspurger/sandbox/pandas/pandas/_testing.py(790)assert_index_equal()
-> diff = np.sum((left.values != right.values).astype(int)) * 100.0 / len(left)
(Pdb) left
Index([<NA>, NaT], dtype='object')
(Pdb) left.values
array([<NA>, numpy.datetime64('NaT')], dtype=object)
(Pdb) right.values
array([<NA>, NaT], dtype=object)
(Pdb) pp np.no
np.nonzero    np.not_equal
(Pdb) pp np.not_equal(left.values, right.values)
*** TypeError: boolean value of NA is ambiguous
```

Are we raising a TypeError but not seeing it since the test is xfailed?

**Comment by VirosaLi** [comment]
> Thanks for the PR. Can you confirm that this is the correct fix? On master I see this
> 
> ```
> > /Users/taugspurger/sandbox/pandas/pandas/_testing.py(790)assert_index_equal()
> -> diff = np.sum((left.values != right.values).astype(int)) * 100.0 / len(left)
> (Pdb) left
> Index([<NA>, NaT], dtype='object')
> (Pdb) left.values
> array([<NA>, numpy.datetime64('NaT')], dtype=object)
> (Pdb) right.values
> array([<NA>, NaT], dtype=object)
> (Pdb) pp np.no
> np.nonzero    np.not_equal
> (Pdb) pp np.not_equal(left.values, right.values)
> *** TypeError: boolean value of NA is ambiguous
> ```
> 
> Are we raising a TypeError but not seeing it since the test is xfailed?

There are 4 xfail at `pandas/tests/indexes/test_index_new.py:99`. Before the change, it was an
`AttributeError: 'bool' object has no attribute 'astype'`. After the change, it became `TypeError: boolean value of NA is ambiguous`.

**Comment by TomAugspurger** [comment]
Right, do we want that TypeError? What's the desired behavior?

**Comment by VirosaLi** [comment]
> Right, do we want that TypeError? What's the desired behavior?

Not sure about this. Might need some discussion. xref #31884

**Pull request closed without merging**
