### PR TITLE
BUG: Index.insert may not coerced to correct dtype

### PR DESCRIPTION
**Pull request by sinhrks**
- [x] tests added / passed
- [x] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry
### on current master

```
# NG, must be float dtype
pd.Index([1]).insert(1, 1.0)
# Int64Index([1, 1], dtype='int64')

# NG, must be object dtype
pd.DatetimeIndex(['2011-01-01']).insert(1, 1)
# TypeError: cannot insert DatetimeIndex with incompatible label
```
## after the PR

```
pd.Index([1]).insert(1, 1.0)
# Float64Index([1.0, 1.0], dtype='float64')

pd.DatetimeIndex(['2011-01-01']).insert(1, 1)
# Index([2011-01-01 00:00:00, 1], dtype='object')
```

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I would keep this for 0.20, as it are some slight changes without a pressing bug fix (unless you have an example case?)

Further, are we sure that we want to upcast the Int64Index to floats, even when the value set is coerceable to a integer? 
Using another (series and indexing, not index and `insert`), but similar case:

```
In [145]: s = pd.Series([2,2,3,4])

In [146]: s[2] = 5.0

In [147]: s
Out[147]: 
0    2
1    2
2    5
3    4
dtype: int64
```

Here the integer dtype is preserved.

**Comment by jreback** [comment]
can you update?

**Comment by jreback** [comment]
@sinhrks status?

**Comment by jreback** [comment]
can you rebase / update

**Comment by jreback** [comment]
issue now in #16277

**Pull request closed without merging**
