### PR TITLE
CI: Try out pre-commit.ci again

### PR DESCRIPTION
**Pull request by mroeschke**
Will need to enable the pre-commit Github app

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
does it fit into the time limit now? I remember that being an issue, but now we've moved from flake8 to ruff and are building black using the wheels

**Comment by mroeschke** [comment]
I still need to turn on the pre-commit Github app to test with this PR, but I'm hopeful that we shouldn't timeout anymore

**Comment by MarcoGorelli** [comment]
oh wow, it's actually within the limit now! neat

**Comment by lithomas1** [comment]
> @MarcoGorelli looks like pre-commit CI completes in less than 3 minutes and the autofix PR feature is working pretty nicely

Pls turn off autofix. It was really annoying the last time it was briefly on, at least for me.

Is there a way to make it trigger on a comment instead (like the old comment bot)?

**Comment by mroeschke** [comment]
> Pls turn off autofix. It was really annoying the last time it was briefly on, at least for me.

Sure, just curious what you found annoying about autofix?

There is a separate command for running the fix if autofix is turned off

**Comment by mroeschke** [comment]
> Is there an opt out mechanism for users, or is autofix by repository?

I think it's autofix by repo.

The latest commit has autofix turned off. A comment command to autofix is perfectly fine

**Comment by mroeschke** [comment]
Since this new configuration is essentially preserves the same checking and autoupdating (the config not PRs) state as before just with pre-commit CI going to merge. Can follow up if needed

**Pull request merged**
