### PR TITLE
BUG: maybe_promote with dt64tz and mismatched NA

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
user facing?

**Comment by jbrockmendel** [comment]
> user facing?

trying to track this down; many of the cases that _would_ be affected go through DTA/TDA/PA methods instead of maybe_promote

**Comment by jbrockmendel** [comment]
> user facing?

so far it looks like the answer is "no", but that the reason involves incorrect NAs being ignored somewhere else that i need to track down separately

**Comment by jbrockmendel** [comment]
> user facing?

increasingly looking like "no"

**Comment by jbrockmendel** [comment]
OK im now almost positive there is nothing user-facing bc 1) the only currently-incorrect case is in the dt64tz path and 2) that path is AFAICT not reachable by any of the non-test uses of maybe_promote

**Comment by jreback** [comment]
ok can you rebase

**Comment by jbrockmendel** [comment]
rebased + green (no longer a bugfix, just a refactor)

**Pull request merged**
