### PR TITLE
remove direct import of nan

### PR DESCRIPTION
**Pull request by jbrockmendel**
Is there a tag I can put into the PR to avoid having a full Travis run for tiny things like this?

 - [ ] closes #xxxx
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master -u -- "*.py" | flake8 --diff``
 - [ ] whatsnew entry

### CODE REVIEW

**Comment by gfyoung** [comment]
@jbrockmendel : If you add `[ci skip]` to your commit, that will stop the builds.  However, even in cases like this, you should let the builds run just in case.

**Comment by jreback** [comment]
thanks. pls try to phrase things more idiomaticallly. 'get rid of' is slang.

**Comment by jorisvandenbossche** [comment]
@jreback dev workflow related thing: you don't need to merge locally to change the commit message, you can just do that with the github merge button

**Comment by jreback** [comment]
i changed the actual commit message which u can't do from the screen

**Comment by jorisvandenbossche** [comment]
> i changed the actual commit message which u can't do from the screen

Yes, you can. After the first click on 'squash and merge' you see a dialog to edit the commit message, no?

**Comment by jbrockmendel** [comment]
> thanks. pls try to phrase things more idiomaticallly. 'get rid of' is slang.

Will do.  Thanks for helping me along the learning curve.

**Pull request closed without merging**
