### PR TITLE
check azure build

### PR DESCRIPTION
**Pull request by TomAugspurger**
This should fail the numpydev build on azure.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I'll try to turn this into a proper test that can actually be merged later.

**Comment by jreback** [comment]
> One possible option is to add a filterwarning to raise all warnings coming from pandas itself to all the builds. I think pytest supports something like that.

this is what setting PANDAS_TESTING_MODE is for (but could migrate to pytest explicity), though using
``-W error::DeprecationWarning`` I could not get things to fail

**Comment by jorisvandenbossche** [comment]
Something else: locally my pytest "warning summary" includes which test the warning is coming from. Anybody know why this is not the case on travis / azure?

**Comment by TomAugspurger** [comment]
Do you get the test name when running multiple jobs with pytest-xdist?

**Comment by jorisvandenbossche** [comment]
I typically don't use that, but tested now some tests with `-n 2`, and still get the name of the test in the warning summary:

```
(dev) joris@joris-XPS-13-9350:~/scipy/pandas$ pytest pandas/tests/io/test_pytables.py -n 2
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.5.5, pytest-3.6.2, py-1.5.4, pluggy-0.6.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/joris/scipy/pandas/.hypothesis/examples')
rootdir: /home/joris/scipy/pandas, inifile: setup.cfg
plugins: xdist-1.25.0, repeat-0.4.1, forked-0.2, hypothesis-3.70.3
gw0 [182] / gw1 [182]
......................................................................................................x.................................................s.............................                       [100%]
================================================================================================= warnings summary =================================================================================================
pandas/tests/io/test_pytables.py::TestHDFStore::()::test_legacy_table_read
  /home/joris/scipy/pandas/pandas/io/pytables.py:3953: FutureWarning: 
  Panel is deprecated and will be removed in a future version.
  The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
  Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
  Pandas provides a `.to_xarray()` method to help automate this conversion.
  
    return super(LegacyFrameTable, self).read(*args, **kwargs)['value']
  /home/joris/scipy/pandas/pandas/io/pytables.py:730: FutureWarning: 
  Panel is deprecated and will be removed in a future version.
  The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
  Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
  Pandas provides a `.to_xarray()` method to help automate this conversion.
  
    columns=columns)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
========================================================================== 180 passed, 1 skipped, 1 xfailed, 2 warnings in 25.33 seconds ===========================================================================
```

**Comment by TomAugspurger** [comment]
The downside is that new warnings from those libraries, and their dependencies, now fail our build. It’s maybe worth trying for a bit provisionally.


________________________________

**Comment by TomAugspurger** [comment]
I'm probably not getting back to this anytime soon. Closing for now.

**Pull request closed without merging**
