### PR TITLE
Add lag parameter to autocorrelation

### PR DESCRIPTION
**Pull request by omtinez**
Add lag parameter to autocorrelation, default to lag-1 autocorrelation so existing code will work unchanged.

### CODE REVIEW

**Comment by omtinez** [comment]
This is not good! Failure unrelated to my commit:

======================================================================
FAIL: test_tquery (pandas.io.tests.test_sql.TestXMySQL)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pydata/pandas/pandas/io/tests/test_sql.py", line 2238, in test_tquery
    tm.assert_series_equal(result, expected)
  File "/home/travis/build/pydata/pandas/pandas/util/testing.py", line 674, in assert_series_equal
    assert_almost_equal(left.values, right.values, check_less_precise)
  File "testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2556)
  File "testing.pyx", line 93, in pandas._testing.assert_almost_equal (pandas/src/testing.c:1794)
  File "testing.pyx", line 140, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2390)
AssertionError: expected -1.00016 but got -1.00015, with decimal 5

Have you seen this before?

**Comment by jreback** [comment]
@omtinez pls add a release note 0.16.0 enhancements section. and then squash. looks ok otherwise.

**Comment by jreback** [comment]
ok this seems ok. pls rebase on master and squash. ping when green.

**Comment by omtinez** [comment]
Sorry about the mess, new to Git. I squashed the changes and now both autocorrelation-lag and master in my repo should reflect all of my desired changes.

**Comment by TomAugspurger** [comment]
@omtinez looks like you may have closed the pull request on accident. Could you reopen it?

**Comment by omtinez** [comment]
For some reason, github closed my pull request and now sees zero commits in my branch. I tried doing a git push -f just to see if github would pick up my commit then but no dice: https://github.com/omtinez/pandas/commit/56739a10e02b18951dfe5c22decfa7de41151fdb

Github won't let me reopen unless it sees the commit, is there a way to fix this or do I need to open a new pull request?

**Pull request closed without merging**
