### PR TITLE
BUG: DataFrame.from_records doesn't raise proper error message when Series passed

### LINKED ISSUE #40429: DataFrame.from_records fails when the argument is Series with non-default index
Summary: if `from_records` is called upon a `Series` with index that doesn't start with `0`, it fails.

```python
import pandas as pd
print(f'Pandas version is {pd.__version__}')
data = pd.Series([{'a': 1, 'b': 2}, {'a': 11, 'b': 22}], index=[10, 20])
pd.DataFrame.from_records(data.values) # works
pd.DataFrame.from_records(data)  # fails
```

Output

```text
Pandas version is 1.2.1
Traceback (most recent call last):
  File "/Users/boris/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1625, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1632, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0
....
```

### PR DESCRIPTION
**Pull request by hasan-yaman**
- [x] closes #40429 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by phofl** [comment]
Since this was tested, should we deprecate these cases first?

**Comment by mzeitlin11** [comment]
The docs say include `sequence of tuples or dicts` as an input option, so continuing to support that seems fine (or at least should be deprecated). So those tests probably shouldn't be deleted.

**Comment by hasan-yaman** [comment]
Passing series will give an error and according to docs Series are not supported  (#40429 ).
With the PR, pandas will continue to support `sequence of tuples or dicts` and it will give more appropriate error message when Series passed.

**Comment by hasan-yaman** [comment]
By the way, any suggestion to fix failing typing error?

**Comment by datapythonista** [comment]
Thanks for the contribution @hasan-yaman 

I think it makes more sense if `DataFrame.from_records(data=Series([1, 2, 3]))` just returns `data.to_frame()`. The code here looks cumbersome, and likely to cause problems in the future. @jreback what do you think?

One question @hasan-yaman, why are you removing tests? I guess I'm missing something, but existing tests should be kept, and a new one passing a `Series` should be added. Removing or editing tests while changing existing code is dangerous.

**Comment by simonjayhawkins** [comment]
@hasan-yaman can you address @datapythonista comments

**Comment by mroeschke** [comment]
Thanks for the PR, but it appears to have gone stale and needs follow up from the other reviewers. Closing, but happy to open if you're interested on continuing.

**Pull request closed without merging**
