### PR TITLE
Backport PR #42318: PERF/REGR: symmetric_difference revert most of #41833

### PR DESCRIPTION
**Pull request by simonjayhawkins**
Backport PR #42318

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
xref https://github.com/pandas-dev/pandas/pull/42318#issuecomment-871255858
```
       before           after         ratio
     [f34376d1]       [ea963bf8]
     <1.3.x>          <backport-of-pr-42318-on-1.3.x>
-      83.0±0.6ms       48.0±0.2ms     0.58  multiindex_object.SetOperations.time_operation('monotonic', 'string', 'symmetric_difference')
-      1.11±0.01s         643±10ms     0.58  multiindex_object.SetOperations.time_operation('monotonic', 'datetime', 'symmetric_difference')
-      83.5±0.8ms       47.8±0.6ms     0.57  multiindex_object.SetOperations.time_operation('non_monotonic', 'string', 'symmetric_difference')
-       102±0.9ms       58.1±0.4ms     0.57  multiindex_object.SetOperations.time_operation('non_monotonic', 'int', 'symmetric_difference')
-       103±0.4ms       58.2±0.8ms     0.57  multiindex_object.SetOperations.time_operation('monotonic', 'int', 'symmetric_difference')
-      1.14±0.01s          643±3ms     0.56  multiindex_object.SetOperations.time_operation('non_monotonic', 'datetime', 'symmetric_difference')
-      7.14±0.1ms      3.97±0.08ms     0.56  index_object.SetOperations.time_operation('datetime', 'symmetric_difference')
-      5.18±0.1ms      2.85±0.04ms     0.55  index_object.SetOperations.time_operation('int', 'symmetric_difference')
-      30.4±0.6ms       16.0±0.4ms     0.53  index_object.SetOperations.time_operation('date_string', 'symmetric_difference')
-      28.7±0.4ms       14.7±0.2ms     0.51  index_object.SetOperations.time_operation('strings', 'symmetric_difference')

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.
```

**Review by jbrockmendel — APPROVED** [review]
I'm pre-caffeine, but this looks identical to the reversion I did last night (with an extra `cast`), in which case LGTM.

**Comment by simonjayhawkins** [comment]
removed MultiIndex symmetric_difference also

**Comment by jbrockmendel** [comment]
> removed MultiIndex symmetric_difference also

Huh, i thought i had done that in the other one.  LGTM.

**Pull request merged**
