### PR TITLE
Release 0.23.1 backports part I

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Review by TomAugspurger — APPROVED** [review]

**Comment by TomAugspurger** [comment]
I wonder, was the travis build skipped because of a `[ci skip]` in a commit message?

**Comment by jorisvandenbossche** [comment]
Hmm, don't know. But wouldn't that only skip that commit?

**Comment by TomAugspurger** [comment]
Not sure:
https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build
seems to suggest it's only the HEAD commit.

**Comment by jorisvandenbossche** [comment]
Added a single extra commit to see if that helps.

**Pull request merged**
