### PR TITLE
Bump up minimum numpy version in windows37 job

### LINKED ISSUE #34724: CI: window 37_141 jobs needs to update numpy version
https://github.com/pandas-dev/pandas/blob/master/ci/deps/azure-windows-37.yaml

we no longer support this, I guess it *still* works ok. But we should advance this job to be numpy 1.15* at least, i would say we should actually test numpy 1.18* here.

might also need to actually rename the job to reflect the update.

### PR DESCRIPTION
**Pull request by bharatr21**
- [x] closes #34724 
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
Can you update the name of the job to reflect the numpy version?

https://github.com/pandas-dev/pandas/blob/a29cee3e0b4f1bf5f91ed7e27ebb3c6d01f47c5e/ci/azure/windows.yml#L16

**Review by WillAyd — APPROVED** [review]
lgtm @jreback

**Comment by jreback** [comment]
thanks @Bharat123rox

**Comment by simonjayhawkins** [comment]
> Can you update the name of the job to reflect the numpy version?

we no longer have Travis since this change.

**Comment by simonjayhawkins** [comment]
> > Can you update the name of the job to reflect the numpy version?
> 
> we no longer have Travis since this change.

it's back. must be unrelated.

**Comment by jreback** [comment]
this is an azure job

**Pull request merged**
