### PR TITLE
CI: Revert splitting 3.10 tests

### LINKED ISSUE #44173: CI: 310-dev build seems to be timing out
xref https://github.com/pandas-dev/pandas/runs/3990827693?check_suite_focus=true

not sure where this changed recently or a numpy issue.

### PR DESCRIPTION
**Pull request by lithomas1**
Maths says this should work now.

- [ ] closes #44173
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Don't backport.

### CODE REVIEW

**Comment by jreback** [comment]
hmm something taking a long time

**Comment by lithomas1** [comment]
> hmm something taking a long time

Not the Python 3.10 tests, though. Just the usual suspects :)

**Comment by lithomas1** [comment]
gentle ping @jreback. This is ready.

**Comment by jreback** [comment]
can u rebase once more

**Review by mroeschke — APPROVED** [review]

**Comment by jreback** [comment]
thanks @lithomas1

**Pull request merged**
