### PR TITLE
DOC: Update mypy version in whatsnew

### PR DESCRIPTION
**Pull request by phofl**
- [x] whatsnew entry

Forgot this in #39407

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]
Thanks @phofl

**Comment by phofl** [comment]
Is backporting here necessary? Meaning regression fixes which do not pass with old mypy?

**Comment by simonjayhawkins** [comment]
> Is backporting here necessary?

no we keep the style checks etc on the backport branch unchanged.

so ci on 1.2.x uses mypy 0.782 and we need to make changes to autobackports if they fail the ci.

**Comment by phofl** [comment]
Ah thanks for the info

**Pull request merged**
