### PR TITLE
CLN: Removed class in pandas/tests/series/test_timezones.py

### PR DESCRIPTION
**Pull request by SaturnFromTitan**
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by SaturnFromTitan** [comment]
This is similar to #32184. Nothing in the tests changed, I just removed the unused class interface to simplify the file

**Review by jreback — CHANGES_REQUESTED** [review]
I dont really see the point of removing the class. Assuming we aren't actually using the setup/teardown methods (which should be fixed), then all other thing equal this is not a big deal. is there anything different about this PR?

**Comment by SaturnFromTitan** [comment]
As we're not using any functionality of the class interface, then why have it? Having the class means...
1. it's harder to reason about the test: functions are more independent than methods
1. it forces `black` to use more line breaks (we reach the line limit earlier because of the extra indentation)
1. it adds more clutter

I think the class interface is just a left-over from #22550

**Comment by jreback** [comment]
> As we're not using any functionality of the class interface, then why have it? Having the class means...
> 
> 1. it's harder to reason about the test: functions are more independent than methods
> 2. it forces `black` to use more line breaks (we reach the line limit earlier because of the extra indentation)
> 3. it adds more clutter
> 
> I think the class interface is just a left-over from #22550

@SaturnFromTitan I get it, and generally i agree, however i also think we have *many* of these, so we are talking many PRs; so unless we are splitting out to separate modules I wouldn't change this. 

Now I could be wrong on the number, if you want to see how many single file with a class we have then I could change.

**Comment by SaturnFromTitan** [comment]
Gotcha. Indeed, there are 100+ files like that.

Even though the effort to change this is very small, I guess the review effort would be significant and would be better to be invested elsewhere. Closing this then

**Pull request closed without merging**
