### PR TITLE
Fixed bug #9733 where stat functions returned a python scalar for empty series

### LINKED ISSUE #9733: Series.sum has inconsistent return type
Series.sum returns a numpy type, except when it's empty, in which case it returns a python int of value "0":

```
In [2]: type(pd.Series([0]).sum())
Out[2]: numpy.int64

In [3]: type(pd.Series().sum())
Out[3]: int
```

This poses a problem when I do `1 / myserie.sum()` because I expect to obtain `np.inf` rather than a divison by 0 exception.

I think the return type of `Series.sum()` for empty series should be inferred from the Series's dtype This way, `Series([], dtype='str').sum()` would return an empty string, and `Series([]).sum()` would return `np.float64(0)` since an empty series' default type seems to be float64.

Tested with Pandas 0.16.0

### PR DESCRIPTION
**Pull request by remiremi**
closes #9733

### CODE REVIEW

**Comment by jreback** [comment]
can you run thru all dtypes (look in ``pandas/src/inference.pyx``) for a list
and do this for say ``sum/mean`` on empties and see what comes back and post it here. thanks.

**Comment by jreback** [comment]
@Remiremi can you update

**Comment by Remiremi** [comment]
Yes, I have updated unit tests to loop through types and methods.

For numpy types, I compare the result type with the equivalent function in numpy.

For the string types, I guess the result should be empty string for the sum and nan for the rest.

It still needs some work: https://github.com/pydata/pandas/compare/master...Remiremi:issue_9733_bis

Let me know if you don't think this is the right direction.

**Comment by jreback** [comment]
you can't change this line, otherwise other platforms will break
``the_sum = values.sum(axis, dtype=dtype_max)``

``uints`` are very odd, not sure how to handle all this

**Comment by jreback** [comment]
@remiremi can you update? I

**Comment by jreback** [comment]
can you rebase / update?

**Comment by jreback** [comment]
@remiremi this looked ok, but I would like to run thru a number of dtypes comprehensively for this.

**Comment by jreback** [comment]
need a release note as well

**Comment by remiremi** [comment]
Just found some time to update the pull request, and added mention in v0.17.0.txt. Let me know

**Comment by jreback** [comment]
@remiremi well, you have taken on a task here. Can you update for the failures.

**Comment by remiremi** [comment]
Mmmh yes, my fix is taking the wrong approach. I'll update later this week.

**Comment by remiremi** [comment]
Just updated the branch but there's still a test failure (in test_resample, test_aggregate_with_nat). It looks to me like a bug in TimeGrouper. It somehow calls nanprod on an empty series, which expectedly returns 1.

**Comment by jreback** [comment]
@remiremi this whole thing is a can of worms, I have a very similar fix, see [here](https://github.com/pydata/pandas/pull/10815) for #9422 

but actually getting this to work is annoying. Because the tests are now dependent on whether bottleneck is installed for testing (and what version), e.g. < 1.0 is the old behavior, >= 1.0 is the new. To make more complicated we actually turn off bottleneck for testing several places (though that is now fixed and consistent).

So need to fix both these issues, and they follow pretty much the same general soln. Want to have go?

**Comment by remiremi** [comment]
Yeah, will give it a shot when I have some time next week

**Comment by remiremi** [comment]
@jreback I rebased today and ran the tests locally and the test test_aggregate_with_nat from test_resample is now successful! Do you know what change might have fixed the issue in TimeGrouper's groupby?

I guess all that needs to be done now is to make sure the tests still pass with both bottle < 1.0 and bottle >= 1.0, right?

**Comment by remiremi** [comment]
All tests passed with bottleneck 1.0 but there was a failure with 0.8... Getting closer

**Comment by jreback** [comment]
I know this is a beast!

closing, but pls reopen if you'd like to work on this again.

**Pull request closed without merging**
