### PR TITLE
MAINT: Use float arange when required or intended

### PR DESCRIPTION
**Pull request by bashtage**
Ensure arange is float when intened or required by NumPy

- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

### CODE REVIEW

**Comment by bashtage** [comment]
Use float initialization to allow NaN to be set of when setting floating points later.

**Comment by bashtage** [comment]
Used to be part of #35427, but split it out to have one PR one issue.  Required by Future NumPy.

**Comment by bashtage** [comment]
Fixes about 12 of the np-dev fails.

**Review by WillAyd — APPROVED** [review]
lgtm

**Review by simonjayhawkins — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
Thanks @bashtage

**Comment by simonjayhawkins** [comment]
@MeeseeksDev backport to 1.1.x

**Pull request merged**
