### PR TITLE
CLN: Remove unused is_datetimelike arg

### PR DESCRIPTION
**Pull request by dsaxton**

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]

**Comment by jbrockmendel** [comment]
are there any situations where we should be passing is_datetimelike in to the cython functions?

**Comment by dsaxton** [comment]
> are there any situations where we should be passing is_datetimelike in to the cython functions?

I'm not sure to be honest. Should the functions be able to infer that from `result` if needed?

**Comment by jbrockmendel** [comment]
> I'm not sure to be honest. Should the functions be able to infer that from result if needed?

I don't think so; any of the datetimelike dtypes will be cast to i8 before being passed to the cython funcs.

Even if we don't have a good answer for that question, this PR certainly doesnt make matters any worse, and is a nice cleanup.  LGTM.

**Comment by jreback** [comment]
thanks @dsaxton 
yeah this looks like some needed cleanup after a previous couple of refactortings.

**Pull request merged**
