### PR TITLE
REF: remove take_1d alias of take_nd

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
@jreback as discussed in https://github.com/pandas-dev/pandas/pull/39692

Since this is just an alias, this is certainly fine in theory. Although now doing it, I think there is still *some* value of the alias to signal that it is taking a 1D array which can provide useful context when *reading* code that uses this.

### CODE REVIEW

**Comment by jreback** [comment]
> @jreback as discussed in #39692
> 
> Since this is just an alias, this is certainly fine in theory. Although now doing it, I think there is still _some_ value of the alias to signal that it is taking a 1D array which can provide useful context when _reading_ code that uses this.

right . i think your next take_1d_array will make more sense (and consider actually naming IT take_1d)

**Comment by jorisvandenbossche** [comment]
Yes, but I am not directly planning on using the `take_1d_array` in places where I renamed `take_1d` here to `take_nd` (that would need checking of each of those cases whether they can guarantee already to be an array)

**Comment by jreback** [comment]
> Yes, but I am not directly planning on using the `take_1d_array` in places where I renamed `take_1d` here to `take_nd` (that would need checking of each of those cases whether they can guarantee already to be an array)

sure but its more clear now. thanks.

**Comment by lithomas1** [comment]
@jreback @jorisvandenbossche This is causing benchmarks CI to fail? 
```ImportError: cannot import name 'take_1d' from 'pandas.core.algorithms' (/home/runner/work/pandas/pandas/pandas/core/algorithms.py)```

**Comment by jreback** [comment]
@lithomas1 can u show where
this passed in master

**Comment by lithomas1** [comment]
I think this is it https://github.com/pandas-dev/pandas/runs/1875678358.

**Comment by jreback** [comment]
ahh the benchmarks 

ok - care to do a PR to fix

**Comment by jorisvandenbossche** [comment]
Whoops, sorry forgot to search/replace in the benchmarks

**Pull request merged**
