### PR TITLE
ENH: Add is_sparse method to check for sparse columns in a DataFrame (GH26706)

### LINKED ISSUE #26706: Recommended way to check for sparse data (DataFrame or Series)
Previously, you check for the SparseDataFrame class, but now we want people to store sparse data in normal DataFrames/Series. 

So for a library developer, what is the recommended way to check for sparse data?

For a Series (or SparseArray), the `pd.api.types.is_sparse` still works on a plain Series with sparse data:

```
In [42]: df = pd.DataFrame({'a': pd.SparseArray([1, np.nan, 1])}) 

In [43]: s = df['a']

In [44]: type(s)
Out[44]: pandas.core.series.Series

In [45]: pd.api.types.is_sparse(s)
Out[45]: True
```

but for a DataFrame that function does not work. So you could apply that method on each column/dtype, and check with `any` or `all` depending on your requirements:

```
In [56]: df = pd.DataFrame({'a': pd.SparseArray([1, np.nan, 1]), 'b': [1, 2, 3]})

In [57]: df.dtypes.apply(pd.api.types.is_sparse)
Out[57]: 
a     True
b    False
dtype: bool

In [58]: df.dtypes.apply(pd.api.types.is_sparse).any()
Out[58]: True

In [59]: df.dtypes.apply(pd.api.types.is_sparse).all()
Out[59]: False
```

So that actually works quite OK, now I am writing it. 
Do we want to make this even easier somehow? Or document this?

### PR DESCRIPTION
**Pull request by avinashpancham**
- [x] closes #26706 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by avinashpancham** [comment]
Implemented the method `df.is_sparse` and not the method `df.sparse.is_sparse`, since using the sparse accessor requires that all columns are sparse.

**Comment by topper-123** [comment]
Thanks, @avinashpancham.

Is this not too specific? I´d like better an is_dtype method, e.g. doing df.is_dtype(“sparse”).

@jorisvandenbossche

**Comment by topper-123** [comment]
Considering it again, I think:

>>> df = DataFrame({"A": SparseArray([1, np.nan, 1]), "B": [1, 2, 3]})
>>> df.dtypes == “sparse”
Series([True, False], index=["A", "B"])

would archieve the same and more general. Does the added method add anything over the above?

**Comment by avinashpancham** [comment]
The current imp does only that. That's also (part of) the reason why not everyone agreed on adding such a method

**Comment by topper-123** [comment]
Ok. IMO this method is too narrow to add to the dataframe namespace. So I`m -1 on this.

**Comment by avinashpancham** [comment]
Np, I will wait for others to share their opinion and then we can decide whether to continue with or close this PR

**Comment by jorisvandenbossche** [comment]
The actual proposal in the issue was to add this not in the "top-level" DataFrame namespace, but in the `sparse` accessor, so you would do like `df.sparse.is_sparse`. Given that we already have the `.sparse` accessor for sparse-related things, I personally don't think that it is "too specific".

Now, there is already a lot of discussion about it on the issue (https://github.com/pandas-dev/pandas/issues/26706), so let's have the discussion whether we want this or not there.

> Implemented the method df.is_sparse and not the method df.sparse.is_sparse, since using the sparse accessor requires that all columns are sparse.

Yes, to do that, we need to change the sparse accessor to also work when not all columns are sparse. 

> Considering it again, I think: ... `df.dtypes == sparse` ... would achieve the same and be more general. 

@topper-123 that's potentially a nice idea, but to be clear, that doesn't work currently, as far as I can see:

```
In [2]: df = DataFrame({"A": pd.arrays.SparseArray([1, np.nan, 1]), "B": [1, 2, 3]})

In [3]: df.dtypes == "sparse"
Out[3]: 
A    False
B    False
dtype: bool
```

(but the proposal can then be to make this work?)

**Comment by mroeschke** [comment]
Thanks for the PR but it appears we need further discussion on https://github.com/pandas-dev/pandas/issues/26706 on the API before moving forward with a PR. Closing

**Pull request closed without merging**
