### PR TITLE
STYLE double-quote cython strings #21

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
task here is:

add id: double-quote-cython-strings to

https://github.com/pandas-dev/pandas/blob/3d0d197cec32ed5ce30d28b922f329510c03f153/.pre-commit-config.yaml#L29

run pre-commit run double-quote-cython-strings --all-files

git add -u, git commit -m 'double quote cython strings', git push origin HEAD`

Motivation for this comes from https://github.com/pandas-dev/pandas/pull/49866#discussion_r1030853463

pyData 2022 sprint 
https://github.com/noatamir/pydata-global-sprints/issues/21

@jorisvandenbossche, @MarcoGorelli, @WillAyd, @rhshadrach, @phofl @noatamir

### CODE REVIEW

**Comment by phofl** [comment]
Cool! Could you merge main? There seems to be a conflict

**Comment by DeaMariaLeon** [comment]
> Cool! Could you merge main? There seems to be a conflict

Locally? or here? I got lost

**Comment by phofl** [comment]
Locally, and then you can push to this branch

**Comment by MarcoGorelli** [comment]
you'll do it locally, and then push - something like
```
git fetch upstream
git merge upstream/main
<fix up merge conflicts>
git add -u
git commit
git push origin HEAD
```

**Comment by DeaMariaLeon** [comment]
> git fetch upstream
> git merge upstream/main
> <fix up merge conflicts>
> git add -u
> git commit

Run the previous commands. After that there is a test that failed
```
double-quote Cython strings.............................................................................Failed
- hook id: double-quote-cython-strings
- exit code: 1
- files were modified by this hook
```
I still tried to push to my origin (maybe I shouldn't have) but then there is a message "Everything up-to-date"

**Comment by MarcoGorelli** [comment]
after that, you'll need to stage and commit again:
```
git add -u
git commit -a -m 'your commit message goes here'
```

**Comment by phofl** [comment]
Yep this means that the code you pulled still had single quotes. pre-commit fixed it, so if you commit again you should be good

**Comment by phofl** [comment]
Only if pre commit fails

**Comment by MarcoGorelli** [comment]
`pre-commit` will block your commit if any of the hooks' checks fail, or if they modified your files. here, one of them modified your files. so you'll need to stage (`git add -u`) and commit (`git commit -m 'commit message'`) again

**Review by phofl — APPROVED** [review]
Looks good!

**Comment by DeaMariaLeon** [comment]
Should I just wait now? :)

**Comment by phofl** [comment]
Yep the ci runs around 2 hours. We will merge after everything is green

**Comment by MarcoGorelli** [comment]
thanks @DeaMariaLeon !

**Comment by DeaMariaLeon** [comment]
Thanks All for your patience :)

**Pull request merged**
