### PR TITLE
STYLE start enabling TCH

### PR DESCRIPTION
**Pull request by MarcoGorelli**
This one should actually make a difference to performance, https://github.com/snok/flake8-type-checking#examples

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by twoertwein — APPROVED** [review]
Looks good to me but I believe we had a discussion in the past about that (I believe back then performance wasn't the goal so the outcome might be different now) @simonjayhawkins

**Comment by twoertwein** [comment]
xref https://github.com/pandas-dev/pandas/pull/47968 (moved non-`pandas._typing` imports into the `TYPE_CHECKING` block)

**Comment by twoertwein** [comment]
(Unrelated: ruff implements more and more of flake8-pyi, could potentially avoid flake8-pyi in a few weeks/months)

**Comment by MarcoGorelli** [comment]
> xref https://github.com/pandas-dev/pandas/pull/47968 (moved non-pandas._typing imports into the TYPE_CHECKING block)

yeah this seems like the same thing

agree on keeping `_typing` excluded, but we can start enabling it in other places - merging then, thanks for your review!

**Comment by twoertwein** [comment]
> agree on keeping `_typing` excluded, but we can start enabling it in other places - merging then, thanks for your review!

Personally, I would be fine moving even `pandas._typing` in the `TYPE_CHECKING` block. It might not be strictly needed but otherwise, we would need to add too many exceptions to enable TCH.

**Pull request merged**
