### PR TITLE
DEPR: casting date to dt64 in maybe_promote

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Once enforced, maybe_promote behavior will match DatetimeArray._validate_setitem_value and infer_dtype_from_scalar

sits on top of #39743

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
great can you add a whatsnew :>

**Comment by jbrockmendel** [comment]
> great can you add a whatsnew :>

whatsnew added + green

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks!

**Comment by jbrockmendel** [comment]
nice.  getting close to done with the maybe_promote stuff.  big outstanding one is #39769, then just numeric dtypes left

**Comment by jreback** [comment]
> nice. getting close to done with the maybe_promote stuff. big outstanding one is #39769, then just numeric dtypes left

done too!

**Pull request merged**
