### PR TITLE
CI: Fix ci flake error

### PR DESCRIPTION
**Pull request by charlesdong1991**
- [ ] xref #36305 
 came across it in #36305

### CODE REVIEW

**Comment by jreback** [comment]
hmm on master, ok thanks

**Comment by charlesdong1991** [comment]
@jreback I think an issue needs to be created to address this, it is the second time this happened: basically flake8 check doesn't detect `imported but unused` cases in feature PR, only detect the error once PR being merged to master.

Have seen it in #37923 and in #37703 , so ci checks ran successfully in those feature PRs, but actually they should have been detected this unused import.

**Comment by jreback** [comment]
hmm interesting, cc @MarcoGorelli

**Comment by jbrockmendel** [comment]
when ive seen this in the past it  has involved multiple PRs which independently are each correctly passed by flake8, only causing a problem when both are merged

**Comment by MarcoGorelli** [comment]
> when ive seen this in the past it has involved multiple PRs which independently are each correctly passed by flake8, only causing a problem when both are merged

I think this is the issue - in #37584 I got this exact error during the PR CI

**Comment by charlesdong1991** [comment]
ehh, okay, i thought of this scenario as well, but just feel surprised to come across them twice recently

thanks @MarcoGorelli @jbrockmendel shall I close the issue?

**Comment by MarcoGorelli** [comment]
I'll just dig through the logs to try to verify that that's actually what happened

Just for reference, the exact same command is run during CI for both PRs and builds from master:
```
pre-commit run --show-diff-on-failure --color=always --all-files
```

**Comment by charlesdong1991** [comment]
i closed #37940

**Comment by MarcoGorelli** [comment]
OK, got it - 3 days ago, Brock opened #37872 and #37865, both of which removed an instance of `Label` from `pandas/core/indexes/period.py `.

#37872 was merged first. Then, a couple of days later, #37865 was merged, without it having been updated with changes from `master` - so it's own CI was still green, but when it was merged, both instances of `Label` were gone and the CI check turned red

**Comment by MarcoGorelli** [comment]
Anyway, this looks right and passes relevant checks - merging so the CI checks are fixed

**Pull request merged**
