### PR TITLE
CI: Fix wheel builder uploading

### PR DESCRIPTION
**Pull request by lithomas1**
The uploading has been broken on nightly wheels for a while.

Hopefully, this fixes it. I've tested on my fork with a dummy token.

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @lithomas1 

Only comment is that Iprobably wouldn't use the anaconda channel, but just the conda-forge (actually I'd use the nodefaults to make sure it's not used). I'm not aware of the anaconda channel adding any value, but I've seen it causing issues when mixed with conda-forge.

**Comment by lithomas1** [comment]
> I'm not aware of the anaconda channel adding any value, but I've seen it causing issues when mixed with conda-forge.

In this case, anaconda publishes the anaconda-client to the anaconda channel. The conda-forge version of the client is several versions out of date unfortunately :( .

I'm going to merge this now to test that this works.

**Comment by datapythonista** [comment]
Ah, ok, makes sense then.

**Comment by lithomas1** [comment]
It works! https://github.com/pandas-dev/pandas/actions/runs/3404407427

**Pull request merged**
