### PR TITLE
CLN: clean benchmarks to get them running

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Changes to be compatible with latest master / py3.

### CODE REVIEW

**Comment by jreback** [comment]
this is great 

not sure if docs need any updates
i would default to 3.6 in the asv config as well

**Comment by jorisvandenbossche** [comment]
Almost forgot, there was one remaining error related to hdf5:

```
[ 38.26%] ··· Running hdfstore_bench.HDF5.time_query_store_table_wide                                                                                                                           failed
[ 38.26%] ····· Traceback (most recent call last):
                  File "/home/joris/scipy/asv/asv/benchmark.py", line 794, in <module>
                    commands[mode](args)
                  File "/home/joris/scipy/asv/asv/benchmark.py", line 771, in main_run
                    result = benchmark.do_run()
                  File "/home/joris/scipy/asv/asv/benchmark.py", line 455, in do_run
                    return self.run(*self._current_params)
                  File "/home/joris/scipy/asv/asv/benchmark.py", line 547, in run
                    all_runs.extend(timer.repeat(repeat, number))
                  File "/home/joris/miniconda3/envs/dev/lib/python3.5/timeit.py", line 206, in repeat
                    t = self.timeit(number)
                  File "/home/joris/miniconda3/envs/dev/lib/python3.5/timeit.py", line 178, in timeit
                    timing = self.inner(it, self.timer)
                  File "<timeit-src>", line 6, in inner
                  File "/home/joris/scipy/pandas/asv_bench/benchmarks/hdfstore_bench.py", line 89, in time_query_store_table_wide
                    ('index', '<', self.df_wide2.index[15000])])
                  File "/home/joris/scipy/pandas/pandas/io/pytables.py", line 722, in select
                    return it.get_result()
                  File "/home/joris/scipy/pandas/pandas/io/pytables.py", line 1428, in get_result
                    results = self.func(self.start, self.stop, where)
                  File "/home/joris/scipy/pandas/pandas/io/pytables.py", line 715, in func
                    columns=columns, **kwargs)
                  File "/home/joris/scipy/pandas/pandas/io/pytables.py", line 4103, in read
                    if not self.read_axes(where=where, **kwargs):
                  File "/home/joris/scipy/pandas/pandas/io/pytables.py", line 3302, in read_axes
                    self.selection = Selection(self, where=where, **kwargs)
                  File "/home/joris/scipy/pandas/pandas/io/pytables.py", line 4664, in __init__
                    self.terms = self.generate(where)
                  File "/home/joris/scipy/pandas/pandas/io/pytables.py", line 4677, in generate
                    return Expr(where, queryables=q, encoding=self.table.encoding)
                  File "/home/joris/scipy/pandas/pandas/core/computation/pytables.py", line 532, in __init__
                    where = ' & ' .join(["(%s)" % w for w in where])  # noqa
                  File "/home/joris/scipy/pandas/pandas/core/computation/pytables.py", line 532, in <listcomp>
                    where = ' & ' .join(["(%s)" % w for w in where])  # noqa
                TypeError: not all arguments converted during string formatting
```

Benchmarks are here: https://github.com/pandas-dev/pandas/blob/master/asv_bench/benchmarks/hdfstore_bench.py#L87-L93 
I am not very familiar with HDFStore, do you know what the issue is?

**Comment by jreback** [comment]
add a commit to use the correct syntax.

**Comment by jorisvandenbossche** [comment]
Thanks!

(BTW, you should link your two sigma address to your github account, it is not yet recognizing your commits)

**Comment by jorisvandenbossche** [comment]
Changed to 3.6 as well!

**Comment by jreback** [comment]
> (BTW, you should link your two sigma address to your github account, it is not yet recognizing your commits)

where do you see a problem?

side issue - I have a couple more small reorgs (indexes, tools) coming

**Comment by jorisvandenbossche** [comment]
If you look at the commit you added in this PR, it doesn't have your icon, and if you look at the commit: https://github.com/pandas-dev/pandas/pull/16025/commits/7e4b9dc12b20decc8d5b7be234a769f82871a6e7, the question mark next to the author gives some more explanation

**Comment by jreback** [comment]
e-mail address fixed thanks!

**Pull request merged**
