### PR TITLE
DOC: added exp weighting clarifications from #8861

### PR DESCRIPTION
**Pull request by matthewgilbert**
I integrated the comments in #8861 from @seth-p into the exponential weighted moment functions docs.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Thanks! Looks good from a technical point. 
@seth-p Can you do a review?

**Comment by seth-p** [comment]
It looks good, though would be even better to include some of the substance in @immerrr's https://github.com/pydata/pandas/issues/8861#issuecomment-63778421, specifically that for the ``adjust=False`` case to make sense, you need to assume that "the first element is not an ordinary value, but rather a prior knowledge of the whole infinite-ish series".

**Comment by matthewgilbert** [comment]
Good point, I'll put some of that content in.

**Comment by jreback** [comment]
@matthewgilbert pls review the doc string ``pd.ewma`` as well for consistency with this (you can also put in a link to the actual docs to not make it overly long)

**Comment by matthewgilbert** [comment]
@jreback Bit confused with your suggestion to link to the docs string, was there a specific place you had in mind for this?

**Comment by jreback** [comment]
put a link in the doc-string to the more detailed explanations

**Comment by matthewgilbert** [comment]
Incorporated link to the docstring and added some explanation of describing assumptions on first element when `adjust=False`, squashed this into one commit

**Comment by seth-p** [comment]
@matthewgilbert, I'm afraid I don't think you incorporated @immerrr's point in https://github.com/pydata/pandas/issues/8861#issuecomment-63778421 correctly. It is when ``adjust=False`` that one is implicitly assuming that ``x[0]`` is a moving average encapsulating the data from all "previous" observation; whereas for ``adjust=True`` one is implicitly assuming that ``x[0]`` is an observation just like every other ``x[i], i>0``. (In all of these, ``0`` should really be replaced by the index of the first non-``NaN`` value in ``x[]``, but I'm glossing over that subtlety.)

**Comment by matthewgilbert** [comment]
@seth-p Thanks, yes this was a typo, sorry about that. Just to be clear, changing

"When `adjust=True` we have..." to "When `adjust=False` we have..." should fix this, or is there something else I'm missing?

**Comment by seth-p** [comment]
@matthewgilbert, I think that's fine, though also I think `` :math:`\alpha x_t + (1 - \alpha) y_{t-1}` `` should be `` :math:`y_t = \alpha x_t + (1 - \alpha) y_{t-1}` ``.

**Comment by matthewgilbert** [comment]
All comments have been incorporated. I squashed this all into one commit so unsure if as a result this does not send notifications and thought I would just comment here to be sure.

**Comment by jreback** [comment]
@matthewgilbert yes a push does not ping anyone.

This looks good.

@seth-p any final comments?

**Comment by seth-p** [comment]
Looks good.

**Comment by jorisvandenbossche** [comment]
@matthewgilbert Thanks a lot! 
In some time, this should be built in the dev docs: http://pandas-docs.github.io/pandas-docs-travis/, so you can always check there if everything looks fine

**Pull request merged**
