### PR TITLE
STYLE use pd_array in core

### PR DESCRIPTION
**Pull request by MarcoGorelli**
As requested by @jbrockmendel [here](https://github.com/pandas-dev/pandas/pull/40150)

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@MarcoGorelli i think an easier solution is

construction.py:
```
def pd_array(...):
```

\_\_init\_\_.py:
```
from pandas.core.construction import pd_array as array
```

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
Sorry to have a contradictory opinion .. but I am personally think that using the import alias where it's used is nicer. I would prefer to keep the actual name of the function (`array`) the same as the name how it is exposed publicly, since you still *see* this name (eg in the repr of the function object), and it's only distracting if that's different IMO.

**Comment by jorisvandenbossche** [comment]
For me this is fine (but it's @jbrockmendel that suggested otherwise)

The linting error seems relevant.

**Comment by jbrockmendel** [comment]
joris makes a reasonable point about `repr(pd_array)`.  im fine with the approach in this PR

**Comment by MarcoGorelli** [comment]
> The linting error seems relevant.

Indeed - fixed, thanks!

**Comment by jorisvandenbossche** [comment]
@MarcoGorelli can you do another (final) merge of master to be sure there are no new failures?

**Comment by jreback** [comment]
@MarcoGorelli if you can merge master once more

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @MarcoGorelli

**Pull request merged**
