### PR TITLE
BUG: #10652 google-api-python-client minimum version check

### PR DESCRIPTION
**Pull request by fdellavedova-zz**
Fixes [bug](https://github.com/pydata/pandas/issues/10652) with version check for google-api-python-client

### CODE REVIEW

**Comment by jreback** [comment]
this is not tested on travis, not really sure how to evaluate this.

cc @jacobschaer
cc @sean-schaefer

**Comment by fdellavedova** [comment]
What do you mean? it seems the [tests passed](https://travis-ci.org/pydata/pandas/builds/72177378) . Am I missing something?

**Comment by jreback** [comment]
and they pass on current master (w/o this change). So you will have to show an environment that fails first.

**Comment by fdellavedova** [comment]
to replicate:

$ pip install google-api-python-client==1.2.0

and then:

>>> from pandas.io import gbq
>>> gbq.read_gbq('foo', 'spam')
....
ImportError: pandas requires google-api-python-client >= 1.2.0 for Google BigQuery support, current version 1.2

**Comment by jreback** [comment]
gr8. so modify one of the ci environments to load that version. have it fail and then use your change to have it pass. It is run in ``ci/requirements-2.7.txt`` now.

**Comment by jacobschaer** [comment]
I remember this issue... seems a shame to have to resort to using regular expression matching. @parthea mentioned using `StrictVersion` instead of `LooseVersion` might resolve the issue - I haven't really looked into the differences, but his example in the discussion for: https://github.com/pydata/pandas/pull/10857 seems to suggest it will work.

**Comment by jreback** [comment]
replaced by #10857

**Pull request closed without merging**
