### PR TITLE
CLN: removes BinGrouper kind of cython methods

### PR DESCRIPTION
**Pull request by behzadnouri**

### CODE REVIEW

**Comment by jreback** [comment]
prob the most lines removed at one time!

can you do an asv run and see if any anomalies.

you can kill that bin grouper test (that you are now skipping) as well.

**Comment by behzadnouri** [comment]
I checked with vbench and benchmarks were stable. [this line](https://github.com/pydata/pandas/pull/10976/files#diff-720d374f1a709d0075a1f0a02445cd65R1799) is the only added overhead which is pretty efficient

**Comment by jreback** [comment]
gr8 thanks!

**Comment by shoyer** [comment]
Very nice! I was wondering why we had all these binned groupby routines in Cython.

**Pull request merged**
