### PR TITLE
DOC: Fixing EX01 - Added examples

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Towards https://github.com/pandas-dev/pandas/issues/37875

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
nice, looks good to me on green!

**Comment by MarcoGorelli** [comment]
looks like an error
```

/home/runner/work/pandas/pandas/pandas/core/dtypes/base.py:docstring of pandas.core.dtypes.base.ExtensionDtype:67: ERROR: Inconsistent literal block quoting.
```

**Comment by DeaMariaLeon** [comment]
Latest failing test not related, I think.

**Comment by MarcoGorelli** [comment]
right, thanks!

**Pull request merged**
