### PR TITLE
ENH: add data hashing routines

### PR DESCRIPTION
**Pull request by jreback**
xref https://github.com/dask/dask/pull/1807

### CODE REVIEW

**Comment by jreback** [comment]
cc @mikegraham 
cc @jcrist 
cc @mrocklin

added ``index=True`` kw to by default hash the index.

**Comment by mikegraham** [comment]
With this broader goal in mind, it might be worth considering exactly what the applications are. This current implementation uses the `hash` builtin, so it will have hash randomization for strings for some Pythons. I don't know what the right move is there, but it's something to keep in mind.

There was a big discussion for the dask application about whether to handle the case where dtype was object but the objects weren't strings, and whether to handle strings in a way that was stable between runs. Part of what shaped that discussion was dask's refraining from introducing C extensions.

**Comment by jreback** [comment]
@mikegraham yes a stable string hash would be nice. (esp between runs). I don't think performance is an issue ATM (this is pretty fast). But can certainly deal with that if it comes up. Do you have a 'better' way of hashing strings?

**Comment by jreback** [comment]
should we be using ``hashlib``? https://www.peterbe.com/plog/best-hashing-function-in-python

**Comment by jreback** [comment]
```
(pandas) [Thu Nov 24 11:26:03 ~/pandas]$ python -c "import hashlib; print(int(hashlib.md5('foo'.encode('utf8')).hexdigest(), 16) % (10 ** 8))"
985560
```
I have seen this done. Its stable across runs & compat between python versions.

**Comment by jreback** [comment]
we could also always stringify ``object`` dtype data.

**Comment by jreback** [comment]
```
In [2]: df = tm.makeMixedDataFrame()

In [3]: df = pd.concat([df]*100000)

In [4]: df.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 500000 entries, 0 to 4
Data columns (total 4 columns):
A    500000 non-null float64
B    500000 non-null float64
C    500000 non-null object
D    500000 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 19.1+ MB

In [5]: df.hash()
Out[5]: 
array([ 7765496462383768478,  9003743364327424712, 10642375279821279843,
       ..., 10642375279821279843, 15490030136262591728,
        1988273298325137642], dtype=uint64)

In [6]: %timeit df.hash()
1 loop, best of 3: 995 ms per loop

```

note great about 1/2 time is spent in hashlib. but can work on that later.

**Comment by mikegraham** [comment]
> should we be using `hashlib`? 

It will be slow has heck. I have a Cython siphash implementation I can contribute if you want. This should also be able to be GIL-releasing.

> we could also always stringify object dtype data.

You mean `str(x)`? I don't think that's super valid -- it will often have unstable data (like the id) in it and will often not have real information about the object in it.

**Comment by mikegraham** [comment]
https://gist.github.com/mikegraham/feab49dd9a0ac98cc1fb26a3366e84e4

**Comment by jreback** [comment]
@mikegraham ok, using your cython code we now get about a 6x speedup. so 120ms for 500k rows.
couple of issues.

- have to handle things like tuples (e.g. from a multiindex) / non-strings
- the hash does not appear consistent. maybe I am doing something wrong. can you have a look.

**Comment by jreback** [comment]
ok, fixed the consistency issue. key has to be 16 long! hahha

**Comment by jreback** [comment]
and latest push makes this nogil!

**Comment by jreback** [comment]
ok, added tests for mixed dtypes, empty objects.
support for encoding and different hash_keys.

Timing is not bad

```
In [33]: len(s2)
Out[33]: 500000

In [34]: %timeit s2.hash()
10 loops, best of 3: 126 ms per loop
```

We can do even better by factorizing first & then hashing (so we wouldn't even need the object hashing code).
```
In [35]: %timeit Series(s2.factorize()[0]).hash()
10 loops, best of 3: 28 ms per loop
```

Is this a valid thing to do?

**Comment by jreback** [comment]
are repeated hashes likely?
```
In [21]: N=1000000; s = pd.Series(tm.makeStringIndex(10).take(np.random.randint(0, 10, size=N)))

In [22]: c = s.astype('category')

In [23]: c.cat.categories
Out[23]: Index(['56bjQF4AsK', '8ZAYAT8GPT', 'AR3qPSViwT', 'I7RtoX1MVN', 'IlKrENATh1', 'QWnGtQeaPG', 'YhkZCbpQHJ', 'a7N5Sb78rE', 'fE08yrQbJ7', 'jVm54MmpWD'], dtype='object')

In [24]: c.cat.categories.hash()
Out[24]: 
array([16874492830844911956, 17129770899522711342, 16874492830844911956,
       17129770899522711342, 16874492830844911956, 17129770899522711342,
       16874492830844911956, 17129770899522711342, 16874492830844911956,
       17129770899522711342], dtype=uint64)
```

hmm, something funny going on........
```
In [27]: Index(['foo', 'bar', 'baz']).hash()
Out[27]: array([ 477881037637427054, 1374399572096150070,  477881037637427054], dtype=uint64)
```

**Comment by jreback** [comment]
nvm, was incorretly assigning the pointer.

```
In [1]: Index(['foo', 'bar', 'baz']).hash()
Out[1]: array([3600424527151052760, 1374399572096150070,  477881037637427054], dtype=uint64)
```

**Comment by mikegraham** [comment]
> We can do even better by factorizing first & then hashing (so we wouldn't even need the object hashing code).

That will make the hash only valid for one given series/df, I think, not between different dfs. I don't know what all the uses are for hashing, but for the dask uses, I think it wouldn't since the hash values for similar values wouldn't agree between partitions.

**Comment by jreback** [comment]
ok I categorize, hash, and re-broadcast (so its equivalent to the original), but we don't duplicate work.

```
In [1]: N=1000000; s = pd.Series(tm.makeStringIndex(10).take(np.random.randint(0, 10, size=N)))

In [2]: %timeit s.hash()
10 loops, best of 3: 63.4 ms per loop

In [3]: len(s)
Out[3]: 1000000

In [4]: N=1000000; s = pd.Series(tm.makeStringIndex(1000).take(np.random.randint(0, 1000, size=N)))

In [5]: %timeit s.hash()
10 loops, best of 3: 80.7 ms per loop

In [6]: N=1000000; s = pd.Series(tm.makeStringIndex(100000).take(np.random.randint(0, 100000, size=N)))

In [7]: %timeit s.hash()
1 loop, best of 3: 309 ms per loop
```

**Comment by jreback** [comment]
and using some revised code (was sorting when factorizing, which is uncessary)

```
10 loops, best of 3: 73.2 ms per loop
10 loops, best of 3: 87.5 ms per loop
1 loop, best of 3: 194 ms per loop
```

**Comment by mrocklin** [comment]
Is there a planned release date for 1.19.2?  Planning dask.dataframe work.

**Comment by jreback** [comment]
schduled now for 12/16 about; I picked that because of the 3.6 release date.

**Comment by jreback** [comment]
should I add this ``.sum()`` to the doc-string. I *think* this provides an effective way of getting a hash for an entire pandas object (something people occasionally ask for).

```
In [3]: pd.DataFrame({'A': [1, 2, 3], 'B': ['foo', 'bar', 'baz']}).hash()
Out[3]: array([11603696091789712533,  5345384428795788641,    46691607209239364], dtype=uint64)

In [4]: pd.DataFrame({'A': [1, 2, 3], 'B': ['foo', 'bar', 'baz']}).hash().sum()
Out[4]: 16995772127794740538

In [5]: pd.DataFrame({'A': [2, 2, 3], 'B': ['foo', 'bar', 'baz']}).hash().sum()
Out[5]: 11177462582024945927
```

**Comment by jreback** [comment]
@jorisvandenbossche @chris-b1 @TomAugspurger @sinhrks @wesm if any comments.

**Comment by mrocklin** [comment]
> should I add this .sum() to the doc-string. I think this provides an effective way of getting a hash for an entire pandas object (something people occasionally ask for).

The problem here is that `['a', 'b']` and `['b', 'a']` would hash to the same value, which is bad.  

Instead you could use something like the following:

```python
import hashlib
hashlib.sha256(result.data).hexdigest()

In [1]: import numpy as np

In [2]: import hashlib

In [3]: h = hashlib.sha256(np.ones(5).data)

In [4]: h.hexdigest()
Out[4]: '6e91e92205f42beb0df4ddf13cf0af352b29ffd2de9465348cdb1447a324e828'
```

**Comment by jreback** [comment]
@mrocklin ahh, so ``.hash()`` is independent of column ordering then.

**Comment by jreback** [comment]
actually, we do hash in a specific way (e.g. in column order), then the index if so indicated, so I *think* that these are a pretty good row wise data hash.

```
In [3]: pd.DataFrame({'A': [1, 2, 3], 'B': ['foo', 'bar', 'baz']}).hash()
Out[3]: array([11603696091789712533,  5345384428795788641,    46691607209239364], dtype=uint64)

In [4]: pd.DataFrame({'B': [1, 2, 3], 'A': ['foo', 'bar', 'baz']}).hash()
Out[4]: array([14224550840762107975, 10786791860424998761,  8249554186654362168], dtype=uint64)
```

**Comment by mikegraham** [comment]
Yeah, looks like the current `.hash()` is not independent of column ordering. Column order dependence was what my whole `np.multiply(h, np.uint(3), h)` bit was about.

**Comment by mikegraham** [comment]
`adder` is implemented in such a way that it is order-dependent.

**Comment by jreback** [comment]
@mikegraham 

> adder is implemented in such a way that it is order-dependent.
this is a feature!

**Comment by mikegraham** [comment]
Right, one I added, but I wasn't clear before that you had noticed while absorbing it ;)

**Comment by jreback** [comment]
@mikegraham 

> should I add this .sum() to the doc-string. I think this provides an effective way of getting a hash for an entire pandas object (something people occasionally ask for).

from my comment above, is this true?

**Comment by mrocklin** [comment]
@jreback under `sum()` would the following two hash to the same value?

```python
a = pd.Series([1, 2])
b = pd.Series([2, 1])
```

**Comment by jreback** [comment]
@mrocklin the ``.sum()`` 'trick' only works with ``DataFrames``. 

```
In [8]: Series([1,2]).hash().sum()
Out[8]: 17131413955381384498

In [9]: Series([2,1]).hash().sum()
Out[9]: 17131413955381384498
```

but I suspect there *is* a robust way to aggregate these to preserve the row data hashes
```
In [10]: Series([1,2]).hash()
Out[10]: array([  267474170112184751, 16863939785269199747], dtype=uint64)

In [11]: Series([2,1]).hash()
Out[11]: array([10625867037328620958,  6505546918052763540], dtype=uint64)
```

**Comment by mikegraham** [comment]
@jreback I don't know such people's use for a hash of a whole df...it only works if they specifically want a hash that doesn't depend on the order of the rows.

**Comment by jreback** [comment]
> I don't know such people's use for a hash of a whole df...it only works if they specifically want a hash that doesn't depend on the order of the rows.

not sure what you mean here.

The point of this hash is that it *does* depend on the ordering of data (and data within columns). Since we include the index it is representative of a unique signature for a data frame.

**Comment by mikegraham** [comment]
> The point of this hash is that it does depend on the ordering of data (and data within columns). 

Cool, like I said, I didn't know what people wanted in these cases. "Has all the same values in the same places", "has all the same values at all", and "has all the same rows" are all coherent things to me.

For the first thing, you can use siphash again on the resultant series from `.hash()`, use sha-512, use the prime multiplier trick, or whatever. You might also want to include column labels somehow if that's something that matters.

**Comment by jreback** [comment]
@mrocklin so then should we include meta-data here as well (e.g. ``.name`` for Series``, ``.name`` for ``Index``, and column labels for DataFrame?

**Comment by mikegraham** [comment]
Do you know of the specific use-cases people were wanting this for off-hand?

**Comment by mrocklin** [comment]
Depends on how you want to has, but yes, I think so.

Thinking adversarially, can you think of any two different dataframes that
hash to the same value?  Names might be good examples here.

**Comment by jreback** [comment]
now for dask I don't actually think this is an issue. as you *always* know the meta-data anyhow.

```
In [10]: pd.DataFrame([[1, 'foo'], [2, 'bar'], [3, 'baz']]).hash()
Out[10]: array([11603696091789712533,  5345384428795788641,    46691607209239364], dtype=uint64)

In [11]: pd.DataFrame([[1, 'foo'], [2, 'bar'], [3, 'baz']], columns=list('AB')).hash()
Out[11]: array([11603696091789712533,  5345384428795788641,    46691607209239364], dtype=uint64)

```

**Comment by mikegraham** [comment]
I meant to ask what the specific use cases for a whole-dataframe hash were.

**Comment by mrocklin** [comment]
We use hashing for other things in dask as well.  For example we use whole-dataframe hashing to determine keys if they are not given.

```python
In [1]: from dask.base import tokenize

In [2]: import pandas as pd

In [3]: tokenize(pd.DataFrame({'x': [1, 2, 3]}))
Out[3]: '873595b6236c19b206f2e28992546e10'
```

https://github.com/dask/dask/blob/master/dask/base.py#L292-L315

**Comment by chris-b1** [comment]
Since this is a row-based hash, it may make sense to wrap the results back in a `Series` with the original row index?  

I'm not 100% clear on the use-case - I would have guessed the `DataFrame` one is column based, so I also  think the docstring could use some stronger language to make it clear it is row-based.

**Comment by jreback** [comment]
@chris-b1 addressed your comments.

**Comment by jorisvandenbossche** [comment]
No comments directly about the implementation, but regarding the API: is it needed to have this as a method on the DataFrame/Series/Index object itself? 
I think this is not a functionality that will be used a lot directly by users, where interactive tab completion and method chaining is important, but rather used by library developers (eg dask)? Is that correct? In that case, I don't think it is that much an inconvenience for dask to eg have to use `pd.tools.hash(df)` instead of `df.hash()`? 

The reason I raise this points is because we already have so many methods on dataframe, we should be weigh the added value of having it as a method.

Also not that fond of having it in 0.19.2, but I understand you want to have this quickly :-)

**Comment by mrocklin** [comment]
I'm quite happy to call an internal method within Dask.  It's all the same
to me.

**Comment by jreback** [comment]
ok, removed the public API. should be just along for the ride now. We can think about when (or if) to expose this publicly.

**Comment by MaximilianR** [comment]
Thought about using this to override `__hash__()`, and so making the pandas objects Hashable?

**Comment by mikegraham** [comment]
@MaximilianR I don't think that's appropriate -- the `__eq__` of a pandas object is subject to change.

**Comment by jreback** [comment]
@MaximilianR in theory this *could* provide ``__hash__``, but its not cheap to produce, so it couldn't be cached (unless we then track whether data actually is changed, IOW, to mark it dirty). Its *mostly* useful when a frame is serialized / deserialized anyhow, not the typical scenario for ``__hash__``.

**Comment by mikegraham** [comment]
Even if you could reliably detect stale cached values, I'm not sure it would be appropriate to define `__hash__` for pandas objects. According to the Python Language Reference

> If a class defines mutable objects and implements a `__cmp__()` or `__eq__()` method, it should not implement `__hash__()`

**Comment by jreback** [comment]
@mikegraham we r leaving '__hash__' out for now
but this IS a valid use case to provide a data hash that does change when the data is changed . pandas objects are mutable but occasionally you do want to compare versions of them (now there are more explicit ways / namely compare the elements)

This is non trivial and requires knowing objects IN a container change. this could be quite non performant for say a python list (where u may have to arbitrarily descend the object tree); a dataframe is more limited in how it can change and generally doesn't hold arbitrary other objects), so this is feasible. whether it is in practice reallly useful is another matter.

**Comment by jreback** [comment]
any further comments?

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by mikegraham** [comment]
@jreback Thanks for relating, I agree 100%, I was just saying that it seems like `__hash__` isn't the right name for this particular use case.

**Pull request merged**
