### PR TITLE
Add keyword sort to pivot_table

### LINKED ISSUE #39143: QST:Why DataFrame.pivot() will change the order of the rows of DataFrame?
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable

```

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #39143
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

This adds support for sort=False to pivot_table if we want to do this

### CODE REVIEW

**Review by attack68 — APPROVED** [review]
lgtm. im +1 for this.

**Review by mroeschke — APPROVED** [review]
LGTM. This seems reasonable to me as well.

**Comment by jreback** [comment]
thanks @phofl very nice!

**Comment by jiahe224** [comment]
Will keyword sort be added to pivot?

**Comment by phofl** [comment]
see #15105

**Pull request merged**
