### PR TITLE
TYPING: lockdown test modules passing mypy

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref https://github.com/pandas-dev/pandas/pull/28904#discussion_r333740051 and https://github.com/pandas-dev/pandas/pull/28746#discussion_r330499267

### CODE REVIEW

**Comment by WillAyd** [comment]
Are some of these easy to fix? Would be nice to keep the setup.cfg small if could do as precursors

**Comment by simonjayhawkins** [comment]
maybe, not really looked in detail. and I personally won't be prioritising this over the main codebase.

it was so others, could add type hints to the tests and have them checked(well most of them)  see #28904

also if doing it on a per module basis, easier to confirm in review if the module is also removed from setup.cfg (process adopted for check_untyped_defs, seems to work well)

**Comment by WillAyd** [comment]
Sounds good. No major objection from me - @jreback any thoughts?

**Comment by simonjayhawkins** [comment]
not at desktop atm. will give you a better idea of the workload tomorrow. i _think_ it was about 200 errors. but many duplicates. and some files _might_ only have a couple.

I _think_ if the extra noise in setup.cfg is an issue, we could consider using mypy.ini

**Comment by jreback** [comment]
didn’t we use mypy.ini as some point?

i guess that’s better

**Comment by WillAyd** [comment]
Yea went from mypy.ini to setup.cfg in #27427 - I don't know if there are any real nuances to going back so would be OK with that

**Comment by jreback** [comment]
ok, yeah let's keep in the same

**Comment by simonjayhawkins** [comment]
FYI xref #28910

now that this is on master, a mypy bump to 0.730 would break ci 

```
$ mypy pandas
pandas\tests\indexes\datetimes\test_tools.py:270: error: Module has no attribute "FixedOffset"
pandas\tests\indexes\datetimes\test_tools.py:275: error: Module has no attribute "FixedOffset"
pandas\tests\indexes\datetimes\test_tools.py:281: error: Module has no attribute "FixedOffset"
pandas\tests\indexes\datetimes\test_tools.py:282: error: Module has no attribute "FixedOffset"
pandas\tests\indexes\datetimes\test_tools.py:290: error: Module has no attribute "FixedOffset"
pandas\tests\indexes\datetimes\test_tools.py:292: error: Module has no attribute "FixedOffset"
pandas\tests\indexes\datetimes\test_tools.py:2082: error: Module has no attribute "FixedOffset"
pandas\tests\indexes\datetimes\test_tools.py:2087: error: Module has no attribute "FixedOffset"
Found 8 errors in 1 file (checked 805 source files)
```

PR coming soon. just parking here for reference.

**Pull request merged**
