### PR TITLE
DEPR: _metadata propagation

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

xref #51280

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Mothballing, will revisit in a few months to see if the pro-_metadata folks make progress on getting it fully working.

**Comment by jorisvandenbossche** [comment]
> Mothballing, will revisit in a few months to see if the pro-_metadata folks make progress on getting it fully working.

It _is_ working ...

**Comment by jbrockmendel** [comment]
137 xfailed tests in tests.generic.test_finalize say otherwise.

**Comment by jorisvandenbossche** [comment]
The existence of a many packages implementing subclasses that happily make use of `_metadata` says otherwise?

The tests you are referring to use `attrs` to test this, and not all those tests are relevant for the subclasses using `_metadata`. For example, `describe` is xfailing but I would say this is fine to not propagate attrs/metadata. `squeeze` is xfailing, but that's only because it doesn't actually return a pandas object but a scalar. Some reductions are failing, but I think many subclasses don't care about that use case to preserve the class. Idem for categorical accessors.

So I would say that those xfailed tests are not really an indication of how well this is working in general.

**Comment by jbrockmendel** [comment]
There are better uses of both our time; I have PRs I've been asked to review, and I've asked you to look at topper's reduction PR.

**Pull request closed without merging**
