### PR TITLE
fix missing arg in timestamp asvs

### PR DESCRIPTION
**Pull request by jbrockmendel**
Pretty good bet that I broke this a little while ago...

### CODE REVIEW

**Comment by jreback** [comment]
also, can you run a full asv and compare to 0.21.0, see how doing so far.

**Comment by jbrockmendel** [comment]
> also, can you run a full asv and compare to 0.21.0, see how doing so far.

Will do.  You uh, might want to get a second opinion though.

**Comment by jreback** [comment]
@mroeschke can u run vs 0.21 and show significant diffs?

**Comment by mroeschke** [comment]
I think this is the right commit hash for 0.21 [ref](https://github.com/pandas-dev/pandas/commit/81372093f1fdc0c07e4b45ba0f47b0360fabd405)

```
$ asv continuous -f 1.1 upstream/master 81372093f1fdc0c07e4b45ba0f47b

before           after         ratio
     [982ad07c]       [81372093]
!           23.1s           failed      n/a  gil.nogil_datetime_fields.time_datetime_to_period
!     8.86±0.02ms           failed      n/a  timeseries.ToDatetime.time_cache_false_with_dup_seconds_and_unit
!     3.80±0.01ms           failed      n/a  timeseries.ToDatetime.time_cache_false_with_dup_string_dates
!     3.99±0.01ms           failed      n/a  timeseries.ToDatetime.time_cache_false_with_dup_string_dates_and_format
!       417±0.1ms           failed      n/a  timeseries.ToDatetime.time_cache_false_with_dup_string_tzoffset_dates
!     7.96±0.02ms           failed      n/a  timeseries.ToDatetime.time_cache_true_with_dup_seconds_and_unit
!     5.38±0.03ms           failed      n/a  timeseries.ToDatetime.time_cache_true_with_dup_string_dates
!     5.42±0.03ms           failed      n/a  timeseries.ToDatetime.time_cache_true_with_dup_string_dates_and_format
!     5.76±0.03ms           failed      n/a  timeseries.ToDatetime.time_cache_true_with_dup_string_tzoffset_dates
+     5.81±0.01ms            2.83s   487.49  timedelta.DatetimeAccessor.time_timedelta_dt_accessor_seconds
+     5.78±0.01ms            2.80s   484.24  timedelta.DatetimeAccessor.time_timedelta_dt_accessor_nanoseconds
+     5.82±0.01ms            2.82s   484.08  timedelta.DatetimeAccessor.time_timedelta_dt_accessor_days
+     5.85±0.02ms            2.78s   475.79  timedelta.DatetimeAccessor.time_timedelta_dt_accessor_microseconds
+         119±4ms            12.7s   106.88  plotting.Plotting.time_series_plot
+       234±0.9ms            12.4s    53.18  plotting.Plotting.time_frame_plot
+          56.8ms            749ms    13.19  timeseries.DatetimeIndex.time_to_date
+       549±0.6μs      2.32±0.01ms     4.23  series_methods.series_map_series.time_series_map_series
+           7.20s            24.8s     3.45  offset.ApplyIndex.time_apply_index(<BusinessYearEnd: month=12>)
+           7.51s            25.3s     3.37  offset.ApplyIndex.time_apply_series(<BusinessYearEnd: month=12>)
+     67.0±0.07μs        183±0.1μs     2.73  offset.SemiMonthOffset.time_end_apply
+      66.2±0.1μs        177±0.2μs     2.67  offset.SemiMonthOffset.time_begin_apply
+         312±1ns          809±6ns     2.59  timedelta.TimedeltaProperties.time_timedelta_seconds
+      80.3±0.2μs        190±0.4μs     2.36  offset.SemiMonthOffset.time_end_incr
+      80.0±0.1μs        189±0.4μs     2.36  offset.SemiMonthOffset.time_begin_incr
+      89.9±0.1μs          205±2μs     2.28  offset.SemiMonthOffset.time_begin_decr
+      88.8±0.1μs        201±0.5μs     2.26  offset.SemiMonthOffset.time_end_incr_n
+      89.0±0.2μs        201±0.3μs     2.25  offset.SemiMonthOffset.time_begin_incr_n
+      54.0±0.1ms       121±0.05ms     2.25  categoricals.Constructor.time_all_nan
+      91.8±0.1μs        205±0.3μs     2.24  offset.SemiMonthOffset.time_end_decr
+      97.9±0.2μs        213±0.8μs     2.18  offset.SemiMonthOffset.time_end_decr_n
+       319±0.3ns          693±1ns     2.18  timedelta.TimedeltaProperties.time_timedelta_days
+      99.5±0.2μs        216±0.3μs     2.17  offset.SemiMonthOffset.time_begin_decr_n
+       313±0.2ns          674±2ns     2.15  timedelta.TimedeltaProperties.time_timedelta_microseconds
+     2.18±0.01ms      4.10±0.02ms     1.88  series_methods.series_map_dict.time_series_map_dict
+           7.21s            13.6s     1.88  offset.ApplyIndex.time_apply_index(<BusinessMonthBegin>)
+           7.26s            13.6s     1.88  offset.ApplyIndex.time_apply_index(<BusinessQuarterBegin: startingMonth=3>)
+           7.23s            13.5s     1.86  offset.ApplyIndex.time_apply_index(<BusinessMonthEnd>)
+           7.49s            13.9s     1.85  offset.ApplyIndex.time_apply_series(<BusinessMonthBegin>)
+           7.24s            13.3s     1.84  offset.ApplyIndex.time_apply_index(<BusinessYearBegin: month=1>)
+           7.51s            13.7s     1.83  offset.ApplyIndex.time_apply_series(<BusinessYearBegin: month=1>)
+           7.60s            13.8s     1.82  offset.ApplyIndex.time_apply_series(<BusinessQuarterBegin: startingMonth=3>)
+       266±0.4μs          481±4μs     1.81  offset.CBMonthEnd.time_custom_bmonthend_incr
+           7.59s            13.7s     1.80  offset.ApplyIndex.time_apply_series(<BusinessMonthEnd>)
+       300±0.8μs        527±0.5μs     1.76  offset.CBMonthEnd.time_custom_bmonthend_incr_n
+       312±0.6μs        539±0.8μs     1.73  offset.CBMonthEnd.time_custom_bmonthend_decr_n
+           7.57s            11.3s     1.50  offset.ApplyIndex.time_apply_series(<BusinessQuarterEnd: startingMonth=3>)
+           7.29s            10.8s     1.48  offset.ApplyIndex.time_apply_index(<BusinessQuarterEnd: startingMonth=3>)
+        609±30ns          864±2ns     1.42  indexing.IndexerLookup.time_lookup_iloc
+        614±20ns          861±6ns     1.40  indexing.IndexerLookup.time_lookup_loc
+      68.1±0.2μs       92.1±0.4μs     1.35  period.PeriodUnaryMethods.time_now('M')
+     3.61±0.01ms      4.85±0.02ms     1.34  indexing.PanelIndexing.time_subset
+       112±0.5ms        143±0.8ms     1.27  io_sql.WriteSQLTypes.time_string_sqlalchemy
+     1.13±0.04ms      1.43±0.04ms     1.26  series_methods.series_nlargest2.time_series_nlargest2
+       123±0.7ms        154±0.5ms     1.25  io_sql.WriteSQLTypes.time_float_sqlalchemy
+       348±0.8μs          435±1μs     1.25  offset.CBMonthBegin.time_custom_bmonthbegin_decr_n
+     1.11±0.04ms      1.38±0.03ms     1.24  series_methods.series_nsmallest2.time_series_nsmallest2
+     11.5±0.08ms      14.2±0.04ms     1.24  groupby.groupby_nth.time_groupby_series_nth_any
+       423±0.6μs        521±0.8μs     1.23  offset.CBMonthBegin.time_custom_bmonthbegin_incr_n
+         191±1ms          234±1ms     1.23  plotting.TimeseriesPlotting.time_plot_regular_compat
+         197±2ms          240±4ms     1.22  plotting.TimeseriesPlotting.time_plot_irregular
+     17.0±0.01μs      20.7±0.03μs     1.22  index_object.Float64.time_slice_indexer_basic
+     3.09±0.03μs      3.73±0.01μs     1.21  period.PeriodProperties.time_month('M')
+     6.33±0.03ms      7.63±0.02ms     1.21  groupby.groupby_nth.time_groupby_series_nth_none
+      13.8±0.1ms      16.6±0.04ms     1.21  timeseries.DatetimeAccessor.time_dt_accessor_normalize
+     3.07±0.02μs      3.66±0.02μs     1.19  period.PeriodProperties.time_dayofweek('M')
+     1.65±0.06ms      1.96±0.04ms     1.18  series_methods.series_nlargest1.time_series_nlargest1
+          16.8μs      19.7±0.04μs     1.17  index_object.Float64.time_slice_indexer_even
+     16.7±0.01μs      19.5±0.02μs     1.17  index_object.StringIndex.time_slice_indexer_even
+       219±0.7ms          256±1ms     1.17  io_sql.WriteSQL.time_sqlalchemy
+       178±0.3μs          206±1μs     1.16  period.PeriodUnaryMethods.time_now('min')
+       119±0.4μs        138±0.4μs     1.16  period.PeriodUnaryMethods.time_asfreq('M')
+       118±0.1μs        137±0.3μs     1.16  period.PeriodUnaryMethods.time_asfreq('min')
+     17.2±0.01μs      19.9±0.02μs     1.15  index_object.StringIndex.time_slice_indexer_basic
+     3.25±0.02μs      3.75±0.03μs     1.15  period.PeriodProperties.time_year('M')
+     3.09±0.01μs      3.55±0.01μs     1.15  period.PeriodProperties.time_hour('M')
+     3.19±0.02μs      3.65±0.01μs     1.14  period.PeriodProperties.time_dayofyear('M')
+         201±2ms        230±0.8ms     1.14  io_sql.WriteSQLTypes.time_datetime_sqlalchemy
+     3.03±0.02μs      3.45±0.01μs     1.14  period.PeriodProperties.time_dayofweek('min')
+          1.05ms           1.19ms     1.14  timeseries.DatetimeIndex.time_reset_index_tz
+     3.17±0.02μs      3.61±0.02μs     1.14  period.PeriodProperties.time_second('M')
+     3.19±0.02μs      3.63±0.01μs     1.14  period.PeriodProperties.time_year('min')
+        297±10μs         338±10μs     1.14  series_methods.series_constructor_no_data_datetime_index.time_series_constructor_no_data_datetime_index
+       316±0.5ms          359±2ms     1.14  groupby.groupby_indices.time_groupby_indices
+       221±0.3μs        251±0.6μs     1.13  period.PeriodProperties.time_end_time('min')
+     3.18±0.03μs      3.60±0.03μs     1.13  period.PeriodProperties.time_hour('min')
+           3.15s            3.56s     1.13  packers.SQL.time_write_sql
+     28.5±0.09μs      32.2±0.05μs     1.13  period.Indexing.time_shallow_copy
+       221±0.5μs          249±1μs     1.13  period.PeriodProperties.time_end_time('M')
+        1.42±0ms      1.60±0.01ms     1.13  categoricals.Repr.time_rendering
+     3.17±0.01μs      3.57±0.02μs     1.13  period.PeriodProperties.time_month('min')
+       207±0.3μs        233±0.7μs     1.13  period.PeriodUnaryMethods.time_to_timestamp('min')
+       207±0.5μs        233±0.4μs     1.12  period.PeriodProperties.time_start_time('min')
+       208±0.3μs        233±0.8μs     1.12  period.PeriodProperties.time_start_time('M')
+     3.37±0.02μs      3.78±0.02μs     1.12  period.PeriodProperties.time_daysinmonth('min')
+     3.19±0.02μs      3.57±0.02μs     1.12  period.PeriodProperties.time_week('min')
+     3.18±0.01μs      3.54±0.01μs     1.11  period.PeriodProperties.time_second('min')
+     3.19±0.02μs      3.56±0.01μs     1.11  period.PeriodProperties.time_day('M')
+     3.41±0.02μs      3.79±0.01μs     1.11  period.PeriodProperties.time_daysinmonth('M')
+     3.20±0.02μs      3.55±0.02μs     1.11  period.PeriodProperties.time_dayofyear('min')
+       129±0.7ms          142±2ms     1.11  gil.NoGilGroupby.time_max_2
+     3.15±0.01μs      3.47±0.01μs     1.10  period.PeriodProperties.time_quarter('min')
+       166±0.7μs        183±0.8μs     1.10  indexing.StringIndexing.time_getitem_pos_slice
+     3.27±0.02μs      3.60±0.01μs     1.10  period.PeriodProperties.time_qyear('M')
-     7.53±0.05ms      6.83±0.04ms     0.91  frame_methods.Interpolate.time_interpolate_some_good_infer
-     6.11±0.03ms      5.53±0.02ms     0.91  strings.StringMethods.time_slice
-        48.6±1ms         43.4±1ms     0.89  groupby.groupby_pivot_table.time_groupby_pivot_table
-     3.34±0.03ms      2.98±0.01ms     0.89  io_bench.read_parse_dates_iso8601.time_read_parse_dates_iso8601
-      12.5±0.1ms       11.0±0.1ms     0.88  strings.StringMethods.time_pad
-     6.87±0.03ms      5.94±0.01ms     0.87  timeseries.ResampleDataFrame.time_max_numpy
-           718ms        620±0.2ms     0.86  groupby.Groups.time_groupby_groups('object_small')
-     6.86±0.03ms      5.86±0.01ms     0.85  timeseries.ResampleDataFrame.time_max_string
-      28.1±0.2ms       23.8±0.2ms     0.85  groupby.groupby_agg_multi.time_groupby_multi_different_numpy_functions
-      51.9±0.3ms         43.9±1ms     0.85  frame_methods.frame_fancy_lookup.time_frame_fancy_lookup_all
-      29.8±0.2ms       25.0±0.1ms     0.84  reindex.Duplicates.time_frame_drop_dups
-     28.2±0.03ms      23.6±0.08ms     0.84  groupby.groupby_agg_multi.time_groupby_multi_different_functions
-      65.5±0.2μs       54.6±0.1μs     0.83  offset.YearBegin.time_timeseries_year_incr
-        1.36±0ms         1.12±0ms     0.82  indexing.DataFrameIndexing.time_boolean_rows_object
-      88.3±0.3ms       72.2±0.3ms     0.82  groupby.groupby_period.time_groupby_sum
-      7.32±0.3ms      5.90±0.02ms     0.81  timeseries.ResampleDataFrame.time_min_string
-      53.1±0.2μs       42.5±0.2μs     0.80  offset.YearBegin.time_timeseries_year_apply
-      7.39±0.1ms      5.88±0.01ms     0.80  timeseries.ResampleDataFrame.time_min_numpy
-     2.88±0.04ms      2.26±0.03ms     0.79  groupby.GroupBySuite.time_sem('int', 100)
-      42.3±0.2ms       33.0±0.4ms     0.78  binary_ops.Timeseries.time_timestamp_ops_diff(None)
-      59.7±0.1ms       44.6±0.2ms     0.75  packers.MsgPack.time_write_msgpack
-      44.5±0.5ms       33.0±0.2ms     0.74  categoricals.Constructor.time_regular
-       206±0.8μs        150±0.2μs     0.73  indexing.Int64Indexing.time_ix_slice
-       166±0.3μs        111±0.4μs     0.67  indexing.Int64Indexing.time_ix_scalar
-     58.4±0.08μs      38.6±0.02μs     0.66  timestamp.TimestampProperties.time_is_month_end(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-     58.5±0.03μs       38.4±0.3μs     0.66  timestamp.TimestampProperties.time_is_year_end(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-      58.2±0.2μs      38.1±0.03μs     0.65  timestamp.TimestampProperties.time_is_leap_year(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-      58.5±0.1μs      38.1±0.08μs     0.65  timestamp.TimestampProperties.time_is_year_start(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-     54.8±0.05μs      35.7±0.05μs     0.65  timestamp.TimestampProperties.time_week(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-     54.1±0.05μs      35.2±0.07μs     0.65  timestamp.TimestampProperties.time_dayofyear(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-     54.1±0.06μs      35.1±0.06μs     0.65  timestamp.TimestampProperties.time_days_in_month(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-      58.4±0.1μs       37.9±0.1μs     0.65  timestamp.TimestampProperties.time_is_quarter_end(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-      59.1±0.2μs      38.3±0.07μs     0.65  timestamp.TimestampProperties.time_is_quarter_start(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-     58.5±0.07μs      37.8±0.05μs     0.65  timestamp.TimestampProperties.time_is_month_start(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-      55.0±0.1μs      35.2±0.03μs     0.64  timestamp.TimestampProperties.time_quarter(<DstTzInfo 'Europe/Amsterdam' LMT+0:20:00 STD>)
-     14.8±0.03ms      8.06±0.04ms     0.54  period.Algorithms.time_value_counts('series')
-     12.5±0.04ms      6.47±0.01ms     0.52  period.Algorithms.time_drop_duplicates('series')
-      69.0±0.2μs      19.6±0.06μs     0.28  indexing.DataFrameIndexing.time_get_value_ix
-      46.3±0.5μs          924±5ns     0.02  indexing.IndexerLookup.time_lookup_ix
```

**Comment by jreback** [comment]
can u do the reverse of this; so regressions are > 1 (and current master)

and open a new issue - i think a couple of regressions here

**Pull request merged**
