### PR TITLE
DOC: Capitalize the 'p' in 'pandas code style guide'

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
I think this is intentionally lowercase

**Comment by WillAyd** [comment]
Closing as I think just a matter of convention, but can be reopened if anyone disagrees

Thanks in any case @MomIsBestFriend  - appreciate all your contributions

**Comment by MomIsBestFriend** [comment]
> I think this is intentionally lowercase

I was the one who wrote this file :smiley:
and It's not on purpose I can guarantee you.

**Comment by MomIsBestFriend** [comment]
> appreciate all your contributions

Thank you, means a lot!

**Pull request closed without merging**
