### PR TITLE
REF/TST: mixed use of mock/monkeypatch

### PR DESCRIPTION
**Pull request by simonjayhawkins**
doubt if this will work as don't have gbq configured locally.

will need to check output of CI.

### CODE REVIEW

**Comment by WillAyd** [comment]
Is the goal here to get rid of the import? We are dropping Py27 for 0.25 onwards so may be able to remove organically.

I suppose by using a lambda we are making more assumptions about the `pandas_gbq` codebase and how they treat their functions. May or may not make a difference but I'd lean towards just waiting to drop Py27 as part of cleanup

**Comment by simonjayhawkins** [comment]
@WillAyd we could drop the import in this module by using the mock fixture from conftest.py.

this was to see if we need mock at all and could just use monkeypatch instead of both mock and monkeypatch.

i expect this PR to fail on the parameters, i'll either change the number of inputs or change the lambda to a function with *args and **kwargs.

**Comment by jreback** [comment]
we also have a mock fixture in pandas/conftest.py should remove that too

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
lgtm @jreback

**Comment by jreback** [comment]
thanks!

**Pull request merged**
