### PR TITLE
CI: Fixed travis-36-cov build

### LINKED ISSUE #30309: CI: travis-36-cov failing
I'm seeing

```
from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS
```

in e.g. https://travis-ci.org/pandas-dev/pandas/jobs/626304911#L648

Still debugging. scikit-learn 0.22 was just released to defaults. Some of our deps look fishy there (mixing defaults and conda-forge a bunch).

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes #30309 

Just debugging right now. Can't reproduce locally yet.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
In theory, setting `LD_PRELOAD=/opt/conda/lib/libgomp.sov` will fix this. Trying to understand the issue a bit more first.

**Comment by WillAyd** [comment]
Rather than updating that may also just want to get off of the trusty service since may have been patched in glibc

https://github.com/pytorch/pytorch/issues/2575#issuecomment-523667875

**Comment by TomAugspurger** [comment]
Mmm good to know.

**Comment by TomAugspurger** [comment]
The LD_LIBRARY_PRELOAD thing did the trick, but I'd prefer to solve it more cleanly. Trying Will's suggestion next.

**Comment by WillAyd** [comment]
I think also need to add the appropriate DB services for CI to be green:

https://docs.travis-ci.com/user/database-setup/#mysql

**Comment by WillAyd** [comment]
Whoops sorry I see you did that one some already, but I guess that's what is causing the CI failure for the ones currently red

**Comment by TomAugspurger** [comment]
Yep, I have a commit to fix that, just waiting for the running job to see if the openmp thing is fixed.

**Comment by TomAugspurger** [comment]
OK that one passed. Took 34 minutes though, compared to 27 in https://travis-ci.org/pandas-dev/pandas/builds/626386764 :/

**Comment by WillAyd** [comment]
Hmm yea something watch, though I think the runs normally fluctuate in that range

**Review by WillAyd — APPROVED** [review]
lgtm if green

**Comment by TomAugspurger** [comment]
Thanks for the help Will! I'm glad to have avoided the LD_LIBRARY_PRELOAD stuff.

This last run took 32 minutes. I recall some ongoing work to balance these builds a bit, will see if I can track that down.

**Pull request merged**
