### PR TITLE
DEPR: remove deprecated date casting; closes #21359

### LINKED ISSUE #21359: Revert changes to comparison between Series[datetime64ns] and datetime.date
Revert the changes in https://github.com/pandas-dev/pandas/pull/21361

- [ ]: Remove check in `core/ops.py`
- [ ]: Remove test `pandas/tests/tseries/test_arithmetic.py::TestTimestampSeriesComparison.test_dt64_ser_cmp_date_warning`
- [ ]: Reenable test `pandas/tests/tseries/test_arithmetic.py::TestTimestampSeriesComparison.test_dt64ser_cmp_date_invalid`

Target this for 0.24?

xref https://github.com/pandas-dev/pandas/issues/21152

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #21359
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Review by jreback — CHANGES_REQUESTED** [review]
hmm  this might be a bit premature and should wait for 1.0, or is this blocking other things?

cc @TomAugspurger @jorisvandenbossche

**Comment by jbrockmendel** [comment]
Not blocking, but in #21359 the discussed plan was to remove in 0.24.0

**Comment by TomAugspurger** [comment]
Reading through https://github.com/pandas-dev/pandas/issues/21359, it seems like @jreback and @jorisvandenbossche preferred a bit longer of a deprecation. I don't have a preference.

**Comment by jreback** [comment]
this is probably mergable for 1.0, can you rebase

**Comment by jbrockmendel** [comment]
Rebased

**Review by TomAugspurger — APPROVED** [review]

**Comment by TomAugspurger** [comment]
Thanks.

**Pull request merged**
