### PR TITLE
TST/REF: collect tests by method

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@WillAyd do you have time to look at the npdev json failure (i think its affecting all PRs ATM)

**Comment by WillAyd** [comment]
Can’t dive too deep at the moment but could have some time tonight. If I had to guess the origin it may come from the PyArg_ParseTupleAndKeywords in objToJSON.c since the format string specifies int for the doublePrecision and indent arguments. Haven’t really debugged though

**Comment by jbrockmendel** [comment]
@seberg any ideas what in npdev could be causing a `DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python` to be issued?  I looked at recently-merged PRs and didn't see anything obvious.

Only occurs with datetime64tz columns

**Comment by seberg** [comment]
There is one stranger change in the recent dev version that might be related, would have to dig in

If you had a `string + number` or maybe also `string + datetime64` promotion in an array creation, like `np.array(["string", 1])`, that might give you an object array, which in turn might run into this Deprecation warning?  That is a bit around the corner though :). (https://github.com/numpy/numpy/issues/18425 although that one focuses on masked arrays)

I also recently modified that `float + timedelta64` always raises an error during a promotion. That could lead to a similar "to object" behaviour when using `np.array([...])`.

**Comment by WillAyd** [comment]
@jbrockmendel have you been able to reproduce locally? I tried with 3.8.5 and the DEV numpy but couldn't get the test to fail

**Comment by jbrockmendel** [comment]
> have you been able to reproduce locally? I tried with 3.8.5 and the DEV numpy but couldn't get the test to fail

are you passing `-W error`?  im getting the warning with np 1.19.5, which actually suggests its something on our end

**Comment by jreback** [comment]
FYI opened https://github.com/pandas-dev/pandas/issues/39854 for the failure

**Comment by jreback** [comment]
@jbrockmendel same number tests before / after?

**Comment by jreback** [comment]
well your after will be higher (as you split some).

**Comment by jbrockmendel** [comment]
> same number tests before / after?

nothing removed, just moved or split

**Pull request merged**
