### PR TITLE
TST: Fix makeObjectSeries data as object type

### LINKED ISSUE #28378: tm.makeObjectSeries returns a Series with dtype="datetime64[ns]"
```python-traceback
>>> import pandas.util.testing as tm
>>> tm.makeObjectSeries()
...
t1Q4jcW3nW   2000-02-09
ElZCr3WTz2   2000-02-10
p43Nqg7u4D   2000-02-11
dtype: datetime64[ns]
```

@jbrockmendel and I were both surprised that calling `makeObjectSeries` returns a Series with a datetime dtype. I think it would be more logical for this function to actually return an object dtype Series

### PR DESCRIPTION
**Pull request by jmg7173**
- [x] closes #28378 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
Cool this looks good. Any chance you looked at where this was ultimately used? Would be nice to clean up any casting that this required in the past

**Comment by jmg7173** [comment]
Umm, there is no casting about this.

One thing that I can doubt is usage on `test_objarr_add_invalid`. Because it tested about `add` and `sub` operation on object that made by `datetime64[ns]`.
It is at `pandas/tests/arithmetic/test_object.py L144`.

Other things are used just representing a `series` made by `object` as I summarized at #28378.

Can you tell me more details about what should I do?

And should I add an entry at whatsnew on v1.0?

**Comment by WillAyd** [comment]
> One thing that I can doubt is usage on `test_objarr_add_invalid`. Because it tested about `add` and `sub` operation on object that made by `datetime64[ns]`.
> It is at `pandas/tests/arithmetic/test_object.py L144`.

Yea that's a great find - thanks for being thorough. Can you see where that was introduced to see what the intention was? The fact that it blanket catches an `Exception` is a little bit of a red flag as to the intent.

Also looking these over I'm surprised that all of the `makeABCSeries` methods don't actually make a series of dtype `ABC`, but instead just contain an index of dtype `ABC`. Do you have any thoughts on how those methods are comprehensively used?

**Comment by jmg7173** [comment]
> Can you see where that was introduced to see what the intention was? 

Although I can't find origin of `test_objarr_add_invalid`, but it's intention was raising error on numerical operator about `datetime64[ns]` like object. Here's my reference(https://github.com/pandas-dev/pandas/commit/91ee418fe8ebe2951599eeb49159379c5200c029). I can't find more deeply because file was deleted.(`pandas/tests/test_series.py`)
https://github.com/pandas-dev/pandas/blob/91ee418fe8ebe2951599eeb49159379c5200c029/pandas/tests/series/test_operators.py#L187-L195
So, test would be modified as `datetime64[ns]` converted to base object.

> Also looking these over I'm surprised that all of the `makeABCSeries` methods don't actually make a series of dtype `ABC`, but instead just contain an index of dtype `ABC`. 

Yes, only `makeObjectSeries` returns a series that contains `dtype=object`... It is so weird. I think `makeObjectSeries` do correct job and other things are not. I think every `makeABCSeries` should return `dtype=ABC` with default index. What do you expect as exact result of `makeABCSeries`? 

> Do you have any thoughts on how those methods are comprehensively used?

About that, it's too hard question to me :)

**Comment by WillAyd** [comment]
> I think `makeObjectSeries` do correct job and other things are not. I think every `makeABCSeries` should return `dtype=ABC` with default index.

Yea that seems logical to me though doesn't appear to be the case. cc @jreback in case of any historical knowledge as to why things are that way

**Comment by jreback** [comment]
thanks @jmg7173 

yeah we likely have enough testing already in place.

**Pull request merged**
