### PR TITLE
ENH: Move NumExprClobberingError to error/__init__.py per GH27656

### PR DESCRIPTION
**Pull request by dataxerik**
- [x] xref #27656. this GitHub issue is being done in multiple parts
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by mroeschke** [comment]
Looks like there are docbuild failures

```
2022-06-06T02:29:12.9065297Z /home/runner/work/pandas/pandas/doc/source/reference/testing.rst:64:<autosummary>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
2022-06-06T02:29:12.9067287Z /home/runner/work/pandas/pandas/pandas/errors/__init__.py:docstring of pandas.errors.NumExprClobberingError:2: WARNING: Inline interpreted text or phrase reference start-string without end-string.
```

**Comment by dataxerik** [comment]
> Looks like there are docbuild failures
> 
> ```
> 2022-06-06T02:29:12.9065297Z /home/runner/work/pandas/pandas/doc/source/reference/testing.rst:64:<autosummary>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
> 2022-06-06T02:29:12.9067287Z /home/runner/work/pandas/pandas/pandas/errors/__init__.py:docstring of pandas.errors.NumExprClobberingError:2: WARNING: Inline interpreted text or phrase reference start-string without end-string.
> ```

Ah yeah, my bad, illegal use of bad tick lol. I've fixed it. Thank you for the feedback

**Review by mroeschke — COMMENTED** [review]
Looks good. Just a merge conflict otherwise LGTM

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Making great progress on that issue, thanks again!

**Pull request merged**
