### PR TITLE
DOC/BLD: unpin sphinx to use sphinx 1.7

### LINKED ISSUE #16705: DOC: fix API docs generation with sphinx 1.6
See discussion https://github.com/pandas-dev/pandas/pull/16702#issuecomment-308689543. Pinned sphinx to 1.5* for now (https://github.com/pandas-dev/pandas/pull/16704)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/pandas-dev/pandas/issues/18147, closes https://github.com/pandas-dev/pandas/issues/16705

Sphinx 1.7 is released, so let's try out if we can now remove the pinning of sphinx to 1.5.x

### CODE REVIEW

**Comment by jreback** [comment]
loooks like the build timedout

**Comment by jorisvandenbossche** [comment]
Yep, but it is still using sphinx 1.6.6, so therefore that was to be expected. 
Apparently it's not yet on the defaults channel (it's on conda-forge, but I assume we just use defaults?)

**Comment by jorisvandenbossche** [comment]
Last commit seems to work! No failure, no time-out

**Comment by jorisvandenbossche** [comment]
I think it would be good (in another PR) to update our vendored versions of IPython.sphinxext and numpydoc to their latest versions, so once they are released, it will be easier to remove them.

**Comment by TomAugspurger** [comment]
@jorisvandenbossche I think the main channel has been updated to include sphinx 1.7

**Comment by jorisvandenbossche** [comment]
OK, thanks for noticing. Updated the PR. If it builds, this should be good to go.

**Comment by jreback** [comment]
FYI I won't generally merge doc related PR's (for doc building type things), unless you ping and say ok

**Comment by jorisvandenbossche** [comment]
It was just a general note, not necessarily meant to say that you should merge this :) 
Anyway, it is building! (and not timing out)

**Pull request merged**
