### PR TITLE
ENH: Distinguish widths argument in read_fwf

### LINKED ISSUE #34953: ENH: more distinguish name for widths arugment in read_fwf
#### Is your feature request related to a problem?
We ran into the problem that `read_fwf` uses `widths` as an argument to define contigious intervals. But because of `**kwargs`, it will also accept `width` and not throw a warning or error. In this case it will product the wrong output, but without seeing the typo, it;s hard to find out what went wrong.
#### Describe the solution you'd like

Instead of the argument `widths`, use a more distinguish / informative name like `fixed_widths`. Or if changing the name is not preferable, we can throw a warning when a `width` is used in `read_fwf` instead of `widths`

#### API breaking implications

Not sure

Example with using the correct argument `widths`
```python
d = StringIO("""
AA1234     aaaa     bbb
BB5678     cccc     ddd
CC9999     eeee     fff
""")

fixed_widths = [2, 4, 9, 8]
df = pd.read_fwf(d, widths=fixed_widths)

  Unnamed: 0  Unnamed: 1 Unnamed: 2 Unnamed: 3
0         AA        1234       aaaa        bbb
1         BB        5678       cccc        ddd
2         CC        9999       eeee        fff
```
Example using the wrong argument `width`:
```
d = StringIO("""
AA1234     aaaa     bbb
BB5678     cccc     ddd
CC9999     eeee     fff
""")

fixed_widths = [2, 4, 9, 8]
df = pd.read_fwf(d, width=fixed_widths)

  Unnamed: 0 Unnamed: 1 Unnamed: 2
0     AA1234       aaaa        bbb
1     BB5678       cccc        ddd
2     CC9999       eeee        fff
```

### PR DESCRIPTION
**Pull request by erfannariman**
- [x] closes #34953
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by erfannariman** [comment]
To start the discussion about the argument names, thought I make the changes and create a PR. To make it consistent, I changed `colspecs` to `col_specs` as well.

**Comment by WillAyd** [comment]
This breaks API pretty heavily so can't just go with it in current form; would have to go through a depreciation cycle first

This is somewhat related to #22639 though I don't think `col_specs` is much better than `colspecs` so I'd be -1 on doing this given churn

**Comment by erfannariman** [comment]
> This breaks API pretty heavily so can't just go with it in current form; would have to go through a depreciation cycle first
Sure, but I'm not familiar with it, is there any documentation on that which I can go through? 

> This is somewhat related to #22639 though I don't think `col_specs` is much better than `colspecs` so I'd be -1 on doing this given churn

In my opinion I think going with `col_specs` and `col_widths` would make more sense, purely for the consistency and the problem I mentioned in the issue, where using `width` instead of `widths` will not throw an error and the argument names are too similar.

**Comment by WillAyd** [comment]
> where using `width` instead of `widths` will not throw an error and the argument names are too similar.

That is unrelated to the naming convention. I think if you wanted to remove kwargs from this and replace with the appropriate name arguments that would make more sense, as there are probably only a few that should be passed from this to the TextFileReader

**Comment by erfannariman** [comment]
> > where using `width` instead of `widths` will not throw an error and the argument names are too similar.
> 
> That is unrelated to the naming convention. I think if you wanted to remove kwargs from this and replace with the appropriate name arguments that would make more sense, as there are probably only a few that should be passed from this to the TextFileReader

That makes sense as well. Although I would not be sure how to decide which name arguments to include / exclude, would that be all the arguments which can be found in the tests?

**Comment by WillAyd** [comment]
The best way I think is to look at the TextFileReader implementation and see what kwargs it reads that make sense for a fixed width file

**Review by jreback — CHANGES_REQUESTED** [review]
yeah we cannot simply change these w/o a deprecation cycle, nor do i think the churn is worthile.

However as @WillAyd indicated, remove the ability to accept ``**kwargs`` would be ok

**Comment by erfannariman** [comment]
Yes, will pick this up after my vacation.

**Comment by dsaxton** [comment]
@erfannariman Can you merge master to fix conflicts?

**Pull request closed without merging**
