### PR TITLE
BUG: DatetimeIndex.snap incorrectly setting freq

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by WillAyd** [comment]
Sounds good though I think we want to deprecate this function? #27098

**Comment by jbrockmendel** [comment]
> though I think we want to deprecate this function

Yah, i think the argument was that `round` can do what it snap does, but there was a comment somewhere that this isnt quite accurate.  Regardless, fixing the bug is worthwhile.

**Comment by jorisvandenbossche** [comment]
Should infer the frequency in case the result is actually regular? (to keep the correct behavior for those cases)

**Comment by jbrockmendel** [comment]
> Should infer the frequency in case the result is actually regular? (to keep the correct behavior for those cases)

Either way I guess.  I tend to prefer not inferring in most places.

**Comment by jreback** [comment]
thanks

**Pull request merged**
