### PR TITLE
DOC: fix DataFrame.quantile docstring and doctests

### LINKED ISSUE #22898: DOC: Fix the docstring of quantile in pandas/core/frame.py
pandas docstring are expected to follow the format defined in https://pandas.pydata.org/pandas-docs/stable/contributing_docstring.html

This includes among other things:
- There is a short description fitting in one line (there can be a longer one after that).
- The description of the parameters, the returns section, and the see also items, starts with a capital letter and ends with a period.
- In the Return section there is no name before the type (e.g. `transformed : Series`) but just the type (e.g. `Series`) in the first line.
- The examples are valid PEP-8 code, and when executed, they produce the shown input.

We should make the required adjustments in the docstring of the function `quantile` in `pandas/core/frame.py`.

We should validate the docstring with our validator (which does not validate all the formats, but some):
- `./scripts/validate_docstrings.py pandas.DataFrame.quantile`

And we should validate the PEP-8 of the examples (note that the next command will validate the PEP-8 of all examples, just make sure that none of the shown is in the function being addressed, the rest will be fixed in separate issues):
- `flake8 --doctests pandas/core/frame.py`

### PR DESCRIPTION
**Pull request by Moisan**
- [x] closes #22898
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Based on #22459. Fix the docstring for DataFrame.quantile. I also updated `ci/code_checks.sh`.

### CODE REVIEW

**Comment by Moisan** [comment]
Crap forgot to double check the open pull requests before working on this. Closing in favor of #22906.

**Comment by datapythonista** [comment]
@Moisan, #22906 is stale. Reopening this. If you don't mind taking a look at the discussions there, and finish the changes here, that would be great.

**Comment by brute4s99** [comment]
Gimme half hour, finishing it

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @Moisan 

the CI is currently broken, you'll have to merge maste when #24160 is fixed, so we can see everything is green.

**Comment by datapythonista** [comment]
@Moisan can you merge master and push again. CI is fixed now.

**Comment by jreback** [comment]
thanks @Moisan

**Pull request merged**
