### PR TITLE
avoid non-standard imports

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you add a rule to find these in the 'patterns' section

**Comment by jbrockmendel** [comment]
> can you add a rule to find these in the 'patterns' section

There are still 22 files left that do this, so itll take a couple more passes.

**Comment by jreback** [comment]
would be nice to have a rule - u can comment it out for now that finds these

**Comment by jbrockmendel** [comment]
Done

**Review by jreback — APPROVED** [review]

**Pull request merged**
