### PR TITLE
Concat perf

### LINKED ISSUE #11958: Performance issue with DataFrames with numpy fortran-order arrays and pd.concat
Hi,

When trying to concat() multiple big fortran order arrays, there is a big performance hit, as most of the work goes into calling ravel().  

See: 
https://github.com/pydata/pandas/blob/master/pandas/core/internals.py#L4772

You can see the  `is_null(self)` is using just a few values from the data after calling `.ravel()`

An easy fix is to change that line to `values_flat = values.ravel(order='K')`

Here is a link to numpy.ravel docs:  http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.ravel.html

``` ‘K’ means to read the elements in the order they occur in memory, except for reversing the data when strides are negative. By default, ‘C’ index order is used.```

### PR DESCRIPTION
**Pull request by jennolsen84**
fixes #11958

### CODE REVIEW

**Comment by jreback** [comment]
pls add a whatsnote in v0.18.0 on perf section.

squash as well

**Comment by jennolsen84** [comment]
Done, please let me know if you need anything else.  Curious, any ETA yet on 0.18.0? (No rush)

**Comment by jreback** [comment]
thanks long when green

0.18.0 prob end of the month

**Comment by jennolsen84** [comment]
All green.  Thanks @jreback

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/3667b7636da878427c72dd59e1a5845e52ea306c

thanks!

**Pull request closed without merging**
