### PR TITLE
ENH: add np.nan* funcs to cython_table

### LINKED ISSUE #19629: series.agg(np.nansum) etc. returns a  series, scalar expected
```python
>>> pd.Series([1,2,3,4]).agg(np.sum)
10
>>> pd.Series([1,2,3,4]).agg(np.nansum)
0    1
1    2
2    3
3    4
dtype: int64
```
I would expect the return values of ``.agg(np.nansum)`` and ``agg(np.sum)`` to be the same. 

the same issue is with np.nanmean, np.nanmax etc.

#### Problem description

The underlying issue is that ``SelectionMixIn._cython_table`` has records for ``np.sum``, ``np.mean`` etc, but not ``np.nansum``, ``np.nanmean`` etc.

From a quick look at it, it seems that the issue is easily fixable, by adding the ``np.nan*`` function to cython_table.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 7590b8723516a9d595c287067fa639fbb9e19ec1
python: 3.6.3.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0.dev0+710.g7590b87.dirty
pytest: 3.3.1
pip: 9.0.1
setuptools: 38.2.5
Cython: 0.26.1
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.9
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0b10
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by topper-123**
- [x] closes #19629
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

This PR ensures that ``Series.agg`` can correctly take np.nan* funcs as inputs, e.g.:

```python
>>> pd.Series([1,2,3,4]).agg(np.nansum)
10
```

Previously that operation returned a Series. See #19629 for details.

Tests are added through the use of ``_get_cython_table_params`` in the parametrisation of ``test_agg_cython_table`` test function in ``series/test_apply``/``frame/test_apply``.

### CODE REVIEW

**Comment by topper-123** [comment]
The failure is caused by a bug introduced in #21224. A fix has been proposed in #22110.

**Comment by jreback** [comment]
so couple of things on this. I don't the the additional functions are actually tested when run in pandas/tests/frame/test_apply.py. Its also very hard to see as the ``ids`` are not specified when actually running these tests, can you fixup?

**Comment by jreback** [comment]
@topper-123 can you rebase

**Comment by jreback** [comment]
can you rebase

**Comment by topper-123** [comment]
Rebased.

Also, there were xfailed tests in ``test_agg_category_nansum`` that now pass. They also use the fixture from conftest.fy. Not sure if the test should be just deleted.

**Pull request merged**
