### PR TITLE
COMPAT: pyarrow >= 0.7.0 compat

### LINKED ISSUE #17581: TST/CI: PyArrow Test Failures
Weird `pyarrow` failures going on with <a href="https://github.com/pandas-dev/pandas/commit/37e23d03e1ba2298d9df05ded69028dfac0e823e">37e23d</a>:

https://travis-ci.org/pandas-dev/pandas/jobs/276857797
https://travis-ci.org/pandas-dev/pandas/jobs/276857799

Looks unrelated to commit, so something probably went wrong with `pyarrow`

cc @jreback @jorisvandenbossche @wesm

### PR DESCRIPTION
**Pull request by jreback**
closes #17581

### CODE REVIEW

**Comment by jreback** [comment]
```
In [13]: import pyarrow

In [14]: pyarrow.__version__
Out[14]: '0.7.0'

In [15]: df = pd.DataFrame({'a': pd.Categorical(list('abc'))})

In [16]: df.dtypes
Out[16]: 
a    category
dtype: object

In [17]: df.to_parquet('foo.pq', engine='pyarrow')

In [18]: pd.read_parquet('foo.pq', engine='pyarrow')
Out[18]: 
   a
0  a
1  b
2  c

In [19]: pd.read_parquet('foo.pq', engine='pyarrow').dtypes
Out[19]: 
a    object
dtype: object
```

@wesm 
de-serializing seems not to preserve the cat type ?

**Comment by wesm** [comment]
Correct, it comes back as non-categorical. _Parquet does not have a categorical type_. We can try to emulate it as best we can (not foolproof; when dictionaries grow too big, encoding is turned off) but it will take some more work in parquet-cpp.

**Comment by jreback** [comment]
no need to emulate. will make a note in the docs.

**Comment by wesm** [comment]
We're going to support direct column reads as categorical soon hopefully, which will use the dictionary page if there is one, but that has some edge cases:

* Dictionaries generally will be different from file to file
* Dictionaries may be different within each row group
* A column chunk may switch to plain encoding mid-stream (if the dictionary got too big)

**Pull request merged**
