### PR TITLE
TST: add messages to bare pytest raises in pandas/tests/io/pytables/test_timezones.py

### PR DESCRIPTION
**Pull request by marktgraham**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This PR adds messages to the bare pytest raises in pandas/tests/io/pytables/test_timezones.py. This PR references https://github.com/pandas-dev/pandas/issues/30999.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Nice, thanks! looks good to me pending green

---

feel free to take on more than one file in the same PR if the changes aren't too big

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
It looks like, during one of the CI jobs, the error shows `'existing_value [dateutil/US/Eastern] conflicts with new value [dateutil/EET]'`, without `/usr/share/zoneinfo`

so you may need a regular expression here, e.g. something like
```python
        msg = (
            r"invalid info for \[values_block_1\] for \[tz\], "
            r"existing_value \[dateutil/.*US/Eastern\] "
            r"conflicts with new value \[dateutil/.*EET\]"
        )
```

**Comment by marktgraham** [comment]
> Nice, thanks! looks good to me pending green

Thanks!

> feel free to take on more than one file in the same PR if the changes aren't too big

Will do, I think that will work for a couple of the other files.

**Comment by marktgraham** [comment]
@MarcoGorelli thanks for your suggestion, I made the change and now all the checks pass.

**Review by MarcoGorelli — APPROVED** [review]

**Comment by jreback** [comment]
thanks @marktgraham

**Pull request merged**
