### PR TITLE
PERF: consolidate imports inside parse_time_string

### PR DESCRIPTION
**Pull request by qwhelan**
This PR adds an asv benchmark for the creation of `Period` objects directly from integers, and an associated speedup for the same case.

When calling `Period._from_ordinal()`, the runtime is unfortunately dominated by a pair of import statements needed to pull in the global config settings `display.date_dayfirst` and `display.date_yearfirst`. Thus, simply consolidating them leads to a significant speedup:
```
Benchmarks that have improved:

       before           after         ratio
     [08395af4]       [696b40f1]
     <parse_time_string~1>       <parse_time_string>
-         176±3ms         98.7±3ms     0.56  period.PeriodIndexConstructor.time_from_ints('D')
```

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase on master; I think there might be an error in the benchmark (or if not the script should complete green, the CI has been fixed).

**Comment by jreback** [comment]
can you remove the ``warnings`` from ``asv/benchmarks/frame_methods`` and re-push. thanks.

**Comment by qwhelan** [comment]
@jreback I believe the warnings in frame_methods were handled in another PR, so I've rebased again off master.

**Comment by jreback** [comment]
thanks @qwhelan

**Pull request merged**
