### PR TITLE
DOC: Fix rendering of whatsnew entries

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
cc @rhshadrach those render in a weird box if you have a space in the beiginning

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Looks good, thanks for fixing those.

In case you want to also address it here, looks like we've got a second notable bug fixes section that I guess we want to get rid of.

**Comment by phofl** [comment]
We tend to keep those and clean them up when releasing, it’s a good placeholder until we cut the release

**Comment by rhshadrach** [comment]
Thanks @phofl

**Pull request merged**
