### PR TITLE
BUG: format multiple CSS selectors correctly

### LINKED ISSUE #34061: BUG: using a list in "selector" for set_table_styles produces wrong rules
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

Example: I want to apply a style like this:

`df.style.set_table_styles([{'selector': 'th.col_heading,th.blank', 'props': [('display', 'none')]}])`

Note a list (`th.col_heading,th.blank`) as selector. This produces wrong CSS, because UUID of the table is only prepended once to this selector:

    #T_table_UUID th.col_heading, th.blank {
          display: none;
    }

i.e. __all__ `th.blank` elements in all tables on the page are hidden. This is not exactly intuitive, although the workaround is simple: you need to write

`set_table_styles([{'selector': 'th.col_heading', 'props': [('display', 'none')]}, {'selector': 'th.blank', 'props': [('display', 'none')]}])`

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.6.10-arch1-1
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : 3.0.3
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.14.0
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.16
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by attack68**
- [x] closes #34061 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Fixes a bug that doesn't format multiple CSS elements in selectors properly.

### CODE REVIEW

**Comment by attack68** [comment]
Anyone know how to correctly define a `TypedDict` for testing??

`from typing import TypedDict` failed on all python 3.7.

`from typing_extensions import TypedDict` failed on some python 3.7 builds since there is no `typing_extensions` module??

**Comment by jreback** [comment]
you mean like `Dict[str, Any]` or whatever?

**Comment by attack68** [comment]
> you mean like `Dict[str, Any]` or whatever?

to get this function to work nicely with `mypy` I needed to add:

```
class CSSDict(TypedDict):
    selector: str
    props: CSSProperties
```
which needed either
```
from typing import TypedDict  # 3.8+
from typing_extensions import TypedDict  # only included in some of the 3.7- builds.

**Comment by jreback** [comment]
can u make a data class instead?

**Comment by jreback** [comment]
@simonjayhawkins any suggestions here

**Comment by attack68** [comment]
OK I reformatted and ignored the structure, just used `cast` instead to fix `mypy`.

@jreback this is greenish now for review

**Comment by simonjayhawkins** [comment]
> just used `cast` instead to fix `mypy`.

we should only use a cast if know better than mypy or it is a false positive.

can you add a comment in the code, about why we can guarantee that `style["selector"]` is a `str` and not a `CSSList` if `styles` is of type `CSSStyles` which is `List[Dict[str, CSSProperties]]` and `CSSProperties` is of type `Union[str, CSSList]`

the list comprehension has 4 for statements. If this is refactored, does that help mypy?

**Comment by attack68** [comment]
@simonjayhawkins 

Thats why I tried to incorporate the TypedDict to make it clearer previously:

```
class CSSDict(TypedDict):
    selector: str
    props: CSSProperties
```
But didn't work for some of the 3.7builds which didn't have `typing_extensions`

so I reverted to 
```
Dict[str, Union[str, CSSProperties]]
```

But I know that in the case of the `selector` key it is only `str` type, so I think `cast` here is OK?

**Comment by simonjayhawkins** [comment]
> Thats why I tried to incorporate the TypedDict to make it clearer previously:
> 
> ```
> class CSSDict(TypedDict):
>     selector: str
>     props: CSSProperties
> ```

in the code we have the aliases...

```
CSSPair = Tuple[str, Union[str, int, float]]
CSSList = List[CSSPair]
CSSProperties = Union[str, CSSList]
CSSStyles = List[Dict[str, CSSProperties]]
```
> But I know that in the case of the `selector` key it is only `str` type, so I think `cast` here is OK?

so without `TypedDict` that knowledge about `CSSDict` is not codified into the type aliases, so a comment in the code to help future readers may be beneficial.

from https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md

> Typed Dictionaries, Data Classes, and Named Tuples
>If your library runs only on newer versions of Python, you are encouraged to use some of the new type-friendly classes.
>
>NamedTuple (described in PEP 484) is preferred over namedtuple.
>
>Data classes (described in PEP 557) is preferred over untyped dictionaries.
>
>TypedDict (described in PEP 589) is preferred over untyped dictionaries.

so if we can't use `TypedDict` we should use data classes as suggested by @jreback in https://github.com/pandas-dev/pandas/pull/39942#issuecomment-784153922, or less preferable convert the untyped dict to a namedtuple.

**Comment by attack68** [comment]
@simonjayhawkins I investigated the `DataClass` solution which was new to me, and correct me if I'm wrong, but since the api input args use dicts and the user cannot be expected to pass in a `DataClass` then there would have to be a lot of internal mechanics to coordinate this, let alone changing hundreds of lines of tests (which I already did once and don't fancy doing again). Primarily since `d['selector']` doesn't work for a dataclass: you have to change to `d.selector`. So I think thats why I disregarded that one.

And then I considered the named tuple, and again from memory I think this faced exactly the same issue.

I'm tempted to fix this very trivially, *in the future*, with the `TypedDict` when it becomes fully available in `pandas`!

I understand he point about the aliases that exist in the code and helping future readers, but two months ago there wasn't any typing for these and a mismatch of patterns across the module (but it is improving) , so I'm keen just to code comment it for now. :)

**Comment by simonjayhawkins** [comment]
> but since the api input args use dicts and the user cannot be expected to pass in a `DataClass`

if that's the case, then indeed we can't change that.

> I understand he point about the aliases that exist in the code and helping future readers, but two months ago there wasn't any typing for these and a mismatch of patterns across the module (but it is improving) , so I'm keen just to code comment it for now. :)

code comment is fine

**Comment by jreback** [comment]
looks fine. ping on green.

**Comment by attack68** [comment]
@jreback ping all green.

**Comment by jreback** [comment]
thanks @attack68

**Pull request merged**
