### PR TITLE
Fix for 55753 BUG: No kwargs in df.apply(raw=True) [  Backport to 2.1.x ]

### LINKED ISSUE #55753: BUG: No kwargs in `df.apply(raw=True)`
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

def func(a, b):
    return a + b

df = pd.DataFrame([[1, 2], [3, 4]])
df.apply(func, b=1) # OK
df.apply(func, raw=True, b=1) # TypeError: func() missing 1 required positional argument: 'b'
```

### Issue Description

`df.apply(raw=True)` should act similarly to `df.apply(Raw=False)`. It worked below v2.1.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.9.18.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.0-75-generic
Version             : #82~20.04.1-Ubuntu SMP Wed Jun 7 19:37:37 UTC 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8
pandas              : 2.1.2
numpy               : 1.25.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 67.4.0
pip                 : 23.0.1
Cython              : 3.0.4
pytest              : 7.4.3
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : 2.8.7
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

### PR DESCRIPTION
**Pull request by dannyi96**
- [x] closes #55753
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
Thanks could you add a whatsnew entry in `v2.1.4.rst`?

**Comment by dannyi96** [comment]
done, updated the whatsnew

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @dannyi96

**Comment by lithomas1** [comment]
I think we needed to move the whatsnew from 2.2.0 to 2.1.3, since there's an existing whatsnew already from the original PR that fixed this.

@dannyi96 Interested in doing another PR against main fixing this?

**Comment by dannyi96** [comment]
sure @lithomas1.
do you mean removing the related whatsnew in v2.2.0.rst since its already been added in v2.1.3.rst ( & hence not a new fix in 2.2.0) ?

**Comment by lithomas1** [comment]
You need to move it since your changes only applied to 2.1.x not main.

**Pull request merged**
