### PR TITLE
TST: isort tests/sparse

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref #23334

### CODE REVIEW

**Comment by jreback** [comment]
thanks, ping on green.

**Comment by alimcmaster1** [comment]
```
2019-01-02T18:24:36.6848722Z` Generating script.
2019-01-02T18:24:36.7511360Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\9e867d74-ceab-4e48-b2ab-0e4ef4136180.cmd""
2019-01-02T18:24:36.9818850Z Could not find conda environment: pandas-dev
```

Does a core dev mind restarting the failed azure builds here? Seems to be an issue with the conda env.. not sure what this could be.

**Comment by jreback** [comment]
see #24564 on hold till this is fixed

**Comment by jreback** [comment]
thanks @simonjayhawkins

**Pull request merged**
