### PR TITLE
CI: Code checks ensure return status is handled

### PR DESCRIPTION
**Pull request by alimcmaster1**
Follow up from discussion here. https://github.com/pandas-dev/pandas/pull/30370#discussion_r361213525

Seems like we are not return the return code of all these code checks - unless I am missing something?

Expected this to fail on master until https://github.com/pandas-dev/pandas/pull/30455 is merged

cc. @WillAyd @datapythonista

### CODE REVIEW

**Comment by WillAyd** [comment]
Hmm OK - so I guess none of these were doing anything before? Do they all return the same value on failure or is it possible for a -1 return to clash with a +1 return now?

**Comment by alimcmaster1** [comment]
> Hmm OK - so I guess none of these were doing anything before? Do they all return the same value on failure or is it possible for a -1 return to clash with a +1 return now?

Yeah I believe these were not doing anything before.. all our other uses of invgrep update RET afterwards.

Believe our invgrep only returns [0,1] in `code_checks.sh`, so no need to worry about return values < 0 unless i'm missing something?

```
function invgrep {
    # grep with inverse exist status and formatting for azure-pipelines
    #
    # This function works exactly as grep, but with opposite exit status:
    # - 0 (success) when no patterns are found
    # - 1 (fail) when the patterns are found
```

**Comment by WillAyd** [comment]
OK lgtm then. @datapythonista care to take a look?

**Review by datapythonista — APPROVED** [review]
Strange that we missed this before, but yes, this seems to make sense.

**Review by datapythonista — APPROVED** [review]
Strange that we missed this before, but yes, this seems to make sense.

**Comment by alimcmaster1** [comment]
Will merge master once Marc has had a look. (Code checks should then pass since #30455 is now merged)

**Comment by alimcmaster1** [comment]
> Strange that we missed this before, but yes, this seems to make sense.

Great thanks for taking a look - much appreciated!

**Comment by datapythonista** [comment]
Thanks for spotting and fixing those @alimcmaster1 

For reference, this was introduced here: #29318

Not sure if for consistency/clarity we could have a separate error message for each of those, like everywhere else in the file. But not really important.

**Pull request merged**
