### PR TITLE
REF/API: make construct_array_type a non-classmethod

### LINKED ISSUE #58663: REF/API: make construct_array_type a non-classmethod
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
NA
```

### Issue Description

It is already a non-classmethod for StringArray, in order to support different storage attributes that are present on the instance but not on the class.  We should make this official if, as seems likely, more dtypes are going to become parametrized (see PDEP-13, PDEP-14)

### Expected Behavior

NA

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

### PR DESCRIPTION
**Pull request by miguelpgarcia**
- [x] closes #58663 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Comment by miguelpgarcia** [comment]
Since it is already a non-classmethod in StringArray, making the abstract method non-classmethod would ensure code consistency.

**Comment by miguelpgarcia** [comment]
Since it's my first PR, I would greatly appreciate your valuable feedback @jbrockmendel

**Comment by jbrockmendel** [comment]
#58663 is not a good issue for a beginner.  please look for an issue with the "good first issue" label

**Comment by miguelpgarcia** [comment]
I did indeed look for some alternatives with this label, but ultimately concluded that this issue remained the most appropriate one and the one I was most interested in investigating further.

**Comment by jbrockmendel** [comment]
> concluded that this issue remained the most appropriate one

It is not.  Please look again.

**Comment by miguelpgarcia** [comment]
I apologize if I chose an inappropriate issue. I consulted with a colleague who has previously contributed to this repository and they assured me it was fine. If anything is missing from the modified files, or if further discussion/research regarding the issue is needed, that's perfectly okay.

**Comment by jbrockmendel** [comment]
The hard part of addressing #58663 is not changing a few lines of code, but in achieving consensus that it is a change we _want_ to make, then in making the change without breaking 3rd party subclasses.

**Comment by mroeschke** [comment]
Thanks for the PR @miguelpgarcia but agreed that making a PR is premature at this point and would need more coordination to start opening a PR to address. Going to close, but happy to have your contributions towards issues labeled `good first issue`

**Pull request closed without merging**
