### PR TITLE
DOC: Fixed PR06 (wrong parameter type) in pandas.Timestamp

### PR DESCRIPTION
**Pull request by willpeppo**

### CODE REVIEW

**Comment by dsaxton** [comment]
@willpeppo Your change looks right, but I think you also need to make the corresponding change in pandas/_libs/tslibs/nattype.pyx to get CI to pass

**Comment by willpeppo** [comment]
Dan- thank you for the feedback!   I decided over the weekend to make my first oss contribution and have been wrestling through it the past few days.  I really appreciate the comment.  How did you determine that btw ?

**Comment by dsaxton** [comment]
> Dan- thank you for the feedback! I decided over the weekend to make my first oss contribution and have been wrestling through it the past few days. I really appreciate the comment. How did you determine that btw ?

No problem, thanks for the contribution. You can see what's wrong by clicking the "Details" next to one of the failed pipelines, for example: https://github.com/pandas-dev/pandas/pull/34561/checks?check_run_id=736430284.

It shows that two tests failed and you can take a look at the logs by clicking "View more details on Azure Pipelines" and going to "Tests". There you can look for an error message and by thinking through what's being tested figure out how to fix the issue.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks @willpeppo for the contribution, and @dsaxton for the review!

**Pull request merged**
