### PR TITLE
Switch to setup-micromamba

### PR DESCRIPTION
**Pull request by jonashaag**
We are deprecating `provision-with-micromamba` and replacing it with https://github.com/mamba-org/setup-micromamba.

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jonashaag** [comment]
@pavelzw sorry for not synchronizing on this. I’ll merge your changes into this. Anything else I should include?

**Comment by pavelzw** [comment]
No worries, I didn't see anything else that was not in my PR on first glance.

**Comment by jonashaag** [comment]
Should be good when green

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Sweet, thanks @jonashaag

**Comment by mroeschke** [comment]
Noting based on the conflicts, I don't think we should backport this.

**Comment by pavelzw** [comment]
```yml
extra-specs: |
  a
  b
  c
```

should be changed to
```yml
create-args: >-
  a
  b
  c
```

**Comment by mroeschke** [comment]
Thanks! I will create a PR to update this

**Comment by jonashaag** [comment]
Whoops thanks

**Pull request merged**
