### PR TITLE
ENH: `sparse_columns` and `sparse_index` added to `Styler.to_html` 

### PR DESCRIPTION
**Pull request by attack68**
Checks an item off the list in #41693

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@attack68 does this need a release note?

you can keep adding to the 1.3 release notes. is Styler still experimental? I think we can merge these changes to 1.3 during the rc (if not done before)

**Comment by attack68** [comment]
> @attack68 does this need a release note?
> 
> you can keep adding to the 1.3 release notes. is Styler still experimental? I think we can merge these changes to 1.3 during the rc (if not done before)

No release note needed, since these args _could_ have been added in the previous PR that added the method to 1.3.0.

I think Styler is fully functional now, it has extensive docs, improved performance and features, high test coverage, and very close to being able to deprecate DataFrame.to_html and DataFrame.to_latex. Its also been around a number of years now so I would say well integrated into the package.

No reason this can't get into 1.3 as long as it fits your timeline.

**Comment by simonjayhawkins** [comment]
> No reason this can't get into 1.3 as long as it fits your timeline.

i think OK for 1.3

**Comment by jreback** [comment]
don't add milestones

**Comment by simonjayhawkins** [comment]
> don't add milestones

sure. if not 1.3 will need a release note. IIUC This sits on top an enhancement for 1.3.

**Comment by simonjayhawkins** [comment]
and versionadded tags for the new parameters

**Comment by attack68** [comment]
@simonjayhawkins has this missed the boat for 1.3.0?

I can change to 1.4.0 if so.

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins has this missed the boat for 1.3.0?

not necessarily if additions to enhancements added in 1.3. The `to_html` of Styler is new for 1.3? I've not really followed the changes. Do we still have a `.render` method and does it share code?

**Comment by attack68** [comment]
> > @simonjayhawkins has this missed the boat for 1.3.0?
> 
> not necessarily if additions to enhancements added in 1.3. The `to_html` of Styler is new for 1.3? I've not really followed the changes. 

yes this is additions to a 1.3.0 enhancement. The only reason it wasn't added previously was to reduce the size of that other  PR and for this to be a simple follow on.

> Do we still have a `.render` method and does it share code?

Yes there is still a `.render` method currently but I will look to propose its deprecation for 1.4.0 since it becomes redundant. Its a reasonable amount of work to migrate the tests though thats why I didnt have time for 1.3.0.

**Comment by attack68** [comment]
This seemed to miss 1.3.0 so I have added the necessary tags and comments for 1.4.0 insted.

**Review by jreback — APPROVED** [review]
lgtm merge on green

**Comment by jreback** [comment]
thanks @attack68

**Pull request merged**
