### PR TITLE
CI: troubleshoot OOB timedelta test

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@jreback looks like this gets us back to green

**Comment by jreback** [comment]
great, weird that the f-string wouldn't string-ify the same, but I guess it does repr?

**Comment by jbrockmendel** [comment]
must be something either in cython or numpy?

**Comment by nmay231** [comment]
FYI, you can use `f'{value!s}'` to call str() instead of repr()

**Pull request merged**
