### PR TITLE
Bump asv Python version

### LINKED ISSUE #34677: BUG: ASV Benchmarks failing to build
ASV benchmarks fail to build on master. Could this be related to #34666? 

`error: command 'gcc' failed with exit status 1`

Anyone else having this issue?

### PR DESCRIPTION
**Pull request by dsaxton**
Got this error trying to run the asvs locally and bumping the Python version in asv.conf.json fixed it:

```
   STDOUT -------->
   Processing /Users/danielsaxton/pandas/asv_bench/env/a36d556a9d1611aba4092dc48036d261/project
       Preparing wheel metadata: started
       Preparing wheel metadata: finished with status 'done'
   STDERR -------->
   ERROR: Package 'pandas' requires a different Python: 3.6.10 not in '>=3.7.1'
```

Let me know if this is needed / correct in general or if it was just a thing with my machine.

cc @TomAugspurger 

Closes https://github.com/pandas-dev/pandas/issues/34677

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
If we change this, let's directly bump to Python 3.8?

It has come up a few times before recently (updating the python version, eg https://github.com/pandas-dev/pandas/pull/34699), and the conclusion was to do this after the 1.1 release, so now is the time ;)

**Comment by TomAugspurger** [comment]
Yep, might as well do it now.

Though it would be good if anyone could scan through the recent values to
look for regressions, since that will become harder after the break.

**Comment by dsaxton** [comment]
Does this then close https://github.com/pandas-dev/pandas/issues/34677? There's a comment there about things failing on Python 3.6 which seems not to be relevant anymore.

**Comment by dsaxton** [comment]
Taking a quick look at the asv time series a few that jumped out to me:

https://pandas.pydata.org/speed/pandas/#timeseries.TimeDatetimeConverter.time_convert
https://pandas.pydata.org/speed/pandas/#reindex.LevelAlign.time_reindex_level
https://pandas.pydata.org/speed/pandas/#timedelta.TimedeltaIndexing.time_intersection
https://pandas.pydata.org/speed/pandas/#io.hdf.HDFStoreDataFrame.time_read_store_mixed

Looks like the first two are somewhat recent regressions that may or may not already have issues (I think you reported a bunch of these recently @TomAugspurger), the other two go a bit further back.

https://pandas.pydata.org/speed/pandas/

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by TomAugspurger** [comment]
Let's give this a shot. I'll hopefully have time to debug stuff in the next couple days if the benchmark machine doesn't pick this up automatically.

**Pull request merged**
