### PR TITLE
DOC: Make pyplot import explicit in the 10 minutes to pandas page

### PR DESCRIPTION
**Pull request by ghost**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
I think should unhide this where it appears later in the guide rather than import here

**Comment by yuseitahara** [comment]
Hello. I made another PR https://github.com/pandas-dev/pandas/pull/30279 that unhide plt import. Could you merge it if it was ok? @WillAyd

**Comment by datapythonista** [comment]
@yuseitahara do you mind translating your last comment to English please, so we can understand it.

The solution here to remove the block with the `:suppress:` and add the import at the beginning of the only block where `plt` is used.

If you can't edit this PR from the GitHub UI, you should clone the pandas repo locally, and edit there.

**Comment by yuseitahara** [comment]
@datapythonista Thank you for your comment. My previous comment written in Japanese was for @Koki-kobe whom I helped during an OSS event to submit this PR since he was a beginner and what I wrote was about how to fix his PR as you wrote above. It seems that he does not notice this conversation unfortunately. Since I do not have a right to edit this PR, if you do not mind, could you please close this PR? Then I will make a new PR. Thank you.

**Comment by datapythonista** [comment]
Thanks for clarifying @yuseitahara 

Closing as requested.

**Pull request closed without merging**
