### PR TITLE
CLN: Enforce deprecation of using alias for builtin/NumPy funcs

### PR DESCRIPTION
**Pull request by rhshadrach**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Ref: #53974

### CODE REVIEW

**Comment by rhshadrach** [comment]
A bit of a complication here - I missed one of the paths in apply where we use the builtin/NumPy -> cython table.

https://github.com/pandas-dev/pandas/blob/54d2033fabc1a064b05842b41f8247ae3fdd6fd6/pandas/core/apply.py#L1439-L1442

Sadly, it's probably one of the more common cases where users will see a difference. This is because `apply` will first try to operate row-by-row (unless `by_row=False`), and e.g. `np.sum` works on rows.

I'm thinking we enforce the deprecation as-is (we already were not very consistent with where we were making these replacements), and deprecate the last remaining case as part of 3.x.

cc @jorisvandenbossche @mroeschke

**Review by mroeschke — COMMENTED** [review]
Changes generally look good. npdev failure looks real?

> I'm thinking we enforce the deprecation as-is (we already were not very consistent with where we were making these replacements), and deprecate the last remaining case as part of 3.x.

Yeah fine to do a follow up deprecation in 3.x

**Comment by jorisvandenbossche** [comment]
Yes, sounds good to me too!

**Comment by rhshadrach** [comment]
@mroeschke - green now.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @rhshadrach

**Pull request merged**
