### PR TITLE
MAINT: Fix broadcasting of arrays

### LINKED ISSUE #35481: Numpydev CI Failures
It looks like some `.intersection` tests are failing. AFAICT this traces back to here:

https://github.com/pandas-dev/pandas/blob/bdcc5bffaadb7488474b65554c4e8e96a00aa4af/pandas/_libs/lib.pyx#L685

Which on numpy dev during test execution isn't raising an `OverflowError` and instead performs a wraparound. Interestingly enough, running:

```python
np.asarray([2 ** 63, 2**63 + 1], dtype="int64") 
```

With numpydev does overflow in the Python space, so perhaps a Cython issue?

### PR DESCRIPTION
**Pull request by bashtage**
Prevent empty object arrays from being broadcast

- [X] closes #35481
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by bashtage** [comment]
Probably not the right fix for the future empty array assignment issue, but seems to work.

**Comment by simonjayhawkins** [comment]
@bashtage if this fixes #35481, I think tests should be failing (with XPASS), see #35502

**Comment by bashtage** [comment]
I thought it worked prior to rebase...I'll need to see what happens.

**Comment by bashtage** [comment]
Definitely not a fix.

**Pull request closed without merging**
