### PR TITLE
BUG: in Timestamp.replace when replacing tzinfo around DST changes

### LINKED ISSUE #15683: BUG: Timestamp.replace chaining not compat with datetime.replace
#### Code Sample, a copy-pastable example if possible

```python
import pytz
import pandas as pd
from datetime import datetime
pytz.timezone('CET').localize(datetime(2016, 3, 27, 1), is_dst=None)
pytz.timezone('CET').localize(pd.Timestamp(datetime(2016, 3, 27, 1)), is_dst=None)
```
#### Problem description

The above code runs with Pandas 0.18 but raises the following exception with Pandas 0.19:
```python
>>> pytz.timezone('CET').localize(pd.Timestamp(datetime(2016, 3, 27, 1)), is_dst=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localhome/stefan/emsconda/envs/popeye/lib/python3.6/site-packages/pytz/tzinfo.py", line 327, in localize
    raise NonExistentTimeError(dt)
pytz.exceptions.NonExistentTimeError: 2016-03-27 01:00:00
```
Is this an intentional API breakage of 0.19 or a bug?

#### Expected Output

<no exception>

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS

commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.12-100.fc24.x86_64+debug
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8
LOCALE: de_DE.UTF-8

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 34.3.0
Cython: None
numpy: 1.12.0
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.3.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: 1.5.0
bottleneck: None
tables: None
numexpr: None
matplotlib: 2.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.1.5
pymysql: None
psycopg2: None
jinja2: None
boto: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by jreback**
replaces #17356 
closes #15683

### CODE REVIEW

**Comment by sscherfke** [comment]
Really? You don’t really help with my PR for half a year and than you just replace it?

I hope I will never have to contribute to this project again.

**Comment by gfyoung** [comment]
@sscherfke : I haven't followed this PR (and its history) too closely.  However, based on what I have read, let me see if I can unpack this:

@jreback put up this PR 9 days after the last comments regarding your PR (#17356).  Generally, this is quite early to do a replacement PR.  That being said, I suspect the decision to do this was driven by the fact that there was lot more work to address on the *performance* and *code quality* sides than I imagine we anticipated.

From your previous comments, it sounded like you did not have much free time or energy left to devote to doing that (understandable, no one's life is purely just this repository).  Thus, it might have been easier logistically for us to take this under our wing and off your plate so that we could take it to the finish line.

**Comment by gfyoung** [comment]
> I hope I will never have to contribute to this project again.

I'm sorry that you feel this way.  Contributing to open source can sometimes be difficult, especially when the interests of the contributors and the maintainers don't fully align (I've sat on both sides of this conversation).  It happens, but that doesn't mean we don't appreciate the effort you've taken to help make `pandas` better.  Mind you that we're taking our own free time out of our busy lives to do this, so we have to use it wisely.  The fact that several of us have chosen to take the time to review your PR says something.

I should add though that you are not forced to use the official installations for your development.  You can apply these patches (in their current form) to your own installed version of `pandas`, and you don't have to worry about it getting merged into the official installation for the time being.

**Comment by jreback** [comment]
your commit is still here - and you will get the credit for it

**Comment by sscherfke** [comment]
I’ve been contributing to and maintaining my own OSS projects since many years now—and it wasn’t always easy. But this issue has been the most nerve-racking and exhausting one.

I reported the issue more than half a year ago (I guess) and when I finally convinced you that it was actually a bug I was told to make a PR. I asked for help because the Pandas source is not very easy to work with if you have never worked with and contributed to Pandas before. I received verly-little to no help except for comments like “not good enought”, “it’s not fast enough” (implying that fast is better than correct), and “please move your change log entries to the new history file” (every couple of weeks when there was a new release).

Now that I made a new, clean PR that finally received a “looks quite good“ you just replace it without discussion which felt very rude to me. I don’t care about the credit, I care about nice treatment of contributors (and especially first-time contributors) and I care about correct software. It feels like I have just wasted too much time on this project.

(We already apply this patch in our own Conda recipe for pandas.)

**Comment by jreback** [comment]
@sscherfke your comments are quite disengenous. We have 2000 open issues and 100 PR's. Sure your PR is certainly helpful as it  does fix a bug. But you never really responded to the perf concerns or put benchmarking in place.

I made a new PR, but your commit is the same whether it exists in the existing code or new. Not really sure what you are bothered by.

> implying that fast is better than correct), and “please move your change log entries to the new history file” (every couple of weeks when there was a new release).

This is a very disengenous comment. Sure correct is always better. But it is very hard to assess the performance impact of a very critical code path without performance testing. Sure you picked a really technical issue. I am glad that it is solved, though I still have perf concerns for the changes on top of yours. 

I haven't decided to actually merge this yet; it still needs more work.

**Comment by jreback** [comment]
merging. I think the impact will be limited to *only* .replace on Timestamps, so perf hit is ok.

**Pull request merged**
