### PR TITLE
fix isin method for series

### LINKED ISSUE #43460: ENH: Behaviour Series.isin with dataframe comparison is confusing [for discussion]
Right now we can compare a Series with a DataFrame through `Series.isin`, but is this expected / wanted behaviour? 
I would say this should raise, since expectations can be pretty ambiguous here and is confusing to me.

Also the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.isin.html) right now states that the `values` parameter should be "set or list-like"

Code example:

```python
values = list("ABCD")
s = pd.Series(values)
df = pd.DataFrame({"Column": values})

print(s)
0    A
1    B
2    C
3    D
dtype: object

print(df)
  Column
0      A
1      B
2      C
3      D
```
```python
# comparing DataFrame to Series, this is okay (right?) and I understand the result
df.isin(s)

   Column
0    True
1    True
2    True
3    True


#  comparing a series to df, what do we expect here? Should this raise? Why do you want to compare a Series to a DataFrame?
s.isin(df)

0    False
1    False
2    False
3    False
dtype: bool
```

Proposal: when passing anything else than "set or list-like" should raise in `Series.isin`

### PR DESCRIPTION
**Pull request by nvanommeren**
- [X] closes #43460 (Replace 43460 with the GitHub issue number)
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by noatamir** [comment]
Thanks for the PR @nvanommeren and @sophievdberg! The CI caught some errors which I think you can solve locally if you run pre-commit. Let us know if you need help.

**Review by phofl — COMMENTED** [review]
I'd be ok with updating the tests, adding a DataFrame here is weird. Are you ok with this @mroeschke ?

**Comment by mroeschke** [comment]
Yeah `Series.isin(df)` should raise IMO

**Comment by phofl** [comment]
Thx! @nvanommeren Could you update the tests?

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
