### PR TITLE
BUG: `pd.period_range` ignores multiple of `start` frequency.

### LINKED ISSUE #47465: BUG: `pd.period_range` ignores multiple of `start` frequency
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

start = pd.Period("2020", freq="3D")

a = pd.period_range(start, periods=2, freq=start.freq)
assert a[1] == start + 1

# Fails
b = pd.period_range(start, periods=2)
assert b[1] == start + 1
```

### Issue Description

The issue lies in `_get_ordinal_range`:

https://github.com/pandas-dev/pandas/blob/37d4c31c8e26a6af8eeb9780d252fab47a4ef57f/pandas/core/arrays/period.py#L1044-L1089

A fix could be to replace:

https://github.com/pandas-dev/pandas/blob/37d4c31c8e26a6af8eeb9780d252fab47a4ef57f/pandas/core/arrays/period.py#L1068-L1072

with

```py
   if freq is None:
        if is_start_per:
            freq = start.freq
            mult = freq.n
        elif is_end_per:
            freq = end.freq
            mult = freq.n
```

### Expected Behavior

Omitting the `freq` argument of `pd.period_range` should be the same as passing the `freq` of the start or end field to it via `freq=`.

### Installed Versions

Not relevant to issue.

### PR DESCRIPTION
**Pull request by jaheba**
Fixes: #47465

- [x] closes #47465
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Looks like this broke stuff

**Comment by jaheba** [comment]
Hopefully that is fixed now.

@phofl However, during testing I found this behaviour odd:

```py
In [1]: import pandas as pd

In [2]: p = pd.Period("2020", freq="Y")

In [3]: pd.Period(p, freq="3Y")
Out[3]: Period('2020', 'A-DEC')

In [4]: pd.Period(p, freq="3D")
Out[4]: Period('2020-12-31', '3D')
``

The `freq` argument is ignored when the value is already a `Period` and has the same base-freq. I assume this is also not intended?

**Comment by jaheba** [comment]
This looks wrong:

https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/tslibs/period.pyx#L2554-L2561

Checking the `_period_dtype_code` should not be sufficient, if the `.n` do not match.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
