### PR TITLE
TYP: groupby.pyi

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
@jbrockmendel you may have answered this, but how do we tests / keep these up to date?

**Comment by jbrockmendel** [comment]
> but how do we tests / keep these up to date?

@simonjayhawkins has a branch (though i dont see a PR) that implements tests, but im not sure exactly how that works.  as for keeping it up to date: manually

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins has a branch (though i dont see a PR) that implements tests

#40202 - closed until after arrow string array is further progressed.

**Comment by simonjayhawkins** [comment]
> as for keeping it up to date: manually

related issue #28133

**Pull request merged**
