### PR TITLE
0.20.2 backports 2

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Reminder to change to "rebase and merge" instead of squash.

**Comment by jreback** [comment]
> Reminder to change to "rebase and merge" instead of squash.

huh?

**Comment by TomAugspurger** [comment]
For the github merge button. We want the 0.20.x branch to have the commit history, rather than squashing all of the commits in the PR down to one.

**Comment by jreback** [comment]
> For the github merge button. We want the 0.20.x branch to have the commit history, rather than squashing all of the commits in the PR down to one.

no we want 1 commit per PR.

**Comment by TomAugspurger** [comment]
This will have 1 commit per *original* PR. I don't think there'd be anything informative about a single squashed commit for commits that happened to be in this PR.

I'm also not sure what squashing would do to `git cherry`, which I've used to double check that I've correctly gotten the commits I should. Git is probably smart enough to figure that out, but I'm not sure.

**Comment by jorisvandenbossche** [comment]
@jreback this is not a typical PR, we indeed don't want to squash this one.

**Comment by jreback** [comment]
yes backporting is fine
don't want the general setting to change :)

**Comment by jorisvandenbossche** [comment]
The `ngroup` is a new method and should not be backported IMO

**Comment by TomAugspurger** [comment]
It was a fairly large enhancement. I'm ok withholding it until 0.20.2. Are the others under Enhancements OK?

```
- Unblocked access to additional compression types supported in pytables: 'blosc:blosclz, 'blosc:lz4', 'blosc:lz4hc', 'blosc:snappy', 'blosc:zlib', 'blosc:zstd' (:issue:`14478`)
- ``Series`` provides a ``to_latex`` method (:issue:`16180`)
```

**Comment by jreback** [comment]
i don't see why we shouldn't add this enhancement to 0.20.2 (ngroup)

**Pull request merged**
