### PR TITLE
CLN: derivation of nogil param

### PR DESCRIPTION
**Pull request by jbrockmendel**
This moves the `nogil` parameter of in the template from being hard-coded to being derived from the other parameters.

This changes the parameter value on line 18 (int8/int8) which currently has `nogil=False` which I think is incorrect.

### CODE REVIEW

**Comment by jreback** [comment]
any perf changes? (would expect +)?

**Comment by jbrockmendel** [comment]
> any perf changes? (would expect +)?

I'll do some timeit checks, but I dont expect much.  Only int8/int8 cases should be affected

**Comment by jbrockmendel** [comment]
Still poking a timeit, but so far looks indistinguishable

**Comment by jreback** [comment]
cool thanks

**Pull request merged**
