### PR TITLE
PERF: maybe_convert_objects convert_numeric=False

### PR DESCRIPTION
**Pull request by jbrockmendel**
I think this fixes a perf regression that @phofl pinged me about a few weeks/months ago, but I forget the details.

### CODE REVIEW

**Comment by phofl** [comment]
maybe merge? Can't remember anymore either

**Comment by jbrockmendel** [comment]
Explode?

**Comment by phofl** [comment]
Ah explode might be the culprit, yes

**Comment by phofl** [comment]
couple of failing tests

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @jbrockmendel (accidentally pressed the wrong button...)

Lets see how this changes our asvs, if we see a regression fix then can backport?

**Comment by jbrockmendel** [comment]
works for me

**Comment by phofl** [comment]
Looks like it's worth backporting

https://asv-runner.github.io/asv-collection/pandas/#reshape.Explode.time_explode

**Comment by phofl** [comment]
@meeseeksdev backport 2.0.x

**Pull request merged**
