### PR TITLE
patch wsl compatibility

### LINKED ISSUE #38527: BUG: can't use to_clipboard/read_clipboard on WSL 2.0
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> pd.read_clipboard()
PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error

>>> pd.DataFrame().to_clipboard()
PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error
```

#### Problem description

`pd.read_clipboard` and `pd.DataFrame.to_clipboard` should work. For instance, I can run the following with no issues:
```python
>>> import pyperclip
>>> pyperclip.copy('foo')
>>> pyperclip.paste()
'foo'
```

#### Expected Output
N/A
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.128-microsoft-standard
Version          : #1 SMP Tue Jun 23 12:58:10 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by mbkupfer**
Change wsl check to something more universal and consistent

- [x] closes #38527
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]
Thanks. I am not sure this can reliably be tested, but confirmed this works on your end?

**Comment by mbkupfer** [comment]
> Thanks. I am not sure this can reliably be tested, but confirmed this works on your end?

I see, and yes, it's working for me.

**Review by jreback — CHANGES_REQUESTED** [review]
thanks @mbkupfer 

can you add a whatsnew note, 1.3. bug fix for i/o section.
can you open an issue and push this upstream as well

**Comment by simonjayhawkins** [comment]
> > Thanks. I am not sure this can reliably be tested, but confirmed this works on your end?
> 
> I see, and yes, it's working for me.

works for me too.

**Comment by mbkupfer** [comment]
@jreback I've rebased the original commit and added a line in whatsnew. Let me know if you need anything else from my end.

**Comment by jreback** [comment]
thanks @mbkupfer

**Pull request merged**
