### PR TITLE
Add examples for pandas.*.sample

### PR DESCRIPTION
**Pull request by proinsias**
The following doc files are generated from the sample() function from
pandas/core/generic.py:

pandas.DataFrame.sample.html
pandas.Panel.sample.html
pandas.Panel4D.sample.html
pandas.Series.sample.html

Examples for each have been added to the sample() function docstring.

### CODE REVIEW

**Comment by shoyer** [comment]
This looks great, but I would drop the examples for Panel and Panel4D. These structures (especially Panel4D) are rarely used, so including them adds noise.

**Comment by proinsias** [comment]
Done!

**Comment by shoyer** [comment]
This looks good to me -- anyone else have any comments before I merge?

**Comment by jorisvandenbossche** [comment]
Yep, thanks!

**Pull request merged**
