### PR TITLE
TST,WARN: read_csv raises warning at wrong stacklevel, but _assert_raised_with_correct_stacklevel doesn't fail 

### LINKED ISSUE #47385: TST,WARN: read_csv raises warning at wrong stacklevel, but _assert_raised_with_correct_stacklevel doesn't fail
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example
Make a file `t.py` with

```python

import io
import pandas as pd

pd.read_csv(io.StringIO('a'), ' ')
```

### Issue Description

Running this on `main` gives
```
$ python t.py 
sys:1: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
```

### Expected Behavior

I would have expected
```
$ python t.py 
t.py:4: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
```

cc @twoertwein in case you know what this might be due to

I noticed this in https://github.com/pandas-dev/pandas/pull/47035 - `find_stacklevel` seems to be working correctly, I think it's the test which is wrong. Currently the test passes, although it should fail.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : f491c651bf67cb8491dd805b4c78ef6ba76ebd48
python           : 3.9.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.106-15290-g6e9d70c8a9b4
Version          : #1 SMP PREEMPT Wed May 11 19:17:10 PDT 2022
machine          : aarch64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+959.gf491c651bf
numpy            : 1.22.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 62.1.0
pip              : 22.0.4
Cython           : 0.29.30
pytest           : 7.1.2
hypothesis       : 6.47.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [x] closes #47385 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Review by mroeschke — COMMENTED** [review]
Do you think this needs a whatsnew for 1.5?

**Comment by MarcoGorelli** [comment]
> Do you think this needs a whatsnew for 1.5?

yes, probably, thanks

should this be backported too?

**Comment by mroeschke** [comment]
> > Do you think this needs a whatsnew for 1.5?
> 
> yes, probably, thanks
> 
> should this be backported too, as it affects legibility of warnings to do with an upcoming deprecation?

Yeah I think this would be okay to backport cc @simonjayhawkins

**Comment by simonjayhawkins** [comment]
> Yeah I think this would be okay to backport cc @simonjayhawkins

sure. there's a bug fix section in the 1.4.4 release notes.

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
