### PR TITLE
DOC: Make highlight functions match documentation

### PR DESCRIPTION
**Pull request by parchd-1**
Fixes mismatch between function and docs defined in #16998

### CODE REVIEW

**Comment by TomAugspurger** [comment]
We want to adjust the docs to match the function. This change as it stands now *should* break some tests (if not then we don't have good enough test coverage).

**Comment by parchd-1** [comment]
Ah, I see. I wasn't sure which was the intended behaviour, which is why I didn't make the change myself to start with, but when prompted I went for what I considered the *expected* behaviour.

**Comment by gfyoung** [comment]
It's not too often that I am happy that tests fail :smile: 

This indicates we have coverage for this, which is good!

@parchd-1 : if you could just update the documentation (and revert your code change), everything will be green, and this PR will be on its way to being merged.

**Comment by parchd-1** [comment]
Sure, I'll do that. Before I do, though. I also noticed that _highlight_handler defaults to axis=None. Is it intentional that this has a different default to highlight_min and highlight_max? This was another part of why I originally changed the code to match the docs, rather than the other way round.

**Comment by gfyoung** [comment]
> Is it intentional that this has a different default to highlight_min and highlight_max?

"Intentional" is not necessarily the same as "logical" :smile:  I agree it is a little inconsistent, but maybe @TomAugspurger can say more.

In any case, the best thing to do here is to make the doc change, and you'll be set!

**Comment by parchd-1** [comment]
Ok, done.

**Comment by gfyoung** [comment]
Thanks @parchd-1 !

**Pull request merged**
