### PR TITLE
Change Naming Scheme of Series

### LINKED ISSUE #53271: DOC: Change "Convention for examples" to use Series name as `ser` instead of `s`
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/development/contributing_docstring.html#conventions-for-the-examples

### Documentation problem

There's a general preference to use `ser =` instead of `s =`  in examples

Per @MarcoGorelli 

### Suggested fix for documentation

Change `s` to `ser` on paragraph:

"When illustrating examples with a single Series use the name `s`, and if illustrating with a single DataFrame use the name df. For indices, idx is the preferred name. If a set of homogeneous Series or DataFrame is used, name them `s1`, `s2`, `s3`"

### PR DESCRIPTION
**Pull request by austinburnett**
closes #53271 

**Checklist:**
- [x] I modified all versions of series with the naming scheme s to ser.
- [x] pre-commit checks pass.

### CODE REVIEW

**Comment by austinburnett** [comment]
It looks like all the pre-commit checks are passing on my end when I run:
pre-commit run --files <files you have modified>

**Comment by MarcoGorelli** [comment]
thanks but there's already an open PR, please find another issue to contribute to

**Comment by MarcoGorelli** [comment]
wait, sorry, my bad - looks like you'd expressed interest before the other contributor - reopening this one and closing the other one then

**Comment by DeaMariaLeon** [comment]
Well done @austinburnett ! 
LGTM but we need someone else with the super powers to merge (and double check). 
Like @MarcoGorelli maybe?

**Comment by austinburnett** [comment]
> Well done @austinburnett ! LGTM but we need someone else with the super powers to merge (and double check). Like @MarcoGorelli maybe?

Thank you! LGTM! I look forward to contributing more to Pandas!

**Review by MarcoGorelli — APPROVED** [review]
nice one, thanks @austinburnett (and Dea for reviewing!)

**Comment by austinburnett** [comment]
Hahahah thanks @MarcoGorelli. I look forward to contributing more to Pandas!

**Pull request merged**
