### PR TITLE
DOC: add redirects to ensure old links instead of building the docstring page

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
We still have a lot of API pages with 'old' namespace usage (eg `pandas.io.parsers.read_csv` instead of `pandas.read_csv` as how it should show up in the documentation). Now we build the pages as well, this PR changes this in adding redirect pages.

(The reason I care about this is that googling eg `read_csv` still often turns up the old page (although I don't know how fast this disappears when we would just remove it) and these are therefore used a lot on eg SO)

### CODE REVIEW

**Comment by shoyer** [comment]
Does Google pick this up as a permanent redirect? In theory, I think that sort of thing is possible (redirecting the links in search results before users even click on them).

**Comment by jorisvandenbossche** [comment]
@shoyer Not really an idea, no expert at that. If there is a better solution, I am all ears (certainly as I would like to restructure the tutorial docs as well later on, which would make a lot of links invalid). 

I quickly did some google search, and you probably mean a 301 redirect (instead of the meta refresh I did here)?

**Comment by shoyer** [comment]
Yeah, in theory I think a 301 redirect would be preferable. But it looks like that's only possible to do with server-side code, not inside an HTML page.

**Comment by jorisvandenbossche** [comment]
Depending on how the pydata server is hosted, I suppose we could add a .htaccess file with this: http://sphinx-doc.org/latest/config.html#confval-html_extra_path

**Pull request merged**
