### PR TITLE
Update `to_gbq` wrapper method to contain `api_method` parameter

### LINKED ISSUE #46117: ENH: Update to_gbq method in gbq.py to be equal to pandas_gbq.
#### Is your feature request related to a problem?

Yes, I'm using to_gbq pandas's method to upload data from a DataFrame to BigQuery but I can't write floating point to NUMERIC column, the problem is solved by adding the argument `api_method="load_csv"`  (check out the conversation about it: https://www.giters.com/googleapis/python-bigquery-pandas/issues/421)

#### Describe the solution you'd like

Change this code -> https://github.com/pandas-dev/pandas/blob/main/pandas/io/gbq.py#L198-L224 to:
```python
def to_gbq(
        dataframe: DataFrame,
        destination_table: str,
        project_id: str | None = None,
        chunksize: int | None = None,
        reauth: bool = False,
        if_exists: str = "fail",
        auth_local_webserver: bool = False,
        table_schema: list[dict[str, str]] | None = None,
        location: str | None = None,
        progress_bar: bool = True,
        credentials=None,
        api_method: str = "default",
) -> None:
    pandas_gbq = _try_import()
    pandas_gbq.to_gbq(
        dataframe,
        destination_table,
        project_id=project_id,
        chunksize=chunksize,
        reauth=reauth,
        if_exists=if_exists,
        auth_local_webserver=auth_local_webserver,
        table_schema=table_schema,
        location=location,
        progress_bar=progress_bar,
        credentials=credentials,
        api_method=api_method,
    )
```
#### API breaking implications

Just adds the possibility of placing the argument `api_method`

#### Describe alternatives you've considered

I solved the problem using pandas_gbq directly, here is an example:

```Python
import pandas as pd
import pandas_gbq as gbq

table_schema = [{
    "name": "id",
    "type": "INTEGER"
}, {
    "name": "nombre",
    "type": "STRING"
}, {
    "name": "precio",
    "type": "NUMERIC"
}, {
    "name": "fecha",
    "type": "DATE"
}]

data = pd.DataFrame({'id': [123], 'nombre': ['Anderson'], 'precio': [1.25],
                     'fecha': ['2021-12-12']})

project_id = 'proyecto111'
table_name = 'prueba.clientes'

gbq.to_gbq(data, table_name, project_id, if_exists='append',
           table_schema=table_schema, api_method="load_csv")
```

#### Additional context
N/A

### PR DESCRIPTION
**Pull request by wangjoshuah**
ENH: add api_method parameter and some documentation
DOC: update dependencies to require at least version 0.16.0 of pandas-gbq

- [ ] closes #46117
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jreback** [comment]
looks fine. @tswast ok here?

**Review by tswast — APPROVED** [review]
If we didn't want to bump the minimum pandas-gbq, we could instead do the kwargs trick like we do in `read_gbq`. https://github.com/pandas-dev/pandas/blob/main/pandas/io/gbq.py#L181

**Review by mroeschke — APPROVED** [review]

**Review by mroeschke — CHANGES_REQUESTED** [review]
Temporarily disapproving to validate that this dependency can be resolved in our min version build

**Comment by mroeschke** [comment]
Yeah appears that pandas-gbq requires pyarrow>=3.0 while pandas still support pyarrow>=1.0.1. To support this for 1.5 we would need to do the kwargs trick mentioned https://github.com/pandas-dev/pandas/pull/47539#pullrequestreview-103004336

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
