### PR TITLE
TST: tighten assert_index_equal calls

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
i don't think it would pass `exact='equiv'` ` as that's the default. I think this is confusing. Unless you want to change `equiv=True` as the default

**Comment by jbrockmendel** [comment]
> Unless you want to change `equiv=True` as the default

That is what I want, but last time I changed a default kwarg in one of these it caused a backlash, so im taking it slow.  This is basically all the changes that we would have to make to continue passing if we did change the default (along with #38034, #38028, and some other RangeIndex tinkering that hasn't been pushed yet)

**Comment by jreback** [comment]
> > Unless you want to change `equiv=True` as the default
> 
> That is what I want, but last time I changed a default kwarg in one of these it caused a backlash, so im taking it slow. This is basically all the changes that we would have to make to continue passing if we did change the default (along with #38034, #38028, and some other RangeIndex tinkering that hasn't been pushed yet)

ok fair, though again i still wouldn't actually specify the default and rather the exception no? we will like have to deprecate this change in any event (maybe that's just easier)? then specifying this is fine.

**Comment by jbrockmendel** [comment]
> i still wouldn't actually specify the default and rather the exception no?

if/when we do change the default we'll need to go through and change these all then.  in the interim this is just being explicit about which places it makes difference

**Comment by jreback** [comment]
> > i still wouldn't actually specify the default and rather the exception no?
> 
> if/when we do change the default we'll need to go through and change these all then. in the interim this is just being explicit about which places it makes difference

ok, problem is that new tests won't have this, i guess its not a big deal, but going to have a consistency nightmare, why are you against leaving off the `exact='equiv'` entirely?

**Comment by jbrockmendel** [comment]
> why are you against leaving off the exact='equiv' entirely?

not looking forward to re-doing the process of tracking down which ones need it when the default is changed.  not a big deal.  will revert.

**Comment by jreback** [comment]
> > why are you against leaving off the exact='equiv' entirely?
> 
> not looking forward to re-doing the process of tracking down which ones need it when the default is changed. not a big deal. will revert.

as an alternative, can you add as a comment after the call?

**Comment by jbrockmendel** [comment]
just reverted them

**Review by jreback — APPROVED** [review]

**Pull request merged**
