### PR TITLE
TYP: check typings with pyright

### PR DESCRIPTION
**Pull request by twoertwein**
small followup to #44233

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @twoertwein

Any changes needed for the pre-commit check?

**Comment by twoertwein** [comment]
Do you think it makes sense to replace 

```py
numba = import_optional_dependency("numa")
```

with

```py
import_optional_dependency("numa")
import numba
```

Unfortunately, I didn't find a way to type `import_optional_dependency` (even with overloads, a module by itself is no type).

> Any changes needed for the pre-commit check?

No, pre-commit just calls `pyright` same as for the CI.

**Comment by simonjayhawkins** [comment]
I have a PR whch i'm just running the tests etc for before opening in which I use

```python
    if TYPE_CHECKING:
        import numba
    else:
        numba = import_optional_dependency("numba")
```

**Review by lithomas1 — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
Thanks @twoertwein

**Pull request merged**
