### PR TITLE
DOC: Fixing EX01 - Added examples

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Towards https://github.com/pandas-dev/pandas/issues/37875

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
> No preview found for PR #54350. Did the docs build complete?

how odd, it shows here https://github.com/pandas-dev/pandas/actions/runs/5725144896?pr=54350

**Comment by MarcoGorelli** [comment]
hey, this looks correct! 🙌 

image

**Review by MarcoGorelli — APPROVED** [review]
Looks good to me, thanks @DeaMariaLeon 

@datapythonista any idea why the preview isn't rendering? The docs build produced an artifact correctly, and I was able to download it and open the docs

**Comment by DeaMariaLeon** [comment]
It's green

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @DeaMariaLeon

**Pull request merged**
