### PR TITLE
DOC: Correct docstring for Series.apply

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

Ref: https://github.com/pandas-dev/pandas/pull/39941#issuecomment-829604511 and the conversation preceding it. While I don't find @MarcoGorelli's suggestion as implemented here very clear, it at least makes it correct and I don't see a better way.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks - an alternative would be to just revert  #39941 ?

**Comment by rhshadrach** [comment]
@MarcoGorelli The docstring was incorrect before #39941 - I think we should value a correct docstring here even if it's not exactly clear what the behavior is. To be sure, while I find this unclear, my opinion is that it's the implementation (changing behavior based on whether an EA has certain private method or not) that is undesirable, but I don't see a clear way to fix.

**Comment by jreback** [comment]
thanks @rhshadrach

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
