### PR TITLE
Backport PR #40877 on branch 1.2.x (Skipt failing tests for numpy dev)

### PR DESCRIPTION
**Pull request by phofl**
Backport PR #40877

Had to add the is_numpy_dev import, we could otherwise import from other directory if this would be preferrable

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@phofl have added Backport PR #40877 to OP. the ref in the title donsn't create a link to the original PR.

**Comment by simonjayhawkins** [comment]
> Had to add the is_numpy_dev import, we could otherwise import from other directory if this would be preferrable

maybe since we likely are doing a release between now and the revert, let's not change the code only the tests.

**Comment by phofl** [comment]
Seems reasonable,

Done

**Review by simonjayhawkins — APPROVED** [review]
Thanks @phofl

**Pull request merged**
