### PR TITLE
STY: Spaces over concat strings - batch 1

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
I personally prefer the spaces at the start of the strings. I find it easier to spot missing spaces. not sure what others think.

**Comment by WillAyd** [comment]
No strong preference but I think OK. @MomIsBestFriend can you merge master?

**Review by datapythonista — APPROVED** [review]
I'm more used to spaces at the end, but whatever it is, I think it's good to have a convention.

This comes from this new guide: https://dev.pandas.io/docs/development/code_style.html#id6 I think the standard started from a discussion in a review.

This PR lgtm, happy to get it merged. But also ok on reopening the discussion if the discussion when merging the style guide wasn't visible enough.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @MomIsBestFriend

**Pull request merged**
