### PR TITLE
DEBUG verbose pre-commit

### PR DESCRIPTION
**Pull request by MarcoGorelli**
pre-commit-ci timed out, so just checking hooks' timings with `verbose: true`

### CODE REVIEW

**Comment by mroeschke** [comment]
Is it possible to make the the pre-commit.ci check xfail-able while it's being debugged?

**Comment by MarcoGorelli** [comment]
Hey @mroeschke - I don't think so, I've suggested to @jreback that we simply uninstall it for now as it times out at 180s and `flake8` and `black` alone go over that limit

Closing this for now anyway as the pre-commit/action, although deprecated, seems to be working fine

**Comment by jreback** [comment]
@MarcoGorelli ok i should install?

**Comment by MarcoGorelli** [comment]
yeah I'd say so, thanks

**Comment by jreback** [comment]
ok it's suspended

**Pull request closed without merging**
