### PR TITLE
CI: move py39 build to conda #33948

### LINKED ISSUE #33948: CI: Move Python 3.9 Build to Conda
Once Python 3.9 is released (Oct 2020) as a follow up from https://github.com/pandas-dev/pandas/pull/33505 we can move the builds to conda and to run on Azure.

Note: Use numpy wheels when available current installs from source.

### PR DESCRIPTION
**Pull request by fangchenli**
- [x] closes #33948

### CODE REVIEW

**Comment by jreback** [comment]
very nice ping on green-ish

**Review by jreback — CHANGES_REQUESTED** [review]
you can't use conda to install numpy (yet) as i don't think there are *any* conda packages for 3.9 (soon though)

**Comment by jreback** [comment]
i think this could work now, @fangchenli can you merge master and let's see

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
very nice @fangchenli

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.1.x

**Pull request merged**
