### PR TITLE
COMPAT: blacklist numexpr=2.4.4

### LINKED ISSUE #12489: blacklist numexpr 2.4.4
Under some circumstances, numexpr 2.4.4 can lead to flaky output (see #12023 and links therein).  This happened again once on SO in the last few days, and it's a suspect in another case.

[UPDATE: the suspect was convicted of the second crime as well!]

We should just refuse to work with 2.4.4, rather than leave the impression pandas is unstable, and require a later version as soon as we can.  There are apparently still enough people out there with up-to-date pandas and out-of-date numexpr that a warning could probably help someone. Accordingly, after some discussion on gitter, it sounds like we should

(1) add a warning to the docs
(2) centralize the version check (right now both computation/eval and computation/expressions check the numexpr version)
(3) only allow numexpr if >= 2.1 and not == 2.4.4; otherwise, set _USE_NUMEXPR to False
(4) in the warning we raise, recommend upgrading from 2.4.4 because we can't easily prevent other dependencies from using it
(5) add a test to make sure that the presence of 2.4.4 disables _USE_NUMEXPR (say, by adding it to the requirements-3.4_SLOW).

### PR DESCRIPTION
**Pull request by jreback**
close #12489
xref #11915

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Maybe you want to add a short note to the dependencies section of the main `README.md`? We should probably just remove that section and link to the docs so it doesn't fall out of date.

**Comment by jreback** [comment]
@TomAugspurger hmm, that is a good point. want to do a (can separate) PR for that?

**Comment by TomAugspurger** [comment]
Yeah, I'll do one separate.

**Comment by jreback** [comment]
thank you sir!

**Comment by gfyoung** [comment]
Travis is giving a green light.  Don't know if you intend to add anything else to this PR though.

**Pull request closed without merging**
