### PR TITLE
Fix typos, via a Levenshtein-style corrector

### PR DESCRIPTION
**Pull request by bwignall**
Should be non-semantic.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

**Review by topper-123 — APPROVED** [review]

**Comment by topper-123** [comment]
Thanks @bwignall. Mind sharing how you do this? I’m familiar with Levenstein, but do you have a program that scans source codes for spelling errors?

**Comment by bwignall** [comment]
Certainly, @topper-123 : I use https://github.com/bwignall/typochecker . It's a basic script (that's already in need of some refactoring), but the first version used https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines to find likely typos, and it has bootstrapped the list of likely typos by looking at a few heuristics (such as a subset of Levenshtein edits) that have been run against some non-trivial codebases, including pandas.

**Comment by topper-123** [comment]
Nice thanks. Can be nice to keep in mind when cleaning code bases.

**Pull request merged**
