### PR TITLE
Troubleshoot Travis

### PR DESCRIPTION
**Pull request by jbrockmendel**
Reverts #33228, which appears to be the first build that started failing on Travis.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@WillAyd looks like Travis passed (though it still shows yellow here, need to click through).  any idea why the categorical test would affect the numexpr test?

**Comment by WillAyd** [comment]
On phone so haven’t checked in detail but seemingly unrelated?

**Comment by jbrockmendel** [comment]
Any objection to merging this to get the CI fixed, then re-implementing #33228 in pieces to track down the issue?

cc @jreback

**Comment by jreback** [comment]
nope, do it when green

**Comment by BenjaminLiuPenrose** [comment]
> nope, do it when green

Hello @jreback any idea why CI test always fail for numexpr test?

**Comment by jbrockmendel** [comment]
> nope, do it when green

If you click through to Travis, it is green there (and has been for 16 hours), just hasnt de-yellowed here.

**Comment by jreback** [comment]
cool, seems we have seen this when  travis status not updating before oh well

**Pull request merged**
