### PR TITLE
REG: restore format_type attr

### LINKED ISSUE #30962: AttributeError: 'FrameFixed' object has no attribute 'format_type' on 1.0.0rc0
```python
import pandas as pd


df = pd.DataFrame({"A": [1, 2]})
df.to_hdf("foo.h5", "foo")

with pd.HDFStore("foo.h5") as hdf:
    for key in hdf.keys():
        storer = hdf.get_storer(key)
        print(type(storer), storer.format_type)
```

On 0.25.3, we have

```python
<class 'pandas.io.pytables.FrameFixed'> fixed
```

On 1.0.0rc0

```pytb
Traceback (most recent call last):
  File "bug.py", line 10, in <module>
    print(storer.format_type)
AttributeError: 'FrameFixed' object has no attribute 'format_type'
```

Didn't see anything about this in the release notes. cc @jbrockmendel (if this was part of your tables cleanup).

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #30962

cc @TomAugspurger

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks. Two questions:

1. Thoughts on the need for a simple test? I worry a bit about a comment being overlooked in a future refactor clearing stuff out / looking at "dead" code.
2. Do we want this API going forward? Clearly, we don't have a need for it. Is there an alternative we should deprecate in favor of?

**Comment by simonjayhawkins** [comment]
> 1. Thoughts on the need for a simple test?

code sample in issue as test in pandas\tests\test_downstream.py

**Comment by simonjayhawkins** [comment]
wrong button!

**Comment by jbrockmendel** [comment]
@TomAugspurger suggestions for a snippet to test?

**Comment by TomAugspurger** [comment]
Nothing fancy. Just an asset that hdf.get_storer(key).format_type is the expected value for that format

**Comment by WillAyd** [comment]
Is the purpose of this field documented anywhere? If not can we add a comment?

**Comment by TomAugspurger** [comment]
Pushed a test.

**Comment by TomAugspurger** [comment]
> Is the purpose of this field documented anywhere? If not can we add a comment?

IMO we can keep PR to just fixing the regression.

**Review by TomAugspurger — APPROVED** [review]

**Comment by TomAugspurger** [comment]
Thanks @jbrockmendel.

**Pull request merged**
