### PR TITLE
CI: debug azure timeouts

### PR DESCRIPTION
**Pull request by mzeitlin11**
More attempts to see what's causing the timeouts.

### CODE REVIEW

**Comment by jreback** [comment]
arm failure is ok if you merge master

**Comment by mzeitlin11** [comment]
> arm failure is ok if you merge master

Sounds good. Sorry, should've marked this as draft - want to let CI run a few times because I added `pytest-timeout` and want to see if we can catch whatever the test(s) which get stuck and cause timeouts or actions jobs that take hours

**Comment by jbrockmendel** [comment]
Thanks for taking the lead on this.  Looks like its one of the mac builds that timed out this last time.

**Comment by mzeitlin11** [comment]
> Thanks for taking the lead on this. Looks like its one of the mac builds that timed out this last time.

But no timeout was detected :(

**Comment by mzeitlin11** [comment]
Logs from a timeout: https://dev.azure.com/pandas-dev/e01c9671-576d-40f3-a1a1-7bef78604087/_apis/build/builds/66368/logs/77

```
...
2021-09-18T04:51:29.0847391Z pandas/tests/io/parser/test_parse_dates.py::test_invalid_parse_delimited_date[pyarrow-32/32/2019] 
2021-09-18T04:51:29.0898854Z [gw0] XFAIL pandas/tests/io/parser/test_parse_dates.py::test_invalid_parse_delimited_date[pyarrow-32/32/2019] 
2021-09-18T05:22:53.6837334Z ##[error]The operation was canceled.
2021-09-18T05:22:53.6851486Z ##[section]Finishing: Test
```

Just goes quiet for 30 min, can't think of anything around the tests running there that would cause this. Wonder if timeout shows up same place every time

**Comment by mzeitlin11** [comment]
Hmm latest timeout looks to have `gw0` stuck in same place - right before hypothesis tests...

**Comment by jreback** [comment]
@mzeitlin11 still active here?

**Comment by mzeitlin11** [comment]
Closing for now - anyone is welcome to reopen and run some pipelines if seeing lots of azure timeouts

**Pull request closed without merging**
