### PR TITLE
Added message to pytest raises for test_constructor_dict

### PR DESCRIPTION
**Pull request by Dom-L-G**
- [x] ref #30999 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x]  added message to pytest.raises for test_constructor_dict

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks @DominicG88

**Review by simonjayhawkins — COMMENTED** [review]
Thanks @DominicG88 lgtm. can you merge master. Failing CI should be fixed now.

**Comment by DominicG88** [comment]
Thanks @simonjayhawkins  @MarcoGorelli  :)

Merged and pushed.

**Comment by jreback** [comment]
thanks @DominicG88

**Pull request merged**
