### PR TITLE
REF: Avoid importing xlrd

### LINKED ISSUE #56692: pandas.read_excel 'Can't determine version for xlrd' - old bug on pandas-2.1
BUG: read_excel failing to check older xlrd versions properly #39355

I ran into this bug on pandas-2.1
without xlrd present no problem; but when installed, excel file is not loaded:

>
    In [5]: df_ref=pd.read_excel(refprots, engine="openpyxl", na_values =[''])
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    Cell In[5], line 1
    ----> 1 df_ref=pd.read_excel(refprots, engine="openpyxl", na_values =[''])
    
      ImportError: Can't determine version for xlrd
    
    In [6]: df_ref=pd.read_excel(refprots, na_values =[''])
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    Cell In[6], line 1
    ----> 1 df_ref=pd.read_excel(refprots, na_values =[''])
    
      ImportError: Can't determine version for xlrd
    
    In [7]: import xlrd
    
    In [8]: xlrd.__version__
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    Cell In[8], line 1
    1 xlrd.__version__
    
    AttributeError: module 'xlrd' has no attribute '__version__'
    
    In [9]: xlrd.__VERSION__
    Out[9]: '1.1.0'
    
    In [10]: pd.__version__
    Out[10]: '2.1.4'

_Originally posted by @brobr in https://github.com/pandas-dev/pandas/issues/39355#issuecomment-1872921058_

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] closes #56692 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Not sure how I'd add a test here.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Could check sys.modules for presence of xlrd?

**Comment by rhshadrach** [comment]
> Could check sys.modules for presence of xlrd?

True; since that's global I think it'd have to check it in a subprocess. It seems to me a bit of an odd thing to test - unless we think we should have more testing that we don't import an optional dependency if it's not used more generally. Are we okay foregoing a test here?

**Comment by jbrockmendel** [comment]
Fine by me

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @rhshadrach

**Pull request merged**
