### PR TITLE
BUG: MultiIndex, IntervalIndex intersection with Categorical

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
what is the bug here? need a whatsnew? can you rebase

**Comment by jbrockmendel** [comment]
> can you rebase

just did, and managed to fully share the intersection methods!

> need a whatsnew?

added

> what is the bug here? 

```
mi = pd.MultiIndex.from_product([range(2), range(3)])
cat = mi.to_flat_index().astype('category')

>>> mi.intersection(cat)
MultiIndex([], )
```

**Comment by jreback** [comment]
nice ping on greenish

**Comment by jbrockmendel** [comment]
ping

**Pull request merged**
