### PR TITLE
CLN: remove typing ignores

### PR DESCRIPTION
**Pull request by attack68**
mypy now passes without ignorance

### CODE REVIEW

**Review by alimcmaster1 — APPROVED** [review]
LGTM

**Comment by attack68** [comment]
Actually this is green on my local `mypy`, which is upto date with pandas requirements file, but the CI here seems to require the type ignore comments.
@MarcoGorelli can you give me a hint?

**Comment by MarcoGorelli** [comment]
> Actually this is green on my local `mypy`, which is upto date with pandas requirements file, but the CI here seems to require the type ignore comments.
> @MarcoGorelli can you give me a hint?

:thinking: are the rest of your dependencies up to date? Perhaps do another `conda env update -f environment.yml` then `conda activate pandas-dev`?
Another suggestion I've seen here is to run `mypy pandas --no-incremental`

**Comment by attack68** [comment]
> 
> 🤔 are the rest of your dependencies up to date? Perhaps do another `conda env update -f environment.yml` then `conda activate pandas-dev`?
> Another suggestion I've seen here is to run `mypy pandas --no-incremental`

I reinstalled a py3.9 environment and installed dependencies with pip. Still get the stange mypy behaviour here, even with the --no-incremental flag.

will close this, seems to be my local error

**Pull request closed without merging**
