### PR TITLE
ENH: EA.interpolate

### LINKED ISSUE #50950: ENH: .interpolate() with EA Dtypes
```python
ser = pd.Series([1, 2, None, 4], dtype="Int64")

>>> ser.interpolate()
[...]
ValueError: Invalid fill method. Expecting pad (ffill) or backfill (bfill). Got linear
```

EABackedBlock.interpolate dispatches to EA.fillna, which doesn't handle `method="linear"`.  Getting this right probably will require implementing something new at the EA level.

### Expected Behavior

`pd.Series([1, 2, 3, 4])`

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #50950 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Fixed some incorrect type annotations, de-duplicate some code paths.

### CODE REVIEW

**Review by Dr-Irv — COMMENTED** [review]
I just looked at `_typing.py`.  Introducing `InterpolateOptions` is something we should pull over to `pandas-stubs` .   Created https://github.com/pandas-dev/pandas-stubs/issues/732 for that

**Review by mroeschke — COMMENTED** [review]
Looks good. Could use a whatsnew note in 2.1 that EA.interpolate was added

**Comment by jbrockmendel** [comment]
> Looks good. Could use a whatsnew note in 2.1 that EA.interpolate was added

updated+green

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
