### PR TITLE
DOC: Move Other bugfixes to appropriate sections

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

### CODE REVIEW

**Comment by jreback** [comment]
hmm mypy is failing oddly

**Comment by rhshadrach** [comment]
Comparing to the most recent commit on master, I'm seeing numpy 1.21.0 here and 1.20.3 there.

**Comment by rhshadrach** [comment]
CI failure is unrelated (ref #42196), @jreback and @simonjayhawkins for review.

**Comment by jreback** [comment]
thanks @rhshadrach

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
