### PR TITLE
add histogram method to series

### PR DESCRIPTION
**Pull request by bluesquall**
Add a histogram method to `pandas.Series` -- just a thin wrapper around `np.histogram`.

- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by bluesquall** [comment]
Apparently there were 4 more pull requests while I was pushing this, so the note in whatsnew shows an incorrect PR number. I'll update this once the rest of the tests are complete.

**Comment by gfyoung** [comment]
@bluesquall : Thank you for opening this PR!  We already have a histogram method (`Series.hist`), so unfortunately, this PR is actually unnecessary.

In the future, I would recommend that you open an issue before opening the PR, as that's where we work out whether there's any need to address whatever is at hand.

**Comment by jreback** [comment]
.hist is for plotting the histogram
but this indeed is better done with pd.cut

**Comment by bluesquall** [comment]
@gfyoung: This returns the counts and bins edges. It doesn't generate the plot, so it isn't directly about visualization (like @jreback noted).

I'm using it for preprocessing with a few more steps before a plot, usually. Sometimes it's just for processing.

@jreback: I did play with pandas.cut a bit before submitting this PR. If I recall correctly, it required a few extra steps to get the output to the form I needed, while simply wrapping numpy.histogram didn't.

I'm happy to open an issue later this week to discuss further and to give some examples.

If you would rather have it implemented using pandas.cut, I'm open to that, too.

**Pull request closed without merging**
