### PR TITLE
API: Revert breaking `.values` changes

### PR DESCRIPTION
**Pull request by TomAugspurger**
User-facing change: `Series[period].values` nad `Series[interval].values`
continues to be an ndarray of objects. Recommend ``.array`` instead.

There are a handful of related places in pandas where we assumed that
``Series[EA].values`` was an EA.

Part of #23995

### CODE REVIEW

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
lgtm

**Comment by TomAugspurger** [comment]
Only failure was the Azure lining, which has since been fixed on master.

@jorisvandenbossche IIRC, you preferred that `Series[period].values` would return an ndarray of objects right?

**Comment by jorisvandenbossche** [comment]
>  you preferred that Series[period].values would return an ndarray of objects right?

That might be :-) In any case, since then we added `array`, so I think the rationale to keep `.values` backward compatible makes sense.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by TomAugspurger** [comment]
Sounds good. Merging.

**Pull request merged**
