### PR TITLE
DOC: Fixing SS02 errors as per #25113

### LINKED ISSUE #25113: Fix validation error type `SS02` and check in CI
#### Problem description
In order to have a continuous check by the CI on validation error `SS02` (Summary does not start with a capital letter), fixing them in the code base enables the addition to the CI for automated testing in the future.

`SS02` has just 61 occurrences (see [overview of the errors](https://gist.github.com/198cfa552c727d71bd7360fda66fdbb4)):

method | file | file_line | github_link
-- | -- | -- | --
pandas.tseries.offsets.DateOffset.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BusinessDay.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BusinessHour.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.CustomBusinessDay.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.CustomBusinessHour.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.MonthOffset.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.MonthEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.MonthBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BusinessMonthEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BusinessMonthBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.CustomBusinessMonthEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.CustomBusinessMonthBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.SemiMonthOffset.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.SemiMonthEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.SemiMonthBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.Week.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.WeekOfMonth.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.LastWeekOfMonth.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.QuarterOffset.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BQuarterEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BQuarterBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.QuarterEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.QuarterBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.YearOffset.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BYearEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BYearBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.YearEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.YearBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.FY5253.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.FY5253Quarter.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
... | ... | ... | ...
pandas.tseries.offsets.Tick.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.Day.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.Hour.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.Minute.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.Second.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.Milli.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.Micro.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.Nano.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BDay.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BMonthEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.BMonthBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.CBMonthEnd.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.CBMonthBegin.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.tseries.offsets.CDay.normalize | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timestamp.ceil | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timestamp.combine | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timestamp.floor | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timestamp.fromordinal | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timestamp.fromtimestamp | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timestamp.replace | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timestamp.strftime | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timestamp.strptime | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timedelta.view | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timedelta.ceil | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timedelta.floor | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Timedelta.to_pytimedelta | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.HDFStore.groups | pandas/io/pytables.py | 1093.0 | https://github.com/pandas-dev/pandas/blob/master/pandas/io/pytables.py#L1093
pandas.Panel.items | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Panel.major_axis | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone
pandas.Panel.minor_axis | None | NaN | https://github.com/pandas-dev/pandas/blob/master/None#LNone

Todo:
* [ ]  get rid of the errors in the code base
* [ ]  update the `code_check.sh` script to take into account the `SS02` type of errors

### PR DESCRIPTION
**Pull request by souvik3333**
Some of the SS02 error mentioned are not because of methods but of docstring.
For example, in the first SS02 error pandas/tseries/offsets.py has no method named normalize.

- [X] Closes #25113 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by gfyoung** [comment]
@souvik3333 : Before we can close the issue, we will need to fix all the errors in the issue.  It looks like you only addressed some of them, unless you're planning to tackle the rest in this PR.

**Comment by souvik3333** [comment]
Yes, I would like to tackle the rest errors, but rest of the error creating line numbers are not coming up and when I am trying to find the error in the mentioned file, the mentioned method in not in that file. One example for this issue is given in commit description. I need little help here.

**Comment by gfyoung** [comment]
@souvik3333 : Can you update our doc checking script to enable `SS02` to see which errors you get?

> Yes, I would like to tackle the rest errors, but rest of the error creating line numbers are not coming up and when I am trying to find the error in the mentioned file, the mentioned method in not in that file.

cc @kynan @datapythonista

**Comment by souvik3333** [comment]
> @souvik3333 : Can you update our doc checking script to enable `SS02` to see which errors you get?
Can you explain bit more on what I have to do?

**Comment by gfyoung** [comment]
https://github.com/pandas-dev/pandas/blob/4be995c13452766da48a82f3ecd0b5a24e48f526/ci/code_checks.sh#L245

Add the `SS02` error at the end of the line (with the comma-delimited values).

**Comment by souvik3333** [comment]
> Add `SS02` at the end of the line shown above (comma-delimited).

Nothing changed, Same errors are coming up.

**Comment by gfyoung** [comment]
> Nothing changed, Same errors are coming up.

@souvik3333 : What I mean is: you need to add that to the script and push that change to your PR.

**Comment by souvik3333** [comment]
I have updated the PR. Can you check @gfyoung what I need to do next?

**Comment by gfyoung** [comment]
@souvik3333 : Have a look at the `SS02` failures here:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=8520

(Click the `Checks_and_doc_job`)

Correct those errors, and I think this PR will be good to go!  I do realize that it may be difficult to verify since you were saying you had some trouble replicating all of the errors, but the error descriptions are pretty clear that you can figure out what to correct and push to the PR.

**Comment by souvik3333** [comment]
> Correct those errors, and I think this PR will be good to go! I do realize that it may be difficult to verify since you were saying you had some trouble replicating all of the errors, but the error descriptions are pretty clear that you can figure out what to correct and push to the PR.

Yes, but I am facing problem finding the exact location of the error! Can you please show me how to find the error creating line for one error then I can try for the rest of them?

**Comment by gfyoung** [comment]
> Can you please show me how to find the error creating line for one error then I can try for the rest of them?

cc @WillAyd @datapythonista : Would it be possible to provide line numbers and file paths instead of using the "dot" syntax for pointing to errors?  This seems to be a very valid concern

@souvik3333 : The errors should be located in the following files:

https://github.com/pandas-dev/pandas/blob/b2c751985ebd09b72d917d08dc06193dc0922018/pandas/_libs/tslibs/timestamps.pyx
https://github.com/pandas-dev/pandas/blob/b2c751985ebd09b72d917d08dc06193dc0922018/pandas/tseries/offsets.py

The last three around I think should be ignored.  `Panel` is being removed, so I think we ignore those warnings, though I'm not sure what the right is to ignore them (or if we can)...

**Comment by WillAyd** [comment]
> cc @WillAyd @datapythonista : Would it be possible to provide line numbers and file paths instead of using the "dot" syntax for pointing to errors? This seems to be a very valid concern

@souvik3333 feel free to open an issue for this request if there's not already one out there - can be discussed further therein!

**Comment by datapythonista** [comment]
Those `None(None)` are the file path and line number when we can guess where the docstring is defined. But there are limitations on that. For example, it's not trivial (or not possible) to know the file and line when the docstring is in a Cython file. Or when the docstring is created in a variable and then set to the `__doc__` attribute of the object.

I think for this case you'll have to try things like `grep -R "class Timstamp" *`, `grep -r "def ceil" *` until you find where those methods are defined.

**Comment by WillAyd** [comment]
@souvik3333 can you update errors as mentioned above?

**Comment by souvik3333** [comment]
> @souvik3333 can you update errors as mentioned above?

Yes, I need a little more time. I will update the PR once it's done.

**Comment by nmusolino** [comment]
I was thinking of continuing the work for this pull request, by tracking down all the outstanding failures and fixing them.

@souvik3333 , I would keep your existing commits and build on top of them, so your work would be preserved.

Is there some way I can contribute commits here without creating a new pull request?

**Comment by souvik3333** [comment]
> Is there some way I can contribute commits here without creating a new pull request?

I don't know but you can work on it as I am busy with my exams and it would take me some time before starting working on it again.

**Comment by WillAyd** [comment]
@nmusolino if you'd like you can clone this and push to your own PR

@souvik3333 closing as stale given your latest comment. Thanks in any case!

**Pull request closed without merging**
