### PR TITLE
CI/BENCH: Make CategoricalIndexIndexing benchmark less flaky

### PR DESCRIPTION
**Pull request by mroeschke**
Resizing `data_unique` to be the same length as `data` which maybe is some source of flakiness since `data_unique` was 3x `data`

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
I can't reproduce the flakiness locally (but have seen it fail in CI a few times), so not sure how to check whether this fixes the issue, but this does seem reasonable (not to mention more readable...)

**Comment by mroeschke** [comment]
I'll merge in main maybe 2 more times just to confirm.

**Comment by MarcoGorelli** [comment]
might be quicker to just re-run the code-checks jobs

image

**Comment by MarcoGorelli** [comment]
I restarted the job and it still passed, so let's ship this, if it fails again we can revisit. Thanks @mroeschke !

**Pull request merged**
