### PR TITLE
DOC: added docstring for `storage_options` in `read_html`

### LINKED ISSUE #54772: DOCS: the `storage_options` parameter is not included in the `read_html` docstring
pandas 2.1.0rc

### PR DESCRIPTION
**Pull request by rsm-23**
- [x] closes #54772
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.

### CODE REVIEW

**Comment by rsm-23** [comment]
@mroeschke docstring validation failing with
`Redefining name from outer scope.........................................Failed
- hook id: pylint
- duration: 45.12s
- exit code: 4

************* Module pandas.io.html
pandas/io/html.py:368:28: W0621: Redefining name 'doc' from outer scope (line 26) (redefined-outer-name)
pandas/io/html.py:599:28: W0621: Redefining name 'doc' from outer scope (line 26) (redefined-outer-name)
pandas/io/html.py:731:28: W0621: Redefining name 'doc' from outer scope (line 26) (redefined-outer-name)`

one such function which shares the same name as the decorator is this:
`    def _parse_tables(self, doc, match, attrs):`

Any suggestions? should I rename the parameter name?

**Comment by mroeschke** [comment]
> should I rename the parameter name?

Yes this sounds reasonable

**Comment by rsm-23** [comment]
@mroeschke can you please review this PR?

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @rsm-23

**Pull request merged**
