### PR TITLE
Revert "Remove pyx dependencies from setup (#17478)"

### PR DESCRIPTION
**Pull request by jreback**
This reverts commit e6aed2ebb7374ed2a6a7c284750d47728aec285e.
xref #17555

### CODE REVIEW

**Comment by jreback** [comment]
cc @jbrockmendel 

let's start over with this (you can do it all in #17555). Either we need to add this on to the tests on CI (which is possible), or maybe have a local script which checks.

**Comment by gfyoung** [comment]
@jreback : In light @jbrockmendel comment <a href="https://github.com/pandas-dev/pandas/pull/17555#issuecomment-330108102">here</a>, perhaps we should revert the reversion? 😄

**Comment by jorisvandenbossche** [comment]
No, the conclusion of that comment is just that @jbrockmendel won't further investigate it, which means bringing it back to how it was (possibly a bit too much specified deps, but working correctly) is the correct action, and that is what this PR does.

**Comment by jreback** [comment]
I agree
I think they might be over specified but we don't have a good way of ensuring that changes are correct on the dev side ATM

**Comment by gfyoung** [comment]
Fair enough.  The initial PR sounded like it was cutting down on the dependencies, and we haven't seen anything crash so far.  That was why I asked.

**Comment by jorisvandenbossche** [comment]
@gfyoung if you read the discussion (it's a bit long) in the thread you linked to, you will see this is not about 'crashing', at least not on travis or so, but only for local development workflow of incremental builds. And you would already have needed to edit a specific cython file over the last week and made an incremental build to have seen a problem, so it is likely we just didn't see any crashes yet

**Comment by gfyoung** [comment]
@jorisvandenbossche : Fair enough (I did read the discussion but not super in-detail, hence why I was asking).  Did we confirm any issues with dev-building after this by any chance?

**Comment by jorisvandenbossche** [comment]
> Did we confirm any issues with dev-building after this by any chance?

No we did not, but as I said, the chance you ran into it is not that big during this week, so if we want to change this, the best would be to for each change in `deps` in setup.py to specifically test it

**Comment by gfyoung** [comment]
Sounds good.

**Pull request merged**
