### PR TITLE
DOC/BLD: Pinning sphinx to 1.5, as 1.7 has been released and it's incompatible with vendored numpydoc

### LINKED ISSUE #19742: Building docs fails with the latest version of sphinx
It seems like one week ago sphinx 1.7.0 was released, and the version of numpydoc included with pandas is not compatible with it (it uses the `sphinx.util.compat` which has been deprecated).

Anaconda already includes sphinx 1.7.0, which is used by default. As in `requirements_dev.txt` sphinx is specified without version, after following the instructions in the contributing documentation, building the documentation fails.

I assume that numpydoc has been modified, if included in the repository instead of being added as a dependency. So, may be a quick solution is to specify `sphinx==1.6.7` in `requirements_dev.txt`.

Happy to contribute a pull request, if you can clarify what needs to be done.

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #19742
- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
thanks

**Comment by jreback** [comment]
ahh that's right.

**Comment by jorisvandenbossche** [comment]
If the performance problems are solved with Sphinx 1.7, I would rather do the small fix in our vendored numpydoc version instead of keep pinning sphinx to 1.5. 
I am trying to test this in https://github.com/pandas-dev/pandas/pull/19687, but the problem it keeps installing sphinx 1.6 because it is not yet available on defaults. Will change it temporarily to install from conda-forge to test it.

**Comment by jorisvandenbossche** [comment]
I reverted this in https://github.com/pandas-dev/pandas/pull/19687, and the last commit there tested sphinx 1.7 on travis, and it ran without failure and without time-out. So it seems we are good for sphinx 1.7.

**Pull request merged**
