### PR TITLE
BUG: Prevent 3D-ndarray for nested tuple labels (#24687)

### PR DESCRIPTION
**Pull request by skimbleshank**
Being a very rare issue encountered with nested tuples as column and index labels, here is the fix I've managed to come up with - for the time being.  While `clean_index_list()` in `pandas/_libs/lib.pyx` is responsible for returning an invalid result (a 3D ndarray where the inner dimensions should be nested tuples), debugging Cython is very challenging for me.  And yes, use of tuples in this way is extremely uncommon.  So far, the code has run successfully on two distance matrices.
fix

### CODE REVIEW

**Comment by gfyoung** [comment]
@summonholmes : Thanks for contribution!  Given the limited use-case as you point, I wonder what the trade-off might be between degree of use vs. work to maintain.

Also, we're going to need at least one test and a `whatsnew` entry for this contribution.

**Review by jreback — CHANGES_REQUESTED** [review]
not really sure what this PR is trying to do

**Comment by jreback** [comment]
@summonholmes your are missing my point
pls show a reproducible example of what is the problem; what you are doing is likely an error

**Comment by summonholmes** [comment]
> @summonholmes your are missing my point
> pls show a reproducible example of what is the problem; what you are doing is likely an error

It's in the bug report that I created, but I'll post a more concise demo here:
```python
from pandas._libs import lib
from pandas import DataFrame
from seaborn import light_palette

# Using the nested tuple cluster
broken_cluster = {
    (("Turtle", "Chicken"), (("Man", "Monkey"), "Dog")): (0, 28.375, 31.875),
    "Tuna": (28.375, 0, 41),
    "Moth": (31.875, 41, 0)
}
broken_cluster = DataFrame(broken_cluster, index=broken_cluster.keys())
broken_cluster.style.background_gradient(
    cmap=light_palette("indigo", as_cmap=True))

# Without using the nested tuple cluster
working_cluster = {
    "S": (0, 28.375, 31.875),
    "Tuna": (28.375, 0, 41),
    "Moth": (31.875, 41, 0)
}
working_cluster = DataFrame(working_cluster, index=working_cluster.keys())
working_cluster.style.background_gradient(
    cmap=light_palette("indigo", as_cmap=True))
# Highlight mins

# The culprit:
lib.clean_index_list([(('Turtle', 'Chicken'), (('Man', 'Monkey'), 'Dog'))])

```
I welcome any feedback, and any indication of what I might be doing wrong.  I used tuples in this program for the sake of Pythonic automation, nothing else.  You might also wish to see #24688

**Comment by jreback** [comment]
```
In [4]: broken_cluster.index                                                                                                                                                                                                                                            
Out[4]: Index([(('Turtle', 'Chicken'), (('Man', 'Monkey'), 'Dog')), 'Tuna', 'Moth'], dtype='object')
```
this has NO support in pandas whatsoever. If you can raise an error in a performant way great would take it

**Comment by TomAugspurger** [comment]
> It's in the bug report that I created, but I'll post a more concise demo here:

What's the issue number?

It's not really clear to me what the changes here are doing. e.g. why check specifically against a shape of `(1, 2, 2)`, not not something more general? This feels like you're trying to use pandas for something it isn't well-suited for.

**Comment by summonholmes** [comment]
> > It's in the bug report that I created, but I'll post a more concise demo here:
> 
> What's the issue number?
> 
> It's not really clear to me what the changes here are doing. e.g. why check specifically against a shape of `(1, 2, 2)`, not not something more general? This feels like you're trying to use pandas for something it isn't well-suited for.

The original issue I was addressing with this PR was #24687, and after further testing I've determined that nested tuples can generate even more anomalous shapes than `(1, 2, 2)`.  The fix on my end is simply converting to string and recording the actual tuples somewhere else.  Yes, I would never use pandas like this on a normal day.  Therefore, I believe this PRs intention will change to prevent this use of pandas in the first place.

> ```
> In [4]: broken_cluster.index                                                                                                                                                                                                                                            
> Out[4]: Index([(('Turtle', 'Chicken'), (('Man', 'Monkey'), 'Dog')), 'Tuna', 'Moth'], dtype='object')
> ```
> this has NO support in pandas whatsoever. If you can raise an error in a performant way great would take it

Please correct me if I'm wrong, I'd be happy to work on a fix.  You're saying that an error should be raised, as soon as a tuple is assigned to a column or index label?   I'm assuming that the approach required is closely related to #24688 and #24702.

**Comment by TomAugspurger** [comment]
Thanks. I don't think the resolution of #24688 and #24702 is clear yet.

**Comment by jreback** [comment]
looks like this was completly reverted, closing.

**Pull request closed without merging**
