### PR TITLE
DOC: Improve GL03 message re: blank lines at end of docstrings.

### PR DESCRIPTION
**Pull request by douglatornell**
re: conversation with @datapythonista in issue #23632

- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by datapythonista** [comment]
Did you run the tests `python -m pytest scripts`? Not sure if that specific error message is checked, but would be worth checking, as the CI will take some time.

Also, if you feel like it, may be you can add a test for the blank line at the end, to make sure we're giving that error. And if we don't have one with the two blank lines, you can add it too.

But happy to merge this PR as it is too, if no test is failing.

**Comment by douglatornell** [comment]
Thanks for the review!

Yes, I ran the tests locally to make sure that I hadn't broken anything, and they passed with the exception of 4(?) that are marked as expected failures.

I will take a look tomorrow at the possibility of adding test(s) and get update this PR one way or the other.

**Review by datapythonista — APPROVED** [review]
lgtm, I'd merge and add tests for this in a separate PR

**Comment by douglatornell** [comment]
Sorry @datapythonista, I didn't see your message about adding the tests in a new branch/PR before I pushed them into this one. How do you want me to proceed from here?

**Comment by datapythonista** [comment]
Don't worry, the changes are also all right here, doesn't make a difference, as this is not yet merged.

I think your tests are saying that does docstrings are correct (which is not the case). But I don't see them failing in the CI. I'm in my phone and can't check well right now, but I think the tests should say that the error messages are generated.

**Comment by datapythonista** [comment]
Sorry, my bad. From the phone I couldn't check well, and I thought they were checked with the `test_good_docstrings`.

Ideally I'd test them with `test_bad_examples`, so we not only assert that they are wrong, but we also assert that they generate the right error messages.

**Comment by douglatornell** [comment]
Okay, I'll take a look at putting them in `test_bad_examples` tomorrow (I hope).

**Comment by datapythonista** [comment]
@douglatornell do you have time to make the update to the tests?

**Comment by douglatornell** [comment]
@datapythonista yes. I have a flight later today and am hoping to do them then.

**Comment by douglatornell** [comment]
@datapythonista bad linebreak tests moved into `test_bad_examples()` and CI looks happy.

**Comment by datapythonista** [comment]
Thanks for the update @douglatornell. I'll ask one more change here if you don't mind.

There is something wrong in the tests (not your code, but in master) that is the name `test_bad_examples`. While the class `BadExamples` refers to the examples section of the docstrings, the name `test_bad_examples` refer to testing all the wrong things in any section.

So, if I can ask you to move back the two new examples of line breaks to `BadGenericDocStrings`, as they don't refer to the examples section. And then rename `test_bad_examples` to a better name, so it's not confusing, that would be great.

Thanks!

CC @WillAyd

**Comment by datapythonista** [comment]
Sorry @douglatornell, I think I wasn't clear in my last comment.

Moving the methods with the docstrings back to `BadGenericDocStrings` is correct.

But the code to call the tests (in the parametrization of `test_bad_examples`) was already right, and those didn't have to be moved. Instead, what I proposed was to rename the name of the function of the test. As `test_bad_examples` suggest that only the examples sections is tested there, which is not the case.

Does this make sense?

**Comment by douglatornell** [comment]
@datapythonista I have reverted the commit that put the new extra linebreak tests into `test_bad_examples()`.

I was going to change the name of `test_bad_examples()` to `test_bad_examples_section()`, but looking at its huge `pytest.mark.parametrize()` decorator, I realize that it also tests other docstring sections; e.g. "See Also". So, maybe it should be `test_bad_docstring_sections()`. But then I note that the decorator also contains `BadGenericDocStrings` and I look above it and see the `test_bad_generic_functions()` test...

I don't know the history of the `test_validate_docstrings` module, nor if you have big goal in mind for these docstring clean-up issues, but I am wondering if `test_validate_docstrings` needs a wholesale refactoring?

**Comment by datapythonista** [comment]
The `validate_docstrings.py` script almost contains everything we have in mind now. Just few validations missing. So, no big goal in mind.

I don't think the tests need a major refactoring. May be merging the two tests you mention can make sense (I didn't check in detail), but other than that I think we should be all right.

I'd rename `test_bad_examples` to `test_bad_docstrings` in this PR, and if you think more changes would make things better, I'd open another PR for that.

What do you think?

**Review by datapythonista — APPROVED** [review]
Thanks for the update @douglatornell, looks perfect now.

**Comment by jreback** [comment]
thanks @douglatornell

**Pull request merged**
