### PR TITLE
Enforce flake8 E741

### PR DESCRIPTION
**Pull request by alimcmaster1**
Enforce flake8 E741

#19496 ( Was added here )
But running `flake8 --select E741` returns nothing

Looks like this is a valid flake8 rule: ( unless im looking at the wrong docs )

https://lintlyci.github.io/Flake8Rules/

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm @TomAugspurger

**Comment by jbrockmendel** [comment]
+1

**Comment by WillAyd** [comment]
Simple enough and Travis passed so I'll take @jbrockmendel 's +1 as approval to merge :-)

Thanks @alimcmaster1

**Comment by alimcmaster1** [comment]
Thanks! @WillAyd

**Pull request merged**
