### PR TITLE
COMPAT: boto import issues

### PR DESCRIPTION
**Pull request by jreback**

### CODE REVIEW

**Comment by jreback** [comment]
@TomAugspurger any progress on #11915 

for ``boto`` to release a broken version is really annoying.

**Comment by jreback** [comment]
@TomAugspurger I just moved this all to a better location which at worse case would only raise on actual s3 import, rather than at pandas import time. I think this will also make integrating via s3fs slightly easier.

lmk.

**Comment by TomAugspurger** [comment]
K, rebasing on those changes is `test_parser.py` right now. I think I was pretty close to having it working. Will put up a PR this morning.

**Comment by jreback** [comment]
I have revised a bit. certainly ok with you making whatever changes, just want to get this out of the main import path.

**Comment by jreback** [comment]
@TomAugspurger any issue with this reorg? (I think your PR should easily go on top of this). hopefully can add more test coverage :)

**Comment by TomAugspurger** [comment]
Yeah, +1 on this I think.

**Comment by jreback** [comment]
@TomAugspurger gr8.

**Pull request closed without merging**
