### PR TITLE
Fix Inconsistent MultiIndex Sorting

### LINKED ISSUE #20945: Data is mismatched with labels after stack with MultiIndex columns
```python
df = pd.DataFrame([
    ['DIM', 'A', 1, 2, 3, 4],
    ['DIM', 'B', 11, 22, 33, 44],
])
df.columns = ["dim1", "dim2", 'c', 'b', 'a', 'd']
df = df.set_index(["dim1", "dim2"])
df.columns.name = 'metrics'

print(df)
metrics     c   b   a   d
dim1 dim2                
DIM  A      1   2   3   4
     B     11  22  33  44

print(df.unstack('dim2').stack('metrics'))

dim2          A   B
dim1 metrics       
DIM  a        1  11
     b        2  22
     c        3  33
     d        4  44
```
#### Problem description

After stacking data by one level of MultiIndex columns, the output is unexpected. 'metrics' labels are sorted alphabetically, but data is show as is - without being matched with labels.

#### Expected Output

Either option shown below would be fine and expected:

```python
dim2          A   B
dim1 metrics       
DIM  a        3  33
     b        2  22
     c        1  11
     d        4  44

dim2          A   B
dim1 metrics       
DIM  c        1  11
     b        2  22
     a        3  33
     d        4  44
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Darwin
OS-release: 17.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.21.0
pytest: 3.2.3
pip: 9.0.1
setuptools: 38.2.3
Cython: None
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: None
patsy: 0.5.0
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0b10
sqlalchemy: None
pymysql: 0.7.11.None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

### LINKED ISSUE #20994: DataFrame.sort_index by Level Name Incorrect After Unstack/Swaplevel
This is a very obscure issue but I think it is responsible for things getting out of whack in #20945

```python
In [1]: mi = pd.MultiIndex.from_product([[0], ['d', 'c']], names=['bar', 'baz'])
In [2]: df = pd.DataFrame([[0, 2], [1, 3]], index=mi, columns=['B', 'A'])
In [3]: df.columns.name = 'foo'

In [4]: df
Out[4]: 
foo      B  A
bar baz      
0   d    0  2
    c    1  3

In [5]: df.unstack().swaplevel(axis=1)
Out[5]: 
baz  c  d  c  d
foo  B  B  A  A
bar            
0    1  0  3  2

In [6]: df.unstack().swaplevel(axis=1).sort_index(axis=1, level=0)
Out[6]: 
baz  c     d   
foo  A  B  A  B  # Here subsequent levels get sorted
bar            
0    3  1  2  0

In [7]: df.unstack().swaplevel(axis=1).sort_index(axis=1, level='baz')
Out[7]: 
baz  c     d   
foo  B  A  B  A  # Here subsequent levels aren't getting sorted
bar            
0    1  3  0  2
```

If the DataFrame in step 5 above was constructed directly, the sorting would be the same regardless of whether or not you used the level index or label:

```python
In [1]: mi = pd.MultiIndex.from_tuples([('c', 'B'), ('d', 'B'), ('c', 'A'), ('d', 'A')], names=['baz', 'foo'])
In [2]: df = pd.DataFrame([[1, 0, 3, 2]], columns=mi, index=pd.Index([0], name='bar'))
In [3]: df  # Same as step 5 in above example
Out[3]: 
baz  c  d  c  d
foo  B  B  A  A
bar            
0    1  0  3  2

In [4]: df.sort_index(axis=1, level=0)
Out[4]: 
baz  c     d   
foo  A  B  A  B
bar            
0    3  1  2  0

In [5]: df.sort_index(axis=1, level='baz')
Out[5]: 
baz  c     d   
foo  A  B  A  B  # Sort is the same as item above, regardless of using label or not
bar            
0    3  1  2  0
```

Note that this only happened when doing the `unstack`  and `swaplevel` together. My original thought was that the latter would be solely responsible, but I could not reproduce the issue using just that alone, so I'm assuming the former is mutating some kind of state of the MultiIndex?

<details>

INSTALLED VERSIONS
------------------
commit: eff1faf2729fa0fb0c2d7913107201e475de33d6
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 17.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.0rc2+27.geff1faf27
pytest: 3.4.1
pip: 9.0.1
setuptools: 38.5.1
Cython: 0.27.3
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.7.0
patsy: None
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.5
feather: None
matplotlib: 2.1.2
openpyxl: 2.5.0
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.5
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### LINKED ISSUE #21052: sort_index with sort_remaining=False does not work with int level
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
mi = pd.MultiIndex.from_tuples([[2,2],[2,1],[1,2],[1,1]], names=list('AB'))
a = pd.Series([1,2,3,4], index=mi)
a.sort_index(level=0, sort_remaining=False)
```
returns:
```
A  B
1  1    4
   2    3
2  1    2
   2    1
dtype: int64
```

#### Problem description

Besides A (level 0), also B (level 1) is sorted. This, despite the fact that sort_remaining is set to False.

#### Expected Output

By comparison, the correct result is obtained when specifying the level by its name:

```python
a.sort_index(level='A', sort_remaining=False)
```
with
```
A  B
1  2    3
   1    4
2  2    1
   1    2
dtype: int64
```
Exactly the same result should be expected when using `level=0` instead of `level='A'`.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.22.0
pytest: None
pip: 9.0.3
setuptools: 36.4.0
Cython: None
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: 0.10.0
IPython: 5.3.0
sphinx: 1.6.3
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: 2.5.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.2.3
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by WillAyd**
closes #20994
closes #20945
closes #21052
- [X] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This is a pretty dark corner and I'll admit that I don't fully understand all of the elements in play. That said, the first problem I noticed with the first referenced issue was an errant conditional that was causing `level=0` and `level='foo'` to go down two different branches, even if the name of the first level was in fact 'foo'.

After uncovering that, the subsequent ordering of the returned index then was incorrect regardless of the argument. I moved a monotonic sort around to fix this, though I feel like:

 - There may be a more general purpose solution to fix this AND
 - There may be more expressive tests to add here

Feedback appreciated

### CODE REVIEW

**Comment by WillAyd** [comment]
Just added a test and fix to cover Series as well, as we just had another related issue pop up

cc @kdebrab

**Comment by jreback** [comment]
thanks @WillAyd very nice!

**Comment by jorisvandenbossche** [comment]
Does this need a whatsnew?

**Comment by WillAyd** [comment]
@jorisvandenbossche I can add one. Should I just open a separate PR for that?

**Comment by jorisvandenbossche** [comment]
If you think it is needed (if there are user facing changes), then a new PR is perfect

**Pull request merged**
