### PR TITLE
Fixed mypy errors in frequencies.py

### PR DESCRIPTION
**Pull request by srotondo**
- [ ] xref #37715 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by srotondo** [comment]
Shoot, looks like I accidentally left a change from one of my previous PRs in here, I'll fix that

**Review by phofl — APPROVED** [review]
lgtm

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @srotondo

**Review by twoertwein — APPROVED** [review]
Would also be fine with keeping it as-is and waiting for https://github.com/python/typeshed/issues/8219 allowing any object in `.get`

**Pull request merged**
