### PR TITLE
CI: move py36 slow to azure (#34776)

### LINKED ISSUE #34776: CI: move 3.6,slow or 3.6 locale builds from travis to azure
we have capacity on azure (we are using 8/10) and slightly overloaded on travis.

### PR DESCRIPTION
**Pull request by fangchenli**
- [x] closes #34776
- [x] 0 tests added / 0 passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by alimcmaster1** [comment]
Thanks for the PR. We would need to configure MySQL and PostGres on Azure Pipelines for this to work.

**Comment by VirosaLi** [comment]
> Thanks for the PR. We would need to configure MySQL and PostGres on Azure Pipelines for this to work.

Thanks, I'll look into this.

**Comment by VirosaLi** [comment]
I haven't figured out how to correctlly setup sql on Azure Pipelines. The current commit has sql removed for py36 slow.

**Comment by jreback** [comment]
thanks @VirosaLi 

I created a followup issue #35160 to add back the sql tests :->

**Comment by alimcmaster1** [comment]
Isn’t this the only place where the slow SQL tests where running? Think we should add back

**Comment by jreback** [comment]
yes we should

**Comment by jreback** [comment]
but ok as a follow up

**Comment by alimcmaster1** [comment]
> but ok as a follow up

Gotcha missed your comment above

**Pull request merged**
