### PR TITLE
Revert Cythonized Kendall implementation and improve test case to prevent regressions

### LINKED ISSUE #43401: BUG: Cythonized kendall correlation implementation is incorrect
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Problem description

The Cythonized implementation of Kendall correlation implemented [here](https://github.com/pandas-dev/pandas/pull/39132) has been completely broken in the case of tied values since its original commit.

Scipy (and most other stats pacakges) [implement](https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L4717) the [b variant](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient#Tau-b) of Kendall's tau, not the original version. Rank based correlation algorithms absolutely need to handle ties correctly as ordinal data often includes repeated values in some columns.

Even if we wanted to implement the "a variant" of Kendall's tau (which would be a breaking change from the implementation prior to the Cythonization diff), the correct code would disregard ties entirely, whereas the current implementation is including them in its calculations.

It's non-trivial to implement a Cythonized version of the correct code with tie-handling here, and I think that the Cythonized version should be reverted.

#### Code Sample, a copy-pastable example
```
df = pd.DataFrame([[1, 2], [2, 1], [1, 3]])
df[0].corr(df[1],method='kendall') == df.corr(method='kendall')[0][1]
# output
False
```

#### Expected Output

`True`

#### Change to test case that catches this bug

https://github.com/zrait/pandas/commit/94a0eea77bf587e4d502684da6a4ba8c6797ae83 is a simple change to the correlation test case that ensures that one of the columns used has repeated values and fails with the current implementation but not if the Cythonization is reverted.

More generally, I think the float test data should be updated to include duplicates, as a danger of randomly generated float data is the fact that it won't naturally include any duplicates.

### PR DESCRIPTION
**Pull request by zrait**
- [x] closes #43401 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
instead of reverting would be better to actually fix it
this is an edge case

**Comment by zrait** [comment]
I don't actually agree that this is an edge case. Kendall correlation is intended to be used with ordinal data and a textbook application would be something like computing correlation between a survey response with a limited domain 1-10 and some other variable--a case in which you're almost certain to have many duplicates.

**Comment by zrait** [comment]
If you look at the #scipy# Kendall code it is pretty clever and well vectorized and also uses a Cythonized Fenwick tree to compute the discordant pairs.

Looking at the original diff here and the performance improvements cited on it, I actually think a significant amount of the benefit is that ignoring ties allows you to take some major shortcuts. I'll note that I'm not an experienced Cython optimizer so if someone can make this handle ties while retaining the same margin of performance improvements I'd be very impressed and agree that'd be better. My intuition is that no matter what, a correct implementation will still have appreciably worse performance than the current incorrect one.

**Comment by lithomas1** [comment]
I'm fine with reverting this.

**Comment by simonjayhawkins** [comment]
> I'm fine with reverting this.

This is in released pandas so would also need a release note if we do this.

**Comment by zrait** [comment]
> > I'm fine with reverting this.
> 
> This is in released pandas so would also need a release note if we do this.

I added a release note referencing this is as fixing a regression.

To add a bit more to my above remarks, I think that in general if a change made solely to improve performance introduces incorrect behavior, unless the fix is trivial, the correct response is to first revert it and _then_ reopen the original goal of improving performance as a separate issue. Incorrect code is worse than slow code, and the baseline for a new attempt at improving performance should be the original implementation (in this case the scipy path that was used prior to the Cython implementation), not the wrong-but-faster code.

**Comment by jreback** [comment]
this is failing pre-commit: https://github.com/pandas-dev/pandas/pull/43403/checks?check_run_id=3526049796

**Comment by zrait** [comment]
> this is failing pre-commit: https://github.com/pandas-dev/pandas/pull/43403/checks?check_run_id=3526049796

Oops, should be fixed now--accidentally removed an extra newline in `pandas/_libs/algos.pyx`

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @zrait

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Comment by jreback** [comment]
@zrait if you wouldn't mind following the instructions above for the backport.

**Comment by zrait** [comment]
> @zrait if you wouldn't mind following the instructions above for the backport.

https://github.com/pandas-dev/pandas/pull/43431

**Pull request merged**
