### PR TITLE
BUG: RangeIndex accepting length-1 arrays as argument

### LINKED ISSUE #13542: BUG: groupby.transform fails with incompatible size
#### Code Sample, a copy-pastable example if possible
```python

np.random.seed(12345)
panel = pd.Panel(np.random.randn(125,200,10))
panel.iloc[:,:,0] = np.round(panel.iloc[:,:,0])
panel.iloc[:,:,1] = np.round(panel.iloc[:,:,1])
x = panel
cols = [0,1]
_x = x.swapaxes(0, 2).to_frame()
numeric_cols = []
for df_col in _x:
    if df_col not in cols and pd.core.common.is_numeric_dtype(_x[df_col].dtype):
        numeric_cols.append(df_col)

def _noop(df):
    return df

groups = _x.groupby(cols)
groups.transform(_noop)
```

#### Expected Output
The original input.  `_noop` is just a trivial example.

#### Error
```python
C:\anaconda\lib\site-packages\pandas\core\internals.py in construction_error(tot_items, block_shape, axes, e)
   3968         raise ValueError("Empty data passed with indices specified.")
   3969     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
-> 3970         passed, implied))
   3971 
   3972 

ValueError: Shape of passed values is (8, 25000), indices imply (8, 25799)
```

#### Comments
The indices have reversed order, which is problem 1.  Also, one index has lost a value.

#### output of ``pd.show_versions()``
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 23.0.0
Cython: 0.24
numpy: 1.11.0
scipy: 0.17.1
statsmodels: 0.8.0.dev0+f060948
xarray: 0.7.2
IPython: 4.2.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.6.0
matplotlib: 1.5.1
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: 0.2.1
```

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
- [x] closes #13542
- [x] tests added / passed
- [x] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback OK?

**Comment by jreback** [comment]
can you add the orginal issue example somewhere (and assert it works)

**Comment by jorisvandenbossche** [comment]
That's what I added in `test_concat.py` (next to the addition in the tests in `test_range.py`) I think?

**Comment by jreback** [comment]
is it a simplified example?


the original one is on a panel

**Comment by jorisvandenbossche** [comment]
Well, looking back at the original issue https://github.com/pydata/pandas/issues/13542, this is indeed not the original example I included in the tests. But I found the reported example rather convoluted/difficult to comprehend what was going on. And the example I added, is a simplified (whithout using panels) example that experience exactly the same issue (it is what happened inside the groupby).

But I can add the original panel example as well if you like

**Comment by jreback** [comment]
it's fine
a simplified example is often better anyhow
so lgtm

**Pull request merged**
