### PR TITLE
BUG: Weighted rolling aggregations min_periods=0

### LINKED ISSUE #51449: BUG: Weighted rolling aggregations do not respect min_periods=0
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame([np.nan, 0, 1, 2,])

print(df.rolling(window=3, win_type="exponential", min_periods=0).sum(tau=1))
#           0
# 0       NaN
# 1       NaN
# 2       NaN
# 3  1.735759
print(df.rolling(window=3, min_periods=0).sum())
#      0
# 0  0.0
# 1  0.0
# 2  1.0
# 3  3.0
print(df.rolling(window=3, win_type="exponential", min_periods=0).mean(tau=1))
#      0
# 0  NaN
# 1  NaN
# 2  NaN
# 3  1.0
print(df.rolling(window=3, min_periods=0).mean())
#      0
# 0  NaN
# 1  0.0
# 2  0.5
# 3  1.0
```

### Issue Description

When using weighted rolling aggregation and setting `min_periods` to `0` does not work and it is treated as `None`. Aggregations without weight work as expected.

### Expected Behavior

Weighted and not-weighted rolling aggregations should behave the same way with `min_periods=0` and fill `NaN` in the same positions.

### Installed Versions

<details>

commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.11.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 66.1.1
pip              : 22.2.2
Cython           : None
pytest           : 7.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.8.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

### PR DESCRIPTION
**Pull request by Savlik**
- [x] closes #51449
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
Looks pretty good. Could you add a whatsnew note in `v2.1.0.rst`?

**Comment by Savlik** [comment]
> Looks pretty good. Could you add a whatsnew note in `v2.1.0.rst`?

Sure thing. Done.

**Comment by mroeschke** [comment]
Looks like there's a merge conflict. Can you merge main once more?

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Savlik

**Pull request merged**
