### PR TITLE
TST: reenable some old quantile tests

### PR DESCRIPTION
**Pull request by ghost**
These disabled tests now pass on 3.7. Let's see what CI says.

### CODE REVIEW

**Comment by WillAyd** [comment]
Can you parametrize here instead? Generally better than than tests touching multiple cases, especially with skips like this

**Review by jreback — CHANGES_REQUESTED** [review]
ok on the re-enabling, but agree that makes sense to parameterize here.

**Comment by pilkibun** [comment]
I don't think I'll spend time parameterizing this old tests. I was just working on quantile, and noticed that it's been a long time since they were disabled, and they just worked. 

Feel free to close if you don't want this as-is.

**Comment by jreback** [comment]
can you merge master

**Comment by pilkibun** [comment]
updated.

**Comment by pilkibun** [comment]
seems like no interest in this

**Pull request closed without merging**
