### PR TITLE
DOC: Removal of return variable names [WIP]

### PR DESCRIPTION
**Pull request by Fosnet**
@datapythonista 

This is part of the sprint (3rd February). It removes the return variable name from the docstrings.

### CODE REVIEW

**Comment by WillAyd** [comment]
Looks generally good. Can you post the output of the validation script for the affected entries?

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @hannah-c 

Let us know if you need help with the validation docstring, but I don't think it's that relevant, this PR is just removing the name of the return, and I'd keep any other improvement to those docstrings in a separate PR.

**Comment by jreback** [comment]
thanks @hannah-c

**Comment by datapythonista** [comment]
@hannah-c if you want to double check that everything looks good now that this is merged, in around an hour or later you can check the development documentation: https://pandas-docs.github.io/pandas-docs-travis/

**Pull request merged**
