### PR TITLE
DOC: add highlights and toc to whatsnew file for 0.23.0

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
@TomAugspurger in case you didn't do this yet

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
(don't merge yet, I will at once go through the full file as well)

**Comment by TomAugspurger** [comment]
Ah thanks, I had not.

**Comment by TomAugspurger** [comment]
@jorisvandenbossche can you fix https://github.com/pandas-dev/pandas/pull/21051#issuecomment-389226304

Should be "from 0.22.0", not "0.23.0"  in `release.rst`.

**Comment by TomAugspurger** [comment]
OK @jorisvandenbossche just this one remaining :)

**Comment by jorisvandenbossche** [comment]
Merge away!

**Pull request merged**
