### PR TITLE
Revert "TYP: Many typing constructs are invariant"

### PR DESCRIPTION
**Pull request by twoertwein**
I accidentally pushed to pandas instead of my fork :(

Is it possible in github to disallow direct pushes to the repository (only allow PRs)?

edit: It seems that this is possible https://stackoverflow.com/a/57685576

### CODE REVIEW

**Comment by twoertwein** [comment]
@jreback @simonjayhawkins

**Comment by jreback** [comment]
go ahead and merge when ready

i think can prevent merging directly to master

**Comment by jreback** [comment]
I protected the main branch from direct pushes.

**Comment by twoertwein** [comment]
Some windows tests fail with:

> ImportError: the 'read_file' function requires the 'fiona' package, but it is not installed or does not import correctly.
> Importing fiona resulted in: DLL load failed while importing ogrext: The specified procedure could not be found.

Seems unrelated, but I am not going to merge this myself - messed up enough for today :(

**Review by MarcoGorelli — APPROVED** [review]
> Seems unrelated, but I am not going to merge this myself

Agreed that it looks unrelated - happy to merge then as it's just a revert

> messed up enough for today :(

Please don't be hard on yourself, I'm sure everyone appreciates your contributions to the community! :raised_hands:

**Comment by jreback** [comment]
yep yep totally fine @twoertwein

**Comment by simonjayhawkins** [comment]
> I protected the main branch from direct pushes.

@jreback the release scripts do a direct push. for main this is only an issue for rc. Is 1.4.x protected?

**Comment by jreback** [comment]
nope other branches are not protected

**Pull request merged**
