### PR TITLE
REGR: Fix to_numpy for masked array with non-numeric dtype

### LINKED ISSUE #56991: BUG: to_numpy_dtype_inference returns None when array is non-numeric and dtype isn't given
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
mport numpy as np
from pandas.core.arrays._utils import to_numpy_dtype_inference

# Issue 1: ArrayLike type of np.ndarray doesn't have atrribute .dtype.numpy_dtype
try:
    to_numpy_dtype_inference(np.array([1,2,3]), None, np.nan, False)
except Exception as e:
    print(e)

# Issue 2: If dtype isn't given and array is not a numeric dtype, returned dtype is None 
print(to_numpy_dtype_inference(np.array(['b','b','c']), None, np.nan, False))
```

### Issue Description

Two places in utility method 'to_numpy_dtype_inference' have issues. The first is that the input array arg "arr" can be of type[ndarray] but ndarray doesn't have an attribute ".dtype.numpy_dtype". The second is that non-numeric array inputs without a given dtype will return None instead of np.dtype(np.object_)

```python
def to_numpy_dtype_inference(
    arr: ArrayLike, dtype: npt.DTypeLike | None, na_value, hasna: bool
) -> tuple[npt.DTypeLike, Any]:
    if dtype is None and is_numeric_dtype(arr.dtype):
        dtype_given = False
        if hasna:
            if arr.dtype.kind == "b":
                dtype = np.dtype(np.object_)
            else:
                if arr.dtype.kind in "iu":
                    dtype = np.dtype(np.float64)
                else:
                    dtype = arr.dtype.numpy_dtype  # type: ignore[union-attr] # <-- Issue 1
                if na_value is lib.no_default:
                    na_value = np.nan
        else:
            dtype = arr.dtype.numpy_dtype  # type: ignore[union-attr]
    elif dtype is not None:
        dtype = np.dtype(dtype)
        dtype_given = True
    else:
        dtype_given = True # <-- Issue 2 [this should instead be "dtype = np.dtype(np.object_)"]

    if na_value is lib.no_default:
        na_value = arr.dtype.na_value

    if not dtype_given and hasna:
        try:
            np_can_hold_element(dtype, na_value)  # type: ignore[arg-type]
        except LossySetitemError:
            dtype = np.dtype(np.object_)
    return dtype, na_value

```

### Expected Behavior

Issue 1: This case doesn't apply to me so I don't have any expectation other than Pandas shouldn't throw an exception.
Issue 2: return np.dtype(np.object_) when array is non-numeric and dtype is not provided

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : f538741432edf55c6b9fb5d0d496d2dd1d7c2457
python                : 3.10.13.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.2.0
Version               : Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.3
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 69.0.3
pip                   : 23.3.2
Cython                : None
pytest                : 7.4.4
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 14.0.2
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : 2024.1.0
xlrd                  : None
zstandard             : 0.22.0
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #56991 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
Needs a whatsnew otherwise LGTM

**Comment by mroeschke** [comment]
> Should the following return pd.NA or np.nan for the na_value? It is returning pd.NA but that isn't allowed in a float64 array:

Personally I would expected `np.nan` here

**Comment by phofl** [comment]
#57233

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @phofl

**Pull request merged**
