### PR TITLE
CI: mypy fixup for #32261

### PR DESCRIPTION
**Pull request by simonjayhawkins**
https://github.com/pandas-dev/pandas/runs/485121000

### CODE REVIEW

**Comment by WillAyd** [comment]
Thanks for looking at the CI failures. Looks like you have a few PRs - can you advise on the priority of the,?

**Comment by simonjayhawkins** [comment]
> Thanks for looking at the CI failures. Looks like you have a few PRs - can you advise on the priority of the,?

hold on this for a minute.

**Comment by simonjayhawkins** [comment]
need to check Windows py36_np15

**Comment by simonjayhawkins** [comment]
> need to check Windows py36_np15

looks like test_value_counts_null is still flakey, xref #32281 cc @SaturnFromTitan

**Comment by SaturnFromTitan** [comment]
darn.. I'll have a look

**Comment by SaturnFromTitan** [comment]
Can you point me to a stacktrace for further investigation @simonjayhawkins?

**Comment by simonjayhawkins** [comment]
@SaturnFromTitan https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=29965&view=logs&j=077026cf-93c0-54aa-45e0-9996ba75f6f7&t=e95cf409-86ae-5b4d-6c5f-79395ef75e8f

**Comment by simonjayhawkins** [comment]
@WillAyd I think this is ok to merge now.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @simonjayhawkins

**Pull request merged**
