### PR TITLE
CLN: share compatibility-check code

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
what is the advantage of having raise_on_incompatible return an exception, just to *always* raise it?

**Comment by jbrockmendel** [comment]
> what is the advantage of having raise_on_incompatible return an exception, just to always raise it?

Among other things, mypy has an easier time telling that we have raised.  This is also the pattern we've moved to in Index

**Comment by WillAyd** [comment]
AFAIK you could just type the function as `NoReturn` (though maybe not available until 3.6.4)

No preference on my end between raise and return so lgtm

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
ok thanks

**Pull request merged**
