### PR TITLE
DOC: update conf.py to use new numpy doc url

### LINKED ISSUE #33953: DOC: Update numpy website url
When clicking on the `See Also` item of https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.argsort.html

We go to the old numpy url (docs.scipy.org), and a warning is shown to the user. We should update the target url of our numpy links.

Sphinx builds automatically these links, I guess the url is in `doc/source/conf.py`.

### PR DESCRIPTION
**Pull request by codeloop**
- [X] closes #33953
- [X] tests added / passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks @codeloop, did you build the docs locally and checked that the link is working all right? I guess the intersphinx file is available at the new URL, but we need to make sure before merging this. Thanks!

**Comment by codeloop** [comment]
@datapythonista , I'm building the docs, following the steps from here [Contributing to the documentation](https://pandas-docs.github.io/pandas-docs-travis/development/contributing.html#contributing-to-the-documentation), will update after build is complete & tested locally.

**Comment by codeloop** [comment]
successfully built documentation locally using this commit, now the links point to numpy url. 
For eg: In the pandas docs at https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.argsort.html
earlier it was referencing to : https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.argsort.html#numpy.ndarray.argsort
After this commint & build it references to : https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html#numpy.ndarray.argsort

Looks good to me.

**Review by datapythonista — APPROVED** [review]
Great, thanks @codeloop, lgtm

**Comment by datapythonista** [comment]
@jorisvandenbossche may be you want to have a look

**Review by jorisvandenbossche — APPROVED** [review]
Perfect, thanks!

**Comment by simonjayhawkins** [comment]
@Meeseeksdev backport to 1.0.x

**Pull request merged**
