### PR TITLE
PERF: column_arrays

### PR DESCRIPTION
**Pull request by jbrockmendel**
Shaves a couple percent off of time_to_json_wide asv

### CODE REVIEW

**Comment by jreback** [comment]
seems fine, cna you rebase

**Comment by jreback** [comment]
can you rebase again just to be sure

**Comment by jbrockmendel** [comment]
getting segfaults on some builds, must be coming from the json c code.  @WillAyd anything stand out to you?

**Comment by WillAyd** [comment]
Won’t be able to look or the next week or so. Have you tried running the tests under a debugger? Should break on any segfault 

https://pandas.pydata.org/docs/development/debugging_extensions.html

FWIW I personally haven’t been getting symbols to show up in the debugger when compiling with clang - not sure what caused that recently but gdb may make things easier if available to you

**Comment by jbrockmendel** [comment]
mothballing to clear the queue, need to figure out why this is segfaulting on some builds

**Pull request closed without merging**
