### PR TITLE
ENH: `Styler.format_index` split PR base components

### PR DESCRIPTION
**Pull request by attack68**
Splits #43101 to debug failing tests

All this PR does is add a method and fix failing tests because of a minor change to jinja2 templates.

### CODE REVIEW

**Comment by attack68** [comment]
This PR suffers the same undiagnosable fault as the mentioned PR.. 
If anyone fancies having a crack at solving the mysterious failure, please shout out.

**Comment by jreback** [comment]
try renaming this to format_index2 as a test and see if it works

**Comment by attack68** [comment]
> try renaming this to format_index2 as a test and see if it works

so that worked? whats the scoop?

**Comment by jreback** [comment]
> > try renaming this to format_index2 as a test and see if it works
> 
> so that worked? whats the scoop?

wow. so was thinking that `.format_index` shadows something, but we don't have a method by that name so that's obviously bunk, but maybe we somehow autogenerate something.

**Comment by attack68** [comment]
> > > try renaming this to format_index2 as a test and see if it works
> > 
> > 
> > so that worked? whats the scoop?
> 
> wow. so was thinking that `.format_index` shadows something, but we don't have a method by that name so that's obviously bunk, but maybe we somehow autogenerate something.

so you wanna keep the method named like this or something else. i've not faced issue like this before so bit clueless.

**Comment by jreback** [comment]
must be some sphinx thing 

ideally let's keep format_index though could call format_axis

**Comment by attack68** [comment]
OK well this PR now uses `format_axis` and the original PR still has `format_index`, which I prefer since it complements `apply_index` and `applymap_index`, downside being it breaks the CI and I can't fix it! So you can choose either! (I'll fix up the tests and add the doc examples if you go with this one)

**Comment by jreback** [comment]
yeah might try to google this
i suspect we can set some sphinx option in conf.py to avoid this

**Pull request closed without merging**
