### PR TITLE
CI testing for s3 reads from public buckets on 1.0.x - DO NOT MERGE

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref #34626

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche this works for me locally. If you can have a look at the failures in Travis and let me know if we're confident that #34626 is fixed on 1.0.x

**Comment by jorisvandenbossche** [comment]
Does the test run on one of the azure builds as well?

**Comment by jorisvandenbossche** [comment]
cc @TomAugspurger do you have any experience with this? On travis, the S3 public bucket reading is failing with boto / permission errors.

I checked out the 1.0.x branch locally, and can confirm it is working locally.

**Comment by TomAugspurger** [comment]
Not sure. I notice that the two jobs with failing moto / boto issues have moto==1.3.7. https://travis-ci.org/github/pandas-dev/pandas/jobs/698478225#L1128 has 1.3.14. Perhaps we failed to backport a dependency update?

**Comment by jorisvandenbossche** [comment]
But moto shouldn't be used for that test? (unless that is done automatically?)

**Comment by TomAugspurger** [comment]
Ah I missed that this was for the public bucket. You're correct, I think moto shouldn't be involed here..

**Comment by TomAugspurger** [comment]
When you're testing locally, do you run the whole file or just the single test? s3fs does cache things, including the S3FSFileSystem constructor, which might cause this.

**Comment by simonjayhawkins** [comment]
> Does the test run on one of the azure builds as well?

i'll create a failing test to make sure

**Comment by jorisvandenbossche** [comment]
> When you're testing locally, do you run the whole file or just the single test? s3fs does cache things, including the S3FSFileSystem constructor, which might cause this.

I just ran ``pd.read_csv("s3://nyc-tlc/misc/taxi _zone_lookup.csv")`` in a console

**Comment by jorisvandenbossche** [comment]
But running it with `pytest pandas/tests/io/test_s3.py` also works

**Comment by simonjayhawkins** [comment]
if we get the tests passing, does pandas have an amazon account where we can place a test file in a public bucket?

**Comment by simonjayhawkins** [comment]
hmm travis didn't run. 

> Does the test run on one of the azure builds as well?

on 3 azure builds, will revert the fail shortly

**Comment by jorisvandenbossche** [comment]
OK, if it thus was passing on azure, I think we can be confident enough for the 1.0.5 release that this is  properly working. And can then figure out the travis failure later when we fix this in master

**Comment by simonjayhawkins** [comment]
> OK, if it thus was passing on azure, I think we can be confident enough for the 1.0.5 release that this is properly working. And can then figure out the travis failure later when we fix this in master

OK closing

**Comment by jorisvandenbossche** [comment]
We could also already merge it (but then in the master branch), with an xfail, if you want

**Comment by simonjayhawkins** [comment]
i'm not sure about the ethics of using someones public bucket for testing

**Comment by alimcmaster1** [comment]
Ref my comment here: https://github.com/pandas-dev/pandas/issues/34626#issuecomment-640286333

I couldn’t get a test for public buckets working using moto.

I propose we use an Amazon Open Data public s3 bucket: https://aws.amazon.com/opendata/public-datasets/

We can use the tm.network decorator? Would be helpful to catch future regressions - especially since we are moving to fsspec. Thoughts @jorisvandenbossche @simonjayhawkins 

I can open a PR.

**Comment by jorisvandenbossche** [comment]
Using an existing public s3 bucket seems fine for this (we should just find a small dataset). 
And indeed, we have network tests, so we can just test this for real, without moto, with the network decorator.  Thanks @alimcmaster1 !

**Pull request closed without merging**
