### PR TITLE
~Finish collecting m8[ns] tests, start collecting division by zero tests

### PR DESCRIPTION
**Pull request by jbrockmendel**
The division by zero tests aren't yet parametrized, are mostly just moved as-is.  Both these and the newly moved m8[ns] tests will need a bunch of de-duplication in the next pass.

Tons of DataFrame tests failing.  #22074 is the PR we need, though maybe not the one we deserve.

Started in on fixtures.

### CODE REVIEW

**Comment by jreback** [comment]
k, rebase on top as merged #22074

**Comment by jbrockmendel** [comment]
One build is failing because it says there is no "box" fixture, but there is.  Seen this before?

**Comment by jbrockmendel** [comment]
@jreback this should go before others for easiest rebasing

**Comment by jreback** [comment]
ok lgtm. can you rebase and merge on green (just to make sure). can you make the next followup to split this to a sub-dir (i know its all td atm but just to make it clear / easier)

**Pull request merged**
