### PR TITLE
MAINT: Remove self.assertFalse from testing

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.

Partially addresses #15990.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
One remark for this replacement: in certain cases it might be that we want to test that something is *actually* ``False``, and not falsey (for which you would need to do `` assert xx is False`` instead of ``assert not xx``) 
But, this is difficult to say without looking in more detail into each of the tests, which is a bit too much work ..

**Comment by gfyoung** [comment]
@jorisvandenbossche : Well according to `unittest` documentation, `assertFalse(expr)` checks that `bool(expr) is False`, so I think that concern might be moot.

**Comment by jorisvandenbossche** [comment]
Ah, you're correct. The implementation actually just does ``if expr: raise ..``, which is equivalent.

**Comment by MaximilianR** [comment]
@gfyoung you're a hero for running through all these!

**Comment by gfyoung** [comment]
@MaximilianR : Thanks!  Couldn't do it without bash ;)

**Comment by jreback** [comment]
thanks!

**Pull request merged**
