### PR TITLE
DOC: Change code-block to ipython in r_interface.rst

### PR DESCRIPTION
**Pull request by FHaase**
The documentation mainly uses the `.. ipython::` directive. This changes
the code-blocks to ipython blocks so there is a unified visual style.

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
In this case that the tests shouldn't be executed, I find the `.. code-block:: python` clearer than the `ipython` with outputs. But replacing the `doctest: +SKIP` by the `:verbatim:` looks good.

**Comment by FHaase** [comment]
I've decided to use a `.. ipython::` block as it automatically changes the row numbers.

As there isn't a `>>>` anymore, `doctests` shouldn't find it as a test. This would eliminate the `doctest: +SKIP` which would be displayed in the documentation.

**Comment by FHaase** [comment]
The `ipython` directive is an extension of `IPython`. see [IPython sphinxext](https://ipython.readthedocs.io/en/stable/sphinxext.html)

> `[at]verbatim`:
insert the input and output block in verbatim, but auto-increment the line numbers. Internally, the interpreter will be fed an empty string, so it is a no-op that keeps line numbering consistent. Also, can be applied to the entire `.. ipython` block as a directive option with `:verbatim:`.

> `[at]doctest`:
Compare the pasted in output in the ipython block with the output generated at doc build time, and raise errors if they don’t match. Also, can be applied to the entire `.. ipython` block as a directive option with `:doctest:`.

> Pseudo-Decorators:
Note: Only one decorator is supported per input. If more than one decorator is specified, then only the last one is used.

As the `code-block` directive is not part of the IPython library it wouldn't have been run anyway. This way it's just using the style of the rest of the documentation.

**Comment by FHaase** [comment]
Ohh wait, you mean something like this:

```
.. ipython:: python
    :verbatim:

    from rpy2.robjects import r
    r.data('iris')
    r['iris'].head()

        Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
    0           5.1          3.5           1.4          0.2  setosa
    1           4.9          3.0           1.4          0.2  setosa
```

This way the output is recognized as some more input lines. That's why I utilized the `In [X]:` again.

**Comment by datapythonista** [comment]
In this case we can't use `ipython:: python` as the output can't be automatically generated. My point was that I find more readable the `>>>` syntax than the `In [1]`. And while these examples are not being run at the moment (except for the `ipython::python` to generate the output), it's not so important the `doctest: +SKIP` or the `verbatim`, but I think it's good to have it in case we run them later, and to make it explicit that those examples shouldn't run.

It's not very important, but personally I'd use `ipython:: python` for most cases, as it's the clearer, and a regular code-block for a case like this. I found those the most readable.

**Comment by FHaase** [comment]
> In this case we can't use ipython:: python as the output can't be automatically generated.
`verbatim` stops executing the code and makes the line(s) a no-op. 

> verbatim: insert the input and output block in verbatim, but auto-increment the line numbers. Internally, the interpreter will be fed an empty string, so it is a no-op that keeps line numbering consistent. Also, can be applied to the entire .. ipython block as a directive option with :verbatim:.

I like `>>>` more as well, but this way the style would be consistent with the rest of the documentation.

**Comment by datapythonista** [comment]
I think I asked you in another issue, but didn't yet understand. What's the reason you're using `ipython:: ipython` with the `In [1]` in other parts? I guess I'm missing something, but I'd use `ipython:: python` everywhere, and just in this case that the output can't be generated I'd use a code-block. So, I'd never use the `In [1]` syntax, so in this case the `>>>` would be as consistent as the `In [1]`.

**Comment by FHaase** [comment]
Well using:
```
.. ipython:: python
   >>> something
```

renders as:
```
In [1]: >>> something
```

**Review by datapythonista — APPROVED** [review]
Ok, I understand your point now. I thought you were talking about the consistency in terms of the code, not in how it is presented to the user (I thought it was always rendered the same).

lgtm then, thanks @FHaase

**Comment by jreback** [comment]
thanks @FHaase

**Pull request merged**
