### PR TITLE
ENH: support MultiIndex and tuple hashing

### PR DESCRIPTION
**Pull request by jreback**
on top of #15216 

closes #15227

### CODE REVIEW

**Comment by jreback** [comment]
cc @mikegraham 

I separated this from the prior PR.

yes my goal here is to effectively emulate ``hash(tuple)`` but doing it efficiently (e.g. we already have the arrays in a packed format, turning into python objects, just to compute a tuple hash is very inefficient).

**Comment by jreback** [comment]
@mikegraham 
ok I incorporated your commit (with a slight modification) and now passes tests!

**Comment by mikegraham** [comment]
There were a couple memory improvements in 187573bd490027078cb3d9b4bd9af349675a6a9d over the commit as you cherry-picked it, I think.

**Comment by jreback** [comment]
@mikegraham ahh ok, I will pick-again. thanks!

**Comment by jreback** [comment]
@mikegraham ok fixed.

Note that this obviously returns ``uint64``, so it is not quite compat with the tuplehashing in python?

**Comment by mikegraham** [comment]
I stole the algorithm, but it's not compatible. I also iterate over the members in forward error rather than reverse...I don't think that is substantive.

**Comment by jreback** [comment]
cc @mikegraham any final comments?

@jorisvandenbossche

**Comment by mikegraham** [comment]
We might want to do something about this behavior.

```>>> pandas.tools.hashing.hash_pandas_object(pandas.DataFrame(), index=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/tools/hashing.py", line 91, in hash_pandas_object
    h = _combine_hash_arrays(hashes, num_items)
  File "pandas/tools/hashing.py", line 19, in _combine_hash_arrays
    first = next(arrays)
StopIteration```

**Comment by jreback** [comment]
@mikegraham updated

**Pull request closed without merging**
