### PR TITLE
TST: remove 2D tests irrelevant for pyarrow

### PR DESCRIPTION
**Pull request by jbrockmendel**
Gets rid of 3367 irrelevant xfails cc @mroeschke

### CODE REVIEW

**Comment by mroeschke** [comment]
Could we skip them instead or leave a comment in this file that they are intentionally not implemented? Just don't want someone to try to re-address these tests in the future.

**Comment by jbrockmendel** [comment]
What if we better-documented the fact that these are only relevant for 2D-supporting EAs (and NDArrayBacked2DTests specifically for NDArrayBackedExtensionArray)?

**Comment by mroeschke** [comment]
> NDArrayBacked2DTests

Sure, that would work too.

**Comment by jbrockmendel** [comment]
added an extra comment

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel 

Backporting as relevant to the new ArrowExtensionArray in 1.5

**Pull request merged**
