### PR TITLE
Docs readme update

### PR DESCRIPTION
**Pull request by alexander-l-stone**
- [x] Helps with #23084 
- [x] No tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] Modified the process for updating forks in docs/README.rst to use git merge instead of git rebase. Also added the git command for setting upstream to pandas.

### CODE REVIEW

**Review by WillAyd — CHANGES_REQUESTED** [review]
Thanks for the PR! Do you also want to update the README to account for the non-functional `python make.py build` line?

**Comment by TomAugspurger** [comment]
This all seems duplicative of the contributing page. How about we extract what isn't in there already and just change `doc/README.rst` to a link pointing to that?

**Comment by jreback** [comment]
@alexander-l-stone can you update to @TomAugspurger suggestion.

**Comment by datapythonista** [comment]
Closing as stale. @alexander-l-stone if you want to continue working on it, please reopen or create a new PR, and refer to #23828.

**Pull request closed without merging**
