### PR TITLE
CLN: C408 Unnecessary dict call - rewrite as a literal #38138

### LINKED ISSUE #38138: CLN: C408 Unnecessary dict call - rewrite as a literal
The following files contain flake8 C408 Unnecessary dict call - rewrite as a literal. Good for first time contributors. See #38078 and #38116 for how to fix them. Use `flake8 [file_path]` to check for each file.

### C408
- [x] ./pandas/core/generic.py
- [x] ./pandas/core/series.py
- [x] ./pandas/core/frame.py
- [x] ./pandas/core/strings/accessor.py
- [x] ./pandas/core/dtypes/dtypes.py
- [x] ./pandas/core/computation/pytables.py
- [x] ./pandas/core/computation/expressions.py
- [x] ./pandas/core/arrays/floating.py
- [x] ./pandas/core/arrays/interval.py
- [x] ./pandas/core/arrays/numpy_.py
- [x] ./pandas/core/arrays/base.py
- [x] ./pandas/core/ops/methods.py
- [x] ./pandas/core/indexes/interval.py
- [x] ./pandas/core/indexes/multi.py
- [x] ./pandas/core/indexes/numeric.py
- [x] ./pandas/core/indexes/base.py
- [x] ./pandas/io/pytables.py
- [x] ./pandas/tests/reshape/concat/test_datetimes.py
- [x] ./pandas/tests/reshape/merge/test_merge.py
- [x] ./pandas/tests/reshape/merge/test_multi.py
- [x] ./pandas/tests/tools/test_to_numeric.py
- [x] ./pandas/tests/resample/test_time_grouper.py
- [x] ./pandas/tests/util/test_assert_series_equal.py
- [x] ./pandas/tests/util/test_assert_interval_array_equal.py
- [x] ./pandas/tests/util/test_assert_index_equal.py
- [x] ./pandas/tests/util/test_assert_extension_array_equal.py
- [x] ./pandas/tests/io/test_parquet.py
- [x] ./pandas/tests/io/generate_legacy_storage_files.py
- [x] ./pandas/tests/io/formats/test_format.py
- [x] ./pandas/tests/io/parser/test_comment.py
- [x] ./pandas/tests/io/parser/test_parse_dates.py
- [x] ./pandas/tests/io/parser/test_c_parser_only.py
- [x] ./pandas/tests/io/parser/test_dialect.py
- [x] ./pandas/tests/io/parser/test_skiprows.py
- [x] ./pandas/tests/io/parser/test_encoding.py
- [x] ./pandas/tests/io/parser/test_read_fwf.py
- [x] ./pandas/tests/io/parser/test_python_parser_only.py
- [x] ./pandas/tests/io/parser/test_na_values.py
- [x] ./pandas/tests/io/parser/test_usecols.py
- [x] ./pandas/tests/io/parser/test_quoting.py
- [x] ./pandas/tests/io/parser/test_header.py
- [x] ./pandas/tests/io/parser/test_index_col.py
- [x] ./pandas/tests/io/json/test_ujson.py
- [x] ./pandas/tests/io/json/test_normalize.py
- [x] ./pandas/tests/io/pytables/test_timezones.py
- [x] ./pandas/tests/io/pytables/test_store.py
- [x] ./pandas/tests/frame/test_reductions.py
- [x] ./pandas/tests/frame/test_arithmetic.py
- [x] ./pandas/tests/frame/methods/test_to_records.py
- [x] ./pandas/tests/frame/methods/test_sort_values.py
- [x] ./pandas/tests/frame/methods/test_fillna.py
- [x] ./pandas/tests/frame/methods/test_to_csv.py
- [x] ./pandas/tests/frame/indexing/test_indexing.py
- [x] ./pandas/tests/frame/indexing/test_where.py
- [x] ./pandas/tests/dtypes/test_inference.py
- [x] ./pandas/tests/groupby/test_function.py
- [x] ./pandas/tests/groupby/transform/test_transform.py
- [x] ./pandas/tests/plotting/test_boxplot_method.py
- [x] ./pandas/tests/plotting/frame/test_frame_subplots.py
- [ ] ./pandas/tests/io/parser/test_common.py

### Remove ignore setting from flake8 section
- [ ] setup.cfg

### PR DESCRIPTION
**Pull request by UrielMaD**
Fix in:
./pandas/tests/io/generate_legacy_storage_files.py

- [x] closes #38138
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks @UrielMaD , looks good to me pending green

**Comment by UrielMaD** [comment]
@MarcoGorelli It will be all green in a bit, then maybe it can close the issue, I tried to commit the setup.cfg but then the checks crashes because it has some flake8 errors.

**Comment by MarcoGorelli** [comment]
I haven't checked yet, but if there are still some leftover files then we'll need to wait for those to be rewritten before we can update setup.cfg and close the issue

**Comment by UrielMaD** [comment]
I think these were the last 10 files remaining

**Comment by MarcoGorelli** [comment]
then I'm not sure why flake8 would fail, can you post the errors?

**Comment by UrielMaD** [comment]
Sure, take a look:

(base) root@7be73fd07673:/workspaces/pandas-urielmd# flake8 setup.cfg
setup.cfg:12:28: E226 missing whitespace around arithmetic operator
setup.cfg:13:27: E226 missing whitespace around arithmetic operator
setup.cfg:15:26: E999 SyntaxError: invalid syntax
setup.cfg:18:4: E226 missing whitespace around arithmetic operator
setup.cfg:18:9: E226 missing whitespace around arithmetic operator
setup.cfg:20:5: E113 unexpected indentation
setup.cfg:28:5: E113 unexpected indentation
setup.cfg:28:8: E226 missing whitespace around arithmetic operator
setup.cfg:28:18: E226 missing whitespace around arithmetic operator
setup.cfg:29:8: E226 missing whitespace around arithmetic operator
setup.cfg:29:14: E226 missing whitespace around arithmetic operator
setup.cfg:30:8: E226 missing whitespace around arithmetic operator
setup.cfg:30:13: E226 missing whitespace around arithmetic operator
setup.cfg:31:10: E226 missing whitespace around arithmetic operator
setup.cfg:35:8: E226 missing whitespace around arithmetic operator
setup.cfg:36:4: E226 missing whitespace around arithmetic operator
setup.cfg:36:9: E226 missing whitespace around arithmetic operator
setup.cfg:38:5: E113 unexpected indentation
setup.cfg:43:10: E111 indentation is not a multiple of four
setup.cfg:43:10: E113 unexpected indentation
setup.cfg:44:10: E111 indentation is not a multiple of four
setup.cfg:45:10: E114 indentation is not a multiple of four (comment)
setup.cfg:46:10: E111 indentation is not a multiple of four
setup.cfg:47:10: E111 indentation is not a multiple of four
setup.cfg:48:10: E114 indentation is not a multiple of four (comment)
setup.cfg:49:10: E111 indentation is not a multiple of four
setup.cfg:50:10: E111 indentation is not a multiple of four
setup.cfg:53:5: E113 unexpected indentation
setup.cfg:53:8: E226 missing whitespace around arithmetic operator
setup.cfg:53:15: E226 missing whitespace around arithmetic operator
setup.cfg:53:27: E226 missing whitespace around arithmetic operator
setup.cfg:60:19: E226 missing whitespace around arithmetic operator
setup.cfg:60:24: E226 missing whitespace around arithmetic operator
setup.cfg:63:5: E113 unexpected indentation
setup.cfg:63:10: E231 missing whitespace after ':'
setup.cfg:63:17: E231 missing whitespace after ':'
setup.cfg:64:10: E231 missing whitespace after ':'
setup.cfg:64:26: E231 missing whitespace after ':'
setup.cfg:65:13: E225 missing whitespace around operator
setup.cfg:70:6: E111 indentation is not a multiple of four
setup.cfg:70:6: E113 unexpected indentation
setup.cfg:70:7: E226 missing whitespace around arithmetic operator
setup.cfg:70:13: E226 missing whitespace around arithmetic operator
setup.cfg:71:6: E111 indentation is not a multiple of four
setup.cfg:71:12: E226 missing whitespace around arithmetic operator
setup.cfg:72:6: E111 indentation is not a multiple of four
setup.cfg:72:12: E226 missing whitespace around arithmetic operator
setup.cfg:79:5: E113 unexpected indentation
setup.cfg:79:11: E226 missing whitespace around arithmetic operator
setup.cfg:82:5: E116 unexpected indentation (comment)
setup.cfg:83:5: E113 unexpected indentation
setup.cfg:96:5: E112 expected an indented block
setup.cfg:97:5: E112 expected an indented block
setup.cfg:99:1: E112 expected an indented block
setup.cfg:105:30: E231 missing whitespace after ','
setup.cfg:105:45: E231 missing whitespace after ','
setup.cfg:105:59: E226 missing whitespace around arithmetic operator
setup.cfg:105:60: E231 missing whitespace after ','
setup.cfg:105:74: E231 missing whitespace after ','
setup.cfg:107:33: E231 missing whitespace after ','
setup.cfg:107:43: E231 missing whitespace after ','
setup.cfg:108:18: E231 missing whitespace after ','
setup.cfg:108:25: E231 missing whitespace after ','
setup.cfg:108:36: E231 missing whitespace after ','
setup.cfg:108:45: E231 missing whitespace after ','
setup.cfg:108:54: E231 missing whitespace after ','
setup.cfg:108:61: E231 missing whitespace after ','
setup.cfg:108:72: E231 missing whitespace after ','
setup.cfg:108:82: E231 missing whitespace after ','
setup.cfg:108:89: E501 line too long (93 > 88 characters)
setup.cfg:114:14: E226 missing whitespace around arithmetic operator
setup.cfg:117:17: E226 missing whitespace around arithmetic operator
setup.cfg:126:6: E226 missing whitespace around arithmetic operator
setup.cfg:127:19: E225 missing whitespace around operator
setup.cfg:129:6: E226 missing whitespace around arithmetic operator
setup.cfg:130:19: E225 missing whitespace around operator
setup.cfg:132:6: E226 missing whitespace around arithmetic operator
setup.cfg:133:19: E225 missing whitespace around operator

**Comment by MarcoGorelli** [comment]
you don't need to run `flake8` on setup.cfg, but on the rest of the project.

Can you run
```
pre-commit run flake8 --all-files
```
? If that passes, we're good to update it and close the issue

**Comment by UrielMaD** [comment]
My bad, there are still some unnecessary dict and tuple calls, I will check all of them and submit a new PR

**Comment by MarcoGorelli** [comment]
cool, thanks @UrielMaD !

**Comment by MarcoGorelli** [comment]
@UrielMaD looks like there's only `pandas/tests/io/parser/test_common.py` - if you make a PR for that one and update `setup.cfg` we should be good to close the issue

**Pull request merged**
