### PR TITLE
BUG/PERF: MaskedArray.__setitem__ validation

### LINKED ISSUE #44172: PERF: `apply` on `boolean`-dtype DataFrame is exceedingly slow
### 

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this issue exists on the master branch of pandas.

### Reproducible Example

```python3
from timeit import timeit
import pandas as pd

# Create a dummy DataFrame of bools and null values.
df = pd.DataFrame([[True, False, pd.NA] * 200] * 200, dtype = "object")

# This runs very slowly!
print(timeit(lambda: df.astype("boolean").apply(lambda row: row.count(), axis = 1), number = 10)) # 112s

# (As can be easily seen, this is due partly to the `astype` on the entire DataFrame, but mainly to the subsequent `apply` being particularly slow for a boolean-dtype DataFrame).
print(timeit(lambda: df.astype("boolean"), number = 10)) # 3.98s

# This *equivalent* statement runs fast. There seems to be no good reason why the call to `apply` in the previous statement (overall equivalent) must be so slow.
print(timeit(lambda: df.apply(lambda row: row.astype("boolean").count(), axis = 1), number = 10)) # 0.95s
```

There is no problem using the first method in some cases, but it is inconvenient in other situations to cast back and forth between object-dtype and boolean-dtype just to make `apply` efficient.

### Installed Versions

<details>

commit           : aced6eedf90f3fdb0e658f33ac89c13fad62b06e
python           : 3.9.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.4.0.dev0+970.gaced6eedf9
numpy            : 1.20.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.2.0
Cython           : 0.29.24
pytest           : 6.2.5
hypothesis       : 6.23.4
sphinx           : 4.2.0
blosc            : 1.10.6
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.2
IPython          : None
pandas_datareader: 0.10.0
bs4              : 4.10.0
bottleneck       : None
fsspec           : 2021.10.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : 2021.10.1
scipy            : 1.7.1
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : 0.19.0
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.54.1

</details>

### Prior Performance

Not applicable.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #44172
- [x] closes #44186
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Fixes a bunch of ways we currently allow invalid setting, but ATM does _not_ fix the non-scalar equivalents.

Perf example from #44172 OP
```
df = pd.DataFrame([[True, False, pd.NA] * 200] * 200, dtype = "object")
df2 = df.astype("boolean")

%timeit res = df2.apply(lambda row: row.count(), axis = 1)
3.9 s ± 192 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # <- main
886 ms ± 40.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # <- PR
```

### CODE REVIEW

**Comment by jreback** [comment]
what's the bug fix here?

**Comment by jbrockmendel** [comment]
> what's the bug fix here?

```
arr = pd.array([True, False])
arr[0] = pd.NaT  # <- fails to raise
```

**Comment by jreback** [comment]
> > what's the bug fix here?
> 
> ```
> arr = pd.array([True, False])
> arr[0] = pd.NaT  # <- fails to raise
> ```

kk prob worth a note in a followon

**Comment by jreback** [comment]
@jbrockmendel seems something related to setitem is breaking on master: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=72425&view=logs&j=e2350215-d973-503e-a41e-d287ff823797&t=751e993b-1954-5330-832a-a54bd1064f7d&l=44

**Comment by jbrockmendel** [comment]
yah just put up a PR that should fix it

**Pull request merged**
