### PR TITLE
DOC: Remove alias for numpy.random.randn from the docs

### PR DESCRIPTION
**Pull request by WuraolaOyewusi**
Based on this comment: https://github.com/pandas-dev/pandas/issues/28038#issuecomment-523439376

Supersedes #28068

### CODE REVIEW

**Comment by WuraolaOyewusi** [comment]
@datapythonista Hi Marc, I've done this

**Comment by datapythonista** [comment]
do you mind having both changes in the same PR? thanks @WuraolaOyewusi

**Comment by WuraolaOyewusi** [comment]
ok @datapythonista

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @WuraolaOyewusi

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
@WuraolaOyewusi Thanks a lot!

**Pull request merged**
