### PR TITLE
TST: update gbq service account key

### LINKED ISSUE #34779: CI: gbq tests failing
https://travis-ci.org/github/pandas-dev/pandas/builds/698328374
and specificallly these 2 builds: https://travis-ci.org/github/pandas-dev/pandas/jobs/698328378

cc @alimcmaster1 @tswast 

if you have any insights

### PR DESCRIPTION
**Pull request by tswast**
Re-enable gbq integration tests.

- [ ] closes #34779
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by tswast** [comment]
Build currently running at https://travis-ci.org/github/tswast/pandas/builds/704072366. I need additional permissions in order to create the encryption key environment variables on the pandas-dev Travis config.

**Comment by jreback** [comment]
@tswast does this run?

**Comment by tswast** [comment]
@jreback It [runs on my fork](https://travis-ci.org/github/tswast/pandas/builds/704081779), but still having trouble with encrypting the keys for use in the pandas-dev org.

```
$ travis encrypt-file -r pandas-dev/pandas $GBQ_JSON_FILE travis_gbq.json.enc -f

encrypting pandas-gbq-tests-e842e94bcd25.json for pandas-dev/pandas
storing result as travis_gbq.json.enc
storing secure env variables for decryption
resource not found ({"error":"Couldn't find repository"})
```

I can now see the pandas project under "my repositories" in Travis. But maybe it's still not working because I can't see the "Settings" menu like I can on my fork.

Screen Shot 2020-07-06 at 9 45 32 AM

Screen Shot 2020-07-06 at 9 47 25 AM

**Comment by tswast** [comment]
Looks like write access is needed in order to update settings (including adding encryption keys?). 😕 https://docs.travis-ci.com/user/travis-ci-for-private/#who-has-access-to-the-builds

**Comment by tswast** [comment]
I was able to add the required keys to Travis. Since Travis doesn't allow the use of keys from forks, I also pushed this branch https://github.com/pandas-dev/pandas/tree/issue34779-enable-gbq-tests, which can be deleted once verifying the build at https://travis-ci.org/github/pandas-dev/pandas/builds/705824144

**Comment by jreback** [comment]
ok let's try this.

**Pull request merged**
