### PR TITLE
Fix AttributeError in scripts/validate_docstrings for doc.returns[0].name

### LINKED ISSUE #27622: BUG: AttributeError in scripts/validate_docstrings for doc.returns[0].name
#### Code Sample, a copy-pastable example if possible

```shell
python scripts/validate_docstrings.py pandas.Series.item
```
```
Traceback (most recent call last):
  File "scripts/validate_docstrings.py", line 1047, in <module>
    args.ignore_deprecated,
  File "scripts/validate_docstrings.py", line 969, in main
    result = validate_one(func_name)
  File "scripts/validate_docstrings.py", line 836, in validate_one
    errs, wrns, examples_errs = get_validation_data(doc)
  File "scripts/validate_docstrings.py", line 760, in get_validation_data
    if len(doc.returns) == 1 and doc.returns[0].name:
AttributeError: 'tuple' object has no attribute 'name'
```
#### Problem description

I get an AttributeError when running the script.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

### PR DESCRIPTION
**Pull request by albertvillanova**
- [X] closes #27622
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you add some tests for this

**Comment by WillAyd** [comment]
What version of numpydoc is this? IIRC they have been using named tuples in more recent versions which is preferable from a readability perspective. Does upgrading resolve your issue?

**Comment by albertvillanova** [comment]
@WillAyd, yes you are right: since numpydoc version 0.9, they use a Parameter named tuple (https://github.com/numpy/numpydoc/commit/136d4dd75207f529078c5c47dc4db53d0f38b4bf); I have v0.8.0 in my pandas dev environment.

**Comment by WillAyd** [comment]
I’d prefer to just bump our min version here for readability. Still pretty new (0.9 came out in April) but I think OK for a dev dependency.

**Comment by gfyoung** [comment]
> Still pretty new (0.9 came out in April) but I think OK for a dev dependency.

I'm in agreement on this.  We can be a little more aggressive for development dependencies.

**Comment by WillAyd** [comment]
We actually already do require this in environment.yaml per #26188 so I don't think anything to do here (unless we care to document further)

**Comment by gfyoung** [comment]
> I don't think anything to do here 

I'm agreement with this.

@albertvillanova : I'm closing this because the fix is just to upgrade to `numpydoc` per the new requirements on `master`.  Thanks for contributing though!  You are more than welcome to tackle any of our other open issues in our issue tracker.

**Comment by albertvillanova** [comment]
Yes, I had noticed the version requirement in environment.yaml.

@gfyoung @WillAyd What about documenting how to update the dev environment in Contributing section?

**Comment by gfyoung** [comment]
When you say document, what would you add about upgrading?  It’s just doing a `pip` or `conda` upgrade, no?

**Comment by albertvillanova** [comment]
You have thoroughly documented the creation of the dev environment using the environment.yaml file. However nothing is said about updating it (using the environment.yaml, which might have changed since the last time, with new packages or new version requirements). Nevertheless, if you think it is OK as it is... Nevermind!

**Comment by gfyoung** [comment]
> Nevertheless, if you think it is OK as it is... Nevermind!

Not saying that I think it's OK as is.  I'm just trying to understand what you wanted to do.

Why don't you submit a PR, and we can better evaluate.

**Pull request closed without merging**
