### PR TITLE
REF: refactor implementation of to_dict out of frame.py and into core.methods.to_dict

### LINKED ISSUE #49845: REF: Move `to_dict` implementation to pandas.core.methods.to_dict
Ref: https://github.com/pandas-dev/pandas/pull/46487#pullrequestreview-1059398661

For code organization, it'd be good to get the implementation of these methods out of `frame.py` and to a more suitable location - `pandas.core.methods.to_dict`

### PR DESCRIPTION
**Pull request by kostyafarber**
- [x] closes #49845 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Following https://github.com/pandas-dev/pandas/pull/46487#pullrequestreview-1059398661 a decision was made to move the implementation of `to_dict` in `frame.py` into `pandas.core.methods.to_dict`.

### CODE REVIEW

**Comment by kostyafarber** [comment]
@rhshadrach friendly ping

**Review by rhshadrach — APPROVED** [review]
lgtm

**Comment by rhshadrach** [comment]
Thanks @kostyafarber! There are other methods that should now go in this directory - describe is one example. Would you be interested in continuing this kind of refactor?

**Comment by kostyafarber** [comment]
Hey @rhshadrach no worries, glad I can help - Yeah sure! 

If you wanna open up an issue with a list of methods, I can open PRs against them and work on it.

**Comment by kostyafarber** [comment]
@rhshadrach shall I look into describe or are you compiling a list? Happy to work on describe in the meantime.

**Comment by rhshadrach** [comment]
@kostyafarber - I don't plan on compiling a list; I think describe would be great to work on.

**Comment by kostyafarber** [comment]
@rhshadrach `describe.py` currently is as a standalone file in `core` would the refactor simply be moving that file into `methods`?

**Comment by kostyafarber** [comment]
?

**Comment by rhshadrach** [comment]
@kostyafarber - thanks for the ping; yes, that's correct.

**Pull request merged**
