### PR TITLE
TST: Split graphics_test to main and others

### PR DESCRIPTION
**Pull request by sinhrks**
Because `test_graphics.py` gets little longer, I've splitted it to 2 files. Test methods itself are not changed.
- `test_graphics.py` is for `.plot()` methods.
- `test_graphics_others.py` is for other plots, such as `.hist()`, `.boxplot` and miscs.

### CODE REVIEW

**Comment by shoyer** [comment]
OK, this seems fine by me... though we do eventually probably want to consolidate all these methods into `.plot.hist()` and so forth (I promise I'll finish that PR!)

**Comment by sinhrks** [comment]
@shoyer In plot accessor, hist and box calls ``.plot(kind="hist")`` and ``.plot(kind="box")`` internally. These tests are included in ``test_graphics`` because these are part of ``.plot`` method. So no worries.

Moved to "test_graphics_others.py" are  ``DataFrame.hist`` and ``DataFrame.boxplot`` which used prior to ``.plot(kind="hist")``,  etc. These use separate (inconsistent) logic from ``.plot``.

**Comment by sinhrks** [comment]
Is this OK after v0.16.1 visualization-related PRs are merged (#8885)?
@jreback, @TomAugspurger

**Comment by TomAugspurger** [comment]
Yeah. I have time set aside this weekend.  Will review then.

**Comment by jreback** [comment]
@sinhrks status?

**Comment by sinhrks** [comment]
@TomAugspurger  OK for this?

**Comment by TomAugspurger** [comment]
Yeah, the only thing I would maybe add is a module docstring at the top of the file explaining which tests go where. But go ahead and merge.

**Comment by sinhrks** [comment]
@TomAugspurger Thanks. Added short explanations to both files, and will merge after it gets green.

**Pull request merged**
