### PR TITLE
DOC: modify typos in Contributing section

### PR DESCRIPTION
**Pull request by alyssafuward**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I participated in an open source sprint day today. This is my first attempt to request a PR to contribute to open source. I made changes to fix a few minor typos.

### CODE REVIEW

**Review by gfyoung — APPROVED** [review]
@alyssafuward : Nice job!

Welcome to Open Source contributing!  We hope you continue to contribute.  We're always looking for people to volunteer and help improve our codebase.

cc @jreback

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
@alyssafuward Thanks a lot!

**Comment by alyssafuward** [comment]
Thank you for the support! This totally made my night!

**Comment by gfyoung** [comment]
@alyssafuward : Our pleasure!  We hope that you'll continue to contribute more to our repository (and to open source in general) in the future!

**Pull request merged**
