### PR TITLE
MAINT: Remove Long and WidePanel

### PR DESCRIPTION
**Pull request by gfyoung**
Deprecated since 0.17.0.

xref #10892

### CODE REVIEW

**Comment by jreback** [comment]
any doc references to these? (prob not, but give a check)

**Comment by jreback** [comment]
looks like a minor flake issue. i can fix on merge. ping when everything else is green. (or you can repush up to you).

**Comment by gfyoung** [comment]
> any doc references to these? (prob not, but give a check)

Didn't find when I did a GitHub search

> looks like a minor flake issue

Yep, found it.  Will patch on repush

**Comment by jreback** [comment]
thanks!

**Pull request merged**
