### PR TITLE
Fix mypy error in testing

### PR DESCRIPTION
**Pull request by phofl**
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them

Fixup to get ci green again

### CODE REVIEW

**Comment by jreback** [comment]
great merge in green

**Comment by jbrockmendel** [comment]
can i suggest the approach taken in #44744?  (also fixes a FutureWarning that is failing the npdev build)

**Comment by jbrockmendel** [comment]
i think closed by #44744

**Comment by jreback** [comment]
yeah i think fixed on master already, thanks @phofl

**Comment by phofl** [comment]
No worries

**Pull request closed without merging**
