### PR TITLE
CLN: remove SingleBlockManager.get_values

### PR DESCRIPTION
**Pull request by jbrockmendel**
It is only used in one place, and its behavior doesn't match `self.blocks[0].get_values()`, which is counter-intuitive.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@datapythonista do you think it would be viable to make the docbuild output less verbose to make it easier to see what is causing a failure?

**Comment by datapythonista** [comment]
> @datapythonista do you think it would be viable to make the docbuild output less verbose to make it easier to see what is causing a failure?

Not sure if it's possible to have more control, but may be we can call it with `-q`. Those are the options I see:
```
console output options:
  -v                increase verbosity (can be repeated)
  -q                no output on stdout, just warnings on stderr
  -Q                no output at all, not even warnings
```
I think it can make sense, I don't think there is anything in the output that I find that useful (surely not all the "reading" and "writing" for the progress). But @jorisvandenbossche should know better if that makes sense.

**Comment by jorisvandenbossche** [comment]
If we want that, someone should investigate if all errors we want to see still show up (eg the output of ipython directive might be put on stdout).

But @jbrockmendel, for this specific PR, what was failing in the doc build? (I only see a failure to checkout in the pipeline)

**Comment by jbrockmendel** [comment]
> for this specific PR, what was failing in the doc build?

I never found out.  AFAICT it was unrelated and eventually re-pushing solved it.

**Comment by jorisvandenbossche** [comment]
> But @jbrockmendel, for this specific PR, what was failing in the doc build? (I only see a failure to checkout in the pipeline)

As far as I looked, the doc build actually didn't fail. It was the checkout phase of the the action that failed

**Comment by jbrockmendel** [comment]
> As far as I looked, the doc build actually didn't fail. It was the checkout phase of the the action that failed

Looking in the logs I see the same thing, maybe past-me intended to ask about this on a different PR.

**Pull request merged**
