### PR TITLE
Blacken the code base

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
So we can see what it looks like

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@TomAugspurger a question we are having here at the sprint, is that if you add it as a pre-commit hook, does it run black on the full code base (as that takes a while for pandas) ?

**Comment by TomAugspurger** [comment]
Nope it's just the changed files.

**Comment by jorisvandenbossche** [comment]
The test with 79 limit added around 20,000 lines

**Comment by TomAugspurger** [comment]
@simonjayhawkins is the black default of 88 too wide?

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins is the black default of 88 too wide?

I'm happy to go with the black default and see how it goes, if nobody else is objecting strongly.

> The test with 79 limit added around 20,000 lines

maybe too much nested code!

**Comment by jreback** [comment]
@jorisvandenbossche should prob merge this right after the RC is cut

**Comment by WillAyd** [comment]
Would we consider doing it before? Seems like we’d get better test coverage of it if cut with the initial RC

**Comment by jreback** [comment]
@jorisvandenbossche sorry just merged the last 2 PRs

**Comment by jorisvandenbossche** [comment]
No problem, the main work here was updating the fixup commits and checking they are still fine for flake8 / isort. Once we actually put it in, I can just cherry-pick them on top of the latest blackened one.

**Comment by jorisvandenbossche** [comment]
Do we want to do this now? (after the RC is fine for me as well) @TomAugspurger are you still planning to tag tonight?

**Comment by jreback** [comment]
cool, I would say fix this up and let's push it in!

**Comment by TomAugspurger** [comment]
Up, fine with doing this now.

**Comment by jorisvandenbossche** [comment]
Do we also want to blacken the asv benchmarks ? (currently I only did the actual pandas package)

Re-applying it now

**Comment by jreback** [comment]
i think blacken everything as we flake everything

**Comment by TomAugspurger** [comment]
@jorisvandenbossche fixed the conflicts, reformatted, and fixed the lint errors in https://github.com/pandas-dev/pandas/runs/161581700

**Comment by jorisvandenbossche** [comment]
Ah, sorry, have them locally as well. Did you also fix the test_validate_docstrings error? That I am doing now (and also ran black on the full repo instead of only on /pandas)

**Comment by TomAugspurger** [comment]
Ah, sorry. I missed the validate_docstrings one.

Feel free to force push.

**Comment by TomAugspurger** [comment]
```diff
 class TimedeltaConstructor:
diff --git a/pandas/core/indexes/datetimelike.py b/pandas/core/indexes/datetimelike.py
index f2e6f631ae9..731ab9c4163 100644
--- a/pandas/core/indexes/datetimelike.py
+++ b/pandas/core/indexes/datetimelike.py
@@ -73,14 +73,14 @@ class DatetimeIndexOpsMixin(ExtensionOpsMixin):
     # properties there.  They can be made into cache_readonly for Index
     # subclasses bc they are immutable
     inferred_freq = cache_readonly(
-        DatetimeLikeArrayMixin.inferred_freq.fget
-    )  # type: ignore
+        DatetimeLikeArrayMixin.inferred_freq.fget  # type: ignore
+    )
     _isnan = cache_readonly(DatetimeLikeArrayMixin._isnan.fget)  # type: ignore
     hasnans = cache_readonly(DatetimeLikeArrayMixin._hasnans.fget)  # type: ignore
     _hasnans = hasnans  # for index / array -agnostic code
     _resolution = cache_readonly(
-        DatetimeLikeArrayMixin._resolution.fget
-    )  # type: ignore
+        DatetimeLikeArrayMixin._resolution.fget  # type: ignore
+    )
     resolution = cache_readonly(DatetimeLikeArrayMixin.resolution.fget)  # type: ignore
 
     _maybe_mask_results = ea_passthrough(DatetimeLikeArrayMixin._maybe_mask_results)
```

seemed to fix the typing issue.

**Comment by jorisvandenbossche** [comment]
BTW, are you OK with re-enabling the flake8 check for whitespace after comma? I first put that in the exclude list, as black can generate that (eg in `df.loc[1,]` instead of `df.loc[, ]`). But, for the docs + docstrings, it is nice to keep that flake8 check strict. 
In the code that black formats, it is only on a few lines that I need to add a `noqa` to have flake8 pass

**Comment by jorisvandenbossche** [comment]
Up to now I kept separate commits for updating CI, the actual reformatting, and some fix-ups (because it made re-applying easier). Do we want to keep those separate when merging to keep the automated changes in a separate commit? (or it might be fine to have the separate commits here in the PR)

**Comment by TomAugspurger** [comment]
Multiple commits (rebase and merge) seems fine.

**Comment by TomAugspurger** [comment]
@jorisvandenbossche all green.

**Comment by jorisvandenbossche** [comment]
I just rebased to update the commit titles and to combine the last two fixup commits (so they should be fine to rebase/merge). They should still be exactly the same content, so relying on green CI of the previous push.

**Comment by TomAugspurger** [comment]
Thanks! I'll need to give a bottle before pushing the tag. I'll check the
build on master when it finishes.

**Pull request merged**
