### PR TITLE
Inconsistent index between plain DataFrame and read_sql DataFrame

### LINKED ISSUE #47608: BUG: inconsistent index between plain DataFrame and read_sql DataFrame
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import sqlite3

conn = sqlite3.connect(":memory:")

cur = conn.cursor()
cur.execute("CREATE TABLE data (id int, val real)")
cur.execute("INSERT INTO data VALUES (1, 150.0), (2, 160.0)")
conn.commit()

full_df = pd.DataFrame({"id": [1, 2], "val": [150.0, 160.0]})
full_sql_df = pd.read_sql("SELECT * FROM data", conn)

empty_df = pd.DataFrame({"id": [], "val": []})
empty_sql_df = pd.read_sql("SELECT * FROM data WHERE (1 = 0)", conn)

pd.testing.assert_frame_equal(full_df, full_sql_df)
pd.testing.assert_frame_equal(empty_df, empty_sql_df)
```

### Issue Description

The empty DataFrame returned from read_sql has a different index type than if one constructs an empty DataFrame directly. When the returned SQL frame is not empty, the index types match.

### Expected Behavior

The returned empty SQL DataFrame's index is also a `RangeIndex(start=0, end=0, step=1)`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252
pandas           : 1.4.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 58.2.0
pip              : 21.3
Cython           : None
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>

### PR DESCRIPTION
**Pull request by weikhor**
- [ ] closes #47608 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
Would be good to have the sql smoke test from the original issue as well.

**Review by phofl — COMMENTED** [review]
Do we want this? This seems to be deliberate.

I think the if isn't needed at all, if we want a RangeIndex?

**Review by phofl — CHANGES_REQUESTED** [review]
I am -1 on this change without deprecation and -0 on this change in general.

```
data = {1: ["foo"], 2: ["bar"]}
exp = DataFrame(data, columns=["a", "b"])
```

```
DataFrame()
```

These operations create regular Index objects, not a RangeIndex, this change would cause inconsistencies. 

You can also see this on the number of tests you had to change for this

**Comment by weikhor** [comment]
ok. I try to use search other method.

**Comment by weikhor** [comment]
Hi @phofl 
1)
```
data = {"a": [], "b": []}
exp = pd.DataFrame(data, columns=["a", "b"])
print(exp)
print(exp.index)
```
```
Empty DataFrame
Columns: [a, b]
Index: []
RangeIndex(start=0, stop=0, step=1)
```
2)
```
data = {1: ["foo"], 2: ["bar"]}
exp = pd.DataFrame(data, columns=["a", "b"])
print(exp)
print(exp.index)
```
```
Empty DataFrame
Columns: [a, b]
Index: []
Index([], dtype='object')
```

On current main branch, index type created is not same. Is this expected?

**Comment by phofl** [comment]
Can you create an overview of all possible cases and then add it to the issue? We should aim for consistency if we make a change

**Comment by weikhor** [comment]
Hi @phofl  Possible cases of empty dataframe is as follow. I based on documentation  
```
class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)

Parameters
    data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
           Dict can contain Series, arrays, constants, dataclass or list-like objects. If data is a dict, column order follows insertion- 
           order. If a dict contains Series which have an index defined, it is aligned by its index.
```
1. Iterable
```
data = []
df = pd.DataFrame(data, columns=["A", "B"])
print(df.index)

Index([], dtype='object')
```
2. Dict

a) using series
```

data = {'a': pd.Series([]), 'B': pd.Series([])}
df = pd.DataFrame(data, columns=["A", "B"])
print(df.index)

RangeIndex(start=0, stop=0, step=1)
```
b) using list
```
data = {"A": [], "B": []}
df = pd.DataFrame(data)
print(df.index)

RangeIndex(start=0, stop=0, step=1)
```
c) using array
```
data = {'A': np.array([]), 'B': np.array([])}
df = pd.DataFrame(data)
print(df.index)
```
d) based on columns
```
data = {1: ["foo"], 2: ["bar"]}
df = pd.DataFrame(data, columns=["A", "B"])
print(df.index)

Index([], dtype='object')
```

4. Read csv
```
df = pd.read_csv("empty.csv")
print(df.index)

Index([], dtype='object')
```

**Comment by weikhor** [comment]
Based on https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html, 
```
index  : Index or array-like
         Index to use for resulting frame. Will default to RangeIndex if no indexing information part of input data and no index 
         provided.
```

**Comment by mroeschke** [comment]
Thanks for your investigation so far @weikhor! I think your findings also intersect with https://github.com/pandas-dev/pandas/issues/47959 so would be good to document your findings there as well.

I think this topic needs more discussion in the issues before moving forward with a fix, so closing. But thanks for your effort here so far.

**Pull request closed without merging**
