### PR TITLE
Standardize cast_str behavior in all datetimelike fill_value validators

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

This will in turn allow us to simplify/de-duplicate a bunch of code since we now pass cast_str in all cases.

### CODE REVIEW

**Comment by jreback** [comment]
can you actually just remove this parameter entirely now? (e.g. its always true), or other cases?

**Comment by jbrockmendel** [comment]
> can you actually just remove this parameter entirely now? (e.g. its always true), or other cases?

yes, planned for the next pr

**Comment by jbrockmendel** [comment]
actually, since i need to rebase anyway, might as well now

**Comment by jreback** [comment]
lgtm ping on green

**Comment by jbrockmendel** [comment]
ping

**Comment by jbrockmendel** [comment]
@jreback gentle ping; this is a blocker for long-awaited code de-duplication

**Pull request merged**
