### PR TITLE
BUG: do not hard-code matplotlib backend for boxplot

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by datapythonista** [comment]
This was implemented in #27432, and was intentional. My preference was to delegate everything to the backends, but the final decision was to just delegate the plots called via accessor.

I'm happy with changing it for boxplot, even if I'd personally deprecate `DataFrame.boxplot()` in favor of `DataFrame.plot(kind='box')`.

@TomAugspurger thoughts on this change?

**Comment by datapythonista** [comment]
My understanding is that there are these ways of calling a boxplot from pandas:
```python
df.plot.box()
df.plot(kind='box')
df.boxplot()
pandas.plotting.boxplot(df)
```
The decision was to delegate to the backend anything that is not a `Series` or `DataFrame` method. In this case the 4 cases are implemented in `_core.py`, but the last one is the only that doesn't delegate.

I think we can merge this if it affects you. Otherwise I'd say better don't touch it, and focus on deprecating it. There was an initial discussion on deprecations in #26747, but the scope of the issue was too big and no decision was made on that. I guess deprecating `df.hist()` and `df.boxplot()` is controversial, but I guess people there will be agreement on `pandas.plotting.boxplot`.

I'll try to open an issue later today to make a decision on that.

**Comment by datapythonista** [comment]
> Makes sense – so from the contents of this file it appears that plotting backends can override `pandas.plotting.hist_series`, `pandas.plotting.hist_frame`, `pandas.plotting.boxplot_frame`, and `pandas.plotting.boxplot_frame_groupby`, but not `pandas.plotting.boxplot`. Was that your intent?

`pandas.plotting.hist_series`... are not expected to be called directly afaik, there are just the functions that are called when `Series.hist()`... are called.

There are many things in the current API that I think are explained by how things were implemented, and that are inconsistent. That's why I mentioned that I think what we should do is have a discussion on what to deprecate, and leave things simple, standardized and without inconsistencies.

Let's see what can be done, I think once there is agreement in what should be done, should be fast to implement the changes.

**Comment by datapythonista** [comment]
I think you're right for `Series.plot.hist()`, but not for `Series.hist()`. See here: https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L4804

It's confusing, that's exactly why I think we should deprecate `Series.hist` (or just make an alias for `Series.plot.hist`, but I think alias also cause confusion).

**Comment by datapythonista** [comment]
If you want users to be able to plot with your backend when calling `Series.hist()`... you should implement them. I'd just call `plot(kind='hist')` there. I think there are subtle differences among the two, but we should take care of those in our end.

Making you implement those is not great, sorry. They won't be needed in the future, I think. But for now this is how the API works.

**Review by WillAyd — APPROVED** [review]
Not my area of expertise but lgtm to keep consistent. @datapythonista

**Comment by jakevdp** [comment]
I'm going to close this, because the discussion is larger than the files I've touched here.

**Pull request closed without merging**
