### PR TITLE
TST: match matplotlib warning message

### PR DESCRIPTION
**Pull request by ivanovmg**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Follow up on #36982.
Since, currently ``assert_produces_warning`` now allows matching warning message,
instead of the comment we will match the message.

### CODE REVIEW

**Review by charlesdong1991 — APPROVED** [review]
very nice!

**Comment by MarcoGorelli** [comment]
Nice!

Not a blocker, but why not match the entire message?
```python
        msg = (
            "To output multiple subplots, the figure containing "
            "the passed axes is being cleared"
        )
```

**Comment by ivanovmg** [comment]
> 
> 
> Nice!
> 
> Not a blocker, but why not match the entire message?
> 
> ```python
>         msg = (
>             "To output multiple subplots, the figure containing "
>             "the passed axes is being cleared"
>         )
> ```

I did that to have a slight immunity to minor modifications of the warning message by matplotlib team, just in case.
This concerns only the second part of the message, so it may not be fully justifiable.
Anyway, I will update to the full message.

**Comment by ivanovmg** [comment]
It is greenish since there are some internal CI errors. All relevant tests seem to pass successfully.

**Comment by MarcoGorelli** [comment]
Thanks @ivanovmg !

**Pull request merged**
