### PR TITLE
BUG: DTA/TDA incorrectly accepting iNaT for setitem

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

First of several related PRs.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@TomAugspurger the Travis failure here seems to be affecting everything.  The traceback looks like its somewhere in xdist or pytest.  Didn't we recently deal with something really similar?

**Comment by TomAugspurger** [comment]
Yeah, I think pytest 5.x is incompatible with pytest-xdist<=1.28

pytest                    5.0.1                    py36_0
pytest-forked             1.0.2                    py36_0
pytest-mock               1.10.4                   py36_0
pytest-xdist              1.28.0                     py_0


So probably bump pytest-xdist>=1.29 in this env if possible.

**Comment by jbrockmendel** [comment]
green

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks

**Pull request merged**
