### PR TITLE
CLN: Cython warnings for type declartions

### PR DESCRIPTION
**Pull request by alimcmaster1**
```
warning: pandas/_libs/internals.pyx:144:29: Strings should no longer be used for type declarations. Use 'cython.int' etc. directly.
warning: pandas/_libs/internals.pyx:147:32: Strings should no longer be used for type declarations. Use 'cython.int' etc. directly.
warning: pandas/_libs/internals.pyx:188:28: Strings should no longer be used for type declarations. Use 'cython.int' etc. directly.
```
(Against cython master)

### CODE REVIEW

**Comment by WillAyd** [comment]
Can you merge master again; doesn't look like all the checks have run. Chance this might not work with Py36 but will see in CI (maybe PEP 563 is a pre-cursor)

**Comment by alimcmaster1** [comment]
@WillAyd thanks - all checks have run now

**Comment by WillAyd** [comment]
lgtm. I suppose this differs slightly from Python annotation requirements before PEP 563 was implemented but I don't have any objection unless @scoder knows any better

**Comment by scoder** [comment]
Hmm … yeah, that's PEP-563. I think it's really best to move forward with this and use real types in annotations instead of string names.

**Comment by jreback** [comment]
thanks @alimcmaster1

**Pull request merged**
