### PR TITLE
ENH: StringMethods supports is_xxx methods

### PR DESCRIPTION
**Pull request by sinhrks**
Derived from #9111.

Add following methods to be compat with standard `str`.
- StringMethods.isalnum
- StringMethods.isalpha
- StringMethods.isdigit
- StringMethods.isspace
- StringMethods.islower
- StringMethods.isupper
- StringMethods.istitle

### CODE REVIEW

**Comment by jreback** [comment]
since these functions are quite similar. can you change impl to use a function generator to create these? (with the appropriate doc strings)

**Comment by sinhrks** [comment]
Right, how about this?

**Comment by jreback** [comment]
looks good. can you add the methods here as well?

http://pandas.pydata.org/pandas-docs/stable/text.html#method-summary (maybe we want to auto-generate this as well from the StringMethods?)

**Comment by sinhrks** [comment]
@jreback Sure. Did it.

**Comment by jreback** [comment]
this needs to go after #9233 (and might need a rebase after that) as the docs are changing a bit)

**Comment by sinhrks** [comment]
OK, rebased.

**Comment by jreback** [comment]
thanks @sinhrks

**Pull request merged**
