### PR TITLE
DOC: 0.24.1 whatsnew

### PR DESCRIPTION
**Pull request by TomAugspurger**
This PR has the documentation changes that are just for 0.24.x. I'll have another PR later with changes to 0.24.1.rst that should go to master first, before being backported.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Hmm, this is a bit the disadvantage of having the bugfix releases on separate pages, as it would be nice to keep pointing users to the more relevant 0.24.0 whatsnew docs?

**Comment by jorisvandenbossche** [comment]
Or maybe explicitly link to that the 0.24.0 docs in the 0.24.1 release notes

**Comment by jreback** [comment]
alternative, we *could* simply insert the changed *into* the 0.24.0 docs with an annotation, maybe [0.24.1] next to it?

**Comment by TomAugspurger** [comment]
Keep in mind that when you're on http://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html, you see all the previous releases in the TOC-tree. So you can easily access them already.

Good to merge?

**Comment by jreback** [comment]
lgtm.

**Pull request merged**
