### PR TITLE
TST: parametrize in tests/plotting/test_frame.py

### PR DESCRIPTION
**Pull request by ivanovmg**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Parametrize some tests in ``pandas/tests/plotting/test_frame.py``.

### CODE REVIEW

**Review by charlesdong1991 — APPROVED** [review]
very nice! 

it seems two jobs just got stuck, i rerun it and hopefully ci jobs can be finished this time.

**Comment by jreback** [comment]
very nice!

**Comment by jreback** [comment]
@ivanovmg if you wouldn't mind can you mark most of these parameterized tests as slow. we are timing out are builds pretty offten: https://travis-ci.org/github/pandas-dev/pandas/jobs/745534073

and its taking like 45min. i don't think in and of themselves these tests are slow, but they do take some time.  the slow builds have more room these tests.

**Comment by ivanovmg** [comment]
> 
> 
> @ivanovmg if you wouldn't mind can you mark most of these parameterized tests as slow. we are timing out are builds pretty offten: https://travis-ci.org/github/pandas-dev/pandas/jobs/745534073
> 
> and its taking like 45min. i don't think in and of themselves these tests are slow, but they do take some time. the slow builds have more room these tests.

Sure, I will go through it and mark the slowish tests as slow.

**Comment by jreback** [comment]
> > @ivanovmg if you wouldn't mind can you mark most of these parameterized tests as slow. we are timing out are builds pretty offten: https://travis-ci.org/github/pandas-dev/pandas/jobs/745534073
> > and its taking like 45min. i don't think in and of themselves these tests are slow, but they do take some time. the slow builds have more room these tests.
> 
> Sure, I will go through it and mark the slowish tests as slow.

great. likley let's mark most / all of them. the fast builds are just taking too long and timing out.

**Pull request merged**
