### PR TITLE
DEPR: pandas.stats.var, pandas.stats.plm, pandas.stats.ols, pandas.stats.fama_macbeth

### LINKED ISSUE #6077: MIGRATE: move stats code to statsmodels / deprecate in pandas
related #5884

- [ ] OLS https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/linear_model.py
- [ ] plm (regression for panels)
- [ ] fama_macbeth
- [ ] VAR https://github.com/statsmodels/statsmodels/tree/master/statsmodels/tsa/vector_ar

### PR DESCRIPTION
**Pull request by jreback**
closes #6077 

this cleans ups the remainder of the `pandas.stats` modules

we are directing:
- `OLS` -> `http://statsmodels.sourceforge.net/stable/regression.html`
- `PanelOLS/MovingOLS/PooledOLS` to `http://statsmodels.sourceforge.net/stable/mixed_linear.html`
- `VAR` to `http://statsmodels.sourceforge.net/stable/vector_ar.html#var`
- `fama_macbeth` to `http://statsmodels.sourceforge.net/stable/index.html` (as not implemented in statsmodell, but good place to start)

### CODE REVIEW

**Comment by jreback** [comment]
cc @jseabold 
cc @josef-pkt

looks reasonable?

**Comment by josef-pkt** [comment]
looks fine to me (without checking details)

Hopefully the deprecation warnings induce some users to help, at least with missing API and testing.
I can check panel models (missing conveniences for fixed effects handling) and move FamaMacBeth (given the example and test case in the issue) in late winter or spring.

I don't know if there is anything directly to do about expanding and rolling OLS or whether it's handled by just a call to the general pandas methods. (I haven't looked at that in years.)

**Comment by jreback** [comment]
thanks @josef-pkt 

yeah meant to deprecate these a while ago.

**Comment by jorisvandenbossche** [comment]
+1 !

**Pull request merged**
