### PR TITLE
CLN: typing/mypy cleanup: Small fixes to make stubgen happy

### PR DESCRIPTION
**Pull request by Naddiseo**
No code changes, just moved a few comments, and fixed a few broken types.

This patch allows stubgen to run over the pandas codebase without generating errors

### CODE REVIEW

**Comment by WillAyd** [comment]
Hmm thanks. So our next minor release drops support for Py27 so maybe time to convert these into 3.X compatible hints? @jreback @TomAugspurger

**Comment by TomAugspurger** [comment]
We'll need to talk a bit about that (maybe on the call tomorrow). Someone will need to look into whether we're using things from typing that are 3.6+.

**Comment by WillAyd** [comment]
Cool - makes sense as a conversation piece tomorrow. The only one that I *think* would be very useful from 3.6 would be the Collections type, though I admittedly don't have a ton of experience with hints. 

In any case I still think those in this PR should be converted to the 3.X syntax

**Comment by jreback** [comment]
@Naddiseo I think it would be worthile adding what you are running into code_checks.sh (maybe separate test) to avoid regressions here.

**Comment by TomAugspurger** [comment]
We'll leave that as a subtask for #25601.

Thanks @Naddiseo!

I'm curious @Naddiseo, what was your motivation for this PR? We're going to start adding type hints to the codebase when we make master python-3 only compatible (next week probably). If you have experience with typing, your input would be appreciated in #25601.

**Comment by Naddiseo** [comment]
@TomAugspurger, I've found that a large number of the bugs in our code at $work could have been prevented if it had correct typing, so I'm slowly moving our code base to have more typing. A coworker of mine has recently started a ML sub-project that's integrated with my code, however I don't have a lot of experience with pandas/ML (maths/stats isn't my strong suit), so naturally I want to make sure I don't accidentally break my coworkers code because of not knowing the type of a variable. That led me to look for types for pandas/numpy, and not finding any for pandas, decided to use stubgen and subsequently finding the the issues addressed in this PR.

**Pull request merged**
