### PR TITLE
CLN: Removed unnecessary variable call

### LINKED ISSUE #34934: BUG: unnecessary repetition of variable in explode test
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

In the test `test_typical_usecase` in `series/methods/test_explode.py` there's 

```python
def test_typical_usecase():

    df = pd.DataFrame(
        [{"var1": "a,b,c", "var2": 1}, {"var1": "d,e,f", "var2": 2}],
        columns=["var1", "var2"],
    )
    exploded = df.var1.str.split(",").explode()
    exploded
    result = df[["var2"]].join(exploded)
    expected = pd.DataFrame(
        {"var2": [1, 1, 1, 2, 2, 2], "var1": list("abcdef")},
        columns=["var2", "var1"],
        index=[0, 0, 0, 1, 1, 1],
    )
    tm.assert_frame_equal(result, expected)
```

#### Problem description

The variable `exploded` is called unnecessary.

### PR DESCRIPTION
**Pull request by erfannariman**
- [x] closes #34934
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Can you prepend `CLN` to the pull request title?

**Comment by erfannariman** [comment]
> Can you prepend `CLN` to the pull request title?

Yes done, just for my learning, why are we doing that?

**Comment by MarcoGorelli** [comment]
> > Can you prepend `CLN` to the pull request title?
> 
> Yes done, just for my learning, why are we doing that?

It's just to make it clear what a PR does (e.g. this one cleans up some code)

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
