### PR TITLE
TST/REF: split io/parsers/test_common into multiple files

### PR DESCRIPTION
**Pull request by arw2019**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Another precursor to #38370

### CODE REVIEW

**Comment by arw2019** [comment]
On this branch:
```
(pandas-dev) andrewwieteska@Andrews-MacBook-Pro pandas % pytest pandas/tests/io/parser/common/
============================================================= test session starts =============================================================
platform darwin -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/andrewwieteska/repos/pandas, configfile: setup.cfg
plugins: forked-1.2.0, xdist-2.1.0, cov-2.10.1, asyncio-0.14.0, hypothesis-5.41.2, instafail-0.4.1
collected 646 items                                                                                                                           

pandas/tests/io/parser/common/test_chunksize.py .......................................XXX............                                  [  8%]
pandas/tests/io/parser/common/test_common_basic.py ................s................................................................... [ 21%]
........................................................................................                                                [ 34%]
pandas/tests/io/parser/common/test_data_list.py ............                                                                            [ 36%]
pandas/tests/io/parser/common/test_decimal.py .........                                                                                 [ 38%]
pandas/tests/io/parser/common/test_file_buffer_url.py ................................................................................. [ 50%]
................................................                                                                                        [ 58%]
pandas/tests/io/parser/common/test_float.py .............................................                                               [ 65%]
pandas/tests/io/parser/common/test_index.py ................................................                                            [ 72%]
pandas/tests/io/parser/common/test_inf.py ...............                                                                               [ 74%]
pandas/tests/io/parser/common/test_ints.py ............................................................                                 [ 84%]
pandas/tests/io/parser/common/test_iterator.py .....................                                                                    [ 87%]
pandas/tests/io/parser/common/test_read_errors.py ...........................................................................           [ 99%]
pandas/tests/io/parser/common/test_verbose.py ......                                                                                    [100%]

================================================= 642 passed, 1 skipped, 3 xpassed in 21.19s ==================================================
```
On master:
```
(pandas-dev) andrewwieteska@Andrews-MacBook-Pro pandas % pytest pandas/tests/io/parser/test_common.py 
============================================================= test session starts =============================================================
platform darwin -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/andrewwieteska/repos/pandas, configfile: setup.cfg
plugins: forked-1.2.0, xdist-2.1.0, cov-2.10.1, asyncio-0.14.0, hypothesis-5.41.2, instafail-0.4.1
collected 646 items                                                                                                                           

pandas/tests/io/parser/test_common.py ..................................s.............................................................. [ 15%]
........................................................................................................................XXX............ [ 35%]
....................................................................................................................................... [ 56%]
....................................................................................................................................... [ 77%]
....................................................................................................................................... [ 98%]
.........                                                                                                                               [100%]

================================================= 642 passed, 1 skipped, 3 xpassed in 21.49s ==================================================
```

**Comment by jreback** [comment]
@arw2019 can you merge master once more to make sure recent merges didn't mess this up. ping on green.

**Comment by arw2019** [comment]
Green

**Comment by jreback** [comment]
thanks

**Pull request merged**
