### PR TITLE
TYP: timedeltas.pyi

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

@simonjayhawkins mypy is unhappy about `Timedelta.__new__` potentially returning `NaT`.  Thoughts on how to handle this?  (it'll come up again in Timestamp and Period)

```
pandas/_libs/tslibs/timedeltas.pyi:51: error: "__new__" must return a class instance (got "Union[Timedelta, NaTType]")  [misc]
```

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@simonjayhawkins im pretty sure this is non-actionable based on what I read in python/mypy#1020, but would like your say-so before mothballing this

**Comment by simonjayhawkins** [comment]
yes. looks tricky. I would add ignores for now since imo the benefit of the added types outweighs the extra ignores.

**Review by simonjayhawkins — COMMENTED** [review]
I guess we need some lint checks on the stubs.

**Comment by jbrockmendel** [comment]
updated per comments

**Pull request merged**
