### PR TITLE
DEBUG: Debug failing macpython wheels

### PR DESCRIPTION
**Pull request by phofl**
might be because of a change in hypothesis

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@phofl i've closed the nightly build issue. We may need an issue to unpin hypothesis if this PR gets closed.

**Comment by phofl** [comment]
Yeah we  should probably open a new issue. Here or in the MacPython repo?

**Comment by simonjayhawkins** [comment]
it does need to get unpinned in MacPython eventually, but there is not much visibility there, so an issue in pandas would be better. Do we know why we didn't see the same failures on pandas ci?

**Comment by mroeschke** [comment]
If this was an issue in `test_round_sanity` as suggested in https://github.com/pandas-dev/pandas/issues/47933#issuecomment-1205909274, we did xfail(strict=False) this test in https://github.com/pandas-dev/pandas/pull/47803

**Review by Blessed4eva — APPROVED** [review]

**Comment by mroeschke** [comment]
Still needed?

**Comment by phofl** [comment]
Opened an issue, can close here

**Pull request closed without merging**
