### PR TITLE
Backport PR #25262 on branch 0.24.x (REF/TST: resample/test_base.py)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #25262: REF/TST: resample/test_base.py

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@TomAugspurger why does this need to be backported? For the collection problems?

**Comment by TomAugspurger** [comment]
Yeah. But if we decide to keep 0.24.x pinned at the older pytest, then this
is unnecessary.

**Comment by simonjayhawkins** [comment]
@TomAugspurger : if this does solve the collection problem, we can close #25197.

**Comment by jreback** [comment]
is this mergable or should close?

**Comment by jreback** [comment]
let's see if this works

**Pull request merged**
