### PR TITLE
TYP: fix hashable keys for pd.concat

### PR DESCRIPTION
**Pull request by twoertwein**
Could use `Any` but I think in this case the covariant `TypeVar` approach isn't ugly (I think so - happy to change to `Any`).

### CODE REVIEW

**Review by Dr-Irv — APPROVED** [review]
I'm still wary about using `HashableT` as a key in `Mapping`, but I can't find a case where it doesn't work.

**Comment by twoertwein** [comment]
> I'm still wary about using `HashableT` as a key in `Mapping`, but I can't find a case where it doesn't work.

Was about to change it to `Any` but then mypy seems to complain about overlapping overloads (either something wrong with my setup or a mypy bug?)

> pandas/core/reshape/concat.py:65: error: Overloaded function signatures 1 and 2 overlap with incompatible return types  [misc]

**Comment by Dr-Irv** [comment]
> Was about to change it to `Any` but then mypy seems to complain about overlapping overloads (either something wrong with my setup or a mypy bug?)

It's neither.  The issue here is that `Mapping[Any, DataFrame]` intersects  `Iterable[Series]` .  Something that matches `Mapping[Series, DataFrame]` also matches `Iterable[Series]`  and `Mapping[Any, DataFrame]` , so you get the overlapping return types because there is an intersection in the type of the `objs` parameter.

**Comment by twoertwein** [comment]
Thank you for finding this @Dr-Irv! I guess it works with TypeVars because Series/DataFrame are not Hashable.

**Pull request merged**
