### PR TITLE
STYLE fix: pylint "consider-using-from"

### PR DESCRIPTION
**Pull request by fabinca**
Refers to one of the issues in https://github.com/pandas-dev/pandas/issues/48855

- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

- [x] Fixed imports triggering pylints "consider using from" message

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
not sure the merge conflict was quite resolved right, there's now an empty file `pandas/io/excel/_xlwt.py`, could you remove it please?

**Review by MarcoGorelli — APPROVED** [review]
Looks good to me pending green, thanks @fabinca !

**Review by MarcoGorelli — APPROVED** [review]
Looks good to me pending green, thanks @fabinca !

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Awesome, thanks @fabinca

**Pull request merged**
