### PR TITLE
CI autofix_prs: false for pre-commit.ci

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Somehow, this autoupdate job doesn't trigger all the workflows. I don't know why, because [the same workflow in PyMC3](https://github.com/pymc-devs/pymc3/pull/4466) works just fine.

From [this action's README](https://github.com/technote-space/create-pr-action), all the actions have commit email and commit name set - setting them is all I can think to try at the moment. @afeld any ideas? Maybe there's a different workflow that should be used instead?

### CODE REVIEW

**Comment by afeld** [comment]
Sorry for the slow response. The difference between pandas (e.g. https://github.com/pandas-dev/pandas/pull/40439) and pymc3 (e.g. https://github.com/pymc-devs/pymc3/pull/4466) is that the former is sending the pull request from @github-actions. [More info, with workaround.](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)

**Comment by MarcoGorelli** [comment]
Thanks @afeld , that's useful! I'll get back to this

**Comment by MarcoGorelli** [comment]
@jreback shall we try making a new token? I'll paste the instructions I sent one of the PyMC3 maintainer, as it worked for them (though we may have to choose a new name instead of ACTION_TRIGGER_TOKEN)

---

1. click 'Settings' on your profile icon:

image

2. click 'developer settings'

image

3. select 'personal access tokens', and then 'generate new token'

image

4. call it 'ACTION_TRIGGER_TOKEN' and then check the 'repo' checkbox

image

5. you'll see a token generated. copy it to the clipboard

image

6. go to the pandas-dev/pandas repo, and go to 'settings'

image

7. click 'secrets' and then 'new repository secret'

image

8. name it ACTION_TRIGGER_TOKEN, and paste the value you copied in step 5 in value. Then, 'add secret' and that should be everything 

image

**Comment by MarcoGorelli** [comment]
I've repurposed this to set `autofix_prs: false` in the settings for [pre-commit.ci](https://pre-commit.ci/) - if we enable it then we can get rid of .github/workflows/comment_bot.yml, .github/workflows/autoupdate-pre-commit-config.yml, and .github/workflows/pre-commit.yml

**Comment by jreback** [comment]
> I've repurposed this to set `autofix_prs: false` in the settings for [pre-commit.ci](https://pre-commit.ci/) - if we enable it then we can get rid of .github/workflows/comment_bot.yml, .github/workflows/autoupdate-pre-commit-config.yml, and .github/workflows/pre-commit.yml

sounds good

**Comment by MarcoGorelli** [comment]
Awesome - @jreback do you want to re-enable pre-commit-ci then? It should be in settings -> integrations

**Pull request merged**
