### PR TITLE
TST: Add hex color strings test

### LINKED ISSUE #10299: Cannot use hex strings or named matplotlib colors with DataFrame.plot
I was going to put this on SO but I think it might belong here instead:

I have a pandas DataFrame where I want to plot each column as a line with the same color. This might sound useless but I am showing groups of lines from certain selections of the DataFrame. The only problem is it appears that the `DataFrame.plot` method does not accept any matplotlib hex strings or named colors in the color kwarg.

A trivial example:

    pd.DataFrame([range(10),range(10)]).plot(color='#008000')

gives a blank subplot with no errors, however, 

    pd.DataFrame([range(10),range(10)]).plot(color='g')

gives the expected result. To me this seems like a bug considering that `color='g'` works but not its hex string equivalent. The same issue occurs when trying to use a named matplotlib color like `color='lightgray'`. This does however work when using `Series.plot` or `DataFrame.plot` with one column or if a list of hex strings or named colors are given with length equal to the number of columns as in,

    pd.DataFrame([range(10),range(10)]).plot(color=['#008000']*2)

### PR DESCRIPTION
**Pull request by hironow**
It's already resolved. I added hex string color test.

closes #10299

### CODE REVIEW

**Comment by sinhrks** [comment]
Thanks! This looks to be fixed by #9894. 

@TomAugspurger Please merge if it looks OK.

```
df = pd.DataFrame(np.random.randn(5, 5))
custom_colors = ['#FF0000', '#0000FF', '#FFFF00', '#000000', '#FFFFFF']
df.plot(color=custom_colors)
```

**Comment by jreback** [comment]
@hironow pls add a whats new note (bug fxies)

**Comment by hironow** [comment]
Sorry, unexpectedly closed.
I tried to 'git rebase' (and replace this PR's repo) to resolve conflicts, but I deleted this by mistake. 
So, what should I do about this PR?

**Comment by TomAugspurger** [comment]
Does Github show a button for you to restore the branch?

**Comment by hironow** [comment]
@TomAugspurger Thanks for your comment. I restore this branch.
I've created a branch of duplicate name in my own forked repo.

**Comment by sinhrks** [comment]
Thanks for updates. Can you squash to the single commit? You can do it by:

1. Open your local pandas repository
2. ``git checkout master`` to switch to master
3. ``git remote add upstream https://github.com/pydata/pandas.git`` to register original url
4. ``git pull upsream master`` to update your master
5. ``git checkout pyconjp-2015-sprint``
6. ``git rebase -i master`` to apply the master's update to PR branch

Pls feel free to ask me if you have any question.

**Comment by hironow** [comment]
@sinhrks Thanks for your comment and list of git commands.
I probably was able to squash this branch.

**Comment by sinhrks** [comment]
@hironow Thanks!

**Pull request merged**
