### PR TITLE
Fix import format pandas/tests/indexing

### PR DESCRIPTION
**Pull request by amphy**
- [x] xref #23334
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Ran `isort --recursive pandas` and then checked imports using `isort --recursive --check-only pandas`

PR capped at 20 files, but 21 files changed because it includes setup.cfg which has also been changed.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by thoo** [comment]
@amphy Do you have to rerun `isort`? I still have issue travis-ci. And I also saw you had before.

**Comment by amphy** [comment]
@thoo Yeah, I re-ran isort after checking the pandas/tests/indexing directory again with isort and it seems to pass what was giving me trouble earlier with Travis CI (My issue was that I was getting an error from ./ci/code_checks.sh so I ran that locally which revealed that I was getting some errors from isort)

**Comment by thoo** [comment]
@amphy  I looked at your log before and we are getting the same error. I have 3-4 commits with similar errors.  I  think it might be related to rebasing with upstream/master.  Thanks for the reply. Hopefully it will solve.

**Comment by thoo** [comment]
@amphy  Thanks. Mine is fixed too.

**Pull request merged**
