### PR TITLE
Add various display types for pivot table such as Excel

### PR DESCRIPTION
**Pull request by gtnx**
Excel offers several types of values display for a pivot table (ratio of row, ratio of column, ratio of total, difference with, cumulated sum ...)
This ticket aims to implement this option in the pivot table API. I implemented the three types cited above for a start.
I chose "display_value" for the argument name. One can find too generic, so i'm opened to suggestions.

### CODE REVIEW

**Comment by jreback** [comment]
I think this could be better in the cookbook. Closing. But if you want to put an example there would be gr8.

**Comment by gtnx** [comment]
If you want to display values as ratio of column/row/table total like Excel/Calc allows, here's a piece of code which will do the job:

    if display_value == "col_ratio":
        # Display values as a ratio of column total
        table = table.div(table.sum(axis=0), axis=1)
    elif display_value == "row_ratio":
        # Display values as a ratio of row total
        table = table.div(table.sum(axis=1), axis=0)
    elif display_value == "total_ratio":
        # Display values as a ratio of table total
        table = table.div(table.sum().sum())

**Comment by jorisvandenbossche** [comment]
Indeed, I think this would be a nice example to add to the docs.

@gtnx In general, if you want to prevent the fact that we close a PR, it's better to first open an issue asking if such an enhancment would be desired.

**Comment by gtnx** [comment]
You're right. I realized it after i did the dev. I will do that next time

**Pull request closed without merging**
