### PR TITLE
CI: Install moto from conda-forge

### LINKED ISSUE #27161: CI: Install fail for PyYAML
`conda env create -n travis-36-cov --force -f ci/deps/travis-36-cov.yaml `

is failing with

```
Downloading and Extracting Packages
psutil-5.6.2         | 318 KB    | ######################################################################################################################################### | 100%
dask-2.0.0           | 11 KB     | ######################################################################################################################################### | 100%
dask-core-2.0.0      | 576 KB    | ######################################################################################################################################### | 100%
distributed-2.0.1    | 365 KB    | ######################################################################################################################################### | 100%
gcsfs-0.2.3          | 26 KB     | ######################################################################################################################################### | 100%
pytz-2019.1          | 236 KB    | ######################################################################################################################################### | 100%
google-api-core-1.13 | 79 KB     | ######################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/Users/taugspurger/miniconda3/envs/travis-36-cov/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt']
Pip subprocess output:
Collecting brotlipy (from -r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7c/17/365232505a464b27b993f7fed99d235eb0a46a538a470d6d9a4b60b6055d/brotlipy-0.7.0-cp36-cp36m-macosx_10_6_intel.whl
Requirement already up-to-date: coverage in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from -r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 2)) (4.5.3)
Collecting moto (from -r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/68/43/c7afe0bfbd44f8a72981bd96c2c3b159333625e4aef24397a93870346b4d/moto-1.3.9.tar.gz (819kB)
Collecting pandas-datareader (from -r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/cc/5c/ea5b6dcfd0f55c5fb1e37fb45335ec01cceca199b8a79339137f5ed269e0/pandas_datareader-0.7.0-py2.py3-none-any.whl
Requirement already up-to-date: python-dateutil in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from -r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 5)) (2.8.0)
Requirement already satisfied, skipping upgrade: cffi>=1.0.0 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from brotlipy->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 1)) (1.12.3)
Requirement already satisfied, skipping upgrade: Jinja2>=2.10.1 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (2.10.1)
Collecting boto>=2.36.0 (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/23/10/c0b78c27298029e4454a472a1919bde20cb182dab1662cec7f2ca1dcc523/boto-2.49.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: boto3>=1.9.86 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (1.9.162)
Requirement already satisfied, skipping upgrade: botocore>=1.12.86 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (1.12.163)
Requirement already satisfied, skipping upgrade: cryptography>=2.3.0 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (2.7)
Collecting datetime (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/73/22/a5297f3a1f92468cc737f8ce7ba6e5f245fcfafeae810ba37bd1039ea01c/DateTime-4.3-py2.py3-none-any.whl (60kB)
Requirement already satisfied, skipping upgrade: requests>=2.5 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (2.22.0)
Collecting xmltodict (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: six>1.9 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (1.12.0)
Collecting werkzeug (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
Collecting PyYAML==3.13 (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
Requirement already satisfied, skipping upgrade: pytz in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (2019.1)
Collecting python-jose<4.0.0 (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/96/da/c0dcc5e7a98a53440b8db3cf9771345fa696754f79e8734ea59123f7d734/python_jose-3.0.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: mock in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (3.0.5)
Collecting docker>=2.5.1 (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/95/47/5560c9cf0c92b50da24216f0e7733250fbed5a497f69e3c70e1be62143fe/docker-4.0.2-py2.py3-none-any.whl
Collecting jsondiff==1.1.2 (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
Collecting aws-xray-sdk!=0.96,>=0.93 (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/58/f2/79f7918f4ddeec525742ddd4607abe4a82a29a6bc4c7e297995f59a18965/aws_xray_sdk-2.4.2-py2.py3-none-any.whl
Collecting responses>=0.9.0 (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/d1/5a/b887e89925f1de7890ef298a74438371ed4ed29b33def9e6d02dc6036fd8/responses-0.10.6-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (2.8)
Collecting cfn-lint (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/9c/f7/aa8542ab69196d5da1bcfa70845c1767e7a02dd40cd7b396e9f6eeb17584/cfn_lint-0.22.0-py3-none-any.whl (2.5MB)
Collecting sshpubkeys<4.0,>=3.1.0 (from moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/08/96/b5308537f88df326939006a8331a2edc528f25d920c49dbd9fc2c53c4e68/sshpubkeys-3.1.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pandas>=0.19.2 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from pandas-datareader->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 4)) (0.24.2)
Collecting lxml (from pandas-datareader->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/00/c0/9c435597032e43a29af816fb0bee71c3c798635c9da023ea241084e80393/lxml-4.3.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting wrapt (from pandas-datareader->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 4))
Requirement already satisfied, skipping upgrade: pycparser in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from cffi>=1.0.0->brotlipy->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 1)) (2.19)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from Jinja2>=2.10.1->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (1.1.1)
Requirement already satisfied, skipping upgrade: s3transfer<0.3.0,>=0.2.0 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from boto3>=1.9.86->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (0.2.0)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from boto3>=1.9.86->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (0.9.4)
Requirement already satisfied, skipping upgrade: docutils>=0.10 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from botocore>=1.12.86->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (0.14)
Requirement already satisfied, skipping upgrade: urllib3<1.26,>=1.20 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from botocore>=1.12.86->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (1.24.2)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from cryptography>=2.3.0->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (0.24.0)
Collecting zope.interface (from datetime->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/f8/11/0d2c7017ee0014801251470b4ace8590ff6f8acdf431b04e08cdb2661246/zope.interface-4.6.0-cp36-cp36m-macosx_10_6_intel.whl (140kB)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from requests>=2.5->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from requests>=2.5->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (2019.6.16)
Requirement already satisfied, skipping upgrade: rsa in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from python-jose<4.0.0->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (3.4.2)
Collecting ecdsa<1.0 (from python-jose<4.0.0->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/23/a8/8aa68e70959e1287da9154e5164bb8bd5dd7025e41ae54e8d177b8d165c9/ecdsa-0.13.2-py2.py3-none-any.whl
Collecting future<1.0 (from python-jose<4.0.0->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
Collecting websocket-client>=0.32.0 (from docker>=2.5.1->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl
Collecting jsonpickle (from aws-xray-sdk!=0.96,>=0.93->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/07/07/c157520a3ebd166c8c24c6ae0ecae7c3968eb4653ff0e5af369bb82f004d/jsonpickle-1.2-py2.py3-none-any.whl
Collecting jsonpatch (from cfn-lint->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/a0/e6/d50d526ae2218b765ddbdb2dda14d65e19f501ce07410b375bc43ad20b7a/jsonpatch-1.23-py2.py3-none-any.whl
Collecting aws-sam-translator>=1.12.0 (from cfn-lint->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/dd/79/d4eabac6f1c39d2502f241f0473b4854d713d8e745c53ae557476a8027d1/aws-sam-translator-1.12.0.tar.gz (97kB)
Collecting jsonschema~=3.0 (from cfn-lint->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/aa/69/df679dfbdd051568b53c38ec8152a3ab6bc533434fc7ed11ab034bf5e82f/jsonschema-3.0.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: setuptools in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from cfn-lint->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (41.0.1)
Requirement already satisfied, skipping upgrade: numpy>=1.12.0 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from pandas>=0.19.2->pandas-datareader->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 4)) (1.15.4)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from rsa->python-jose<4.0.0->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (0.4.5)
Collecting jsonpointer>=1.9 (from jsonpatch->cfn-lint->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/18/b0/a80d29577c08eea401659254dfaed87f1af45272899e1812d7e01b679bc5/jsonpointer-2.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /Users/taugspurger/miniconda3/envs/travis-36-cov/lib/python3.6/site-packages (from jsonschema~=3.0->cfn-lint->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3)) (19.1.0)
Collecting pyrsistent>=0.14.0 (from jsonschema~=3.0->cfn-lint->moto->-r /Users/taugspurger/sandbox/pandas/ci/deps/condaenv.dhb14niq.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/68/0b/f514e76b4e074386b60cfc6c8c2d75ca615b81e415417ccf3fac80ae0bf6/pyrsistent-0.15.2.tar.gz
Building wheels for collected packages: moto, aws-sam-translator, pyrsistent
  Building wheel for moto (setup.py): started
  Building wheel for moto (setup.py): finished with status 'done'
  Stored in directory: /Users/taugspurger/Library/Caches/pip/wheels/a6/60/88/3c5fb3de8983f06caab8d5343a20a59ca65e4cc0fb3b9d89c3
  Building wheel for aws-sam-translator (setup.py): started
  Building wheel for aws-sam-translator (setup.py): finished with status 'done'
  Stored in directory: /Users/taugspurger/Library/Caches/pip/wheels/dc/c5/93/a32768379da1c365917cfffad512c071639a71d93569924398
  Building wheel for pyrsistent (setup.py): started
  Building wheel for pyrsistent (setup.py): finished with status 'done'
  Stored in directory: /Users/taugspurger/Library/Caches/pip/wheels/6b/b9/15/c8c6a1e095a370e8c3273e65a5c982e5cf355dde16d77502f5
Successfully built moto aws-sam-translator pyrsistent
Installing collected packages: brotlipy, boto, zope.interface, datetime, xmltodict, werkzeug, PyYAML, ecdsa, future, python-jose, websocket-client, docker, jsondiff, jsonpickle, wrapt, aws-xray-sdk, responses, jsonpointer, jsonpatch, pyrsistent, jsonschema, aws-sam-translator, cfn-lint, sshpubkeys, moto, lxml, pandas-datareader
  Found existing installation: PyYAML 5.1

Pip subprocess error:
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

```

Looking into it now.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/27161

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Has anyone seen the CI failures in https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=13760&view=logs&jobId=d6a36677-9147-59f9-684d-001fc5c44c5e&taskId=3c0dbaee-3ff4-52d1-1ed4-1a677fa78d98&lineStart=51&lineEnd=52&colStart=1&colEnd=1

I'll rerun, in case it's a flaky thing.

**Comment by WillAyd** [comment]
I think just started today?

**Review by WillAyd — APPROVED** [review]
lgtm. I can't imagine np 3.5 failures are related

**Comment by TomAugspurger** [comment]
They're unfortunately consistent :/

**Comment by TomAugspurger** [comment]
First failure on master I see is https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=13742

These were maybe touched in https://github.com/pandas-dev/pandas/pull/27106

**Comment by TomAugspurger** [comment]
I can reproduce locally with

```
pytest --count=2 pandas/tests/indexes/multi/test_format.py::test_dtype_str -v -x
```

so some kind of inter-test dependency issue.

**Comment by TomAugspurger** [comment]
Ah of course, because we cache_readonly it. Removing that now.

**Comment by TomAugspurger** [comment]
FYI merging on green.

**Pull request merged**
