### PR TITLE
REF: Assert json roundtrip equal

### LINKED ISSUE #28555: Create helper function in pandas/tests/io/json/test_pandas.py
A lot of the tests in that module repeat the following pattern:

```python
if orient == "records" or orient == "values":
    expected = expected.reset_index(drop=True)
if orient == "values":
    expected.columns = range(len(expected.columns))

assert_frame_equal(result, expected)
```

This is because the `records` and `values` formats intentionally do not completely preserve the axes labels. It would be nice to refactor this into a dedicated helper function (`assert_json_roundtrip_equal`?)

### PR DESCRIPTION
**Pull request by bganglia**
Replaces a some frequently repeated lines with a function.

- [x] closes #28555
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
This is really nice, thanks.  Looks like the linter is finding trailing whitespace that you need to delete

**Review by WillAyd — CHANGES_REQUESTED** [review]
I think `test_roundtrip_intframe` is the one outstanding - can you use this function therein as well? After that lgtm can get this merged - thanks for the PR!

**Comment by bganglia** [comment]
Thank you, yes. I will do that now.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @bganglia nice PR and great first contribution. Would welcome more PRs to tackle other issues!

**Pull request merged**
