### PR TITLE
REF/TST: Add pytest idiom to reshape/test_tile

### PR DESCRIPTION
**Pull request by gfyoung**

### CODE REVIEW

**Comment by jreback** [comment]
can you organize into 3 sections: basic, cut, qcut and either: put each in a class, or just put a section break between (maybe better)?

**Comment by gfyoung** [comment]
> put each in a class

Kind of defeats the purpose of converting to `pytest` idiom 😉 

I actually think we can just break up into two modules (`test_cut` and `test_qcut`).

**Comment by WillAyd** [comment]
> Kind of defeats the purpose of converting to `pytest` idiom 😉

What's the reasoning of that? Plenty of examples on their documentation for using classes to organize; curious where its established as non-idiomatic to use classes

**Comment by jreback** [comment]
@gfyoung we do use classes, though I think i prefer separate files generally. for this case could be either way.

**Comment by gfyoung** [comment]
> What's the reasoning of that? Plenty of examples on their documentation for using classes to organize

@WillAyd : I'm not saying that classes are not idiomatic.  They are just less pytest-idiomatic than functions.  Functional testing is the core feature of `pytest` (vs. something like `unittest`).

In this case, there was not real reason to have OOP overhead for these tests.

**Comment by gfyoung** [comment]
@jreback @WillAyd : I split up the test into two files, which should be a little easier to read.  PTAL.

**Comment by jreback** [comment]
thanks @gfyoung

**Pull request merged**
