### PR TITLE
48779-doc-MonthEnd

### LINKED ISSUE #48779: BUG: pd.offsets.MonthEnd() delevers wrong month
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
ts = pd.Timestamp(2017, 1, 31)
ts + pd.offsets.MonthEnd()
```

### Issue Description

I expect that the answer is: Timestamp('2017-01-31 00:00:00')
but I get: Timestamp('2017-02-28 00:00:00')

### Expected Behavior

Timestamp('2017-01-31 00:00:00')

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Dutch_Netherlands.1252

pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 61.2.0
Cython           : 0.29.28
pytest           : 7.1.1
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : 
sqlalchemy       : 1.4.32
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.20.1
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

### PR DESCRIPTION
**Pull request by natmokval**
- [x] closes #48779
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
As proposed by @MarcoGorelli I updated docs for `MonthEnd` and added one more example to highlight “the last day of the month” behavior.

I checked that build of documentation shows the new description.

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Nice, thanks for working on this!

First, can you check the docstring guide please https://pandas.pydata.org/docs/development/contributing_docstring.html ? Looks like there's a docstring validation error https://github.com/pandas-dev/pandas/actions/runs/3572834601/jobs/6006181203

It might also be good to have an example which uses `n=0`?

**Comment by natmokval** [comment]
Thank you @MarcoGorelli, for your comments and hints. I corrected my docstring and added an example, which uses `n=0`

Unfortunately, my docker environment is broken by absence of visioner.py and I can not validate my changes locally.
If I am not mistaken, visioner.py is missing after recent commit: BLD: use nonvendor versioneer (#49924)

**Comment by MarcoGorelli** [comment]
thanks for updating!

could you try updating your environment? `versioneer` was added to the `environment.yml` file in that PR. I don't know about how it works in the Docker container, but for me `mamba env update -n pandas-dev --file environment.yml` worked

**Comment by WillAyd** [comment]
Assuming you are using the Dockerfile in this repo, a force rebuild of the image should pick up the versioneer dependency

**Comment by natmokval** [comment]
> Assuming you are using the Dockerfile in this repo, a force rebuild of the image should pick up the versioneer dependency

Thank you @WillAyd, I fixed my problem with docker image.

**Comment by natmokval** [comment]
> could you try updating your environment? `versioneer` was added to the `environment.yml` file in that PR. I don't know about how it works in the Docker container, but for me `mamba env update -n pandas-dev --file environment.yml` worked

Thank you, @MarcoGorelli, my environment works well now. I fixed errors in docs for `MonthEnd` and added an example for `n=0`. Docstring validation also requested me to add `See Also` section. I added the reference to `DateOffset`.

I noticed one check during CI failed, but I assume it was caused by timeout and not by my changes.

**Review by MarcoGorelli — APPROVED** [review]
Looks good, thanks @natmokval !

If there's other DateOffsets where similar confusion can arise, PRs to add examples / clarification there too would be welcome

Regarding the "see also" note - this isn't strictly necessary to pass CI, as the codes in 

https://github.com/pandas-dev/pandas/blob/4d0a4365870893e232f639af13fea44c7d3ff9d4/ci/code_checks.sh#L83

are currently checked - but it's nice to have it anyway, thanks!

**Comment by natmokval** [comment]
> If there's other DateOffsets where similar confusion can arise, PRs to add examples / clarification there too would be welcome
> 
Certainly. Checking other DateOffsets looks like a good idea. I will look into it.
> Regarding the "see also" note - this isn't strictly necessary to pass CI, as the codes in
> 
> https://github.com/pandas-dev/pandas/blob/4d0a4365870893e232f639af13fea44c7d3ff9d4/ci/code_checks.sh#L83
> 
> are currently checked - but it's nice to have it anyway, thanks!
> 
I will use the same list of errors locally the next time.

Thank you @MarcoGorelli, for your guidance and support. It makes contributing to pandas pleasant and not too complicated.

**Pull request merged**
