### PR TITLE
BUG: DecimalArray and JSONArray that are empty return incorrect results for isna()

### LINKED ISSUE #21189: BUG: DecimalArray and JSONArray that are empty return incorrect results for isna()
#### Code Sample, a copy-pastable example if possible

```python
In [1]: import pandas as pd

In [2]: from pandas.tests.extension.decimal.array import DecimalArray

In [3]: from pandas.tests.extension.json.array import JSONArray

In [4]: DecimalArray([]).isna()
Out[4]: array([], dtype=float64)

In [5]: JSONArray([]).isna()
Out[5]: array([], dtype=float64)

In [6]: import decimal

In [7]: DecimalArray([decimal.Decimal(1.0)]).isna()
Out[7]: array([False])

In [8]: DecimalArray([decimal.Decimal(1.0)]).isna().dtype
Out[8]: dtype('bool')
```
#### Problem description

This relates to a discussion with @TomAugspurger in #21183 when I made (since redacted) changes to `pandas/util/testing.py` in `assert_extension_array_equal` .  It turns out that the implementations of `isna()` in `DecimalArray` and `JSONArray` return an `ndarray` of the wrong dtype if the arrays are empty.

So we need to force the dtype of the result of `isna()` to be `bool` in those implementations

#### Expected Output

```
In [4]: DecimalArray([]).isna()
Out[4]: array([], dtype=bool)

In [5]: JSONArray([]).isna()
Out[5]: array([], dtype=bool)

```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.3.2
pip: 9.0.1
setuptools: 38.4.0
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.1
pymysql: 0.7.11.None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by Dr-Irv**
- [x] closes #21189
- [x] tests added / passed
  - Modified tests/extension/base/missing.py to test when arrays are empty
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry
  - Did not put anything here because it's internal code

Probably for @TomAugspurger to review.

### CODE REVIEW

**Review by TomAugspurger — APPROVED** [review]

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Do we target such small fixed to ExtensionArrays for 0.23.1 or 0.24.0 ?

**Review by jreback — CHANGES_REQUESTED** [review]
lgtm. pls add a whatsnew note in 0.24. virtually all extension changes will have to be in 0.24. FYI

**Comment by TomAugspurger** [comment]
This is a test-only change. I think it's fine for 0.23.1, and doesn't need
a release note.

**Comment by jreback** [comment]
no it does need a release note, you have technically changed the behvaior. its ok for 0.23.1 but this may get messy, much easier just to put all EA changes in 0.24

**Comment by Dr-Irv** [comment]
@jreback I'm in agreement with @TomAugspurger .  You write:

> no it does need a release note, you have technically changed the behvaior.

The behavior that is changed is in a test class that is not documented. Has it been prior practice to document in whatsnew when bugs in a test class are fixed?  If so, then I'm fine to add a whatsnew.

I'm indifferent on the version number.  Given the disagreement between the two of you, please let me know how you will reconcile on both the version number issue as well as the whatsnew issue, and how to proceed.

**Comment by jorisvandenbossche** [comment]
Yep, the "user facing" (meaning "extension author facing") change was indeed only in a test, so no whatsnew needed.

**Comment by jorisvandenbossche** [comment]
Tagging this as 0.23.1, just so we don't forget it. When PRs get backported, we can still change it to 0.24.0 if we decided by then

**Pull request merged**
