### PR TITLE
Revert 31791

### PR DESCRIPTION
**Pull request by WillAyd**
supersedes #31800

we never back ported this so just cleaning up master (assuming it now works again)

### CODE REVIEW

**Comment by jbrockmendel** [comment]
one npdev fail left

**Comment by jreback** [comment]
thanks @WillAyd

**Comment by jorisvandenbossche** [comment]
Why did we revert this? 

We are testing all external error messages, IMO there is no point in testing those so detailed (each time a package changes the wording slightly, our tests will start failing)

**Comment by jreback** [comment]
not all of these are external , they need to be separated into 2 lists

**Pull request merged**
