### PR TITLE
CLN: Remove unncessary lambda wrapper

### PR DESCRIPTION
**Pull request by skasturi**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

A lambda wrapper is unnecessary in these cases as the underlying methods are themselves callable. Moreover, the code does not add any logic in the wrapper to warrant the usage of lambda.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
how are these inecessary?

did you time the difference 

these are timing using a lambda function 

using max actually transforms this to another operation

**Comment by skasturi** [comment]
how are these inecessary?
[skasturi]  
- `max` and `lambda x: max(x)` have the exact functionality. 
- `fmt.format` and `lambda x: fmt.format(x)` have the exact functionality

did you time the difference
[skasturi] Thank you for suggesting me to do this. They both seem to have the almost similar timing. Guess it's a macro replacement? 

these are timing using a lambda function
[skasturi] I am not sure what you meant by this. 

using max actually transforms this to another operation
[skasturi] Yes. As I mentioned earlier `max` and `fmt.format` are themselves `Callable`. Therefore, in general it might not be necessary to wrap them in a `lambda`.

**Comment by jreback** [comment]
> how are these inecessary?
> [skasturi]
> 
> * `max` and `lambda x: max(x)` have the exact functionality.
> * `fmt.format` and `lambda x: fmt.format(x)` have the exact functionality
> 
> did you time the difference
> [skasturi] Thank you for suggesting me to do this. They both seem to have the almost similar timing. Guess it's a macro replacement?
> 
> these are timing using a lambda function
> [skasturi] I am not sure what you meant by this.
> 
> using max actually transforms this to another operation
> [skasturi] Yes. As I mentioned earlier `max` and `fmt.format` are themselves `Callable`. Therefore, in general it might not be necessary to wrap them in a `lambda`.

show the the asv results

**Comment by skasturi** [comment]
Sure. Would you mind telling me how to run the asv_bench? I am unable to find it in the top level readme.

**Comment by jreback** [comment]
https://pandas.pydata.org/docs/development/contributing.html#running-the-performance-test-suite

**Comment by WillAyd** [comment]
Thanks for the PR but AFAICT the intent of these benchmarks is to actually measure the application of a lambda function. We should already have measurements for the built-in max function, so I think don't want to do this

**Comment by jreback** [comment]
agree with @WillAyd here, the point of these asv's is to specifically measure when using a lambda. so this change is measuring something else.

**Comment by skasturi** [comment]
Thank you @WillAyd and @jreback for the context.

**Pull request closed without merging**
