### PR TITLE
ENH: enable mul, div on Index by dispatching to Series

### PR DESCRIPTION
**Pull request by jbrockmendel**
One of the last remaining inconsistencies between Index and Series arithmetic is that division and multiplication is entirely disabled for object-dtype Index, while for Series we operate pointwise.  This PR makes Index behave the same way, and simplifies the code by using existing Series-op-wrapping code to do so.

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I'm pretty sure there is at least one issue for this, will track it down.

### CODE REVIEW

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
Can you explain your changes?

**Review by jreback — CHANGES_REQUESTED** [review]
are we actually testing these? it seems we are enabling *all* numeric methods; do all of these even make sense on datetimelikes?

**Comment by jbrockmendel** [comment]
> are we actually testing these?

Yes.  In particular see the tests.arithmetic tests that are currently xfailed that this un-xfails.

> it seems we are enabling all numeric methods; do all of these even make sense on datetimelikes?

DTI/PI get these methods from DTA/PA, which define them with `make_invalid_op`, so these correctly raise.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
ok seems fine to me. @jorisvandenbossche

**Comment by jreback** [comment]
lgtm. do we need a release note for the additional things that Index can now do? (e.g. can you enumerate them). pls merge master.

**Comment by jbrockmendel** [comment]
updated+green

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
