### PR TITLE
Hdffixes

### LINKED ISSUE #12221: KeyError Iterating on empty HDFStore
list(pd.HDFStore("non_existing_store.hdf"))

should, I think, return ``[]``, instead it yields:

    KeyError: 'No object named 0 in the file'

### PR DESCRIPTION
**Pull request by toobaz**
This fixes #12221 and #10381 . Same source file, but let me know if you want separate PRs.

### CODE REVIEW

**Comment by jreback** [comment]
these changes are separate

the iterable a ones don't have tests

**Comment by toobaz** [comment]
Yes, they are separate: do you prefer different PRs?

The iterable one has test at line 394 of ``pandas/io/tests/test_pytables.py``.

**Comment by jreback** [comment]
separate

the iterator one needs to inherit from BaseIterator

**Comment by toobaz** [comment]
OK, now repushing them separately. But BaseIterator is not a meaningful ancestor for HDFStore itself, since the latter can be iterated more than once, i.e. doesn't have state (i.e. doesn't have __next__).

**Comment by toobaz** [comment]
Replaced by https://github.com/pydata/pandas/pull/12251 , https://github.com/pydata/pandas/pull/12252 , https://github.com/pydata/pandas/pull/12253

**Pull request closed without merging**
