### PR TITLE
DOC: migrate from sphinx-panels to sphinx-design

### LINKED ISSUE #52939: DOC: move from ``sphinx-panels`` to ``sphinx-design``
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

sphinx-panels is no longer maintained and restricts our sphinx version. The maintainers recommend using ``sphinx-design``.

https://github.com/executablebooks/sphinx-panels

We should switch I guess.

### Documentation problem

sphinx panels no longer maintained

### Suggested fix for documentation

move over

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
- closes #52939

Eventually it is the goal that the sphinx-design package replaces the sphinx-panels package (see https://github.com/executablebooks/sphinx-panels/issues/67 and https://sphinx-design.readthedocs.io/en/furo-theme/get_started.html#migrating-from-sphinx-panels, sphinx-design has the same (and more) features, but with a refactored and more flexible code base). 

So this PR moves our usage of sphinx-panels to sphinx-design (at least already for the front page, still need to do the same for the getting started pages)

It gives almost identical result as we have now (screenshot is with this PR, compare with eg https://pandas.pydata.org/pandas-docs/version/1.3/):

image

### CODE REVIEW

**Comment by jreback** [comment]
looks like failing doc build

**Comment by datapythonista** [comment]
```
Extension error:
Could not import extension sphinx_design (exception: No module named 'sphinx_design')
```
Is a dependency missing?

**Comment by jbrockmendel** [comment]
is this active?

**Comment by simonjayhawkins** [comment]
> is this active?

thanks @jorisvandenbossche for the additional commits. Is this ready for review?

**Comment by mroeschke** [comment]
Closing to clear the queue, but feel free to reopen if you have time and interest to work on it again.

**Comment by mroeschke** [comment]
@phofl @datapythonista @jorisvandenbossche I think this PR is ready now if you could review when you have time

**Review by datapythonista — APPROVED** [review]
Thanks @mroeschke, looks good to me

**Pull request merged**
