### PR TITLE
TST: cleanup of any_* test fixtures GH38017

### LINKED ISSUE #38017: TST: any_* fixtures are confusingly named
the naming on the any_* fixtures in `pandas/conftest.py` is pretty confusing

- `any_int_dtype` (numpy only)
- `any_int_nullable_dtype` (EA only)
- `any_numeric_dtype` both numpy & EA
- `any_real_dtype` both numpy int & float
- `sint_dtype` signed numpy ints

for example

so we need dtypes that are numpy_only and EA only and numpy + EA both for ints & floats

would propose something like

`any_int_numpy_dtype`
`any_int_ea_dtype`
`any_int_dtype` -> both numpy + ea

same for float

then

`any_numeric_nump_dtype`
`any_numeric_ea_dtype`

for float + int

which means we rename
`sint_dtype` -> `any_signed_int_numpy_dtype`

I think this would require a PR to organize, a PR to create new names & fix everything.

### PR DESCRIPTION
**Pull request by pratyushsharan**
- [X] closes #38017 
- [ ] tests added / passed
- [X] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
ok looks pretty good
- precommit is failing
- can you show the number of tests on master vs number of tests here (should be the same unless there is an error somewhere)

merge master & ping when green (as any PRs might affect this so can  merge quickly after looks good).

**Comment by pratyushsharan** [comment]
@github-actions pre-commit

**Comment by pratyushsharan** [comment]
> * precommit is failing

Fixed.

> * can you show the number of tests on master vs number of tests here (should be the same unless there is an error somewhere)

I've checked the number of tests using `pytest pandas --collect-only` and both master and this branch have the same number of tests - 181359. The results on Azure pipelines also give the same result. 
This branch: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=64499&view=ms.vss-test-web.build-test-results-tab
Master branch: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=64511&view=ms.vss-test-web.build-test-results-tab

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @pratyushsharan very nice!

**Pull request merged**
