### PR TITLE
TST: move conftest.py to top-level

### PR DESCRIPTION
**Pull request by jreback**
xref #15341

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback The concerns of before regarding `pd.test()` (the reason conftest.py was not in the top level), are those solved / not needed anymore ?

**Comment by jreback** [comment]
@jorisvandenbossche so the issue was that when installed, if ``conftest.py`` is at the top-level (and not below pandas), then its not installed; this can be resolved by by actually including it as a data file in ``setup.py``, but then need to have to explicity tell ``pytest`` . This *only* matters for ``pandas.test()``; so we *could* explicity path it in there.

But this is just simpler. In any even I made the ``BUILD_TEST`` build now run ``pandas.test()`` so this is tested anyhow.

**Comment by jreback** [comment]
FYI I reverted my original commit: 59b88ab6123338e1dfcc0f77dfb3e5c4c511889a

**Comment by jorisvandenbossche** [comment]
For what reason did you revert?

Personally, it doesn't really matter to me where `conftest.py` goes. It is just a choice when putting it top-level that `pd.test()` cannot specify the custom markers. Which is not the biggest problem I think. But I also don't mind it being inside pandas (it is not visible to users, so not really a problem)

**Comment by jreback** [comment]
@jorisvandenbossche well, it IS a problem in that in reality ``conftest.py`` will have more and more things. This is a central repository for fixtures and such. If pandas had been built from the ground up with ``pytest``, we would have a whole set of ``conftest.py``. So its not a problem per-se, just not very clean (and not very typical).

**Comment by jorisvandenbossche** [comment]
OK, so we agree to just keep it in pandas? 
That was not fully clear to me that you were OK with that, so that was the only reason of my question above!

**Comment by jreback** [comment]
yeah not sure what to do with it really.

**Pull request merged**
