### PR TITLE
CI/TST: Add network tests to CI

### LINKED ISSUE #43559: CI: network tests
In #43545, found that "not network" was not actually skipping network tests. 

In the process of looking for a build which explicitly runs network tests, looked like all pytest patterns include "not network" or "slow". In that case, no network tests will be selected (unless they also happen to be "slow"). Can anyone please confirm this or point me to the build where network tests are meant to run?

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #43559
- [x] tests added / passed

No network tests were running on the CI, so adding these tests to PY38 and PY39 Linux, MacOS and Window builds

### CODE REVIEW

**Comment by lithomas1** [comment]
We might want to run these on the database builds as well and maybe a slow build. LGTM otherwise.

**Comment by mroeschke** [comment]
> We might want to run these on the database builds as well and maybe a slow build

Hmm wouldn't that just be essentially duplicating the same tests in multiple PY38 or PY39 environments (AFAICT these tests don't depend on optional dependencies since it used urllib to make the network call)?

**Comment by jreback** [comment]
> > We might want to run these on the database builds as well and maybe a slow build
> 
> Hmm wouldn't that just be essentially duplicating the same tests in multiple PY38 or PY39 environments (AFAICT these tests don't depend on optional dependencies since it used urllib to make the network call)?

yeah just a fast & slow build are fine

**Comment by jreback** [comment]
can you only enable this on a few builds? the linux ones are prob enough (e.g. 1 fast and 1 slow)

**Comment by mroeschke** [comment]
> can you only enable this on a few builds? the linux ones are prob enough (e.g. 1 fast and 1 slow)

These are enabled on:

Linux PY38
Linux PY39
MacOS PY38
Windows PY38
Windows PY39

which is good coverage IMO. Running on a slow build I don't think is worth it because it's equivalent to running on Linux PY38 twice.

**Pull request merged**
