### PR TITLE
DOC: fix wrongly placed versionadded

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Just came across a wrongly placed versionadded tag

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. side issue: seems doc build is having issues

@TomAugspurger

**Comment by TomAugspurger** [comment]
Maybe related to sphinx 1.6? I tried to build with 1.6 when it was released and it worked but seemed to take a while. I'll do some timings.

**Comment by jorisvandenbossche** [comment]
Something with the autosummary / autodoc is going wrong (all classes warn about methods with unknown toctree references, a problem we have had before), and indeed started going wrong since sphinx 1.6.

Might be that the big timing is just due to the gigantic amount of warnings (log is too large for travis, that's why it stopped).

But we need to fix the autodoc anyway. Will do a PR to fix sphinx to 1.5 for now.

**Comment by jorisvandenbossche** [comment]
Made a PR to pin for now, and an issue to track the problem: https://github.com/pandas-dev/pandas/issues/16705

**Pull request merged**
