### PR TITLE
docstrings: typos, clarity

### PR DESCRIPTION
**Pull request by stragu**
Minor changes only in docstrings: capitalisation, hyphenation, "indexes" -> "indices", typos.

- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Apologies for not testing, as the changes are minor and only affect docstrings.
No `whatsnew` entry either because minor.

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
both spellings are acceptable https://grammarist.com/usage/indexes-indices/

**Comment by mzeitlin11** [comment]
> both spellings are acceptable https://grammarist.com/usage/indexes-indices/

Not sure if distinction is necessary, but from a `pandas` perspective I like the idea of 

- Indexes: Multiple `Index` objects
- Indices: Values used to index into something

**Comment by stragu** [comment]
Thank you both for your comments. I amended the commit to not touch indices vs indexes.

**Review by simonjayhawkins — APPROVED** [review]
Thanks @stragu

**Pull request merged**
