### PR TITLE
DOC: added see also to docstrings in mean and median

### PR DESCRIPTION
**Pull request by Brett-Dixon**
Added, See also for mean and median in doctring 

see https://github.com/pandas-dev/pandas/issues/58065

### CODE REVIEW

**Comment by Aloqeely** [comment]
Thanks for the PR! Changes look good but can you take a look at the failing checks?

**Comment by BDixon808** [comment]
Thanks! I believe  ci/code_checks.sh needs to be updated.

**Comment by Aloqeely** [comment]
Yes, could you update it to remove the ones you fixed?

**Comment by BDixon808** [comment]
Sure, no problem!

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @BDixon808

**Pull request merged**
