### PR TITLE
REF: share to_native_types with ArrayManager

### PR DESCRIPTION
**Pull request by jbrockmendel**
also combine implementations of Block.fill_value

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@jorisvandenbossche are you happy with this approach?  if so, i think can use it to get rid of at least one or two more uses of apply_with_block

**Review by jorisvandenbossche — APPROVED** [review]
Yes, thanks!

Should we try to find a better place to put the `to_native_types` function?

**Comment by jbrockmendel** [comment]
> Should we try to find a better place to put the to_native_types function?

Sure.  Have somewhere in mind?

**Comment by jorisvandenbossche** [comment]
Not directly a better idea. Let's worry about that later.

**Pull request merged**
