### PR TITLE
Fix automatic xlims in line plots

### LINKED ISSUE #11310: Pandas.plot() fails to calculate the right xlims
While working with cyclic data, Pandas failed to calculate the right limits for the plot. I am not sure which exact characteristic of my data causes the problem, but I will observe if further when I have time for it. Until then, here is the notebook in which the error occurred:

http://nbviewer.ipython.org/gist/AKuederle/d7837facee0479beb6cf

The first plot is the pandas plot, which has the wrong x-limits.
The second plot is the same (or at least I thought) the same plot using matplotlib directly.
The third plot shows, that it padas issue is indeed the x-limits and not something else in plotting process

Edit:
Used package Versions:

```
commit: None
python: 3.4.3.final.0
python-bits: 64
OS: Windows
OS-release: 8
machine: AMD64
processor: AMD64 Family 16 Model 10 Stepping 0, AuthenticAMD
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.2
nose: 1.3.7
Cython: 0.23.3
numpy: 1.9.3
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 4.0.0
sphinx: 1.2.3
patsy: 0.4.0
dateutil: 2.4.1
pytz: 2015.6
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.4.3
openpyxl: 2.0.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.5
lxml: 3.4.4
bs4: 4.3.2
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.8
pymysql: None
psycopg2: None
```

### LINKED ISSUE #11471: plot with unsorted indices misses data points
Compare these 2 plots below, this is not expected behavior:

```
import pandas as pd
from numpy.random import rand
testarr1=rand(100)
testarr2=rand(100)
pd.DataFrame(testarr2,index=testarr1).plot(style='.')
pd.DataFrame(testarr2,index=testarr1).sort().plot(style='.')
```

### LINKED ISSUE #15495: Update plotting functions to use the new Matplotlib default styles
In version 2.0.0, Matplotlib introduced several changes in it's default style. Pandas plotting functions should be updated to use the new style.

http://matplotlib.org/users/dflt_style_changes.html

### PR DESCRIPTION
**Pull request by nmartensen**
- [x] closes #11310, closes #11471, closes #15495
 - [x] tests added / passed
 - [x] passes ``git diff upstream/master --name-only -- '*.py' | flake8 --diff``
 - [x] whatsnew entry

### CODE REVIEW

**Comment by nmartensen** [comment]
So this breaks 18 Tests:
1. test_finder_annual - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_finder_daily - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_finder_hourly - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_finder_minutely - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_finder_monthly - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_finder_quarterly - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_format_timedelta_ticks_narrow - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_format_timedelta_ticks_wide - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_irregular_ts_shared_ax_xlim - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_mixed_freq_regular_first - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_mixed_freq_regular_first_df - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_secondary_y_irregular_ts_xlim - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_secondary_y_non_ts_xlim - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_secondary_y_regular_ts_xlim - pandas.tests.plotting.test_datetimelike.TestTSPlot
1. test_area_lim - pandas.tests.plotting.test_frame.TestDataFramePlots
1. test_line_lim - pandas.tests.plotting.test_frame.TestDataFramePlots
1. test_ts_area_lim - pandas.tests.plotting.test_series.TestSeriesPlots
1. test_ts_line_lim - pandas.tests.plotting.test_series.TestSeriesPlots

These tests hardcode expectations from previous MPL defaults. It is only the second commit (which allows MPL to apply its new defaults) that breaks the tests. Do they need a second set of expected results depending on which MPL version is used? Or can we simply update the expected results to what current MPL produces?

The existing tests do not yet cover the case of unsorted x axis (the subject of the first commit). This will need new tests. Is a single test sufficient or do we need different instances for datetimelike/DataFrame/Series?

**Comment by TomAugspurger** [comment]
Thanks for this. Your changes look correct.

> Do they need a second set of expected results depending on which MPL version is used? Or can we simply update the expected results to what current MPL produces?

I think we test on an old matplotlib (1.3.1) on python 2.7, and the most recent matplotlib otherwise. So yes, ideally we would cover both. If it's excessively difficult, you can raise skiptests for older matplotlibs where nescessary.

> Is a single test sufficient or do we need different instances for datetimelike/DataFrame/Series?

I think just a test for line plots covering a few cases

- `Series.plot` with unsorted index
- `DataFrame.plot` with unsorted index
- `DataFrame.plot(x='x', y='y')` with unsorted `x`
 
should be sufficient.

We'll also need a release note. If you rebase on master, there should be a `docs/source/whatsnew/v0.20.3.txt` you can add this to.

**Comment by TomAugspurger** [comment]
Actually, it's probably best to do this for 0.21.0, not 0.20.3, since the xlim will be now following matplotlib 2's.

**Comment by nmartensen** [comment]
So the codecov decrease in plotting/_tool.py is actually the point of one of the patches &ndash; xlims should only be adjusted with older matplotlib.

If you prefer this PR to be split into two (one for wrong xlims and one for MPL xlim defaults), or if you have other comments, let me know.

**Comment by TomAugspurger** [comment]
> So the codecov decrease...

That may be inaccurate. I don't recall which versions of matplotlib are installed on the runs that report code coverage.

**Comment by jreback** [comment]
can you rebase / update according to comments

**Comment by TomAugspurger** [comment]
I think you'll just need a rebase. IIRC, things looked pretty good last time I looked.

**Comment by nmartensen** [comment]
rebased

**Comment by jreback** [comment]
can you rebase / update once again

**Comment by nmartensen** [comment]
rebased

**Comment by TomAugspurger** [comment]
Thanks @nmartensen! (sorry about the extra rebase)

**Pull request merged**
