### PR TITLE
BUG: set df.plot.area linewidth to 0

### LINKED ISSUE #32106: df.plot.area() Stacked area graph shows glitch "lines" at limit between colors
#### Code Sample

```python
# library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Dataset
x = np.random.rand(10, 4)
df = pd.DataFrame(x, columns=['a', 'b', 'c', 'd'])

# plot
df.plot.area()

plt.figure()
# Generate with matplotlib for glitchless version.

plt.stackplot(df.index.tolist(), x.transpose(), labels=list("abcd"))

plt.show()
```
#### Problem description
The pandas-generated stacked area graph has weird glitches at the limit between colors
Pandas figure
Pandas figure (details)

This issue can also be seen at [Python graph galery example #254](https://python-graph-gallery.com/254-pandas-stacked-area-chart/).
NB: export to png further exacerbate this effect.

<details>

</details>

#### Expected Output
The matplotlib-generated graph, without the glitches.

Matplotlib figure
Capture d’écran 2020-02-19 à 15 15 31

#### Output of ``pd.show_versions()``
I first saw this on 0.25.1, after a pip update it still happens.

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8

pandas           : 1.0.1
numpy            : 1.17.4
pytz             : 2018.5
dateutil         : 2.7.3
pip              : 20.0.1
setuptools       : 41.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.0.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.0
html5lib         : None
pymysql          : None
psycopg2         : 2.8.2 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 7.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.0
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

### PR DESCRIPTION
**Pull request by leogermond**
- [x] closes #32106 
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry (`1.1.0`)

### CODE REVIEW

**Review by WillAyd — CHANGES_REQUESTED** [review]
Can you add a test?

**Comment by leogermond** [comment]
Sure, however tests as they are don't pass on my machine: 7 of them fail and I can't really make sense of the logs, even on upstream master 8 won't pass.
I included them if you want to help me have a look: [pandas_test.log](https://github.com/pandas-dev/pandas/files/4266534/pandas_test.log).

**Comment by MomIsBestFriend** [comment]
@leandermaben Can you open an issue for the failing tests?

**Comment by WillAyd** [comment]
@leogermond not sure about your local environment but can you still add one here? Can leverage CI

**Comment by WillAyd** [comment]
Closing as stale, but happy to reopen if you want to address comments and provide a test

**Pull request closed without merging**
