### PR TITLE
added sytle in stylesheet for <blockquote>

### LINKED ISSUE #48758: WEB: Add style for blockquote
Looks like when we have a `<blockquote>` tag in our website, our stylesheet doesn't have a specific style for it, and it's rendered as just a normal text.

Look at the second paragraph in the Implementation section in https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html

It probably makes sense to print it with a left padding, and with a brighter color (or use a bootstrap style, which is probably overwritten by mistake).

### PR DESCRIPTION
**Pull request by Himanshuwagh**
Closes #48758

added styles for stylesheets for `<blockquote>` tag
1. added left-padding
2. also changed the font color ( default black to gray )

### - screenshot of desktop
op1

### - screenshot of mobile
op2

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks for working on this @Himanshuwagh. Would be good if you can share a screenshot of how this looks in both desktop and mobile, so people can have feedback on that.

Also, if it makes sense, would be good to keep consistency on `#ffffff` vs `rgb(255, 255, 255)` or `px` vs `em` format. If you have a reason for using different ways it's fine, but otherwise would make things easy to maintain if things are consistent in my opinion.

**Comment by Himanshuwagh** [comment]
> Thanks for working on this @Himanshuwagh. Would be good if you can share a screenshot of how this looks in both desktop and mobile, so people can have feedback on that.
> 
> Also, if it makes sense, would be good to keep consistency on `#ffffff` vs `rgb(255, 255, 255)` or `px` vs `em` format. If you have a reason for using different ways it's fine, but otherwise would make things easy to maintain if things are consistent in my opinion.

**Comment by Himanshuwagh** [comment]
@datapythonista can you help to check changes on mobile version. 
P.S : I have attached screenshot for desktop in description

**Comment by datapythonista** [comment]
If you're using Brave or Chrome (and probably other browsers), you can simply right click anywhere in the screen, select `Inspect`, and then you have a small icon of a phone in the top left of the panel that opens. With that you can easily simulate in mobile.

If you also include the nonrmal paragraphs around the blokquote in the screenshot that would be better, it'll make it clearer how things look like.

Thanks for all the work on this @Himanshuwagh

**Comment by Himanshuwagh** [comment]
@datapythonista Thanks for help.
I have updated and attached screenshots for both (desktop + mobile). You can review it now.

**Comment by datapythonista** [comment]
Thanks @Himanshuwagh this is great. I wonder if it'd look better if we remove the left margin, leave the line aligned with the text, and increase a bit the padding between the left line and the text. What do you think? No big deal, probably just a personal preference, but having both padding and margin looks a bit strange to me. Feel free to disagree if you think it's ok like it is now. Thanks!

**Comment by Himanshuwagh** [comment]
> Thanks @Himanshuwagh this is great. I wonder if it'd look better if we remove the left margin, leave the line aligned with the text, and increase a bit the padding between the left line and the text. What do you think? No big deal, probably just a personal preference, but having both padding and margin looks a bit strange to me. Feel free to disagree if you think it's ok like it is now. Thanks!
#### Yes, looks good to me. Let me know if you suggested the same.
op3

**Comment by datapythonista** [comment]
Yes, your screenshot is what I'd do. I'd probably have the same padding in the top and bottom of the gray box too. Having the padding much smaller in the top loos a bit strange to me.

**Comment by Himanshuwagh** [comment]
@datapythonista updated sir
op5

**Review by datapythonista — APPROVED** [review]
looks good to me, thanks @Himanshuwagh, nice work!

**Comment by Himanshuwagh** [comment]
Thanks @datapythonista for helping throughout. Next steps ?

**Comment by datapythonista** [comment]
Someone else from the team will double check and merge

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Himanshuwagh

**Pull request merged**
