### PR TITLE
DOC: Added check for standard pandas reference

### LINKED ISSUE #32316: DOC: Standardize references to pandas in the documentation
In our documentation (files in `doc/source/../*.rst`), we refer to pandas as `Pandas`, `pandas`, and `*pandas*` (sphinx italics).

For documentation consistency, we should standardize these to one form. `pandas` is the preferable form in our documentation files.

Unfortunately I don't think we create a lint rule for this pattern since we have to be flexible to references and hyperlinks.

### PR DESCRIPTION
**Pull request by joybh98**
- [x] xref #32316
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

As suggested by @datapythonista , I've added checks in `ci/code_checks.sh` to look if the pandas is being referenced in a standardized way i.e pandas, not *pandas* or Pandas

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
This is not working. We're here to help, but please try your changes locally before submitting a PR.

**Comment by joybhallaa** [comment]
> This is not working. We're here to help, but please try your changes locally before submitting a PR.

@datapythonista my bad, will try my changes locally from now on.

**Comment by joybhallaa** [comment]
> This is not working. We're here to help, but please try your changes locally before submitting a PR.

I'm getting `./ci/code_checks.sh: line 243: RET: command not found`, I can't understand why I'm getting this error. All the checks are using it.

**Comment by datapythonista** [comment]
Once again, can you check locally if things are working? This is my 10th time reviewing this PR and it's obvious once more that this is not working. There are more than 100 cases of the work `Pandas` in `doc/`, and your changes are not detecting those. No need for your PRs to be perfect, but can you please stop proposing changes that you didn't try locally even once to see if they run without errors or they make sense? Thank you

**Comment by simonjayhawkins** [comment]
@joybhallaa are you still working on this?

**Comment by willie3838** [comment]
take

**Comment by alimcmaster1** [comment]
Closing this looks like @willie3838 is looking

**Pull request closed without merging**
