### PR TITLE
REF: collect to_xarray tests

### PR DESCRIPTION
**Pull request by jbrockmendel**
I'm split on where to put test_to_xarray.  Since its testing one method, tests/generic/methods/ makes sense.  BUT we could try to reserve that directory for tests that are nicely parametrized over Series/DataFrame, which these are not.  Thoughts?

### CODE REVIEW

**Comment by jreback** [comment]
I would create pandas/tests/downstream and move pandas/tests/test_downstream.py to there along with this test file (name is good), maybe even move the xarray test to that (inside test_downstream.py)

**Comment by jreback** [comment]
ping on green.

**Comment by jbrockmendel** [comment]
> I would create pandas/tests/downstream and move pandas/tests/test_downstream.py to there along with this test file (name is good), maybe even move the xarray test to that (inside test_downstream.py)

I'll give this some thought.  I kind of like test_downstream.py for the specific "dont break downstream" purpose it has no (just asked xarray folks to open a PR with a regression test thatll go there)

**Comment by jreback** [comment]
hmm needs a rebase

**Comment by jreback** [comment]
thanks

**Pull request merged**
