### PR TITLE
DOC: Add dateutil to intersphinx #24437

### LINKED ISSUE #24437: DOC: Add dateutil to intersphinx
Looks like we'ree using `dateutil` items in the `See Also` section, for example:
https://pandas-docs.github.io/pandas-docs-travis/generated/pandas.tseries.offsets.DateOffset.html

But, for sphinx to generate the links, we need `dateutil` configured as an intersphinx item in `doc/source/conf.py`.

### PR DESCRIPTION
**Pull request by benjaminr**
- [x] closes #24437 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by benjaminr** [comment]
I generated the documentation and the dateutil link worked okay for example in the pandas.tseries.offsets.DateOffset doc you initially described.

The order is now alphabetically listed to make it slightly more legible for reading through the list as it grows and changes.

**Review by datapythonista — APPROVED** [review]
good, but if the order is alphabetical, you may want to have `dateutil` the first, not the last :)

**Comment by benjaminr** [comment]
Ah, whoops! I reordered the listing and then added dateutil. Fixed now.

**Comment by jreback** [comment]
thanks @benjaminr

**Comment by benjaminr** [comment]
No probs @jreback

**Pull request merged**
