### PR TITLE
Moved caching in AbstractHolidayCalendar to the instance level

### LINKED ISSUE #9552: Disable class level caching in AbstractHolidayCalendar
By caching at the *class* level it prevents instances from defining different rules - e.g.
```python
import numpy as np
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday

class HolidayCalendar(AbstractHolidayCalendar):
    def __init__(self, rules):
        self.rules = list(np.atleast_1d(rules))

jan1 = HolidayCalendar(Holiday('jan1', year=2015, month=1, day=1))
jan2 = HolidayCalendar(Holiday('jan2', year=2015, month=1, day=2))


jan1.holidays()
Out[2]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-01]
Length: 1, Freq: None, Timezone: None

jan2.holidays()
Out[3]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-01]    <--------------------------- uses cached result from *other* instance!
Length: 1, Freq: None, Timezone: None
```

```python
import numpy as np
from pandas.tseries.holiday import AbstractHolidayCalendar, Holiday

class HolidayCalendar(AbstractHolidayCalendar):
    def __init__(self, rules):
        self.rules = list(np.atleast_1d(rules))

jan1 = HolidayCalendar(Holiday('jan1', year=2015, month=1, day=1))
jan2 = HolidayCalendar(Holiday('jan2', year=2015, month=1, day=2))


jan2.holidays()
Out[2]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-02]
Length: 1, Freq: None, Timezone: None

jan1.holidays()
Out[3]: 
<class 'pandas.tseries.index.DatetimeIndex'>
[2015-01-02]    <--------------------------- uses cached result from *other* instance!
Length: 1, Freq: None, Timezone: None
```
https://github.com/pydata/pandas/blob/a72d95163b4d268012709255d7a52bbe5c1a7eb6/pandas/tseries/holiday.py#L351-L357

### PR DESCRIPTION
**Pull request by dhirschfeld**
Closes #9552

### CODE REVIEW

**Comment by dhirschfeld** [comment]
image

**Comment by jreback** [comment]
@dhirschfeld this looks good. Can you add a release note in Bug fixes, and squash. ping me when pushed.

**Comment by dhirschfeld** [comment]
@jreback - added a comment in `whatsnew/v0.16.1.txt`. Let me know if that's ok.

**Comment by jreback** [comment]
@dhirschfeld looks good. pls ping when green.

**Comment by dhirschfeld** [comment]
@jreback - looks like travis finally got there in the end!

**Comment by dhirschfeld** [comment]
@jreback - rebased after conflicts in `whatsnew/v0.16.1.txt`. Will ping when travis says ok

**Comment by jreback** [comment]
thanks @dhirschfeld

**Pull request merged**
