### PR TITLE
PERF: Categorical getitem perf

### LINKED ISSUE #30744: PERF: Categorical indexing performance regression
Recent regression in the `categoricals.CategoricalSlicing.time_getitem_list` benchmark: https://pandas.pydata.org/speed/pandas/#categoricals.CategoricalSlicing.time_getitem_list?commits=6efc2379-b9de33e3

Reproducible example for this benchmark:

```
N = 10 ** 6
categories = ["a", "b", "c"]
values = [0] * N + [1] * N + [2] * N
data = pd.Categorical.from_codes(values, categories=categories)

list_ = list(range(10000))

%timeit data[list_]
```

Now, this slowdown is due to the changes in https://github.com/pandas-dev/pandas/pull/30308. Categorical `__getitem__` now checks if the key is a boolean indexer: https://github.com/pandas-dev/pandas/pull/30308/files#diff-f3b2ea15ba728b55cab4a1acd97d996d

So this slowdown is of course expected, and also only for Categorical itself (eg pd.Series indexing already handles this boolean checking). So in that light, we can certainly ignore this regression. 
But, this led me think: maybe the ExtensionArrays are a good place to start not supporting object dtype as boolean indexer? (and so not add support for it now, which also avoids this performance regression)

### PR DESCRIPTION
**Pull request by TomAugspurger**
Convert to an array earlier on.
Closes https://github.com/pandas-dev/pandas/issues/30744

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Master

```python
   ...: %timeit data[list_]
1.44 ms ± 5.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

```

This PR

```
   ...: %timeit data[list_]
740 µs ± 5.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

```

Will post the pre-indexing with NA timing in a bit.

**Comment by jreback** [comment]
cool, can you add an asv

**Comment by TomAugspurger** [comment]
> can you add an asv

I think Joris caught this because the existing asv `CategoricalSlicing.time_getitem_list` https://pandas.pydata.org/speed/pandas/#categoricals.CategoricalSlicing.time_getitem_list?commits=6efc2379-b9de33e3

**Comment by jbrockmendel** [comment]
LGTM

**Comment by jorisvandenbossche** [comment]
So I reported this for Categorical (indeed because of the existing benchmark), but a similar change was made for other dtypes in https://github.com/pandas-dev/pandas/pull/30308. Also the boolean and integer (and numpy) arrays have the same issue.

**Pull request merged**
