### PR TITLE
DOC: Add pandas_path to the accesor list in the documentation

### PR DESCRIPTION
**Pull request by pjbull**
Added the [`pandas_path`](https://github.com/drivendataorg/pandas-path/) package that I just released to the list of third-party accessor extensions.

As a bonus, added a Description column for the existing libraries.

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm @datapythonista

**Review by datapythonista — APPROVED** [review]
Nice extension. Besides adding it to the table of acessors, doesn't it make sense to have a longer description in one of the other sections?

**Comment by pjbull** [comment]
@datapythonista Cool, I added a longer description to the "Data cleaning" section, which seemed the most relevant. That make sense?

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @pjbull

**Comment by WillAyd** [comment]
Thanks @pjbull

**Pull request merged**
