### PR TITLE
DOC: Add whatsnew file for 2.1.0

### PR DESCRIPTION
**Pull request by datapythonista**

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
This looks like the format for 2.0.1 and not a minor release?

**Comment by datapythonista** [comment]
> This looks like the format for 2.0.1 and not a minor release?

Yes, you're correct, my mistake, fixed it.

**Review by phofl — APPROVED** [review]
thx

**Comment by phofl** [comment]
Removed the contributor command, this failed the doc build (also left it out in the other release notes initially)

**Comment by datapythonista** [comment]
> Removed the contributor command, this failed the doc build (also left it out in the other release notes initially)

Thanks for taking care of this. That was because the tag `2.0.0` doesn't exist yet, updating to `2.0.0rc0` (which is the correct one) would have also fixed the problem, but we can add it later.

**Pull request merged**
