### PR TITLE
DOC:Update python version support info

### LINKED ISSUE #27558: DOC: Unable to import pandas on python 3.5.2
#### Code Sample, a copy-pastable example if possible

```python
import pandas
```
#### Problem description

Although it seems like a typing issue pandas is still affected, error:
```
root@ae9a5374fe6d:/buildbot# python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from .array_ import array  # noqa: F401
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/arrays/array_.py", line 7, in <module>
    from pandas.core.dtypes.common import (
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/dtypes/common.py", line 11, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/dtypes/dtypes.py", line 53, in <module>
    class Registry:
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/dtypes/dtypes.py", line 84, in Registry
    self, dtype: Union[Type[ExtensionDtype], str]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

To reproduce:
```
$ docker pull ursalab/amd64-ubuntu-16.04-python-3:worker
$ docker run -it ursalab/amd64-ubuntu-16.04-python-3:worker bash
# python -c "import pandas"
```

#### Output of ``pip freeze | grep pandas``

```
pandas==0.25.0
```

### PR DESCRIPTION
**Pull request by sameshl**
Updated the python version support info.
Added minimum version for Python 3.5 is 3.5.3 and removed python 2.7 support info.

closes #27558

### CODE REVIEW

**Comment by WillAyd** [comment]
Looks good to me. Is this the last area that needed to be fixed?

**Comment by TomAugspurger** [comment]
We can probably drop the "Plan for dropping Python 2.7" starting on line 20.

**Comment by TomAugspurger** [comment]
L932 in user_guide/io.rst also refers to 2.7

```
932:   an ordering on their keys. On Python 2.7+ you may use `collections.OrderedDict`
``

**Comment by sameshl** [comment]
@TomAugspurger so I just have to remove the part on "Plan for dropping Python 2.7" starting on line 20? right?

**Comment by jreback** [comment]
> @TomAugspurger so I just have to remove the part on "Plan for dropping Python 2.7" starting on line 20?

yes

**Comment by jreback** [comment]
looks ok, the docs checks are failing, click thru to see. ping on green.

**Comment by sameshl** [comment]
@jreback I understand the problem. The internal ref, `install.dropping-27`, which was pointing to the section which I just removed on "Droping Python 2.7"  is broken. There are few instances of this ref in the `doc/source/whatsnew/` files. Should I go and remove them ?

**Comment by jreback** [comment]
what you need to do is replace the refs with actual http links to the 0.24.2 docs

https://pandas.pydata.org/pandas-docs/version/0.24/install.html#install-dropping-27

**Comment by TomAugspurger** [comment]
Thanks @sameshl, this looks good.

@jreback for doc-only PRs that aren't specific to 0.25, I think we shouldn't backport. What do you think?

**Comment by jreback** [comment]
@TomAugspurger agree generally on this point
however we want this one to update the 0.25.x docs as it’s particularly relevant

**Comment by TomAugspurger** [comment]
SGTM.

**Comment by jreback** [comment]
thanks @sameshl

**Comment by sameshl** [comment]
Thanks @jreback and @TomAugspurger!

**Pull request merged**
