### PR TITLE
REGR: sort_value can not sort levels with non nas and nans

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @lukemanley 

open for suggestions if there is a more efficient way, but this raises right now while it did not before

### CODE REVIEW

**Comment by lukemanley** [comment]
#48495 handles this case (I just tested it). If we can merge #48495 I don't think we need this.

**Comment by phofl** [comment]
Can you add this specific test too?

**Comment by lukemanley** [comment]
yep, added.

**Comment by phofl** [comment]
Thx, will keep open till the other is merged.

**Comment by phofl** [comment]
other pr was merged, so this is fixed

**Pull request closed without merging**
