### PR TITLE
BUG: avoid usage in_qtconsole for recent IPython versions

### PR DESCRIPTION
**Pull request by TomAugspurger**
I've verified this manually with qtconsole 4.4.0, but if others want to check that'd be helpful.

screen shot 2019-01-30 at 2 22 06 pm

What release should this be done in? 0.24.1, 0.24.2 or 0.25.0?

Closes https://github.com/pandas-dev/pandas/issues/25036

### CODE REVIEW

**Comment by TomAugspurger** [comment]
For reference, IPython 3.0 was released in Feb. 2015 https://pypi.org/project/ipython/3.0.0/

**Comment by jorisvandenbossche** [comment]
> What release should this be done in? 0.24.1, 0.24.2 or 0.25.0?

Is there a reason to already do it in 0.24.x ?

**Comment by jreback** [comment]
sure we should drop, but this should be done in 0.25

**Comment by jreback** [comment]
ok this seems fine then for 0.24.1

**Comment by jreback** [comment]
can you add a note in whatsnew

**Comment by TomAugspurger** [comment]
@jorisvandenbossche switched to the check you suggested in 
https://github.com/pandas-dev/pandas/pull/25039#issuecomment-459116270, if you want to check.

I'll followup with the original PR of removing all this shortly after 0.24.1.

**Review by jorisvandenbossche — APPROVED** [review]
Looks good!

**Pull request merged**
