### PR TITLE
DEPR: DateOffset.__call__

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Is there an issue about this?

**Comment by jbrockmendel** [comment]
> Is there an issue about this?

No

**Comment by jreback** [comment]
can you add this to the deprecation removal list as well

**Comment by jbrockmendel** [comment]
> can you add this to the deprecation removal list as well

added

**Comment by jorisvandenbossche** [comment]
Can you then at least give a reasoning?

**Comment by jbrockmendel** [comment]
> Can you then at least give a reasoning?

Because its entirely redundant.

**Comment by jorisvandenbossche** [comment]
Thank you. It would be helpful if you can sometimes just give a bit more explanation when opening a PR (you know, I can't read your mind ;))

**Comment by jbrockmendel** [comment]
> Thank you. It would be helpful if you can sometimes just give a bit more explanation when opening a PR (you know, I can't read your mind ;))

I'll keep that in mind.  Thanks for keeping me honest.

**Pull request merged**
