### PR TITLE
DOC: Removed parenthesis from .loc,.iloc,.at,.iat

### LINKED ISSUE #49254: DOC: 10 minutes to pandas Selection section `DataFrame.loc` followed by `()`
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/10min.html

### Documentation problem

`DataFrame.loc`, etc should not be followed by parenthesis, because they are not functions. 

> # Selection
> While standard Python / NumPy expressions for selecting and setting are intuitive and come in handy for interactive work, for production code, we recommend the optimized pandas data access methods, [DataFrame.at()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at), [DataFrame.iat()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iat.html#pandas.DataFrame.iat), [DataFrame.loc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc) and [DataFrame.iloc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc).

> ## Selection by label
> See more in [Selection by Label](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-label) using [DataFrame.loc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc) or [DataFrame.at()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at).

> ## Selection by position
> See more in [Selection by Position](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-integer) using [DataFrame.iloc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc) or [DataFrame.at()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at).

### Suggested fix for documentation

> ... optimized pandas data access methods, [DataFrame.at](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at), [DataFrame.iat](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iat.html#pandas.DataFrame.iat), [DataFrame.loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc) and [DataFrame.iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc).

### PR DESCRIPTION
**Pull request by EleekaN**
- [ ] closes #49254 
- Removed parenthesis from **.loc**, **.iloc**, **.at**, **.iat** under `Selection`, `Selection by Label` and `Selection by Position`.

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Hi, thanks for your contribution. Please don't open a new pr for every change, you can just edit your existing pr

**Comment by EleekaN** [comment]
Sure...looks like something went wrong while doing it and I am not sure
what I did. I will be careful next time. 👍

**Comment by EleekaN** [comment]
What should I do next?

**Comment by EleekaN** [comment]
Thank you @rhshadrach and @phofl for your feedback and guidance. Appreciated!!!
Now, I am thinking there are no pending actions from me with the message below.
*--------------------------------*
 #**Development**
Successfully merging this pull request may close these issues.

https://github.com/pandas-dev/pandas/issues/49254

**Review by mroeschke — CHANGES_REQUESTED** [review]
As mentioned in https://github.com/pandas-dev/pandas/issues/49254#issuecomment-1289408116, these are technically methods since they accept an axis keyword:

Would you be interested in adding examples to the `loc` and `iloc` docstrings showing `axis` can be passed instead?

**Comment by datapythonista** [comment]
Thanks for taking care of this @EleekaN.

I guess this PR just removes the `()` after `.loc`... Even if it's not technically correct as @mroeschke I'm fine with it. But feel free to close @mroeschke if you prefer to be strict.

@EleekaN do you want to open a PR or an issue to add the suggested examples? Thanks!

**Comment by EleekaN** [comment]
Hi @datapythonista  and @mroeschke ......thank you for your time and for sharing your thoughts on my PR. 
I would really love to update what is requested; probably I will raise a separate issue on this. 
So, I guess we can close this PR without merging.

**Pull request closed without merging**
