### PR TITLE
CLN: Remove the Panel4D and PanelND classes

### PR DESCRIPTION
**Pull request by gfyoung**
Deprecated back in v0.19.0

xref #13147

### CODE REVIEW

**Comment by jreback** [comment]
love it! thanks!

**Comment by gfyoung** [comment]
@jreback : If you have any emotional attachment to that code, I'd be more than happy to create a separate branch where it lives on :smile:

**Comment by jreback** [comment]
hahah
i still prob have the original branch 
i don’t usually delete them (so i have thousands :)

**Comment by gfyoung** [comment]
> i still prob have the original branch
i don’t usually delete them (so i have thousands :)

Awesome, glad we resolved that (non-)issue :)

**Pull request merged**
