### PR TITLE
DOC: Fix errors in pandas.Series.argmax

### PR DESCRIPTION
**Pull request by farhanreynaldo**
- [x] closes https://github.com/pandanistas/pandanistas_sprint_jakarta2020/issues/18
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

output of `python scripts/validate_docstrings.py pandas.Series.argmax`:
```
################################################################################
################################## Validation ##################################
################################################################################
```

### CODE REVIEW

**Comment by MomIsBestFriend** [comment]
Isn't this a duplicate of #31999 ?

**Comment by farhanreynaldo** [comment]
> 
> 
> Isn't this a duplicate of #31999 ?

I think it is, I was trying to tackle 1 error on the issue and I pull request for the rest of error on the issue.

**Comment by MomIsBestFriend** [comment]
> > Isn't this a duplicate of #31999 ?
> 
> I think it is, I was trying to tackle 1 error on the issue and I made another pull request for the rest of error on the issue.

I think what happen was is that you ran ```git checkout``` from the branch you were working on, and you forgot to commit the rest of the changes.

**Comment by farhanreynaldo** [comment]
> 
> 
> > > Isn't this a duplicate of #31999 ?
> > 
> > 
> > I think it is, I was trying to tackle 1 error on the issue and I made another pull request for the rest of error on the issue.
> 
> I think what happen was is that you ran `git checkout` from the branch you were working on, and you forgot to commit the rest of the changes.

Oh I see. Thank you for let me know this. Anything I should do regarding the PR duplication?

**Comment by MomIsBestFriend** [comment]
> > > > Isn't this a duplicate of #31999 ?
> > > 
> > > 
> > > I think it is, I was trying to tackle 1 error on the issue and I made another pull request for the rest of error on the issue.
> > 
> > 
> > I think what happen was is that you ran `git checkout` from the branch you were working on, and you forgot to commit the rest of the changes.
> 
> Oh I see. Thank you for let me know this. Anything I should do regarding the PR duplication?

The way I see it, for this PR you can either close it or making the changes to initially intended to do.

---

Either way thank you for working on this!

**Pull request closed without merging**
