### PR TITLE
WEB/CI: Use GITHUB_TOKEN when making Github API calls

### PR DESCRIPTION
**Pull request by mroeschke**
Follow up to https://github.com/pandas-dev/pandas/pull/50811, might as well still make authenticated API calls to Github

### CODE REVIEW

**Comment by lithomas1** [comment]
Wouldn't you have to expose the token using a ``with:`` block as well?
(e.g. https://github.com/pandas-dev/pandas/blob/3d8993146ccb6054ecad6b7e97ee39e97c6d84e5/.github/workflows/ubuntu.yml#L177-L178 which is setting the environment-file env var)

I doubt that the GITHUB_TOKEN would be directly accessible without doing it (IIRC secrets are encrypted).

**Comment by mroeschke** [comment]
It's already here https://github.com/pandas-dev/pandas/blob/3d8993146ccb6054ecad6b7e97ee39e97c6d84e5/.github/workflows/docbuild-and-upload.yml#L18 (it wasn't removed in https://github.com/pandas-dev/pandas/pull/50811)

**Comment by lithomas1** [comment]
Ah, makes sense. Sorry for the noise.

**Review by lithomas1 — APPROVED** [review]

**Comment by datapythonista** [comment]
Sorry to remove that, I assumed it was to fix the quota problem, and that it didn't work. What is this doing? Is it increasing the quota, or something else?

**Comment by mroeschke** [comment]
Yeah I think authenticating with the GIthub Token bumps up our requests/hour (but is still limited) https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions

**Comment by datapythonista** [comment]
Did you check if the token is working as expected? I see github send some headers with the limits: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limit-headers

We should have quota for more than 20 web builds per hour with the 1,000 limit (not considering we were caching most of them in theory), and it felt that the CI was failing pretty quickly anyway. Since secrets aren't available for PRs, only for commits, I guess this may be indeed helping the commit builds, the ones that are deployed and really matter. Not sure if the failures I saw were mainly PRs.

**Pull request merged**
