### PR TITLE
CI, CLN remove unnecessary noqa statements, add CI check

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

This changes loads of files, but most changes are quite trivial

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

**Comment by dsaxton** [comment]
> This changes loads of files, but most changes are quite trivial

Many trivial improvements is a non-trivial improvement 😄

**Comment by jreback** [comment]
can you rebase just to make sure

**Comment by WillAyd** [comment]
Are we only down to F401 and F403? If so can we just fix the import machinery and get rid of noqa statements altogether? I think would be preferable to adding another tool to code checks

**Comment by MarcoGorelli** [comment]
Sure, have merged and pushed

@WillAyd in #36684 Jeff wrote

> ideally if we have a script to see these (maybe a grep is enough), and even better to have a code-check, but not sure how heavy handed that is.

Currently it only takes about 4-5 minutes to run all the checks we're doing in pre-commit on the entire codebase, and this one accounts for about 20 seconds.

FWIW, my suggestion would be to keep this in until the import machinery is fixed, and _then_ to remove it once there are no `noqa`s anymore

**Comment by jreback** [comment]
> Are we only down to F401 and F403? If so can we just fix the import machinery and get rid of noqa statements altogether? I think would be preferable to adding another tool to code checks

i don't think a big deal on time; these are on the azure builds and are still faster than travis so nbd.

**Comment by jreback** [comment]
thanks @MarcoGorelli

**Pull request merged**
