### PR TITLE
CLN: Remove special case for rank in groupby.ops

### PR DESCRIPTION
**Pull request by rhshadrach**
- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]
LGTM (failure unrelated)

**Comment by rhshadrach** [comment]
@mroeschke - I realized I could removed the TODO here. While I don't know why we couldn't do `out[:, k] = result` before, we certainly can't do it now.

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by mroeschke** [comment]
Thanks @rhshadrach

**Pull request merged**
