### PR TITLE
CI: fix numba typing

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
I think this broke tests

**Comment by MarcoGorelli** [comment]
you're right, thanks - just gotta `# type: ignore` it

**Comment by phofl** [comment]
updated to get the other fixes in

**Review by phofl — APPROVED** [review]

**Comment by MarcoGorelli** [comment]
thanks for review - merging then to get CI green

**Comment by MarcoGorelli** [comment]
> Can't Dooooo.... It seem like this is already backported (commit is empty).I won't do anything. MrMeeseeks out.

right, Matt had already made this change on 2.0.x

**Pull request merged**
