### PR TITLE
Unpin mypy

### PR DESCRIPTION
**Pull request by WillAyd**
Right now we have mypy 0.73 pinned in CI. However, newer versions will yield a lot of warnings like this:

```sh
pandas/core/groupby/base.py:32: error: "GroupByMixin" has no attribute "obj"
pandas/core/groupby/base.py:36: error: "GroupByMixin" has no attribute "_attributes"
pandas/core/groupby/base.py:40: error: "GroupByMixin" has no attribute "_groupby"
pandas/core/groupby/base.py:42: error: "GroupByMixin" has no attribute "_groupby"
pandas/core/groupby/base.py:44: error: Too many arguments for "GroupByMixin"
pandas/core/groupby/base.py:44: error: Unexpected keyword argument "groupby" for "GroupByMixin"
pandas/core/groupby/base.py:44: error: Unexpected keyword argument "parent" for "GroupByMixin"
pandas/core/groupby/base.py:45: error: "GroupByMixin" has no attribute "_reset_cache"
```

Most mixins we have will be problematic, if not all. Fortunately newer versions of mypy offer support for Protocols as a "self type", which were officially introduced in Python 3.8

This draft is an attempt at clarifying how that would work and seeing if it makes sense for the group. Depending on feedback, we may want to consider some kind of compat for this model to get it to work across Py36 and Py37 so our mypy doesn't lag too far behind

More info on the mypy release notes:

https://mypy-lang.blogspot.com/2019/11/mypy-0.html

@simonjayhawkins

### CODE REVIEW

**Comment by jbrockmendel** [comment]
could define in pandas._typing:

```
if PY38:
    from typing import Protocol
else:
    class Protocol:
         pass
```

I think I tried this with typing.final with mixed success

**Comment by WillAyd** [comment]
closing for now; hopefully food for thought in the future

**Comment by WillAyd** [comment]
I've repurposed this PR to try and unpin mypy 0.73 because the newer versions have a lot of great features that will work much better with the mix-ins that we have.

Unfortunately going to be a huge PR (in current state doens't work, actually causes more errors than before). Defining a protocol and checking for adherence on the DatetimeLike arena is where the difficulty lies

I'll post back when I have something reviewable

**Comment by simonjayhawkins** [comment]
@WillAyd I _think_ bumping mypy could(should) be kept seperate to introducing Protocols for Mixins. see https://github.com/pandas-dev/pandas/pull/29493#issuecomment-561165933

**Comment by simonjayhawkins** [comment]
bumping to mypy 0.740 is probably the most difficult bump, see https://github.com/pandas-dev/pandas/pull/28339#issuecomment-551972405 and https://github.com/pandas-dev/pandas/pull/28339#issuecomment-543684846

in #28339, I originally started to address some of the 0.740 issues (before reverting back to 0.730), so there is a small overlap with some of the changes here.

I will reopen #28339 temporarily and resync with my local branch. (for reference/comparison)

**Comment by WillAyd** [comment]
> @WillAyd I _think_ bumping mypy could(should) be kept seperate to introducing Protocols for Mixins. see [#29493 (comment)](https://github.com/pandas-dev/pandas/pull/29493#issuecomment-561165933)

Yea I was hoping this at first, but when looking at it I wasn't really sure of a way to solve all of the mix-in patterns we have and the mypy errors they throw without the Protocol. 

Maybe overlooked in what you linked but did you have alternate strategies in mind? Only other one I could think of is just ignoring errors in the datetimelike file where they occur, as that is probably more than half of the upgrade issues

**Comment by simonjayhawkins** [comment]
not looked at the specific errors for a while, and now we have more functions typed, it probably won't no longer be as simple as updating the check_untyped_defs list.

not used protocols, but my understanding of PEP 544 and looking at typeshed. my initial reaction is that the protocols added here are not in the spirit of protocols, but that's a subjective opinion.

the issue of Mixins and the use of Protocols in self types, came after PEP544 and the introduction of automatically assigning the self type to self in 0.740, so I appreciate that this issue needs to be addressed.

to help keep the code clean, we should probably put protocols in pandas._typing.

There are other uses of protocol such as user facing apis and using @runtime_checkable to potentially replace so is_* functions. Since there is also NoReturn, Literal and TypedDict, it may be worth a seperate PR for vendoring typing extensions. May also be better not to put in pandas/ so that our lint checks do not apply.

and bumping mypy is probably long overdue. so anything to keep the PR manageable welcome.

**Comment by simonjayhawkins** [comment]
just in case you want to update the list I use

mypy pandas --check-untyped-defs|grep -oP "^.*?(?=:)"|sort|uniq|sort|grep -oP "^.*?(?=\.)"|sed 's/\\/./g'|sed 's/^/[mypy-/'|sed 's/$/]\ncheck_untyped_defs=False\n/'

not elegant but works with the exception of clipboard which needs the \_\_init__ removed. Need to manually remove the check_untyped_defs overrides in setup.py first.

**Comment by WillAyd** [comment]
> not used protocols, but my understanding of PEP 544 and looking at typeshed. my initial reaction is that the protocols added here are not in the spirit of protocols, but that's a subjective opinion.

Can you clarify that more? FWIW I think ideally you would define the protocol first and keep it tight so subclasses can adhere to it. But we are tackling this from the other way where things are already defined so have to define the Protocol that fits the requirements in place. Makes the protocols more verbose than you would want for sure. 

Not sure if that's the issue you are describing or if you have something else in mind

**Comment by simonjayhawkins** [comment]
That sums it up, but I agree that the Mixin issue is a different use case.

**Comment by jbrockmendel** [comment]
is this actionable?

**Comment by simonjayhawkins** [comment]
> is this actionable?

we could deal with the Mixin issue now using a pattern described in https://github.com/python/mypy/issues/5837#issuecomment-433243772 and not actually call it a Protocol at this stage.

SomeRealClass would be the same as Protocol here, and the use of TYPE_CHECKING would make the base class only available when checking and leave the runtime behaviour unchanged. (i.e what Protocol is doing( without @runtime_checkable))

so adopting Protocol does not prevent unpinning mypy. These issues are orthogonal.

**Comment by WillAyd** [comment]
Closing again to clear queue. This is going to be tricky; probably a few ways to break up we can continue discussing here or in dedicated issues

**Comment by simonjayhawkins** [comment]
> we could deal with the Mixin issue now using a pattern described in [python/mypy#5837 (comment)](https://github.com/python/mypy/issues/5837#issuecomment-433243772) and not actually call it a Protocol at this stage.

FYI this pattern fails with Generic types, whereas Protocol could be generic.

This may be irrelevant to the decision at this stage if we are reluctant to use the Generic abc. The same discussion will probably arise for Protocol since it adds a base class at runtime as well and in some ways is not so different from Generic.

the protocols in this PR are not generic, so the pattern could be used.

**Pull request closed without merging**
