### PR TITLE
ENH: Timestamp.tz_localize support non-nano

### PR DESCRIPTION
**Pull request by jbrockmendel**
Sits on top of #47346

Not sure why the .github files are in the diff, they don't show up in the diff locally

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
I forgot if we discussed this prior, but what about frequencies larger than seconds? (day, hour, seconds)

I imagine those larger frequencies might cause problems here.

**Comment by jbrockmendel** [comment]
yah ATM we support s, ms, us, ns, raise on the other resos.  We could in principle support some of the others but im not aware of much demand for those, and they would impose other complications

**Comment by mroeschke** [comment]
Okay good to know. At what codepath would those larger frequencies raise? 

Curious because it would be nice to specifically raise in tz_localize/tz_convert that freq >= minute is not supported because DST is hard.

**Comment by jbrockmendel** [comment]
> Okay good to know. At what codepath would those larger frequencies raise?

In the constructor Timestamp._from_value_and_reso, though looks like I was wrong and minutes is allowed.  will change that in an upcoming PR (also Timedelta allows a bunch more resos that ill probably disable)

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
