### PR TITLE
DOC: Add Pandas-Bokeh to pandas ecosystem page

### PR DESCRIPTION
**Pull request by PatrikHlobil**
This PR adds Pandas-Bokeh reference to Pandas ecosystem page. 

Best, Patrik

### CODE REVIEW

**Comment by gfyoung** [comment]
Docs look good.  I would merge / rebase with `master` to re-trigger the CI.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
> Docs look good. I would merge / rebase with master to re-trigger the CI.

The docs and checks CI builds are passing, so a re-trigger is not needed I think.

**Comment by jorisvandenbossche** [comment]
Thanks @PatrikHlobil ! (and also thanks for working on the pandas-bokeh package!)

**Comment by PatrikHlobil** [comment]
@jorisvandenbossche : Thanks for reviewing this PR so fast and also thanks for working on Pandas ;)

**Pull request merged**
