### PR TITLE
CLN: Import abc from collections.abc in prep for py3.8

### PR DESCRIPTION
**Pull request by ghost**
#23750, and various issues on supporting upcoming python 3.8.

Azure (multiple):
```
[warning] Using or importing the ABCs from 'collections' instead 
of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

From https://docs.python.org/3/library/collections.html?highlight=collections#module-collections:
```
Changed in version 3.3: Moved Collections Abstract Base Classes to the 
collections.abc module. For backwards compatibility,  they continue to be 
visible in this module through Python 3.7.  
Subsequently, they will be removed entirely.
```

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
Looks good to me - this would show less warnings in tests right?

**Review by jorisvandenbossche — COMMENTED** [review]
I don't fully understand this PR. Isn't `from collections import abc` and `import collections.abc as abc` equivalent?

(I think many of the abc warnings in the tests are from other packages that we use)

**Comment by pilkibun** [comment]
You're right, I saw the test warning looked it up and completely misread the warning. 
It's `from collections import ABCfoo` which will break with 3.8, and I can't find any. Sorry for the noise.

**Comment by jorisvandenbossche** [comment]
No problem, the warnings are not always very clear in where they are coming from ..

**Comment by pilkibun** [comment]
btw, just as a sanity check, I verified and the two are not equivalent.
the abc symbol under a module and a sub-package are distinct things and can coexist (though its obviously not best practice). I simply misread where the warning was coming from.

**Pull request closed without merging**
