### PR TITLE
Bump s3fs to 2021.08.00

### LINKED ISSUE #48271: CI: newer version of s3fs is pulled causing builds to fail
Looks like we are pulling 0.6.0 (which is way smaller than our minimum version btw) instead of 0.4.2. The 0.6.0 requires aiobotocore, but is not compatible with the new version.

Working build:
https://github.com/pandas-dev/pandas/runs/8026125010?check_suite_focus=true

Failed build:
https://github.com/pandas-dev/pandas/runs/8035127801?check_suite_focus=true

Lets try to force at least the minimum s3fs version.

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #48271 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @mroeschke @lithomas1

### CODE REVIEW

**Comment by phofl** [comment]
Have to bump the others too

**Review by mroeschke — APPROVED** [review]
Nice! LGTM

**Review by lithomas1 — APPROVED** [review]

**Comment by lithomas1** [comment]
thanks @phofl

**Comment by lithomas1** [comment]
@meeseeksdev backport 1.5.x

**Pull request merged**
