### PR TITLE
BUG: Attributes are lost when subsetting columns in groupby

### LINKED ISSUE #9959: columns selection after groupby reset group_keys to True
```
df = pd.DataFrame({"g":[1, 2, 1, 2, 1], "a":range(5), "b":range(1, 6), "c":range(2, 7)})
g = df.groupby("g", group_keys=False)
print g.group_keys  #False
print g[["a", "b", "c"]].group_keys  #True
```

So the `apply()` results are different for these two case:

```
print g.apply(lambda x:x[:2])
```

ouput:

```
   a  b  c  g
0  0  1  2  1
2  2  3  4  1
1  1  2  3  2
3  3  4  5  2
```

but 

```
print g[["a", "b", "c"]].apply(lambda x:x[:2])
```

output:

```
     a  b  c
g           
1 0  0  1  2
  2  2  3  4
2 1  1  2  3
  3  3  4  5
```

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] closes #9959
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Avoiding the behavior of Series here, e.g. `df.groupby('a')['b']` as I think that will involve some API changes. Will follow up: ref #35443

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@rhshadrach test is failing on Linux py37_np_dev

```
=========================== short test summary info ============================
FAILED pandas/tests/groupby/test_groupby.py::test_subsetting_columns_keeps_attrs[squeeze-True]
=== 1 failed, 70023 passed, 4046 skipped, 1022 xfailed in 541.95s (0:09:01) ====
```

**Comment by rhshadrach** [comment]
Thanks @simonjayhawkins, passing now.

**Comment by jreback** [comment]
does this also close: https://github.com/pandas-dev/pandas/issues/35014 ?

**Comment by arw2019** [comment]
> does this also close: #35014 ?

@jreback I ran the OP in 35014 on this branch, the error persists

**Comment by jreback** [comment]
@rhshadrach can you merge master and ping on green.

**Comment by rhshadrach** [comment]
@jreback master has been merged, failures are unrelated

**Comment by simonjayhawkins** [comment]
> failures are unrelated

restarted 

<details>

```

C:\Miniconda\envs\pandas-dev\lib\site-packages\hypothesis\core.py:637: in execute_once
    self.__flaky(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <hypothesis.core.StateForActualGivenExecution object at 0x00000234496FE130>
message = 'Hypothesis test_shift_across_dst(offset=<0 * MonthBegins>) produces unreliable results: Falsified on the first call but did not on a subsequent one'

    def __flaky(self, message):
        if len(self.falsifying_examples) <= 1:
>           raise Flaky(message)
E           hypothesis.errors.Flaky: Hypothesis test_shift_across_dst(offset=<0 * MonthBegins>) produces unreliable results: Falsified on the first call but did not on a subsequent one

C:\Miniconda\envs\pandas-dev\lib\site-packages\hypothesis\core.py:847: Flaky
--------------------------------- Hypothesis ----------------------------------
Falsifying example: test_shift_across_dst(
    offset=<0 * MonthBegins>,
)
Unreliable test timings! On an initial run, this test took 884.81ms, which exceeded the deadline of 500.00ms, but on a subsequent run it took 1.18 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.

You can reproduce this example by temporarily adding @reproduce_failure('5.24.3', b'AAAAAAA=') as a decorator on your test case

```
</details>

**Comment by jreback** [comment]
wait, what happend to the tests?

**Comment by rhshadrach** [comment]
@arw2019 @jreback: I added all attributes to the `ndim=1` case except `as_index` and `axis` as these might be considered an API change. Failures are unrelated.

**Review by jreback — CHANGES_REQUESTED** [review]

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @rhshadrach 

good approach about separating something potentially controversial to another issue.

**Pull request merged**
