### PR TITLE
Fix blank line skipping in read_fwf, issue 22693

### LINKED ISSUE #22693: read_fwf: skip_blank_lines does nothing
#### Code Sample, a copy-pastable example if possible

```python
from io import StringIO
import pandas as pd

f = StringIO('''A B

C D''')

df = pd.read_fwf(f, colspecs=[(0, 1), (2,3)], header=None, skip_blank_lines=True)
print(df)
```

#### Problem description

Output:
```
     0    1
0    A    B
1  NaN  NaN
2    C    D
```

The (second) blank line is not skipped, but instead there is a row with two `NaN` values. It seems that `skip_blank_lines` has no effect on `read_fwf`. On the other hand, `read_csv(f, sep=' ', header=None)`, produces the expected output below.

#### Expected Output

```
   0  1
0  A  B
1  C  D
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.1
pytest: 3.6.2
pip: 18.0
setuptools: 39.0.1
Cython: None
numpy: 1.15.1
scipy: None
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: 1.5.5
patsy: None
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by xiejxie**
- [x] closes #22693 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Fixes the bug where blank lines are not skipped using read_fwf even when skip_blank_lines is set to true. Override default behaviour in FixedWidthFieldParser.

### CODE REVIEW

**Comment by jreback** [comment]
closing as stale. if you'd like to continue, pls ping.

**Comment by dvalters** [comment]
Hi, just wondering if we could pick this up and continue the work of @xiejxie here? Seems like we are on track towards a fix, just need a bit more iteration. (Also I think the current test might result in a false positive, as `read_csv` is also affected by the bug?)

**Comment by WillAyd** [comment]
@dwalters feel free to open a new PR

**Comment by TianyiPeng** [comment]
> Hi @jreback, just wondering if we could pick this up and continue the work of @xiejxie here? Seems like we are on track towards a fix, just need a bit more iteration. (Also I think the current test might result in a false positive, as `read_csv` is also affected by the bug?)

@dvalters I would like to help but not sure how to do it. Any intuition on how to fix the `read_csv` bug?

**Pull request closed without merging**
