### PR TITLE
CI: Don't auto-cancel on master

### LINKED ISSUE #42076: CI: disable auto-cancel for master branch
#41962 enabled auto-cancel for GitHub Actions on both master and PRs. Ideally, we should only have this feature turned on for PRs.

Auto-cancel is achieved with the `concurrency` feature. It looks like this:
```yaml
    concurrency:
      group: ${{ github.ref }}-xxx
      cancel-in-progress: true
```
The group attribute specifies a group name. So only one job can run for each group. 

To disable it for master, we need to select the appropriate workflow/job variables from https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions for the group name so that it's different for each commit to the master but identical for each PR.

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #42076 
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

I haven't tested that this skips the cancel on master branch, only that it cancels already running workflows on PRs(e.g. https://github.com/lithomas1/pandas/pull/3). 
So, be ready to revert if needed.

### CODE REVIEW

**Review by fangchenli — APPROVED** [review]
It should work.

**Comment by fangchenli** [comment]
One potential problem is this could cause a blockage if we merge many PRs in a short amount of time.

**Comment by jreback** [comment]
> One potential problem is this could cause a blockage if we merge many PRs in a short amount of time.

no this is ok / fine. as we used to do exactly this.

**Comment by jreback** [comment]
thanks @lithomas1 

if you'd monitor would be great.

**Pull request merged**
