### PR TITLE
Switch deps to Conda

### PR DESCRIPTION
**Pull request by jonashaag**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by attack68** [comment]
is there any discussion on this proposal and wider implications?

**Comment by jonashaag** [comment]
It’s a follow up to https://github.com/pandas-dev/pandas/pull/44817

**Review by lithomas1 — APPROVED** [review]

**Review by mroeschke — COMMENTED** [review]
LGTM. Could you merge main one more time?

**Comment by mroeschke** [comment]
Thanks @jonashaag

**Comment by mroeschke** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
