### PR TITLE
f-string update for core.base.

### PR DESCRIPTION
**Pull request by dplutcho**
- [ ] ref #29547
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by WillAyd — CHANGES_REQUESTED** [review]
Thanks for the PR. Looks good and I think CI failures are unrelated / have been fixed on master since this was created.

To be sure, can you locally on your feature-firstcontrib branch run:

```sh
git fetch upstream
git merge upstream/master
git push origin feature-firstcontrib
```

I think should get CI green for this. Flag me down at PyData if you have any questions

**Comment by dplutcho** [comment]
Done. All went fine. Do I need to do another pull request or is this all
set.

Darin Plutchok
206-909-3665

**Comment by WillAyd** [comment]
Don't need a new PR; just keep pushing to this. Looks like CI is running so let's see

**Review by simonjayhawkins — APPROVED** [review]
@dplutcho lgtm pending green ci.

**Comment by jreback** [comment]
thanks @dplutcho

**Pull request merged**
