### PR TITLE
DOC: remove inplace usage from docstring examples

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Removes the inplace=True usage examples from the docstring examples.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Looks good to me pending green

**Comment by phofl** [comment]
Removed 2 additional examples advertising copy=False

**Comment by MarcoGorelli** [comment]
is using `copy` discouraged as well? I may have missed that

if so, no objections, lgtm

**Comment by phofl** [comment]
copy=False will be the new default with CoW. copy=True can be done through ``df.func().copy()``, so we will propose removing the copy argument as well in PDEP7. Copy won't have any use in the future, so should remove the reference I guess.

**Comment by MarcoGorelli** [comment]
makes sense, thanks! anything else you wanted to get in here or good to merge?

**Comment by phofl** [comment]
Nothing I can think of right now, so good to go I think

**Comment by MarcoGorelli** [comment]
let's ship it, thanks @phofl !

**Pull request merged**
