### PR TITLE
BLD/CI fix arm64 build #36397

### LINKED ISSUE #30041: arm64 CI takes too much time to complete .
Hi, I am trying to add support for arm64 in travis CI for Pandas. but unfortunately, all tests are taking more than 50min to complete and hence, travis shows up :
`The job exceeded the maximum time limit for jobs, and has been terminated.`

I have attached the logs here:
[travis-ci-test.txt](https://github.com/pandas-dev/pandas/files/3921219/travis-ci-test.txt)

Can anyone help me to identify the root cause for this ?

### LINKED ISSUE #34149: CI: Moving ARM64 build from allowed failures
@jreback ,

As suggested in #30641 , adding an issue on moving ARM64 build from allow_failures tag in Travis-CI.

### LINKED ISSUE #36397: BLD/CI: fix arm64 builds
https://travis-ci.org/github/pandas-dev/pandas/jobs/727691006

these are failing (and have been for a while).

I believe we *can* now use the numpy wheels so this should make this build fast enough to include in the main matrix (and avoid using the often ignored allow_failures).

- [ ] use wheels for numpy
- [ ] remove from the allow_failures matrix

this could be for 1.1.3 or 1.2

### PR DESCRIPTION
**Pull request by fangchenli**
- [x] closes #36397 and 
closes #34149 and
closes #30041

### CODE REVIEW

**Comment by jreback** [comment]
I would put a market on most of tthese tests so we skip on arm64 (as too slow)

```
-- Docs: https://docs.pytest.org/en/stable/warnings.html
---- generated xml file: /home/travis/build/pandas-dev/pandas/test-data.xml ----
============================= slowest 30 durations =============================
64.26s call     pandas/tests/test_sorting.py::TestSorting::test_int64_overflow_moar
48.15s call     pandas/tests/groupby/transform/test_transform.py::test_cython_transform_frame[shift-args3-<lambda>]
47.99s call     pandas/tests/indexing/test_chaining_and_caching.py::TestChaining::test_detect_chained_assignment
44.52s call     pandas/tests/arithmetic/test_datetime64.py::TestDatetime64Arithmetic::test_dt64arr_add_timedeltalike_scalar[tzutc()-Timedelta-DataFrame]
42.54s call     pandas/tests/indexing/multiindex/test_chaining_and_caching.py::test_indexer_caching
38.96s call     pandas/tests/groupby/test_groupby_dropna.py::test_groupby_dropna_datetime_like_data[None-unique_nulls_fixture22-True-values0-datetime10-datetime20]
29.91s call     pandas/tests/frame/test_constructors.py::TestDataFrameConstructors::test_constructor_range_dtype[category]
29.43s call     pandas/tests/indexes/test_base.py::TestIndex::test_engine_reference_cycle
27.33s call     pandas/tests/tseries/offsets/test_offsets_properties.py::test_on_offset_implementations
26.79s call     pandas/tests/indexes/multi/test_duplicates.py::test_duplicated_large[first]
25.48s call     pandas/tests/indexes/multi/test_integrity.py::test_hash_collisions
25.16s call     pandas/tests/tseries/offsets/test_ticks.py::test_tick_equality[Nano]
23.06s call     pandas/tests/indexes/timedeltas/test_timedelta.py::TestTimedeltaIndex::test_engine_reference_cycle
22.52s call     pandas/tests/indexes/period/test_period.py::TestPeriodIndex::test_engine_reference_cycle
22.31s call     pandas/tests/indexes/categorical/test_category.py::TestCategoricalIndex::test_engine_reference_cycle
21.55s call     pandas/tests/indexes/test_base.py::TestMixedIntIndex::test_engine_reference_cycle
21.32s call     pandas/tests/indexes/datetimes/test_datetimelike.py::TestDatetimeIndex::test_engine_reference_cycle
21.02s call     pandas/tests/indexes/ranges/test_range.py::TestRangeIndex::test_engine_reference_cycle
20.21s call     pandas/tests/io/sas/test_sas7bdat.py::TestSAS7BDAT::test_iterator_loop
19.90s call     pandas/tests/io/sas/test_xport.py::TestXport::test1_basic
19.71s call     pandas/tests/groupby/transform/test_transform.py::test_cython_transform_frame[shift-args2-<lambda>]
18.88s call     pandas/tests/io/parser/test_parse_dates.py::test_bad_date_parse[python--True]
14.11s call     pandas/tests/io/sas/test_sas7bdat.py::TestSAS7BDAT::test_from_iterator
12.83s call     pandas/tests/io/parser/test_common.py::test_chunks_have_consistent_numerical_type[python]
11.45s call     pandas/tests/groupby/test_function.py::test_builtins_apply[keys1-min]
11.22s call     pandas/tests/io/parser/test_c_parser_only.py::test_grow_boundary_at_cap[c_low]
11.20s call     pandas/tests/generic/test_frame.py::TestDataFrame::test_head_tail[interval]
11.10s call     pandas/tests/io/parser/test_c_parser_only.py::test_grow_boundary_at_cap[c_high]
9.70s call     pandas/tests/groupby/test_function.py::test_builtins_apply[keys1-max]
9.38s call     pandas/tests/io/parser/test_common.py::test_warn_if_chunks_have_mismatched_type[python]
= 72115 passed, 4426 skipped, 1143 xfailed, 6 xpassed, 16 warnings in 1531.93s (0:25:31) =
```

**Comment by jreback** [comment]
retriggered this to see if the good perf repeats

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
cc @TomAugspurger @simonjayhawkins 

doing for 1.2 until really think we need it for 1.1.3 (its really just a ci patch)

**Comment by jreback** [comment]
2nd run wasn' bad 36 min

**Comment by simonjayhawkins** [comment]
> doing for 1.2 until really think we need it for 1.1.3 (its really just a ci patch)

no strong preference.

**Comment by WillAyd** [comment]
I think should back port unless we are really sure that 1.1.3 is the last bug fix release in the 1.1. series

**Comment by jreback** [comment]
> I think should back port unless we are really sure that 1.1.3 is the last bug fix release in the 1.1. series

fair enough.

**Comment by jreback** [comment]
thanks @VirosaLi 

this will likely be a manual backport as well :->

**Comment by fangchenli** [comment]
xref  #34131

**Pull request merged**
