### PR TITLE
TST: Period tests reorg (gh14854)

### PR DESCRIPTION
**Pull request by TrigonaMinima**
- [x] Almost completes #14854 
 - [x] tests reorg
 - [x] passes ``git diff upstream/master | flake8 --diff``
 - [x] whatsnew: Reorganization of ```Period``` tests.

### CODE REVIEW

**Comment by jreback** [comment]
whoosh that ``test_period`` was huge. ok. ping when green.

**Comment by TrigonaMinima** [comment]
hahah yeah. As a result, ```scalar/test_period.py``` and ```indexes/period/test_ops.py``` have gotten big as well.

**Comment by jreback** [comment]
yep
certainly can come back later and split things a bit

but let's wait on that for now

**Comment by jreback** [comment]
@TrigonaMinima going to merge shortly.

**Comment by jreback** [comment]
thanks again @TrigonaMinima !

if you are up for more :>

let's move the remainder of tseries/tests to pandas/tests/tseries

also let's remove tests/timeseries_legacy.py (and some of data can be removed as well).

BUT  should move any useful tests to a proper location. IOW the pickle things you can simply remove (they are really old). but some of the freq tests might be useful.

**Comment by TrigonaMinima** [comment]
Sure. I'll try to do it tonight.

I should also thank you. You are helping me alot throughout the way.

Is there something remaining to done in this PR?

**Comment by jreback** [comment]
closed via https://github.com/pandas-dev/pandas/commit/9ba10089f1c57d6fff569af39f0e6d37ee0210f5

@TrigonaMinima no this is all good. thanks!

**Pull request closed without merging**
