### PR TITLE
adding plotly to ecosystem

### PR DESCRIPTION
**Pull request by msund**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Thanks!

**Comment by msund** [comment]
Thanks for adding us @jorisvandenbossche; we're delighted to be included and a pandas tool :hammer:

**Comment by jorisvandenbossche** [comment]
@msund No problem! 
Just one question (which I didn't think of before merging it ..): I don't think plotly is fully open source, but you have a free (limited?) version? Is that correct?

If so, would you mind to add one sentence explaining the situation a little bit? (something in the line of "The free version includes .." or "The cloud based environment is free for public files", but you will know that better :-))

**Comment by msund** [comment]
Good idea, thanks. Does https://github.com/pydata/pandas/pull/10714 do it in the way you had in mind?

**Comment by jorisvandenbossche** [comment]
yes, that looks good! thanks

**Pull request merged**
