### PR TITLE
Added .editorconfig

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
What's this for? Most editors will recognize the settings in our setup.cfg.

**Comment by KOLANICH** [comment]
>Most editors will recognize the settings in our setup.cfg.

Most editors don't support `setup.cfg`. `.editorconfig` is a language-invariant way widely supported by editors.

**Comment by datapythonista** [comment]
-1 on this

@KOLANICH can you provide information on which scenario this could be useful?

**Comment by KOLANICH** [comment]
Contributing using Notepad++ as an editor.

**Comment by tacaswell** [comment]
xref https://github.com/matplotlib/matplotlib/pull/12922 https://github.com/scipy/scipy/pull/9560 https://github.com/scikit-learn/scikit-learn/pull/12710 and 17 others (see https://github.com/KOLANICH ).

I am :-1: on this (both here and else where).

**Comment by datapythonista** [comment]
thanks for the heads up @tacaswell

**Pull request closed without merging**
