### PR TITLE
CLN: helper attribute to check for ArrayManager

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/pandas-dev/pandas/pull/41878#discussion_r758514585

### CODE REVIEW

**Comment by jbrockmendel** [comment]
grepping for `hasattr.*blocks` shows a few more places this can be used

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/runs/4364239489?check_suite_focus=true some typing :-<

**Comment by jorisvandenbossche** [comment]
Any suggestion how to deal with this? Because if mypy doesn't understand the helper function, that basically means that you need to add a `cast` every time this is used ..

**Comment by jbrockmendel** [comment]
> Any suggestion how to deal with this? Because if mypy doesn't understand the helper function, that basically means that you need to add a cast (or ignore comment) every time this is used ..

1) `type: ignore`
2) add a `blocks` property to AM that raises NotImplementedError
3) ping @simonjayhawkins

**Comment by simonjayhawkins** [comment]
I assume would need to make DataFrame Generic and add the `_mgr` class as a type parameter. Since `_mgr` is private, not sure it this would be best practice from a typing perspective as the DataFrame typing is public.

https://mypy.readthedocs.io/en/stable/generics.html#generics

**Comment by simonjayhawkins** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
