### PR TITLE
AreaPlot:  add support for step drawstyle

### LINKED ISSUE #29451: Add ability to plot area kind with "steps" drawstyle
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame()
df['x'] = range(0,100,5)
df['y'] = range(0,1000,50)
df = df.set_index('x')

# stepped line plot 
df.plot.line()
plt.savefig('line')

# area plot
df.plot.line(drawstyle="steps")
plt.savefig('line-steps')


# Feature Request: stepped area plot
df.plot.area(drawstyle="steps")
plt.savefig('area-steps')

# Alternative solution, use bar plots.
df.plot.bar(width=1.0)
plt.savefig('bar')

```
#### Problem description

It would be nice to be able to create a "stepped" area plot.  Similar to a line(drawstyle="steps"),  but with the area under the line filled in:

 **df.plot.line(drawstyle="steps")**
image

As a work around,  I have been plotting a `bar` plot with `width=1.0`:  

**df.plot.bar(width=1.0)**
image

however this has issues of its own:

1. It is much slower with lots of data  
2. Will have to limit the xaxis labels,  by default it will generate a label per bar.
3. It doesn't interact well with line plots on a secondary y-axis 

Alternatively,  I think could manually resample the data,  but it would be really nice to have similar `drawstyle='steps'`

#### Expected Output

I would expect a plot similar to this:
image

### PR DESCRIPTION
**Pull request by nick-schultz**
- [ ] closes #29451
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
How are you calling this from a user perspective? Just a call to `.plot(kind="step")`? 

If you can add a test case would help frame the review - typically the most important part of any PR

**Comment by nick-schultz** [comment]
> How are you calling this from a user perspective? Just a call to `.plot(kind="step")`?
> 
> If you can add a test case would help frame the review - typically the most important part of any PR

I have some more discussion in my original issue #29451 .  It would be `.plot(kind='area', step='mid')`  or `.plot.area(step='mid')` .  I think the issue stems from the fact that matplotlib has two different APIs for specifying the draw style -  fill_between uses `steps`,  where the regular line plot uses `drawstyle`.

I look into adding a test.

**Comment by TomAugspurger** [comment]
Can users accomplish this behavior by passing in the correct keyword arguments, which are passed through to mpl?

**Comment by nick-schultz** [comment]
I don't believe so.

From what I can tell, [`AreaPlot._plot` ](https://github.com/pandas-dev/pandas/blob/6dbd2b1142a1fa1be33f031d319ee2ef7a49faef/pandas/plotting/_matplotlib/core.py#L1241) has two drawing calls, and each of them have different keywords for controlling the stepping behavior: 

1. drawing lines:
    -  `lines = MPLPlot._plot(ax, x, y_values, style=style, **line_kwds)`
    -   Keywords: **drawstyle**: {`default`, `steps`, `steps-pre`, `steps-mid`, `steps-post`}

2. filling area:
    -  `rect = ax.fill_between(xdata, start, y_values, **kwds)`
    - Keywords: **step**: {`pre`, `post`, and `mid`}


submitting the wrong keyword throws an assert, so the following does not work:

```
.plot.area(step='mid', drawstyle="steps-mid" )
```

as the first call to `MPLPlot._plot` will complain about seeing the `step` keyword

**Comment by WillAyd** [comment]
@nick-schultz is this still active? If so can you add a test case?

**Comment by jreback** [comment]
closing as stale, if you want to continue pls ping.

**Comment by rinatspb** [comment]
> How are you calling this from a user perspective? Just a call to `.plot(kind="step")`?

df.plot.area(drawstyle='steps-post')

**Pull request closed without merging**
