### PR TITLE
ENH: allow saving wide dataframes to hdf with format table

### PR DESCRIPTION
**Pull request by P-Tillmann**
based on #11788
closes #6245

This PR allows to save wide dataframes to hdf. It will break forward compatibility, old versions of pandas will not be able to read hdfs from new versions.
The column is saved to a vlarray with object atomic. This is rather slow for very wide dfs but does not require any type checks.
One test fails because the saved column is not compressed but the compression level is checked for all nodes. I think this is fine but i wanted to consult with you before rewriting the test.

Two tests were added to check if a wide df can be saved and if it is appendable.

Please let me know what you think and if there is additional need for test coverage.

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
in principle this change is ok, but this must be able to read existing arrays; so would need to commit some samples to the repo to test for this. once you can pass all of these tests I can have a look.

**Comment by P-Tillmann** [comment]
@jreback 
I included tests for several kinds of different column types that were stored with the current release version of pandas.
But I think i need some help with the failing tests. There are two tests failing:

1. "Docstring validation" and "Testing docstring validaton script" are failing. code_checks.sh runs fine locally. I don't understand how my changes are effecting these.

2. In one of the travis enviroments most pytables test fail with "ValueError: cannot set WRITEABLE flag to True of this array" This seems to be related to #24839. I can reproduce it locally by creating an environment with the corresponding environment.yml The tests are passed fine if I manually upgrade pytables to 3.5.1 (which was fixed to work with numpy 1.6).
If i understand correctly xfail_non_writeable was introduced in #25517 to prevent code that triggers this bug to fail the tests. By using vlarrays for all columns when format='table' this is now triggered for most tests. Does it makes sense to mask all the failing tests with xfail_non_writeable? Or is it more reasonable to not merge this PR until pytables 3.5.1 is the standard in all travis environments?

**Comment by jreback** [comment]
can you merge master and update

**Comment by P-Tillmann** [comment]
@jreback Updated.
1. "Docstring validation" and "Testing docstring validaton script" is ok now. 
2. "ValueError: cannot set WRITEABLE flag to True of this array" still leads to lots of fails in one of the test environments.

**Comment by jreback** [comment]
something is not right with your patch; merge upstream/master

**Comment by P-Tillmann** [comment]
Hi Jeff,
thanks for your feedback. I need some help understanding what the issue is. I just pulled upstream master and it merged without conflict. I don't have any local changes. Can you specify were the problem is?

**Comment by jreback** [comment]
maybe u didn’t push
the PR has 377 changed files

**Comment by P-Tillmann** [comment]
I see, thanks for the help. You were right, i didn't push.

**Comment by jreback** [comment]
can you merge master; note we moved the test_pytables to a subdirectory

**Comment by jbrockmendel** [comment]
@P-Tillmann can you rebase

**Comment by P-Tillmann** [comment]
@jreback @jbrockmendel I updated to current master. But travis stil has an environment with pytables "cannot set WRITEABLE flag" bug for vlarrays. And since this PR uses a lot of vlarrays it fails almost all tests.

**Comment by WillAyd** [comment]
Closing as stale but if this is still relevant please ping and can reopen

**Pull request closed without merging**
