### PR TITLE
(📚) update docs to mention 3.11 support

### LINKED ISSUE #49301: DOC: Update docs to indicate python 3.11 support
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/getting_started/install.html

https://pypi.org/project/pandas/

### Documentation problem

We should update our docs, and the pypi page to indicate that python 3.11 is supported.

### Suggested fix for documentation

Update the docs page (and publish it!!) and pyproject.toml to show 3.11 support.

### PR DESCRIPTION
**Pull request by KotlinIsland**
- [x] closes #49301 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by lithomas1** [comment]
Can you add a line below https://github.com/pandas-dev/pandas/blame/main/setup.cfg#L25 for Python 3.11, and also below https://github.com/pandas-dev/pandas/blame/main/setup.cfg#L25 (where Python 3.11 would install numpy 1.23.2)?

I think we also need to bump oldest-supported-numpy to >= 2022.8.16 here https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L8. 

Sorry for the mess, I overlooked this when I added the initial support. Let me know if you have any other questions.

**Comment by KotlinIsland** [comment]
TODO: Update `3.11-dev` to `3.11` now that Marcos has a release.

**Comment by KotlinIsland** [comment]
@lithomas1 

> Can you add a line below https://github.com/pandas-dev/pandas/blame/main/setup.cfg#L25 for Python 3.11

I have already added a trove classifier for 3.11 in setup.cfg.

> , and also below https://github.com/pandas-dev/pandas/blame/main/setup.cfg#L25 (where Python 3.11 would install numpy 1.23.2)?

This is the same link as before, did you mean in the `install_requires` section? I've updated this.

Want to take another look now?

**Review by lithomas1 — APPROVED** [review]
LGTM. Thanks for the PR!

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @KotlinIsland

**Comment by mroeschke** [comment]
@KotlinIsland mind following the instructions to submit a backport PR? (will need to target the 1.5.x branch)

**Comment by KotlinIsland** [comment]
Attention rick-and-morty bot, I have done it! I have done some good work! I wonder if I will turn into a Pickle! I'll be Pickle-KotlinIsland!!!!! (#49440)

**Comment by KotlinIsland** [comment]
@mroeschke I found this 

https://github.com/pandas-dev/pandas/blob/46cb18c4a021f5058f9018aa9c3106cfc7914aa7/.github/workflows/sdist.yml#L33

and this

https://github.com/pandas-dev/pandas/blob/46cb18c4a021f5058f9018aa9c3106cfc7914aa7/.github/workflows/sdist.yml#L82-L89

Does this need to be updated to 3.11 as well?

**Comment by mroeschke** [comment]
Nice find @KotlinIsland, yeah it would be great to update that sdist build with 3.11 as well

**Comment by KotlinIsland** [comment]
#49460

**Pull request merged**
