### PR TITLE
WIP/TST/ENH: require freq match in assert_index_equal

### PR DESCRIPTION
**Pull request by jbrockmendel**
582 tests are failing locally, so there's some work yet to be done.

@mroeschke 3 of those 582 are in window tests.  Can you take a look and suggest where an edit should go?

### CODE REVIEW

**Comment by mroeschke** [comment]
@jbrockmendel sorry which tests in this PR should I look at that relate to the window test?

**Comment by jbrockmendel** [comment]
@mroeschke from the azure py37 build, the last ~4 failures are for window tests, e.g.:

```
________________________ test_rolling_window_as_string _________________________
[gw0] linux -- Python 3.7.6 /home/vsts/miniconda3/envs/pandas-dev/bin/python

    def test_rolling_window_as_string():
        # see gh-22590
        date_today = datetime.now()
        days = pd.date_range(date_today, date_today + timedelta(365), freq="D")
    
        npr = np.random.RandomState(seed=421)
    
        data = npr.randint(1, high=100, size=len(days))
        df = DataFrame({"DateCol": days, "metric": data})
    
        df.set_index("DateCol", inplace=True)
        result = df.rolling(window="21D", min_periods=2, closed="left")["metric"].agg("max")
E       [left]:  None
E       [right]: <Day>

pandas/tests/window/moments/test_moments_rolling.py:1412: AssertionError
```

**Comment by mroeschke** [comment]
@jbrockmendel after a cursory glance at the rolling failures, looks like the construction of the `expected` DataFrame/Series needs to include frequency. The `rolling` operation is adding `freq` to the index.

**Comment by jbrockmendel** [comment]
closing to clear the queue, will continue to chip away this locally

**Pull request closed without merging**
