### PR TITLE
[WIP] set_axis now has inplace=False

### LINKED ISSUE #14636: API: set_axis does not have inplace=False
http://pandas.pydata.org/pandas-docs/version/0.19.1/generated/pandas.DataFrame.set_axis.html

### PR DESCRIPTION
**Pull request by den-run-ai**
- [ ] closes #14636
 - [ ] tests added / passed
 - [ ] passes ``git diff upstream/master | flake8 --diff``
 - [ ] whatsnew entry

### CODE REVIEW

**Comment by denfromufa** [comment]
https://github.com/pandas-dev/pandas/issues/14636

**Comment by jreback** [comment]
needs tests and lint fixing (which will now show up after you rebase)

**Comment by jreback** [comment]
@denfromufa can you add tests?

**Comment by jreback** [comment]
closing as stale

**Pull request closed without merging**
