### PR TITLE
ENH: make Tick comparisons match Timedelta behavior

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Can you indicate if (I assume so, given the title), and if so, what behaviour exactly changed?

**Comment by jbrockmendel** [comment]
> Can you indicate if (I assume so, given the title), and if so, what behaviour exactly changed?

`pd.offsets.Minute(3) < pd.Timedelta(4)` will now return `False` instead of raising `TypeError`

**Comment by jreback** [comment]
looks fine, can you add a whatsnew note

**Comment by jbrockmendel** [comment]
updated with whatsnew + green

**Pull request merged**
