### PR TITLE
 BUG: warning shown when parsing delimited date string even if users can't do anything about it

### LINKED ISSUE #50231: WARN: warning shown when parsing delimited date string even if users can't do anything about it
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
In [2]: Timestamp('13-01-2000')
<ipython-input-2-710ff60ba7e6>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  Timestamp('13-01-2000')
Out[2]: Timestamp('2000-01-13 00:00:00')
```

### Issue Description

This was added in #42908 

This helped warn about some of the inconsistencies in #12585, but it's now unnecessary

This warning only shows up when using `Timestamp` - however, users can't pass `format` or `dayfirst` to `Timestamp`, so the warning is unnecessary

If people use `to_datetime`, there's already the more informative message(s) from PDEP4:
```
In [1]: to_datetime('13-01-2000')
<ipython-input-1-9a129e754905>:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  to_datetime('13-01-2000')
Out[1]: Timestamp('2000-01-13 00:00:00')
```

If we remove the warning from `parse_delimited_date`, then `to_datetime` will keep its informative warnings from PDEP4, and `Timestamp` will no longer show a warning which users can't do anything about

### Expected Behavior

```
In [2]: Timestamp('13-01-2000')
Out[2]: Timestamp('2000-01-13 00:00:00')
```

### Installed Versions

<details>

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/marcogorelli/pandas-dev/pandas/util/_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "/home/marcogorelli/pandas-dev/pandas/util/_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "/home/marcogorelli/pandas-dev/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/home/marcogorelli/mambaforge/envs/pandas-dev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/marcogorelli/mambaforge/envs/pandas-dev/lib/python3.8/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/marcogorelli/mambaforge/envs/pandas-dev/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/marcogorelli/mambaforge/envs/pandas-dev/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [ ] closes #50231  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]
LGTM

**Comment by jbrockmendel** [comment]
are there any contexts where we _do_ want to issue a warning?

**Comment by MarcoGorelli** [comment]
I wouldn't think so, because users can't pass `format` nor `dayfirst` to Timestamp

If anything, maybe Timestamp should become stricter and only accept iso8601 strings?

**Comment by jbrockmendel** [comment]
> I wouldn't think so, because users can't pass format nor dayfirst to Timestamp

i meant more along the lines of if the warning should be issued when we are parsing sequences.  (so it would need to be issued somewhere else presumably)

**Comment by MarcoGorelli** [comment]
Timestamp doesn't accept sequences, and to_datetime already warns - I've probably misunderstood though, is there another path that accepts sequences that might get here? I'll check more carefully tomorrow

**Comment by jbrockmendel** [comment]
> and to_datetime already warns

wasnt aware of that.  all good here.

**Comment by jbrockmendel** [comment]
> If anything, maybe Timestamp should become stricter and only accept iso8601 strings?

id be OK with more strict than the status quo (problems have been caused by the parsing code accepting "t2m", though Timestamp still rejects that as OOB for nanosecond reso).  iso8601-only is probably too strict for my tastes

long long ago i wrote a dateutil-like parser that passed all/most of the dateutill tests and IIRC it was mostly just a handful of regexes (and appreciably more performant).  ill see if i can dig that up.

**Comment by MarcoGorelli** [comment]
> > and to_datetime already warns
> 
> wasnt aware of that. all good here.

thanks! merging then

**Pull request merged**
