### PR TITLE
CI Fix w/o tm helper

### PR DESCRIPTION
**Pull request by WillAyd**
Alternate to #31791

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

**Comment by MomIsBestFriend** [comment]
TBH I am ```-1``` on that, as we are trying to get rid of all the ```bare pytest raises```.
maybe the name of ```external_error_raised``` is not good, and needs a different (and better) name.

**Comment by WillAyd** [comment]
@momisbestfriend the problem is that helper isn’t backported so can’t be used to fix CI

**Comment by jreback** [comment]
> @MomIsBestFriend the problem is that helper isn’t backported so can’t be used to fix CI

we can simply backport the helper, no?

**Comment by WillAyd** [comment]
Sure that would be an alternative

**Comment by WillAyd** [comment]
Looks like the CI failures may have resolved themselves on the 1.0.x branch, so I guess no need to do this. However, should probably revert original PR then - @jbrockmendel do you agree? Something you have time to tackle?

**Comment by jbrockmendel** [comment]
> Something you have time to tackle?

I'm stretched pretty thin ATM.  Won't hitting the green button here get the job done?

**Comment by WillAyd** [comment]
Closing in favor of #31931

**Pull request closed without merging**
