### PR TITLE
DEV: remove geopandas from the environment.yml file

### PR DESCRIPTION
**Pull request by StefanieSenger**
- [x] closes #https://github.com/noatamir/pyladies-berlin-sprints/issues/9
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks for working on this

@mroeschke you'd said you wanted the environment to enable people to run anything - should this single downstream test be removed?

**Comment by MarcoGorelli** [comment]
Hi @StefanieSenger - did you close this by accident? I think it looks right, I just wanted to double-check with Matthew whether we should also remove the downstream test or whether this is fine as-is

**Comment by StefanieSenger** [comment]
@MarcoGorelli I must have, though I didn't realise I did ... Sorry, I'd keep it open.

**Comment by mroeschke** [comment]
Yeah I would be partial to be consistent and remove geopandas everywhere if we also want to remove it from the `environment.yml` for consistency (CI dependency files, unit tests, any ASVs, any doc reference)

**Comment by phofl** [comment]
@StefanieSenger could you remove it from the environment.yml again? 

Additionally, you can delete the test ``test_geopandas`` in pandas/tests/test_downstream.py to get the ci passing. We can reopen the pr then

**Comment by jorisvandenbossche** [comment]
@StefanieSenger if you want to reopen the PR, you will first have to "restore" the branch (there should be a button somewhere in the UI)

**Comment by StefanieSenger** [comment]
Thanks for the instructions and the beginner friendly atmosphere. I will do this some time today.

**Pull request closed without merging**
