### PR TITLE
DOC/TST: doctests leaving extraneous files

### LINKED ISSUE #23201: DOC/TST: doctests leaving extraneous files
after running

``LINT=1 ci/code_check.sh``

we get some garbage left around

```
(pandas) bash-3.2$ git st
On branch PR_TOOL_MERGE_PR_23096
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        df.parquet.gzip
        df_info.txt
        output.xlsx
        output1.xlsx

nothing added to commit but untracked files present (use "git add" to track)
```

### PR DESCRIPTION
**Pull request by RomainSa**
- [x] closes #23201 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by datapythonista** [comment]
Looks good.

@RomainSa did you run the doctests (the command is in the issue description) and verified that no file is created after running them?

**Comment by RomainSa** [comment]
Yes, I used the command in issue description:
```
LINT=1 ci/code_check.sh
```
along with the ```git status``` command to make sure that the files initially created by the doctests were not created anymore after using the +SKIP flag

**Review by datapythonista — APPROVED** [review]
Nice, looks great, and nothing else should be created then, I guess.

Thanks for fixing it @RomainSa

**Comment by RomainSa** [comment]
You're welcome, thanks for your feedback @datapythonista !

**Comment by jreback** [comment]
thanks @RomainSa

**Pull request merged**
