### PR TITLE
DOC: Fix minimum Python version in contributing docs

### LINKED ISSUE #40485: DOC: Outdated Python version in contributing docs
#### Location of the documentation
[URL of the documentation](https://pandas.pydata.org/docs/development/contributing.html#creating-a-python-environment-pip)

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).
(Problem exist in the latest version: [here](https://pandas.pydata.org/docs/dev/development/contributing.html?highlight=contributing#creating-a-python-environment-pip))
#### Documentation problem

In the documents, it says  `at least Python 3.6.1 installed` to create Python virtual environment to contribute Pandas. However, to install some development requirements (such as NumPy) Python version must be >=3.7. See [here](https://pypi.org/project/numpy/) for NumPy minimum requirement.

#### Suggested fix for documentation
We should update the relevant document so contributors can install an appropriate virtual environment for contribution.
Suggested edit:
 `You’ll need to have at least Python 3.7 installed on your system.`

### PR DESCRIPTION
**Pull request by hasan-yaman**
- [x] closes #40485

### CODE REVIEW

**Comment by hasan-yaman** [comment]
I think the failed check also fails in the current master. So, what should I do?

**Comment by attack68** [comment]
> I think the failed check also fails in the current master. So, what should I do?

nothing. just wait. it might get approved without, or you might be asked to rebase when master goes green again (gets fixed)

**Comment by hasan-yaman** [comment]
Thanks for the explanation.

**Comment by MarcoGorelli** [comment]
Hi @hasan-yaman - could you fetch and merge upstream/master please?

**Comment by MarcoGorelli** [comment]
Thanks @hasan-yaman for updating - let's just wait for #40130 to be in before proceeding here

**Comment by MarcoGorelli** [comment]
#40130 is in - @hasan-yaman if you rebase and ping when ready this should be good to go

**Comment by hasan-yaman** [comment]
@MarcoGorelli 

I moved the changes to contributing_environment.rst

Thanks for your help.

**Review by MarcoGorelli — APPROVED** [review]
Thanks @hasan-yaman , looks good to me pending green

**Pull request merged**
