### PR TITLE
inspect-safety for DataFrame._constructor_expanddim

### LINKED ISSUE #31474: Not supported for DataFrames Exception triggered by a simple inspect.getmembers() call on a DataFrame
#### Code Sample, a copy-pastable example if possible

```python
import inspect
import pandas as pd
df = pd.DataFrame()
try:
   members = inspect.getmembers(df)
except Exception as e:
   print(e)

```
#### Problem description

A "**Not supported for DataFrames Exception**" is triggered by a simple inspect.getmembers() call on a DataFrame instance.  There are some useful libraries like the Python 'fire' library which are disabled by this bug, which was not present in Pandas Release 0.24.2 but emerged in 0.25.0

#### Expected Output

A list of DataFrame members (without crashing)

#### Output of ``pd.show_versions()``

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-26-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #31549, closes #31474
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by TomAugspurger — COMMENTED** [review]
LGTM, once you get the jinja2 thing sorted out.

**Comment by TomAugspurger** [comment]
Ah, interesting, it's  failing *without* jinja2, since `df.style` returns a Styler, which requires jinja2 to initialize.

I'm fine with just ignoring this for now, and essentially requiring jinaj2 for `inspect.getmembers` to work.

**Comment by jbrockmendel** [comment]
> I'm fine with just ignoring this for now, and essentially requiring jinaj2 for inspect.getmembers to work.

agreed

**Comment by jreback** [comment]
thanks

**Comment by simonjayhawkins** [comment]
how about a follow-up for Series._constructor_sliced

**Pull request merged**
