### PR TITLE
Removing dict calls

### PR DESCRIPTION
**Pull request by joao-zanutto**
- [ ] xref #38138 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Removed the dict calls for the files:

`./pandas/core/arrays/floating.py`
`./pandas/core/arrays/numpy_.py`
`./pandas/core/arrays/interval.py`

### CODE REVIEW

**Review by arw2019 — COMMENTED** [review]
thanks for doing this!

There's pre-commit failure (styling issue)

**Comment by zanuttin** [comment]
@arw2019 thanks for your attention! I have used flake8 for the three files that I modified and it returned nothing for me, can you help me on how I can solve this issue?

**Comment by arw2019** [comment]
> @arw2019 thanks for your attention! I have used flake8 for the three files that I modified and it returned nothing for me, can you help me on how I can solve this issue?

if you run the precommit tool locally it will take care of this

**Comment by zanuttin** [comment]
Hey @arw2019 looks like my modifications passed the checks by removing the conflict with another branch. Thanks for your help.

**Comment by jreback** [comment]
thanks @zanuttin

**Pull request merged**
