### PR TITLE
ENH: Added warning when excel file contains duplicate column names

### PR DESCRIPTION
**Pull request by terrytangyuan**
See #10970 and #10982. Users face bugs but no informative errors are given. This should warn them and inform them what might be wrong.

### CODE REVIEW

**Comment by jreback** [comment]
rather than a warning, should be able to handle this.  of course a tests would help

**Comment by terrytangyuan** [comment]
So like automatic renaming duplicate column names?

**Comment by jreback** [comment]
no, they should simply be handled.

**Comment by terrytangyuan** [comment]
When I run tests `nosetests pandas/io/tests/test_excel.py`, I got a lot of errors but the code is just pulled from master without any changes. Could anyone try it on your end?

**Pull request closed without merging**
