### PR TITLE
DEPR: remove deprecated keywords in read_excel, to_records

### PR DESCRIPTION
**Pull request by jbrockmendel**
There are a handful of these PRs on the way and they're inevitably going to have whatsnew conflicts.  I'm trying to group together related deprecations so as to have a single-digit number of PRs for these.

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm - thanks for tackling this

@gfyoung care to take a look?

**Comment by jreback** [comment]
lgtm. needs a rebase

**Comment by jbrockmendel** [comment]
rebased+green

**Comment by WillAyd** [comment]
Thanks @jbrockmendel

**Pull request merged**
