### PR TITLE
TST: Fix maybe_promote xfails

### PR DESCRIPTION
**Pull request by jbrockmendel**
Fix a handful of these, clean up a bunch of others.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
This gets towards the end of what I can clean up without major changes.  I'm inclined to try to remove the `box=True` cases and disallow ndarray `fill_value` arg, which would simplify the code a bit and the tests a ton.  AFAICT we can do this without breaking any existing tests (outside of tests for `dtypes.cast`), but I don't think we can rule out it being _possible_ to get there in the handful of places where maybe_promote is called.

**Comment by jbrockmendel** [comment]
Reverted unnecessary test cleanup to make a smaller diff

**Comment by jreback** [comment]
maybe rebase this as we merged a few other things, ping on green.

**Comment by jbrockmendel** [comment]
sure.  heads up: im out of town until monday, will be less responsive than usual

**Comment by jbrockmendel** [comment]
ping

**Comment by jreback** [comment]
thanks

**Pull request merged**
