### PR TITLE
rewrite dict as literal in tests/io/parser/test_index_col.py

### PR DESCRIPTION
**Pull request by pillemer**
for issue # 38138 
rewrite unnecessary dict call as a literal in pandas/tests/io/parser/test_index_col.py

Please let me know if anything needs to be amended, changed or fixed. I'm new to contributing.

- [ ] issue #38138 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by mroeschke** [comment]
Thanks. Could you fix up the linting errors?

**Comment by pillemer** [comment]
@mroeschke, no problem, done! Is there anything else?

**Comment by MarcoGorelli** [comment]
> @mroeschke, no problem, done! Is there anything else?

There's still some failures, could you try again please? 
```
pre-commit run --files pandas/tests/io/parser/test_index_col.py
```

**Comment by MarcoGorelli** [comment]
closing as it looks like this one's already been done, sorry about that

**Pull request closed without merging**
