### PR TITLE
BUG: DataFrame with scalar tzaware Timestamp

### LINKED ISSUE #42505: BUG: Regression - AmbiguousTimeError creating DataFrame
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

Pandas 1.25:
```python
import pandas as pd
dt = pd.to_datetime('2019-11-03 01:00:00-0700').tz_convert('America/Los_Angeles')
pd.DataFrame({'dt': dt, 'value': [1]})
#                          dt  value
# 0 2019-11-03 01:00:00-07:00      1
```
Pandas 1.3:
```python
import pandas as pd
dt = pd.to_datetime('2019-11-03 01:00:00-0700').tz_convert('America/Los_Angeles')
pd.DataFrame({'dt': dt, 'value': [1]})

#  File "pandas/_libs/tslibs/tzconversion.pyx", line 284, in pandas._libs.tslibs.tzconversion.tz_localize_to_utc
# pytz.exceptions.AmbiguousTimeError: Cannot infer dst time from 2019-11-03 01:00:00, try using the 'ambiguous' argument
```

#### Problem description

The `dt` object already has a timezone attribute, so it shouldn't be converting/inferring at all.

#### Expected Output

1.25 and 1.3.0 should have the same output.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.5.0
Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0
numpy            : 1.21.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 57.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.1 (dt dec pq3 ext lo64)
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #42505
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

@simonjayhawkins where does the whatsnew for this go?

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins where does the whatsnew for this go?

wdyt?

`sequence_to_dt64ns` is called from `sequence_to_datetimes` which is called from `maybe_infer_to_datetimelike` and `maybe_cast_to_datetime` in  `pandas/core/dtypes/cast.py` so this change is not narrowly targeted to the reported issue or reverting to previous behavior.

I have no doubt that this is the correct long term fix, option 2 in https://github.com/pandas-dev/pandas/issues/42505#issuecomment-972787122 but not sure if other interactions would expose other latent bugs.

This is fine for 1.4 IMO, but would a more narrowly targeted fix for 1.3.5 be safer, option 3 in https://github.com/pandas-dev/pandas/issues/42505#issuecomment-972787122

We must have little testing of scalars passed to `DatetimeArray._from_sequence`. Is there a risk that fixing this properly here change any existing behavior?

**Comment by jbrockmendel** [comment]
> wdyt?

I guess for now put it in the 1.4 file and discuss whether to backport?

> We must have little testing of scalars passed to DatetimeArray._from_sequence. Is there a risk that fixing this properly here change any existing behavior?

Only incorrect behavior AFAICT.

> but would a more narrowly targeted fix for 1.3.5 be safer, option 3 in #42505 (comment)

I'm not clear on how we can get more targeted than this.

**Comment by jreback** [comment]
this is fine, can you add a whatsnew for 1.3.5

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Comment by jreback** [comment]
@jbrockmendel if you can push the backport :-<>

**Comment by simonjayhawkins** [comment]
> > but would a more narrowly targeted fix for 1.3.5 be safer, option 3 in #42505 (comment)
> 
> I'm not clear on how we can get more targeted than this.

I was thinking special case in `construct_1d_arraylike_from_scalar`. The return type from `infer_dtype_from_scalar` is now a `Timestamp` whereas it was a `int` in pandas 1.2.5

So we then have the block... `if isinstance(dtype, ExtensionDtype)` where we pass the value onto `DataTimeArray._from_sequence`, so my thinking was to pass value.value if is instance of Timestamp to restore the 1.2.5 behavior explicitly without touching `DataTimeArray._from_sequence`.

so I was thinking something like...

```diff
diff --git a/pandas/core/dtypes/cast.py b/pandas/core/dtypes/cast.py
index 6d5162f3fe..a02e8e085c 100644
--- a/pandas/core/dtypes/cast.py
+++ b/pandas/core/dtypes/cast.py
@@ -1900,6 +1900,8 @@ def construct_1d_arraylike_from_scalar(
 
     """
 
+    from pandas.core.arrays import DatetimeArray
+
     if dtype is None:
         try:
             dtype, value = infer_dtype_from_scalar(value, pandas_dtype=True)
@@ -1908,6 +1910,8 @@ def construct_1d_arraylike_from_scalar(
 
     if isinstance(dtype, ExtensionDtype):
         cls = dtype.construct_array_type()
+        if issubclass(cls, DatetimeArray) and isinstance(value, Timestamp):
+            value = value.value
         subarr = cls._from_sequence([value] * length, dtype=dtype)
 
     else:
```

with an appropriate code comment about the hack.

The non-extension array block seems to include some special handling for `dtype.kind in ["M", "m"]` to unbox the values so this location for a fix, unboxing the values from a TimeStamp is maybe not so strange after all?

> > We must have little testing of scalars passed to DatetimeArray._from_sequence. Is there a risk that fixing this properly here change any existing behavior?
> 
> Only incorrect behavior AFAICT.

yes. any change in behavior from doing the proper fix for 1.3.5 can probably be put under the "bug fix" umbrella, so maybe this is fine.

**Pull request merged**
