### PR TITLE
TYP: Remove  _ensure_type

### LINKED ISSUE #31925: pandas.DataFrame.reindex_like throws if called from a derived class instance
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import pandas.testing as pdt

class MyDataFrame(pd.DataFrame):
    pass

mdf = MyDataFrame()
df = pd.DataFrame()
# In DataFrame.reindex_like, the derived class is compared to
# the base class. The following line will throw
# 'AssertionError: <class 'pandas.core.frame.DataFrame'>'
mdf.reindex_like(df)

# In pdt.assert_frame_equal,
# check_like=True triggers a call to DataFrame.reindex_like.
# The following line will throw the same
# 'AssertionError: <class 'pandas.core.frame.DataFrame'>'
pdt.assert_frame_equal(mdf, df, check_like=True)
```
#### Problem description

The method `reindex_like` throws an `AssertionError` when the caller is an instance of a derived class of `pandas.DataFrame`.

#### Expected Output

No exception thrown.

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-65-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 39.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : 0.999999999
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

### PR DESCRIPTION
**Pull request by simonjayhawkins**
- [ ] closes #31925
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@TomAugspurger do we also want to add a test and a whatsnew, or merge these changes into original PR?

**Comment by TomAugspurger** [comment]
Thanks! This seems good for now. I don't think we would need any additional tests, but a whatsnew would be nice (fixed regression).

**Comment by simonjayhawkins** [comment]
ok can revert test. will add whatsnew.

**Review by TomAugspurger — APPROVED** [review]

**Comment by TomAugspurger** [comment]
No harm in keeping the test.

**Comment by WillAyd** [comment]
lgtm. w.r.t. test no strong preference, though do we see ourselves getting confused with that in the future? 

Maybe just my lack of familiarity with our subclassing, but not sure why we would want a reindex to return a different type than the caller

**Comment by TomAugspurger** [comment]
I think we'll be able to track it back to this discussion.

But yes, I think in general the return type on `_constructor` should be the same as the input, but how we go about encouraging / requiring that is a bigger discussion.

**Pull request merged**
