### PR TITLE
REF: separate flex from non-flex DataFrame ops

### LINKED ISSUE #36796: API: disallow frame.__and__(other, axis="foo", fill_value="bar") etc
For code-sharing purposes we re-use ops.arith_method_FRAME for both flex and non-flex methods.  As a result, the non-flex methods have the flex signature, and accept arguments not generally accepted by dunder methods.  We even have a few tests e.g.

```
result = d.__and__(s, axis="columns")
result = d.__and__(s, axis=0)
```

in tests.frame.test_operators.

Should we disallow passing these arguments?  Is it relevant that we do _not_ have flex versions of and/or/xor?

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #36796
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Unless supporting this is intentional, in which case we should deprecate and explicitly implement flex-bool operations.

If/when this is done, we can stop passing `special` and even `cls`.

### CODE REVIEW

**Comment by jreback** [comment]
i guess technicaly this is an api change, so add a note.

cc @TomAugspurger if any comments.

**Comment by TomAugspurger** [comment]
I'm not sure what a "flex" method is. What's the user-facing change here?

**Comment by jbrockmendel** [comment]
"flex" methods are all the non-dunder arith/cmp ops: add, sub, eq, ne, ...

The user facing change is that `frame.__and__(other, axis=0, fill_value= ...)`, or other dunder methods non-idiomatically accepting kwargs.  The potential trouble is that for &|^, there are no non-dunder versions with the kwarg support.

**Comment by jreback** [comment]
can you rebase

**Comment by TomAugspurger** [comment]
> The user facing change is that frame.__and__(other, axis=0, fill_value= ...), or other dunder methods non-idiomatically accepting kwargs.

So this would break explicitly calling `frame.__and__(other, axis=0)`? I'm fine with that. I'm fine with not calling that a breaking change since dunder methods should be called by using the operators or the `operator` module.

**Comment by jbrockmendel** [comment]
whatsnew added, green-as-it-gets

**Comment by jreback** [comment]
thanks

**Pull request merged**
