### PR TITLE
BUG: resample Grouper in a list grouping on a column with NaT throws an error

### LINKED ISSUE #14715: resample Grouper in a list grouping on a column with pd.NaT throws an error
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'completed':pd.date_range('1/1/2011', periods=365, freq='D')})

# In the real case i have nulls in my data
df.iloc[-1] = pd.NaT

# This works
df.groupby(pd.Grouper(key='completed', freq='AS'))

# This doesn't and throws an error
df.groupby([pd.Grouper(key='completed', freq='AS')])
```
#### Problem description

Second form throws the following error:

```python
/anaconda/lib/python2.7/site-packages/pandas/indexes/base.pyc in _assert_take_fillable(self, values, indices, allow_fill, fill_value, na_value)
   1537                 taken[mask] = na_value
   1538         else:
-> 1539             taken = values.take(indices)
   1540         return taken
   1541

IndexError: index 364 is out of bounds for size 364
```

#### Expected Output
A proper grouper

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Darwin
OS-release: 14.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.7
pip: 8.1.2
setuptools: 0.6
Cython: 0.23.4
numpy: 1.11.0
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext)
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by discort**
- [x] closes #14715
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by discort** [comment]
@jreback

**Review by jreback — CHANGES_REQUESTED** [review]

**Comment by discort** [comment]
@jreback

**Comment by discort** [comment]
@jreback

**Comment by discort** [comment]
@jreback

**Review by jreback — APPROVED** [review]

**Pull request merged**
