### PR TITLE
DOC: Updates Index.any docstring from #40362

### LINKED ISSUE #40362: DOC: Wrong examples
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.all.html

#### Documentation problem

This documentation is about 'pandas.Index.all' but it has examples of 'pandas.Index.any'.
The examples of 'pandas.Index.any' are also included in [its own page](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.any.html).

#### Suggested fix for documentation

Delete 'any()' examples on the documentation of 'all()', I think this is wrong place.

### PR DESCRIPTION
**Pull request by Beluuuuuuga**
- [ ] closes #40362: add an introduction to all() function as described in "See also"
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
@Beluuuuuuga from the OP

> The examples of 'pandas.Index.any' are also included in its own page.

I think my preference would be to delete the `any` examples from the `all` method docstring.

If we are adding as here, can we shares the examples instead to make them consistent.

**Comment by simonjayhawkins** [comment]
> Or should I submit a new pull request?

you can push changes to the same PR as it's the same issue.

**Comment by Beluuuuuuga** [comment]
@simonjayhawkins 

I'll commit this week.

**Comment by MarcoGorelli** [comment]
@Beluuuuuuga is this still active?

**Comment by Beluuuuuuga** [comment]
> @Beluuuuuuga is this still active?

Sorry for the delay. I'll do it tomorrow.

**Comment by MarcoGorelli** [comment]
sure, no hurry

**Comment by mroeschke** [comment]
Thanks for the PR, but it appears to have gone stale. Closing due to inactivity but feel free to push updates to your branch and when you're ready for another review we can reopen.

**Pull request closed without merging**
