### PR TITLE
CI: troubleshoot timeouts

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by mroeschke** [comment]
If you're trying to debug the Azure timeouts, from what I've surmised, it's hanging during the pytest teardown step after the `pandas/tests/window.moments` tests.

**Comment by jbrockmendel** [comment]
> If you're trying to debug the Azure timeouts, from what I've surmised, it's hanging during the pytest teardown step after the pandas/tests/window/moments tests.

OK, do you have a gameplan for this?

**Comment by mroeschke** [comment]
I've been trying various approaches to increasing timeouts and seeing if there's the same behavior on GHA (no luck so far). I wouldn't be opposed to just not running the `pandas/tests/window/moments` test again to hopefully get things to green

**Comment by jbrockmendel** [comment]
> I wouldn't be opposed to just not running the pandas/tests/window/moments test again to hopefully get things to green

Yah let's disable it for now and maybe try re-introducing it bit by bit?

**Pull request closed without merging**
