### PR TITLE
Added theme_switcher 

### LINKED ISSUE #48598: DOC: Add light/dark theme switcher
With the upgrade to the latest version of `pydata-sphinx-theme` (see #48285) our docs now are available in dark mode. By default, the Sphinx theme will use the version (light/dark) set up by the user. But would be nice to add a switcher to the navigation bar of the docs, so users can change the theme manually.

See for example in the top right corner of https://www.blosc.org/c-blosc2/c-blosc2.html the icon to change the sphinx theme. I think we should add the same to the pandas docs too.

### PR DESCRIPTION
**Pull request by deepaksirohiwal**
Added theme_switcher in  navbar_end to display the Dark/Light theme switcher

- [x] closes #48598 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by datapythonista** [comment]
In Python you need to leave one space after commas. You can use flake8 to validate that there are no issies with the style of your code. That will make the checks green.

**Comment by datapythonista** [comment]
Thanks @deepaksirohiwal, looks good to me. Did you try this locally? Do you mind adding a screenshot here, so others can see how this will look when merged please?

**Comment by deepaksirohiwal** [comment]
Here are some screenshots of the new visual changes. Now Theme switch is available (top right) to toggle between different modes (Dark, Light and Auto) 
1
Light
Light mode-Switch
2
dark
Dark mode -Switch
3
auto

Auto mode(according to system setting)-Switch

**Review by datapythonista — APPROVED** [review]
Excellent, thanks @deepaksirohiwal, looks perfect!

**Comment by infvie** [comment]
thank you so much the dark theme is so hard to read in the docs!

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @deepaksirohiwal

**Comment by deepaksirohiwal** [comment]
Thank you @datapythonista and @mroeschke, I really learnt a lot and would love to contribute more.

**Pull request merged**
