### PR TITLE
Refactor tables latex

### PR DESCRIPTION
**Pull request by SylvainLan**
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

As suggested [here](https://github.com/pandas-dev/pandas/pull/35284#issuecomment-665273834), utils fonctions which begin or end tables / tabulars / longtables environments could be merged.

### CODE REVIEW

**Comment by SylvainLan** [comment]
@toobaz

**Comment by SylvainLan** [comment]
I had to change one test to have the same behaviour between tables and longtable, their was no newline between the caption and the label when both were provided, which is fine for latex but I guess it's better to match the behaviours

**Comment by SylvainLan** [comment]
The `backlash_` variable in the buffer is a bit artificial but I had to create it to handle the different scenarios that could arise whether position, label and/or caption were provided.

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by jreback** [comment]
thanks @SylvainLan very nice.

**Pull request merged**
