### PR TITLE
Added note in docs for giving the developer the option of choosing be…

### PR DESCRIPTION
**Pull request by Pydare**
…tween both parameters and kwargs. Exampled included

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
thanks @Pydare

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by simonjayhawkins** [comment]
this closes #45258?

**Comment by jreback** [comment]
yep

**Pull request merged**
