### PR TITLE
MAINT: Drop pd.options.display.mpl_style

### PR DESCRIPTION
**Pull request by gfyoung**
Deprecated in 0.18.0

xref #12190

(another nice short deprecation! 😄 )

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by gfyoung** [comment]
@jorisvandenbossche : Can this be merged?

**Comment by jorisvandenbossche** [comment]
Thanks!

**Comment by gfyoung** [comment]
Also, thanks for patching the merge conflict!

**Comment by jorisvandenbossche** [comment]
for such a small conflict in non-code stuff, the web interface is useful :-)

**Pull request merged**
