### PR TITLE
converted the assert error to TypeError with proper informative message

### PR DESCRIPTION
**Pull request by harshitsinha6**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by phofl — CHANGES_REQUESTED** [review]

**Review by jreback — CHANGES_REQUESTED** [review]
what are you trying to do?
this is an internal assertion
if it's violated then that is a bug
making a type error is not useful

**Comment by harshitsinha6** [comment]
> sure but this is way too low level
> you should validate this in .take itself

yes, but the error arises in "assert isinstance(values, np.ndarray), type(values)" and as per the requirement we have to display proper message with proper error.
but in .take it is not raising any error or it showing any relevant message.

**Comment by mzeitlin11** [comment]
@harshitsinha6 looks to already be being fixed in #42886? Also see that pr for what was meant by validating in take, not here

**Comment by jreback** [comment]
closing as a duplicate of #42886

**Pull request closed without merging**
