### PR TITLE
DOC: Fix PR02 errors in Timedelta attributes (min, max, resolution) d…

### PR DESCRIPTION
**Pull request by brownl83**
Part of #59698 
 

Addresses:

pandas.Timedelta

Added the missing explanations (PRO2) for min, max, and resolution.

Removed from code_checks.sh

i "pandas.Timedelta.resolution PR02" \
i "pandas.Timedelta.min PR02" \
i "pandas.Timedelta.resolution PR02" \

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks for your pr, looks like there's some issues
```
/home/runner/micromamba/envs/test/lib/python3.10/site-packages/numpydoc/docscrape.py:203: UserWarning: potentially wrong underline length... 
Returns 
-------- in 

Return utc offset.... in the docstring of utcoffset
  while not self._is_at_section() and not self._doc.eof():
/home/runner/micromamba/envs/test/lib/python3.10/site-packages/numpydoc/docscrape.py:203: UserWarning: potentially wrong underline length... 
Examples 
------------ in 

Check whether all characters in each string are titlecase.... in the docstring of istitle in /home/runner/work/pandas/pandas/pandas/core/strings/accessor.py.
  while not self._is_at_section() and not self._doc.eof():
Error: None:None:PR02:pandas.Timedelta.max:Unknown parameters {'value', 'unit', '**kwargs'}
Error: None:None:PR02:pandas.Timedelta.min:Unknown parameters {'value', 'unit', '**kwargs'}
Error: None:None:PR02:pandas.Timedelta.resolution:Unknown parameters {'value', 'unit', '**kwargs'}
```

**Comment by brownl83** [comment]
I will take any suggestions on how to deal with those unknown parameters, as I have exhausted all possible ideas. I am not sure that the min, max, and Resolution are good to be tagged with the "good first issue".

**Comment by brownl83** [comment]
Can the ignores be left in code_checks.sh and still have it update the documentation? This could be a workaround to get the documentation updated.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
