### PR TITLE
DOC: Fix heading capitalization in doc/source/whatsnew - part6 (#32550)

### PR DESCRIPTION
**Pull request by cleconte987**
- [ ] Modify files v0.22.0.rst, v0.23.1.rst, v0.19.0.rst, v0.24.0.rst, v0.24.2.rst

-[ ] Add exceptions in 'validate_rst_title_capitalization.py'

### CODE REVIEW

**Comment by cleconte987** [comment]
I added 'Expanding' exception keyword in validate_rst_title_capitalization.py, and now it is causing troubles with same word in doc/source/reference/window.rst line 42. How would you like to treat this word? I figured it should be capitalized in doc/source/whatsnew/v0.23.0.rst line 300.

**Comment by alimcmaster1** [comment]
Thanks for the PR! Can you merge master?

**Comment by cleconte987** [comment]
I really don't understand what's happening with azure. What is the problem? I tried to update the PR but there are still problems with azure, what's happening?

**Comment by alimcmaster1** [comment]
> I really don't understand what's happening with azure. What is the problem? I tried to update the PR but there are still problems with azure, what's happening?

Likely just a flakey test - I would merge master and push again. Also mind linking the issue in the PR description?

**Pull request closed without merging**
