### PR TITLE
DOC: removed vendored IPython.sphinxext - take 2

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
This reverts commit d6049a0efb7c04996bc374f3747bab8fe4c84bac.

xref https://github.com/pandas-dev/pandas/issues/18147, re-do  https://github.com/pandas-dev/pandas/pull/18193 (which was reverted in https://github.com/pandas-dev/pandas/pull/18320 because there was still a bug in IPython, which is now fixed in the released version: https://github.com/ipython/ipython/pull/10907)

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@TomAugspurger We were actually a bit fast, the fix of https://github.com/ipython/ipython/pull/10907 is actually not yet in a released version.

**Comment by TomAugspurger** [comment]
Oh, I thought the backported in
https://github.com/ipython/ipython/pull/10908 was released, but apparently
not yet.

**Comment by jreback** [comment]
this looks fine. @jorisvandenbossche merge when ready.

**Comment by jorisvandenbossche** [comment]
Don't merge, we need to wait until the next IPython release ..

**Comment by jreback** [comment]
status @jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
This needs to wait until IPython has a new release. If you rather close the PR until then, that's fine for me as well (having it open is a reminder for me, but can also open an issue)

**Comment by jreback** [comment]
it’s fine -

**Comment by jorisvandenbossche** [comment]
IPython has released, update the PR, and this seems to be working now

**Review by TomAugspurger — COMMENTED** [review]
Looks good, only thing I would say is bump `ci/requirements-optional-conda.txt` to require at least 6.3.1?

**Pull request merged**
