### PR TITLE
TST: clean up to change setup.cfg to `xfail_strict = True` (GH23057)

### LINKED ISSUE #23057: Make default xfail strict
Pytest let's you configure the default xfail strictness in the `setup.cfg`

```
xfail_strict=true
```

This issue is to

1. Make that change
2. Update tests that are currently XPASSing
    - If always passing then remove the xfail entirely
    - If only sometimes passing (flaky test, dependency, configuration, etc.) then mark that specific test as `strict=False`.

cc @jbrockmendel @jreback

### PR DESCRIPTION
**Pull request by dcreekp**
- [x] closes #23057
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Looks like there are some xfailing tests that are passing: https://travis-ci.org/pandas-dev/pandas/jobs/455669456#L2806

There may be others in https://travis-ci.org/pandas-dev/pandas/builds/455669455?utm_source=github_status&utm_medium=notification, I only looked at the first build.

The ones that are flaky should be `xfail(strict=False)`.

**Comment by dcreekp** [comment]
Oh I get it. 
At least for https://travis-ci.org/pandas-dev/pandas/jobs/455669458 and https://travis-ci.org/pandas-dev/pandas/jobs/455669460 are xpassing when running py3.7 on travis, while running py3.6 locally didn't xpass

**Comment by dcreekp** [comment]
this one https://travis-ci.org/pandas-dev/pandas/jobs/455669458
will probably still fail because it is the same as this https://github.com/pandas-dev/pandas/issues/23726

**Comment by jreback** [comment]
can you rebase

**Comment by jreback** [comment]
you are picking up other changes. merge master and push again.

**Comment by dcreekp** [comment]
@jreback should I close this pull request and make another clean one?

**Comment by jreback** [comment]
better for this one

**Comment by TomAugspurger** [comment]
Diff looks good here. CI is still failing from tests xpassing. You may need to add conditions or `strict=False` to those xfails.

**Comment by jreback** [comment]
lgtm. @TomAugspurger

**Comment by TomAugspurger** [comment]
Thanks @dcreekp! This will be very useful.

**Comment by dcreekp** [comment]
Awesome.
Just to let you know, as python2.7 support is going to be dropped. There are two or three tests that are marked xfail only because of the test failing on 2.7.
@TomAugspurger @jreback

**Pull request merged**
