### PR TITLE
CLN: Don't catch TypeError in FrameApply.agg

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

Ref: #34224. Back when transform and agg shared code, this was introduced to stop transform from having an infinite recursive loop. Now they do not, it is no longer necessary and only serves to obfusticate the error message.

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM (assuming CI failures are unrelated)

**Comment by rhshadrach** [comment]
@jbrockmendel - merged master CI is now green except code coverage, which appears incorrect to me. Throwing a `raise ValueError` just above the untested lines fails 385 tests in tests.apply.

**Review by jbrockmendel — APPROVED** [review]
LGTM cc @jreback

**Comment by jreback** [comment]
thanks @rhshadrach

**Pull request merged**
