### PR TITLE
DOC: Add 1.0.2 whatsnew

### PR DESCRIPTION
**Pull request by alimcmaster1**
- Need this for PR https://github.com/pandas-dev/pandas/issues/31677

cc. @TomAugspurger @jorisvandenbossche

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Can you use the same format (the sections) as the v1.0.1 file ?

**Comment by jorisvandenbossche** [comment]
And you can also already fill in the "contributor" (see the v1.0.1 file for how it is done there)

**Comment by alimcmaster1** [comment]
Thanks - Done @jorisvandenbossche

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by jorisvandenbossche** [comment]
@alimcmaster1 I removed the deprecation section as well, as normally there shouldn't be any deprecations (in 1.0.1 it was a special case to fix a regression that it was restored but also deprecated)

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks!

**Comment by alimcmaster1** [comment]
> @alimcmaster1 I removed the deprecation section as well, as normally there shouldn't be any deprecations (in 1.0.1 it was a special case to fix a regression that it was restored but also deprecated)

thanks make sense!

**Pull request merged**
