### PR TITLE
DEPR: Enforce deprecations

### PR DESCRIPTION
**Pull request by mroeschke**
Introduced in #43248, #33091, #45523

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM pending green

**Comment by mroeschke** [comment]
Failure is unrelated (and remaining check is the requirements-dev.txt install), so merging

**Comment by rhshadrach** [comment]
This patch may have induced a potential regression. Please check the links below. If any ASVs are parameterized, the combinations of parameters that a regression has been detected appear as subbullets. This is a partially automated message.

Subsequent benchmarks may have skipped some commits. See the link below to see which commits are between the two benchmark runs where the regression was identified.

https://github.com/pandas-dev/pandas/compare/6122c7de128fce3a84d91ef91b9dc3a914531745...c0445543a10ae6c6abe5a3efc519fd9edcd2d276

 - [series_methods.ToFrame.time_to_frame](https://asv-runner.github.io/asv-collection/pandas/#series_methods.ToFrame.time_to_frame)
   - [dtype='Int64'; name=None](https://asv-runner.github.io/asv-collection/pandas/#series_methods.ToFrame.time_to_frame?p-dtype=%27Int64%27&p-name=None)
   - [dtype='category'; name=None](https://asv-runner.github.io/asv-collection/pandas/#series_methods.ToFrame.time_to_frame?p-dtype=%27category%27&p-name=None)
   - [dtype='datetime64[ns]'; name=None](https://asv-runner.github.io/asv-collection/pandas/#series_methods.ToFrame.time_to_frame?p-dtype=%27datetime64%5Bns%5D%27&p-name=None)
   - [dtype='int64'; name=None](https://asv-runner.github.io/asv-collection/pandas/#series_methods.ToFrame.time_to_frame?p-dtype=%27int64%27&p-name=None)

**Comment by rhshadrach** [comment]
I think this looks fine, just the difference between `Index([name])` and `default_index(1)`, but wanted to be sure.

**Pull request merged**
