### PR TITLE
REGR: Revert GH51335

### PR DESCRIPTION
**Pull request by rhshadrach**
Ref: https://github.com/pandas-dev/pandas/pull/51955#issuecomment-1478685300

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

@jbrockmendel - this only reverts the change to `_reduce`, but leaves other changes untouched. Would you prefer to revert all of #51335?

### CODE REVIEW

**Comment by rhshadrach** [comment]
@jbrockmendel - yes, it did - thanks.

**Comment by jbrockmendel** [comment]
OK this looks fine.  Let's reiterate the plan for when i inevitably forget: merge this, backport to 2.0, then for 2.1 do either #51923, which might need to be updated to un-revert some or all of this?

**Comment by rhshadrach** [comment]
I think you meant #51955 instead of #51923. #51955 can either go into 2.0 or 2.1 depending on whether there is time.

**Comment by phofl** [comment]
Is this ready for 2.0?

**Comment by rhshadrach** [comment]
I believe this is ready, wanted to make sure @jbrockmendel is on board with the plan. I think both this and #51955 would be good for 2.0.1.

**Comment by rhshadrach** [comment]
Ack - need to update the whatsnew, so no, this isn't ready anymore.

**Comment by jbrockmendel** [comment]
Yes I am on board with the plan.

**Comment by rhshadrach** [comment]
I'm a bit more negative on this now. With 2.0.0 now released, this with #51955 will now reintroduce bad behavior (test_minmax_tzaware_skipna_axis_1 is xfailed). I'm going to see if I can get that test working in #51955, and if this is the case then I think we can go foward. 

Without being able to fix that test, I think this path should be abandoned and we should instead pursue (a) increase perf of transpose as @jorisvandenbossche has suggested (#52083) and (b) use online ops where possible as @jbrockmendel has suggested (https://github.com/pandas-dev/pandas/pull/52083#issuecomment-1476470581).

**Comment by jbrockmendel** [comment]
I like this plan; I'm excited to be a part of it.

**Comment by rhshadrach** [comment]
I don't see any reasonable way to support axis=1 with tzaware dtypes by operating on NumPy arrays - so I think there is no way forward in this direction.

**Pull request closed without merging**
