### PR TITLE
Fix issue with merge-pr.py script

### PR DESCRIPTION
**Pull request by wesm**
The commented line shown produces an error on fresh clones of pandas, and is not needed AFAICT.

### CODE REVIEW

**Comment by jreback** [comment]
this gave me an error after it pushed the merged branch to master

it said: ``Would you like to pick %s into another branch?``

and I said ``Y``, at which point ``latest_branch`` was undefined. Not really even sure what that's supposed to do. I presume it would have cherry-picked to my local copy of master, as the remote mastser was already updated. 

The script exited and all was ok.

What is the purpose of that section?

**Comment by wesm** [comment]
You say no to that. We can also remove that section

**Comment by wesm** [comment]
@jreback I removed the cruft. If looks good merge away. If we find ourselves doing much backporting to maintenance branches in the future we can add some tools for that

**Comment by jreback** [comment]
merged. thanks.

**Pull request closed without merging**
