### PR TITLE
BUG: Do not error on other dbapi2 connections

### PR DESCRIPTION
**Pull request by abowden1989**
Do not throw an error in `pandasSQL_builder` when the connection is a dbapi2 connection that is not `sqlite3` and `sqlalchemy` is not installed. Also restores the behaviour prior to #42546 when the connection is a string but `sqlalchemy` is not installed.

This partially addresses #45660 (it removes the requirement for `sqlalchemy` to be installed to use another connection object, however it does not remove the warning that such behaviour is unsupported).

Prior to #42546, other dbapi2 objects would work regardless of whether `sqlalchemy` was installed, without a warning - after this PR, they were not supported. Support was re-added (with a warning) in #45496 , but with an unnecessary requirement on `sqlalchemy`

- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
cc @fangchenli

**Review by fangchenli — APPROVED** [review]

**Review by jreback — CHANGES_REQUESTED** [review]
@abowden1989 can you add a whatsnew note in 1.4.1 describing this change

**Comment by jrandall** [comment]
> @abowden1989 can you add a whatsnew note in 1.4.1 describing this change

@jreback a regression note has been added to the whatsnew for 1.4.1

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @abowden1989

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by jreback** [comment]
@abowden1989 if you can follow the instructions above and push a backport PR would be great.

**Comment by simonjayhawkins** [comment]
> @abowden1989 if you can follow the instructions above and push a backport PR would be great.

Thanks @abowden1989 for the PR. backport done in #45754

**Comment by abowden1989** [comment]
> > @abowden1989 if you can follow the instructions above and push a backport PR would be great.
> 
> Thanks @abowden1989 for the PR. backport done in #45754

Thanks for taking care of this @simonjayhawkins , I wasn't available the past few days so didn't have chance

**Pull request merged**
