### PR TITLE
CLN/ASV clean-up frame stat ops benchmarks

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Small clean-up and testing of both with/without bottleneck. 

Also includes a benchmark for https://github.com/pandas-dev/pandas/pull/16509

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Output is currently something like this:

```
(dev) joris@joris-XPS-13-9350:~/scipy/pandas/asv_bench$ asv dev -b FrameOps
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Building for existing-py_home_joris_miniconda3_envs_dev_bin_python
[  0.00%] ·· Benchmarking existing-py_home_joris_miniconda3_envs_dev_bin_python
[100.00%] ··· Running stat_ops.FrameOps.time_op                                                                                                                                                                                                                               ok
[100.00%] ···· 
               ======== ================== ================== ================ ================ =================== =================== ================= =================
               --                                                                  use_bottleneck / dtype / axis                                                           
               -------- ---------------------------------------------------------------------------------------------------------------------------------------------------
                  op     True / float / 0   True / float / 1   True / int / 0   True / int / 1   False / float / 0   False / float / 1   False / int / 0   False / int / 1 
               ======== ================== ================== ================ ================ =================== =================== ================= =================
                 mean         1.23ms             1.53ms            1.58ms           1.70ms             5.33ms              9.06ms             6.91ms            8.09ms     
                 sum          1.13ms             1.52ms            1.33ms           1.58ms             5.64ms              6.24ms             6.06ms            6.76ms     
                median        8.52ms             6.53ms            7.84ms           6.46ms            12.68ms              3.66s             13.17ms            3.40s      
               ======== ================== ================== ================ ================ =================== =================== ================= =================
```

**Comment by jreback** [comment]
that formatting is actually hard to read (IOW its better if all of the comparisons on row-wise). did you do something to get that?

**Comment by jorisvandenbossche** [comment]
nope, this is just the default output of asv when you have parameterized benchmarks. I agree it is not that clear. 
But, when you do a comparison of eg PR against master, you get them as separate entries in the before/after table. So given that, I think this is OK (the only alternative is not using parameterized tests, or asking asv to have an option to change the formatting)

**Comment by jreback** [comment]
ahh I c, ok then.

**Comment by jreback** [comment]
thanks!

**Pull request merged**
