### PR TITLE
 Add base test for Series[ExtensionArray].sort_values with sort=False

### PR DESCRIPTION
**Pull request by akulagrawal**
- [x] closes ##23074
- [x] one base test added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by akulagrawal** [comment]
Oh my bad! I am a beginner and this is my first contribution to pandas. As for the match, according to my system the output is:

> In [21]: ser = pd.Series([1, 2, 2, 2, 1, 0])
In [22]: ser.value_counts(sort=False)
Out[22]:
2    1
1    2
0    3
dtype: int64
In [23]: ser.astype(int).value_counts(sort=False)
Out[23]:
0    1
1    2
2    3
dtype: int64

I understand they are incorrect  but they don't match with yours atleast

**Comment by TomAugspurger** [comment]
Yeah, I'm not sure why those don't match. Presumably there's whatever internally does this hashing doesn't preserve order.

I'd recommend holding off on this PR and maybe finding another issue until we can decide exactly what we want the requirements on order to be here.

**Comment by akulagrawal** [comment]
Oh... first of all there was some error in my last comment. I meant they matched on my system (output updated in the comment), though both seem to be incorrect.
Alright, moving onto other issue. Thanks @TomAugspurger !

**Comment by jorisvandenbossche** [comment]
Closing the PR (to shorten our backlog of open PRs). We still have the issue to track it, so if we decide to keep value_counts on that issue, we can simply reopen this PR. @akulagrawal That is OK?

**Comment by akulagrawal** [comment]
yes sure :)

**Pull request closed without merging**
