### PR TITLE
TST/REF: move tools test files

### PR DESCRIPTION
**Pull request by jbrockmendel**
These files are in the index tests, but they're not really testing the index objects.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
i'm not sure about date_range, period_range and timedelta_range as these only return Indexes and so are effectively Index constructors. see what others think.

the others make more sense. (the return value in the docs for pandas.to_timedelta https://dev.pandas.io/docs/reference/api/pandas.to_timedelta.html appears incorrect. Should be scalar, Series or TimedeltaIndex?)

**Comment by jbrockmendel** [comment]
> i'm not sure about date_range, period_range and timedelta_range as these only return Indexes and so are effectively Index constructors.

Thats reasonable.  My thought is that these are top-level convenience functions, and the directories they are currently in are getting crowded (and likely to become more so)

**Comment by mroeschke** [comment]
I agree with @simonjayhawkins. I tend to view these as "constructors" more than "tools".

How about `pandas/tests/indexes/datetimes/constructors/test_date_range.py` and then `pandas/tests/indexes/datetimes/test_constructors.py` could be `pandas/tests/indexes/datetimes/constructor/test_datetimeindex.py` or something?

**Comment by jbrockmendel** [comment]
will revert the non-consensus changes

**Comment by simonjayhawkins** [comment]
Thanks @jbrockmendel

**Pull request merged**
