### PR TITLE
DOC: Add pandas video series to tutorials.rst

### PR DESCRIPTION
**Pull request by justmarkham**
This is a 6-hour video tutorial series that is freely available on YouTube. If you would like to quickly preview the contents of the series, you can see all of the code in this [Jupyter Notebook](http://nbviewer.jupyter.org/github/justmarkham/pandas-videos/blob/master/pandas.ipynb).

Collectively, these videos have nearly 20,000 likes across 1 million views. If you would like to read some testimonials about the quality of the instruction, [please see here](https://www.dataschool.io/testimonials/#aboutmypandasvideoshttpwwwdataschoolioeasierdataanalysiswithpandas).

Please let me know if you have any questions or would like me to make any changes. Thanks for your consideration!

### CODE REVIEW

**Comment by datapythonista** [comment]
-1 on this

Personally, I don't think we should have that whole page in the pandas repo. It's surely useful, but should be maintained somewhere else.

**Comment by TomAugspurger** [comment]
Given that the page is there, doesn't it make sense to add this? I haven't watched it, but Kevin's work is typically high quality.

**Comment by datapythonista** [comment]
Not a big deal this PR. But maintaining a page like this, seems to me like a lot of work of keeping the content updated, verify the content that people propose to add...

I'd say that at the moment, as it's not easy to navigate the pandas documentation, this page is not as popular. But with some luck, we'll have better navigation and visibility of the pages soon, and besides the time to keep it updated, I think it'll be an increasing demand for content creators to have their resources there.

You can see also this PR: https://github.com/pandas-dev/pandas-website/pull/67

My point is that it'd be great to have a page like this with resources. But I think we already have enough to do to have to keep deciding what content is worth to be "endorsed" in the official pandas website, and what's not.

But as said, feel free to merge it, my concerns are more about the mid-term.

**Comment by WillAyd** [comment]
At the very least can we just have one link to the playlist instead of one to each video?

**Comment by justmarkham** [comment]
Hello all, thanks so much for your thoughtful comments. In case it's helpful, I wanted to clarify my motivation for this PR:

I love that the pandas documentation provides a great level of detail about much of the pandas functionality. However, many sections of the documentation lack what might be most helpful to beginners (in my opinion), which is a high-level overview of "how do I accomplish some common task" or "when should I use this particular feature", along with corresponding examples using real-world datasets.

For example, a beginner might have many of these questions:

- What exactly is the "axis"?
- When should I use "inplace"?
- What is the purpose of the index?
- When should I use a "groupby"? What do the results tell me?
- How do I use the MultiIndex? What's the purpose of it?
- How do I fix the SettingWithCopyWarning? What happens if I just ignore it?
- and so on...

To be fair, the answers to many of these questions may be available in the documentation, but they are not often easy to find (in my experience), especially if you don't already know the terminology to look for. And when you do find the right section, the deep level of detail can obscure the high-level information.

My goal, when creating this video series, was specifically to answer many of those beginner and intermediate questions. I use real-world datasets to make the examples more relatable. And each video is titled such that if you just want to know about some particular topic (e.g., how to use a string method), you immediately know which video to watch by its title ("How do I use string methods in pandas?")

My guess is that lots of beginners poke around in the documentation, looking for answers to these questions, and many of them come across the Tutorials page. For those users, I wanted to provide an easy way to get an answer to their particular question, which is why I listed the videos out individually.

However, I totally understand if my vision for the Tutorials page is not in line with the core team's vision for this page, and I'm happy to proceed however you like!

**Comment by datapythonista** [comment]
I agree on your points, and we're making a big effort to improve the documentation and make sure all these questions are answered. And PRs to help on that are more than welcome.

For me the discussion is whether we want to maintain a page of external resources for pandas. I think the people who can merge these PRs have already enough work, to have to review the linked content, and deal with the spam that such a page will generate (once we make navigating the documentation easier).

I won't be reviewing the content, and my feeling is that nobody else will in most cases. So, I'd leave that task to some external website that is interested on maintaining a list of pandas resources.

I'm ok if somebody wants to review and merge this. But personally I'd prefer to remove this page, and close PRs like this or the one for the video links in the web directly.

**Comment by jreback** [comment]
yeah this should only be a single link

**Comment by justmarkham** [comment]
I've removed the original list of videos, and instead added a link to the YouTube playlist under the "Video Tutorials" section. I included links to both the GitHub repo and the Jupyter Notebook, since the Notebook effectively summarizes the content of the video series.

I additionally included a second (separate) pandas video series from PyCon 2018.

I'd be glad to make additional changes as requested. Thanks!

**Comment by jorisvandenbossche** [comment]
> I think Joris has stats on the actual page views, so we can see if anyone
goes here.

It's actually (surprisingly, at least to me) quite popular: n° 22 in ranking of most visited pages (although only n° 34 for unique visits). Around 50,000 page visits (for the last 30 days), compared to eg around 95,000 for api.html

I am fine with the reduced list as it is now in this PR (given that we have the page at the moment).

But in general, it is true that if we have such a page, it should also be maintained. Which it isn't at the moment. And it's not only about reviewing PRs with new additions, but also cleaning up current content, as older links also get out of date. 
On the other hand, a good *curated* page similar to this is also very valuable to users.

> For example, a beginner might have many of these questions:

All good questions, and *ideally*, those should be much better answered in the main docs as well ..

**Comment by jorisvandenbossche** [comment]
Triggered by the discussion here, I was looking at the current page, and I find the long listing of content of some of the tutorials (but others much less) a bit distractive of the overall list. So proposal to shorten the long ones: https://github.com/pandas-dev/pandas/pull/24152

**Review by WillAyd — APPROVED** [review]
I'm OK with this

**Comment by datapythonista** [comment]
@justmarkham can you merge master, update the PR, and make sure the CI is green, so we can merge this please

**Comment by justmarkham** [comment]
@datapythonista I merged master, and it looks like the Travis CI build failed. I looked at the error logs, and the failure I'm seeing doesn't seem to relate to my change. Please pardon my ignorance, but I'm not sure how to proceed from here? Thanks for any help!

**Comment by datapythonista** [comment]
Thanks @justmarkham, I think I've seen this test failing randomly some times. We should take a look and fix it's more deterministic (not sure if that's easy being  a `hypothesis` test). I restarted it, hopefully this time finish successfully.

**Comment by justmarkham** [comment]
@datapythonista Thanks for restarting the tests, this time it passed! 👍✅

**Comment by datapythonista** [comment]
Thanks @justmarkham

**Pull request merged**
