### PR TITLE
Updated Cheatsheet with some extra functions added

### PR DESCRIPTION
**Pull request by ashishbalti4**
-Added a new page
- Added new functions related to IO tools, Data transform and Visualization.
- -Also applied some new functions like df.isin, df.sample, etc.

[Pandas_CheatSheet (1).pdf](https://github.com/pandas-dev/pandas/files/9836279/Pandas_CheatSheet.1.pdf)

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Could you provide a list what you've changed?

**Comment by ashishbalti4** [comment]
@phofl I have added a new page with functions like IO tools, Data transform, and visualization.

**Review by datapythonista — CHANGES_REQUESTED** [review]
There seems to be things that don't make sense in the new page of the cheatsheet, like `df.to_datetime()`. See: https://github.com/pandas-dev/pandas/blob/86a11d43cdfd98e2d36bfc184e9c25839e5c633a/Pandas_CheatSheet.pdf

@ashishbalti4, I think it's better if you start by opening an issue to discuss what you want to add to the cheatsheet. There are some good ideas in what you implemented, having a table with the IO functions could be a good addition. But we need to make sure that what we provide is accurate and relevant.

**Comment by ashishbalti4** [comment]
Added a new page

Added new functions related to IO tools, Data transform and Visualization.
-Also applied some new functions like df.isin, df.sample, etc.

**Pull request closed without merging**
