### PR TITLE
Support large strings in interchange protocol

### LINKED ISSUE #56702: ENH: Support large string types in the interchange protocol
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

The interchange protocol supports the large string type. Pandas could also support it, but currently does not. It only supports 'small' strings.

### Feature Description

This currently works:

```python
import pandas as pd

df = pd.Series([], name="a", dtype="string[pyarrow]").to_frame()
dfi = df.__dataframe__()
result = pd.api.interchange.from_dataframe(dfi)
# result is equal to df
```

This does not:

```python
import pandas as pd

df = pd.Series([], name="a", dtype="large_string[pyarrow]").to_frame()
dfi = df.__dataframe__()
result = pd.api.interchange.from_dataframe(dfi)
# ValueError: Data type large_string[pyarrow] not supported by interchange protocol
```

### Alternative Solutions

n/a

### Additional Context

@MarcoGorelli FYI. Supporting large string would mean better interop with Polars and pyarrow.

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #56702 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @MarcoGorelli

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Thanks for working on this!

If I run
```python
df = pd.Series([], name="a", dtype="large_string[pyarrow]").to_frame()
dfi = df.__dataframe__()
result = pd.api.interchange.from_dataframe(dfi)
print(dfi.__dataframe__().get_column_by_name('a').get_buffers()['data'])
```
then I get
```
(PandasBuffer({'bufsize': 0, 'ptr': 94739763740952, 'device': 'CPU'}), (<DtypeKind.STRING: 21>, 8, 'u', '='))
```

I think it should be `'U'` at the end?

I think you just need to update

https://github.com/pandas-dev/pandas/blob/d2f05c2d237d8d23781f3aeaa12051ef4b4389af/pandas/core/interchange/column.py#L303-L309

**Comment by WillAyd** [comment]
That may also fix https://github.com/pandas-dev/pandas/issues/56754

**Comment by phofl** [comment]
@MarcoGorelli Does your commit fix the issue you detected earlier? If yes, we could backport to 2.2

**Review by MarcoGorelli — APPROVED** [review]
thanks @phofl !

**Comment by phofl** [comment]
Thanks to you :)

**Pull request merged**
