### PR TITLE
CI: Bump pandas-gbq to one that doesn't pin pyarrow

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by mroeschke** [comment]
Might be worth bumping the min version to https://github.com/googleapis/python-bigquery-pandas/releases/tag/v0.18.1 so users also don't get bit my pyarrow being pinned

**Comment by lithomas1** [comment]
Ugh 0.18.1 isn't on conda-forge.

Is it fine to just go directly to 0.19.x?

**Comment by mroeschke** [comment]
> Ugh 0.18.1 isn't on conda-forge.
> 
> Is it fine to just go directly to 0.19.x?

Yeah that should be fine

**Comment by mroeschke** [comment]
A few more places need bumping otherwise looks good

**Comment by lithomas1** [comment]
Not entirely making sense of the error, but looks like there is a conflict between pyarrow dependencies
(aws-sdk-cpp) and google-bigquery dependencies(grpcio) fighting over openssl 1 and openssl 3.

I think what needs to happen is that we need to bump pyarrow from 7 to something newer. 

PDEP-10 stops this from happening for 2.1, but maybe we can bump as soon as 2.2?
There seems to be no support plan in that PDEP, stopping us from bumping pyarrow as we please.

cc @jorisvandenbossche (this relates to the issue with pyarrow effectively being pinned on CI)

**Comment by mroeschke** [comment]
Going to close to clear the queue for now

**Comment by mroeschke** [comment]
I think I may have tackled this in https://github.com/pandas-dev/pandas/pull/55524?

**Comment by lithomas1** [comment]
Nice, thanks Matt.

**Pull request closed without merging**
