### PR TITLE
[ENH] MultiIndex: astype dict

### PR DESCRIPTION
**Pull request by ghost**
astype multiindex with dict-like of names/int names index with pandas dtype

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by debnathshoham** [comment]
Thanks for PR @NickFillot!
Is there a particular issue you're working on?

**Comment by NickFillot** [comment]
Hello,

I am trying to fix index typing, on set_index method it doesn't recover the old dtypes

Br
Nicolas

**Comment by attack68** [comment]
Hi @NickFillot, what @debnathshoham means is: is there a pandas issue number that you are working on. Has this problem been discussed?

**Comment by NickFillot** [comment]
Hello,

After deeper checks, i just saw it was pandas.Int64Dtype() (nullable dtypes), and i had object dtype in index

I think it would be nice to set pandas nullable types as dtype instead of object if possible

My bad, thanks for support

Br
Nicolas

**Comment by NickFillot** [comment]
Issue for feature request if possible: [Issue](https://github.com/pandas-dev/pandas/issues/43857)

**Pull request closed without merging**
