### PR TITLE
fix for the issue-11833

### PR DESCRIPTION
**Pull request by Vutsuak16**
updated the to_string() function of  DataFrameFormatter(TableFormatter) class ,in format.py file, of the core directory

Closes https://github.com/pydata/pandas/issues/11833

### CODE REVIEW

**Comment by jreback** [comment]
needs tests

**Comment by Vutsuak16** [comment]
@jreback   so how should I push the commit?

**Comment by jreback** [comment]
just push
nothing special

**Comment by Vutsuak16** [comment]
@jreback  it shows that the commit fails the check, but it solves the issue mentioned??
can you review the commit ?

**Comment by jreback** [comment]
you need to have it pass all existing and any new tests

**Comment by jorisvandenbossche** [comment]
@Vutsuak16 The problem is that you *also* need to change the test that fails. As we are changing the behaviour here (it was explicitly tested that there were blank spaces, which we now want to remove)

**Comment by Vutsuak16** [comment]
#11909

**Pull request closed without merging**
