### PR TITLE
added a note on index creation for pandas dataframe stored in hdf5 file

### PR DESCRIPTION
**Pull request by ksxh**
Based on my discussion with Jeff

http://stackoverflow.com/questions/25714549/indexing-and-data-columns-in-pandas-pytables/25715005?noredirect=1#comment53932720_25715005

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback This isn't useful enough to go in the main hdf5 docs?

**Comment by jreback** [comment]
yeh,, why don't you move this into: http://pandas.pydata.org/pandas-docs/stable/io.html#indexing

**Comment by jreback** [comment]
@ksxh can you move as described above

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/74f0111e0aa049077fc808e07b0300ca143a517f

thanks!

**Pull request closed without merging**
