### PR TITLE
xfail to fix CI

### PR DESCRIPTION
**Pull request by jbrockmendel**
to keep the wheels running while I troubleshoot this

### CODE REVIEW

**Comment by jreback** [comment]
sure

**Comment by jbrockmendel** [comment]
Travis fail looks like its caused by something different, but I've also seen that in a bunch of recent builds.

**Comment by TomAugspurger** [comment]
Restarted the failing Mac build. We can debug that separately.

**Comment by jreback** [comment]
thanks @jbrockmendel

**Comment by jbrockmendel** [comment]
tried building on raspi so I could troubleshoot the 32bit build, but the build process segfaulted on the first gcc call

**Comment by TomAugspurger** [comment]
Is it 32-bit specific? https://github.com/TomAugspurger/pandas-docker may be helpful. `git clone` pandas in that directory and `make pandas32` should give you a docker image with a 32-bit pandas inside.

**Comment by jbrockmendel** [comment]
> Is it 32-bit specific?

No, thats just one of several builds that were failing, and I'm tying to find any of them that I can reproduce.

**Pull request merged**
