### PR TITLE
REF: remove always-True DataFrame._iset_item kwarg

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@jorisvandenbossche any idea why this would be failing on the AM build?  my only guess is that yesterday's change from skipping to xfailing is interacting with the weird statefullness of the tests in test_expressions

**Comment by jorisvandenbossche** [comment]
I have seen that before the last days (maybe in that PR, not fully sure, the tests were passing in the last commit there), but always only appeared from time to time (restarting might "solve" it), and I am not able to reproduce it locally. 

> change from skipping to xfailing is interacting with the weird statefullness of the tests in test_expressions

The `test_expressions.py` itself is not using any skip/xfails, so I have a hard time understanding how that would be related. 

Looking at the failures, I think all have to do with for some reason not actually using numexpr, when the test is thought to be using it. Will have a check if any of the tests we currently skip->xfail might meddle with those settings.

**Comment by jbrockmendel** [comment]
> I have seen that before the last days

that's pretty strong evidence that the skip->xfail change is unrelated.  thanks for taking a look.

**Comment by jorisvandenbossche** [comment]
>> I have seen that before the last days
>
> that's pretty strong evidence that the skip->xfail change is unrelated. thanks for taking a look.

In the end it _was_ related, but not to any ArrayManager stuff in that PR, but by enabling a dask test (which we don't run anywhere else), which changes the use_numexpr setting ... and our tests are not robust against that changed setting ... -> https://github.com/pandas-dev/pandas/pull/44601

**Pull request merged**
