### PR TITLE
STY: Using __all__; removed "noqa" comment

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
I am personally -1 on this, I find the relative imports much clearer to signal it are all imports internally from the module.

**Comment by MomIsBestFriend** [comment]
I personally don't have a strong opinion on relative vs absolute imports, just wanted to remove the ```# flake8: noqa``` comment.

---

If we do want relative imports in some places, https://dev.pandas.io/docs/development/code_style.html#imports-aim-for-absolute should be updated.

**Comment by jbrockmendel** [comment]
> I find the relative imports much clearer to signal it are all imports internally from the module.

I'm with Joris on this one.

**Comment by WillAyd** [comment]
absolute imports are recommended by PEP8 and are used 99% of the time in our code base, so I think we should go with this

**Comment by jorisvandenbossche** [comment]
PEP8 also says:

> However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose

(which I would say applies here)

So I don't think PEP8 is a good reason to do this. 
Consistency within pandas of course *is*. And it is correct than almost all code uses absolute imports. But that is also because there are regularly PRs like this one that converts to absolute imports that we merge ;) (just meaning, this is a "rule" we set ourselves that can be discussed)

**Comment by jreback** [comment]
> I am personally -1 on this, I find the relative imports much clearer to signal it are all imports internally from the module.

I disagree, we barely use them. having a mix is SO confusing. Since we use absolute almost everywhere we should just continue to do this.

**Comment by jreback** [comment]
all that said, we could have a policy to use relative in *some* parts of the codebase. I just don't want to mix it *within* a file. This file looks fine as is. But we need to define how we communicate this policy (and how its enforced).

**Comment by WillAyd** [comment]
Is there a path forward here? I'm still OK with this

**Comment by jbrockmendel** [comment]
> I personally don't have a strong opinion on relative vs absolute imports, just wanted to remove the # flake8: noqa comment.

Let's just do the `__all__` for now

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @MomIsBestFriend

**Pull request merged**
