### PR TITLE
BUG: DataFrame._slice doesnt retain metadata

### LINKED ISSUE #9776: BUG: DataFrame doesn't hold _metadata when sliced by slice instance
```
import pandas as pd


class TestDataFrame(pd.DataFrame):

    _metadata = ['testattr']

    @property
    def _constructor(self):
        return TestDataFrame

df = TestDataFrame({0: [1, 2, 3], 1: [1, 2, 3]})
df.testattr = 'XXX'
df.testattr
# XXX

# Using list is OK
df.iloc[[0, 1], :].testattr
# XXX

# Using slice is NG
df.iloc[0:1, :].testattr
# AttributeError: 'TestDataFrame' object has no attribute 'testattr'
```

### PR DESCRIPTION
**Pull request by sinhrks**
Closes #9776.

### CODE REVIEW

**Comment by jreback** [comment]
@sinhrks this is gr8.

**Comment by sinhrks** [comment]
@jreback I looked through `generic.py` and `indexing.py`, and all the `_constructor` looks have required ``__finalize__``, except for intermediate output purpose.

**Comment by jreback** [comment]
thanks!

**Comment by jreback** [comment]
interested in #8572 ?

**Pull request merged**
