### PR TITLE
CI: Pin ipython version

### LINKED ISSUE #48431: CI: Docbuild started to fail
As far as I can see, this was unrelated to any changes we added

https://github.com/pandas-dev/pandas/runs/8218023423?check_suite_focus=true

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #48431 (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Should fix the docbuild till they release the fix

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]
`Doc build and Upload` and `Code Checks` are green so LGTM.

**Comment by phofl** [comment]
I checked this in more detail, I don't think we need the okexcept at all, this builds ok locally

image

**Comment by mroeschke** [comment]
Perfect thanks @phofl

**Comment by phofl** [comment]
Ok second thought,
Maybe should backport to 1.4.x too just in case we need another release?

**Comment by mroeschke** [comment]
Sure, a manual backport should be fine just in case.

**Pull request merged**
