### PR TITLE
DOC: GH39672 Pandas dataframe pct_change function arguments

### LINKED ISSUE #39672: Pandas dataframe pct_change function arguments
Typically financial data is ordered by columns in reverse chronology ie columns '2020', '2019', '2018', '2017'.. But we need the pct_change function in reverse order. Looking at the Pandas reference (last example): https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pct_change.html?highlight=pct_change#pandas.DataFrame.pct_change

df.pct_change(axis='columns')

           2016    2015         2014

GOOG NaN -0.151997 -0.086016

APPL NaN 0.337604 0.012002

Such a calculation makes no sense or at least is not useful. We need to look at change from today over past period, not past period over future period. Other than iterating in reverse order or transposing, can the pct_change function be augmented with a new argument to reverse the calculation to the form: (A0-A1)/A1 instead of (A1-A0)/A0 ??

### PR DESCRIPTION
**Pull request by ianozsvald**
- [x] closes #39672
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by ianozsvald** [comment]
Running `validate_docstrings.py` produces:
```
# python scripts/validate_docstrings.py pandas.DataFrame.pct_change

################################################################################
################### Docstring (pandas.DataFrame.pct_change)  ###################
################################################################################
...
>>> df = pd.DataFrame({
...     '2016': [1769950, 30586265],
...     '2015': [1500923, 40912316],
...     '2014': [1371819, 41403351]},
...     index=['GOOG', 'APPL'])
>>> df
          2016      2015      2014
GOOG   1769950   1500923   1371819
APPL  30586265  40912316  41403351

>>> df.pct_change(axis='columns', periods=-1)
          2016      2015  2014
GOOG  0.179241  0.094112   NaN
APPL -0.252395 -0.011860   NaN

################################################################################
################################## Validation ##################################
################################################################################

1 Errors found:
	The first line of the Returns section should contain only the type, unless multiple values are being returned
```

Where the last cell with `>>> df.pct_change(axis='columns', periods=-1)` is the docstring I've updated, prior to making this edit the same "1 Error found" message was generated.

**Comment by ianozsvald** [comment]
Running `# ./ci/code_checks.sh ` yields one failure but this is unrelated (surely?) to my PR so I'm not sure what to do about it?

```
Doctests computation DONE
Doctests dtypes
..........................................F...................                                                                                                                                                                         [100%]
================================================================================================================== FAILURES ==================================================================================================================
____________________________________________________________________________________________ [doctest] pandas.core.dtypes.dtypes.DatetimeTZDtype _____________________________________________________________________________________________
654     ------
655     pytz.UnknownTimeZoneError
656         When the requested timezone cannot be found.
657 
658     Examples
659     --------
660     >>> pd.DatetimeTZDtype(tz='UTC')
661     datetime64[ns, UTC]
662 
663     >>> pd.DatetimeTZDtype(tz='dateutil/US/Central')
Expected:
    datetime64[ns, tzfile('/usr/share/zoneinfo/US/Central')]
Got:
    datetime64[ns, tzfile('US/Central')]

/home/pandas-ianozsvald/pandas/core/dtypes/dtypes.py:663: DocTestFailure

```

**Comment by ianozsvald** [comment]
@MarcoGorelli (following up on Gitter but I don't know if you've signed out of there for now) - do I need to do anything or does the perhaps get re-run automatically? I'm not sure what my next step might be? Cheers, Ian.

**Comment by MarcoGorelli** [comment]
Thanks @ianozsvald - the `dtypes` doctest check works fine for me running it on your branch, not sure why you were seeing an error. CI failures are unrelated

**Pull request merged**
