### PR TITLE
update pd.DataFrame.merge - add typing for `how` parameter

### LINKED ISSUE #48503: ENH: `.merge` - specify string literals for `.merge` `how` keyword
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

The `how` keyword for `DataFrame.merge` is typed as a string - which means that type checkers can miss potential errors, as it only accepts a subset of strings ("inner", "outer", "left", "right", "cross").

### Feature Description

`pandas._typing` : add a `MergeHow` type, specifying the string literals that `how` accepts

`pandas.core.frame`: `how` as accepting an argument of type `MergeHow`

### Alternative Solutions

Alternatively we could specify the string literals in the `merge` method function header

### Additional Context

[Related PR for `pandas-stubs`](https://github.com/pandas-dev/pandas-stubs/pull/289#issuecomment-1242756941)

### PR DESCRIPTION
**Pull request by vmayron**
- [x] closes #48503
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by alexc-yellowcanary** [comment]
PR for `pandas-stubs`: https://github.com/pandas-dev/pandas-stubs/pull/289

**Review by phofl — COMMENTED** [review]
Thx, can you add this for join too? Additionally, I think we are typing how internally too, would be great to add this there too

**Comment by twoertwein** [comment]
> Thx, can you add this for join too? Additionally, I think we are typing how internally too, would be great to add this there too

For `DataFrame.join`, you probably need `MergeHow | Literal["cross"]`.

Could also use `MergeHow` in `Index.join/_join* `(in pandas/core/indexes/base.py) and for the align methods `NDFrame/DataFrame/Series.align` (in pandas/core/{generic,frame,series}.py)

**Comment by phofl** [comment]
MergeHow includes cross already?

**Comment by twoertwein** [comment]
> MergeHow includes cross already?

You are right :) Forget about my comment :)

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
