### PR TITLE
TST: Use stronger assertion in test_regression_allowlist_methods

### LINKED ISSUE #49629: TST: Use stronger assertion in `pandas/tests/groupby/test_allowlist.py::test_regression_allowlist_methods`
Before https://github.com/pandas-dev/pandas/pull/49611, `test_regression_allowlist_methods` was a comprehensive groupby test that asserted `frame.groupby(...).op(...)` was equivalent to `frame.op(level=..., ...)`. Now that `level` has been removed, this test should ideally have a stronger assertion than current testing that a DataFrame is returned; ideally using `tm.assert_frame_equal`

### PR DESCRIPTION
**Pull request by isaac-chung**
- [ ] closes #49629
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
Nice. Glad this worked. Thoughts on this approach @rhshadrach? (maybe `agg` should be used instead of `apply` since these are all reductions?

**Review by rhshadrach — APPROVED** [review]
lgtm

> (maybe agg should be used instead of apply since these are all reductions?

apply should produce the same output as agg for a reducer currently, I'm okay with either.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Awesome work @isaac-chung

**Comment by isaac-chung** [comment]
Thanks for your help! @mroeschke

**Pull request merged**
