### PR TITLE
DOC: fix incorrect example in unstack docstring (GH14206)

### LINKED ISSUE #14206: pandas.DataFrame.unstack() documentation example has errors
The last part of the documentation says

```python
>>> df = s.unstack(level=0)
>>> df.unstack()
one  a  1.
     b  3.
two  a  2.
     b  4.
```

although we'd have

```python
>>> import pandas as pd
>>> index = pd.MultiIndex.from_tuples([('one', 'a'), ('one', 'b'),
...                                     ('two', 'a'), ('two', 'b')])
>>> import numpy as np
>>> s = pd.Series(np.arange(1.0, 5.0), index=index)
>>> s
one  a    1.0
     b    2.0
two  a    3.0
     b    4.0
dtype: float64
>>> s.unstack(level=-1)
       a    b
one  1.0  2.0
two  3.0  4.0
>>> s.unstack(level=0)
   one  two
a  1.0  3.0
b  2.0  4.0
>>> df = s.unstack(level=0)
>>> df.unstack()
one  a    1.0
     b    2.0
two  a    3.0
     b    4.0
dtype: float64
```

### PR DESCRIPTION
**Pull request by sudk1896**
- [x] closes #14206 

The following PR closes #14206 and corrects the Docs as suggested in the issue thread.
@jorisvandenbossche Kindly review.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I don't think you actually changed the output? (apart from the floating notation, which is OK). It is the output of `df.unstack()` that was wrong (the 2 and 3 are swapped), and which should be corrected.

**Comment by sudk1896** [comment]
@jorisvandenbossche : Oops, my bad. I corrected the mistake now.

**Comment by jorisvandenbossche** [comment]
@sudk1896 Thanks for the fix! 
(small note: you had a small trailing whitespace error which was captured by our linter (I corrected it), but I would recommend setting your editor to automatically remove trailing whitespace)

**Comment by sudk1896** [comment]
@jorisvandenbossche: Will do from next time. Thanks.

**Pull request merged**
