### PR TITLE
[CLN] cy cleanup, de-duplication

### PR DESCRIPTION
**Pull request by jbrockmendel**
Small cleanups, remove some unnecessary casting, add typing in timezones.

### CODE REVIEW

**Comment by jreback** [comment]
looks fine. may want to run a perf check as touching some sensitive paths.

**Comment by jbrockmendel** [comment]
Traveling today, will run asv when home.  It should be a clear but very
small improvement.

**Comment by jbrockmendel** [comment]
asv is raising git-related errors for me on both linux and mac.  Is anyone else getting these?

**Comment by jbrockmendel** [comment]
Results are probably meaningless, but at least they're all good-meaningless.

```
asv continuous -E virtualenv -f 1.1 master HEAD -b timeseries
[...]
    before     after       ratio
  [da6e26db] [13c4e8a0]
-    8.39ms     7.61ms      0.91  timeseries.ToDatetimeISO8601.time_iso8601_nosep
-    2.36ms     2.11ms      0.89  timeseries.ResampleSeries.time_resample('datetime', '1D', 'ohlc')
-    6.98μs     6.21μs      0.89  timeseries.DatetimeIndex.time_get('tz_aware')
-    5.91μs     5.01μs      0.85  timeseries.DatetimeIndex.time_get('tz_naive')
```

**Comment by jreback** [comment]
thanks !

**Pull request merged**
