### PR TITLE
REF: avoid returning self in io.pytables

### PR DESCRIPTION
**Pull request by jbrockmendel**
Another small step towards making these less stateful

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@jreback it looks like the LegacyFixed methods are not covered in the tests.  Any chance we can rip out those classes?

**Comment by jbrockmendel** [comment]
also read_sparse_intindex, write_sparse_intindex, read_block_index, write_block_index, so we might not need BlockIndex/IntIndex (which are imported from arrays.sparse)?

**Comment by jreback** [comment]
so i think i can blow away all Legacy stuff

i think these read the legacy_hdf dir in data/

but these are quite old iirc


also exception on line 635 can remove that is some versions prior to what we support now

**Comment by jbrockmendel** [comment]
great, i'll make a PR specific to ripping that stuff out.  hopefully that will snowball into more simplfications

**Comment by jreback** [comment]
thanks

**Pull request merged**
