### PR TITLE
CI: fix test for SSL warning

### PR DESCRIPTION
**Pull request by Dr-Irv**
follow up to #41083 to change test

### CODE REVIEW

**Comment by jbrockmendel** [comment]
any idea why str(actual_warning) doesnt work here?

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by Dr-Irv** [comment]
> any idea why str(actual_warning) doesnt work here?

No clue.  But I looked at output from one of my CI runs and saw that the message is what contains the string

**Comment by jreback** [comment]
thanks @Dr-Irv

**Pull request merged**
