### PR TITLE
Update cython version for asv conf

### LINKED ISSUE #44067: BUG: CI cannot create benchmark environments with Cython < 0.29.24
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
asv continuous -f 1.1 -E virtualenv upstream/master HEAD -b style.Render

RuntimeError: Cannot cythonize with old Cython version (0.29.21 installed, needs 0.29.24)
```

### Issue Description

Needed to update `asv.conf.json` to get this to work.

### Expected Behavior

probably need to update dependency verisons.

### Installed Versions

master at 17 Oct.

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #44067

### CODE REVIEW

**Review by alimcmaster1 — APPROVED** [review]
Do any of the benchmarks change dramatically with this change?

**Review by alimcmaster1 — COMMENTED** [review]
`cython>=0.29.21` seems to be in environment.yml. Think this needs bumped.

**Comment by jreback** [comment]
we bumped the min to support 3.10

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by phofl** [comment]
Modified enviornment and requirements too

**Comment by simonjayhawkins** [comment]
> Do any of the benchmarks change dramatically with this change?

I changed this on the 1.3.x tracker (https://simonjayhawkins.github.io/fantastic-dollop/) a couple of weeks back. Haven't noticed any significant changes.

**Comment by jbrockmendel** [comment]
FWIW ive changed my local asv.conf.json to use py39

**Review by jreback — APPROVED** [review]
lgtm merge away

**Pull request merged**
