### PR TITLE
[CI] Add pip dependence explicitly

### LINKED ISSUE #27374: CI: conda warning
from "setup environment" stage:

``` 
conda env create -q --file=ci/deps/azure-macos-35.yaml
Warning: you have pip-installed dependencies in your environment file, 
but you do not list pip itself as one of your conda dependencies. 
Conda may not use the correct pip to install your packages,
and they may end up in the wrong place. 

Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```

```
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

### PR DESCRIPTION
**Pull request by makbigc**
Close #27374. Get rid of the conda warning.

### CODE REVIEW

**Comment by datapythonista** [comment]
@makbigc can you add it to the other CI deps too? If it makes sense to have it for that build, I guess it makes sense to have it in all them (and also `environment.yml`).

Thanks!

CC: @TomAugspurger

**Comment by TomAugspurger** [comment]
Agreed with doing it for all the env files.

**Comment by makbigc** [comment]
Added in other builds. And pip is already added in environment.yml.
https://github.com/pandas-dev/pandas/blob/e118b1d6b23d1d829c3db05505ef4873f0314e99/environment.yml#L55

**Comment by datapythonista** [comment]
Sorry I wasn't very specific @makbigc, but I meant to add it to the dependency files where pip is being used, we don't need it in the files where there are no pip dependencies. For what you say I guess it was only missing in the file you initially changed. Sorry about that.

**Comment by makbigc** [comment]
It doesn't matter. I haven't done a lot of work.
`azure-macos-35.yaml`  is the only file which doesn't specify pip dependence explicitly but use pip to install other packages.

**Review by datapythonista — APPROVED** [review]
Cool, thanks @makbigc.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
