### PR TITLE
BUG: `Styler.to_latex` now doesn't manipulate the `Styler` object.

### LINKED ISSUE #42320: BUG: `Styler.to_latex` permanently impacts `table_styles` for successive calls
For

```styler = DataFrame([[1]]).style```

doing

```styler.to_latex(hrules=True)``` (or any other kw argument which impacts `table_styles`)

results in:

```
\begin{tabular}{lr}
\toprule
{} & {0} \\
\midrule
0 & 1 \\
\bottomrule
\end{tabular}
```

Now doing 

```styler.to_latex(hrules=False)```

still results in 

```
\begin{tabular}{lr}
\toprule
{} & {0} \\
\midrule
0 & 1 \\
\bottomrule
\end{tabular}
```

because the `table_styles` attribute on `styler` has been overwritten by first call which dominates the second.

### PR DESCRIPTION
**Pull request by attack68**
- [x] closes #42320 
- [x] tests added / passed
- [x] whatsnew entry not needed if included in 1.3.0 (although will be needed for 1.3.1)

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
> [ ] whatsnew entry (probably for 1.3.1)

you can put in 1.3.0 for review purposes and move later. (after #42312)

although there seems to be conda-incubator/setup-miniconda@v2 issues today which could slow down the ability to release

**Comment by attack68** [comment]
> > [ ] whatsnew entry (probably for 1.3.1)
> 
> you can put in 1.3.0 for review purposes and move later. (after #42312)
> 
> although there seems to be conda-incubator/setup-miniconda@v2 issues today which could slow down the ability to release

if thats the case then not technically necessary for 1.3.0 (it fixes a feature that was added for 1.3.0)

**Comment by simonjayhawkins** [comment]
@jreback ok for 1.3 (we have issues with #42304 that's blocking release)

**Comment by jreback** [comment]
thanks @attack68

**Comment by jreback** [comment]
@attack68 

shouldn't the following render the output as Latex in a notebook?

```
df = pd.DataFrame([[1, 2.2, "dogs"], [3, 4.4, "cats"], [2, 6.6, "cows"]],
                  index=["ix1", "ix2", "ix3"],
                  columns=["Integers", "Floats", "Strings"])
s = df.style.highlight_max(
    props='cellcolor:[HTML]{FFFF00}; color:{red};'
          'textit:--rwrap; textbf:--rwrap;'
)

from IPython.display import display, Latex
display(Latex(s.to_latex()))
```

**Comment by attack68** [comment]
@jreback I don't use LaTeX much in a notebook but I believe Jupyter uses MathJax to render and Mathjax does not support all LaTeX environements including tabular, so this just displays as text in a box.

**Pull request merged**
