### PR TITLE
TST/ERR: GH10369 read_msgpack checks argument type

### LINKED ISSUE #10369: pandas.read_msgpack(None) returns [78, 111, 110, 101]
It should return an error, as that's what it most likely is. 

If someone is really sending empty msgpacks out there to transmit [78, 111, 110, 101], they could add a special case.

### PR DESCRIPTION
**Pull request by kawochen**
To close #10369

### CODE REVIEW

**Comment by jreback** [comment]
nice - pls add a release note

**Comment by kawochen** [comment]
Sure. In which section does this belong?

**Comment by jreback** [comment]
I'd call this a bug fix

**Comment by kawochen** [comment]
@jreback tests are green.

**Comment by jreback** [comment]
@kawochen thanks!

**Pull request merged**
