### PR TITLE
Backport PR #25171 on branch 0.24.x

### PR DESCRIPTION
**Pull request by albertvillanova**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
why did u push this? backports are done automatically

**Comment by jreback** [comment]
ic you followed the manual back port instructions, ok.

**Comment by albertvillanova** [comment]
@jreback yes, I was asked to backport manually. All checks have passed.

**Comment by jreback** [comment]
thanks @albertvillanova

**Pull request merged**
