### PR TITLE
Standard library imports

### PR DESCRIPTION
**Pull request by Thextan**
This is part 1 of 2 making style changes to GH49647

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Hey @Thextan 

you wrote on Slack about how you'd got some flake8 errors - looking at https://github.com/pandas-dev/pandas/actions/runs/3586876309/jobs/6036589332, it seems that flake8 passed

the only one failing is `stdlib-imports`, which you should fix as part of this PR

**Comment by Thextan** [comment]
Marco,

I may need some help with this push request. Those stdlib-imports are the files I worked on. I don't think I am merging my changes correcly.
Below is what I asked about. running pre-commit run stdlib-imports --all-files showed all files passed (with the pandas/tests excluded).

flake8..................................................................................................Failed
- hook id: flake8
- exit code: 1

pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.BOOL' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.DWORD' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.HANDLE' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.HGLOBAL' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.HINSTANCE' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.HMENU' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.HWND' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.INT' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.LPCSTR' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.LPVOID' imported but unused
pandas/io/clipboard/__init__.py:56:1:F401 'ctypes.wintypes.UINT' imported but unused

isort...................................................................................................Passed

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by MarcoGorelli** [comment]
to push your changes, you need to do:
```
git add -u
git commit -a -m 'fixed up standard library imports'
git push origin HEAD
```

**Comment by Thextan** [comment]
> to push your changes, you need to do:
> 
> ```
> git add -u
> git commit -a -m 'fixed up standard library imports'
> git push origin HEAD
> ```

on git commit ... I get the flake8 errors.
on git push ... I get 
 ! [rejected]              HEAD -> standard-library-imports (fetch first)
error: failed to push some refs to 'github.com:Thextan/pandas.git'
I ran 
git pull git@github.com:Thextan/pandas.git standart-library-imports
git fetch origin
git push origin HEAD
Now says Everything up-to-date.

what should be my next step?

**Comment by MarcoGorelli** [comment]
you can do `git commit -a -m 'fixed up standard library imports' -n` (with the `-n` at the end) to skip the pre-commit checks when committing

**Pull request closed without merging**
