### PR TITLE
DOC: Add note about unicode layout

### PR DESCRIPTION
**Pull request by sinhrks**
Follow-up for #11102. Added note because doc output may look incorrect depending on font.

### CODE REVIEW

**Comment by jreback** [comment]
hmm maybe better to put this in a code block which has a mono spaced font?

**Comment by sinhrks** [comment]
OK, let me check code block results.

**Comment by jreback** [comment]
@sinhrks ?

**Comment by jreback** [comment]
@sinhrks ?

**Comment by sinhrks** [comment]
I may misunderstand something, but code block doesn't use monospaced font always? I tried both ``::`` and ``.. code-block::``, but the results look same.

#### Markdown

```
::

    >>> df = pd.DataFrame({'a': ['xxx', u'¡¡'], 'b': ['yyy', u'¡¡']})
    >>> df
         a    b
    0  xxx  yyy
    1   ¡¡   ¡¡

.. code-block:: python

   >>> df = pd.DataFrame({'a': ['xxx', u'¡¡'], 'b': ['yyy', u'¡¡']})
   >>> df
        a    b
   0  xxx  yyy
   1   ¡¡   ¡¡
```

#### Output



Do you know any way to force all characters to be monospaced? Alternative idea is attach the screenshot of the console...

CC: @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
Hmm, don't think I can help here. So the 'easy' solution is indeed to use a picture that shows the effect (I think that is better than the note in any case, as the user can then visually see what is meant)

Some possible things: the output during the doc built is always decoded to utf-8 in a hack in the ipython directive (https://github.com/pydata/pandas/blob/master/doc/sphinxext/ipython_sphinxext/ipython_directive.py#L255) 
It happens with the ambiguous width characters? And you needed to change something (the previous PR) to ensure the console output shows correcty? So maybe a similar issue is the case here with the sphinx directive

**Comment by sinhrks** [comment]
@jorisvandenbossche Thanks to confirm. The screen capture using ipython directive is attached on the bottom of #11102. Affected characters seems to depend on environment. At a quick glance, CSS doesn't specify monospaced font for highlight blocks.

As a workaround, updated to attach screen captures of each output as below.

**Comment by jreback** [comment]
thanks @sinhrks

**Pull request merged**
