### PR TITLE
CLN: _consolidate_inplace less

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jreback** [comment]
great. any perf impact? (i know this means running a big asv.....)

**Comment by jbrockmendel** [comment]
> i know this means running a big asv

im dealing with hardware issues that keep me from running this for a while

**Comment by jreback** [comment]
> > i know this means running a big asv
> 
> im dealing with hardware issues that keep me from running this for a while

ok happy to merge this now then

**Comment by jorisvandenbossche** [comment]
I don't think this should have been merged without any discussion or performance check?

**Comment by jreback** [comment]
sure the nightly regression should show this in any event: https://pandas.pydata.org/speed/pandas/#regressions?sort=1&dir=desc

but maybe note updating recently? @TomAugspurger

**Comment by TomAugspurger** [comment]
Seems to have segfaulted when compiling pandas a couple weeks back and
never recovered.

I won't have time to debug this for a little while.

**Comment by jorisvandenbossche** [comment]
>  the nightly regression should show this in any event

Not necessarily, we don't have benchmarks for all functionality and use cases.

The current BlockManager is optimized to deal with consolidated blocks. At once not consolidating anymore before certain operations, has the *potential* to cause a slowdown for those operations (where the slowdown could in principle be more than the gain of not consolidating). It might very well be that none of the changes has any impact. But I can't tell that without checking. And I don't think we should do that without checking. 
So my proposal is to revert the PR for now, until someone has time to check it.

**Comment by jorisvandenbossche** [comment]
(and note that this is not in conflict with what I am saying on the mailing list. It's my opinion that we should optimize the case of "many 1D blocks" in the internals, but that doesn't mean that right now "many 2D blocks" is optimized).

**Comment by jreback** [comment]
its fine to revert if you want @jbrockmendel can you put up a PR. but going to continue optimizing generally anyhow.

**Comment by jorisvandenbossche** [comment]
I already made the branch before (using github's "revert" button), so -> https://github.com/pandas-dev/pandas/pull/34407

**Pull request merged**
