### PR TITLE
Save the name of undefined variables in expressions.

### PR DESCRIPTION
**Pull request by kalekundert**
This can be useful information for downstream error-handling code.

### CODE REVIEW

**Comment by jreback** [comment]
would need a test to show the use of this

**Review by jreback — CHANGES_REQUESTED** [review]
see comments

**Comment by jbrockmendel** [comment]
@kalekundert can you make a test case out of some of the downstream code that motivated this?  Once this is tested this will be about ready.

**Comment by jbrockmendel** [comment]
@kalekundert ping re implementing a test.

**Comment by WillAyd** [comment]
Closing as stale. Ping if you'd like to reopen

**Pull request closed without merging**
