### PR TITLE
TST: Add pytest-instafail to environment.yml

### PR DESCRIPTION
**Pull request by dsaxton**
Pretty useful pytest plugin for getting immediate feedback on test failures instead of waiting for an entire test suite to run:

```
(pandas-dev) ➜  pandas git:(add-pytest-instafail) ✗ pytest pandas/tests/groupby --instafail
============================================================================================ test session starts ============================================================================================
platform darwin -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/danielsaxton/pandas, configfile: setup.cfg
plugins: hypothesis-5.28.0, forked-1.2.0, asyncio-0.12.0, xdist-2.1.0, cov-2.10.1, instafail-0.4.1
collected 4533 items                                                                                                                                                                                        

pandas/tests/groupby/test_allowlist.py .............................................................................................................................................................. [  3%]
...........................................................                                                                                                                                           [  4%]
pandas/tests/groupby/test_apply.py ............x.x.x...................................................x..........................F

________________________________________________________________________________________________ test_fails _________________________________________________________________________________________________

    def test_fails():
>       assert False
E       assert False

pandas/tests/groupby/test_apply.py:1101: AssertionError

pandas/tests/groupby/test_apply_mutate.py ...                                                                                                                                                         [  6%]
pandas/tests/groupby/test_bin_groupby.py ..........                                                                                                                                                   [  7%]
pandas/tests/groupby/test_categorical.py .....................................................................................xxx..............................sss................................x.. [ 10%]
...
```

### CODE REVIEW

**Comment by jreback** [comment]
is this not exactly what
```
  -x, --exitfirst       exit instantly on first error or failed test.
```
does? part of pytest itself

**Comment by jreback** [comment]
and we do not want to do this in CI builds.

**Comment by dsaxton** [comment]
This continues running the test suite on test failure, only shows the output of failures. In general I think that's a bit more useful than exiting the whole run.

**Comment by jreback** [comment]
ahh so it shows it as it goes, but still runs the entire thing, ok, that's useful.

**Comment by jbrockmendel** [comment]
LGTM pending green

**Comment by jreback** [comment]
thanks @dsaxton

**Pull request merged**
