### PR TITLE
DOC: Fix extending.rst code style #36777

### LINKED ISSUE #36777: DOC: Fix code style in documentation
The docs use certain coding style conventions that are no longer used in pandas (e.g., we adopt black's opinions in terms of line wrapping and quoting), for instance https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html. We should update the docs to match current style preferences.

[blacken-docs](https://github.com/asottile/blacken-docs) is a useful tool that can help in doing _some_ of this formatting, but it has to be used carefully since it might render lines that are too long and will fail flake8-rst checks, or it may not be able to parse certain files because of nuances in how the docs are written (raw output or magic commands in code blocks). One approach is to comment out the erring lines, let the tool handle all the others, then finish the commented lines manually.

Example cleanup: https://github.com/pandas-dev/pandas/pull/36700/files

List of files that need updating (if you submit a PR be sure to link back to this issue):

**doc/source/development:**

- [x] code_style.rst
- [x] contributing.rst
- [x] contributing_docstring.rst
- [x] developer.rst
- [x] extending.rst
- [x] index.rst
- [x] internals.rst
- [x] maintaining.rst
- [x] meeting.rst
- [x] policies.rst
- [x] roadmap.rst

**doc/source/getting_started/comparison:**

- [x] comparison_with_r.rst
- [x] comparison_with_sas.rst
- [x] comparison_with_sql.rst
- [x] comparison_with_stata.rst
- [x] index.rst

**doc/source/getting_started/intro_tutorials:**

- [x] 01_table_oriented.rst
- [x] 02_read_write.rst
- [x] 03_subset_data.rst
- [x] 04_plotting.rst
- [x] 05_add_columns.rst
- [x] 06_calculate_statistics.rst
- [x] 07_reshape_table_layout.rst
- [x] 08_combine_dataframe.rst
- [x] 09_timeseries.rst
- [x] 10_text_data.rst

**doc/source/getting_started:**

- [x] index.rst
- [x] install.rst
- [x] overview.rst
- [x] tutorials.rst

**doc/source/user_guide**:

- [x] 10min.rst
- [x] advanced.rst
- [x] basics.rst
- [x] boolean.rst
- [x] categorical.rst
- [x] computation.rst
- [x] cookbook.rst
- [x] dsintro.rst
- [x] duplicates.rst
- [x] enhancingperf.rst
- [x] gotchas.rst
- [x] groupby.rst
- [x] index.rst
- [x] integer_na.rst
- [x] io.rst
- [ ] merging.rst
- [x] missing_data.rst
- [x] options.rst
- [x] reshaping.rst
- [x] scale.rst
- [x] sparse.rst
- [x] text.rst
- [x] timedeltas.rst
- [x] timeseries.rst
- [x] visualization.rst

### PR DESCRIPTION
**Pull request by aniaan**
ref #36777
I tried to format development/extending.rst, please review
cc @dsaxton

### CODE REVIEW

**Comment by erfannariman** [comment]
Thanks for the PR. Can you replace "closes 36777" to "ref 36777" in your description, this is part of the issue, it will not solve it and close it.

**Comment by BeanNan** [comment]
> Thanks for the PR. Can you replace "closes 36777" to "ref 36777" in your description, this is part of the issue, it will not solve it and close it.

I have adjusted description, take a look

**Review by erfannariman — APPROVED** [review]

**Comment by erfannariman** [comment]
Thanks @BeanNan lgtm

**Comment by dsaxton** [comment]
@BeanNan Can you merge master? Another PR was merged that also touched this file.

**Pull request closed without merging**
