### PR TITLE
Change width of specific columns using col_space param in df.to_html

### LINKED ISSUE #28917: DataFrame.to_html col_space parameter to change width of a specific column only
#### Problem description

Currently `col_space` changes width of all columns that are present in the dataframe. There must be a way to change the width of a specific column only while converting dataframe to html.

#### Expected Output
`col_space` to accept a list or dict where we can mention the column name to change only a specific column's width.

### PR DESCRIPTION
**Pull request by SRIRAM777**
DataFrame.to_html col_space parameter to change width of a specific column only

- [ ] closes #28917 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@SRIRAM777 there is already a PR for this, see #28929.

**Comment by SRIRAM777** [comment]
> @SRIRAM777 there is already a PR for this, see #28929.

Hi @simonjayhawkins Since you had requested to avoid the usage of an additional argument in that PR, I thought of utilizing the existing argument col_space to accept dict values like {'col1':25,'col2':50} to handle column width for specific columns. I'm new to open source contribution. Am I not supposed to raise another PR when there's already one?

**Comment by simonjayhawkins** [comment]
we don't encourage competing PRs. The other PR is not stale. The OP is awaiting some clarification on the requirements. If you could review that PR and make suggestions, that'll be great.

**Comment by SRIRAM777** [comment]
> we don't encourage competing PRs. The other PR is not stale. The OP is awaiting some clarification on the requirements. If you could review that PR and make suggestions, that'll be great.

@simonjayhawkins Sorry about that. So, should I close this one?

**Comment by simonjayhawkins** [comment]
> So, should I close this one?

for now, that's probably best.

Thanks for taking the time to look into this.

**Pull request closed without merging**
