### PR TITLE
Backport PR #57553 on branch 2.2.x (API: avoid passing Manager to subclass init)

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by mroeschke** [comment]
I didn't realize this was going to be backported. Would be good to have a whatsnew note in `v2.2.2.rst`

**Comment by jbrockmendel** [comment]
> 
I didn't realize this was going to be backported. Would be good to have a whatsnew note in v2.2.2.rst

Good idea.  Do I add the note in this PR or does it need to go into a PR in main?

**Comment by mroeschke** [comment]
>  Do I add the note in this PR or does it need to go into a PR in main?

Yeah the note should go into main and 2.2.x.

**Comment by jbrockmendel** [comment]
> Yeah the note should go into main and 2.2.x.

Done in #58075

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
