### PR TITLE
Feature: Memory Layout of DataFrames ndarrays can be set/changed

### LINKED ISSUE #26502: Copy and grouby-sum changes column-major-ordering to row-major-ordering with huge impact on performance
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd

print("pandas version: ", pd.__version__)

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array.flags
print("Numpy array is C-contiguous: ", data.flags.c_contiguous)

dataframe = pd.DataFrame(array, index = pd.MultiIndex.from_tuples([('A', 'U'), ('A', 'V'), ('B', 'W')], names=['dim_one', 'dim_two']))
print("DataFrame is C-contiguous: ", dataframe.values.flags.c_contiguous)

dataframe_copy = dataframe.copy()
print("Copy of DataFrame is C-contiguous: ", dataframe_copy.values.flags.c_contiguous)

aggregated_dataframe = dataframe.groupby('dim_one').sum()
print("Aggregated DataFrame is C-contiguous: ", aggregated_dataframe.values.flags.c_contiguous)

## Output in Jupyter Notebook
# pandas version:  0.23.4
# Numpy array is C-contiguous:  True
# DataFrame is C-contiguous:  True
# Copy of DataFrame is C-contiguous:  False
# Aggregated DataFrame is C-contiguous:  False

```
#### Problem description

pandas.DataFrame.copy return a copy with underlying numpy array with the major-ordering changed from C to F if initially was C order

pandas.DataFrame.groupby.sum return a a DataFrame with underlying numpy array with the major-ordering changed from C to F if initially was C order on the DataFrames values.

This impacts performance on aggregation substantially! I observer a decrease from 17 seconds to 5 min 46 seconds when aggregating on the index on a 45023 times 100000 scenarios dataset.

Copy and Aggregation operations need to preserve the major-order on the underlying data! 

#### Expected Output

```python
# Output in Jupyter Notebook
 pandas version:  0.23.4
 Numpy array is C-contiguous:  True
 DataFrame is C-contiguous:  True
 Copy of DataFrame is C-contiguous:  True
 Aggregated DataFrame is C-contiguous:  True
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.14.4.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.2.3
pip: 19.0.2
setuptools: 40.8.0
Cython: 0.22
numpy: 1.15.4
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.6.3
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 2.2.2
openpyxl: 2.4.7
xlrd: 1.1.0
xlwt: None
xlsxwriter: 1.0.2
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.3.3
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by TannhauserGate42**
- [ ] closes #26502
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by TomAugspurger** [comment]
At a glance, this doesn’t seem to integrate well with the rest of pandas. I don’t think a library-level global is the way to go. I’d recommend writing a proposal summarizing the issue and a design for a fix first.

**Review by jreback — CHANGES_REQUESTED** [review]
so you would need
- substantial tests l / asserts in the code to prove this actually works
- full asv runs to show this doesn’t reduce performance anywhere and increases in. some cases
- this looks very java-esque code - is there a reason you did it this way?

**Comment by TannhauserGate42** [comment]
> so you would need
> 
> * substantial tests l / asserts in the code to prove this actually works
> * full asv runs to show this doesn’t reduce performance anywhere and increases in. some cases
> * this looks very java-esque code - is there a reason you did it this way?

I apologise for my simple code.

In any case, the code is quite explicit and easy to read. Java, don't say that ...

It was not easy to find the source of the current inconsistency in pandas (first aggregation is fast, and all subsequent slow due to implicit and inconsistent change to F-major-ordering by a side effect)

In any case, the current pandas versions have a 'bug': pandas flips uncontrolled from C to F major order. It writes to HDFStores in C-major-order and reads as such. It flips and consumes time to F due to a transpose and subsequent copy operation which leads implicitly to F-major-ordering (I can explain this elsewhere if you are interested)

The problem with this is not only that performance suffers, as I have shown in my examples. But the developer / analyst cannot choose the memory layout appropriate for his analysis. 

This is a shortcoming, together with the inconsistent layout flip it is a no-go.

**Comment by TannhauserGate42** [comment]
> At a glance, this doesn’t seem to integrate well with the rest of pandas. I don’t think a library-level global is the way to go. I’d recommend writing a proposal summarizing the issue and a design for a fix first.

For sure, it does not fit nicely into the current pandas, but it fixes a but and leads to much higher performance. 

The new code is very well separated and can easily be removed, once a better concept is available. 

Besides implementatory details, a global setting/switch is maybe even the right way to go. You can switch the behaviour for all your instances. Using pandas in a business application, this is safest. You don't want to keep track where you use which layout. Within a notebook you can do the same. In both cases you can chose the 'K' option, which means keep the major order of the instance to copy. The provided implementation fullfills this requirement. The current pandas does none of them. This is especially infortunate, because numpy does very well with it and taking it over would not be a great deal.

**Comment by jreback** [comment]
@TannhauserGate42 you are missing the point
if you claim performance improvements then you need you need to show them and show that there are no regressions (which is very doubtful)

**Comment by jreback** [comment]
this is also on the wrong branch; it must be a PR to master
but before this is even considered you need to show perf

**Comment by TannhauserGate42** [comment]
> this is also on the wrong branch; it must be a PR to master
> but before this is even considered you need to show perf

Since we have 0.23.4 in our company, I branched out from that one. 
(had problems with tornado, dask, distributed, numpy and pandas on Azure and could not upgrade to a higher version) 
But, I could bring it into master too, sooner or later.

**Comment by TannhauserGate42** [comment]
> @TannhauserGate42 you are missing the point
> if you claim performance improvements then you need you need to show them and show that there are no regressions (which is very doubtful)

I see that point. Sure.

Are there performance tests already in place in the test suite of pandas? I can come up with some. But don't know how to integrate in the test suite ...

I would like to create a build which I can use in my application ... Is it possible to create one via GitHub from my branch? I would load it into artifactory and create a build of my two applications then ... 

There will be one regression for sure!!! But each bugfix shows a regression.

The current pandas is able to create a C-ordered frame and will implicitly convert it to a F-ordered. Depending on the performance tests already in place, these may perform better or worse due this behaviour. Now one explicitly choses the order or uses at least the consistent order set per default.

Suppose you have a test where you create a fixture and aggregate two times on the same frame. A pre-aggregation and a subsequent aggregation. Then you might aggregate on a C-ordered array first and on a F-ordered in the second place. With the new default setting one would preaggregate already on a F-ordered and then again on a F-ordered array. So I expect for sure a regression. If one sets the order with the new ArrayLayout to C, then one would also observe a change. Whether it performs better or worse depends on the use case, whether one aggregate on the rows or columns.

But let's check it. 

When I'm back in the office tomorrow, we will integrate it into our application and let's see ... 
Should it work, I will continue here.

**Comment by jreback** [comment]
http://pandas-docs.github.io/pandas-docs-travis/development/contributing.html#running-the-performance-test-suite

as i said this change would need to be on top of master

**Pull request closed without merging**
