### PR TITLE
DEPR: deprecate Index.is_object

### PR DESCRIPTION
**Pull request by bang128**
- [ ] progress towards https://github.com/pandas-dev/pandas/issues/50042
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by bang128** [comment]
@topper-123 Do you know what I got wrong? I have looked at some other pull requests, but they have both common and different files to fix. Actually, I am not sure how to detect which file I should change is_object to is_object_dtype. Do you have any suggestion for me?

**Comment by topper-123** [comment]
Hi @bang128 I think you're getting quite close. The issues that I see are:

1: doc/source/whatsnew/v2.0.0.rst
There are some artifacts in `doc/source/whatsnew/v2.0.0.rst` likely from a git rebase. Can you fix those.

2: failures
In general you need to go through the test logs above (click the "detalis" button) to see which errors have been raised. I can see these, which need to be fixed in one test log:

```
FAILED pandas/tests/series/methods/test_describe.py::TestSeriesDescribe::test_numeric_result_dtype[complex] - TypeError: a must be an array of real numbers
FAILED pandas/tests/series/methods/test_describe.py::TestSeriesDescribe::test_numeric_result_dtype[complex64] - TypeError: a must be an array of real numbers
FAILED pandas/tests/series/methods/test_describe.py::TestSeriesDescribe::test_numeric_result_dtype[complex128] - TypeError: a must be an array of real numbers
```

Looks like something related to the treatment of complex numbers. I'm not able to run these tests right now, but if you could attempt to solve them, I can take a closer look tonight and help you fix them, if you haven't been able to before.

There may be others, I haven't checked all test failures.

**Comment by topper-123** [comment]
Hi @bang128  can you try to fix the issues in `doc/source/whatsnew/v2.0.0.rst` and push again. I think that may be enough to fix this.

Regarding how to find the instances to correct, you should run the pandas test suite locally and fix errors that show up. Depending on your coding proficiency, this may not be entirely trivial, but it'll be a good learning exercise in any case :-)

**Comment by bang128** [comment]
Okay, let me try to fix the doc issue first

**Comment by topper-123** [comment]
Hi @bang

**Comment by topper-123** [comment]
Can you rebase.

**Comment by topper-123** [comment]
Ping. Should I rebase for you?

**Comment by topper-123** [comment]
Hey @bang128 , the rebase was a bit difficult, so I’ve rebased & merged this. Thanks a lot for yoyr contribution!

**Pull request merged**
