### PR TITLE
Update vendored pyperclip to 1.5.8

### LINKED ISSUE #9263: Clipboard functions don't support Unicode on Windows
Recent versions of pyperclip (``pandas.util.clipboard``) use CF_UNICODETEXT getting data from and putting data to the WIndows Clipboard.

### PR DESCRIPTION
**Pull request by jcjf**
Resolves #9263 

Tested:
- [x] windows
- [x] macosx
- [x] linux

### CODE REVIEW

**Comment by jreback** [comment]
add this to the first line of ``test_clipboard.py``

``# -*- coding: utf-8 -*-``

**Comment by jcjf** [comment]
Yeah, I took a look at Travis too... I forgot about those Python 2 peoples!

**Comment by jreback** [comment]
@jcjf further, what platform are you testing this on? (as this requires some 'manual' testing I think), pls check the appropriate box

**Comment by jcjf** [comment]
Hmm... this might be related to https://github.com/asweigart/pyperclip/issues/11

One alternative is to only update the win32 parts of pyperclip. We could take that from pyperclip itself or perhaps from https://github.com/pyreadline/pyreadline/blob/master/pyreadline/clipboard/win32_clipboard.py

**Comment by jcjf** [comment]
@jreback Suggested path forward?

**Comment by jreback** [comment]
actually I think what u did is ok

the test is failing because xclip / xsel is not installed

iirc we were doing this in the install script somewhere

have a look in ci/install_conda.py

lmk

**Comment by jreback** [comment]
@jcjf can u update?

**Comment by jcjf** [comment]
I've been very busy recently and haven't had time to take another look at
this.

**Comment by jcjf** [comment]
So basically my earlier attempts forgot to maintain compatibility by raising a subclass of `OSError`.

I believe the CI builds don't actually test the GTK+ 2 clipboard properly. There isn't any setup that would make `import gtk` work on its own. However, I claim that this was broken before remains broken now, and most people will be using xclip / xsel / PyQt4 / PySide anyway.

**Comment by jreback** [comment]
ok, looks reasonable, can you add a release note for 0.17.0 with the referenced issue. We are claiming this is just a bug fix, yes? (e.g. it now supports unicode on windows).

squash.

Then need to have people tests this out on various system, e.g. some manual validation.

**Comment by jreback** [comment]
can you rebase?

**Comment by jreback** [comment]
this looks reasonable. can people give this a whirl to make sure it works?

**Comment by jreback** [comment]
ok, this works on windows, but is failing on mac. any ideas? (I *think* working on linux as travis is passing)

**Comment by jreback** [comment]
@jcjf want to rebase this

**Comment by jcjf** [comment]
pyperclip upstream has updated to 1.5.15 - maintain the change 1.5.11 only or try to update?

**Comment by jreback** [comment]
@jcjf that sounds fine. The main issue I think was testing on this.

**Comment by jreback** [comment]
can you rebase this

**Comment by jreback** [comment]
ok, can you rebase & add a whatsnew note for 0.18.0

**Comment by jcjf** [comment]
@jreback I've rebased this for the third time now. Can you please indicate whether this is still failing on mac and wheter you intend to merge this soon?

**Comment by jreback** [comment]
This doesn't pass on macosx, not really sure why. Does this pass on windows?

```
======================================================================
FAIL: test_round_trip_frame_sep (pandas.io.tests.test_clipboard.TestClipboard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jreback/pandas/pandas/io/tests/test_clipboard.py", line 71, in test_round_trip_frame_sep
    self.check_round_trip_frame(dt,sep=',')
  File "/Users/jreback/pandas/pandas/io/tests/test_clipboard.py", line 67, in check_round_trip_frame
    tm.assert_frame_equal(data, result, check_dtype=False)
  File "/Users/jreback/pandas/pandas/util/testing.py", line 1012, in assert_frame_equal
    '{0}, {1}'.format(right.shape[1], right.columns))
  File "/Users/jreback/pandas/pandas/util/testing.py", line 819, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame are different

DataFrame shape (number of columns) are different
[left]:  2, Index([u'en', u'es'], dtype='object')
[right]: 0, Index([], dtype='object')
```
seems the index is not matching on the nonascii

```
(Pdb) p data
        en       es
0       in       en
1  English  espa?ol
(Pdb) p result
Empty DataFrame
Columns: []
Index: [0       in       en, 1  English  espa?ol]
(Pdb) p read_clipboard(sep=sep)
           en       es
0  0       in       en
1  1  English  espa?ol
(Pdb) p read_clipboard(sep=sep,index_col=0)
Empty DataFrame
Columns: []
Index: [0       in       en, 1  English  espa?ol]
```

**Comment by jreback** [comment]
these seem to all pass on windows.

**Comment by jreback** [comment]
I will amend. These seem to pass on a vanlilla terminal in macosx, I have a weird xterm going.

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/925f62a690086d52664379a58f35e26b146a9146

thanks!

**Pull request closed without merging**
