### PR TITLE
TST: add cases for nearest_workday and before_nearest_workday

### PR DESCRIPTION
**Pull request by ivanovmg**
- [ ] xref #38139
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Add cases for testing observance rules ``nearest_workday`` and ``before_nearest_workday`` for their full coverage.

### CODE REVIEW

**Comment by jreback** [comment]
can you merge master, CI looks to be acting up.

**Comment by ivanovmg** [comment]
Linux tests are red due to a failure to build environment (new pip).
Windows test failure is irrelevant.

```
    @tm.network
    @pytest.mark.single
    def test_round_trip_exception_(self):
        # GH 3867
        csv = "https://raw.github.com/hayd/lahman2012/master/csvs/Teams.csv"
>       df = pd.read_csv(csv)

```

**Comment by simonjayhawkins** [comment]
> Linux tests are red due to a failure to build environment (new pip).
> Windows test failure is irrelevant.

re-run and green

**Comment by jreback** [comment]
thanks @ivanovmg

**Pull request merged**
