### PR TITLE
CI: testing newer matplotlib with jinja

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by jreback** [comment]
I don't think this should work at all w/o jinja2

just raise a nice error

**Comment by TomAugspurger** [comment]
Are you talking about the warnings? those were just so I could see them in the Travis logs (wasn't sure when setUpModule gets called). It errors as soon as you `df.style` if you don't have Jinja.

**Comment by tacaswell** [comment]
I am a tad confused about the link between mpl and jinja...

**Comment by TomAugspurger** [comment]
Well I'm extremely confused by it :). I haven't been able reproduce it locally, but from my other PR I found out that *trying* to import Jinja, whether it's installed or not, was was what caused the failures, which makes no sense at all. It's [these](https://github.com/pydata/pandas/blob/master/ci/requirements-2.7_LOCALE.run) requirements if your curious (that's matplotlib 1.2.1, so you might not be).

**Comment by jreback** [comment]
@TomAugspurger keep open?

**Pull request closed without merging**
