### PR TITLE
BUG: fix timedelta floordiv with scalar float (correction of #44466)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Follow-up on https://github.com/pandas-dev/pandas/pull/44466#discussion_r749430496

I still need to add a test that would actually catch this

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Actually, I don't directly find a way to edit the test that it would have catched this. It seems that in practice timedelta division already acts similar as a floor division:

```
In [16]: np.array([1, 2, 3, 4, 5], dtype="m8[ns]") / 3
Out[16]: array([0, 0, 1, 1, 1], dtype='timedelta64[ns]')

In [17]: np.array([1, 2, 3, 4, 5], dtype="m8[ns]") // 3
Out[17]: array([0, 0, 1, 1, 1], dtype='timedelta64[ns]')

In [18]: np.array([1, 2, 3, 4, 5], dtype="m8[ns]").astype(float) / 3
Out[18]: array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])
```

(so the integers for timedelta divison result already seem to be obtained with a floor round)

**Comment by jorisvandenbossche** [comment]
Actually with a round towards zero (so ``np.fix`` and not `np.floor`), but that is still done for both division and floor division.

**Comment by jorisvandenbossche** [comment]
To conclude: this can be merged as is?

**Comment by jbrockmendel** [comment]
later today ill look at the scalar timedelta tests to see if past-me came up with anything.

**Comment by jbrockmendel** [comment]
BTW @jorisvandenbossche can you take a look at #43840

**Comment by jbrockmendel** [comment]
Looking at the scalar `Timedelta.__floordiv__` i dont see anywhere where this makes a difference.

LGTM

**Comment by jorisvandenbossche** [comment]
OK, merging this then

**Pull request merged**
