### PR TITLE
CLN: use putmask_simple instead of putmask

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jreback** [comment]
looks fine, i assume this doesn't have any perf differences as no tests broke (so for example we are not coercing to object any differnt than current).

**Comment by jbrockmendel** [comment]
> (so for example we are not coercing to object any differnt than current).

definitely not, the point of this is to use the method that _never_ coerces

**Comment by jreback** [comment]
> > (so for example we are not coercing to object any differnt than current).
> 
> definitely not, the point of this is to use the method that _never_ coerces

sure, benchmarks should show that something unintential didn't change

**Comment by jreback** [comment]
am sure you are keeping track of perf

**Pull request merged**
