### PR TITLE
BUG: frame.shift(axis=1) with ArrayManager

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by mroeschke — COMMENTED** [review]
LGTM. Just needs a whatsnew note.

**Comment by jbrockmendel** [comment]
> Just needs a whatsnew note

should only affect ArrayManager, which isn't public/documented.

**Review by mroeschke — APPROVED** [review]

**Comment by jreback** [comment]
still don't reallly like this code path but ok. ping on green.

**Comment by jbrockmendel** [comment]
ping

**Pull request merged**
