### PR TITLE
REF: Implement isin on DTA instead of DTI

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by jreback — COMMENTED** [review]
looks reasonable, pre commit failing

**Review by jorisvandenbossche — COMMENTED** [review]
Why add it to the array class while for none of our other EAs it is implemented on the array? 

(now, this could also be an indication we _should_ think about adding `isin` more generally)

**Comment by jbrockmendel** [comment]
> Why add it to the array class while for none of our other EAs it is implemented on the array?

1) it is implemented on Categorical
2) jreback requested the move in #37528
3) i intend to de-duplicate code in `isin`, `equals`, and `_validate_listlike`

**Comment by jorisvandenbossche** [comment]
OK, sounds good

**Comment by jreback** [comment]
thanks @jbrockmendel 

yeah I am +1 on adding .isin too the base class (and coercion would go thru `_from_sequence` so likely this would mostly be a base-class method (not much need to override)

**Pull request merged**
