### PR TITLE
TST: GH30999 Add match=msg to all "with pytest.raises" in pandas/tests/io/pytables/test_store.py

### PR DESCRIPTION
**Pull request by moink**
This pull request xref #30999 to remove bare `pytest.raises`. It doesn't close that issue as I have only addressed one file: `pandas/tests/io/pytables/test_store.py`. In that file there were 80 instances of bare `pytest.raises`.

`test_append_to_multiple_dropna_false` is marked as failing because it isn't raising the `ValueError` that it should. Because of this, I didn't know what the message should be, and reading through the code didn't help me figure it out. I wrote a draft error message and added a `TODO` (line 3790) and I hope that's the best way to handle it.

In `test_multiple_open_close` there were several assertions that `ClosedFileError` is raised with the same error message, with one in the middle that asserts that an `AttributeError` is raised with a different error message. I moved the one for the `AttributeError` to the end of the list (line 4229) to organize the assertions a little better and make clear that the `msg` parameter is the same for all the `ClosedFileError`s.

I did not add a whatsnew entry since it only changes the tests. Let me know if I should add one (and I am a bit unclear on how, i.e. what version this would end up in).

- [ ] xref #30999
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by moink** [comment]
I can't figure out what went wrong with the Travis CI build. Any hints from anyone would be appreciated.

**Comment by jreback** [comment]
> I can't figure out what went wrong with the Travis CI build. Any hints from anyone would be appreciated.

ignore it, giving us trouble.

**Comment by jreback** [comment]
@moink can you merge master and ping on green (or greenish if the travis build fails like that again).

**Comment by jreback** [comment]
OT: @moink love to split this file up: pandas/tests/io/pytables/test_store.py in a separate PR :->

**Comment by jreback** [comment]
thanks @moink very nice

**Comment by moink** [comment]
> OT: @moink love to split this file up: pandas/tests/io/pytables/test_store.py in a separate PR :->

I agree - I noted that when I made these changes I pushed `test_store.py` over 5000 lines. But I would note that the module it is testing is over 5200 lines and in my opinion also needs to be split up, and then the test module perhaps split up in the same way as the code module.

I am not actually knowledgeable about PyTables and I suspect wouldn't be the best person to do this task. Would you like me to create a new issue?

**Comment by jreback** [comment]
you can create a new issue

but splitting the tests first is much easier just for visibility

**Pull request merged**
