### PR TITLE
BUG: catch almost-null-slice in _convert_slice_indexer

### PR DESCRIPTION
**Pull request by jbrockmendel**
its a contrived corner case, but i wanted to use com.is_null_slice rather than duplicating it in _convert_slice_indexer

### CODE REVIEW

**Comment by WillAyd** [comment]
Reachable from user code?

**Comment by jbrockmendel** [comment]
> Reachable from user code?

Haven't found any examples so far.

**Comment by jreback** [comment]
rebase this just in case

**Comment by jbrockmendel** [comment]
rebased+green

**Comment by jreback** [comment]
thanks!

**Pull request merged**
