### PR TITLE
Update Dockerfile to use conda-forge compilers

### PR DESCRIPTION
**Pull request by xhochy**
Additionally I switched to the miniforge3 image as this bases its installation on conda-forge
and I also have used `mamba` to install the environment as this massively saves time.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by xhochy** [comment]
I'm not really sure where this is used / why this is useful but as it seems that it is broken and people seem to use it somehow, I gave it some love.

**Comment by jreback** [comment]
yeah this is fine. I don't think we are actively using this, assume you have tested it?

**Comment by xhochy** [comment]
> yeah this is fine. I don't think we are actively using this, assume you have tested it?

Yes, tested and works.

**Comment by jreback** [comment]
thanks @xhochy

**Comment by yehoshuadimarsky** [comment]
just saw this, FWIW I use this, to get an isolated environment for working on pandas. Especially if I'm on Windows and want to use the Linux shell, thanks @xhochy for the update

**Pull request merged**
