### PR TITLE
BUG: Make Styler ignore None index names to match to_html behaviour

### PR DESCRIPTION
**Pull request by HHammond**
Addresses https://github.com/pydata/pandas/pull/12090#issuecomment-180695902 by making the `Styler` behaviour match regular `to_html` behaviour. 

This PR is based from #12162.
##### New behaviour

screen shot 2016-02-08 at 10 35 23 am

cc @TomAugspurger

### CODE REVIEW

**Comment by HHammond** [comment]
Actual commit: https://github.com/pydata/pandas/commit/0cb2be1cd94483057b59bc714b0a73a7bfe27b77

**Comment by HHammond** [comment]
Tests are failing on lint with files this PR doesn't touch: https://travis-ci.org/pydata/pandas/jobs/107799224#L1134-L1154

```
$ ci/lint.sh
inside ci/lint.sh
discarding /home/travis/miniconda/bin from PATH
prepending /home/travis/miniconda/envs/pandas/bin to PATH
linting -> pandas/core
linting -> pandas/io
pandas/io/sql.py:24:1: F401 'Appender' imported but unused
pandas/io/tests/test_sql.py:2327:33: E127 continuation line over-indented for visual indent
pandas/io/tests/test_sql.py:2675:33: E127 continuation line over-indented for visual indent
pandas/io/tests/test_sql.py:2741:25: E127 continuation line over-indented for visual indent
linting -> pandas/stats
linting -> pandas/compat
linting -> pandas/sparse
linting -> pandas/tools
linting -> pandas/tseries
linting -> pandas/tests
linting -> pandas/computation
linting -> pandas/util
The command "ci/lint.sh" exited with 1.
```

**Comment by TomAugspurger** [comment]
Joris is fixing that [here](https://github.com/pydata/pandas/pull/12263). I'll restart your travis build once that's merged.

**Comment by TomAugspurger** [comment]
@HHammond can you rebase on master when you get a chance. I *think* it should be a clean rebase.

**Comment by TomAugspurger** [comment]
@jreback Wanted to double check with you before I mess anything up, the merge script will handle this merge cleanly right? There's the two commits, one of which is now in master. Second commit has no conflicts.

**Comment by jreback** [comment]
you can run the merge script then pause when it asked if u want to push upstream
thrn in another window check that everything is good (you can even edit the commit message at this point)

**Comment by TomAugspurger** [comment]
OK, thanks. I'll document that in the wiki.

**Comment by jorisvandenbossche** [comment]
For some reason, the travis builds started to fail after merging this one. But does not seem to be related at first sight ("ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory" and "ERROR: test_get_all_data (pandas.io.tests.test_data.TestYahooOptions)")

**Comment by TomAugspurger** [comment]
Looking into it now, sorry.

**Pull request closed without merging**
