### PR TITLE
Resolved duplicate issue by updating obj object

### LINKED ISSUE #50845: BUG: Duplicate columns get duplicated in DataFrame.align
```
# With duplicate columns
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns=list('abb'))
result = df.drop(columns='a').align(df, join="inner", copy=False)
print(result[0])
#    b  b  b  b
# 0  2  2  3  3
# 1  5  5  6  6

# Without duplicate columns
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns=list('abc'))
result = df.drop(columns='a').align(df, join="inner", copy=False)
print(result[0])
#    b  c
# 0  2  3
# 1  5  6

# With duplicate columns but without the drop(columns=...)
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns=list('abb'))
result = df.align(df, join="inner", copy=False)
print(result[0])
#    a  b  b
# 0  1  2  3
# 1  4  5  6
```

Duplicate columns get duplicated again in alignment. If `self` and `other` have the same columns, then a different code path is taken and the bug does not appear.

### PR DESCRIPTION
**Pull request by asadullahnaeem**
- [x] closes #50845 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
Looks like tests are failing. This fix would need a whatsnew note and a new test as well

**Comment by asadullahnaeem** [comment]
@mroeschke Can you please tell me in which file I have to add the test case.

**Comment by mroeschke** [comment]
pandas/tests/frame/methods/test_align.py

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
