### PR TITLE
DEPR: ‘names’ param in Index.copy

### PR DESCRIPTION
**Pull request by topper-123**
Deprecates this parameter. `names` is not used in `Index.__init__`, so no reason to be used in `Index.copy`.

### CODE REVIEW

**Comment by jreback** [comment]
@jbrockmendel ok here?

**Comment by jbrockmendel** [comment]
No objections

**Comment by jreback** [comment]
thanks @topper-123

**Comment by jbrockmendel** [comment]
@topper-123 shouldnt this be done in RangeIndex.copy too? should `name` be deprecated in MultiIndex.copy?

**Pull request merged**
