### PR TITLE
TST: Fixturize series/test_analytics.py

### PR DESCRIPTION
**Pull request by Anjali2019**
- [ ] This is in reference to issue #22550

### CODE REVIEW

**Comment by gfyoung** [comment]
@Anjali2019 : We recently dropped the AppVeyor build.  Can you rebase?

**Comment by jreback** [comment]
rebase and ping on green

**Comment by jreback** [comment]
closing as stale. if you'd like to continue pls ping.

**Comment by gfyoung** [comment]
I'd like to continue this.

**Comment by gfyoung** [comment]
@jreback : Any comments on this?

**Pull request merged**
