### PR TITLE
BLD: Make sure to copy ZIP files for parser tests

### PR DESCRIPTION
**Pull request by gfyoung**
The ZIP file wasn't listed in `setup.py` from #18091.

Will merge on green.

### CODE REVIEW

**Comment by jreback** [comment]
good point. thanks @gfyoung

**Comment by jreback** [comment]
did you port to the 0.21.x branch? don't do that. we will move everything all at once in the order it was done. otherwise you can get conflicts.

**Comment by gfyoung** [comment]
Oops, my bad.  I thought that was what the backport label meant for us to do.

**Comment by jreback** [comment]
no, it means we *should* do it, but don't do it now.

**Comment by gfyoung** [comment]
Yeah, that's what I meant.  Should I just remove those two commits from the branch then?

**Comment by jreback** [comment]
no its fine

**Pull request merged**
