### PR TITLE
CLN: Avoid unnecessary values_from_object

### PR DESCRIPTION
**Pull request by jbrockmendel**
xref #27165.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
What are the cases where `asarray` and `values_from_object` would give a different result?

**Comment by jbrockmendel** [comment]
> What are the cases where asarray and values_from_object would give a different result?

They should only ever be distinct for EA dtypes, none of which is the case here

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jreback** [comment]
great. yeah this was for compatibility when we removed Series from subclassing ndarray (like 0.13 or so), so would be nice to actually completely remove `values_from_object`

**Comment by jbrockmendel** [comment]
> so would be nice to actually completely remove values_from_object

Yah, I got tripped up the other day by `PeriodIndex.values` and am now tilting at windmills to get rid of a few patterns like this.

**Pull request merged**
