### PR TITLE
Add usage example to DataFrame.to_csv's doc

### PR DESCRIPTION
**Pull request by stefan-niculae**
- [x] add usage example to doc

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks! Looks like you made the PR against the maintenance 0.20.x branch instead of master. You can try updating it to be against master: https://stackoverflow.com/questions/24159036/how-to-modify-a-pull-request-on-github-to-change-target-branch-to-merge-into, though this could cause some conflicts.

**Comment by gfyoung** [comment]
On that note, you should probably add a couple more examples (2 - 3 would be nice) where you pass in different parameters to show what is possible with `to_csv`.

**Comment by jreback** [comment]
can you update?

**Comment by jreback** [comment]
closing as stale, if you want to work on this, pls ping.

**Pull request closed without merging**
