### PR TITLE
CLN: remove incorrect usages of com.AbstractMethodError

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by fortrue23** [comment]
Please cancela pool thanks

**Comment by jbrockmendel** [comment]
Ping

**Comment by jreback** [comment]
can you rebase

**Comment by jreback** [comment]
thanks!

**Pull request merged**
