### PR TITLE
DOC: GH42420 Fix typo in windows C compiler install guide

### LINKED ISSUE #42420: DOC: Inconsistency in Setting Up Dev Env
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/development/contributing_environment.html#installing-a-c-compiler

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

> You will need Build Tools for Visual Studio 2017.
> 
> Warning
> 
> You DO NOT need to install Visual Studio 2019. You only need “Build Tools for Visual Studio 2019”

#### Suggested fix for documentation

Someone should update. This is confusing for me because I'm trying to set one up.

### PR DESCRIPTION
**Pull request by sidalope**
Closes #42420

### CODE REVIEW

**Comment by DavidDeLord** [comment]
closes #42420 (very nice)

**Comment by DavidDeLord** [comment]
also in the future mention the issue with a # in the desc and comment take on it to assign it to yourself

**Comment by AlessandroBisiani** [comment]
Thank you, will do!
Would it make sense to push several updates to documentation at once, with a comment like "- closes #123456, #654321, #214365"? Or might it muddy the waters?

**Comment by mzeitlin11** [comment]
> Would it make sense to push several updates to documentation at once, with a comment like "- closes #123456, #654321, #214365"? Or might it muddy the waters?

Tightly-scoped prs are easiest to review, so if the updates are unrelated, best to keep them to separate prs

**Comment by AlessandroBisiani** [comment]
> > Would it make sense to push several updates to documentation at once, with a comment like "- closes #123456, #654321, #214365"? Or might it muddy the waters?
> 
> Tightly-scoped prs are easiest to review, so if the updates are unrelated, best to keep them to separate prs

Thank you!

**Review by rhshadrach — APPROVED** [review]
lgtm

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @AlessandroBisiani

**Comment by AlessandroBisiani** [comment]
Thank you!

**Pull request merged**
