### PR TITLE
REF: remove unnecessary SparseDataFrame arith methods

### PR DESCRIPTION
**Pull request by jbrockmendel**
this sits on top of #28027.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Closing to clear the queue.  Will reopen after #28027, which is a blocker for this.

**Comment by jbrockmendel** [comment]
Re-opened following #28027.

**Comment by jbrockmendel** [comment]
@TomAugspurger did the Sparse-removal get merged?  If so this is now irrelevant.

**Comment by TomAugspurger** [comment]
Yep, it's in.

**Pull request closed without merging**
