### PR TITLE
DOC: Update flake8 command instructions

### PR DESCRIPTION
**Pull request by gfyoung**
xref <a href="https://github.com/pandas-dev/pandas/pull/16738#issuecomment-315211329">#16738 (comment)</a>

cc @thequackdaddy

### CODE REVIEW

**Comment by gfyoung** [comment]
Ignore the Appveyor failure.  That's it being silly on a PR with `[ci skip]`.

**Comment by gfyoung** [comment]
@jreback : Just curious, do I have similar permissions as I do on Travis for builds?  I tried navigating to one and didn't see any options to restart builds or anything.

**Comment by jreback** [comment]
@gfyoung login using pandas-dev username; it will validate using github and you should be able to interact

**Comment by gfyoung** [comment]
> login using pandas-dev username

If I try clicking the `GitHub` button, it logs in using my `GitHub` account.  However, if I try entering `pandas-dev` into the username-password field, I need a password 😉 - what am I doing wrong here?

**Comment by gfyoung** [comment]
@thequackdaddy : if you have anything you would like to add, let me know.  Otherwise, I'll merge this later today or tomorrow (without the `ci skip`).

**Pull request merged**
