### PR TITLE
DOC: Start 0.24.2.rst

### PR DESCRIPTION
**Pull request by TomAugspurger**
[ci skip]

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thoughts on how we should handle tagging / backporting these? I made a 0.24.2 milestone that will backport, but I don't think we should actually use that until 0.24.1 is released (since we don't want 0.24.2 changes on 0.24.x until 0.24.1 is released).

This documentation change is an exception, since it doesn't affect the output, and we do want this back ported.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
I would simply wait with merging such PRs until the 0.24.1 release is out? (or, even just wait with merging the backport PRs, meeseeksdev can already create them in principle)

**Comment by TomAugspurger** [comment]
Yes, either of those should work.

**Comment by jorisvandenbossche** [comment]
This one can already be merged right? (it's only other PRs targeted to 0.24.2 that need to wait)

**Pull request merged**
