### PR TITLE
REGR: NumPy func warning when dropping nuisance in agg, apply, transform

### LINKED ISSUE #50538: API: GroupBy.agg() numeric_only deprecation with custom function
Case: using `groupby().agg()` with a custom numpy funtion object (`np.mean`) instead of a built-in function string name (`"mean"`).

When using pandas 1.5, we get a future warning about numeric_only going to change, and that you can specify the keyword:

```python
>>> df = pd.DataFrame({"key": ['a', 'b', 'a'], "col1": ['a', 'b', 'c'], "col2": [1, 2, 3]})
>>> df
  key col1  col2
0   a    a     1
1   b    b     2
2   a    c     3
>>> df.groupby("key").agg(np.mean)
FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. 
In a future version, numeric_only will default to False. Either specify numeric_only or select 
only columns which should be valid for the function.
     col2
key      
a     2.0
b     2.0

```

However, if you then try to specify the `numeric_only` keyword as suggested, you get an error:

```
In [10]: df.groupby("key").agg(np.mean, numeric_only=True)
...
File ~/miniconda3/envs/pandas15/lib/python3.10/site-packages/pandas/core/groupby/generic.py:981, in DataFrameGroupBy._aggregate_frame(self, func, *args, **kwargs)
    978 if self.axis == 0:
    979     # test_pass_args_kwargs_duplicate_columns gets here with non-unique columns
    980     for name, data in self.grouper.get_iterator(obj, self.axis):
--> 981         fres = func(data, *args, **kwargs)
    982         result[name] = fres
    983 else:
    984     # we get here in a number of test_multilevel tests

File <__array_function__ internals>:198, in mean(*args, **kwargs)

TypeError: mean() got an unexpected keyword argument 'numeric_only'
```

I know this is because when passing a custom function to `agg`, we pass through any kwargs, so `numeric_only` is also passed to `np.mean`, which of course doesn't know that keyword.

But this seems a bit confusing with the current warning message. So I am wondering if we should do at least either of both:

* If the current behaviour is intentional (`numeric_only` only working for built-in functions specified by string name), then the warning message could be updated to be clearer
* Could we actually support `numeric_only=True` for generic numpy functions / UDFs as well? (was this ever discussed before? Only searched briefly, but didn't directly find something)

cc @rhshadrach @jbrockmendel

### PR DESCRIPTION
**Pull request by rhshadrach**
- [x] closes #50538 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by rhshadrach** [comment]
@jorisvandenbossche @jbrockmendel @mroeschke for any thoughts/feedback

**Comment by jorisvandenbossche** [comment]
In case we keep the current behaviour (no special handling of `numeric_only`, just passing through), then this is at least a clear improvement in the warning messages!

**Comment by rhshadrach** [comment]
@jorisvandenbossche - I think trying to change the pass through behavior is too tricky for a patch (this is targeted to go straight into 1.5.3). I do plan to work on it for future versions (e.g. #50624). If you want this to not close #50538, I can remove it from the OP here, but I do think this is the safest route for 1.5.3.

**Comment by rhshadrach** [comment]
@mroeschke - friendly ping.

**Review by mroeschke — APPROVED** [review]
LGTM. Agreed that improving the exception message here is more reasonable than try to shim `numeric_only` support of any kind

**Comment by mroeschke** [comment]
Thanks @rhshadrach

**Pull request merged**
