### PR TITLE
STYLE: replace unwanted-patterns-strings-to-concatenate with ruff #5… #51504Harsimran

### PR DESCRIPTION
**Pull request by harsimran44**

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
hi - no need to open a new PR, you can use the same one

this is failing pre-commit checks, you need to run them locally https://github.com/pandas-dev/pandas/actions/runs/4233382935/jobs/7354278813

**Comment by MarcoGorelli** [comment]
Closing for now (as I'm fairly certain you didn't follow the steps I outlined in the issue), so others can work on it

Feel free to open a new PR if you follow the steps

**Comment by harsimran44** [comment]
sorry i wasn't able to do the steps.
i have run them locally but its showing error can you help me in solving this
git test

**Comment by MarcoGorelli** [comment]
check https://beta.ruff.rs/docs/rules/explicit-string-concatenation/

**Pull request closed without merging**
