### PR TITLE
CI: Pin Python to 3.7.3

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
I'm currently looking to see what other projects are affected.   Maybe try master from 2 weeks ago?

**Comment by TomAugspurger** [comment]
Oh, we're on python 3.7.4 now. That's most likely it.

**Comment by TomAugspurger** [comment]
Let's get CI passing, and investigate later.

**Comment by TomAugspurger** [comment]
The windows 3.7.4 build passed just fine, so I didn't pin that to 3.7.3.

**Comment by TomAugspurger** [comment]
This may break the pip dep handling in https://github.com/pandas-dev/pandas/blob/master/scripts/generate_pip_deps_from_conda.py#L22. We skip exactly on `python=3` there.

But I'd like to have a single commit that we can revert when the conda 3.7.4 packages are sorted out.

**Comment by jbrockmendel** [comment]
all green, LGTM

**Pull request merged**
