### PR TITLE
TST: fix Nullable xfails

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
user visible?

**Comment by jbrockmendel** [comment]
Whatsnew added + greenish

**Comment by jreback** [comment]
hmm a codecheck issue?

**Comment by jbrockmendel** [comment]
> hmm a codecheck issue?

#44590

**Pull request merged**
