### PR TITLE
CLN: Remove unnecessary rolling subclass

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Does the affect Rolling._constructor?

**Comment by jbrockmendel** [comment]
lint complaint about importing private _Window

**Comment by mroeschke** [comment]
> Does the affect Rolling._constructor?

Thanks for the catch, added the property directly to `Rolling`

**Comment by jbrockmendel** [comment]
thanks @mroeschke

**Pull request merged**
