### PR TITLE
TYP: Fix chainmap typing for mypy 0.740+

### PR DESCRIPTION
**Pull request by xhochy**
This will otherwise raise a failure during a `mypy` update. Also increase type precision of this file to 100%.

- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

cc @simonjayhawkins

### CODE REVIEW

**Comment by jreback** [comment]
cc @simonjayhawkins

**Comment by jreback** [comment]
note we are currently pinned to 0.73 for a number of issues.

**Comment by xhochy** [comment]
> note we are currently pinned to 0.73 for a number of issues.

Yes, I'm aware of them and this a tiny step to get rid of them.

**Comment by jreback** [comment]
> > note we are currently pinned to 0.73 for a number of issues.
> 
> Yes, I'm aware of them and this a tiny step to get rid of them.

great that's what I figured, thanks!

**Comment by topper-123** [comment]
PR looks good to me.

There has been a build-in collections.ChainMap since python 3.3. Is this version different or could we switch over to the builtin version?

**Comment by xhochy** [comment]
> PR looks good to me.
> 
> There has been a build-in collections.ChainMap since python 3.3. Is this version different or could we switch over to the builtin version?

The `typing` one used here is simply a typed alias for it that exists since Python 3.6.

**Review by simonjayhawkins — APPROVED** [review]
@xhochy lgtm. Thanks for the PR.

**Comment by simonjayhawkins** [comment]
> note we are currently pinned to 0.73 for a number of issues.

This will help for 0.73 too...

#30539 pandas\compat\chainmap.py:4: error: Implicit generic "Any". Use "typing.ChainMap" and specify generic parameters

**Comment by jreback** [comment]
thanks @xhochy

**Pull request merged**
