### PR TITLE
DOC: Clarify deprecation of freq for Timestamp

### PR DESCRIPTION
**Pull request by bashtage**
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by bashtage** [comment]
The failure is wrong.  Very strange, but both of these are clearly used.

**Comment by bashtage** [comment]
Should it go in for 1.5.x?

**Comment by jbrockmendel** [comment]
> Should it go in for 1.5.x?

sounds good

**Comment by phofl** [comment]
Needs a rebase and ci is failing

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
