### PR TITLE
DOC: Remove claims of unbiasedness from doc string for std

### PR DESCRIPTION
**Pull request by kawochen**
xref #12230

### CODE REVIEW

**Comment by jreback** [comment]
@TomAugspurger ?

**Comment by TomAugspurger** [comment]
+1, For reference the `np.std` docstring also clarifies that a `ddof=1 still won't be an unbiased.

**Comment by jreback** [comment]
is it worthwhile putting in a link to the wiki on the doc-string?

**Comment by TomAugspurger** [comment]
Do you mean our wiki or wikipedia? I'd say no either way probably.

Are you OK with merging even though that py35 build failed? I saw you open that other issue.

**Comment by kawochen** [comment]
Actually should I just say 'sample standard deviation' in `basics.rst` and `computation.rst`, since the correction can be specified by passing `ddof`?

**Comment by kawochen** [comment]
Well actually the same can be said of variance, so never mind.

**Pull request closed without merging**
