### PR TITLE
DEPR: special-casing dt64/td64 in Series.unique

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

```
dti = pd.date_range('2016-01-01', periods=3).repeat(2)
ser = pd.Series(dti)

>>> ser.unique()
<stdin>:1: FutureWarning: Series.unique behavior with datetime64[ns] dtype is deprecated. In a future version this will return a <class 'pandas.core.arrays.datetimes.DatetimeArray'> instead of a np.ndarray
array(['2016-01-01T00:00:00.000000000', '2016-01-02T00:00:00.000000000',
       '2016-01-03T00:00:00.000000000'], dtype='datetime64[ns]')

```

### CODE REVIEW

**Comment by jreback** [comment]
can you add a release note. IIUC this will *always* warn? how does one avoid this?

**Comment by jbrockmendel** [comment]
> IIUC this will always warn? how does one avoid this?

i guess could do ._values.unique

**Comment by jreback** [comment]
i am confused over when the user would see this, can you update the top of the PR

**Comment by jbrockmendel** [comment]
added example to OP

**Comment by jreback** [comment]
so the problem is this will *always* warn right?

**Comment by jbrockmendel** [comment]
yah,  i guess could do it without deprecation in 2.0

**Comment by jreback** [comment]
@jbrockmendel worth fixing this up?

**Comment by jbrockmendel** [comment]
> worth fixing this up?

i think this is worth doing.  IIRC the trouble was that if we issue a FutureWarning, we don't have a good way to say "do X instead to get the future behavior".  Best idea ATM is to just make the change in 2.0 without a deprecation cycle.

**Comment by jreback** [comment]
yeah sounds good to me

**Comment by jreback** [comment]
@jbrockmendel this for 2.0? if so let's just close it

**Comment by jbrockmendel** [comment]
> this for 2.0? if so let's just close it (and add to the list itself which i think you did)

sure.

**Pull request closed without merging**
