### PR TITLE
DOC Change slack invitation from email to link

### PR DESCRIPTION
**Pull request by noatamir**
Simplified the slack invitation process after discussion with @rhshadrach and @MarcoGorelli.

The current email process is maintenance heavy and until now, we received very little spam. We want to try letting people join themselves and see if spam increases or not.

Local build looked correct.

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
thanks @noatamir !

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
blocking as per

> If there are no further comments I'll start the release in like one hour. Please don't merge anyhing to 2.0.x until further notice. Thanks!

https://github.com/pandas-dev/pandas/issues/46776#issuecomment-1471941616

just in case anyone accidentally ships it

**Comment by phofl** [comment]
I think we can merge now, tag has been pushed

**Review by phofl — APPROVED** [review]

**Review by MarcoGorelli — APPROVED** [review]
yup, thanks @noatamir !

**Pull request merged**
