### PR TITLE
(Closes #25029) Removed extra bracket from cheatsheet code example.

### LINKED ISSUE #25029: The "Create DataFrame with a MultiIndex" code example in the cheatsheet contains an extra bracket
The code example shown for "Create DataFrame with a MultiIndex" in the cheatsheet is incorrect as it contains an extra trailing bracket:

```python
df = pd.DataFrame(
          {"a" : [4 ,5, 6], 
           "b" : [7, 8, 9], 
           "c" : [10, 11, 12]},    index = pd.MultiIndex.from_tuples(
          [('d',1),('d',2),('e',2)],
             names=['n','v'])))
```
It should read:

```python
df = pd.DataFrame(
          {"a" : [4 ,5, 6], 
           "b" : [7, 8, 9], 
           "c" : [10, 11, 12]},    index = pd.MultiIndex.from_tuples(
          [('d',1),('d',2),('e',2)],
             names=['n','v']))
```

### PR DESCRIPTION
**Pull request by M-YD**
Closes #25029

There was an additional bracket present under the "Create DataFrame with a MultiIndex" code example.

I removed this in both the English and Japanese versions of the cheatsheet.

### CODE REVIEW

**Comment by jreback** [comment]
doc/cheatsheet/Pandas_Cheat_Sheet.pptx was deleted?

**Comment by MusTheDataGuy** [comment]
> doc/cheatsheet/Pandas_Cheat_Sheet.pptx was deleted?

No. I changed it, along with Pandas_Cheat_Sheet_JA.pptx and generated the .pdf files off of the back of those, yet the commit keeps showing doc/cheatsheet/Pandas_Cheat_Sheet.pptx as having been deleted, despite it still existing in my repository.

I have checked if the file is tracked, which it is, yet when committing it only shows that three files have been updated, despite four showing as having been modified.

Any ideas what is happening here?

**Comment by MusTheDataGuy** [comment]
> you may need to `git add <file> -f` as this is probably excluded by default in the .gitignore

I have tried this (with a fresh clone of the repository), adding each individual file via your suggested manner, and it is still producing the same output, which states that four files have been changed, yet only lists three files in the summary:

```
4 files changed, 0 insertions(+), 0 deletions(-)                                                                 
rewrite doc/cheatsheet/Pandas_Cheat_Sheet.pdf (73%)                                                              
rewrite doc/cheatsheet/Pandas_Cheat_Sheet_JA.pdf (93%)                                                           
rewrite doc/cheatsheet/Pandas_Cheat_Sheet_JA.pptx (98%)
--
```

What else could cause this?

**Comment by WillAyd** [comment]
@MusTheDataGuy no idea and I don't think gitignore affects those files anyway. Any chance you've been able to figure this out? Maybe another version of git would work?

**Comment by MusTheDataGuy** [comment]
> @MusTheDataGuy no idea and I don't think gitignore affects those files anyway. Any chance you've been able to figure this out? Maybe another version of git would work?

I have the latest version of Git and it still produces the same effect - only three files showing as updated despite detecting four before the commit.

**Comment by jreback** [comment]
after you add, did you force push?

**Comment by MusTheDataGuy** [comment]
> after you add, did you force push?

I just tried this method and still nothing - `doc/cheatsheet/Pandas_Cheat_Sheet.pptx` still shows up as deleted.

**Comment by jreback** [comment]
thanks @MusTheDataGuy

**Pull request merged**
