### PR TITLE
ENH: support Akima 1D interpolation

### PR DESCRIPTION
**Pull request by stahlous**
I went hunting for some low-hanging fruit in the area of missing data and came across #7588. I had to implement it a little differently than krogh, pchip, etc. because there is no convenience function for Akima like there are for the already supported methods.

Once #11445 is merged I can rebase.

### CODE REVIEW

**Comment by jreback** [comment]
ok, can you rebase on master

**Comment by jreback** [comment]
if you can do this on master (and not depend on the other branch), we can take it.

pls reopen if you wish to do so

**Comment by dershow** [comment]
I was just working with akima, and I think that there is an issue with akima is handled.  I posted a report here:  [](https://github.com/pandas-dev/pandas/issues/21276)

**Comment by dershow** [comment]
I was just working with akima and I think that there is an issue.  I've posted a bug report here:   [https://github.com/pandas-dev/pandas/issues/21276](https://github.com/pandas-dev/pandas/issues/21276)

**Pull request closed without merging**
