### PR TITLE
fix: type error when exporting file as bytes

### PR DESCRIPTION
**Pull request by zhaxnb**
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
image
[official doc url](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#writing-excel-files)
"Writing Excel files to memory" part

### CODE REVIEW

**Comment by rhshadrach** [comment]
Thanks for the PR! It seems to me that `WriteExcelBuffer` was should have `io.BytesIO` as a subtype, is this not the case?

**Comment by zhaxnb** [comment]
image
No, while it seems to be a subtype, it doesn't actually work

**Comment by rhshadrach** [comment]
> No, while it seems to be a subtype, it doesn't actually work.

I'm against adding unnecessary type-hints to make IDEs happy. If it is a subtype, then the IDE should be fine with it and this is an issue with the IDE, not pandas.

**Comment by zhaxnb** [comment]
Okay, I'll double-check if it's an IDE problem.

**Pull request closed without merging**
