### PR TITLE
Revert "DEPR: Deprecate returning a DataFrame in SeriesApply.apply_standard

### LINKED ISSUE #55134: ENH: Don't remove the ability to expand a Series to a DataFrame by applying a function that returns Series
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Being able to expand a Series by applying a function to its cells is very convenient, but in 2.1 in produces a 
`FutureWarning: Returning a DataFrame from Series.apply when the supplied function returns a Series is deprecated and will be removed in a future version`

### Feature Description

Right now I can do this:

```
def expand_cell(s: Union[str, np.ndarray, list]) -> pd.Series:

    result = process_cell(s)
    data = {
        'foo': result.foo,
        'bar': result.bar,
        ...
    }
    return pd.Series(data)
        
df = pd.concat([
    df,
    df[column].apply(expand_cell),
], axis=1)
```

I tried to get rid of the FutureWarning, but changing the `expand_cell` return value to be `pd.Series(data).to_frame()` didn't help, because in such case the result of `apply()` is a Series with each cell containing a DataFrame.

I might be missing something, but as of right now the only working solution which doesn't raise a Warning seems be the replacement of the concise `df[column].apply(expand_cell)` with a more ugly `pd.DataFrame([expand_cell(c) for c in df[column]])`. 

### Alternative Solutions

Keep everything as is, I guess? :)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by phofl**
Reasons for reverting:

- This was done for performance reasons, but this kills the use case to unpack nested data (lists for example)
- The deprecation is poorly done (axis 1 does not emit a warning)
- There is no documentation what users should do, this is necessary if we deprecate something for performance reasons

#52116

closes #55134

### CODE REVIEW

**Comment by mroeschke** [comment]
I'm okay with reverting this for now. Could you link any related open user issues (if available)?

Also might be worth adding a unit test for unpacking nested data with apply.

cc @topper-123

**Comment by phofl** [comment]
Added a test and linked the issue in the top post

**Review by lithomas1 — APPROVED** [review]

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @phofl. This deprecation is probably highly relevant in the PDEP 13 discussion

**Comment by phofl** [comment]
yep agree

**Pull request merged**
