### PR TITLE
TST: Remove tests for hdf files created with pandas <= v0.11

### PR DESCRIPTION
**Pull request by topper-123**
- [ x] closes #17375
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x ] whatsnew entry

Tests for old compatability removed because this issue is sufficiently old now, that people should be expected to have solved this by now.

@jreback , the methods ``test_legacy_table_read`` and ``test_legacy_table_write`` don't say if they concern pandas <=0.11 or it's newer compatability issues. It it ok to remove those?

See also discussion in #17375.

### CODE REVIEW

**Comment by topper-123** [comment]
I'm having some strange issue with changes in the the doc directory not being registered by git.

I'm going do everything over again in a new pull request.

**Comment by jorisvandenbossche** [comment]
@topper-123 even if you clean-up your branch locally, you can still push to the same branch on your fork to update this PR

**Comment by topper-123** [comment]
I made the changes to ``v0.21.txt`` in the Github online editor, but that got me those red crosses. 

I really don't know what's causing this and i'm not interested in investigating. I would rather just start over (unless you got a quick tip I could try out)

**Comment by topper-123** [comment]
This has been replaced by #17404. Closing.

**Pull request closed without merging**
