### PR TITLE
REF: de-duplicate nested-dict handling in DataFrame construction

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

This was the motivation for #41707.  This will introduce some overhead, but will also prevent the behaviors from getting out of sync again.

### CODE REVIEW

**Comment by jreback** [comment]
oh i like this!

**Comment by jorisvandenbossche** [comment]
This might have caused a big slowdown in one of the benchmarks: https://pandas.pydata.org/speed/pandas/#frame_ctor.FromDicts.time_nested_dict_int64?python=3.8&Cython=0.29.21

@jbrockmendel can you verify this?

**Comment by jbrockmendel** [comment]
That looks plausible; noted in the OP we'd take a perf hit in these cases

**Comment by jorisvandenbossche** [comment]
Yes, but "some overhead" turns out to be a 6x slowdown. 
So then having the cython implementation (and the added effort of ensuring it is kept in sync) might be worth it.

**Comment by jbrockmendel** [comment]
do you have anything in particular in mind?  could revert until after the release

**Comment by jbrockmendel** [comment]
> I didn't follow the original context, but IIUC, this PR didn't "fix" anything, correct? (like a bug) But it did remove a faster cython implementation to reduce maintenance cost in the idea the added overhead would only be small?

This context is that this follows #41707, which did fix a bug in the Series constructor that didn't affect DataFrame construction because they had separate implementations.

**Comment by jorisvandenbossche** [comment]
I opened https://github.com/pandas-dev/pandas/issues/42248 to keep track of this regression.

**Pull request merged**
