### PR TITLE
DOC: Update meeseeksmachine reference

### PR DESCRIPTION
**Pull request by mroeschke**

### CODE REVIEW

**Comment by lithomas1** [comment]
Wait, ... they changed it? 😱 

I remember using ``@meeseeksdev`` still worked, at least a couple weeks back.

**Comment by mroeschke** [comment]
Idk I tried using it in https://github.com/pandas-dev/pandas/pull/57078 and wasn't getting a response from the old command. Also probably best to change this since meeseeksdev points to a user profile now

**Comment by datapythonista** [comment]
@MeeseeksDev hello

**Comment by datapythonista** [comment]
I have the feeling that using `@meeseeksdev` is like when we use `/preview`, not really tagging that user, but just the keyword for the bot. I still see in all the docs that the right command is `@meeseeksdev`, and from the above test seems like it's still working. Happy to get this merged if I'm missing something, but in general I don't think this is needed.

**Comment by mroeschke** [comment]
Ah OK maybe I was impatient with the response time of the bot so I'll close this PR

**Pull request closed without merging**
