### PR TITLE
BUG-24915 fix unhashble Series.name in df aggregation

### LINKED ISSUE #24915: Cannot do agg if dataframe has column "name"
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd

df = pd.DataFrame({"a": range(10)})
df.agg({"a": 'mean'}) # this line runs good

df["name"] = range(10)
df.agg({"a": 'mean'}) # now we have RuntimeError: maximum recursion depth exceeded
```
#### Problem description

If a dataframe has a column which is called "name", doing aggregation on the dataframe will cause RuntimeError.

##### But if the column is not called "name" but with some variant like "name0", "name_", it runs good.

```python
import pandas as pd

df = pd.DataFrame({"a": range(10)})
df.agg({"a": 'mean'}) # this line runs good

df["name_"] = range(10)  # not "name"
df.agg({"a": 'mean'}) # this line runs good as well
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.15.final.0
python-bits: 64
OS: Darwin
OS-release: 18.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.16.0
scipy: 1.2.0
pyarrow: 0.11.1
xarray: None
IPython: 5.8.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: 0.2.0
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by lofoyet**
- [x] closes #24915
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Before creating a pd.Series and pass {name} as argument, check if {name} is hashable. If not use default None.

### CODE REVIEW

**Comment by lofoyet** [comment]
@yaoquanye @daisysu0310

**Comment by lofoyet** [comment]
1. not sure about what tests to add

**Comment by lofoyet** [comment]
@youhealthy and I are the same person

**Review by mroeschke — CHANGES_REQUESTED** [review]
Needs:

* Whatsnew entry for 0.24.1
* Test: Add a test based on the example in the original issue. Construct the DataFrame/Series that replicates the issue and the expected DataFrame/Series

**Review by jreback — CHANGES_REQUESTED** [review]
this needs a test. I am also not sure this is actually the correct fix. constructio of a Series from scalars with an invalid name with raise now. IOW this should be raising *already*, so not sure this is a good remedy.

`
```
In [1]: Series([1,2],name=[1,2])                                                                                                                                                                                                                                        
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-360525e04c11> in <module>
----> 1 Series([1,2],name=[1,2])

~/pandas/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    266         generic.NDFrame.__init__(self, data, fastpath=True)
    267 
--> 268         self.name = name
    269         self._set_axis(0, index, fastpath=True)
    270 

~/pandas/pandas/core/generic.py in __setattr__(self, name, value)
   5077             object.__setattr__(self, name, value)
   5078         elif name in self._metadata:
-> 5079             object.__setattr__(self, name, value)
   5080         else:
   5081             try:

~/pandas/pandas/core/series.py in name(self, value)
    400     def name(self, value):
    401         if value is not None and not is_hashable(value):
--> 402             raise TypeError('Series.name must be a hashable type')
    403         object.__setattr__(self, '_name', value)
    404 

TypeError: Series.name must be a hashable type
```

**Comment by lofoyet** [comment]
@jreback I agree with you. You can refer to #24915 for the problem.

There are 2 ways that I have in mind to fix this:
1. This PR.
2. Make change to how __getattr__ works.

For 2. What I looked at is

```python
#pandas.core.generic.py
if (name in self._internal_names_set or name in self._metadata or
    name in self._accessors):
        return object.__getattribute__(self, name)
else:
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
        return self[name]
    return object.__getattribute__(self, name)
```
`getattr(self, "name") will go to else clause, and if "name" is a column, it will return in if clause. But df.name is really an attribute rather not a column name. It should skip that "if" in "else" and goes to object.__getattribute__().

How do you propose to change? @jreback

**Comment by lofoyet** [comment]
@jreback any idea?

**Comment by jreback** [comment]
@lofoyet first thing you need here is a test. Then step thru it until you get to the source of the error, see if you patch fixes.

I would rather shy away from changing the way getattr works. Also I am not sure your change is the right way.

**Comment by WillAyd** [comment]
Closing as stale. @lofoyet ping if you'd like to continue though as mentioned above this needs a test first and foremost

**Pull request closed without merging**
