### PR TITLE
TST/DEV: remove geopandas downstream test + remove from environment.yml

### PR DESCRIPTION
**Pull request by StefanieSenger**
See https://github.com/pandas-dev/pandas/pull/49994 for context

- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit)

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks @StefanieSenger - can you run the pre-commit checks too please? check the contributing guide for how

**Comment by StefanieSenger** [comment]
Hey @MarcoGorelli, thanks for coming back to me. I did run the pre-commit tests on `environment.yml ` and `pandas/tests/test_downstream.py`, but but unfortunately didn't notice that one of the tests didn't pass:
```
Generate pip dependency from conda......................................................................Failed
- hook id: pip-to-conda
- files were modified by this hook
```
This explains, why geopandas is still listed in requirements-dev.txt and didn't autogenerate from the .yml file, I suppose.
I think I should now investigate why that happened, but I'm a bit lost here, I need to admit. Any advice?

**Comment by MarcoGorelli** [comment]
you just need to stage and commit again:
```
git add -u
git commit -m 'your commit message goes here'
```

**Review by MarcoGorelli — APPROVED** [review]
looks good, thanks @StefanieSenger

**Comment by jorisvandenbossche** [comment]
@StefanieSenger I updated the title of the PR to something more descriptive (the title is used for the resulting commit message)

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by StefanieSenger** [comment]
@MarcoGorelli @jorisvandenbossche Awesome, thanks you much for your support! :)

**Pull request merged**
