### PR TITLE
Fix matplotlib converter registering warning

### LINKED ISSUE #26760: Fix implicitly registered converter warning
This shouldn't warn, since it's a Series.plot.

The warning should only show up for `Axes.plot(datetimelike, ndarray)`.

```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]:    ts = pd.Series(np.random.randn(1000),
   ...:                   index=pd.date_range('1/1/2000', periods=1000))
   ...:    ts = ts.cumsum()

In [4]: ts.plot()
/Users/taugspurger/sandbox/pandas/pandas/plotting/_matplotlib/converter.py:96: FutureWarning: Using an implicitly registered datetime converter for a matplotlib plotting method. The converter was registered by pandas on import. Future versions of pandas will require you to explicitly register
matplotlib converters.
```

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes #26760

Tests were being skipped, because the module name changed in https://github.com/pandas-dev/pandas/pull/18307/files.

### CODE REVIEW

**Comment by jreback** [comment]
is there any way to actually test this? can run a subprocess tests and check for warnings in the output?

**Comment by jorisvandenbossche** [comment]
> is there any way to actually test this?

@TomAugspurger actually proposed a way to test this in https://github.com/pandas-dev/pandas/pull/24964, but you were against adding it (the test was called separately from `ci/run_tests.sh`. Although that indeed adds complexity to the CI testing code, this is only temporary and in a place (run_tests.sh) that does not need to be touched often. So personally, I would just add it like in the original version of that PR.

**Comment by jreback** [comment]
> > is there any way to actually test this?
> 
> @TomAugspurger actually proposed a way to test this in #24964, but you were against adding it (the test was called separately from `ci/run_tests.sh`. Although that indeed adds complexity to the CI testing code, this is only temporary and in a place (run_tests.sh) that does not need to be touched often. So personally, I would just add it like in the original version of that PR.

re-looking that's a good idea actually. @TomAugspurger can you re-add something like that?

**Comment by TomAugspurger** [comment]
Gonna try subprocess first, and then that if subprocess fails.

**Comment by TomAugspurger** [comment]
Subprocess seems to work pretty well here.

**Comment by jorisvandenbossche** [comment]
cc @datapythonista

**Comment by jorisvandenbossche** [comment]
The failures seem related (as they are about plotting), but not sure what change in this PR caused those

**Comment by TomAugspurger** [comment]
For posterity, my current hypothesis is that

1. `import pandas` imports `matplotlib.pyplot` by default again
2. This likely happens before we every call `td.skip_if_no_mpl()`
3. Which means we've imported `matplotlib.pyplot` before calling `matplotlib.use()`, which is bad.

https://github.com/pandas-dev/pandas/pull/26770/commits/d03a41de1f04b7063da8175d532c3881b8590caa may have a warning in the log.

Not sure how to fix yet. Ideally, `import pandas` would only import `matplotlib` (not `matplotlib.pyplot)`. Not sure if that's feasible...

**Comment by jorisvandenbossche** [comment]
> import pandas imports matplotlib.pyplot by default again

But this is something we can fix? I suppose this was introduced in the PR with the matplotlib split

**Comment by TomAugspurger** [comment]
Yep. https://github.com/pandas-dev/pandas/pull/26770/commits/28aaecfd357a6ad62166e67fcf91b90e2645c1b8 got them all I think.

**Comment by TomAugspurger** [comment]
The warning was being emitted by matplotlib: https://travis-ci.org/pandas-dev/pandas/jobs/546786281#L2428 (that's before https://github.com/pandas-dev/pandas/commit/28aaecfd357a6ad62166e67fcf91b90e2645c1b8)

**Comment by TomAugspurger** [comment]
OK, all green if you have another chance to look @jorisvandenbossche.

Basically, we can / need to have `import pandas` do `import matplotlib`. But it can't do `import matplotlib.pyplot`. Those need to be delayed. I've added that to our code checks.

And again, this is all going away in a release or so.

In my debugging, I've compat code like https://github.com/pandas-dev/pandas/pull/26770/files#diff-53e8fd9a1f847dd40d9aba697909409fL524, which no longer seem to be tested, and https://github.com/pandas-dev/pandas/pull/26770/files#diff-53e8fd9a1f847dd40d9aba697909409fL1096, which isn't needed for any recent matplotlib version.

**Comment by jreback** [comment]
thanks @TomAugspurger 

merged, so @datapythonista can rebase the backend PR

**Pull request merged**
