### PR TITLE
TST: split up tests/plotting/test_frame.py into subdir & modules #34769

### LINKED ISSUE #34769: TST: split up tests/plotting/test_frame.py into subdir & modules
we should split up this test file into a separate subdir and multiple test modules for better groking. first PR should be a straight move, then can split (or all in one is ok)

### PR DESCRIPTION
**Pull request by Mikhaylov-yv**
- [ ] closes #34769
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I moved the file to a new directory.
What is the best structure for this folder?

### CODE REVIEW

**Comment by jreback** [comment]
you could start with groupby, subplots, colors 

just look for a grouping of tests that are common and move them. i would recommend merge master on this and can merge, then do followup PRs to extract.

**Comment by Mikhaylov-yv** [comment]
@jreback OK thanks.

I think I figured out what to do with the tests.
But I didn't understand the merge conflict. The merge goes fine locally.

**Comment by jreback** [comment]
make sure to `git pull upstream/master`

**Comment by Mikhaylov-yv** [comment]
Am I doing the right thing?

**Comment by jreback** [comment]
yes this looks fine. can you show the before / after test runs for this dir (make sure test counts don't change).

ping when ready. btw no need to do anymore in this PR, can followup with others. ping on green.

**Comment by Mikhaylov-yv** [comment]
Oh no. I did something wrong.
excuse me

**Pull request closed without merging**
