### PR TITLE
DEPR: create_block_manager_from_blocks

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by mroeschke** [comment]
Are you aware of any libraries using this?

**Comment by jbrockmendel** [comment]
> Are you aware of any libraries using this?

@phofl says dask is using it

**Comment by phofl** [comment]
Yep, I’d prefer not to deprecate

**Comment by jbrockmendel** [comment]
im pretty set on this; we need to ween dask and anyone else off of internals in general if we want to be able to change anything.  in particular i want to get the axes out of the Managers

**Comment by phofl** [comment]
We are serializing/de-serializing the blocks. I am open to do this differently though, but not sure if there is an efficient way of doing this

**Comment by jbrockmendel** [comment]
> We are serializing/de-serializing the blocks. I am open to do this differently though, but not sure if there is an efficient way of doing this


Create a DataFrame for each block and concat them?

**Comment by phofl** [comment]
Can we offer a private api for this maybe? List of blocks and axes?

**Comment by jbrockmendel** [comment]
> Can we offer a private api for this maybe? List of blocks and axes?

After this PR dask can get continue to import the function from internals.api which is explicitly pseudo-public for pyarrow/dask.  This PR is just getting the function to the more-correct place.

Long-term, no.  dask and anyone else need to stop using Blocks/Managers directly.

**Review by jreback — APPROVED** [review]
lgtm

**Pull request merged**
