### PR TITLE
DEPS: replace pyperclip with pyclip #39834

### LINKED ISSUE #39834: DEPS: change clipboard backend to pyclip
Currently, we are using a vendered version of [pyperclip](https://github.com/asweigart/pyperclip). This project was dead for a couple of years. And there were some updates in 2020. But, it's not under active development right now. 

Recently I found this project [pyclip](https://github.com/spyoungtech/pyclip). It looks well maintained and has identical functionalities as pyperclip does. We should investigate if we could replace the vendered pyperclip with pyclip.

### PR DESCRIPTION
**Pull request by fangchenli**
- [x] closes #39834

### CODE REVIEW

**Comment by jreback** [comment]
wouldn't we need to include this as a dependency?

**Comment by fangchenli** [comment]
While testing on macOS 10.14, 

```bash
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/runner/miniconda3/envs/pandas-dev/include -arch x86_64 -I/Users/runner/miniconda3/envs/pandas-dev/include -arch x86_64 -I/Users/runner/miniconda3/envs/pandas-dev/include/python3.7m -c src/pasteboard/pasteboard.m -o /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-015vu04t/pasteboard_2bcc45bc11da408ead13e044a5aa8313/build/temp.macosx-10.9-x86_64-3.7/src/pasteboard/pasteboard.o -Wall -Wextra -Wpedantic -Werror
  src/pasteboard/pasteboard.m:267:33: error: 'NSPasteboardTypeFileURL' is only available on macOS 10.13 or newer [-Werror,-Wunguarded-availability-new]
      NSArray *supportedTypes = @[NSPasteboardTypeFileURL];
                                  ^~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:38:38: note: 'NSPasteboardTypeFileURL' has been marked as being introduced in macOS 10.13 here, but the deployment target is macOS 10.9.0
  APPKIT_EXTERN NSPasteboardType const NSPasteboardTypeFileURL                    NS_AVAILABLE_MAC(10_13); // Equivalent to kUTTypeFileURL
                                       ^
  src/pasteboard/pasteboard.m:267:33: note: enclose 'NSPasteboardTypeFileURL' in an @available check to silence this warning
      NSArray *supportedTypes = @[NSPasteboardTypeFileURL];
```

I wonder why it says `the deployment target is macOS 10.9.0`.

Change the Azure vmImage to 10.15 fixed this.

**Review by jreback — CHANGES_REQUESTED** [review]
can you update the install.rst instructions for this
can you add a note in the whatsnew (put in the deps section, use a ..warning). as this is basically a breaking change.

so we may want to consider leaving the original impl here (though i find that annoying).

thoughts @pandas-dev/pandas-core

**Comment by Dr-Irv** [comment]
> thoughts @pandas-dev/pandas-core

Here's my 2 cents, and I will leave it to the more experienced members of the core team to weigh in.

The proposal is that we depend on `pyclip` instead of `pyperclip`.  Prior to today, I had never heard of either project, so my analysis is based on looking at their GitHub repos. 

`pyperclip` is a project that has been around for almost 10 years.  There has not been much activity lately in terms of commits , and it has 71 open issues. But the latest PR was merged on 2/20/21.  There have been multiple contributors over the 10 years.  As an outsider, I would say that it is probably a pretty stable piece of code. 

`pyperclip` is a much younger project, started in January of 2021.  There is one contributor. So it is most likely not as "battle tested" as `pyperclip`.  I'd be a little concerned about having pandas depend on such a young project.

So unless `pyclip` is fixing an issue that affects pandas users that is a problem with using `pyperclip`, I'd vote for not making this change.

But others may feel differently, because `pyclip` is the more active project.

**Comment by rhshadrach** [comment]
I'll only add that it appears pyperclip appears to require less on our side, which I love. But I agree with @Dr-Irv assessment. I feel  wary adding a 2 month old project, even as an optional dependency. I also wonder how used this feature is (SO gives 161 results for `pandas clipboard`)

**Comment by bashtage** [comment]
I think this is a nearly interactive only function, so I'm not sure it will show up much in github. I have used it a few times in the past month in quick experiments.

**Comment by bashtage** [comment]
@Dr-Irv you have an unfortunate type in the fourth paragraph.

**Comment by jreback** [comment]
thanks @fangchenli let's reconsider this after the project is a bit more mature.

**Pull request closed without merging**
