### PR TITLE
CI: Bump timeout to 180 minutes

### PR DESCRIPTION
**Pull request by mroeschke**
Noticing a few timeouts on builds lately.

Investigating whether we need to bump the timeout limit or some tests are stalling.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
The test suite has definitely gotten slower in the last month or two.  Used to be ~15 minutes locally, now closer to twice that.

**Comment by jbrockmendel** [comment]
FYI just ran `pytest pandas/tests/extension/test_arrow.py --skip-slow --skip-db` after upgrading to newest pyarrow and a) took 10:15 and b) 4441 xfails

**Comment by mroeschke** [comment]
Failures are related to https://github.com/pandas-dev/pandas/issues/48432. Merging as this will help alleviate the timeouts in the meantime

**Comment by phofl** [comment]
@mroeschke I think we should backport, do you agree?

**Comment by mroeschke** [comment]
Sure, this should be a low risk change to backport.

**Comment by phofl** [comment]
@meeseeksdev backport 1.5.x

**Comment by phofl** [comment]
Yep agreed. Want to avoid dealing with the timeouts for the next 5-6 months

**Pull request merged**
