### PR TITLE
DOC: improve binary operator docs (fixes #10093)

### LINKED ISSUE #10093: DOC: clarify docstring of DataFrame.sub et al
http://stackoverflow.com/questions/30144170/what-does-pandas-sub-operator-do/30144239#30144238

The docstring of `DataFrame.sub` states `Binary operator sub`, so if you don't directly see the link with "subtraction", this is not very clear

### PR DESCRIPTION
**Pull request by mortada**
fixes #10093

@jorisvandenbossche this covers `Series`, `DataFrame` and `Panel`, please take a look

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
The resulting text would now be: `Binary operator subtraction.` 

I think that maybe also the 'binary operator' part can be confusing for people. I don't know if this terminology is that familiar for most users? 
Thinking about an alternative, I came up with ```Subtraction of series and other (binary operator ``sub``). ```

**Comment by mortada** [comment]
actually the current implementation is such that the doc would be: `Binary operator sub (subtraction)`

**Comment by jorisvandenbossche** [comment]
Ah, yes, I see the `desc` line! 
But still, my reservation about 'binary operator' stays the same

**Comment by mortada** [comment]
hmm... yeah the wording for this is kind of tricky

**Comment by mortada** [comment]
if we go with `Subtraction of series and other (binary operator sub)` maybe it should be `Subtraction of other from series` instead to indicate the order of operation, and so `rsub` would be `Subtraction of series from other`. But I'm not sure if this is actually more clear.

**Comment by jorisvandenbossche** [comment]
Proposal:

```
Subtraction of series and other, element-wise (binary operator `sub`).

Equivalent to ``series - other``, but with support to substitute a fill_value for missing data in
one of the inputs.
```

But agree that the "series and other" is maybe better as "other from series", but that will depend a bit from operator to operator how to best specify it.

Can you maybe also add a 'see also' section each time to the reversed/non-reversed version (add -> radd, radd -> add, ...)

**Comment by mortada** [comment]
So I ended up restructuring the code quite a bit in order to pack more information into the docstring, also added a unit test for it. Please take a look.

Basically the docstrings look like this now:
```
Signature: pd.DataFrame.sub(self, other, axis='columns', level=None, fill_value=None)
Docstring:
Subtraction of dataframe and other, element-wise (binary operator `-`).

Equivalent to ``dataframe - other``, but with support to substitute a fill_value for
missing data in one of the inputs.

Parameters
----------
other : Series, DataFrame, or constant
axis : {0, 1, 'index', 'columns'}
    For Series input, axis to match Series index on
fill_value : None or float value, default None
    Fill missing (NaN) values with this value. If both DataFrame locations are
    missing, the result will be missing
level : int or name
    Broadcast across a level, matching Index values on the
    passed MultiIndex level

Notes
-----
Mismatched indices will be unioned together

Returns
-------
result : DataFrame

See also
--------
DataFrame.rsub
```

**Comment by jorisvandenbossche** [comment]
Nice!  Thanks a lot.

**Comment by mortada** [comment]
Noticed a small problem, instead of:
```element-wise (binary operator `-`)```
we should have:
```element-wise (binary operator `sub`)```

it's fixed now

**Comment by jorisvandenbossche** [comment]
Travis is failing, but seems to be related to another issue

**Comment by jreback** [comment]
yep will be fixed by #10152

**Comment by jorisvandenbossche** [comment]
OK, merging then. @mortada Thanks a lot!

**Pull request merged**
