### PR TITLE
CLN: remove is_period_arraylike, is_datetime_arraylike

### PR DESCRIPTION
**Pull request by jbrockmendel**
There are better alternatives

### CODE REVIEW

**Comment by jreback** [comment]
needs a rebase. are these public? if so need to deprecate (unfortunately) and provide a shim.

**Comment by jbrockmendel** [comment]
> are these public?

no

**Comment by jbrockmendel** [comment]
@WillAyd any idea why mypy would be complaining here (and i think on many other PRs) but not locally?

**Comment by WillAyd** [comment]
Can you merge master? @simonjayhawkins had a recent fix for mypy

**Comment by simonjayhawkins** [comment]
@jbrockmendel can you merge master

**Comment by jbrockmendel** [comment]
rebased+green

**Review by simonjayhawkins — APPROVED** [review]
Thanks @jbrockmendel merge away.

**Pull request merged**
