### PR TITLE
DOC: clarfiy sum of empty Series case in 0.21.0 whatsnew

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Attempt to better highlight the change of empty Series, instead of mainly focussing now on all-NaN (given the recent issues that were raised were often about the empty case)

### CODE REVIEW

**Comment by jreback** [comment]
this is ok, but are you intending to actually update the current docs?

**Comment by jorisvandenbossche** [comment]
> this is ok, but are you intending to actually update the current docs?

Well, that would also be nice. But at least backporting it to 0.21.1 will make sure it is in the 0.21 docs by the time that is released, and there will still be upgrading lots of people to 0.21 by that time.

@TomAugspurger to update the current docs, I don't think it is easy to make a new build with those changes? (as then the commit tag is not correctly 0.21.0 etc). Maybe I can just edit the source html a bit if I really want it there?

**Comment by TomAugspurger** [comment]
Uhm, I can just hardcode `__version__` in `pandas/__init__.py` before building.

@jorisvandenbossche could you also expand the "matplotlib no longer imported"? Last item here: http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#other-api-changes

Something like

```
Pandas no registers our datetime, datetime64, and Period converters with
matplotlib on import. Matplotlib plot methods (``plt.plot``, ``ax.plot``, ...),
will not nicely format the x-axis for ``DatetiemIndex`` or ``PeriodIndex``
values. You must explicitly register these methods:

.. ipython:: python

   from pandas.tseries import converter
   converter.register()

   fig, ax = plt.subplots()
   plt.plot(pd.date_range('2017', periods=12), range(12))

Pandas built-in ``Series.plot`` and ``DataFrame.plot`` *will* register these
on first-use (:issue:17710).
```

**Comment by TomAugspurger** [comment]
Actually, I'll just push that to this branch.

**Pull request merged**
