### PR TITLE
TST: Don't mark all plotting tests as slow

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Ideally we should be more targeted regarding a slow test

### CODE REVIEW

**Comment by jreback** [comment]
hmm windows builds taking a long time (but succeeding)

**Comment by mroeschke** [comment]
> hmm windows builds taking a long time (but succeeding)

Added some `@pytest.mark.slow` to some of the plotting tests (ones in the top 30 slowest)

**Comment by jreback** [comment]
hmm this are you sure we should not mark these slow? seems to be increasing the ci times

**Comment by mroeschke** [comment]
> hmm this are you sure we should not mark these slow? seems to be increasing the ci times

That would mean _no_ plotting tests would run on MacOS/Windows builds since we're running `not slow`. I was able to discover a PY3.10 entrypoints bug since we weren't running these tests before

IMO testing platform coverage should be more important than CI times since a lot of pandas development is pretty async

**Comment by jreback** [comment]
can we run a slow build on those platforms?

**Comment by mroeschke** [comment]
> can we run a slow build on those platforms?

I can follow up by removing `not slow` from these builds

**Comment by jreback** [comment]
can you rebase

**Comment by jreback** [comment]
can we reduce the matrix a bit to lower the number of total jobs?

**Comment by mroeschke** [comment]
Hmm the current jobs were deemed "important" at some point. If we need to prune jobs, my vote would be to remove the 2 locale jobs first.

* Runs a lot of redundant tests
* Relevant tests cannot be targeted
* Encourage users to locally tests, patches accepted, but not practical to test (every locale) in our CI. Similar to our 32 bit testing eventually: https://github.com/pandas-dev/pandas/issues/44453

**Comment by mroeschke** [comment]
We could also remove testing pyarrow 6. I think that would reduce 3 builds.

**Comment by jreback** [comment]
for pyarrow oldest and newest are fine (are we testing more)?

**Comment by mroeschke** [comment]
We're testing 1.0.1 (min), 5, 6, 7 right now. (we're not testing 2 or 3 since we've observed read_csv timeouts with those versions)

IIRC @jorisvandenbossche aimed to test more pyarrow versions since some pandas-pyarrow functionality is only available in certain versions.

**Comment by jreback** [comment]
ok then dropping 6 is fine as 5,7 are testing

**Pull request merged**
