### PR TITLE
CI/TST: Mark test_basic_series_frame_alignment for python engine as flaky

### PR DESCRIPTION
**Pull request by mroeschke**
Seems to also be flaky with the python engine: https://github.com/pandas-dev/pandas/actions/runs/4109864025/jobs/7092127908

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Bummer.  Does pytest have a marker to mark something as flaky rather than non-strict xfail?  Im thinking something like "if it fails re-run up to N times and pass if it passes any time"

**Comment by phofl** [comment]
Looks like there is a plugin 

https://github.com/pytest-dev/pytest-rerunfailures


No idea if this is maintained well enough though

**Comment by mroeschke** [comment]
I can explore that plugin in a follow up PR. I think we have a few tests that are flaky like this

**Comment by phofl** [comment]
Sounds good! Thx

**Review by phofl — APPROVED** [review]

**Pull request merged**
