### PR TITLE
Added E741 to flake8 config

### PR DESCRIPTION
**Pull request by TomAugspurger**
Makes this easier to run locally.

Do we want to ignore bare exception (E722) too? Or is the hope that we'll fix all those eventually?

### CODE REVIEW

**Comment by jreback** [comment]
no the excepts should be fixed (there is an issue)
the 1 letter variables are prob ok

**Comment by jreback** [comment]
thanks!

**Comment by alimcmaster1** [comment]
Hey - out of interest how come we ignore this error (E741) I don't see any instances of it in the codebase and thinking we could now enforce it?

**Comment by TomAugspurger** [comment]
Not sure. I may have copied it from another config (this came from updates
to flake8's rules).

**Pull request merged**
