### PR TITLE
BUG: workaround PyTables 319, but not setting expected rows (GH8265, GH9676)

### LINKED ISSUE #8265: HDF5 index corruption
I generated a multindexed DataFrame and wrote it to hdf5 using to_hdf.  It uses zlib level 5 compression.  The file was written all at once.  The file is located here: https://www.dropbox.com/s/122q55g5ubcf4fl/indexIssue.h5?dl=0

The below methods should be identical but the former select with a where clause has 2892 records but getting all values and subselecting on the path returns 2972 (values are missing for path 6 between 3-5-2015 20:00 to 3-6-2015 9:00).  I tried using reindex on the able but that didn't fix anything.  I don't really know what's going on.

```
store   =   HDFStore(path_to_file, mode='r')

p1      =   store.select('ts', where=Term('Path', '=', 6), auto_close=False)
print(len(p1))
p2      =   store.select('ts', auto_close=False)
p2s     =   p2[p2.index.get_level_values('Path') == 6]
print(len(p2s))
```

### LINKED ISSUE #9676: BUG: entries missing when reading from pytables hdf store using "where" statement
When I select from a HDF store using a "where" string (locating entries in which one field matches a particular string value), the function returns fewer rows than when I load the entire dataframe into memory and then match on that field. Below is some code that reproduces the problem; unfortunately, I can't easily provide the code that generates the source HDF store, but I'm happy to provide the kept_tids_20150310.h5 file if it would help. There are no nan values in the dataframe.

Running ptrepack on the dataframe solves the problem, but I don't believe this should happen in the first place.

I am using pandas 0.15.2 but have not tried 0.16.0.

```python
>>> import pandas as pd
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.3.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-46-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.15.2
nose: 1.3.4
Cython: 0.19.2
numpy: 1.9.2
scipy: 0.15.1
statsmodels: 0.5.0
IPython: 2.4.0
sphinx: 1.2.3
patsy: 0.2.1
dateutil: 2.4.1
pytz: 2014.10
bottleneck: 0.8.0
tables: 3.1.0
numexpr: 2.3
matplotlib: 1.4.2
openpyxl: None
xlrd: None
xlwt: 0.7.2
xlsxwriter: None
lxml: 2.3.2
bs4: 4.3.2
html5lib: 0.999
httplib2: 0.7.2
apiclient: None
rpy2: 2.4.2
sqlalchemy: None
pymysql: None
psycopg2: None
>>> kept_tids = pd.read_hdf('kept_tids_20150310.h5', 'kept_tids', mode='r')
>>> kept_tids.to_hdf('kept_tids_20150310_resave.h5', 'kept_tids', mode='w', format='t', data_columns=True)
>>> chroms = kept_tids['chrom'].drop_duplicates().order().tolist()
>>> print chroms
['chr1', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr2', 'chr20', 'chr21', 'chr22', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chrM', 'chrX', 'chrY']
>>> len(kept_tids)
202836
>>> sum(len(pd.read_hdf('kept_tids_20150310_resave.h5', 'kept_tids', mode='r', where="chrom == '%s'"%x)) for x in chroms)
193757
>>> (kept_tids['chrom']=='chr16').sum()
10157
>>> len(pd.read_hdf('kept_tids_20150310_resave.h5', 'kept_tids', mode='r', where="chrom == 'chr16'"))
6278
```

### PR DESCRIPTION
**Pull request by jreback**
closes #8265
closes #9676

### CODE REVIEW

**Comment by jreback** [comment]
cc @rockg 
cc @alexfields 

give this a try and see if it fixed the issues you guys reported. lmk and can put this in 0.16.0

**Comment by rockg** [comment]
That did not work for me and actually returned fewer records than previously.  With this change, 2804 records were returned versus 2892 previously (the actual number should be 2972 records).

**Comment by rockg** [comment]
Maybe important to note that I tested this on 0.14.0 and putting your change in as that is what I have at work.  I don't know if there have been other substantive changes that might impact my test.

**Comment by alexfields** [comment]
My test agrees with @rockg - resaving my "problem" hdf via this commit and then reading with where statements gives slightly fewer lines than before (192334 vs 193757 previously, full file is 202836). Sorry @jreback! BTW in my case I am not using chunks or start/stop, I am selecting on the full file, and it still fails.

In the meantime I've just been calling ptrepack every time I save an HDF. I don't know if this always solves the problem but it has solved it every time I've tested, and gives an added bonus of speeding up on-disk selects anyway. As long as the tables saved by ptrepack are OK, this doesn't seem like such a bad workaround for now.

**Comment by jreback** [comment]
hmm ok
can u guys test with master on your dataset when u have a chance and lmk?

**Comment by alexfields** [comment]
Master 026a1221dee770597b5438a8a43f154bbdf891df is giving me the same 193757 number as in 0.15.2 (different from the 7480a4b0411400acc86bd9ca92c902b4081921a0 commit you sent earlier).

**Comment by jreback** [comment]
ok, seems that even though MY test worked, something else is going on. Ok will close this and can bug the PyTables guys to see if they can fix.

**Pull request closed without merging**
