### PR TITLE
rename multi-index

### PR DESCRIPTION
**Pull request by waitingkuo**
## Fix Issue #4160

While renamed a `MultiIndex`, the `mapper` walk through every tuple in the MultiIndex and every element in a tuple. So the mapper { (index1, index2): (new_index1, new_index2) } didn't work for the MultiIndex case.

This pull request is to modify it to walk through every tuple in a MultiIndex and use the mapper to map each tuple.
Also, the test case has been added.

### CODE REVIEW

**Comment by jreback** [comment]
closing for now. @waitingkuo if you want to update, pls do.

**Comment by gordol** [comment]
is this possible yet?

**Comment by jreback** [comment]
see the issue - it's open

**Comment by gordol** [comment]
yeah but there are about 10-15 dupe issues of this, and some of them have merged resolutions... it's not clear what the status is.

**Comment by jorisvandenbossche** [comment]
@gordol there are also many ways to rename a MultiIndex. For example, to rename a label in a single level in the meantime works (https://github.com/pandas-dev/pandas/pull/13766), but using tuples to rename a full entry (the open issue) not yet

**Pull request closed without merging**
