### PR TITLE
Fix docstring of Index.join in base.py

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
That's a very strange thing and it's better if pandas devs can have a closer look here.

I can see the `Examples` have been added with https://github.com/pandas-dev/pandas/pull/53403 but there is no sign of any failure. Everything looks good over there (cc @DeaMariaLeon @MarcoGorelli).

**Comment by kmuehlbauer** [comment]
> Everything looks good over there (

I did not look far down enough. The "Examples" heading is indeed one space to far to the right. So this PR should fix it.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Nice thanks @kmuehlbauer

**Comment by kmuehlbauer** [comment]
@mroeschke @lithomas1 Could this be included into 2.1.1? This breaks doc-building downstream.

**Comment by lithomas1** [comment]
@meeseeksdev backport 2.1.x

**Pull request merged**
