### PR TITLE
COMPAT: Update old numpy aliases

### LINKED ISSUE #55454: CI: npdev is failing
Looks like issues are caused by removal of the "a" (alias for S, used in our stata code) and "unicode" (also alias for S) aliases.

xref https://github.com/pandas-dev/pandas/actions/runs/6454504887/job/17520199451?pr=55450

I'll have a look in the afternoon if this isn't fixed by then.

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #55454 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature

### CODE REVIEW

**Comment by mroeschke** [comment]
@lithomas1 do you think we should backport this to 2.1.2? It appears that Numpy 2.0 is going to remove the `np.dtype("a")` alias https://github.com/numpy/numpy/pull/24854

**Comment by lithomas1** [comment]
We'd need the minimum version of Cython to be 3.0 to be fully compatible with numpy 2.0 and I'm not sure if that's going to happen before we release 2.2.

**Review by lithomas1 — APPROVED** [review]

**Comment by lithomas1** [comment]
thanks @mroeschke.

**Comment by lithomas1** [comment]
@meeseeksdev backport 2.1.x.

**Comment by lithomas1** [comment]
@meeseeksdev backport 2.1.x.

**Pull request merged**
