### PR TITLE
Backport PR #34711 on branch 1.0.x (BLD: Pin cython for 37-locale build)

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref #34711

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
see https://github.com/pandas-dev/pandas/pull/34711#issuecomment-644148383, abort this backport?

**Comment by simonjayhawkins** [comment]
closing for now. I probably should have pinned at 0.29.13 anyway.

**Comment by simonjayhawkins** [comment]
cc @jorisvandenbossche just to be aware i've closed this.

**Comment by jorisvandenbossche** [comment]
OK!

**Pull request closed without merging**
