### PR TITLE
REF: use more explicit to_numpy(object) instead of astype(object) in EA implementation

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Somewhat related to https://github.com/pandas-dev/pandas/issues/24877 / https://github.com/pandas-dev/pandas/pull/43699, but regardless of whether we want to stop `astype` returning numpy arrays or not, I think when we know we want to get an object-dtype numpy array as result, using `to_numpy(object)` is more explicit about this when reading the code.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Can't speak to the general case, but DTA is more performant in astype

```
In [3]: dti = pd.date_range('2016-01-01', periods=10**5, freq='s', tz="US/Pacific")

In [4]: dta = dti._data

In [5]: %timeit dta.astype(object)
50.8 ms ± 2.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: %timeit dta.to_numpy(object)
178 ms ± 6.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by jorisvandenbossche** [comment]
Good catch. That seems to be because in datetimelike `__array__` we explicitly go through a list, which shouldn't be needed:

https://github.com/pandas-dev/pandas/blob/fefccfe10a34d244ec1df0bba5792fbc894c4402/pandas/core/arrays/datetimelike.py#L313-L316

We can probably call astype there (or do the same than astype does). Astype special cases object dtype for datetime64 to directly call `ints_to_pydatetime`:

https://github.com/pandas-dev/pandas/blob/fefccfe10a34d244ec1df0bba5792fbc894c4402/pandas/core/arrays/datetimelike.py#L410-L422

(which is what `list(self)` will also call, but then iteratively)

**Comment by jbrockmendel** [comment]
xref #44484 for dispatch logic

**Comment by jorisvandenbossche** [comment]
Yes, although the behaviour differences I note in that issue are for other dtypes, not object dtype (for object, it's only a matter of performance, as far as I see)

**Comment by simonjayhawkins** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
