### PR TITLE
ENH: add MultiIndex.to_dataframe

### LINKED ISSUE #12397: Add to_dataframe() method to MultiIndex
I find the `Index.to_series` method is a convenient way to allow indices to act as columns of a dataframe where desired. However, the behavior of `MultiIndex.to_series`, which gives a `Series` of tuples, is less useful.

Would it be convenient to provide a `to_dataframe` method for index classes? This would be a natural extension of the utility of `to_series`, and more useful for `MultiIndex` objects I would think.

I'm   something equivalent to:

> ```
> def to_dataframe(self):
>    DataFrame(self.tolist(), columns=self.names, index=self)
> ```

### PR DESCRIPTION
**Pull request by jreback**
ENH: allow hashing of MultiIndex

closes #12397

### CODE REVIEW

**Comment by jreback** [comment]
```
In [52]: i = pd.MultiIndex.from_tuples([(118, 472), (236, 118), (51, 204), (102, 51)])

In [53]: i
Out[53]: 
MultiIndex(levels=[[51, 102, 118, 236], [51, 118, 204, 472]],
           labels=[[2, 3, 0, 1], [3, 1, 2, 0]])

In [55]: i.to_dataframe(index=False)
Out[55]: 
     0    1
0  118  472
1  236  118
2   51  204
3  102   51

In [56]: from pandas.tools.hashing import hash_pandas_object

In [57]: hash_pandas_object(i.to_dataframe(index=False), index=False)
Out[57]: 
0    11950414010286087598
1    11950414010286087598
2    10472907816967777234
3    10472907816967777234
dtype: uint64

In [58]: hash_pandas_object(i.to_dataframe(index=False), index=True)
Out[58]: 
0    17404497957148711178
1     5195826631379738351
2    10365020365066803200
3    15157173997208611942
dtype: uint64
```

odd that [57] can produce duplicates. any thoughts @mikegraham 
(in practice I don't think this matters as we normally *also* include the index, which then makes these unique)

but I have a case where I just want to uniquely hash values (no index)

**Comment by mikegraham** [comment]
Were these collisions hit naturally, or were they engineered / selected from a really big set? Collisions are inevitable, but should be pretty rare. If you hit multiple easily, that's disconcerting.

It's possible that my algorithms are no good. I think the bitmixer behind hash_array is actually decent, but didn't put any special thought into the combining logic in adder. We can try replacing it with the combiner used with one like http://www.boost.org/doc/libs/1_55_0/doc/html/hash/reference.html#boost.hash_combine or https://github.com/python-git/python/blob/master/Objects/tupleobject.c#L290 -- this will of course make these collisions go away, but I'm not sure how to ascertain if there was an actual improvement.

**Comment by mikegraham** [comment]
I can try setting up something to fuzz the heck out of it some time soon if we think it comes to that.

**Comment by jreback** [comment]
@jorisvandenbossche ok with this? (I need to build on top of this for other things).....

**Comment by jorisvandenbossche** [comment]
Yes, looks good. Only thing I am wondering is the name. We already have `Series.to_frame` as well, so it would be nice to be consistent here (although I think I like `to_dataframe` more ..). 

Also wondering if this should be restricted to MultiIndex and not just general for Index (but that can certainly go in a follow-up PR if we want that)

**Comment by jreback** [comment]
sure will change ``.to_frame()``

not sure if we should add this to ``Series``, it doesn't really make senses there :>

**Comment by jorisvandenbossche** [comment]
> not sure if we should add this to ``Series``, it doesn't really make senses there :>

I wrote Index, not Series (but maybe that's what you meant :-)). Index already has a `to_series` method, which is more logical for an Index, but the main motivation would be to just not create more distinction in api between single/multi index  (eg to not always have to check the number of levels of your index when writing generic code, cfr #3268)

**Comment by jreback** [comment]
@jorisvandenbossche yeah that is a fair point, we can revisit, i'll create an issue.

**Pull request closed without merging**
