### PR TITLE
CI: troubleshoot segfault

### PR DESCRIPTION
**Pull request by jbrockmendel**
I can't reproduce the CI failures locally, so just rolling back a few commits to narrow it down.

### CODE REVIEW

**Comment by dsaxton** [comment]
Looking at https://github.com/pandas-dev/pandas/issues/31922#issuecomment-585999883 it seems the test reverted in https://github.com/pandas-dev/pandas/pull/36511/commits/4679970b2d64d3c55150e0953d04a15d8ae23a48 wasn't supposed to run across all builds?

**Comment by jbrockmendel** [comment]
> wasn't supposed to run across all builds?

Looks like, yah

**Review by dsaxton — APPROVED** [review]
Nice, thanks for finding that

**Comment by jreback** [comment]
hmm this is failing older builds?

**Comment by jreback** [comment]
ok so merging this and will re-open #31922 as this is supposed to run only on numpy master? (are the older build too old)?

**Pull request merged**
