### PR TITLE
CI: fix flake8 warning

### PR DESCRIPTION
**Pull request by MarcoGorelli**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
#49457 and #49485 both removed warnings from that file and were merged in close succession (without being updated), hence the CI failure crept through - no biggie

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by MarcoGorelli** [comment]
thanks - merging then as this affects the builds of open PRs, and is also a trivial change

**Comment by mroeschke** [comment]
Thanks for catching my oversights @MarcoGorelli

**Comment by MarcoGorelli** [comment]
It's OK, always updating all PRs to be up-to-date with upstream/main isn't really feasible given the volume of PRs, if there's the occasional lint issue that creeps through that's OK, it's not a common occurrence

**Pull request merged**
