### PR TITLE
REF: simplify _get_empty_dtype_and_na

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase as i think we merged some of the prior ones

**Comment by jbrockmendel** [comment]
> can you rebase as i think we merged some of the prior ones

git is telling me this is up to date (though github is showing me a weird diff)

**Comment by jreback** [comment]
> > can you rebase as i think we merged some of the prior ones
> 
> git is telling me this is up to date (though github is showing me a weird diff)

hmm interesting, i see pieces of several merged PRs AFAICT

**Comment by jbrockmendel** [comment]
ill force push to be on the safe side

**Comment by jbrockmendel** [comment]
rebased + green

**Comment by jreback** [comment]
i think merge master as other things have been merged which touch this

**Comment by jbrockmendel** [comment]
> i think merge master as other things have been merged which touch this

rebased 2 hours ago, following #39454, so we should be good here

**Review by jreback — APPROVED** [review]

**Pull request merged**
