### PR TITLE
DOC: Done the changes as specified in issue#49254

### LINKED ISSUE #49254: DOC: 10 minutes to pandas Selection section `DataFrame.loc` followed by `()`
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/10min.html

### Documentation problem

`DataFrame.loc`, etc should not be followed by parenthesis, because they are not functions. 

> # Selection
> While standard Python / NumPy expressions for selecting and setting are intuitive and come in handy for interactive work, for production code, we recommend the optimized pandas data access methods, [DataFrame.at()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at), [DataFrame.iat()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iat.html#pandas.DataFrame.iat), [DataFrame.loc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc) and [DataFrame.iloc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc).

> ## Selection by label
> See more in [Selection by Label](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-label) using [DataFrame.loc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc) or [DataFrame.at()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at).

> ## Selection by position
> See more in [Selection by Position](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-integer) using [DataFrame.iloc()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc) or [DataFrame.at()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at).

### Suggested fix for documentation

> ... optimized pandas data access methods, [DataFrame.at](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at), [DataFrame.iat](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iat.html#pandas.DataFrame.iat), [DataFrame.loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc) and [DataFrame.iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc).

### PR DESCRIPTION
**Pull request by EleekaN**
- [ ] closes #49254

### CODE REVIEW

**Comment by ge-li** [comment]
Should also change the doc under the **Selection by label** and **Selection by position** sections. See **Documentation problem** #49254

**Comment by rhshadrach** [comment]
Thanks for the PR! Can you make the title more descriptive here? Ideally, when a maintainer reads just the title, they'd like to have a good sense of what the PR is doing overall. This makes navigating the PR queue a lot easier for us. In this PR, I only know that it solves some issue with a code, which doesn't tell me much. Of course I can go look that issue up, but the goal is for me to get a sense of what this is doing without having to look it up.

A suggestion would be something along the lines of `DOC: Remove parentheses after loc, iloc, at, iat`

**Comment by EleekaN** [comment]
Thank you for your feedback. I have applied the changes, hope it looks good
this time.

**Comment by rhshadrach** [comment]
Ah, my apologies! I wasn't specific enough - I had meant the title at the top:

image

This can be edited at any point by clicking the button on the very right of this screen shot. But your new open PR looks good! I wouldn't change anything at this point.

**Pull request closed without merging**
