### PR TITLE
BUG: Styler cell_ids fails on multiple renders

### LINKED ISSUE #35663: BUG: Styler `cells_ids` fails on second render
issue #35588 addressed the issue of `cell_ids` failing.

This bug reports a failure on second render(), due to `ctx` object, as a `defaultdict`, having a key inserted when it is queried, which then impacts the programming logic the second time it is run.

The solution is to move the query within conditional a few lines above.

### PR DESCRIPTION
**Pull request by attack68**
- [x] closes #35663 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by attack68** [comment]
@jreback this is a very minor alteration to my previously merged commit. Are you able to review? Should go to 1.1.1, where a bug fixes line already exists in the 'whats changed' file to address this `cell_ids` arg.

**Review by jreback — CHANGES_REQUESTED** [review]
ok this is fine. pls append the issue number onto the original whatsnew (for 1.1.1), rebase and ping on green.

**Comment by attack68** [comment]
changes complete @jreback .. ping

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @attack68

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.1.x

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.1.x

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.1.x

**Pull request merged**
