### PR TITLE
REF: simplify Block.setitem

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Yak-shaving to get to a point where we can share Block.setitem with Block subclasses.

### CODE REVIEW

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/runs/4834282676?check_suite_focus=true look relevant

**Comment by jbrockmendel** [comment]
> https://github.com/pandas-dev/pandas/runs/4834282676?check_suite_focus=true look relevant

addressed + greenish

**Comment by jreback** [comment]
do we know what is wrong with the windows builds

**Comment by jbrockmendel** [comment]
> do we know what is wrong with the windows builds

no idea, seems like more than the usual number of timeouts today

**Pull request merged**
