### PR TITLE
BUG: string slicing on MultiIndex DatetimeIndex level

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Original motivation was to get rid of _get_partial_string_timestamp_match_key.

### CODE REVIEW

**Comment by jreback** [comment]
rebase. plus this does look like a user facing change.

**Comment by jbrockmendel** [comment]
Rebased, what’s new added, green

**Comment by jreback** [comment]
looks fine, can you rebase

**Comment by jbrockmendel** [comment]
rebased + green

**Pull request merged**
