### PR TITLE
BLD: consolidate remaining extensions

### PR DESCRIPTION
**Pull request by jreback**
moves extensions to ``pandas/libs``, which holds the extension code and also the generated builds (as its importable). ``pandas/src`` is now almost an includes dir, holding low-frequency changing code.

This consolidates the import process making it more uniform and consistent throughout the codebase.

Finally this cleans up the remaining top-level namespace (with some deprecations in place for example ``pandas.lib``, ``pandas.tslib``, ``pandas.json``, ``pandas.parser``. I listed all of the changes in the whatsnew, but I don't think worthwhile deprecating anything else.

### CODE REVIEW

**Comment by chris-b1** [comment]
I'd suggest deprecating at least `tslib`.  I suspect there are some things like `from pandas.tslib import Timestamp` in the wild.

**Comment by jreback** [comment]
@chris-b1 added

**Comment by jreback** [comment]
cc @wesm

**Comment by jreback** [comment]
cc @shoyer 

FYI (I could make this a DeprecationWarning, but those get ignored :<)

```
(pandas) bash-3.2$ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> import xarray
/Users/jreback/miniconda3/envs/pandas/lib/python3.5/site-packages/xarray/conventions.py:9: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version. Please import from the pandas.libs.tslib instead
  from pandas.tslib import OutOfBoundsDatetime
```

**Comment by shoyer** [comment]
We used `from pandas.tslib import OutOfBoundsDatetime` because we needed to catch that specific exception and couldn't find it exposed in the public API anywhere.

It would be nice to move that to public API somewhere, maybe `pandas.errors` if the top level namespace is getting too crowded.

**Comment by wesm** [comment]
This looks fine from superficial glance. Might want to nest src at `pandas/libs/src`. Sort of a "hear lies all ye compiled code" (eventually headed for Davy Jones's locker once the libpandas games get going. I feel like a broken record but it really is going to happen =) )

**Comment by jreback** [comment]
@wesm sure that sounds good. yeah that's the idea :>

**Comment by jreback** [comment]
going to merge on pass.

**Comment by jorisvandenbossche** [comment]
Big +1 on consolidation of where and how the c/cython extensions are organized (and for removing them from the top-level namespace).

Some comments:

- is there a specific reason libwindow is in core and not libs?
- the same as I commented in the other PR, IMO we should think about whether we need to recommend users to import from `pandas.libs` directly (the deprecation warnings now do that).
- Regarding the indication of 'privateness', something like `pandas.tools.libhash` looks more public compared to `pandas._hash` to me (it's not because it is not top-level anymore, that it is not public. We have public non-top-level API). So if we regard that as non-public, I find that not an improvement (that aspect). 

I am personally in favour of using more underscores, making it very clear that something is private stuff.

**Comment by shoyer** [comment]
underscores!

**Comment by jreback** [comment]
well, underscores do a lot to make this non-readable.

I *could* make this ``pandas._libs`` (IOW, make all extensions private). I prefer to have imports *inside* pandas code like this

``from pandas._libs import tslib, lib``
rather than
``from pandas.libs import _tslib, _lib``

which looks really ugly to me.

**Comment by shoyer** [comment]
> I could make this pandas._libs (IOW, make all extensions private). I prefer to have imports inside pandas code like this
> 
> from pandas._libs import tslib, lib
rather than
from pandas.libs import _tslib, _lib
>
> which looks really ugly to me.

Agreed, there's no need to use more than one level of underscores. I also prefer using `_libs.lib` to `libs._lib`.

**Comment by jreback** [comment]
> Agreed, there's no need to use more than one level of underscores. I also prefer using _libs.* to libs._*.

ok that seems reasonable. Could also do ``_internals``, though that is a bit longish.

**Comment by jreback** [comment]
renamed to ``_libs``. This drops if from the main pd namespace as well, so that's a plus.

@jorisvandenbossche w.r.t. the ``lib*``. I can make those private (but still keep the code in those locations) if desired (prob in a followup though)

**Comment by jreback** [comment]
bombs away.

**Pull request closed without merging**
