### PR TITLE
CLN/DOC: cache_readonly: remove allow_setting + preserve docstring

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes https://github.com/pandas-dev/pandas/issues/18197

This kind of 'works' in that `?` or `__doc__` now give the correct docstring, but it's not yet fully ideal as it is now seen as a class (which will probably mess up sphinx' autodoc/autosummary, which I didn't check yet)

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback the `cache_readonly` property now has the `allow_setting` option, which is only used for `Index.is_unique`. But this is actually not used anymore internally (it was used for the default index, see https://github.com/pandas-dev/pandas/commit/8c08acaef77e3b901dcbe09b612de785b0c5e782, but that is now a range index). Do you mind me removing it?

**Comment by jreback** [comment]
yeah i think can remove that

**Comment by jorisvandenbossche** [comment]
Another thing, a test is failing for  (with `ind` being an Index):

```
ind.view(np.ndarray).view(Index)

```

but I think this stems from the time that Index was an array subclass. As this now raises an error (with this PR, because `pd.Index.dtype` no longer returns None but an instance of the cached property), while before it was just silently returning garbage.

**Comment by jorisvandenbossche** [comment]
@jreback any comments ?

**Comment by jorisvandenbossche** [comment]
Did some manual timeits on a cache attribute (Index.hasnans), and once it is cached seeing a small slowdown from ca 85 ns to ca 95 ns. Not sure if this is actually related to this, but since this is about 10 nanoseconds, this doesn't seem a problem.

**Pull request merged**
