### PR TITLE
DOC: remove private parameters from method/constructor signatures

### LINKED ISSUE #52028: DOC: Remove internally used/private parameters from method signatures
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.html#pandas.Series

### Documentation problem

The public api contains internally used parameter. In this case the Series constructor contains `fastpath` parameter which isn't documented in the docstring. However, is part of the constructor signature.

### Suggested fix for documentation

Suggested solution:

1. Prefix the internally used/private parameter with an underscore (`_`)
2. Remove all the parameters starging with an underscore while processing the method signatures in sphinx.

This problem is already identified in a very old issue: #6903

### PR DESCRIPTION
**Pull request by numanijaz**
- [x] closes #52028
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

The documentation (e.g. for Series constructor) contain the parameters which are used only internally (fastpath in case of Series). Now if a parameter is private and prefixed with an underscore `_` it will not be part of the signature in the output.

### CODE REVIEW

**Review by phofl — CHANGES_REQUESTED** [review]
This is an API change, we can't do this without deprecating.

**Comment by NumanIjaz** [comment]
@phofl thanks for the review. Is there any guide on how we do the deprecation?

**Comment by phofl** [comment]
You should start by opening an issue to discuss it

**Comment by NumanIjaz** [comment]
Created #52028 for the discussion.

**Comment by mroeschke** [comment]
Seems like the issue needs more discussion before moving forward with a PR so closing for now, but we can reopen when theres more consensus

**Pull request closed without merging**
