### PR TITLE
DEPR: deprecate element-wise operations in (Series|DataFrame).transform

### LINKED ISSUE #54906: DEPR: deprecate element-wise operations in (Series|DataFrame).transform
A discussion has been going on in #54747 (PDEP 13) about making `Series.transform` and `DataFrame.transform` always operate on Series. See https://github.com/pandas-dev/pandas/pull/54747#issuecomment-1698804000 and related comments. Opening a separate issue to separate that discussion from PDEP 13/#54747.

Currently,  `Series.transform` tries to operates on series element and if that fails if tries operating on the series.  So it uses a fallback mechanism, which makes it difficult to use + the first choice (element-wise operations) is very slow. `DataFrame.transform` operates on series (i.e. columns/rows) when given callables, but operates on elements, when given lists or dicts of callables, which is . Examples:

```python
>>> df = pd.DataFrame({"x":range(100_000)})
>>> %timeit df["x"].transform(lambda x: x + 1) # operates on elements, slow
15.5 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
>>> %timeit df['x'].transform(np.sin) # ufunc, fast
784 µs ± 19.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
>>> %timeit df['x'].transform(lambda x: np.sin(x)). # non-ufunc, operates on elements, slow
86.6 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
>>> %timeit df.transform(lambda x: x + 1)  # operates on the columns/series, fast
142 µs ± 589 ns per loop
>>> %timeit df.transform([lambda x: x + 1])  # lists/dicts operate on the elements, slow
16.7 ms ± 165 µs per loop
```

All in all, the above is very inconsistent and difficult to reason about for users, similarly to the discussion regarding `apply` in #54747/PDEP 13.

I propose to deprecate element-wise operations in `(Series|DataFrame).transform`, so in Pandas v3.0 giving callables (and lists/dicts of callables) to `(Series|DataFrame).transform` always operates on  series.  The benefit of this is that the `(Series|DataFrame).transform` will become much more predictable and faster. When users want to do element-wise operations, they should be directed to  use `(Series|DataFrame).map`. So no functionality is lost, but we get clearer separation between series-wise and element-wise operations.

The deprecation is proposed implemented in pandas v2.2, where we add a new keyword parameter `series_ops_only` to `(Series|DataFrame).transform`. When set to true, `(Series|DataFrame).transform` will always operate on the whole series. When False, the old behavior will be kept, and a deprecation warning will be emitted. In pandas v3.0, the old behavior will be removed and `(Series|DataFrame).transform` will only operate on series.

Related PRs:
* #54747
* #52140
* #53325 (similar issue for `agg`, already implemented)
* #40112

### PR DESCRIPTION
**Pull request by topper-123**
- [x] closes #54906 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Still need to do docs, docstrings and whatsnew and possibly some separate deprecation tests but otherwise should be ready for review.

### CODE REVIEW

**Review by phofl — CHANGES_REQUESTED** [review]
I generally think this is a good idea, but this needs more time for discussion first

**Comment by Dr-Irv** [comment]
> Still need to do docs, docstrings and whatsnew and possibly some separate deprecation tests but otherwise should be ready for review.

I think the implications of this PR can only be understood with appropriate changes to the docs.

**Comment by topper-123** [comment]
The failure looks unrelated.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. Let's continue the affirm the choice to move forward with this in the issue before moving forward here

**Pull request closed without merging**
