### PR TITLE
Gbq upgrade

### PR DESCRIPTION
**Pull request by tworec**
This adds support for service account authorization to Google Big Query API + some informative messages on std out.

GBQ can be used with Python 3. In RTBHouse we are doing this since may. It works perfectly with this pandas upgrade.

### CODE REVIEW

**Comment by jreback** [comment]
this was done in 0.17.0 released on October 

http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#google-bigquery-enhancements

so pls rebase on master

you can submit other enhancements if you wish -

**Comment by tworec** [comment]
I will rebase :) sorry
but I do not see any support for google service account auth in master now.
This is usable when working from remote host Jupyter/iPython web notebooks and one can not authorize to google by web request

**Comment by jreback** [comment]
iirc we have an issue for the service account
if u can find one pls xref it (and of course impl welcome as well)

**Comment by tworec** [comment]
ok, I found this 
https://github.com/pydata/pandas/issues/8489
I'll push my patch for that

**Pull request closed without merging**
