### PR TITLE
BUG: Fix bug where sort_index if unsorted levels.

### LINKED ISSUE #12261: sort_index doesn't sort MultiIndex when .loc[] referred to non-existent label on other axis
```
In [2]: df = pd.DataFrame(0, columns=[], index=pd.MultiIndex.from_product([[], []]))

In [3]: df.loc['b', '2'] = 1

In [4]: df.loc['a', '3'] = 1

In [5]: df.sort_index()
Out[5]: 
      2    3
b   1.0  NaN
a   NaN  1.0

In [6]: df.sort_index().index.is_monotonic
Out[6]: False
```

Am I missing anything obvious?!
(Notice that this is not related to any of the two axes being initialized as empty)

### PR DESCRIPTION
**Pull request by tshauck**
Closes #12261

### CODE REVIEW

**Comment by tshauck** [comment]
Not sure if this is the best way to solve this, but it looks like the bug in #12261 is because the labels are sorted, but the levels aren't.

It seems like the better way is `is_lexsorted` should return `False` if the levels aren't sorted because you could get the potential mismatch, but that's a layer below this issue so I didn't want to touch it.

**Comment by jreback** [comment]
this is not the right way to go about this.

**Comment by tshauck** [comment]
Ok... Does this help you see what this issue is enough (you didn't seem to have an idea from the issue*) to recommend what the appropriate path would be?

* Seems to be the level sorting issue unless it's a red herring.

**Comment by jreback** [comment]
yeh I haven't really delved into it much.

**Comment by tshauck** [comment]
Ok...

**Pull request closed without merging**
