### PR TITLE
DOC: fix versionchanged blank line usage (#49117)

### LINKED ISSUE #49117: DOC: Fix versionchanged directive in DataFrame.plot
Looks like there is something wrong in the documentation of `DataFrame.plot`, and the `.. versionchanged` directive of the parameters `logx`, `logy` and `loglog` is not rendered correctly: https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.plot.html

It's probably a typo, a missing space or something. We should have a look and compare with another docstring where a parameter `versionchanged` is correctly rendered, see what's wrong, and fix it.

### PR DESCRIPTION
**Pull request by mathpn**
- [ ] closes #49117 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
Thanks @mathpn, looks good to me. Did you try to render the docs locally to doubke check thast this renders as expected? Or you can download the artifact with the built docs from the CI too.

**Comment by mathpn** [comment]
@datapythonista thank you for the review. Yes, docs built locally are rendered as expected ("Changed in version 0.25.0"). However, the CI doc build failed for a reason that looks unrelated to the changes introduced by the commit (URLError: <urlopen error [Errno 104] Connection reset by peer>).

**Comment by datapythonista** [comment]
Thanks! Connection errors happen sometimes, let's rerun the CI and see if we're lucky.

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @mathpn

**Pull request merged**
