### PR TITLE
GH31391 - Fixed typos and fixed inexistant path in a SAS class comment

### PR DESCRIPTION
**Pull request by jeandersonbc**
Simple change: just fixed some typos and incorrect path as reported in #31391

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks, @jeandersonbc !

I don't think we would typically update an old whatsnew note, could you please revert that one to how it is on the master branch?

**Comment by jbrockmendel** [comment]
> I don't think we would typically update an old whatsnew note,

@TomAugspurger whats the policy on this?

**Comment by TomAugspurger** [comment]
I don’t think we have one. What would you recommend?

**Comment by jbrockmendel** [comment]
I think for legitimate typos we're OK retroactively fixing.

**Comment by jbrockmendel** [comment]
thanks @jeandersonbc

**Pull request merged**
