### PR TITLE
TYP: Make components of Suffixes Optional

### PR DESCRIPTION
**Pull request by scravy**
The documentation on the parameters that actually are of type `Suffixes`:

> *suffixeslist-like, default is (“_x”, “_y”)*
> A length-2 sequence where each element is optionally a string indicating the suffix to add to overlapping column names in left and right respectively. _**Pass a value of None**_ instead of a string to indicate that the column name from left or right should be left as-is, with no suffix. At least one of the values must not be None.

### CODE REVIEW

**Comment by scravy** [comment]
Yes, still interested in this.

**Comment by jreback** [comment]
@scravy pls merge master and can have a look

**Comment by scravy** [comment]
Do you prefer rebasing or merging from master?

**Comment by jreback** [comment]
either are fine

**Comment by scravy** [comment]
@jreback I rebased.

**Comment by jreback** [comment]
thanks @scravy

**Pull request merged**
