### PR TITLE
Update hist.py

### PR DESCRIPTION
**Pull request by guptaarth87**
- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by guptaarth87** [comment]
improvement in documentation

**Comment by MarcoGorelli** [comment]
thanks but no thanks - please check the good first issues and the contributing guide for how to get started

**Comment by ThiefMaster** [comment]
please mark the PR as `[invalid]` to the OP gets banned from hacktoberfest for this spam

**Comment by MarcoGorelli** [comment]
thanks - hope there's not more of this coming

**Pull request closed without merging**
