### PR TITLE
CLN: Use generators instead of lists in built-in Python functions

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] tests passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Pass generators in built-in Python functions instead of passing in a list, e.g `any([value for value in iterator])` --> `any(value for value in iterator)`

### CODE REVIEW

**Comment by jreback** [comment]
@mroeschke thanks.

can you add a linting check in ``ci/lint.sh`` to search for cases like this?

**Comment by jreback** [comment]
does this have any perf impact ?

**Comment by mroeschke** [comment]
I ran one full asv and two asvs for `benchmarks/frame_methods.py` and got pretty inconsistent results. I can rerun if needed.

Sure I can include this check in `ci/lint.sh`. I'll be available to add it later in the week.

**Comment by jreback** [comment]
thanks

> Sure I can include this check in ci/lint.sh. I'll be available to add it later in the week.


would be great

**Comment by jorisvandenbossche** [comment]
I don't thing you would expect to see any difference in asv. I think this is mainly about code style / redundancy. Certainly given that, apparently (just tried it out, didn't expect this), with small lists it can actually be a bit faster using a list comprehension instead of generator (for bigger ones there is a clear difference though):

```
In [168]: l = [True, False]*2

In [169]: %timeit any(i for i in l)
511 ns ± 7.38 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [170]: %timeit any([i for i in l])
448 ns ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [171]: l = [True, False]*100

In [172]: %timeit any(i for i in l)
514 ns ± 7.66 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [173]: %timeit any([i for i in l])
5.7 µs ± 39.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

(and the cases in our code typically are small numbers, eg looping of the axes of a DataFrame (thus 2))

**Pull request merged**
