### PR TITLE
Revert FrozenList changes (doc build slowdown, #15559)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See #15559. This temporarily reverts #15506, to see if this fixes the doc build slowdown.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
So I am totally puzzled about why, but reverting this *does* fix the doc build timeout, see https://travis-ci.org/pandas-dev/pandas/builds/207655451

While we figure this out, I would like to merge this revert for now, because with current master it makes doc building really unbearable (certainly with the docathon coming up).

**Comment by jreback** [comment]
sure pls create an issue (or leave this one open and i'll take a look)

where was the doc build hanging (what part)?

**Comment by jorisvandenbossche** [comment]
The full 'reading' part (that is AFAIK the part where the ipython code blocks are executed). I am thinking of how we can try to profile that).

**Comment by jreback** [comment]
using this to debug (it prints a LOT)
``-vvv`` is verbose, ``-N`` removes the color output, and removed the ``-P`` to try

```
diff --git a/doc/make.py b/doc/make.py
index 8a6d4e5..3c47409 100755
--- a/doc/make.py
+++ b/doc/make.py
@@ -197,7 +197,7 @@ def html():
                 print(e)
                 print("Failed to convert %s" % nb)
 
-    if os.system('sphinx-build -P -b html -d build/doctrees '
+    if os.system('sphinx-build -vvv -b html -d build/doctrees '
                  'source build/html'):
         raise SystemExit("Building HTML failed.")
```
we should prob *always* add ``-v`` just to have it print out files as it reads them.

still not sure why it fails

**Comment by jreback** [comment]
so going to merge this and we can figure out later.

**Pull request closed without merging**
