### PR TITLE
TYP: offsets

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@TomAugspurger are things like this mergeable during the RC or are they just cluttering the queue for the next couple of weeks?

Side-note: running the tests has started leaving a bunch of .pickle files behind.  Is that just me?

**Comment by TomAugspurger** [comment]
I've noticed the stray pickle files. Not sure what test is leaving them.

IMO, these kind of PRs can be merged to master, but don't need to be
backported. So they'll be included in 1.1.

**Review by WillAyd — APPROVED** [review]
lgtm @simonjayhawkins

**Comment by simonjayhawkins** [comment]
Thanks @jbrockmendel

**Pull request merged**
