### PR TITLE
BUG: ArrowExtensionArray logical ops raising KeyError

### PR DESCRIPTION
**Pull request by lukemanley**
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/v2.1.0.rst` file if fixing a bug or adding a new feature.

fixes the following:

```
import pandas as pd

ser = pd.Series([True, False, True], dtype="boolean[pyarrow]")

ser & True  # KeyError: 'and_'
ser | True  # KeyError: 'or_'

ser & ser   # KeyError: 'and_'
ser | ser   # KeyError: 'or_'
```

### CODE REVIEW

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
cc @mroeschke

**Review by mroeschke — APPROVED** [review]
LGTM. Wouldn't be opposed to backporting to 2.0. WDYT @phofl?

**Comment by phofl** [comment]
@lukemanley could you move the whatsnew?

**Comment by lukemanley** [comment]
> @lukemanley could you move the whatsnew?

moved to 2.0, thanks

**Review by mroeschke — APPROVED** [review]

**Comment by phofl** [comment]
thx @lukemanley

**Pull request merged**
