### PR TITLE
ENH: Add dtype_backend to to_numeric

### PR DESCRIPTION
**Pull request by mroeschke**

### CODE REVIEW

**Review by phofl — APPROVED** [review]
Like my read_json pr :)

Can we open an issue about implementing this properly?

**Comment by phofl** [comment]
thx @mroeschke

**Comment by mroeschke** [comment]
> Can we open an issue about implementing this properly?

This may be the "proper" way to implement this since the non-numeric inference & downcasting logic is all done in cython/numpy? I don't think there's any pure arrow equivalent to do this

**Comment by phofl** [comment]
Yeah we’d need a maybe downcast equivalent for this

**Pull request merged**
