### PR TITLE
STYLE: moving unwanted pattern check to precommit

### LINKED ISSUE #42123: STYLE move patterns checks to pre-commit
These checks from `ci/code_checks.sh` should be moved to pre-commit:
```
### PATTERNS ###
if [[ -z "$CHECK" || "$CHECK" == "patterns" ]]; then

    # Check for the following code in the extension array base tests: `tm.assert_frame_equal` and `tm.assert_series_equal`
    MSG='Check for invalid EA testing' ; echo $MSG
    invgrep -r -E --include '*.py' --exclude base.py 'tm.assert_(series|frame)_equal' pandas/tests/extension/base
    RET=$(($RET + $?)) ; echo $MSG "DONE"

    MSG='Check for deprecated messages without sphinx directive' ; echo $MSG
    invgrep -R --include="*.py" --include="*.pyx" -E "(DEPRECATED|DEPRECATE|Deprecated)(:|,|\.)" pandas
    RET=$(($RET + $?)) ; echo $MSG "DONE"

    MSG='Check for backticks incorrectly rendering because of missing spaces' ; echo $MSG
    invgrep -R --include="*.rst" -E "[a-zA-Z0-9]\`\`?[a-zA-Z0-9]" doc/source/
    RET=$(($RET + $?)) ; echo $MSG "DONE"

    MSG='Check for unnecessary random seeds in asv benchmarks' ; echo $MSG
    invgrep -R --exclude pandas_vb_common.py -E 'np.random.seed' asv_bench/benchmarks/
    RET=$(($RET + $?)) ; echo $MSG "DONE"

fi

```

some might fit in the `unwanted patterns` hook, others might need their own pygrep hook (no additional dependencies are necessary here though so the same existing virtualenvs will be reused)

- [ ] check for invalid EA testing
- [ ] deprecated messages without sphinx directive
- [ ] backticks incorrectly rendering because of missing spaces
- [ ] unnecessary random seeds in asv benchmarks

### PR DESCRIPTION
**Pull request by debnathshoham**
- [x] closes #42123 
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
cool, thanks - can you remove "patterns" from ci/code_checks as well? (e.g. in line 20)

**Comment by debnathshoham** [comment]
@MarcoGorelli done. 
Please let me know if this looks okay.

**Review by MarcoGorelli — APPROVED** [review]
nice, thanks (minor point - the dots (`.`) in the `entry`, `files`, and `exclude` could be escaped (`\.`) as they all just check regular expressions, but this is fine as-in)

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
there's

https://github.com/pandas-dev/pandas/blob/eaee348792cf45b0f8ca52944f066b7f27503066/.github/workflows/ci.yml#L35-L37

too

**Review by MarcoGorelli — APPROVED** [review]
looks good to me

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @debnathshoham

**Pull request merged**
