### PR TITLE
TST: Fix broken test cases where Timedelta/Timestamp raise

### PR DESCRIPTION
**Pull request by jbrockmendel**
Orthogonal to #28725, but will need to be rebased after that is merged.

### CODE REVIEW

**Comment by jreback** [comment]
see my comment on #28725

**Comment by jreback** [comment]
can you rebase

**Comment by jbrockmendel** [comment]
rebased+green

**Comment by WillAyd** [comment]
These are user facing changes right? Need a whatsnew?

**Comment by jreback** [comment]
> These are user facing changes right? Need a whatsnew?

not unless you have an example of what is changed. these are broken behavior in an internal method, likely there is a lot of duplicated / unsused code (except by the tests).

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
