### PR TITLE
BUG: Fixed bug in len(DataFrame.groupby) causing IndexError when there's a NaN-only column (issue11016)

### PR DESCRIPTION
**Pull request by terrytangyuan**
This is the new PR for Fixed issue #11016

### CODE REVIEW

**Comment by jreback** [comment]
generally we don't make *new* PR's. just ``push -f`` the old ones. ok for now. but pls have a look at:

http://pandas.pydata.org/pandas-docs/stable/contributing.html

**Comment by terrytangyuan** [comment]
@jreback Got it.  I will take a closer look at it.

**Comment by terrytangyuan** [comment]
So when I run `nosetests pandas/tests/test_groupby.py`, it gave me a lot of errors. This is on master branch from recent pydata/pandas. I think the errors are from recent commits rather than this PR.

**Comment by jreback** [comment]
you need to rebuild the c extensions
after u pull from master do this

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/066783c6ea16115d2cbc75dca443e973e81ad754

thanks

**Comment by marcelm** [comment]
Thanks for fixing!

**Pull request merged**
