### PR TITLE
Backport PR #49386 on branch 1.5.x (DOC: add name parameter to the IntervalIndex for #48911)

### PR DESCRIPTION
**Pull request by silviaovo**
…#48911

### CODE REVIEW

**Comment by phofl** [comment]
cc @Dr-Irv Is this a new argument? In general, we try to avoid backporting documentation fixes

**Comment by Dr-Irv** [comment]
> cc @Dr-Irv Is this a new argument? In general, we try to avoid backporting documentation fixes

No.  In the current docs, the argument is listed in the signature of these methods, but it is not described.

**Comment by mroeschke** [comment]
Yeah typically we only backport doc fixes if it was pertinent to something added in the last minor version or other exceptional cases to minimize backport conflicts

**Comment by datapythonista** [comment]
From the conversation above, seems like we don't want to backport this, closing.

**Pull request closed without merging**
