### PR TITLE
remove enum import for PY2 compat, xref #22802

### PR DESCRIPTION
**Pull request by jreback**
xref #22802

### CODE REVIEW

**Comment by jreback** [comment]
@TomAugspurger

**Comment by jreback** [comment]
this is quite tricky to test as would have to uninstall enum34 first.

**Review by TomAugspurger — APPROVED** [review]

**Comment by effigies** [comment]
I'll be able to confirm that this works in the absence of enum34, once this hits the nightly builds.

**Comment by jreback** [comment]
@TomAugspurger updated

**Review by TomAugspurger — APPROVED** [review]

**Comment by effigies** [comment]
Just a note that our tests based on the nightly builds are now passing. Thanks!

**Comment by jreback** [comment]
great! @effigies

**Pull request merged**
