### PR TITLE
BUG: join changes index type when doing join on empty dataframes

### LINKED ISSUE #52777: BUG: join resets index even when doing left join on empty dataframes
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

foo = pd.DataFrame([], index=pd.Index([], dtype="object"))
bar = foo.copy()

foo.join(bar).indexfoo.join(bar).index
```

### Issue Description

On Pandas 1.5.3 above example produces `Index([], dtype='object')` while on 2.0.0 it produces `RangeIndex(start=0, stop=0, step=1)`. I have not found this change in the [release notes](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html) so I have to assume it is an unintended change and it causes unwanted consequences.

### Expected Behavior

I expect the same behavior as in version 1.5.3

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.0-38-generic
Version          : #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 59.6.0
pip              : 23.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2023.3

</details>

### PR DESCRIPTION
**Pull request by topper-123**
- [X] closes #52777
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by mroeschke** [comment]
Looks good, but since 2.0.3 going out today, lets wait for this to go into 2.0.4

**Comment by topper-123** [comment]
whatsnew for v2.0.4 isn't in the repo yet. Should I just move this to v2.1.0?

**Comment by mroeschke** [comment]
Yeah let's just have this fix for 2.1

**Comment by topper-123** [comment]
👍 I've moved it.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks again @topper-123

**Pull request merged**
