### PR TITLE
Backport #59144 on 2.2.x / 2.3.x (remove ops div class to solve #2137)

### LINKED ISSUE #21374: pd.eval() discards imaginary part in division "/"
#### Code Sample

```python
data = {"a": [1 + 2j], "b": [1 + 1j]}
df = pd.DataFrame(data = data)
df.eval("a/b")

/usr/local/lib64/python3.6/site-packages/pandas/core/dtypes/cast.py:730: ComplexWarning: Casting complex values to real discards the imaginary part
  return arr.astype(dtype, copy=True)

0    1.0
dtype: float64
```
#### Problem description
The output type was coerced into a float. This also happens by assigning the result to another existing column:

```python
data = {"a": [1 + 2j], "b": [1 + 1j], "c": [1j]}
df = pd.DataFrame(data = data)
df.eval("c = a/b")

/usr/local/lib64/python3.6/site-packages/pandas/core/dtypes/cast.py:730: ComplexWarning: Casting complex values to real discards the imaginary part
  return arr.astype(dtype, copy=True)
Out[82]: 
        a       b    c
0  (1+2j)  (1+1j)  1.0
```
And even if the operation is in place:

```python
data = {"a": [1 + 2j], "b": [1 + 1j], "c": [1j]}
df = pd.DataFrame(data = data)
df.eval("c = a/b", inplace = True)
/usr/local/lib64/python3.6/site-packages/pandas/core/dtypes/cast.py:730: ComplexWarning: Casting complex values to real discards the imaginary part
  return arr.astype(dtype, copy=True)

df
        a       b    c
0  (1+2j)  (1+1j)  1.0
```

#### Expected Output
The expected output is
```python
df["a"]/df["b"]

0    (1.5+0.5j)
dtype: complex128
```
The problem seems to happen only with the "/" operator. In fact, the correct result can be obtained by replacing the division with a multiplication and a negative exponent:

```python
df.eval("a*b**(-1)")

0    (1.5+0.5j)
dtype: complex128
```

#### Output of ``pd.show_versions()``
<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.16.12-300.fc28.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: en_US.UTF-8

pandas: 0.23.0
pytest: None
pip: 9.0.3
setuptools: 39.2.0
Cython: None
numpy: 1.14.4
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: 0.4.1
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.1
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: None
lxml: 4.1.1
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### LINKED ISSUE #58548: BUG: pandas testsuite on 2.2.x with numpy 2 fails on numexpr
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# pip install 'numpy>=2.0.0rc1' 'pandas==2.2.2' hypothesis pytest numexpr
import pandas
pandas.test(extra_args=["-k", "test_eval and numexpr", "-l", "--tb=long"])
```

### Issue Description

I'm currently testing numpy 2 on the the openSUSE python ecosystem. I notice the pandas test suite failing when numpy 2.0.0rc1 is installed instead of 1.26.4.

See also https://github.com/pydata/numexpr/issues/483

```
============================================================================================= FAILURES =============================================================================================
___________________________________________________________ TestTypeCasting.test_binop_typecasting[numexpr-python-left_right0-float64-/] ___________________________________________________________

self = <pandas.tests.computation.test_eval.TestTypeCasting object at 0x7fdda001f250>, engine = 'numexpr', parser = 'python', op = '/', dt = <class 'numpy.float64'>, left_right = ('df', '3')

    @pytest.mark.parametrize("op", ["+", "-", "*", "**", "/"])
    # maybe someday... numexpr has too many upcasting rules now
    # chain(*(np.core.sctypes[x] for x in ['uint', 'int', 'float']))
    @pytest.mark.parametrize("dt", [np.float32, np.float64])
    @pytest.mark.parametrize("left_right", [("df", "3"), ("3", "df")])
    def test_binop_typecasting(self, engine, parser, op, dt, left_right):
        df = DataFrame(np.random.default_rng(2).standard_normal((5, 3)), dtype=dt)
        left, right = left_right
        s = f"{left} {op} {right}"
>       res = pd.eval(s, engine=engine, parser=parser)

df         =           0         1         2
0  0.189053 -0.522748 -0.413064
1 -2.441467  1.799707  1.144166
2 -0.325423  0.773807  0.281211
3 -0.553823  0.977567 -0.310557
4 -0.328824 -0.792147  0.454958
dt         = <class 'numpy.float64'>
engine     = 'numexpr'
left       = 'df'
left_right = ('df', '3')
op         = '/'
parser     = 'python'
right      = '3'
s          = 'df / 3'
self       = <pandas.tests.computation.test_eval.TestTypeCasting object at 0x7fdda001f250>

pdtestenv/lib64/python3.11/site-packages/pandas/tests/computation/test_eval.py:756:

...

>           ret = eng_inst.evaluate()

eng        = <class 'pandas.core.computation.engines.NumExprEngine'>
eng_inst   = <pandas.core.computation.engines.NumExprEngine object at 0x7fdd41459490>
engine     = 'numexpr'
env        = Scope(scope=['Timestamp',
 'datetime',
 'True',
 'False',
 'list',
 'tuple',
 'inf',
 'Inf',
 '__name__',
 '__doc__',
...t_set_inplace',
 'TestValidate',
 'self',
 'op',
 'dt',
 'left_right',
 'df',
 'left',
 'right',
 's']
, resolvers=[]
)
expr       = 'df / 3'
exprs      = ['df / 3']
first_expr = True
global_dict = None
inplace    = False
level      = 0
local_dict = None
multi_line = False
parsed_expr = (df) / (np.float64(3.0))
parser     = 'python'
resolvers  = ()
ret        = None
target     = None
target_modified = False

pdtestenv/lib64/python3.11/site-packages/pandas/core/computation/eval.py:357:

...

==================================================================================== short test summary info ======================================================================================
FAILED pdtestenv/lib64/python3.11/site-packages/pandas/tests/computation/test_eval.py::TestTypeCasting::test_binop_typecasting[numexpr-python-left_right0-float64-/] - ValueError: Expression (df) / (np.float64(3.0)) has forbidden control characters.
FAILED pdtestenv/lib64/python3.11/site-packages/pandas/tests/computation/test_eval.py::TestTypeCasting::test_binop_typecasting[numexpr-python-left_right1-float64-/] - ValueError: Expression (np.float64(3.0)) / (df) has forbidden control characters.
FAILED pdtestenv/lib64/python3.11/site-packages/pandas/tests/computation/test_eval.py::TestTypeCasting::test_binop_typecasting[numexpr-pandas-left_right0-float64-/] - ValueError: Expression (df) / (np.float64(3.0)) has forbidden control characters.
FAILED pdtestenv/lib64/python3.11/site-packages/pandas/tests/computation/test_eval.py::TestTypeCasting::test_binop_typecasting[numexpr-pandas-left_right1-float64-/] - ValueError: Expression (np.float64(3.0)) / (df) has forbidden control characters.
FAILED pdtestenv/lib64/python3.11/site-packages/pandas/tests/computation/test_eval.py::TestOperations::test_simple_arith_ops[numexpr-python] - ValueError: Expression (np.float64(1.0)) / (np.float64(1.0)) has forbidden control characters.
FAILED pdtestenv/lib64/python3.11/site-packages/pandas/tests/computation/test_eval.py::TestOperations::test_simple_arith_ops[numexpr-pandas] - ValueError: Expression (np.float64(1.0)) / (np.float64(1.0)) has forbidden control characters.
====================================================== 6 failed, 5432 passed, 62 skipped, 199038 deselected, 2 xpassed, 4 warnings in 32.69s =======================================================
```

### Expected Behavior

Passing test suite, proper string evaluation

### Installed Versions

<details>

```
INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.9.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.8.7-1-default
Version               : #1 SMP PREEMPT_DYNAMIC Thu Apr 18 07:12:38 UTC 2024 (5c0cf23)
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : de_DE.UTF-8
LOCALE                : de_DE.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.0rc1
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 65.5.0
pip                   : 24.0
Cython                : None
pytest                : 8.2.0
hypothesis            : 6.100.2
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : 2.10.0
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
```
</details>

### PR DESCRIPTION
**Pull request by bnavigator**
Backport #59144

* remove core.computation.ops.Div resolves #21374 #58748

* need to preserve order

* updating tests

* ~~update whatsnew~~ // no whatsnew for 2.2.x and 2.3 yet

* solve mypy issue

* fixing pytests

* better than cast

* adding specific test

* ~~Update pandas/tests/frame/test_query_eval.py~~ // Not backported, fails on 2.2

* Update pandas/tests/computation/test_eval.py

---------

- [x] closes #58548
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.  -- *no one found for 2.x*

### CODE REVIEW

**Comment by rhshadrach** [comment]
@WillAyd - 2.3.x should only have backports related to PDEP-14, is that right?

**Comment by bnavigator** [comment]
If that's your policy, be advised that the current stable release 2.2 is not and minor release updates of it will never fully work with Numpy 2

**Comment by WillAyd** [comment]
There's a few things not required for PDEP-14 that have made their way in just to get the test suite green, but mostly it is for PDEP-14.

We actually haven't started backporting anything yet to 2.3 - the first PR to do so an get that branch up to speed is https://github.com/pandas-dev/pandas/pull/59513

I'll take a look at this particular change as part of that

**Comment by rhshadrach** [comment]
Thanks @WillAyd - I wouldn't push for this PR to be backported to 2.3, but no objection either.

**Comment by WillAyd** [comment]
I've actually been wondering about a few of the errors on 2.3 (see https://github.com/pandas-dev/pandas/pull/59513#issuecomment-2305587191) and this appears to address some of them, so I _think_ it will be required (thanks @bnavigator for investigating!)

**Comment by jorisvandenbossche** [comment]
cc @lithomas1

**Comment by lithomas1** [comment]
I _think_ this fixes the failures, so going to merge on red.

thanks @bnavigator

**Comment by bnavigator** [comment]
AFAICT most of this has also been used in #59513 by @WillAyd, so now that this one has been merged into `2.2.x`, his PR into `2.3.x` will probably need adjustments as well. Plus `2.3.x` probably needs a forward

**Pull request merged**
