### PR TITLE
BUG: setitem with mixed-resolution dt64s

### LINKED ISSUE #56410: BUG/API: setitem/where with mixed dt64 units
```python
import pandas as pd

dti = pd.date_range("2016-01-01", periods=3, unit="s")
item = pd.Timestamp("2016-02-03 04:05:06.789")

ser = pd.Series(dti)

ser[0] = item
>>> assert ser[0] == item  # <- raises bc item is rounded

mask = [False, True, True]
res = ser.where(mask, item)
>>> assert res[0] == item  # <- raises bc item is rounded

ser2 = ser.copy()
ser2[0] = pd.NaT
res2 = ser2.fillna(item)
>>> assert res2[0] == item  # <- raises bc item is rounded
```

### Issue Description

The operations above all go through DatetimeArray._validate_setitem_value -> _validate_scalar -> _unbox_scalar.  _unbox_scalar does a `value.as_unit(self.unit)`, which uses the default `round_ok=True`, so casts the ms-unit `item` to s-unit, which truncates.  

(Something similar happens if we use a vector `vec = pd.date_range(item, periods=3, unit="ms")` instead of scalar `item`, but that also has other issues that I'll address later)

The apparent solution here is to do the as_unit casting in _validate_scalar, bug pass `round_ok=False`.  This fixes the cases above (the `__setitem__` case correctly issues a PDEP6 warning).  But it breaks test_resample_ohlc_result, test_resample_dst_anchor2, and test_clip_with_timestamps_and_oob_datetimes.

In the clip test, the change causes us to raise in EABackedBlock.where, fall back to coerce_to_target_dtype, which identifies `new_dtype` and `M8[ns]`, tries to cast, and raises OutOfBoundsDatetime.  There are a few non-crazy options here.  I lean toward doing a PDEP6-like deprecation for cases that go through this path (where, mask, clip, fillna).

The other cases are raising a KeyError on a DatetimeIndex.get_loc call when doing something like `ser.loc[:"4-15-2000"]`.  I need to look into this more closely, tentatively looks solvable.

---

Last I want to make sure I write down the really ugly bug in where/fillna if we use a vector:

```
vec = pd.date_range(item, periods=3, unit="ms")
mask = [False, True, True]

res = ser.where(mask, vec)
arr = res._values
>>> arr.dtype == arr._ndarray.dtype  # <- raises, yikes!
```

This goes though NDArrayBackedExtensionArray._where, which does `value = self._validate_setitem_value(value)` which fails to cast the unit of `vec`, so gets back `value` which is a `M8[ms]` ndarray instead of `M8[s]`.  We then pass it to np.where which gives back `res_values` with `M8[ms]` dtype, and then call _from_backing_data which assumes that `res_values.dtype == self._ndarray.dtype`.  That assumption is wrong in this case and we get a corrupted EA back.

I've got a branch addressing this, just want to make sure this is written down somewhere.

--- 

cc @MarcoGorelli to make sure we're in agreement that the cases above should not silently truncate.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #56410 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
what happens after this PR for the cases in https://github.com/pandas-dev/pandas/issues/56410 ? would they emit a warning now, and raise in the future?

**Comment by jbrockmendel** [comment]
> what happens after this PR for the cases in https://github.com/pandas-dev/pandas/issues/56410 ? would they emit a warning now, and raise in the future?

The `__setitem__` case issues a PDEP6 warning and will raise when that is enforced.  The .where and .fillna cases case to "M8[ms]".

**Comment by jbrockmendel** [comment]
@MarcoGorelli gentle ping

**Comment by jbrockmendel** [comment]
if there are no further comments, i plan to merge this next week

**Comment by MarcoGorelli** [comment]
sorry for the delay, will try to take a look tomorrow

**Comment by MarcoGorelli** [comment]
Sorry this has taken a while, just not sure about something

Isn't this going to risk causing overflows? E.g.
```python
ser = pd.Series(np.array(['NaT', '3000-01-01', '3000-01-02'], dtype='datetime64[s]'))

item = pd.Timestamp('2020-01-01T00:00:00.123456789')
print(ser.fillna(item))
```
This raises
```
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 3000-01-01 00:00:00
```

Checking the behaviour for nullable integers:
```
pd.Series([pd.NA, 2, 3], dtype='Int64').fillna(1.5)  # raises
pd.Series([pd.NA, 2, 3], dtype='Int64[pyarrow]').fillna(1.5)  # silently truncates 1.5 to 1
```

**Comment by jbrockmendel** [comment]
> Isn't this going to risk causing overflows? E.g.

Yes, and that is a good thing.  In the status quo we silently round that non-nano fill value and give an incorrect result.

The pyarrow example looks pretty clearly buggy to me.

**Comment by MarcoGorelli** [comment]
to be honest I'm not totally sure about this - I'm not going to block it, but don't really feel comfortable approving, could you ask someone else please?

**Comment by jbrockmendel** [comment]
@mroeschke @phofl thoughts?

**Comment by mroeschke** [comment]
I do find the overflow behavior a better behavior than silently truncating.

But I also find the exception message in @MarcoGorelli 's https://github.com/pandas-dev/pandas/pull/56419#issuecomment-2051569888 kinda opaque compared to setting a float into a nullable int (`TypeError: Invalid value '1.5' for dtype Int64`)

**Comment by mroeschke** [comment]
> How about f"Incompatible (high-resolution) value for {self.dtype}. Explicitly cast before operating."

Yeah I would be good with that

**Comment by jbrockmendel** [comment]
npdev failure looks unrelated

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
