### PR TITLE
BUG: NaN should have pct rank of NaN

### PR DESCRIPTION
**Pull request by gfyoung**
Backport of #22600.

### CODE REVIEW

**Comment by gfyoung** [comment]
@jreback @TomAugspurger : Looks like we need to backport #22601 and #21814 ?

**Comment by jreback** [comment]
@gfyoung yep those CI backport are needed 
can u PR?

**Comment by gfyoung** [comment]
@jreback : Yep, sounds good.

**Comment by gfyoung** [comment]
This is a clean backport, and with all tests now passing, going to merge this.

**Pull request merged**
