### PR TITLE
Docs formatting df join validate

### PR DESCRIPTION
**Pull request by sleepypioneer**
- [x] closes **https://github.com/noatamir/pyladies-hh23-sprint/issues/9** (however this issue is no longer available, this was a follow-up task for the bold first list item.
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

@noatamir @phofl PyLadies Hamburg Sprint

Very small updates for changing the formatting of these docs.

BEFORE:

Screenshot 2023-07-30 at 15 35 38

Remove the `.` between sort it and lexicographically on third list item.

AFTER:

Screenshot 2023-07-30 at 15 35 15

BEFORE:
Screenshot 2023-07-30 at 15 35 28

Make the first list item not bold.

AFTER: 

Screenshot 2023-07-30 at 15 35 21

### CODE REVIEW

**Comment by sleepypioneer** [comment]
Screen shots for changes:

Screenshot 2023-07-30 at 18 05 04

Screenshot 2023-07-30 at 18 06 25

**Comment by sleepypioneer** [comment]
Seems this failing test is failing also on the main branch.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @sleepypioneer

**Pull request merged**
