### PR TITLE
BUG: CoW not tracking references when indexing midx with slice

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I think https://github.com/pandas-dev/pandas/pull/51895 will (as a side affect) also fix this. But of course should merge at least the test anyway.

**Comment by phofl** [comment]
I guess we should merge this anyway since we'll backport CoW fixes?

**Comment by jorisvandenbossche** [comment]
Given that the other PR is fixing an annoying bug for geopandas, I was kind of planning to backport that as well (but yeah, the order of which gets merged first doesn't matter, fine to already merge and backport this)

**Comment by phofl** [comment]
Lets get this into the rc to be save

**Pull request merged**
