### PR TITLE
CI: Unpin Miniconda for CI

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/17696

xref https://github.com/pandas-dev/pandas/pull/17700

### CODE REVIEW

**Comment by jreback** [comment]
lgtm.

**Comment by TomAugspurger** [comment]
I may wait to see what's going on in https://github.com/conda-forge/pytables-feedstock/issues/19 before merging this.

**Comment by jreback** [comment]
@TomAugspurger yeah I think that the recipe for that is messed up. they claim its a zlbi thing, but not so sure.

**Comment by jreback** [comment]
I think this is fine (and the pytables issue is now fixed). merging.

**Comment by TomAugspurger** [comment]
Great, thanks.

**Pull request merged**
