### PR TITLE
Don't run GHA CI for Azure changes and vice-versa

### PR DESCRIPTION
**Pull request by jonashaag**
- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Review by simonjayhawkins — APPROVED** [review]
If I merge this to main now, autobackport will probably fail. 

but ndb if another maintainer wants to merge as we can ping meeseeksmachine again.

**Comment by jreback** [comment]
i don't like changes like this as it makes much harder to understand what is running

**Review by jreback — CHANGES_REQUESTED** [review]
see comments

**Comment by simonjayhawkins** [comment]
removing milestone for now.

**Comment by jonashaag** [comment]
We don't need this once we switch away from Azure

**Pull request closed without merging**
