### PR TITLE
DOC: warnings and remove HTML

### PR DESCRIPTION
**Pull request by TomAugspurger**
Couple comments in https://github.com/pydata/pandas/issues/11610#issuecomment-158411503
- warning in the whatsnew
- warning in the Styler docstring
- removes generated HTML version of the notebook, that's built as part of the doc build.

Building the docs now to double check, I'll merge  when those are good.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Looks good!

**Comment by jreback** [comment]
@jorisvandenbossche IIRC we have ``ipython`` as a requirement of the doc-builds, should also add ``ipython-notebook`` (or ``jupyter``)

**Comment by jorisvandenbossche** [comment]
in principle, it's not `ipython notebook`, but just ipython for <4 (nbconvert it included, so that is OK) or `nbconvert` for >= 4

**Comment by jorisvandenbossche** [comment]
But maybe safer to use `ipython nbconvert` instead of `jupyter nbcnvert` in make.py (as the first one works for all versions, the jupyter one only for the more recent)

**Comment by jorisvandenbossche** [comment]
@TomAugspurger did you also check the api docs for the new styler if they render work correctly?

**Comment by TomAugspurger** [comment]
Yep, the warning shows up there. I can upload the generated version somewhere if you want.

**Comment by TomAugspurger** [comment]
Ahh, shoot found one mistake.  I forgot to change `Styler.set` to `Styler.use` in `api.rst`. Is it easiest for you to change that?

**Comment by TomAugspurger** [comment]
This is line 1713 in the current version of master, not sure how to link to it since GH renders the rst. `   Styler.set` -> `   Styler.use`

**Comment by jorisvandenbossche** [comment]
no, you can go ahead and change it (I still have to switch from windows to linux for the final build)

**Pull request merged**
