### PR TITLE
DOC/CLN: Change API reference section title

### PR DESCRIPTION
**Pull request by simonjayhawkins**

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
i'm not sure whats best here, Indexes, Indices, Index Types, but Indexing is not appropriate.

**Comment by simonjayhawkins** [comment]
@WillAyd do you mean links to this page, or using the term Indexing to refer to index types?

i've left the name of the file unchanged (indexing.rst) so links shouldn't be affected, but the title is changed so that the Table of Contents makes more sense. Am i missing something? i've not done much on the docs before.

**Comment by WillAyd** [comment]
I mean any implicit hyperlink targets to the section, but looks like there's an explicit name anyway (`api.indexing`) so should be OK

**Review by WillAyd — APPROVED** [review]
This makes sense to me. @datapythonista if you want to take a look

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
