### PR TITLE
BUG: fix array conversion from Arrow for slided array

### LINKED ISSUE #38525: BUG: pyarrow_array_to_numpy_and_mask is not taking offset into account when creating mask
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
from pyarrow import Table

df = pd.DataFrame({'int_na': [0, None, 2, 3, None, 5, 6, None, 8]}, dtype=pd.Int64Dtype())
print(df)
```
```python
    int_na

0 0 
1 <NA>
 2 2 
3 3 
4 <NA>
 5 5 
6 6 
7 <NA> 
8 8
```
```python
Table.from_pandas(df).slice(2, None).to_pandas()
```
```python
  int_na
0 2
1 <NA>
2 1
3 5
4 <NA>
5 1
6 8
```

#### Problem description

The pandas array does not accurately reflect the pyarrow array.

#### Expected Output

```python
Table.from_pandas(df).slice(2, None).to_pandas()
```
```python
  int_na
0 2
1 3
2 <NA>
3 5
4 6
5 <NA>
6 8
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.9.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-58-generic
Version          : #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 49.6.0.post20201009
Cython           : 0.29.21
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0.dev391+g26aef88b5.d20201216
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes #38525

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jreback** [comment]
lgtm, needs a whatsnew note bug fix (ok for 1.2 or 1.3)

**Comment by jorisvandenbossche** [comment]
Yeah, I didn't yet add a whatsnew because we need to decide which version to target. Normally, plain bug fixes should go in 1.3 right now, but since this is actually causing a silent data corruption, it might be worth putting in 1.2

**Comment by jreback** [comment]
1.2 sounds good to me

**Comment by jreback** [comment]
thanks @jorisvandenbossche

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
