### PR TITLE
CI/DOC: Fix docbuild link warnings

### PR DESCRIPTION
**Pull request by mroeschke**
Showing up in recent builds

```
/home/runner/work/pandas/pandas/doc/source/user_guide/advanced.rst:1263: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/2388' could be replaced by an extlink (try using ':issue:`2388`' instead)
/home/runner/work/pandas/pandas/doc/source/user_guide/cookbook.rst:210: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/2904' could be replaced by an extlink (try using ':issue:`2904`' instead)
/home/runner/work/pandas/pandas/doc/source/user_guide/cookbook.rst:412: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/2995' could be replaced by an extlink (try using ':issue:`2995`' instead)
/home/runner/work/pandas/pandas/doc/source/user_guide/cookbook.rst:927: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/3791' could be replaced by an extlink (try using ':issue:`3791`' instead)
/home/runner/work/pandas/pandas/doc/source/user_guide/cookbook.rst:964: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/2996' could be replaced by an extlink (try using ':issue:`2996`' instead)
/home/runner/work/pandas/pandas/doc/source/user_guide/cookbook.rst:1087: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/2886' could be replaced by an extlink (try using ':issue:`2886`' instead)
/home/runner/work/pandas/pandas/doc/source/user_guide/cookbook.rst:1222: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/19842#issuecomment-892150745' could be replaced by an extlink (try using ':issue:`19842#issuecomment-892150745`' instead)
/home/runner/work/pandas/pandas/doc/source/user_guide/cookbook.rst:1243: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/3032' could be replaced by an extlink (try using ':issue:`3032`' instead)
/home/runner/work/pandas/pandas/doc/source/whatsnew/v0.17.1.rst:52: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/11610' could be replaced by an extlink (try using ':issue:`11610`' instead)
```

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Looks like a few more?

```
/home/runner/work/pandas/pandas/doc/source/development/contributing_codebase.rst:504: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/wiki/Testing' could be replaced by an extlink (try using ':wiki:`Testing`' instead)
/home/runner/work/pandas/pandas/doc/source/development/roadmap.rst:77: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/28095' could be replaced by an extlink (try using ':issue:`28095`' instead)
/home/runner/work/pandas/pandas/doc/source/development/roadmap.rst:131: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/wiki/(Tentative)-rules-for-restructuring-indexing-code' could be replaced by an extlink (try using ':wiki:`(Tentative)-rules-for-restructuring-indexing-code`' instead)
/home/runner/work/pandas/pandas/doc/source/ecosystem.rst:603: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/14468' could be replaced by an extlink (try using ':issue:`14468`' instead)
/home/runner/work/pandas/pandas/doc/source/ecosystem.rst:603: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/26766' could be replaced by an extlink (try using ':issue:`26766`' instead)
/home/runner/work/pandas/pandas/doc/source/ecosystem.rst:603: WARNING: hardcoded link 'https://github.com/pandas-dev/pandas/issues/28142' could be replaced by an extlink (try using ':issue:`28142`' instead)
```

**Comment by jreback** [comment]
hmm do we need to backport this? (i am going to say yes but i think we might need a different PR for 1.4) as we don't have all doc patches backported

**Comment by mroeschke** [comment]
Yeah probably needs backporting to 1.4.

Sphinx just released 4.4.0 and this feature triggered this warning https://github.com/sphinx-doc/sphinx/pull/9800

**Comment by mroeschke** [comment]
We could also pin sphinx <4.4.0 on the 1.4 branch but not sure if that's a messier change.

**Comment by jreback** [comment]
> We could also pin sphinx <4.4.0 on the 1.4 branch but not sure if that's a messier change.
i think that would be ok for 1.4 (whatever is easier)

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by jreback** [comment]
@mroeschke do what you can for the 1.4 branch (pin is ok)

**Comment by mroeschke** [comment]
@jreback just did a manual one at https://github.com/pandas-dev/pandas/pull/45458

**Pull request merged**
