### PR TITLE
Use DeprecationWarning instead of FutureWarning for is_.._dtype deprecations

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/pandas-dev/pandas/issues/54970

Those kind of helpers functions are, I think, for a large part used by other libraries, and to a lesser extent by direct user code. For that kind of deprecations, we first start with a DeprecationWarning, so it's not visible for the end-user (like users of seaborn got a flood of warnings before their latest release). 

Of course, changing it now might also give some churn in case some other projects already added some code to suppress them, but I think it's still useful to do now (many people have not yet upgraded to 2.1).

### CODE REVIEW

**Comment by rhshadrach** [comment]
> Of course, changing it now might also give some churn in case some other projects already added some code to suppress them, but I think it's still useful to do now (many people have not yet upgraded to 2.1).

People may have not upgraded, but downstream packages? If a package is dependent on pandas I would imagine it is likely to become "2.1-compliant" faster than end users. Though hopefully packages are not handling warnings by suppressing them :laughing: If they are though, and they are suppressing the FutureWarning, they will have to change it to a DeprecationWarning, then back to FutureWarning (assuming they haven't addressed it).

I'm on the fence here.

**Comment by jorisvandenbossche** [comment]
> People may have not upgraded, but downstream packages? If a package is dependent on pandas I would imagine it is likely to become "2.1-compliant" faster than end users.

Taking the example of seaborn, which is a well maintained package, that only had a release fixing this a few weeks after the pandas release. And I expect there to be many packages that are slower than the seaborn maintainer (note that it is not enough to fix this but also to release).

**Comment by jorisvandenbossche** [comment]
And indeed, if they addressed the warning, they either fixed it (and this PR won't change anything for them), or either they suppressed it temporarily, and then they will see the warning again (requiring them to suppress it temporarily again, or prompt them to actually fix it)

**Comment by rhshadrach** [comment]
I'm good with changing to a DeprecationWarning, but would like to get thoughts from those who originally deprecated. cc @jbrockmendel @phofl @mroeschke

**Comment by jbrockmendel** [comment]
fine by me

**Review by rhshadrach — APPROVED** [review]
lgtm

**Review by rhshadrach — CHANGES_REQUESTED** [review]
This failure looks related. https://github.com/pandas-dev/pandas/actions/runs/6653673736/job/18080148037?pr=55703#step:8:107

**Review by mroeschke — APPROVED** [review]
LGTM. Merge when ready @rhshadrach

**Review by rhshadrach — APPROVED** [review]

**Comment by rhshadrach** [comment]
Thanks @jorisvandenbossche

**Pull request merged**
