### PR TITLE
CI: Set max job limit for test runs

### PR DESCRIPTION
**Pull request by mroeschke**
xref https://github.com/pandas-dev/pandas/pull/45946

If a test run goes beyond 1.5/2 hours, I think it's safe to assume that the test run had an issue. (Since GHA will run for 6 hours, better to short circuit at 2 hours)

### CODE REVIEW

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by jreback** [comment]
@mroeschke if you would'nt mind putting the manual backport up

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.4.x

**Comment by simonjayhawkins** [comment]
ah yes. I missed that since I was working from the milestone tasks and didn't check open pull requests. can close either.

(on the manual ones add the PR number in the description so that a link is created. and the milestone too)

**Pull request merged**
