### PR TITLE
CLN: Remove unused functions

### PR DESCRIPTION
**Pull request by tqa236**
It's pretty hard to be 100% sure that these non-private functions are unused, but I'm pretty sure that they are not commonly used, if at all, after some searches in Google, GitHub, and pandas doc.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]
Thanks! These directories are documented as "private" so they are OK to remove.

**Comment by mroeschke** [comment]
Keep them coming! @tqa236

**Comment by tqa236** [comment]
@mroeschke thanks! I'm combing through `vulture` to see what can be removed. May I know where the documentation about the private directories is, please? It'll surely help me decide if a report is a true or false positive

**Comment by mroeschke** [comment]
> May I know where the documentation about the private directories is, please?

https://pandas.pydata.org/docs/reference/index.html#api-reference

**Comment by tqa236** [comment]
Thank you!

**Pull request merged**
