### PR TITLE
CLN: simplify _setitem_with_indexer

### PR DESCRIPTION
**Pull request by jbrockmendel**
The MultiIndex check it is doing is unnecessary for positional indexing.

Other things being cleaned up here appear to be remnants from Panel

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Now you have been working with `_setitem_with_indexer`, could you add a docstring for it explaining what the scope of this function is (eg only used for positional indexing?)

**Comment by jbrockmendel** [comment]
> could you add a docstring for it explaining what the scope of this function is (

good idea

**Comment by jbrockmendel** [comment]
im of mixed mind on adding a docstring at the moment, because there is a big gap between what the method does vs what it is supposed to do.

**Comment by jorisvandenbossche** [comment]
Even trying to write down a bit what you know about what it is supposed to do and what it actually does (what led you to previous comment) is useful IMO; it doesn't need to be a perfectly standard formatted docstring

**Comment by jreback** [comment]
lgtm needs a rebase

**Comment by jbrockmendel** [comment]
rebased+green

**Comment by jbrockmendel** [comment]
@jorisvandenbossche gentle ping

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
