### PR TITLE
CI: troubleshoot openpyxl failures

### PR DESCRIPTION
**Pull request by jbrockmendel**
tested on OSX 36 and 37, we'll see if that generalizes

### CODE REVIEW

**Comment by WillAyd** [comment]
@jorisvandenbossche I think noticed this last week

**Comment by MomIsBestFriend** [comment]
> @jorisvandenbossche I think noticed this last week

Right [here (comment)](https://github.com/pandas-dev/pandas/pull/29862#issuecomment-559013181).

**Comment by jbrockmendel** [comment]
is there a better workaround someone has in mind to get the CI back to green?

**Comment by jbrockmendel** [comment]
@TomAugspurger gentle ping

**Comment by jreback** [comment]
thanks @jbrockmendel happy to keep Ci green
keep an eye open for when can revert

**Comment by alimcmaster1** [comment]
Might be awhile according to openpyxl devs:

https://bitbucket.org/openpyxl/openpyxl/issues/1373/broken-writer-with-lxml-defusedxml

**Pull request merged**
