### PR TITLE
TST/CLN: deduplicate fixture from test_to_latex.py

### PR DESCRIPTION
**Pull request by simonjayhawkins**
this PR is basically just to promote the float_frame fixture to top-level conftest.

once there, there is opportunities to re-use by fixturising current instances of 

```
df = DataFrame(tm.getSeriesData())
```

also allows removing duplicate fixture from pandas/tests/io/formats/test_to_latex.py

so this is just a move for now, fixturization in follow-on PRs

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. CI failing on doc build, so will merge after that is disabled.

**Comment by jreback** [comment]
i think i accidentally cancellled this one
can u merge master and ping on green

**Comment by simonjayhawkins** [comment]
@jreback all green

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @simonjayhawkins

**Pull request merged**
