### PR TITLE
BUG: fix Panel.fillna() ignoring axis parameter

### LINKED ISSUE #8251: Panel.fillna with method='ffill' ignores the axis parameter and only fills along axis=1
This is also a documentation error, as the docs say the default axis is axis = 0

```
import pandas as pd
from pandas.util.testing import makePanel

#
# Demo A: We want to fill along axis 0
# 
p = makePanel().transpose(1,0,2)
p.iloc[10:20,0,0] = np.nan

# Demonstrate we have a gap
p.iloc[:,0,0].plot()

# Demonstrate that nothing seems to fill the gap
p.fillna(method='ffill').iloc[:,0,0].plot()
p.fillna(method='ffill', axis=0).iloc[:,0,0].plot()
p.fillna(method='ffill', axis=1).iloc[:,0,0].plot()
p.fillna(method='ffill', axis=2).iloc[:,0,0].plot()

# At least one of the above should be the same as:
p.apply(lambda series: series.fillna(method='ffill'), axis=0).iloc[:,0,0].plot()

#
# Demo B: We want to fill along axis 1
#
p = makePanel()
p.iloc[0, 10:20,0] = np.nan

# Demonstrate we have a gap
p.iloc[0,:,0].plot()

# Demonstrate the gap is filled regardless of the axis
p.fillna(method='ffill').iloc[0,:,0].plot()
p.fillna(method='ffill', axis=0).iloc[0,:,0].plot()
p.fillna(method='ffill', axis=1).iloc[0,:,0].plot()
p.fillna(method='ffill', axis=2).iloc[0,:,0].plot()
```

### PR DESCRIPTION
**Pull request by stahlous**
This fixes #8251. It may need some more comprehensive tests but before I go too much farther I want to make sure the axis numbering scheme makes sense . The default behavior of `fillna` is to fill along `axis=0`. In the case of a DataFrame this fills along the columns. However, in the case of a Panel, filling along `axis=0` means you're filling along items. I'm not sure if that's the behavior that most users would think is the default. You might note that I also removed the references to what the behavior of each axis value is in the docstring since it gets a bit arbitrary when you consider both DataFrames and Panels.

### CODE REVIEW

**Comment by jreback** [comment]
@stahlous can you rebase / revisit?

**Comment by jreback** [comment]
pls rebase/update. closing, but reopen if you want to work on.

**Comment by stahlous** [comment]
Revisiting this after an extended hiatus. Do I need to submit another pull request, or can this one be re-opened?

**Comment by jreback** [comment]
no, you can just push to this one

**Comment by stahlous** [comment]
I pushed to the `fillna_bug` branch of my fork, but it doesn't seem to have any effect here. I still only see the old commits in this PR.

Also, I'm having an odd problem with Travis. Anywhere that `LooseVersion()` is used I get an error. For example:

    ======================================================================
    ERROR: test_deprecated_levels (pandas.tests.test_categorical.TestCategorical)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/stahlous/pandas/pandas/tests/test_categorical.py", line 1261, in test_deprecated_levels
        self.assertFalse(LooseVersion(pd.__version__) >= '0.18')
      File "/home/travis/miniconda/envs/pandas/lib/python3.5/distutils/version.py", line 70, in __ge__
        c = self._cmp(other)
      File "/home/travis/miniconda/envs/pandas/lib/python3.5/distutils/version.py", line 337, in _cmp
        if self.version < other.version:
    TypeError: unorderable types: str() < int()

It's like `LooseVersion()` has lost its mind on the Travis machine. I can't reproduce the problem on my machine and the tests pass without a problem. Have you seen anything like this?

**Comment by jreback** [comment]
you need to rebase on master

**Pull request closed without merging**
