### PR TITLE
STY: Replace .format() to fstrings and %r to repr()

### PR DESCRIPTION
**Pull request by EydenVillanueva**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

#29886

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Some test failures, e.g. 

```pytb
self = <pandas.tests.test_nanops.TestEnsureNumeric object at 0x14d026208>

    def test_non_convertable_values(self):
        msg = "Could not convert foo to numeric"
        with pytest.raises(TypeError, match=msg):
>           nanops._ensure_numeric("foo")
E           AssertionError: Pattern 'Could not convert foo to numeric' not found in "Could not convert 'foo' to numeric"

```

Can you check on those?

**Comment by EydenVillanueva** [comment]
> Some test failures, e.g.
> 
> ```
> self = <pandas.tests.test_nanops.TestEnsureNumeric object at 0x14d026208>
> 
>     def test_non_convertable_values(self):
>         msg = "Could not convert foo to numeric"
>         with pytest.raises(TypeError, match=msg):
> >           nanops._ensure_numeric("foo")
> E           AssertionError: Pattern 'Could not convert foo to numeric' not found in "Could not convert 'foo' to numeric"
> ```
> 
> Can you check on those?

Sure.

**Comment by WillAyd** [comment]
@EydenVillanueva I think a mistake on merging here. Can you rollback to your change, merge master and re-push? Shouldn't need to force push if you go that route

**Comment by EydenVillanueva** [comment]
> @EydenVillanueva I think a mistake on merging here. Can you rollback to your change, merge master and re-push? Shouldn't need to force push if you go that route

Hi, something went wrong not sure why, to clean up a little bit I'll close this PR, and make another one without all this mess, haha thank you.

**Pull request closed without merging**
