### PR TITLE
DOC: create shared includes for comparison docs, take II

### PR DESCRIPTION
**Pull request by afeld**
This is a duplicate of https://github.com/pandas-dev/pandas/pull/38771, but instead of defining `:tips:` in a `:suppress:` block, it attempts to tell flake8-rst to ignore those warnings. In other words, only one of these pull requests should be merged; the other can be closed.

- [ ] ~~closes #xxxx~~
- [ ] tests added / passed
- [ ] ~~passes `black pandas`~~
- [ ] ~~passes `git diff upstream/master -u -- "*.py" | flake8 --diff`~~
- [ ] ~~whatsnew entry~~

### CODE REVIEW

**Comment by jreback** [comment]
great. let's see how the ci does.

**Comment by afeld** [comment]
As [expected](https://github.com/pandas-dev/pandas/pull/38771#issuecomment-751955518), it's getting `F821 undefined name 'tips'` in all those include files that reference that variable. Very possible I just don't know what I'm doing and missed some part of the configuration.

**Comment by jorisvandenbossche** [comment]
The doc build is failing because flake8-rst is not installed in that env:

```
Could not import extension flake8_rst.sphinxext.custom_roles (exception: No module named 'flake8_rst')
```

Now, for the pre-commit check, that indeed fails. 
For me locally, I get the same failure. If I do `:flake8-group: Ignore` (which ignores the block completely), then it doesn't complain. 

Short term, I would maybe just add those `*/includes/*` files to the exclude list of flake8-rst:

https://github.com/pandas-dev/pandas/blob/72ad7178cc584e2048bc26e773249fb9579e6ca0/setup.cfg#L51-L52

And then I would open an issue at https://github.com/kataev/flake8-rst reporting that the `:flake8-add-ignore: F821` is not working for this example (it might be a bug in the package).

**Comment by afeld** [comment]
> I would maybe just add those */includes/* files to the exclude list of flake8-rst

Done: https://github.com/pandas-dev/pandas/pull/38887 (Sorry for the litany of pull requests; just wanted to make sure the different approaches can be seen independently.)

> I would open an issue at https://github.com/kataev/flake8-rst reporting that the `:flake8-add-ignore: F821` is not working for this example

Done: https://github.com/kataev/flake8-rst/issues/25

**Comment by jreback** [comment]
#38887 is before this? should this close?

**Comment by afeld** [comment]
Closing in favor of https://github.com/pandas-dev/pandas/pull/38887.

**Pull request closed without merging**
