### PR TITLE
Accessor registry

### LINKED ISSUE #19963: Classes should maintain a registry of accessors
Dask would like to inherit the accessors registered by `register_*_acessor`. This would be much easier if the `regiser_*_accessor` methods added the name of the accessor to a (private) class variable.

It seems like we have use of it in pandas as well: https://github.com/pandas-dev/pandas/pull/19960/files#r171815351

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes #19963 

cc @datapythonista I think this would have solved your issues w/ the validation script.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Do we want to document this as the official way to get a list of the registered accessors for an object?

**Comment by jreback** [comment]
lgtm. ok to update docs / merge.

**Comment by jorisvandenbossche** [comment]
> Do we want to document this as the official way to get a list of the registered accessors for an object?

Do you want to use this in eg Dask? 
If so, then maybe we should document that.

**Comment by TomAugspurger** [comment]
I think the current preference is for authors to explicitly register their
accessors with Dask as well.

Let's leave it private for now, and if people need it later on we will
document it.

**Pull request merged**
