### PR TITLE
Add type to arg of series/drop-duplicates

### PR DESCRIPTION
**Pull request by olgarithms**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

I noticed in https://github.com/pandas-dev/pandas/pull/40867 that keep didn't specify a type, so adding it here.

### CODE REVIEW

**Comment by olgarithms** [comment]
@MarcoGorelli if you can have a look, I don't think I can assign the PR :)

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Nice, thanks @olgarithms !

Can we be more precise? How about
```python
keep: Literal['first', 'last', False]
```
where `Literal` will have to be imported as
```python
if TYPE_CHECKING:
    from typing import Literal
```
(because it's not available in py37)

**Comment by jreback** [comment]
> Nice, thanks @olgarithms !
> 
> Can we be more precise? How about
> 
> ```python
> keep: Literal['first', 'last', False]
> ```
> 
> where `Literal` will have to be imported as
> 
> ```python
> if TYPE_CHECKING:
>     from typing import Literal
> ```
> 
> (because it's not available in py37)

you can define this in pandas._typing as we use keep in a number of places

**Comment by simonjayhawkins** [comment]
@olgarithms can you address comments

**Comment by olgarithms** [comment]
Hi, yes! I am going to work on it this weekend!

**Comment by simonjayhawkins** [comment]
@olgarithms closing to clear queue. ping if you would like to continue working in this, and i'll reopen.

**Pull request closed without merging**
