### PR TITLE
SAS7BDAT parser: Improve subheader lookup performance

### PR DESCRIPTION
**Pull request by jonashaag**
Avoid constructing `_SubheaderPointer` objects and make dictionary lookups in C rather than in Python.

Speedup relative to current `main`:

```
     <main>           <sas/shlookup~1>
-     8.32±0.07ms      7.51±0.06ms     0.90  io.sas.SAS.time_test_meta2_pagesas7bdat
-      82.8±0.5ms       73.6±0.5ms     0.89  io.sas.SAS.time_read_sas7bdat_2_chunked
       before           after         ratio
```

Will extend what's new from https://github.com/pandas-dev/pandas/pull/47404 once that's merged.

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jonashaag** [comment]
@mroeschke any pointers for the failing test (see comment above)?

**Comment by mroeschke** [comment]
Sorry, I'm not too familiar with this part of the codebase. It looks like it's using the shared file handling code, but not sure if the one of the sas is still keeping a reference to the file handle somewhere?

**Comment by jonashaag** [comment]
Bug in `file_leak_context`, see #30096.

**Comment by jonashaag** [comment]
@mroeschke tests fixed, should be good to review now.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jonashaag

**Pull request merged**
