### PR TITLE
DOC: fix slashes in read_csv line_terminator/sep kwargs descriptions

### LINKED ISSUE #13738: Too many backslashes stripped in documentation generation
I've noticed the generated documentation for [to_csv](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html) strips backslashes in the newline character

> line_terminator : string, default ‘n’

I thought it was a case of slash stripping, but I checked [the code](https://github.com/pydata/pandas/blob/master/pandas/core/frame.py#L1346) and it's double backslashed there - so the doc generation is a bit aggressive. The [IO doc](http://pandas.pydata.org/pandas-docs/stable/io.html#writing-to-csv-format) is fine, [its code](https://github.com/pydata/pandas/blob/master/doc/source/io.rst) is the same - double backslashed.

### PR DESCRIPTION
**Pull request by shawnheide**
- [x] closes #13738
- [ ] tests added / passed
- [ ] passes `git diff upstream/master | flake8 --diff`
- [ ] whatsnew entry

Added additional '\' characters in order to produce the correct format in the documentation.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@shawnheide Could you try if using raw strings works as well? Because that way it would maybe be possible to have it look good in both the plain text docstring as the online html one.

**Comment by shawnheide** [comment]
@jorisvandenbossche I hadn't thought about the docstrings before, still learning I guess. It looks like the build failed under 2.7 for some reason as well. I tried with raw docstrings and the Sphinx still converted them. 

My last attempt was to use the raw docstrings and enclose the special characters ("/s+", etc.) in double back ticks, which keeps Sphinx from interpreting them. This works for the docs, but then the docstrings show the back ticks (see attached images). I searched the codebase for other examples of special characters in both the docstrings and documentation but couldn't find any. Anyone have any other ideas?

Docs: 
screen shot 2016-07-24 at 11 34 25 am

Docstring:
screen shot 2016-07-24 at 11 35 47 am

**Comment by jorisvandenbossche** [comment]
And when using raw string, but without the backticks, sphinx does still interprete the backslash? 
If that is the case, I think this is the best solution possible (it looks good in html, and better in the docstring compared to the double backslashes

The travis failure is because we have a linter for one of the 2.7 builds. If you look at the log of the failing build, down below, there is the output of the linter:

pandas/io/parsers.py:282:80: E501 line too long (80 > 79 characters)

**Comment by shawnheide** [comment]
Yes, with raw string it still interprets backslash characters, so the docs look the same as they currently do now. I found the warning box on this [page](http://openalea.gforge.inria.fr/doc/openalea/doc/_build/html/source/sphinx/rest_syntax.html#text-syntax-bold-italic-verbatim-and-special-characters) helpful in understanding what's going on with Sphinx. 

Thanks for explaining the build failure. I looked at the details, but must have missed seeing that explanation. I'll make sure my next commit keeps the code at less than 80 characters long. 

Just to clarify, you're saying to use the version I posted images for with the raw docstrings and the backticks correct?

**Comment by jorisvandenbossche** [comment]
> Just to clarify, you're saying to use the version I posted images for with the raw docstrings and the backticks correct?

Yes, those look good!

> Yes, with raw string it still interprets backslash characters, so the docs look the same as they currently do now. I found the warning box on this page helpful in understanding what's going on with Sphinx. 

My interpretation is that the raw string ensures that sphinx sees the backslash, but that sphinx also uses the backslash itself to escape characters it uses (eg `*` for bold), so in this way to show a backslash in sphinx, you still need two of them in the raw string (or four in the python string), or put it in a literal code block, like you proposed now.

**Comment by jorisvandenbossche** [comment]
@shawnheide Thanks a lot!

**Comment by jorisvandenbossche** [comment]
@shawnheide Really nice to have some doc contributions!

**Pull request merged**
