### PR TITLE
Added padding and fixed columns for sponsor logos in mobile view

### LINKED ISSUE #48519: WEB: Fix sponsor logos in mobile
The sponsor logos look pretty bad in mobile. CZI and Two sigma are significantly smaller than the others, and some padding would help see the logos better.

And it could probably look better if there were two logos per column, instead of just one (we're using bootstrap, that should be quite quick to implement).

pandas_sponsors

### PR DESCRIPTION
**Pull request by amay-patel**
Added padding and fixed columns for sponsor logos in mobile view

- [ ] closes #48519  (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks for the work on this @amay-patel. Do you mind uploading screenshots on how these changes look in both mobile and desktop please? This way reviewers can provide feedback not only in the code changes, but in the final result. Thanks!

**Comment by amay-patel** [comment]
Hi datapythonista! I put a screenshot of what the website looks like on my localhost:8000 with a regular computer view and a mobile view

Screen Shot 2022-09-28 at 4 46 10 PM
Screen Shot 2022-09-28 at 4 47 00 PM

**Review by datapythonista — APPROVED** [review]
Thanks @amay-patel. Not sure if we could make them look even better, in desktop the alignment and the spacing among rows looks a bit strange to me. But this seems like a clear improvement to what we've got, so happy to get this merged.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Awesome! Thanks @amay-patel

**Pull request merged**
