### PR TITLE
DOC: attempt to fix contributors for 0.24.0, 0.25.0/1/2

### PR DESCRIPTION
**Pull request by jgehrcke**
This hopefully addresses https://github.com/pandas-dev/pandas/issues/29151, please review!

CC @TomAugspurger @jreback

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. can you have a look at the other whatsnew for the same issue?

**Comment by TomAugspurger** [comment]
Looks like there are a few

```
doc/source/whatsnew/v0.24.0.rst:1936:.. contributors:: v0.23.4..HEAD
doc/source/whatsnew/v0.25.1.rst:119:.. contributors:: v0.25.0..HEAD
doc/source/whatsnew/v0.25.0.rst:1270:.. contributors:: v0.24.x..HEAD
doc/source/whatsnew/v0.25.2.rst:49:.. contributors:: v0.25.1..HEAD
```

I think all of those can be updated.

**Comment by jgehrcke** [comment]
Okay, the `.x` technique only works with branches i.e. w/o the `v` prefix, and even then the underlying git command might fail with

```
$ git shortlog -s 0.24.x..v0.25.0
fatal: ambiguous argument '0.24.x..v0.25.0': unknown revision or path not in the working tree.
```

Not sure how the repo is cloned / checked out in the environment used for building documentation. But in my clone of the repo I need to do
```
$ git shortlog -s remotes/origin/0.24.x..v0.25.0
```
to make this technique work.

**Review by TomAugspurger — APPROVED** [review]
You may need `git fetch upstream --tags` locally to test that.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
