### PR TITLE
Unpin xarray

### PR DESCRIPTION
**Pull request by djgray780**
- [X] closes [#42716](https://github.com/pandas-dev/pandas/issues/42716) 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
looks like this is breaking a doctest example
```
FAILED pandas/core/generic.py::pandas.core.generic.NDFrame.to_xarray
```
https://github.com/pandas-dev/pandas/runs/6429906335?check_suite_focus=true

**Comment by simonjayhawkins** [comment]
> looks like this is breaking a doctest example

xref https://github.com/pandas-dev/pandas/issues/42716#issuecomment-886271371 for the doctest issue (the mypy part seems fine now)

**Comment by djgray780** [comment]
It seems that the CircleCI: test-arm is not passing. Upon inspecting the error, it seems there might be a [numpy dependency missing](https://app.circleci.com/pipelines/github/pandas-dev/pandas/11048/workflows/10dc60d8-ff99-407f-8f7d-ee5d065df965/jobs/41887?invite=true#step-102-1166). Any thoughts or hints on how best to proceed to get that passing?

**Review by MarcoGorelli — APPROVED** [review]
Nice, thanks

The test-arm failure looks unrelated, might be worth fetching and merging upstream/main when it's fixed to check

**Pull request merged**
