### PR TITLE
CI: Format rst code blocks with blacken-docs

### LINKED ISSUE #46865: STYLE replace flake8-rst with something maintained
Currently, we use flake8-rst for running flake8 in code snippets in rst files:

https://github.com/pandas-dev/pandas/blob/2e56a838cf5ed3058df16c11e5ebae862520bab7/.pre-commit-config.yaml#L95-L102

However, flake8-rst isn't maintained, and is currently run in its own environment with a different flake8 version because of incompatibilities with flake8 v4

Task here is:
- search around to see if there's a maintained tool which does the same thing (runs flake8 on code snippets in rst files)
- try using that instead, fixup any new errors which may result from running it via `pre-commit` on all files
- make a PR

### PR DESCRIPTION
**Pull request by tqa236**
- [ ] closes #46865
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by datapythonista** [comment]
What's the plan with this @tqa236? Are the problems in the CI a blocker to move forward with this?

**Comment by tqa236** [comment]
hi @datapythonista, this problem is not related to the recent broken CI, although the broken CI indeed doesn't help testing or exploring.

The exact issue that prevents us from having a green CI is just the number of new lines in some code blocks in the doc where `black` enforces the new lines but `ipython` raises a warning there, which are treated as errors per our configuration. This warning doesn't affect the build, as the rendered doc still looks correct.

The approach I'm exploring now is a way to disable this warning by passing `ipython_warning_is_error=False` to silent this warning while still keeping other `sphinx` warning. 

I raised the issue [here](https://github.com/ipython/ipython/issues/14333) and [here](https://github.com/ipython/ipython/issues/14334) as well, but any quick change seems unlikely.

If you can point me to where I can pass `jupyter` or `sphinx` config to the build, it would be a great help.

**Comment by datapythonista** [comment]
Thanks for the update @tqa236.

I can't find the warnings in the doc build, are they still happening?

Configuration changes should be placed in `doc/source/conf.py`, I see an `nbsphinx` option to control the warnings: https://nbsphinx.readthedocs.io/en/0.9.3/configuration.html#suppress_warnings

I don't fully understand why ipython/nbsphinx should complain about blank lines, they shouldn't validate the style or format that I know, just execute the code. I can have a look if you can point me to the warnings that are making the CI fail, I only see an error I think I saw in other PRs about the section underlines.

CC @MarcoGorelli in case you have any opinion here.

**Comment by tqa236** [comment]
closed as I don't know how to proceed yet.

**Pull request closed without merging**
