### PR TITLE
TST: Making use of tm.external_error_raised

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

After #31130 got merged, I can do what I couldn't do [here](https://github.com/pandas-dev/pandas/pull/30998#discussion_r368177775)

### CODE REVIEW

**Comment by WillAyd** [comment]
I think this is confusing to say `external_error_raised` for something in internals

**Comment by WillAyd** [comment]
Can you alternately not just add the message?

**Comment by MomIsBestFriend** [comment]
> I think this is confusing to say `external_error_raised` for something in internals

@WillAyd I am with you on that, still it's raising an external error message, do you suggest moving it to somewhere else?

**Comment by MomIsBestFriend** [comment]
> Can you alternately not just add the message?

@WillAyd I really prefer not to, in #30999 we are fixing all the bare ```pytest raises```, and in order to silent the test case in #30755 we have to pass in the "match" argument, we could just pass in the ```match=None``` but as you said [here](https://github.com/pandas-dev/pandas/pull/30998#discussion_r368177775) this is not very clear.

**Comment by WillAyd** [comment]
I don't have a problem with `match=None` per se - where you linked my comment I was just asking what the purpose of it was

As mentioned I don't think this adds any value and if anything is confusing, but let's see what others think

**Comment by WillAyd** [comment]
Closing as I don't think this is moving in the right direction, but thanks in any case @MomIsBestFriend !

**Pull request closed without merging**
