### PR TITLE
CI Failing: TestReadHtml.test_spam_url #28708

### LINKED ISSUE #28708: CI Failing: TestReadHtml.test_spam_url
http://ndb.nal.usda.gov/ndb/foods/show/300772?fg=&man=&lfacet=&format=&count=&max=25&offset=&sort=&qlookup=spam

image

### PR DESCRIPTION
**Pull request by ladyyvii**
- [x] closes #28708 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] fixed test_spam_url test by changing a url address to the same html page stored in the pandas github repo

### CODE REVIEW

**Comment by jreback** [comment]
lgtm merge on green.

**Comment by jreback** [comment]
is this a new failure? https://travis-ci.org/pandas-dev/pandas/jobs/591987317
@jorisvandenbossche @simonjayhawkins 
```
_______________ TestReadHtml.test_thousands_macau_index_col[bs4] _______________
[gw0] linux -- Python 3.6.9 /home/travis/miniconda3/envs/pandas-dev/bin/python
self = <pandas.tests.io.test_html.TestReadHtml object at 0x7fa2b70d77f0>
datapath = <function datapath.<locals>.deco at 0x7fa2bbdc30d0>
    @pytest.mark.slow
    def test_thousands_macau_index_col(self, datapath):
        all_non_nan_table_index = -2
        macau_data = datapath("io", "data", "macau.html")
>       dfs = self.read_html(macau_data, index_col=0, header=0)
pandas/tests/io/test_html.py:390: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/io/html.py:1103: in read_html
    displayed_only=displayed_only,
pandas/io/html.py:919: in _parse
    raise_with_traceback(retained)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
exc = AttributeError("'NoneType' object has no attribute 'items'",)
traceback = None
    def raise_with_traceback(exc, traceback=Ellipsis):
        """
        Raise exception with existing traceback.
        If traceback is not passed, uses sys.exc_info() to get traceback.
        """
        if traceback == Ellipsis:
            _, _, traceback = sys.exc_info()
>       raise exc.with_traceback(traceback)
E       AttributeError: 'NoneType' object has no attribute 'items'
pandas/compat/__init__.py:47: AttributeError
```

**Comment by jorisvandenbossche** [comment]
Thanks @ladyyvii !

@jreback no, that is already failing on master as well.

**Comment by jorisvandenbossche** [comment]
@MeeseeksDev backport 0.25.x

**Comment by simonjayhawkins** [comment]
> is this a new failure? https://travis-ci.org/pandas-dev/pandas/jobs/591987317

see #28125, tests pass with beautifulsoup4 4.7.1, fails with 4.8.0.

**Comment by ladyyvii** [comment]
thanks, guys! It was my first PR to open source :-)

**Comment by jorisvandenbossche** [comment]
> thanks, guys! It was my first PR to open source :-)

And already more PRs open I see ! ;)

**Pull request merged**
