### PR TITLE
Documentation: Indexing and selecting data¶

### LINKED ISSUE #41629: QST: difference using ['column'] or .column?
Hi All,

I was wondering if you have any guidelines as to when it is possible to just go for df.column instead of df['column'], as I prefer the former for code styling, but I recall it gave me some issues before. I'm not sure I understand the specific difference between one and the other, is there any?

For now, what I do is only use ['column'] when declaring a new column and then always go for .column.

Thank you,
Iván.

### PR DESCRIPTION
**Pull request by rbrishabh**
fixes #41629 

Hi @LukeTonin, how does this look?
let me know if this needs any changes!
Thanks

### CODE REVIEW

**Comment by attack68** [comment]
Just commenting that medium.com is a paid article provider. That link is not always available, depending upon how many "free" articles you are permitted view in a period of time.

**Comment by ZurMaD** [comment]
Maybe can be added this https://stackoverflow.com/a/41130329/10491422 due it's a common limitation that causes confusion

**Comment by rbrishabh** [comment]
Sure! I can do that

**Comment by LukeTonin** [comment]
@rbrishabh That looks good. Agreed with the point about medium not always being accessible. A "free" resource would be better.

**Comment by rbrishabh** [comment]
Thanks! @LukeTonin made that `url` change

**Comment by jreback** [comment]
can i make this into a :note: to make this more prominent

text looks good

ping when greenish

**Comment by jreback** [comment]
yeah i see this is already adequately documented: https://pandas.pydata.org/pandas-docs/dev/user_guide/indexing.html#attribute-access, thanks @mwaskom 

thanks for the effort @rbrishabh

**Pull request closed without merging**
