### PR TITLE
BUG: to_datetime with unit mapping ignores utc and box arguments

### LINKED ISSUE #23760: BUG: to_datetime with unit mapping ignores utc and box arguments
```
In [12]: pd.__version__
Out[12]: '0.24.0.dev0+1040.g24bce1a5f'

In [13]: df = pd.DataFrame({'year': [2015, 2016],
    ...:                        'month': [2, 3],
    ...:                        'day': [4, 5]})
    ...:

In [14]: pd.to_datetime(df, box=False)
Out[14]:
0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

In [15]: pd.to_datetime(df, utc=True)
Out[15]:
0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]
```
These arguments need to be handled directly in this function or the output

https://github.com/pandas-dev/pandas/blob/24bce1a5fdd70a66b9fb5e2f9f51631d1df6add3/pandas/core/tools/datetimes.py#L574
#### Expected Output
```
In [16]: pd.to_datetime(df, box=False).values
Out[16]:
array(['2015-02-04T00:00:00.000000000', '2016-03-05T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [17]: pd.to_datetime(df, utc=True).dt.tz_localize('UTC')
Out[17]:
0   2015-02-04 00:00:00+00:00
1   2016-03-05 00:00:00+00:00
dtype: datetime64[ns, UTC]
```

### PR DESCRIPTION
**Pull request by jzhaojieh**
- [ ] closes #23760
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by datapythonista** [comment]
@jzhaojieh can you remove your comments with prints... from the PR please

**Comment by datapythonista** [comment]
@jzhaojieh it's better to open a pull request when you finish your work. The maintainers of the project usually receive notifications of updates to PR, and the continuous integration, which has usually a long queue, will run tests for every change you push.

Closing this for now, feel free to reopen or create a new PR when you finish.

**Comment by jzhaojieh** [comment]
@datapythonista Is there a way for me to run the continuous integration tests without creating a PR?

**Comment by datapythonista** [comment]
yes, `python -m pytest pandas` should run the tests locally. You should have all the info here: https://pandas.pydata.org/pandas-docs/stable/contributing.html (if something is not clear in that document, feel free to ask me, and then you can clarify it in a PR).

**Pull request closed without merging**
