### PR TITLE
STY: fstrings, repr pandas/io/html.py

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [x] ref #29547 #29886
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by alimcmaster1** [comment]
Kicking off CI again - its this test. https://github.com/pandas-dev/pandas/issues/30031

**Review by alimcmaster1 — APPROVED** [review]
LGTM

**Comment by MomIsBestFriend** [comment]
@alimcmaster1 Travis passed before, right?

Is there anything wrong with the changes? any suggestions?

**Comment by alimcmaster1** [comment]
Looks like a segfault on the travis run unrelated to your changes @MomIsBestFriend

**Comment by jreback** [comment]
thanks @MomIsBestFriend

**Pull request merged**
