### PR TITLE
PERF: Remove unnecessary asof join functions

### PR DESCRIPTION
**Pull request by wlach**
Several functions in the join cython are module are basically just calling others, and can probably be removed. This wouldn't
be a big deal inside python, but in this case it cuts down considerably on the amount of generated cython code.
    
The tests pass for me locally when I do this and there seems to be significant space savings.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
> significant space savings

cool, how much?

**Comment by wlach** [comment]
> > significant space savings
> 
> cool, how much?

I think I was seeing about a megabyte on join.pyx, although I think there might be the potential for further gains.

Unfortunately I wasn't running the tests properly so I didn't notice that my PR didn't actually work. :frowning: Need to dig in a bit further.

**Comment by wlach** [comment]
Ok, think I got this working now. It's not as big an improvement as I thought (about 100k or ~4% off of the generated .so for join) but I don't think it impacts readability (arguably it helps) so it seems worth doing.

Before

- 2617696 bytes
- nm: 2949 symbols

After

- 2508880 bytes
- nm: 2873 symbols

**Comment by wlach** [comment]
Ok, I think this is ready for a look!

docstring and typing information is giving an error but I don't see how it could be related to the code changes here (a very similar pull request from last night was passing):

```
Error: /home/runner/work/pandas/pandas/pandas/core/generic.py:2529:PR03:pandas.DataFrame.to_hdf:Wrong parameters order. Actual: ('path_or_buf', 'key', 'mode', 'complevel', 'complib', 'append', 'format', 'index', 'min_itemsize', 'nan_rep', 'dropna', 'data_columns', 'errors', 'encoding'). Documented: ('path_or_buf', 'key', 'mode', 'complevel', 'complib', 'append', 'format', 'index', 'errors', 'encoding', 'min_itemsize', 'nan_rep', 'dropna', 'data_columns')
```

**Comment by jreback** [comment]
> Ok, I think this is ready for a look!
> 
> docstring and typing information is giving an error but I don't see how it could be related to the code changes here (a very similar pull request from last night was passing):
> 
> ```
> Error: /home/runner/work/pandas/pandas/pandas/core/generic.py:2529:PR03:pandas.DataFrame.to_hdf:Wrong parameters order. Actual: ('path_or_buf', 'key', 'mode', 'complevel', 'complib', 'append', 'format', 'index', 'min_itemsize', 'nan_rep', 'dropna', 'data_columns', 'errors', 'encoding'). Documented: ('path_or_buf', 'key', 'mode', 'complevel', 'complib', 'append', 'format', 'index', 'errors', 'encoding', 'min_itemsize', 'nan_rep', 'dropna', 'data_columns')
> ```

this is unrelated

**Comment by jreback** [comment]
thanks @wlach

**Pull request merged**
