### PR TITLE
Remove unused arguments from np_datetime_strings

### PR DESCRIPTION
**Pull request by jbrockmendel**
Same deal as #18546.  This completes the pure-cleaning phase for np_datetime_strings.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
After this and #18567 there are two more PRs on deck to simplify src/datetime.

**Comment by jreback** [comment]
yep rebase

**Comment by jbrockmendel** [comment]
Travis error is a timeout, looks unrelated.  Will re-push this evening.

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by jbrockmendel** [comment]
ping

**Comment by jbrockmendel** [comment]
Once this is closed we can kill off datetime.pxd

**Comment by jreback** [comment]
kill it!

**Pull request merged**
