### PR TITLE
Backport PR #37613 on branch 1.1.x: BUG: read-only values in cython funcs

### PR DESCRIPTION
**Pull request by simonjayhawkins**
Backport PR #37613

will update milestones on PR and associated issues once this is green-ish. Will also need to update release notes on master. (move from 1.2 to 1.1.5)

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@simonjayhawkins whats your preferred way to move forward here?

**Comment by jreback** [comment]
i could prob just close this backport (and fix the release note), but either way ok

**Comment by jreback** [comment]
any resolution on this one (happy to just not backport as well).

**Comment by simonjayhawkins** [comment]
leave it open, I keep putting this off!, but the open issues on 1.1.5 milestone is getting less, so can't put it off much longer!

**Comment by simonjayhawkins** [comment]
closing for now. nothing needs to change on master as milestone and release note are 1.2 for #37613

**Pull request closed without merging**
