### PR TITLE
COMPAT/BLD: int dtype in json tests

### PR DESCRIPTION
**Pull request by chris-b1**
Fixes failing windows build
https://ci.appveyor.com/project/jreback/pandas-465/build/job/p8hju341jyhnkogc

### CODE REVIEW

**Comment by jreback** [comment]
so maybe add a note in json docs that deserializstion will go to platform ints

**Comment by chris-b1** [comment]
The public json api (`pd.read_json`) actually coerces everything to int64, it's only the internal methods where you can get a platform int.

```python
In [45]: s = pd.Series([1,2,3])

In [46]: pd.read_json(s.to_json(orient='records'), typ='series').dtype
Out[46]: dtype('int64')

In [47]: from pandas.json import loads

In [48]: loads(s.to_json(orient='records'), numpy=True).dtype
Out[48]: dtype('int32')
```

**Comment by jreback** [comment]
ok thanks @chris-b1 ping on green.

**Comment by jreback** [comment]
thank you sir!

**Pull request merged**
