### PR TITLE
ENH: fill_value argument for shift #15486

### LINKED ISSUE #15486: ENH: fill_value argument for shift
#### Feature Request

At the moment, the Series/DataFrame `shift` methods always fill with nans, which causes an upcast for boolean/integer types. In cases where there is an appropriate non-nan fill value, it would be useful to provide this value in `shift`, rather than having to correctly downcast the result. This would presumably also be more efficient than `.shift().fillna()` in those cases where no upcast is required.

#### Example Code

```python
>>> pd.Series([True]).shift(fill_value=False)
0    False
dtype: bool
```

### PR DESCRIPTION
**Pull request by samuelsinayoko**
This is a work in progress. 

Checklist for other PRs (remove this part if you are doing a PR for the pandas documentation sprint):

- [X] closes #15486 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
what issue is this for? can you fix the title

**Comment by samuelsinayoko** [comment]
This is work in progress. Current implementation doesn't work for categorical data, hoping to fix that soon.

**Comment by FancyCoder0** [comment]
Hi Samuel Sinayoko (@samuelsinayoko),
We are researchers working on identifying redundant development and duplicated pull requests. We have found there is a pull request: https://github.com/pandas-dev/pandas/pull/15527 which might be a potentially duplicate to this one. We would like to build the link between developers to reduce redundant development. We would really appreciate if you could help us to validate and give us feedback.
Thank you very much for your time!

**Comment by jreback** [comment]
closing as stale, if you want to continue working, pls ping and we can re-open. you will need to merge master.

**Pull request closed without merging**
