### PR TITLE
BUG: period_range gives incorrect output 

### LINKED ISSUE #53687: BUG: `period_range` gives incorrect output
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

start = pd.Period("2002-01-01 00:00", freq="30T")
print(
    pd.period_range(start=start, periods=5),
    pd.period_range(start=start, periods=5, freq=start.freq),
)
```

### Issue Description

The code above outputs:

```
PeriodIndex(['2002-01-01 00:00', '2002-01-01 00:01', '2002-01-01 00:02',
             '2002-01-01 00:03', '2002-01-01 00:04'],
            dtype='period[30T]')
PeriodIndex(['2002-01-01 00:00', '2002-01-01 00:30', '2002-01-01 01:00',
             '2002-01-01 01:30', '2002-01-01 02:00'],
            dtype='period[30T]')
```

The two outputs are not the same. The default behavior when `freq` is not passed as an argument is incorrect.

### Expected Behavior

By default `period_range` should use the `start`/`end` Period's freq as mentioned in the documentation but the output is incorrect.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.9.16.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.0-1033-aws
Version          : #37~20.04.1-Ubuntu SMP Fri Mar 17 11:39:30 UTC 2023
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : 2023.5.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : 2023.5.0
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

### PR DESCRIPTION
**Pull request by jayendra-patil33**
- [x] closes #53687
- [x] [Tests added and passed]
- [x] All [code checks passed]
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file

### CODE REVIEW

**Comment by jayendra-patil33** [comment]
I couldn't find any test case for `period_range()`, so which should the test case go in?

**Comment by mroeschke** [comment]
> I couldn't find any test case for `period_range()`, so which should the test case go in?

`pandas/tests/indexes/period/test_constructors.py`

**Comment by jayendra-patil33** [comment]
done.

**Comment by mroeschke** [comment]
Thanks @jayendra-patil33

**Pull request merged**
