### PR TITLE
BLD: Fixed pip install with no numpy

### LINKED ISSUE #25193: Pip install of version 0.24 is broken for platforms without wheels
#### Code Sample, a copy-pastable example if possible
Easiest way to reproduce this is in a fresh docker container, as below
```bash
docker run --rm -it alpine:latest
$ apk update
$ apk add build-base python3 python3-dev py3-pip
$ pip3 install pandas
Collecting pandas
  Downloading https://files.pythonhosted.org/packages/81/fd/b1f17f7dc914047cd1df9d6813b944ee446973baafe8106e4458bfb68884/pandas-0.24.1.tar.gz (11.8MB)
    100% |████████████████████████████████| 11.8MB 4.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 346, in get_provider
        module = sys.modules[moduleOrReq]
    KeyError: 'numpy'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y3ff_xpr/pandas/setup.py", line 732, in <module>
        ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
      File "/tmp/pip-install-y3ff_xpr/pandas/setup.py", line 475, in maybe_cythonize
        numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1136, in resource_filename
        return get_provider(package_or_requirement).get_resource_filename(
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 348, in get_provider
        __import__(moduleOrReq)
    ModuleNotFoundError: No module named 'numpy'
```

#### Problem description

Note that pip installing numpy and then pandas does work
```bash
pip3 install numpy
pip3 install pandas
```
But the standalone command is broken.
```bash
pip3 install pandas
```

Unfortunately, this means that a requirements.txt file is insufficient to for setting up a new environment with pandas installed (like in a docker container).

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes #25193 

Still testing this locally and on https://github.com/pandas-dev/pandas-ci/pull/6

### CODE REVIEW

**Comment by TomAugspurger** [comment]
So a `pip install --no-binary :all: pandas-0.25.0.dev0+203.g3e652ac56.tar.gz` into an sdist I built with this PR works... Anything else we should verify?

**Comment by TomAugspurger** [comment]
In https://github.com/pandas-dev/pandas-ci/pull/6 the CI run https://travis-ci.org/pandas-dev/pandas-ci/jobs/502590460 failed with

```
[pip-test-env before]
# packages in environment at /home/travis/miniconda3/envs/pip-test-env:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py37_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libstdcxx-ng              8.2.0                hdf63c60_1  
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1b               h7b6447c_0  
pip                       19.0.3                   py37_0  
python                    3.7.2                h0371630_0  
readline                  7.0                  h7b6447c_5  
setuptools                40.8.0                   py37_0  
sqlite                    3.26.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.1                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
[pip install]
Processing ./dist/pandas-0.25.0.dev0+203.g3e652ac56.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/travis/miniconda3/envs/pip-test-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 359, in get_provider
        module = sys.modules[moduleOrReq]
    KeyError: 'numpy'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ngo5yevd/setup.py", line 738, in <module>
        ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
      File "/tmp/pip-req-build-ngo5yevd/setup.py", line 481, in maybe_cythonize
        numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
      File "/home/travis/miniconda3/envs/pip-test-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1144, in resource_filename
        return get_provider(package_or_requirement).get_resource_filename(
      File "/home/travis/miniconda3/envs/pip-test-env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 361, in get_provider
        __import__(moduleOrReq)
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-ngo5yevd/
real	0m1.582s
user	0m1.448s
sys	0m0.124s
The command "ci/install.sh" failed and exited with 1 during .
```

Which is good (that was against master).

I'm going to submit a temporary commit there that applies this patch.

**Comment by jreback** [comment]
lgtm. release note?

**Comment by jreback** [comment]
thanks @TomAugspurger

**Pull request merged**
