### PR TITLE
CI/TST: xfail git test failure on 32 bit job

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Doesn't appear that a specific commit changed this recently, so xfailing for now.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
strict=False?  i dont think its failing on all builds, e.g. #46839

**Comment by mroeschke** [comment]
> strict=False? i dont think its failing on all builds, e.g. https://github.com/pandas-dev/pandas/pull/46839

Looks like the Azure didn't run which has the 32 bit build

**Comment by jbrockmendel** [comment]
somehow the xfail condition is evaluating to False?

**Comment by jbrockmendel** [comment]
LGTM

**Comment by mroeschke** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
