### PR TITLE
Set hypothesis healthcheck

### LINKED ISSUE #22593: Set hypothesis HealthCheck
from https://github.com/pandas-dev/pandas/pull/22280#issuecomment-416407165

```
# add to pandas/conftest.py
from hypothesis import settings, HealthCheck

settings.default.suppress_health_check = (HealthCheck.TooSlow,)
                                       # HealthCheck.all() to disable all health checks
```

### PR DESCRIPTION
**Pull request by alimcmaster1**
- [y] closes #22593
- [pending] tests added / passed
- [y] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [N/A] whatsnew entry

### CODE REVIEW

**Comment by TomAugspurger** [comment]
If you fetch and merge master the CI failures should be fixed.

**Review by gfyoung — APPROVED** [review]
cc @jreback @TomAugspurger

**Review by jreback — CHANGES_REQUESTED** [review]
small comments. ping on green.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @alimcmaster1

**Pull request merged**
