### PR TITLE
MAINT: Style check *.c and *.h files

### PR DESCRIPTION
**Pull request by gfyoung**
`cpplint` was introduced #14740, and this commit extends to check other `*.c` and `*.h` files.

Currently, they all reside in `pandas/src`, and this commit expands the lint to check all of the following:

1) `datetime` (dir)
2) `ujson` (dir)
3) `period_helper.c`
4) `All header files`

The parser directory was handled in #14740, and the others have been deliberately omitted per the discussion <a href="https://github.com/pandas-dev/pandas/pull/14740#issuecomment-265260209">here</a>.

### CODE REVIEW

**Comment by gfyoung** [comment]
@jreback : Any comments on this?  Should be ready to merge.

**Comment by gfyoung** [comment]
@jreback : Any comments on this?  Should be ready to merge.

**Comment by jreback** [comment]
lgtm.

**Comment by jreback** [comment]
@jorisvandenbossche I *think* u included the other style in 0.19.2, so can do this as well (up 2 you)

**Comment by jorisvandenbossche** [comment]
I didn't include the first style PR for 0.19.2, so for now will do the same for this one. I don't foresee many PRs anymore for 0.19.2, so shouldn't give too much problem

**Comment by jreback** [comment]
thanks!

**Comment by jreback** [comment]
any way you can not have the Done processing things show up?
we are explicity set to *only* errors (and which sub-dir) we are handling show up, otherwise its too much text.

```
linting -> pandas/src/*.h
Done processing pandas/src/numpy_helper.h
Done processing pandas/src/parse_helper.h
Done processing pandas/src/datetime_helper.h
Done processing pandas/src/helper.h
Done processing pandas/src/skiplist.h
Done processing pandas/src/period_helper.h
linting -> pandas/src/period_helper.c
Done processing pandas/src/period_helper.c
linting -> pandas/src/datetime
Done processing pandas/src/datetime/np_datetime_strings.c
Done processing pandas/src/datetime/np_datetime_strings.h
Done processing pandas/src/datetime/np_datetime.h
Done processing pandas/src/datetime/np_datetime.c
linting -> pandas/src/parser
Done processing pandas/src/parser/tokenizer.h
Done processing pandas/src/parser/io.h
Done processing pandas/src/parser/tokenizer.c
Done processing pandas/src/parser/io.c
linting -> pandas/src/ujson
Done processing pandas/src/ujson/python/ujson.c
Done processing pandas/src/ujson/python/JSONtoObj.c
Done processing pandas/src/ujson/python/objToJSON.c
Done processing pandas/src/ujson/lib/ultrajson.h
Done processing pandas/src/ujson/python/version.h
Done processing pandas/src/ujson/lib/ultrajsondec.c
```

**Comment by gfyoung** [comment]
@jreback : Yes, see #14924.

**Pull request closed without merging**
