### PR TITLE
DOC: Pandas Cheat Sheet (GH13202)

### LINKED ISSUE #13202: DOC: pandas cheat sheet
https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

I think we could pretty much rip this off exactly as is and just substitute pandas functions directly.

Further could update `comparison with R` a bit.

anyone up for this?

### PR DESCRIPTION
**Pull request by Dr-Irv**
- [x ] closes #13202 

Pandas Cheat Sheet.  Someone needs to figure out (or tell me the best way to do it!) how the PDF version gets integrated into the documentation tree.

### CODE REVIEW

**Comment by jreback** [comment]
I see!.

can you add a whatsnew note (put in a  path, I can fix if its not exactly right).

**Comment by Dr-Irv** [comment]
@jreback Pushed out a whatsnew.  Not sure why there is a conflict.  The other thing I'm not sure of is whether the main documentation tree should have a link to the cheat sheet, and if so, how to make it so that the whole documentation build process isn't messed up by a link to something outside the tree.

**Comment by jreback** [comment]
thanks!

I merged this, and so should show up on the doc-build.!

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf

!

**Comment by jreback** [comment]
once we upload this to pandas.pydata.org will need to fix the link
cc @jorisvandenbossche

**Pull request closed without merging**
