### PR TITLE
Fixes NonExistentTimeError when resampling weekly 

### LINKED ISSUE #53666: BUG: Unnecessary NonExistentTimeError when resampling weekly
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = pd.DataFrame({
    'ts': [datetime(2005, 10, 9, 21)],
    'values': [10.]
})
df['ts'] = df['ts'].dt.tz_localize('Chile/Continental')
df.resample('W-Mon', on='ts', closed='left', label='left')
```

### Issue Description

This throws
```python
NonExistentTimeError: 2005-10-09 00:00:00
```

I don't see why it should need to though - the window it needs to create is `[2005-10-03, 2005-10-10)`, so why would it matter that there's a non-existent time in that interval?

### Expected Behavior

```python
                         ts  values
0 2005-10-03 00:00:00-04:00    10.0
```

For reference, polars would give that output:
```python
In [35]: (
    ...:     pl.from_pandas(df)
    ...:     .with_columns(pl.col("ts").set_sorted())
    ...:     .groupby_dynamic("ts", every="1w", start_by="monday")
    ...:     .agg(pl.col("values").sum())
    ...: )
Out[35]:
shape: (1, 2)
┌─────────────────────────────────┬────────┐
│ ts                              ┆ values │
│ ---                             ┆ ---    │
│ datetime[ns, Chile/Continental] ┆ f64    │
╞═════════════════════════════════╪════════╡
│ 2005-10-03 00:00:00 -04         ┆ 10.0   │
└─────────────────────────────────┴────────┘
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : None
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

### PR DESCRIPTION
**Pull request by omar-elbaz**
- [ ] closes #53666 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) 
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Thanks for your PR!

To be honest I'm not sure this is the solution, I think we need to re-evaluate how the windows are determined

The end-points of the windows are not on ambiguous datetimes, so there's no reason why we should be hitting a non-existent datetime

**Comment by omar-elbaz** [comment]
@MarcoGorelli thanks for reviewing.
Do you have any recommended steps to get started?

**Comment by oluwatonio** [comment]
@mroeschke Please could you help my mentee with advice/review here? Thanks

**Comment by mroeschke** [comment]
Sorry for the delay here. I don't think anyone on the core team has bandwidth right now to suggest a quick solution to this complex issue right now. As alluded to in https://github.com/pandas-dev/pandas/pull/54609#pullrequestreview-1583975480, this may require a larger refactor.

Going to close for now, but happy to have contribution on other issues

**Pull request closed without merging**
