### PR TITLE
Modernize the fix for #10043

### PR DESCRIPTION
**Pull request by xhochy**
- [ ] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by xhochy** [comment]
This fails for non-writeable `object` NumPy arrays as they cannot be declared as `const` in Cython. This leaves us with either the case that we don't support them or that we reject this PR again.

**Comment by jreback** [comment]
hmm, that's annoying. so we still the the work around but only for ``object``.

**Comment by jreback** [comment]
you could leave the workaround in place and use the const keyword for non-object. i suppose that's an improvement.

**Comment by jorisvandenbossche** [comment]
> This fails for non-writeable object NumPy arrays as they cannot be declared as const in Cython. 

Do you know if that is an inherent limitation, or something that can be improved in Cython? (in which case we should report this there)

**Comment by xhochy** [comment]
Looking a bit deeper into this, I think this could be a limitation of Cython but I'm missing the necessary background knowledge, thus I opened a bug: https://github.com/cython/cython/issues/2485

**Comment by jreback** [comment]
closing as pending a cython fix :<

**Pull request closed without merging**
