### PR TITLE
REGR: <th> tags for notebook display closes #28204

### LINKED ISSUE #28204: CSS selector for index cells
While using **Jupyter notebooks**, I like to change the **color of header cells** in Pandas dataframes (all index cells, up and left) for more **contrast between the indexes and the data itself** (especially when I'm dealing with multiple indexes after using `.groupby()` like in the picture below) :

example

I used to achieve this using this CSS code :

```html
%%HTML
<style> 
.dataframe th {
background: #3f577c ;
font-family: monospace ;
color: white ;
border: 3px solid white ;
text-align: left !important ; } 
</style>
```

This worked because every index cell (in all indexes, up and left) used to be represented by a `<th> </th>` HTML tag.

However, after updating to Pandas version **`0.25.1`** from version **`0.21.x`**, the CSS stopped working because the HTML changed so only the upper index cells (column names) are wrapped in `<th> <th>` tags. The left index simply uses `<td> </td>` tags, just like the data cells (See image below. Note that both Genre and MediaTypeId are indexes):

example

Was this intentional? I tried using `first-child` like below but it only worked with dataframes having only 2 indexes (up and left). For the dataframes with more than one index on the left, only the first index is affected :

```html
%%HTML
<style>
.dataframe th, td:first-child {
background: #3f577c ;
font-family: monospace ;
color: white ;
border: 3px solid white ;
text-align: left !important ; }                                             
</style>
```

Any ideas?

### PR DESCRIPTION
**Pull request by simonjayhawkins**
- [ ] closes #28204
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
not added whatsnew. target 0.25.2?

**Comment by TomAugspurger** [comment]
Was it a regression in 0.25 or earlier?

**Comment by simonjayhawkins** [comment]
haven't checked thoroughly but i think the bug was introduced in  0.25.1 #27991

**Comment by TomAugspurger** [comment]
With 0.25.0

```python
In [2]: df = pd.DataFrame({"a": 1}, index=pd.MultiIndex.from_product([['a'], [2, 3]]))

In [3]: print(df._repr_html_())
```

```html
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>a</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="2" valign="top">a</th>
      <th>2</th>
      <td>1</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>
```

and with 0.25.1

```html
In [3]: print(df._repr_html_())
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>a</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="2" valign="top">a</td>
      <td>2</td>
      <td>1</td>
    </tr>
    <tr>
      <td>3</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>
```

So it seems to have been a 0.25.1 regression (so target for 0.25.2)

**Comment by simonjayhawkins** [comment]
thanks @TomAugspurger . will do.

**Review by TomAugspurger — APPROVED** [review]
LGTM. Merge conflict in the release notes.

**Review by TomAugspurger — APPROVED** [review]

**Pull request merged**
