### PR TITLE
DEPS: bump sqlalchemy min support version to 1.4.0

### PR DESCRIPTION
**Pull request by fangchenli**
precursor of #42976

### CODE REVIEW

**Review by alimcmaster1 — COMMENTED** [review]
This is quite a big jump forward in terms of time.

SQLAlchemy 1.3.11 = November 19
SQLAlchemy 1.4.0 = March 21

I know in the past we've wanted to move abit more slowly. So cc @jreback for a decision on this.

**Comment by jreback** [comment]
no this is fine
the prior version is for compatibility (i mean if we can keep 1.3.11 compat would be great but not sure it's possible)

**Review by alimcmaster1 — APPROVED** [review]

**Review by alimcmaster1 — CHANGES_REQUESTED** [review]
Think you will also need to update: https://github.com/pandas-dev/pandas/blob/master/pandas/compat/_optional.py#L29

and https://github.com/pandas-dev/pandas/blob/master/ci/deps/actions-38-locale_slow.yaml#L26

otherwise looks good

**Comment by jbrockmendel** [comment]
> I think we might even have sqlalchemy 1.4 compat problems see #40682. This might not be safe to do for 1.4.

@lithomas1 can you clarify are you saying this isn't safe to do for pandas 1.4 or isnt safe to support sqlalchemy 1.4?

**Comment by lithomas1** [comment]
I meant bumping the min version. Sorry for the confusion

**Comment by jreback** [comment]
@fangchenli status of this?

**Comment by fangchenli** [comment]
> @fangchenli status of this?

ready

**Comment by jreback** [comment]
can you add a whatsnew note about this change (assume we are dropping < 1.4)? (fine by me)

**Comment by fangchenli** [comment]
> can you add a whatsnew note about this change (assume we are dropping < 1.4)? (fine by me)

It's already included in the 1.4 whatsnew doc.

**Comment by jreback** [comment]
thanks @fangchenli

**Pull request merged**
