### PR TITLE
CI: Improve error message format in validate_docstrings.py

### PR DESCRIPTION
**Pull request by luke396**
Enhance the error message generated by executing `scripts/validate_docstrings.py --format=actions --errors=EX03 method-name`. 

Additionally, there appears to be a discrepancy, as including the ``--error=EX03`` flag still results in the display of another error. The cause of this inconsistency is unclear, and it might be related to a specific configuration.

(This observation and suggestion were brought to our attention by @asishm https://github.com/pandas-dev/pandas/issues/56804#issuecomment-1885402362)

After 
image

Before 
image

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by asishm** [comment]
> Additionally, there appears to be a discrepancy, as including the `--error=EX03` flag still results in the display of another error. The cause of this inconsistency is unclear, and it might be related to a specific configuration.

This is because when a method name is passed, it goes through the `print_validate_one_results(func_name)` path which only takes the method name and ignores the other arguments.

https://github.com/pandas-dev/pandas/blob/5955ca6645e45d23c978076ab8e556cb91ef124c/scripts/validate_docstrings.py#L444-L458

**Comment by asishm** [comment]
in addition, it looks like the CI check for validating EX03 issues returns success even if errors exist.

looking at the logs of this build - https://github.com/pandas-dev/pandas/actions/runs/7484980320/job/20372693999?pr=56827#step:9:258 there is an error reported for EX03, however the CI is still green

**Review by datapythonista — COMMENTED** [review]
This seems reasonable. I think it can be helpful to still keep one tab at the beginning, so the list of errors is still indented. What do you think?

**Comment by luke396** [comment]
> This seems reasonable. I think it can be helpful to still keep one tab at the beginning, so the list of errors is still indented. What do you think?

Can't agree any more!

image

**Comment by luke396** [comment]
The CI failure is strange, but it doesn't seem to be related to this pr's modification.

**Review by datapythonista — APPROVED** [review]
Thanks @luke396, looks great.

Yes, the CI failure seems unrelated, you may need to wait until it's fixed in the `main` branch, and then merge the branch again here. But other than that, this seems ready.

**Pull request merged**
