### PR TITLE
TST: fix errant tight_layout test

### LINKED ISSUE #9351: DataFrame.hist() does not get along with matplotlib.pyplot.tight_layout()
When `tight_layout()` is called after `DataFrame.hist()` it raises `AttributeError: 'NoneType' object has no attribute 'is_bbox` if any of subplots is empty (number of charts with histograms is smaller than number os subplots).

I.e. the following code:

```
pd.DataFrame({'a':np.random.randn(100),
              'b':np.random.randn(100),
              }).hist()
plt.tight_layout()
```

works fine, but this code:

```
pd.DataFrame({'a':np.random.randn(100),
              'b':np.random.randn(100),
              'c':np.random.randn(100),
              }).hist()
plt.tight_layout()
```

raises `AttributeError`.

My versions:
pandas: 0.15.2
numpy: 1.9.1
scipy: 0.14.1
IPython: 2.3.1
matplotlib: 1.4.2

### PR DESCRIPTION
**Pull request by ResidentMario**
closes #9351

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Why is it needed to remove this test?

**Comment by ResidentMario** [comment]
The test itself is incorrect because the `2` should be a `3` (not my best moment, this was). Additionally, this is patched in `matplotlib 2.0.1`, not `matplotlib 2.0.0` as indicated here. So to keep the test around, we would need to modify when it skips.

More substantially, this bug was actually a bug in `matplotlib`, which I fixed and added a regression test for in their test suite. `pandas` doesn't *really* need to duplicate it.

**Comment by jorisvandenbossche** [comment]
Ah, the reason that it is 2 instead of 3 is the reason it now just passes, while the test should actually fail because it needs >= 2.0.1 instead of >= 2.0.0 ?

I think testing this in pandas is fine, as we should keep tight_layout working with pandas plots (we may change implementation details in the hist method that could cause problems with tight_layout)

**Comment by ResidentMario** [comment]
Yes, exactly.

Hmm. OK, can do.

**Comment by ResidentMario** [comment]
@jreback @jorisvandenbossche Does this look good? Tests pass.

**Comment by ResidentMario** [comment]
This would close #9351.

**Comment by jreback** [comment]
lgtm. @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
