### PR TITLE
ENH: `Styler.show` shorthand alternative to `hide`

### LINKED ISSUE #42533: ENH: Enhance printing options for stylized DataFrames
#### Is your feature request related to a problem?

More like an improvement.

#### Describe the solution you'd like

I just started playing around with pandas styling, and I noticed there is no way to print only the head and/or tail of a stylized DataFrame. It would be awesome if the styling could be applied to the whole df but then we could print only selected rows, like head and/or tail.

#### API breaking implications

I guess there could be a parameter passed to methods such as `bar`,  or a new method to be appended to the end of a call.

#### Describe alternatives you've considered

I can apply the style to a slice of a DataFrame but then the styling function is applied to this slice only. What if I want to highlight_max to the whole df but print head/tail only?

### PR DESCRIPTION
**Pull request by attack68**
- [x] closes #42533
- [x] tests added / passed
- [x] whatsnew entry

Provides a convenient shorthand for displaying only specified rows as data exploration:

### Example

Screenshot 2022-01-03 at 17 59 15

### Rendered Docstring

Screenshot 2022-01-03 at 18 03 07
Screenshot 2022-01-03 at 18 03 16

### CODE REVIEW

**Comment by jreback** [comment]
why not just expose `.head()`, `.tail()`, `.iloc[...]` ?

**Comment by ivasve** [comment]
Hi @attack68 , it seems that the "pandas-dev.pandas" build has failed. (conflicts in a branch). So this issue is still open.

**Comment by attack68** [comment]
Closing this, I have a different idea for **docs** instead which does not include new methods

**Comment by LinuxIsCool** [comment]
> Closing this, I have a different idea for **docs** instead which does not include new methods

What are your ideas? Where can they be found in the docs? 

It's frustrating that `max_rows` can not be applied to a stylized dataframe as discussed in #42533

**Pull request closed without merging**
