### PR TITLE
CLN: Clean-up use of super() in instance methods.

### PR DESCRIPTION
**Pull request by topper-123**
- [x] xref #25725

Simplifies the use of simple uses of ``super`` by converting to use python3 idioms. This is a quite big PR, but only deals with converting ``super(MyClass, self)`` to ``super()`` so it's very simple.

In addition to the uses of ``super`` dealt with in this PR, there are some more advanced uses of ``super`` in the code base, e.g. in classmethods and using ``super`` to jump to a specific point in the MRO-chain. I'd like to tackle those in a seperate PR in order to keep the the current large PR very simple.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm, will merge after I fixup master.

can you do a followup to prohitbit the old style in code-checks (or push to this one ok too)

**Comment by topper-123** [comment]
I can add that to the follow-up, where I take the rest of ``super``.

**Comment by topper-123** [comment]
The failure seems unrelated, don't know what's going on:

```
  @pytest.mark.parametrize('cache', [True, False])
    def test_string_na_nat_conversion(self, cache):
        # GH #999, #858
    
        strings = np.array(['1/1/2000', '1/2/2000', np.nan,
                            '1/4/2000, 12:34:56'], dtype=object)
    
        expected = np.empty(4, dtype='M8[ns]')
        for i, val in enumerate(strings):
            if isna(val):
                expected[i] = iNaT
            else:
                expected[i] = parse(val)
    
        result = tslib.array_to_datetime(strings)[0]
        tm.assert_almost_equal(result, expected)
    
        result2 = to_datetime(strings, cache=cache)
        assert isinstance(result2, DatetimeIndex)
        tm.assert_numpy_array_equal(result, result2.values)
    
        malformed = np.array(['1/100/2000', np.nan], dtype=object)
    
        # GH 10636, default is now 'raise'
        msg = (r"\(u?'Unknown string format:', '1/100/2000'\)|"
               "day is out of range for month")
        with pytest.raises(ValueError, match=msg):
>           to_datetime(malformed, errors='raise', cache=cache)
E           AssertionError: Pattern '\(u?'Unknown string format:', '1/100/2000'\)|day is out of range for month' not found in 'Unknown string format: 1/100/2000'
```

**Comment by WillAyd** [comment]
Certainly strange. Looks like it is a result of this PR though. Maybe revert the changes to pandas/_libs/tslibs/strptime.pyx (or other cython modules) and see if the error disappears - could certainly be differences with how Cython handles super calls versus Python

**Comment by topper-123** [comment]
This error message shows up in #22511 also, so must be something else. If it`s only my code, its very strange. I`ll look into that.

**Comment by jreback** [comment]
thanks @topper-123

**Pull request merged**
