### PR TITLE
 Remove blank lines-->fix cookbook rendering issue

### LINKED ISSUE #23128: DOC: possible cookbook rendering issue with PR #22761
When building the cookbook documentation locally I noticed that the function `distcorr` under the Computation header is getting cut off at the first empty line (PR #22761 and commit `904af03c36b63d8df911b5cdba1e29e66c6df4b4`).  I tried adding white space indentation but that doesn't seem to have helped.  Anyone have ideas as to what the issue might be?

### PR DESCRIPTION
**Pull request by thoo**
Fixes #23128

### CODE REVIEW

**Comment by jreback** [comment]
what are you removing lines? if anything they improve code readability

**Review by datapythonista — APPROVED** [review]
It'd be nice to find a better way to fix the problem with the ipython directive, but unless someone knows how to do that, I think we can merge this, which is probably better than having the function incomplete (ipython only renders until the first blank line). See: https://pandas-docs.github.io/pandas-docs-travis/cookbook.html#correlation

**Comment by jreback** [comment]
better way is to use multiple ipython blocks
simpler and more descriptive (as u. can comment on code)
having large blocks of code is an anti-pattern

**Comment by datapythonista** [comment]
But can we split the code of a function across different ipython blocks?

I'm thinking that may be a better option is to use a `python` code block instead of an `ipython` one. That should fix the problem and we still keep the readability of the code.

Closing this PR. @thoo do you want to take care of that? The idea is to use  `.. code-block:: python` instead. And that requires that instead of the code directly without the outputs, we use `>>>` and the outputs, for example:
```
>>> def func():
...      print('hello world')
>>> func()
hello world
```

**Comment by thoo** [comment]
@datapythonista Sure. Let me take a look. Hopefully it is straight forward.

**Comment by thoo** [comment]
@datapythonista  Will this work?
```
>>> def distcorr(x, y):
        n = len(x)
        a = np.zeros(shape=(n, n))
        b = np.zeros(shape=(n, n))

        for i in range(n):
            for j in range(i + 1, n):
                a[i, j] = abs(x[i] - x[j])
                b[i, j] = abs(y[i] - y[j])
        a += a.T
        b += b.T

        a_bar = np.vstack([np.nanmean(a, axis=0)] * n)
        b_bar = np.vstack([np.nanmean(b, axis=0)] * n)

        A = a - a_bar - a_bar.T + np.full(shape=(n, n), fill_value=a_bar.mean())
        B = b - b_bar - b_bar.T + np.full(shape=(n, n), fill_value=b_bar.mean())

        cov_ab = np.sqrt(np.nansum(A * B)) / n
        std_a = np.sqrt(np.sqrt(np.nansum(A**2)) / n)
        std_b = np.sqrt(np.sqrt(np.nansum(B**2)) / n)

        return cov_ab / std_a / std_b

>>> df = pd.DataFrame(np.random.normal(size=(100, 3)))

>>> df.corr(method=distcorr)
            0         1         2
    0  1.000000  0.209812  0.132786
    1  0.209812  1.000000  0.153526
    2  0.132786  0.153526  1.000000
```

**Comment by datapythonista** [comment]
I think you need the `...` in the blank lines too. Can you check how to run doctests on the Internet, and find a way to run it to make sure please.

**Pull request closed without merging**
