### PR TITLE
remove useless semicolons

### PR DESCRIPTION
**Pull request by wdroz**
Some semicolons were used without reason.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I don't think this is without reason? 
I think it supresses the output like `Out[15]: <matplotlib.axes._subplots.AxesSubplot at 0x7fc57ae70c50>` 

Still, question is if this is needed, but IMO it makes the docs a bit cleaner.

**Comment by jorisvandenbossche** [comment]
BTW, something that may not be needed is actually the full `plt.figure();`

**Comment by wdroz** [comment]
The semicolons that I remove were probably copy/paste mistakes

**Comment by wdroz** [comment]
omg, it's seem to be a features... there are some hidden tricks with IPython using semicolons.

**Pull request closed without merging**
