### PR TITLE
REF: Move Loc-only methods to Loc

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jreback** [comment]
looks good, straight moves?

**Comment by jbrockmendel** [comment]
> straight moves?

in a couple of places i got rid of `o = self.obj` and substituted in `self.obj`

**Comment by jbrockmendel** [comment]
rebased+green

**Comment by jbrockmendel** [comment]
gentle ping; merge conflicts are going to pile up

**Comment by jreback** [comment]
yep, can you rebase; merge on green.

**Pull request merged**
