### PR TITLE
CI: disable codecov

### PR DESCRIPTION
**Pull request by jbrockmendel**
xref #27602

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Give me ~15 minutes here. Doing some debugging of our config.

**Comment by TomAugspurger** [comment]
This may be unnecessary if https://github.com/pandas-dev/pandas/pull/28070 passes.

**Comment by jbrockmendel** [comment]
I’m AFK for a bit.  If codecov problem is resolved, feel free to close this.

**Comment by TomAugspurger** [comment]
No luck just targeting master (400 error again).

Just disabling.

**Pull request merged**
