### PR TITLE
[ArrayManager] TST: run all tests with separate not slow / slow build

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref #39146

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@jreback @jbrockmendel as discussed, this splits the current actions build with ArrayManager in two and runs the full test suite with slow / not slow markers.

**Comment by jbrockmendel** [comment]
nice.  any estimate how this affects CI runtime?

**Comment by jorisvandenbossche** [comment]
>  any estimate how this affects CI runtime?

Note that with this PR, not much changes (we were already running almost all tests in this build). It is https://github.com/pandas-dev/pandas/pull/40496 that is adding tests to all other builds

**Comment by jorisvandenbossche** [comment]
And to answer your actual question: this added one build (for the slow tests) that takes 25m.

**Comment by jreback** [comment]
thanks @jorisvandenbossche very nice

**Pull request merged**
