### PR TITLE
BUG: Series.__getitem__ with MultiIndex and leading integer level

### LINKED ISSUE #33355: BUG/API: should MultiIndex with leading integer level fallback to positional?
```

idx = pd.Index(range(3))
dti = pd.date_range("2016-01-01", periods=2)
mi = pd.MultiIndex.from_product([idx, dti])

ser = pd.Series(range(len(mi))[::-1], index=mi)

>>> ser
0  2016-01-01    5
   2016-01-02    4
1  2016-01-01    3
   2016-01-02    2
2  2016-01-01    1
   2016-01-02    0
dtype: int64
>>> ser[3]
2
```

My intuition is that `ser[3]` should behave like indexing on just the first level of the MultIIndex:

```
ser2 = ser.droplevel(1)

>>> ser2
0    5
0    4
1    3
1    2
2    1
2    0
dtype: int64
>>> ser2[3]
KeyError: 3
```

Should we avoid the fallback-to-positional behavior in this case?

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #33355
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
looks good, does your patch also fix these cases by @jorisvandenbossche https://github.com/pandas-dev/pandas/issues/33355#issuecomment-611152308?

**Comment by jbrockmendel** [comment]
> does your patch also fix these cases

one of them, am about to push a commit with a test.  the list-like cases no

**Comment by jbrockmendel** [comment]
Follow-up coming up that fixes the listlike MultiIndex case as well as a related IntervalIndex bug

**Comment by jreback** [comment]
thanks

**Pull request merged**
