### PR TITLE
Update : In DataFrame Class, Columns should not contain duplicate val…

### PR DESCRIPTION
**Pull request by MohakGangwani**
Also updated the Docstring.(#12991)

### CODE REVIEW

**Comment by dsaxton** [comment]
I don't think this is addressing the original issue. DataFrames can have columns with duplicate labels, the problem is when trying to modify only one.

**Comment by MohakGangwani** [comment]
Wouldn't it be better if pandas didn't allow us to have duplicate column names ? Having columns with same name would rather create confusion for us.
Plus, this may avoid the issue #12991

**Comment by dsaxton** [comment]
> Wouldn't it be better if pandas didn't allow us to have duplicate column names ? Having columns with same name would rather create confusion for us.
> Plus, this may avoid the issue #12991

Probably yes, there's a WIP PR about not allowing duplicate labels https://github.com/pandas-dev/pandas/pull/28394

**Comment by MarcoGorelli** [comment]
Thanks @MohakGangwani

AFAICT, #28394 would already address the issue of optionally disallowing duplicate column labels. Suddenly raising an exception without any prior warning wouldn't be good form - furthermore, you would need to add tests for this new behaviour.

Closing for now then as this looks like it's inactive and probably not the solution pandas would want to go with

**Pull request closed without merging**
