### PR TITLE
TYP: annotation of __init__ return type (PEP 484) (pandas/utils)

### PR DESCRIPTION
**Pull request by nafarya**
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

According to [documentation](https://pandas.pydata.org/docs/dev/development/contributing_codebase.html#type-hints) pandas uses [PEP484](https://www.python.org/dev/peps/pep-0484/) for type hints.
PEP484 states that `__init__` function should have `-> None` return type annotation.
In this PR I added return type annotation to `__init__` functions in `pandas/utils` module.
Thanks!

### CODE REVIEW

**Comment by NickCrews** [comment]
@nafarya Hi! Thanks for this! I'm wondering if there is a way to configure our code checks so that this is caught automatically? ie can black or flake8 somehow catch this? That seems like the golden standard, if possible, so that the **entire** codebase is consistent.

**Comment by nafarya** [comment]
> @nafarya Hi! Thanks for this! I'm wondering if there is a way to configure our code checks so that this is caught automatically? ie can black or flake8 somehow catch this? That seems like the golden standard, if possible, so that the **entire** codebase is consistent.

Hi! Thats great idea and I think it should be possible! Maybe it could be done the same way as you check for [PEP 8](https://www.python.org/dev/peps/pep-0008): via https://github.com/pep8speaks

**Comment by NickCrews** [comment]
Floated the idea to black here: https://github.com/psf/black/issues/2913

**Comment by phofl** [comment]
Please wait for https://github.com/pandas-dev/pandas/pull/46283#discussion_r823143278

**Comment by jreback** [comment]
thanks @nafarya

**Pull request merged**
