### PR TITLE
Issue46882

### LINKED ISSUE #46882: ENH: allow preserving one of the indexes when merging two DataFrames
#### Is your feature request related to a problem?

I want to be able to merge two DataFrames, but keep the index of the left one in the final result:

```python
>>> import pandas as pd
>>> import string
>>> df1 = pd.DataFrame({"a": range(5), "b": range(10, 15)}, index=list(string.ascii_lowercase[:5]))
>>> df2 = pd.DataFrame({"a": range(5), "c": list(string.ascii_uppercase[:5])})
>>> df1
   a   b
a  0  10
b  1  11
c  2  12
d  3  13
e  4  14
>>> df2
   a  c
0  0  A
1  1  B
2  2  C
3  3  D
4  4  E
```
The current merge behaviour is to just drop the index entirely:
```python
>>> df1.merge(df2, on="a")
   a   b  c
0  0  10  A
1  1  11  B
2  2  12  C
3  3  13  D
4  4  14  E
```

#### Describe the solution you'd like

We add a new parameter `preserve_index` to `merge`, which takes either `"left"`, `"right"`, or `None`

`DataFrame.merge(preserve_index="left")`

In my above example, this would work like:
```python
>>> df1.merge(df2, on="a", preserve_index="left")
   a   b  c
a  0  10  A
b  1  11  B
c  2  12  C
d  3  13  D
e  4  14  E
```

#### API breaking implications

None. This is a new parameter, and if it is not provided the API is identical.

#### Describe alternatives you've considered

It is already possible to work around this by resetting the index and then setting it as an index again, [as described here](https://stackoverflow.com/a/11982843/2148718) but this is:
* More verbose
* Not intuitive or clear to users (hence the StackOverflow question's popularity)
* Probably less efficient

### PR DESCRIPTION
**Pull request by Mehgarg**
- [ ] closes #46882 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
We don't want to implement this yet, as there is no agreement to support this parameter

**Comment by Mehgarg** [comment]
What would be blocking this? The original issue was marked at Contributions Welcome so I assumed the parameter was supported.

**Comment by phofl** [comment]
@attack68 was -1 on this and I would also lean to not support this

**Comment by jreback** [comment]
-1 as well

.join already does this not worth yet another kwarg in .merge

ok for a doc example of how to do

**Comment by mroeschke** [comment]
Thanks for the pull request @Mehgarg and sorry for the false impression that this feature was ready for a pull request, but generally it appears that the core team is not in favor of supporting this yet so closing. We're happy to have your contributions on other issues (generally ones where a team member has said a pull request is welcome in the comments).

**Pull request closed without merging**
