### PR TITLE
CLN: Replace old format strings to f-strings in pandas/tests/base

### PR DESCRIPTION
**Pull request by rbharadwaj9**
- [x] Contributes to #29547 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by rbharadwaj9** [comment]
I am unable to for the life in my run pytest on the repository and by this I mean that it doesn't work for the unchanged `master` branch.
If anyone can help me as to where I'm going wrong I'd appreciate it.

**Comment by jreback** [comment]
thanks @rbharadwaj9 

pls make sure your environment is setup and you have compiled the extensions

**Comment by charlesdong1991** [comment]
this might help @rbharadwaj9 if following through:

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html

**Comment by rbharadwaj9** [comment]
I got it. Thanks for the help!

**Pull request merged**
