### PR TITLE
DOC: generate docs for the `Series.dt.isocalendar()` method.

### PR DESCRIPTION
**Pull request by tswast**
- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by tswast** [comment]
Screenshots of successfully built docs:

weekofyear docs linking to isocalendar docs

isocalendar docs


Series index, showing link to isocalendar docs

**Comment by jreback** [comment]
hmm can you rebase on master, i think the doc build was borked previous.

**Comment by jreback** [comment]
thanks @tswast something odd on doc CI but your change is orthogonal.

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
