### PR TITLE
Timedelta index 29236

### LINKED ISSUE #29236: DOCS: Formatting Errors pandas.TimedeltaIndex
[pandas/core/Indexes/timedeltas.py](https://github.com/pandas-dev/pandas/blob/c7462edc33e89452ae55cb52f61b23cb66e48a5b/pandas/core/indexes/timedeltas.py)

#28602 
#27977

[pandas/core/indexes/base.py](https://github.com/pandas-dev/pandas/blob/0a44feafd58f3c5576e5f4bf3d0136dcacc352f2/pandas/core/indexes/base.py)

```
python ./scripts/validate_docstrings.py pandas.TimedeltaIndex.to_series
```

```
7 Errors found:
	Summary should fit in a single line
	Parameter "index" description should start with a capital letter
	Parameter "index" description should finish with "."
	Parameter "name" description should start with a capital letter
	Parameter "name" description should finish with "."
	The first line of the Returns section should contain only the type, unless multiple values are being returned
	Return value has no description
```

[pandas/core/arrays/datetime.py](https://github.com/pandas-dev/pandas/blob/18a9e4c8ab253e83ba43767d890576186be13332/pandas/core/arrays/datetimelike.py)
```
./scripts/validate_docstrings.py pandas.TimedeltaIndex.mean
```

```
5 Errors found:
	Parameters {**kwargs, *args} not documented
	Unknown parameters {skipna}
	Parameter "skipna" description should finish with "."
	Return value has no description
	Missing description for See Also "numpy.ndarray.mean" reference
```

### PR DESCRIPTION
**Pull request by HughKelley**
- [ ] closes #29236 

only remaining docstring errors are for `TimedeltaIndex.mean`

    Parameters {*args, **kwargs} not documented
    Unknown parameters {skipna}

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@HughKelley can you address linting issues

**Comment by HughKelley** [comment]
@WillAyd what is the 1.0 milestone used for?

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
> @WillAyd what is the 1.0 milestone used for?

We use this for tracking PRs making their way into our next release

**Comment by WillAyd** [comment]
Thanks @HughKelley !

**Pull request merged**
