### PR TITLE
DOC: updated docstrings for FramePlotMethods and SeriesPlotMethods

### LINKED ISSUE #15458: DOC: DataFrame.plot options are not documented in docstring form
These can be seen by inspecting the `__call__` attribute, but they are referenced from the particular plotting methods, but not easily learned about in IPython/Jupyter.

https://github.com/pandas-dev/pandas/blob/master/pandas/tools/plotting.py#L3781

### PR DESCRIPTION
**Pull request by yinleon**
Closes #15458

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@yinleon I don't think we will want to duplicate the full docstring.

I don't think our decorator will work with a class docstring, but what you can also do is something like:

```
class SeriesPlotMethods
    ....

SeriesPlotMethods.__doc__ = _shared_docs['plot'] % _shared_doc_series_kwargs
```

to reuse the existing docs.

**Comment by yinleon** [comment]
Thanks for the tip @jorisvandenbossche! I made the requested changes in commit `aa09f91`. I was told to rebase commits on another project, and can do so if requested.

**Comment by jorisvandenbossche** [comment]
Hmm, this approach also does not seem to work (didn't know that):

```
  File "/home/travis/build/pandas-dev/pandas/pandas/tools/plotting.py", line 3766, in <module>
    SeriesPlotMethods.__doc__ = _shared_docs['plot'] % _shared_doc_series_kwargs
AttributeError: attribute '__doc__' of 'type' objects is not writable
```

This only errors on Python 2, but you normally can do this assignment in the class definition as well

like 

```
class ..

    __doc__ = _shared_docs['plot']

```

**Comment by jorisvandenbossche** [comment]
@yinleon Do you have time to update this?

**Comment by jreback** [comment]
@yinleon can you rebase / update

**Comment by jreback** [comment]
closing as stale

**Pull request closed without merging**
