### PR TITLE
Check boundary undefined with non-default close parameter for DatetimeIndex #23198

### LINKED ISSUE #23198: Check boundary undefined with non-default close parameter for DatetimeIndex
#### Code Sample
```python
import pandas as pd
```

1:
```python
print(pd.DatetimeIndex(start="2018-10-17", periods="7", closed="left"))
```

2:
```python
print(pd.DatetimeIndex(start="2018-10-17", periods="7", closed="right"))
```

3:
```python
print(pd.DatetimeIndex(end="2018-10-17", periods="7", closed="left"))
```

4:
```python
print(pd.DatetimeIndex(end="2018-10-17", periods="7", closed="right"))
```

#### Problem description

There is a check in the code that should not allow this cases. It raises a `ValueError`. The `if`condition is bugged and thus this check is not being processed. This was found while investigating #23176.

Note: this issue is not debating wether allowing or disallowing `closed` differents to `None` for only partially bounded `DatetimeIndex`es (understanding partially bounded as only one of `start` and `end` provided). It is just pointing out that the current code is skipping a check.

#### Expected Output
1:
```python
ValueError("Closed has to be None if not both of startand end are defined")
```

2:
```python
ValueError("Closed has to be None if not both of startand end are defined")
```

3:
```python
ValueError("Closed has to be None if not both of startand end are defined")
```

4:
```python
ValueError("Closed has to be None if not both of startand end are defined")
```

#### Output of ``pd.show_versions()``

```
python: 3.6.4.final.0

pandas: 0.23.4
```

### PR DESCRIPTION
**Pull request by Adirio**
- [X] closes #23198 
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by Adirio** [comment]
No idea what happened with the failed test.

**Comment by jbrockmendel** [comment]
The failed test is unrelated; don't worry about it.

This does need its own test though.

**Comment by Adirio** [comment]
I have no previous experience with pytest, I guess I need to add a new method to the `TestDatetimeArray` class [here](https://github.com/Adirio/pandas/blob/patch-1/pandas/tests/arrays/test_datetimelike.py#L48) that checks that a `ValueError` is raised if `closed != None` while one of the boundaries is not given, but no idea how to check that.

**Comment by mroeschke** [comment]
You can use the `pytest.raises` context manager and see if the examples in the linked issue will raise a `ValueError`:

```
with pytest.raises(ValueError):
    pd.date_range(...)
```

**Comment by jreback** [comment]
this would need to assert all of the test cases in the OP

**Comment by jreback** [comment]
can you merge master and update.

**Comment by jreback** [comment]
closing as stale. ping if you'd like to continue.

**Comment by Adirio** [comment]
@jreback I can merge master if you wish but I can not provide the requested tests right now.

**Pull request closed without merging**
