### PR TITLE
error resolution in sas file

### PR DESCRIPTION
**Pull request by pranava1709**
- [x] closes https://github.com/pandas-dev/pandas/issues/18198
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] SAS file is now giving empty dataframe. Not NONE.

### CODE REVIEW

**Review by phofl — CHANGES_REQUESTED** [review]
What are you trying to do?

**Comment by attack68** [comment]
hi @Pranava1709 seems like a fat finger or mistaken PR. You can't really just add random python script files that don't have any impact on the codebase.
Please re-open and re-commit if you have code change contributions to make

**Comment by Pranava1709** [comment]
The python script that I have added solves one of the issues. I have also
tested it on my local computer. You can cross-check the issue.

**Comment by phofl** [comment]
This is outside of anything Pandas uses. How does that solve any issues?

**Comment by Pranava1709** [comment]
My code has used only one library which is pandas. The issue(#43326) was
that the SAS file with 0 rows was giving NONE, while CSV was giving an
empty data frame. With this script, SAS file is also giving empty data
frame instead of none.

**Comment by phofl** [comment]
But how does this fix the pandas function read_sas?

**Comment by Pranava1709** [comment]
It does not fix read_sas. It fixes the issue that was coming in the output.
According to the issue, there is no mention that the issue is in read_sas.
I solved this issue keeping the problem in mind that it was not giving an
empty data frame with 0 rows.
So I took a file, removed the rows and checked it and got the required
output.

**Comment by phofl** [comment]
We would want read_sas to return the correct result. Everything Else does Not help out users. Please read the contributing guidelines

**Comment by Pranava1709** [comment]
It is returning. It's just I had a random dataset, in which I removed the
rows. If you pass an original file with 0 rows read_sas will give the same
output. The extra part is the preprocessing of data that's it as the file
was not empty.

**Comment by phofl** [comment]
Then the function already is correct, so no need to das anything except a Test case

**Comment by Pranava1709** [comment]
This was an issue so I took it up.

**Comment by phofl** [comment]
If an issue is already fixed we add a test to close and avoid regressions.

**Comment by Pranava1709** [comment]
So what do I do now? I took this issue for my internship. They wanted to
fix one of the issues and send the pull request to them.

**Comment by phofl** [comment]
Add a test checking that an empty sas file is read as an empty dataframe.

**Pull request closed without merging**
