### PR TITLE
fix

### PR DESCRIPTION
**Pull request by csaoma**
- [x] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by csaoma** [comment]
f strings

**Comment by jbrockmendel** [comment]
@csaoma can you give your PRs informative titles in the future

**Comment by csaoma** [comment]
> @csaoma can you give your PRs informative titles in the future

**Comment by alimcmaster1** [comment]
Closing - you have a PR open with these changes

**Pull request closed without merging**
