### PR TITLE
Avoid redirect

### PR DESCRIPTION
**Pull request by chankeypathak**
A minor change to avoid 301 redirect on link.

### CODE REVIEW

**Comment by alimcmaster1** [comment]
Looks good - mind merging master for green CI?

**Comment by chankeypathak** [comment]
@alimcmaster1 done, not sure why it's failing...

**Comment by alimcmaster1** [comment]
Ref: #35737 for CI failures

**Comment by alimcmaster1** [comment]
If you merge master the CI issues should be fixed - thanks

**Comment by alimcmaster1** [comment]
If you merge master again CI failures should be resolved

**Review by alimcmaster1 — APPROVED** [review]
LGTM - pending green CI

**Pull request merged**
