### PR TITLE
Fix traceback.format_exc(e) call

### PR DESCRIPTION
**Pull request by Pehat**
As of https://docs.python.org/2/library/traceback.html#traceback.format_exc , format_exc() accepts an integer for traceback depth limit, not the traceback itself.

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
Interesting find. Do we even need the `try...except` now?

**Comment by jbrockmendel** [comment]
The docs say that format_exc signature is `traceback.format_exc(limit=None, chain=True)`.  In fact, passing `e` raises on py3 and is OK in py2

**Comment by WillAyd** [comment]
Yea change makes sense. I think can just remove the entire try...except surrounding it - @Pehat is that something you can do?

**Comment by Pehat** [comment]
@WillAyd done, checks seem to be OK.

**Pull request closed without merging**
