### PR TITLE
Updated years in LICENSE

### PR DESCRIPTION
**Pull request by ShaharNaveh**
Really not sure about this change.

(Feel free to close this PR at any time, if this file should not be changed).

### CODE REVIEW

**Comment by WillAyd** [comment]
Not sure about this either. Maybe @TomAugspurger knows

**Comment by TomAugspurger** [comment]
Not sure either.

**Comment by WillAyd** [comment]
Maybe @wesm would know then

**Comment by wesm** [comment]
I would recommend splitting out multiple copyright lines.

I was being paid by AQR from 2008 until mid/late 2011 (first as a FTE and then as a contractor), so I think you can state AQR as a copyright holder from 2008 - 2011. 

Beyond 2011 I think you can simply say "Copyright 2011 - 2020 pandas contributors". The project uses a shared copyright model where copyright is owned by the individuals contributing code to the project. So that would be my recommendation

```
Copyright 2008 - 2011 AQR Capital Management, LLC
Copyright 2011 - 2020 pandas open source contributors
```

or similar

**Comment by jreback** [comment]
thanks @MomIsBestFriend

**Pull request merged**
