### PR TITLE
REF: Remove many Panel tests

### PR DESCRIPTION
**Pull request by jbrockmendel**
Stopped this branch at the point where I'd have to do surgery on `legacy_table.h5` to fix `test_legacy_table_read`.  If we're dropping that entirely and can just remove the file, I can push forward on removing a bunch more of `io.pytables`.

### CODE REVIEW

**Comment by jreback** [comment]
```
    def test_legacy_table_fixed_format_read_py2(self, datapath):
    def test_legacy_table_read_py2(self, datapath):
    def test_legacy_table_read(self, datapath):
    def test_legacy_datetimetz_object(self, datapath):
```

so can remove      these 2

```
def test_legacy_table_read(self, datapath):
 def test_legacy_datetimetz_object(self, datapath):
```

which are really old legacy formats (just make a note in the whatsnew). The others need to stay as they are written in PY2 and should still be readable (as these are really just tests of encoding).

**Comment by jbrockmendel** [comment]
> This can certainly be a followup.

Sounds good.  I'm AFK for a bit, will do this in the next pass.

**Comment by jreback** [comment]
thanks!

**Comment by jbrockmendel** [comment]
> which are really old legacy formats (just make a note in the whatsnew). The others need to stay as they are written in PY2 and should still be readable (as these are really just tests of encoding).

Putting together a PR for this in the next pass.  What do you have in mind for the whatsnew?  We already have a "Panel is removed" entry with a growing list of associated issues/PRs

Can we entirely remove some subset of the classes in io.pytables?  e.g. LegacyTable and subclasses?

**Comment by simonjayhawkins** [comment]
> Putting together a PR for this in the next pass

@jbrockmendel : you will be removing..?

./pandas/tests/indexing/multiindex/test_panel.py
./pandas/tests/indexing/test_panel.py
./pandas/tests/test_panel.py

**Comment by jbrockmendel** [comment]
I got stuck on some of the IO tests where pickle and msgpack files need to be rebuilt.  Feel free to pick up the baton with these.

**Comment by simonjayhawkins** [comment]
when changing to pytest.raises context manager, i skipped `./pandas/tests/test_panel.py`, so i'll look at removing that one first.

**Pull request merged**
