### PR TITLE
Update v0.16.2.txt

### PR DESCRIPTION
**Pull request by fbrundu**
Added description of Pull Request 9544

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Can you add this to the PR itself? Just commit this on the branch you are using there and push again.

**Comment by fbrundu** [comment]
Ok, because I had a old fork and I didn't know if I could push correctly.

**Comment by jorisvandenbossche** [comment]
No problem! If you have questions with git, just ask! (here or in our dev chat room https://gitter.im/pydata/pandas)

**Comment by fbrundu** [comment]
Thanks :)

**Pull request closed without merging**
