### PR TITLE
BUG: passing TDA and wrong freq to TimedeltaIndex

### PR DESCRIPTION
**Pull request by jbrockmendel**
Caught while working towards making TimedeltaArray._simple_new more strict about its inputs.

- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by jorisvandenbossche — COMMENTED** [review]
Are there perf implications of going through `_from_sequence` instead of `_shallow_copy` / `_simple_new` ?

**Comment by jbrockmendel** [comment]
> Are there perf implications of going through _from_sequence instead of _shallow_copy / _simple_new ?

Yes, this removes two fast-paths.  The alternative is adding the relevant checks to those fastpaths, but I prefer to avoid the duplication that entails.



```
In [3]: tdi = pd.timedelta_range("1 day", periods=10000)                                                                                                                                                                                                
In [4]: tda = tdi._data                                                                                                                                                                                                                                 
In [5]: %timeit pd.TimedeltaIndex(tdi)                                                                                                                                                                                                                  
7.48 µs ± 261 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)   # <-- master
20.6 µs ± 210 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)   # <-- PR

In [6]: %timeit pd.TimedeltaIndex(tda)                                                                                                                                                                                                                  
4.93 µs ± 49.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)   # <-- master
17.4 µs ± 317 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)   # <-- PR
```

Once this bug is fixed, we'll be able to simplify TDA/TDI._simple_new which should make up some lost ground.

Also there's an easy optimization to make in sequence_to_td64ns that brings the times here to 15.5us and 11.9us, respectively.

**Comment by jbrockmendel** [comment]
I guess we could just add `and freq is None` to the TDA check and keep the fastpaths.

**Comment by jorisvandenbossche** [comment]
> I guess we could just add and freq is None to the TDA check and keep the fastpaths.

That sounds good to me as well. In any case, I would find it a bit strange that passing an TimedeltaArray to TimedeltaIndex(..) wouldn't be a relatively fast path.

**Comment by jbrockmendel** [comment]
updated to restore fastpath, just skips it if freq is non-None

**Comment by jreback** [comment]
thanks, if we don't have already, some asvs on Index constructions from equiv Arrays would be good.

**Pull request merged**
