### PR TITLE
CI/TST: use https to avoid ResourceWarning in html tests

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
See #36467 
(no idea if this would actually fix anything, just mimicking what @alimcmaster1 did in https://github.com/pandas-dev/pandas/pull/36480)

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jorisvandenbossche** [comment]
At least it passed once .. ;)

**Comment by jorisvandenbossche** [comment]
Also passed a second time, so let's merge to see what happens

**Comment by jorisvandenbossche** [comment]
@simonjayhawkins is this something that needs to be backported?

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins is this something that needs to be backported?

the coverage build is failing on 1.1.x, #37309, so no need to backport for now.

**Pull request merged**
