### PR TITLE
CLN/REF: stop allowing iNaT in DatetimeBlock

### PR DESCRIPTION
**Pull request by jbrockmendel**
Sits on top of #27411 

xref #16674.  The broader goal is de-special-casing code in internals.

### CODE REVIEW

**Comment by jreback** [comment]
ok will look after resolve / merge #27411

**Comment by jreback** [comment]
lgtm. can you rebase just to be sure. ping on green.

**Comment by jbrockmendel** [comment]
ping

**Comment by jreback** [comment]
thanks

**Pull request merged**
