### PR TITLE
CI/WEB: Use Github token to authenticate API calls

### PR DESCRIPTION
**Pull request by mroeschke**
Hopefully to help the doc and web build sometimes failing because of hitting the rate limit of the GIthub API

```
Traceback (most recent call last):
  File "web/pandas_web.py", line 403, in <module>
    main(args.source_path, args.target_path, args.base_url, args.ignore_io_errors)
  File "web/pandas_web.py", line 349, in main
    context = get_context(config_fname, ignore_io_errors, base_url=base_url)
  File "web/pandas_web.py", line 305, in get_context
    context = preprocessor(context)
  File "/home/runner/work/pandas/pandas/web/pandas_web.py", line 172, in maintainers_add_info
    resp.raise_for_status()
  File "/home/runner/micromamba/envs/test/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/users/shoyer

```

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Did this work locally? My impression was, that multiple doc builds were running on the same machine which caused us to hit the limit.

**Comment by lithomas1** [comment]
Haven't looked into this closely, but maybe the problem is that we have too many maintainers 🤣  , causing us to hit the API rate limit(I think it's set really low by default by Github).

We should probably figure out a way to use the GITHUB_TOKEN to call the API on CI, and fall back to unauthenticated API use when its not present(e.g. developing locally).
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api

**Comment by mroeschke** [comment]
Changed to use the `GITHUB_TOKEN` if available as an environment variable. Looks to be building the site correctly in the CI

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
Thx, lets give it a shot

**Pull request merged**
