### PR TITLE
Update ecosystem.md

### PR DESCRIPTION
**Pull request by sqali**
Hi @lithomas1 ,

This pull request has been raised to update the documentation file - ecosystem.md. As discussed in issue #53451, I have replaced the deprecated qgrid with the modin-spreadsheet in the ecosystem.md file. I am new to open source, kindly let me know if any modifications need to be made.

### CODE REVIEW

**Comment by sqali** [comment]
Hi @datapythonista ,

I have updated the documentation, and all the CI/CD checks have passed. Kindly review it.

**Comment by sqali** [comment]
Hi @datapythonista ,

Kindly review this.

**Comment by sqali** [comment]
Hi @datapythonista  @lithomas1 ,

Kindly review this.

**Review by lithomas1 — APPROVED** [review]

**Comment by lithomas1** [comment]
thanks @sqali

**Pull request merged**
