### PR TITLE
Relocate exceptions #14800

### LINKED ISSUE #14800: DEPR: relocate exceptions in pandas.core.common
move these to ``pandas.api.exceptions``

using ``pandas.util.depr_module`` this should be straightforward

### PR DESCRIPTION
**Pull request by m-charlton**
- [x] closes #14800
 - [x] tests added / passed
 - [x] passes ``git diff master | flake8 --diff``
 - [x] whatsnew entry

Deprecation warnings will only be issued when exceptions/warnings are raised. I did think of 
putting a deprecation warning in ``pandas.common.core`` indicating that these exceptions 
were deprecated but these would be seen when *anything* was imported from ``pandas.core.common``. Please advise.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I think we had the same problem before (I seem to remember this from #14479), but decorating exceptions does not seem to work in practice:

```
In [1]: from pandas.core.common import UnsortedIndexError

In [2]: try:
   ...:     raise pd.api.exceptions.UnsortedIndexError()
   ...: except UnsortedIndexError:
   ...:     print('catched')
   ...:     
---------------------------------------------------------------------------
UnsortedIndexError                        Traceback (most recent call last)
<ipython-input-2-c3dad543bd57> in <module>()
      1 try:
----> 2     raise pd.api.exceptions.UnsortedIndexError()
      3 except UnsortedIndexError:

UnsortedIndexError: 

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-c3dad543bd57> in <module>()
      1 try:
      2     raise pd.api.exceptions.UnsortedIndexError()
----> 3 except UnsortedIndexError:
      4     print('gevangen')
      5 

TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by m-charlton** [comment]
O.K. Will wait further instructions.

**Comment by jreback** [comment]
so I think what you have to do here, is add an option to ``_DeprecatedModule`` to allow it to function as an entire proxy module, but not to show the deprecation warning, except on the removals.

IOW, we want to proxy ``pandas.core.common``, and if its a ``_removals``, then show the deprecation message.

So if you add an option (default it to True), to show the ``DeprecationWarning`` for the module itself (but when you call it here, you will pass False). add the ``_removals`` for the exceptions, this could work.

the ``_add_proxy`` is wrapping a function around the exception which doesn't work (and I don't think we are actually using this anywhere)

**Comment by jreback** [comment]
closing in favor of #15541

**Pull request closed without merging**
