### PR TITLE
STYLE: replace unwanted-patterns-strings-to-concatenate with ruff #51406 #51591

### PR DESCRIPTION
**Pull request by harsimran44**
issue

### CODE REVIEW

**Comment by harsimran44** [comment]
can u help me with this error please

**Comment by harsimran44** [comment]
Capture

**Comment by MarcoGorelli** [comment]
sorry, there's already an open PR for this, from someone who had already been assigned

if you're interested in working on an issue, please comment `take` so it's assigned to you (as per the contributing guide)

**Comment by harsimran44** [comment]
take

**Comment by harsimran44** [comment]
sorry i wasn't able to solve the issue in time. can u guide me to do next

**Pull request closed without merging**
