### PR TITLE
BUG: recognize M8[ns, tzstr]

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

ATM `dtype == "M8[ns, UTC]"` fails while `dtype == "datetime64[ns, UTC]"` succeeds

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Is this needed to support? (what's the use case?) 
M8 is a numpy short-hand name, but tz-aware dtype is not a numpy dtype.

**Comment by jreback** [comment]
lgtm.

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
see comment

**Comment by jreback** [comment]
> see comment

I find this ok, all we are asserting here is that `datetime64==M8` which is true

**Comment by jbrockmendel** [comment]
> Is this needed to support? (what's the use case?)

needed?  No.  convenient?  yes.

Until recently there as a test that checked `dtype == "M8[ns, US/Eastern]"` that would have failed if it wasn't missing the "assert".

**Comment by jorisvandenbossche** [comment]
What is the convenience? Just less typing?

**Comment by jbrockmendel** [comment]
> What is the convenience? Just less typing?

Sure.  Or maybe "lease surprise" is more accurate.  e.g. `is_dtype_equal(dtpye, "M8[ns, US/Eastern]")` is True ATM while `dtype == "M8[ns, US/Eastern]"` is False

**Comment by jorisvandenbossche** [comment]
OK, but then it is fixing a bug, not providing something for convenience. 

Eg, it seems that `pd.Series([1, 2, 3]).astype("M8[ns, UTC]")` already worked. Then of course `.dtype == "M8[ns, UTC]"` should also work. 
Do you know if it is tested that `astype` / `pandas_dtype(..)` works with this notation? If not, can you add a test for that?

**Comment by jbrockmendel** [comment]
> If not, can you add a test for that?

added

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request merged**
