### PR TITLE
DOC: Set verbose parameter as deprecated in docstring

### LINKED ISSUE #57451: DOC: Parameter verbose does not appear as deprecated
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_table.html

### Documentation problem

The parameter "verbose" was deprecated in 2.2.0 but this fact does not appear in the corresponding docstrings. See:
- #56556

### Suggested fix for documentation

The "deprecated" Sphinx directive should be added to the docstring.

### PR DESCRIPTION
**Pull request by albertvillanova**
This PR follows:
- #56556

TODO:
- [x] closes #57451
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm, thanks for taking care of this @albertvillanova

**Comment by phofl** [comment]
thx

**Comment by datapythonista** [comment]
There was a problem with the previewer, seems like GitHub only returns the first 30 elements of a request by default, we've got more than 30 jobs, and the job we needed to download the artifact wasn't being returned. I increased the number of returned items to 100, the maximum, and seems like the preview is working again.

This is rendering as expected:

https://pandas.pydata.org/preview/pandas-dev/pandas/57450/docs/reference/api/pandas.read_csv.html

Thanks again @albertvillanova and sorry for the noise.

**Pull request merged**
