### PR TITLE
ENH: port time.pxd from cython

### PR DESCRIPTION
**Pull request by jbrockmendel**
Until cython3 is out, we port it here.  This will allow a cython implementation of dateutil's tzlocal, which will [yak-shaving] for non-nano dt64/td64.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Review by mroeschke — CHANGES_REQUESTED** [review]
Actually, looks like this doesn't build on windows?

```
building 'pandas._libs.tslibs.ctime' extension
ctime.c
pandas\_libs/tslibs/ctime.c(2383): error C2039: 'tm_zone': is not a member of 'tm'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\corecrt_wtime.h(26): note: see declaration of 'tm'
pandas\_libs/tslibs/ctime.c(2383): error C2198: 'PyBytes_FromString': too few arguments for call
pandas\_libs/tslibs/ctime.c(2386): error C2039: 'tm_gmtoff': is not a member of 'tm'
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\corecrt_wtime.h(26): note: see declaration of 'tm'
pandas\_libs/tslibs/ctime.c(2386): error C2198: '__Pyx_PyInt_From_long': too few arguments for call
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

**Comment by jbrockmendel** [comment]
> Actually, looks like this doesn't build on windows?

Well that doesn't look good.  @scoder area the analogous tests not run on any windows builds in the cython CI?

**Comment by scoder** [comment]
> are the analogous tests not run on any windows builds in the cython CI?

`libc/time.pxd` is different in 0.29.x. It still contains two struct fields that were commented out in 3.0 because they are GNU specific. Removing them from 0.29.x would be a backwards incompatible change, though.

https://github.com/cython/cython/blob/f0ccd6851e80654585fa6acb7a0626bf615857fe/Cython/Includes/libc/time.pxd
https://github.com/cython/cython/commit/1a6bba912fee840fc32b6a4d3288d57a12369820

Note that the field declarations shouldn't hurt as long as you're not trying to (auto-)convert the struct into a Python dict. So you can probably get by with adapting the tests.

**Comment by mroeschke** [comment]
> pandas/tests/tslibs/test_ctime.py:10: error: Module "pandas._libs.tslibs" has no attribute "ctime"  [attr-defined]

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
