### PR TITLE
DOC fix EX02 algorithms.factorize docstring

### PR DESCRIPTION
**Pull request by albuzenet**
- [x] Part of #51236
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Towards #51236.

Fix EX02 docstring errors for :

`pandas.factorize`
`pandas.Index.factorize`
`pandas.Series.factorize`

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
thanks! can you remove them from the excludes list?

**Comment by albuzenet** [comment]
Done. Thanks for the review @MarcoGorelli

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Looks like these are failing

```
Error: /home/runner/work/pandas/pandas/pandas/core/base.py:1138:EX02:pandas.Index.factorize:Examples do not pass tests:
**********************************************************************
Line 53, in pandas.Index.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1, 2, 0], dtype=int64)
Got:
    array([0, 0, 1, 2, 0])
**********************************************************************
Line 62, in pandas.Index.factorize
Failed example:
    codes
Expected:
    array([1, 1, 0, 2, 1], dtype=int64)
Got:
    array([1, 1, 0, 2, 1])
**********************************************************************
Line 72, in pandas.Index.factorize
Failed example:
    codes
Expected:
    array([ 0, -1,  1,  2,  0], dtype=int64)
Got:
    array([ 0, -1,  1,  2,  0])
**********************************************************************
Line 83, in pandas.Index.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1], dtype=int64)
Got:
    array([0, 0, 1])
**********************************************************************
Line 97, in pandas.Index.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1], dtype=int64)
Got:
    array([0, 0, 1])
**********************************************************************
Line 107, in pandas.Index.factorize
Failed example:
    codes
Expected:
    array([ 0,  1,  0, -1], dtype=int64)
Got:
    array([ 0,  1,  0, -1])
**********************************************************************
Line 113, in pandas.Index.factorize
Failed example:
    codes
Expected:
    array([0, 1, 0, 2], dtype=int64)
Got:
    array([0, 1, 0, 2])

Error: /home/runner/work/pandas/pandas/pandas/core/base.py:1138:EX02:pandas.Series.factorize:Examples do not pass tests:
**********************************************************************
Line 53, in pandas.Series.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1, 2, 0], dtype=int64)
Got:
    array([0, 0, 1, 2, 0])
**********************************************************************
Line 62, in pandas.Series.factorize
Failed example:
    codes
Expected:
    array([1, 1, 0, 2, 1], dtype=int64)
Got:
    array([1, 1, 0, 2, 1])
**********************************************************************
Line 72, in pandas.Series.factorize
Failed example:
    codes
Expected:
    array([ 0, -1,  1,  2,  0], dtype=int64)
Got:
    array([ 0, -1,  1,  2,  0])
**********************************************************************
Line 83, in pandas.Series.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1], dtype=int64)
Got:
    array([0, 0, 1])
**********************************************************************
Line 97, in pandas.Series.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1], dtype=int64)
Got:
    array([0, 0, 1])
**********************************************************************
Line 107, in pandas.Series.factorize
Failed example:
    codes
Expected:
    array([ 0,  1,  0, -1], dtype=int64)
Got:
    array([ 0,  1,  0, -1])
**********************************************************************
Line 113, in pandas.Series.factorize
Failed example:
    codes
Expected:
    array([0, 1, 0, 2], dtype=int64)
Got:
    array([0, 1, 0, 2])

Error: /home/runner/work/pandas/pandas/pandas/core/algorithms.py:612:EX02:pandas.factorize:Examples do not pass tests:
**********************************************************************
Line 58, in pandas.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1, 2, 0], dtype=int64)
Got:
    array([0, 0, 1, 2, 0])
**********************************************************************
Line 67, in pandas.factorize
Failed example:
    codes
Expected:
    array([1, 1, 0, 2, 1], dtype=int64)
Got:
    array([1, 1, 0, 2, 1])
**********************************************************************
Line 77, in pandas.factorize
Failed example:
    codes
Expected:
    array([ 0, -1,  1,  2,  0], dtype=int64)
Got:
    array([ 0, -1,  1,  2,  0])
**********************************************************************
Line 88, in pandas.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1], dtype=int64)
Got:
    array([0, 0, 1])
**********************************************************************
Line 102, in pandas.factorize
Failed example:
    codes
Expected:
    array([0, 0, 1], dtype=int64)
Got:
    array([0, 0, 1])
**********************************************************************
Line 112, in pandas.factorize
Failed example:
    codes
Expected:
    array([ 0,  1,  0, -1], dtype=int64)
Got:
    array([ 0,  1,  0, -1])
**********************************************************************
Line 118, in pandas.factorize
Failed example:
    codes
Expected:
    array([0, 1, 0, 2], dtype=int64)
Got:
    array([0, 1, 0, 2])

Partially validate docstrings (EX02) DONE
```

**Comment by albuzenet** [comment]
The Docstring validation should be good now.

**Review by MarcoGorelli — APPROVED** [review]
yup - thanks @albuzenet !

**Pull request merged**
