### PR TITLE
REF: use CoW helpers more

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@phofl in Block._maybe_copy there is a path where we can pass deep=False to Block.copy.  i think we could simplify things if instead we just returned `self` there.  would that be OK?

**Comment by phofl** [comment]
I’ll have to look into this more, there are scenarios where this could be problematic. This ties a bit into my todo list that’s related to replace. Might get to this over the weekend or next week

**Comment by jbrockmendel** [comment]
> there are scenarios where this could be problematic

Yah, just remembered there are a couple places where we set `block.values` post-`__init__`.  Refactoring to avoid those might make that safer.  I don't think this PR should be affected though.

**Comment by jbrockmendel** [comment]
i think the helper here should be OK?

**Review by phofl — APPROVED** [review]

**Pull request merged**
