### PR TITLE
DEPR: Enforce disallowing loc with positionals

### PR DESCRIPTION
**Pull request by mroeschke**
Introduced in https://github.com/pandas-dev/pandas/pull/31840

### CODE REVIEW

**Comment by jbrockmendel** [comment]
looks like sql asvs failed

**Comment by jbrockmendel** [comment]
the asvs failing here are also failing on some of my PRs, so must be unrelated

**Comment by mroeschke** [comment]
> the asvs failing here are also failing on some of my PRs, so must be unrelated

It looks to have failed on main for https://github.com/pandas-dev/pandas/commit/6b4fa02e10480c4ddae0714e36b7fe765fa42eac, so might be related?

**Comment by mroeschke** [comment]
Merged and green

**Review by jbrockmendel — APPROVED** [review]

**Comment by jbrockmendel** [comment]
thanks @mroeschke

**Pull request merged**
