### PR TITLE
CLN: Fix common spelling mistakes

### PR DESCRIPTION
**Pull request by SaturnFromTitan**
I applied [this awesome automatic spell fixer](https://github.com/vlajos/misspell-fixer) to our codebase. I needed to do a manual review as it was attempting to fix some names, but the false-positive rate was pretty low!

They also provide a GitHub action for automatic checks on PRs. Might be helpful, especially for the `docs`.

If this is merged, I can create a follow-up issue for a discussion on the CI hook.

### CODE REVIEW

**Comment by jreback** [comment]
looks fine ping on green.

**Comment by SaturnFromTitan** [comment]
@jreback CI is green

**Comment by WillAyd** [comment]
Thanks @SaturnFromTitan

**Pull request merged**
