### PR TITLE
 DOC: updated the docstring of Series.dot 

### PR DESCRIPTION
**Pull request by HubertKl**
- [ ] closes #xxxx
- [ ] tests added / passed
- [x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by datapythonista — COMMENTED** [review]
Great PR, added some comments, just minor things.

**Comment by HubertKl** [comment]
Thanks @datapythonista  for the comments! I updated the pull request. 

I did check PEP8 with the command
git diff upstream/master -u -- "*.py" | flake8 --diff
but nothing came out of this. Maybe my PEP8 checker is not well configured...

**Review by datapythonista — APPROVED** [review]
lgtm, thanks @HubertKl 

If you want, may be it would be useful to show in the examples `s @ other` too.

**Comment by HubertKl** [comment]
Thanks for the advice, it looks even better now. I added the s @ other example.

**Comment by datapythonista** [comment]
Thanks @HubertKl

**Pull request merged**
