### PR TITLE
Add warning about HDFStore concurrent reads

### PR DESCRIPTION
**Pull request by yikelu**
Not too much to say; this is a documentation PR.

### CODE REVIEW

**Comment by jreback** [comment]
@yikelu can you update according to above comments?

**Comment by yikelu** [comment]
@jreback I've been incredibly busy, and I haven't figured out the
documentation.

**Comment by jreback** [comment]
@yikelu can you update, pls.

**Comment by jreback** [comment]
closing as stale, but if you would like to reopen and fixup pls do.

**Pull request closed without merging**
