### PR TITLE
BLD: include dll in package_data on Windows

### LINKED ISSUE #21106: Pandas 0.23.0 gives ImportError: DLL load failed
Installed pandas not able to import with:

```
ImportError: DLL load failed: The specified module could not be found.
```

As far as we know, this happens if you install with pip on Windows 32bit machines (if you have another case, please comment below with specifying your OS, Python version, how you installed pandas, ..).

**Workaround for now is to keep your version at pandas 0.22.0.** (or to install using conda, or to install VS tools for C++, see https://github.com/pandas-dev/pandas/issues/21106#issuecomment-391459521)

We will fix this problem for 0.23.1.

---
original post:

#### Code Sample, a copy-pastable example if possible

```python
import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lfletcher\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Users\lfletcher\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "C:\Users\lfletcher\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\pandas\core\groupby\__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "C:\Users\lfletcher\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\pandas\core\groupby\groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Users\lfletcher\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\pandas\core\frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "C:\Users\lfletcher\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\pandas\core\series.py", line 3978, in <module>
    Series._add_series_or_dataframe_operations()
  File "C:\Users\lfletcher\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\pandas\core\generic.py", line 8891, in _add_series_or_dataframe_operation
s
    from pandas.core import window as rwindow
  File "C:\Users\lfletcher\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\pandas\core\window.py", line 36, in <module>
    import pandas._libs.window as _window
ImportError: DLL load failed: The specified module could not be found.

### PR DESCRIPTION
**Pull request by chris-b1**
- [x] closes #21106
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Not sure how to test this, but I believe should remove the runtime dependency by static linking against the MSVC++ runtime.  @cgohlke any thoughts?

### CODE REVIEW

**Comment by cgohlke** [comment]
If I read this correctly, this will not only static link the C++ runtime to one C++ extension, but static link the C multi-threaded runtime library to all Pandas extension modules. That is [not a good idea](https://bugs.python.org/issue25027) since Python can only load a total of ~127 of such DLLs. 

It's probably better to allow distributors to include the C++ runtime DLL,, in the wheels, e.g. 
```diff
diff --git a/setup.py b/setup.py
index 6febe674f..e161b1534 100755
--- a/setup.py
+++ b/setup.py
@@ -733,7 +733,7 @@ setup(name=DISTNAME,
       maintainer=AUTHOR,
       version=versioneer.get_version(),
       packages=find_packages(include=['pandas', 'pandas.*']),
-      package_data={'': ['data/*', 'templates/*'],
+      package_data={'': ['data/*', 'templates/*', '_libs/*.dll'],
                     'pandas.tests.io': ['data/legacy_hdf/*.h5',
                                         'data/legacy_pickle/*/*.pickle',
                                         'data/legacy_msgpack/*/*.msgpack',

```
Distributors could then copy (or not) the C++ runtime DLL to the `_libs` folder before building the wheel.

**Comment by jreback** [comment]
@chris-b1 is this the fix mpl did?

**Comment by chris-b1** [comment]
No, mpl packages the whole DLL.  I thought static linking might be better in terms of limiting ending binary size, but wasn't aware of issue @cgohlke linked.

@cgohlke - wasn't clear to me looking at mpl setup, do you just manually copy DLL over into that directory?  I see the stuff adding it to `package_data` but couldn't figure out how the DLL gets there in the first place.

https://github.com/matplotlib/matplotlib/blob/6ec80eac66c4828f28540f76734cae811787d626/setupext.py#L1770

**Comment by cgohlke** [comment]
> wasn't clear to me looking at mpl setup, do you just manually copy DLL over into that directory? 

Yes, this way it is up to the distributor to copy any required DLL to the `_libs` folder before building the wheel. IMO it is not worth automating this in setup.py because there are many possible Visual Studio versions and use cases to consider. Canopy and Anaconda distributions won't need to package any C/C++ runtime DLL.

**Comment by chris-b1** [comment]
@TomAugspurger - is it correct that the Windows wheels you upload to PyPI are from @cgohlke?  If that's the case, @cgohlke does this work for you?

**Comment by TomAugspurger** [comment]
That's correct.

**Comment by cgohlke** [comment]
> does this work for you?

I'm sure it does for Python 3. The build script will copy `MSVCP140.DLL` and `CONCRT140.DLL` from the Visual Studio redist directory to `pandas\_libs\` before running setup.py, e.g.:
```
copy /Y /B "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT\MSVCP140.DLL" pandas\_libs\
copy /Y /B "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT\CONCRT140.DLL" pandas\_libs\
```

It's probably better not to copy `msvcp90.dll` for Python 2.7. IIRC the Python installer already installs the C++ runtime unless it's a per user installation. The .pyd file may or may not be missing a manifest to load `msvcp90.dll` next to it. I do not have any system for testing without the redistributable package installed. I am not aware of any other package that distributes `msvcp90.dll`, not matplotlib and not pyzmq.

**Comment by jreback** [comment]
does the MANIFEST.in need updating here?

**Comment by jreback** [comment]
@chris-b1 can you rebase. ready to go?

**Comment by chris-b1** [comment]
Just rebased, Should be good, I'm not familiar with MANIFEST.in, but seems to only involve source distributions?

https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute

**Comment by jreback** [comment]
@chris-b1 ok that sounds good then.

**Pull request merged**
