### PR TITLE
Added a New Page in Cheatsheet with some extra functions.

### PR DESCRIPTION
**Pull request by ashishbalti4**
-Added a new page that includes:
- IO Tools
- Visualization
- Data transform functions
- Apply functions.

### CODE REVIEW

**Review by Dr-Irv — CHANGES_REQUESTED** [review]
Any changes to the cheat sheet should be done to the original PPTX files here: 
https://github.com/pandas-dev/pandas/tree/main/doc/cheatsheet

Then push the new PPTX and PDF files. 

Please adjust this PR to not add new files, but to modify the files already in the repo.

**Review by datapythonista — CHANGES_REQUESTED** [review]
Same feedback as in #49180, please open an issue to discuss what to add first, some of what you add doesn't seem to make sense.

**Comment by Dr-Irv** [comment]
> Same feedback as in #49180, please open an issue to discuss what to add first, some of what you add doesn't seem to make sense.

We do have https://github.com/pandas-dev/pandas/issues/40680 that has a bunch of ideas.

But the PR also has to update the correct files!

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
