### PR TITLE
Change check_freq default to False

### LINKED ISSUE #35570: Change the default of `check_freq` to `False` as it breaks existing code
As already mentioned in https://github.com/pandas-dev/pandas/pull/34050 the default of `check_freq` was set to True, which leads to broken code / tests. 

I suggest to change it to `False` as it ensures existing code won't break.

>k thanks. pls open an issue to change this to `check_freq=False`; I *think* this might break downstream, IIRC a comment by @jorisvandenbossche

_Originally posted by @jreback in https://github.com/pandas-dev/pandas/pull/34050#issuecomment-626227446_

### PR DESCRIPTION
**Pull request by MaxWinterstein**
- [x] closes #35570
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
This effectively disables a bunch of existing checks.  passing check_freq=True explicitly in a ton of places is an option i guess.   or could change the default to False and warn that it will become True in a future version

**Review by jreback — CHANGES_REQUESTED** [review]
we need to leave this as true as its more strict; sure it might have broken downstream, but not testing things is not great, so -1 on this PR

**Comment by TomAugspurger** [comment]
And FYI, this came up on the dev call on Wednesday. The consensus was roughly "we didn't mean to change this for 1.1.0, but now that we have it's best to just leave it."

Apologies for the accidental breaking change @MaxWinterstein, and thanks for working on the PR but we'll pass.

In the future, you might want to subscribe to pandas releases by "watching" the repo for "releases only". We make binaries available for release candidates so it should be easy to test.

**Comment by MaxWinterstein** [comment]
> And FYI, this came up on the dev call on Wednesday. The consensus was roughly "we didn't mean to change this for 1.1.0, but now that we have it's best to just leave it."
> 
> Apologies for the accidental breaking change @MaxWinterstein, and thanks for working on the PR but we'll pass.
> 
> In the future, you might want to subscribe to pandas releases by "watching" the repo for "releases only". We make binaries available for release candidates so it should be easy to test.

**First of all, i am totally fine by keeping it that way. No hate.**

I was/am just a little unhappy that this is - in my opinion - a bigger change that should be mentioned in the change logs anywhere. But afaik there is no mention at all. 
As our automated tests on ou rCI failed successfully, there was no hassle or problem on production side, as we keep requirements versioned (as everybody should 😉 ). But when you try to update your requirements and you need to dig inside the projects to find why something is suddenly broken, its a little bit frustrating...

**Comment by TomAugspurger** [comment]
For sure. This was a process failure where we merged a breaking API change to master. That was noticed during review, but a followup issue was never opened.

As I mentioned in the issue, updating the release notes to explain this API change may still be worthwhile since it might help future upgraders.

**Pull request closed without merging**
