### PR TITLE
ENH: Add Series.set_index

### LINKED ISSUE #27058: ENH: add Series.set_index
```python
import pandas as pd
 
dates=[
"2001-01-01 23:50",
"2001-01-02 14:00", 
"2001-01-03 00:08"] 
 
ser=pd.Series(range(3),pd.DatetimeIndex(dates))
```

sometimes when writing a sequence of operation, you want to replace the index of the object you're working on. Say, quantizing the dates. I can't find the .method way of doing
``
ser.index= expr
``
So that I can't write something like
```
(ser
      .replace_index(ser.index.floor("D"))    # < this doesn't exist
      .rolling("5d")
       .sum()
```

Things that don't solve this:
- `reindex` is aligning, so if your new index permutes the indexes, it isn't suitable. 
- `set_index` <del>takes a column name, not an expression</del>, and isn't available on series. **update** works for frames, though you must provide an arraylike, not a listlike.
- `reindex_like` expects a PandasObject instead of a listlike, and is aligning
- `reset_index` does not take a values argument

```
In [1]: [_ for _ in dir(ser) if 'index' in _ and not _.startswith("_")]
Out [1]: 
['first_valid_index',
 'index',
 'last_valid_index',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'reset_index',
 'sort_index']
```

### PR DESCRIPTION
**Pull request by ghost**
- [X] closes #27058, #21684
- [X] whatsnew entry
- [x] append and list of levels (like `DataFrame.set_index` has)
- [ ] tests added / passed

Help users method-chain all the things. This is modeled closely on the original support for Arrays added in 2011 by Wes Mckinney in   

553bacc7abe341991e4d043a5c17521902c7f127 `ENH: can pass external arrays in lieu of column names to DataFrame.set_index`

This is also how `DataFrame.set_index` behaves (though poorly documented), modulo support for column keys which don't apply here.

related discussion #24046, and end of https://github.com/pandas-dev/pandas/issues/14829#issuecomment-404884912, https://github.com/pandas-dev/pandas/issues/12392

### CODE REVIEW

**Comment by WillAyd** [comment]
I think this has the same issue as the previous PR where the semantics for a Series now break from a DataFrame as the former here accepts list-likes whereas the latter is used for labels.  

Haven't kept totally current on this - was this approach ever agreed to in one of the issues or are you just submitting to restart conversation?

**Comment by pilkibun** [comment]
I wasn't aware of previous discussion, I just saw that issue when I opened the PR. Let me read up on the previous discussion.

**Comment by WillAyd** [comment]
So to maybe get you up to speed here the semantics of this PR would differ from a DataFrame. Taking your first test case this:

```python
# Sets the index as "A", "B", "C"
>>> pd.Series(range(3)).set_index(["A", "B", "C"])
A    0
B    1
C    2
dtype: int64
```

Would exhibit different behavior than what happens on a DataFrame with the same number of rows

```python
# Selects columns "A", "B", "C" and moves to the index
>>> pd.DataFrame(np.ones((3,3)), columns=list('ABC')).set_index(["A", "B", "C"])
Empty DataFrame
Columns: []
Index: [(1.0, 1.0, 1.0), (1.0, 1.0, 1.0), (1.0, 1.0, 1.0)]
```

So in a vacuum this PR would make sense but given the current state of things would need to have something additional to bridge behavior between the two object types.

**Comment by pilkibun** [comment]
> So to maybe get you up to speed here 

Thanks! before we get into this. I think the docstring for DataFrame.set_index has grew in piecs over the years and could use a little TLC. I've submitted #27513 for review which update it. And let's come back to this after.

**Comment by pilkibun** [comment]
So I understand this usage of `set_index` is unoffically frowned upon but not yet officially deprecated, and that `set_axis` is not well-known but meant to serve this purpose. Note that in the issue I opened, a user suggested that DataFrame does this, but didn't know about `set_axis` either. 

It would be nice to deal with the deprecation before 1.0.0. So, I've updated the PR to  closely follow `DataFrame.set_index`'s behavior and I'd liek to suggest suggest merging this, but also immediately deprecating this case in both DataFrame/Series with a message redirecting users towards `set_axis`.

**Comment by pilkibun** [comment]
> Would exhibit different behavior than what happens on a DataFrame with the same number of rows

Fixed. I've updated the code to follow `DataFrame.set_index` more closely. lists of lists are now not allowed, and I added a test for this.

I realize the heated discussion in the other thread makes it impossible to merge this. I'm Keeping the PR open in hopes that will be resolved in the future.

**Comment by pilkibun** [comment]
> Would exhibit different behavior than what happens on a DataFrame with the same number of rows

Fixed. I've updated the code to follow `DataFrame.set_index` more closely and added your example as a test 

I realize the heated discussion in the other thread makes it impossible to merge this. I'm Keeping the PR open in hopes that will be resolved in the future.

**Comment by pilkibun** [comment]
This is very contentious issue among the maintainers it seems, and considering how #22225 ended, seems unlikely this is going anywhere.

**Pull request closed without merging**
