### PR TITLE
CI: enable auto-cancel for GitHub Actions

### PR DESCRIPTION
**Pull request by fangchenli**

### CODE REVIEW

**Comment by fangchenli** [comment]
It's working correctly. I got email notifications when previous jobs were canceled.

**Comment by MarcoGorelli** [comment]
What does auto-cancel do?

**Comment by fangchenli** [comment]
> What does auto-cancel do?

A new commit will cancel all unfinished builds. So only the CI only runs for the latest commit.

**Review by MarcoGorelli — APPROVED** [review]
nice!

**Review by jbrockmendel — COMMENTED** [review]
LGTM

**Comment by jreback** [comment]
thanks @fangchenli very nice!

**Comment by fangchenli** [comment]
Maybe we should turn this off for the master branch. Or find a way to mark canceled jobs as 'success'.

**Pull request merged**
