### PR TITLE
ENH: improve bigquery connector to optionally allow use of gcloud credentials

### LINKED ISSUE #8489: BigQuery authentication on remote servers
Hello, I can't get the BigQuery auth to work on remote servers:

```
WARNING:root:This function, oauth2client.tools.run(), and the use of the gflags library are deprecated and will be removed in a future version of the library.
Your browser has been opened to visit:

    big-url-here

If your browser is on a different machine then exit and re-run
this application with the command-line parameter

  --noauth_local_webserver
```

Even if I try to open that URL on my workstation, it tries to redirect me to a local server. The documentation says that:

>Should the browser not be available, or fail to launch, a code will be provided to complete the process manually.

however, I've yet to see this alternative.

Any help?

### PR DESCRIPTION
**Pull request by ichuang**
closes #8489

The pandas google bigquery connector can be difficult to use from an ipython notebook: when no authentication token exists, it fails silently (and can hang the notebook).  This happens because the oauth2client library is trying to bring up a browser on the console, to request an auth token.  

This PR provides an improved mechanism: an optional `use_gcloud_auth` argument which specifies that the user wants to employ a pre-existing authentication token, generated using [gcloud auth login](https://cloud.google.com/sdk/gcloud/reference/auth/login).  An error is raised if the credentials file is missing.

### CODE REVIEW

**Comment by jacobschaer** [comment]
@jreback - Can we get this merged in soon as well? Tests passed fine.

**Comment by jreback** [comment]
needs a release note (enhancement section), maybe update on the docs? 
pls also squash

**Comment by jreback** [comment]
These tests appear to all be skipped because of an import issue: https://travis-ci.org/pydata/pandas/jobs/41446098

can you have a look?

**Comment by jacobschaer** [comment]
@ichuang, or @shaun-schaefer - Are these skips expected? I don't see why they would skip for the import error - so think the CI requirements calls for all the needed libs? Also, can you rebase and fix docs?

**Comment by sean-schaefer** [comment]
I double checked the Travis logs on that job and something strange happened with the install of the Google API client. The logs recognize it as a dependency and fetch the package, seems like everything goes well there. But if you look at the output of ci/print_versions.py after all the tests run, the version of the apiclient is None.

I'll try and look into it more soon.

**Comment by jreback** [comment]
can u rebase this?

**Comment by jacobschaer** [comment]
@jreback - Who is the Travis CI point of contact?

**Comment by jreback** [comment]
in Travis itself - I just email them thru their help facility - if u have question on pandas side ask away

**Comment by jacobschaer** [comment]
The problem with the Travis skipping all those tests seems to be that the optional dependencies aren't being installed properly. This seems unique to Travis, when I build locally (pip) all the dependencies are pulled correctly. You can see that the conda install script does attempt to download and install them, but when it goes to print out the version strings they aren't there. @Sean-Schaefer was also running into some SSL issues with a couple of the packages when he tried to alter our test script to attempt to catch exactly what deps are failing.

**Comment by jreback** [comment]
closing pls reopen if/when updated

**Pull request closed without merging**
