### PR TITLE
DOC: Fix version switcher

### LINKED ISSUE #53180: DOC: Doc version slider is broken (no options)
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Any page with the version slider, e.g
https://pandas.pydata.org/docs/development/contributing_codebase.html

### Documentation problem

image

### Suggested fix for documentation

I should be able to select other versions of pandas from the slider.

@datapythonista Any idea whats going on here?

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #53180

### CODE REVIEW

**Comment by mroeschke** [comment]
This is the same error I was getting in my earlier branch

```
2023-05-11T18:16:18.6054339Z WARNING: The version switcher "https://pandas.pydata.org/versions.json" file cannot be read due to the following error:
2023-05-11T18:16:18.6055458Z HTTPError('404 Client Error: Not Found for url: https://pandas.pydata.org/versions.json')
```

**Comment by datapythonista** [comment]
I think the error is because the CI docs build is looking for the production versions file, which it doesn't exist right now, but it'll exist after merging. So I'm going to merge this, and I think the next docs build should work.

**Comment by datapythonista** [comment]
Ok, it's a bit trickier, if I merge the next build will also fail before creating the file. I created the file manually in production and I'm rerunning. If it works, I'll merge, and when the docs build syncs with prod, it'll start rewriting the file.

If something is merge before this, it'll delete the file again, but I'll just recreate it until this works.

**Comment by mroeschke** [comment]
Thanks for investigating @datapythonista . Feel free to merge when ready

**Comment by datapythonista** [comment]
CI is green, and the file is still there, I think everything should be fine once the CI of the merge completes.

**Pull request merged**
