### PR TITLE
Plotting Tables x-axis labels display

### PR DESCRIPTION
**Pull request by marydmit**
Added x-axis labels on top. Adjusted figure sizes in order to have the complete table visible in the user guide.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@marydmit you already have an open PR for this at https://github.com/pandas-dev/pandas/pull/34884 ?

**Comment by marydmit** [comment]
Sorry, I may have done something wrong! I was working on another issue in the visualization rst, submitted a PR, then worked on the plotting tables part in the same doc. I am new to this, so not sure if this should be in the same PR or two different ones?

**Comment by MarcoGorelli** [comment]
Yes, it seems that #34884 includes everything from this branch. If you intended to keep them separate, you should make sure to reset to `master` when you open a new branch - I usually do
```bash
git checkout -b <my new branch>
git fetch upstream master
git reset --hard upstream/master
```
just to be sure

For this time I think it's OK to carry on in the other PR :)

**Comment by MarcoGorelli** [comment]
Closing as it's been taken forward in #34884

**Pull request closed without merging**
