### PR TITLE
ENH: Explode multiple columns of DataFrame

### PR DESCRIPTION
**Pull request by kylestahl**
Now .explode() can take a list of column names and will explode multiple at the same time (given that each element across all the columns have the same length in every single row
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
always add tests first

**Comment by WillAyd** [comment]
Just a heads up - this was part of the original implementation in #27267 so you can check there for inspiration on tests and implementation. The big blocker there though was how to handle duplicate values, i.e. whether we should generate a cartesian product or not. Do you know how other similar tools would handle that?

**Comment by stahl085** [comment]
Thanks for the info, I like that #27267 implementation much better!
By duplicate do you mean the user passes in the same column name twice? ex: ['A', 'A']

I haven't seen this implemented elsewhere, but to me it seems un-natural for this to return a cartesian product. Would it make sense to include that as an optional argument `cartesian=False`?

**Review by jreback — CHANGES_REQUESTED** [review]
this would need a number of tests; the impl will be very  non-performant, so needs updating.

**Pull request closed without merging**
