### PR TITLE
BLD: minor break ci/requirements-optional-pip.txt

### LINKED ISSUE #22595: KeyError on master in TestExcelWrtiter
https://travis-ci.org/pandas-dev/pandas/jobs/424485100 isn't master, but it's seeminglyon other PRs. e.g. https://travis-ci.org/pandas-dev/pandas/jobs/424480841#L2253

```
______________ TestExcelWriter.test_tsframe[openpyxl-.xlsx-True] _______________
[gw0] darwin -- Python 3.5.6 /Users/travis/miniconda3/envs/pandas/bin/python
self = <pandas.tests.io.test_excel.TestExcelWriter object at 0x1148ad9b0>
merge_cells = True, engine = 'openpyxl', ext = '.xlsx'
    def test_tsframe(self, merge_cells, engine, ext):
        df = tm.makeTimeDataFrame()[:5]
    
>       df.to_excel(self.path, 'test1')
pandas/tests/io/test_excel.py:1153: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pandas/core/frame.py:1749: in to_excel
    engine=engine)
pandas/io/formats/excel.py:658: in write
    freeze_panes=freeze_panes)
pandas/io/excel.py:1419: in write_cells
    xcell.value, fmt = self._value_with_fmt(cell.val)
../../../miniconda3/envs/pandas/lib/python3.5/site-packages/openpyxl/cell/cell.py:291: in value
    self._bind_value(value)
../../../miniconda3/envs/pandas/lib/python3.5/site-packages/openpyxl/cell/cell.py:193: in _bind_value
    self._set_time_format(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <Cell 'test1'.A2>, value = Timestamp('2000-01-03 00:00:00', freq='B')
    def _set_time_format(self, value):
        """Set number format for Python date or time"""
        fmts = {
            datetime.datetime:numbers.FORMAT_DATE_DATETIME,
            datetime.date:numbers.FORMAT_DATE_YYYYMMDD2,
            datetime.time:numbers.FORMAT_DATE_TIME6,
            datetime.timedelta:numbers.FORMAT_DATE_TIMEDELTA,
                }
>       self.number_format = fmts[type(value)]
E       KeyError: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
```

Trying to reproduce locally now.

### PR DESCRIPTION
**Pull request by minggli**
- [x] closes #22595 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

When adding optional dependencies, below error appears from 

> Invalid requirement: 'openpyxl=2.5.5'
> = is not a valid operator. Did you mean == ?

To core dev, should we fix the version or simply specify lower bound (i.e. >=)?

### CODE REVIEW

**Comment by datapythonista** [comment]
Thanks for the PR @minggli. Those files are autogenerated. Can you check the comments in this PR: #22749 and fix in the source file please (and then autogenerate the ones you changed)?

**Comment by datapythonista** [comment]
I think we want that specific version of openpyxl, so it'd be `openpyxl=2.5.5` (not `>=`). Can you confirm @TomAugspurger

**Review by datapythonista — APPROVED** [review]
Cool, I didn't remember that. Lgtm. Thanks for the fix @minggli

**Review by datapythonista — CHANGES_REQUESTED** [review]
Sorry, I think I misunderstood. If I understand correctly, the conda file required one equal only (so you shouldn't add the extra one), and the script `convert_deps.py` should be updated to make it two in the pip file. And after that generate the pip file.

**Review by datapythonista — APPROVED** [review]
lgtm

It can surely be in a separate PR, but I think at some point it'd be nice to have a single function in the script that we call twice (one for required and one for optional), and that we unit test.

**Comment by jreback** [comment]
thanks. this is a dev requirement only.

**Comment by minggli** [comment]
thanks for reviewing @jreback @datapythonista @TomAugspurger!

**Pull request merged**
