### PR TITLE
DOC: updated required dependencies list

### LINKED ISSUE #54492: DOC: tzdata should be listed as a required dependency since 2.0.0
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/getting_started/install.html#dependencies

### Documentation problem

Since pandas 2.0.0, tzdata has been required.

### Suggested fix for documentation

Add tzdata into required dependencies list.

### PR DESCRIPTION
**Pull request by rsm-23**
- [x] closes #54492 
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Comment by rsm-23** [comment]
@alimcmaster1 tagging as reviewer

**Comment by mroeschke** [comment]
@MarcoGorelli could you remind me why we added tzdata as a required dependency?

**Comment by asishm-wk** [comment]
> @MarcoGorelli could you remind me why we added tzdata as a required dependency?

added here https://github.com/pandas-dev/pandas/pull/51247

**Comment by alimcmaster1** [comment]
> @MarcoGorelli could you remind me why we added tzdata as a required dependency?

Think its a PEP 615 thing - zoneinfo only works on certain platforms.
https://peps.python.org/pep-0615/#abstract

**Comment by mroeschke** [comment]
Right but I'm curious why we didn't make this dependency platform specific

**Comment by MarcoGorelli** [comment]
On my phone, but IIRC that was a request from @lithomas1

**Comment by lithomas1** [comment]
I don't think it's necessary on all platforms but doesn't hurt.

We are able to enforce that tzdata exists (the db isn't guaranteed to exist on all platforms) and also enforce a minimum version by putting it as a dep.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @rsm-23

**Pull request merged**
