### PR TITLE
TST: Check series names

### PR DESCRIPTION
**Pull request by sinhrks**
Related to #9972. Made `assert_series_equal` to check name attribute.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. any things that we need to put to watch out for in the future? e.g. where you needed to do ``check_names=False`` but couldn't check the name?

**Comment by sinhrks** [comment]
As far as I know:

- ``eval`` using ``numexpr`` (#10239)
- ``value_counts`` (#10150)

But we may find further when adding ``name`` attribute to all ``Series`` in test cases.

**Comment by jreback** [comment]
@sinhrks but you are testing this no? (e.g. you added it and fixed what was necessary)

**Comment by sinhrks** [comment]
Ah, I meant the ``name`` attributes of existing test cases are all tested. But I didn't change test cases which uses ``Series(..., name=None)`` yet, and adding explicit name may reveal further problem. 

I'll continue to work on ``Index`` and ``Series`` metadata issues, hopefully change all test cases to have explicit name assignment like below (intends to be a fix for #10150):

- https://github.com/pydata/pandas/compare/master...sinhrks:base_name_handling

**Comment by jreback** [comment]
ahh, I see. cool. ok let's merge this. thanks!

**Pull request merged**
