### PR TITLE
style: fix import format at pandas/core/reshape

### PR DESCRIPTION
**Pull request by streeck**
- [ ] xref #23334
- [x] passes `git diff master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by thoo** [comment]
@streeck You got error in Travis due to `/pandas/core/reshape/pivot.py:25:1: E303 too many blank lines (3)` . You can locally run flake8 on `pivot.py` to make sure it is in a proper format.

**Comment by jreback** [comment]
can you merge master, we just updated the isort cfg

**Comment by streeck** [comment]
Done 👍

**Comment by jreback** [comment]
not passing, pls see if you can fix up.

**Comment by streeck** [comment]
Looks like I need to run the sort of imports again for some reason 🤔

**Comment by jreback** [comment]
yes, the isort config changed slightly to reorder some things. pls ping on your open PR's when done.

**Comment by streeck** [comment]
@jreback This one looks like it's good to go again 😃

**Comment by jreback** [comment]
thanks!

**Pull request merged**
