### PR TITLE
CI: Pin micromamba to 1.x

### PR DESCRIPTION
**Pull request by rhshadrach**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by rhshadrach** [comment]
Merging to restore the CI.

**Comment by rhshadrach** [comment]
@jorisvandenbossche @WillAyd @lithomas1 - do we want to backport this? I can do so if desired.

**Comment by WillAyd** [comment]
Most likely - I'll take a look when I give the branch another pass. Thanks!

**Comment by jorisvandenbossche** [comment]
@MeeseeksDev backport to 2.3.x

**Pull request merged**
