### PR TITLE
BUG: wrong exception raised by Week+Day

### PR DESCRIPTION
**Pull request by jbrockmendel**
With that fixed, we can clean up an Exception in tseries.frequencies.

### CODE REVIEW

**Comment by WillAyd** [comment]
Makes sense to me. Can you add a whatsnew for 1.0.0?

**Review by TomAugspurger — APPROVED** [review]
Verified that this will continue to work with thing like `pendulum.DateTime`, which is a subclass of datetime.datetime.

**Comment by jbrockmendel** [comment]
> Verified that this will continue to work with thing like pendulum.DateTime, which is a subclass of datetime.datetime.

Is this something we need to test more generally?

**Comment by TomAugspurger** [comment]
Probably not. Just had reports from them in the past.

**Pull request merged**
