### PR TITLE
CLN: remove Hypothesis warning during test

### PR DESCRIPTION
**Pull request by ghost**
```plain
hypothesis\_settings.py:193: HypothesisDeprecationWarning: The timeout setting can 
safely be removed with no effect.
```

Starting with 4.0.0 released in Jan, the timeout setting does [nothing](https://github.com/HypothesisWorks/hypothesis/commit/2b9506b7120c2f0593539c1e5d9b526d7ec1377f).

https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.timeout
```plain
    The timeout setting has been deprecated and no longer does anything.

    default value: not_set

    The timeout setting can safely be removed with no effect.
```

Bump dependency from `>=3.8.2` and remove setting.

### CODE REVIEW

**Comment by WillAyd** [comment]
The bump here just suppresses the warning right? Would also want to add a note to min dependencies section in 0.25 whatsnew

**Review by jreback — CHANGES_REQUESTED** [review]
you also need to update any ci/deps where we explicity set the hypothesis versions

**Comment by pilkibun** [comment]
> The bump here just suppresses the warning right?

Yeah, and it seems to be gone from CI. Don't expect any breaking due to upgrade.

> you also need to update any ci/deps where we explicity set the hypothesis versions

thanks.

**Comment by pilkibun** [comment]
Turns out hypothesis 4.0.0 dropped python3.5 support. What do you want to do?

**Comment by WillAyd** [comment]
Does just removing the timeout without bumping get us to the same place?

**Comment by pilkibun** [comment]
> Does just removing the timeout without bumping get us to the same place?

For the CI? yeah, in that even without bumping 'hypothesis>=3.58.2' installs the current version. a user who hasn't updated deps in 8 months may run into some timeout issues. Sounds ok.

**Comment by jreback** [comment]
this is ok, ping on green.

**Comment by pilkibun** [comment]
@jreback green.

**Review by jreback — APPROVED** [review]

**Review by WillAyd — APPROVED** [review]

**Pull request merged**
