### PR TITLE
Progress bar gbq

### PR DESCRIPTION
**Pull request by bagmanas**
Add variable for progress bar

### CODE REVIEW

**Comment by WillAyd** [comment]
Does this reference a particular issue number?

**Comment by WillAyd** [comment]
Ok please be sure to open an issue first before making any code changes. I’m not entirely sure what this is from limited gbq knowledge but tests are required as well

**Comment by alimcmaster1** [comment]
#21628 Looks like the relevant changes have been made in this PR. I think we are good to close this one. @WillAyd @TomAugspurger

**Comment by WillAyd** [comment]
Still need an issue to be opened for this along with the relevant test case(s)

**Comment by alimcmaster1** [comment]
Wait I meant the changes this PR addresses, have already been made on master see #21628. So this is a duplicate. Hence we can close this? @WillAyd

**Comment by WillAyd** [comment]
@alimcmaster1 ah thanks for the link. Looks like it - closing as duplicative

**Pull request closed without merging**
