### PR TITLE
BUG: Copy categorical codes if empty (fixes #18051)

### LINKED ISSUE #18051: BUG: method .nunique on categorical series in v0.21 with only NaNs gives ValueError
#### Code Sample, a copy-pastable example if possible

```python
>>> ser = pd.Series(pd.Categorical([np.nan]))
>>> ser.nunique()
ValueError: buffer source array is read-only
```
#### Problem description

The above code gave 0 in v20.3 and is expected to give 0 also in v0.21. The problem is independent of if I set some categories.

**EDIT**: Actually this doesn't give error if I set categories. so this only happens if no categories are set. The use case for no categories in my case is programmatically reading in data, where some columns are empty and of dtype categorical.

#### Expected Output

0 (zero)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: 81372093f1fdc0c07e4b45ba0f47b0360fabd405
python: 3.5.4.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.5.0.post20170922
Cython: None
numpy: 1.13.3
scipy: None
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.4.8
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

### PR DESCRIPTION
**Pull request by topper-123**
In [agreement with @ghasemnaddaf](https://github.com/pandas-dev/pandas/pull/18279#issuecomment-346488176) , I've finished up his PR #18279 (added correct tests). Is it time still to get this into v0.21.1?

- [ x] closes #18051 
- [ x] tests added / passed
- [x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by topper-123** [comment]
2 out 3 are green. I can check the last one tomorrow if needed.

**Comment by jreback** [comment]
thanks @topper-123 keep em coming!

**Comment by topper-123** [comment]
And thanks to @ghasemnaddaf for actually finding and correcting this bug!

**Comment by ghasemnaddaf** [comment]
urw :-)

**Pull request merged**
