### PR TITLE
Fix pandas-gbq deps

### LINKED ISSUE #25910: CI: build failing because of gbq testing
see https://github.com/pandas-dev/pandas/pull/25554#issuecomment-477602786

added back the gbq dep and this is now failing.

### PR DESCRIPTION
**Pull request by h-vetinari**
Should close #25910, see https://github.com/pandas-dev/pandas/issues/25910#issuecomment-477611959. @jreback

### CODE REVIEW

**Comment by h-vetinari** [comment]
As a side note, it seem the gbq-tests are not actually run correctly in PRs, otherwise this should have been caught in #25554.

**Review by WillAyd — APPROVED** [review]
Makes sense to me. I assume can remove once 0.9.1 comes out right?

**Comment by jreback** [comment]
thanks @h-vetinari

**Comment by h-vetinari** [comment]
> @WillAyd: Makes sense to me. I assume can remove once 0.9.1 comes out right?

It's actually been fixed by @tswast in 0.9.0 [already](https://github.com/pandas-dev/pandas/issues/25910#issuecomment-477680482), so, if I understand correctly, this PR could safely be reverted now.

**Pull request merged**
