### PR TITLE
BUG: Check for duplicate names columns and index in crosstab

### LINKED ISSUE #22529: Crosstab Not Working with Duplicate Column Labels
#### Code Sample, a copy-pastable example if possible

# 1. Example with 2 lambdas applied on same column
df = pd.DataFrame([[0, 1], [0, 1], [1, 0]], columns=['a', 'b'])
df
   a b
0 0 1
1 0 1
2 1 0

pd.crosstab(df['a'].apply(lambda x: x), df['a'].apply(lambda x: x+1))
a 1 2
a
1 2 0
2 0 1

# 2. Example by manually renaming a column
df = pd.DataFrame([[0, 1], [0, 1], [1, 0]], columns=['a', 'b'])
df
   a b
0 0 1
1 0 1
2 1 0

pd.crosstab(df['a'], df['b'])
b 0 1
a
0 0 2
1 1 0

s = df['b']
s.name = 'a'
pd.crosstab(df['a'], s)
a 0 1
a
0 1 0
1 0 2

In both cases, the output is not the one expected. The crosstab applies one Series to itself.

#### Problem description

I encountered the problem when using a crosstab on the same column with 2 different lambdas. The crosstab output a crosstab applying the second column to itself. It seems that crosstab is confused by the same name of the 2 series.

The problem is the same when the 2nd column is manually renamed with the name of the 1rst one, before applying the crosstab. See examples.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.3.2
pip: 10.0.0
setuptools: 38.4.0
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.4.10
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

### PR DESCRIPTION
**Pull request by cuchoi**
- [ ] closes #22529
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by WillAyd — CHANGES_REQUESTED** [review]
Can you add tests? Ideally the first part of any PR

**Comment by cuchoi** [comment]
Sure! Wanted to know that this was the right approach to solving this issue before writing the tests.

**Comment by cuchoi** [comment]
Added tests. Basically updated an old test that would break if we used different data. This would break before:

```
s1 = pd.Series(range(3), name='foo')
s2 = s1 + 1

expected = pd.crosstab(s1, s2.rename("bar"))
result = pd.crosstab(s1, s2)

tm.assert_frame_equal(result, expected)
```

So now I add exceptions checking that there are not duplicated index, columns and now name shared between the index and columns.

**Comment by jreback** [comment]
can you merge master and see if you can get this passing

**Comment by jbrockmendel** [comment]
@cuchoi pls rebase

**Comment by cuchoi** [comment]
Hi! I rebased. Is it not showing up because the issue is closed? Can your reopen it?

**Comment by TomAugspurger** [comment]
Yes. GitHub struggles with reopening PRs to branches that have been closed. You're probably best off opening a new PR if you're wanting to work on this again!

**Comment by cuchoi** [comment]
PR here: https://github.com/pandas-dev/pandas/pull/28474

**Pull request closed without merging**
