### PR TITLE
DOC: Add `DataFrame.to_numpy` method

### LINKED ISSUE #57016: DOC:  API doc missing for DataFrame.to_numpy()
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

### Documentation problem

`DataFrame.to_numpy` API docs are missing on version 2.2 of the docs. In version 2.1 it's here: https://pandas.pydata.org/pandas-docs/version/2.1/reference/api/pandas.DataFrame.to_numpy.html, but on version 2.2 https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html doesn't have a link to a page documenting `to_numpy()`.

### Suggested fix for documentation

Add link on https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html to `to_numpy()` API docs.

### PR DESCRIPTION
**Pull request by luke396**
- [x] closes #57016  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @luke396

**Comment by cbrnr** [comment]
This method seems to be not the only one missing from the current (and dev) docs, e.g. https://pandas.pydata.org/pandas-docs/version/2.1/reference/api/pandas.Index.array.html. Not sure how to check for all occurrences, because this is likely not the only additional method not working...

**Comment by luke396** [comment]
@cbrnr Thank you for the reminder. I will make an effort to locate and include the missing documents, as you mentioned earlier

**Comment by lithomas1** [comment]
@meeseeksdev backport 2.2.x

**Pull request merged**
