### PR TITLE
CI: Reverted changes related to 'jedi' warnings

### LINKED ISSUE #31407: CI: revert the warning change once IPython updates
A couple days ago, there was a CI broken caused by the latest jedi release, and back then, made a patch to catch the warning. Ideally, after ipython updates and fixes the deprecated code, then the warning should be removed, and we should be able to revert the change in #31323

FYI, I created an issue on IPython: https://github.com/ipython/ipython/issues/12102

### PR DESCRIPTION
**Pull request by ShaharNaveh**
- [x] closes #31407
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by charlesdong1991** [comment]
Hi, @MomIsBestFriend seems IPython hasn't fixed and released the new version, so I think this should wait?

**Comment by MomIsBestFriend** [comment]
@charlesdong1991thank you for the quick response :)

 It seemes that IPython did release a new upgrade (or maybe I had it outdated), anyway, I will re-base once in a while, until the problem is fixed, so we will know if it's fixed even if they fixed it but forgot to close the issue.

You are more than welcome to close this PR, but I haven't got warnings while trying it locally, but the problem is that I have  python ```3.8.1``` so I can't know for sure.

**Comment by charlesdong1991** [comment]
ah, okay, this is the issue i posted on ipython, seems still open, that's why i thought this should wait
ipython/ipython#12102

**Comment by jbrockmendel** [comment]
is this still active?

**Comment by MomIsBestFriend** [comment]
@jbrockmendel yes, I am updating this every week (ish)

**Comment by jbrockmendel** [comment]
@MomIsBestFriend can you close this until it becomes actionable?

**Comment by MomIsBestFriend** [comment]
Sure, Will reopen (and ping) when this is mergeable (if that's even a word)

**Pull request closed without merging**
