### PR TITLE
WIP/ENH: reading older Stata versions, #11526

### LINKED ISSUE #11526: read_stata issue
I have the following error when reading a bunch of stata file

    ValueError: Version of given Stata file is not 104, 105, 108, 113 (Stata 8/9), 114 (Stata 10/11), 115 (Stata 12), 117 (Stata 13), or 118 (Stata 14)

I do not know the way to check the stata version of the file but I suspect it is fairly recent.
Opening the file with stata 12 and saving it solves the problem. 
But I do not have stata installed on my machine and I cannot do that everytime.
How can I check the version of the file ?
Is there anybody kind enough  to have a look at the problematic file (personnal email please) ?
I suspect encoding problem. data is a sample of a french survey with many string with accent etc.

Thanks for help

### PR DESCRIPTION
**Pull request by kshedden**
A simple file seems to read OK if we just treat it like other "old format" (version 104-115) files.  However I do not currently have any documentation for this format.  The only relevant resource I can find is the file `foreign/src/stataread.c` in the R `foreign` package sources:

https://cran.r-project.org/src/contrib/foreign_0.8-66.tar.gz

It suggests some special handling for version 111 but I haven't had time to figure out exactly what it is doing.
- [x] closes #11526 
- [x] tests added / passed
- [x] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
can you add a whatnew in Bug Fixes. ping on green.

**Comment by jreback** [comment]
can you rebase and push again

**Comment by kshedden** [comment]
@jreback I don't understand the issue with appveyor here

**Comment by jreback** [comment]
need to rebase on master

**Comment by kshedden** [comment]
@jreback, looks OK now

**Comment by jreback** [comment]
thanks!

**Pull request closed without merging**
