### PR TITLE
CI: Use conda-forge to create Python 3.10 env

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

Anaconda messed up their recipe :(. Fixes the sdist job.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

should we expect an upstream fix at some point?  do we revert this at that point?

**Comment by jreback** [comment]
thanks @lithomas1

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Comment by lithomas1** [comment]
> LGTM
> 
> should we expect an upstream fix at some point? do we revert this at that point?

Probably. No need to revert this one, though, since we really should be using conda-forge's stuff for everything.

**Pull request merged**
