### PR TITLE
Period 29073

### LINKED ISSUE #29073: DOCS: Errors PR08 PR09 in pandas.Period
Subset of #28602 (PR09) and #25232 (PR08) for #27977 (docstrings validation). 

pandas/_libs/tslibs/period.pyx

```
python scripts/validate_docstrings.py --errors=PR08
python scripts/validate_docstrings.py --errors=PR09
python scripts/validate_docstrings.py pandas.Period

```

```
pandas.Period: Parameter "value" description should finish with "."
pandas.Period: Parameter "freq" description should finish with "."
pandas.Period.asfreq: Parameter "how" description should finish with "."
pandas.Period.to_timestamp: Parameter "freq" description should finish with "."
pandas.Period.to_timestamp: Parameter "how" description should finish with "."
pandas.PeriodDtype: Parameter "freq" description should finish with "."
pandas.Period.to_timestamp: Parameter "how" description should start with a capital letter
```

```
10 Errors found:
	Parameters {ordinal} not documented
	Parameter "value" description should finish with "."
	Parameter "freq" description should finish with "."
	Parameter "year" has no description
	Parameter "month" has no description
	Parameter "quarter" has no description
	Parameter "day" has no description
	Parameter "hour" has no description
	Parameter "minute" has no description
	Parameter "second" has no description
```

### PR DESCRIPTION
**Pull request by HughKelley**
- [ ] closes #29073
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by HughKelley** [comment]
One of the CI checks failed so I closed and was going to work back threw it but looking at the checks for recent commits to Master this might be a Travis issue so reopening.

**Comment by WillAyd** [comment]
Looks like the failure is trailing whitespace on line 1781

**Comment by HughKelley** [comment]
hmm thanks, fixed. Initially the check that failed was that Travis timed out while compiling. 

Is it normal for commits to master to be showing CI check fails? When i saw that, I assumed there was something going on and that I should just try again later.

**Comment by jbrockmendel** [comment]
> Is it normal for commits to master to be showing CI check fails? When i saw that, I assumed there was something going on and that I should just try again later.

We recently added a Travis build for python3.8 and it is timing out annoyingly often.  Just re-started that, so hopefully it will resolve itself.

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Great thanks @HughKelley

**Pull request merged**
