### PR TITLE
WEB: Added stying for pre element within the codeblock divs

### PR DESCRIPTION
**Pull request by dsamuel27**
- [x] closes ##51657 (Replace xxxx with the GitHub issue number)
- ENH: Enhancement, adding styling (padding and border) for code blocks

### CODE REVIEW

**Comment by dsamuel27** [comment]
I was reviewing the stylesheets. Would you rather have me add the new styling to codehilite.css since it's effecting the of the codehilite class?

**Review by datapythonista — APPROVED** [review]
Thanks for taking care of this @dsamuel27, I had a look at the [rendered version](https://pandas.pydata.org/preview/51665/pdeps/0004-consistent-to-datetime-parsing.html) and looks great.

> I was reviewing the stylesheets. Would you rather have me add the new styling to codehilite.css since it's effecting the codehilite class?

I guess it's a more natural place to be, yes. @lithomas1 do you want to have a look here?

**Comment by dsamuel27** [comment]
I ended up moving the css code to codehilite.css

**Comment by datapythonista** [comment]
> I ended up moving the css code to codehilite.css

Great, probably better. I'll someone else from the core dev team have a second look and merge, otherwise I'll merge myself in couple of days. But this should be good to go.

**Comment by datapythonista** [comment]
> Website preview of this PR available at: https://pandas.pydata.org/preview/51665/

An example of where the changes can be seen is here: https://pandas.pydata.org/preview/51665/pdeps/0004-consistent-to-datetime-parsing.html

**Comment by datapythonista** [comment]
Thanks @dsamuel27, very nice!

**Pull request merged**
