### PR TITLE
DEPR: support axis=None in DataFrame reductions

### LINKED ISSUE #21597: Support axis=None in all reductions
https://github.com/pandas-dev/pandas/pull/21486 is implementing support for `axis=None` for compatibility with NumPy 1.15's `all` / `any`.

The basic idea is to have `df.op(axis=None)` be the same as `np.op(df, axis=None)` for reductions like `sum`, `mean`, etc.

Getting there poses a backwards-compatibility challenge. Currently for some reduction functions like `np.sum` we interpret `axis=None` as

```python
In [11]: df = pd.DataFrame({"A": [1, 2]})

In [12]: np.sum(df)
Out[12]:
A    3
dtype: int64
```

The best I option I see is to just warn that the behavior will change in the future, without providing a way to achieve the behavior today. Then users can update things like `np.sum(df)` to `np.sum(df, axis=0)`. In a later version we'll make the actual change to interpret `axis=None` like NumPy.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #21597 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Haven't yet added tests or docs, want to see if anyone cares about the warnings we get in the groupby tests when we do e.g. `gb.apply(np.sum)`

### CODE REVIEW

**Comment by rhshadrach** [comment]
Will users also see this message when doing `np.sum(df)`? Might make sense say `DataFrame.sum or numpy.sum`. Then the error message would also make sense in the groupby apply case.

**Comment by jbrockmendel** [comment]
Looks like this does produce the warning for `np.sum(df)`, will update

**Review by topper-123 — COMMENTED** [review]
Generally LGTM. There are some tests failing, but I guess that's fixable

**Comment by mroeschke** [comment]
```

pandas/core/series.py:6050: error: Argument 1 of "prod" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6050: note: This violates the Liskov substitution principle
pandas/core/series.py:6050: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/series.py:6081: error: Argument 1 of "sem" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6081: note: This violates the Liskov substitution principle
pandas/core/series.py:6081: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/series.py:6092: error: Argument 1 of "var" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6092: note: This violates the Liskov substitution principle
pandas/core/series.py:6092: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/series.py:6103: error: Argument 1 of "std" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6103: note: This violates the Liskov substitution principle
pandas/core/series.py:6103: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11001: error: Argument 1 of "sum" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11001: note: This violates the Liskov substitution principle
pandas/core/frame.py:11001: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11013: error: Argument 1 of "prod" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11013: note: This violates the Liskov substitution principle
pandas/core/frame.py:11013: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11044: error: Argument 1 of "sem" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11044: note: This violates the Liskov substitution principle
pandas/core/frame.py:11044: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11055: error: Argument 1 of "var" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11055: note: This violates the Liskov substitution principle
pandas/core/frame.py:11055: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11066: error: Argument 1 of "std" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11066: note: This violates the Liskov substitution principle
pandas/core/frame.py:11066: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11096: error: Incompatible types in assignment (expression has type "Callable[[Optional[Union[int, Literal['index', 'columns', 'rows']]], bool, bool, int, KwArg(Any)], Any]", base class "NDFrame" defined the type as "Callable[[Union[int, None, Literal['index', 'columns', 'rows', _NoDefault.no_default]], bool, bool, int, KwArg(Any)], Any]")  [assignment]
Found 11 errors in 2 files (checked 1418 source files)

mypy (stubtest)............................................................Failed
- hook id: stubtest
- duration: 117.05s
- exit code: 1

error: not checking stubs due to mypy build errors:
pandas/core/series.py:6039: error: Argument 1 of "sum" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6039: note: This violates the Liskov substitution principle
pandas/core/series.py:6039: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/series.py:6050: error: Argument 1 of "prod" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6050: note: This violates the Liskov substitution principle
pandas/core/series.py:6050: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/series.py:6081: error: Argument 1 of "sem" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6081: note: This violates the Liskov substitution principle
pandas/core/series.py:6081: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/series.py:6092: error: Argument 1 of "var" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6092: note: This violates the Liskov substitution principle
pandas/core/series.py:6092: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/series.py:6103: error: Argument 1 of "std" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/series.py:6103: note: This violates the Liskov substitution principle
pandas/core/series.py:6103: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11001: error: Argument 1 of "sum" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11001: note: This violates the Liskov substitution principle
pandas/core/frame.py:11001: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11013: error: Argument 1 of "prod" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11013: note: This violates the Liskov substitution principle
pandas/core/frame.py:11013: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11044: error: Argument 1 of "sem" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11044: note: This violates the Liskov substitution principle
pandas/core/frame.py:11044: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11055: error: Argument 1 of "var" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11055: note: This violates the Liskov substitution principle
pandas/core/frame.py:11055: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11066: error: Argument 1 of "std" is incompatible with supertype "NDFrame"; supertype defines the argument type as "Union[Union[int, Literal['index', 'columns', 'rows']], None, Literal[_NoDefault.no_default]]"  [override]
pandas/core/frame.py:11066: note: This violates the Liskov substitution principle
pandas/core/frame.py:11066: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
pandas/core/frame.py:11096: error: Incompatible types in assignment (expression has type "Callable[[Optional[Union[int, Literal['index', 'columns', 'rows']]], bool, bool, int, KwArg(Any)], Any]", base class "NDFrame" defined the type as "Callable[[Union[int, None, Literal['index', 'columns', 'rows', _NoDefault.no_default]], bool, bool, int, KwArg(Any)], Any]")  [assignment]
```

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
