### PR TITLE
PERF: speed up data frame comparison when shape differs

### LINKED ISSUE #53945: PERF: df.equals() does not check same shape to improve speed
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.

### Reproducible Example

I was looking in stackoverflow and found [this question](https://stackoverflow.com/questions/76587013/pandas-dataframe-equals-why-not-first-checking-equal-shapes) where they asked why does pd.equals() not check for the shape as a first measurement of equality (if they have different shape, they're not equal). I checked and there seems to be no explanation, so I opened this issue. Here's the MWE from the question, I run it in my computer and it takes around 10 seconds more without the shape check.

```
import pandas as pd
import numpy as np
import itertools
import time
import random


def flag_duplicate_v1(dfs) -> None:
    for pairs in itertools.permutations(dfs.keys(), r=2):
        df1 = dfs[pairs[0]]
        df2 = dfs[pairs[1]]
        if type(df1) == str or type(df2) == str:
            # df1 or df2 has been marked duplicate in this loop, skip
            # comparing to remaining non-duplicate is enough
            continue

        if df1.equals(df2):
            print(f"df1 {pairs[0]} and df2 {pairs[1]} are duplicates")
            dfs[pairs[1]] = "DUPLICATE"
    return dfs


def flag_duplicate_v2(dfs) -> None:
    for pairs in itertools.permutations(dfs.keys(), r=2):
        df1 = dfs[pairs[0]]
        df2 = dfs[pairs[1]]
        if type(df1) == str or type(df2) == str:
            # df1 or df2 has been marked duplicate in this loop, skip
            # comparing to remaining non-duplicate is enough
            continue

        if df1.shape == df2.shape:
            if df1.equals(df2):
                print(f"df1 {pairs[0]} and df2 {pairs[1]} are duplicates")
                dfs[pairs[1]] = "DUPLICATE"
        # else not same shape so not duplicates
    return dfs


if __name__ == "__main__":
    # create number_df random dataframes
    dfs = {}
    number_df = 500
    for i in range(number_df):
        length = random.randint(1, 10)
        df = pd.DataFrame(
            {
                "A": np.random.randn(length),
                "B": np.random.randint(2, 10, length),
                "C": [
                    np.random.choice(["rand_1", "rand_2", "rand_4", "rand_6"])
                    for i in range(length)
                ],
            }
        )
        dfs[i] = df
    # add a duplicate
    dfs[number_df] = dfs[random.randint(1, number_df - 1)]

    tic_full_process = time.perf_counter()
    dfs_with_duplicates_v1 = flag_duplicate_v1(dfs)
    print(f"V1 : {time.perf_counter() - tic_full_process:0.1f}")

    tic_full_process = time.perf_counter()
    dfs_with_duplicates_v2 = flag_duplicate_v2(dfs)
    print(f"V2 : {time.perf_counter() - tic_full_process:0.1f}")

    if dfs_with_duplicates_v1 == dfs_with_duplicates_v2:
        print("SAME RESULT")
    else:
        print("DIFFERENT RESULT")
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.16.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : es_ES.cp1252

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 66.0.0
pip              : 23.0.1
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.5
brotli           :
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : 0.19.0
tzdata           : None
</details>

### Prior Performance

_No response_

### PR DESCRIPTION
**Pull request by rouille**
- [ ] closes #53945
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Speed up data frame (or series) comparison when shapes are different. A noticeable improvement is observed. The following scripts:
```
>>> import pandas as pd
>>> import time
>>> df = pd.DataFrame({1: range(1000), 2: range(1000)})
>>> other = pd.DataFrame({1: range(1001), 2: range(1001)})
>>> start = time.process_time()
>>> df.equals(other)
False
>>> print(time.process_time() - start)
```
gives `0.00019999999999997797` before changes and ` 0.003806999999999894` after.

### CODE REVIEW

**Comment by topper-123** [comment]
The underlying perf issue here is that DataManager.equals uses generators, which slows things down there. I'd prefer fixing that directly.

Did you encounter perf. improvements from this fix, outside of `equals` itself?

**Comment by jbrockmendel** [comment]
> gives 0.00019999999999997797 before changes and  0.003806999999999894 after.

is this a typo?  looks like "before" is faster

**Comment by rouille** [comment]
> The underlying perf issue here is that DataManager.equals uses generators, which slows things down there. I'd prefer fixing that directly.
> 
> Did you encounter perf. improvements from this fix, outside of `equals` itself?

I did not investigate further. I was trying to fix a corner case discussed in #53945. That said, as raised by @jbrockmendel in the issue, the check on the shape is already done.

**Comment by rouille** [comment]
> > gives 0.00019999999999997797 before changes and  0.003806999999999894 after.
> 
> is this a typo? looks like "before" is faster

Yes, it is a typo. Thanks for pointing out. That said, it is not rigorous, the evaluation should be done on a large sample of data frames with various dimensions. Following discussion in #53945, we can probably close this PR.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
