### PR TITLE
PERF: add ._simple_new method to masked arrays

### PR DESCRIPTION
**Pull request by topper-123**
Add a `._simple_new` method to `BaseMaskedArray` and child classes in order to allow instantiation without validation to get better performance when validation is not needed.

Example:

```python
>>> import pandas as pd
>>> arr = pd.array(np.arange(2), dtype="Int32")
>>> %timeit arr.reshape(-1, 1)
1.4 µs ± 12 ns per loop  # main
544 ns ± 1.87 ns per loop  # this PR
```

Motivated by performance considerations for https://github.com/pandas-dev/pandas/pull/52836.

### CODE REVIEW

**Comment by topper-123** [comment]
Ping @jbrockmendel & @rhshadrach. This is currently contained in #52788 to fix a slowdown I saw when working in that PR.

**Review by jbrockmendel — APPROVED** [review]

**Review by rhshadrach — APPROVED** [review]
lgtm

**Comment by rhshadrach** [comment]
@topper-123 - just a conflict to resolve

**Comment by topper-123** [comment]
I got some social obligations, so merging this, so #52788 is rebased and ready, when I'm back...

**Pull request merged**
