### PR TITLE
Replace tar_csv.tar.gz with gzipped tar

### PR DESCRIPTION
**Pull request by ginggs**
tar was not compressed previously

### CODE REVIEW

**Comment by jreback** [comment]
cc @gfyoung

**Comment by jreback** [comment]
```
(pandas) bash-3.2$ ls pandas/tests/io/parser/data/
iris.csv                salaries.csv.bz2        salaries.csv.zip        tar_csv.tar             test1.csv.bz2           test_mmap.csv           tips.csv.gz             utf16_ex_small.zip
items.jsonl             salaries.csv.gz         sauron.SHIFT_JIS.csv    tar_csv.tar.gz          test1.csv.gz            tips.csv                unicode_series.csv
salaries.csv            salaries.csv.xz         sub_char.csv            test1.csv               test2.csv               tips.csv.bz2            utf16_ex.txt
```

?

**Comment by ginggs** [comment]
@jreback try `ls -l`, you'll see `tar_csv.tar` and `tar_csv.tar.gz` are both 10240 bytes in size.

**Review by gfyoung — APPROVED** [review]

**Review by datapythonista — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @ginggs !

**Pull request merged**
