### PR TITLE
Revert "Add 'color' and 'size' to arguments (#44856)" 

### PR DESCRIPTION
**Pull request by phofl**
- [x] xref #49732 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

cc @MarcoGorelli would you be ok with reverting?

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
yeah should be fine 👍

**Review by mroeschke — APPROVED** [review]
LGTM. @MarcoGorelli merge when ready

**Review by MarcoGorelli — APPROVED** [review]
awesome thanks @phofl

**Comment by MarcoGorelli** [comment]
@meeseeksdev backport 1.5.x

**Comment by MarcoGorelli** [comment]
don't know what's up with meeseeksdev, but I've done this manually in https://github.com/pandas-dev/pandas/pull/49752

**Pull request merged**
