### PR TITLE
Bug in melt raising Error with dup columns as value vars

### LINKED ISSUE #41951: DataFrame.melt fails if there are duplicate value_vars
DataFrame.columns.get_indexer fails if there are duplicate column names. 

https://github.com/pandas-dev/pandas/blob/05552d354a430f17a45b5fda8a1fd417f4c60c2e/pandas/core/reshape/melt.py#L109

This is really unfortunate -- melting should handle such cases

id   value value
id1  2       3 

should go to

id1 2
id1 3

### PR DESCRIPTION
**Pull request by phofl**
- [x] closes #41951
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

@simonjayhawkins I think this changed in May last year, so probably not woth backporting?

### CODE REVIEW

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
> @simonjayhawkins I think this changed in May last year, so probably not woth backporting?

i'll do a bisect to confirm and decide from there

**Comment by jreback** [comment]
thanks @phofl 

this seemed simple enough

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins I think this changed in May last year, so probably not woth backporting?

can confirm, first bad commit: [62c7dd3e771d5dc2921212cb363239b8f1447058] Fix MultiIndex melt when col_level is used (#34329)

This looks like it would be a straightfoward backport. I see no harm in backporting as it's a regression, but would need release notes moving first so that autobackports work.

**Comment by phofl** [comment]
Meaning opening a new PR for the Whatsnew before backporting this?

**Comment by simonjayhawkins** [comment]
> Meaning opening a new PR for the Whatsnew before backporting this?

yes. @jreback thoughts on including this regression fix in 1.2.5? (it was a regression in 1.1)

**Comment by jreback** [comment]
prob not worth backport to 1.2.x

**Pull request merged**
