### PR TITLE
WIP/REF: BlockManager.setitem_blockwise

### PR DESCRIPTION
**Pull request by jbrockmendel**
Posting largely for discussion with @phofl.

Motivations:

1) Try to end up with fewer code paths for setitem so that we can ensure consistent inplace/view/copy behavior (xref #38896)
2) Simplify (ATM this does not simplify things)
3) Perf: iterating over blocks instead of columns may save some copies (though doing the Index.intersection calls may go the other way) (havent done any profiling yet)

Non-trivial overlap with #39044.
Some of this would be simplified by #39163.
No logical overlap with #39266, but will require rebase.

### CODE REVIEW

**Comment by phofl** [comment]
Is there a specific place where I can be of help?

**Comment by jbrockmendel** [comment]
Mostly just want to keep you in the loop on what i have in mind since you're working on similar parts of the code.

**Comment by jbrockmendel** [comment]
@phofl this fails the test added in #39280.  Thoughts on an appropriate fix?

(a branch that only has the edits to `DataFrame._setitem_array` has the same failure)

**Comment by phofl** [comment]
Not per se a fix, but I had similar dificulties in #39341 

We have to account for duplicate column names in these checks. Maybe using get_indexer_for or something like that if there is a faster alternative. Simply comparing the lenght does not work with duplicates

**Comment by phofl** [comment]
You could use 
```
if self.columns.is_unique:
    len_key = len(key)
else:
    len_key = len(self.columns.get_indexer_non_unique(key))
if len(value) != len_key:
    raise ValueError("Columns must be same length as key")
```

as a helper functions for both len(value) != len(key) checks. Test will keep failing because the column is now cast to integer, but this is good since this is consistent with other setitem cases. If you like I could implement this in #39341. I am dispatching to the else block there right now, since this does the trick currently.

**Comment by jbrockmendel** [comment]
mothballing

**Pull request closed without merging**
