### PR TITLE
REGR: follow-up to return copy with df.interpolate on empty DataFrame

### PR DESCRIPTION
**Pull request by simonjayhawkins**
follow-up to #35543

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
do we want to test this explicitly in this case

**Comment by jreback** [comment]
> do we want to test this explicitly in this case

sure could add a test

**Comment by simonjayhawkins** [comment]
@jreback OK to merge (and backport)

**Comment by jreback** [comment]
thanks. I still don't tihink this is actually the correct place to do this (as it should be handled gracefully in the internal interpolate), but not a blocker.

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.1.x

**Pull request merged**
