### PR TITLE
ENH: allow non-Tick offsets in index.round/ceil/floor

### LINKED ISSUE #15303: Can't use dt.ceil, dt.floor, dt.round with coarser target frequencies
#### Code Sample
This works fine:
```
In [16]: hours = pd.Series(pd.date_range('2017-01-01', '2017-01-31', freq='H'))

In [17]: hours.dt.ceil('D')
Out[17]: 
0     2017-01-01
1     2017-01-02
2     2017-01-02
3     2017-01-02
4     2017-01-02
...
```
But this doesn't:
```
In [18]: days = pd.Series(pd.date_range('2017-01-01', '2017-01-31', freq='D'))

In [19]: days.dt.ceil('M')
...
/home/andrew/git/pandas-rosnfeld-py3/pandas/tseries/offsets.py in nanos(self)
    510     @property
    511     def nanos(self):
--> 512         raise ValueError("{0} is a non-fixed frequency".format(self))
    513 
    514 

ValueError: <MonthEnd> is a non-fixed frequency

```

#### Problem description

I haven't done an exhaustive test, but it seems that one can't use coarser frequencies like 'M', 'Q', 'A' in the dt.ceil/floor/round set of methods.

#### Expected Output

It would seem reasonable to be able to take a series of scattered dates and be able to "coarsen" them into month-ends, quarter-ends, year-ends, etc.

#### Output of ``pd.show_versions()``
<details>
(admittedly some pretty old stuff in this environment but I also got the same behavior on 0.19.2 with latest of everything else)
INSTALLED VERSIONS
------------------
commit: 74e20a0c4146919a82312c1027dcb57b48b613e3
python: 3.5.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-62-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.19.0+300.g74e20a0.dirty
nose: 1.3.7
pip: 7.1.2
setuptools: 19.1.1
Cython: 0.23.4
numpy: 1.10.2
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: 4.0.1
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2016.4
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
feather: None
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.2
lxml: 3.5.0
bs4: None
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: 0.6.7.None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by ghost**
related #27087 (Add `DayBegin`, `DayEnd` offsets)

- [ ] closes #15303
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

I ran into #15303 
```python
In [4]: import pandas as pd
   ...: index=pd.date_range("2000-01-01","2000-01-02",freq="1H")
   ...: index.round("M")
ValueError: <MonthEnd> is a non-fixed frequency
```

This [comment](https://github.com/pandas-dev/pandas/issues/15303#issuecomment-277401817) argues that implementing `round()` doesn't make sense here, since with non-fixed offsets it might round some midpoints up and some down. That might be what the user actually wants, but it's a subtle point. I put the commented code in anyway, just as an option, and implemented dti.`floor`/`ceil`.

If there's intent-to-merge, I'll add the tests etc'.

### CODE REVIEW

**Review by mroeschke — CHANGES_REQUESTED** [review]
I'm a little weary of adding rounding for exotic, non-fixed offsets with the potential ambiguity in behavior.

To begin, if you could create a table with a dummy example and the rounding behavior for the offests contained in this section, that'd help flesh out some potential edge cases:

https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#dateoffset-objects

**Comment by pilkibun** [comment]
`DatetimeIndex.snap()` already does for me what this possible `round` would, and I don't need the extra knobs. So you're both not keen and I don't want it, why don't we just punt on it? Implementing ceil/floor which appear well-defined would still be a good step forward.

Is that reasonable?  is the code ok?

**Comment by mroeschke** [comment]
Okay for `ceil` and `floor`, I think implementing in terms of https://github.com/pandas-dev/pandas/pull/27087#issuecomment-506780186 would be fine.

**Comment by jreback** [comment]
see also #27098, implementing .round() would also be ok for non-Tick based offsets using something like the current implementation of .snap()

**Comment by pilkibun** [comment]
round does work for non-fixed right now, I think. but all three raise for non-fixed. 

ok, good, i'll get it together.

**Comment by pilkibun** [comment]
> Okay for ceil and floor, I think implementing in terms of #27087 (comment) would be fine.

To copy here, the suggested idiom is:
```python
dr.to_period('MS').to_timestamp(how='end')                     
```
I switched to that and added tests. 

There are two problems:
1. `PeriodIndex.to_timestamp` fails for frequencies which imply start/end like "MS"/"BMS"/"BME". 
```python
import pandas as pd
from pandas._libs.tslibs import frequencies as libfrequencies
pi=pd.period_range("2001-01-01",periods=3,freq="MS")
dti=pi.to_timestamp(how='start') 

pandas/core/arrays/period.py in _get_ordinal_range(start, end, periods, freq, mult)
    883 
    884     if freq is not None:
--> 885         _, mult = libfrequencies.get_freq_code(freq)
ValueError: Invalid frequency: MS
```
2. M implies `MonthEnd`. But `dr.to_period('M').to_timestamp(how='start')` rounds to the start of the *month*. It doesn't round to the previous *MonthEnd*, which is what I think it should do.
```python
In [26]: import pandas as pd
    ...: from pandas._libs.tslibs import frequencies as libfrequencies
    ...: dti=pd.DatetimeIndex(["2001-02-01"])
    ...: print(dti)
    ...: dti.to_period('M').to_timestamp(how='start')
DatetimeIndex(['2001-02-01'], dtype='datetime64[ns]', freq=None)
Out[26]: DatetimeIndex(['2001-02-01'], dtype='datetime64[ns]', freq=None)
```

I think that result is what `dti.to_period('MS').to_timestamp(how='start')` is expected to do.

**Comment by pilkibun** [comment]
The approach I originally suggested was rejected (and had issues). The alternative you suggested doesn't work out. Some guidance, please?

Users wanted this t years ago and it stalled because the contributor needed feedback and didn't get it. It'd be a shame for that to happen a second time.

**Comment by pilkibun** [comment]
I'd like to complete this, but I'm stuck without an answer. My approach was rejected, and the one suggested hit a wall. I'm wary of investing time in another approach only to have it rejected again.

**Comment by pilkibun** [comment]
ping.

**Comment by pilkibun** [comment]
I really wanted to get this working but it's been ignored enough to make me give up on it.

**Pull request closed without merging**
