### PR TITLE
DOC: rewrite DataFrame.set_index docstring

### PR DESCRIPTION
**Pull request by ghost**
The docstring for DataFrame is a little confusing about the cases it supports. Explain the 3 cases:
1. specify a column to be used as new index labels
2. pass a like-length array of new index labels
3. pass a mixed list of either, each item becoming a levels of a MultiIndex.

and clarify the meaning of `append` in this context as adding new MultiIndex levels.

### CODE REVIEW

**Comment by WillAyd** [comment]
> 2\. pass a like-length array of new index labels

I would rather deprecate this and push users toward `set_axis` than document more

**Comment by pilkibun** [comment]
> I would rather deprecate this and push users toward set_axis than document more

I had no idea `set_axis` existed. And a search through the docs shows it only appears in the API reference. No wonder few people know about it. I think it makes sense to separate the two, and `set_axis` works for me. So that solves my problem. But there's still the problem of users expecting `Series.set_index` to handle this, and `set_axis` not being widely known.

So, would you consider:
1. accepting this change, marking that case as deprecated
2. extending `set_index` to also have this behavior, marked as deprecated
3. modifying both to issue a deprecation warning telling users to use `set_axis` instead?

I can also open a docs PR to feature `set_axis` more prominently in the indexing section of the docs to help with that.

**Comment by WillAyd** [comment]
> 2\. extending `set_index` to also have this behavior, marked as deprecated

If this is in reference to adding to Series then no I personally think it's not value-added to implement a method that is immediately deprecated

**Comment by pilkibun** [comment]
ordinarily no. But that issue was very heated and made little progress. Going that route would close that original issue, and the deprecation would set a course for resolving this once and for all. 

There's been dissatisfaction with this for over two years, it'd be easier to just take steps to put the issue to rest. Please consider.

**Comment by pilkibun** [comment]
The issue of `Series.set_index` vs. pointing users at `set_axis` is as stuck as ever, and until then it seems even documenting current behavior is being blocked. Oh well.

**Pull request closed without merging**
