### PR TITLE
BLD: Use conda(-forge) compilers

### PR DESCRIPTION
**Pull request by xhochy**
Use the compiler setup from conda-forge inside a conda environment. The compilers in conda-forge can be different and slightly incompatible with the system ones causing some headaches. Also this hopefully helps with initial setup of new contributors.

Is this worth a whatsnew entry?

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I don't think a whatsnew is needed. But maybe we should update the contributing docs related to installing a compiler? https://pandas.pydata.org/docs/dev/development/contributing.html#installing-a-c-compiler (at mention that that manual step is not needed when installing the env using conda)

Does this also work on Windows? (I thought there you still need to manually install MS build tools in addition?)

**Comment by xhochy** [comment]
> Does this also work on Windows? (I thought there you still need to manually install MS build tools in addition?)

You still need the build tools but I have mentioned the exact command to get the minimally necessary VS2017 components for that. This should also be sufficient for `pip`-based setups.

**Review by jreback — APPROVED** [review]
lgtm ping on green.

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
