### PR TITLE
BUG: .astype() of a Float64Index to a Int64Index

### LINKED ISSUE #12866: read_json changes dtype (int => float)
Hi there!

This might be a well-known problem but could not find a track/explaination about it. When reading a json to create a pandas object (Series or DataFrame), the index dtype is changed from int to float.

The  [doc](http://pandas.pydata.org/pandas-docs/stable/io.html#data-conversion) only mentions the inverse trans-typing:

> a column that was float data will be converted to integer if it can be done safely, e.g. a column of 1.

Is this behaviour expected as well? Is the only solution giving the `read_json` a `dtype` argument? 

#### Code Sample, a copy-pastable example if possible

```
    In [1]: import pandas as pd

    In [2]: s = pd.Series([11, 12, 13])

    In [3]: s
    Out[3]: 
    0    11
    1    12
    2    13
    dtype: int64

    In [4]: s.to_json()
    Out[4]: '{"0":11,"1":12,"2":13}'

    In [5]: pd.read_json(s.to_json(), typ="serie")
    Out[5]:  
    0.0    11
    1.0    12
    2.0    13
    dtype: int64

    In [6]: s.index.dtype  
    Out[6]: dtype('int64')

    In [7]: pd.read_json(s.to_json(), typ="serie").index.dtype
    Out[7]: dtype('float64')
``` 

#### Expected Output

I would like to recover the integer index for the new `Series` : 
```
    In [5]: pd.read_json(s.to_json(), typ="serie")
    Out[5]:  
    0    11
    1    12
    2    13
    dtype: int64

    In [7]: pd.read_json(s.to_json(), typ="serie").index.dtype
    Out[7]: dtype('int64')
```

#### Output of ``pd.show_versions()``

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.9.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-44-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: fr_FR.UTF-8

pandas: 0.18.0
nose: 1.3.4
pip: 1.5.6
setuptools: 12.2
Cython: None
numpy: 1.11.0
scipy: 0.14.1
statsmodels: 0.5.0
xarray: None
IPython: 4.0.0
sphinx: 1.2.3
patsy: 0.3.0
dateutil: 2.5.2
pytz: 2016.3
blosc: None
bottleneck: None
tables: 3.1.1
numexpr: 2.4
matplotlib: 1.3.1
openpyxl: 2.2.0-b1
xlrd: 0.9.2
xlwt: 0.7.5
xlsxwriter: None
lxml: 3.4.2
bs4: 4.3.2
html5lib: 0.999
httplib2: 0.9
apiclient: None
sqlalchemy: 1.0.0
pymysql: None
psycopg2: 2.6 (dt dec mx pq3 ext lo64)
jinja2: 2.8
boto: None
```

Thanks!

### LINKED ISSUE #12881: BUG: .astype of Float64Index
xref #12866 
```
data = Index([u'0', u'1', u'2'], dtype='object')
data.astype('float64').astype('int64')
TypeError: Setting <class 'pandas.indexes.numeric.Float64Index'> dtype to anything other than float64 or object is not supported
```
this should work

### PR DESCRIPTION
**Pull request by jreback**
closes #12881
closes #12866 

xref #12309

### CODE REVIEW

**Comment by jreback** [comment]
So we allow astyping only to F8 (and now I8). 

```
In [2]: i = pd.Float64Index([0, 1, 2])

In [3]: pd.Float64Index([0, 1, 2]).astype('i8')
Out[3]: Int64Index([0, 1, 2], dtype='int64')

In [4]: pd.Float64Index([0, 1.1, 2]).astype('i8')
Out[4]: Float64Index([0.0, 1.1, 2.0], dtype='float64')

In [5]: pd.Float64Index([0, 1.1, 2]).astype('i4')
TypeError: Setting <class 'pandas.indexes.numeric.Float64Index'> dtype to anything other than float64 or object is not supported
```

Should we allow other integer/floats? (even though we upcast them anyhow)

e.g. we allow: 
```
In [6]: Index([0, 1.1, 2],dtype='float32')
Out[6]: Float64Index([0.0, 1.10000002384, 2.0], dtype='float64')
```

Further on [4], should this raise instead?

**Comment by jreback** [comment]
@sinhrks @TomAugspurger @jorisvandenbossche @shoyer

**Comment by jorisvandenbossche** [comment]
On In[4], shouldn't we follow numpy behaviour here?

```
In [3]: np.array([0, 1.1, 2]).astype('i8')
Out[3]: array([0, 1, 2], dtype=int64)
```

**Comment by jreback** [comment]
ok all fixed up:

```
In [8]:  pd.Float64Index([0, 1, 2]).astype('i8')
Out[8]: Int64Index([0, 1, 2], dtype='int64')

In [9]: pd.Float64Index([0, 1.1, 2]).astype('i8')
Out[9]: Int64Index([0, 1, 2], dtype='int64')

In [10]: pd.Float64Index([0, 1.1, 2]).astype('i4')
Out[10]: Int64Index([0, 1, 2], dtype='int64')

In [11]: pd.Float64Index([0, 1.1, 2]).astype('f4')
Out[11]: Float64Index([0.0, 1.10000002384, 2.0], dtype='float64')
```

**Pull request closed without merging**
