### PR TITLE
DEPR: DatetimeIndex.union with mixed timezones

### LINKED ISSUE #39328: API: DatetimeIndex union vs join different behavior with mismatched tzs
For union when we have mismatched tzs or mismatched tzawareness, we cast to object.

For join when we have mismatched tzawareness we raise TypeError, with mismatched tzs we cast to UTC.

It would be convenient if these had the same behavior.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #39328
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
is this user facing anywhere aside from a direct index .union op? e.g. does this bubble to a concat?

**Comment by jbrockmendel** [comment]
> is this user facing anywhere aside from a direct index .union op? e.g. does this bubble to a concat?

not concat, _might_ be used in merge, will look into this

**Comment by jbrockmendel** [comment]
confirmed that merge is not affected (though we dont have any tests for this case with DTI, so ill add some in a separate PR)

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
