### PR TITLE
Update issue template

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by WillAyd** [comment]
Why remove this? Flake8 still checks for things that black doesn't

**Comment by pilkibun** [comment]
What kind of things for instance? asking contributors to run 2 linters after every change is bit much.

**Comment by WillAyd** [comment]
Unused or missing imports

**Comment by pilkibun** [comment]
And the CI doesn't catch this?

**Comment by pilkibun** [comment]
nm. I thought it was an oversight after the black switchover but it isn't. Thanks for clarifying.

**Pull request closed without merging**
