### PR TITLE
aggregations.pyx: use std:: for signbit() and sqrt().

### LINKED ISSUE #51047: BUG: aggregations.pyx importing signbit() and sqrt()
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
While trying to build this on NetBSD, the following appears in the build log:


pandas/_libs/window/aggregations.cpp: In function 'void __pyx_f_6pandas_5_libs_6window_12aggregations_add_mean(__pyx_t_5numpy_float64_t, Py_ssize_t*, __pyx_t_5numpy_float64_t*, Py_ssize_t*, __pyx_t_5numpy_float64_t*, __pyx_t_5numpy_int64_t*, __pyx_t_5numpy_float64_t*)':
pandas/_libs/window/aggregations.cpp:4784:18: error: 'signbit' was not declared in this scope; did you mean 'std::signbit'?
 4784 |     __pyx_t_1 = (signbit(__pyx_v_val) != 0);
      |                  ^~~~~~~
      |                  std::signbit
```

This happens both on NetBSD/amd64 and NetBSD/powerpc, with pandas version 1.5.3.
```


### Issue Description

See above for the build error.

The reason for this build failure on NetBSD is that even though `<math.h>` is included, the `<complex>` C++ header is included later, and that includes `<cmath>` which `#undef`s the macros defined in `<math.h>`, among them `signbit()`.  So at this point, you have to use the `std::signbit` variant instead, and this has consequences for how those functions should be imported into the `aggregations.pyx` file.  This used to be OK in pandas version 1.3.5, but things have changed in 1.5.3 so that this no longer builds on NetBSD.

I have a suggested change lined up which re-does the import of `signbit()` and `sqrt()` to come from the `std::` namespace, but don't know if there is a particular reason the change between 1.3.5 and 1.5.3 was introduced.

### Expected Behavior

The build should succeed.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.8.final.0
python-bits      : 64
OS               : NetBSD
OS-release       : 9.99.104
Version          : NetBSD 9.99.104 (GENERIC) #2: Wed Nov  2 15:11:41 UTC 2022  he@stest.urc.uninett.no:/usr/obj/sys/arch/amd64/compile/GENERIC
machine          : amd64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.23.4
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.4.3
pip              : 22.3.1
Cython           : 0.29.32
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.5
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.3
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

### PR DESCRIPTION
**Pull request by he32**
This reintroduces how this was done in pandas 1.3.5. This should fix issue #51047.

- [x] closes #51047
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Can we get this from numpy?

worth up streaming a fix to cython?

**Comment by WillAyd** [comment]
Thanks a ton for the research. I agree with @jbrockmendel though I think this change should be done upstream in Cython

**Comment by he32** [comment]
> Thanks a ton for the research. I agree with @jbrockmendel though I think this change should be done upstream in Cython

Really?  Well, OK.  Who takes that up with the Cython maintainers?  Myself I barely know python, and much less Cython, so feel kind of lost.

**Comment by WillAyd** [comment]
Hmm on second thought this might be something we need to handle on our end. What is importing the C++ complex header? Is that done via deque?

**Comment by he32** [comment]
> Hmm on second thought this might be something we need to handle on our end. What is importing the C++ complex header? Is that done via deque?

The generated `aggregations.cpp` contains

```
/* Header.proto */
#if !defined(CYTHON_CCOMPLEX)
  #if defined(__cplusplus)
    #define CYTHON_CCOMPLEX 1
  #elif defined(_Complex_I)
    #define CYTHON_CCOMPLEX 1
  #else
    #define CYTHON_CCOMPLEX 0
  #endif
#endif
#if CYTHON_CCOMPLEX
  #ifdef __cplusplus
    #include <complex>
  #else
    #include <complex.h>
  #endif
#endif
```
but that is long after
```
#include "Python.h"
```
in the generated `aggregations.cpp` file.  `Python.h` includes `pyport.h`, which in turn includes `<math.h>`.  So, since this is a C++ file, `<complex>` gets included, long after `<math.h>` is included.

`CYTHON_CCOMPLEX` is not defined elsewhere in the `agggrergations.cpp` file, and therefore, on NetBSD at least, you end up with `signbit()` and `sqrt()` only being available via the C++ `std::` name space at that point.

This is with Python 3.10 on NetBSD/macppc 10.0_BETA and cython 0.29.33.

**Comment by WillAyd** [comment]
Awesome - appreciate all the details again. Yea this is a bit tricky - I see why your solution works but (especially since we don't have CI set up for your issue) am wary of how fragile it will be for us over time.

Does importing as an alias from Cython have any effect, i.e. doing `from libc.math import signbit as c_signbit`? Or do things still get clobbered that way

@scoder may have a better solution

**Comment by scoder** [comment]
There's a PR for adding `libcpp.cmath` declarations to Cython 3.0: https://github.com/cython/cython/pull/5262

> `from libc.math import signbit as c_signbit`

This won't change anything in the generated C/C++ code.

Since yo appear to be generating C++ code here, it seems reasonable to use the C+ math functions from their respective namespace. That's generally safer than using something prone to naming collisions from the flat global C namespace.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Comment by he32** [comment]
I'm sorry, I ran out of energy trying to understand what would be your alternative suggestions.  To me it seems "more correct" and less ambigious and less dependent on the particular layout of the C header files to use the `std::` versions of these functions when doing so from C++, as is the case here.

**Comment by WillAyd** [comment]
Sorry lost in the shuffle but from the conversation I think this is ok. If you want to meet in main and get the CI green I would approve

**Comment by WillAyd** [comment]
Err wait...from the PR linked above it looks like Cython has libcpp.math - can you import from there now?

**Pull request closed without merging**
