### PR TITLE
ENH: PandasArray ops use core.ops functions

### PR DESCRIPTION
**Pull request by jbrockmendel**
Needs tests, hopefully i can tweak fixture usage in tests.arithmetic

### CODE REVIEW

**Comment by jreback** [comment]
> Needs tests, hopefully i can tweak fixture usage in tests.arithmetic

you want to do this as a followon?

**Comment by jbrockmendel** [comment]
> you want to do this as a followon?

No, i'll add them here before long

**Comment by jbrockmendel** [comment]
closing to clear the queue while i figure out tests locally

**Comment by jbrockmendel** [comment]
updated with tests

**Comment by jreback** [comment]
thanks

**Pull request merged**
