### PR TITLE
CI: Clean circleci setup env file

### LINKED ISSUE #48307: CI: compile fails sometimes on ci because of undefined object
Currently, the ci is failing occasionally (increasing frequency I think) during the compile process on arm (not sure If this is also true for our other builds).

https://app.circleci.com/pipelines/github/pandas-dev/pandas/15347/workflows/ae3dcf3d-210a-4e9f-b6a9-ac0bdce57c98/jobs/46179

cc @mroeschke I think we had something similar in the past that was fixed by you?

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] closes #48307 (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature

#48307 is tracked by #47305. Cleaning the `setup_ev.sh` file since it's only used for this build.

### CODE REVIEW

**Comment by phofl** [comment]
Thx for this. Wasn’t aware that the issue was still open.

should we switch to mambaforge as a follow up?

**Comment by mroeschke** [comment]
> should we switch to mambaforge as a follow up?

Yes, that would be a useful followup PR.

**Review by phofl — APPROVED** [review]
lgtm

Should investigate in the future to check if we can get this running again in parallel. This is quite a performance penalty.

**Comment by phofl** [comment]
Thx @mroeschke

**Pull request merged**
