### PR TITLE
CLN: Update Cython data pointers for rolling apply

### PR DESCRIPTION
**Pull request by mroeschke**
- [x] xref #34014
- [x] tests passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Performance looks pretty comparable between master and this PR

```
N = 10 ** 3
arr = 100 * np.random.random(N)
roll = pd.DataFrame(arr).rolling(10)
%timeit roll.apply(lambda x: np.sum(x) + 5, raw=True)

4.48 ms ± 14.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) <--PR
4.34 ms ± 29.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) <--master
```

### CODE REVIEW

**Comment by TomAugspurger** [comment]
cc @WillAyd & @jbrockmendel since I think you have some experience here.

It's good to see that performance is comparable.

**Comment by WillAyd** [comment]
This looks great! I assume memory impact is roughly the same? Also do you know if this will work in reductions.pyx as well?

**Comment by jbrockmendel** [comment]
LGTM.  

> Also do you know if this will work in reductions.pyx as well?

My understanding is that these are pretty different usages.  #34009 addresses one of the usages in reductions.pyx; local attempts to address the other usages are proving more troublesome.

**Comment by mroeschke** [comment]
>  I assume memory impact is roughly the same?

My ASVs are botched, but memit shows comparable memusage. Looks like this pointer dance was to avoid copying data, and I think the slicing in this PR should be operating on views.

```
N = 10 ** 3
arr = 100 * np.random.random(N)
roll = pd.DataFrame(arr).rolling(10)
%memit roll.apply(lambda x: np.sum(x) + 5, raw=True)

peak memory: 74.94 MiB, increment: 0.00 MiB <--PR

peak memory: 74.72 MiB, increment: 0.53 MiB <--master
```

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by TomAugspurger** [comment]
Alrighty, thanks!

**Pull request merged**
