### PR TITLE
ENH: Number formatting support for excel styles

### LINKED ISSUE #22027: No way to control display format when exporting to excel
#### Code Sample, a copy-pastable example if possible

```python
# format call does nothing
df.style.format("{:.2%}").to_excel('styled.xlsx')

```
#### Problem description

The current excel styler doesn't implement anything for the styler format method. To get number format there are two possible options. First is to connect this method to something. Second is to allow some way to set the number_format attribute on excel cells. The second option is a bit cleaner IMHO since data conversion like truncating decimal places can result in loss of information and number_format is also sort of how excel declares data types eg. displaying a number as a time.

### PR DESCRIPTION
**Pull request by marknsikora**
- [x] closes #22027 
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

Add number formatting support to the excel styles using a fake css entry. 

```css
number-format: 0%;
```

Added new tests, updated docs, and manually verified outputs using both excel output engines that support styling.

### CODE REVIEW

**Comment by WillAyd** [comment]
Haven't reviewed code in detail yet but does this reference an existing issue? If not can you open and add reference in whatsnew?

**Comment by marknsikora** [comment]
Done

**Review by WillAyd — CHANGES_REQUESTED** [review]
cc @gfyoung for input.

May just be my lack of familiarity with styling but what is the preferred way of using this from an end user perspective? `.apply` with a UDF? Might be worth adding an example to the style notebook to illustrate

**Comment by gfyoung** [comment]
@marknsikora : This looks good at the moment.  Could you add `whatsnew` entry for `0.24.0` ?

**Comment by TomAugspurger** [comment]
Thanks @marknsikora .

**Pull request merged**
