### PR TITLE
BUG: allow DataFrame[mask]=value with mixed non-numeric dtypes

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Looks like this check was implemented to avoid some inconsistency, but I can no longer find what that inconsistency was.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Could also just call this a bugfix since we're going from raising to not raising

**Comment by mroeschke** [comment]
Yeah I would be okay calling this a bug fix

**Comment by jbrockmendel** [comment]
Changed from deprecation to bugfix

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
