### PR TITLE
CLN: Another unused script

### PR DESCRIPTION
**Pull request by mroeschke**
xref https://github.com/pandas-dev/pandas/pull/37825

Another script that looks unused and undocumented

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM, maybe should get an opinion from a windows user

**Comment by alimcmaster1** [comment]
> LGTM, maybe should get an opinion from a windows user

@simonjayhawkins maybe?

**Comment by simonjayhawkins** [comment]
i tend to use git bash as the terminal rather than anaconda prompt so never use this (or test_fast.bat). Have just tested in anaconda prompt and the scripts both work.

if the scripts are undocumented then I guess no harm in removing.

**Comment by mroeschke** [comment]
I kept the `test_fast.*` scripts since they were documented in `contributing.rst`. I'll move forward with removing this one, thanks

**Pull request merged**
