### PR TITLE
CLN: Fix mypy error in 'pandas/tests/computation/test_eval.py'

### PR DESCRIPTION
**Pull request by immaxchen**
Added explicit typing annotation for _parsers: Dict[str, Type[BaseExprVisitor]]
Also added some import for Dict, Type and BaseExprVisitor

- [x] relates to #28926 
- [x] tests added / passed
- [x] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by simonjayhawkins — COMMENTED** [review]
@immaxchen Thanks for the PR. changes look good. ci failures are unrelated. see #29008

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
@immaxchen can you merge master.

**Comment by immaxchen** [comment]
Sure, thank you, Simon!

**Review by simonjayhawkins — APPROVED** [review]
@immaxchen lgtm @WillAyd

**Comment by WillAyd** [comment]
Thanks @immaxchen

**Pull request merged**
