### PR TITLE
Corrected the grammar in Exception

### PR DESCRIPTION
**Pull request by imaskm**
Exception on different arrays' length corrected

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
this message is checked in a test, pls find and change it as well (see the CI logs)

**Comment by imaskm** [comment]
@jreback , I have updated the message in 2 other files.

**Review by mroeschke — APPROVED** [review]

**Comment by imaskm** [comment]
@jreback can you merge this MR?

**Comment by mroeschke** [comment]
Thanks @imaskm

**Pull request merged**
