### PR TITLE
STYLE check for ability to remove 'c-extension-no-member' from pylint exclusions

### PR DESCRIPTION
**Pull request by roadswitcher**
- [ x] addresses one concern listed in #48855 .

Removed `c-extension-no-member` from `pyproject.toml`, ran the precommit checks in Docker build environment, found no instances of the error.

Looks like `c-extension-no-member` can be removed from the list of pylint exclusions in pyproject.toml

### CODE REVIEW

**Comment by roadswitcher** [comment]
OK, that's decidedly odd -- nothing found in the code by pylint, but if I enable the check the pylint process fails on the Ubuntu workflow?    I'll have to look into this more.

**Comment by MarcoGorelli** [comment]
it's almost certainly unrelated, don't worry about it

**Comment by roadswitcher** [comment]
> it's almost certainly unrelated, don't worry about it

I'm choosing to view this as a Self Guided Learning Experience into the intricacies of Github Actions, and not as something to worry about.

**Review by mroeschke — APPROVED** [review]
LGTM merge when ready @MarcoGorelli

**Comment by MarcoGorelli** [comment]
thanks @roadswitcher

**Pull request merged**
