### PR TITLE
CI: Attempt to unpin pytest-xdist

### LINKED ISSUE #35756: CI: Unpin pytest-xdist
Ref: https://github.com/pandas-dev/pandas/issues/35737

Ref: https://github.com/scipy/scipy/pull/12730

Restricting version for now.

### PR DESCRIPTION
**Pull request by alimcmaster1**
- [x] closes #35756

2.1.0 was released yesterday: https://pypi.org/project/pytest-xdist/#history

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by alimcmaster1** [comment]
restarting CI to check no flakeyness.

**Comment by simonjayhawkins** [comment]
Thanks @alimcmaster1

**Pull request merged**
