### PR TITLE
CI: Fixed CI

### PR DESCRIPTION
**Pull request by TomAugspurger**
cc @jbrockmendel

### CODE REVIEW

**Comment by jbrockmendel** [comment]
dask complaint

**Comment by TomAugspurger** [comment]
What dep is pulling in dask?

**Comment by TomAugspurger** [comment]
Ah I guess the old xarray package...

**Comment by jbrockmendel** [comment]
LGTM

**Comment by jbrockmendel** [comment]
Thanks @TomAugspurger

**Pull request merged**
