### PR TITLE
ENH: add ignore index to DataFrame / Series.sample

### LINKED ISSUE #38581: ENH: add ignore_index to DataFrame / Series.sample
#### Is your feature request related to a problem?

When sampling a dataframe / series we get the original index back by default, which is good, but we should add an option to ignore the index to keep it consistent with other methods like `drop_duplicates` and `explode` for example.
#### Describe the solution you'd like

Add `ignore_index` argument to Series/DataFrame.sample.
#### API breaking implications

None as far as I can tell.

```python
df = pd.DataFrame(
    {"col1": range(10, 20), "col2": range(20, 30), "colString": ["a"] * 10}
)
df.sample(n=3, ignore_index=True)

   col1  col2 colString
0    14    24         a
1    17    27         a
2    11    21         a
```

### PR DESCRIPTION
**Pull request by mzeitlin11**
- [x] closes #38581
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Picking up #38594. Left in 1.3 for now since all comments were addressed except small typing issues and seems like a nice enhancement, but let me know if it should be moved.

### CODE REVIEW

**Comment by jreback** [comment]
thanks @mzeitlin11 and @erfannariman for the original!

**Comment by jreback** [comment]
cc @meeseeksdev backport 1.3.x

**Comment by jreback** [comment]
@mzeitlin11 looks like a conflict on 1.3 if you do a manual PR (cc @simonjayhawkins)

**Comment by mzeitlin11** [comment]
> @mzeitlin11 looks like a conflict on 1.3 if you do a manual PR (cc @simonjayhawkins)

Yep I can take care of it later today

**Pull request merged**
