### PR TITLE
Fix mypy errors tests.dtypes.test_common

### PR DESCRIPTION
**Pull request by AbhijeetKrishnan**
xref #28926

- [x] xref #28926
- [x] tests passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jbrockmendel** [comment]
@AbhijeetKrishnan can you rebase

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
Thanks @AbhijeetKrishnan for the PR.

we generally want to avoid cast, see https://dev.pandas.io/docs/development/contributing.html#style-guidelines

**Comment by AbhijeetKrishnan** [comment]
@simonjayhawkins Thanks for the review. I will try to see how the code might be refactored to appease mypy. I plan on submitting another PR if I fix it, so this PR can be closed.

**Comment by simonjayhawkins** [comment]
> I plan on submitting another PR if I fix it, so this PR can be closed.

no need. make updates on same branch and push to keep history.

**Comment by jbrockmendel** [comment]
@AbhijeetKrishnan can you rebase

**Comment by jbrockmendel** [comment]
@AbhijeetKrishnan can you rebase, this looks about ready

**Comment by alimcmaster1** [comment]
Looks like this has now been addressed in https://github.com/pandas-dev/pandas/pull/29179 thanks all the same @AbhijeetKrishnan

**Pull request closed without merging**
