### PR TITLE
BUG: Series.isnull() respect use_inf_as_na

### LINKED ISSUE #50495: BUG: `Series.isnull()` and `DataFrame.isnull()` do not respect `use_inf_as_na` option
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

srs = pd.Series([1, 0, pd.NA, float('Inf')], dtype=pd.Float64Dtype())

# Base case: pd.isnull() and pd.Series.isnull() produce identical results
pd.set_option('use_inf_as_na', False)
assert (srs.isnull() == srs.apply(pd.isnull)).all()

# Raises error below
pd.set_option('use_inf_as_na', True)
assert (srs.isnull() == srs.apply(pd.isnull)).all()  # fails, inconsistent with assertion above
```

### Issue Description

`Series.isnull()` and `DataFrame.isnull()` do not respect the option `use_inf_as_na=True`.

### Expected Behavior

While `Series.isnull()`/`DataFrame.isnull()` and `pd.isnull()` are different functions with slightly different applications, I would expect the behavior of each assertion in this example above to be the same.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.10.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8

pandas           : 1.5.2
numpy            : 1.23.5
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 63.2.0
pip              : 22.3.1
Cython           : None
pytest           : 7.2.0
hypothesis       : None
sphinx           : 5.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.5
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.11.0
scipy            : None
snappy           : None
sqlalchemy       : 1.4.45
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

### PR DESCRIPTION
**Pull request by SaadAhmedGit**
- [x] closes #50495 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Please always add tests

**Comment by SaadAhmedGit** [comment]
@phofl 

> Please always add tests

It seems that I misunderstood the checkbox (it's my first time on the contributing to this repo). I thought it meant that my code was passing tests which were already there but I have now realized that it is referring to any new tests that I have added (which I haven't since there was already a test for it). Is that making sense or am I still wrong?

**Comment by phofl** [comment]
Yes correct, every fix should include a test that did not pass before

**Comment by jborman-exos** [comment]
any update on this?

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Pull request closed without merging**
