### PR TITLE
Fix mypy erroring on backport branches

### PR DESCRIPTION
**Pull request by phofl**
see #48235

cc @twoertwein 

Any suggestions on how to deal with this more effectively?

### CODE REVIEW

**Comment by phofl** [comment]
Seems like the rounding issues with he Timedelta test are back

**Comment by phofl** [comment]
This is the correct syntax, thx.

Like this? Could also explain in text, not as comment

**Review by twoertwein — APPROVED** [review]
Looks good to me

**Comment by phofl** [comment]
cc @mroeschke

**Review by mroeschke — APPROVED** [review]
Thanks this looks okay.

As a followup (or in this PR), could be good to also improve the warning message if the user doesn't have a dev version installed

```
pd_version = getattr(pd, "__version_", "")
if not pd_version:
    # current condition
if "dev" not in pd_version:
    warnings.warn(f"stubtest may fail as {pd_version} is not a dev version. Please install a pandas dev version or see <link to the docs> on how to skip the stubtest")
```

**Comment by phofl** [comment]
Thx, will open an issue. 

I think we can merge? Typing is already green

**Comment by mroeschke** [comment]
Awesome, thanks @phofl and @twoertwein

**Pull request merged**
