### PR TITLE
BUG: support skew function for custom BaseIndexer rolling windows

### PR DESCRIPTION
**Pull request by AlexKirko**
- [X] xref #32865 
- [X] 1 tests added / 1 passed
- [X] passes `black pandas`
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [X] whatsnew entry

## Scope of PR
This PR does a couple things to fix the performance of `skew`, and this also fixes the behavior of all the functions that have `require_min_periods` for small values of `min_periods`:
* clarify docs. Name all sample methods uniformly, add a note to the caveat that users should in general be careful about using sample methods with windows
* fix bug in `_apply` that made us never go into the `BaseIndexer` control flow branch
* fix bug in `_apply`: pass `window_indexer.window_size` into `calc_min_periods` instead of `min_periods or 1`. We want the custom indexer window size there, so it's not clear to me why we were passing `min_periods or 1` .

## Details
The algorithm itself is robust, but it defaults to sample skewness, which is why there was a difference between its output and `numpy`. To prevent misunderstandings, I clarified the docs a bit.
We were also passing a wrong value to `calc_min_periods`, and we weren't going into the proper if branch, because we were checking the type of `window` instead of `self.window`.

## Background on the wider issue
We currently don't support several rolling window functions when building a rolling window object using a custom class descended from `pandas.api.indexers.Baseindexer`. The implementations were written with backward-looking windows in mind, and this led to these functions breaking.
Currently, using these functions returns a `NotImplemented` error thanks to #33057, but ideally we want to update the implementations, so that they will work without a performance hit. This is what I aim to do over a series of PRs.

## Perf notes
No changes to algorithms.

### CODE REVIEW

**Comment by AlexKirko** [comment]
@jreback @mroeschke 
Here is the fix for `skew` with custom rolling windows. Mainly, this returns sample skewness, similarly to `std` and `var`, but I also stumbled onto a couple adjacent bugs while calling this with small values of `min_periods`.

Fixed those and edited the docs to be more clear.

Details in the description above.

**Comment by AlexKirko** [comment]
Did something happen? Why are we running CI only on macOS? Can't find an issue that led to this . . .

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/issues/33747

**Review by mroeschke — APPROVED** [review]

**Comment by AlexKirko** [comment]
@jreback 
There still seem to be problems with CI. I'm reasonably confident that this fix isn't platform-dependent, but please say if you'd like to wait until we can launch all the pipelines and have them report back.

Plenty horrible stuff got into software, because 'it should have worked'.

**Comment by jreback** [comment]
k can you merge master again

CI should run

**Comment by AlexKirko** [comment]
@jreback 
Done, all green.

**Comment by jreback** [comment]
thanks @AlexKirko

**Pull request merged**
