### PR TITLE
added cut as method to Series

### LINKED ISSUE #28925: Add cut as a Series method
#### Problem description

It would be to have `cut` as a series method so that we can method chain. Currently, we must use `pd.cut`, for example,

```
filled_series = df.some_series.fillna(0)
pd.cut(filled_series, 10).mean()
```

it would be nice to do,

```
df.some_series.fillna(0).cut(10).mean()
```

This would also help hugely with tab completion.

#### Expected Output

To have a tab-completed series method for `cut`.

### PR DESCRIPTION
**Pull request by R4HMATT**
- [x] closes #28925 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Not sure if we need to totally re-implement cut. Please feel free to give any advice, I am new to contributing.

### CODE REVIEW

**Comment by WillAyd** [comment]
Thanks for the PR. Why do you think this is a good idea though?

**Comment by mroeschke** [comment]
Echoing @WillAyd and my https://github.com/pandas-dev/pandas/issues/28925#issuecomment-541977217, I am still not convinced adding cut as a Series method makes sense.

**Comment by R4HMATT** [comment]
Not sure if you are referring to the implementation or for the feature itself.

For the feature itself, the original issue expressed better method chaining for series like so:
`df.some_series.fillna(0).cut(10).mean()`.

At the moment, the above can only be done like this:
```
filled_series = df.some_series.fillna(0)
pd.cut(filled_series, 10).mean()
```

**Comment by mroeschke** [comment]
Series is only 1 possible output from `cut` that can be chained with other methods.

`cut` can otherwise produce a `Categorical`, `tuple`, or `ndarray` that cannot be chained.

**Comment by R4HMATT** [comment]
@mroeschke Would it make sense (or even possible) to force the Series method implementation of cut to only return another Series objects then?

**Comment by mroeschke** [comment]
Possibly, but making the output behavior of `pd.cut` inconsistent with `Series.cut` would be odd from an API perspective.

Also for chaining, one can always call `Series.apply(pd.cut)`

**Comment by mroeschke** [comment]
Thanks for your interest in contributing @R4HMATT. I think there needs to be more discussion from the community plus core developers before starting a PR for this feature. 

Feel free to contribute to many of the other issues!

**Pull request closed without merging**
