### PR TITLE
TST: Dtype constants into pandas._testing to avoid direct imports from conftest

### PR DESCRIPTION
**Pull request by SaturnFromTitan**
part of #30914

- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

---------------------------------------------------------------------------------------

Took a naive approach to move these constants into `pandas._testing`. Could also move them to a separate module instead. Let me know what you think is best.

### CODE REVIEW

**Comment by jreback** [comment]
looks pretty good

**Comment by jbrockmendel** [comment]
LGTM pending green

**Comment by SaturnFromTitan** [comment]
@jbrockmendel @jreback Thanks for the review. CI is green now.

**Comment by jreback** [comment]
thanks @SaturnFromTitan

**Pull request merged**
