### PR TITLE
update io docs for OpenDocument Spreadsheets

### LINKED ISSUE #49790: DOC: to_excel OpenDocument Spreadsheets (ODS) write support not updated
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/user_guide/io.html?highlight=ods#opendocument-spreadsheets

### Documentation problem

Write support for Open Document Spreadsheet (ODS) was added in https://github.com/pandas-dev/pandas/pull/32911 but the documentation was not updated.

### Suggested fix for documentation

add documentation to show writing to ODS files is also supported and was added in `v1.1.0`

### PR DESCRIPTION
**Pull request by vamsi-verma-s**
- [x] closes #49790
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Review by rhshadrach — APPROVED** [review]
lgtm

**Comment by attack68** [comment]
I believe this documentation is shared by `Styler.to_excel`. Can I ask double check if this write mode also supports that output method including the addition of excel colors, number formats and borders? etc.

**Comment by rhshadrach** [comment]
@attack68 - not sure what you mean by "shared" here; is it that the `Styler.to_excel` docs link to this section of the documentation? I checked and that doesn't seem to be the case (but I might be missing it?).

**Comment by attack68** [comment]
I am of the understanding that there is no direct documentation for `Styler.to_excel` it is a shared substitution of `DataFrame.to_excel`.
```
    @doc(
        NDFrame.to_excel,
        klass="Styler",
        storage_options=_shared_docs["storage_options"],
        storage_options_versionadded="1.5.0",
    )
```
Therefore I wonder if this update to those docs will automatically apply to `Styler.to_excel` and if the alternative render engine can correctly parse styles. Lot of ifs, but worth the question.

**Comment by rhshadrach** [comment]
This isn't an update to the doc strings, it's an update to the User Guide here: https://pandas.pydata.org/pandas-docs/dev/user_guide/io.html#opendocument-spreadsheets

**Comment by attack68** [comment]
great. my bad, thx for highlighting.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @vamsi-verma-s

**Pull request merged**
