### PR TITLE
[ArrayManager] TST: enable IO tests

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
xref https://github.com/pandas-dev/pandas/issues/39146

This basically just adds IO testing to the set of tests we run for ArrayManager. I already added skips for JSON in the past (and now also for PyTables IO and pickle), so those are still skipped now as well.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Some failing SQL tests use `from_records` and will be fixed by https://github.com/pandas-dev/pandas/pull/40301

**Comment by jreback** [comment]
looks like array manager tests are reporting failures?

**Comment by jorisvandenbossche** [comment]
Yes, there are still a few errors I need to skip (parquet test outside of test_parquet.py). But the strange thing is that the github action kept running, although the output shows it finished (6 failed, 7616 passed, 2180 skipped, 280 deselected, 23 xfailed, 3 xpassed in 192.71s (0:03:12)). But after the IO tests, it never continued with the next tests ..

**Comment by jorisvandenbossche** [comment]
Now it's passing

**Comment by jorisvandenbossche** [comment]
Going to merge, since this is just adding some skips for ArrayManager

**Pull request merged**
