### PR TITLE
DOC: clean-up of v1.2.1 whatsnew

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
First commit is fixing links to the reference docs (many were not actually working links), the second commit is just a reorder to group related ones together (but together it makes the diff a bit difficult to interpret)

cc @simonjayhawkins

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @jorisvandenbossche . also need to move a note that I moved in error https://github.com/pandas-dev/pandas/pull/39233#issuecomment-761900915, do that here?

**Comment by jorisvandenbossche** [comment]
Will do that here

**Review by simonjayhawkins — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche merge when ready. `test_coordinates` is flaky

**Comment by simonjayhawkins** [comment]
Thanks @jorisvandenbossche

**Pull request merged**
