### PR TITLE
DEPR: Update groupby.apply DeprecationWarning to FutureWarning

### PR DESCRIPTION
**Pull request by rhshadrach**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Ref: https://github.com/pandas-dev/pandas/pull/54950#issuecomment-1896995028

### CODE REVIEW

**Comment by rhshadrach** [comment]
Just got caught up with some of the chat on slack, marking this as a draft until https://github.com/pandas-dev/pandas/pull/59513 is merged.

**Review by WillAyd — APPROVED** [review]
I'll admit I didn't track the full scope of this, but as far as the change from Deprecation to FutureWarning goes in 2.3 I would be on board.

I see this has been open for a while. Let's give @jorisvandenbossche a few days in case of any objection; otherwise can merge!

**Comment by jorisvandenbossche** [comment]
I also assume we discussed the actual deprecation thoroughly before, and then +1 on updating it from DeprecationWarning to FutureWarning now.

**Comment by jorisvandenbossche** [comment]
@rhshadrach can you add a brief whatsnew note for 2.3 (maybe just linking to the earlier whatsnew note about it). Users might still start seeing this when updating to 2.3, so it would be good to have some mention of it.

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
