### PR TITLE
BUG: do not escape placeholder in to_latex()

### LINKED ISSUE #18667: Spurious braces in output of DataFrame.to_latex() with MultiIndex columns, MultiIndex index and missing level name
#### Code Sample, a copy-pastable example if possible

```python
In [2]: mi = pd.MultiIndex.from_product([[1, 2], [3,4]], names=['', 'named'])

In [3]: df = pd.DataFrame(-1, index=mi, columns=mi)

In [4]: df.to_latex()
Out[4]: '\\begin{tabular}{llrrrr}\n\\toprule\n  & \\{\\} & \\multicolumn{2}{l}{1} & \\multicolumn{2}{l}{2} \\\\\n  & named &  3 &  4 &  3 &  4 \\\\\n{} & named &    &    &    &    \\\\\n\\midrule\n1 & 3 & -1 & -1 & -1 & -1 \\\\\n  & 4 & -1 & -1 & -1 & -1 \\\\\n2 & 3 & -1 & -1 & -1 & -1 \\\\\n  & 4 & -1 & -1 & -1 & -1 \\\\\n\\bottomrule\n\\end{tabular}\n'
```

#### Problem description

The problem is the content of the second cell, ``\\{\\}``.

#### Expected Output

The same, but with the second cell left empty.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: fdba133336c2ec8f1269eb15e73d48797840c48b
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-4-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.22.0.dev0+301.gfdba13333
pytest: 3.2.3
pip: 9.0.1
setuptools: 36.7.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.0dev
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.3.0
xlsxwriter: 0.9.6
lxml: 4.1.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.2.1

</details>

### PR DESCRIPTION
**Pull request by toobaz**
- [x] closes #18667
- [x] tests added / passed
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
cc @agartland  
cc @syxolk 
cc @MxKy 

this looks reasonable, if any of you have any thoughts.

**Comment by syxolk** [comment]
I don't see the use case. @toobaz Can you give further explanations?

**Comment by toobaz** [comment]
> I don't see the use case. @toobaz Can you give further explanations?

I gave an example in #18667, but maybe the following looks more "normal":

```python
pd.DataFrame(-1,
             index=pd.MultiIndex.from_product([[1, 2]]*3, names=['a', 'b', 'c']),
             columns=range(2)
             ).unstack().to_latex()
```

**Comment by jreback** [comment]
thanks @toobaz

**Pull request merged**
