### PR TITLE
REF: gradually move ExtensionIndex delegation to use inherit_names

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Closing to clear the queue, will revisit once indexing fixes are done

**Comment by TomAugspurger** [comment]
Are all of these changes appropriate for 1.0.0? Or does it rely on stuff that hasn't been backported?

**Comment by jbrockmendel** [comment]
> Are all of these changes appropriate for 1.0.0? Or does it rely on stuff that hasn't been backported?

`inherit_from_data` was in the RC, though this does change that a little bit.  I could do a PR that omits the CategoricalIndex and TimedeltaIndex edits.

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
