### PR TITLE
TYP: Upgrade to mypy 0.920

### PR DESCRIPTION
**Pull request by phofl**
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them

new mypy was released

### CODE REVIEW

**Comment by phofl** [comment]
Converting to draft till mypy is on conda-forge

**Comment by twoertwein** [comment]
> Converting to draft till mypy is on conda-forge

seems to be available: https://anaconda.org/conda-forge/mypy

**Comment by phofl** [comment]
yep, ci is green, was failing before

**Review by twoertwein — APPROVED** [review]

**Comment by jreback** [comment]
one more rebase if you don't mind (as just merged your typing PR)

**Comment by phofl** [comment]
rebased and greenish @jreback

**Comment by jreback** [comment]
thanks @phofl

**Pull request merged**
