### PR TITLE
ENH/BUG: consistently cast strs to datetimelike for searchsorted

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] whatsnew entry

ATM we are pretty inconsistent in how we handle strings for (DTI|TDI|PI|Series).searchsorted.  The underlying EAs will cast scalar strings but not Sequene[str].  The Indexes will raise on both scalars and sequences.  Series follows the EA and casts "2016-01-01" but not `["2016-01-01"]`.

This makes us consistently cast in all cases.

### CODE REVIEW

**Comment by jreback** [comment]
sure, i guess need a whatsnew for this

**Comment by jbrockmendel** [comment]
whatsnew added + green

**Comment by jreback** [comment]
sure

**Comment by jbrockmendel** [comment]
FYI im planning PRs to make cast_str=True in _all_ of the validator method in that file for internal consistency (and ideally to end up with fewer methods)

**Pull request merged**
