### PR TITLE
WEB: Adding governance document to the website

### PR DESCRIPTION
**Pull request by datapythonista**
This adds the governance document to the new website.

The rest of the information in the governance repo should already be in the website, so we shouldn't need that repo anymore.

Advantages I see on having this in the website:
- Users can see the governance information from the website, with the same look and feel as the rest, and not navigating to an external github repo
- Simpler (one extra markdown file in the website vs a whole github repo)
- No repetitive information to maintain. The list of maintainers, committees... is now in `web/pandas/config.yml` and can be used in any of the pages of the website. So, in case of changes there will be a single place where to change things.
- I think having it in the main pandas repo will make it easier to keep things updated. There are currently several outdated links in the governance repo (mainly pointing to the repo in `pydata/pandas` instead of `pandas-dev/pandas`).

@jorisvandenbossche you said you saw advantages on keeping the information in a separate github repo, can you comment here about them please.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I'll admit that its maybe partly subjective, but I personally *like* keeping the official governance documents in a separate repo (or: I like having the separate repo). 
Still trying to give some rational arguments for it:

- The separate repo gives a focused home for all governance-related documents / issues, that does not drawn in the huge pandas repo and issues list. 
- In principle, those governance documents are not only about the pandas-dev/pandas repo, but also for others projects in our organisation (which might grow in the future).
- A comparison is https://github.com/jupyter/governance/, but that is of course a much bigger project.

That's for the separate repo. And personally, for the website itself:

- IMO it is not needed to have this text in full on the website. If someone wants to read it, you can read it on the github repo. I would personally rather have a more high-level page explaining how this works, which can then refer to the full, official text on github. 
  See eg https://jupyter.org/about and https://jupyter.org/community which both link to more detailed resources in their repo. I find such high-level pages more useful on the website.

The other points you mention about avoiding having to update things in two places are certainly true (at least for the list of people/orgs, if we keep the separate repo, the full document would still be in once place). But, (and that's then my personal feeling), I don't find that important enough to get rid of the separate repo.




<sub><sup>From looking at our governance repo now: if we take our governance documents strictly, we actually need to vote on such a change ... ;)</sup></sub>

**Comment by datapythonista** [comment]
Doesn't make a big difference to me whether we move the governance document or not. But being honest, I don't see any of your points us a reason for keeping the governance repo. :)

I think @TomAugspurger is who usually updates that repo, would be good to hear from him. For me it's not a problem to keep the governance repo, I'll keep ignoring it as I do now. But feels like the last thing pandas needs is more separate systems, repos, exceptions and complexity in general. Having a unified and obvious place where to find things seems a much better strategy.

But feel free to close this if you prefer to keep the repo, not a problem for me. But if you do you may want to update the links in that document, many point to a repo that doesn't exist anymore.

**Comment by TomAugspurger** [comment]
I think I kinda prefer it in the separate repo too, but can't really
articulate why. Don't have a strong opinion.

I think if we move it, we would need to inform NumFOCUS, possibly others,
to let them know that the source
had moved.

**Comment by WillAyd** [comment]
From comments above I think this is something we want in the separate repo so closing, but can reopen if anyone disagrees

**Comment by datapythonista** [comment]
I'll reopen this for now. I think it's worth having a decision about this. I don't think it's a big deal for anyone where the governance docs are, but the separate github repo is outdated, and this PR has updated content (one of the reasons why I think we should have the docs in the website). So, let's keep this open at least since a decision is made and someone updates the governance docs where they are now (or since this is merged).

**Comment by datapythonista** [comment]
In today's call we agreed on adding to the governance the new policies for triagers.

I still think that having the governance in a separate repo just causes the information there to be outdated (we currently have an outdated list of core devs, broken links in the governance doc...). And having everything in the website would avoid duplication and make it easy to keep things updated.

Do you want to reconsider this? If we're updating the files in the governance repo, I'll close this.

**Pull request closed without merging**
