### PR TITLE
Fixes to resample over DST boundaries

### LINKED ISSUE #5172: BUG/API: master issue for resample on DST days
- [x] #5694
```
df = pd.DataFrame([0], index=[datetime(2012, 11, 4, 23, 0, 0)])
df = df.tz_localize('America/New_York')
df.resample(rule='D', how='sum')
```
raises a AmbiguousTimeError even though datetime(2012, 11, 4, 23, 0, 0) is not ambiguous.

- [x] #8601 
```
idx = date_range('2014-10-08 00:00','2014-10-09 00:00', freq='D', tz='Europe/Berlin')
pd.Series(5, idx).resample('MS')
```
- [ ] #8744
```
index = pd.to_datetime(pd.Series([
'2014-10-26 07:35:49',
'2014-10-26 07:45:08',
'2014-10-26 08:04:58'
]))

df = pd.DataFrame(np.arange(len(index)), index=index)
df = df.tz_localize('Asia/Krasnoyarsk', ambiguous='NaT')
df.resample('D')

AmbiguousTimeError: Cannot infer dst time from Timestamp('2014-10-26 01:00:00'), try using the 'ambiguous' argument
```

- [ ]  #8653 (might be separate issue)
```
import datetime
import pytz as tz
import pandas as pd

rome = tz.timezone('Europe/Rome')

dr = []
for i in range(2):
    dp = datetime.datetime(2014, 10, 25) + datetime.timedelta(days=i)
    dr.append(rome.localize(dp))

series = {}
for i, ddr in enumerate(dr):
    series[ddr] = i * 10

s1 = pd.Series(series)
s1 = s1.resample('D', how='mean')
```

- [x] #9119 
- [ ] #9173
- [x] #9468

### LINKED ISSUE #8794: ENH: add .normalize() to Timestamp?
From http://stackoverflow.com/questions/26882499/reset-time-part-of-a-pandas-timestamp#26882499

There is now a `DatetimeIndex.normalize()` method to set times to midnight. 
Would it be useful to also have this method available on the individual `Timestamp` object?

Further, this method could also be added to the `.dt` accessor (udpate: for this, there already is a similar issue: #5502).

### LINKED ISSUE #9173: BUG: "ValueError: Values falls after last bin" on resample('1D') of df with DST index, new in 0.15.2
I just upgraded to pandas 0.15.2 and now hit this when I do resample. It worked fine in 0.15.1 (I rolled back to 0.15.1 to confirm). As far as I can tell it occurs when the first date in the index is during daylight savings and the last is not, or vice versa. 

For example, with a date just before and another just after the DST change date of April 6:

    df = pd.DataFrame(index=pd.DatetimeIndex(['2014-04-04 10:00:00', '2014-04-07 10:00:00']), data={'open':0.5}).tz_localize('Australia/Sydney')
    print(df.resample('1D', how={'open':'first'}))

Traceback (most recent call last):
  File "D:/Documents/Programming/Projects/IB/play.py", line 1332, in <module>
    main()
  File "D:/Documents/Programming/Projects/IB/play.py", line 48, in main
    print(df.resample('1D', how={'open':'first'}))
  File "C:\Users\Tom\Anaconda\envs\py2test\lib\site-packages\pandas\core\generic.py", line 3005, in resample
    return sampler.resample(self).__finalize__(self)
  File "C:\Users\Tom\Anaconda\envs\py2test\lib\site-packages\pandas\tseries\resample.py", line 85, in resample
    rs = self._resample_timestamps()
  File "C:\Users\Tom\Anaconda\envs\py2test\lib\site-packages\pandas\tseries\resample.py", line 275, in _resample_timestamps
    self._get_binner_for_resample(kind=kind)
  File "C:\Users\Tom\Anaconda\envs\py2test\lib\site-packages\pandas\tseries\resample.py", line 123, in _get_binner_for_resample
    self.binner, bins, binlabels = self._get_time_bins(ax)
  File "C:\Users\Tom\Anaconda\envs\py2test\lib\site-packages\pandas\tseries\resample.py", line 184, in _get_time_bins
    bins = lib.generate_bins_dt64(ax_values, bin_edges, self.closed, hasnans=ax.hasnans)
  File "pandas\lib.pyx", line 1064, in pandas.lib.generate_bins_dt64 (pandas\lib.c:17790)
ValueError: Values falls after last bin

On the other hand if I roll back to 0.15.1 I get what I expect:
                               open
    2014-04-04 00:00:00+11:00   0.5
    2014-04-05 00:00:00+11:00   NaN
    2014-04-06 00:00:00+11:00   NaN
    2014-04-07 00:00:00+10:00   0.5

Alternatively in 0.15.2 if I add another date in the previous year, such that the first and last dates are either both in daylight savings (even in a different year) or both not in daylight savings, it also seems to work fine.

### LINKED ISSUE #9468: BUG: Series.resample across daylight saving boundary causes segfault.
The following snippet of code is causing a segfault. Here it's failing at head, but I've seen it fail in the 0.15.2 release as well, with both NumPy 1.7.1 and NumPy 1.9.1.
Interestingly this doesn't happen with Pandas 0.13.1.

```
>>> import pandas
>>> import pytz
>>> pandas.show_versions()
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-30-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
pandas: 0.15.2-182-gbb9c311
nose: None
Cython: 0.20.1post0
numpy: 1.9.1
scipy: None
statsmodels: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.4.0
pytz: 2013b
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
rpy2: None
sqlalchemy: None
pymysql: None
psycopg2: None
>>> LA_TZ = pytz.timezone('America/Los_Angeles')
>>> 
>>> s = pandas.Series({
...     pandas.Timestamp('2010-1-1', tz=LA_TZ): 1,
...     pandas.Timestamp('2011-4-1', tz=LA_TZ): 1})
>>> s
2010-01-01 00:00:00-08:00    1
2011-04-01 00:00:00-07:00    1
dtype: int64
>>> s.resample('D', how='max', fill_method='pad')
Segmentation fault (core dumped)
```

Other observations:
- The start/end need to cross the daylight savings switch. Notice utc-08:00 vs utc-07:00 above
- Only fails with how=max and fill_method=pad
- Needs a large enough resampled window. 2011-1-1 to 2011-4-1 won't do it. But 2010-1-1 to 2011-4-1 will.

### PR DESCRIPTION
**Pull request by rockg**
closes #5172 
closes #8744
closes #8653 
closes #9173
closes #9468
closes #8794

fixes all issues but one attached to #5172.  There were several issues as mentioned by my comments in the master list.  They are:
1. Offset classes were not working properly over DST boundaries.  I added flags on the class to handle specially.
2. `normalize_date` does not work with DST change dates as the tz offset is not adjusted. `normalize` is added to Timestamp as discussed in #8794 (I don't like how this was done, but it seemed the easiest rather than duplicating lots of code in `tslib.date_normalize`.
3. `_adjust_dates_anchored` was not localizing properly once times were adjusted.

### CODE REVIEW

**Comment by rockg** [comment]
The outstanding issue is #9119 which is timezone related, but not DST related.

**Comment by jreback** [comment]
@rockg awesome!

I listed all of the issues, pls give a check.

pls give a release note (listing all of the issues) as well.

**Comment by jreback** [comment]
@rockg can you run a perf test (looks like it should be fine, but pls check)

**Comment by jreback** [comment]
@rockg I'd like to get this in the 0.16.0 rc, which I am going to do prob tomorrow (0.16. prob 1 week later), can you update?

**Comment by rockg** [comment]
Yes, fixing everything up.  Should have something in an hour.

**Comment by rockg** [comment]
Wow that vbench takes over an hour (and it only works for python 2 which was a nice surprise).  There are a few date things in here which surprised me.
```
reshape_stack_simple                         |   3.8433 |   3.5164 |   1.0930 |
frame_ctor_dtindex_BusinessDayx1             |   2.2870 |   2.0920 |   1.0932 |
dataframe_resample_min_numpy                 |   3.2500 |   2.9697 |   1.0944 |
frame_ctor_dtindex_CustomBusinessDayx1       |   2.3030 |   2.1026 |   1.0953 |
frame_ctor_dtindex_BDayx2                    |   2.3340 |   2.1287 |   1.0965 |
frame_ctor_dtindex_YearBeginx1               |   2.2504 |   2.0523 |   1.0965 |
frame_ctor_dtindex_CBMonthEndx1              |   6.5024 |   5.8760 |   1.1066 |
groupby_ngroups_100_sum                      |   0.7041 |   0.6344 |   1.1099 |
groupby_ngroups_100_count                    |   0.5260 |   0.4703 |   1.1183 |
reshape_unstack_simple                       |   5.0033 |   4.4693 |   1.1195 |
concat_empty_frames2                         |   1.4807 |   1.3180 |   1.1234 |
timeseries_custom_bmonthend_incr             |   0.3620 |   0.3190 |   1.1348 |
panel_shift_minor                            |   0.1633 |   0.1436 |   1.1372 |
replace_replacena                            |   2.7843 |   2.4397 |   1.1413 |
timeseries_custom_bmonthbegin_decr_n         |   0.4679 |   0.4090 |   1.1442 |
replace_fillna                               |   3.4404 |   3.0044 |   1.1451 |
timeseries_iter_periodindex_preexit          |  14.1080 |  12.3093 |   1.1461 |
timeseries_custom_bmonthbegin_incr_n         |   0.4480 |   0.3854 |   1.1625 |
strings_lower                                |   5.3800 |   4.4383 |   1.2122 |
timeseries_custom_bday_cal_decr              |   0.0687 |   0.0520 |   1.3211 |
timeseries_custom_bday_decr                  |   0.0679 |   0.0513 |   1.3235 |
timeseries_custom_bday_cal_incr_neg_n        |   0.0690 |   0.0517 |   1.3354 |
timeseries_custom_bday_cal_incr              |   0.0617 |   0.0447 |   1.3808 |
timeseries_custom_bday_cal_incr_n            |   0.0620 |   0.0447 |   1.3879 |
timeseries_year_apply                        |   0.0453 |   0.0319 |   1.4179 |
timeseries_year_incr                         |   0.0490 |   0.0337 |   1.4528 |
timeseries_custom_bday_apply_dt64            |   0.0520 |   0.0356 |   1.4598 |
timeseries_custom_bday_incr                  |   0.0477 |   0.0320 |   1.4888 |
timeseries_custom_bday_apply                 |   0.0456 |   0.0306 |   1.4909 |
frame_object_equal                           |  21.1930 |  11.3687 |   1.8642 |
frame_nonunique_equal                        |  21.2193 |  11.3026 |   1.8774 |
```

**Comment by jreback** [comment]
vbench looks fine, the things that take < 1ms are really hard to time correctly.
usually I pass ``-r regex`` which will only do those tests that are most interesting.

**Comment by rockg** [comment]
Great news.

**Comment by jreback** [comment]
I think this is ok, however, need to check one thing. Can you make a pickle from 0.15.2 and add to the tests, like this: https://github.com/pydata/pandas/blob/master/pandas/tests/test_categorical.py#L2640 (need to test that the DateOffsets survive this change). Basically save say a dict of a couple of examples, pickle it to a file (in 0.15.2), then read in (in the tests) and make sure they compare equal (I think they should), but since adding this attribute, need to make sure.

**Comment by rockg** [comment]
The pickle test worked fine.  Think we should be good on that front.

**Comment by jreback** [comment]
ok looks good

will merge in the morning

if u have s chance see if anything needs to be updated in the docs about tz (eg in resample section)

**Comment by jreback** [comment]
merged via https://github.com/pydata/pandas/commit/dcc68d7c5a06df85fe9fec568566bee1e9936b10

thanks!

**Comment by rockg** [comment]
@jreback...thanks.  There are a couple travis errors on two of 2.7 jobs with the pickle test (however one of them succeeded).  Any thoughts? 

======================================================================
ERROR: test_pickle_v0_15_2 (pandas.tseries.tests.test_offsets.TestCommon)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pydata/pandas/pandas/tseries/tests/test_offsets.py", line 424, in test_pickle_v0_15_2
    self.assertEqual(offsets, read_pickle(pickle_path))
  File "/home/travis/build/pydata/pandas/pandas/io/pickle.py", line 60, in read_pickle
    return try_read(path)
  File "/home/travis/build/pydata/pandas/pandas/io/pickle.py", line 57, in try_read
    return pc.load(fh, encoding=encoding, compat=True)
  File "/home/travis/build/pydata/pandas/pandas/compat/pickle_compat.py", line 116, in load
    return up.load()
  File "/home/travis/miniconda/envs/pandas/lib/python2.6/pickle.py", line 858, in load
    dispatch[key](self)
  File "/home/travis/build/pydata/pandas/pandas/compat/pickle_compat.py", line 20, in load_reduce
    stack[-1] = func(*args)
  File "/home/travis/miniconda/envs/pandas/lib/python2.6/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: object.__new__(X): X is not a type object (classobj)

**Comment by jreback** [comment]
I rebuilt the pick on 0.15.2 and it works fine. How did you create the pickle?

I have only seen this error IIRC if you pickle I think in text mode.

**Comment by rockg** [comment]
I thought I used the same recipe as your example.  I created a new
virtualenv and saved the pickle with the file in 'wb' mode.

**Comment by jreback** [comment]
Python 2?

**Comment by rockg** [comment]
Almost positive (I can confirm tonight).  I am positive that I ran the test locally with Python 2.7.  Anyways, I'm not sure it's worth more thought right now.  Thanks for taking care of it.

**Pull request closed without merging**
