### PR TITLE
REF: remove DatetimeBlock, TimeDeltaBlock

### PR DESCRIPTION
**Pull request by jbrockmendel**
sits on top of #40456

### CODE REVIEW

**Review by jreback — APPROVED** [review]
nice

**Comment by jorisvandenbossche** [comment]
Similarly as https://github.com/pandas-dev/pandas/pull/40527, we should maybe first deprecate those Block classes before removing them?

**Comment by jreback** [comment]
why? what is using them

**Comment by jorisvandenbossche** [comment]
In pyarrow, we are explicitly using CategoricalBlock, DatetimeTZBlock, ObjectBlock and ExtensionBlock. So not DatetimeBlock or TimedeltaBlock, but that's only one data point, and given that we are already using many of the block classes, I think we should be careful with removing any of them.

**Comment by jreback** [comment]
i agree with @jbrockmendel 
perpetuating internals is not great

if something downstream is breaking that we can re add and depreciate

**Pull request merged**
