### PR TITLE
DOC: capitalize NumPy as proper noun

### PR DESCRIPTION
**Pull request by erictleung**
In a similar vein to https://github.com/pandas-dev/pandas/pull/37808

- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
is it possible to modify the docs checkers to make sure this in enforced?

**Comment by erictleung** [comment]
We could add a spelling checker when building Sphinx https://sphinxcontrib-spelling.readthedocs.io/en/latest/index.html. I don't see this extension used in the current `conf.py` file (https://github.com/pandas-dev/pandas/blob/master/doc/source/conf.py#L52-L69). But of course, this would add to the number of dependencies, which may or may not be wanted.

If there's another place you're referring to, @jreback, I'd be interested to learn.

**Comment by jreback** [comment]
i think this needs to be a pre-commit hook or maybe we discussed as a code_check. cc @MarcoGorelli

can do later for that i guess.

**Comment by MarcoGorelli** [comment]
I think a `pygrep` hook to check that we don't use `Numpy` (with only the `N` capitalised) would be OK - @erictleung if you check the other local pygrep hooks in `.pre-commit-config.yaml` they can provide a guide, feel free to reach out to me for help (here or on the gitter channel) if you want to do this and need help

**Comment by jreback** [comment]
thanks @erictleung

**Pull request merged**
