### PR TITLE
Remove _DtypeOpsMixin

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by WillAyd** [comment]
Seems pretty straightforward. So this is purely dead development at this point right?

**Comment by TomAugspurger** [comment]
right. It was just needed until all our old dtypes became real extension
dtypes. I forgot to remove after adding DatetimeTZDtype.

**Comment by TomAugspurger** [comment]
So the bulk of https://github.com/pandas-dev/pandas/pull/26331/commits/acb5b49c08512aca15b8ab00fafcccc556d86ae6 is just moving methods from _DtypeOpsMixin to ExtensionDtype.

**Review by gfyoung — APPROVED** [review]

**Comment by jreback** [comment]
looks fine, merge pending CI resolution.

**Comment by jreback** [comment]
thanks @TomAugspurger

**Pull request merged**
