### PR TITLE
CI,STYLE: narrow down list of ignored words

### PR DESCRIPTION
**Pull request by chinggg**
I have used `grep` to check if the words in the list exist in the code.  
Only `ba` can be deleted from the list.

### CODE REVIEW

**Comment by jreback** [comment]
@chinggg we can delete these if we change the references to better words where appropriate

**Comment by MarcoGorelli** [comment]
I don't think it can be removed:
```
codespell..............................................................................................Failed
- hook id: codespell
- exit code: 65

pandas/core/resample.py:1383: BA ==> BY, BE
pandas/core/shared_docs.py:604: ba ==> by, be
pandas/core/shared_docs.py:610: ba ==> by, be
pandas/core/shared_docs.py:616: ba ==> by, be
pandas/core/shared_docs.py:622: ba ==> by, be
pandas/core/shared_docs.py:628: ba ==> by, be
```
Rather, it may be that you can change the occurrences of these "words" in the code to more meaningful ones such that they don't have to be ignored

`ba` is used in
```
    >>> df.replace(to_replace=r'^ba.$', value='new', regex=True)
```
so it likely can't be removed

---

to check whether something can be removed, you should run
```
pre-commit run codespell --all-files
```

**Comment by MarcoGorelli** [comment]
On the other hand, `fo` can be removed by applying
```diff
diff --git a/pandas/core/strings/accessor.py b/pandas/core/strings/accessor.py
index 339ad2653..975115584 100644
--- a/pandas/core/strings/accessor.py
+++ b/pandas/core/strings/accessor.py
@@ -1547,10 +1547,10 @@ class StringMethods(NoNewAttributesMixin):
 
         Examples
         --------
-        >>> s = pd.Series(["koala", "fox", "chameleon"])
+        >>> s = pd.Series(["koala", "nox", "chameleon"])
         >>> s
         0        koala
-        1          fox
+        1          nox
         2    chameleon
         dtype: object
 
@@ -1568,19 +1568,19 @@ class StringMethods(NoNewAttributesMixin):
 
         >>> s.str.slice(stop=2)
         0    ko
-        1    fo
+        1    no
         2    ch
         dtype: object
 
         >>> s.str.slice(step=2)
         0      kaa
-        1       fx
+        1       nx
         2    caeen
         dtype: object
 
         >>> s.str.slice(start=0, stop=5, step=3)
         0    kl
-        1     f
+        1     n
         2    cm
         dtype: object
 
@@ -1588,7 +1588,7 @@ class StringMethods(NoNewAttributesMixin):
 
         >>> s.str[0:5:3]
         0    kl
-        1     f
+        1     n
         2    cm
         dtype: object
         """
```

**Comment by chinggg** [comment]
Sorry, I did not know how to use `codespell` and `pre-commit'` well before. And I tried to type `diff --git` or `git diff` as you presented above, but there must be some mistakes and it does not work.  
But now I have understood your instructions and made corresponding modifications.Finally it passed the `pre-commit` test on my machine.  
Thanks!

**Pull request closed without merging**
