### PR TITLE
DOC: Add docstrings for fixtures defined from pandas.tests.io.conftest

### PR DESCRIPTION
**Pull request by jordan-d-murphy**
Add docstrings for fixtures defined from pandas.tests.io.conftest

- [x] xref https://github.com/pandas-dev/pandas/issues/19159
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jordan-d-murphy** [comment]
@datapythonista would you please give this PR a review and share any feedback?

**Comment by datapythonista** [comment]
Is there any validation for it we are trying to enforce? I personally don't see much value here otherwise. It'd be nice to have proper documentation for fixtures for sure, but that would take understanding well them and providing useful information on what they are exactly and when they can be used. This PR seems to simply repeat the fixture names in a more verbose way. I'd prefer to not have them rather than this.

**Comment by mroeschke** [comment]
Agreed with @datapythonista on the value of this. If you're interested, continuing to enforce numpydoc validations would be worthwhile: https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks

**Comment by jordan-d-murphy** [comment]
@datapythonista @mroeschke 

Thank you gentlemen, I appreciate the feedback and guidance! 

One way I do think this adds value is when running `pytest --fixtures pandas` the output before these changes looks like this: 
before

and after adding the docstrings: 

after

Considering this, is this meaningful to add? If not, I'm happy to revert these changes and move on to the working on continuing to enforce numpydoc validations as Matthew suggested.

**Comment by mroeschke** [comment]
> Considering this, is this meaningful to add?

Just to make my last comment clearer - I would still be OK with documenting these pytest fixtures, but I don't think there's a ton of value (impact) in doing so.

**Comment by jordan-d-murphy** [comment]
@mroeschke I've opened https://github.com/pandas-dev/pandas/issues/57111 to continue work on enforcing numpydoc validations: https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks

**Pull request closed without merging**
