### PR TITLE
ENH: #2679 - DataFrame.to_html() urls_as_links parameter.

### PR DESCRIPTION
**Pull request by lexual**
New urls_as_links boolean paramater that will output urls as href html
links. ref #2679 

Thanks for @tdas14 for initial code.

### CODE REVIEW

**Comment by jreback** [comment]
@TomAugspurger (I recall you doing some work on conditional html formatting, though orthogonal to this affect API)

**Comment by jreback** [comment]
@lexual can you rebase

**Comment by jreback** [comment]
@lexual can you rebase / update

**Comment by jreback** [comment]
pls see comments on #9880

**Comment by jreback** [comment]
IOW this needs to have a global option (that defaults to ``False``)

**Comment by jreback** [comment]
closing, but if you would like to continue working on this pls reopen

**Comment by lexual** [comment]
I have rebased, but don't have permissions to re-open I believe.

Please advise next steps to get it merged.

Apologies for long absence ;)

**Comment by lexual** [comment]
https://github.com/lexual/pandas/commit/49992e9c5b5edfe9880d93466df4d448f3add5db

rebase @jreback

**Comment by jreback** [comment]
@lexual this is more appropriate as a method in ``df.style`` for #10250 

e.g.

``df.style.show_urls_as_links()`` or something. You want to do a PR against @TomAugspurger branch for that?

**Comment by TomAugspurger** [comment]
@lexual let me know if you want to do that PR agains my branch in #10250, it will actually be quite simple thanks to jinja.

Right now in the Jinja template I've got [a check](https://github.com/pydata/pandas/pull/10250/files#diff-871722e2eeea86e2eb7c981fa3748d4fR113) for if the value is a number or not. Jinja has a [urlize](http://jinja.pocoo.org/docs/dev/templates/#urlize) filter that you can apply to the else block.

We will need a more general way of applying arbitrary tags / modify the template, but that could work for now.

**Comment by lexual** [comment]
@TomAugspurger yep, I'll try to take a look when I get a chance.

**Pull request closed without merging**
