### PR TITLE
CI: Migrate to circleci 2.0

### LINKED ISSUE #19929: CI: Migrate to circle CI 2.0
1.0 is being shut down: https://circleci.com/blog/sunsetting-1-0/?mkt_tok=eyJpIjoiT0dFMVkyWXlZV05pT1RFNSIsInQiOiJrWVJVc0lUSjZ3NSttZHJDM2h2UFhoY0JacGw4YUNwR09qb1QwZzRFM2NOKzk4WEI5VXhxS055S2JPbVdFUWdmbWVPWmx5R0N1TFB6ZEFsZm5JUklob1dXTXAzZWtCaWpYSmE0TUdSd3RRemh3WWYxMDhleHhtVkh0dU9obStGRiJ9

- http://go.circleci.com/E020Z0bCMOi0k0MH2Z04G00
- http://go.circleci.com/p0400Z00DH0M0PkM2G0biZ2
- http://go.circleci.com/r40Q0H2Z0MEGikZ0b00M020

### PR DESCRIPTION
**Pull request by TomAugspurger**
closes https://github.com/pandas-dev/pandas/issues/19929

### CODE REVIEW

**Comment by jreback** [comment]
this is more readable! hahah

**Comment by TomAugspurger** [comment]
Slightly! I haven't tried de-duplicating things between the jobs yet, but will once things are passing (hopefully this commit).

**Comment by TomAugspurger** [comment]
Still need to figure out the database tests.

**Comment by jreback** [comment]
@TomAugspurger

**Comment by TomAugspurger** [comment]
Locale stuff will hopefully be working now.

FYI, the slow cases where flipped in https://github.com/pandas-dev/pandas/blob/a43947283dd6dc9f9dc2742700c7fa4677d7e27a/circle.yml#L37. Job 1 (36_LOCALE) was running slow only and Job 2 (36_LOCALE_SLOW) was skipping the slow ones. I've corrected that.

Working on the database now.

**Comment by jorisvandenbossche** [comment]
@TomAugspurger what is the status here?

**Comment by TomAugspurger** [comment]
Just down to locale failures, which https://github.com/pandas-dev/pandas/pull/22213 hopefully fixed.

Will merge master and try again.

**Comment by TomAugspurger** [comment]
Actually, looking more closely I don't think those locale failures will be resolved by #22213...

```pytb
value = '三, 08 8月 2018 17:42:53 GMT'

    def parse_timestamp(value):
        """Parse a timestamp into a datetime object.
    
        Supported formats:
    
            * iso8601
            * rfc822
            * epoch (value is an integer)
    
        This will return a ``datetime.datetime`` object.
    
        """
        if isinstance(value, (int, float)):
            # Possibly an epoch time.
            return datetime.datetime.fromtimestamp(value, tzlocal())
        else:
            try:
                return datetime.datetime.fromtimestamp(float(value), tzlocal())
            except (TypeError, ValueError):
                pass
        try:
            # In certain cases, a timestamp marked with GMT can be parsed into a
            # different time zone, so here we provide a context which will
            # enforce that GMT == UTC.
            return dateutil.parser.parse(value, tzinfos={'GMT': tzutc()})
        except (TypeError, ValueError) as e:
>           raise ValueError('Invalid timestamp "%s": %s' % (value, e))
E           ValueError: Invalid timestamp "三, 08 8月 2018 17:42:53 GMT": ('Unknown string format:', '三, 08 8月 2018 17:42:53 GMT')
```

I'll look more closely today.

**Comment by TomAugspurger** [comment]
In theory, just `TestDatetime64.test_datetime_name_accessors[crh_UA.UTF-8]` should fail now. Looking into it now.

**Comment by TomAugspurger** [comment]
This is fun

```python
(Pdb) x
'İyun'
(Pdb) y
'İyun'
(Pdb) [(ord(a), ord(b)) for a, b in zip(x, y)]
[(73, 304), (775, 121), (121, 117), (117, 110)]
```

`x` came from us, `y` came from `calendar.month_name`. It seems like `calendar.month_name` normalizes the strings

```python
(Pdb) unicodedata.normalize("NFC", x) == x
False
(Pdb) unicodedata.normalize("NFC", y) == y
True
```

Not sure why this wasn't failing earlier though.

**Comment by TomAugspurger** [comment]
And it passes for me locally as well, even when I override LANG and LC_ALL. I'm only able to reproduce in the docker image from circle.

**Comment by TomAugspurger** [comment]
All green (finally).

**Comment by TomAugspurger** [comment]
Opened https://github.com/pandas-dev/pandas/issues/22396 with a couple followup items. Will do that in a couple days in case we notice anything else.

**Comment by jorisvandenbossche** [comment]
Thanks a lot Tom!

**Pull request merged**
