### PR TITLE
DEPS: Update cython

### PR DESCRIPTION
**Pull request by phofl**
- [x] xref #47978
- [x] xref #46848

### CODE REVIEW

**Comment by phofl** [comment]
#47978

**Comment by simonjayhawkins** [comment]
Thanks @phofl 

we also want to add a release note (see 1.4.3, moreless copy and paste that one). Cython is a dev only dependency so I'll milestone as 1.4.4 for now.

we should probably also add the test from #47097

**Comment by simonjayhawkins** [comment]
all the ci files and the setup.py also need updating

**Comment by simonjayhawkins** [comment]
Thinking some more (after https://github.com/pandas-dev/pandas/pull/47097#issuecomment-1202934142) I think ok to also add a release note for the regression fix too.

**Comment by phofl** [comment]
Changed the other versions (forgot about them earlier) and added the test

**Comment by simonjayhawkins** [comment]
Thanks @phofl . Let's give others chance to comment before we merge as I only opened the issue this morning.

**Review by lithomas1 — CHANGES_REQUESTED** [review]
Thanks for the PR. Can you upgrade pyproject.toml too? 
LGTM otherwise.

**Comment by lithomas1** [comment]
BTW, I've edited the description to not close the two issues, since we still need MacPython/pandas-wheels#188 as well.

**Comment by zlspgz** [comment]
您好，邮件已收到，谢谢！祝万事胜意！

**Comment by phofl** [comment]
Updated pyproject.toml too.

**Review by lithomas1 — APPROVED** [review]

**Review by simonjayhawkins — APPROVED** [review]
Thanks @phofl will merge later today if no objections

**Pull request merged**
