### PR TITLE
DOC: Fix release note typo

### PR DESCRIPTION
**Pull request by dsaxton**

### CODE REVIEW

**Review by simonjayhawkins — APPROVED** [review]
Thanks @dsaxton merge when green-ish

**Comment by simonjayhawkins** [comment]
probably need to wait till #36669 merged to do backport.

**Comment by dsaxton** [comment]
> probably need to wait till #36669 merged to do backport.

Ok, should I go ahead and open the backport PR? I have it ready.

**Comment by simonjayhawkins** [comment]
yep. likely have conflicts if created b4 merge.

**Comment by simonjayhawkins** [comment]
it's typically that normally need to trigger the backport and when you don't want it, it works.

**Pull request merged**
