### PR TITLE
BUG: DTA/TDA/PA add/sub object-dtype

### PR DESCRIPTION
**Pull request by jbrockmendel**
Bonus: we get to get rid of is_offsetlike

### CODE REVIEW

**Review by jreback — APPROVED** [review]
lgtm ping on green. is this a bug fix? e.g. is there an issue

**Comment by jbrockmendel** [comment]
> is this a bug fix? e.g. is there an issue

There is no associated issue.  I stumbled on this when implementing block-wise arithmetic for the non-scalar cases.

**Comment by jbrockmendel** [comment]
ping

**Comment by jreback** [comment]
k thanks.

**Pull request merged**
