### PR TITLE
TST: xfail 32-bit test

### LINKED ISSUE #35294: Various 32-bit failures at MacPython/pandas-wheels
https://dev.azure.com/pandas-dev/pandas-wheels/_build/results?buildId=39280&view=logs&j=a846d25a-e32c-5640-1b53-e815fab94407&t=8fc25549-8157-5c9c-f998-0884bd2e8ccb&l=3099

```
FAILED test_venv/lib/site-packages/pandas/tests/window/test_api.py::test_multiple_agg_funcs[rolling-2-expected_vals0]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_apply.py::test_rolling_apply_args_kwargs[args_kwargs0]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_apply.py::test_rolling_apply_args_kwargs[args_kwargs1]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_groupby_rolling[1.0-True]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_groupby_rolling[0.0-False]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_getitem
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling_quantile[linear]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling_quantile[lower]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling_quantile[higher]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling_quantile[midpoint]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling_quantile[nearest]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling_apply[True]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling_apply[False]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_grouper.py::TestGrouperGrouping::test_rolling_apply_mutability
FAILED test_venv/lib/site-packages/pandas/tests/window/test_rolling.py::test_closed_one_entry_groupby[min]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_rolling.py::test_closed_one_entry_groupby[max]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_rolling.py::test_rolling_positional_argument[True-grouping0-_index0]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_rolling.py::test_rolling_positional_argument[True-grouping1-_index1]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_rolling.py::test_rolling_positional_argument[False-grouping0-_index0]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_rolling.py::test_rolling_positional_argument[False-grouping1-_index1]
FAILED test_venv/lib/site-packages/pandas/tests/window/test_timeseries_window.py::TestRollingTS::test_groupby_monotonic
FAILED test_venv/lib/site-packages/pandas/tests/window/test_timeseries_window.py::TestRollingTS::test_non_monotonic
```

Just going to skip these for now. Maybe (probably?) some overlap with #35148 @mroeschke. Not sure.

### PR DESCRIPTION
**Pull request by erfannariman**
ref #35294

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Does that fail for you on a 32-bit system? The second passes for me locally

```
pandas/tests/window/test_api.py::test_multiple_agg_funcs[rolling-2-expected_vals0] XFAIL                                                              [ 50%]
pandas/tests/window/test_api.py::test_multiple_agg_funcs[expanding-None-expected_vals1] PASSED                                                        [100%]
```

Also this wouldn't close #35294. To close that we would need to make the code compatible with 32-bit systems.

**Comment by erfannariman** [comment]
> Does that fail for you on a 32-bit system? The second passes for me locally
Not sure how to test it locally, I thought I push it and see if it passes the tests.

> Also this wouldn't close #35294. To close that we would need to make the code compatible with 32-bit systems.
Yes, my bad, removed the linked issue.

**Comment by TomAugspurger** [comment]
Our CI isn't set up to handle this yet. You're welcome to give that a shot, but it's not clear how best to do that since 32-bit conda packages aren't readily available.

**Comment by erfannariman** [comment]
@TomAugspurger so should I close this PR for now, then later maybe open an issue + PR to handle 32-bit failures?

**Comment by TomAugspurger** [comment]
Yeah, we'll close this.

I don't think we need any new issues though I may be wrong.

**Pull request closed without merging**
