### PR TITLE
STYLE: Ignore some pycodestyle errors

### PR DESCRIPTION
**Pull request by TomAugspurger**
xref https://github.com/pandas-dev/pandas/issues/16933

### CODE REVIEW

**Comment by jreback** [comment]
no don't change these here
we don't actually want to change the linter itself
rather configure the pep8speaks (i will turn off for now)

**Comment by TomAugspurger** [comment]
> rather configure the pep8speaks (i will turn off for now)

You mean add a `.pep8speaks.yml` file?

**Comment by jreback** [comment]
yeah I am going to push one now

**Comment by gfyoung** [comment]
@TomAugspurger : Closing in light of @jreback comment <a href="https://github.com/pandas-dev/pandas/pull/16944#issuecomment-315532966">above</a>.

**Pull request closed without merging**
