### PR TITLE
ENH: droplevel copy keyword

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
One merge conflict otherwise LGTM

**Comment by jbrockmendel** [comment]
i think CI fail is unrelated

**Review by jorisvandenbossche — CHANGES_REQUESTED** [review]
@jbrockmendel I see you did already another PR to add `copy` to `set_axis` as well. In general (and certainly if you are planning a concerted effort to add this to several methods), it would be helpful if you would create an issue for this that can be referenced, and to give some context for the proposed change. 

Personally, I am not sure we should actually add those keywords right now (or we should at least have some discussion about it). I know we already have some places that have such a keyword (and in general I would like to see this used more as well). But with https://github.com/pandas-dev/pandas/pull/46958/ we are also planning to change the behaviour of that keyword. 
So we would be adding a new feature that might actually change behaviour in one the next releases. And that change of behaviour is quite subtle (it's not something that we can easily deprecate about for those specific cases). I would really like to avoid that more people start to rely on the mutability of dataframes returned in such a `copy=False` case.

**Comment by jbrockmendel** [comment]
opened #48141

**Comment by jorisvandenbossche** [comment]
Thanks for opening the issue!

**Pull request closed without merging**
