### PR TITLE
CLN: remove _set_subtyp

### PR DESCRIPTION
**Pull request by jbrockmendel**
its not used anywhere, apparently legacy leftover

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
Lgtm

**Comment by gfyoung** [comment]
https://github.com/pandas-dev/pandas/search?q=_subtyp&unscoped_q=_subtyp

@jbrockmendel : Do you intend to remove any remaining ones after this?  Or could we tackle all of them in this PR?

**Comment by jreback** [comment]
sure

**Comment by jbrockmendel** [comment]
> Do you intend to remove any remaining ones after this

You mean legacy methods?  Nothing actively planned, just as I come across them.  Or are you suggesting _subtyp should be removed from _internal_names?

**Comment by jreback** [comment]
> > Do you intend to remove any remaining ones after this
> 
> You mean legacy methods? Nothing actively planned, just as I come across them. Or are you suggesting _subtyp should be removed from _internal_names?

this actually migtht be doable

**Pull request merged**
