### PR TITLE
STY: add pandas._typing to the known_pre_core block for isort

### LINKED ISSUE #27534: STY: add pandas._typing to the known_pre_core block for isort

### PR DESCRIPTION
**Pull request by sameshl**
closes #27534

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Did you run I sort after this change?  I expect imports will be shuffled

**Comment by sameshl** [comment]
No i didn't run isort after the change

**Comment by jbrockmendel** [comment]
You’ll need to do that in order to get the CI to pass

**Comment by jbrockmendel** [comment]
hmm may need to put this on hold while the dependencies in pandas._typing get resolved.  ATM it isn't strictly correct to call it pre-core

**Comment by sameshl** [comment]
the error i am getting is [here](https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=14940&view=logs&jobId=435ca956-9126-505f-566f-fff31072e2ba&taskId=e3717827-2a2f-5148-8ad4-7900d2171f6e&lineStart=36&lineEnd=38&colStart=1&colEnd=1)
 It looks like isort is failing on `pandas/io/formats/formats.py` but then I tried running isort on that file on my local system it seems to pass the test.

**Comment by WillAyd** [comment]
How are you running this locally? It does appear that _typing is after core in that module so failure seems legit

**Review by WillAyd — CHANGES_REQUESTED** [review]
see comment above

**Comment by sameshl** [comment]
@WillAyd I first ran `isort --recursive --check-only pandas` and then after seeing failing import on `formats.py`, I ran `isort pandas/io/fomats/formats.py`.

**Comment by WillAyd** [comment]
@sameshl can you merge master?

**Comment by sameshl** [comment]
@WillAyd Do you want me to merge master into my branch? Isn't rebasing a better option?

**Comment by WillAyd** [comment]
Sorry for late reply as I've been on vacation for the past few weeks but yes we typically merge master instead of rebasing

**Comment by jreback** [comment]
pls merge master (you can rebase if you want, but merging is simpler); we squash on final merge anyways so it doesn't mater. ping on green.

**Comment by jreback** [comment]
closing as stale, if you want to continue, pls ping (and merge master)

**Pull request closed without merging**
