### PR TITLE
BLD: add tempita files to depends

### PR DESCRIPTION
**Pull request by chris-b1**
This change makes it so that if a `.pxi.in` file is modified, the appropriate module will be rebuilt.

### CODE REVIEW

**Comment by jreback** [comment]
what's the repro on current master?

change an .in and everything recompiles?

**Comment by chris-b1** [comment]
Opposite - e.g., change `algos_take_helper.pxi.in` and nothing recompiles, if it was already up to date.

**Comment by jorisvandenbossche** [comment]
Looks good to me

**Comment by jreback** [comment]
thanks!

**Pull request closed without merging**
