### PR TITLE
DOC: Fix Series nlargest and nsmallest doc strings (#43964)

### LINKED ISSUE #43937: DOC:
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

- https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.replace.html
- https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.replace.html
- and more 

### Documentation problem

Sphinx doc list item strange bold effect.

image

### Suggested fix for documentation

In using sphinx experience, the following could fix that.
Note that `numeric` and `replaced` have the same indent level.

```diff
            - numeric: numeric values equal to `to_replace` will be
-                replaced with `value`
+              replaced with `value`
```

```
- numeric: numeric values equal to `to_replace` will be
  replaced with `value`  
```

My local test result.

image

### PR DESCRIPTION
**Pull request by Zeroto521**
- [x] closes #43937
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] Cancel nlargest and nsmallest's doc list item text bold effect, detail could see below.

From
Clip_20211011_094600
To
Clip_20211011_105541

### CODE REVIEW

**Review by attack68 — APPROVED** [review]
lgtm

**Comment by alimcmaster1** [comment]
Thanks @Zeroto521  - LGTM.

Could you also fix or create a follow up issue for `DataFrame.nlargest` - look inconsistent with others backticks are not correct around the first args: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nlargest.html 
https://github.com/pandas-dev/pandas/blob/accf59c8d1c581a056d8202d1fed95fdfae1d897/pandas/core/frame.py#L6597

**Comment by alimcmaster1** [comment]
> > Could you also fix or create a follow up issue for `DataFrame.nlargest` - look inconsistent with others backticks are not correct around the first args: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nlargest.html
> 
> Do you mean to add double backticks for `first` and `last`, like the following?
> 
> ```diff
> -           - `first` : prioritize the first occurrence(s)
> -           - `last` : prioritize the last occurrence(s)
> +           - ``first`` : prioritize the first occurrence(s)
> +           - ``last`` : prioritize the last occurrence(s)
>             - ``all`` : do not drop any duplicates, even it means
>               selecting more than `n` items.
> ```

Yes exactly so they are consistent with the docs here :) @Zeroto521

**Comment by Zeroto521** [comment]
@alimcmaster1 see #44040

**Pull request merged**
