### PR TITLE
DEPR: Enforce ewm(times=str) deprecation

### PR DESCRIPTION
**Pull request by mroeschke**
Introduced in https://github.com/pandas-dev/pandas/pull/43265

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Test that it raises? Whatsnew?

**Comment by mroeschke** [comment]
> Test that it raises? Whatsnew?

Added test here https://github.com/pandas-dev/pandas/pull/48842/files#diff-3f0452bb29c5fda1dfc3fb1ec8346ac3a1fffe504c857d232c1df7a043b45ad8R239

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Review by phofl — COMMENTED** [review]
typing needs fixing, otherwise lgtm

**Pull request merged**
