### PR TITLE
DOC: Update development documentation urls

### PR DESCRIPTION
**Pull request by datapythonista**
In #26648 we started building the documentation in https://dev.pandas.io . Updated the links to the development documentation to point to the new url.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
and the README.md?

**Comment by datapythonista** [comment]
good point, updated, thanks @simonjayhawkins

**Comment by jreback** [comment]
how is  the domain permissioned?

**Comment by datapythonista** [comment]
Not sure what you mean, Wes configured the dns setting, and we set up it in github with a file name `CNAME` when we push to the github pages repo. The https is set up automatically by github (they generated a certificate for us, that took longer than expected but it's been working for couple of days).

**Comment by jreback** [comment]
can the prior site redirect to this new one?

**Comment by datapythonista** [comment]
Not setting up the dns, I'd say what we could do is replace every html in that site for a page with an http/javascript redirect.

I wouldn't bother being the dev site, there shouldn't be important links I guess. But I may be missing something.

**Comment by datapythonista** [comment]
discussed with @jorisvandenbossche, and we don't think it's worth bothering on building something to create redirects from the travis dev docs to the new dev docs.

If that's all right I'll simply add a note and a link in the home page of the old dev docs, in case anyone is not aware of the change. But we need to merge #26856 first, or travis will overwrite the note.

**Comment by TomAugspurger** [comment]
Agreed it's not worth redirecting.

**Comment by jreback** [comment]
yeah its fine not to redirect (in the docs themselves, but maybe just a message on the site would be fine with the new uri (e.g. a 1-time update)

**Comment by datapythonista** [comment]
I opened https://github.com/pandas-docs/pandas-docs-travis/pull/3 with the redirect message, I don't have write permissions to that repo. Does anyone have them? Otherwise, @jorisvandenbossche I think you've got the github token to push to that repo, don't you?

**Comment by datapythonista** [comment]
@jreback does this PR looks good? Probably worth merging soon, since we stopped the travis build now, and the urls are wrong.

**Comment by jreback** [comment]
thanks @datapythonista

**Pull request merged**
