### PR TITLE
CI: remove usage of legacy NPY_PROMOTION_STATE

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
We no longer need this, see also discussion in https://github.com/pandas-dev/pandas/pull/60140.

And this fixes CI on main (tests are currently failing if you use numpy >= 2 with this env variable set)

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
CI is passing, except for the pyarrow nightly build, which seems to be using numpy 1.26

**Comment by mroeschke** [comment]
Looks like I added a `numpy < 2` pin in `ci/deps/actions-311-pyarrownightly.yaml` in https://github.com/pandas-dev/pandas/pull/59046. Maybe that can be removed now.

If that works, maybe we can also remove the `nomkl` install patch as well now.

**Comment by jorisvandenbossche** [comment]
The Arrow nightly build seems a good one to use a later numpy version, but it might still be useful to test 1.26 somewhere?

**Comment by jorisvandenbossche** [comment]
This is all passing, so going to merge this to get CI green again. 

But I still think we ideally get the tests passing for numpy 1.26 as well (at some point our min version might be that version and we will test with it anyway. But will open a separate follow-up PR for that)

**Comment by jorisvandenbossche** [comment]
Manual backport -> https://github.com/pandas-dev/pandas/pull/60153

**Pull request merged**
