### PR TITLE
CI: Skip test when no xlwt or openpyxl

### PR DESCRIPTION
**Pull request by alimcmaster1**
Ref: https://github.com/pandas-dev/pandas/pull/37818

Seeing error in CI: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=47726&view=logs&j=acc1347f-8235-55b0-95c7-0e2189e61659&t=486f34f1-eda6-516a-fc5d-d8195128dacd

Skip logic same as `test_to_excel` in this file

cc @jreback

### CODE REVIEW

**Comment by jreback** [comment]
thanks @alimcmaster1 merge on green.

**Comment by alimcmaster1** [comment]
> thanks @alimcmaster1 merge on green.

will do thanks!

**Comment by alimcmaster1** [comment]
Potentially flaky test below - other issues seem fixed.
```
self = <pandas.tests.plotting.test_converter.TestRegistration object at 0x000001C5058A3C48>

    def test_pandas_plots_register(self):
        plt = pytest.importorskip("matplotlib.pyplot")
        s = Series(range(12), index=date_range("2017", periods=12))
        # Set to the "warn" state, in case this isn't the first test run
        with tm.assert_produces_warning(None) as w:
            s.plot()
    
>       assert len(w) == 0
E       assert 2 == 0
E        +  where 2 = len([<warnings.WarningMessage object at 0x000001C51321A188>, <warnings.WarningMessage object at 0x000001C506E39348>])

pandas\tests\plotting\test_converter.py:82: AssertionError
```

**Comment by alimcmaster1** [comment]
\azp run

**Comment by jreback** [comment]
its fine to merge this

**Pull request merged**
