### PR TITLE
CLN: remove unnecessary check in MultiIndex

### PR DESCRIPTION
**Pull request by jbrockmendel**
We raise a ValueError and immediately ignore it.

### CODE REVIEW

**Comment by jreback** [comment]
> We raise a ValueError and immediately ignore it.

this is an extra special technique!

**Comment by jbrockmendel** [comment]
> this is an extra special technique!

Yah, looks like this check was copied from the base class method and wrapped in a try/except for expedience

**Comment by jreback** [comment]
FYI ci all fixed now, just ping on green for the rest of the builds

**Comment by jreback** [comment]
thanks

**Pull request merged**
