### PR TITLE
BUG: Fix redundant run of unwinding nested dictionary

### PR DESCRIPTION
**Pull request by jiangyue12392**
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

The original implementation of checking whether the json contains nested structure is wrong as it will return `True` even for a non nested json (e.g. `[{'x' : 1}]`). The changes ensures that `nested_to_record` is not called unnecessarily

### CODE REVIEW

**Comment by WillAyd** [comment]
Is this in reference to a particular issue? Typically prefer an issue to be created first with a minimally reproducible example for discussion (simple documentation fixes are excepted)

**Comment by jiangyue12392** [comment]
I don't think there is an issue catering to this yet. The current implementation would not produce wrong result, but will run some codes unnecessarily. Should I produce an issue for this? @WillAyd

**Comment by jreback** [comment]
no need to make an actual issue but is there a performance boost or just code simplification? do our tests exercise this specifically?

**Comment by jiangyue12392** [comment]
There would be a performance boost for non-nested json objects as they would not be looped through unnecessarily again which is the intention of the `if` statement. There is no test for this currently. @jreback

**Comment by jiangyue12392** [comment]
@WillAyd Do you have any idea why the travis check failed?

**Comment by WillAyd** [comment]
Not sure might be a one off with the environment just restarted let’s see

**Comment by jiangyue12392** [comment]
@jreback Are you expecting tests to be added for this?

**Comment by jreback** [comment]
> @jreback Are you expecting tests to be added for this?

yep and / or perf benchmark

**Comment by WillAyd** [comment]
@jiangyue12392 do you have tests for this?

**Comment by WillAyd** [comment]
Thanks for the PR but somewhat unclear what this does. If you can add a test and / or performance benchmark feel free to ping and we can reopen to pick back up

**Pull request closed without merging**
