### PR TITLE
CI: Pin PYTEST_WORKERS=1 for Windows builds due to memory errors

### PR DESCRIPTION
**Pull request by mroeschke**
1. Running tests without xdist is okay
2. It's not due to pyarrow v8 (I think)
3. Same error with `windows-2019` as `windows-latest`

### CODE REVIEW

**Comment by mroeschke** [comment]
> im not seeing a way to download the log file (which is too big to display in the browser)

https://github.com/pandas-dev/pandas/suites/6902339888/logs?attempt=2 is the direct download link for the 3.9 build

**Comment by jbrockmendel** [comment]
Looks like you're doing trial/error to figure out what test is failing?  LMK if i can be helpful

**Comment by mroeschke** [comment]
> Looks like you're doing trial/error to figure out what test is failing? LMK if i can be helpful

Yeah, I think there's a memory leak somewhere but for now I'm just skipping tests to hopefully skip the one that leaks. If you have time/ideas how to identify the leaking test(s) that would be helpful

**Comment by mroeschke** [comment]
@jbrockmendel the first PR merged into main that exhibited these failures was https://github.com/pandas-dev/pandas/pull/47299. If you have a change could you comb over that PR again to see if any change there could cause a memory leak?

**Comment by jbrockmendel** [comment]
The changes in tzconversion.pyx are the most plausible candidate, though
not a slam dunk

**Comment by mroeschke** [comment]
@simonjayhawkins should we backport to 1.4.x or just merge to main?

**Comment by mroeschke** [comment]
Okay merging to get the CI back to green for Windows builds

**Comment by simonjayhawkins** [comment]
sure. have not seen windows failures on 1.4.x but if we don't know the root cause then no harm.

**Pull request merged**
