### PR TITLE
TST: Test pivot with categorical data

### LINKED ISSUE #8731: BUG: incorrectly output index ordering with an ordered Categorical and pivot
xref #8860, soln might be the same

from [SO](http://stackoverflow.com/questions/26741204/pandas-pivot-table-alphabetically-sorts-categorical-data-incorrectly-when-addi)

```
In [32]: df = DataFrame({'Sales' : [100,120,220], 'Month' : ['January','January','January'], 'Year' : [2013,2014,2013]})

In [33]: df
Out[33]: 
     Month  Sales  Year
0  January    100  2013
1  January    120  2014
2  January    220  2013

In [34]: df['Month'] = df['Month'].astype('category').cat.set_categories(['January', 'February', 'March', 'April', 'May', 'June',      'July', 'August', 'September', 'October', 'November', 'December'])

In [35]: df.dtypes
Out[35]: 
Month    category
Sales       int64
Year        int64
dtype: object

In [36]: df['Month']
Out[36]: 
0    January
1    January
2    January
Name: Month, dtype: category
Categories (12, object): [January < February < March < April ... September < October < November < December]

In [37]: df.pivot_table(values="Sales", index="Month")
Out[37]: 
Month
January      146.666667
February            NaN
March               NaN
April               NaN
May                 NaN
June                NaN
July                NaN
August              NaN
September           NaN
October             NaN
November            NaN
December            NaN
Name: Sales, dtype: float64

In [38]: df.pivot_table(values="Sales", index="Month").index
Out[38]: Index([u'January', u'February', u'March', u'April', u'May', u'June', u'July', u'August', u'September', u'October', u'November', u'December'], dtype='object')

In [39]: result = df.pivot_table(values='Sales', index="Month", columns="Year", aggfunc="sum")

In [40]: result
Out[40]: 
Year       2013  2014
Month                
April       NaN   NaN
August      NaN   NaN
December    NaN   NaN
February    NaN   NaN
January     320   120
July        NaN   NaN
June        NaN   NaN
March       NaN   NaN
May         NaN   NaN
November    NaN   NaN
October     NaN   NaN
September   NaN   NaN
```

### LINKED ISSUE #8860: Maintaining the order of the categorical variable that is passed into pd.crosstab
xref #8731, soln might be the same

Currently when we do a `crosstab`, the distinct values in each column is reported in the lexical order. But crosstabs are usually useful when we have categorical data (that may have an inherent ordering). 

``` python
import pandas as pd

d = {'MAKE' : pd.Series(['Honda', 'Acura', 'Tesla', 'Honda', 'Honda', 'Acura']),
'MODEL' : pd.Series(['Sedan', 'Sedan', 'Electric', 'Pickup', 'Sedan', 'Sedan'])}
data = pd.DataFrame(d)
pd.crosstab(data['MAKE'],data['MODEL'])

data['MODEL'] = data['MODEL'].astype('category')
data['MODEL'] = data['MODEL'].cat.set_categories(['Sedan','Electric','Pickup'])
pd.crosstab(data['MAKE'],data['MODEL'])
```

Both the cross-tab statements above result in the same output as below - essentially the code I believe is performing a lexical sort on the contents of the `Series` being passed.

```
Output:
MODEL  Electric  Pickup  Sedan
MAKE                          
Acura         0       0      2
Honda         0       1      2
Tesla         1       0      0
```

Would it be possible for `crosstab` to maintain the ordering of the categorical variable if column.cat.ordered on the passed column is True? Thanks!

### LINKED ISSUE #9534: pivot_table(aggfunc="count") with category column raise "ValueError: Cannot convert NA to integer"
Here is the test code, that return the right table:

```
import pandas as pd
data = {"C1":["A", "B", "C", "C"], "C2":["a", "a", "b", "b"], "V":[1, 2, 3, 4]}
df = pd.DataFrame(data)
df.pivot_table("V", index="C1", columns="C2", aggfunc="count")
```

when convert column to category, ValueError is raised:

```
df2 = df.copy()
df2["C1"] = df2["C1"].astype("category")
df2.pivot_table("V", index="C1", columns="C2", aggfunc="count")
```

groupby also raise the same error:

```
df2.groupby(["C1", "C2"]).count()
```

add `dropna()` to `count()` in `groupby.py` fix this problem:

```
    def count(self, axis=0):
        return self._count().dropna().astype('int64')
```

### PR DESCRIPTION
**Pull request by mroeschke**
closes #8860
closes #8731
closes #9534

Looks like the examples in these issues pass in the master branch. Added test to confirm.

### CODE REVIEW

**Comment by jreback** [comment]
@mroeschke thanks! 

can you see if you can figure out what issues solved these and list here.

If they are in 0.19.2 or 0.20, then we want to add these issues to the current whatsnew.

**Comment by jorisvandenbossche** [comment]
Cool! 
In any case, they were already solved in 0.19.1

**Comment by mroeschke** [comment]
Looks like #11371 may have helped address these issues back in 0.17.1, but I am not finding any recent PRs fixing these issues.

**Comment by jreback** [comment]
thanks!

**Pull request closed without merging**
