### PR TITLE
DOC: update ohlc docstring so that it reflects the real use #31919

### LINKED ISSUE #31919: ohlc documentation
The documentation for ohlc is missleading. In https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html The following doc appears, which probably references the docstring in the code.
image

A sentence like `Computes open, high, low and close values, excluding missing values` is probably more complete.

### PR DESCRIPTION
**Pull request by dequadras**
- [x] closes #31919
- [x] tests added / passed

The test python scripts/validate_docstrings.py pandas.core.groupby.GroupBy.ohlc returns errors, but that is something that happens with many functions at the moment

```################################################################################
################# Docstring (pandas.core.groupby.GroupBy.ohlc) #################
################################################################################

Compute open, high, low and close values of a group, excluding missing values.

For multiple groupings, the result index will be a MultiIndex

Returns
-------
DataFrame
    Open, high, low and close values within each group.

See Also
--------
Series.groupby
DataFrame.groupby

################################################################################
################################## Validation ##################################
################################################################################

3 Errors found:
	Missing description for See Also "Series.groupby" reference
	Missing description for See Also "DataFrame.groupby" reference
	No examples section found```

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
Thanks @dequadras - the errors seem unrelated

**Comment by MarcoGorelli** [comment]
> but that is something that happens with many functions at the moment

Yes, the CI check ignores certain errors:
```
### DOCSTRINGS ###
if [[ -z "$CHECK" || "$CHECK" == "docstrings" ]]; then

    MSG='Validate docstrings (GL03, GL04, GL05, GL06, GL07, GL09, GL10, SS04, SS05, PR03, PR04, PR05, PR10, EX04, RT01, RT04, RT05, SA02, SA03, SA05)' ; echo $MSG
    $BASE_DIR/scripts/validate_docstrings.py --format=actions --errors=GL03,GL04,GL05,GL06,GL07,GL09,GL10,SS04,SS05,PR03,PR04,PR05,PR10,EX04,RT01,RT04,RT05,SA02,SA03,SA05
    RET=$(($RET + $?)) ; echo $MSG "DONE"

fi
```

**Comment by WillAyd** [comment]
Can you merge master?

**Comment by dequadras** [comment]
> Can you merge master?

I don't have write access

**Comment by MarcoGorelli** [comment]
> > Can you merge master?
> 
> I don't have write access

I think Will was suggesting that you merge them locally and push another commit:
```
git fetch upstream master
git merge upstream/master
git push origin ohlc-docstring-update
```

**Comment by dequadras** [comment]
> Can you merge master?

Done

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @dequadras

**Pull request merged**
