### PR TITLE
Backport PR #38247 on branch 1.2.x (BUG: Limited available colors)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #38247: BUG: Limited available colors

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
This is an enhancement, we shouldn't start backporting such PRs IMO

**Comment by jreback** [comment]
> This is an enhancement, we shouldn't start backporting such PRs IMO

this is to 1.2 and actually was ready way before the rc. i don't view this as a big deal.

**Comment by jorisvandenbossche** [comment]
Yes, sure, for this specific PR it would be more work to undo it, but so I was speaking in general for other PRs

**Comment by jreback** [comment]
agreed

only regressions for 1.2  at this point

**Pull request merged**
