### PR TITLE
CI: Troubleshoot

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by mroeschke** [comment]
My theory proved incorrect in https://github.com/pandas-dev/pandas/pull/45500. Looks like you're having more luck here?

**Comment by jbrockmendel** [comment]
looks like azure is green.  time to whittle these down...

**Comment by jreback** [comment]
great

**Comment by jreback** [comment]
any luck here?

**Comment by jreback** [comment]
can we force the windows builds to a single cpu? (and maybe disable some expensive tests / keep 2 builds)

**Comment by jbrockmendel** [comment]
> any luck here?

slowly narrowing it down

**Comment by jbrockmendel** [comment]
OK! looks like its somewhere in usecols...

**Comment by jbrockmendel** [comment]
im bashing my head against the wall here, need to tag someone else in on this

**Comment by jreback** [comment]
can we look at the past CI runs when we were green and see what changed in the config?

**Comment by jbrockmendel** [comment]
The build that just failed is almost identical to one that passed a few hours ago (see the "remove usecols" commit above 71bf824).  That commit also removed the entire usecols directory, while this one left `usecols/__init__.py`

**Comment by mroeschke** [comment]
> can we force the windows builds to a single cpu? (and maybe disable some expensive tests / keep 2 builds)

Trying this approach in https://github.com/pandas-dev/pandas/pull/45547. The CI is really backed up right now so it might take a while to get to

**Comment by jbrockmendel** [comment]
> The CI is really backed up right now so it might take a while to get to

Could/should we just cancel some of the non-fixing-this azure jobs to speed this up?

**Comment by mroeschke** [comment]
> > The CI is really backed up right now so it might take a while to get to
> 
> Could/should we just cancel some of the non-fixing-this azure jobs to speed this up?

Yeah if there are lot of queued up jobs it would allow to debug this quicker. But looks like the queue cleared up overnight

**Comment by jbrockmendel** [comment]
azure green!

**Comment by mroeschke** [comment]
> azure green!

Confident it was this or do you think retriggering the CI will confirm this?

**Comment by jreback** [comment]
ok let's merge on green (i retriggered)

**Comment by jreback** [comment]
let's also an issue to troubleshoot this as well (this case you are skipping)

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
