### PR TITLE
[ArrowStringArray] PERF: use pyarrow.compute.replace_substring(_regex) if available

### LINKED ISSUE #41602: BUG: case argument ignored when regex is False in Series.str.replace
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> ser = pd.Series(["A.", "a.", "Ab", "ab", np.nan], dtype="object")
>>> ser
0     A.
1     a.
2     Ab
3     ab
4    NaN
dtype: object
>>> 
>>> ser.str.replace("a", "c", case=False, regex=False)
0     A.
1     c.
2     Ab
3     cb
4    NaN
dtype: object
>>> 
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Expected Output

```
>>> ser.str.replace("a", "c", case=False, regex=False)
0     c.
1     c.
2     cb
3     cb
4    NaN
dtype: object
>>> 
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

### PR DESCRIPTION
**Pull request by simonjayhawkins**
```
[ 50.00%] ··· strings.Methods.time_replace                                                                                                                ok
[ 50.00%] ··· ============== ==========
                  dtype                
              -------------- ----------
                   str        20.6±0ms 
                  string      16.3±0ms 
               arrow_string   1.83±0ms 
              ============== ==========
```

happy to break up if easier to review.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
> happy to break up if easier to review.

will do that and mark this as draft for now.

**Comment by simonjayhawkins** [comment]
closes #41602 , will break off once other pre-cursors merged

**Comment by simonjayhawkins** [comment]
> closes #41602 , will break off once other pre-cursors merged

opened #41606, after that is merged, this PR is just the addition of the method on ArrowStringArray

**Comment by simonjayhawkins** [comment]
> opened #41606, after that is merged, this PR is just the addition of the method on ArrowStringArray

will close till then to help clear the queue.

**Comment by jreback** [comment]
@simonjayhawkins at some point should have a whatsnew sub-section about the new arrow perf string functions.

**Comment by simonjayhawkins** [comment]
sure. I think should probably draw a line under the str accessor methods for now (this is perf only as str accessor methods all fallback if not implemented on the array, we have parameterised test for most) and concentrate on dtype/docs/skipped tests. Will do that in parallel with preparing for the rc.

**Comment by simonjayhawkins** [comment]
> @simonjayhawkins at some point should have a whatsnew sub-section about the new arrow perf string functions.

added to #39908

**Pull request merged**
