### PR TITLE
BUG: Corrected TypeError message

### LINKED ISSUE #50974: BUG: DatetimeIndex() constructor with mixed timezones gives confusing TypeError
Passing strings with different timezone offsets correctly raises an error, but the error message is wrong / confusing:

```
In [2]: pd.DatetimeIndex(["2013-11-02 22:00-05:00", "2013-11-03 22:00-06:00"], ambiguous=True)
...
File ~/scipy/pandas/pandas/core/arrays/datetimes.py:2176, in objects_to_datetime64ns(data, dayfirst, yearfirst, utc, errors, allow_object)
   2174     if allow_object:
   2175         return result, tz_parsed
-> 2176     raise TypeError(result)
   2177 else:  # pragma: no cover
   2178     # GH#23675 this TypeError should never be hit, whereas the TypeError
   2179     #  in the object-dtype branch above is reachable.
   2180     raise TypeError(result)

TypeError: [datetime.datetime(2013, 11, 2, 22, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400)))
 datetime.datetime(2013, 11, 3, 22, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800)))]
```

This happens on current main (2.0.0dev), but I see  the same behaviour on released pandas (1.5.3)

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [x ] closes #50974  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ x] Added an entry in the latest `doc/source/whatsnew/v2.0.0.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Can you add a test checking the error message?

**Comment by DeaMariaLeon** [comment]
Sure @phofl but where??? at pandas/tests/indexes/datetimes/test_datetime.py ? 
or
pandas/tests/indexes/datetimes/test_indexing.py  maybe?  

Thanks in advance

**Comment by phofl** [comment]
I'd suggest

```
pandas/tests/indexes/datetimes/test_constructors.py
```

**Review by phofl — APPROVED** [review]

**Comment by phofl** [comment]
thx @DeaMariaLeon

**Comment by DeaMariaLeon** [comment]
Thank you @phofl

**Pull request merged**
