### PR TITLE
BUG: PeriodIndex[B].to_timestamp inferring "D" instead of "B".

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [x] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]

**Comment by jreback** [comment]
looks user facing? needs a note

**Comment by jreback** [comment]
> > looks user facing? needs a note
> 
> sure, will update.

ping when ready

**Comment by jbrockmendel** [comment]
ping

**Comment by jreback** [comment]
hmm are these failures in master?

**Comment by jbrockmendel** [comment]
> hmm are these failures in master?

yes.  i think #44381 handles all but one of them

**Comment by jreback** [comment]
ok can you rebase just to check then. what is the one that is not handedl?

**Comment by jbrockmendel** [comment]
> what is the one that is not handedl?

theres an sdist one that's failing in 52 seconds

**Review by jreback — APPROVED** [review]

**Pull request merged**
