### PR TITLE
DOC: Fix some RT02 issues in docstrings

### LINKED ISSUE #49968: DOC: Fix RT02 issues in docstrings
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Several different pandas modules. See below for the list from ./scripts/validate_docstrings.py.

### Documentation problem

The functions below have more than just the return type in the first line of the returns section. (RT02: The first line of the Returns section should contain only the type, unless multiple values are being returned)

### Suggested fix for documentation

Per the recommendation in #27977, I've created this issue for the RT02 error code. To prevent duplicate work, comment below which functions you're going to take and reference this issue in your PR.

- [ ] pandas.io.formats.style.Styler.apply
- [ ] pandas.io.formats.style.Styler.applymap
- [ ] pandas.io.formats.style.Styler.apply_index
- [ ] pandas.io.formats.style.Styler.applymap_index
- [ ] pandas.io.formats.style.Styler.format
- [ ] pandas.io.formats.style.Styler.format_index
- [ ] pandas.io.formats.style.Styler.relabel_index
- [ ] pandas.io.formats.style.Styler.hide
- [ ] pandas.io.formats.style.Styler.concat
- [ ] pandas.io.formats.style.Styler.set_td_classes
- [ ] pandas.io.formats.style.Styler.set_table_styles
- [ ] pandas.io.formats.style.Styler.set_table_attributes
- [ ] pandas.io.formats.style.Styler.set_tooltips
- [ ] pandas.io.formats.style.Styler.set_caption
- [ ] pandas.io.formats.style.Styler.set_sticky
- [ ] pandas.io.formats.style.Styler.set_properties
- [ ] pandas.io.formats.style.Styler.set_uuid
- [ ] pandas.io.formats.style.Styler.highlight_null
- [ ] pandas.io.formats.style.Styler.highlight_max
- [ ] pandas.io.formats.style.Styler.highlight_min
- [ ] pandas.io.formats.style.Styler.highlight_between
- [ ] pandas.io.formats.style.Styler.highlight_quantile
- [ ] pandas.io.formats.style.Styler.background_gradient
- [ ] pandas.io.formats.style.Styler.text_gradient
- [ ] pandas.io.formats.style.Styler.bar
- [ ] pandas.io.formats.style.Styler.export
- [ ] pandas.io.formats.style.Styler.use
- [ ] pandas.Index.all
- [ ] pandas.Index.any
- [ ] pandas.Index.drop
- [ ] pandas.Index.drop_duplicates
- [ ] pandas.Index.insert
- [ ] pandas.Index.repeat
- [ ] pandas.Index.map
- [ ] pandas.Index.intersection
- [ ] pandas.Index.union
- [ ] pandas.Index.difference
- [ ] pandas.Index.symmetric_difference
- [ ] pandas.Index.get_indexer
- [ ] pandas.Index.get_loc
- [ ] pandas.Index.slice_indexer
- [ ] pandas.Index.slice_locs
- [ ] pandas.CategoricalIndex.rename_categories
- [ ] pandas.CategoricalIndex.reorder_categories
- [ ] pandas.CategoricalIndex.add_categories
- [ ] pandas.CategoricalIndex.remove_categories
- [ ] pandas.CategoricalIndex.remove_unused_categories
- [ ] pandas.IntervalIndex.get_indexer
- [ ] pandas.IntervalIndex.set_closed
- [ ] pandas.MultiIndex.to_frame
- [ ] pandas.MultiIndex.get_loc
- [ ] pandas.MultiIndex.get_loc_level
- [ ] pandas.MultiIndex.get_indexer
- [ ] pandas.MultiIndex.get_level_values
- [ ] pandas.DatetimeIndex.to_pydatetime
- [ ] pandas.TimedeltaIndex.to_pytimedelta
- [ ] pandas.Series.astype
- [ ] pandas.Series.infer_objects
- [ ] pandas.Series.copy
- [ ] pandas.Series.get
- [ ] pandas.Series.pipe
- [ ] pandas.Series.pct_change
- [ ] pandas.Series.align
- [ ] pandas.Series.set_axis
- [ ] pandas.Series.take
- [ ] pandas.Series.first_valid_index
- [ ] pandas.Series.last_valid_index
- [ ] pandas.Series.dt.total_seconds
- [ ] pandas.Series.str.center
- [ ] pandas.Series.str.encode
- [ ] pandas.Series.str.ljust
- [ ] pandas.Series.str.normalize
- [ ] pandas.Series.str.rjust
- [ ] pandas.Series.cat.rename_categories
- [ ] pandas.Series.cat.reorder_categories
- [ ] pandas.Series.cat.add_categories
- [ ] pandas.Series.cat.remove_categories
- [ ] pandas.Series.cat.remove_unused_categories
- [ ] pandas.DataFrame.astype
- [ ] pandas.DataFrame.infer_objects
- [ ] pandas.DataFrame.copy
- [ ] pandas.DataFrame.get
- [ ] pandas.DataFrame.pipe
- [ ] pandas.DataFrame.pct_change
- [ ] pandas.DataFrame.align
- [ ] pandas.DataFrame.set_axis
- [ ] pandas.DataFrame.take
- [ ] pandas.DataFrame.swapaxes
- [ ] pandas.DataFrame.update
- [ ] pandas.DataFrame.first_valid_index
- [ ] pandas.DataFrame.last_valid_index
- [ ] pandas.DataFrame.sparse.to_coo
- [ ] pandas.merge_asof
- [ ] pandas.date_range
- [ ] pandas.arrays.IntervalArray.set_closed
- [ ] pandas.api.types.is_dict_like
- [ ] pandas.api.types.is_file_like
- [ ] pandas.api.types.is_named_tuple
- [ ] pandas.api.types.is_number
- [ ] pandas.api.types.is_re
- [ ] pandas.api.types.is_re_compilable
- [ ] pandas.core.groupby.DataFrameGroupBy.get_group
- [ ] pandas.core.groupby.SeriesGroupBy.get_group
- [ ] pandas.core.groupby.SeriesGroupBy.apply
- [ ] pandas.core.groupby.DataFrameGroupBy.apply
- [ ] pandas.core.groupby.SeriesGroupBy.pipe
- [ ] pandas.core.groupby.DataFrameGroupBy.pipe
- [ ] pandas.core.groupby.DataFrameGroupBy.filter
- [ ] pandas.core.groupby.SeriesGroupBy.filter
- [ ] pandas.core.groupby.DataFrameGroupBy.take
- [ ] pandas.core.groupby.SeriesGroupBy.take
- [ ] pandas.read_pickle
- [ ] pandas.io.json.build_table_schema
- [ ] pandas.read_hdf
- [ ] pandas.core.resample.Resampler.get_group
- [ ] pandas.core.resample.Resampler.transform
- [ ] pandas.core.resample.Resampler.pipe
- [ ] pandas.api.extensions.ExtensionArray.astype
- [ ] pandas.api.extensions.ExtensionArray.dropna
- [ ] pandas.api.extensions.ExtensionArray.isna
- [ ] pandas.api.extensions.ExtensionArray.repeat
- [ ] pandas.api.extensions.ExtensionArray.unique

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [ ] closes #49968 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Towards #49968

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Awesome good to see this fully enforced @DeaMariaLeon!

If interested in continuing with these validation there are other codes that we don't enforce https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks

( I would personally love to see EX01 enforced )

**Comment by DeaMariaLeon** [comment]
Thanks @mroeschke. 

> If interested in continuing with these validation there are other codes that we don't enforce https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks
> 
> ( I would personally love to see EX01 enforced )

Yes, I'm interested. Would it be this issue? #37875

**Comment by mroeschke** [comment]
Correct.

**Comment by MarcoGorelli** [comment]
Yeah, exactly - even a PR to add something like
```
    MSG='Partially validate docstrings (EX01)' ; echo $MSG
    $BASE_DIR/scripts/validate_docstrings.py --format=actions --errors=EX01 --ignore_functions \
	    <list of functions goes here>
```
(just like there was for RT02, until you fixed them all 🙌 ) would be really welcome

**Comment by DeaMariaLeon** [comment]
Sure @MarcoGorelli I would be happy to help. Thanks for letting me know.

**Pull request merged**
