### PR TITLE
DEPR: to_clipboard, read_clipboard

### LINKED ISSUE #52129: DEPR: to_clipboard
Discussed briefly in #52020.  At least some of the relevant tests are xfailed (though they are xpassing locally for me on mac).  Might just be "wide unicode"?

`pandas.io.clipboard.__init__` looks like it is adapted from "pyperclip".  Is there a real need for this to live in pandas?

xref #45433 similar suggestion for s3 support

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #52129 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by WillAyd** [comment]
Why do we want to deprecate these? I personally find them useful every now and again - are these a maintenance burden?

**Comment by jbrockmendel** [comment]
My main complaint is that we effectively aren't (and AFAICT can't) test it on the CI.  If I'm wrong about it being rarely used then i wont mind keeping it around.

**Comment by WillAyd** [comment]
I would prefer to keep these. Sure not the main reason for using pandas, but they are nice for quick transfers of data across applications

**Comment by MarkRotchell** [comment]
I use this functionality all the time. Often will define something like the below at the top of a notebook for sending arbitraty array-likes to the clipboard as I'm modelling. Clearly,  not something needed (much?) in production code, but when doing ad-hoc throw-away work/analysis, it's incredibly useful.

```python
def clippy(data):
    pd.DataFrame(data).to_clipboard()
```

**Comment by mroeschke** [comment]
My attempt to test clipboard in the CI in https://github.com/pandas-dev/pandas/pull/56084

**Comment by phofl** [comment]
Merged the test pr, so closing here

**Pull request closed without merging**
