### PR TITLE
Pandas sql

### LINKED ISSUE #30480: Adding sql functionality to pandas similar to spark sql
I would like to add functionality to pandas so that data frames can be queried like database tables, similar to the way that they can be in spark-sql. 

I think it should work in a similar fashion.

A table can be registered using register_temp_table(dataframe, table_name).

Then using ```pandas.query("select * from table_name")``` you can query the data frame or any other ones registered using standard sql syntax.

I've already implemented the entire thing, but I was told to open an issue for it. 

Also I'm aware that there is a package called pandassql but this package actually just puts a data frame into a sql lite database, as opposed to querying a data frame directly, and transforming the sql into pandas methods that are then applied to the data frame.

Motivation:
The motivation for this enhancement is to make pandas more accessible to a crowd of users that may not be as technical and also to provide ease of transition for legacy code in systems like sas that have SQL already embedded in their programs. I'll supply a context free grammar in my documentation to show exactly what this system can handle, but it can basically handle any traditional SQL select statement, including subqueries, joins, where clauses, group by clauses, any aggregate function already supported by pandas, limit, and order by clauses. It also has support for rank and dense_rank window functions. It can't do things that sql wouldn't normally do like cross tab and you can't use a user defined function in it although I think that could be a good add-on. 

Datatypes:
The interface supports all pandas datatypes, so to cast something as an integer the syntax would currently be cast(some_number as int64) or cast(some_int as object). I've played around with the idea of varchar, char, bigint and smallint, but I think those would be misleading as those aren't datatypes that are supported by pandas currently.

Errors:
Currently the exceptions that it will throw that come this api are based solely around trying to select from an unregistered table, or from submitting an improperly written sql query, both of which you wouldn't want to silence so there's only one error mode. 

Api Choices:
The reason I made the register_temp_table section of the api top level was to avoid attaching a method to DataFrame although if others think it might be better as a method, I would change it in that manner (DataFrame.register_temp_table(table_name)). The reason pandas.query is a top level method is that it's relational in structure. You can select from multiple tables and join them and such and so it wouldn't make sense for it to be on a DataFrame level. The only similarity to the .query DataFrame method though is the name. DataFrame.query is just an alternate way of expressing things like DataFrame[some_condition] whereas my .query encompasses a large amount of the pandas api.

Built In:
I have two reasons that I think this would be better built in. The first is that the target audience for this is less technical pandas users. Part of making this api easier to use is lessening the burden of researching code and learning how python works, so I think that for them to go looking for an external package may be hard to begin with and they would also need to know to look for one. 
My second reason is that, from using what I've built, I've found pandas a lot easier to use just as a developer.
Suppose we have a DataFrame with one column called A, it goes from 
This code:
```
dataframe[name_1] = dataframe[a] - 1
dataframe[name_2] = dataframe[a] + 1
dataframe = dataframe[dataframe[name_1] == dataframe[name_2]]
dataframe.drop(columns=['a'], inplace=True)
```

To this code:
```pd.query("select a - 1 as name_1, a + 1 as name_2 from some_table where name_1 = name_2")```

Also although I did implement register_temp_table as an api level function, it would serve best as a method on a DataFrame so that's another thing to consider. 

I can't really provide any support for the lark part, other than that it seemed like the best tool for what I was making.

I apologize for the style and such, I'll be fixing all that before I'm done. I implemented this outside of pandas first, so that's why there are so many style and documentation discrepancies.

### PR DESCRIPTION
**Pull request by zbrookle**
closes #30480 

This merge will add in a functionality that works as follows:

A table can be registered using register_temp_table(dataframe, table_name)

Then using pandas.query("select * from table_name") you can query the data frame or any other ones registered using standard sql syntax.

### CODE REVIEW

**Comment by alimcmaster1** [comment]
Thanks for the PR - @zbrookle ! Is there an issue open for this?

**Review by jreback — CHANGES_REQUESTED** [review]
pls
open an issue first for discussion first

how does this differ from pandassql package?

**Comment by zbrookle** [comment]
The pandas sql package actually just puts dataframes in a SQLite database whereas this actually collects metadata and parses the sql string, and then transforms it into actual pandas commands. All of the functionality in this is native to pandas

**Comment by jreback** [comment]
@zbrookle see the link i added; this would be interesting if it generated an ibis expression directly

**Comment by zbrookle** [comment]
@jreback I agree that ibis would be interesting, but I don't think it will provide the value that I'm looking to add in this merge. Part of the reason that I think sql would be so useful in pandas is because it will make it more accessible to data analysts that know only sql and not too much about coding, and it will also make it easier for legacy systems that have code written in sql to transition over to pandas from something like SAS. I realize this could be another package, but the same could be said for spark sql and really for certain parts of pandas that already exist, but they're in one cohesive package for ease of use. Putting this into another package will make it just that much harder for the audience that I think this enhancement will help to utilize it

**Comment by datapythonista** [comment]
Thanks for the contribution @zbrookle 

But as being said, there needs to be some discussion before we consider accepting a PR for this.

I'm -1 on several things here:
- The `query` function is ambiguous with `DataFrame.query`
- `register_temp_table` doesn't seem important enough to live as a top-level function
- There is no documentation
- Adding new csv files (pandas code is already huge, takes a long time to download, and is we are not careful  it'll grow too big)

I think the best approach here is to implement this as a third-party package. If you require changes in pandas itself to develop this properly as an extension, PRs are more than welcome (open an issue first). If you create an extension make sure you add it to the ecosystem page, so people is aware of it. If eventually this becomes popular and mature enough, we can surely discuss moving it to pandas.

Closing this, as I don't think we'll be merging, and having too many open pull requests makes our life more difficult as maintainers.

**Comment by WillAyd** [comment]
I actually like this idea as I can see it being much more useful than the existing `.query` method, though noted on all concerns above. @zbrookle is this something you have actually used? Perhaps in a standalone package?

**Comment by jreback** [comment]
see my comments / questions [here](https://github.com/pandas-dev/pandas/issues/30480#issuecomment-569055323) which need resolution.

**Comment by zbrookle** [comment]
@datapythonista Those are all really valid points, I actually implemented this outside of pandas first, which is why there are so many differences in style. The reason register_temp_table is a top level function is because that seemed like the best way to not interfere with the structure of dataframe objects, although I would prefer if it was dataframe.register_temp_table().
The documentation is something I can definitely add. 
Also in terms of CSVs I can redo my unit testing to use ones that are already present

**Comment by alimcmaster1** [comment]
> @datapythonista Those are all really valid points, I actually implemented this outside of pandas first, which is why there are so many differences in style. The reason register_temp_table is a top level function is because that seemed like the best way to not interfere with the structure of dataframe objects, although I would prefer if it was dataframe.register_temp_table().
> The documentation is something I can definitely add.
> Also in terms of CSVs I can redo my unit testing to use ones that are already present

Let’s wait for the discussion to reach a conclusion in the issue before writing and more code. (In the interest of your time)

**Pull request closed without merging**
