### PR TITLE
Use NaN as na_value for new pyarrow_numpy StringDtype

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

xref https://github.com/pandas-dev/pandas/issues/54792

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Looking just at the single commit https://github.com/pandas-dev/pandas/pull/54585/commits/d862ecaf3aa05082d36512f994d99106cc7c10b1, that looks good to me

**Comment by phofl** [comment]
cc @jbrockmendel

**Comment by phofl** [comment]
rebased, the diff is more manageable now

cc @jorisvandenbossche @jbrockmendel

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by phofl** [comment]
merging this

**Comment by phofl** [comment]
@meeseeksdev backport to 2.1.x

**Pull request merged**
