### PR TITLE
CI: Improve API of --ignore_errors in validate_docstrings.py

### PR DESCRIPTION
**Pull request by datapythonista**
Follow up of #57879, to use `--ignore_errors PR02,SA01` instead of `--ignore_errors * PR02,SA01`.

I also make the script ignore the specified errors when running for a single document (i.e. `validate_docstrings.py pandas.Series -i SA01` was reporting the SA01 error before this PR, and it won't with the changes here).

CC: @mroeschke

### CODE REVIEW

**Review by dontgoto — APPROVED** [review]
It's probably overly safe, but one could verify that only one CLI parameter is specifying globally ignored errors, otherwise one set would overwrite the other

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @datapythonista

**Comment by jordan-d-murphy** [comment]
Thanks for all the work on this @datapythonista! `code_checks.sh` is looking awesome with thse new improvements. Just wanted to check and make sure this was the last change you had pending. If this is the final update, I can go ahead and open new issues to address these.

**Comment by datapythonista** [comment]
Yes, no more changes to the ignore functions in `code_checks.sh`. You should also have the triage permissions now.

**Comment by jordan-d-murphy** [comment]
Opened [DOC: Enforce Numpy Docstring Validation (Parent Issue) #58063](https://github.com/pandas-dev/pandas/issues/58063) as a parent issue for fixing docstrings based on the refactoring in code_checks.sh 

Feel free to swing by and help out! 🙂

**Pull request merged**
