### PR TITLE
CLN/COMPAT: Remove raise StopIteration syntax in SparseArray.__iter__

### LINKED ISSUE #11108: COMPAT: return instead of raising StopIteration in generator
And a couple other changes for [PEP479](https://www.python.org/dev/peps/pep-0479/) to avoid warnings. Will submit a PR if others agree.

### PR DESCRIPTION
**Pull request by kawochen**
closes #11108

### CODE REVIEW

**Comment by jreback** [comment]
why is this bad? e.g. if you are iterating with a generator with works just fine

**Comment by kawochen** [comment]
this causes a `PendingDeprecationWarning` in 3.5 and will be deprecated in 3.7 ([PEP479](http://legacy.python.org/dev/peps/pep-0479/))
this syntax doesn't cause a problem here, but it could if combined with a context manager, where the `StopIteration` exception will be caught in `__exit__()` and potentially causes the context manager to take a different path (depending on the presence of try-except constructs in the context manager)

**Comment by jreback** [comment]
is this an API change though?

**Comment by kawochen** [comment]
No.  Using `return` (or just leaving it out, since there is no more code) and `raise StopIteration` are the same in this function (except for the warnings).  They are different only when there is something inside the generator that could interfere with exception propagation.

**Comment by jreback** [comment]
ok seems reasonable. add a whatsnew note.

**Comment by kawochen** [comment]
which section?

**Comment by jreback** [comment]
I guess API changes; this is mainly to have a record of this.

**Comment by kawochen** [comment]
green

**Comment by jreback** [comment]
thanks!

**Pull request merged**
