### PR TITLE
CLN: move pytables tests to tests/io/pytables dir

### PR DESCRIPTION
**Pull request by jgehrcke**
This is a follow-up to [this comment](https://github.com/pandas-dev/pandas/pull/26818#issuecomment-504443559).

This moves two test modules (`test_pytables.py` and `test_pytables_missing.py`) into the new `tests/io/pytables` directory introduced in https://github.com/pandas-dev/pandas/pull/26818.

@jreback let me know if I should create an issue for this first.

### CODE REVIEW

**Comment by jreback** [comment]
@jgehrcke no issue needed for this, which is basically a pre-cursor for #18498 

can you add an ``__init__.py`` (we traditionally do this for the test dirs) and ping on green.

**Comment by jgehrcke** [comment]
> can you add an __init__.py (we traditionally do this for the test dirs)

Now that you mentioned it three times I suppose it's time :-) Done.

**Comment by jreback** [comment]
> > can you add an **init**.py (we traditionally do this for the test dirs)
> 
> Now that you mentioned it three times I suppose it's time :-) Done.

thanks!

**Comment by jreback** [comment]
thanks @jgehrcke very nice!

**Pull request merged**
