### PR TITLE
REF: remove is_simple_frame from json code

### PR DESCRIPTION
**Pull request by jbrockmendel**
cc @WillAyd the simple_frame path is kludgy, I expect fragile to non-numpy blocks.  This just rips it out to simplify the code.

### CODE REVIEW

**Comment by lithomas1** [comment]
Any perf impact?

**Review by WillAyd — APPROVED** [review]
lgtm if no regression. good to get rid of these branches

**Comment by jbrockmendel** [comment]
```
import numpy as np
import pandas as pd

arr = np.random.randn(10**4, 10)
df = pd.DataFrame(arr)

In [4]: %timeit df.to_json()
12.8 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)  # <- main
12.4 ms ± 448 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)  # <- PR

In [5]: %timeit df.T.to_json()
12 ms ± 413 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)  # <- main
19.2 ms ± 309 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)  # <- PR
```

So for very-wide cases this takes a hit, but indistinguishable for normal cases.

**Comment by WillAyd** [comment]
I think that is fine. Not worth optimizing to_json for very wide frames at the ms level

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
