### PR TITLE
TST: add NaN tests for all data types (#12535)

### LINKED ISSUE #12535: TST: test_window/Datetimelike adjustments
- need to include nans in `Datetimelike`. they work, but need to adjust tests.

xref #12376

### PR DESCRIPTION
**Pull request by tq0**
- [x] closes #12535
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by WillAyd** [comment]
Any interest in converting this to a fixture(s)?

**Comment by tq0** [comment]
@WillAyd yes, I might try to do that, but not right now, though.

**Comment by WillAyd** [comment]
OK thanks. This is in real need of it so any contribution there would be *greatly* appreciated.

I think this looks OK otherwise though @jreback

**Comment by jreback** [comment]
i’ll look soon

**Comment by jreback** [comment]
@tq0 can you use paramterize here instead; this is getting long and is non-idiomatic.

**Review by jreback — CHANGES_REQUESTED** [review]
comments

**Comment by TomAugspurger** [comment]
I'd prefer parametreziation be done separately. The diff here is relatively
easy to understand.

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @tq0 if you can follow up with a PR to parameterize would be great.

**Pull request merged**
