### PR TITLE
Finish moving period_helper to cython

### LINKED ISSUE #19465: period_helper should be in cython
Doing maintenance is nigh-impossible ATM.

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #19465

There is probably some cleanup that can be done now that period logic is self-contained.

No evident perf impact.
```
asv continuous -E virtualenv -f 1.1 master HEAD -b period
[...]
       before           after         ratio
     [776fed3a]       [7cc0d9e8]
+        1.14±0μs      1.28±0.01μs     1.13  period.PeriodProperties.time_property('M', 'qyear')
-        579±30ms          509±4ms     0.88  groupby.Datelike.time_sum('period_range')
```

(will post results from a couple more runs as they become available)
<b> update<b/> two more runs show zero change, not even noise.

<b>update</b> Oh, also did some unrelated modernizing of string formatting in timedeltas.

### CODE REVIEW

**Comment by gfyoung** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/412170226#L3465

Looks like you have some linting failures.

**Comment by gfyoung** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/412207881#L3475

Looks like you (still) have some linting failures. 🙁

**Comment by gfyoung** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/412219771#L3474

Getting there, but not quite.  Are you able to check locally via [cpplint](https://github.com/pandas-dev/pandas/blob/776fed3ab63d74ddef6e5af1a702b10c2a30bbb6/ci/lint.sh#L99)?

**Comment by jreback** [comment]
> asv continuous -E virtualenv -f 1.1 master HEAD -b period

can you create an issue to add more period benchmarks

**Comment by jbrockmendel** [comment]
> can you create an issue to add more period benchmarks

Done

**Comment by jreback** [comment]
thanks!

**Pull request merged**
