### PR TITLE
DOC/CI: fix class alias docstrings for sphinx 3.4 + unpin sphinx

### LINKED ISSUE #38600: DEPS: unpin sphinx from doc build
once warnings are fixed in updated sphinx can unpin #38598

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes #38600

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
(we can also wait a bit to see what they answer on the sphinx side)

**Comment by jreback** [comment]
looks fine. but agreed looks like sphinx broke this.

**Comment by jreback** [comment]
prob need to backport this

**Comment by jreback** [comment]
@meeseeksdev backport 1.2.x

**Pull request merged**
