### PR TITLE
Comma cleanup

### PR DESCRIPTION
**Pull request by JonathanShrek**
- [x] pandas/tests/indexes/datetimes/test_datetime.py
- [x] pandas/tests/indexes/datetimes/test_timezones.py
- [x] pandas/tests/indexes/multi/test_constructors.py
- [x] pandas/tests/indexes/multi/test_isin.py
- [x] pandas/tests/indexes/test_base.py
- [x] pandas/tests/indexes/timedeltas/test_scalar_compat.py
- [x] pandas/tests/indexes/timedeltas/test_searchsorted.py
- [x] pandas/tests/indexing/common.py
- [x] pandas/tests/indexing/test_callable.py
- [x] pandas/tests/indexing/test_check_indexer.py
- [x] pandas/tests/indexing/test_coercion.py
- [x] pandas/tests/indexing/test_floats.py

### CODE REVIEW

**Comment by JonathanShrek** [comment]
This latest commit passed the Azure checks, but for some reason now fails on the typing validation checks.

**Comment by simonjayhawkins** [comment]
> This latest commit passed the Azure checks, but for some reason now fails on the typing validation checks.

unrelated, xref #36085

**Comment by MarcoGorelli** [comment]
Thanks @JonathanShrek - can you fetch and merge upstream/master and push to get the CI checks green please?

**Comment by JonathanShrek** [comment]
Thanks @simonjayhawkins I’ll push another commit tonight.

**Comment by JonathanShrek** [comment]
@MarcoGorelli I’ll do that tonight. Thanks for the help!

**Review by MarcoGorelli — APPROVED** [review]
Wow, that's a lot of files - all looks good to me, thanks!

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
Actually, I see why it looks like there's so many files changed - you still have commits here from #36058 , likely because you've done this from the same branch.

Could you drop these commits? I'd expect either of the following to work:
```
git checkout commaCleanup
git fetch upstream master
git rebase -i upstream/master  # here you would drop the first three commits
git push origin commaCleanup -f
```
or
```
git fetch upstream master
git reset --mixed upstream/master
git add <here, only put the new files you changed>
git commit -m "<some message>"
git push origin commaCleanup -f
```

(note: I wouldn't normally advise rebasing and force-pushing, I now only do it when I have commits I want to drop).

Whenever I start work on some new development I usually do
```
git checkout -b <new branch>
git fetch upstream master
git reset --hard upstream/master
```
to make sure I'm starting from how the code is on `upstream/master`

**Comment by JonathanShrek** [comment]
Yeah I can do this. I actually noticed all of the other files that had already been merged in the diffs as well, but wasn’t sure how to fix it and nobody had said anything so I was just going with it. I’ll get this done this afternoon. Thanks for the detailed response!

**Comment by jreback** [comment]
thanks @JonathanShrek

**Pull request merged**
