### PR TITLE
CI/DOC: Enforce ES01 in CI

### PR DESCRIPTION
**Pull request by jordan-d-murphy**
Enforce ES01 in CI so that it can be fixed and enforced in chunks like other docstring errors.

The added functions come from the result of running `scripts/validate_docstrings.py --format=actions --errors=ES01`

Part of our ongoing work to continue enforcing numpydoc validations: https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks

- [x]  xref https://github.com/pandas-dev/pandas/pull/56971
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jordan-d-murphy** [comment]
pre-commit.ci autofix

**Review by mroeschke — APPROVED** [review]
Just of warning, more maintainers _may_ decide some of these numpydoc rules are not worth enforcing, but for now OK to include

**Comment by mroeschke** [comment]
Thanks @jordan-d-murphy

**Comment by jordan-d-murphy** [comment]
okay - thanks for the heads up. Always happy to adjust and redirect effort elsewhere as needed. I certainly appreciate the speedy reviews and helpful suggestions!

**Comment by mroeschke** [comment]
In the end it's open source and any contribution of yours is welcome :)

_Personally_ I find fixing the docs to enforce these rules is a bit more externally useful than enforcing some of the missing rules in the CI (since pandas doesn't not add new APIs with docs often anymore)

**Pull request merged**
