### PR TITLE
CLN: Replace '.format' with f-strings in some test files #29547

### PR DESCRIPTION
**Pull request by vandana-iyer**
Updates the below 2 test files to use f-strings (fast and preferred) instead of '.format' (old and slow)

1) pandas/tests/reshape/test_reshape.py
2) pandas/tests/scalar/period/test_period.py
 
For more details on the issue, refer: https://github.com/pandas-dev/pandas/issues/29547

- [x] tests passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jbrockmendel** [comment]
LGTM

**Comment by vandana-iyer** [comment]
It is my first contribution to the pandas library and I am all excited :)
Thanks for the review @jbrockmendel and thanks for adding the label @MomIsBestFriend. I will make note to add appropriate labels in my future pull requests.

**Comment by MomIsBestFriend** [comment]
@vandana-iyer Thank you for the PR :)

**Comment by jreback** [comment]
thanks @vandana-iyer

**Pull request merged**
