### PR TITLE
DOC: Enforce Numpy Docstring Validation for pandas.Series.max

### PR DESCRIPTION
**Pull request by tuhinsharma121**
- [ ] xref #58504 

fixes
```
-i "pandas.Series.max RT03" \

```

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @tuhinsharma121

**Comment by Aloqeely** [comment]
Sorry for the late review, but is there a reason why you are re-writing the docs from scratch instead of fixing it from the `make_doc` function? You fixed it for `Series.max` but `DataFrame.max` and some other reduction methods are still failing @mroeschke @tuhinsharma121

**Comment by mroeschke** [comment]
Another benefit of this change is avoiding the dynamic docstring so that docstring formating can happen via `ruff`

**Comment by tuhinsharma121** [comment]
yeah. And `See Also` section can have flexibility to differ slightly for Series and DataFrame methods this way.

**Pull request merged**
