### PR TITLE
REF: use inherit_names for TimedeltaIndex

### PR DESCRIPTION
**Pull request by jbrockmendel**
ATM we have two separate ways of doing inheritance/pass-through for our EA-backed Indexes.  This moves TDI over to all-inherit_names,  Will do the same for other EA-Indexes in their own PRs.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Can you explain a bit what's the difference between the two mechanisms? (the delegate_names vs inherit_names)

**Comment by jbrockmendel** [comment]
> Can you explain a bit what's the difference between the two mechanisms? (the delegate_names vs inherit_names)

1) inherit_names has a kwarg that allows us to inherit a property as a cache_readonly
2) inherit_names works for class attributes, i.e. not properties or methods
3) inherit_names lets us to avoid repeating boilerplate of PandasDelegate

**Comment by jreback** [comment]
thanks @jbrockmendel

**Comment by jorisvandenbossche** [comment]
> inherit_names works for class attributes, i.e. not properties or methods

What do you mean exactly? In this PR it's being used for methods? (eg sum, median, etc)

**Comment by jbrockmendel** [comment]
> What do you mean exactly? In this PR it's being used for methods? (eg sum, median, etc)

e.g. We use inherit names on DatetimeIndex to inherit _bool_ops, which is just a list

**Pull request merged**
