### PR TITLE
DOC: Imporve `json_normalize` record_prefix and mate_prefix

### LINKED ISSUE #54121: DOC: description of record_prefix param for json_normalize is wrong
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/dev/reference/api/pandas.json_normalize.html

https://github.com/pandas-dev/pandas/blob/3d7a44ab39b092feb30bbf79923e6d970a6f67fc/pandas/io/json/_normalize.py#L270-L272

### Documentation problem

The description implies `record_prefix` is taken as a boolean, but as said above, it's actually a string. There's an example below that shows how it actually behaves:

https://github.com/pandas-dev/pandas/blob/3d7a44ab39b092feb30bbf79923e6d970a6f67fc/pandas/io/json/_normalize.py#L377-L383

### Suggested fix for documentation

I might suggest:

> record_prefix : str, default None
> If provided, prefix records with this string, e.g. foo.bar.field if record_prefix is 'foo.bar.'.

---

BTW, I think `meta_prefix` also has the same problem, but I don't have an example to test it on.

### PR DESCRIPTION
**Pull request by luke396**
- [ ] closes #54121  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by wjandrea** [comment]
That's not how it works. For example:

```python
data = {"A": [1, 2]}
pd.json_normalize(data, "A", record_prefix=True)
```

```none
   True0
0      1
1      2
```

See also the example lower in the docs.

**Comment by luke396** [comment]
> That's not how it works. For example:
> 
> ```python
> data = {"A": [1, 2]}
> pd.json_normalize(data, "A", record_prefix=True)
> ```
> 
> ```
>    True0
> 0      1
> 1      2
> ```
> 
> See also the example lower in the docs.

You are right. I ignored this and just changed the type.

**Comment by mroeschke** [comment]
Thanks for the pull request, but it appears to have gone stale. If interested in continuing, please merge in the main branch, address any review comments and/or failing tests, and we can reopen.

**Comment by luke396** [comment]
@mroeschke Sorry for later reply.

I have merged the branch with main, should we reopen the pr, or I need to open a new one?

**Pull request closed without merging**
