### PR TITLE
Remove Deprecated Azure CI Step

### PR DESCRIPTION
**Pull request by WillAyd**
Found this while investigating #26345 may or may not be related but figured worth a separate PR in either case

### CODE REVIEW

**Comment by datapythonista** [comment]
@WillAyd looks like this step is required to install conda, right?

**Comment by WillAyd** [comment]
@datapythonista not entirely sure. The build logs show this task and deprecated and it appears to be documented as such on the Azure side:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/conda-environment?view=azure-devops#yaml-snippet

I think the preference is to use a task that just exposes conda via the system path:

https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=ubuntu-16-04#add-conda-to-your-system-path

**Comment by datapythonista** [comment]
That sounds good to me. I saw that the CI was failing because of deleting the step, but if we can just set an environment variable that sounds better.

**Comment by WillAyd** [comment]
FWIW here's the issue on the Azure side of things:

https://github.com/microsoft/azure-pipelines-tasks/pull/9573

**Review by datapythonista — APPROVED** [review]
lgtm, nice clean up

logs mention about updating conda (i.e. `conda update -n base -c defaults conda`), may be we could add that, but in any case, happy with the PR

**Comment by jreback** [comment]
thanks @WillAyd

**Pull request merged**
