### PR TITLE
fix negative n for str.replace with arrow string

### PR DESCRIPTION
**Pull request by rohanjain101**
- [ ] closes #56404 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by phofl — COMMENTED** [review]
Shouldn't we rather raise?

**Comment by rohanjain101** [comment]
You mean raise if n <= -2? (since n=-1 on the docs means unlimited), I can make that change, but I was trying to follow the behavior of pd.StringDtype(), which seems like it allows any negative value to be unlimited.

**Comment by phofl** [comment]
Ah that's fine then

**Review by phofl — APPROVED** [review]

**Comment by jbrockmendel** [comment]
This should probably be the same for ArrowStringArray._str_replace?

**Pull request merged**
