### PR TITLE
REF: make CustomMixin a cdef class

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase

**Comment by jreback** [comment]
one more time :->

**Comment by jbrockmendel** [comment]
```
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BDay.calendar.rst: WARNING: document isn't included in any toctree
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BDay.holidays.rst: WARNING: document isn't included in any toctree
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BDay.weekmask.rst: WARNING: document isn't included in any toctree
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BusinessDay.calendar.rst: WARNING: document isn't included in any toctree
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BusinessDay.holidays.rst: WARNING: document isn't included in any toctree
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BusinessDay.weekmask.rst: WARNING: document isn't included in any toctree
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BusinessHour.calendar.rst: WARNING: document isn't included in any toctree
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BusinessHour.holidays.rst: WARNING: document isn't included in any toctree
/home/runner/work/pandas/pandas/doc/source/reference/api/pandas.tseries.offsets.BusinessHour.weekmask.rst: WARNING: document isn't included in any toctree
```

cc @jorisvandenbossche suggestions for how to suppress these warnings?  The situation: in order to fix [cython MRO troubles] i had to add these attributes in the _declaration_ for these classes, but these classes never actually define/use these attributes, so they _shouldnt_ be in the docs.

**Comment by jreback** [comment]
I would remove from the docs for now? once the cython classes are unified maybe can get away with re-adding?

**Comment by jbrockmendel** [comment]
I would remove from the docs for now?

you mean remove the classes entirely?

**Comment by jorisvandenbossche** [comment]
@jbrockmendel you can add those classes in the docs in a comment, so they don't show up in the overview list, but are actually built (to shut up sphinx to warn about it) 
See eg at the bottom of `reference/index.rst` as example

**Comment by jorisvandenbossche** [comment]
But BDay indeed doesn't exist in `pd.tseries.frequencies`?

**Comment by jbrockmendel** [comment]
> But BDay indeed doesn't exist in pd.tseries.frequencies?

No, it is in tseries.offsets.  If I move the comment-text up to just before `.. _api.frequencies:` then the warning is 

```
WARNING: [autosummary] failed to import 'pandas.tseries.offsets.Methods': no module named pandas.tseries.offsets.Methods
WARNING: [autosummary] failed to import 'pandas.tseries.offsets.Properties': no module named pandas.tseries.offsets.Properties
```

**Comment by jorisvandenbossche** [comment]
You will need to show the change that gives this warning

**Comment by jbrockmendel** [comment]
> You will need to show the change that gives this warning

Locally, this file now ends with

```
    [...]
    CDay.rollback
    CDay.rollforward
    CDay.__call__

.. This is to prevent warnings in the doc build. We don't want to encourage
.. these methods.  See GH#34345

..
    BDay
    ----
    .. autosummary::
       :toctree: api/

        BDay

    Properties
    ~~~~~~~~~~
    .. autosummary::
       :toctree: api/

        BDay.base
        BDay.freqstr
        BDay.kwds
        BDay.name
        BDay.nanos
        BDay.normalize
        BDay.offset
        BDay.rule_code
        BDay.n

    Methods
    ~~~~~~~
    .. autosummary::
       :toctree: api/

        BDay.apply
        BDay.apply_index
        BDay.copy
        BDay.isAnchored
        BDay.onOffset
        BDay.is_anchored
        BDay.is_on_offset
        BDay.rollback
        BDay.rollforward
        BDay.__call__


.. _api.frequencies:

===========
Frequencies
===========
.. currentmodule:: pandas.tseries.frequencies

.. _api.offsets:

.. autosummary::
   :toctree: api/

   to_offset

```

**Comment by jbrockmendel** [comment]
@jorisvandenbossche i still need to rebase+test this, so not a huge hurry, but any thoughts on the doc issue?  we're at the tail end of this process

**Comment by jorisvandenbossche** [comment]
Not directly, sorry. But if you can push it here, might be easier to check with the full change

**Comment by jorisvandenbossche** [comment]
The docs are passing here?

**Comment by jbrockmendel** [comment]
> The docs are passing here?

Yes.  In the most recent commit i added the "dummy" attributes to the docs for the non-custom classes, so if accessed they will just be None.

**Comment by jbrockmendel** [comment]
green, booyah

**Comment by jorisvandenbossche** [comment]
>  In the most recent commit i added the "dummy" attributes to the docs for the non-custom classes, so if accessed they will just be None.

But why do `BDay` etc need to be in the docs at all?

**Comment by jbrockmendel** [comment]
No idea

**Comment by jorisvandenbossche** [comment]
It was not meant as a technical "why" question, but a documentation question, and you are the expert in offsets: is `BDay` a class is used by users? (or is only a base class they should never use, I don't know)

**Comment by jbrockmendel** [comment]
BDay is an alias for BusinessDay, which i think is fairly common.  It is used directly by users

**Comment by jorisvandenbossche** [comment]
OK, so it's good to have it in the docs then. But maybe we could only add the class docstring page itself, without adding all methods/properties? (we have machinery for that, will do a PR just for BDay)

**Pull request merged**
