### PR TITLE
CI: Fix import of coo_matrix after scipy dev upgrade

### PR DESCRIPTION
**Pull request by phofl**
New scipy_dev renamed ``coo`` to ``_coo`` to make it private

### CODE REVIEW

**Comment by phofl** [comment]
Fixes the scipy affected tests. The numpy affected tests are still failing

**Comment by jbrockmendel** [comment]
Best guess is this np.quantile PR https://github.com/numpy/numpy/pull/18203 is causing the current build failures.

**Comment by phofl** [comment]
I think it is https://github.com/numpy/numpy/commit/cd7a02a4db7e760b881f3feeb832ffd84fa8645a

**Comment by simonjayhawkins** [comment]
@phofl duplicate of #44362?

**Comment by phofl** [comment]
The scipy part yes

**Pull request closed without merging**
