### PR TITLE
DOC: Added a Multi Index example for the Series.sum method

### PR DESCRIPTION
**Pull request by vadakattu**
Added a simple example of using the sum method on a multi-indexed series.

- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by datapythonista — APPROVED** [review]
lgtm

I'm on my phone and can't check whether travis failure is caused by the changes, but happy to merge this on green

**Comment by vadakattu** [comment]
Travis failure seems to be a code coverage timeout while uploading the second report, `/tmp/cov-multiple.xml`. Should I submit an empty commit to rerun the test suite?
```Travis CI detected.
    project root: .
    Fixing merge commit SHA
    Yaml found at: codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Appending build variables
    + TRAVIS_OS_NAME
    + TRAVIS_PYTHON_VERSION
==> Reading reports
    + /tmp/cov-multiple.xml bytes=2000278
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=649fd4c37bee8af43ff6ae0eec78f1a524a49f7b&build=45600.4&build_url=&name=&tag=&slug=pandas-dev%2Fpandas&service=travis&flags=multiple&pr=23279&job=445227336
    -> Pinging Codecov
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by datapythonista** [comment]
you can merge master into your branch and push, that's what we usually do (equivalent to an empty commit)

**Comment by datapythonista** [comment]
I think it's worth using from_product in the example:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.MultiIndex.from_product.html

**Comment by vadakattu** [comment]
> I think it's worth using from_product in the example:
> https://pandas.pydata.org/pandas-docs/stable/generated/pandas.MultiIndex.from_product.html

Oh nice! Didn't know about that, will update.

**Review by datapythonista — COMMENTED** [review]
not sure if the indentation of the index is correct, if you can make sure that it follows pep8, this looks good to me

**Comment by vadakattu** [comment]
It seemed ok with `git diff upstream/master -u -- "*.py" | flake8 --diff` but I've reformatted nonetheless -- is this indentation better?

**Review by datapythonista — APPROVED** [review]
lgtm, thanks!

**Review by WillAyd — APPROVED** [review]

**Comment by WillAyd** [comment]
Thanks @vadakattu

**Pull request merged**
