### PR TITLE
Re-enable parallel builds in CI

### PR DESCRIPTION
**Pull request by WillAyd**

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
awesome!

**Comment by lithomas1** [comment]
thanks @WillAyd.

**Comment by lithomas1** [comment]
@meeseeksdev backport 2.0.x

**Comment by WillAyd** [comment]
Thanks for review. Don't think we can backport this without #51525 as well though

**Comment by lithomas1** [comment]
My bad, forgot about that one. I don't think we should backport that one, since it changes a lot of the C extensions making it pretty risky.

**Comment by WillAyd** [comment]
Yea I'm ok without it being backported. We've lived this long without it on 2.0

**Comment by WillAyd** [comment]
By the way I couldn't believe how easy this was to re-enable. Kudos @lithomas1 or whoever has been consolidating those CI jobs - super cool

**Pull request merged**
