### PR TITLE
BUG: Catch overflow in both directions for checked add

### PR DESCRIPTION
**Pull request by gfyoung**
Port of #14324 after project name change.

### CODE REVIEW

**Comment by gfyoung** [comment]
@jreback : Doesn't seem like Appveyor is picking up this PR

**Comment by jreback** [comment]
lgtm. can you add a whatsnew note. put in a new API Changes section in 0.19.1

**Comment by jorisvandenbossche** [comment]
Please no api change section for 0.19.1. We put it in the bug section for 0.19.0, so then can put it here there as well I think

**Comment by gfyoung** [comment]
@jreback : But this is an internal function?

@jorisvandenbossche : So just a line in the "bugs" section is fine?

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
bug fix section is fine

**Comment by jorisvandenbossche** [comment]
@gfyoung Thanks!

**Comment by gfyoung** [comment]
@jreback , @jorisvandenbossche : So while it's good that we're catching underflow, when I try to integrate this check with tdi + tdi OR tdi + td, we run into issues:
~~~python
>>> import pandas as pd
>>>
>>> tdi = pd.TimedeltaIndex([pd.NaT])
>>> td = pd.Timedelta('1 days')
>>>
>>> tdi - td   # Should return TimedeltaIndex([pd.NaT])
...
OverflowError: Overflow in int64 addition
~~~
This is because we are doing the checked add with the `asi8` values, meaning that `NaT` becomes `np.iinfo(np.int64).min`, so the subtraction underflows as expected but not as we want.  Not sure what the best way is to NOT do checked add for those elements whose value is `NaN`.

**Comment by gfyoung** [comment]
@jreback , @jorisvandenbossche : So while it's good that we're catching underflow, when I try to integrate this check with tdi + tdi OR tdi + td, we run into issues:
~~~python
>>> import pandas as pd
>>>
>>> tdi = pd.TimedeltaIndex([pd.NaT])
>>> td = pd.Timedelta('1 days')
>>>
>>> tdi - td   # Should return TimedeltaIndex([pd.NaT])
...
OverflowError: Overflow in int64 addition
~~~
This is because we are doing the checked add with the `asi8` values, meaning that `NaT` becomes `np.iinfo(np.int64).min`, so the subtraction underflows as expected but not as we want.  Not sure what the best way is to NOT do checked add for those elements whose value is `NaN`.  Thoughts?

**Comment by jorisvandenbossche** [comment]
Additionally mask for that in the checking code?

**Comment by gfyoung** [comment]
Hmmm...I suppose, though that will impact performance again :cry: .  I can give it a shot anyways and see what happens.

**Pull request merged**
