### PR TITLE
BUG: also use Float Nullable dtypes in read_parquet when use_nullable_dtypes=True

### LINKED ISSUE #45694: BUG: Float Nullable dtypes not being returned when `use_nullable_dtypes=True` in `pd.read_parquet`
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> df = pd.DataFrame({'a':[1, 2, 3], 'b':[1.0, 2.0, 3]})
>>> df['c'] = pd.Series([1, 2, 3], dtype='uint8')
>>> df.to_parquet('a')
>>> pd.read_parquet('a').dtypes
a      int64
b    float64
c      uint8
dtype: object
>>> pd.read_parquet('a', use_nullable_dtypes=True).dtypes
a      Int64
b    float64
c      UInt8
dtype: object
>>> pd.__version__
'1.4.0'
```

### Issue Description

When `use_nullable_dtypes=True` in parquet reader the floating column is being read as `float64` instead of `Float64`(A nullable dtype)

### Expected Behavior

>>> pd.read_parquet('a', use_nullable_dtypes=True).dtypes
a      Int64
b    Float64
c      UInt8
dtype: object

### Installed Versions

<details>

pd.show_versions()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/pandas/util/_print_versions.py", line 109, in show_versions
    deps = _get_dependency_info()
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/pandas/util/_print_versions.py", line 88, in _get_dependency_info
    mod = import_optional_dependency(modname, errors="ignore")
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/pandas/compat/_optional.py", line 126, in import_optional_dependency
    module = importlib.import_module(name)
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 71, in do_override
    ensure_local_distutils()
  File "/Users/pgali/opt/anaconda3/envs/del/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /Users/pgali/opt/anaconda3/envs/del/lib/python3.9/distutils/core.py

</details>

### PR DESCRIPTION
**Pull request by Jaafarben2**
fixes #45694 
Add float types in the mapping dictionary

### CODE REVIEW

**Comment by rhshadrach** [comment]
Please add tests, whatsnew line, and link this PR to the original issue.

**Comment by Jaafarben2** [comment]
**Before Fix** :  float64 is returned instead of Float64 #45700 
```
>>> import pandas as pd
>>> df = pd.DataFrame({'a':[1, 2, 3], 'b':[1.0, 2.0, 3]})
>>> df['c'] = pd.Series([1, 2, 3], dtype='uint8')
>>> df.to_parquet('a')
>>> pd.read_parquet('a').dtypes
a      int64
b    float64
c      uint8
dtype: object
>>> pd.read_parquet('a', use_nullable_dtypes=True).dtypes
a      Int64
b    float64
c      UInt8
dtype: object
```


**After Fix :**  Float64 is returned instead of float64 and bug is fixed
```
>>> import pandas as pd 

>>> df = pd.DataFrame({'a':[1, 2, 3], 'b':[1.0, 2.0, 3]})

>>> df['c'] = pd.Series([1, 2, 3], dtype='uint8')

>>> pd.read_parquet('a').dtypes
a      int64
b    float64
c      uint8
dtype: object

>>> df.to_parquet('a')

>>> pd.read_parquet('a', use_nullable_dtypes=True).dtypes
a      Int64
b    Float64
c      UInt8
dtype: object
```

**Comment by rhshadrach** [comment]
@Jaafarben2 - the tests need to be added to `pandas.tests`, see [the dev docs](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#test-driven-development-code-writing) for more details.

**Review by jreback — CHANGES_REQUESTED** [review]
yup, w/o tests we can't even tell if this works

**Comment by jorisvandenbossche** [comment]
Thanks for the PR!

To be explicit for the required test, there is an existing test for this functionality at

https://github.com/pandas-dev/pandas/blob/5c757e9c4cf6a74fabfa1983dcd72b4759a88e5f/pandas/tests/io/test_parquet.py#L603-L645

This tests the roundtrip of a dataframe with some columns that have a nullable dtype variant in pandas. I think it should be sufficient to add two extra columns to the test dataframe (float32 and float64) in that existing test.

**Pull request closed without merging**
