### PR TITLE
feature wanted: pd.DataFrame.info() should show line numbers #17304

### PR DESCRIPTION
**Pull request by Alexandreae**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
Thanks for the PR. This is a continuation of #17332 right?

**Comment by Alexandreae** [comment]
Yes. The function is working but for some reason only a single test passed, can you give me some advice on that?

**Comment by WillAyd** [comment]
At least one of the repr tests is failing. You can see that in CI but here's a link to it as well:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=18136&view=logs&jobId=3a03f79d-0b41-5610-1aa4-b4a014d0bc70&taskId=264dbb61-dd41-5ada-cfaa-25751f4c2dca&lineStart=61&lineEnd=62&colStart=1&colEnd=1

**Comment by WillAyd** [comment]
Superseded by #28876

**Pull request closed without merging**
