### PR TITLE
REF: implement Index._should_partial_index

### PR DESCRIPTION
**Pull request by jbrockmendel**
Formalize the IntervalIndex special case, in principle let subclasses override.

### CODE REVIEW

**Comment by jreback** [comment]
can you rebase

**Comment by jbrockmendel** [comment]
Rebased + green

**Comment by S-T-A-R-L-O-R-D** [comment]
Is this issue still open?

**Comment by jbrockmendel** [comment]
> Is this issue still open?

No, this PR has been merged.

**Pull request merged**
