### PR TITLE
BUG: Removed bug from groupby/min on categoricals 

### LINKED ISSUE #52151: BUG: Inconsistent behavior with `groupby/min` and `observed=False` on categoricals between 1.5.3 and 2.1
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "cat_1": pd.Categorical(list("AB"), categories=list("ABCDE"), ordered=True),
    "cat_2": pd.Categorical([1, 2], categories=[1, 2, 3], ordered=True),
    "value_1": np.random.uniform(size=2),
})

chunk1 = df[df.cat_1 == "A"]
chunk2 = df[df.cat_1 == "B"]

df1 = chunk1.groupby("cat_1", observed=False).min()
df2 = chunk2.groupby("cat_1", observed=False).min()
df3 = pd.concat([df1, df2], ignore_index=False)

res3 = df3.groupby(level=0, observed=False).min()
print(f"\n{res3}")
```

### Issue Description

When performing a `groupby/min` with a categorical dtype and `observed=False`, the results differ between 1.5.3 and 2.1.

Output with 1.5.3:

```python
      cat_2   value_1
cat_1
A         1  0.384993
B         2  0.955231
C       NaN       NaN
D       NaN       NaN
E       NaN       NaN
```

Output with the latest `main`:

```python
      cat_2   value_1
cat_1
A         1  0.297557
B         1  0.081856
C         1       NaN
D         1       NaN
E         1       NaN
```

The change can be traced to this PR:

* https://github.com/pandas-dev/pandas/pull/52120

### Expected Behavior

I'm not sure if the changed behavior is intended. Please advise.

### Installed Versions

<details>

commit           : d22d1f2db0bc7846f679b2b0a572216f23fa83cc
python           : 3.8.16.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.3.0
Version          : Darwin Kernel Version 22.3.0: Thu Jan  5 20:50:36 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6020
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.1.0.dev0+293.gd22d1f2db0
numpy            : 1.23.5
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.4.0
pip              : 23.0.1
Cython           : 0.29.33
pytest           : 7.2.1
hypothesis       : 6.68.2
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.8
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.11.0
pandas_datareader: None
bs4              : 4.11.2
bottleneck       : 1.3.6
brotli           :
fastparquet      : 2023.2.0
fsspec           : 2023.1.0
gcsfs            : 2023.1.0
matplotlib       : 3.6.3
numba            : 0.56.4
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.1.0
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : 1.2.1
pyxlsb           : 1.0.10
s3fs             : 2023.1.0
scipy            : 1.10.1
snappy           :
sqlalchemy       : 2.0.4
tables           : 3.7.0
tabulate         : 0.9.0
xarray           : 2023.1.0
xlrd             : 2.0.1
zstandard        : 0.19.0
tzdata           : None
qtpy             : None
pyqt5            : None

</details>

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [ x] closes #52151 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Can you add a test for the fixed bug

**Comment by DeaMariaLeon** [comment]
Yes but where?
tests.groupby.test_min_max.py 
or
tests.groupby.text_categorical.py  ... maybe ?

**Comment by jbrockmendel** [comment]
either of those would be fine, i guess the min_max one would be my preference.

**Comment by DeaMariaLeon** [comment]
@jbrockmendel I added the test. I think that the failings are not related with what I did, but I'm not sure.

**Comment by mroeschke** [comment]
Could you merge the main branch once more?

**Comment by DeaMariaLeon** [comment]
Done.

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @DeaMariaLeon

**Pull request merged**
