### PR TITLE
REF: simplify extension reduction tests

### LINKED ISSUE #44742: API: extension tests BaseNoReduceTests/BaseBooleanReduceTests is confusing
Could maybe have one class for this and a class attribute `implements = ["any", "all", ...]`?

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #44742 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Will clean up the pyarrow tests usage in a follow-up.

Didn't remove the no-longer-used test classes since downstream projects might be using them.  Are we OK just ripping those out or does that require a deprecation cycle?

### CODE REVIEW

**Comment by mroeschke** [comment]
> Are we OK just ripping those out or does that require a deprecation cycle?

Probably should deprecate them since we advertise users to test with them, but since it's not extremely public maybe we can do a 3.0 change?

**Comment by jbrockmendel** [comment]
> Probably should deprecate them since we advertise users to test with them, but since it's not extremely public maybe we can do a 3.0 change?

Works for me

**Comment by jbrockmendel** [comment]
> Probably should deprecate them since we advertise users to test with them, but since it's not extremely public maybe we can do a 3.0 change?

Just checking: you mean OK to move forward with this PR as is then remove the old classes in 3.0?

**Comment by mroeschke** [comment]
> you mean OK to move forward with this PR as is then remove the old classes in 3.0?

Yeah I think deprecating tests is sticky business and probably just worth noting in 3.0 to use a different test class

**Comment by mroeschke** [comment]
Thanks @jbrockmendel

**Pull request merged**
