### PR TITLE
STYLE pylint: 48855-duplicate-value

### PR DESCRIPTION
**Pull request by natmokval**
Issue #48855. This PR enables pylint type "W" warning: `duplicate-value`
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

### CODE REVIEW

**Review by MarcoGorelli — APPROVED** [review]
looks good to me pending green, thanks @natmokval !

**Comment by MarcoGorelli** [comment]
apologies, this was an accident, I swapped back to the wrong tab, I meant to merge https://github.com/pandas-dev/pandas/pull/49527, looks like this one's failing one check
```
pylint..................................................................................................Failed
- hook id: pylint
- exit code: 8

************* Module pandas.core.dtypes.concat
pandas/core/dtypes/concat.py:284:8: R1720: Unnecessary "elif" after "raise", remove the leading "el" from "elif" (no-else-raise)

------------------------------------
Your code has been rated at 10.00/10
```

**Comment by natmokval** [comment]
Hi @MarcoGorelli , my local pylint passes. I don’t know if this error is related to my changes. Could you please show me how the fixup for R1720 https://github.com/pandas-dev/pandas/pull/49537/commits/9739c1da8f4794f76f6f9280927962a31e583169 relates to this PR?

**Comment by MarcoGorelli** [comment]
Hey @natmokval - here's the CI run from your PR https://github.com/pandas-dev/pandas/actions/runs/3396656270/jobs/5647961896 , which shows

```
pylint..................................................................................................Failed
- hook id: pylint
- exit code: 8

************* Module pandas.core.dtypes.concat
pandas/core/dtypes/concat.py:284:8: R1720: Unnecessary "elif" after "raise", remove the leading "el" from "elif" (no-else-raise)

------------------------------------
Your code has been rated at 10.00/10
```

What probably happened is that a PR was merged after you'd opened yours, which modified `concat.py` - so the check passed for you locally, but did pass in CI. If you'd updated your branch again,
```
git fetch upstream
git merge upstream/main
```
then you should have seen the error locally as well (well, not now, because https://github.com/pandas-dev/pandas/pull/49520#issuecomment-1304369602 has been merged 😄 )

There's a lot of activity in this repo, and lot's of PRs getting merged, so sometimes these kinds of things slip through

Thanks for all your help fixing linting issues!

**Comment by MarcoGorelli** [comment]
Hey @natmokval - you're right, it didn't come from your PR, it came from https://github.com/pandas-dev/pandas/pull/49520

**Comment by natmokval** [comment]
Thank you @MarcoGorelli for the explanation. It helps me to understand how changes are getting in.

**Pull request merged**
