### PR TITLE
WEB: Adding new pandas logo

### LINKED ISSUE #21376: DOC: Pandas Logo
Several people have expressed interest.  Just collecting usernames here:

@joelostblom https://github.com/pandas-dev/pandas/issues/3825#issuecomment-392896641
@nunojesus https://github.com/pandas-dev/pandas/issues/21371
@tswast https://github.com/pandas-dev/pandas/issues/21376#issuecomment-475911516

To anyone else who encounters this and wants to express interest, just add a comment, and we'll add your name to this list!

### PR DESCRIPTION
**Pull request by datapythonista**
- [X] closes #21376, xref #28521
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

logo_screenshot

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
nice!

**Review by TomAugspurger — APPROVED** [review]

**Review by jreback — APPROVED** [review]
lgtm

**Comment by jorisvandenbossche** [comment]
Do we also have the font of the logo?

**Comment by datapythonista** [comment]
It's from Adobe, can be downloaded from their web. I'm in my phone now, but can send the link later.

**Comment by datapythonista** [comment]
The font is the bold version of this one: https://fonts.adobe.com/fonts/mr-eaves-xl

**Comment by jorisvandenbossche** [comment]
I don't much about fonts and licensing etc, but something I am wondering: should we rather use an open source font? (try to find something that resembles this font)

The logo with the Adobe font is free to use (even for commercial logo's), but to create the logo you still need a license, as far as I understand (https://helpx.adobe.com/fonts/using/font-licensing.html#act-own):

> ... if your client needs to have the font installed to edit your design, they will need their own license

**Comment by datapythonista** [comment]
I assume the designer has a license for the font (I guess it comes with whatever software she uses). And the logo file is not using the font, the letters has been converted to paths.

I don't see any problem, but I'm happy to get you in touch with the designer, you can discuss any concern with her, and if you prefer a new logo with another font, happy to hand over this to you.

**Review by WillAyd — APPROVED** [review]
lgtm

**Pull request merged**
