### PR TITLE
REF: Implement RelativeDeltaOffset

### PR DESCRIPTION
**Pull request by jbrockmendel**
RelativeDeltaOffset (basically the same as the existing DateOffset class) is a bit of an odd duck _attributes-wise, this is just a move without yet cdef-ing it.

### CODE REVIEW

**Comment by jreback** [comment]
hmm can you rebase after all of the merges. maybe ABCTimestamp -> _Timestamp as needed.

**Comment by jbrockmendel** [comment]
Rebased+green

**Comment by jbrockmendel** [comment]
true-green

**Comment by jreback** [comment]
once more rebase i think these were back of queue

**Comment by jbrockmendel** [comment]
rebased+green

**Pull request merged**
