### PR TITLE
0.20.2 backports 1

### PR DESCRIPTION
**Pull request by TomAugspurger**
First round of backports. Covers everything up to and including https://github.com/pandas-dev/pandas/pull/16526

@jorisvandenbossche I can't remember, did you make PRs for batches of backports or commit directly to the maintenance branch? I think I prefer PRs, if only for another historical record.

And I think we want to rebase and merge onto 0.20.x, not squash.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. this covers to current master?

**Comment by jreback** [comment]
maybe create a new label for backporting?

**Comment by TomAugspurger** [comment]
Yes, it's through current master.

I've made a new label, "Needs Backport". Let's try labeling new PRs for 0.20.x with that, then I'll remove it when I've backported (cc. @jorisvandenbossche)

**Comment by jorisvandenbossche** [comment]
> @jorisvandenbossche I can't remember, did you make PRs for batches of backports or commit directly to the maintenance branch? I think I prefer PRs, if only for another historical record.

I cherry picked directly to the 0.19.x branch, but making a PR like this seems also a nice way to keep track of things. So seems good!

> And I think we want to rebase and merge onto 0.20.x, not squash.

Yeah, certainly, like you did in the meantime

**Pull request merged**
