### PR TITLE
CLN: have Timestamp return NotImplemented

### PR DESCRIPTION
**Pull request by jbrockmendel**
broken off from a branch fixing #28080.

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
lgtm

**Comment by WillAyd** [comment]
What is your plan for a whatsnew here? I think should mention but AFAICT you have a few more follow ups to make this complete?

**Comment by jbrockmendel** [comment]
Shouldn’t be any user facing change here

**Comment by jreback** [comment]
thanks @jbrockmendel

**Pull request merged**
