### PR TITLE
 [DOC] Fix typo in Cheat sheet with regex

### LINKED ISSUE #25156: An extra single quotation marks (') in cheat sheet/ Subset Variables (Columns)/regex (Regular Expressions) Examples
#### Problem description
https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf

In Pandas_Cheat_Sheet/ Subset Variables (Columns)/ regex (Regular Expressions) Examples
#### ''^(?!Species$).*' Matches strings except the string 'Species'
The second ' in regex is unnecessary.
#### Expected Output
execute sucessfully

#### Actual result:  
```python
# features = data_df.filter(regex=''^(?!SalePrice$).*')
```
  File "<ipython-input-168-4e3c4f16b4c5>", line 5
    features = data_df.filter(regex=''^(?!SalePrice$).*')
                                        ^
SyntaxError: invalid syntax

#### should be:
```python
# features = data_df.filter(regex='^(?!SalePrice$).*')
```

### PR DESCRIPTION
**Pull request by Dr-Irv**
- [x ] closes #25156
- [x ] tests added / passed
   tests not needed - just a doc change
- [x ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
  not needed - just a doc change
- [x ] whatsnew entry
   Not needed - just a doc change

Small typo fixed in Powerpoint and PDF versions of cheat sheet.

Ideally, when merged, new PDF versions should push to current pandas release.

### CODE REVIEW

**Comment by jreback** [comment]
it shows you are deleting a file, is that intentional? maybe need to update the .gitignore.

**Comment by Dr-Irv** [comment]
@jreback I think this is some odd bug in github reporting.  It shows on the files changed:
```
BIN -4 Bytes (100%) doc/cheatsheet/Pandas_Cheat_Sheet.pptx
```
But if you click on that file, it shows it is 103KB big, which is correct.  So I don't see the deletion that you refer to.

Looking at the file that is in master and the file in my pull request, the new file is 4 bytes smaller (makes sense - I only deleted a single quote), comparing to master.  The "-100%" is wrong.

**Comment by WillAyd** [comment]
Hmm that's weird. I suppose its the same issue we are seeing in #25032 then

**Review by WillAyd — APPROVED** [review]
Notwithstanding potential GH bug changes lgtm. @jreback - not sure if there's risk to merging this?

**Comment by Dr-Irv** [comment]
@WillAyd Possibly so, but if there are two pending pull requests on the cheat sheet, they will not merge correctly. because the files are binary

**Comment by WillAyd** [comment]
For sure; whichever gets merged first will have to be accounted for in second PR

**Comment by jreback** [comment]
@Dr-Irv can you rebase here (sorry the other PR was first) :>

**Comment by Dr-Irv** [comment]
@jreback I've done that.  Note that I think these fixes should get published as soon as possible to the pandas doc web site rather than wait for a new release, since the changes here and in #25032 are just fixing typos.

**Comment by TomAugspurger** [comment]
I can upload these manually I think. Just ping me again once this is merged.

**Comment by TomAugspurger** [comment]
Hmm it looks like our current one is pretty out of data.

Does this get included anywhere in the rst documentation? Or is it just the
link from getting_started/tutorials.rst ->
pandas.pydata.org/Pandas_Cheat_Sheet.pdf?

**Comment by Dr-Irv** [comment]
@TomAugspurger I believe we just have the link as you wrote it, but there was supposed to be some process for copying over the PDF files to the location `pandas.pydata.org/Pandas_Cheat_Sheet.pdf` .

**Comment by TomAugspurger** [comment]
Yep. https://github.com/pandas-dev/pandas-release/issues/6

**Comment by jreback** [comment]
thanks @Dr-Irv

**Comment by TomAugspurger** [comment]
I updated the cheatsheets on pandas.pydata.org with the latest version.

**Comment by Dr-Irv** [comment]
@TomAugspurger can you check that?  If I go to http://pandas.pydata.org/Pandas_Cheat_Sheet.pdf, I'm seeing the old version.  You can tell by looking in two places:

1. On the left side, right above "Create DataFrame with a MultiIndex", there should be two right parens.
2. The last regex on the right side should have one single quote, not two.

**Comment by TomAugspurger** [comment]
It seems like these are getting cached pretty aggressively. I removed the
files completely, but we were still serving them.

When I scp the files from the server locally, I have the corrected version.

Let's check again tomorrow.

**Comment by Dr-Irv** [comment]
@TomAugspurger Looks good this morning.  Thanks

**Pull request merged**
