### PR TITLE
TST/CLN: remove frame replace class

### PR DESCRIPTION
**Pull request by mzeitlin11**
Class doesn't seem to have any purpose here

### CODE REVIEW

**Comment by jbrockmendel** [comment]
is there any meaningful organization of the tests within the class?

**Comment by mzeitlin11** [comment]
> is there any meaningful organization of the tests within the class?

Not currently. There are a bunch of tests for regex-related functionality, so that at least could be split out into its own file if you think that makes sense.

**Comment by jbrockmendel** [comment]
> Not currently. There are a bunch of tests for regex-related functionality, so that at least could be split out into its own file if you think that makes sense.

We put the file-per-method structure in place last year.  Unless there's a compelling reason, id prefer not to break that pattern, but instead use classes to organize tests within those files if necessary.

**Comment by mzeitlin11** [comment]
That makes sense, will close this then and put up something later to try to split this up

**Comment by jbrockmendel** [comment]
BTW that test organization process is ongoing.  if this is something you're interested in im happy to point you at parts of the tests that havent gotten much attention

**Comment by mzeitlin11** [comment]
Yeah always happy to know where time/attention is most valuable

**Comment by jbrockmendel** [comment]
> where time/attention is most valuable

FWIW i think of test organization less about being high priority than as being something useful i can do when burned out on more difficult tasks.

A few areas of test organization that i either didnt get to or stalled out on
- tests/arithmetic/ there are many comments to the effect of "TODO: parametrize or de-duplicate".  There's tons of these and a lot of duplication.
- groupby/, apply/, resample/, reshape/ i haven't looked at the test organization at all, no idea if these have a a reasonable layout (roughly defined as "if i want to know if we have tests for X, is it obvious where to look?")
- many tests in frame/methods/test_foo and series/methods/test_foo can likely be shared

**Comment by mzeitlin11** [comment]
Thanks that's good to know will keep in mind!

**Pull request closed without merging**
