### PR TITLE
REF/TST: method-specific files for Series timeseries methods

### PR DESCRIPTION
**Pull request by jbrockmendel**
cc @WillAyd @simonjayhawkins got the [go ahead](https://github.com/pandas-dev/pandas/pull/32110#issuecomment-589974610) the other day to take these off Jeff's plate

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@jbrockmendel running `pytest pandas/tests/series/`

this PR
=========== 2620 passed, 23 skipped, 7 xfailed, 1 warning in 19.32s ===========
master 
=========== 2617 passed, 23 skipped, 7 xfailed, 1 warning in 22.35s ===========

**Comment by jbrockmendel** [comment]
test_localized_at_time_between_time gets split into test_localized_at_time and test_localize_between_time.  Since that is parametrized over two values, that accounts for 2 extra tests.  not clear where the third is coming from.  ill see if i can narrow it down

**Comment by jbrockmendel** [comment]
The third extra test was a test_between in test_period.py that was left behind, just updated.

**Review by simonjayhawkins — APPROVED** [review]
@jbrockmendel lgtm pending green.

**Comment by simonjayhawkins** [comment]
Thanks @jbrockmendel

**Pull request merged**
