### PR TITLE
DOC: Removing repeated NA

### LINKED ISSUE #53404: DOC: pandas.NA repeated on website
The link to pandas.NA can be found 3 times on the [web's](https://pandas.pydata.org/docs/reference/api/pandas.NA.html#pandas.NA) leftsidebar - 
Please see pic.

It seems related to PR #48455 @mroeschke 

pandas NA

@MarcoGorelli  FYI

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
- [x] closes #53404 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by DeaMariaLeon** [comment]
@MarcoGorelli 
I'm trying to do what you suggested about this issue but I'm missing something. Would you mind taking a look please? thanks

**Comment by MarcoGorelli** [comment]
thanks - looks like there's a CI failure, but I'm hoping it's unrelated - have tried merging upstream/main, let's see

**Comment by MarcoGorelli** [comment]
I downloaded the docs build, and it looks fine - what were you referring to when you wrote "but I'm missing something"?

Only comment I have is that `NaT` is also repeated, and that if we're going to have a missing values section, then I think that should also be moved there together with NA?

**Comment by DeaMariaLeon** [comment]
I wrote "but I'm missing something" because the preview didn't work. I thought that there was an error on what I did. I'll add the `NaT` to the section then. Thanks

**Comment by DeaMariaLeon** [comment]
> I downloaded the docs build

Hey @MarcoGorelli, how did you do that? (I tried and couldn't find it).

**Comment by MarcoGorelli** [comment]
hey - if you click on https://github.com/pandas-dev/pandas/actions/runs/6341541518/job/17225406933?pr=54821 and then "summary", at the bottom of the page it says "artifacts"

you can download then, extract it, and then from `python3 -m http.server` from inside (I think from the docs folder), and then open `localhost:8000` in your browser

**Comment by DeaMariaLeon** [comment]
Thanks @MarcoGorelli. 
Now, is this OK? : 

Screenshot 2023-09-29 at 12 50 39

**Review by MarcoGorelli — APPROVED** [review]
nice one, thanks for doing this!

**Pull request merged**
