### PR TITLE
CoW: Copy less in replace implementation with listlikes

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

This is the best version I could come up with

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
> This is the best version I could come up with

General concern: do we think this is worth the added complexity? (and the replace code is already _really_ complex ..)

The case it is trying to solve is that if you do an inplace replace with a list like, this could be done actually inplace (if there are no other refs to start with), while now it always makes a copy?

**Comment by phofl** [comment]
This is generally for listlike replace ops, not only inplace. The current implementation copies for every pass, which is too slow imo

**Comment by jorisvandenbossche** [comment]
> The current implementation copies for every pass, which is too slow imo

And does that only happen under CoW, or also in the default?

**Comment by phofl** [comment]
Both as far as I know, but we should fix this anyway

**Comment by phofl** [comment]
Also agreed to merge

**Pull request merged**
