### PR TITLE
Auto backport of pr 25701 on 0.24.x

### PR DESCRIPTION
**Pull request by WillAyd**
@TomAugspurger @jorisvandenbossche @jreback want to double check I did this right. I didn't use the -m flag during the cherry-pick process as that was causing failures

0.24.3 at this point?

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@WillAyd what was wrong is that the PR was not targetting the 0.24.x branch but master (I changed it now, but before it was showing a huge number of commits). 
So when you crate a PR, you can choose which branch you want to merge it in. Or after creating, if you do the "Edit" button next to the title, you can still change it.

But so now with targetting 0.24.x branch, this looks fine.

I typically use `git cherry-pick -x <sha>`

**Comment by WillAyd** [comment]
@jorisvandenbossche thanks yea that did look off so thanks for fixing and clarifying.

**Comment by jreback** [comment]
@WillAyd this should be merged or closed?

**Comment by WillAyd** [comment]
@jreback I think OK to merge

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
