### PR TITLE
CI: Force newer S3FS

### LINKED ISSUE #48271: CI: newer version of s3fs is pulled causing builds to fail
Looks like we are pulling 0.6.0 (which is way smaller than our minimum version btw) instead of 0.4.2. The 0.6.0 requires aiobotocore, but is not compatible with the new version.

Working build:
https://github.com/pandas-dev/pandas/runs/8026125010?check_suite_focus=true

Failed build:
https://github.com/pandas-dev/pandas/runs/8035127801?check_suite_focus=true

Lets try to force at least the minimum s3fs version.

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #48271  (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by phofl — CHANGES_REQUESTED** [review]
Please remove aiobotocore if not pinned, it's not a dependency of us

**Comment by mroeschke** [comment]
Could we enforce `botocore>=1.23.0` instead? Looks like the six changes occured there: https://github.com/boto/botocore/commit/5d4eccaa700556ed279bd243b9b7688748e2aad8

Not totally ideal IMO that this s3fs pinning in these files is higher than our minimum version.

**Comment by lithomas1** [comment]
Is there a reason to pin down s3fs? 

mamba is pulling really old versions of s3fs by chance(I think it's happening because old s3fs are not pinning down aiobotocore, allowing for mamba to pull down the newest aiobotocore versions which are not actually compatible with s3fs). Really old s3fs working with the newest aiobotocore is more luck than anything else.

This PR is just forcing mamba not to do this by setting a lower bound to a s3fs that pins down aiobotocore to a version it can support. The minimum version is still getting tested in the min version build so I don't think we're losing coverage.

> Could we enforce botocore>=1.23.0 instead? Looks like the six changes occured there: https://github.com/boto/botocore/commit/5d4eccaa700556ed279bd243b9b7688748e2aad8

I haven't tested this, but I'm pretty sure aiobotocore pins/controls the botocore version(IIUC it messes around with botocore internals so they have to pin down to a specific botocore version), so doing that would probably just result in an unsolvable environment. 

(As for why we care about aiobotocore, its a dependency of s3fs)

I agree with you on the point of bumping s3fs though(I think we should probably do it ASAP for 2.0).

**Comment by phofl** [comment]
Yeah the actual issue is that our minimum version of s3fs is not pinning aiobotocore, causing failures, hence we have to pin aiobotocore too causing the python 3.10 issues…

**Comment by phofl** [comment]
Yeah the actual issue is that our minimum version of s3fs is not pinning aiobotocore, causing failures, hence we have to pin aiobotocore too causing the python 3.10 issues…

**Comment by mroeschke** [comment]
I'll check the environment solving by lower pinning `botocore` quickly in https://github.com/pandas-dev/pandas/pull/48297

> Is there a reason to pin down s3fs?

Not really. I think it was May when I updated the min version of several packages using a 1-year-release-prior rule of thumb. IMO I think it would be okay to bump s3fs for 1.5 to `2021.08.0` since we advertise our min versions of optional dependencies as the ones we test with, and lower versions may very well still work.

**Comment by phofl** [comment]
Yeah then let’s bump this for the rc, if the solve fails

**Comment by phofl** [comment]
#48299, if this works out then we can close here

**Pull request closed without merging**
