### PR TITLE
CI: Try numpydev skip test

### PR DESCRIPTION
**Pull request by phofl**
- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by mroeschke** [comment]
Here's what I got from debugging on my repo https://github.com/mroeschke/pandas/pull/16

```
2023-02-23T18:26:51.3325944Z [gw0] node down: Not properly terminated
2023-02-23T18:26:51.3816201Z [gw0] FAILED pandas/tests/test_sorting.py::TestSorting::test_nargsort[False-last-exp6-<lambda>] 
2023-02-23T18:26:51.3816794Z 
2023-02-23T18:26:51.3817054Z replacing crashed worker gw0
```

```
2023-02-23T18:33:56.3583342Z [gw2] node down: Not properly terminated
2023-02-23T18:33:56.4068472Z [gw2] FAILED pandas/tests/extension/test_interval.py::TestMethods::test_sort_values[<lambda>-False] 
2023-02-23T18:33:56.4068954Z 
2023-02-23T18:33:56.4069119Z replacing crashed worker gw2
```

**Comment by phofl** [comment]
There are different tests failing, all sorting related as it seems

**Comment by jbrockmendel** [comment]
could be related to the avx512 sorting thing numpy implemented last week?

**Comment by lithomas1** [comment]
Yeah, this is not going to be easy to debug. I think pytest exists when all workers crash, so you'd only be able to flush out segfaulting tests 2 at a time.

I will try to get a backtrace with catchsegv, but in the meantime it's probably better to pin numpy to a specific nightly version.

**Pull request closed without merging**
