### PR TITLE
DOC: Expanded Using a Docker Container section

### LINKED ISSUE #35345: DOC: expand "using a Docker container" section
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#using-a-docker-container
#### Documentation problem

Someone unfamiliar with Docker would be confused reading this.

#### Suggested fix for documentation

The expansion needed is quite small, just:

1. link to the Docker installation instructions
2. link to how to develop in a container using PyCharm (current docs only link to vs code instructions)
3. mention that you might still need to rebuild the C extensions if/when you merge with upstream/master with
   ```
   python setup.py build_ext --inplace -j 4
   ```

### PR DESCRIPTION
**Pull request by alexhlim**
- [x] closes #35345
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Added Docker installation link, Docker commands, and PyCharm sections.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @alexhlim for the PR. test failure in Windows py37_np18 is unrelated.

```
INTERNALERROR> assert not 'pandas/tests/base/test_unique.py::test_unique_bad_unicode[idx_or_series_w_bad_unicode0]'
```

**Comment by alexhlim** [comment]
Thanks for the reply, @simonjayhawkins! Let me know if there are any revisions I need to do on my end to get these checks passing.

**Comment by simonjayhawkins** [comment]
restarted failed job

**Review by MarcoGorelli — APPROVED** [review]
Thanks @alexhlim ! I think this makes it more accessible

**Comment by alexhlim** [comment]
No problem, @MarcoGorelli. Glad I could help!

**Comment by simonjayhawkins** [comment]
Thanks @alexhlim

**Pull request merged**
