### PR TITLE
CI/DOC: replace master -> main branch

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Follow-up on https://github.com/pandas-dev/pandas/issues/39577

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
This has failed a few times it appears. Not sure why this PR would influence this failure:

https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=72190&view=logs&j=c4a134e2-1a49-5486-5bb3-f47b2d22370f&t=a5a6d308-4ac5-5e83-907a-cda493e43b7d&l=49

**Comment by jreback** [comment]
do we need to backport this? (yes?)

**Comment by mroeschke** [comment]
> do we need to backport this? (yes?)

I would think so.

**Comment by jreback** [comment]
thanks @jorisvandenbossche

**Comment by jreback** [comment]
@meeseeksdev backport 1.4.x

**Comment by jorisvandenbossche** [comment]
The backport is actually already done at https://github.com/pandas-dev/pandas/pull/45338 by meeseeksdev (not fully sure why he mentioned here that "something went wrong")

**Comment by jreback** [comment]
yeah i always trigger (though i realiE i don't really need to)

**Comment by simonjayhawkins** [comment]
> yeah i always trigger (though i realiE i don't really need to)

yeah probably safer to make sure nothing gets missed. If the PR has a release note then I check release notes are in sync so these won't get missed. If if fixes ci then again won't get missed as the ci would be failing on the backport branch. If it's a doc fix or some other cleanup then could potentially be missed if the bot does not pick it up and it is not triggered manually.

**Pull request merged**
