### PR TITLE
ENH: automatic rpy2 instance conversion

### PR DESCRIPTION
**Pull request by sinhrks**
Derived from #7309. Create a wrapper for `robjects.r` in `pandas.rpy.common` to perform automatic pandas `DataFrame` and `Series` conversion. `Series` will be converted to R data.frame to preserve rownames (index).

If looks OK, I'll modify the doc (#7309) based on following API.

```
import pandas as pd
import pandas.rpy.common as com

iris = com.load_data('iris')
com.r.assign('iris', iris)
returned = com.r['iris']
type(returned)
# <class 'pandas.core.frame.DataFrame'>

df = pd.DataFrame(np.random.randn(20, 5),
                  index=pd.date_range(start='2011/01/01', freq='D', periods=20))
com.r.assign('df', df)
returned = com.r['df']
type(returned)
# <class 'pandas.core.frame.DataFrame'>

s = pd.Series(np.random.randn(20), name='test')
com.r.assign('s', s)
returned = com.r['s']
type(returned)
# <class 'pandas.core.frame.DataFrame'>
```

### CODE REVIEW

**Comment by jreback** [comment]
@sinhrks can you rebase / update

what is the status of this?

**Comment by jreback** [comment]
@sinhrks what's the status of this?

**Comment by sinhrks** [comment]
@jreback @jorisvandenbossche Based on #9187, direct conversion is maintained in `rpy2` ? Then I'll forward the request to rpy2 if any.

**Comment by jreback** [comment]
see #9602  we are deprecating in 0.16.0. and redirecting to ``rpy2`` for furture conversions.

**Pull request closed without merging**
