### PR TITLE
Use NumPy macros for overflow detection

### PR DESCRIPTION
**Pull request by WillAyd**

### CODE REVIEW

**Comment by mroeschke** [comment]
Looks like the complier warnings are still appearing in the MacOS build

```bash
  [88/152] Compiling C object pandas/_libs/pandas_datetime.cpython-39-darwin.so.p/src_vendored_numpy_datetime_np_datetime.c.o
  ../../pandas/_libs/src/vendored/numpy/datetime/np_datetime.c:358:40: warning: incompatible pointer types passing 'int64_t *' (aka 'long long *') to parameter of type 'long *' [-Wincompatible-pointer-types]
    return checked_int64_sub(year, 1970, result);
```

**Comment by WillAyd** [comment]
Ah cool that's helpful to see - thanks for pointing it out

**Comment by WillAyd** [comment]
Ok think the warnings are gone now

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @WillAyd

**Pull request merged**
