### PR TITLE
CI: Ignore this

### PR DESCRIPTION
**Pull request by TomAugspurger**
just trying from a different branch.

### CODE REVIEW

**Comment by jreback** [comment]
try

``conda install libpng=1.5.13``

I think the latest ``qt/pyqt`` installs the latest ``libpng`` which seems broken

**Comment by jreback** [comment]
just add ``libpng=1.5.13`` in ``ci/requirements-2.7_SLOW.build``

**Comment by TomAugspurger** [comment]
I'll try that next, that seems to be the version picked up though: https://travis-ci.org/pydata/pandas/jobs/90647120#L909. `libpng:         1.5.13-1`

**Comment by jreback** [comment]
hmm when I did this on s vm it installed pyqt and not pyside that is very odd (same version of qt though)

**Comment by TomAugspurger** [comment]
I don't even know anymore.... for whatever reason https://github.com/pydata/pandas/commit/428259aae91550af17ca06c4ec3fdab00e0b6945 kicked off two Travis runs, [1](https://travis-ci.org/pydata/pandas/builds/90647106) which failed on 2.7 so I killed it, and [2](https://travis-ci.org/pydata/pandas/builds/90647118) which is still running, but has gotten past the point of failure.

**Comment by jreback** [comment]
@TomAugspurger any luck on this?

did you specify using ``pyqt`` directly so it doesn't install ``pyside``.

**Comment by TomAugspurger** [comment]
let me try pyqt, any specific version?

**Comment by jreback** [comment]
this worked for me on a local vm (after failing with the same errors as on travis) when I fixed
libpng, but also try fixing ``qt=4.8.5`` and ``pyqt=4.10.4``

**Comment by jreback** [comment]
note that these are slightly older versions

**Comment by jreback** [comment]
side issue, we should prob just drop testing with mpl 1.2.1 (make an issue), as even mpl doesn't support older than 1.4

**Comment by TomAugspurger** [comment]
Yeah, I went with the newest. I'll try those next.

If this doesn't work then I've got a new clean repo and I'll just copy over my changes a couple at a time to see when it breaks.

**Comment by TomAugspurger** [comment]
https://travis-ci.org/pydata/pandas/builds/90940774 failed with unsatisfiable dependencies (most recent version of pyqt and the mpl 1.2.1).

Trying with the older pyqt and qt now in https://travis-ci.org/pydata/pandas/builds/90943124

**Comment by TomAugspurger** [comment]
Same [libshiboken errors on 2.7](https://travis-ci.org/pydata/pandas/jobs/90943126) when setting pyqt and qt.

**Comment by jreback** [comment]
is that the only build failing? just take jinja2 out then.. :<

**Comment by TomAugspurger** [comment]
It fails with or without Jinja though, which makes no sense at all. There's semi-regularly segfaults on the 3.4 build.

I'm just stepping through all the possibilities from this fresh branch today. I'll keep updating the thread with the results for reference.

change | result
--------- | ---------
update all CI files to jinja2 | |
update CI files excluding problematic 2.7 | |
update code only, not ci | |
update code and ci | |

**Comment by jreback** [comment]
@TomAugspurger side thing. update ``utils/print_version.py`` for ``jinja2/markupsafe`` as well

**Comment by TomAugspurger** [comment]
This is strange right? The failing build is only build 2, `27_slow_nnet_LOCALE`. It *doesn't* fail if we install Jinja2. It only fails when my actual code is included, *whether or not Jinja is installed*... So it's either

- *trying* to import Jinja (successfully or not) triggers the fail
- My `core/style.py` or the  `tests/test_style.py` is doing something

**Comment by jreback** [comment]
did u try renaming core/style.py ?

**Comment by TomAugspurger** [comment]
Yeah, let me try it from this branch though.

**Comment by TomAugspurger** [comment]
@jreback so I think [this](https://travis-ci.org/pydata/pandas/builds/91114804) succeeding narrowed it down to *trying to import Jinja*. Doesn't matter whether it's installed or not. Removing the tests means that it just isn't imported. I try to import it in the toplevel of `pandas.core.Style`, but I don't think that code was run at all in the last build. The only other option I see is something in my tests causing the failure, other than trying to import jinja.

**Pull request closed without merging**
