### PR TITLE
CLN: remove never-used kwargs, make kwargs explicit

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by WillAyd** [comment]
Nice PR - always on board with these types of cleanups

**Comment by jreback** [comment]
thanks

**Comment by simonjayhawkins** [comment]
ci is failing. was already failing here. revert or push fix? @jbrockmendel

**Comment by jbrockmendel** [comment]
the 37npdev build should have been fixed.  the mypy complaint ill push a PR for in a few minutes

**Pull request merged**
