### PR TITLE
REF: SparseArray imports

### PR DESCRIPTION
**Pull request by TomAugspurger**
arrays/sparse.py was doing an `import pandas as pd`, which is prone to cause circular imports. I've eliminated that import and updated the namespaces appropriately (NaT, isna, algos.unique / factorize).

Also updated `setup.cfg` to check the import order in `arrays/sparse.py`.

### CODE REVIEW

**Comment by alimcmaster1** [comment]
LGTM -  thanks for cleaning up the imports using isort too :)

**Comment by alimcmaster1** [comment]
I think if you remove one of the newlines after `from pandas.errors import PerformanceWarning` in sparse.py that should fix the isort failure on CI :)

**Comment by TomAugspurger** [comment]
Thanks.

Merging tonight, since this is a straight refactor, and I have another PR building on top if it.

**Comment by jreback** [comment]
pls merge master ping on green.

**Comment by TomAugspurger** [comment]
CircleCI seems to be ~10 hours behind. OK to cancel those, since we're dropping (most) of them anyway? I'll be free to clean things up this afternoon if we accidentally break anything.

**Comment by jreback** [comment]
sure

**Pull request merged**
