### PR TITLE
CI: Xfails on Python 3.10

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

~~The Python 3.10 CI is actually red, but the continue-on-error flag makes it so that the job is not failed. WIP because tests actually have to be fixed.~~
Added Xfails for some tests. Pretty much green except for #41935

### CODE REVIEW

**Comment by jreback** [comment]
right this was done on purpose so that we have time to fix the tests

so happy to merge this once all green otherwise

**Comment by lithomas1** [comment]
@jreback I think we should xfail these instead of doing this for now, and look into fixing them. The current setup means that its hard to tell if something breaks more tests on Python 3.10 in addition to the ones currently failing.

**Comment by jreback** [comment]
> @jreback I think we should xfail these instead of doing this for now, and look into fixing them. The current setup means that its hard to tell if something breaks more tests on Python 3.10 in addition to the ones currently failing.

sure happy to do that as well. I agree that's better.

**Review by jreback — CHANGES_REQUESTED** [review]
looks good ;
comment and ping when green

**Comment by lithomas1** [comment]
Still WIP becaue there's a ton of flaky tests and idk what's wrong with sparse tests.

**Review by jreback — CHANGES_REQUESTED** [review]

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
thanks @lithomas1 very nice!

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
