### PR TITLE
BUG: Unary pos/neg ops on IntegerArrays failing with TypeError

### PR DESCRIPTION
**Pull request by asishm**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
does this have a linked issue? can you add a whatsnew note (you can put in bug fixes for ExtensionArrays) for 1.2

**Comment by kokes** [comment]
This is a follow-up to #36078, which aimed to address #36063

**Comment by simonjayhawkins** [comment]
> does this have a linked issue? can you add a whatsnew note (you can put in bug fixes for ExtensionArrays) for 1.2

marking as 1.1.2 for now to match #36063

**Review by simonjayhawkins — CHANGES_REQUESTED** [review]
needs a release note and test from issue OP? (or comment in test with issue number)

**Comment by asishm** [comment]
sorry. I made an attempt to fix the issue (#36036) but then I realized I was trying to do stuff without fully understanding it, I'm not sure if this is even in the right direction at the moment. I can close this PR (put it in draft anyway because I was unsure) if someone else wants a crack at this.

**Comment by simonjayhawkins** [comment]
Thanks @asishm no problem, no pressure. will remove milestone.

**Pull request closed without merging**
