### PR TITLE
Adding DuckDB as a SQL Database for the to_sql() function

### PR DESCRIPTION
**Pull request by pdet**
This PR adds DuckDB as a direct possibility to the to_sql() function. 
It basically uses DuckDBs internal pandas integration to load data frames as a duckdb table.

I think I've added duckdb correctly as an optional dependency, I'm happy to fix it if I made any mistake :-)

I'm also really supporting the optional ```if_exists``` attribute, if any other attribute is a 'must-have' I'm also happy to do so.

### CODE REVIEW

**Comment by alimcmaster1** [comment]
Hey, thanks for the PR, DuckDb looks interesting. Might be worth opening an issue + getting agreement from core team that this is something we want to support before continuing dev here

**Review by mroeschke — CHANGES_REQUESTED** [review]
I commented on your created issue as well, but noted in https://github.com/pandas-dev/pandas/issues/45678#issuecomment-1024456727 that it would be great to have a SQL engine interface to implement Duck DB instead of having Duck DB specific code here

**Comment by jreback** [comment]
agree with @mroeschke recommendations here.

**Comment by mroeschke** [comment]
Thanks for the pull request, but as mentioned, in https://github.com/pandas-dev/pandas/issues/45678#issuecomment-1024456727, pandas would need to support a DB engine interface first before supporting DuckDB directly. Closing for now, but happy to have progress on the interface!

**Pull request closed without merging**
