### PR TITLE
STY/WIP: check for private imports/lookups

### PR DESCRIPTION
**Pull request by jbrockmendel**
Mostly this is an amalgam of #33479, #33394, and #33393.

### CODE REVIEW

**Comment by jreback** [comment]
looks good.

**Comment by jbrockmendel** [comment]
We're down to 4 things that need to either be renamed or add to the ignore list: _GroupBy, _Rolling, _Rolling_and_Expanding, _IntegerDtype.

@mroeschke any preferences for the Rolling names?

**Comment by mroeschke** [comment]
No preference for those.

**Comment by jbrockmendel** [comment]
green, booyah

**Comment by jreback** [comment]
very nice! (hopefully recent merges don't break on this :->)

**Comment by jbrockmendel** [comment]
> hopefully recent merges don't break on this

`make check` passes on master

**Pull request merged**
