### PR TITLE
DOC: Fixed GL02 errors in documentation

### PR DESCRIPTION
**Pull request by fshi01**
Fixed 2 of the 4 GL02 errors generated by pandas_validation_errors.ipynb 
The remaining two errors are from pandas.Timestamp.isoweekday and will be tackled next.

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]

**Comment by jbrockmendel** [comment]
is there a linter check we're going to add for this?

**Comment by mroeschke** [comment]
xref https://github.com/pandas-dev/pandas/issues/25120

**Comment by mroeschke** [comment]
Thanks @fshi01. Happy to have you to tackle the remaining GL02 errors and add a check in our CI.

**Comment by fshi01** [comment]
In addition to the remaining GL02 errors and adding a check to the CI, is there anything else I should do before it is merged?

**Comment by mroeschke** [comment]
Nothing in particular.

**Pull request merged**
