### PR TITLE
Revert fastparquet nullable dtype support

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by lithomas1** [comment]
OK, failing tests are flaky. So this is ready for review now. The backport will be a bit tricky, so I'll do it manually. (Basically backport the last PR and this PR together. We're still gonna backport that one since it unpins fastparquet even though most of its changes are reverted here).

cc @jorisvandenbossche (sorry for not pinging last time) @jreback

**Review by jorisvandenbossche — COMMENTED** [review]
Thanks a lot, looks good to me

>  The backport will be a bit tricky, so I'll do it manually. (Basically backport the last PR and this PR together. We're still gonna backport that one since it unpins fastparquet even though most of its changes are reverted here).

Another option is to first do a simple plain revert of the previous PR, and then include the changes of both PRs here (that will also make a easier to understand diff of the final changes), and then there is only a single PR to backport.

**Comment by jreback** [comment]
i am fine with this change.

**Comment by lithomas1** [comment]
ping for merge @jreback. Just merged master

**Comment by jreback** [comment]
thanks @lithomas1

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Comment by jreback** [comment]
@lithomas1 if you wouldn't mind do the manual backport here

**Comment by simonjayhawkins** [comment]
> Basically backport the last PR and this PR together.

The net result is no release note. do we need one? It's not clear to me what is changed/fixed?

**Comment by jorisvandenbossche** [comment]
Indeed, no release note, but the two combined PRs still have some changes to support the latest fastparquet version properly (in theory that could have been added as release note).

**Comment by simonjayhawkins** [comment]
> @lithomas1 if you wouldn't mind do the manual backport here

@lithomas1 what is added and then removed in the release notes is identical, so have synced the notes in #42985, so no need to backport that change.

**Comment by lithomas1** [comment]
Sorry, thanks for fixing that, planning on doing the backport now.

**Pull request merged**
