### PR TITLE
BLD: Pin cython for 37-locale build

### PR DESCRIPTION
**Pull request by TomAugspurger**
Seeing if this resolves the build failure.

xref https://github.com/pandas-dev/pandas/issues/34704

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Also the Checks and Docs github action builds are failing, and those use the main environment.yml I think?

**Comment by WillAyd** [comment]
Thanks @TomAugspurger

**Comment by WillAyd** [comment]
Though looks like we still have this pinned here:

https://github.com/pandas-dev/pandas/blob/08febd2b9f77fd8f943de92939788e8bc53ee2d2/ci/deps/azure-37-numpydev.yaml#L17

I can push a follow up PR. We might not even need that any more

**Comment by jorisvandenbossche** [comment]
@MeeseeksDev backport to 1.0.x

**Comment by simonjayhawkins** [comment]
@jorisvandenbossche will do this next

**Comment by WillAyd** [comment]
We actually don’t need to backport this can just do #34718

**Pull request merged**
