### PR TITLE
Removed unused strict struct member in tokenizer

### PR DESCRIPTION
**Pull request by WillAyd**
I don't see where this would ever be assigned a value

### CODE REVIEW

**Review by jbrockmendel — APPROVED** [review]
LGTM

**Comment by jreback** [comment]
cc @gfyoung 

we don't have any tests that hit this ?

**Review by gfyoung — APPROVED** [review]
Nice catch @WillAyd!  LGTM.

@jreback - given that the `strict` attribute is hard-coded to `0`, the branch being deleted looks dead, so none of our tests would have been able to hit it.

**Comment by jreback** [comment]
thanks @WillAyd

**Pull request merged**
