### PR TITLE
DEPR: Series.__setitem__ with Float64Index falling back to positional

### LINKED ISSUE #33469: API: __getitem__[int] vs __setitem__[int] with Float64Index
```
ser = pd.Series([1, 2, 3, 4], index=[1.1, 2.1, 3.0, 4.1])

>>> ser[5]                    # <--we are treating 5 as a label
KeyError: 5

>>> ser[5] = 5                # < --we are treating 5 as position
IndexError: index 5 is out of bounds for axis 0 with size 4

>>> ser[3] = 5                # <-- we are treating 3 as a label
>>> ser
1.1    1
2.1    2
3.0    5
4.1    4
dtype: int64
```

The `ser[5] = 5` case is an outlier because instead of having its label-vs-positional behavior determined by `ser.index._should_fallback_to_positional`, it is defermined by `if is_integer(key) and not self.index.inferred_type == "integer":`

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #33469
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
@jorisvandenbossche ok here?

**Comment by jorisvandenbossche** [comment]
Looks good to me.

Can you add an explicit test (eg with the example series from the issue) that checks the warning is raised if the key (as float) is not present and does not raise a warning when it is present (that case that already works correctly label-based right now)?

There are no other index types that can end up in this case and trigger the warning?

**Comment by jbrockmendel** [comment]
> Can you add an explicit test (eg with the example series from the issue) that checks the warning is raised if the key (as float) is not present and does not raise a warning when it is present (that case that already works correctly label-based right now)?

Good idea, will do.

> There are no other index types that can end up in this case and trigger the warning?

Brainstorming I came up with 2 more cases; will update the whatsnew

```
msg = "Treating integers as positional in Series.__setitem__"

ii = IntervalIndex.from_breaks(range(10))[::2]
ser2 = Series(range(len(ii)), index=ii)
expected2 = ser2.copy()
expected2.iloc[-1] = 9

with tm.assert_produces_warning(FutureWarning, match=msg):
    ser2[4] = 9
tm.assert_series_equal(ser2, expected2)

mi = MultiIndex.from_product([[1.1, 2.1, 3.0, 4.1], ["A", "B"]])
ser3 = Series(range(len(mi)), index=mi)
expected3 = ser3.copy()
expected3.iloc[4] = 99

with tm.assert_produces_warning(FutureWarning, match=msg):
    ser3[4] = 99
tm.assert_series_equal(ser3, expected3)
```

**Comment by jreback** [comment]
i need to re-look can you rebase

**Review by jreback — APPROVED** [review]
lgtm. @jorisvandenbossche if comments

**Pull request merged**
