### PR TITLE
CLN: Use defaultdict for minor optimization

### PR DESCRIPTION
**Pull request by jaketae**
Edit `_from_nested_dict()` by using defaultdict for optimization in performance

- [ ] closes #32209 
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jaketae** [comment]
@WillAyd @jreback Should this fix the problem? Thanks again for your input, and apologies for achieving this in such a roundabout fashion.

**Comment by WillAyd** [comment]
Yea we typically ask that you keep updates to the change all in one PR, but OK as is

**Review by WillAyd — APPROVED** [review]
Lgtm @jreback any objections?

**Comment by jreback** [comment]
this is ok

pls add labels

**Comment by jaketae** [comment]
> Yea we typically ask that you keep updates to the change all in one PR, but OK as is

@WillAyd I will make sure to follow that guideline for any future PRs. Thanks for the understanding.

**Comment by jreback** [comment]
thanks @jaketae

**Pull request merged**
