### PR TITLE
DOC: Document behaviour of head(n), tail(n) for negative values of n except on GroupBy

### LINKED ISSUE #30192: DOC: undocumented head(n), tail(n) accept negative values. But not on GroupBy
DOC: undocumented behavior that works: **`head(n)`, `tail(n)`accept negative values** both for DataFrame, Series. But not for [`GroupBy.head(n)`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.head.html#pandas.core.groupby.GroupBy.head) ; doesn't correctly handle negative values.

This is quite useful and could be documented. 
- `head(-n)` returns all rows(/elements) other than the n first values. Similar to `df[-6::]`.
- `tail(-n)` returns all rows(/elements) other than the n last values
- There is no error if the length n specified is too long for the dataframe(/series), just silently returns an empty result.

#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'x': range(18,0,-1), 'y': [x % 6 for x in range(18)] })

df.head(-25)
Empty DataFrame
Columns: [x, y]
Index: []

df.head(-15)
    x  y
0  18  0
1  17  1
2  16  2

 df.tail(-15)
    x  y
15  3  3
16  2  4
17  1  5

df['x'].tail(-15)
15    3
16    2
17    1

# But GroupBy.head(n) doesn't
 df.groupby('y').head(-1)
Empty DataFrame
Columns: [x, y]
Index: []
df.groupby('y').tail(-1)
Empty DataFrame
Columns: [x, y]
Index: []

```
#### Problem description

Add to documented behavior. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 18.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 5.2.4
pip: 19.3.1
setuptools: 41.6.0.post20191030
Cython: 0.29.14
numpy: 1.17.3
scipy: 1.3.1
pyarrow: None
xarray: None
IPython: 7.9.0
sphinx: 2.2.1
patsy: 0.5.1
dateutil: 2.8.1
pytz: 2019.3
blosc: None
bottleneck: 1.3.1
tables: 3.6.1
numexpr: 2.7.0
feather: None
matplotlib: 3.1.1
openpyxl: 3.0.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.2.6
lxml.etree: 4.4.1
bs4: 4.8.1
html5lib: 1.0.1
sqlalchemy: 1.3.11
pymysql: None
psycopg2: 2.8.4 (dt dec pq3 ext lo64)
jinja2: 2.10.3
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

### PR DESCRIPTION
**Pull request by bharatr21**
- [x] xref #30192 
- [x] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Output of `python3 scripts/validate_docstrings.py pandas.DataFrame.head`

```bash
################################################################################
###################### Docstring (pandas.DataFrame.head)  ######################
################################################################################

Return the first `n` rows.

This function returns the first `n` rows for the object based
on position. It is useful for quickly testing if your object
has the right type of data in it.

For negative values of `n`, this function returns all rows except
the last `n` rows, equivalent to ``df[:-n]``.

Parameters
----------
n : int, default 5
    Number of rows to select.

Returns
-------
same type as caller
    The first `n` rows of the caller object.

See Also
--------
DataFrame.tail: Returns the last `n` rows.

Examples
--------
>>> df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
>>> df
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

Viewing the first 5 lines

>>> df.head()
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey

Viewing the first `n` lines (three in this case)

>>> df.head(3)
      animal
0  alligator
1        bee
2     falcon

For negative values of `n`

>>> df.head(-3)
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot

################################################################################
################################## Validation ##################################
################################################################################

Docstring for "pandas.DataFrame.head" correct. :)
```

Output of `python3 scripts/validate_docstrings.py pandas.DataFrame.tail`

```bash
################################################################################
###################### Docstring (pandas.DataFrame.tail)  ######################
################################################################################

Return the last `n` rows.

This function returns last `n` rows from the object based on
position. It is useful for quickly verifying data, for example,
after sorting or appending rows.

For negative values of `n`, this function returns all rows except
the first `n` rows, equivalent to ``df[n:]``.

Parameters
----------
n : int, default 5
    Number of rows to select.

Returns
-------
type of caller
    The last `n` rows of the caller object.

See Also
--------
DataFrame.head : The first `n` rows of the caller object.

Examples
--------
>>> df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
>>> df
      animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

Viewing the last 5 lines

>>> df.tail()
   animal
4  monkey
5  parrot
6   shark
7   whale
8   zebra

Viewing the last `n` lines (three in this case)

>>> df.tail(3)
  animal
6  shark
7  whale
8  zebra

For negative values of `n`

>>> df.tail(-3)
   animal
3    lion
4  monkey
5  parrot
6   shark
7   whale
8   zebra

################################################################################
################################## Validation ##################################
################################################################################

Docstring for "pandas.DataFrame.tail" correct. :)
```

Output of `./ci/code_checks.sh doctests` passed for `groupby.py`

### CODE REVIEW

**Review by TomAugspurger — APPROVED** [review]
This looks nice. I think we'll leave https://github.com/pandas-dev/pandas/issues/30192 open to either implement this for GroupBy or raise.

**Comment by TomAugspurger** [comment]
@Bharat123rox can you verify that we have unit tests for negative values in DataFrame.head?

**Comment by Bharat123rox** [comment]
We do have the unit tests 👍
 
https://github.com/pandas-dev/pandas/blob/a2bbdb5a0abd131d0190fe58c0ba7cbf21b960c9/pandas/tests/generic/test_generic.py#L306-L308

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
