### PR TITLE
DEP: add pytest-mock to environment.yml

### PR DESCRIPTION
**Pull request by h-vetinari**
Ran into errors when trying to run the test suite in a freshly installed conda environment. There's an error being caused by the fact that #25346 added `pytest-mock` as a dependency in all the CI jobs (to be able to use the `mocker` fixture), but didn't adapt `environment.yml`. This PR fixes that.

### CODE REVIEW

**Comment by jreback** [comment]
ok thanks

**Comment by jreback** [comment]
thanks

**Comment by TomAugspurger** [comment]
Do we want this as a "required" test dependency?

Also, why was pytest-mock needed? Was something not working with unittest.mock?

**Comment by jreback** [comment]
this is already added 

unittest.mock is not always available PY2 and is not useful with pytest (gets was broken)

**Comment by TomAugspurger** [comment]
What's "gets"?

Previously, we had a mock fixture that provided unittest.mock if it was
present, and skipped if not (py2).

From the diff in https://github.com/pandas-dev/pandas/pull/25346/files it
doesn't seem like we're using any of the pytest-specific features of
pytest-mock.
OK to revert those and just use unittest.mock when we drop python 2?

**Pull request merged**
