### PR TITLE
CI: Xfail less on Python 3.10

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

Thanks realead for fixing the tests.

### CODE REVIEW

**Comment by jreback** [comment]
this ok to backport? these were related to @realead patches that we *did* backport?

**Comment by lithomas1** [comment]
Yep should be #42135 and #41988 iirc.

**Comment by jreback** [comment]
great thanks @lithomas1

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
