### PR TITLE
BUG: Don't extract header names if none specified

### LINKED ISSUE #11733: BUG: read_excel with multi-indexed column ignores index_col=None
From SO: http://stackoverflow.com/questions/34020061/excel-to-pandas-dataframe-using-first-column-as-index

@chris-b1 another one on the multi-index excel issues .. :-)

Small test case: content of excel file:

| A | A | B | B |
| --- | --- | --- | --- |
| key | val | key | val |
| 1 | 2 | 3 | 4 |
| 1 | 2 | 3 | 4 |

gives:

```
In [2]: pd.read_excel("test_excel_index_col.xlsx", header=[0,1], index_col=None)
Out[2]:
A     A    B
key val key  val
1     2    3   4
1     2    3   4
```

It's not super clear in the formatting of the dataframe, but the [1, 1] is the index and [A, key] are seen as the level names of the multi-indexed columns.

### PR DESCRIPTION
**Pull request by gfyoung**
Closes #11733.

### CODE REVIEW

**Comment by gfyoung** [comment]
@chris-b1 @jreback : Rebased my changes, and all is green.  PTAL.

**Comment by gfyoung** [comment]
@chris-b1 @jreback : Any further thoughts on this?

**Comment by jreback** [comment]
@gfyoung it looks fine to me, but @chris-b1 should have a look.

**Review by WillAyd — APPROVED** [review]

**Comment by chris-b1** [comment]
Just to confirm, since they don't diff - none of the existing cases in the xlsx files were modified?  Assuming no, looks good to me!

**Comment by gfyoung** [comment]
@chris-b1 : I just added a new test to those Excel files.  None of the existing tabs were modified. 👍

**Comment by gfyoung** [comment]
Alright, with three LGTM's, I think this is good to merge now. 🙂

**Pull request merged**
