### PR TITLE
CLN/PERF: remove unused out kwd in take_nd

### PR DESCRIPTION
**Pull request by jbrockmendel**
And in a few places where we know allow_fill=False, just call the numpy version directly.

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. any perf benefit?

**Comment by jbrockmendel** [comment]
> any perf benefit?

mostly in the places where we call ndarray.take directly instead of going through algos.take

**Comment by jorisvandenbossche** [comment]
@jbrockmendel did you run benchmarks for this change? 
There are lots of regressions at https://pandas.pydata.org/speed/pandas/#regressions?sort=1&dir=desc that point to this commit (although it's not always very accurate in pointing to the correct commit, so it can also be something else, but so should be checked)

**Comment by jbrockmendel** [comment]
i profiled with ipython, didnt run the asv suite.  do you have a hypothesis for what part of this might be the culprit?

**Comment by jorisvandenbossche** [comment]
>  do you have a hypothesis for what part of this might be the culprit?

No, I didn't check it in detail. This PR is touching several places, and it is also a variety of benchmarks that seem to be affected (reindexing, merge, groupby, ops, select_dtypes, dropna)

**Comment by jorisvandenbossche** [comment]
@jbrockmendel were you able to look into this? 
(if not, I would propose to revert it for now (because that will only get harder later), and add it again in smaller parts)

**Comment by jbrockmendel** [comment]
> (if not, I would propose to revert it for now (because that will only get harder later), and add it again in smaller parts)

OK i guess

**Comment by jorisvandenbossche** [comment]
@jbrockmendel can you follow-up on this?

**Pull request merged**
