### PR TITLE
DOC: Update documentation with correct link

### PR DESCRIPTION
**Pull request by listentojohan**
Fixed from shttp to https in docs link

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
You are doing a PR against the 0.20.x branch. Can you do it against master?

**Comment by listentojohan** [comment]
@jorisvandenbossche You changed the branch. Do you need me to do anything else?

**Comment by jorisvandenbossche** [comment]
Yes, I tried, but that apparently does not work (many other commits are then included). You can also do that, but then you need to rebase on latest master?

**Comment by gfyoung** [comment]
@jorisvandenbossche : The PR has been fixed to be against `master` now.

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request merged**
