### PR TITLE
DEPR: silently ignoring unrecognized timezones

### LINKED ISSUE #18702: Timezones silently dropped in parsing
TLDR: pandas should pass a `tzinfos` kwarg to the dateutil parser using sensible defaults.

dateutil has a bug that silently drops most timezones.  That bug is inherited by pandas.  The following is run on a machine located in US/Pacific:

```
>>> pd.Timestamp('2017-12-08 08:20 PM PST')     # <-- only parsed correctly because of locale
Timestamp('2017-12-08 20:20:00-0800', tz='tzlocal()')
>>> pd.Timestamp('2017-12-08 08:20 PM EST')     # <-- timezone silently dropped
Timestamp('2017-12-08 20:20:00')
```

There is a partial [fix in progress](https://github.com/dateutil/dateutil/pull/540) over at dateutil, the most likely outcome of which is that these cases will raise in the future unless a `tzinfos` kwarg is explicitly passed to `dateutil.parser.parse`.  The issue for pandas is then to decide on what tzinfos to pass (a [suggestion](https://github.com/dateutil/dateutil/issues/575) to handle the most common use cases by default within dateutil went nowhere).

The `tzinfos` kwarg is a dictionary taking a string and returning a `tzinfo` object, e.g.

```
unambiguous_tzinfos = {
    'PDT': dateutil.tz.gettz('US/Pacific'),
    'PT': dateutil.tz.gettz('US/Pacific'),
    'MDT': dateutil.tz.gettz('US/Mountain'),
    'MT': dateutil.tz.gettz('US/Mountain'),
    'ET': dateutil.tz.gettz('US/Eastern'),
    'CET': dateutil.tz.gettz('Europe/Amsterdam),
    'NZDT': dateutil.tz.gettz('Pacific/Auckland')}
```

This example includes only abbreviations for which there are no other alternatives listed [here](https://www.timeanddate.com/time/zones/).  So e.g. "CST" is excluded since it could also be "China Standard Time", "EST" is excluded since it could refer to "Australian Eastern Standard Time".  Note this is only a subset of the unambiguous abbreviations.

### LINKED ISSUE #51476: BUG: inferring incorrect datetime format
```python
dtstr = "2014 Jan 9 05:15 FAKE"
arg = np.array([dtstr], dtype=object)

>>> pd.core.tools.datetimes._guess_datetime_format_for_array(arg, dayfirst=None)
'%Y %b %d %H:%M FAKE'
```

Because _guess_datetime_format_for_array keeps "FAKE", to_datetime then goes through _array_strptime_with_fallback, which drops the bad tz completely.

Not sure exactly where to catch this, but need to handle it somewhere in order to deprecate #18702.

cc @MarcoGorelli

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #18702 (Replace xxxx with the GitHub issue number)
- [x] closes #51476
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

<s>WIP part is need to figure out #51476 before the deprecation warning will be issued by to_datetime.</s>Update: addressed.

### CODE REVIEW

**Comment by jbrockmendel** [comment]
updated to handle strptime inference cc @MarcoGorelli

**Review by MarcoGorelli — APPROVED** [review]
Is the idea just to raise the warning on the pandas side, so that we have control over it and can raise in the future?

Looks good to me!

**Comment by MarcoGorelli** [comment]
> WIP part is need to figure out https://github.com/pandas-dev/pandas/issues/51476 before the deprecation warning will be issued by to_datetime.

Looks like you've figured this out? `guess_datetime_format` now raises the deprecation warning

**Comment by jbrockmendel** [comment]
> Is the idea just to raise the warning on the pandas side, so that we have control over it and can raise in the future?

yes.

> Looks like you've figured this out? guess_datetime_format now raises the deprecation warning

yes.

**Comment by phofl** [comment]
note was added for 2.0, do we want to backport or move the note?

**Comment by jbrockmendel** [comment]
probably better to move the note.  will add to my next Assorted branch

**Comment by phofl** [comment]
thx

**Pull request merged**
