### PR TITLE
DOC: Move import conventions from wiki to docs #30808

### LINKED ISSUE #30808: DOC: Move import conventions from wiki to docs
The section about imports here: https://github.com/pandas-dev/pandas/wiki/Code-Style-and-Conventions#imports-aim-for-absolute

Can be moved to the code style guide in the documentation: https://dev.pandas.io/docs/development/code_style.html

This way we can remove the page from the wiki, that is mostly outdated.

### PR DESCRIPTION
**Pull request by souvik3333**
- [x] closes #30808
- [ ] tests added / passed
- [x] passes `black pandas`
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by souvik3333** [comment]
@datapythonista I was looking into testing files and there all imports are absolute but previously (according to wiki) explicit relative imports were encouraged. Are absolute imports encouraged in test files also?

**Comment by datapythonista** [comment]
Lots of people contribute to pandas, so if we don't enforce the policies with validation in the CI, you'll find any possible kind of practice in the code base. I think the preferred option is using absolute imports, so for now, if you can move that policy to the docs, that's a first step. Then, we may considering if its worth detecting relative imports, fixing them, and validating in the CI that they are not reintroduced. Feel free to open an issue to discuss that after this is closed.

**Comment by souvik3333** [comment]
@datapythonista, I have updated the docs. Let me know if there should be any changes.

**Review by datapythonista — APPROVED** [review]
lgtm, @simonjayhawkins do you want to have a look?

**Review by simonjayhawkins — APPROVED** [review]

**Comment by simonjayhawkins** [comment]
Thanks @souvik3333

**Comment by datapythonista** [comment]
Thanks both, I deleted the wiki page.

**Pull request merged**
