### PR TITLE
CLN: remove unused freq kwarg in libparsing

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by jbrockmendel** [comment]
Travis is green, just hasnt updated here

**Review by gfyoung — APPROVED** [review]

**Comment by jreback** [comment]
hmm, no tests need changing?

**Comment by jbrockmendel** [comment]
> hmm, no tests need changing?

nope, we just never pass the argument

**Comment by jreback** [comment]
kk ping on green

**Review by mroeschke — APPROVED** [review]

**Pull request merged**
