### PR TITLE
DOC: remove references to dev.pandas.io

### LINKED ISSUE #39368: WEB: decommission dev.pandas.io
#### Location of the documentation

http://dev.pandas.io/

#### Documentation problem

Both http://dev.pandas.io/ and https://pandas.pydata.org/docs/dev/ exist, and it's confusing what the difference is / what each are for.

#### Suggested fix for documentation

- [x] Remove references to `dev.pandas.io` -> #39377
- [ ] Ensure all content from http://dev.pandas.io/pandas-blog/ is on https://pandas.pydata.org/community/blog/
   - https://github.com/pandas-dev/pandas-blog/tree/master/content
   - https://github.com/pandas-dev/pandas/tree/master/web/pandas/community/blog
- [ ] Redirect `dev.pandas.io`

### PR DESCRIPTION
**Pull request by ayushmankumar7**
- [ ] xref #39368 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Suggested fix 

- [x] Remove references to dev.pandas.io
- [ ] Ensure all content from http://dev.pandas.io/pandas-blog/ is on https://pandas.pydata.org/community/blog/
https://github.com/pandas-dev/pandas-blog/tree/master/content
https://github.com/pandas-dev/pandas/tree/master/web/pandas/community/blog
- [ ] Redirect dev.pandas.io

### CODE REVIEW

**Comment by jreback** [comment]
looks fine to me. cc @afeld @datapythonista

**Review by datapythonista — APPROVED** [review]
Yes, I think all those are ok to point to the stable docs, looks good.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Indeed, thanks @ayushmankumar7 !

**Comment by ayushmankumar7** [comment]
@jorisvandenbossche  Thanks for accepting my PR! :100:

**Comment by phamvantuong** [comment]
I THANK YOUCẢM ƠN TẤT CẢ MỌI NGƯỜI ĐÃ GỌI VÀ LIÊN KẾT ĐẾN TÔI KÝ TÊN PHẠM VĂN TƯỜNG Vào 24 Th1, 2021 23:59, Ayushman Kumar <notifications@github.com> đã viết: closes #39368 tests added / passed Ensure all linting tests pass, see here for how to run them whatsnew entry
Suggested fix
 Remove references to dev.pandas.io Ensure all content from http://dev.pandas.io/pandas-blog/ is on https://pandas.pydata.org/community/blog/
https://github.com/pandas-dev/pandas-blog/tree/master/content
https://github.com/pandas-dev/pandas/tree/master/web/pandas/community/blog Redirect dev.pandas.io



You can view, comment on, or merge this pull request online at:
  https://github.com/pandas-dev/pandas/pull/39377

Commit Summary
removed references to dev.pandas.io

File Changes

    M
    .github/ISSUE_TEMPLATE/documentation_improvement.md
    (2)
  
    M
    README.md
    (2)
  
    M
    doc/source/whatsnew/v0.25.0.rst
    (2)
  
    M
    doc/source/whatsnew/v1.0.0.rst
    (4)
  
    M
    doc/source/whatsnew/v1.1.0.rst
    (2)
  
    M
    doc/source/whatsnew/v1.2.0.rst
    (2)
  
    M
    doc/source/whatsnew/v1.3.0.rst
    (2)
  

Patch Links:
https://github.com/pandas-dev/pandas/pull/39377.patchhttps://github.com/pandas-dev/pandas/pull/39377.diff

**Pull request merged**
