### PR TITLE
TST: correct parquet test expected partition column dtype for pyarrow 2.0

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Follow-up on https://github.com/pandas-dev/pandas/pull/35814, but now incorporating the changes in pyarrow 2.0

cc @alimcmaster1 

Also related to https://github.com/pandas-dev/pandas/issues/37286 and https://github.com/pandas-dev/pandas/pull/37296/ (timezone related failures), but doing this fix separate as it's not something that needs to be reverted.

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
the travis-36-cov builds regularly fails to build with `The build has been terminated` so haven't yet seen this failing on 1.1.x but probably makes sense to backport this.

**Comment by jreback** [comment]
thanks @jorisvandenbossche

**Comment by jreback** [comment]
> the travis-36-cov builds regularly fails to build with `The build has been terminated` on 1.1.x so haven't yet seen this failing on 1.1.x but probably makes sense to backport this.

yeah this is happening regularly, odd

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.1.x

**Comment by simonjayhawkins** [comment]
> > the travis-36-cov builds regularly fails to build with `The build has been terminated` on 1.1.x so haven't yet seen this failing on 1.1.x but probably makes sense to backport this.
> 
> yeah this is happening regularly, odd

i'll open a dedicated issue so that references to this can be collated.

**Pull request merged**
