### PR TITLE
CI: tz dtype mismatch in test_parquet following pyarrow upgrade

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
prob need to backport this

**Comment by jbrockmendel** [comment]
this caused a different failure in Travis.  cc @jorisvandenbossche thoughts on the right way to solve this?

**Comment by jorisvandenbossche** [comment]
I am looking into the actual cause (it's our testing machinery that cannot handle with different but equivalent timezones), let's use https://github.com/pandas-dev/pandas/issues/37286 to further discuss this. 
As a temporary fix to get green CI, I put up https://github.com/pandas-dev/pandas/pull/37303 (I prefer that intead of this PR, because setting `check_categorical` to False is only fixing it "by accident", I think)

**Comment by jorisvandenbossche** [comment]
> this caused a different failure in Travis

Did a separate PR for that one (not a timezone related failure): https://github.com/pandas-dev/pandas/pull/37304

**Pull request closed without merging**
