### PR TITLE
BUG: Datareader index name shows unicode characters

### LINKED ISSUE #8967: DataReader with google source returns DataFrame with incorrect index name
Hello,

    import pandas.io.data as web
    import datetime

    symbol = "AAPL"
    end = datetime.datetime.now()
    start = end - datetime.timedelta(days=10)
    df = web.DataReader("AAPL", 'google', start, end)

    df.index.name

is `'\xef\xbb\xbfDate'` it should be only `'Date'`

\xef\xbb\xbf characters are invisible !

A quick and dirty solution is to change

    def _retry_read_url(url, retry_count, pause, name):
        for _ in range(retry_count):
            time.sleep(pause)

            # kludge to close the socket ASAP
            try:
                with urlopen(url) as resp:
                    lines = resp.read()
            except _network_error_classes:
                pass
            else:
                rs = read_csv(StringIO(bytes_to_str(lines)), index_col=0,
                              parse_dates=True)[::-1]
                # Yahoo! Finance sometimes does this awesome thing where they
                # return 2 rows for the most recent business day
                if len(rs) > 2 and rs.index[-1] == rs.index[-2]:  # pragma: no cover
                    rs = rs[:-1]
                return rs

        raise IOError("after %d tries, %s did not "
                      "return a 200 for url %r" % (retry_count, name, url))

to

    def _retry_read_url(url, retry_count, pause, name):
        for _ in range(retry_count):
            time.sleep(pause)

            # kludge to close the socket ASAP
            try:
                with urlopen(url) as resp:
                    lines = resp.read()
            except _network_error_classes:
                pass
            else:
                rs = read_csv(StringIO(bytes_to_str(lines)), index_col=0,
                              parse_dates=True)[::-1]
                rs.index.name = 'Date'
                # Yahoo! Finance sometimes does this awesome thing where they
                # return 2 rows for the most recent business day
                if len(rs) > 2 and rs.index[-1] == rs.index[-2]:  # pragma: no cover
                    rs = rs[:-1]
                return rs

        raise IOError("after %d tries, %s did not "
                      "return a 200 for url %r" % (retry_count, name, url))

so adding rs.index.name = 'Date'
fix the problem but it could have side effect for other datasource

Kind regards

### PR DESCRIPTION
**Pull request by davidastephens**
Fixes #8967

### CODE REVIEW

**Comment by jreback** [comment]
@dstephens99 this looks ok, pls rebase.

alos note that we are moving the dataread stuff to a separate package, pandas-datareade, i'll send you an invite to the repo

**Comment by dstephens99** [comment]
Can this get ported to datareader? Or should I submit a pull request there as well?

**Comment by jreback** [comment]
@dstephens99 this needs to be merged to pandas? or no

**Comment by dstephens99** [comment]
No, it got merged in with #9358

**Comment by jreback** [comment]
@dstephens99 gr8 thankns!

**Pull request closed without merging**
