### PR TITLE
PERF: indexing on UInt64Index with int64s

### LINKED ISSUE #41873: PERF: performance regression in indexing UInt64Index with an array-like
See eg https://pandas.pydata.org/speed/pandas/#indexing.NumericSeriesIndexing.time_loc_list_like?python=3.8&Cython=0.29.21&p-index_dtype=%3Cclass%20'pandas.core.indexes.numeric.UInt64Index'%3E&p-index_structure='unique_monotonic_inc'

Up to 180x slowdown in the `indexing.NumericSeriesIndexing.time_loc_array/time_loc_list_like` benchmarks with UInt64Index.

Indicated range of responsible commits is https://github.com/pandas-dev/pandas/compare/21d61451...c9d50d82

Didn't check, but potential candidate: https://github.com/pandas-dev/pandas/pull/41777 or #41804

cc @jbrockmendel

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] closes #41873
- [ ] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
This fixes a regression on master so should be backported to 1.3.x

**Comment by simonjayhawkins** [comment]
@jbrockmendel can you post some timings.

**Review by jreback — CHANGES_REQUESTED** [review]
can u add a test here

**Comment by jbrockmendel** [comment]
> can u add a test here

not actually changing any behavior

> can you post some timings

based on the asv mentioned in #41873

```
index = pd.UInt64Index(range(10**6))
ser = pd.Series(np.random.randn(10**6), index=index)

%timeit ser.loc[[800000]]
278 µs ± 12.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)   # <- PR
124 ms ± 1.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)   # <- master
```

**Review by jreback — APPROVED** [review]

**Comment by jreback** [comment]
@meeseeksdev backport 1.3.x

**Pull request merged**
