### PR TITLE
BUG: Bug in .to_datetime() when passing integers or floats, no unit and errors=coerce

### LINKED ISSUE #13180: Converting float64 values to datetime64[ns] format using pd.to_datetime results in NaT if errors='coerce'
#### Code Sample, a copy-pastable example if possible

A Pandas dataframe contains a date variable that is formatted as float64 as follows:
```
tempDF = pd.DataFrame({'group': ['a','b'],
                       'date': [1.434692e+18,1.432766e+18]})

print(tempDF)
```
Which appears as:
```
           date group
0  1.434692e+18     a
1  1.432766e+18     b
```
The date variables can be formatted to datetime64[ns] as follows:
```
tempDF['date'] = pd.to_datetime(tempDF['date'],format=None)
print(tempDF)
```
Which works as expected:
```
                 date group
0 2015-06-19 05:33:20     a
1 2015-05-27 22:33:20     b
```
However, if errors='coerce' is included in the do_datetime() function, the dates are returned as NaT.
```
tempDF['date'] = pd.to_datetime(tempDF['date'],format=None,errors='coerce')
print(tempDF)
```
Which produces the following:
```
  date group
0  NaT     a
1  NaT     b
```
This issue was identified as a result of a reported bug (#12821 ) where datetime64[ns] columns are returned as float64 following agg() function where all dates in a group are NaT. Converting columns back to datetime64[ns] format is necessary. However, identifying valid numeric values as errors when errors='coerce' and returning NaT values results in unnecessary data-loss.

#### Expected Output
```
                 date group
0 2015-06-19 05:33:20     a
1 2015-05-27 22:33:20     b
```

#### output of ``pd.show_versions()``
```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.1.final.0
python-bits: 64
OS: Darwin
OS-release: 15.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.18.1
nose: None
pip: 1.5.6
setuptools: 20.1.1
Cython: None
numpy: 1.11.0
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: 4.1.1
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.0
openpyxl: 2.3.2
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
```

### PR DESCRIPTION
**Pull request by jreback**
closes #13180

### CODE REVIEW

**Comment by jreback** [comment]
@jorisvandenbossche 

note that prior to 0.18.1 we would handle

``pd.to_datetime([1])`` with ``unit='ns'`` as the default. This PR addresses this, but after looking again, should we *make* the user specify it here (when it IS ns), e.g. as in the accompanied issue.

**Comment by jreback** [comment]
any comments @jorisvandenbossche

**Comment by melzoghbi** [comment]
I have pandas version 0.19.2 and i still get this error when using to_datetime() method. My column type is int64 and here is the error message when i use the following:
image

1)  pd.to_datetime(ds['createdTime'], unit='s')   -->  OutOfBoundsDatetime: cannot convert input with unit 's'

2) pd.to_datetime(ds['createdTime']) --> no conversion

image

Any idea how to fix this? Thanks a lot.

**Comment by jorisvandenbossche** [comment]
@melzoghbi if you still have an issue, please open a *new* issue (as your example is not related to the above issue). However, please first make sure to test on the latest pandas (0.21.0) and make sure to have an actual reproducible examples (so copy-pasteable code, not as an image). 

Further, for me this actually converts to a datetime:

```
In [121]: s = pd.Series([1508258340299])

In [122]: pd.to_datetime(s)
Out[122]: 
0   1970-01-01 00:25:08.258340299
dtype: datetime64[ns]
```

**Comment by melzoghbi** [comment]
Thanks for your help and this actually works 💯

**Comment by hashamMunir** [comment]
issue persists in pd 0.23.3
converting the unixtime to date time. 
1970-01-01 00:00:01.529009633
it returns 1970

**Comment by pushyamig** [comment]
this is still an issue in the Pandas `0.23.4`, is there any workaround?

**Comment by jorisvandenbossche** [comment]
This is a closed issue that is fixed. If you think there is still a bug, please open a *new* issue with a reproducible example.

If it is about the year 1970, that is not a bug but because `to_datetime` interprets integers as nanoseconds by default:

```
In [11]: s = pd.Series([1510675225])

In [12]: pd.to_datetime(s)
Out[12]: 
0   1970-01-01 00:00:01.510675225
dtype: datetime64[ns]

In [13]: pd.to_datetime(s, unit='s')
Out[13]: 
0   2017-11-14 16:00:25
dtype: datetime64[ns]
```

**Pull request closed without merging**
