### PR TITLE
CI: Skip testing step in Pypy job

### PR DESCRIPTION
**Pull request by mroeschke**
@lithomas1 during today's dev call, I asked if we still need the Pypy build since it's actively failing (but passing in the CI) and no one is really ensuring we have compat with Pypy. Thought if we can remove it?

### CODE REVIEW

**Comment by lithomas1** [comment]
Can you just remove the testing phase instead?

We still build PyPy packages on conda (and pandas has failed to compile on PyPy come release time at least once).

**Comment by phofl** [comment]
The validate min versions script errors on the PyPy build, should investigate if we keep the file around

**Comment by mroeschke** [comment]
Sure, let's just skip the testing steps of the Pypy jobs instead

But IIRC it doesn't looks like our cibuildwheel is building for pypy which uploads to conda?

https://github.com/pandas-dev/pandas/blob/81b08a9581a72545bee2d3026d3cf5d030ff2223/.github/workflows/wheels.yml#L58

**Comment by jbrockmendel** [comment]
cc @cfbolz we (pandas) don't have anyone championing pypy support.  Can you suggest anyone from the pypy team who might be interested?

**Comment by lithomas1** [comment]
> Sure, let's just skip the testing steps of the Pypy jobs instead
> 
> But IIRC it doesn't look like our cibuildwheel is building for pypy which uploads to conda?
> 
> https://github.com/pandas-dev/pandas/blob/81b08a9581a72545bee2d3026d3cf5d030ff2223/.github/workflows/wheels.yml#L58

Although we upload PyPI wheels to Anaconda, we upload them to Anaconda's PyPI repositories, not the conda ones.

The conda packages are built separately by the pandas-feedstock repo, and the packages are built from the Github release tarball.
https://github.com/conda-forge/pandas-feedstock/blob/76269c33f5865e0642232cf9c73fdefb7f9412a7/recipe/meta.yaml#L8

**Review by lithomas1 — APPROVED** [review]

**Pull request merged**
