### PR TITLE
COMPAT: 32-bit compat fixes mainly in testing

### LINKED ISSUE #13566: Test failures on 32-bit Linux
Testing 32-bit Manylinux1 wheels for Pandas 0.18.1 gives the following errors:

```
======================================================================
ERROR: test_read_dta12 (pandas.io.tests.test_stata.TestStata)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/io/tests/test_stata.py", line 244, in test_read_dta12
    parsed_117 = self.read_dta(self.dta21_117)
  File "/venv/local/lib/python2.7/site-packages/pandas/io/tests/test_stata.py", line 86, in read_dta
    return read_stata(file, convert_dates=True)
  File "/venv/local/lib/python2.7/site-packages/pandas/io/stata.py", line 170, in read_stata
    return reader.read()
  File "/venv/local/lib/python2.7/site-packages/pandas/io/stata.py", line 1499, in read
    data = self._insert_strls(data)
  File "/venv/local/lib/python2.7/site-packages/pandas/io/stata.py", line 1595, in _insert_strls
    data.iloc[:, i] = [self.GSO[k] for k in data.iloc[:, i]]
KeyError: 4294967299
======================================================================
FAIL: test_isin (pandas.tseries.tests.test_timedeltas.TestTimedeltaIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tseries/tests/test_timedeltas.py", line 1681, in test_isin
    self.assertTrue(result.all())
AssertionError: False is not true
======================================================================
FAIL: test_isin (pandas.tseries.tests.test_timeseries.TestDatetimeIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tseries/tests/test_timeseries.py", line 3452, in test_isin
    self.assertTrue(result.all())
AssertionError: False is not true
======================================================================
FAIL: test_isin_with_i8 (pandas.tests.series.test_analytics.TestSeriesAnalytics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tests/series/test_analytics.py", line 1128, in test_isin_with_i8
    assert_series_equal(result, expected)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1049, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3887)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2769)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different
Series values are different (40.0 %)
[left]:  [False, False, False, False, False]
[right]: [True, True, False, False, False]
======================================================================
FAIL: test_basic (pandas.tests.test_algos.TestIsin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tests/test_algos.py", line 371, in test_basic
    tm.assert_numpy_array_equal(result, expected)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 957, in assert_numpy_array_equal
    raise_assert_detail(obj, msg, left, right)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: numpy array are different
numpy array values are different (33.33333 %)
[left]:  [False, False, False]
[right]: [True, False, False]
======================================================================
FAIL: test_drop_level_nonunique_datetime (pandas.tests.test_multilevel.TestMultiLevel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/pandas/tests/test_multilevel.py", line 1978, in test_drop_level_nonunique_datetime
    assert_frame_equal(result, expected)
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1119, in assert_frame_equal
    '{0}, {1}'.format(right.shape[0], right.index))
  File "/venv/local/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame are different
DataFrame shape (number of rows) are different
[left]:  5, MultiIndex(levels=[[2, 3, 4, 5], [2016-03-23 14:00:00, 2016-03-23 15:00:00, 2016-03-23 16:00:00, 2016-03-23 17:00:00]],
           labels=[[0, 1, 2, 2, 3], [0, 1, 2, 2, 3]],
           names=[u'id', u'tstamp'])
[right]: 3, MultiIndex(levels=[[2, 3, 4, 5], [2016-03-23 14:00:00, 2016-03-23 15:00:00, 2016-03-23 16:00:00, 2016-03-23 17:00:00]],
           labels=[[0, 1, 3], [0, 1, 3]],
           names=[u'id', u'tstamp'])
```

https://travis-ci.org/MacPython/pandas-wheels/jobs/142424407

### PR DESCRIPTION
**Pull request by jreback**
closes #13566

### CODE REVIEW

**Comment by jreback** [comment]
this was a PITA 

cc @jorisvandenbossche 
cc @sinhrks 
cc @gfyoung

**Comment by gfyoung** [comment]
@jreback : any reason why we don't test 32-bit for PR's?  Our parent library `numpy` has at least one machine for 32-bit testing as you can see <a href="https://github.com/numpy/numpy/blob/master/.travis.yml#L40">here</a>.

**Comment by jreback** [comment]
oh didn't know you could set it up that way 

sure u want to add another build (under the bottom section - go for it)

**Comment by gfyoung** [comment]
There's a little bit more that happens behind the scenes, but I just wanted to throw that out there.  I can certainly take a look.

**Comment by jorisvandenbossche** [comment]
What is the reason `searchsorted` has to return platform int?

**Comment by gfyoung** [comment]
Alas, adding a 32-bit config is way more complicated than I imagined (I thought perhaps Ctrl+P from `numpy` might suffice, but alas, that doesn't even work).  So tabling that idea for now.

**Comment by jreback** [comment]
32-bit linux
```
In [12]: arr = np.array([0,1,2])

In [13]: arr.dtype
Out[13]: dtype('int32')

In [14]: arr.searchsorted(arr).dtype
Out[14]: dtype('int32')
```

64-bit windows
```
In [15]: arr = np.array([0,1,2])

In [16]: arr.dtype
Out[16]: dtype('int32')

In [17]: arr.searchsorted(arr)
Out[17]: array([0, 1, 2], dtype=int64)
``


64-bit all around / OSX
```
In [1]: arr = np.array([0,1,2])

In [2]: arr.searchsorted(arr)
Out[2]: array([0, 1, 2])

In [3]: arr.searchsorted(arr).dtype
Out[3]: dtype('int64')

In [4]: arr.dtype
Out[4]: dtype('int64')
```

So the issue is that on 64-bit we have integers defaults to 64-bit upon construction, and indexing routines (e.g. ``.searchsorted`` and ``.take`` are also 64-bit)
On 32-bit these are both 32-bit
on windows indexing are 64-bit but 32-bit for integer defaults (this is because windows use ``long long`` for pointers, but ``long`` for integer)

Note that this is NOT an API change, rather a regression to 0.18.1 (so putting it back where it was). Will update soon.

I think somewhere we are doing a forced conversion (in ``.searchsorted``) but should not be.

**Pull request closed without merging**
