### PR TITLE
REF: isinstance(x, int) -> is_integer(x)

### PR DESCRIPTION
**Pull request by attack68**

### CODE REVIEW

**Review by mroeschke — APPROVED** [review]
Nice LGTM

**Comment by jbrockmendel** [comment]
Is there user-facing in a way that could represent a bugfix?

**Comment by attack68** [comment]
> Is there user-facing in a way that could represent a bugfix?

I can't remember why this came up, but there was a reason. It might have been when formatting new Int64 with thousands separator, but the Int64 didn't get detected by `int` so didn't show the separator. This fix was recommended to me in another PR recently.

**Comment by jreback** [comment]
you could actually test this (e.g. pass in np.int64 intead of ints for some args), but nbd.

**Comment by simonjayhawkins** [comment]
@meeseeksdev backport 1.4.x

**Pull request merged**
