### PR TITLE
DOC: Handle whitespace in pathnames

### PR DESCRIPTION
**Pull request by thiviyanT**
Fixed make.py - Now should be able to run make.py in paths with whitespaces (#20862)

### CODE REVIEW

**Comment by jreback** [comment]
@datapythonista @jorisvandenbossche 

how does this look?

**Comment by datapythonista** [comment]
I was taking a look at it yesterday, as I'm not sure in windows the single quotes will handle backslashes well. But unrelated to the ticket I'm getting a segmentation fault when running sphinx-built. Will comment on the ticket with feedback when I manage to test it.

**Comment by jorisvandenbossche** [comment]
Can't test on Windows at the moment, but for linux this patch works nicely and fixes the problem for me.

**Comment by datapythonista** [comment]
@ThiviyanThanapalasingam seems like in Windows the paths need to be escaped with double quotes (the backlash is interpreted as an escape character like in `\n`).

Besides that, I personally find it's not very readable to use backslashes to escape the quotes. Meaning that instead of `'\'{}\''` I think it'd be more clear to use `"'{}'"`. Or now that we need to change to double quotes, the opposite: `'"{}"'`.

Also, I see that there are several paths that are built like `source/*.rst` (instead of `os.path.join('source', '*.rst')`. I couldn't try, but I guess sphinx is failing to exclude these files like in unix systems. Do we want to open an issue for making the script work in Windows @jreback?

**Comment by datapythonista** [comment]
@ThiviyanThanapalasingam do you have time to update the PR based on the feedback I provided?

**Comment by ThiviyanThanapalasingam** [comment]
Yes, I can do that. @datapythonista Have you opened another issue for making the script work in Windows?

**Comment by datapythonista** [comment]
No, I think it should be just the one you opened.

**Comment by jreback** [comment]
@datapythonista ?

**Comment by datapythonista** [comment]
@ThiviyanThanapalasingam can you update the PR based on the previous feedback?

**Comment by datapythonista** [comment]
Made the updates to this PR. But seems like there is a new unrelated problem when the path contains whitespaces: #22836

I think that can be addressed in a separate PR. I would merge this on green, but happy to close this and take care of both problems in a new PR.

**Comment by jorisvandenbossche** [comment]
Let's do that in a separate PR

@ThiviyanThanapalasingam thanks for the original PR!

**Pull request merged**
