### PR TITLE
BUG: Fix to_datetime not respecting dayfirst 

### LINKED ISSUE #58859: BUG: to_datetime behaves differently depending of the format of the string provided
### Pandas version checks

- [ ] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
Python 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.to_datetime("2016-03-11", dayfirst=True)
Timestamp('2016-11-03 00:00:00')
>>> pd.to_datetime("20160311", dayfirst=True)
Timestamp('2016-03-11 00:00:00')
>>>
```

### Issue Description

Dates of the format "YYYYDDMM" are not converted correctly by to_datetime() when dayfirst=True. to_datetime() still reads the date characters as the months

### Expected Behavior

Python 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.to_datetime("2016-03-11", dayfirst=True)
Timestamp('2016-11-03 00:00:00')
>>> pd.to_datetime("20160311", dayfirst=True)
Timestamp('2016-11-03 00:00:00')

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.11.7.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 3.10.0-1160.114.2.el7.x86_64
Version             : #1 SMP Sun Mar 3 08:18:39 EST 2024
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.3
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.3
pip                 : 23.3.2
Cython              : 3.0.7
pytest              : 7.4.4
hypothesis          : 6.94.0
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : 3.1.9
lxml.etree          : 5.1.0
html5lib            : 1.1
pymysql             : None
psycopg2            : None
jinja2              : 3.1.3
IPython             : 8.20.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
dataframe-api-compat: None
fastparquet         : 2023.10.1
fsspec              : 2023.12.2
gcsfs               : None
matplotlib          : 3.8.2
numba               : 0.58.1
numexpr             : 2.8.8
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 16.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.4
sqlalchemy          : 2.0.25
tables              : 3.9.2
tabulate            : 0.9.0
xarray              : 2023.7.0
xlrd                : 2.0.1
zstandard           : 0.19.0
tzdata              : 2023.4
qtpy                : 2.4.1
pyqt5               : None

</details>

### PR DESCRIPTION
**Pull request by Aloqeely**
- [x] closes #58859
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
thanks for your PR!

Are you sure that dateutil doesn't take `dayfirst` into account? it's an argument that's passed in, and it seems to still be respected in cases when the dateutil path is used:

```python
In [11]: pd.to_datetime(['foo', '10.03.2000'], dayfirst=True, errors='coerce')
<ipython-input-11-69ca28852760>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(['foo', '10.03.2000'], dayfirst=True, errors='coerce')
Out[11]: DatetimeIndex(['NaT', '2000-03-10'], dtype='datetime64[s]', freq=None)

In [12]: pd.to_datetime(['foo', '10.03.2000'], errors='coerce')
<ipython-input-12-8697ff36715a>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(['foo', '10.03.2000'], errors='coerce')
Out[12]: DatetimeIndex(['NaT', '2000-10-03'], dtype='datetime64[s]', freq=None)
```

but it's been a while since I looked at this code too closely, so I might be missing something

**Comment by Aloqeely** [comment]
The formatting makes it seem like I made a lot of changes but essentially I just added an `if not dayfirst` check before using `string_to_dts` per your suggestion.

**Review by MarcoGorelli — COMMENTED** [review]
thanks @Aloqeely , this looks better!

the test you've added hits the `conversion.pyx` code you've modified

however, I don't think it hits the line you've modified in `parsing.pyx`? in which case, could you add such a test please?

**Comment by Aloqeely** [comment]
The test fails if I revert the changes in `parsing.pyx`, I believe this is the line of code that hits the changes:
https://github.com/pandas-dev/pandas/blob/4c275301f620105cb2a9b944a815f3e85e1f2bd5/pandas/tests/tools/test_to_datetime.py#L3044-L3046

**Review by MarcoGorelli — APPROVED** [review]
ah nice, so the test already covers both paths

looks good, just a merge conflict to resolve

**Review by mroeschke — APPROVED** [review]

**Comment by mroeschke** [comment]
Thanks @Aloqeely

**Pull request merged**
