### PR TITLE
DOC: ddof in cov when nans present

### LINKED ISSUE #47042: DOC: `ddof` in `cov` when `nan`s present
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.cov.html

### Documentation problem

The `ddof` argument is applicable only when `nan`s are not present in the dataframe.
It can be quite common to calculate a covariance matrix from financial data where the last row might be `nan` since the difference is taken between values. One might expect that since the result is given the `ddof` is adhered to. But it is not. I think this should be explicitly stated in the argument documentation, rather than hidden in the notes.

### Suggested fix for documentation

.

### PR DESCRIPTION
**Pull request by ma-ma-hima**
- [x] closes #47042
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

This PR adds a document about the "``nan``s must not be present in the dataframe" restriction on ddof in pandas.DataFrame.cov.

### CODE REVIEW

**Comment by whooolemilk** [comment]
This is my first time OSS contributing.
`Code Checks / pre-commit (pull_request)` is failing, what should I fix?
Please tell me!!

**Comment by topper-123** [comment]
Hey @whooolemilk Thanks for picking this up!

In general, how to work with errors (there will be many) is to look into the test logs and find the relevant log line. In this case try to look into the `Doc Build and Upload / Doc Build and Upload (pull_request)` one and you'll see an error message `rst inline code next to normal text`,i..e, its the "`nan`s" part that is the problem.

**Comment by topper-123** [comment]
To avoid the rst check issue you could just reword the sentence, for example `This argument is applicable only when no ``nan`` is in the dataframe.`

**Comment by topper-123** [comment]
Looks good. Thanks @whooolemilk.

**Comment by whooolemilk** [comment]
@topper-123 
Thanks for letting me know

**Pull request merged**
