### PR TITLE
REF: array_to_datetime catch overflows in one place

### PR DESCRIPTION
**Pull request by jbrockmendel**
The diff is big, but all this is doing is changing:

```
if A:
    try:
        foo(...)
    except OutOfBoundsDatetime:
        handle(...)
elif B:
    try:
        bar(...)
    except OutOfBoundsDatetime:
        handle(...)
...
```

to:

```
try:
    if A:
        foo(...)
    elif B:
        bar(...)
    ...
except OutOfBoundsDatetime:
    handle(...)
...
```

Orthogonal to #24032, will need rebasing following #24031.  All three of these should go before #24006.

### CODE REVIEW

**Comment by jreback** [comment]
so what i think you should *really* do, is instead of nesting this further, move all that you have inside the try/except (in order to catch OutOfBounds), and put it in another function, then have ``array_to_datetime`` call it. will be much easier on the eyes i think. (see line 712)

maybe something like
```
try:
    return array_to_datetime(...)
except OutOfBounds:
    return array_to_object(...)
else:
    raise TypeError
```

**Comment by jbrockmendel** [comment]
> and put it in another function

Works for me.  This hypothetical function would look _a lot_ like `convert_to_tsobject`.  Hopefully we'll be able to iron out the handful of differences between these and de-duplicate a bunch of code.

```
else:
    raise TypeError
```

I'm not wild about using TypeError for flow-control here because it obscures cases when a TypeError is raised naturally.  #24032 is an orthogonal refactor that I think improves the situation.  Following that I'll take a look at implementing your suggestion here.

**Comment by jreback** [comment]
> Works for me. This hypothetical function would look a lot like convert_to_tsobject. Hopefully we'll be able to iron out the handful of differences between these and de-duplicate a bunch of code.

yep

> I'm not wild about using TypeError for flow-control here because it obscures cases when a TypeError is raised naturally. #24032 is an orthogonal refactor that I think improves the situation. Following that I'll take a look at implementing your suggestion here

oh, that's what the original does, didn't actually mean to change anything.

**Comment by jbrockmendel** [comment]
> oh, that's what the original does, didn't actually mean to change anything.

Yah, its 24032 that does change the behavior.  I'm pretty sure the suggestion you made here will need tweaking after 24032, and I think that's a more important change, so should go first.

**Comment by jreback** [comment]
ok, #24032 merged. rebase this and will look.

**Comment by jreback** [comment]
right it’s nice and clean but might involve some duplicated code

**Comment by jreback** [comment]
ok this is a net improvment. that function is a bear. but if you have time / maybe open an issue to refactor even more.

**Pull request merged**
