### PR TITLE
removed not necessary bn switch decorator on nansum

### PR DESCRIPTION
**Pull request by asdf8601**
Removed not necessary bottleneck_switch decorator on nansum function like nanprod.

### CODE REVIEW

**Comment by jreback** [comment]
should also be on ``nansum``. how did you come to change this? e.g. what broke?

**Comment by mmngreco** [comment]
oh, now I don't see it so clearly and I'm probably wrong. Nothing has been broken, I was checking the code and I noticed that `bottleneck_switch` seems to do nothing when the function is `nansum` or `nanprod` according to `_bn_ok_dtype`, I thought it would be an unnecessary call.

**Comment by jreback** [comment]
@mmngreco no it IS unecessary since 0.22 (as we compute sum/prod inside pandas only). was just wondering how you detected it.

happy to have you remove the one on nansum as well. I don't think there is a test for this that would break, but if you have something would be great.

**Comment by mmngreco** [comment]
I have not found any `bottleneck_switch`, I understand that this would be necessary for this case. I haven't written anything yet. I will try in the next few days as I am not sure how to do it.

**Review by TomAugspurger — APPROVED** [review]
I also don't think you'll find a test where this matters.

Merging later today.

**Comment by TomAugspurger** [comment]
Thanks @mmngreco

**Pull request merged**
