### PR TITLE
BF: boost min cython to 0.23

### LINKED ISSUE #14508: BLD: require more recent cython
see comments [here](https://github.com/pandas-dev/pandas/pull/14496#issuecomment-256497307)

we currently require >= 0.19.1. So probably should move that up.

Not super pressing though.

### LINKED ISSUE #14699: test_quotechar_unicode on Debian jessie (stable)
Seems to happen only with python3 (passes on python2)
```
======================================================================
ERROR: test_quotechar_unicode (pandas.io.tests.parser.test_parsers.TestCParserHighMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/tests/parser/quoting.py", line 152, in test_quotechar_unicode
    result = self.read_csv(StringIO(data), quotechar=u('\u0394'))
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/tests/parser/test_parsers.py", line 59, in read_csv
    return read_csv(*args, **kwds)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 388, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 729, in __init__
    self._make_engine(self.engine)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 922, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1389, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 411, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4130)
  File "pandas/parser.pyx", line 588, in pandas.parser.TextReader._set_quoting (pandas/parser.c:6307)
OverflowError: value too large to convert to char

======================================================================
ERROR: test_quotechar_unicode (pandas.io.tests.parser.test_parsers.TestCParserLowMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/tests/parser/quoting.py", line 152, in test_quotechar_unicode
    result = self.read_csv(StringIO(data), quotechar=u('\u0394'))
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/tests/parser/test_parsers.py", line 77, in read_csv
    return read_csv(*args, **kwds)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 388, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 729, in __init__
    self._make_engine(self.engine)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 922, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/build/pandas-0.19.1/debian/tmp/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1389, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 411, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4130)
  File "pandas/parser.pyx", line 588, in pandas.parser.TextReader._set_quoting (pandas/parser.c:6307)
OverflowError: value too large to convert to char

```

FWIW also happens on ubuntu 15.04 .  Passes on later releases.
Advice on where/how to dig would be appreciated

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-rc2+
machine: x86_64
processor: 
byteorder: little
LC_ALL: C
LANG: C
LOCALE: None.None

pandas: 0.19.1
nose: 1.3.4
pip: None
setuptools: 20.10.1
Cython: 0.21.1
numpy: 1.8.2
scipy: 0.14.0
statsmodels: None
xarray: None
IPython: None
sphinx: 1.2.3
patsy: None
dateutil: 2.2
pytz: 2012c
blosc: None
bottleneck: None
tables: 3.2.1
numexpr: 2.4.3
matplotlib: 1.4.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.3.2
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.7.3
boto: None
pandas_datareader: None
</details>

### PR DESCRIPTION
**Pull request by yarikoptic**
closes #14699
closes #14508

### CODE REVIEW

**Comment by jreback** [comment]
prob need to change a few travis setups in ci
for this to work

**Comment by yarikoptic** [comment]
what is btw really the lowest version of cython which works in your setups and passes the tests? 0.23 here is somewhat arbitrary one higher than 0.21.1 where 14699 manifested

**Comment by jreback** [comment]
```
ci/install_travis.sh:    pip install cython==0.19.1
ci/requirements-2.7.build:cython=0.19.1
ci/requirements-2.7_COMPAT.build:cython=0.19.1
ci/requirements-2.7_LOCALE.build:cython=0.19.1
```

**Comment by jreback** [comment]
@yarikoptic I think 0.23 is fine. if you can add a note on 0.20.0 whatsnew. also need to update ``install.rst`` I think (as well as change those files I listed above).

**Comment by yarikoptic** [comment]
interesting -- now 2nd env in travis fails due to failing to find pandas/index.c   any immediate clue why?

**Comment by jorisvandenbossche** [comment]
@yarikoptic that build is still installing cython 0.19.1 (see the requirements-2.7_LOCALE.build file), so it acts like cython is not installed (I only thought we had a better error message for such cases)

**Comment by jorisvandenbossche** [comment]
LGTM

@jreback

**Comment by jreback** [comment]
seem some files have no changes?

can you add a note in the whatsnew 0.20.0 (in addition to the one you have), about the development requireing a higher version.

can you see if anything needs to be changed in contributing.rst

otherwise lgtm.

**Comment by yarikoptic** [comment]
@jreback 

- "no changes" -- read between the lines ;)  git would not have a change registered if there were no changes -- while at it fixed some permissions
- whatsnew entry was added a while back... now had to resolve merge conflict already.  would appreciate a merge ;)

**Comment by jreback** [comment]
thank you sir!

**Pull request closed without merging**
