### PR TITLE
DOC: change doc build to python 3.6

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
see https://github.com/pandas-dev/pandas/pull/16432

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
With these changes, the doctests now pass. 
But, there seems to be a problem with the clipboard ones by going from PyQt4 to 5 (only 4 is used for clipboard I think). So best to install another package for clipboard? @jreback of all the different possibilities of packages to install for clipboard functionality, a preference to install on travis for the docs?

**Comment by jorisvandenbossche** [comment]
Added `xsel` in the latest commit

**Comment by jreback** [comment]
@jorisvandenbossche lgtm.

**Review by TomAugspurger — APPROVED** [review]
The failure [here](https://travis-ci.org/pandas-dev/pandas/jobs/238491441#L1365) was fixed by https://github.com/pandas-dev/pandas/pull/16575

Merge if / when you're ready @jorisvandenbossche

**Comment by TomAugspurger** [comment]
I should have also brought this up in the other issue, are we OK with expanding our doctests? I think we should, as they make for better examples, and would have caught a couple things last time around. But they do feel a bit fragile (stuff like dtypes, ordering can break them).

**Comment by jorisvandenbossche** [comment]
I am OK with that, and it's what I have been working (very slowly) towards (eg adding the imports in the conftest file to be able to run them, and on the docathon I let a few people corrects examples based on running the doctests). 

As long we don't see it as tests like the actual unit tests, but as testing that the example is correct, I think they are very useful.

**Comment by jorisvandenbossche** [comment]
Yes, this is ready

**Comment by jorisvandenbossche** [comment]
> But they do feel a bit fragile (stuff like dtypes, ordering can break them).

We should maybe make an overview somewhere of the different tricks to use to get the tests passing. And we should also check if we could do some of the directives (eg normalize whitespace) globally, so you don't need to add them in the actual example code

**Pull request merged**
