### PR TITLE
REF: standardize astype in EA subclasses

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
Thanks @jbrockmendel, by changing the accepted types for astype we are changing the api for 3rd party EAs. probably needs a release note. (subclassed EA need to accept the same types as the base class) cc @Dr-Irv if any comments

**Comment by Dr-Irv** [comment]
> Thanks @jbrockmendel, by changing the accepted types for astype we are changing the api for 3rd party EAs. probably needs a release note. (subclassed EA need to accept the same types as the base class) cc @Dr-Irv if any comments

IMHO, I think you ought to first accept/merge in #41251 where I created overloads for `astype` in various subclasses to separate out the cases of using a base type versus a numpy dtype, and then merge in this one.

I think there is a separate issue of how we should handle `astype(extension_dtype)` for crossing between extension dtypes and regular types, and vice versa, which I think this PR is trying to address.

**Comment by jbrockmendel** [comment]
ill just revert the type annotation

**Comment by jbrockmendel** [comment]
Mothballing since i cant replicate the failures locally.

**Pull request closed without merging**
