### PR TITLE
TYP: indexes

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

### CODE REVIEW

**Review by jreback — APPROVED** [review]

**Comment by jbrockmendel** [comment]
gentle ping; code checks are starting to touch nearby code

**Comment by jbrockmendel** [comment]
rebased + green (and approved)

**Comment by jreback** [comment]
lgtm can you rebase as merged some future annotations stuff earlier, ping on green

**Comment by jreback** [comment]
> pandas/core/groupby/generic.py:181: error: Cannot override final attribute "_obj_with_exclusions" (previously declared in base class "SelectionMixin")  [misc]
pandas/core/groupby/generic.py:934: error: Cannot override final attribute "_obj_with_exclusions" (previously declared in base class "SelectionMixin")  [misc]

**Comment by jbrockmendel** [comment]
That’s on master, orthogonal. Easy fix, PR coming in a few minutes

**Comment by jbrockmendel** [comment]
rebased + greenish (mypy fixed by #40930, the other is an unrelated ResourceWarning)

**Pull request merged**
