### PR TITLE
BUG: pickle files left behind by tm.round_trip_pickle

### PR DESCRIPTION
**Pull request by jbrockmendel**

### CODE REVIEW

**Review by jschendel — APPROVED** [review]
lgtm, thanks!

**Review by WillAyd — APPROVED** [review]
makes sense. nice find

**Comment by jreback** [comment]
worth backporting

merge on green

**Comment by jbrockmendel** [comment]
green

**Comment by simonjayhawkins** [comment]
Thanks @jbrockmendel Is it worth moving check_for_file_leaks into a higher level conftest?

**Comment by jbrockmendel** [comment]
> Is it worth moving check_for_file_leaks into a higher level conftest?

Different kind of file leak

**Pull request merged**
