### PR TITLE
TST: add message matches to pytest.raises in test_duplicate_labels.py GH30999

### PR DESCRIPTION
**Pull request by theMogget**
Reference https://github.com/pandas-dev/pandas/issues/30999

- [x] tests added / passed
- [x] passes `black pandas`
- [ ]  passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

Hello! This is my first PR here. I followed the steps in the contributing guidelines [here](https://github.com/pandas-dev/pandas/blob/master/doc/source/development/contributing.rst#contributing-your-changes-to-pandas), but I didn't see anything about `git diff upstream/master -u -- "*.py" | flake8 --diff`. 

When I run the command locally, with `origin/master`, it returns no output. I get fatal with `upstream/master`. Is that expected, and if it isn't, could anyone advise on how to resolve the issue please? 

Thank you!

### CODE REVIEW

**Review by arw2019 — COMMENTED** [review]
Thanks @theMogget for the PR! 

Looks good to me. 

Regarding `flake8` you're good - Continuous Integration checks this and it's all green. For future, however, the relevant section of the contributor docs is [here](https://github.com/pandas-dev/pandas/blob/master/doc/source/development/contributing.rst#python-pep8-black)

**Review by simonjayhawkins — APPROVED** [review]
Thanks @theMogget lgtm

**Comment by theMogget** [comment]
Thanks both for the quick reviews. :) 

@arw2019 thanks for the specific link too, it's really helpful! The amount of information is a bit overwhelming sometimes.

**Comment by charlesdong1991** [comment]
thanks @theMogget very nice!

**Pull request merged**
