### PR TITLE
DOC: add examples of database drivers (GH11686)

### LINKED ISSUE #11686: Install.rst is missing references to optional packages
Following references are missing

* rpy2
* psycopg (at least testing needs it)
* pymysql (at least testing needs it)
* matplotlib

perhaps there are more.

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes #11686

### CODE REVIEW

**Comment by TomAugspurger** [comment]
:+1: Only minor thing is that you have "you also need a database specific driver." could be "you *may* also need a database specific driver." depending on the database your using.

**Comment by jorisvandenbossche** [comment]
True, but I think that is only the case for sqlite? (that it is not necessary) Although you actually need one, only it is included in the standard library. But will include that.

**Comment by TomAugspurger** [comment]
A very, very minor thing :smile:

**Comment by jorisvandenbossche** [comment]
Updated!

**Comment by jreback** [comment]
lgtm

**Pull request merged**
