### PR TITLE
Backport PR #45195 on branch 1.4.x (BLD: updated pydata-sphinx-theme to master in environment.yml)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #45195: BLD: updated pydata-sphinx-theme to master in environment.yml

### CODE REVIEW

**Comment by jreback** [comment]
hmm don't we need to update github actions here to have 1.4 backports run?

cc @lithomas1

**Comment by simonjayhawkins** [comment]
> hmm don't we need to update github actions here to have 1.4 backports run?

will do after #45201 is merged.

**Comment by jreback** [comment]
i *think* may need to rebase this to trigger all the CI

**Comment by jreback** [comment]
oh nvm
it worked

**Pull request merged**
