### PR TITLE
BUG: Series.fillna() raises if given a numerically convertible string

### PR DESCRIPTION
**Pull request by mortada**
First reported here but it's been dormant for a long time: https://github.com/pydata/pandas/pull/9043 

I think it'd be good to patch this bug. @jreback please let me know which release this should go to and I can add a release note. Thanks.

### CODE REVIEW

**Comment by jreback** [comment]
this looks ok for 0.16.1.

**Comment by mortada** [comment]
sounds good, I added a release note

**Comment by jreback** [comment]
ok, ping on green.

**Comment by mortada** [comment]
@jreback green now

**Comment by jreback** [comment]
thanks!

**Pull request merged**
