### PR TITLE
BUG: to_json segfaults when exception occurs in UTF8 encoding of string

### LINKED ISSUE #50307: BUG: strange string causes segmentation fault on df.to_json
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
string = chr(56000)
print(repr(string)) # This is a valid Python string, but can't be printed normally
df = pd.DataFrame({'A': [string]})
df.to_json()
```

### Issue Description

When I run this from the command line, it causes a segmentation fault:
```
zsh: segmentation fault  python main.py
```

### Expected Behavior

It should not segmentation fault. Perhaps it throws some error saying it can't `to_json` it, but it probably shouldn't crash the whole Python runtime (e.g. you can't even recover with a try catch).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.9.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.2
numpy            : 1.23.5
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 56.0.0
pip              : 21.2.4
Cython           : None
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None
</details>

### PR DESCRIPTION
**Pull request by lithomas1**
- [ ] closes #50307 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Review by WillAyd — APPROVED** [review]
Very nice

**Comment by gfyoung** [comment]
LGTM pending CI

**Comment by gfyoung** [comment]
LGTM pending CI

**Comment by WillAyd** [comment]
Awesome thanks @lithomas1 would take an audit of any of these to support https://github.com/pandas-dev/pandas/issues/49756

**Comment by phofl** [comment]
it looks like this causes the 32bit built to time out on main. Any ideas why this is happening?

**Comment by lithomas1** [comment]
Not sure, do you know the exact test that is timing out?

**Comment by MarcoGorelli** [comment]
Pretty sure it's `pandas/tests/io/json/test_ujson.py`

**Comment by lithomas1** [comment]
I can confirm that it hangs on the test added in this PR. I'm going to debug more, but feel free to revert this PR in the meantime.

**Comment by WillAyd** [comment]
Are there any warnings being generated in the logs? I would also maybe check what happens if we get rid of some of the casts - generally we do this too much in the C code

**Comment by lithomas1** [comment]
I've pulled the 32 bit docker container onto my machine, so hopefully I'll be able to debug with gdb soon.

**Comment by WillAyd** [comment]
My other guess  is that `enc->errorMsg = "Encoding failed.";` is problematic. I think the rhs of this is a `char[]` with auto storage, and it is possible that the memory for it has been reused after the function exists and by the time ultrajson actually evaluates it. This could cause undefined behavior

You could try heap allocating that string and see if it allows tests to pass (though it will cause a memory leak)

**Comment by WillAyd** [comment]
Looks like I was wrong about the duration of the string literal

https://stackoverflow.com/questions/9970295/life-time-of-a-string-literal-in-c

**Comment by lithomas1** [comment]
Looks like its getting stuck in Buffer_ReAlloc
```
#0  Buffer_Realloc (enc=0xffa2ac0c, cbNeeded=3079809510)
    at pandas/_libs/src/ujson/lib/ultrajsonenc.c:373
#1  0xf3ede5f8 in encode (obj=0xf1ace110, enc=0xffa2ac0c, name=0x0, cbName=0)
    at pandas/_libs/src/ujson/lib/ultrajsonenc.c:1083
#2  0xf3ede240 in encode (obj=0xf1a55828, enc=0xffa2ac0c, name=0x0, cbName=0)
    at pandas/_libs/src/ujson/lib/ultrajsonenc.c:993
#3  0xf3edea7d in JSON_EncodeObject (obj=0xf1a55828, enc=0xffa2ac0c, 
    _buffer=0xffa2acc4 "[", _cbBuffer=65536)
```
Maybe I need to set the length of the string to zero.

**Comment by lithomas1** [comment]
Looks like that did it

**Pull request merged**
