### PR TITLE
In gbq.to_gbq allow the DataFrame column order to differ from schema

### LINKED ISSUE #11359: pandas.io.gbq verify_schema seems to be too strict.
[This line](https://github.com/pydata/pandas/blob/b2a547e8a9dd6ab3332f18a6f87ecb31181d7d30/pandas/io/gbq.py#L330) seems for me to be too strict for repeated insertion, because apparently GBQ is not consistent in the order of fields in the schema (or my application screws the order of fields up, anyway, I would say the verification is too strict).

So for example:
```python
dict1 = {'fields': [{'name': 'coordinates_0', 'type': 'FLOAT'}, {'name': 'created_at', 'type': 'STRING'}]}
dict2 = {'fields': [{'name': 'created_at', 'type': 'STRING'}, {'name': 'coordinates_0', 'type': 'FLOAT'}]}
dict1 == dict2  # gives False
```
would make verification fail, though insertion would work, as the insert as JSON makes the order of fields irrelevant.

Solved that for myself for the moment with:
```python
    def verify_schema(self, dataset_id, table_id, schema):
        from apiclient.errors import HttpError

        try:
            bq_schema = (self.service.tables().get(
                projectId=self.project_id,
                datasetId=dataset_id,
                tableId=table_id
                ).execute()['schema'])
            return set(
                       [json.dumps(x) for x in bq_schema['fields']]  # dump necessary to make dicts hashable
                      ) == set(
                               [json.dumps(x) for x in schema['fields']]
            )  # this still fails if key order is different. But GBQ seems to keep key order.

        except HttpError as ex:
            self.process_http_error(ex)

### PR DESCRIPTION
**Pull request by parthea**
- [x] closes #11359
- [x] tests added / passed. [Link to Travis-CI build with my gbq credentials](https://travis-ci.org/parthea/pandas/builds/159134242)
- [x] passes `git diff upstream/master | flake8 --diff`
- [x] whatsnew entry

### CODE REVIEW

**Comment by jreback** [comment]
lgtm. ping on green.

**Comment by parthea** [comment]
[All gbq tests passed with my credentials](https://travis-ci.org/parthea/pandas/builds/159134242).

Only 1 test failed on pydata/pandas Travis-ci . At first glance, the failure appears to be unrelated to my changes.

```
======================================================================
FAIL: test_sum (pandas.tests.frame.test_analytics.TestDataFrameAnalytics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pydata/pandas/pandas/tests/frame/test_analytics.py", line 420, in test_sum
    check_less_precise=True)
  File "/home/travis/build/pydata/pandas/pandas/tests/frame/test_analytics.py", line 897, in _check_stat_op
    check_less_precise=check_less_precise)
  File "/home/travis/build/pydata/pandas/pandas/util/testing.py", line 1181, in assert_series_equal
    obj='{0}'.format(obj))
  File "testing.pyx", line 59, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3262)
  File "testing.pyx", line 173, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2590)
  File "/home/travis/build/pydata/pandas/pandas/util/testing.py", line 1018, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different
Series values are different (25.0 %)
[left]:  [0.00050354, 2.75732, -2.34081, 12.0699]
[right]: [0.000502824783325, 2.75732088089, -2.34080505371, 12.06990242]
----------------------------------------------------------------------
Ran 11145 tests in 664.680s
FAILED (SKIP=109, failures=1)
```

**Comment by parthea** [comment]
@jreback At your earliest convenience, please restart the Travis build for this PR. I think it is failing due to a once-off failure:

``
======================================================================
FAIL: test_sum (pandas.tests.frame.test_analytics.TestDataFrameAnalytics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pydata/pandas/pandas/tests/frame/test_analytics.py", line 420, in test_sum
    check_less_precise=True)
  File "/home/travis/build/pydata/pandas/pandas/tests/frame/test_analytics.py", line 897, in _check_stat_op
    check_less_precise=check_less_precise)
  File "/home/travis/build/pydata/pandas/pandas/util/testing.py", line 1181, in assert_series_equal
    obj='{0}'.format(obj))
  File "testing.pyx", line 59, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3262)
  File "testing.pyx", line 173, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2590)
  File "/home/travis/build/pydata/pandas/pandas/util/testing.py", line 1018, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different
Series values are different (25.0 %)
[left]:  [0.00050354, 2.75732, -2.34081, 12.0699]
[right]: [0.000502824783325, 2.75732088089, -2.34080505371, 12.06990242]
----------------------------------------------------------------------
Ran 11145 tests in 664.680s
FAILED (SKIP=109, failures=1)
```

**Comment by parthea** [comment]
@jreback Travis is green

**Comment by jreback** [comment]
thanks!

**Pull request closed without merging**
