### PR TITLE
BUG: overriden methods of subclasses of Styler are not called during …

### PR DESCRIPTION
**Pull request by YifanChao**
…rendering #52728

BUG: overriden methods of subclasses of Styler are not called during rendering #52728

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by phofl** [comment]
Please don't open a PR for every change you have to do on this branch. You can simply push to this branch and the ci will rerun

**Comment by attack68** [comment]
The underlying issue was labelled as "good first issue" and had already been taken and assigned to @nicklausroach. It is not respective of the community to ignore that and push your own PR without commenting in the issue.

If he does not submit a PR within a few days it is possible to ask him if he would not mind reassigning it to you.

**Comment by YifanChao** [comment]
Sorry, I'm a new user who's just testing on these. Since it didn't pass the test. I'll stop there.

**Comment by attack68** [comment]
You can use the search function for issues with 'label:"good first issue"', and this will usually yield some good results that are not taken which are worthwhile trying.

**Comment by phofl** [comment]
Closing then

**Pull request closed without merging**
