### PR TITLE
REF/DEPR: Deprecate AbstractMethodError 

### LINKED ISSUE #48909: Mark methods raising AbstractMethodError as abstractmethods?
Many methods raise `AbstractMethodError` instead of being an `abstractmethod`. Based on #20363 and #19268 it seems that there might be a performance issue with inheriting from `abc.ABC`:

> This class does not inherit from 'abc.ABCMeta' for performance reasons.

I didn't find a reference of why inheriting from `abc.ABC` is slow. Is that a python 2 thing? Would it make sense to use `abc.ABC+abstractmethod` instead of raising `AbstractMethodError`?

### PR DESCRIPTION
**Pull request by twoertwein**
Squashed+rebased version of #48913

closes #48909

### CODE REVIEW

**Comment by twoertwein** [comment]
ASV is failing on github - how do I know which part(s) significantly slowed down? There is no summary and there seems to be no keyword to grep for

**Comment by mroeschke** [comment]
> ASV is failing on github - how do I know which part(s) significantly slowed down? There is no summary and there seems to be no keyword to grep for

The CI just runs the ASVs to see that they have to work, you'll have to run `asv continuous` to see the comparison.

You can search for `failed` to see the failed benchmarks

**Comment by rhshadrach** [comment]
Running ASV with `--show-stderr` will help identify issues. Unfortunately it also outputs anytime we raise `NotImplementedError` to indicate a combination of the parameters should not be run. Still, I'm thinking we should add this flag to the CI.

**Comment by rhshadrach** [comment]
Running ASV with `--show-stderr` will help identify issues. Unfortunately it also outputs anytime we raise `NotImplementedError` to indicate a combination of the parameters should not be run. Still, I'm thinking we should add this flag to the CI.

**Comment by twoertwein** [comment]
I tried to locally run ASV and set the python environment up as documented. When running ASV I get errors that there is no module build:

```sh
python3 -m venv ~/virtualenvs/pandas-dev
. ~/virtualenvs/pandas-dev/bin/activate
python -m pip install -r requirements-dev.txt

cd asv_bench
# change 3.10 to 3.11 in asv.conf.json
 asv continuous -f 1.1 -E virtualenv upstream/main abstract2
```
```
Couldn't load asv.plugins.mamba because
No module named 'mamba'
· Creating environments
· Discovering benchmarks
·· Uninstalling from virtualenv-py3.11-Cython0.29.33-jinja2-matplotlib-meson-meson-python-numba-numexpr-odfpy-openpyxl-pyarrow-python-build-scipy-sqlalchemy-tables-xlrd-xlsxwriter
·· Building a9cffe36 <abstract2> for virtualenv-py3.11-Cython0.29.33-jinja2-matplotlib-meson-meson-python-numba-numexpr-odfpy-openpyxl-pyarrow-python-build-scipy-sqlalchemy-tables-
xlrd-xlsxwriter
·· Error running /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/bin/python -m build -Cbuilddir=builddir --wheel --outdir /var/home/twoertwein/git/pa
ndas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/asv-build-cache/a9cffe36a4fd08ef4ff7bc6c1caf34831f459090 /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053
815874d/project (exit status 1)
   STDOUT -------->
   
   STDERR -------->
   /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/bin/python: No module named build

·· Failed: trying different commit/environment
·· Uninstalling from virtualenv-py3.11-Cython0.29.33-jinja2-matplotlib-meson-meson-python-numba-numexpr-odfpy-openpyxl-pyarrow-python-build-scipy-sqlalchemy-tables-xlrd-xlsxwriter
·· Building 766e2fc7 <main> for virtualenv-py3.11-Cython0.29.33-jinja2-matplotlib-meson-meson-python-numba-numexpr-odfpy-openpyxl-pyarrow-python-build-scipy-sqlalchemy-tables-xlrd-
xlsxwriter
·· Error running /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/bin/python -m build -Cbuilddir=builddir --wheel --outdir /var/home/twoertwein/git/pa
ndas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/asv-build-cache/766e2fc7ceb99f7bb582f96ae8f3c3edc8b5b457 /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053
815874d/project (exit status 1)
   STDOUT -------->
   
   STDERR -------->
   /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/bin/python: No module named build

·· Failed: trying different commit/environment
·· Uninstalling from virtualenv-py3.11-Cython0.29.33-jinja2-matplotlib-meson-meson-python-numba-numexpr-odfpy-openpyxl-pyarrow-python-build-scipy-sqlalchemy-tables-xlrd-xlsxwriter
·· Building ac8d34dd <abstract2~1> for virtualenv-py3.11-Cython0.29.33-jinja2-matplotlib-meson-meson-python-numba-numexpr-odfpy-openpyxl-pyarrow-python-build-scipy-sqlalchemy-table
s-xlrd-xlsxwriter
·· Error running /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/bin/python -m build -Cbuilddir=builddir --wheel --outdir /var/home/twoertwein/git/pa
ndas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/asv-build-cache/ac8d34dd9a3a05bf0c5108e808d3ab0a4e80a93b /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053
815874d/project (exit status 1)
   STDOUT -------->

   STDERR -------->
   /var/home/twoertwein/git/pandas/asv_bench/env/5d81e97ed2503fcaf484d1053815874d/bin/python: No module named build

·· Failed to build the project and import the benchmark suite.
```

**Comment by rhshadrach** [comment]
I was able to pull this branch and run as-is. Maybe delete the ASV cache and see if that resolves it?

**Comment by twoertwein** [comment]
> I was able to pull this branch and run as-is. Maybe delete the ASV cache and see if that resolves it?

Thank you, I will try that (but I think it looked more like an issue with the conda-less environment).

> Also - this is the actual removal, not the deprecation, yea? Is this just to see perf impact to decide whether we want to deprecate?

It is for deprecation but already removing the internal usage of `AbstractMethodError`: either replaced by making `astractmethod` (inheriting from ABC can have a perf impact but IMHO this is more explicit that subclasses have to implement a method) or raising `NotImplementedError` (no perf impact)

**Comment by twoertwein** [comment]
I ran `asv continuous -f 1.1 upstream/main abstract2 > log` and it seems that four read_csv tested failed:
```
$ grep failed log
[62.20%] ··· ...CSVDatePyarrowEngine.time_read_csv_index_col             failed
[62.31%] ··· io.csv.ReadCSVIndexCol.time_read_csv_index_col              failed
[87.20%] ··· ...CSVDatePyarrowEngine.time_read_csv_index_col             failed
[87.31%] ··· io.csv.ReadCSVIndexCol.time_read_csv_index_col              failed
```

**Comment by rhshadrach** [comment]
> or do I have to wait until the benchmarks work again to test whether regressions exists?

Benchmarks are run on every commit to main and it is currently green. I don't think these should be failing. I should have some time to try over the weekend.

**Pull request closed without merging**
