### PR TITLE
CI: Checks job aborted if a step fails GH30298

### LINKED ISSUE #30298: CI: Checks job aborted if a step fails
In our job that checks that the code is ok (flake8, mypy...) [1], we want to run all the steps whether any of them fail or not.

This is implemented by using `if: true` in each step. While this should work, it doesn't. A better way to implement this that probably fixes the issue is to use `if: always()` instead. 

What we should do is:
- Replace all instances of `if: true` by `if: always` in the yaml file. 
- Introduce couple of temporary errors. Something PEP-8 invalid (so flake8 reports the error), and change the order of the imports of a file (so isort reports the error). 
- Open a pull request
- See if the job behaves as expected, and wait for a code review
- Once the pull request is approved, revert the errors introduced, so the changes to the yaml file can be merged

1. https://github.com/pandas-dev/pandas/blob/master/.github/workflows/ci.yml

### PR DESCRIPTION
**Pull request by suzutomato**
- [ ] closes #30298
- [ ] tests added / passed
- [ ] passes `black pandas`
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by WillAyd** [comment]
lgtm @datapythonista

**Review by datapythonista — APPROVED** [review]
Thanks @suzutomato, looks good, if you revert the failing changes we can merge this, looks like the `always()` is fixing the problem.

There is a problem for the benchmarks artifact, but it's unrelated to this, I'll create a separate issue.

**Comment by suzutomato** [comment]
The intentional errors have been removed.
As per the last comment from @datapythonista, I won't take action for the problem with the benchmarks artifact at this moment.
Let me know if anything I can do to solve the problem.

**Comment by datapythonista** [comment]
I guess the CI errors are unrelated, can you merge master into your branch to see if the errors get fixed please?

```
git fetch ustream
git merge upsream/master
git push
```

**Comment by alimcmaster1** [comment]
@suzutomato mind finishing this whenever you have a second - definitely looking forward to this feature

**Comment by suzutomato** [comment]
So sorry, I overlooked your last message.
Working on it now.

**Review by datapythonista — APPROVED** [review]
Thanks!

I'm wondering if always means it'll always run, and ideally we want to run only if the previous step run. But let's merge this, as its surely an improvement and see if we can iterate further later.

**Comment by alimcmaster1** [comment]
LGTM - definite improvement

Side note maybe we really want ``if: success() || failure()``. As the changes in this PR will continue to run the workflow even if it has been cancelled as per:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions.

Assume we are currently using the free plan? https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits

@datapythonista

**Comment by datapythonista** [comment]
I'll give a try to `success() || failure()`, I think it's what we actually want

**Pull request merged**
